### ISSUE TITLE
Feature Request: Allowing Vue.config.delimiters/unsafeDelimiters for the CLI

### ISSUE THREAD

**Issue by zargold** [vuejs/vue-cli#100]
Hi I am using django and I'm sure others have other reasons as well for needing to use different configuration for the delimiters. If there was a way to customize the template will automatically generate the markup with `'[['` `']]'` instead of `{{` `}}` I'd really appreciate it.

**Comment by yyx990803** [comment]
Hmm, this is interesting because in 2.0 delimiters will become a component-level option, which means you only need to set it for the root instance that relies on in-DOM templates. Any components processed by `vueify` or `vue-loader` can just keep using default delimiters.

The change is intended to make it easier to use 3rd party components, since changing the delimiters globally means you will not be able to compile them correctly.

So in the long run, delimiters will have a very narrow use scope and this feature would be unnecessary.

**Comment by LinusBorg** [comment]
Well, there's only one line in the templates that actually uses the delimiters ([Line 3](https://github.com/vuejs-templates/webpack/blob/dist/template/src/components/Hello.vue#L3) in `Hello.vue`).

Therefore, I think adding the ability to change delimiters in the template init process would not have a big enough benefit to put in the work to add this feature, in my opinion.

**Comment by chrisvfritz** [comment]
I agree. Making the 99% of people who don't need custom delimiters make a choice about a feature they may not even know exists probably isn't worth saving 2 minutes for possibly less than 1% of people.

**Comment by dragorwyin** [comment]
So, one percent which uses for example Hugo (golang) as template system will be not able to use Vue 2.0? Very, very bad :/ I'm one of that person and my friends also too :/

**Comment by zargold** [comment]
Hi @dragorwyin you could still use vue.js even without this: vue.js itself allows you to do so, but this is for Vue-Cli which allows you to build Vue components with an easy bash command... anyway soon it will be released.

**Comment by dragorwyin** [comment]
Hi @zargold. Thanks for info. For now, i'm using delimiters parameter on every vue component and it works also too. :) Nice, that there is possibility to change it by myself.
For those who don't know how take a short example:

```
let vm = new Vue({
	el: '#example',
	delimiters: ['${', '}'],
	data: {
		message: "hi there :)"
	}
});
```
So, now everything inside div and between ${ } delimeters will works also too :)
I don't know how many people has the same problem, but I will leave that for future :)

**Comment by posva** [comment]
Chris made a very good point and it looks like we're all against it so I'll close this.

**Comment by JohnRobson** [comment]
Ok, but how to use Vue together with frameworks that use jinja? {{ x }}

**Comment by pipinet** [comment]
> Ok, but how to use Vue together with frameworks that use jinja? {{ x }}

{% raw %}{{ xxxx }}{% endraw %}

**Comment by d0p3fish** [comment]
How to use it with twig {{ }} ?
Cant get it working.

**Comment by WhereJuly** [comment]
Why one would ever use delimiters in Vue while it allows for `v-bind` kind of syntax? Use `v-text="myvalue", `v-html="...html here"`? Or render your templates with `{{` `}}` delimiter into HTML before passing them to Vue.
