### ISSUE TITLE
Sample set-up not working when used with router preinstalled

### ISSUE THREAD

**Issue by dtrinh100** [vuejs/vue-cli#1003]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/dtrinh100/vue_cli_router_issue](https://github.com/dtrinh100/vue_cli_router_issue)

### Steps to reproduce
Vue CLI v3.0.0-beta.6
? Please pick a preset: Manually select features
? Check the features needed for your project: TS, Router
? Use class-style component syntax? Yes
? Compile TS with babel? (experimental) No
? Pick a linter / formatter config: Standard
? Pick additional lint features: None
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated file
? Save this as a preset for future projects? No

Run, then open browser to the localhost link.

### What is expected?
Expected to show the homepage

### What is actually happening?
Instead I am greeted with these errors in the console: 

```
[Vue warn]: Unknown custom element: <router-view> - did you register the component correctly? For recursive components, make sure to provide the "name" option. found in ---> <App> at App.vue <Root>
```

and

```
[Vue warn]: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option. found in ---> <App> at App.vue <Root>
```

**Comment by yzimmermann** [comment]
Soooooo what happened?

**Comment by dtrinh100** [comment]
@yzimmermann I actually am not sure. When I opened this ticket, it really didn't work, then I came back to it after about a week or so, then it suddenly worked (no additional), which is really strange. If there was a bug, I can no longer replicate it, since all new projects that I have started with the cli works as expected.

**Comment by OddMorning** [comment]
But it's still actual for me and I don't know what to do. I use `Vue CLI v3.0.0-beta.6` and doesn't matter what features I select during installing, even single `Router` gives me the same broken page:
![24 04 2018 15-34-36 vivaldi](https://user-images.githubusercontent.com/12204657/39187342-b8201f1a-47d5-11e8-92ba-e0c4670537f6.png)

**Comment by OddMorning** [comment]
Well, I feel stupid now. Since `vue serve` doesn't work by saying `Failed to locate entry file in [path]. Valid entry file should be one of: main.js, index.js, App.vue or app.vue.` (not sure if this is a real issue or I do something wrong again) I was starting the dev server via `vue serve src/App.vue` (because some [articles](https://vuejsdevelopers.com/2018/03/26/vue-cli-3) mention `App.vue` and just `.vue` files so often) but the right way to start it is use the `vue serve src/main.js` command.

**Comment by edwinboon** [comment]
I still have this issue even when I use yarn serve. Any idea on how to fix it?

**Comment by SimaAmini** [comment]
In my case in main.js , I imported router file from a wrong place. 

my current main.js file:

`import Vue from "vue";
import App from "./App.vue";
import router from "./router";

Vue.config.productionTip = false;

new Vue({
  router: router,
  render: h => h(App)
}).$mount("#app");
`
