### ISSUE TITLE
Can not find a way to remove the files and directories generated by built-in plugins

### ISSUE THREAD

**Issue by yibuyisheng** [vuejs/vue-cli#1005]
### What problem does this feature solve?
I created a plugin, and wanted to generate our own `src` , `test`, and so on.

But after reading the docs [here](https://github.com/vuejs/vue-cli/blob/dev/docs/plugin-dev.md#generator), I did not find a standard way to remove the files and directories generated by built-in plugins.

### What does the proposed API look like?
I think, the [GenerateAPI](https://github.com/vuejs/vue-cli/tree/dev/packages/@vue/cli/lib/GeneratorAPI.js) should provide some APIs to mutate the `api.generate.files`, and in the `preset.json`, provide a config to decide the execution order of plugins.

**Comment by Akryum** [comment]
You can use nodejs `fs` API.

**Comment by yibuyisheng** [comment]
Since we have read all files ( exclude `node_modules` ) into memory, I think we should handle these files in memory instead of calling the `fs` API directly.

I find out another better way to solve this problem: In `preset.json`, provide a config to determine whether to call the plugin's generator:

```json
{
    "plugins": {
        "@vue/cli-plugin-babel": {
            "version": "^3.0.0-beta.6",
            "disableGenerator": true
        }
    }
}
```

**Comment by yyx990803** [comment]
After c648301 the generator now gets all files when invoked, and can delete files as well.

**Comment by beatgrabe** [comment]
> You can use nodejs `fs` API.

This is a valid method, just ensure your code will be invoked after the generator has completed its stuff:

__generator.js__
```js
module.exports = (api, options, rootOptions) => {
  // modify package.json fields
  api.extendPackage({
    scripts: {
      test: 'vue-cli-service test'
    }
  })

  // copy and render all files in ./template with ejs
  api.render('./template')

  api.onCreateComplete(() => {
    fs.unlinkSync('some_file')
  })
}
```
