### ISSUE TITLE
IDE ESLint integrations do not get full configuration

### ISSUE THREAD

**Issue by yangmingshan** [vuejs/vue-cli#1006]
### Version
3.0.0-beta.6

### Reproduction link
https://github.com/yangmingshan/vue-cli-demo

### Steps to reproduce
If use `import()` ESLint will show error message `[eslint] Parsing error: Unexpected token import` in VS Code, but `npm run lint` is ok, don't know why.

### What is expected?
ESLint can parse experimental syntax

### What is actually happening?
ESLint can't parse experimental syntax

---

`eslint-config-prettier` `eslint-config-standard` `eslint-config-airbnb` both use default parser which can't parse experimental syntax like import() for now, use babel-eslint can solve this problem.

Is this on purpose or a mistake?

If this is a mistake, I'm happy to open a PR 😜

**Comment by LinusBorg** [comment]
Well, since you say `npm run lint` runs fine, it must be a problem with your editor's eslint implementation, which we can't control.

**Comment by yangmingshan** [comment]
Ok, add the reproduction, can you try it. In `src/router.js`. 

In my Sublime Text 3 have same problem.

**Comment by LinusBorg** [comment]
Well, you commented out babel-eslint, of course it won' work? I don't understand what this is supposed to demonstrate, sorry.

**Comment by LinusBorg** [comment]
Oh, are you saying that babel-eslint is not included in the generated `.eslintrc` file?

**Comment by yangmingshan** [comment]
vue-cli 3.0.0-beta.6 not use babel-eslint by default, babel-eslint is added by me. so I commented out.

The question is, is there error message in your editor. And if so,  is it expected. Thanks.

**Comment by yangmingshan** [comment]
Yes, babel-eslint is not included in the generated .eslintrc file. And is it should be included in `@vue/eslint-config-prettier` etc.

**Comment by LinusBorg** [comment]
> vue-cli 3.0.0-beta.6 not use babel-eslint by default

It uses eslint-plugin-vue, which *does* include babel-eslint under the hood, normally - so that should work.

I can't run the reproduction until this evening, roughtly 9-10 hours away.

**Comment by doppelmutzi** [comment]
I had the same problems. ESLint (any option) with Jest lead to problems with imports in Jest files (at least within Visual Studio Code). npm run lint does not complain.

<img width="686" alt="ad9475d7-f6d7-4a57-a10c-77c1d88211fe" src="https://user-images.githubusercontent.com/4130968/38100592-1a21aa60-337e-11e8-9ab9-58d8cb225868.png">

I could fix the problem with 2 additional manual steps.

I generate the project `$ npx -p @vue/cli vue create .`
Then I selected the options (in the following the relevant choices)

- I selected **Linter / Formatter** and **Unit Testing**
- I selected **ESLint with error prevention only**
- I selected **Jest**

Then `npm run lint` works  but I get the error in Visual Studio Code as seen in the screenshot. To fix this I had to do the following:
- add babel-preset-env: `yarn add --dev babel-preset-env`
- replace in **.babelrc** the content with the following `{
    "presets": [
        [
            "env",
            {
                "modules": false
            }
        ]
    ],
    "env": {
        "test": {
            "presets": ["env"]
        }
    }
}`

**Comment by xierenyuan** [comment]
me too！new can only modify the default eslint config to work.

**Comment by dhensche** [comment]
Is there a good reason for the default plugin eslint config to differ from the base config that is used for the `vue-cli-service lint` command? If not, I could submit a PR that just uses the `lint` command base config as the default config for project generation
