### ISSUE TITLE
Modes and Proxy configuration

### ISSUE THREAD

**Issue by tianlizhao** [vuejs/vue-cli#1008]
### 目前mode加载对应的.env文件是下面这样的

```
1. run script
2. loadEnv( load base .env )
3. loadUserOptions( vue.config.js )
4. Starting server
5. setMode( --mode mock load .env.mock)
6. ...
```

所以就会有个问题，在加载`vue.config.js`文件里除了`configureWebpack`, `chainWebpack`这两个地方写方法可以获取mode和对应加载的env就没办法了，做一些 `mock` 和 `development` 区别就变的不容易

### proxy配置
只能在`vue.config.devServer`这里配置是生效的，在`configureWebpack`, `chainWebpack`这两个地方改都没有merge进去

### What does the proposed API look like?
1. mode设置提前

	```
	1. run script
	2. loadEnv( load base .env )
	3. setMode( --mode mock load .env.mock)
	4. loadUserOptions( vue.config.js )
	5. Starting server
	6. ...
	```

2. 是不是可以考虑也可以在configureWebpack, chainWebpack设置所有配置

**Comment by atilkan** [comment]
English please.

**Comment by yyx990803** [comment]
Closing to be tracked in https://github.com/vuejs/vue-cli/issues/959
