### ISSUE TITLE
Add './src' as a default resolve path

### ISSUE THREAD

**Issue by codebryo** [vuejs/vue-cli#1015]
### What problem does this feature solve?
As the app grows, managing the dependencies should be as simple and consistent as possible.
With complexity and multiple folders it can be tedious to travers through all the paths using relative references.

```js
import Bar from '../../components/foo/Bar'
// Better
import Bar from 'components/foo/Bar'
````

This is super simple to do in Webpack.
Currently I create a config file looking like this:

```js
module.exports = {
  chainWebpack: config => {
    config.resolve.modules.add("./src");
  }
};
```

### What does the proposed API look like?
Adding `./src` to the default webpack config would make this easier for many people and prevent some errors for some developers as the path can always be used from the actual src folder.

**Comment by Akryum** [comment]
You can already write:

```js
import Bar from '@/components/foo/Bar'
```

IMHO this is even better because it's more explicit that it's from the source code and note a node_modules package.
