### ISSUE TITLE
vue add should work with plugins that don't have a generator

### ISSUE THREAD

**Issue by anthonygore** [vuejs/vue-cli#1017]
### What problem does this feature solve?
`vue add` is probably the command that most people will want to use when adding new plugins to their project. Currently, it throws an error for plugins where there is no generator. It seems odd that the user would have to know to use `npm i -D <plugin>` instead for plugins with no generator.

### What does the proposed API look like?
`vue add` will install the plugin then detect if the plugin has a generator, and if not, skip the invoke.

**Comment by Akryum** [comment]
Currently, a vue-cli plugin without generator is invalid. vue-cli plugins are meant to be invoked when added to a project, so I don't see the point of this.

**Comment by anthonygore** [comment]
It’s says in the docs that a plugin “can contain a generator” which I assume to mean is optional

https://github.com/vuejs/vue-cli/blob/dev/docs/plugin-dev.md#generator

Maybe I am confused about something here, but from what I understand, if the plugin only needs to tweak webpack config why should it need a generator?

**Comment by anthonygore** [comment]
Further up in the docs it’s made clear that a generator is optional https://github.com/vuejs/vue-cli/blob/dev/docs/plugin-dev.md#cli-plugin

**Comment by Akryum** [comment]
I mean `vue add` is meant to install **and** invoke a vue-cli plugin. It's like a better `vue invoke`.

**Comment by LinusBorg** [comment]
@Akryum I see your point, but that's not clear from the command's description. While it says "install a plugin and invoke its generator" its not clear that a missing generator will break the command.

So i think we should have `invoke` handle this gracefully. We could either skip the invokation silently or log a message to the console like `<plugin> doesn't contain a generator, skipping invokation` or something.

**Comment by yyx990803** [comment]
Yeah we can make that optional - if the plugin does not have a generator, we will just skip it. In this case `vue add` is simply an alias for `npm install` or `yarn add`, but I think it's good to have the consistency that you can `vue add` any CLI plugin without worrying if it contains a generator. This also makes it easier for plugin authors to write consistent usage docs.

**Comment by Akryum** [comment]
Aye.
