### ISSUE TITLE
can not import image when it in js

### ISSUE THREAD

**Issue by cloudshadow** [vuejs/vue-cli#102]
i write pixi.js demo in vue
but i find can not load image in js code. 
`
  import PIXI from 'pixi.js/bin/pixi.js'
  export default {
    data () {
      return {
        animeImages: {
          bunny: '../assets/anime/bunny.png'
        }
      }
    },
    ready () {
      // let self = this
      var renderer = PIXI.autoDetectRenderer(800, 600, { backgroundColor: 0x1099bb })
      document.body.appendChild(renderer.view)

      var stage = new PIXI.Container()
      // this line not work
      var texture = PIXI.Texture.fromImage('../assets/anime/bunny.png')
      var bunny = new PIXI.Sprite(texture)
      bunny.anchor.x = 0.5
      bunny.anchor.y = 0.5
      bunny.position.x = 200
      bunny.position.y = 150
      stage.addChild(bunny)
      animate()
      function animate () {
        window.requestAnimationFrame(animate)
        bunny.rotation += 0.1
        renderer.render(stage)
      }
    }
  }
</script>`

**Comment by yyx990803** [comment]
http://vuejs-templates.github.io/webpack/static.html
