### ISSUE TITLE
Enable WebStorm to run eslint on .vue files out of the box

### ISSUE THREAD

**Issue by b-jazz** [vuejs/vue-cli#1023]
### What problem does this feature solve?
JetBrains' WebStorm doesn't run eslint on .vue files by default. Turning on the linter for .vue files will help new users write cleaner code in the editor without having to wait for the files to be served by webpack to notice the error.

### What does the proposed API look like?
I found that by adding a **"plugins": ["vue"]** section to the `eslintConfig` section of `package.json`, WebStorm would turn on instant linting of .vue files as well as the .js files it normally lints. Would it be possible to have the configs that are generated by vue-cli at project creation include this `plugins` statement by default?

**Comment by LinusBorg** [comment]
gThat plugin is already loaded by the vue:essential preset we add to the config:

https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/configs/base.js#L21-L23

If Webstorm is not picking up on that, it might be a problem with their implementation?

**Comment by b-jazz** [comment]
Fair enough. Sounds like a problem with Webstorm then. I'll close this bug out.
