### ISSUE TITLE
Option to add cypress-vue-unit-test as an additional/alternative of vue-test-utils

### ISSUE THREAD

**Issue by DrSensor** [vuejs/vue-cli#1026]
### What problem does this feature solve?
https://github.com/bahmutov/cypress-vue-unit-test can be used as the unit test that also can act as presentation layer of some component. It's not meant to replace vue-test-utils but more like to test complex component that needs visual feedback.

### What does the proposed API look like?
```txt
? Pick a unit testing solution:
❯ Mocha + Chai
  Jest
  Cypress unit test
```

<details>
<summary>Or using radio button</summary>

```txt
? Pick a unit testing solution:
❯ Mocha
  Jest
```

then on the next step

```txt
? Pick a unit testing helper:
❯◯ chai
 ◯ vue-test-utils
 ◯ cypress-vue-unit-test
```
</details>

**Comment by LinusBorg** [comment]
Just like for #883:

You can create a third-party vue-clu plugin for that.

I don't think we want to offer too many different choices out of the box. Too many choices increase both maintainance debt for us and decicion fatgue for users

**Comment by yyx990803** [comment]
Closing in favor of a community plugin.
