### ISSUE TITLE
How to disable autoload vue project after update code or any other in vue file

### ISSUE THREAD

**Issue by kpeng2016** [vuejs/vue-cli#1028]
### What problem does this feature solve?
As my project request, I don't hope the function of autoloading project after update code or any other in any vue files

### What does the proposed API look like?
createBundleRenderer({
  inject:true,
  renderScripts: function() { ... },
})

**Comment by yyx990803** [comment]
I have no idea what you are asking for. If you are talking about hot-reload, it can be disabled by setting `hotReload: false` in `vueLoader` options.

**Comment by kpeng2016** [comment]
hi,
Maybe you give me a solution. but does it will make the hotReload false for each vue file.
My case is:
for example I open a page of a.vue file in browser to revie the page status, in this a.vue file page, there are some buttons with saving-fuction that can create/update related .js/.json/... files, if I click one of the button , my purpose is saving/updating a .js/.json/... file, then I contiune to edit this a.vue page, but all information that I typed in page of this a.vue file are missed, because of auto reload function(maybe is this hotReload).
Is that possilbe I assign some .vue/.js/.json/... files don't use this hotReload?
Thanks
William

**Comment by Akryum** [comment]
See:
- https://cli.vuejs.org/config/#devserver
- https://webpack.js.org/configuration/dev-server/#devserver-watchoptions-
- https://webpack.js.org/configuration/watch/#watchoptions-ignored
