### ISSUE TITLE
Cannot fully override rule in Webpack config

### ISSUE THREAD

**Issue by michaelpumo** [vuejs/vue-cli#1030]
### Version
3.0.0-beta.6

### Reproduction link
[https://codesandbox.io/s/7mklr625z6](https://codesandbox.io/s/7mklr625z6)

### Steps to reproduce
Go to App.vue to see the loading of the SVG asset. The SVG contents is displayed in the view.

### What is expected?
svg-sprite-loader is not being used (setup in vue.config.js). The Star data property should be an object after being processed by this loader.

### What is actually happening?
The SVG is still being processed with file-loader from the default Webpack configuration and is therefore returning a string.

**Comment by yyx990803** [comment]
CodeSandbox is not using the latest CLI version yet, so this is not a valid reproduction.

**Comment by michaelpumo** [comment]
I’m not sure then how I would demo a reproduction? The result is the same as what I see on latest anyway. Unsure if it’s a bug then.

**Comment by yyx990803** [comment]
You can provide a GitHub repository as a reproduction.

**Comment by divyamrastogi** [comment]
Hi @yyx990803 ,

Created a repo for reproduction. 
[https://github.com/divyamrastogi/config-override-bug-demo](https://github.com/divyamrastogi/config-override-bug-demo)
I'm facing this same issue while trying to change the loader for svg files, the default loader (file-loader) doesn't get overridden.
Hope you're able to reproduce and reopen this issue. Let me know if you need more information.
Thanks!

**Comment by michaelpumo** [comment]
Hi @yyx990803 - is it possible to get this issue reopened at all in light of the above repo? Thanks.
