### ISSUE TITLE
Why not provide  template formatting ?

### ISSUE THREAD

**Issue by my9074** [vuejs/vue-cli#1033]
### What problem does this feature solve?
Currently there is no uniform formatting standard for the html part of the vue file. This results in different html formatting styles for everyone on the team. Provide a unified html style can effectively improve team efficiency

### What does the proposed API look like?
@vue/cli 3.0 already provides a good default configuration for lint. For example, provide prettier, standard, and so on. But they are all against the script and style tags in the .vue file. The template tag is just a check for vue syntax. Why can't I provide a default configuration for formatting alignment?

**Comment by my9074** [comment]
@LinusBorg I went to prettier community and found that they are planning to support html formatting.
>https://github.com/vuejs/vetur/blob/master/docs/formatting.md#plan


This is the relevant issue, [Vue Support](https://github.com/prettier/prettier/issues/2097) and [Supporting HTML/Mustache](https://github.com/prettier/prettier/issues/1882)

**Comment by yyx990803** [comment]
This is not something that we will add in vue-cli.
