### ISSUE TITLE
Allow a way to get the "full build" of Vue using the CLI

### ISSUE THREAD

**Issue by mattgrande** [vuejs/vue-cli#1040]
### What problem does this feature solve?
(Forgive me if this already exists, I couldn't find it)

As I'm sure you are all aware, there are a few [different builds of Vue](https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds) included in the NPM package. I would be helpful to be able to specify "I would like the full build version."

### What does the proposed API look like?
Eg, `vue-cli-service serve --build=full`

**Comment by yyx990803** [comment]
You can use compiler: true in vue.config.js

**Comment by mattgrande** [comment]
Sorry, I don't see a `vue.config.js` file?

**Comment by Akryum** [comment]
Create one at the root of your project.

**Comment by mattgrande** [comment]
Ah, okay, I see what you're talking about.

For others coming here, documentation is here: https://alligator.io/vuejs/using-new-vue-cli-3/#the-vueconfigjs-file

**Comment by jonathanbrincat** [comment]
For the sanity of others a slight correction to the above info. Key to trigger boolean is:
`runtimeCompiler: false`

Fyi configuration can either go under a `vue` config key in `package.json` or it's own `vue.config.js` file.

**Comment by Akryum** [comment]
Documentation: https://cli.vuejs.org/config/#runtimecompiler
