### ISSUE TITLE
postcss/cssnext

### ISSUE THREAD

**Issue by solidevolution** [vuejs/vue-cli#1043]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/MoOx/postcss-cssnext/issues/455](https://github.com/MoOx/postcss-cssnext/issues/455)

### Steps to reproduce
1. vue create cssnext-bug
2. add some nested postcss in the HelloWorld.vue component
3. npm run test

### What is expected?
Unittest with postcss/cssnext works

### What is actually happening?
Unittest breaks if postcss in component style is nested

---
postcss-nesting version in cssnext doesn't work with jest => vue-test-utils => vue-cli

```
FAIL  tests/unit/components/shared/Notification.spec.js
  ● Test suite failed to run

    undefined:180:3: missing '}'

      at error (node_modules/css/lib/parse/index.js:62:15)
      at declarations (node_modules/css/lib/parse/index.js:259:26)
      at rule (node_modules/css/lib/parse/index.js:560:21)
      at rules (node_modules/css/lib/parse/index.js:117:70)
      at stylesheet (node_modules/css/lib/parse/index.js:81:21)
      at Object.module.exports [as parse] (node_modules/css/lib/parse/index.js:564:20)
      at Function.extractClasses (node_modules/extract-from-css/lib/index.js:14:23)
      at processStyle (node_modules/vue-jest/lib/process-style.js:19:31)
      at parts.styles.map.ast (node_modules/vue-jest/lib/process.js:98:11)
          at Array.map (<anonymous>)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.965s
```

**Comment by LinusBorg** [comment]
A Link to an issue that links back to this issue is *not* a valid reproduction.

**Comment by solidevolution** [comment]
@LinusBorg I didn't created a reproduction link because it's an shell issues of npm run test.
My idea to create it here was, that you guys want's a working vue-cli for everyone. vue-jest and more abstractions in your package.json are not in my view ;)

**Comment by LinusBorg** [comment]
But did you even install cssnext?

**Comment by solidevolution** [comment]
@LinusBorg of course!

**Comment by LinusBorg** [comment]
...but you didn't say so in your steps to reproduce. 

And little missing pieces of information are exactly why we demand a repruction. If we use the same code you do, we can exclude all misunderstandings.

So if you want this fixed (provided it even is a bug, I still can't tell), please provide an exact reproduction.

**Comment by LinusBorg** [comment]
So, looking at the vue-jest README, I came to realize that vue-jest simply doesn't have the ability to compile PostCSS yet.

If you had indicated that the component contains postcss like this:
```html
<style lang="postcss">

</style>
```

It would simply be skipped. since you didn't, it assumed normal CSS, which leads to the error above.

**Comment by solidevolution** [comment]
@LinusBorg thx, didn't find that. Any idea how vue-cli will improve that for postcss and jest in future? We are currently refactoring our frontend build stack because of other problems in the old vue-cli webpack-template

**Comment by LinusBorg** [comment]
vue-jest is actively being worked on, *css integrations are one of the major points right now.
