### ISSUE TITLE
Cannot overwrite existing webpack config

### ISSUE THREAD

**Issue by kayandrae07** [vuejs/vue-cli#1045]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/kayandrae07/vue-issue-reporter/](https://github.com/kayandrae07/vue-issue-reporter/)

### Steps to reproduce
My complaint is similar to #1030 and I created a repository [here](https://github.com/kayandrae07/vue-issue-reporter).

### What is expected?
As you can see in App.vue, I'm trying to overwrite vue's existing svg loader rules.

I wan't to load svg's in my project as objects using shopify's image loader. But, for the life of me, I can't get my loaders to kick in. I know webpack-merge has an option to overwrite existing tools and stuff, but is there a way for me to do this?

### What is actually happening?
Instead of the loader loading svgs as objects, file-loader loads it instead.

**Comment by elevatebart** [comment]
Hey @kayandrae07, 
I faced a similar challenge and the solution is fairly simple. 
You should try using the parameter `chainWebpack` in your vue.config.js like in the described on the forum
https://forum.vuejs.org/t/how-can-i-create-two-separate-bundles-with-vue-cli-3/30353/4

``` js
module.exports = {
  chainWebpack: config => {
    // ...
    config.module.rules.delete("svg");
  }
};
```
I will cook up a quick PR for your repo.

**Comment by elevatebart** [comment]
[here is the PR](kayandrae07/vue-issue-reporter#1)

**Comment by kayandrae07** [comment]
Yes! thank you.
