### ISSUE TITLE
offline use

### ISSUE THREAD

**Issue by mailok** [vuejs/vue-cli#1047]
### What problem does this feature solve?
With the new vue-cli, can I create projects offline?
I say this because we do not all have the internet of the rich countries, and it would be a pity not to be able to use it vue-cli for living in Cuba for example.

### What does the proposed API look like?
I propose that you can create projects by installing vue-cli, but that when creating a vue proyect you do not have to connect to the internet

**Comment by yyx990803** [comment]
Unfortunately this is not possible because you'd have to install npm dependencies... there's no way around that. The alternative is install `@vue/cli-service-global` once and then use `vue serve` and `vue build` while offline.

**Comment by maritaria** [comment]
This could be achieved by passing the parameter `--prefer-offline` to yarn (when using it as package manager) so that dependencies can be installed from cache and you dont have to wait for network timeouts.

**Comment by annymosse** [comment]
@yyx990803 i got a problem when i `yarn serve/npm run serve` without connection , after a longtime developing same project, if i turn the wifi on it's work well turn it off again doesn't work !!!???
