### ISSUE TITLE
vue invoke could be able to rename files

### ISSUE THREAD

**Issue by elevatebart** [vuejs/vue-cli#1048]
### What problem does this feature solve?
When using a plugin immediately at create, files can be renamed or deleted. 
When using `vue invoke` or `vue add` plugins cannot. 
This makes creation of plugin this much harder.

### What does the proposed API look like?
A couple of changes on the Generator.js files to be able to compare file trees before and after plugin would allow the `@vue/cli/lib/util/writeFileTree.js` to delete the file that have been renamed.

I made a quick PR to propose a solution. You can find an illustration of the problem I solve [here](https://github.com/elevatebart/vuecliinvoke)

**Comment by yyx990803** [comment]
Closed via #1049
