### ISSUE TITLE
现在的模版里有一些vue的组件模版，用到了{{some-attr}}的数据绑定，在模版编译的时候发现其中的{{}}里面的东西全被替换成空了

### ISSUE THREAD

**Issue by zhipenglin** [vuejs/vue-cli#105]
现在的模版里有一些vue的组件模版，用到了{{some-attr}}的数据绑定，在模版编译的时候发现其中的{{}}里面的东西全被替换成空了

举个例子：

- Vue.component('child', {
  // 声明 props
  props: ['msg'],
  // prop 可以用在模板内
  // 可以用 `this.msg` 设置
  template: '<span>{{ msg }}</span>'
})

- 通过该模版生成的对应的地方变成Vue.component('child', {
  // 声明 props
  props: ['msg'],
  // prop 可以用在模板内
  // 可以用 `this.msg` 设置
  template: '<span></span>'
})

**Comment by zhipenglin** [comment]
我需要怎么转义一下还是怎么样呢

**Comment by yyx990803** [comment]
模板里要用 `\{{}}`
