### ISSUE TITLE
Please add package.json's browserlist settings to css.md doc

### ISSUE THREAD

**Issue by transtone** [vuejs/vue-cli#1054]
### What problem does this feature solve?
autoprefixer use browserlist for it's browser check, some one like me may not read the autoprefixer's readme carefully.

### What does the proposed API look like?
please mention it in https://github.com/vuejs/vue-cli/blob/dev/docs/css.md doc

**Comment by elevatebart** [comment]
Hello @transtone, 

I would like to propose a quick Pull Request fixing this issue.
What would you expect in a few word for the doc to explain? 
Do you wish for a link to [autoprefixer documentation](https://github.com/postcss/autoprefixer#browsers) ?

Or would you like that I document the supported browsers in this file and how this configuration ican be changed?
[index.js](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/generator/index.js)

``` js
{
  browserslist: [
      '> 1%',
      'last 2 versions',
      'not ie <= 8'
    ]
}
```

**Comment by transtone** [comment]
because postcss-next's setting is in .postcssrc file, but autoprefixer's settings is using browserslist, I'd like the doc tell us the difference. 

```
Vue CLI uses PostCSS internally, and enables autoprefixer by default. You can configure PostCSS via .postcssrc or any config source supported by postcss-load-config.
```
in these words, I thought I could only configure postcss in .postcssrc, or other postcss setting files.

how about this:
```
Vue CLI uses PostCSS internally, and enables autoprefixer by default. You can configure autoprefixer in    package.json(see autoprefixer document) and configure PostCSS via .postcssrc or any config source supported by postcss-load-config.
```

**Comment by yyx990803** [comment]
Closing as it's addressed in the new docs.
