### ISSUE TITLE
Use a custom template  parsing errors when the vue file exists filter

### ISSUE THREAD

**Issue by ketuzhong** [vuejs/vue-cli#1063]
### Version
2.9.3

### Reproduction link
[https://github.com/ketuzhong/cd-vue-template](https://github.com/ketuzhong/cd-vue-template)

### Steps to reproduce
`cd-vue-template`  is a  custom  vue-cli template

when do `vue init ketuzhong/cd-vue-template YourProjectName`  , happened ` Parse error`, because the vue file exists filter

Whether does not support the filter ？

```
vue-cli · [src/containers/course/list/index.vue] Parse error on line 28:
...{{ scope.row.status | courseStatus }}  
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', 'SEP', got 'CLOSE_BLOCK_PARAMS'
```

`courseStatus`  is a filter

```
const courseStatus = {
  published: '发布',
  closed: '已关闭',
  draft: '未发布',
};

export default {
  install(Vue) {
    Vue.filter('courseStatus', value => courseStatus[value]);
  },
};
```

[https://github.com/ketuzhong/cd-vue-template/blob/master/template/src/containers/course/list/index.vue](https://github.com/ketuzhong/cd-vue-template/blob/master/template/src/containers/course/list/index.vue)

```
<el-table-column
        label="课程状态"
        width="120">
        <template scope="scope">
          {{ scope.row.status | courseStatus }}
        </template>
      </el-table-column>
```

### What is expected?
vue-cli template can support `filter`

### What is actually happening?
parsing errors when the vue file exists `filter`

**Comment by LinusBorg** [comment]
You have to escape vue ingerpolations? Otherwise the cli's template engine tries to parse them: 

> \{{ scope.row.status | courseStatus }}
