### ISSUE TITLE
Creating a scoped library fails to load in an application

### ISSUE THREAD

**Issue by johnwebbcole** [vuejs/vue-cli#1064]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/johnwebbcole/vue-cli-scoped-lib-issue](https://github.com/johnwebbcole/vue-cli-scoped-lib-issue)

### Steps to reproduce
# error loading lib created with vue-cli

Creating a lib with `vue-cli` works with the demo, but importing into 
an app (also created by `vue-cli`) returns the following:

```text
This dependency was not found:

* @jwc/alib1 in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"D://src//temp//vue-cli-scoped-lib-issue//app1//node_modules//.cache//cache-loader"}!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/Home.vue

To install it, you can run: npm install --save @jwc/alib1
```

## Steps to reproduce

```bash
git clone https://github.com/johnwebbcole/vue-cli-scoped-lib-issue.git
cd vue-cli-scoped-lib-issue
cd lib1
npm i
npm run build
cd ..
cd app1
npm i
npm run serve
```

I'm not sure if I created the lib wrong or imported it wrong.

### What is expected?
I'm expecting the library `HelloWorld.vue` component to be shown.

### What is actually happening?
Running the app results in

```text
This dependency was not found:

* @jwc/alib1 in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"D://src//temp//vue-cli-scoped-lib-issue//app1//node_modules//.cache//cache-loader"}!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/Home.vue

To install it, you can run: npm install --save @jwc/alib1
```

**Comment by LinusBorg** [comment]
Your lib's package.json doesn't have a `main` or `files` fields which would define the exports of the package, so npm just looks for ` index.js, which doesn't exist.

**Comment by LinusBorg** [comment]
* I would put the `/dist` in `files`, maybe also `/src`.
* I would put the umd build in the `browser` field, and the commonjs one in the `main` field.
*

**Comment by LinusBorg** [comment]
@johnwebbcole  So, did that solve your problem?

**Comment by johnwebbcole** [comment]
Going to try it this weekend, but I suspect that will fix it.

**Comment by johnwebbcole** [comment]
Seems to work! Thx
