### ISSUE TITLE
Allow --preset to accept a file path

### ISSUE THREAD

**Issue by JohnnyCrazy** [vuejs/vue-cli#1068]
### What problem does this feature solve?
I want to test my local preset-repository and it would be a shame if I had to push everytime. So, for testing and general purposes, it would be nice to also load presets by specifying a path to a local file.

### What does the proposed API look like?
so we could either fallback if the preset name is not found, then we could go for:

`vue create my_app --preset preset.json`

or a more specialized way:

`vue create my_app --preset file:preset.json` or even `vue create my_app --preset-file preset.json`

The implementation it self is rather short. When there is an API decision, I could go for a PR.

**Comment by yyx990803** [comment]
I think we can simply assume it's a file if the value ends in `.json`. Open to a PR.
