### ISSUE TITLE
Better error stack info.

### ISSUE THREAD

**Issue by erguotou520** [vuejs/vue-cli#107]
## Vue cli version
2.0.2

## Scene
I forked `vue-template/webpack`, and changed some files. When I init it my project using this forked template, I get an error.
![image](https://cloud.githubusercontent.com/assets/7945757/15799265/fd270824-2a88-11e6-930b-d94bf47f0799.png)

## Suggestion
It's better to log the error's stack info so I can find where the error is. Exactly no result after I searched my forked project.

**Comment by zigomir** [comment]
@erguotou520 It's probably because you run vue-cli@2.0.2 over `master` branch of `vue-template/webpack`? See here: https://github.com/vuejs-templates/webpack/tree/master#version-notice

**Comment by LinusBorg** [comment]
clsoing due to inactivity of the OP.
