### ISSUE TITLE
--target lib Conflicts with custom Webpack entry

### ISSUE THREAD

**Issue by dodekeract** [vuejs/vue-cli#1072]
### Version

3.0.0-beta.6

### Reproduction link

[https://github.com/3YOURMIND/vue-yodify/commit/0e47bed9fbd1acd3bb8fee2934b4720b8d106569](https://github.com/3YOURMIND/vue-yodify/commit/0e47bed9fbd1acd3bb8fee2934b4720b8d106569)

### Steps to reproduce

Install with this commit and compare with the previous commit (or remove the custom env stuff from the vue.config.js).

### What is expected?

Build as library with correct entry point

### What is actually happening?

Builds as app with wrong entry point

**Comment by rafaph** [comment]
I've been thinking about it, here is my current `vue.config.js` for generate a vue component library.

```js
module.exports = {
  chainWebpack(config) {
    // Library name
    const libraryName = "myLibrary";

    // Set library name as entry point and delete app
    config.entryPoints
      .set(libraryName, config.entryPoints.get("app"))
      .delete("app")
      .end();

    // webpack settings for generate a library
    config.output
      .set("filename", "[name].js")
      .set("libraryTarget", "umd")
      .set("library", libraryName)
      .end();

    // set vue as external dependency
    config
      .set("externals", {
        vue: "vue"
      })
      .end();

    // delete unused plugins
    config.plugins
      .delete("hash-module-ids")
      .delete("split-vendor")
      .delete("split-manifest")
      .delete("inline-manifest")
      .delete("split-vendor-async")
      .delete("html")
      .end();

    // remove hash of css filename
    config
      .plugin("extract-css")
      .tap(args => {
        args[0].filename = "[name].css";
        return args;
      })
      .end();
  }
};
```
Hope it helps you. I'm open to suggestions for improving this setting.
