### ISSUE TITLE
Upgrade webpack template to Webpack 4

### ISSUE THREAD

**Issue by bp91** [vuejs/vue-cli#1077]
### What problem does this feature solve?
This version of vue-cli uses a webpack template with following packages:

optimize-css-assets-webpack-plugin 3.2.
webpack  3.6.0
webpack-dev-server 2.9.1

If I try to upgrade these packages, the build script incurs to this error:

```
/node_modules/webpack/lib/webpack.js:165
			throw new RemovedPluginError(errorMessage);
			^

Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
```

Since vue-cli is really usefull, I think it's necessary to upgrade the webpack template

### What does the proposed API look like?
The command

- vue init webpack <app-name>

should create webpack.config.js files that uses the updated modules of webpack

**Comment by zhongzi** [comment]
same problem, thanks.

**Comment by yyx990803** [comment]
This should be posted to the template's own repo. That said, we are unlikely to do that since 2.x templates will be in maintenance mode with CLI 3 coming soon (which will have webpack 4 support)

**Comment by bp91** [comment]
@yyx990803 thanks for the answer
