### ISSUE TITLE
组件重复编译

### ISSUE THREAD

**Issue by acmeid** [vuejs/vue-cli#108]
版本：2.0.2

使用vue-router动态组件的时候：
页面a和页面b都import了一个相同的组件，然而打包的时候，这个组件会分别打包成两个js以供这两个页面调用。
我希望的是，相同的组件可否只打包成一个js文件，供这两个页面应用，避免重复加载。

**Comment by yyx990803** [comment]
这个不属于 vue-cli 的问题，完全是 webpack 的问题 。请自行研究方案
