### ISSUE TITLE
User-defined webpack aliases are not resolved

### ISSUE THREAD

**Issue by davidwallacejackson** [vuejs/vue-cli#1080]
### Version
3.0.0-beta.6

### Reproduction link
[https://codesandbox.io/s/k2noq6mqy5](https://codesandbox.io/s/k2noq6mqy5)

### Steps to reproduce
Just run the app, the error will appear on compilation.

### What is expected?
The homepage of the default vue-cli template should display.

### What is actually happening?
A compilation error: "Could not find dependency: 'src'"

---
I added a webpack alias, `src`, to the vue.config.js file, then changed the `App` component to import `HelloWorld` via that alias.

When I tried this locally:
* I looked at `inspect` and found that my webpack config was being merged as I expected
* There were some other aliases provided by vue-cli, including `@` which pointed to the same directory as my `src` alias
* When I used `@` in my code, it compiled, but `src` gave me a compilation error.

**Comment by LinusBorg** [comment]
codesandbox does not run on vue-cli 3

**Comment by LinusBorg** [comment]
Will close this as invalid.
