### ISSUE TITLE
Build error on deploying to gh-pages

### ISSUE THREAD

**Issue by marco-carvalho** [vuejs/vue-cli#1088]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/marco-carvalho/foursquare](https://github.com/marco-carvalho/foursquare)

### Steps to reproduce
1) Set global variables on CircleCI
2) Use the deploy.sh on the repo
3) Build using CircleCI
4) If the build dont show errors, the gh-pages would be created
5) When I check the link (https://marco-carvalho.github.io/foursquare), there are errors on the console (Failed to load resource: the server responded with a status of 404 () /css/app.23a5f890.css:1)

### What is expected?
I think that the HTML build should have scripts like this:
<script type="text/javascript" src="./js/vendor.de135044.js"></script>

### What is actually happening?
The HTML build doesn't have the dot at the start of the src:
<script type="text/javascript" src="/js/vendor.de135044.js"></script>

**Comment by yyx990803** [comment]
You need to set baseUrl in vue.config.js...
