### ISSUE TITLE
Adding a sass-loader option with chainWebpack requires double entry

### ISSUE THREAD

**Issue by laander** [vuejs/vue-cli#1090]
### What problem does this feature solve?
Given [this example](https://github.com/vuejs/vue-cli/blob/dev/docs/webpack.md#modifying-loader-options) in the webpack part of the docs, you would assume that this is all you need to add a custom option for `sass-loader`, but that snippet only affects standalone `.scss` files handled by webpack.

Code inside `.vue` files in the `<style lang="scss">` is managed by `vue-loader` and this change is not getting copied into the respective `vue-loader.options.loaders.scss` block automatically.

To achieve that, you currently need to do something like this:
```
var path = require('path')
var merge = require('lodash/merge')
var findIndex = require('lodash/findIndex')

module.exports = {
  chainWebpack: config => {
    config.module
      .rule('scss')
      .use('sass-loader')
      .tap(options =>
        merge(options, {
          includePaths: [
            path.resolve(__dirname, 'src/styles')
          ]
        })
      )
    config.module
      .rule('vue')
      .use('vue-loader')
      .tap(options => {
        var i = findIndex(options.loaders.scss, { loader: 'sass-loader' })
        merge(options.loaders.scss[i].options, {
          includePaths: [
            path.resolve(__dirname, 'src/styles')
          ]
        })
        return options
      })
  }
}
```

Notice the double entries; one for the `scss` rule and one for the `vue` rule. Webpack Chain is already hard enough to wrap your head around as it is :)

### What does the proposed API look like?
I would simply expect that all changes added to top level extension rules like `scss` is automatically copied and applied to the same extension specific blocks inside the `vue-loader` options.

Is there any good reason why this should not be a sane default?

**Comment by laander** [comment]
Update: this actually already works if I just use the shorthand config `css.loaderOptions` instead of trying to achieve it through `chainWebpack` as [shown here](https://github.com/vuejs/vue-cli/blob/dev/docs/config.md).

Somebody has clearly thought this through already - awesome 🤘

Full example for others that stumble upon this:

```
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        includePaths: [
          path.resolve(__dirname, 'src/styles')
        ]
    }
  }
}
```

The [example in docs](https://github.com/vuejs/vue-cli/blob/dev/docs/webpack.md#modifying-loader-options) is slightly misleading and should perhaps be updated with the above example instead.

**Comment by yyx990803** [comment]
You don't need to add `sass-loader` yourself. Use `css.loaderOptions` in `vue.config.js`.
