### ISSUE TITLE
Allow presets plugins not to skip prompts

### ISSUE THREAD

**Issue by nothinggift** [vuejs/vue-cli#1092]
### What problem does this feature solve?
We hope to use vue-cli 3 to completely replace the vue template. We have developed some plug-ins to create projects, and some still require our developers to configure them according to the prompts. This is much more convenient than installing these plug-ins after creating the project.

### What does the proposed API look like?
Maybe?
```
"plugins": {
  "vue-cli-plugin-apollo": {
    "prompts": true
  }
}
```

**Comment by andreasvirkus** [comment]
Seems to be a duplicate of https://github.com/vuejs/vue-cli/issues/952

**Comment by nothinggift** [comment]
indeed
