### ISSUE TITLE
cli 3.0 release schedule?

### ISSUE THREAD

**Issue by lzp4ever** [vuejs/vue-cli#1094]
### What problem does this feature solve?
no commit recently, any schedule of the release version? can't wait to use it in prod env !

### What does the proposed API look like?
v3.0.0 release

**Comment by Akryum** [comment]
Very soon! :cat2:

**Comment by osman-mohamad** [comment]
Any specific date @Akryum ?

**Comment by MartinX3** [comment]
@Akryum 

Very soon was many months ago.

**Comment by Akryum** [comment]
Now it's very very soon! 🐈

**Comment by MartinX3** [comment]
Hihihi
I try rc5 in my company now.
