### ISSUE TITLE
Cannot specify fixed output file names

### ISSUE THREAD

**Issue by noscript** [vuejs/vue-cli#1097]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/noscript/vue-cli-nohash](https://github.com/noscript/vue-cli-nohash)

### Steps to reproduce
Add vue.config.js:
```
var ExtractTextPlugin = require("extract-text-webpack-plugin")
module.exports = {
  configureWebpack: config => {
    config.output.filename = "[name].js";
    config.plugins.push(new ExtractTextPlugin({
      filename: 'css/[name].css'
    }));
  }
};
```

### What is expected?
```
  dist/vendor.js               89.20 kb               31.27 kb
  dist/app.js                  12.54 kb               8.00 kb
  dist/manifest.js             0.83 kb                0.47 kb
  dist/css/app.css             0.42 kb                0.26 kb
```

### What is actually happening?
```
  dist/vendor.js               89.20 kb               31.27 kb
  dist/app.js                  12.54 kb               8.00 kb
  dist/manifest.js             0.83 kb                0.47 kb
  dist/css/app.3812306e.css    0.42 kb                0.26 kb
  dist/css/app.css             0.42 kb                0.26 kb
```

---
I really like the idea of slim `vue.config.js` to configure only necessary parts but nowadays vue-cli generates projects with chunks/splitting enabled (for cache busting reasons etc), so .js and .css files have a hash in their file names. Due to the nature of the webserver I use I need to have deterministic file names. I managed to get rid of the hashes in .js files but stuck with css. 

Using `ExtractTextPlugin` I can specify the file name but  I still get another css generated with a hash, which is also included in `index.html`.

P.S. I hope I do not need to bloat `vue.config.js` with entire output of `vue-cli-service inspect` to configure that.

**Comment by Akryum** [comment]
Since you are adding an extra ExtractTextPlugin, you end up with two CSS files. You need to use `tap('extract-css')` to modify the existing ExtractTextPlugin, see the [webpack-chain docs](https://github.com/mozilla-neutrino/webpack-chain#config-plugins-modify-arguments).
