### ISSUE TITLE
 vue-router template missing opening <router-view>

### ISSUE THREAD

**Issue by atilkan** [vuejs/vue-cli#1099]
<img width="356" alt="screen shot 2018-04-09 at 20 20 32" src="https://user-images.githubusercontent.com/1254613/38512482-ed7bc220-3c33-11e8-8a7e-01a745ac176e.png">
### Version
3.0.0-beta.6

### Reproduction link
[http://iwilluploadapicture.com](http://iwilluploadapicture.com)

### Steps to reproduce
It just came like this.

### What is expected?
tags to be matched

### What is actually happening?
tags doesn't match. No opening tag.

**Comment by posva** [comment]
It's a self closing tag: `<router-view></router-view>` <=> `<router-view />`, it's totally valid and preferred for that kind of components 🙂

**Comment by atilkan** [comment]
Ohh, sorry.

**Comment by randName** [comment]
Sorry for necroing this, but is [this comment](https://github.com/vuejs/vue/issues/1036#issuecomment-120634281) still valid and/or applicable in this case? A little confused here.

**Comment by sodatea** [comment]
@randName See https://github.com/vuejs/vue/issues/1036#issuecomment-266756591
In-DOM HTML template does not support this syntax and it's inherent to the browser HTML parser. But  it works with any other kind of string template (Single File Components loaded by vue-loader or the `template` option)
