### ISSUE TITLE
 `error  eol-last  Newline required at end of file but not found` syntax on Home.vue

### ISSUE THREAD

**Issue by aguegu** [vuejs/vue-cli#11]
Just init a bran new project with

```
$ vue init webpack vocabulary2
```

<img width="719" alt="screen shot 2016-01-07 at 17 30 24" src="https://cloud.githubusercontent.com/assets/1559791/12166984/7d4ae02e-b564-11e5-8023-73b815cfd8dc.png">

I just got this `error  eol-last  Newline required at end of file but not found` syntax on Home.vue. 

But the Newline is there. And I have no idea where '//' come from.

My environment setup: 

<img width="580" alt="screen shot 2016-01-07 at 17 30 41" src="https://cloud.githubusercontent.com/assets/1559791/12166986/7f355aa4-b564-11e5-94c4-9da083e7dbb9.png">

**Comment by aguegu** [comment]
quick fix with
```
/* eslint-disable eol-last */ 
```
?

**Comment by yyx990803** [comment]
Fixed in vue-loader@8.0.2.

**Comment by aguegu** [comment]
Thanks for quick fix.

Solve the problem by running 

```
$ npm update --save
```

**Comment by raphcadiz** [comment]
Hi I'm getting this error and I can't fix this on doing running npm update. Any help

**Comment by yangfan0095** [comment]
Thanks too

**Comment by YarenTang** [comment]
Thanks too

**Comment by fionagithub** [comment]
how to fix it?

**Comment by Almusamim** [comment]
@fionagithub 

I was getting this error testin out nuxt as well 
`error  Newline required at end of file but not found  eol-last`

inserting a blank line at the bottom of the xxx.vue﻿ file fixed the issue for me

**Comment by congtoanle** [comment]
@Almusamim Thank you! Work with Latest Nuxt Version!

**Comment by naaataliaazevedo** [comment]
i restarted my project and it's okay now.

**Comment by teddynted** [comment]
Adding a blank line at the end of the file/code worked for me.

**Comment by RoelRoel** [comment]
Who made up these rediculous rules? Why would you want an empty line at the end of each file? And why so strict that it breaks the build. Rediculous control freaks...

**Comment by marmeden** [comment]
Just add a new line, so the other line is not the last

**Comment by 94tomas** [comment]
if it works by increasing a blank line, thanks for the solution

**Comment by stivenjimenez** [comment]
Just add a new line, so  the other line is not the last  
that worked for me
