### ISSUE TITLE
vue create 创建项目时候回报 ERROR command failed: yarn

### ISSUE THREAD

**Issue by lee134134134** [vuejs/vue-cli#1101]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/vuejs/vue-cli/issues/1100](https://github.com/vuejs/vue-cli/issues/1100)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/4250254/38533834-8d6aafca-3cad-11e8-8bf2-39194029b82e.png)

### What is expected?
vue create 创建项目时候回报 ERROR command failed: yarn

### What is actually happening?
见附件图片

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by zhongs** [comment]
我也碰到这个问题，切回npm来安装就好了；

找到.vuerc隐藏文件 ，路径：C:\Users\你的用户名\.vuerc 
修改packageManager 字段为npm

**Comment by 565784135** [comment]
window系统下，新增一个环境变量就好了
https://www.jianshu.com/p/9308e6abbe44

**Comment by qinkaiyuan** [comment]
> 嗨，感谢您的关注，但Github问题仅针对错误报告和功能请求。您可以在[论坛](http://forum.vuejs.org/)，[Discord服务器](https://vue-land.js.org/)，[gitter](https://gitter.im/vuejs/vue)或[StackOverflow上](http://stackoverflow.com/tags/vue.js)[提问](https://gitter.im/vuejs/vue)。

Is this not a bug?

**Comment by youyiqin** [comment]
> 我也碰到这个问题，切回npm来安装就好了；
> 
> 找到.vuerc隐藏文件 ，路径：C:\Users\你的用户名\ .vuerc
> 修改packageManager 字段为npm

或者在`vue create`后加`-m npm`

**Comment by zier95** [comment]
我也遇到这个问题了，先安装yarn: npm install -g yarn,
在创建项目还是会报错，在安装nrm切换镜像，使用nrm use npm ,
切换为npm的镜像后再次安装vue项目
