### ISSUE TITLE
provide baseUrl for development mode

### ISSUE THREAD

**Issue by troy351** [vuejs/vue-cli#1102]
### What problem does this feature solve?
`baseUrl` in `vue.config.js` now only works in production mode.
In my case, I need to load the page as an `iframe`.

something like
```
<!-- http://localhost/ -->
<body>
<iframe src="http://localhost/myframe/"></iframe>
</body>
```

But it turns out `http://localhost/myframe/` will load `app.js` from `http://localhost/` which is not right.

PS. I need to inject some data into `iframe`, so it needed to be run in development mode for debugging

### What does the proposed API look like?
maybe a `devBaseUrl`

```javascript
module.exports = {
  baseUrl: '/myframe/', // this works in production mode
  devBaseUrl: '/myframe/' // this works in development mode
}
```

**Comment by duduluu** [comment]
You could set dev server in vue.config.js like this: 

```javascript
const express = require('express');

module.exports = {
  devServer: {
    proxy: null, // string | Object
    before: app => {
      // the app is the instance of the express app
      app.use('/myframe', express.static('path/to/myframe'));
    },
  },
};
```

**Comment by troy351** [comment]
@duduluu 
both `localhost` and `localhost/myframe` are vue app, and they are developed separately (not the same SPA)

**Comment by duduluu** [comment]
You might use dev server proxy. See https://github.com/vuejs/vue-cli/blob/dev/docs/cli-service.md#configuring-proxy

localhost:8080 for your main spa, localhost:8081 for your embed spa.

Set the vue.config.js of your main project, and cli-service serve both spa.

``` js
module.exports = {
  devServer: {
    proxy: {
      '/myframe': {
        target: 'localhost:8081',
      },
    }
  }
}
```

**Comment by troy351** [comment]
@duduluu you may misunderstood my question.
the problem is that embed spa getting its `app.js` from main spa for there is a `/` before it.
So the embed spa won't render correctly.

The main spa finding embed spa thing works fine with nginx

**Comment by fnoop** [comment]
This is a really basic fix, would be nice to have @Akryum fix released
