### ISSUE TITLE
--no-fix option is ignored by vue-cli-service when using typescript.

### ISSUE THREAD

**Issue by BenoitAverty** [vuejs/vue-cli#1112]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/BenoitAverty/vue-cli-test-tslint](https://github.com/BenoitAverty/vue-cli-test-tslint)

### Steps to reproduce
Run `npm run lint -- --no-fix` or `npx run vue-cli-service lint --no-fix`.

### What is expected?
The lint errors should be reported but no file should be changed.

### What is actually happening?
Errors are fixed in the file and not reported.

---
I would like to run linting in a precommit hook but not format the files. Currently this is not possible.

**Comment by dhensche** [comment]
After some digging, appears to be related to https://github.com/substack/minimist/issues/54

**Comment by BenoitAverty** [comment]
Nice catch. It's probably a unix convention. For example, in git, the --no-XXX options are used to override a previous --XXX. minimist seems to have this convention.

**Comment by dhensche** [comment]
Yeah, I'm working on a fix right now. Not a ton of experience writing tests so that is taking most of my time 😨

**Comment by BenoitAverty** [comment]
Awesome thanks. Don't hesitate to ask if you run into any difficulties (I'll help as best as I can but I'm not very familiar with vue cli 3 yet)

**Comment by BenoitAverty** [comment]
in the meantime, I think `npm run lint -- --no-fix=true` should work as an ugly workaround.

@dhensche If you open a PR, I think the same bug is present in the eslint plugin (when typescript is not chosen)

**Comment by dhensche** [comment]
@BenoitAverty The if block inverting the argument doesn't do anything, but because of the minimist conventions the `--no-fix` argument comes into the `args` property as `fix: false` and results in the argument working as expected. https://github.com/vuejs/vue-cli/blob/e65110f3f6c27ce79d6027fa6abc3d7c930d64ea/packages/%40vue/cli-plugin-eslint/lint.js#L10 
Could probably just get rid of that whole if block

**Comment by BenoitAverty** [comment]
But if we remove that, there won't be any way to disable fixing, since the following line sets the options.fix to true 
(https://github.com/vuejs/vue-cli/blob/e65110f3f6c27ce79d6027fa6abc3d7c930d64ea/packages/%40vue/cli-plugin-eslint/lint.js#L14)

**Comment by yyx990803** [comment]
fixed via #1115
