### ISSUE TITLE
defined webpack-simple in new -v???

### ISSUE THREAD

**Issue by davodaslanifakor** [vuejs/vue-cli#1113]
### Version
2.9.3

### Reproduction link
[https://github.com/davodaslanifakor/tamplatevue](https://github.com/davodaslanifakor/tamplatevue)

### Steps to reproduce
 resolve :{
alias:{  '~':path.resolve(__dirname, './src'), }
}

### What is expected?
this is most be to webpack config

### What is actually happening?
i want load my url root '~/componer....'

**Comment by LinusBorg** [comment]
Please use the forum for questions about how to do things: 

https://forum.vuejs.org
