### ISSUE TITLE
No loader specified

### ISSUE THREAD

**Issue by abcdGJJ** [vuejs/vue-cli#1121]
### Version
3.0.0-beta.6

### Reproduction link
[https://jsfiddle.net/50wL7mdz/298228/](https://jsfiddle.net/50wL7mdz/298228/)

### Steps to reproduce
I run `npm run build` this command, then console throw a error that 

`D:\project\vuets\node_modules\_webpack@3.11.0@webpack\lib\RuleSet.js:274 throw new Error("No loader specified");`.

I have a config of vue.config.js like this:

```
module.exports = {
  chainWebpack: (config) => {
    config.module
      .rule('images')
      .use('url-loader')
      .tap(options => ({ ...options, ...{ name: 'img/[name].[ext]', } }))
  }
}
```

Is anything wrong?

### What is expected?
normal build and output files

### What is actually happening?
throw a error of No loader specified

**Comment by abcdGJJ** [comment]
I know the answer, I used an error loader in other rule

**Comment by baohouse** [comment]
I'm getting this error while using less-loader. If I disable the less-loader line in the vue.config.js, it starts building again (although my less files fail). This looks to be a recent change; it was working a few weeks ago.

**Comment by xyy547491937** [comment]
I'm also found this error in my project ,who know  how to slove it,

**Comment by Simple-Young** [comment]
I know you have add loader() this fun after use() just like this:.
           use('iview-loader')
            .tap(options =>{
                return{
                    prefix:false
                }
            })
            .loader('iview-loader')
            .end()
And this answer will be more people see who is the new-bird

**Comment by Simple-Young** [comment]
I know you have add loader() this fun after use() just like this:.
`use('iview-loader').tap(options =>{ return { prefix:false }}).loader('iview-loader').end()`

And this answer will be more people see who is the new-bird
