### ISSUE TITLE
Allow generator templates to create new directories

### ISSUE THREAD

**Issue by andreasvirkus** [vuejs/vue-cli#1123]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/andreasvirkus/vue-cli-plugin-express](https://github.com/andreasvirkus/vue-cli-plugin-express)

### Steps to reproduce
Install the plugin and invoke it
```
npm i andreasvirkus/vue-cli-plugin-express
vue invoke express
```

### What is expected?
Any directory and its contents are also created

### What is actually happening?
The plugin succeeds, but no `/server` directory is created (nor the contents of `template/default` of the generator).

---
It might be that this is expected behaviour atm and this is actually a feature request.

**Comment by Akryum** [comment]
Your `api.render` call must be put in the main code, not in the `api.onCreateComplete` hook. Take a look at [vue-cli-plugin-apollo](https://github.com/Akryum/vue-cli-plugin-apollo/blob/master/generator/index.js).

**Comment by andreasvirkus** [comment]
Oof, embarrassing. That was it. Sorry and thanks @Akryum !
