### ISSUE TITLE
Nightwatch E2E tests fail with an extract-text-webpack-plugin error when importing styles in a DLL

### ISSUE THREAD

**Issue by davidwallacejackson** [vuejs/vue-cli#1126]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/davidwallacejackson/vue-cli-css-import-repro](https://github.com/davidwallacejackson/vue-cli-css-import-repro)

### Steps to reproduce
1. `npm install`
2. `npx vue-cli-service e2e`

### What is expected?
The automatically-generated E2E tests should pass.

### What is actually happening?
The E2E tests time out. In the browser console, there's an error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

---
vue.config.js is configured to prebuild '@/module-importing-css' into a DLL, which is then referenced from main when it imports './module-importing-css'. If you comment out that line in the config, the tests run correctly.

There's another issue about people encountering this same error (https://github.com/vuejs/vue-cli/issues/997) but the context seems very different (they're using Windows and they're not running e2e tests), so I wasn't sure the error was actually caused by the same bug in both cases.

**Comment by yyx990803** [comment]
Closing as we will be removing the DLL option.

**Comment by davidwallacejackson** [comment]
Fair enough. Could I ask why you're removing it? It was a big help for my project, though it wouldn't be the end of the world to set the plugin up manually.
