### ISSUE TITLE
add deployment instructions

### ISSUE THREAD

**Issue by WillowHQ** [vuejs/vue-cli#1127]
### What problem does this feature solve?
The docs should include instructions for how to deploy to an express instance, or Heroku, GCS, or another common IAAS. 

### What does the proposed API look like?
This would be additional content on the README.md

**Comment by LinusBorg** [comment]
`build` produces an HTML file and a bunch of folders with javascriptl, css and images.

You deploy it the same way as any other javascript fronend code: upload it to the server, serve it with your web server.

I think this is out of the scope of Vue, since it's not specific to Vue or vue-cli.

**Comment by Akryum** [comment]
Also, anyone can write a  vue-cli plugin to deploy apps into any service.

**Comment by WillowHQ** [comment]
Ok, I actually think it is in scope. As a person coming from react to vue, I quickly searched the react CRA docs and was told exactly how to deploy the app on many cloud services. Not so in Vue. Just because something is obvious to an experienced user doesn't mean that there isn't value in creating documentation to make adoption easier for a new user.

**Comment by chrisvfritz** [comment]
That sounds like a terrific plan to me!

**Comment by multiplegeorges** [comment]
This sounds like the way to go.

I have a `yarn deploy` task that syncs to an S3 bucket for really quick and easy deployment. I'd be happy to add this to a deployment cookbook.

**Comment by Akryum** [comment]
@multiplegeorges Or maybe do a vue-cli plugin to do this with a single command? 😸

**Comment by WillowHQ** [comment]
I use Express instances, as well as firebase hosting and google cloud functions to serve bundles. I can add those recipes to the cookbook.

**Comment by sdras** [comment]
I love this idea! Sounds like you're already thinking this way but I really like how Nuxt does it with a little deployment section and runs through a few common use cases. And yes, of course something more particular could be cookbook. Solid plan everyone, thanks for bringing it up @WillowHQ and follow through @LinusBorg

**Comment by piotrb** [comment]
I'd like to know best practices for deploying this to a service like Heroku without having to manually bake in the env configs for the different environments, ie Staging vs Prod.

I've done this in the past by having an express endpoint that would expose specific env variables (in this case it'd be VUE_APP_* as per the convention), and then load them from the server at app start. Doing deploys to different environments with the same codebase is a bit tricky otherwise, since if the built code needs to be changed between environments you're not actually testing the same version each time.

**Comment by WillowHQ** [comment]
@piotrb that is not related to vue-cli. I would google best practices for deployment and environmental variables maybe ?

**Comment by yyx990803** [comment]
Basic deployment tips are in - and platform guides are open to contributions: https://github.com/vuejs/vue-cli/blob/dev/docs/guide/deployment.md
