### ISSUE TITLE
希望增加对 FIS3 的支持

### ISSUE THREAD

**Issue by charleslo1** [vuejs/vue-cli#113]
您好，FIS 是百度Fex团队出品的一款优秀的前端集成构建工具，在国内也算有较多的用户。希望 Vue 对 FIS 也能有相关的插件或工具支持

例如
- 开发 vue 组件编译插件 fis3-parser-vue
- vue-cli 生成 fis 脚手架项目 vue init fis my-project

**Comment by yyx990803** [comment]
https://github.com/okoala/fis3-vue
