### ISSUE TITLE
Bug with Safari

### ISSUE THREAD

**Issue by shammelburg** [vuejs/vue-cli#1132]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/shammelburg/vue-cli-test](https://github.com/shammelburg/vue-cli-test)

### Steps to reproduce
Once you've cloned the project,
1. npm run serve
2. Go to Input.vue 
3. add another input in the template 
4. save (this will show on hot reload)
5. refresh the browser manually (the input is gone)
6. return to the code and save the file again (input appears)

### What is expected?
When I refresh the browser the app needs to give me the latest build from when I saved the changes.

### What is actually happening?
When making changes to a .vue file, eg. changing an input in the template, 

the browser updates initially but when you refresh the browser manually it seems to return to first time you run 'npm run serve'.

When starting and stopping the app through terminal the app runs ok.

A similar things happens when changing property names.

---
I've ran this on Chrome and it works fine.

I'm running this on my Mac.

**Comment by zigomir** [comment]
So weird. It doesn't have to do anything with input, it behaves same for anything you change. Hot reload works, but after refresh you get old contents. I figured if I refresh http://localhost:8080/app.js in another tab I get latest bundle served and manual refresh works again. But not always 🌘 Even [disabling cache (see Safari 11.1 below)](https://stackoverflow.com/questions/46324675/how-do-i-disable-cache-in-safari-11-0) won't help :/ 

It looks like Safari 11.1 caching issue to me. My wild guess would be they introduced regressions with implementing [service workers](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_11_1.html). 👹

**Comment by daniele-orlando** [comment]
I'm facing the same bug.
*Vue-Cli* _3.0.0-beta.6_
*Safari* _11.1_

It is such a problem that I can't use Safari to develop with Vue anymore.

**Comment by yyx990803** [comment]
This is definitely a bug in Safari itself...

**Comment by yyyc514** [comment]
FYI: Confirming issue with Safari 11.1.2.  Also Safari Tech Preview Release 60 (Safari 12.0, WebKit 13606.1.23.1).

Works fine in Chrome.

**Comment by Twinpix** [comment]
I was facing the same annoying bug with Safari (both desktop and mobile), and since "app.js" was not updated , I had to add this code in "vue.config.js" to make it work.

module.exports = {
  chainWebpack: config => {
    config
      .mode('development')
      .output
      .filename('[name].[hash].js') 
}

**Comment by lmuzquiz** [comment]
Same issue here using safari 13.0.4 on Mac OS Catalina 10.15.2

**Comment by iandk** [comment]
Same issue

**Comment by patricklewis** [comment]
Same issue here, Safari 13.0.4 on macOS 10.15.2 and Safari hot-reloads correctly on file changes but then reverts back to an older version of the site upon a refresh.

**Comment by rskvazh** [comment]
Same issue with Safari 13.1 (and older too) and `vue serve`. "Hot reload" reloads code successfully, but when I refresh page (Cmd+R) - old result loading unless I close the tab and open this same URL. In Network tab caching is off.

**Comment by chrisbartow** [comment]
First day using Vue and ran into this issue with Safari 13.1.1 trying to update the Hello World project and nothing changes.

**Comment by adarshsrivastava11** [comment]
> Same issue with Safari 13.1 (and older too) and `vue serve`. "Hot reload" reloads code successfully, but when I refresh page (Cmd+R) - old result loading unless I close the tab and open this same URL. In Network tab caching is off.

@rskvazh @chrisbartow  It is not a bug, Safari caching engine works differently and is currently in not in sync with how vue-loader works, so it'll always cache the first version and keep it persistent. You can change this behaviour in the developers tools. But I'd advices to use chrome or use Safari's incognito mode.

**Comment by cvn** [comment]
This is still an issue as of Safari 14.0.1 and vue-cli 4.5.9.

I filed a WebKit bug report https://bugs.webkit.org/show_bug.cgi?id=219323.

In the meantime, I clear the cache before each reload. 

1. Clear the cache with: <kbd>⌘ Command</kbd> + <kbd>⌥ Option</kbd> + <kbd>E</kbd>  
2. Refresh the page:  <kbd>⌘ Command</kbd> + <kbd>R</kbd>

Thanks to @bfanger for [this tip](https://stackoverflow.com/a/60017146/490592).

P.S. @Twinpix's [workaround](#issuecomment-409916879) is an alternative to clearing the cache before every reload, but apparently it [can cause a memory leak](https://github.com/webpack/webpack-dev-server/issues/377#issuecomment-241258405). Adding the hash to the query string instead of the file name is another option, but can cause issues with some webpack loaders. See commits 33dad39, 52dbdf8, and 0909bc8.

**Comment by panderson1000** [comment]
Unfortunately this is making me think twice about using Vue.  Just rebuilt my site with VueJS 3 and after deployment discovered Safari is choking.  desktop Chrome OK, mobile Chrome OK, mobile Safari OK, desktop Safari NOPE!  See alot of timeouts BUT ONLY on Safari.

**Comment by cvn** [comment]
@panderson1000 This bug is limited to an issue with local development using vue-cli. It does not affect deployed code. Perhaps you can post on the vue forum https://forum.vuejs.org with your issue.

**Comment by FakieKickflip** [comment]
First day with vue and still got this error with safari version 14.0.3. Kinda annoying to clear the cache before reload.

**Comment by herrernst** [comment]
@FakieKickflip You should better report this bug to Apple and insist on fixing it as this [is a problem with Safari](https://github.com/vuejs/vue-cli/issues/1132#issuecomment-384857935) and not with Vue CLI.

**Comment by dele-corporate** [comment]
I believe this is not a problem in safari, I developed several applications that use webpack and run normally.

maybe vue doesn't fully support safari by default.

this comment is at least helpful https://github.com/vuejs/vue-cli/issues/1132#issuecomment-409916879

**Comment by crypthonics** [comment]
This issue still persists on v14.1. Since this is caching related, I don't think it will ever get "fixed" because of different caching methods of Safari, so there is nothing to fix from Safari's side. Emptying the caches and reloading works, but since the deployed code doesn't cause problems, I would suggest to use another browser for active development and just do a final check with Safari when the developed feature is finished.

**Comment by talmobi** [comment]
Still an issue.

Clearing cache does NOT necessarily fix this issue. As crazy as that sounds. I think it may possibly be Service Worker related and here's what's happening.

Even destroying the development/localhost tab and creating a new one may not necessarily work. The first page you get served might be the correct updated one. But after you interact with the page or trigger a hot reload update, the page will REVERT BACK to an old version. This is crazy behaviour. I'm not exactly sure why or how but it smells like Service Worker related to me.

Things that will not work:
- restarting web pack dev server
- clearing cache on Safari
- destroying the localhost tab and opening a new one

The above may work temporarily, but if you interact or issue a HMR update after loading, the page CAN REVERT BACK to an older version.

I found this out after having a `console.log` on a `mounted` on a component. And after having removed the console.log from the code. The old console.log message would appear from time to time (including old behaviour) even after all the above things. Restarting dev server, clearing cache, opening a new tab.

On Chrome at the same time everything was working fine, I was served the most updated version.

I'm not exactly sure what's going on but seems like possibly Service Worker related?

Safari Version 14.0.3 (16610.4.3.1.7)
Chrome Version 91.0.4472.77 (Official Build) (arm64)
OSX 11.2.3 (20D91)
MacBook Pro (13-inch, M1, 2020), M1, 16GB

node v14.16.0
npm 6.14.11
yarn 1.22.10

vue 2
@vue/cli-service 4.4.6

**Comment by rx2347** [comment]
Same thing on Safari 14.1 (15611.1.21.161.7, 15611) on Catalina 10.15.7

Quite annoying.

**Comment by nuvallo** [comment]
I am having the same issue with my m1 8g Macbook Pro. If I clear the cache I will see my new changes but pretty annoying to have to keep clearing the cache for each save or change.

**Comment by bfanger** [comment]
There is nothing the **vue-cli** team can do, it's a bug in Safari:  https://bugs.webkit.org/show_bug.cgi?id=219323
[Even adding a `Cache-Control: no-store, max-age=0 `](https://stackoverflow.com/questions/33374048/caching-issue-with-webpack-dev-server) to the response has **no effect** and the result is still cached (Safari 14.1.1)

It's sad, but Safari simply doesn't comply with [the http spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) and also disregards the disable-cache devtool setting.

Instead of commenting in this thread, report the issue in channels that are read by the Safari browser developers/dev-advocates.

**Comment by talmobi** [comment]
@bfanger Why does this only happen with Vue on Safari? And not with any other devtool?

**Comment by greenuns** [comment]
i have the same issue. I thought my css wasn't working on mobile only to find out it's a vue bug.
For me it's on iPhone and iPad Safari AND Chrome.
The only way to get it work is to not refresh at all and by any chance I refreshed, I would need to close the tab and reopen.

@vue/cli 4.5.13
iOS version: 14.6
iOS Safari version: assuming Safari 14
iOS Chrome version: 91.0.4472.80

**Comment by andrecp** [comment]
+1, it's a quite frustrating first user experience with the project.

**Comment by D1kz** [comment]
+1
still having this issue with Safari 14.1.2

**Comment by agileben** [comment]
Yeah ran into this today with Safari 14.1.2 (16611.3.10.1.3)

**Comment by heelercs** [comment]
Same issue, I'm on Safari 14.1.1

**Comment by musakanneh** [comment]
> I was facing the same annoying bug with Safari (both desktop and mobile), and since "app.js" was not updated , I had to add this code in "vue.config.js" to make it work.
> 
> ```js
> module.exports = {
>   chainWebpack: config => {
>     if (process.env.NODE_ENV === 'development') {
>       config
>         .output
>         .filename('[name].[hash].js') 
>         .end() 
>     }  
>   }
> }
> ```

Thanks for this, mate/

**Comment by cvn** [comment]
Hi, @speg. They already tried it and ran into issues, so they reverted it. See my comment above https://github.com/vuejs/vue-cli/issues/1132#issuecomment-735185087 for a list of commits if you're curious about the details.

**Comment by evvvritt** [comment]
[This comment's config](https://github.com/vuejs/vue-cli/issues/1132#issuecomment-409916879) was no longer working for me so I added `chunkFilenames` hashing and seems to be busting properly now in Safari 15.4
```js
chainWebpack: config => {
    if (process.env.NODE_ENV === 'development') {
      config
        .output
        .filename('[name].[hash].js')
        .chunkFilename('[name].[hash].js')
        .end()
    }
},
 ```

**Comment by jared201** [comment]
> [This comment's config](https://github.com/vuejs/vue-cli/issues/1132#issuecomment-409916879) was no longer working for me so I added `chunkFilenames` hashing and seems to be busting properly now in Safari 15.4
> 
> ```js
> chainWebpack: config => {
>     if (process.env.NODE_ENV === 'development') {
>       config
>         .output
>         .filename('[name].[hash].js')
>         .chunkFilename('[name].[hash].js')
>         .end()
>     }
> },
> ```

This fixed my problem today
