### ISSUE TITLE
webpack-simple build issue (npm run dev)

### ISSUE THREAD

**Issue by thesheepman** [vuejs/vue-cli#1141]
### Version
2.9.3

### Reproduction link
[http://localhost:8080/](http://localhost:8080/)

### Steps to reproduce
I used to run theese commands:
npm install --global vue-cli
vue init webpack-simple cryptoportfolio
cd cryptoportfolio
npm run dev

### What is expected?
Just run default test build

### What is actually happening?
ERROR in ./src/App.vue
Module not found: Error: Can't resolve '../../../..' in 'D:\!work\Vue\cryptoportfolio\src'
 @ ./src/App.vue 4:2-368
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

ERROR in ./src/App.vue
Module not found: Error: Can't resolve '../../../..' in 'D:\!work\Vue\cryptoportfolio\src'
 @ ./src/App.vue 6:25-122
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

ERROR in ./src/App.vue
Module not found: Error: Can't resolve '../../../..' in 'D:\!work\Vue\cryptoportfolio\src'
 @ ./src/App.vue 8:0-173 9:0-186
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

ERROR in ./src/App.vue
Module not found: Error: Can't resolve '../../../..' in 'D:\!work\Vue\cryptoportfolio\src'
 @ ./src/App.vue 11:0-345
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

ERROR in multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js
Module not found: Error: Can't resolve 'D:\' in 'D:\!work\Vue\cryptoportfolio'
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by LinusBorg** [comment]
Please post bug reports for individual templates in their respective repository. You should find a link to that repository in you generated project's README.md
