### ISSUE TITLE
vue serve MyComponent.vue refuses to work

### ISSUE THREAD

**Issue by MrSunshyne** [vuejs/vue-cli#1142]
### Version
3.0.0-beta.6

### Reproduction link
[https://codesandbox.io/s/61owyl467w](https://codesandbox.io/s/61owyl467w)

### Steps to reproduce
1. Create the simplest vue file ever. `<template><div>hello</div></template>`
2. Save to `MyComponent.vue`
3. Run `vue serve MyComponent.vue`
 

### What is expected?
A zero config simple vue app running in on localhost:8080

### What is actually happening?
I get this output in the terminal 
```
 ERROR  Failed to compile with 1 errors                                                      9:41:18 PM

 error  in ./MyComponent.vue?vue&type=template&id=1754c3f3

Module parse failed: Unexpected token (2:0)
You may need an appropriate loader to handle this file type.
|
| <div>hello</div>
```

Screenshot: https://i.imgur.com/vmDbNzp.jpg

---
I thought this was a bug with npm/yarn. 

I was able to run it on the same machine previously.

I tried :
Reinstalling @vue/cli & @vue/cli-service-global
Reinstalled nodejs itself

System : macOS High Sierra
vue-clie version: 3.0.0-beta.6

`vue build MyComponent.vue` works fine

**Comment by LinusBorg** [comment]
Did you do this in an empty directory, or did that content contain a `node_modules` folder?

I may be wrong, but this syntax looks like vue-loader 15-beta:

`/MyComponent.vue?vue&type=template&id=1754c3f3`

...which isn't used in vue-cli yet (will be when 3.0.0 is released). So it crossed my mind you might have it installed as a dependency somewhere.

**Comment by MrSunshyne** [comment]
@LinusBorg Yes it was an empty directory. I also tried new directories at different locations on the machine... 

> I may be wrong, but this syntax looks like vue-loader 15-beta:
This might be the closest i've come to any clue to what's going on. 
What might I do to reverse this?

**Comment by LinusBorg** [comment]
Try npm uninstall -g vue-loader 

Also check that there's no node_modules folder in your projects parent directory path which may contain this loader.

**Comment by MrSunshyne** [comment]
I tried uninstalling..
```
npm uninstall -g vue-loader
up to date in 0.04s
```

I guess it wasn't installed. 

I tried to create a new .vue file in the home directory, i get the same error..


` $ ~/test echo "<template><div>hola</div></template>" > App.vue`

` $ ~/test ls`
App.vue

` $ ~/test vue serve App.vue`

 INFO  Starting development server...
 94% asset optimization

 ERROR  Failed to compile with 1 errors                                                      2:06:48 AM

 error  in ./App.vue?vue&type=template&id=472cff63

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <div>hola</div>

 @ ./App.vue 1:0-81
 @ ../.config/yarn/global/node_modules/@vue/cli-service-global/template/main.js
 @ multi ../.config/yarn/global/node_modules/webpack-dev-server/client/index.js ../.config/yarn/global/node_modules/webpack/hot/dev-server.js ../.config/yarn/global/node_modules/@vue/cli-service-global/template/main.js

Any other ideas?

**Comment by MrSunshyne** [comment]
I logged in as another User on macOS, it works there. I didn't have to reinstall yarn or vue-cli. It was available, and `vue serve` ran as expected.. 

The error still persists in my main dev environment though..

**Comment by MrSunshyne** [comment]
there was a rogue `node_modules` folder in my home directory. Deleting that fixed it. 

Damn it. 5hours on that. Guess i'll laugh it off -____- 

Thanks for the tip @LinusBorg

**Comment by akshaybharambe14** [comment]
for me, reinstalling babel and webpack fixed this issue.

npm install babel-core babel-loader babel-preset-es2015 webpack --save-devnpm install babel-core babel-loader babel-preset-es2015 webpack --save-dev
