### ISSUE TITLE
Add option to bundle as a consumable component library instead of web app

### ISSUE THREAD

**Issue by Rleahy22** [vuejs/vue-cli#1143]
### What problem does this feature solve?
vue-cli currently assumes any usage is for a web application, but it does not allow for bundling a library of individual components that can be consumed by other applications.

### What does the proposed API look like?
`vue create {app}`

What is your intended project type?
 - Web Application
 - Component Library
 - Plugin
 - etc.

**Comment by LinusBorg** [comment]
> vue-cli currently assumes any usage is for a web application

No it does not. Please read this chapter of the documentation:

https://github.com/vuejs/vue-cli/blob/dev/docs/build-targets.md

**Comment by Rleahy22** [comment]
That's exactly what I needed. Sorry about that.

**Comment by bivainis** [comment]
Looks like docs directory structure changed, here's the working link to `build-targets.md`: https://github.com/vuejs/vue-cli/blob/dev/docs/guide/build-targets.md
