### ISSUE TITLE
Need a clean way to load custom plugins during generation

### ISSUE THREAD

**Issue by light24bulbs** [vuejs/vue-cli#1145]
### What problem does this feature solve?
It's not clear from the documentation how to create a custom template for generating new Vue Projects. The documentation has a bit around extending existing applications, but even that is unclear.  What is lacking here is an example or wholistic explanation that shows the pieces working together.  
https://github.com/vuejs/vue-cli/blob/dev/docs/plugin-dev.md#generator
### What does the proposed API look like?
I'd like to see an example of a generator that makes a Vue app, with an explanation of how to run it and how it fits into the existing CLI

**Comment by light24bulbs** [comment]
Looks like the plugin name MUST start with vue-cli-plugin-NAME or it will not be a valid plugin.  I don't see that mentioned in the documentation, had to read the source. 

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-shared-utils/lib/pluginResolution.js

Is there a way to register global plugins so that they will be available at new project generation?

**Comment by andreasvirkus** [comment]
The service provides you with a core Vue App and your plugins can modify it. Search GitHub or npm for examples with `vue-cli-plugin-` (apollo, vuetify, express, docker, etc.)

To have a plugin generator run "at create time", it has to be in your custom preset, which you can then define when running vue create:
```
vue create --preset username/repo my-project
```
See more in the [docs](https://github.com/vuejs/vue-cli/blob/dev/docs/cli.md#presets)

As to the last comment, there's a guide on [plugin development](https://github.com/vuejs/vue-cli/blob/dev/docs/plugin-dev.md) and the `vue-cli-plugin` prefix is covered under [CLI#installing-plugins-in-an-existing-project](https://github.com/vuejs/vue-cli/blob/dev/docs/cli.md#installing-plugins-in-an-existing-project).

**Comment by light24bulbs** [comment]
That does seem to work, thank you!  That's the same conclusion I came to.  I have resorted to writing my configuration to the user's ~/.vuerc and then invoking it from there.  

You can see that the apollo install guide is just a bit roundabout, as you must first generate, add the plugin, and then call its generators again.  

As far as I can tell, this also makes local development difficult plugins that run during create time, because vue automatically tries to install the plugin from remote, rather than checking for global installs that can be `npm link`ed.  

How would you feel about a PR that checks for plugins starting with `vue-cli-plugin-` in global?  Your code looks very clean and straightforward, should be simple to add.

**Comment by yyx990803** [comment]
FYI the docs **will** be incomplete during the beta phase. We will polish the docs extensively when we are ready for RC, but for now, refer to what @andreasvirkus has explained :)
