### ISSUE TITLE
users configuration guide

### ISSUE THREAD

**Issue by zhangyuhan2016** [vuejs/vue-cli#1148]
### What problem does this feature solve?
Hi,As far as I know,
some new users can't find the configuration method,
recommended in vue.config.js or package.json  add configuration link (https://github.com/vuejs/vue-cli/tree/dev/docs),
which may help new users
thanks

### What does the proposed API look like?
Hi,As far as I know,
some new users can't find the configuration method,
recommended in vue.config.js or package.json  add configuration link (https://github.com/vuejs/vue-cli/tree/dev/docs),
which may help new users
thanks

**Comment by yyx990803** [comment]
This is still beta phase, expect docs to be improved in the future.
