### ISSUE TITLE
best way to add own "npm deploy"

### ISSUE THREAD

**Issue by focussing** [vuejs/vue-cli#1149]
### What problem does this feature solve?
In vue-cli 2 environment I would use the following;

    "scripts": {
        "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
        "start": "npm run dev",
        "build": "node build/build.js",
        "deploy": "node build/deploy.js"
    },

Next I would enter "npm deploy" in terminal to deploy the dist folder contents to my webspace.

What would be the preferred way of doing such a thing in vue-cli 3?

### What does the proposed API look like?
The same or something similar

**Comment by LinusBorg** [comment]
> What would be the preferred way of doing such a thing in vue-cli 3?

Provided nobody has yet written a vue-cli plugin for your deployment method of choise:

Exactly the same as before.
