### ISSUE TITLE
hope support react  tsx

### ISSUE THREAD

**Issue by lusess123** [vuejs/vue-cli#1151]
### What problem does this feature solve?
@ vue-cli-service  在黑盒化webpack 方面做得相当不错了，相比起Parcle 有很对优势

  

1. 有时候要利用react生态上的组件互补，会在页面局部使用　react  

2. 在有些不在意js包大小的后台管理系统里面， 共存 react 与vue 页面，

 如果能共用一个打包工具就好了。@ vue-cli-service 能否也支持react开发呢，

### What does the proposed API look like?

1.  需要能支持react 编译， 最好也能支持　typescript 的tsx

2.  在目前的版本中 我应该在vue.config.js 怎么改造才可以做到

**Comment by yyx990803** [comment]
Sorry but no.

**Comment by lusess123** [comment]
@yyx990803  如果我要自己实现这种第三方插件，能否给点思路 ，万分感谢

**Comment by yyx990803** [comment]
先看文档...

**Comment by lusess123** [comment]
@yyx990803   原来支持react 的 tsx 跟 vue-cli 没有关系，只要修改tsconfig.json 的 jsx配置就可以了。
感谢尤大，vue-cli 做的实在好， 在 typescript + react 领域， 可以很好的替代webpack ， 在某些细节甚至比 antd 的 umi , afwebpack 做的更好
