### ISSUE TITLE
Inferring of Typescript version is not accurate and throws error

### ISSUE THREAD

**Issue by atilkan** [vuejs/vue-cli#1152]
### Version
3.0.0-beta.6

### Reproduction link
[https://jsfiddle.net/atilkan/htk8cu8e/1/](https://jsfiddle.net/atilkan/htk8cu8e/1/)

### Steps to reproduce
Typescript option selected is enough to produce. Screenshot says all.

### What is expected?
Infer the correct ts version, might

### What is actually happening?
Infer the correct ts version, might

![screen shot 2018-04-19 at 18 50 39](https://user-images.githubusercontent.com/1254613/39003266-2f014338-4403-11e8-9b31-02c614b2591b.png)

**Comment by LinusBorg** [comment]
Your global typescript version may be 2.7.1, but vue-cli installs the latest stable. 

You can ignore the warning insides as there don't seem to be any incompatibilities even though 2.8 is not officially supported. 

Alternatively, feel free to use 2.7 instead.
