### ISSUE TITLE
lintOnSave true throws error

### ISSUE THREAD

**Issue by atilkan** [vuejs/vue-cli#1154]
### Version
3.0.0-beta.6

### Reproduction link
[https://jsfiddle.net/atilkan/htk8cu8e/](https://jsfiddle.net/atilkan/htk8cu8e/)

### Steps to reproduce
I just created the project and if i change lintOnSave option to true it detect parsing errors on SPC files. There are no errors actually. I did not even touch them. Screenshot.

### What is expected?
Parsing it correct, might.

### What is actually happening?
Doesn't parse
![screen shot 2018-04-19 at 20 34 13](https://user-images.githubusercontent.com/1254613/39008364-2cfecb38-4411-11e8-9391-40f11f37ea46.png)

**Comment by LinusBorg** [comment]
Please provide a reproduction.

> I just created the project 

the LCI ha many options, which ones did you choose? What system are you running on? node&/npm version?

We can't analyse your problem from a screenshot.

**Comment by atilkan** [comment]
I don't know how to share starter template but i will try to write here.
Mac OS
Node / Yarn
**Vue create app** 

- Typescript, Router, Vuex, CSS Pre-processors, Unit Testing
- Use Class Style Component - yes
- Use Babel alongside TypeScript for auto-detected polyfills? - yes
- SCSS / SASS
- ESLint-Prettier
- Lint On Save 
- Jest

**Comment by yyx990803** [comment]
Can't reproduce. Please provide an actual repo.
