### ISSUE TITLE
Prevent `vue inspect` from outputting "omitted long function"

### ISSUE THREAD

**Issue by Dragas** [vuejs/vue-cli#1157]
### What problem does this feature solve?
I've come to an issue where I need to modify the default vue CLI webpack configuration and while trying to output it I found out that key parts (mainly transformers) are omitted for no reason at all. This can be clearly seen on lines 30-32 of `@vue/cli-service/lib/commands/inspect.js` as the following is defined:
```
      if (typeof value === 'function' && value.toString().length > 100) {
        return `function () { /!* omitted long function *!/ }`
      }
```

### What does the proposed API look like?
An additional modifier (for example `-v` for `--verbose`) would do.

**Comment by Dragas** [comment]
The readability is barely improved, considering its already suggested to
output the result to a file.

**Comment by bhouse1273** [comment]
Why not make the hard-coded 100 a config item?  0 for the equivalent of --verbose, 100 default.  That would allow control of the allowable output function size, filtering out the really long functions, but still outputting the not-so-long ones.
