### ISSUE TITLE
hotload is very slow

### ISSUE THREAD

**Issue by luxueyan** [vuejs/vue-cli#1159]
### Version
3.0.0-beta.6

### Steps to reproduce
I used the vue-cli create a new project, but don't know why the hotload is so slow. It may be due to the webpack! But why webpack3 is slower then webpack2 ? How fix it please?

### What is expected?
Hotload is more quick

### What is actually happening?
Hotload is so slow

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

HMR is quite fast but can get slower with large project, this is however normal
