### ISSUE TITLE
Deploys locally, fails to load CSS/JS on heroku due to MIME text/html

### ISSUE THREAD

**Issue by sethdorris** [vuejs/vue-cli#1160]
### Version
3.0.0-beta.6

### Reproduction link
[https://airborne17th.herokuapp.com/](https://airborne17th.herokuapp.com/)

### Steps to reproduce
The bug does not happen locally, but only when pushing the build to heroku.. can someone tell me why the build generated .css and .js files are MIME type text/html and not text/css and text/js?

### What is expected?
I expect the deployment to heroku to be the same as the local version

### What is actually happening?
heroku not loading CSS/JS as mime types are text/html

**Comment by LinusBorg** [comment]
The build result are plain files. 

Mime types are defined by the server / heroku, and consequently have nothing to do with vue-cli.
