### ISSUE TITLE
403 Blacklisted

### ISSUE THREAD

**Issue by niallobrien** [vuejs/vue-cli#1165]
### Version
3.0.0-beta.6

### Reproduction link
[https://gist.github.com/niallobrien/b5daa538b3c9366103d69378a8c277da](https://gist.github.com/niallobrien/b5daa538b3c9366103d69378a8c277da)

### Steps to reproduce
Running `npm install --global vue-cli` on Windows 7, node.js v9.8.0, npm 5.6.0.

### What is expected?
That the Vue CLI tool will be installed.

### What is actually happening?
I am receiving the below errors in my console and the CLI fails to install:

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! code E403
npm ERR! 403 Blacklisted: absolute@0.0.1

**Comment by dhensche** [comment]
Just a note, running `npm install --global vue-cli` will not install a 3.x version of `vue-cli`. The package has been moved to `@vue/cli`

**Comment by yyx990803** [comment]
Not sure why, but cannot reproduce on a fresh 2.x install. This likely has something to do with your network...

**Comment by niallobrien** [comment]
@yyx990803 Yes, This appears to be a problem with McAfee Web Gateway incorrectly reporting `absolute` as a malicious module (malware). I've reported this issue on the `absolute` repo.

Thanks in advance.
