### ISSUE TITLE
Multi target builds

### ISSUE THREAD

**Issue by ThomasKlessen** [vuejs/vue-cli#1169]
### What problem does this feature solve?
Right now i can use quasar to create one app and deploy it to multiple targets (SPA, PWA, Electron, Cordova) or use the different templates of vuetify for that purpose. Both solutions have in common that they lack the possibilities of a "living" build tool like vue-cli.

In my opinion (that likely is false) the "deploy to targets" should be included in vue-cli as an option.

Of course i would work on that by my own with your input and help.
But first i need your feedback for that proposal.

thx

### What does the proposed API look like?
I think of a additional question like:

#Targets?
- [ ] SPA
- [ ] PWA
- [ ] Cordova - iOS
- [ ] Cordova - Android
- [ ] Electron

**Comment by LinusBorg** [comment]
* We already have PWA as an option in `vue-create`
* The other mentioned targets are far too complex to include them by default. The community can write and publish plugins for them, that'S why we have the Plugin system.

**Comment by ThomasKlessen** [comment]
Okay. I will take a look there.
