### ISSUE TITLE
[Question] How add my a template to Organization vuejs-templates ?

### ISSUE THREAD

**Issue by danielschmitz** [vuejs/vue-cli#117]
Hi, 

can't find this answer in docs... 

How i send my template:

https://github.com/danielschmitz/browserify-complete

to organization   vuejs-templates ?

thanks!

**Comment by chrisvfritz** [comment]
vuejs-templates is reserved for officially maintained templates and while we might later decide to add a template like this in the future, we probably won't until after the dust settles from the coming 2.0 release. In the meantime, we'd love to have your template on [the vue-awesome repo](https://github.com/vuejs/awesome-vue) if you want to submit a PR. 😄
