### ISSUE TITLE
cli-plugin-unit-mocha leaks between tests through jsdom (was: --watch caches too much?)

### ISSUE THREAD

**Issue by doppelreim** [vuejs/vue-cli#1171]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/doppelreim/test-route-watch](https://github.com/doppelreim/test-route-watch)

### Steps to reproduce
`npm test -- --watch`

Observe the console output.

First run:
Both test-cases log an empty route-instance. That's cool.

Now, comment in line 20 in the spec-file (`routerMock.push`)
Save the file, the tests run again...

The first test-case logs an empty route in `created` => ok
The watcher on $route fires, and logs the old empty route and the new one with the queryparam => ok

The second test-case gets interesting.
The created hook logs a route-object with the queryparam => That's weird. I expected the test-cases to be independent from each other.

Now, comment out line 20 again.
Save the file, the tests run again.

Now it gets really weird...
Both test-cases log from their created hook a route-object with the queryparam.
Even though the code adding the queryparam was commented out.

I'm confused :/

### What is expected?
Test-cases should be independent of one another

### What is actually happening?
They seemingly aren't.

---
Not entirely sure, if `vue-cli` is the culprit here - but gotta start somewhere :)

Also, not sure if I am using vue et. al. correctly o:)

**Comment by doppelreim** [comment]
We are using `mocha`, not `jest`.
But yeah, same thought applies :)
I'll check out their docs...

**Comment by doppelreim** [comment]
Actually... the underlying issue seems to at least partly be independent of whether you use `--watch`.

If you comment in line 20 in the spec and then run `npm test`, then the second test-case still has the query-param.
From what I understand, that already shouldn't be the case.
(Sorry for not making the repro-repo more minimal in the first place)

**Comment by LinusBorg** [comment]
abstract mode is meant for environments that don't have a url bar, so to speak. As such, it doesn't try to change the window.location, but instead handles the "URL" internally - but the router behaves 100% like you would expect it to otherwise.

So it's a good choice for testing environments no matter what you do, since you never risk of leaking anything to thee global `window.location`

I kept this issue open though, since the issue that you ran into is not the only possible problem that the singleton jsdom could create.

**Comment by yyx990803** [comment]
In my opinion, unit tests should not have side effects. I'm closing as there is a workaround and it's not something we can fix.

**Comment by doppelreim** [comment]
Hi @yyx990803 thanks for chiming in :)

I am confused... I also think, unit tests should not have side-effects.
But currently they have - if you do not use the workaround described by Linus.
If this behaviour can not be fixed in code, then shouldn't at least the workaround be documented somewhere?
