### ISSUE TITLE
NODE_ENV is not accessible in vue.config.js

### ISSUE THREAD

**Issue by sanchitgn** [vuejs/vue-cli#1174]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/sanchitgn/chunk/blob/master/vue.config.js#L1](https://github.com/sanchitgn/chunk/blob/master/vue.config.js#L1)

### Steps to reproduce
1. Create new project (`vue create`)
2. Add `vue.config.js`
3. Log `process.env.NODE_ENV` in `vue.config.js`

### What is expected?
The environment (`development`/`production`) should be output

### What is actually happening?
The output is `undefined`

---
To modify webpack configuration (plugins, loaders, etc), it is necessary to know the node environment

**Comment by LinusBorg** [comment]
Duplicate of #959
