### ISSUE TITLE
vue create gets npm error cb() never called

### ISSUE THREAD

**Issue by mhldtna** [vuejs/vue-cli#1176]
### Version
3.0.0-beta.6

### Reproduction link
[https://codesandbox.io/s/xp4jyxvkxw](https://codesandbox.io/s/xp4jyxvkxw)

### Steps to reproduce
vue create FileManagementUI

after upgrading npm and node and vue to their latest-and-greatest

Used these options:

? Please pick a preset: Manually select features
? Check the features needed for your project: (Press <space> to select, <a> to toggle all, <i> to ? Check the features needed for your project: Router, Vuex, Linter
? Pick a linter / formatter config: Airbnb
? Pick additional lint features: (Press <space> to select, <a> to toggle all, <i> to invert select? Pick additional lint features: Lint on save
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No

### What is expected?
New project named "FileManagement"

### What is actually happening?
Vue CLI v3.0.0-beta.6
✨  Creating project in C:\SpecProOnline\FileManagementUI.
�  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MLINEHA\AppData\Roaming\npm-cache\_logs\2018-04-24T23_47_12_566Z-debug.log
 ERROR  command failed: npm install --loglevel error

---
Reproduces very reliably.

Using Windows 8.1.

**Comment by mhldtna** [comment]
Reference https://github.com/npm/npm/issues/20429 for a corresponding npm issue since it is not clear whether this is a vue-cli or npm bug.

**Comment by mhldtna** [comment]
Follow-up: I tried exactly the same vue create command, but just took the defaults.  All worked fine.  So then I did: "vue add vuex", and I got:
`�  Installing (at-sign)vue/cli-plugin-vuex...

npm ERR! code E404
npm ERR! 404 Not Found: @vue/cli-plugin-vuex@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MLINEHA\AppData\Roaming\npm-cache\_logs\2018-04-25T20_25_06_684Z-debug.log
 ERROR  command failed: npm install --loglevel error -D @vue/cli-plugin-vuex`

So I did "npm install (at-sign)vue/cli-plugin-vuex(at-sign)latest" -- and got a similar error.

Conclusion: I guess vue-cli 3 really is beta code and it's too soon to meet my needs.

**Comment by yyx990803** [comment]
`vue add` is only for CLI plugins. **There is no CLI plugin for Vuex.** Vuex is added as an option of the core CLI service.

**Comment by Akryum** [comment]
@yyx990803 Maybe we could have an option to add vue-router or vuex at a later time to adhere to the progressive nature of the framework?

**Comment by mhldtna** [comment]
So I wish I hadn't mentioned trying "vue add vuex" because it distracted from the original problem.  Please consider the original problem which was that "vue create" did not work when I specified the particular set of options that I requested.
