### ISSUE TITLE
 Adjacent JSX elements errors when configuring eslint to use standardjs

### ISSUE THREAD

**Issue by kaihendry** [vuejs/vue-cli#1178]
### Version
3.0.0-beta.6

### Reproduction link
[https://s.natalian.org/2018-04-26/jsx-lint.zip](https://s.natalian.org/2018-04-26/jsx-lint.zip)

### Steps to reproduce
curl -O https://s.natalian.org/2018-04-26/jsx-lint.zip
unzip jsx-lint.zip
npm i
npm run lint

### What is expected?
No linting errors on the default files.

### What is actually happening?
Weird JSX errors

---
3.0.0-beta.7

**Comment by yyx990803** [comment]
Please provide a repository instead of a zip file :/

**Comment by kaihendry** [comment]
https://s.natalian.org/2018-04-27/vue-1178.txt
https://github.com/kaihendry/vue-cli-1178
git@github.com:kaihendry/vue-cli-1178.git

Thanks!

**Comment by yyx990803** [comment]
Looks like you are using your own ESLint config instead of the built-in one. This is not something we are responsible for. FYI there is a built-in ESLint config for standard.

**Comment by kaihendry** [comment]
Sorry, I don't follow how I'm supposed to make the project use standardjs. I understood from reading:

https://github.com/vuejs/vue-cli/blob/dev/docs/README.md#eslint
https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-eslint

That I needed to create `.eslintrc` with `{ "extends": "standard" }`, i.e. I the way I think to make eslint use standardjs.

How do I activate this **built-in ESLint config for standard** ?

**Comment by yyx990803** [comment]
You had the options when creating the project.
