### ISSUE TITLE
更改favicon.icon不生效

### ISSUE THREAD

**Issue by xuxiaoxiao312** [vuejs/vue-cli#1181]
### Version
3.0.0-beta.6

### Reproduction link
[https://codepen.io/xuxiaoxiao312/pen/bMBepa](https://codepen.io/xuxiaoxiao312/pen/bMBepa)

### Steps to reproduce
在原文件结构基础上，将favicon.ico替换为自定义图标，并在index.html中引入
代码如下：
    `<link rel="shortcut icon" href="./favicon.ico">`
    `<title>测试</title>`

### What is expected?
网页图标换成修改过的图标

### What is actually happening?
图标仍然是默认vue图标

---
请问更换网页图标是否需要特殊配置？

**Comment by yyx990803** [comment]
Chrome 会缓存 icon，清缓存或者换 port 即可

**Comment by 1429880240** [comment]
@xuxiaoxiao312 解决了吗
