### ISSUE TITLE
CSS modules don't work when using JSX

### ISSUE THREAD

**Issue by Tam** [vuejs/vue-cli#1185]
### Version
3.0.0-beta.6

### Reproduction link
[https://codesandbox.io/s/lvx765zjq](https://codesandbox.io/s/lvx765zjq)

### Steps to reproduce
1. Create a Vue component file
2. Write your component script, including a render function using JSX
3. Write some moduled CSS
4. Use `this.$style` to bind your moduled class to a JSX element.

### What is expected?
The element should be styled according to the class.

### What is actually happening?
The class name is bound correctly (as far as I can tell), but it is not styled.

**Comment by posva** [comment]
It's `class` that you need to set to `$style.app}, not `id`
