### ISSUE TITLE
vue-cli · Template does not exist: vuejs-templates/webpack

### ISSUE THREAD

**Issue by hejtful** [vuejs/vue-cli#119]
Hi,

Command I used:
vue init webpack my-project

Error:
vue-cli · Template does not exist: vuejs-templates/webpack

Node version:
v4.4.6

Vue version:
2.1.0

**Comment by posva** [comment]
Works nicely on my machine. It looks as if the cli is unable to retrieve the information. Are you behind a proxy or something?

**Comment by hejtful** [comment]
Yes, I had a leftover proxy I forgot about. Sorry for time wasting, and thanks!
