### ISSUE TITLE
Typescript: IDE reports TS2307: Cannot find module error for Vue components imports

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/vue-cli#1198]
### Version
3.0.0-beta.9

### Reproduction link
[https://pastebin.com/N5A5uWGv](https://pastebin.com/N5A5uWGv)

### Steps to reproduce
- Install Vue with vue-cli,
- Choose Typescript support
- Open any file that imports *.vue files

### What is expected?
No errors are reported

### What is actually happening?
IDE reports TS2307: Cannot find module error for Vue components imports. Imports are higlighted in red.

---
I've already reported this error here: https://github.com/vuejs/vue-class-component/issues/219 because I thought that it is a `vue-class-component` issue, but it's not. It's a configuration issue.

Putting the following `vue-shim.d.ts` declaration file under my ./src directory solves the problem:

``` javascript
declare module "*.vue" {
    import Vue from "vue";
    export default Vue;
}
```

<img width="344" alt="vue-components-imports-ts" src="https://user-images.githubusercontent.com/533954/39417163-444bc0f2-4c4a-11e8-8810-a5c6a8c0ca89.png">

**Comment by weixiao-huang** [comment]
Even though I don't know the reason, but this error may be caused by the new version of `shims.d.ts`. The new version is below:
```typescript
import Vue, { VNode } from 'vue';

declare module '*.vue' {
  import Vue, { VNode } from 'vue';
  export default Vue;
}

declare global {
  namespace JSX {
    // tslint:disable no-empty-interface
    interface Element extends VNode {}
    // tslint:disable no-empty-interface
    interface ElementClass extends Vue {}
    interface IntrinsicElements {
      [elem: string]: any;
    }
  }
}
```

However, just change it to the old version (like beta-6.0)
```typescript
declare module '*.vue' {
  import Vue from 'vue';
  export default Vue;
}
```

You can resolve the modules

**Comment by yyx990803** [comment]
This is weird because the build actually works fine, it's only the IDEs complaining.

/cc @ktsn @HerringtonDarkholme any idea why importing Vue at the root level in `shims.d.ts` breaks the `*.vue` imports?

**Comment by HerringtonDarkholme** [comment]
>  the build actually works fine

ts-loader has special handling for Vue file which doesn't affect IDE.

The workaround is to **split `declare module` and `declare global` into two separate files.**

The first `declare module` is called ambient module, which is used to describe modules written in JavaScript.
The second `declare global` is called (external) module, which is a TypeScript specific module system designed before ES-module. Global types like `Array` and `JSX.Element` resides in this module type.

And finally it seems that TS cannot mix up two modules. So the error occurs.

**Comment by wujekbogdan** [comment]
@HerringtonDarkholme 

Thanks for the explanation. I knew that creating a separate file solves the problem (I found it by accident) but I didn't have the slightest idea why it helps.

**Comment by kubukoz** [comment]
Hey @yyx990803, is this published? I manually made the change from 51c8090 in my project, but the IDE still glows red, so I'd like to see if a newly generated project would work...

**Comment by ocoka** [comment]
Hello! How do you guys found that *Typescript* accepts glob pattern for modules name at all in *declare* expression? Just can`t find it in [Typescript specs](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md)
sorry for off topic, can't stop my curiosity !

**Comment by Rockolin** [comment]
When importing *. Vue files into your code, you need to write the. Vue suffix. The reason is that by default, TypeScript only recognizes *. TS files and does not recognize *. Vue files.That's how I solved it.
<img width="557" alt="Example-image" src="https://user-images.githubusercontent.com/24283212/60255934-397dad00-9903-11e9-9ccb-42c4418a39e2.png">

**Comment by WalkHard95107** [comment]
I also encountered the same problem, have you solved it?

**Comment by hawezo** [comment]
I also have this issue. Using Vue 2.6.10.

![](https://i.imgur.com/Z8fPKtS.gif)

**Comment by medeman** [comment]
This is happening when the `.vue` file extension is emitted from the import statement (i.e. `import MyComponent from '@/components/MyComponent'` instead of `import MyComponent from '@/components/MyComponent.vue'`). Haven't figured out how to make it work without the file extension.

**Comment by viT-1** [comment]
@medeman I am not using cli. Adding shim-vue.d.ts to the project & .vue extension to path not solved this problem for me =(
and setup vue-ts-plugin is not helped too =(

**Comment by viT-1** [comment]
And I forced to dance with .vue files because of unit testing (@vue/test-utils [can't mount](https://github.com/vuejs/vue-test-utils/issues/1319) vue-class-component (.ts files with string template)) =(
I use SystemJS & ES6 bundling & module resolving ([here](https://github.com/viT-1/systemjs-ts-es6-vue) my project).

**Comment by viT-1** [comment]
By the way is need to check that your ts code in component exported default.

**Comment by fyllepo** [comment]
Still an issue it seems!

**Comment by viT-1** [comment]
> And I forced to dance with .vue files only because of unit testing

For testing in jest I'm not need in .vue files. [Solved](https://github.com/vuejs/vue-test-utils/issues/1319#issuecomment-542273692).

**Comment by a-menshchikov** [comment]
I solved this issue by adding additional declarations in shim-vue.d.ts file (all my vue files are into spa/page and spa/components directories expect for App.vue):
```
declare module '*.vue' {
    import Vue from 'vue'
    // noinspection JSDuplicatedDeclaration
    export default Vue
}

declare module '@/spa/pages/*' {
    import Vue from 'vue'
    // noinspection JSDuplicatedDeclaration
    export default Vue
}

declare module '@/spa/components/*' {
    import Vue from 'vue'
    // noinspection JSDuplicatedDeclaration
    export default Vue
}
```

**Comment by sy97** [comment]
> This is happening when the `.vue` file extension is emitted from the import statement (i.e. `import MyComponent from '@/components/MyComponent'` instead of `import MyComponent from '@/components/MyComponent.vue'`). Haven't figured out how to make it work without the file extension.

life saver

**Comment by tinacious** [comment]
I was having this issue only in WebStorm and **not** in VSCode. It was not happening with the `build` nor `serve` commands either. I will leave my "solution" here in case anyone is in my boat and finds this thread, but this does not need to be addressed.

- toggle the WebStorm Vue plugin off and then on again
- quit WebStorm and reopen

Note: I did not implement any of the above-mentioned declaration stubs. Doing so actually broke the `serve` command. With my version of vue-cli, it appears as though similar stubs are already declared in the 2 above-mentioned declaration files.

vue-cli v3.4.1
WebStorm 2019.2.3

**Comment by crazyfree** [comment]
@a-menshchikov live savior 💯

**Comment by Danielg212** [comment]
This is because TypeScript does not resolve webpack aliases automatically.

For TS to resolve aliases, they should be added in tsconfig.json under compilerOptions.paths:

`{  
  "compilerOptions": {
   "paths": {
     "@/*": [
      "./*"
     ]
    }
  }
}`

credit: [https://stackoverflow.com/questions/54839057/vscode-showing-cannot-find-module-ts-error-for-vue-import-while-compiling-doe](url)

**Comment by yoonasy** [comment]
@Danielg212  thank u. resolve

When I have a shim file and still report an error

```
    "paths": {
+    "@/*": ["src/*"],
      "/@/*": ["src/*"],
      "/@/img/*": ["src/assets/img/*"],
...
```

resolve

**Comment by yoonasy** [comment]
> This is because TypeScript does not resolve webpack aliases automatically.
> 
> For TS to resolve aliases, they should be added in tsconfig.json under compilerOptions.paths:
> 
> `{ "compilerOptions": { "paths": { "@/*": [ "./*" ] } } }`
> 
> credit: [https://stackoverflow.com/questions/54839057/vscode-showing-cannot-find-module-ts-error-for-vue-import-while-compiling-doe](url)



> This is because TypeScript does not resolve webpack aliases automatically.
> 
> For TS to resolve aliases, they should be added in tsconfig.json under compilerOptions.paths:
> 
> `{ "compilerOptions": { "paths": { "@/*": [ "./*" ] } } }`
> 
> credit: [https://stackoverflow.com/questions/54839057/vscode-showing-cannot-find-module-ts-error-for-vue-import-while-compiling-doe](url)

@Danielg212  thank u. resolve

When I have a shim file and still report an error

```
    "paths": {
+    "@/*": ["src/*"],
      "/@/*": ["src/*"],
      "/@/img/*": ["src/assets/img/*"],
...
```

resolve

**Comment by hellothursday** [comment]
> This is happening when the `.vue` file extension is emitted from the import statement (i.e. `import MyComponent from '@/components/MyComponent'` instead of `import MyComponent from '@/components/MyComponent.vue'`). Haven't figured out how to make it work without the file extension.

It is expected behavior.  

See: https://github.com/vuejs/vue-cli/issues/5549#issuecomment-638850440

**Comment by kfiri** [comment]
> Still an issue it seems!
> 
> I added the following into `index.d.ts` in project root, works for now.
> 
> ```
> declare module '*.vue' {
>     import Vue from 'vue'
>     export default Vue
> }
> ```

Is there a reason not to use this in the index.d.ts instead?
```
declare module '*.vue' {
  const SFC: Vue.Component;
  export default SFC;
}
```
IIRC, Vue Single-File-Components export `Vue.Component` objects, not specifically `VueConstructor` (the type of Vue from `import Vue from 'vue'`).

**Comment by 57982593** [comment]
I restarted webstorem and this problem was solved. But I don’t know why

**Comment by GeorgioWan** [comment]
> I solved this issue by adding additional declarations in shim-vue.d.ts file (all my vue files are into spa/page and spa/components directories expect for App.vue):
> 
> ```
> declare module '*.vue' {
>     import Vue from 'vue'
>     // noinspection JSDuplicatedDeclaration
>     export default Vue
> }
> 
> declare module '@/spa/pages/*' {
>     import Vue from 'vue'
>     // noinspection JSDuplicatedDeclaration
>     export default Vue
> }
> 
> declare module '@/spa/components/*' {
>     import Vue from 'vue'
>     // noinspection JSDuplicatedDeclaration
>     export default Vue
> }
> ```

This resolved .ts import .vue issue, but it's really wired to touch a declared file in the project 😕

**Comment by Zikoat** [comment]
I had this issue in the served webpage instead of webstorm. Fixed after stopping and restarting `npm run serve`

**Comment by leaderdsn** [comment]
It helped me that I created another additional file with a different name: **'vue-shims.d.ts '** and also wrote in it:

```
declare module "*.vue" {
import Vue from 'vue'
export default Vue
}
```

**Comment by vanessabonis** [comment]
![image](https://user-images.githubusercontent.com/30501478/167790939-97355b32-4dd2-46ab-9ea6-dd5d5abc1981.png)
add /* in vite.config.ts 

solved

**Comment by vanessabonis** [comment]
declare module "*.vue" {
  import type { DefineComponent } from 'vue'
  const component: DefineComponent<{}, {}, any>
  export default component
}

**Comment by pawel-dlugosz** [comment]
Creating file `vue-shim.d.ts` in `src` solved the problem in my case
```ts
declare module "*.vue" {
  import { defineComponent } from "vue";
  const component: ReturnType<typeof defineComponent>;
  export default component;
}
```

**Comment by amidnikmal** [comment]
> ```ts
> declare module "*.vue" {
>   import { defineComponent } from "vue";
>   const component: ReturnType<typeof defineComponent>;
>   export default component;
> }
> ```

For me it works too. Thank you!

Could you please explain why this resolves the issue ?

**Comment by imrim12** [comment]
Bonus: Make sure you include the `*.d.ts` files in your tsconfig.json
```
{
   ...
  "include": ["src/**/*", "src/**/*.vue", "**/*.d.ts"],
   ...
}
```

**Comment by who-Is-Beto** [comment]
Every time I create a Vue-ts project I use this types helper. I hope this type config helps c:
```typescript
//src/shims-vue.d.ts
declare module "*.vue" {
  import Vue from "vue";
  export default Vue;
}

//if you use env variables c:
declare module "*/envs.ts";
```

**Comment by rocifier** [comment]
May be a stupid answer but it happened to me this week - I was opening the root of our project structure as a workspace in vscode, not the front-end vue.js subfolder. When I opened the correct root folder this error went away.

**Comment by vis97c** [comment]
> Bonus: Make sure you include the `*.d.ts` files in your tsconfig.json
> 
> ```
> {
>    ...
>   "include": ["src/**/*", "src/**/*.vue", "**/*.d.ts"],
>    ...
> }
> ```

For me this was the real issue.

**Comment by marekv1** [comment]
For me installing TypeScript Vue Plugin (Volar) for vscode fixed to resolve .vue files for ts.

**Comment by lolicrafter** [comment]
solved this

```
//tsconfig.json
 "compilerOptions": {
    "paths": {
      "@/*": ["/src/*"]
    },
}
```
into
```"@/*": ["./src/*"]```

**Comment by foriLLL** [comment]
for me, creating a vue3(3.3.4) project without TypeScript support has the same problem.(ts(2307))

**Comment by jhunxein** [comment]
@foriLLL  same here.

**Comment by begueradj** [comment]
Same issue when working with Nuxt 3 and Vuetify:

` ERROR  Failed to resolve import "vue3-datepicker.vue" from "components/TestDate.vue". Does the file exist? `

**Comment by Josmun55** [comment]
In webstorm,the following worked for me. Uncheck the vuejs  and vite plugins temporarily and then re-enable them. Restart the IDE  afterwards.

**Comment by emonadeo** [comment]
> Creating file `vue-shim.d.ts` in `src` solved the problem in my case
> 
> ```ts
> declare module "*.vue" {
>   import { defineComponent } from "vue";
>   const component: ReturnType<typeof defineComponent>;
>   export default component;
> }
> ```

`ReturnType<typeof defineComponent>` resolves to `any`.

(see https://github.com/vuejs/core/blob/v3.3.9/packages/runtime-core/src/apiDefineComponent.ts)

**Comment by lordghick** [comment]
To complement @danielg212 answer, that solution fixes the "import" issue, but creates a new error in the script tag. To address both issues, even if I'm not using TS, I created a file at my project's root named "tsconfig.json" with the following:

`{   "compilerOptions": { "paths": { "@/*": [ "./*" ] }, "allowJs": true }  }`

This solved all issues for me

**Comment by kindkitchen** [comment]
In my case because alongside with __typescript__ the __deno__ language server was detected the __hybrid mode__ was ruled out... So my solution is manually turn on it back.
In `settings.json` it should be something like:
```json
"vue.server.hybridMode": true
```
In ui it looks like:
![image](https://github.com/vuejs/vue-cli/assets/53253722/26ffb018-f6a1-42a1-9887-10f32ce49e31)
