### ISSUE TITLE
Allow opting out of Babel

### ISSUE THREAD

**Issue by robcresswell** [vuejs/vue-cli#1199]
### What problem does this feature solve?
Babel adds additional comprehension overhead in entering the modern web app ecosystem (more libraries, more plugins to learn about and understand) as well as potential adding performance hits when transpiling code that isn't standardised. While it has some benefits (supporting older browsers) I don't think we should assume that everyone will use it.

### What does the proposed API look like?
I think the only difference is that the `create` workflow should have an extra step for including babel and the vue preset; the complexity lies in other parts of vue-cli potentially relying on babels presence.

**Comment by yyx990803** [comment]
I think it **should** be included by default because I'd say probably more than half of the users need it. But yeah we should have a way to opt-out.

**Comment by robcresswell** [comment]
True, I should've thought that through in a more utilitarian way. As you said, an opt-out would be good.
