### ISSUE TITLE
npm run dev报错“ERROR in Cannot find module 'estraverse'”

### ISSUE THREAD

**Issue by GuoYongfeng** [vuejs/vue-cli#12]
$ npm run dev

> ficloud-vue@ dev D:\website\vuejs-project\ficloud-vue
> webpack-dev-server --inline --hot --config build/webpack.dev.conf.js

http://0.0.0.0:8080/
webpack result is served from /static/
content is served from D:\website\vuejs-project\ficloud-vue
404s will fallback to /index.html
Hash: 14553b34cf6c239c3a13
Version: webpack 1.12.10
Time: 2198ms
 Asset    Size  Chunks             Chunk Names
app.js  636 kB       0  [emitted]  app
chunk    {0} app.js (app) 214 kB [rendered]
    [0] multi app 52 bytes {0} [built] [1 error]

......

最后提示找不到这个module
ERROR in Cannot find module 'estraverse'
 @ multi app

**Comment by JasinYip** [comment]
这种错误不能通过 `npm install` 解决吗？

**Comment by yyx990803** [comment]
`npm install` 有问题吧。试试删掉 `node_modules` 重装，如果网络不靠谱用 http://npm.taobao.org/
