### ISSUE TITLE
打包出来后，css样式和开发模式不一致

### ISSUE THREAD

**Issue by yanghuanrong** [vuejs/vue-cli#1208]
在开发环境写css渐变背景浏览器可以正常展示，打包出来之后渐变背景样式丢失，以及多行超出显示省略号也会出现同样的问题，这让我感到很郁闷，用的是谷歌浏览器。

**Comment by yyx990803** [comment]
你肯定是只写了 WebKit 前缀版本的规则但没有写无前缀的规则...

**Comment by hcl2020** [comment]
我也遇到过这个问题。比如原来的css是

      background: #ccc;
      -webkit-background-clip: text;

打包之后-webkit-前缀的规则被提到了最前面，变成

      -webkit-background-clip: text;
      background: #ccc;

导致-webkit-background-clip样式失效。 @yyx990803
