### ISSUE TITLE
Typescript error in VSCode when importing .vue files

### ISSUE THREAD

**Issue by kevintighe** [vuejs/vue-cli#1216]
### Version
3.0.0-beta.9

### Reproduction link
[https://github.com/kevintighe/vue-cli-bug-repro](https://github.com/kevintighe/vue-cli-bug-repro)

### Steps to reproduce
- Use _vue-cli 3.0.0-beta.9_
- `vue create my-app`
- Manual configuration, selecting only Typescript
- Open folder with Visual Studio Code (1.22.2)
- Open main.ts

### What is expected?
No errors are reported in Visual Studio Code

### What is actually happening?
In main.ts, the line 

`import App from './App.vue'` 

is underlined in red with the error _[ts] Cannot find module './App.vue'_

---
Note that the app builds and runs with no errors via `npm run serve`.  The error only appears in Visual Studio Code.

**Comment by yibuyisheng** [comment]
https://github.com/vuejs/vue-cli/issues/1198

**Comment by Jieyuhua9193** [comment]
Is this problem solved？Is this problem solved。
