### ISSUE TITLE
Source Links on C

### ISSUE THREAD

**Issue by kenrim626** [vuejs/vue-cli#1221]
### Version
2.9.3

### Reproduction link
[https://github.com/kenrim626/VueErrorReport.git](https://github.com/kenrim626/VueErrorReport.git)

### Steps to reproduce
1.) Open the repository with Visual Studio Code.
2.) Open the command line
3.) Enter "npm install"
4.) Enter "npm run build"
5.) Check the 'index.html' file in the dist directory.

### What is expected?
There are links towards the app.css and a few javascript files. This should be based on the current directory the index.html is in.

Expected link example: "./css/app.650f1adf.css"

### What is actually happening?
The links are based on C:\, because the dot before the slash is missing.

Corrupt link example: "/css/app.650f1adf.css"

---
The project was just now created via the vue-cli. There were no changes made except the two npm commands listed in the steps to reproduce.

**Comment by yyx990803** [comment]
This is expected behavior. Please read up on webpack publicPath.

**Comment by kenrim626** [comment]
@yyx990803 You expect your generated projects to not work at all without manual changes?

I would expect the vue-cli to generate a working project with valid links that I can start without fiddling with any files content and then start from there.

**Comment by Akryum** [comment]
> The links are based on C:, because the dot before the slash is missing.

What do you mean?

> Corrupt link example: "/css/app.650f1adf.css"

If you put the files on a server and you open the page on let's say `https://my-app.com/`, `/css/app.650f1adf.css` will be `https://my-app.com/css/app.650f1adf.css`.

**Comment by kenrim626** [comment]
> The links are based on C:, because the dot before the slash is missing.

> What do you mean?

>If you put the files on a server and you open the page on let's say `https://my-app.com/`, [...]

Im opening the html file directly from my browser, thus the url is `file:///C:/Users/.../VueErrorReport/dist/index.html`. 

Now the `/css/app.650f1adf.css` refers to `file:///C:/css/app.650f1adf.css`. The desired path would be `file:///C:/Users/.../VueErrorReport/dist/css/app.650f1adf.css`. That is the reason I assumed a dot is missing to signal a reference from the current directory.
