### ISSUE TITLE
94% asset optimization ERROR  Failed to compile with 1 errors

### ISSUE THREAD

**Issue by karneaud** [vuejs/vue-cli#1223]
### Version
3.0.0-beta.6

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
* install a vue-cli project with the webpack template
* run yarn install

### What is expected?
project should compile and server should serve files

### What is actually happening?
compilation is failing for some reason always at 94%

---
I'm using a docker node container to run the development project in.

**Comment by karneaud** [comment]
> 2018-05-04T13:42:58.637057802Z   0% compiling 10% building modules 0/1 modules 1 active ... webpack/hot/dev-server ./src/main.js                                          10% building modules 1/1 modules 0 active 10% building modules 1/2 modules 1 active ...ode_modules/webpack/hot/dev-server.js                                          10% building modules 2/2 modules 0 active 10% building modules 2/3 modules 1 active ...client/index.js?http://localhost:8001 10% building modules 2/4 modules 2 active ...x.js??ref--0!/usr/src/app/src/main.js 10% building modules 2/5 modules 3 active ...c/app/node_modules/webpack/hot/log.js 10% building modules 2/6 modules 4 active ...dules/webpack/hot/log-apply-result.js 10% building modules 2/7 modules 5 active ...p/node_modules/webpack/hot/emitter.js 10% building modules 3/7 modules 4 active ...p/node_modules/webpack/hot/emitter.js 10% building modules 4/7 modules 3 active ...p/node_modules/webpack/hot/emitter.js 10% building modules 5/7 modules 2 active ...p/node_modules/webpack/hot/emitter.js 10% building modules 6/7 modules 1 active ...p/node_modules/webpack/hot/emitter.js                                          10% building modules 7/7 modules 0 active 10% building modules 7/8 modules 1 active .../webpack/hot nonrecursive /^\.\/log$/ 10% building modules 7/9 modules 2 active ...s/webpack-dev-server/client/socket.js 10% building modules 7/10 modules 3 active .../webpack-dev-server/client/overlay.js 10% building modules 8/10 modules 2 active .../webpack-dev-server/client/overlay.js     10% building modules 8/11 modules 3 active /usr/src/app/node_modules/url/url.js 10% building modules 8/12 modules 4 active .../app/node_modules/vue/dist/vue.esm.js 10% building modules 8/13 modules 5 active ...src/app/node_modules/events/events.js 11% building modules 9/13 modules 4 active ...src/app/node_modules/events/events.js 11% building modules 10/13 modules 3 active ...src/app/node_modules/events/events.js 11% building modules 11/13 modules 2 active ...src/app/node_modules/events/events.js 11% building modules 11/14 modules 3 active ...f--0!/usr/src/app/src/router/index.js 11% building modules 12/14 modules 2 active ...f--0!/usr/src/app/src/router/index.js 11% building modules 13/14 modules 1 active ...f--0!/usr/src/app/src/router/index.js 11% building modules 13/15 modules 2 active .../app/node_modules/strip-ansi/index.js    11% building modules 13/16 modules 3 active /usr/src/app/node_modules/url/util.js 11% building modules 13/17 modules 4 active ...ode_modules/webpack/buildin/global.js 11% building modules 13/18 modules 5 active ...app/node_modules/punycode/punycode.js 11% building modules 13/19 modules 6 active ...node_modules/querystring-es3/index.js 11% building modules 14/19 modules 5 active ...node_modules/querystring-es3/index.js 11% building modules 15/19 modules 4 active ...node_modules/querystring-es3/index.js 11% building modules 16/19 modules 3 active ...node_modules/querystring-es3/index.js 11% building modules 16/20 modules 4 active ..._modules/sockjs-client/dist/sockjs.js 12% building modules 17/20 modules 3 active ..._modules/sockjs-client/dist/sockjs.js 12% building modules 17/21 modules 4 active ...x.js??ref--0!/usr/src/app/src/App.vue 12% building modules 17/22 modules 5 active ...node_modules/loglevel/lib/loglevel.js 12% building modules 18/22 modules 4 active ...node_modules/loglevel/lib/loglevel.js 12% building modules 19/22 modules 3 active ...node_modules/loglevel/lib/loglevel.js 12% building modules 19/23 modules 4 active ...c/app/node_modules/ansi-html/index.js 12% building modules 20/23 modules 3 active ...c/app/node_modules/ansi-html/index.js 12% building modules 20/24 modules 4 active ...ode_modules/webpack/buildin/module.js 12% building modules 20/25 modules 5 active ...p/node_modules/html-entities/index.js 12% building modules 21/25 modules 4 active ...p/node_modules/html-entities/index.js 12% building modules 22/25 modules 3 active ...p/node_modules/html-entities/index.js 12% building modules 22/26 modules 4 active ...src/app/src/components/HelloWorld.vue 12% building modules 22/27 modules 5 active ...ode_modules/querystring-es3/decode.js 12% building modules 22/28 modules 6 active ...ode_modules/querystring-es3/encode.js 12% building modules 23/28 modules 5 active ...ode_modules/querystring-es3/encode.js 12% building modules 24/28 modules 4 active ...ode_modules/querystring-es3/encode.js 13% building modules 25/28 modules 3 active ...ode_modules/querystring-es3/encode.js 13% building modules 26/28 modules 2 active ...ode_modules/querystring-es3/encode.js 13% building modules 26/29 modules 3 active ...ript&index=0!/usr/src/app/src/App.vue 13% building modules 27/29 modules 2 active ...ode_modules/querystring-es3/encode.js 13% building modules 27/30 modules 3 active ...ue-loader/lib/component-normalizer.js 13% building modules 28/30 modules 2 active ...ue-loader/lib/component-normalizer.js 13% building modules 29/30 modules 1 active ...ue-loader/lib/component-normalizer.js 13% building modules 29/31 modules 2 active ...late&index=0!/usr/src/app/src/App.vue 13% building modules 30/31 modules 1 active ...ue-loader/lib/component-normalizer.js 13% building modules 30/32 modules 2 active ...src/app/src/components/HelloWorld.vue 13% building modules 30/33 modules 3 active ...src/app/src/components/HelloWorld.vue 13% building modules 31/33 modules 2 active ...src/app/src/components/HelloWorld.vue 13% building modules 32/33 modules 1 active ...ue-loader/lib/component-normalizer.js 13% building modules 32/34 modules 2 active ...les/vue-router/dist/vue-router.esm.js 13% building modules 32/35 modules 3 active .../app/node_modules/ansi-regex/index.js 13% building modules 32/36 modules 4 active ...les/html-entities/lib/xml-entities.js 13% building modules 32/37 modules 5 active ...s/html-entities/lib/html5-entities.js 13% building modules 32/38 modules 6 active ...s/html-entities/lib/html4-entities.js 13% building modules 33/38 modules 5 active ...s/html-entities/lib/html4-entities.js 14% building modules 34/38 modules 4 active ...s/html-entities/lib/html4-entities.js 14% building modules 35/38 modules 3 active ...s/html-entities/lib/html4-entities.js 14% building modules 36/38 modules 2 active ...s/html-entities/lib/html4-entities.js 14% building modules 37/38 modules 1 active ...s/html-entities/lib/html4-entities.js                                          14% building modules 38/38 modules 0 active 14% building modules 38/39 modules 1 active ...yles&index=0!/usr/src/app/src/App.vue                                          14% building modules 39/39 modules 0 active 14% building modules 39/40 modules 1 active ...src/app/src/components/HelloWorld.vue                                          14% building modules 40/40 modules 0 active 14% building modules 40/41 modules 1 active ...yles&index=0!/usr/src/app/src/App.vue 14% building modules 40/42 modules 2 active ...src/app/src/components/HelloWorld.vue 14% building modules 40/43 modules 3 active ...ules/vue-hot-reload-api/dist/index.js 14% building modules 40/44 modules 4 active ...e-style-loader/lib/addStylesClient.js 14% building modules 40/45 modules 5 active ...f--3!/usr/src/app/src/assets/logo.png 14% building modules 41/45 modules 4 active ...f--3!/usr/src/app/src/assets/logo.png 15% building modules 42/45 modules 3 active ...f--3!/usr/src/app/src/assets/logo.png 15% building modules 43/45 modules 2 active ...f--3!/usr/src/app/src/assets/logo.png 15% building modules 44/45 modules 1 active ...f--3!/usr/src/app/src/assets/logo.png                                          15% building modules 45/45 modules 0 active 15% building modules 45/46 modules 1 active .../vue-style-loader/lib/listToStyles.js 15% building modules 45/47 modules 2 active ...de_modules/css-loader/lib/css-base.js 15% building modules 46/47 modules 1 active ...de_modules/css-loader/lib/css-base.js                                          15% building modules 47/47 modules 0 active                                 71% sealing 72% optimizing 73% basic module optimization       74% module optimization 75% advanced module optimization     76% basic chunk optimization       77% chunk optimization 78% advanced chunk optiO2018-05-04T13:43:00.293021698Z  ERROR  Failed to compile with 1 errors13:42:59

**Comment by yyx990803** [comment]
That's not a valid repro.

**Comment by karneaud** [comment]
its ok I found something better....you should get it fixed though :-)
