### ISSUE TITLE
Error: command failed: yarn

### ISSUE THREAD

**Issue by tamtm** [vuejs/vue-cli#1234]
### Version
3.0.0-beta.6

### Reproduction link
[http://fuckkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.com](http://fuckkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.com)

### Steps to reproduce
vue create a-new-project

### What is expected?
Run without any error

### What is actually happening?
✨  Creating project in D:\a-new-project.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

'yarn' is not recognized as an internal or external command,
operable program or batch file.
 ERROR  command failed: yarn

**Comment by posva** [comment]
This is probably related to your setup not having yarn correctly installed (or removed) but selected at some point. You can revert back to npm by changing `~/.vuerc`

Closing as this is a system question and please do not posts repro links like that again, thanks

**Comment by tamtm** [comment]
@posva the command uses to create a new project, so what kind of repo link do you want? I don't get it

**Comment by leejh3224** [comment]
If you experience something like this, first check out you have `yarn` installed or not.
```bash
yarn --version
```
Install yarn resolved this issue.

**Comment by L4ZZA** [comment]
@posva How do you do that on Windows tho?

Surely vue should select any available one one it sees that yarn does not exist anymore the same way it recognizes when npm and yarn are both installed.

**Comment by sachiko-kame** [comment]
If you want to do it quickly, you should install "yarn"

`npm install -g yarn`

`sudo npm install -g yarn`

**Comment by paulrobhendrickson** [comment]
I have yarn installed and got this error

**Comment by alejosv** [comment]
Same error:
```
Vue CLI v4.5.15
✨  Creating project in /lxcshared/Typescript/ioset.git/web.
⚙️  Installing CLI plugins. This might take a while...

yarn install v1.22.17
info No lockfile found.




success Saved lockfile.
Done in 33.06s.
🚀  Invoking generators...
 WARN  conflicting versions for project dependency "typescript":
[5/5] ⠠ deasync
- ~3.9.3 injected by generator "@vue/cli-plugin-unit-jest"
- ~4.1.5 injected by generator "@vue/cli-plugin-typescript"

Using newer version (~4.1.5), but this may cause build errors.
📦  Installing additional dependencies...

yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 ERROR  command failed: yarn 
ubuntu@nodejs:/lxcshared/Typescript/ioset.git$ yarn --version
1.22.17
```

**Comment by programmersumanhalder** [comment]
simply uninstall yarn by :npm uninstall -g yarn
and again install by :npm install -g yarn
It worked for me.

**Comment by Ehtisham-Ayaan** [comment]
First of all, check your node version. The node must be on 14.17.0 or whatever you may get on the terminal. You may also manage different node versions using nvm if you want multiple node versions after installing the required node close the terminal and reopen it. There you go. Everything will work fine then and you will not get yarn error again.
