### ISSUE TITLE
am unable to uninstall vue cli

### ISSUE THREAD

**Issue by adityarw** [vuejs/vue-cli#1241]
### Version
3.0.0-beta.6

### Reproduction link
[https://asdsf.com](https://asdsf.com)

### Steps to reproduce
F:\XAMPP\htdocs>npm uninstall -g 

### What is expected?
uninstall vue cli

### What is actually happening?
am getting the bellow response when i tried to uninstall

F:\XAMPP\htdocs>npm uninstall -g 
up to date in 0.127s

F:\XAMPP\htdocs>npm uninstall -g 
up to date in 0.13s

F:\XAMPP\htdocs>npm uninstall -g 
up to date in 0.126s

**Comment by yyx990803** [comment]
You need to give it the name of the package to uninstall... So npm uninstall -g @vue/cli

**Comment by adityarw** [comment]
hey i used this npm uninstall -g @vue/cli

**Comment by adityarw** [comment]
hey it not showing package name here

**Comment by adityarw** [comment]
npm uninstall -g @vue/cli

**Comment by adityarw** [comment]
npm install -g vue/cli

**Comment by adityarw** [comment]
there is an @ before vue/cli

**Comment by adityarw** [comment]
i have used the same as u users but its showing up to date message

**Comment by adityarw** [comment]
@yyx990803 i have used the same as u users but its showing up to date message

**Comment by posva** [comment]
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
