### ISSUE TITLE
Fix Yarn's "unmet peer dependency" warnings with explicit top-level dependencies in subpackages

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-cli#1243]
### What problem does this feature solve?
When installing with Yarn, a Vue CLI 3 project currently emits a lot of warnings:

```
warning "@vue/cli-plugin-babel > babel-loader@8.0.0-beta.2" has unmet peer dependency "webpack@>=2".
warning "@vue/cli-plugin-e2e-cypress > eslint-plugin-cypress@2.0.1" has unmet peer dependency "eslint@>= 3.2.1".
warning "@vue/cli-plugin-eslint > eslint-loader@2.0.0" has unmet peer dependency "webpack@>=2.0.0<5.0.0".
warning "@vue/eslint-config-prettier > eslint-config-prettier@2.9.0" has unmet peer dependency "eslint@>=3.14.1".
warning "@vue/eslint-config-standard > eslint-config-standard@11.0.0" has unmet peer dependency "eslint@>=4.18.0".
warning "@vue/eslint-config-standard > eslint-plugin-import@2.11.0" has unmet peer dependency "eslint@2.x - 4.x".
warning "@vue/eslint-config-standard > eslint-plugin-node@6.0.1" has unmet peer dependency "eslint@>=3.1.0".
warning "@vue/eslint-config-standard > eslint-plugin-standard@3.1.0" has unmet peer dependency "eslint@>=3.19.0".
warning " > sass-loader@7.0.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
```

This is confusing for users, many of them interpreting these warnings as an error or sign that they've done something wrong.

### What does the proposed API look like?
[Neutrino solved this problem](https://github.com/mozilla-neutrino/neutrino-dev/pull/752/files) by duplicating dependencies in subpackages, so I recommend we do the same. It's a little bit of a pain, but if it saves _every Yarn user_ from a confusing experience, I personally think it's worth it.

**Comment by yyx990803** [comment]
The default `vue create` process actually filters out the warnings.

Some cases also isn't entirely cost-free (e.g. the `eslint-plugin-cypress` case, the user may use the Cypress plugin without ESLint, so adding `eslint` as its dep doesn't make sense) - which means we can't entirely get rid of the warnings even if we want to.
