### ISSUE TITLE
how to edit '@vue/prettier' rules

### ISSUE THREAD

**Issue by mimimile** [vuejs/vue-cli#1244]
i want to edit '@vue/prettier' rules
like
```
module.exports = {
  root: true,
  'extends': [
    'plugin:vue/essential',
    '@vue/prettier',
    '@vue/typescript'
  ],
  'rules': {
    '@vue/prettier/semi': false,

    'semi': ['error', 'never'],
    'no-plusplus': ['off'],
    'no-param-reassign': ['off'],
    'no-console': ['error', { allow: ['error', 'warn'] }],
  }
}
```
but it don't work

what should i do?

**Comment by Aysnine** [comment]
@mimimile 

in my package.json

```js
    "extends": [
      "plugin:vue/essential",
      "@vue/prettier"
    ],
    "rules": {
      "prettier/prettier": [
        "warn",
        {
          "#": "prettier config in here :)",
          "singleQuote": true,
          "semi": false,
          "trailingComma": "none"
        }
      ]
    },
    "parserOptions": {
      "parser": "babel-eslint"
    }
```

about config option of prettier : https://prettier.io/docs/en/options.html

**Comment by Aysnine** [comment]
you can [search this](https://github.com/search?p=2&q=++++%22extends%22%3A+%5B+++++++%22plugin%3Avue%2Fessential%22%2C+++++++%22%40vue%2Fprettier%22+++++%5D%2C+++++%22rules%22%3A+%7B&type=Code) get more example :)

**Comment by y0n3r** [comment]
@Aysnine Thanks so much. This is super helpful. I was wondering why my project was ignoring my `.prettierrc` file! Instead of putting it in my `package.json` file directly, I just defined the rules you have above direction inside of `.eslintrc` (which extends prettier in my project). Again, thank you!

**Comment by Zver64** [comment]
> @mimimile
> 
> in my package.json
> 
> ```js
>     "extends": [
>       "plugin:vue/essential",
>       "@vue/prettier"
>     ],
>     "rules": {
>       "prettier/prettier": [
>         "warn",
>         {
>           "#": "prettier config in here :)",
>           "singleQuote": true,
>           "semi": false,
>           "trailingComma": "none"
>         }
>       ]
>     },
>     "parserOptions": {
>       "parser": "babel-eslint"
>     }
> ```
> 
> about config option of prettier : https://prettier.io/docs/en/options.html

I followed your suggestion but it seems to work partially. I work in Webstorm. So the 'Fix eslint problems' option works as expected and changes this code:
```
import { Button, Select } from "element-ui";
import Vue from "vue";
Vue.use(Button);
Vue.use(Select);
```
to this: 
```
import { Button, Select } from 'element-ui'
import Vue from 'vue'
Vue.use(Button)
Vue.use(Select)

```

This is exactly what i need.
But I have warnings in my console when compiling, for instance:

```
warning: Insert `;` (prettier/prettier) at src/element-config.js:3:16:
  1 | import { Button, Select } from 'element-ui'
  2 | import Vue from 'vue'
> 3 | Vue.use(Button)
    |                ^
  4 | Vue.use(Select)
  5 | 
```

Is there something I am doing wrong?

**Comment by Zver64** [comment]
I also found out that everything works well if I choose to keep settings in separate files and add my custom settings in .eslintrc.js instead of package.json like this:
```
module.exports = {
  root: true,
  env: {
    node: true
  },
  extends: ['plugin:vue/essential', '@vue/prettier'],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'prettier/prettier': [
      'warn',
      {
        singleQuote: true,
        semi: false,
        trailingComma: 'none'
      }
    ]
  },
  parserOptions: {
    parser: 'babel-eslint'
  }
}
```

**Comment by Aysnine** [comment]
@Zver64 This depends on the choice you make when initializing the project using the vue-cli.
![image](https://user-images.githubusercontent.com/10137653/53679438-a55e5900-3d07-11e9-8a56-c1abfee1296b.png)

About eslint config: https://cli.vuejs.org/config/#eslint
![image](https://user-images.githubusercontent.com/10137653/53679455-db034200-3d07-11e9-9b8e-4d59edfcb43e.png)

**Different ways, but same configuration.**

**Comment by Zver64** [comment]
> @Zver64 This depends on the choice you make when initializing the project using the vue-cli.
> ![image](https://user-images.githubusercontent.com/10137653/53679438-a55e5900-3d07-11e9-8a56-c1abfee1296b.png)
> 
> About eslint config: https://cli.vuejs.org/config/#eslint
> ![image](https://user-images.githubusercontent.com/10137653/53679455-db034200-3d07-11e9-9b8e-4d59edfcb43e.png)
> 
> **Different ways, but same configuration.**

Yes, this is what I was talking about. Everything works as expected if I choose "In dedicated config files" option. But I have the bug I described above when I choose "In package.json" option and try to set my own settings in package.json.

**Comment by andrevmatos** [comment]
Can confirm, setting `eslintConfig` inside `package.json` is respected by IDE and by `vue-cli-service lint`, but `vue-cli-service [serve|build]` still print warnings (e.g. for longer lines when setting `printWidth` to `99`)

**Comment by EugeneDae** [comment]
How can I disable Prettier for HTML and CSS files in a Vue CLI project?

**Comment by mixalbl4-127** [comment]
Solution for outside `.eslintrc.js` and `.prettierrc` files with same content.

```javascript
const fs = require("fs");

module.exports = {
    "root": true,
    "env": {
        "node": true
    },
    "extends": [
        "plugin:vue/vue3-essential",
        "eslint:recommended",
        "@vue/prettier"
    ],
    "parserOptions": {
        "parser": "babel-eslint"
    },
    "rules": {
        "no-debugger": "warn",
        "no-unused-vars": "warn",
        "prettier/prettier": ["warn", fs.readFileSync(".prettierrc")]
    }
}```

**Comment by Rackar** [comment]
> I also found out that everything works well if I choose to keep settings in separate files and add my custom settings in .eslintrc.js instead of package.json like this:
> 
> ```
> module.exports = {
>   root: true,
>   env: {
>     node: true
>   },
>   extends: ['plugin:vue/essential', '@vue/prettier'],
>   rules: {
>     'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
>     'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
>     'prettier/prettier': [
>       'warn',
>       {
>         singleQuote: true,
>         semi: false,
>         trailingComma: 'none'
>       }
>     ]
>   },
>   parserOptions: {
>     parser: 'babel-eslint'
>   }
> }
> ```

This works. Thank you very much.

**Comment by guohuihot** [comment]
what moudle  the '@vue/prettier'? why it empty
![image](https://user-images.githubusercontent.com/3119995/122965491-d3757480-d3ba-11eb-814e-1f1ad36a0cab.png)
