### ISSUE TITLE
Manifest CommonChunk must exist at dev time for ES6 Single Instance to work

### ISSUE THREAD

**Issue by thiagof** [vuejs/vue-cli#1246]
### Version
2.9.3

### Reproduction link
[http://needs-webpack](http://needs-webpack)

### Steps to reproduce
- Create the project with vue-init
- Create two entrypoints and 1 shared module (add to shared module `console.log('new module instance')`
- Issue this shared module on both entrypoints (`import 'shared.js'`)
- Inject this 2 entrypoints on any page
- Load the page

### What is expected?
The shared module must be a singleton and pass for both entrypoints a single instance

### What is actually happening?
The module is created twice and breaks the Single Instance pattern from ES6

---
Thats a debugging nightmare for devs reusing a vuex store among components/entrypoints.
Note this is not a SPA.

**Comment by thiagof** [comment]
Solution was moving the plugin for the `webpack.base.conf.js`

```js
  plugins: [
    // extract webpack runtime and module manifest to its own file in order to
    // prevent vendor hash from being updated whenever app bundle is updated
    new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest',
      minChunks: Infinity
    }),
  ],
```

**Comment by LinusBorg** [comment]
Assuming this issue is about the "webpack" template for the old CLI, you should probably post it here:

https://github.com/vuejs-templates/webpack

**Comment by loushou** [comment]
We are actually transitioning from one type of frontend to mostly vue-driven frontend... but we are doing it incrementally, one piece at a time. As such, multiple entrypoints on one page are going to be a common occurrence in our project. Thanks @thiagof for tracking it down.

**Comment by thiagof** [comment]
https://github.com/vuejs-templates/webpack/pull/1377
