### ISSUE TITLE
vue-loader link on newly scaffolded project 404s

### ISSUE THREAD

**Issue by stowball** [vuejs/vue-cli#1249]
### Version
3.0.0-beta.6

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
1. Scaffold a new project with `vue create hello-world`
2. `yarn serve`
3. Click the vue-loader link

### What is expected?
It should open a correct url (https://vue-loader.vuejs.org/ ?)

### What is actually happening?
It links to https://vue-loader.vuejs.org/en which 404s

**Comment by yyx990803** [comment]
Fixed in #1229
