### ISSUE TITLE
Lint service arguments

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue-cli#1255]
### What problem does this feature solve?
The user should be able to pass additional arguments to eslint when running the `vue-cli-service lint` command.

### What does the proposed API look like?
`yarn lint --ext .js,.vue,.gql`

**Comment by dhensche** [comment]
The lint command uses the Engine API, which unfortunately does not have option name parity with the CLI. https://eslint.org/docs/developer-guide/nodejs-api#cliengine vs https://eslint.org/docs/user-guide/command-line-interface#options . I will look at creating a PR that renames and propagates the command line args to the engine api
