### ISSUE TITLE
Have a plugin depend on another plugin

### ISSUE THREAD

**Issue by elevatebart** [vuejs/vue-cli#1256]
### What problem does this feature solve?
When a 3rd party plugin is installed, I would like to make sure that all dependencies are installed at the same time. 
For instancee, if my plugin is only applicable in TypeScript an I try to install it on a pure JavaScript engine, it will not work.
Some tools are only relevant for Jest, some for Mocha. 

It would allow as well to publish presets on github as just a package.json and an empty index.js.

### What does the proposed API look like?
When doing :
``` bash
vue invoke dependent-plugin
``` 
the cli would look for the dependencies in package.json.
a prompt informs that some named dependency plugins are missing. 
Even better, would be to propose to install them for me before invoking.

**Comment by yyx990803** [comment]
I don't think that should be the scope of vue-cli. You already can specify `peerDependencies` in your plugin.
