### ISSUE TITLE
my custom webpack plugin does not work in vue-cli 3.0.0

### ISSUE THREAD

**Issue by xuxiaoxiao312** [vuejs/vue-cli#1257]
### Version
3.0.0-beta.6

### Reproduction link
[https://codepen.io/xuxiaoxiao312/pen/JvLRKb](https://codepen.io/xuxiaoxiao312/pen/JvLRKb)

### Steps to reproduce
自定义了一个webpack插件，按文档https://github.com/vuejs/vue-cli/blob/dev/docs/webpack.md引入至vue.config.js 但是运行后没有执行插件中的内容

### What is expected?
execute my custom plugin

### What is actually happening?
didn't execute my custom plugin

**Comment by yyx990803** [comment]
That's not a valid reproduction.
