### ISSUE TITLE
webpack-dev-server Hello component msg update can not live update view

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue-cli#126]
Hi, everything works perfectly when first setup vue webpack developement environment.
I open the http://localhost:8080 to check the live update when updating source code.
1. When change template for both App and Hello, the view will update immediately;
2. When i change msg data property of Hello, it does not update automatically, I must do a refresh;
How can I fix it?

thanks~

**Comment by LinusBorg** [comment]
You can't. It's even described in the [source code of Hello.vue](https://github.com/vuejs-templates/webpack/blob/dist/template/src/components/Hello.vue#L11-L14)
```js
// note: changing this line won't causes changes
// with hot-reload because the reloaded component
// preserves its current state and we are modifying
// its initial state.
msg: 'Hello World'
```
