### ISSUE TITLE
Use vue-cli-service build --dest dist/production report an error.

### ISSUE THREAD

**Issue by iunfire** [vuejs/vue-cli#1260]
### Version
3.0.0-beta.6

### Reproduction link
[https://codesandbox.io/s/93jr9wp824](https://codesandbox.io/s/93jr9wp824)

### Steps to reproduce
run "vue-cli-service build --dest dist/production"

### What is expected?
build a dist in, dist/production folder

### What is actually happening?
Configuration Error: Avoid modifying webpack output.path directly. Use the "outputDir" option instead.

---
I want build a compilation folder for an environment. 
example: 
```
{
"build": "vue-cli-service build --dest dist/production",
"build:dev": "vue-cli-service build --mode development --dest dist/development",
"build:staging": "vue-cli-service build --mode staging --dest dist/staging",
}
```

**Comment by yyx990803** [comment]
This has already been fixed but not released yet.

**Comment by iunfire** [comment]
Oh, Thinks, Is it in the next(3.0.0-beta.9) release?

**Comment by andreydos** [comment]
@iunfire current release is v3.0.0-beta.10

**Comment by iunfire** [comment]
Very Thank you.

**Comment by jousi592** [comment]
I am still getting this error upn running `npm run build`.

I am running:` 3.0.0-beta.15`

vue.config.js looks like:
`module.exports = {
	configureWebpack:{
		output: {
			path: '../test-folder/',
			filename: '[name].js',
			publicPath: '/'
		},
           }
    }`
