### ISSUE TITLE
VisualStudio Code shows errors in new project

### ISSUE THREAD

**Issue by xcambar** [vuejs/vue-cli#1261]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/xcambar/vue-cli-lint-error-typescript](https://github.com/xcambar/vue-cli-lint-error-typescript)

### Steps to reproduce
* `vue create name-of-your-project`
* Select only the "TypeScript" option
* open `HelloWorld.vue` in VSCode

### What is expected?
The linter service and VSCode should provide the same amount of feedback to the user.

### What is actually happening?
The linter service does not throw any error, but VSCode does.

---
I'm new to vue-cli, and despite my Google-fu, I may have missed something.

**Comment by yibuyisheng** [comment]
https://github.com/vuejs/vue-cli/issues/1198 ?

**Comment by xcambar** [comment]
Unfortunately no (or I don't understand the solution): the example repo already contains the declarations as 2 separated files `shims-tsx.d.ts` and `shims-vue.d.ts`

**Comment by kumorig** [comment]
I can confirm this issue, and I'm pretty sure it has to do with the typescript version. `%USERPROFILE%\.vscode\extensions\octref.vetur-0.11.7\package.json` has `"typescript": "^2.6.2",`"typescript": "^2.6.2",  (but https://github.com/vuejs/vetur/blob/master/package.json has `"typescript": "^2.8.1",` but 0.11.7 is the same version so whats up with that?)   Anyway, definite assignment assertions (the exclamation marks after variables) are not in until  typescript v2.7

**Comment by kumorig** [comment]
So the solution for now seems to be to remove vetur from marketplace and:

    cd %USERPROFILE%\.vscode\extensions\
    git clone git@github.com:vuejs/vetur.git

**Comment by kumorig** [comment]
https://github.com/vuejs/vetur/issues/682

**Comment by xcambar** [comment]
I confirm the fix described in https://github.com/vuejs/vetur/issues/682#issuecomment-364267867 works, thanks @kumorig !

IT will do before Vetur 0.11.8 is published 👍
