### ISSUE TITLE
my custom webpack plugin does not work in vue-cli 3.0.0

### ISSUE THREAD

**Issue by xuxiaoxiao312** [vuejs/vue-cli#1264]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/xuxiaoxiao312/vue-demo](https://github.com/xuxiaoxiao312/vue-demo)

### Steps to reproduce
在一个测试项目 https://github.com/xuxiaoxiao312/vue-demo  中自定义了一个webpack插件，按文档https://github.com/vuejs/vue-cli/blob/dev/docs/webpack.md引入至vue.config.js 
运行后没有执行插件中的内容

### What is expected?
execute my custom plugin

### What is actually happening?
didn't execute my custom plugin

**Comment by yyx990803** [comment]
You are using beta.10 which uses webpack 4. You need to do `compiler.hooks.done.tap('my-plugin', cb)`.
