### ISSUE TITLE
Add index.html default template and make public folder optional

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue-cli#1265]
### What problem does this feature solve?
With vue-cli beta10 serve entry feature, vue-cli can be used in more advanced scenarios, but still is expected to provide a `public/index.html` template. 

I would like to suggest a default html template, customized in the config, and make the entire public folder optional. With all that in place, it will be even easier to serve simple dev environment for each vue file.

**Comment by yyx990803** [comment]
I'm not sure what is the reason to make `public` optional - can you be more specific about your use case?

**Comment by miljan-aleksic** [comment]
Ok. Ultimately I would like to be able to use vue-cli as a background for potential vue develop focused tools of my own. A storybook, a styleguide, a playground, and so on. Currently vue-cli is focused on building Apps, but those apps need libraries and those libraries need a good dev workflow.

There are several tools that solve this dev background but most are ported from react world, loading too many dependencies, using own webpack config, not always compatible with vue-devtool... ultimately forcing you to use some difficult to follow workarounds with duplicate build logic just to start working.

I believe vue-cli can be the abstraction that solves these dev tough parts and allow to build on top better solutions than we have now.
