### ISSUE TITLE
eslint plugin does not support --max-warnings option

### ISSUE THREAD

**Issue by BenoitAverty** [vuejs/vue-cli#1268]
### What problem does this feature solve?
ESLint has a `--max-warnings` command line options that triggers an return code > 0 when eslint detects more than n warnings.

This is really useful for example to allow developpers to work without worrying about eslint warnings, but make the CI build fail if there are some warnings.

Since @vue/cli-plugin-eslint uses eslint's `CLIEngine` instead of the cli object, this option is not supported (it is handled by `cli.js`, not `cli-engine.js`). It would be nice to have this feature in vue cli, either by re-implementing it, or by using the `cli.js` script of eslint.

### What does the proposed API look like?
`vue-cli-service lint --max-warnings=0`

**Comment by posva** [comment]
Duplicate of #1255

**Comment by BenoitAverty** [comment]
@posva Is it really a duplicate though ? The issue you linked seems to be about passing arguments to cli engine. This wouldn't solve this. Unless it's a broader issue ? What is the preferred way to cover my specific use case ? Reimplement the functionality or switch to using cli.js ?

**Comment by posva** [comment]
oh true
