### ISSUE TITLE
init后直接执行dev报错：Unexpected token import

### ISSUE THREAD

**Issue by laomao800** [vuejs/vue-cli#127]
### 环境
- window7
- nodejs v6.3.0

### 错误信息
init后直接执行dev，编译过程无报错。浏览器浏览时console报错：'Unexpected token import'  main.js:1

### 解决
后来发现将 `/build/webpack.base.conf.js` 配置文件中的 js 处理loader中的include注释可正常运行
```js
{
  test: /\.js$/,
  loader: 'babel',
  // include: projectRoot,
  exclude: /node_modules/
},
```

请问原因是？

**Comment by atoanofish** [comment]
import 这个错误是因为没有引入es2015.看看你根目录是不是缺少了.babelrc这个文件。如果缺少这个文件 会出现import 这个错误。

**Comment by laomao800** [comment]
@atoanofish 文件是有的，是刚 init 后的状态。

不过删除整个 `node_modules` 重新安装一遍又可以了……难道之前网络不佳某些依赖没有安装好
