### ISSUE TITLE
vue-cli beta.10 is not on the list of issue creator. 

### ISSUE THREAD

**Issue by atilkan** [vuejs/vue-cli#1277]
vue-cli beta.10 is not on the list of issue creator. 
( I am testing and reporting. I don't need help. I am trying to help.)
How can i report this? Do i have to input a reproduction link. What is a reproduction link?

**Comment by atilkan** [comment]
nevermind. i am out.

**Comment by posva** [comment]
Please, next time consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂

**Comment by posva** [comment]
the version problem is fixed now (releases were missing)

**Comment by atilkan** [comment]
@posva thanks. now i can use issue creator but will i. 
What do you expect me to enter as a reproduction link?

**Comment by yyx990803** [comment]
<img width="434" alt="screen shot 2018-05-12 at 6 41 36 pm" src="https://user-images.githubusercontent.com/499550/39962133-21d4533a-5614-11e8-8813-8fdaf751bfcf.png">

**Comment by atilkan** [comment]
@yyx990803 Does vue-cli run any of the links?

**Comment by atilkan** [comment]
BTW i am just creating project with different setting. How can i reproduce this?

**Comment by atilkan** [comment]
@yyx990803 
I know i have a point here. I can't reproduce creating projects by given details.

**Comment by atilkan** [comment]
@yyx990803 
I don't have to put reproduction link anymore. Thanks. 😄
