### ISSUE TITLE
Creating project with camel case

### ISSUE THREAD

**Issue by atilkan** [vuejs/vue-cli#1278]
It is probably because of npm doesn't allow this naming. This should be added to docs with this link -> https://docs.npmjs.com/files/package.json#name
![screen shot 2018-05-13 at 02 09 40](https://user-images.githubusercontent.com/1254613/39962281-8a323170-5652-11e8-9df7-3ccd0637ce7d.png)

**Comment by yyx990803** [comment]
I know you figured out how to get around the bot, but please use the proper feature request template. If you keep doing this I will have to block you.

**Comment by atilkan** [comment]
@yyx990803 ok, i will not. Thanks for the great work.
