### ISSUE TITLE
dev模式，不能断点，这个要怎么配置？

### ISSUE THREAD

**Issue by nicefan** [vuejs/vue-cli#128]

**Comment by posva** [comment]
Hi!
Please make sure to ask the question on the [forums](http://forum.vuejs.org/) or the [gitter chat](https://gitter.im/vuejs/vue).
Next time consider give a bit more of information. English can help you to get more answers too 😉

**Comment by mackxu** [comment]
@nicefan use debugger is a choice

**Comment by nicefan** [comment]
// eval-source-map is faster for development
  devtool: '#cheap-source-map',
