### ISSUE TITLE
webpack-dev-server how to disabled --progress

### ISSUE THREAD

**Issue by zlab** [vuejs/vue-cli#1284]
### What problem does this feature solve?
webpack-dev-server how to disabled --progress
```
 webpackConfig
          .plugin('progress')
          .use(require('webpack/lib/ProgressPlugin'))
```
### What does the proposed API look like?
`vue-cli-service serve`

**Comment by zlab** [comment]
`vue.config.js` set ` devServer.progress=false` dos not work

**Comment by LinusBorg** [comment]
This is a question, not a feature request. Please use forum.vuejs.org or chat.vuejs.org to ask for help.

**Comment by yyx990803** [comment]
Just curious, why would you want to do that?

**Comment by yyx990803** [comment]
This should be possible in the next release.

**Comment by zlab** [comment]
`chainConfig.plugins.delete('progress');`

**Comment by kumorig** [comment]
I think this should be reopened, because you do expect `devServer: {progress:false}` to work. The usual way to toggle progress is via command line `webpack-dev-server --progress` (because config value doesn't work in webpack-dev-server https://github.com/webpack/webpack-dev-server/issues/201) . 

The problem is amplified by `--progress` being passed in by default. Since it's very easy to add, but the method to remove is not very obvious.  (Thanks for the solution, zlab! )

Here is a use case when you don't want progess: Some IDE's (cough, webstorm, cough) doesn't handle the current terminal output very well:  
![webstorm64_2018-05-18_18-06-07](https://user-images.githubusercontent.com/5523938/40226293-3a8f7f60-5ac6-11e8-99d5-418321c9283b.png)

**Comment by geekytime** [comment]
I know this issue is closed, but for anyone that ends up here and is still stuck, I found a potential issue with da38747, and documented a solution here: https://github.com/vuejs/vue-cli/issues/4557#issuecomment-545965828

**Comment by justin-calleja** [comment]
@yyx990803 I would want to disable progress report because when running an app using `vue-cli-service serve --mode development` as a docker-compose service, I get a long wall of text for log output like this very short snippet of the total output:

```
feapp     | <s> [webpack.Progress] 66% building 696/741 modules 45 active /usr/src/app/node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!/usr/src/app/node_modules/postcss-loader/src/index.js??ref--9-oneOf-3-2!/usr/src/app/node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!/usr/src/app/node_modules/vuetify/src/components/VColorPicker/VColorPickerSwatches.sass
feapp     | <s> [webpack.Progress] 66% building 696/742 modules 46 active /usr/src/app/node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!/usr/src/app/node_modules/postcss-loader/src/index.js??ref--9-oneOf-3-2!/usr/src/app/node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!/usr/src/app/node_modules/vuetify/src/components/VProgressLinear/VProgressLinear.sass
feapp     | <s> [webpack.Progress] 66% building 697/742 modules 45 active /usr/src/app/node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!/usr/src/app/node_modules/postcss-loader/src/index.js??ref--9-oneOf-3-2!/usr/src/app/node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!/usr/src/app/node_modules/vuetify/src/components/VProgressLinear/VProgressLinear.sass
feapp     | <s> [webpack.Progress] 66% building 698/742 modules 44 active /usr/src/app/node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!/usr/src/app/node_modules/postcss-loader/src/index.js??ref--9-oneOf-3-2!/usr/src/app/node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!/usr/src/app/node_modules/vuetify/src/components/VProgressLinear/VProgressLinear.sass
feapp     | <s> [webpack.Progress] 66% building 698/743 modules 45 active /usr/src/app/node_modules/core-js/internals/inherit-if-required.js
feapp     | <s> [webpack.Progress] 66% building 698/744 modules 46 active /usr/src/app/node_modules/vue-style-loader/index.js??ref--9-oneOf-3-0!/usr/src/app/node_modules/css-loader/dist/cjs.js??ref--9-oneOf-3-1!/usr/src/app/node_modules/postcss-loader/src/index.js??ref--9-oneOf-3-2!/usr/src/app/node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-3-3!/usr/src/app/node_modules/vuetify/src/components/VExpansionPanel/VExpansionPanel.sass
```
