### ISSUE TITLE
3.0.0-beta.10 breaks postcss

### ISSUE THREAD

**Issue by doublemarked** [vuejs/vue-cli#1285]
### Version
3.0.0-beta.10

### Reproduction link
[https://github.com/doublemarked/broken-lang-postcss](https://github.com/doublemarked/broken-lang-postcss)

### Steps to reproduce
1. Use postcss in a style block within a .vue file, with or without `lang="postcss"`. For example,
```
<style>
  .container {
     color: black;
     & .inner {
        color: red;
     }
  }
</style>
<!-- or -->
<style lang="postcss">
  .container {
     color: black;
     & .inner {
        color: red;
     }
  }
</style>
```

### What is expected?
PostCSS should be supported out of the box, as it was with the previous version. The documentation still implies that it's enabled by default.

### What is actually happening?
1. When no "lang" is specified, PostCSS is ignored (treated as normal CSS).
2. With `lang="postcss"` it's breaking the build with an error such as,
```
 error  in ./src/App.vue?vue&type=style&index=0&lang=postcss

Module parse failed: Unexpected character '#' (13:0)
You may need an appropriate loader to handle this file type.
| 
| 
| #app {
...
```
---
This worked fine until I upgraded from beta 9 to beta 10.

**Comment by doublemarked** [comment]
Hey @LinusBorg - I see you labeled this discussion. Does that mean it's working as intended? At least seems like the docs should be clarified?

**Comment by LinusBorg** [comment]
It means that I'm not sure what we should do with it right now.

**Comment by yyx990803** [comment]
FYI this was never supposed to work. See https://github.com/vuejs/vue-cli/pull/1259

**Comment by yyx990803** [comment]
Without `lang="postcss"` it's working as intended.

**Comment by doublemarked** [comment]
That makes sense. But actually all my code uses the lang attribute, and the build breaks after the upgrade. Is that also as intended?

**Comment by doublemarked** [comment]
Ok, no problem!
