### ISSUE TITLE
normalized environment variable

### ISSUE THREAD

**Issue by narusas** [vuejs/vue-cli#1288]
### What problem does this feature solve?
I have many middle sites (dev, dev2, stg,stg2, www,www2,www3) 
so I should  create many .env.[mode] files.

so there is many duplicated key(little modified)

.env.dev1 
~~~~
domain=foo.com.dev
apidomain=api.foo.com.dev
resourcedomain=res.foo.com.dev
~~~~

.env.stg
~~~~ 
domain=foo.com.stg
apidomain=api.foo.com.stg
resourcedomain=res.foo.com.stg
~~~~

### What does the proposed API look like?
.env
~~~~
apidomain=api.${domain}
resourcedomain=res.${domain}
login_api=${apidomain}/login
~~~~

.env.dev
~~~~
domain=foo.com.dev
~~~~

.env.stg
~~~~
domain=foo.com.stg
~~~~

**Comment by yyx990803** [comment]
I don't think this can work because `.env` is loaded before `.env.[mode]`. The latter is more specific and should be able to overwrite the former.
