### ISSUE TITLE
I' try to find add global scss variables with hot loading 

### ISSUE THREAD

**Issue by 001123** [vuejs/vue-cli#1296]
### Version
3.0.0-beta.10

### Reproduction link
[https://codesandbox.io/s/kkpk186737](https://codesandbox.io/s/kkpk186737)

### Steps to reproduce
I' try to find add global scss variables with hot loading  , how i do this

### What is expected?
global scss variables with hot loading

### What is actually happening?
vue-cli cant do it

**Comment by yyx990803** [comment]
https://github.com/shakacode/sass-resources-loader
