### ISSUE TITLE
v3.0.0-beta.10 is not split out webpack runtime code

### ISSUE THREAD

**Issue by yangmingshan** [vuejs/vue-cli#1297]
### Version
3.0.0-beta.10

### Reproduction link
no need

### Steps to reproduce
npm run build

### What is expected?
webpack runtime code is split out and inline to html

### What is actually happening?
webpack runtime code is inside app.js

---
webpack optimization.runtimeChunk is disabled by default for zero config reason, see this [issue](https://github.com/webpack/webpack/issues/6683), so need set it to `true` to split out webpack runtime code.

**Comment by yyx990803** [comment]
webpack 4 already handles correct hash for vendor chunks, there's little point in splitting the runtime chunk anymore.
