### ISSUE TITLE
Init prompt requires input to continue

### ISSUE THREAD

**Issue by looterz** [vuejs/vue-cli#13]
When running vue-cli on Windows 10 x64 it just completely freezes. The project scaffold is never generated and no output is shown.

**Comment by kucharzyk** [comment]
I've also run Windows 10 x64 and vue-cli works great for me.

```
vue-cli 1.1.1
node v4.2.2
npm 2.14.7
```

Which version of node do You have?

**Comment by looterz** [comment]
```
node v5.1.2-nightly201512091c1c1a0f2b
npm 3.3.3
vue-cli 1.1.1
```

**Comment by looterz** [comment]
Okay, figured out what I was doing wrong. I was treating the init procedure like NPM's, where you can simply press enter to enter either the default value or a blank value, and it wouldn't continue until I gave it a value, so it seems like a bug.

**Comment by yyx990803** [comment]
Hmm, looks like `commander`'s bug on Windows. On other platforms if you don't provide enough arguments it will auto-print the help message :/

**Comment by Loyalsoldier** [comment]
I find that you must answer every single question the CLI asks then everything is okay.

**Comment by nblackburn** [comment]
I second this

**Comment by nblackburn** [comment]
Figured out all of the fields are required but it doesn't ask again if you hit enter.

**Comment by apieceofbart** [comment]
I confirm the same issue on windows 7. I am guessing this is a bug in [khaos](https://github.com/segmentio/khaos) which is used by vue-cli. I tried to find a fix but khaos is not actively maintained - [example](https://github.com/segmentio/khaos/issues/89)

**Comment by yyx990803** [comment]
@apieceofbart vue-cli now uses a forked khaos at https://github.com/yyx990803/khaos - you can submit PRs there.

**Comment by apieceofbart** [comment]
@yyx990803 thanks for guidance. I tried the fix proposed [here](https://github.com/segmentio/khaos/issues/89) but it didn't solve the issue. Looks like there are cross-platform issues, e.g. there's no such thing as process.env.HOME on windows. I'm a noob but will try my best to tackle that - help is appreciated.

**Comment by looterz** [comment]
@apieceofbart This should work http://stackoverflow.com/a/9081436

**Comment by apieceofbart** [comment]
@looterz thanks I tried that and changing to HOMEPATH but still got error: 
    `TypeError: Path must be a string. Received undefined` in path.js 
I will try to look into that tomorrow.

**Comment by apieceofbart** [comment]
After some digging I found out that issue is in *cli-prompt* module, namely in [listen](https://github.com/carlos8f/node-cli-prompt/blob/master/index.js#L24) function. Hitting enter without any pressing other key before results in *key.name* being set to 'm' not 'return' or 'enter' as we would like to. A quick fix could be to check for *key.sequence* as well.
@yanxyz I noticed vue-cli is using older version of cli-prompt package (0.3.2). Could you guide me how to submit pull request to this version?

**Comment by yyx990803** [comment]
@apieceofbart It's part of the dependency of `prompt-for`, also forked here: https://github.com/yyx990803/prompt-for

**Comment by apieceofbart** [comment]
@yyx990803 I noticed but I still don't know how to do pull request on `prompt-for` dependency (`cli-prompt` in this case). Should I just update package.json of this forked `prompt-for`to get the newest version of `cli-prompt` which is fixed already?

**Comment by yyx990803** [comment]
@apieceofbart thanks a lot for digging into this - I have updated the dependencies for `prompt-for-patched` - can you try re-installing vue-cli and see if it solves the issue?

**Comment by apieceofbart** [comment]
I did reinstall and it looks like it's working fine. Yay! Thanks!

**Comment by yyx990803** [comment]
@apieceofbart awesome!
