### ISSUE TITLE
vue文件中，无法使用babel删除console信息

### ISSUE THREAD

**Issue by lihaizhong** [vuejs/vue-cli#1305]
### Version
3.0.0-beta.10

### Reproduction link
[https://codesandbox.io/s/9l2r1m1v0y](https://codesandbox.io/s/9l2r1m1v0y)

### Steps to reproduce
yarn build 后  发现dist中的js还带有console.log信息。

### What is expected?
能把vue文件中的console自动删除。

### What is actually happening?
没有删除vue文件中的console信息

**Comment by yyx990803** [comment]
本来就没这个功能。

**Comment by lincenying** [comment]
自己在生产环境时, 重写写console方法吧.
