### ISSUE TITLE
VUE CLI with webpack 4 does not support chainWebpack properly

### ISSUE THREAD

**Issue by LanFeusT23** [vuejs/vue-cli#1310]
### Version
3.0.0-beta.10

### Reproduction link
[https://github.com/LanFeusT23/vue-cli-webpack-issue](https://github.com/LanFeusT23/vue-cli-webpack-issue)

### Steps to reproduce
vue create project
Add a vue.config.js file and tap into some loader options

```
// vue.config.js
module.exports = {
  chainWebpack: config => {
    config.module
      .rule('scss')
      .use('sass-loader')
      .tap(options =>
        merge(options, {
          includePaths: [path.resolve(__dirname, 'node_modules')],
        })
      )
  }
}

```

npm run serve

It will throw an error when trying to tap into the loader options

### What is expected?
The options should be a an object with many more properties.

### What is actually happening?
the options object only has the following properties:
{ compilerOpitons: { preserveWhitespace: false } } 

options.loaders.scss throws an exception because options doesn't have any other properties added.

---
This worked fine until webpack 4 was released.

**Comment by yyx990803** [comment]
The internal config has changed in beta.10. Use `css.loaderOptions` instead of tapping the loaders directly.

**Comment by LanFeusT23** [comment]
I'm sorry I'm not sure I follow, where is that css.loaderOptions? Could the docs be updated?

https://github.com/vuejs/vue-cli/blob/dev/docs/webpack.md

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue-cli/blob/dev/docs/config.md

**Comment by LanFeusT23** [comment]
That seems to be used to pass options to CSS pre-processors, in my case sass-loader for .scss files.

I don't need to update the sass-loader, I want to add "sass-resources-loader" to the vue-loader. The `css.loaderOptions` doesn't allow me to update the vue loader.

**Comment by yyx990803** [comment]
Your reproduce steps was just mutating the `sass-loader` options. To add a new loader it would be a bit more complicated to explain because the new CSS rules are a bit different after beta.10, so I'd suggest wait for beta.11 which comes with the better `vue inspect` that outputs hints for tapping internal config.

**Comment by yyx990803** [comment]
There is a vue-loader breaking upgrade as well. See https://vue-loader.vuejs.org/migrating.html

**Comment by yyx990803** [comment]
@andriytyurnikov I'm not sure what your specific problem is. `sass-loader` by default should be using webpack's resolver for imports and should not need the change you mentioned.
