### ISSUE TITLE
VUE_DEV_SERVER_URL in nightwatch plugin leads nowhere

### ISSUE THREAD

**Issue by brandonpittman** [vuejs/vue-cli#1314]
### Version
3.0.0-beta.10

### Reproduction link
[https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/specs/test.js](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-e2e-nightwatch/generator/template/tests/e2e/specs/test.js)

### Steps to reproduce
Run `npm run test:e2e` and watch nightwatch be unable to find anything—then die.

```
Error: Command failed: /~projectpath/node_modules/nightwatch/bin/nightwatch --config /~projectpath/node_modules/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js --env chrome
    at makeError (/~projectpath/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/~projectpath/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

If you run `npm run test:e2e -- --url=http://localhost:8080`—if you have a server up and running—the tests pass just fine.

### What is expected?
I expect the #app element to be to visible.

### What is actually happening?
Nightwatch can't find the #app element because it never loads the page.

When Chrome fires up, the URL in the bar says: **data:,**. After that, it attempts to go to `localhost:8081`, but just dies and fails the tests. Again, passing the --url option on the command line gets the tests to pass.

**Comment by yyx990803** [comment]
Cannot reproduce on a fresh beta.10 install. Please provide an actual reproduction repository.

**Comment by brandonpittman** [comment]
My apologies—it was due to a vue.config.js tweak. I had forgotten that e2e tests spin up in production mode. The *development server* part made me think I wasn't in production mode. The production mode has a different public path, and that was screwing with the test.
