### ISSUE TITLE
Webpack checks for jsx while I'm not even using it :\

### ISSUE THREAD

**Issue by mrg0lden** [vuejs/vue-cli#1315]
### Version
3.0.0-beta.10

### Reproduction link
[https://codesandbox.io/s/93mqk630z4](https://codesandbox.io/s/93mqk630z4)

### Steps to reproduce
I used a configuration with TS, Router, and Vuex
I made a component (same Login.vue included in the minimal reproduction)
I imported this component through another View component
when compiling I get an error `Syntax Error: Expected corresponding JSX closing tag for <Info> (125:0)`
While I didn't even use JSX

### What is expected?
It should compile just as normal

### What is actually happening?
It checks for jsx syntax while It's not used at all.

---
The reproduction doesn't show the problem on codesandbox, it should be used locally
My env specs:
Windows 10 64bit latest release (1803)
Node.js 8.2.1

**Comment by mrg0lden** [comment]
@LinusBorg 
Sorry, I felt too lazy to do that, here it's
https://github.com/mrg0lden/vue-cli-bug

**Comment by mrg0lden** [comment]
Well, I'm using an Interface called Info
```this.info = <Info>obj.data;```
I guess it considers `<Info>` as a jsx tag :\, what shall I do?

**Comment by mrg0lden** [comment]
I used the "as" operator to solve the problem for now, but I guess it needs to be fixed

**Comment by yyx990803** [comment]
Btw, your repro repo doesn't contain the code that leads to the problem you described.

**Comment by mrg0lden** [comment]
@yyx990803 
Oh I forgot to commit the changes I did, sorry for that 😞 
Here it's https://github.com/mrg0lden/vue-cli-bug/blob/master/src/components/Login.vue
at line 123 `<Info>`

**Comment by yyx990803** [comment]
Can't seem to reproduce this in beta.10. I think this problem only existed in beta.9 and before but we have since given `lang="ts"` and `lang="tsx"` separate configuration.

**Comment by mrg0lden** [comment]
@yyx990803 I made sure that I'm using vue-cli beta.10 then I made a new project with typescript using class-component-style and got the same problem.

Here's a very minimal reproduction, after creating the project, in HelloWorld.vue I put 
```
  test = null;
  getInfo() {
      let obj = {
        data: {}
      }
      this.test = <Info>obj.data;
  }
```
Then I get 
```ERROR in HelloWorld.vue.tsx(48,20)
      TS17008: JSX element 'object' has no corresponding closing tag.```
