### ISSUE TITLE
Support node version 6.x, as it still in Maintenance LTS duration

### ISSUE THREAD

**Issue by nick-ChenZe** [vuejs/vue-cli#1316]
### What problem does this feature solve?
Hi, i don't know whether this request is in your roadmap. I think this is necessary, because there are still user under node 6.x. You can use babel to compile another cli file for lower version user. 

### What does the proposed API look like?
 See what `parcel` do [link](https://github.com/parcel-bundler/parcel/blob/master/bin/cli.js)

**Comment by yyx990803** [comment]
What prevents you from upgrading Node to 8.x?

**Comment by yyx990803** [comment]
Honestly, this is probably not going to happen, unless there are a substantial group of users who have strong reasons on why they cannot upgrade Node to 8.x, which is now the active LTS.

**Comment by nick-ChenZe** [comment]
@yyx990803 Thank for your replay.
We have a packaged server for building static files used by multiple departments, there is no independent environment or container to do this thing, so we can not actively upgrade the globally node version. I tried something like using repo `nave` to build a virtual environment. But normal role has no authority to change global variable.
At last, if this is not in your roadmap, it's fine. Thank for your work!
