### ISSUE TITLE
Add a watch mode

### ISSUE THREAD

**Issue by zigomir** [vuejs/vue-cli#1317]
### What problem does this feature solve?
Sometimes you don't want to serve html and other build files with integrated `serve` command.

#### Requirements
`watch` command option needs to take into account `vue.config.js`'s `outputDir` or `--dest`. (I'm guessing this would work out of the box even). I think it's actually same as running `webpack-cli` with `webpack --watch`.

Would you be willing to merge a PR that adds this command / command option?

### What does the proposed API look like?
```bash
vue-cli-service watch
```

or (preferably)

```bash
vue-cli-service build --watch
```

**Comment by yyx990803** [comment]
Sure, we can take a PR for `build --watch`

**Comment by gtso86** [comment]
This new featured have a side effect: since the hash on filename changes every time, the dist folder starting to have all old versions from the same file

![image](https://user-images.githubusercontent.com/319048/40852290-60e1ebc8-65a0-11e8-9fd7-bf7b13ba9734.png)

Besides that, is there a way to allow other flag or something to avoid `vue-cli-service build --watch` add hash in the end of filename? This will helps a lot use this build process when you need run Vue.js apps inside old apps, like my actual scenario: I'm building a Vue app runing inside a legacy app, so my Vue instance is only a div inside a whole old webapp.

**Comment by yyx990803** [comment]
@gtso86 during development you should use `--mode development` for faster rebuilds and the files will not have hashes. And we should probably default to dev mode when `--watch` is used... thoughts @zigomir ?

**Comment by zigomir** [comment]
Yeah, this makes sense. I'm always using `--watch` with `--mode development` and can't think of a good use case when you'd want to have `--watch` within a production mode.

**Comment by akhansari** [comment]
Is there any possibility to activate HMR mode with this command:
`vue-cli-service build --watch --mode development`.

Like: `vue-cli-service build --watch --mode development --hmr`

I would like to say that it's primary on not SPA environments.

**Comment by yyx990803** [comment]
If you are using `--watch`, the files are written to disk, so it's impossible to have HMR for that.

**Comment by akhansari** [comment]
Yes, indeed, before I was using the [webpack-hot-middleware](https://github.com/webpack-contrib/webpack-hot-middleware) with my existing server. But with the CLI I don't have this choice anymore.

I'll try to find an alternative solution or to make webpack-hot-middleware work with the CLI.

**Comment by meteorlxy** [comment]
I met two problems with `vue-cli-service build --watch --mode development`.

1. Lots of `[hash].hot-update.json` are being generated:

![vue-cli](https://user-images.githubusercontent.com/18205362/45432434-79f59c80-b6dc-11e8-9c56-37c1cc47c36e.gif)

2. The assets files are not in the sub directory:

![image](https://user-images.githubusercontent.com/18205362/45432535-ab6e6800-b6dc-11e8-8312-339cbeaf7f2e.png)

`dashboard.js` is supposed to be put into `public/js` dir, but it's in `public/` now.

---

Here's my `vue.config.js`:
```js
module.exports = {
  outputDir: 'public',
  
  pages: {
    dashboard: {
      entry: 'client/src/dashboard/app.js',
      template: 'client/public/index.html',
      filename: '../resources/views/dashboard.blade.php',
      chunks: ['chunk-vendors', 'chunk-common', 'dashboard']
    }
  },

  chainWebpack (config) {
    config.resolve
      .alias
        .set('@', path.resolve(__dirname, 'client/src'))
        .end()
  },
}
```

**Comment by anthonylebrun** [comment]
@meteorlxy I found a workaround, but I'm not 100% sure what the issue is or why it works. Today is my first day using vue-cli or webpack for that matter!

This issue tipped me off: https://github.com/vuejs/vue-cli/issues/1617

Setting the `NODE_ENV` to production changes the output dir structure:

`NODE_ENV=production vue-cli-service build --watch --mode development`

If anyone would explain what's actually going on, that would be awesome :D

**Comment by zigomir** [comment]
@anthonylebrun @meteorlxy 

1.) running `vue-cli-service build --watch` runs in `development` mode by default: [reference](https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/Service.js#L184-L185)
2.) about "`dashboard.js` is supposed to be put into `public/js` dir, but it's in `public/` now": not entirely correct. When you build in `development` mode `@vue/cli` won't extract css into separate file and thus sub-directories `js` and `css` aren't needed. If you wan't to use production like build, with split directories, you can use `vue-cli-service build --watch --mode production`. But that will make rebuilds slower due to minification and all.

**Comment by meteorlxy** [comment]
@zigomir 

Yeah, thanks.

---

1. I know the point, and I just found that `vue-cli-service build --watch` with or without `--mode development` has different behaviors, which means `--watch` is not in "really" `development` mode?

---

2. The `css` sub-dir is not necessray, but I think it's better to have the same directory structure (i.e. `js` sub-dir) in `watch` mode.

I notice that the `output.filename` is modified in `prod.js` to have `js` sub-dir, I think `watch` mode should have similar config:

https://github.com/vuejs/vue-cli/blob/ce335da9da54fbf14681c38f598ffc05082fe12c/packages/%40vue/cli-service/lib/config/prod.js#L6-L9

---

Maybe it's not good to discuss here, I'll try to open another issue for that. 😄

**Comment by meteorlxy** [comment]
@anthonylebrun 

LOL that's really an insteresting workaround 😄 I'll try it out. Thank you!

**Comment by vhanla** [comment]
`yarn build --watch` keeps writing inside outputdir recursively, e.g. I set outputdir to `./public/dist` and many `dist` directories are created (**public/dist/dist/dist/...**) and never stops "compiling" files in each "outputdir".

It is a TypeScript Vue project created with vue cli.

Here is my `vue.config.js` file:

```js
const ManifestPlugin = require('webpack-manifest-plugin')
module.exports = {
  // options...
  outputDir: './public/dist',
  baseUrl: process.env.NODE_ENV === 'production' ? '/dist/' : '/',
  filenameHashing: true,
  configureWebpack: {
    resolve: {
      alias: {
        '@': __dirname + '/resources/src'
      }
    }, 
    entry: {
      app: './resources/src/main.ts'
    },
    plugins: [
      // new StatsPlugin('stats.json'),
      new ManifestPlugin({
        fileName: 'assets.json'
      })
    ]
  }
}
```

BTW: here is my `package.json`
```json
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@types/nprogress": "0.0.29",
    "axios": "^0.18.0",
    "nprogress": "^0.2.0",
    "register-service-worker": "^1.5.2",
    "vue": "^2.5.17",
    "vue-breadcrumbs": "^1.1.2",
    "vue-class-component": "^6.2.0",
    "vue-lazyload": "^1.2.6",
    "vue-property-decorator": "^7.1.1",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.1.0",
    "@types/node": "^10.11.0",
    "@vue/cli-plugin-babel": "^3.0.4",
    "@vue/cli-plugin-pwa": "^3.0.4",
    "@vue/cli-plugin-typescript": "^3.0.4",
    "@vue/cli-service": "^3.0.4",
    "ajv": "^6.5.4",
    "babel-loader": "^8.0.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "typescript": "^3.0.3",
    "vue-template-compiler": "^2.5.17",
    "webpack": "^4.20.2",
    "webpack-manifest-plugin": "^2.0.4",
    "write-file-webpack-plugin": "^4.4.0"
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```

**Comment by krisimmig** [comment]
I have the same problem, integrating a vuejs app into an existing website.
For that I would just need the js/css and put a <div id="app"></div> into the existing site.

For that I actually am not using the dev server but the existing website local server to render the page.

But with the current cli setup I think it is a bit complicated to do so:
The `build --watch` task builds the JS assets into the root folder.
The `build --watch --mode production` uses the /js subfolder.

So I have to either change the vuejs JS inlucde folder everytime I want to deploy the app (from root to /js), or develop in production mode.

Wouldn´t it make more sense to put the js files into the same folder regardless if we are using production or development mode?

**Comment by cappe** [comment]
I also support using JS (and optionally CSS) subdirectories both in development and production mode. I am currently working on a project that uses Vue with CMS. The CMS requires including assets using its own including methods, hence it'd be convenient to fetch the assets from their dedicated directories as opposed to build separate configs for development and production modes.

**Comment by MasterB** [comment]
same problem like @gtso86 
Man, i just need "vue-cli-service build" in --watch mode with the same file and filename results!
Can it be that hard?

**Comment by NateWr** [comment]
> Lots of [hash].hot-update.json are being generated

I also ran into this problem in a situation where I am integrating vue into an existing project and can not use the dev server, but I still want to rebuild the package automatically whenever something changes.

After much searching, the best workaround I found was to [limit and restrict these files](https://stackoverflow.com/a/49642379) to a dir that is in `.gitignore`.

```
module.exports = {
	configureWebpack: {
		output: {
			hotUpdateChunkFilename: <your-dir>,
			hotUpdateMainFilename: <your-dir>
		}
	}
}
```

I would prefer a solution that cleans them up automatically whenever they are generated, if anyone knows of one.

**Comment by TatzyXY** [comment]
I have the same problem. 
When I build with `--watch` then it seems that `vue-cli-service` completely ignores the file `vue.config.js`

This is my `vue.config.js`

```
module.exports = {
    filenameHashing: false,
    publicPath: './webroot/dist/',
    outputDir: './webroot/dist/',
    chainWebpack: config => {
        config.plugins.delete('html')
        config.plugins.delete('preload')
        config.plugins.delete('prefetch')
    }
}
```

**Comment by mosfetish** [comment]
I agree. When running without the built-in serve, it should be possible to have a watch in dev mode that creates the same directory structure, else Vue CLI is too opinionated and means dispensing with the CLI altogether and creating a regular Webpack config.

**Comment by smtxdev** [comment]
@MarkiyanPyts @mosfetish 

Can you confirm that the `vue.config.js` is not used when building with `--watch`? Because for me it seems like that. If that is the case then maybe it's a bug in the view-cli.

**Comment by LinusBorg** [comment]
It is using the config file.

The only thing that `--watch` changes, it this:

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/build/index.js#L143-L147

Which only sets [weback's `watch` option](https://webpack.js.org/configuration/watch/#watch) to true.

**Comment by smtxdev** [comment]
@LinusBorg 

This is my `vue.config.js`

```
module.exports = {
    filenameHashing: false,
    publicPath: './webroot/dist/',
    outputDir: './webroot/dist/',
    chainWebpack: config => {
        config.plugins.delete('html')
        config.plugins.delete('preload')
        config.plugins.delete('prefetch')
    }
}
```

When I build with `--watch` then it feels like `vue.config.js` is completely ignored. The files are not written to `/webroot/dist/`. If I use `--watch --mode production` everything works fine and my `vue.config.js` seems to be used.

**Comment by mosfetish** [comment]
> @MarkiyanPyts
> 
> Can you confirm that the `vue.config.js` is not used when building with `--watch`? Because for me it seems like that. If that is the case then maybe it's a bug in the view-cli.

vue.config.js is being used. This is mine:

...
module.exports = {
    outputDir: './public/'
}
...

And in both --watch and non --watch modes the files are written to ./public (the default is ./dist)

My package.json script commands are:

...
    "dev": "vue-cli-service build --watch --mode development",
    "build": "vue-cli-service build --mode production"
...

The problem is that in --watch mode OR in --mode development, a different directory structure is created, as already noted. 

--watch with --mode production creates the full directory structure, as desired, but production mode is not wanted during development.

**Comment by ijunaid8989** [comment]
I am doing this 

```
"dev": "vue-cli-service build --watch --mode development",
```

it only creates 

```
  File                     Size                     Gzipped

  ../priv/static/app.js    18391.72 KiB             3172.99 KiB

  Images and other types of assets omitted.

 DONE  Build complete. Watching for changes...
```

why not any CSS files?
