### ISSUE TITLE
vue create my-project did nothing

### ISSUE THREAD

**Issue by pytong** [vuejs/vue-cli#1318]
### Version
2.9.3

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
```vue create my-project```

### What is expected?
Create a project named my-project.

### What is actually happening?
The command finishes in 1 second with no error but no project has been created.

---
Details of my OS:
macOS High Sierra
Version 10.13.4

**Comment by LinusBorg** [comment]
`vue create` is a command of vue-cli 3.0.0(-beta.*)
