### ISSUE TITLE
iview-loader 配置没生效

### ISSUE THREAD

**Issue by 531431988** [vuejs/vue-cli#1319]
### Version
3.0.0-beta.10

### Reproduction link
[https://www.iviewui.com/docs/guide/iview-loader](https://www.iviewui.com/docs/guide/iview-loader)

### Steps to reproduce
chainWebpack: config => {
      config.module
        .rule('vue')
        .use('iview')
        .loader('iview-loader')
        .options({prefix: false})
  },

### What is expected?
https://www.iviewui.com/docs/guide/iview-loader

### What is actually happening?
可以直接写 <Switch> 和 <Circle> 这两个标签；
参数 prefix 设置为 true 后，所有 iView 组件标签名都可以使用前缀 i-，例如 <i-row>、<i-select>

**Comment by yyx990803** [comment]
这样的前置 loader 用法经测试是没有问题的，请提供可以复现的 repo。另外建议先给 iview-loader 提 issue。
