### ISSUE TITLE
a surprising bug when run `vue init`

### ISSUE THREAD

**Issue by uniquexiaobai** [vuejs/vue-cli#132]
# a surprising bug when run `vue init`
if current directory have the file **_vue.js_**, then when you run command `vue init`, nothing happened but the file **_vue.js_** was opened.
when you delete the file **_vue.js_**, then run command `vue init`, all is ok !

**Comment by zigomir** [comment]
@uniquexiaobai I couldn't reproduce this. I'm suspecting there might be something with your shell configuration that does that. Maybe it runes every `.js` file with node or something?

**Comment by uniquexiaobai** [comment]
@zigomir My operating system is win10, this bug still exists. what system do you use ?

**Comment by zigomir** [comment]
I use latest OSX. At home we have another Win10 PC so I'll try it out there too.

**Comment by zigomir** [comment]
@uniquexiaobai I tried on Win 10 now and it is what I first thought. Node tries to run your vue.js file first. If you write in just console.log in this vue.js file you will get something like this image.
![vuewindows](https://cloud.githubusercontent.com/assets/957321/17405292/cf0096ee-5a13-11e6-93ac-441cddbd0a61.PNG)

This is more like cmd/windows/node issue so I don't think we can do in this repo anything about it.
