### ISSUE TITLE
Consider support webpack-serve

### ISSUE THREAD

**Issue by zlab** [vuejs/vue-cli#1323]
### What problem does this feature solve?
webpack-dev-server base on express.js, consider support webpack-serve, base on koa ?

https://github.com/webpack-contrib/webpack-serve

### What does the proposed API look like?
vue-cli-service

**Comment by posva** [comment]
It's funny that the only thing you talk about is that it uses koa instead of express.
The whole idea of webpack-serve is to use modern features (like websockets) and ship less code at the cost of dropping support for older browsers

**Comment by yyx990803** [comment]
No because it doesn't support older browsers.

**Comment by ChristianStornowski** [comment]
I don't think that anyone want to use a Safari or iOS Safari older then 7 or an Android Browser older then 4.4. for development. The only problematic browser could be ie9. But we should consider that webpack-serve is using for development.
In my project i'm develop in 1 - 3 browser and use the production artifacts to tests against other browsers.

Why not give us choice to use webpack-serve or webpack-dev-server. The last one is in maintenance mode and webpack in the newest version officially supports webpack-serve options. :-)

https://caniuse.com/#feat=websockets

https://github.com/vuejs/vue-cli/blob/v3.0.0-beta.15/packages/%40vue/cli-service/generator/index.js
https://github.com/vuejs/vue-cli/blob/v3.0.0-beta.15/packages/%40vue/cli-ui-addon-webpack/package.json
https://github.com/vuejs/vue-cli/blob/v3.0.0-beta.15/packages/%40vue/cli-ui/package.json

**Comment by yyx990803** [comment]
It explicitly drops support for all IE, and all browsers that do not support ES2015. Maintaining compat for both is extra maintenance burden for us so you need to show some substantial benefits of using webpack-serve except for it being newer.
