### ISSUE TITLE
Use XDG_CONFIG_HOME for the .vuerc file

### ISSUE THREAD

**Issue by tristan957** [vuejs/vue-cli#1325]
### What problem does this feature solve?
Not cluttering my HOME directory

### What does the proposed API look like?
Changing the default directory and using `$HOME` as a backup if `XDG_CONFIG_HOME` does not exist

**Comment by yyx990803** [comment]
This is a niche use case but we'd welcome a PR.

**Comment by tristan957** [comment]
Awesome. Could you point me to where the create command starts and I'll get working on that

**Comment by tristan957** [comment]
Never mind found it.
