### ISSUE TITLE
Display inline-block not working properly for buttons

### ISSUE THREAD

**Issue by anishdcruz** [vuejs/vue-cli#1329]
### Version
3.0.0-beta.9

### Reproduction link
[https://codesandbox.io/s/zqkzlxqlz4](https://codesandbox.io/s/zqkzlxqlz4)

### Steps to reproduce
1. Simply scaffold new project remove all styles.
2. create two button on App.vue
 

### What is expected?
By default inline-block should have margin between elements

### What is actually happening?
The margin between two or more elements is missing.

---
I have attached a plain html code, showing the actual result.

https://codesandbox.io/s/qv9onro02q

Image:

Result from vue-cli:

<img width="188" alt="screen shot 2018-05-19 at 11 07 31 am" src="https://user-images.githubusercontent.com/2182620/40266506-e7fd4f04-5b54-11e8-8df5-efa504bb2ce0.png">

Result from plain html and js:

<img width="206" alt="screen shot 2018-05-19 at 11 07 44 am" src="https://user-images.githubusercontent.com/2182620/40266507-e824c89a-5b54-11e8-93f7-b2e3001bcf32.png">

Thanks!

**Comment by Akryum** [comment]
Hi, thanks for posting this issue but this has nothing to do with vue-cli itself. It's related to vue-loader and more specifically to vue-template-compiler which is removing the whitespaces between your buttons. You can configure that in vue-loader options like [described in the documentation](https://vue-loader.vuejs.org/options.html#compileroptions).
