### ISSUE TITLE
Reference static SVG

### ISSUE THREAD

**Issue by algil** [vuejs/vue-cli#1333]
### Version
3.0.0-beta.10

### Reproduction link
[https://github.com/algil/vue-cli-demo](https://github.com/algil/vue-cli-demo)

### Steps to reproduce
Run the app with `yarn serve` and check svg icons are not shown.

I’m trying to use a SVG sprite to load custom icons. That’s how I use it in a vue component (two options):

#### Adding `icons.svg` in assets folder:

```html
<svg class="icon-menu">
  <use xlink:href="./assets/icons.svg#menu"></use>
</svg>
```

#### Adding `icons.svg` in public folder:

I've linked icons.svg in index.html

```html
<link href="<%= BASE_URL %>icons.svg">
```

The it's used like follow:

```html
<svg class="icon">
   <use xlink:href="#menu"></use>
 </svg>
```

I've tried other way but with no luck.

### What is expected?
Icons should be shown in the page

### What is actually happening?
SVG icons "appear" in the DOM but nothing is shown

**Comment by yyx990803** [comment]
Your SVG must be actually rendered in the HTML to be referable. `<link href>` doesn't work.

As for referencing directly in `assets` with an id hash, it's not supported by the built-in config, as that's a pretty rare use case. You will need custom loader configurations for SVGs to handle that.
