### ISSUE TITLE
Is there any milestone for final release ?

### ISSUE THREAD

**Issue by rajagopalx** [vuejs/vue-cli#1341]
### What problem does this feature solve?
Is there any ETA or milestone for the final release?

### What does the proposed API look like?
Thank you.

**Comment by Akryum** [comment]
Thanks for opening an issue. There are still a few things in the works, such as:

- Bug fixes
- A new powerful API to modify the entry file
- Releasing the UI!

**Comment by rajagopalx** [comment]
Thanks for the quick reply.
