### ISSUE TITLE
Can I install vue development environment offline?

### ISSUE THREAD

**Issue by mayefeng** [vuejs/vue-cli#1343]
### Version
2.0.0

### Reproduction link
[https://jsfiddle.net/50wL7mdz/336138/](https://jsfiddle.net/50wL7mdz/336138/)

### Steps to reproduce
Can I install vue development environment offline?

### What is expected?
Can I install vue development environment offline?

### What is actually happening?
Can I install vue development environment offline?

---
Can I install vue development environment offline?

**Comment by mayefeng** [comment]
@yyx990803 @Jinjiang  please help me for this issue,thanks

**Comment by yyx990803** [comment]
No.
