### ISSUE TITLE
UMD build "window is not defined"

### ISSUE THREAD

**Issue by randyhoulahan** [vuejs/vue-cli#1348]
### Version
3.0.0-beta.11

### Reproduction link
[https://github.com/vuejs/vue-cli/issues/new](https://github.com/vuejs/vue-cli/issues/new)

### Steps to reproduce
Run UMD build component in nuxt or SRR

### What is expected?
We should be able to :
module.exports = {
  output: {
    globalObject: 'typeof self !== \'undefined\' ? self : this'
  }
}
"Invalid options in vue.config.js: "output" is not allowed"

### What is actually happening?
"Invalid options in vue.config.js: "output" is not allowed"
related to webpack bug https://github.com/toji/gl-matrix/issues/311

**Comment by yyx990803** [comment]
This is something we probably need to fix because with `--target lib` the output configurations cannot be modified.
