### ISSUE TITLE
Option of disable the automatic git initialization

### ISSUE THREAD

**Issue by harekazewin** [vuejs/vue-cli#1352]
### What problem does this feature solve?
Some users like me may have multiple identities to initialize different projects. Reset the config of git is not hard but it would be better if vue-cil give users options to let user choose not to initialize git when creating new apps.

### What does the proposed API look like?
1.When creating the app using vue-cli, show an option to use global config to git init or not to initialize git after choosing "manually select features".

2.When the related git's global setting is not set, disable the initialization by default.

**Comment by yyx990803** [comment]
`vue create foo --git false`
