### ISSUE TITLE
import css as a string

### ISSUE THREAD

**Issue by ex3xeng** [vuejs/vue-cli#1357]
1. vue create project (install vue-cli last version)

in **main.js**  i try `import styles from './test.css'` in my test.css i have two class...

in `console.log(styles)` or `console.log(styles.className)` i found **empty object** or **undefined**, why it's happend?

by the way `styles.toString()` doesn't work, in vue-cli doc i found https://github.com/css-modules/css-modules but he is doesn't work too.

same i found such a construction for writing:

```
var myStyle = require('./test.css');
myStyle.use(); //inject it via a `<style>` element
myStyle.unuse(); //removes it
```

http://tomasalabes.me/blog/web-development/2016/09/13/Webpack-Series-Part-4.html

but it also does not work...

maybe i do something wrong? sorry for it, but can someone explain me?

**Comment by TheJaredWilcurt** [comment]
`npm install --save-dev raw-loader`

```js
const styles = require('!!raw-loader!../public/file.css');

// object
console.log(styles);

// string of original file
console.log(styles.default);
```
