### ISSUE TITLE
HUAWEI phone Android own browser error prompt：Uncaught SyntaxError: Duplicate data property in object literal not allowed in strict mode

### ISSUE THREAD

**Issue by andorcba** [vuejs/vue-cli#1365]
### Version
2.9.3

### Reproduction link
[http://m.xiaobaijinfu.com/dist](http://m.xiaobaijinfu.com/dist)

### Steps to reproduce
Direct open

### What is expected?
Rendering the content of the page

### What is actually happening?
Page is not rendered

---
none

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
