### ISSUE TITLE
vue-cli-service build: Unterminated regular expression

### ISSUE THREAD

**Issue by u3u** [vuejs/vue-cli#1367]
### Version
3.0.0-beta.11

### Reproduction link
[https://github.com/MoePlayer/vue-aplayer](https://github.com/MoePlayer/vue-aplayer)

### Steps to reproduce
vue-cli-service build

### What is expected?
build passed

### What is actually happening?
Module build failed: Thread Loader (Worker 0)
App.tsx: Unterminated regular expression

---
https://app.netlify.com/sites/aplayer/deploys/5b07f23e11b73b5571d1c034

**Comment by yyx990803** [comment]
Please try to provide a boiled down, **minimal** repro.

**Comment by u3u** [comment]
@yyx990803 Please see this: https://github.com/u3u/vue-cli-service-jsx
