### ISSUE TITLE
css modules可选配置

### ISSUE THREAD

**Issue by zlab** [vuejs/vue-cli#1369]
### What problem does this feature solve?
目前想使用css modules，必须命名为xxx.module.css，希望增加一个可选配置，xxx.css也能使用css modules，因为组件太多，一个组件(index.js)一个样式文件(index.scss)，方便打包按需加载

``` js
import styles from './index.scss'
```

### What does the proposed API look like?
`cli-service/lib/config/css.js`

``` js
// line 53
const normalRule = baseRule.oneOf('normal')
applyLoaders(normalRule, false)

// applyLoaders(normalRule, options.css.modules)
```

``` js
// 配置文件增加modules
css: {
    modules: true,
}
```

**Comment by yyx990803** [comment]
Closed via 1e98d96
