### ISSUE TITLE
我已经弄了一个草稿版的vue+loopback的项目,希望有loopback+vue的脚手架

### ISSUE THREAD

**Issue by qxl1231** [vuejs/vue-cli#137]
loopback是一个很流行的后端框架,优于express,官方能否出一个loopback+vue+vue-route
r ,babel等的脚手架? 这样前端代码直接生成在client中,对于项目的整体startup是提升很多效率的.

> 草稿版本:https://github.com/qxl1231/app_update_server  还有很多不足,但是初步已经集成在一起.

借鉴了日本一个用户的思路,但是由于我对vue的理解还是不行的,所以肯定还有很多地方可以改进,望指教,或者有空的话,麻烦出一个官方的cli工具咯

**Comment by posva** [comment]
Thanks for sharing your boilerplate!
You're free to create a template from it and people will be able to use it with `vue qxl1231/app_update_server new_project`
To write your own template I recommend starting from an existing one or reading [how to start one](https://github.com/vuejs/vue-cli#writing-custom-templates-from-scratch)
