### ISSUE TITLE
babel.config.js generated when asking to store configs in package.json

### ISSUE THREAD

**Issue by lsorber** [vuejs/vue-cli#1370]
### Version
3.0.0-beta.11

### Steps to reproduce
1. vue create myproject
2. select configs as part of package.json
3. notice that babel config is in babel.config.js

### What is expected?
Babel config inside package.json.

### What is actually happening?
Babel config in babel.config.js.

**Comment by yyx990803** [comment]
This is intentional because this is currently the only way to ensure the same babel config is applied to dependencies in Babel 7.

**Comment by dbpolito** [comment]
> This is intentional because this is currently the only way to ensure the same babel config is applied to dependencies in Babel 7.

Heya, is this still a thing?

I tried to find why to relate here and someday in the future we be able to move to `package.json`, maybe we already can 😄
