### ISSUE TITLE
-g / --git cut the string where there is a ":" character instead of taking the full commit message

### ISSUE THREAD

**Issue by TotomInc** [vuejs/vue-cli#1374]
### Version
3.0.0-beta.11

### Reproduction link
[https://github.com/TotomInc/vue-cli-bug/commits/master](https://github.com/TotomInc/vue-cli-bug/commits/master)

### Steps to reproduce
- `vue create my-app -g chore(vue-cli): init repo with vue-cli (ts + vuex + router)`
- `cd my-app`
- `git log`

### What is expected?
When running `git log` we expect to see a commit message like `chore(vue-cli): init repo with vue-cli (ts   vuex   router)`.

### What is actually happening?
Instead we got `chore(vue-cli):`.

Can't add a reproduction link, so I linked to a repo with the bug.

This can be an issue when trying to follow commitizen convention.

**Comment by Akryum** [comment]
This is how terminals work when you use space, you have to wrap the whole argument between quotes:

```
vue create my-app -g "chore(vue-cli): init repo with vue-cli (ts + vuex + router)"
```

This has nothing to to with vue-cli 😸

**Comment by TotomInc** [comment]
Whoops, my bad. Maybe edit the help given when running `vue create -h`? Actually it looks like this:

```
Options:

...
    -g, --git [message]             Force / skip git intialization, optionally specify initial commit message
...
```

We could replace `-g, --git [message]` by `-g, --git "message"` or `-g, --git ["message"]`?

**Comment by posva** [comment]
I think the help message is generated. Having `[]` (with the description name inside) is the unix convention 😄 
The same happens if you do `git commit -m only the word only will be in the message`

**Comment by yyx990803** [comment]
This is really command line conventions that applies anywhere, you have to wrap your strings yourself...
