### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by 327326724** [vuejs/vue-cli#138]
Npm run dev throw out this error.How can i fix it;
![luxumr zrzjs wt xbh](https://cloud.githubusercontent.com/assets/8953012/17390721/4a043c28-5a42-11e6-9c29-28e6214ec53b.png)

**Comment by octavioamu** [comment]
Hi @327326724 take a look if your not already using port 8080

**Comment by 327326724** [comment]
I've fixed it with update the system os form win7 to sp1
