### ISSUE TITLE
https://new-issue.vuejs.org/?repo=vuejs/vue-cli

### ISSUE THREAD

**Issue by xcsweb** [vuejs/vue-cli#1380]
### Version
2.9.3

### Reproduction link
[https://github.com/xcsweb/error_project.git](https://github.com/xcsweb/error_project.git)

### Steps to reproduce
![](https://ws1.sinaimg.cn/large/af65cd95gy1frr3ctpb6fj20gl08s0td.jpg)

### What is expected?
vue init webpack  first-project

### What is actually happening?
![](https://ws1.sinaimg.cn/large/af65cd95gy1frr3ctpb6fj20gl08s0td.jpg)

**Comment by Akryum** [comment]
https://github.com/vuejs/component-compiler-utils/issues/14
