### ISSUE TITLE
Cannot find module 'cache-loader/package.json'

### ISSUE THREAD

**Issue by Shokas** [vuejs/vue-cli#1384]
### Version
3.0.0-beta.11

### Reproduction link
[https://github.com/Shokas/vue-error-test-project](https://github.com/Shokas/vue-error-test-project)

### Steps to reproduce
npm install
npm run serve

### What is expected?
Get project served at localhost:8080

### What is actually happening?
npm complaining about missing module, after installing one after another, it gets to this error "vue-loader was used without the corresponding plugin. Make sure to include VueLoaderPlugin in your webpack config."

---
$ vue create [project]
pick default preset (babel, eslint)
$ cd [project]
$ npm run serve

**Comment by zlab** [comment]
npm i cache-loader -D

**Comment by Shokas** [comment]
It does not help. As I wrote, errors about missing modules keep coming:
Cannot find module 'eslint-loader/package.json'
Cannot find module 'vue-loader/package.json'
Cannot find module 'babel-loader/package.json'
Cannot find module 'babel-core'
Cannot find module 'eslint-plugin-vue'
and finally 
"vue-loader was used without the corresponding plugin. Make sure to include VueLoaderPlugin in your webpack config."

2 Solutions I've found:
downgrade vue-loader to 14.2.2 or update node, npm and vue-cli to latest versions

**Comment by zlab** [comment]
@yyx990803 
### `cli-plugin-babel` `package.json`锁定了`@babel/core`版本，当我在项目的package.json里面安装
`  "@babel/core": "^7.0.0-beta.49"`，会造成版本冲突，会报错
```
Cannot find module 'babel-loader/package.json' #1384
```

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-babel/package.json
```
"dependencies": {
    "@babel/core": "7.0.0-beta.47",
    "@vue/babel-preset-app": "^3.0.0-beta.12",
    "babel-loader": "^8.0.0-0"
  },
```
