### ISSUE TITLE
Invalid options in vue.config.js: "compiler" is not allowed

### ISSUE THREAD

**Issue by sp00x** [vuejs/vue-cli#1387]
### Version
3.0.0-beta.12 and .beta.11

### Steps to reproduce
Include { compiler: true }  in the vue.config.js file (because I need run-time compiling!)
Try running "npm run serve"

### What is expected?
That it works, like in 3.0.0-beta.10, and like in the documentation which says is valid: https://github.com/vuejs/vue-cli/blob/dev/docs/config.md  

### What is actually happening?
 ERROR  Invalid options in vue.config.js: "compiler" is not allowed

---
I assume it's been renamed, as "kittens: true" also fails. If so, the documentation needs updating

**Comment by LinusBorg** [comment]
Indeed: 

https://github.com/vuejs/vue-cli/blob/dev/CHANGELOG.md#code-refactoring

We'll update the docs.
