### ISSUE TITLE
Laravel Valet like service for Vue CLI projects

### ISSUE THREAD

**Issue by morrislaptop** [vuejs/vue-cli#1390]
### What problem does this feature solve?
- Avoid having to manually start `serve` for each project
- Add the ability to share sites using local tunnels
- Having developer friendly test sites using like `my-project.test` instead of `localhost:8080`

### What does the proposed API look like?
A single node service which would handle all requests. This service would spin up the dev servers on demand and then proxy requests to each dev server based on the domain name. 

If the feature is deemed worthwhile by the community, I'm happy to help start putting this together :)

**Comment by yyx990803** [comment]
This has to be a separate project rather than something provided by vue-cli. Maybe @adamwathan will be interested? ;)

**Comment by morrislaptop** [comment]
@yyx990803 what about as part of ui?
@adamwathan what are your thoughts?

**Comment by morrislaptop** [comment]
@yyx990803 @adamwathan 

I've created a Laravel Valet custom driver which does this - https://github.com/morrislaptop/VueServeValetDriver

For each domain name, it spins up a webpack dev server on a unique port according to the domain name provided. 

For example a request to `my-project.test` would spin up a server at `http://localhost:1032` and then proxy other requests to this server. 

Should be good to go once #1421 is released.

**Comment by yyx990803** [comment]
That sounds pretty neat for Laravel users!

**Comment by morrislaptop** [comment]
Not just Laravel users! Valet is pretty general purpose, but it suffers the same fate as Laravel Mix, which is also a very good general purpose tool...
