### ISSUE TITLE
behaviour of `test:unit --watch` changed?

### ISSUE THREAD

**Issue by doppelreim** [vuejs/vue-cli#1391]
### Version
3.0.0-beta.11

### Reproduction link
[https://github.com/doppelreim/vue-test-app/tree/test-watch-behaviour](https://github.com/doppelreim/vue-test-app/tree/test-watch-behaviour)

### Steps to reproduce
Install dependencies: `npm install`

Run the unit-tests in "watch-mode": `./node_modules/.bin/vue-cli-service test:unit --watch`

After they have passed, open "Other.spec.ts" and change something. For example, change the expectation from 8 to 7.

Save the file.

The tests are run again, automatically (because of `--watch`)

### What is expected?
At least in beta6, only the tests contained in the file that changed are run again.

### What is actually happening?
In beta12, all tests are run again.

---
I'm not sure, what the actually intended behaviour is. Maybe it should always have been like this. But it is different :)

**Comment by yyx990803** [comment]
This is fixed also by e17f78c

**Comment by Oliboy50** [comment]
@yyx990803 the `--watch` option seems to be broken in the latest release (at least using the `cli-plugin-unit-jest`)

I tried both from the `UI` and from my own terminal, and both using `npm` and `yarn`:
- the `UI` outputs nothing, it just waits
- my own terminal outputs `Determining test suites to run...` and then waits

```shell
yarn run v1.7.0
$ vue-cli-service test:unit --watch
```

```json
    "@vue/cli-plugin-unit-jest": {
      "version": "3.0.0-rc.3",
      "resolved": "https://registry.npmjs.org/@vue/cli-plugin-unit-jest/-/cli-plugin-unit-jest-3.0.0-rc.3.tgz",
      "integrity": "sha512-A+ktUdIL856YEpeUVYH+sxccJsgNQ4LA9zH7qNr1bN7pTPEBA7xTNWYbySucwYbhIex66fuRxzQ6Az6MK/DEyw==",
      "dev": true,
      "requires": {
        "@vue/cli-shared-utils": "^3.0.0-rc.3",
        "babel-jest": "^23.0.1",
        "babel-plugin-transform-es2015-modules-commonjs": "^6.26.2",
        "jest": "^23.1.0",
        "jest-serializer-vue": "^1.0.0",
        "jest-transform-stub": "^1.0.0",
        "vue-jest": "^2.6.0"
      }
    },
```

FYI, when I run the `test:unit` command without the `--watch` flag, the tests all run correctly.

**Comment by light24bulbs** [comment]
what is the solution?

**Comment by RickMeijer** [comment]
Old issue, but maybe some lone googler can use this: For me running `npm run test:unit -- --watch` works as expected on a newly instantiated project.

See https://docs.npmjs.com/cli/run-script
> npm will pass all the arguments after the -- directly to your script:

**Comment by aniforprez** [comment]
Trying to send `--watch` as an option always gives me the following error

```
Error: `fsevents` unavailable (this watcher can only be used on Darwin)
    at new FSEventsWatcher (/Users/anirudhs/Documents/personal-projects/reddit-saved/node_modules/sane/src/fsevents_watcher.js:41:11)
    at createWatcher (/Users/anirudhs/Documents/personal-projects/reddit-saved/node_modules/jest-haste-map/build/index.js:780:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/anirudhs/Documents/personal-projects/reddit-saved/node_modules/jest-haste-map/build/index.js:936:44)
    at _buildPromise._buildFileMap.then.then.hasteMap (/Users/anirudhs/Documents/personal-projects/reddit-saved/node_modules/jest-haste-map/build/index.js:355:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by ezpzlmnsqz1337** [comment]
> Old issue, but maybe some lone googler can use this: For me running `npm run test:unit -- --watch` works as expected on a newly instantiated project.
> 
> See https://docs.npmjs.com/cli/run-script
> 
> > npm will pass all the arguments after the -- directly to your script:

This worked for me, after 1 day of trying almost everything, this finally worked!

**Comment by aniforprez** [comment]
Yo thanks for reminding me. The error fixed itself when I reinstalled the supported version of jest. I'm happy you found this after 1 day. I tried so many things for 2 days until I found this ridiculously simple solution. I felt like a fool :sob:

**Comment by baamenabar** [comment]
I jus added `"test:unit:watch": "vue-cli-service test:unit --watch"` to the `scripts` section in my `package.json`, works like a charm.
