### ISSUE TITLE
Cypress CLI options for cypress run are not really supported.

### ISSUE THREAD

**Issue by Octirke** [vuejs/vue-cli#1393]
### Version
3.0.0-beta.11

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
I'm trying to pass cypress cli option to `npm run test:e2`
```bash
npm run test:e2e -- -b electron
error: unknown option `-b'
```
Nothing really works.

### What is expected?
I can use all cypress cli options

### What is actually happening?
 All options outside the classic ones --headless --mode --url don't work.

---
Maybe i'm not using the correct command. If this is the real problem, it should be documented and I can PR that if you want.

**Comment by yyx990803** [comment]
The doc was a bit out of date - the default `test:e2e` runs `cypress open` so it accepts only `cypress open` args. It only accepts `cypress run` args if using `--headless` flag.

In addition there's also a related bug that is fixed in the commit above.
