### ISSUE TITLE
How to add ssr to a vue-cli 3 project?

### ISSUE THREAD

**Issue by leonardovilarinho** [vuejs/vue-cli#1398]
In all SSR tutorials with Vue that I found the webpack merge is used to create a configuration for the server. Could you explain quickly how I would do this in the design created by vue-cli 3? I am also using the PWA plugin.

My current code is:

factory.js
```javascript
...
export default () => new Vue({
  router,
  store,
  render: h => h(App)
})
```

server.js
```javascript
const express = require('express')
const { resolve } = require('path')
const fs = require('fs')

global.Vue = require('vue')
const layout = fs.readFileSync(resolve(__dirname, './dist/index.html'), 'utf8')
const renderer = require('vue-server-renderer').createRenderer()

const app = express()
app.use('/dist', express.static(
  resolve(__dirname, './dist')
))

app.get('/ssr', (req, res) => {
  renderer.renderToString(
    require(resolve(__dirname, './src/factory'))(),
    (err, html) => {
      if (err) {
        console.error(err)
        return res.status(500).send('Server error')
      }
      res.send(layout.replace('<div id="app"></div>', html))
    }
  )
})

app.get('*', (req, res) => {
  res.send(layout)
})

app.listen(process.env.PORT || 3000, () => console.log('Running :3000'))
```

I do not understand how to do it, as it should not be taking the factory.js from the raw code, but compiled.

**Comment by eddyerburgh** [comment]
Here's an example project—https://github.com/eddyerburgh/vue-cli-ssr-example

**Comment by leonardovilarinho** [comment]
@eddyerburgh thank you so much! I would never get this result, thanks for your help

**Comment by EDiaos** [comment]
Hi , I write a project for cli3-ssr-project example, see [here](https://github.com/EDiaos/vue-cli3-ssr-project)

**Comment by 1isten** [comment]
For vue-cli 4 I've implemented [an example](https://github.com/1isten/vue-cli-ssr) following the [official vue ssr guide](https://ssr.vuejs.org/)(see the [second commit](https://github.com/1isten/vue-cli-ssr/commit/75fed43a3b2082b9c95f487bcffbfed557529930), the first commit is just a default vue cli 4 project created via `vue create xxx`), the key point is to use the [`configureWebpack`](https://cli.vuejs.org/dev-guide/plugin-api.html#configurewebpack) option to integrate your webpack configuration into vue-cli's build process. Hope that helps.

**Comment by diachedelic** [comment]
I've [created a gist](https://gist.github.com/diachedelic/5078ef86097d675b56aa157a05c67286) with a diff condensing all of @1isten 's modifications to a default vue cli 4 project
