### ISSUE TITLE
Beta 15, Cannot create new project

### ISSUE THREAD

**Issue by eaf-josephportello** [vuejs/vue-cli#1408]
### Version
3.0.0-beta.15

### Reproduction link
NA

### Image

![vue-create-example](https://user-images.githubusercontent.com/34985835/40738626-a6ffced8-6409-11e8-8116-2660a9164f1e.gif)

### Steps to reproduce

OSX: 10.14.4

Attempted via Bash and ZSH.

Install from scratch or upgrade to latest VUE CLI, Beta 15.

npm install -g vue-cli
or 
npm i -g vue-cli 

Then attempt to create a new project:

vue create my-project

### What is expected?
It will prompt for the creation of a new project.

### What is actually happening?
After running vue create my-project, it immediately returns to command line with no project created or prompt for new project settings.

---
Upgraded to the new CLI due to prompt from creating a new project on Beta 13.

**Comment by Akryum** [comment]
What does `vue --version` output?

**Comment by yyx990803** [comment]
You are using the old 2.x...
3.x is `@vue/cli`, not `vue-cli`.

**Comment by Akryum** [comment]
Oh right, didn't catch that detail in the commands :smile_cat:

**Comment by Akryum** [comment]
@yyx990803 Maybe we could update vue-cli and display a message about @vue/cli?

**Comment by eaf-josephportello** [comment]
@yyx990803 You're right. In my haste I didn't verify it. Thanks for pointing it out.

Regards

**Comment by yyx990803** [comment]
@Akryum just did in 2.9.4
