### ISSUE TITLE
vue-cli 创建项目的时候出现connect ETIMEDOUT 错误，请问如何解决？

### ISSUE THREAD

**Issue by chuquancai** [vuejs/vue-cli#141]
我在用vue-cli创建项目的时候出现了connect ETIMEDOUT 192.30.252.137:443 这个问题。
是最近才出现的，之前还是好好的。我也没改过什么东西，突然就不能用了。。没搜到相关的信息，不知道如何解决呢？

`PS F:\myWeb\1guanggao> vue init webpack testTemp

   vue-cli · connect ETIMEDOUT 192.30.252.137:443`

尝试ping这个地址，发现ping不通，超时

vue：2.1.1
node：4.4.7
npm：3.10.5

**Comment by v8xm** [comment]
I met the same problem.

**Comment by summerGreenTea** [comment]
@yyx990803   求尤大解惑

**Comment by yyx990803** [comment]
This means either your network has problem connecting to GitHub, or GitHub's server was down.

**Comment by luck2011** [comment]
Or maybe you should set HTTP proxy for the `request` method in both `vue-init` and `vue-list` two files. See [https://segmentfault.com/q/1010000005998968](https://segmentfault.com/q/1010000005998968) :smile:

**Comment by 17khba** [comment]
请参考http://huangtengfei.com/2015/03/set-proxy-for-npm-and-git-and-bower/
我设置完就解决这个问题了

**Comment by chuquancai** [comment]
不知道你们的host文件有没有改过？

因为我的改过host翻墙，后来用lantern翻墙。今天无意中看到一个说把host相关翻墙配置删了就可以的，我删了github相关的配置结果真的就可以了。。。如果你们的host也有改过的可以试试看！

个中原因不懂，不过我猜测有没有可能是host文件配置跟代理软件的相关配置冲突了？

**Comment by huangming1994** [comment]
@chuquancai  Thx, 直接删掉host文件就好了。
