### ISSUE TITLE
vue init fails on 2.9.4

### ISSUE THREAD

**Issue by mswaidan** [vuejs/vue-cli#1410]
I'm having an issue with 2.9.4. I can't open an issue with the Vue Issue Helper because 2.9.4 is not available from the version list.

**Steps:**
npm install -g vue-cli
vue init webpack my-project

**Expected:**
Scaffold out my-project

**Actual:**

```
Unknown command init.
vue-cli · Failed to download repo vuejs-templates/[object Object]: Response code 404 (Not Found)
```
**Comments:**
I've reproduced this on multiple Ubuntu 16.04 systems. Confirmed that 2.9.3 on these systems works as expected.

**Comment by william807803** [comment]
same issue:
Unknown command init.


 vue-cli · Failed to download repo vuejs-templates/[object Object]: Response code 404 (Not Found)
