### ISSUE TITLE
npm install -g @vue/cli: 404 not found: @types/graphql@0.12.6

### ISSUE THREAD

**Issue by Rackar** [vuejs/vue-cli#1412]
### Version
3.0.0-beta.13

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
no steps. just install:
npm install -g @vue/cli

### What is expected?
install

### What is actually happening?
error

**Comment by pdylanross** [comment]
To add some info here, I was able to repro on beta.15->beta.12. beta.11 installed fine though.

**Comment by fuad-ardiono** [comment]
I am having same issue.

**Comment by wolfstark** [comment]
I am having same issue.

**Comment by fuad-ardiono** [comment]
<img width="632" alt="screen shot 2018-05-31 at 09 40 29" src="https://user-images.githubusercontent.com/19608528/40756536-b94ae2aa-64b6-11e8-92fc-e2f9a3397b71.png">

**Comment by quangvinh1225** [comment]
same issue

**Comment by apavamontri** [comment]
It appears that version 0.12.6 of graphql just disappeared from the NPM (https://www.npmjs.com/package/graphql). :( . It only has 0.12.3 and jumps to 0.13.0

**Comment by bvelastegui** [comment]
same issue 😢

**Comment by Rackar** [comment]
[vuecli3beta11.zip](https://github.com/vuejs/vue-cli/files/2056393/vuecli3beta11.zip)

temporary solution:
unzip this file to C:\Users\YOURUSERNAME\AppData\Roaming\npm\
its equal to “npm install -g @vue/cli” ,version 3.0.0-beta11

**Comment by quangvinh1225** [comment]
Currently, i installed successful. Maybe package "@types/graphql@0.12.6" is fixed

**Comment by Randysheng** [comment]
I have the same issue today. Then, I update npm by " npm install npm@latest -g ", and update vue-cli by " npm install -g @vue/cli". It works. Hope this answer helpful~

**Comment by falconair** [comment]
I manually installed graphql "npm install -g @types/graphql" and it installed version 0.13.1. I then retried to install vue/cli but received the same error, "@types/graphql@0.12.6" not found. So graphql's version is the problem. However, I don't see graphql in vue/cli's package.json

**Comment by apavamontri** [comment]
Quick look at the `yarn.lock`  only thing that need `graphql@0.12.6` is `apollo-link`???
```
apollo-link@^1.0.0, apollo-link@^1.2.1, apollo-link@^1.2.2:
  version "1.2.2"
  resolved "https://registry.yarnpkg.com/apollo-link/-/apollo-link-1.2.2.tgz#54c84199b18ac1af8d63553a68ca389c05217a03"
  dependencies:
    "@types/graphql" "0.12.6"
    apollo-utilities "^1.0.0"
    zen-observable-ts "^0.8.9"
```

**Comment by Akryum** [comment]
It should be fine now? https://www.npmjs.com/package/@types/graphql/v/0.12.6

**Comment by Akryum** [comment]
Also, this was an npm issue: https://github.com/npm/registry/issues/340

**Comment by kelvinz** [comment]
I just did a
```
npm install npm@latest -g
npm install -g @vue/cli
```
And am getting,

`npm WARN apollo-link-persisted-queries@0.2.0 requires a peer of graphql@0.11.7 but none is installed. You must install peer dependencies yourself.`

**Comment by Akryum** [comment]
@kelvinz You should be fine.

**Comment by oscar6echo** [comment]
Taking the exact same steps as @kelvinz I get the same warning upon install:
```
npm WARN apollo-link-persisted-queries@0.2.0 requires a peer of graphql@0.11.7 but none is installed. You must install peer dependencies yourself.
```

but when I list the global packages, I get errors:
```
npm ERR! peer dep missing: graphql@0.11.7, required by apollo-link-persisted-queries@0.2.0
npm ERR! peer dep missing: graphql@0.11.7, required by apollo-link-persisted-queries@0.2.0
```
(they are due to @vue/cli@3.0.0-beta.16 because they disappear when I uninstall it)

Can I also safely ignore them ?

**Comment by kkkisme** [comment]
@oscar6echo did you resolve it or just ignore them ?

**Comment by oscar6echo** [comment]
The errors still show up - for version @vue/cli@3.0.0-rc.9.  
But they seem to have no impact. So I ignore them.
