### ISSUE TITLE
vue-cli 2.9.4 cannot resolve template's name (unknown command init)

### ISSUE THREAD

**Issue by VeAmas** [vuejs/vue-cli#1413]
### Version
2.9.3

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
Just init a Vue project.

### What is expected?
success

### What is actually happening?
PS D:\Git> vue init webpack certain-name

  Unknown command init.

   vue-cli · Failed to download repo vuejs-templates/[object Object]: Response code 404 (Not Found)

=> seems to resolve the word "webpack" to [object Object]

actully the version of vue-cli is 2.9.4

**Comment by VeAmas** [comment]
in 2.9.3 it works fine.

**Comment by VeAmas** [comment]
But you don't have vesion 2.9.4 right?
https://www.npmjs.com/package/vue-cli

**Comment by fenghengzhi** [comment]
I have the same problem. 
when i run command available in vue-cli like init/list
it will show Unknow command init/list(vue init will fail,while vue list sucess)

**Comment by wch0508** [comment]
$ npm install vue-cli -g
C:\Users\root\AppData\Roaming\npm\vue-list -> C:\Users\root\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-list
C:\Users\root\AppData\Roaming\npm\vue -> C:\Users\root\AppData\Roaming\npm\node_modules\vue-cli\bin\vue
C:\Users\root\AppData\Roaming\npm\vue-init -> C:\Users\root\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-init
+ vue-cli@2.9.4
added 252 packages from 208 contributors in 12.444s


$ vue init webpack my-project

  Unknown command init.

   vue-cli · Failed to download repo vuejs-templates/[object Object]: Response code 404 (Not Found)

**Comment by wch0508** [comment]
$ npm install vue-cli@2.9.3 -g
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coff                      eescript" (no hyphen)
C:\Users\root\AppData\Roaming\npm\vue -> C:\Users\root\AppData\Roaming\npm\node_modules\vue-cli\bin\vue
C:\Users\root\AppData\Roaming\npm\vue-init -> C:\Users\root\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-init
C:\Users\root\AppData\Roaming\npm\vue-list -> C:\Users\root\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-list
+ vue-cli@2.9.3
updated 1 package in 29.3s

root@DESKTOP-BJ4BL45 MINGW64 /f/test
$ vue init nuxt/starter nuxt

  A newer version of vue-cli is available.

  latest:    2.9.4
  installed: 2.9.3

? Project name (nuxt)

**Comment by Kocal** [comment]
It seems it has been introduced in `2.9.4`.

![capture d ecran de 2018-05-31 07-14-32](https://user-images.githubusercontent.com/2103975/40762772-4e84eaec-64a2-11e8-91f5-aadb73bcb315.png)

**Comment by william807803** [comment]
same issue:
Unknown command init.


 vue-cli · Failed to download repo vuejs-templates/[object Object]: Response code 404 (Not Found)

**Comment by F-loat** [comment]
seems should use command `vue-init` like `vue-init mpvue/mpvue-quickstart my-project`

**Comment by fidejade** [comment]
看不懂大家都在聊啥....

**Comment by peanut-cream** [comment]
at global variable environmental,we should use 'npm i vue-cli@2.9.3 -g'.and then,we can vue init webpack XXX to use vue-cli

**Comment by limuxy** [comment]
same problem here with 2.9.4
using `vue-init` instead works at the time being

**Comment by deniszavadskiy** [comment]
It is a patch update!
@yyx990803, does it should contain breaking changes?

**Comment by Akryum** [comment]
This wasn't intended as a breaking change. It's an issue which wasn't foreseen and should be resolved soon. Sorry for the inconvenience.

**Comment by jsonliu** [comment]
$vue init webpack templeVueDemo

Unknown command init.
vue-cli · Failed to download repo vuejs-templates/[object Object]: Response code 404 (Not Found)
same problem here with 2.9.4

**Comment by Kocal** [comment]
@Akryum don't worry, it happens! 🙂

**Comment by yyx990803** [comment]
Fixed in 2.9.5

**Comment by hejialianghe** [comment]
vue2.9.4不识别那个命令 我安装2.9.3就可以了
卸载当前版本 npm uninstall vue-cli -g 
安装 cnpm install vue-cli@2.9.3 -g

**Comment by beingfranklin** [comment]
A new Update fixed the issue

**Comment by Kocal** [comment]
@alishamohanty please open a new issue, this is unrelated to this one.
