### ISSUE TITLE
error message "vue init webpack my-project"

### ISSUE THREAD

**Issue by fulton** [vuejs/vue-cli#1414]
hi,
when i run command "vue init webpack my-project", it show error message :"Unknown command init", "vue-cli · Failed to download repo vuejs-templates/[object Object]: Response code 404 (Not Found)".
![error](https://user-images.githubusercontent.com/1826140/40763208-9a66859a-64d6-11e8-9f4f-e42ae355d39f.png)
please help me. thank you.

**Comment by william807803** [comment]
same issue:
Unknown command init.


 vue-cli · Failed to download repo vuejs-templates/[object Object]: Response code 404 (Not Found)
