### ISSUE TITLE
ui can't create a new project

### ISSUE THREAD

**Issue by genu** [vuejs/vue-cli#1416]
### Version
3.0.0-beta.13

### Reproduction link
[http://www.example.com/not-necessary](http://www.example.com/not-necessary)

### Steps to reproduce
1. run `vue ui`
2. Create a new project 

### What is expected?
A new project is created 

### What is actually happening?
Displays error: `Failed to resolve plugin: @vue/cli-service`

Error is chrome console is:
`ProjectCreate.vue:528 Error: GraphQL error: Cannot return null for non-nullable field Mutation.projectCreate.`

---
Also getting error when trying to import an existing vue project.

Error is: `es6.promise.js:110 Unhandled promise rejection Error: GraphQL error: Cannot read property 'lastIndexOf' of undefined`

Perhaps its related.

**Comment by Akryum** [comment]
I believe this should be fixed in beta.15

**Comment by genu** [comment]
I experienced this in beta.15, but the issue reported didn't have beta.15 as an option. I'll test again though.
