### ISSUE TITLE
Applying latest typescript breaks semver

### ISSUE THREAD

**Issue by wadetandy** [vuejs/vue-cli#1425]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/wadetandy/vue-typescript-version-reproduction](https://github.com/wadetandy/vue-typescript-version-reproduction)

### Steps to reproduce
- Clone
- yarn install
- yarn build
- Observe that there is a type error due to a feature from typescript 2.8, even though my package.json installs 2.6

### What is expected?
As discussed in this issue: https://github.com/Microsoft/TypeScript/issues/14116 , the Typescript project does not follow a traditional semantic versioning pattern.  I would expect to be able to explicitly set the typescript version in my project's package.json (or potentially in the `invoke` prompts) and have that be picked up by the typescript plugin.

### What is actually happening?
The vue-cli-typescript plugin will always use the newest stable version, even if I specify a different version in my project.  This has caused some breaking changes in some of our more advanced typings as versions have been upgraded. If not every version can be supported due to underlying changes in the node API, even being able to have a list of supported versions to choose from would be a step in the right direction.

**Comment by yyx990803** [comment]
The plugin has to specify a minimum version and we don't want to lock users down to a specific minor, but you can override that using [Yarn's selective resolution](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/).
