### ISSUE TITLE
vue-cli 2.9.5 not working on win10

### ISSUE THREAD

**Issue by fprijate** [vuejs/vue-cli#1428]
### Version
2.9.5

### Reproduction link
[https://gist.github.com/fprijate/e55f6ddedf3b149bd92094c387a30c6a.js](https://gist.github.com/fprijate/e55f6ddedf3b149bd92094c387a30c6a.js)

### Steps to reproduce
npm install -g vue-cli@2.9.5

vue init webpack-simple xx

### What is expected?
to create xx dir containing expected files

### What is actually happening?
program breaks after:
downloading ...
? Project name(xx)
? Project description

and no dir is created

### Platform
OS: win10
node: v10.3.0
npm: 6.1.0

**Comment by Schmille** [comment]
same issue here for nuxt starter template!

**Comment by yyx990803** [comment]
Does this happen in 2.9.3? Trying to determine if this is a regression or a undiscovered bug.

**Comment by fprijate** [comment]
The last working version is 2.8.2
By the way:  2.9.* versions doesn't work whichever  template you select.

**Comment by fprijate** [comment]
the problem is with  "inquirer": "^3.3.0",
and ask.js using it.

**Comment by CoffeeOnCloud** [comment]
same issue as you!

**Comment by fprijate** [comment]
cd %USERPROFILE%\AppData\Roaming\npm\node_modules\vue-cli
npm uninstall inquirer
npm install inquirer --save

**Comment by sodatea** [comment]
So it's been fixed in #1448

**Comment by shelru** [comment]
@sodatea same issue on 6.0.0
Update it to 6.2.2
