### ISSUE TITLE
Build step Dashboard & Analyzer not populated

### ISSUE THREAD

**Issue by shshaw** [vuejs/vue-cli#1432]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/shshaw/vue-cli-ui-dashboard-bug](https://github.com/shshaw/vue-cli-ui-dashboard-bug)

### Steps to reproduce
1. Run `npm install`
2. Run `vue ui`
3. Select _Task > Build_ then click _Run Task_

### What is expected?
After compiling, the Dashboard and Analyzer would have details

### What is actually happening?

After compiling, the Dashboard and Analyzer are not populated with details.

---
Terminal output: https://gist.github.com/shshaw/bce6e39c7f6c69e82582e7b1fc679fe3

Original Tweet & screenshot https://twitter.com/shshaw/status/1002567252565250048

**Comment by Akryum** [comment]
I can't reproduce with `@vue/cli` beta 15:

![image](https://user-images.githubusercontent.com/2798204/40879709-35c432f2-66a4-11e8-9e7b-2dfde03eff97.png)

(There are errors because some components are missing but it's not related imho.)

**Comment by shshaw** [comment]
Strange. I was just running it on the existing project, not the reproduction. I can't seem to get this reproduction in the vue UI because I didn't create the reproduction with the vue-cli. Is there a specific way to add a project to the UI?

**Comment by Akryum** [comment]
Well maybe you should create a new project using the vue-cli as a reproduction? 😸

**Comment by shshaw** [comment]
Confirmed that my vue-cli-ui-dashboard-bug repo is not replicating the bug and works as the dashboard is expected to. 

However, the project it is forked from does not. I will see if I can figure out what the difference is and will report back on if I find anything.

**Comment by Akryum** [comment]
I was able to reproduce the issue.

**Comment by Akryum** [comment]
Hum I'm not reproducing the issue anymore after a fresh install. Maybe it's related to the size of the webpack stats data so I will implement a tentative fix by splitting IPC messages in chunks.

**Comment by Akryum** [comment]
This should no longer happen, the webpack stats are transfered using a temporary file now.
