### ISSUE TITLE
Process Hangs When Invoking `vue-cli-service test:unit` with Jest

### ISSUE THREAD

**Issue by jbenner-radham** [vuejs/vue-cli#1435]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/jbenner-radham/vue-cli-jest-test](https://github.com/jbenner-radham/vue-cli-jest-test)

### Steps to reproduce
Via the CLI:
1. `vue create <app-name>`
2. Select "Manually select features"
3. Select "Babel", "Linter / Formatter", and "Unit Testing"
4. Select "ESLint with error prevention only"
5. Select "Lint on save" and "Lint and fix on commit"
6. Select "Jest"
7. Select "In dedicated config files"
8. Enter "n"
9. `cd <app-name>`
10. `yarn test:unit`

### What is expected?
The unit tests to run and complete successfully.

### What is actually happening?
The test service hangs indefinitely e.g.

```sh
➜  vue-cli-jest-test git:(master) yarn test:unit
yarn run v1.7.0
$ vue-cli-service test:unit
```

**Comment by yyx990803** [comment]
Can't reproduce - can you provide your OS / Node / package manager information?

**Comment by jbenner-radham** [comment]
Sure thing.
- MacOS Sierra v10.12.6
- Node.js v10.3.0 _(installed via Homebrew)_
- Yarn v1.7.0 _(installed via npm)_

**Comment by yyx990803** [comment]
Closing stale issues that cannot be reproduced.

**Comment by bierik** [comment]
@jbenner-radham I have the same problem with
- vue-cli 3.0.0
- node 8.11.3 (installed via nvm)
- yarn 1.9.4 (installed via homebrew)
- MacOS High Sierra 10.13.6

Did you finally got a solution for this problem?

**Comment by mvdwaeter** [comment]
Same problem. `yarn test:unit` indefinitely

Tried: reinstalling node modules, clearing node modules cache, different yarn, node, npm and vue-cli versions.
We've tried copying the node_modules of a computer where the unit tests are running. No success.

- vue-cli 3.1.1
- node 8.12.0 and  9.11.2 (installed via nvm)
- yarn 1.12.1 (installed via homebrew)
- MacOS High Sierra 10.13.6

Tests are running on my co-workers computer, he has the same versions apart from the OS (he's running Mojave 10.14.1)

**Comment by mvdwaeter** [comment]
`yarn test:unit --no-watchman` fixes it for me

**Comment by mvdwaeter** [comment]
Or better, on OSX:
`brew uninstall watchman`
`brew install watchman`

After I was able to run the tests normally again:
`yarn test:unit`

**Comment by fdeage** [comment]
Reinstalling `watchman` worked for me too, thanks!

**Comment by PhilippMeissner** [comment]
Bump, plus reinstalling fixed it for me as well.

**Comment by hoomersinpsom** [comment]
i'm having this issue on ubuntu 12.04 it is also related to watchman or something similar ?
