### ISSUE TITLE
TypeError: api.injectImports is not a function

### ISSUE THREAD

**Issue by Zhennan-Ren** [vuejs/vue-cli#1439]
### TypeError: api.injectImports is not a function

**Comment by darraghenright** [comment]
For others stumbling across this issue, just upgrade/reinstall vue cli. 

`yarn global add @vue/cli`

or 

`npm install -g @vue/cli`

I was running 3.0.0-beta.1 when this error started happening to me - runnung beta.16 now and all is well again
