### ISSUE TITLE
Create new project is extremely slow

### ISSUE THREAD

**Issue by stanleyxu2005** [vuejs/vue-cli#1443]
Dear all,

I'm using Vue CLI v3.0.0-beta.14 to create a new project like this
```vue create new_project```
After asking me about whether use Babel and so on, I see `Creating project in ...`. This will take endless time to complete. Usually after waiting for 20 minutes, I will kill the task and do it again. If I have luck, next time, it will take couple of seconds to complete. 

Does anyone have the same problem as I have?

**Comment by yyx990803** [comment]
This means your connection to npm registry is slow. Try find a registry mirror that is faster in your area.
