### ISSUE TITLE
setup my own default preset

### ISSUE THREAD

**Issue by komushi** [vuejs/vue-cli#1455]
### What problem does this feature solve?
The default preset has babel and eslint included. What if I would like to have a different default preset? I prefer to achieve this instead of the my-default preset as it is not possible to create one without creating a new project.

```
Vue CLI v3.0.0-beta.15
? Please pick a preset: 
❯ default (babel, eslint) 
  Manually select features 
```

### What does the proposed API look like?
```
Vue CLI v3.0.0-beta.15
? Please pick a preset: 
❯ default (babel, eslint, router) 
  Manually select features 
```

**Comment by Akryum** [comment]
You can save your feature selection as custom presets which will then be available in this selection step.

**Comment by komushi** [comment]
Please correct me if I got it wrong - currently it is not possible to create custom presets **without creating new projects**

**Comment by Akryum** [comment]
Yes, but at some point you will create a new project using this preset anyway, right?

**Comment by komushi** [comment]
You are right. I am creating my own vue-cli-plugin which needs a certain preset. The plug-in will be used by new users of vue. So it will be friendly to have the preset beforehand.

**Comment by Akryum** [comment]
You can create a preset as a json file and then use it to create new projects on multiple computers. You can also put in a git repository.
