### ISSUE TITLE
Consolidate CLI for different platforms

### ISSUE THREAD

**Issue by yordis** [vuejs/vue-cli#1459]
### What problem does this feature solve?
As Vue starts being used in more platform, platform specific features.

Splitting the community cross platform based CLIs or having more than one Vue project when we could be sharing a lot of code between platforms.

### What does the proposed API look like?
Consolidate the CLI underline architecture for support multi-platform setup.

The proposal is really similar to what Weex CLI has today.

```
vue platform add ios
vue platform add android
vue platform add web
vue platform add electron
vue platform add [insert name here]
```

```
// or maybe everything global, depends of how people like it
yarn add @vue/cli
yarn add @vue/web-cli
yarn add @vue/android-cli
yarn add @vue/android-cli
yarn add @vue/electron-cli
yarn add @vue/[insert name here]-cli
```

Today there is always a `public` folder which would be what could be under `platforms/web` folder.

Because no everyone is using other platforms I think the tradeoff of just installing an extra dependency for the CLI.

Those dependencies should install extra commands to the CLI, example

```
vue web serve
vue ios run
vue android run
```

Those underline platform plugins could do some `default` Webpack transformation as it is required for some platform.

Also the `vue-config.js` should be pass somehow the platform that the CLI used for add some extra transformation.

Some inspiration about the plugin and CLI could be take from here https://github.com/infinitered/gluegun 

### Checklist

- [ ] Be able to add platforms to the CLI
- [ ] Be able to extend the CLI commands by installing platforms
- [ ] Each platform should have the default Webpack pipeline.
- [ ] `vue-config.js` should allow the developer to know the platform for be able to inject different pipelines
- [ ] Consolidate the folders
  - [ ] Add `./platforms` folder
  - [ ] Move `./public` into `./platforms/web` folder
  - [ ] `./dist` folder should have the platform name as child, for example `./dist/web` or `./dist/ios`
- [ ] Add entry points for each platform

cc: @yyx990803 @Akryum @erha19

**Comment by yyx990803** [comment]
Thanks for the ideas, but I don't think we will consider this until Vue 3 / CLI 4. The current focus of the CLI is on web applications only.

**Comment by yordis** [comment]
@yyx990803 why closing the issue if you will considerate this until v3/v4 ?

Also, why to see the CLI as web only when you have weex code in the vue repo, or when there is definitely people that could benefit from this.

@erha19 is putting doing some work for Weex folks when it could be replaced in the future, I see more value on working together on this.

**Comment by yyx990803** [comment]
Also, closing doesn't mean let's forget it - remember issues are used to manage work. This is just me saying: interesting idea, but please don't leave it on my plate just yet.
