### ISSUE TITLE
Storybook option in build process. 

### ISSUE THREAD

**Issue by uharbachou** [vuejs/vue-cli#1464]
### What problem does this feature solve?
Hi, storybook is important in development of components. And every time had some issues in versions of packages of vue-loader, storybook/vue. And will be good option to have also it in templates. 

Thanks in advance,
Vlad

### What does the proposed API look like?
To add storybook in list of options when use cli.

**Comment by LinusBorg** [comment]
This should be solved by the community with a plugin.

There is already one, in fact: https://github.com/almeynman/vue-cli-plugin-storybook
