### ISSUE TITLE
无法设置静态资源为相对路径

### ISSUE THREAD

**Issue by thomasyus** [vuejs/vue-cli#1470]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/thomasyus/vue-cli-3.0beta15-baseUrl/tree/master/demo](https://github.com/thomasyus/vue-cli-3.0beta15-baseUrl/tree/master/demo)

### Steps to reproduce
vue.config.js 在我之前用的版本vue-cli 3.0 beta 11里可以直接设置baseUrl:'./'，可以让所有引入的js和css文件都以相对路径的方式去调用，在beta15版本里，这样设置的话，页面直接空白。

### What is expected?
期望设置baseUrl:'./'  让静态资源以相对路径进行引入

### What is actually happening?
实际页面空白，入口文件没有进行对应的编译渲染

**Comment by jkzing** [comment]
`baseUrl: './'` 改成 `baseUrl: '/'`

**Comment by thomasyus** [comment]
我期望用相对路径来引入资源，因为最终部署到终端服务器上的路径是在某个二级目录下，不能用/绝对路径引入静态资源

**Comment by yyx990803** [comment]
那就设置成要部署的二级目录。

**Comment by jkzing** [comment]
``` js
module.exports = {
  baseUrl: process.env.NODE_ENV === 'production'
    ? '/your/dir/'
    : '/'
}
```

**Comment by thomasyus** [comment]
那这样未免也太麻烦了，能不能做到像beta11之前的版本，直接支持设置baseUrl:'./'，这样前端就不需要关心未来部署的路径了

**Comment by yyx990803** [comment]
下个版本可以。
