### ISSUE TITLE
sockjs-node (Not Found) 

### ISSUE THREAD

**Issue by mavajee** [vuejs/vue-cli#1472]
### Version
3.0.0-beta.15

### Reproduction link
[https://jsfiddle.net/w0jg8bdr/](https://jsfiddle.net/w0jg8bdr/)

### Steps to reproduce
Use with nginx

### What is expected?
HMR working with nginx

### What is actually happening?
I use 3 version of vue cli and nginx.  And each vue app have different sockjs-node path.

vue cli 10 have path 0.0.0.0:8082/sockjs-node/***  and it's work

vue cli 12  have path http://localhost.com:8082/sockjs-node/*** and it's work to

vue cli 15  have path http://localhost.com/sockjs-node/*** and it's not work. How you can see port is missing

UPD. If i run app on 0.0.0.0:8082 without nginx all work fine

---
maybe [ this commit  ](https://github.com/vuejs/vue-cli/commit/a9e12865b5d384288163828f216a7e2499ce1e89#diff-aa4efdd6f3b89b13401c174b06070bd8) is the reason or [ this ](https://github.com/vuejs/vue-cli/commit/04600e63622f0f0e4f58ffa2fc24e845ed020747#diff-aa4efdd6f3b89b13401c174b06070bd8)

It's bug or just I not correct config my app?

**Comment by mavajee** [comment]
versions 10 has the best correct sockjs path to dev serve from any host name. How configure it?

**Comment by jkzing** [comment]
Umm, it should not work like that. What is `baseUrl` in your `vue.config.js`?

**Comment by mavajee** [comment]
@jkzing I try use baseUrl but it not work. in ver 10 I used absolute path to work with nginx

`config.output.publicPath = http://${host}:${port}/`

because need all request send to webpack dev server

**Comment by yyx990803** [comment]
@mavajee you should not be mutating `publicPath` because this value needs to be used in other places in addition to the wepback config. Use the `baseUrl` option.

**Comment by Akryum** [comment]
@yyx990803 Maybe we could check that and display the like of `Don't change webpack 'ouput.publicPath' directly, use vue.config.js 'baseUrl' instead.`

**Comment by yyx990803** [comment]
@Akryum that would be nice although it's a bit difficult to precisely detect that

**Comment by jkzing** [comment]
I guess OP's usage is like having a `baseUrl: 'http://localhost:8082/'` in `vue.config.js'. 

With a nginx config like:
```nginx
server {
  listen 8082 default_server;
  location / {
    proxy_pass  http://localhost:8080;
    proxy_set_header Host $host;
  }
}
```

Then open `http://localhost:8082` in browser.

In above case, current strategy to fix the socket url to '/sockjs-node' is not enough, maybe we need to fix it to 'http://localhost:8080/sockjs-node'.

**Comment by mavajee** [comment]
Thank you for answers. I will check it tomorrow. 

What if make '/sockjs-node' url same absolute dev server url. Anyway HMR and sockjs work only with dev server

**Comment by mavajee** [comment]
@jkzing, hi, now it work for me, but if i put to baseUrl absolutePath, I have this 
![image](https://user-images.githubusercontent.com/10177998/41019508-a6bac15e-6967-11e8-9797-21b71c2ef278.png)

**Comment by mavajee** [comment]
and about [`historyApiFallback`](https://github.com/jkzing/vue-cli/blob/40f3f7970f1947764a0a5e57087d83b49f41198a/packages/%40vue/cli-service/lib/commands/serve.js#L118), just my usage situations.  If use absolute url, it's will make some troubles.

**Comment by jkzing** [comment]
@mavajee Just FYI, if current historyApiFallback not works for you, you can still overwrite it in `vue.config.js`.

**Comment by mavajee** [comment]
@jkzing, yes I did it, i think it comment will be helpful for you

**Comment by linguamatics-albert** [comment]
Sorry to bother you guys again with this.

I'm finding a similar issue but I'm not so sure is related to this, so just in case I prefer to drop the comment here.

This one comes when running ```vue-service-cli serve --host xyz```. When running it rise the webpack dev server successfully with everything, but the hot reload it won't work. A further inspection on the error log it shows that the webpack dev server cannot reach sockjs-node:

```
sockjs.js?9be2:1601 GET http://localhost:8080/sockjs-node/info?t=1528877926478 net::ERR_CONNECTION_REFUSED 
```

but the webpack dev server was opening in the hostname specified by the --host flag.

In previous versions of vue-cli I was doing the same thing and I didn't got the same problem.

I've got the suspicious that this comes because here:

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/serve.js#L89

```urls.lanUrlForConfig``` is always undefined when setting a host name through --host flag, therefore it will always spawn sockjs-node to localhost.

But maybe I'm doing something wrong. Am I missing something?

I'm suing the latest webpak 4.12.0 which I believe that is the one that it get install when running ```vue create myProject```

**Comment by jkzing** [comment]
@linguamatics-albert , It's actually a bug of `serve` command, it should not act like that. 

As a work around, you can use `devServer.public` in `vue.config.js` to specify your host.
Which is included in this PR [https://github.com/vuejs/vue-cli/pull/1526](https://github.com/vuejs/vue-cli/pull/1526).

**Comment by srchulo** [comment]
I think this issue still happens if you have a path at the end of devServer.public:

```
devServer: {
    host: '0.0.0.0',
    public: '0.0.0.0:8081/app',
    disableHostCheck: true
},
```

I can get it to work if I remove `/app`. As a workaround, I've done this in my vue.config.js for the vue project that's doing the proxying:

```
proxy: {                                                                                                                                                                                                                
    '/app': {
        target: 'http://frontend_app:8081',
        changeOrigin: true,
        pathRewrite: {
            '^/app/sockjs-node': ''
        },
    }
}
```

This fixes the sockjs-node not found error, however, now hot reload doesn't seem to be working.

**Comment by srchulo** [comment]
Also, this error only started occurring for me once I upgraded to vue cli 3 from 2.

**Comment by srchulo** [comment]
Never mind, I thought my above solution worked, but it looks like it doesn't.

**Comment by thomhickey** [comment]
For me, all that was required to lock sockjs down to the dev server is:

```
module.exports = {

    devServer: {
        port: 8081,
    }
}
```

I am using vue-cli-service 3.9.0 ... without the above the generated urls for sockjs go back to my web front-end port (in my case it's a micro-framework in Scala that runs on port 2112) instead of to the dev server.

**Comment by Goldziher** [comment]
This error is still occuring. I'm working on a multi vue app project that is contained within an nginx layer. Whenever I try to upgrade one of the apps (all using vue-cli 3) to a newer version of the vue-cli, or run yarn upgrade on vue-cli or any of its plugins, this errors occurs. 

Any suggested fix?

**Comment by amravazzi** [comment]
I'm having a kind of different problem. I'm getting twice the error in console:

`WebSocket connection to 'ws://localhost:8082/sockjs-node/355/xgym14in/websocket' failed: Unknown reason`

Here is my vue.config.js: 

```javascript
module.exports = {
  baseUrl: 'http://localhost:8082/',
  devServer: {
    public: 'localhost:8082',
    host: 'localhost',
    port: 8082,
    disableHostCheck: true,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept'
    }
  }
}
``` 

I spent 2 days searching in Google, but couldn't find anything useful. Any help?

**Comment by chanlito** [comment]
@amravazzi same here.

**Comment by marcoippolito** [comment]
In Ubuntu 18.04.03 Server Edition and with vue@2.6.11, I'm getting these error messages, when deploying my starting-page of webapp with vue.js: 
  GET https://192.168.1.7:8081/sockjs-node/info?t=1579780726858 
  net::ERR_SSL_PROTOCOL_ERROR
  GET https://192.168.1.7/sockjs-node/info?t=1579780726857 
  net::ERR_CERT_COMMON_NAME_INVALID


![sockejsError01](https://user-images.githubusercontent.com/3073209/72983668-1efcab00-3de2-11ea-99dc-6248c02d3ba7.jpg)

![sockejsError02](https://user-images.githubusercontent.com/3073209/72983672-22903200-3de2-11ea-965d-82a8c855b211.jpg)

![sockejsError03](https://user-images.githubusercontent.com/3073209/72983676-2754e600-3de2-11ea-8356-d32b8e3c97a6.jpg)

This is my vue.config.js file :    

    module.exports = {
      productionSourceMap: false,
      pluginOptions: {
        i18n: {
          enableInSFC: true
        }
      },
      devServer: {
        host: '192.168.1.7',
        hot: true,
        disableHostCheck: true
      }
    }

How to solve the problem?

**Comment by Monakiel** [comment]
> 
> 
> I used @srchulo's comment and added the following to my `vue.config.js` and the error went away for me using cli 3.0.
> 
> ```
> host: '0.0.0.0',
> public: '0.0.0.0:8080',
> disableHostCheck: true
> ```
> 
> I'm assuming this only occurs to the dev server and does not happen in production build?

1 year later but I had trouble finding a solution too. And yours worked. Thanks!

**Comment by WiseTap** [comment]
> @jkzing, hi, now it work for me, but if i put to baseUrl absolute url, I have this (just incorrect display, but all work)
> ![image](https://user-images.githubusercontent.com/10177998/41019508-a6bac15e-6967-11e8-9797-21b71c2ef278.png)
> 
> vue.config.js
> 
> ```
> const path = require('path')
> 
> const host = '0.0.0.0'
> const port = 8085
> 
> module.exports = {
>   lintOnSave: false,
>   baseUrl: `http://${host}:${port}/`,
> 
>   devServer: {
>     port,
>     host,
>     hotOnly: true,
>     disableHostCheck: true,
>     clientLogLevel: 'warning',
>     inline: true,
>     headers: {
>       'Access-Control-Allow-Origin': '*',
>       'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, PATCH, OPTIONS',
>       'Access-Control-Allow-Headers': 'X-Requested-With, content-type, Authorization'
>     },
>   }
> }
> ```

It worked
thank you!

**Comment by colorfulyang** [comment]
I've got the same problem with @marcoippolito,I wanna know how did you solve this problem at last.@marcoippolito
