### ISSUE TITLE
Zero config demo not work as expected

### ISSUE THREAD

**Issue by yoanmarchal** [vuejs/vue-cli#1474]
### Version
3.0.0-beta.15

### Steps to reproduce
npm install -g @vue/cli-service-global
echo `<template><h1>Hello!</h1></template>` > App.vue
vue serve --open

### What is expected?
expect to open browser & show 'Hello!'

### What is actually happening?
white screen
log say Failed to mount component: template or render function not defined.

---
Environnement Windows 10
node v10.3.0
npm 6.1.0

**Comment by mavajee** [comment]
default vue-cli entry path is src/main.js. You need change this path maybe

**Comment by yoanmarchal** [comment]
i'm trying to reproduce exemple of zero config by Evan You at VueConf 2018

> https://www.vuemastery.com/conferences/vueconf-2018/opening-keynote-evan-you
At 12:44

**Comment by yyx990803** [comment]
Can't reproduce. Make sure your `App.vue` contains the correct content. You are not wrapping the content in quotes...

**Comment by yoanmarchal** [comment]
i was, i just dont know how to do ' in markdown

**Comment by Akryum** [comment]
What's the content of your `App.vue` file?

**Comment by yoanmarchal** [comment]
<template><h1>Hello!</h1></template>

**Comment by yoanmarchal** [comment]
& the file was correctly written by bash

**Comment by Neme12** [comment]
It's not working for me either.
