### ISSUE TITLE
Allowing the disabling or removal of the HTMLPlugin

### ISSUE THREAD

**Issue by cecilphillip** [vuejs/vue-cli#1478]
### What problem does this feature solve?
I'm using v3.0.0-beta.15 of the CLI.

I have an existing backend that generates it's down default document. I don't need an index.html file generated or copied to my output folder.

I'm able to run `vue create .` in a sub folder of my project. I've manually deleted the `public` folder. Then I've created a `vue.config.js` file and tried the follow 3 options. However, non of these options work in preventing the index.html being copied.
```JavaScript
    chainWebpack: config => {
        config.plugin('html').clear();
    }

....

    chainWebpack: config => {
        config.plugins.delete('html');
    }

....

    chainWebpack: config => {
        config.plugins.delete('copy');
    }
```

### What does the proposed API look like?
This configuration setting should work, unless there's an alternative API already available that would be a better fit.

```JavaScript
   chainWebpack: config => {
           config.plugins.delete('html');
   }
```

**Comment by cecilphillip** [comment]
I was able to get this to work after disabling some other plugins, but I still think it would be better behind a config setting.

```JavaScript
module.exports = {
    outputDir: '../wwwroot',
    chainWebpack: config => {
        config.plugins.delete('html');
        config.plugins.delete('preload');
        config.plugins.delete('prefetch');
    }
};
```

**Comment by yyx990803** [comment]
This should work:

``` js
module.exports = {
  chainWebpack: config => {
    config.plugins.delete('html')
    config.plugins.delete('preload')
    config.plugins.delete('prefetch')
  }
}
```

**Comment by MrToy** [comment]
If in multi-page mode,How to disable index generation?
Here is my option, however it still generate the index.html and subpage.html
```js
module.exports = {
    filenameHashing: false,
    pages: {
        index: 'src/main.js',
        subpage: 'src/sub.js'
    },
    chainWebpack: config => {
        config.plugins.delete('html')
        config.plugins.delete('preload')
        config.plugins.delete('prefetch')
    }
}
```

**Comment by mikedidthis** [comment]
```JS
module.exports = {
    filenameHashing: false,
    pages: {
        index: 'src/main.js',
        subpage: 'src/sub.js'
    },
    chainWebpack: config => {
        config.plugins.delete('html-index')
        config.plugins.delete('preload-index')
        config.plugins.delete('prefetch-index')
        config.plugins.delete('html-subpage')
        config.plugins.delete('preload-subpage')
        config.plugins.delete('prefetch-subpage')
    }
}
```

You can find out the plugin names to delete by using `vue inspect --plugins`.

**Comment by Kenvdb** [comment]
I was looking for the same solution for the setup in multi page application, the solution of @mikedidthis worked for me. Many thanks!

**Comment by Kenvdb** [comment]
@Akryum - if you would like to keep it dynamic, you could do following:

```
let vueConfig = {
    filenameHashing: false,
    pages: {
        index: 'src/main.js',
        subpage: 'src/sub.js'
    },
    chainWebpack: config => {
	Object.keys(vueConfig.pages).forEach(function (key) {
            config.plugins.delete('html-' + key);
            config.plugins.delete('preload-' + key);
            config.plugins.delete('prefetch-' + key);
        });
    }
}

module.exports = vueConfig;
```

**Comment by ommehaz** [comment]
You will still have an index.html file in your build with this:
`  chainWebpack: config => {
    config.plugins.delete('html');
    config.plugins.delete('preload');
    config.plugins.delete('prefetch');
    //config.plugins.delete('copy');
},`
If you don't want it, then uncomment the last line copy.
