### ISSUE TITLE
Preset "Router" not working

### ISSUE THREAD

**Issue by dimensi** [vuejs/vue-cli#1479]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/dimensi/test-vue-cli](https://github.com/dimensi/test-vue-cli)

### Steps to reproduce
Start vue-cli ui. Try create new project.
Select npm as package manager.
Select manual preset
Select Babel, Vuex, Router, CSS, Linter presets.
Select Stylus.
Pick linter "Eslint   Standard"
Wait installing and open the project

### What is expected?
Vue-router in project

### What is actually happening?
Nothing. Installing only vuex.

---
I can't understand what's happen.
I try create 5 times a new project. 
4 times i not got router. 1 time i got router, but not got babel...

**Comment by yyx990803** [comment]
Hmm this is really weird, unfortunately, I've never run into this and have no way to reproduce this, so there's really nothing we can do about it.

**Comment by dimensi** [comment]
@yyx990803, I film [it](https://drive.google.com/file/d/1fKtEW9FALjkuGvob7fcXMZwjQv5igKL_/view) :)

**Comment by yyx990803** [comment]
Oh this seems to be a UI only problem. @Akryum

**Comment by dimensi** [comment]
Yes, problem in UI.

**Comment by Akryum** [comment]
I can't reproduce with either vue-cli 3.0.0-beta.15 nor the dev branch. I'm using node 10.3.0 and npm 6.1.0 on MacOS.

**Comment by wistcc** [comment]
Yeah, I wasn't able to reproduce either.
