### ISSUE TITLE
HMR doesn't respect devServer publicPath

### ISSUE THREAD

**Issue by kalekseev** [vuejs/vue-cli#1483]
### Version
3.0.0-beta.15

### Reproduction link
[https://gist.github.com/kalekseev/0f6b00540dbdb16b8f8c685a88ab7f97](https://gist.github.com/kalekseev/0f6b00540dbdb16b8f8c685a88ab7f97)

### Steps to reproduce
Serve  index html on localhost:8000 while dev server is started on localhost:8080

### What is expected?
HMR uses ws://localhost:8080/ address

### What is actually happening?
HMR uses ws://localhost:8000/ address

---
Was working that way in beta.11, this addition in serve.js `  '?/sockjs-node'` somehow force client to use page address

**Comment by yyx990803** [comment]
You are not supposed to change `output.publicPath` directly. Use the `baseUrl` option.

**Comment by Aukhan** [comment]
For anyone landing here, [baseUrl has been deprecated](https://cli.vuejs.org/config/#baseurl) and `publicPath` should do the trick. Modify `devServer.public` if the baseUrl that the app is being used on is different from where the app is being served.
