### ISSUE TITLE
Allow env files to be yaml/json/other

### ISSUE THREAD

**Issue by gjuchault** [vuejs/vue-cli#1485]
### What problem does this feature solve?
Hello,

I've been using the new @vue/cli and sometimes a bit frustrated when my config was using complex structures (array / objects / nested). A simple workaround is indeed to have stringified json in the .env, but it would be awesome to choose the .env file format when creating the project (yaml/toml/hson/json/.env)

### What does the proposed API look like?
When @vue/cli is asking for template options, add an option about the .env format wanted (default to `key/value .env`).
Add parser in node-modules accordingly, and use it to parse the .env file. Not sure about the file extension though, it might change to `.env.json` and `.env.local.json`.

**Comment by yyx990803** [comment]
I don't think this justifies the additional complexity because env variables can only be simple key-value pairs.
