### ISSUE TITLE
Dynamic imports not splitting into different chunk for lazy loading

### ISSUE THREAD

**Issue by pranavjindal999** [vuejs/vue-cli#1488]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/pranavjindal999/beta15-repro](https://github.com/pranavjindal999/beta15-repro)

### Steps to reproduce
- Create a new Vue project using Vue Cli 3 (any version)
- Make a dynamic import anywhere in the code. (using `import('module-name')` )
- Build the project with Vue CLI-3.0.0.beta 12 or above

### What is expected?
Dynamically imported module should split into a separate file and is not included in vendor bundle.

### What is actually happening?
Dynamically imported module is included in vendor bundle and NO separate file is made.

---

**Comment by pranavjindal999** [comment]
Thanks for the quick fix 👍

**Comment by atyshka** [comment]
Having this same issue in Vue CLI 4.3.1, suggestions?
