### ISSUE TITLE
关于build后，css中背景图片的路径问题

### ISSUE THREAD

**Issue by zlf911216** [vuejs/vue-cli#149]
![ctk8f 9y4s x g 5b vd](https://cloud.githubusercontent.com/assets/14553661/17828852/cd8a39d2-66cf-11e6-8e64-ac3fe34e7199.png)
![l 3s 4z49j 6na w p c56t](https://cloud.githubusercontent.com/assets/14553661/17828853/cdc2b956-66cf-11e6-9246-cab1d283e4ed.png)

打包后在css中引入的图片路径不对，请问怎么修改这个配置

**Comment by zlf911216** [comment]
![a5hee83rdl0zxf3 484 kb](https://cloud.githubusercontent.com/assets/14553661/17829094/2251ac66-66d5-11e6-90a7-a597014f78ed.png)
如果修改这里的话，写在html里的img路径也会被修改。能不能只修改css中引入图片的路径

**Comment by zhangbihua** [comment]
一样遇到这样的问题，

**Comment by nicefan** [comment]
与src平级的那个static文件夹里的内容在编译的时候会直接复制到dist/static文件夹中,所以在使用的时候应该使用根目录的形式 "/static"

**Comment by egoist** [comment]
请不要直接打开 index.html，用 http-server 之类的工具打开。

相关的模板问题请先阅读对应的文档。

**Comment by appliqiang** [comment]
请问最后是怎么解决的 谢谢 @zhangbihua @zlf911216
