### ISSUE TITLE
Use the "outputDir" option instead. Error 

### ISSUE THREAD

**Issue by jousi592** [vuejs/vue-cli#1496]
### Version
3.0.0-beta.15

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
Set up vue.config.js like this:

```
module.exports = {

   configureWebpack:{

      output: {
	 path: '../test-folder/',
	 filename: '[name].js',
	 publicPath: '/'
       },
   }
}
```

And run `npm run build`

### What is expected?
To get build files in the `test-folder ` folder

### What is actually happening?
I am getting the: `Configuration Error: Avoid modifying webpack output.path directly. Use the "outputDir" option instead.`

---
Should have been fixed in `3.0.0-beta.10`

**Comment by benoit-ponsero** [comment]
Hi, 

I have the same problem. Why does this issue is closed ?

**Comment by jousi592** [comment]
@benoit-ponsero 
If you can add a reproduction, then it can be re-opened.

I didnt have time to create a repro.

**Comment by zoosky** [comment]
Hi @jousi592 here is the repoduction: I use`"@vue/cli-service": "^3.0.0-rc.3"` and have the same issue.

You find the repo in the assests folder as a git submodule @ https://github.com/zoosky/hello-exs/assets

```bash
 assets git:(master) ✗ yarn build                 
yarn run v1.7.0
$ vue-cli-service build

⠋  Building for production... ERROR  Error: 
               
Configuration Error: Avoid modifying webpack output.path directly. Use the "outputDir" option instead.
               
Error: 

Configuration Error: Avoid modifying webpack output.path directly. Use the "outputDir" option instead.

    at build (/Users/andreas/dev/examples/exlixir/hello/assets/node_modules/@vue/cli-service/lib/commands/build/index.js:137:11)
    at api.registerCommand (/Users/andreas/dev/examples/exlixir/hello/assets/node_modules/@vue/cli-service/lib/commands/build/index.js:64:13)
    at Service.run (/Users/andreas/dev/examples/exlixir/hello/assets/node_modules/@vue/cli-service/lib/Service.js:179:12)
    at Object.<anonymous> (/Users/andreas/dev/examples/exlixir/hello/assets/node_modules/@vue/cli-service/bin/vue-cli-service.js:22:9)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
```
Does this help?

**Comment by zig999** [comment]
Hello, any workarround for this error?
I'm getting the same msg:
`Configuration Error: Avoid modifying webpack output.path directly. Use the "outputDir" option instead.`

**Comment by kamidev** [comment]
This works for me. 

const path = require('path');

module.exports = {
  lintOnSave: true,
  outputDir: path.resolve(__dirname, '../priv/static'),
};

**Comment by zoosky** [comment]
@kamidev nice. thx!

**Comment by borantula** [comment]
changing it within `vue ui` created the file below which started working with custom directory. Haven't debugged yet which one helped.
```
module.exports = {
    publicPath: undefined,
    outputDir: '../public/site/dist',
    assetsDir: undefined,
    productionSourceMap: undefined,
    parallel: undefined,
    css: undefined
}
```

**Comment by opadilla** [comment]
How would I use this to change output filename, library, and libraryTarget?

**Comment by dinglittle** [comment]
The same problem , what can I do , chang output library and libraryTarget?
