### ISSUE TITLE
.env vars overload vars set in environment

### ISSUE THREAD

**Issue by morrislaptop** [vuejs/vue-cli#1499]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/morrislaptop/vue-env-issue](https://github.com/morrislaptop/vue-env-issue)

### Steps to reproduce
* Step 1: Run `yarn serve`
* Step 2: Run `VUE_APP_FOO=foorbar yarn serve`

Now put "VUE_APP_FOO=bar" in `.env.local`

* Step 3: Run `yarn serve`
* Step 4: Run `VUE_APP_FOO=foorbar yarn serve`

### What is expected?
I would expect the env vars to be loaded with the following specificity (later overrides earlier)

* .env
* .env.local
* shell environment variables

Results:

1. VUE_APP_FOO=foo
2. VUE_APP_FOO=foobar
3. VUE_APP_FOO=bar
4. VUE_APP_FOO=foobar

### What is actually happening?
The env vars are loading in the following specificity (later overrides earlier)

* shell environment variables
* .env
* .env.local

Results:

1. VUE_APP_FOO=foo
2. VUE_APP_FOO=foo
3. VUE_APP_FOO=bar
4. VUE_APP_FOO=bar

**Comment by LinusBorg** [comment]
[These Lines](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/util/loadEnv.js#L5-L7)
```javascript
  Object.keys(config).forEach(key => {
    process.env[key] = config[key]
})
```
should probably look more like this:
```javascript
  Object.keys(config).forEach(key => {
    if (!process.env[key]) {
      process.env[key] = config[key]
    }
})
```
Then we would have to switch the order off appliance to 

* .env.mode.local
* .env.mode
* .env.local
* .env

which means switching these calls:

https://github.com/vuejs/vue-cli/blob/5064cf5999cb4e909b95cde9c19e684520b542f0/packages/%40vue/cli-service/lib/Service.js#L109-L110

...as well as these:

https://github.com/vuejs/vue-cli/blob/5064cf5999cb4e909b95cde9c19e684520b542f0/packages/%40vue/cli-service/lib/Service.js#L57-L61

**Comment by Akryum** [comment]
I would probably do `if (typeof process.env[key] === 'undefined') {` instead.

**Comment by LinusBorg** [comment]
right!
