### ISSUE TITLE
Command: vue config

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-cli#1506]
Currently users have to manually open and edit `~/.vuerc` and by looking at the help message users don't really realize it's there.

We should have a `vue config` command that allows users to more easily inspect and modify the config (and potentially makes it easier for external tools to access/modify the config via the CLI).

- `vue config`: prints the resolved full path and content of `~/.vuerc`
- `vue config get <path>` - e.g. `vue config get packageManager`
- `vue config set <path> <value>` - e.g. `vue config set useTaobaoRegistry false` (should handle special case parsing for boolean and number values)
- `vue config delete <path>` - e.g. deleting a preset: `vue config delete preset.foo`
- `vue config edit` - opens `~/.vuerc` with the default editor (via `EDITOR` env var)

**Comment by beardedpayton** [comment]
I'd love to tackle this!

**Comment by beardedpayton** [comment]
Trying to get familiar with the code base, is this path correct for a new command?

vue-cli/packages/@vue/cli-service/lib/commands/

**Comment by yyx990803** [comment]
@beardedpayton you should be looking at [here](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli/lib)

**Comment by beardedpayton** [comment]
@yyx990803 In /packages/@vue/cli/bin I've added a command with what looks to be commander js you are using. I then created config.js in the lib. I tried a simple log to the console before I started building it out.

I'm getting command not found in the terminal when running the new command. Am I missing something for the dev environment? If you have an open slack channel, maybe you'd like to move this convo there.

**Comment by LinusBorg** [comment]
I would like to suggest to rename this to `vue preset` - that makes the intend of the command clearer and differentiates it from `vue.config.js`

**Comment by beardedpayton** [comment]
Is it cool if I go ahead and submit a PR for just 'vue config' command and get some feedback? Make sure everything looks good? Or would you like one PR with everything?
![screen shot 2018-06-08 at 1 42 15 pm](https://user-images.githubusercontent.com/20526900/41172417-d2186368-6b21-11e8-9ab7-c83aed89df47.png)

**Comment by beardedpayton** [comment]
@yyx990803 is it cool if I go ahead and submit PR for just 'vue config' command to get some feedback? I want to make sure I'm keeping everything consistent. I've got it working just haven't implemented the rest of the options yet. 

![screen shot 2018-06-08 at 1 46 32 pm](https://user-images.githubusercontent.com/20526900/41172666-8b7ab496-6b22-11e8-94ef-14f0157eedf8.png)

**Comment by Akryum** [comment]
@LinusBorg It's not only about presets but also about global vue-cli configuration.

**Comment by beardedpayton** [comment]
Pull request [here](https://github.com/vuejs/vue-cli/pull/1522) for first command ```vue config```

Really not sure why it shows two commits for one?

**Comment by beardedpayton** [comment]
@yyx990803 I've got this wrapped up except for one command ```vue config set <path> <value>```

I don't believe Commander supports this by default https://github.com/tj/commander.js/issues/674

Did you have something in mind on how to achieve this? I thought about capturing the value via process.argv[5] since it should always be the fifth element in the array.

Thoughts?

**Comment by beardedpayton** [comment]
PR [here](https://github.com/vuejs/vue-cli/pull/1554)

**Comment by yyx990803** [comment]
Thanks @beardedpayton for the contribution!

**Comment by ImCharmainejoy** [comment]
I'm currently trying the Vue-CLI 3  but i'm having these error below after i set the packageManager: "pnpm"
```Vue CLI v3.6.3
 Creating project in /home/../my-project. 

Installing CLI plugins. This might take a while... ERROR command failed: pnpm install --loglevel error --shamefully-flatten```

and I found that it was actually stored somewhere and made some edits.. thanks to @yyx990803 for the vue config 
```
/Desktop/WebpackPackage/my-folder$ vue config
Resolved path: /home/charmainejoy/.vuerc
 {
  "useTaobaoRegistry": false,
  "packageManager": "npm"
}
````
finally I got my new application working..

**Comment by nnivxix** [comment]
> Currently users have to manually open and edit `~/.vuerc` and by looking at the help message users don't really realize it's there.
> 
> We should have a `vue config` command that allows users to more easily inspect and modify the config (and potentially makes it easier for external tools to access/modify the config via the CLI).
> 
> * `vue config`: prints the resolved full path and content of `~/.vuerc`
> * `vue config get <path>` - e.g. `vue config get packageManager`
> * `vue config set <path> <value>` - e.g. `vue config set useTaobaoRegistry false` (should handle special case parsing for boolean and number values)
> * `vue config delete <path>` - e.g. deleting a preset: `vue config delete preset.foo`
> * `vue config edit` - opens `~/.vuerc` with the default editor (via `EDITOR` env var)

yeah now the problem has been solved, if you strugle find that file, btw im using linux Ubuntu, there is in directory '`.config/vue`'


thank you
