### ISSUE TITLE
"vue create" in current directory

### ISSUE THREAD

**Issue by Tajnymag** [vuejs/vue-cli#1509]
### What problem does this feature solve?
Currently the only option, I'm aware of, to create a new project is to let vue-cli create it's folder from scratch somewhere in the current directory as a subfolder. I'd like an option to create the project in the directory where vue-cli command was invoked.

### What does the proposed API look like?
```bash
# when run without specifiying project's name, vue-cli would use the current dir's name and place all the new files in the current directory
vue create
```

**Comment by andreasvirkus** [comment]
You can pass in an existing directory's name and you'll be prompted whether to overwrite or merge any existing files. Does that not solve the use case already?

**Comment by Tajnymag** [comment]
Well, yes, but it removes for some reason the local dev installation of vue-cli. Is it intended?

**Comment by brandon93s** [comment]
> You can pass in an existing directory's name and you'll be prompted whether to overwrite or merge any existing files. Does that not solve the use case already?

One limitation of this is folder names that aren't valid project names. For instance, I may have an `App.UI` folder where I want to create my Vue project. Currently, this isn't possible. You have to `vue create app-name` inside of the folder, and then copy the contents of the `App.UI/app-name` folder back out to the root `App.UI` folder.

Possible syntax: 
```sh
# Syntax
vue create [options] <app-name> [folder-name]

# Example - Default to .\app-name folder
vue create app-name

# Example - Current Folder
vue create app-name .

# Example - Specified Folder
vue create app-name .\App.UI\

```

**Comment by sodatea** [comment]
Creating project in current directory is already supported by running `vue create .`
(https://github.com/vuejs/vue-cli/pull/916)
As for the folder naming issue, I think this thread https://github.com/facebook/create-react-app/issues/2165#issuecomment-301627339 has given some very persuasive arguments.

**Comment by goldengecko** [comment]
> you can't do this with vue ui - it just throws an error if the folder already exists.
> 
Yeah, I got this error too. It gave me a warning that the folder already exists at the start of the process and asked me if I wanted to overwrite it, so I said no, but then at the end when I went to create, it said the folder already exists and wouldn't continue (v3.5.1)

**Comment by AndrewBro** [comment]
Just try 
`vue create .`

**Comment by iostreamer-X** [comment]
This works but if one has a folder with a preexisting package.json, `vue create .` simply hijacks it.
This probably is very niche, but I wanted to have a monorepo and I built my server side first and then tried adding the client side stuff.

**Comment by spaceneenja** [comment]
If you don't have the Vue CLI installed globally you can still use `vue create` fairly easily.

`npx -p @vue/cli -- create my-vue-app`

It takes a while so go grab a latte or something.

You can also install it (again) as a devDependency in your new app to use `vue add` etc...

**Comment by ereztdev** [comment]
`vue create .` works 100%

**Comment by quangv** [comment]
I had thought `vue create .` would work, but turns if you're in a parent directory and do `vue create existingProject` you'd get more prompts:

![vue-create_Capture](https://user-images.githubusercontent.com/1171187/78505035-9cc42780-773e-11ea-9fc3-30236bda55e9.PNG)

I expected `vue create .` and `vue create existingProject` to be the same.

**Comment by Adnan-Bacic** [comment]
> If you don't have the Vue CLI installed globally you can still use `vue create` fairly easily.
> 
> `npx -p @vue/cli -- create my-vue-app`
> 
> It takes a while so go grab a latte or something.
> 
> You can also install it (again) as a devDependency in your new app to use `vue add` etc...

this is the only thing that worked for me. i wanted to avoid installing the vue cli globally since the yarn docs said it was a bad idea, you dont get the cli version in the package.json file. by installing it to every project you get the cli version in your dependencies, which is nice.

also i found
`npx vue create`
to be much faster than
`npx @vue/cli create`

**Comment by Subilan** [comment]
However, `vue create .` doesn't work if the current directory is named with capital letters. Although this is surely intended, I think the usage of `vue create <project-name> [location (relative or absolute)]` is better as it allows the difference between the project's name and the directory's name.

**Comment by 0xecho** [comment]
Yeah, if the folder naming doesn't follow the package naming conventions, you have to 1. rename the folder, 2. create the app, 3. rename the folder back.

**Comment by shomurodow** [comment]
`vue create .` or `npm create vue@latest .`

**Comment by vm-kit** [comment]
It asks me to remove existing files and continue. I already have git initialized, and some other files.

I want it to proceed and don't touch or merge whatever it has to do.
