### ISSUE TITLE
Uncaught SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by zhangbihua** [vuejs/vue-cli#151]
npm run dev 正常没有报错， 但是浏览器访问报错main.js?3479:1 Uncaught SyntaxError: Unexpected token import
![image](https://cloud.githubusercontent.com/assets/13499245/17842557/af01edd8-6856-11e6-97c3-62937e0ebbe4.png)
![image](https://cloud.githubusercontent.com/assets/13499245/17842563/beab8eba-6856-11e6-8096-2d63ba196667.png)

**Comment by zhangbihua** [comment]
看见将 /build/webpack.base.conf.js 配置文件中的 js 处理loader中的include注释可正常运行
```js
{
  test: /\.js$/,
  loader: 'babel',
  // include: projectRoot,
  exclude: /node_modules/
},
````

**Comment by dan0314** [comment]
因为浏览器不支持import啊

**Comment by luqingxuan** [comment]
我也是，好奇怪，vue1.x时候 没问题，升级2.x，就挂了

**Comment by luqingxuan** [comment]
http://stackoverflow.com/questions/35387991/webpack-vue-error
这篇应该能够帮助你

**Comment by luqingxuan** [comment]
http://stackoverflow.com/questions/35387991/webpack-vue-error
这篇应该能够帮助你

**Comment by onesez** [comment]
Uncaught SyntaxError: Unexpected token <
