### ISSUE TITLE
Add JSX feature

### ISSUE THREAD

**Issue by zzuu666** [vuejs/vue-cli#1516]
### What problem does this feature solve?
When I use vue-cli v3.0.0-beta.15 ,  I create a Vue project by `vue create vue-project`.I want to this project  use JSX. I have to config `babelrc` by myself, now. I think should add an option in step 2 `Check the features needed for your project`.

### What does the proposed API look like?
I think should add an option in step 2 `Check the features needed for your project`.

**Comment by yyx990803** [comment]
JSX is included by default. There's nothing you need to do.
