### ISSUE TITLE
importing vendor external style doesn't work inside project style file

### ISSUE THREAD

**Issue by lucileFievet** [vuejs/vue-cli#1519]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/lucileFievet/simple-relative-css-demo](https://github.com/lucileFievet/simple-relative-css-demo)

### Steps to reproduce
git clone https://github.com/lucileFievet/simple-relative-css-demo;
cd simple-relative-css-demo;
npm install;
npm run serve;

### What is expected?
We should build the usual lending page of Vue boiler plate application, as created from "vue create simple-relative-css-demo"

### What is actually happening?
It doesn't build with message : 
 ERROR  Failed to compile with 1 errors                                                                                               15:27:48

 error  in ./src/App.scss?vue&type=style&index=0&lang=scss

Module build failed (from ../node_modules/sass-loader/lib/loader.js):

#app {
^
      Media query expression must begin with '('
      in /home/awa/Projets/simple-relative-css-demo/src/App.scss (line 5, column 1)

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/lib??ref--8-oneOf-1-2!../node_modules/sass-loader/lib/loader.js??ref--8-oneOf-1-3!./src/App.scss?vue&type=style&index=0&lang=scss 4:14-307 14:3-18:5 14:307-18:4 15:22-315
 @ ./src/App.scss?vue&type=style&index=0&lang=scss
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

---
I just took the freshly generated boiler plate, add two vendors and set the css inside html inside separate scss files, add an import from my project asset. Import works fine, except when it is done inside a scss file and import an asset with external import ...  
Full description here https://stackoverflow.com/questions/50758738/vue-cli-import-relative-scss-is-not-working-for-vendors-external-librairies

**Comment by yyx990803** [comment]
You are missing a semicolon after the import statement...
There is still an error after that but it's not Vue CLI related.
