### ISSUE TITLE
npm install dependency failed

### ISSUE THREAD

**Issue by MAYDAY1993** [vuejs/vue-cli#152]
![image](https://cloud.githubusercontent.com/assets/14831051/17878229/efd93378-691b-11e6-9b7d-cded1bb5ab7a.png)

after npm install -g vue-cli ,I came across a problem when npm install devs ,I'm wondering why ?After that I tried twice ,both failed

**Comment by LinusBorg** [comment]
which template did you use?

**Comment by posva** [comment]
also, which node/npm version

**Comment by MAYDAY1993** [comment]
@posva  npm version is 2.14.7 ,I just follow the guide http://cn.vuejs.org/guide/installation.html about vue-cli,
 template is webpack

**Comment by DasonCheng** [comment]
It's just  `WARN` , so U can ignore

**Comment by posva** [comment]
Using npm@3.x.x everything works fine. I encourage you to use hat version in the future.
