### ISSUE TITLE
Project Create Error

### ISSUE THREAD

**Issue by marceloavf** [vuejs/vue-cli#1521]
### Version
3.0.0-beta.16

### Reproduction link
There is not reproduction link since it's Vue UI problem.

### Steps to reproduce
1. Init vue ui
2. Create a project with manual options
3. Select all resources
4. Options like this one:

![image](https://user-images.githubusercontent.com/5435657/41174773-7e4bd476-6b31-11e8-9965-11f0e5d4310b.png)

### What is expected?
Create a project

### What is actually happening?
Message: Cannot read property 'includes' of undefined
```shell
Error: GraphQL error: Cannot return null for non-nullable field Mutation.projectCreate.
    at new e (ApolloError.js:43)
    at Object.next (QueryManager.js:103)
    at Object.handler (client.js:108)
    at t.processReceivedData (client.js:443)
    at WebSocket.client.onmessage (client.js:397)
```

**Comment by Akryum** [comment]
I can't reproduce on my system (node 10.4.0, yarn 1.7.0, elementary OS linux).

**Comment by marceloavf** [comment]
Restarted the machine and worked fine (node 8.10.0, yarn 1.7.0, W10)
