### ISSUE TITLE
npm run build --mode [.env.mode] not working as expected

### ISSUE THREAD

**Issue by paanoop** [vuejs/vue-cli#1528]
### Version
3.0.0-beta.16

### Reproduction link
[https://codesandbox.io/s/qlx254n09j](https://codesandbox.io/s/qlx254n09j)

### Steps to reproduce
1. Create `.env.staging` file in the root 
2. Add key pairs `NODE_ENV=production` and `VUE_APP_ENV=staging` in the file
3. Add script to package.json      `"staging":"vue-cli-service build --mode staging",`
4. Run `npm run build --mode staging`
5. Run `npm run staging`

### Case 1
 `npm run buid --mode staging` 

gives a **production** oriented build with **staging** variables

### Case 2
 `npm run staging` 

gives a **production** oriented build with **staging** variables

### Case 1 
It gives a **production** oriented build with **production** variables

### Case 2 
It gives a **development** oriented build with **staging** variables

---
I need this to deploy this to Heroku. CD/CI. I'm using `postinstall` script to build `production`, `dev` or `staging` servers based on the `APP_VUE_ENV` variable. Please help me. I'm super excited with Vue so far!

### Reference: ###
https://cli.vuejs.org/guide/mode-and-env.html#example-staging-mode
https://github.com/vuejs/vue-cli/issues/948
https://forum.vuejs.org/t/how-to-build-production-app-with-varying-config/29708

**Comment by LinusBorg** [comment]
This is related to how npm passes arguments to scripts when using `npm run`
```
# passes the `mode` argument to npm
npm run build --mode staging

#passes the `mode` argument to vue-cli service`
npm run build -- --mode staging

**Comment by paanoop** [comment]
@LinusBorg There is no way that you get a **production** oriented build in a **staging** env. I added the npm commands just to demonstrate.

**Comment by yyx990803** [comment]
This seems to be a regression introduced in #1503

**Comment by jnarowski** [comment]
I'm having the same issue, I have this in my postinstall hook, deploying to dokku:

`"postinstall": "vue-cli-service build --mode staging"`

I have a .env.staging with 
`NODE_ENV=production
APP_ENV=staging
VUE_APP_ENV=staging
`

I just updated to the latest vue-cli (rc3). 
My staging build is not getting build as a production build, no minification etc. 

If I run 
`"postinstall": "vue-cli-service build --mode production"`

It builds properly on staging.

**Comment by heihachi88** [comment]
@LinusBorg ghost is right, there's no way to get exact production build, but with staging/test env.

**Comment by LinusBorg** [comment]
See my last comment.

**Comment by RobinManoli** [comment]
@LinusBorg this is still an issue, and the reproduction has been there since 9 Jun 2018

**Comment by LinusBorg** [comment]
the codesandbox that is provided by OP does not use Vue CLI 3, so is obviously *not* a valid reproduction.

**Comment by RobinManoli** [comment]
Ok never mind.

This issue actually seems resolved for me as I misunderstood the documentation. NOTE_ENV needs to be set explicitly and it is it works, even if using "staging":"vue-cli-service build --mode staging" in package.json

**Comment by LinusBorg** [comment]
Glad you could solve your problem.
