### ISSUE TITLE
Fix Accessibility and SEO Lighthouse scores

### ISSUE THREAD

**Issue by km333** [vuejs/vue-cli#1532]
### What problem does this feature solve?
Hi, 
Using 3.0.0-beta.15 I have created a new PWA app and immediately wanted to see the Lighthouse scores as this is something important to me. I got very good scores for Performance (94), Progressive Web App (91), Best Practices (94).
But a poor score for Accessibility (62) and SEO (? Errors).
I think it would be a quick win for the Vue team to fix these two up so everything is high when your users create a new project.
Cheers 

### What does the proposed API look like?
Accessibility main problems:
Image elements do not have [alt] attributes
Background and foreground colors do not have a sufficient contrast ratio
<html> element does not have a [lang] attribute

SEO Main problems:
Document does not have a meta description
Document doesn't have a valid hreflang
Document does not have a valid rel=canonical
Page has unsuccessful HTTP status code
Page is blocked from indexing

**Comment by yyx990803** [comment]
Accessibility and SEO are completely determined by the content you end up building - the score of the demo app is irrelevant since no one's gonna ship that as their actual app.
