### ISSUE TITLE
The router is not installed properly

### ISSUE THREAD

**Issue by ondrej-janosik** [vuejs/vue-cli#1537]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/ondrej-janosik/error-report-vue-cli-3](https://github.com/ondrej-janosik/error-report-vue-cli-3)

### Steps to reproduce
1) Create a project with VUE CLI 3 and select router option
2) npm run serve
3) Open browser and console - you will se error: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <App> at src\App.vue
       <Root>

### What is expected?
The router should be registered properly

### What is actually happening?
The router is not working - Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by yyx990803** [comment]
Did you create the project using the UI?

**Comment by Smekalin** [comment]
I have same problem with vue-cli 3.0.0-beta.11. It happens because main.js doesn't import router and doesn't include it in new Vue instance (https://github.com/ondrej-janosik/error-report-vue-cli-3/blob/master/src/main.ts#L6). It work properly in vue-cli 3.0.0-beta.16 for me. 
@ondrej-janosik  Can you check app creating for vue-cli 3.0.0-beta.16?

**Comment by ondrej-janosik** [comment]
@yyx990803 
I used "@vue/cli-service": "^3.0.0-beta.16" CI and the mistake persist.
@Smekalin
Main.js is still generated without the router included.

import Vue from 'vue'
import App from './App.vue'

Vue.config.productionTip = false

new Vue({
  render: h => h(App)
}).$mount('#app')

**Comment by yyx990803** [comment]
@ondrej-janosik please answer the question... did you create the project via the UI, or using the `vue create` command?

**Comment by Moland92** [comment]
@yyx990803 I get the exact same problem with the `vue create` command, so I suppose it is worth looking into. 

During creation I selected the following:
- Manually select features: `Babel`, `Typescript`, `Router`, `Vuex`, `CSS Pre-processors`, `Linter / Formatter`
- Use class-style component syntax? `Yes`
- Use Babel alongside TypeScript for auto-detected polyfills? `Yes`
- CSS Pre-processor: `SCSS/SASS`
- Linter / formatter: `TSLint`
- Lint features: `Lint on save`
- Configs: `In dedicated config files`

**Comment by yyx990803** [comment]
@Moland92 can you reproduce this every time, or it appears on and off? I can't reproduce it locally.

**Comment by Moland92** [comment]
@yyx990803 I get the same errors every time. 

Currently I am using a Macbook with High Sierra 10.13.4
I have tried using both `npm`and `yarn` commands to run the server.

**Comment by Moland92** [comment]
@yyx990803 
I tried adding the following to `src/main.ts`:
```
import Vue from 'vue';
import App from './App.vue';
import router from './router';  // Added this

new Vue({
    router,  // Added this
    render: (h) => h(App),
}).$mount('#app');
```

Seems to be working now.

**Comment by Smekalin** [comment]
@yyx990803 vue-cli 3.0.0-beta16 working for me, but I have similar behavior if my vue-cli version is 3.0.0-beta**11**. Can you try it? I did next steps:
1. npm i -g @vue/cli@3.0.0-beta11 
2. vue --version 
$ 3.0.0-beta.11
3. vue create app11
4. Enable router (you may disable or enable other points - it isn't important)
5. Waiting for create
5. File app11/src/main.js doesn't include router.

It reproduce every time.

**Comment by yyx990803** [comment]
@Smekalin if it doesn't happen in the latest version what's the point of looking at an older version?

**Comment by Smekalin** [comment]
@yyx990803 you are right 👍   It is more interesting to me.

**Comment by ondrej-janosik** [comment]
@yyx990803  I used vue create command. The problem no more occurs in the 3.0.0-beta.16, you can close this issue, thanks :)
![image](https://user-images.githubusercontent.com/18070427/41282753-29aa6b7e-6e35-11e8-8306-c08119339447.png)
![image](https://user-images.githubusercontent.com/18070427/41283242-56e8bca2-6e36-11e8-98a3-0333a9131068.png)
