### ISSUE TITLE
Develop en test simultaneously

### ISSUE THREAD

**Issue by andre-dw** [vuejs/vue-cli#1538]
### What problem does this feature solve?
Testing your Vue components while developing. 

### What does the proposed API look like?
yarn serve --test-unit

**Comment by yyx990803** [comment]
Use https://github.com/mysticatea/npm-run-all

**Comment by Akryum** [comment]
Or use the UI to run multiple tasks simultaneously. 😸

**Comment by andre-dw** [comment]
@Akryum Thanks! works perfectly within the UI. Is there an option to add -w flag in the ui to test?
