### ISSUE TITLE
cypress: EPIPE error on windows after successful test run

### ISSUE THREAD

**Issue by sandrosc** [vuejs/vue-cli#1539]
### Version
3.0.0-beta.15

### Reproduction link
[https://www.microsoft.com/en-us/windows](https://www.microsoft.com/en-us/windows)

### Steps to reproduce
- run windows
- create a new repo with cypress tests
- add the following command to package json: "test:e2e:headless": "vue-cli-service test:e2e --headless"
- run the command

### What is expected?
tests pass, process exits

### What is actually happening?
tests pass, EPIPE error

---
Issue with cypress: https://github.com/cypress-io/cypress/issues/1841

**Comment by yyx990803** [comment]
Yeah, this is a known issue in Cypress 3.0.

**Comment by yyx990803** [comment]
Confirm it's been fixed in Cypress 3.0.2.
