### ISSUE TITLE
baseUrl not support CDN address

### ISSUE THREAD

**Issue by yangmingshan** [vuejs/vue-cli#1545]
### Version
3.0.0-beta.16

### Reproduction link
[https://github.com/yangmingshan/vue-cli-issue](https://github.com/yangmingshan/vue-cli-issue)

### Steps to reproduce
- yarn
- npm run build

### What is expected?
dist folder is organized

### What is actually happening?
dist folder is messy

---
`baseUrl` is a CDN address in `vue.config.js`

**Comment by tardyp** [comment]
I think I reproduce this issue:

If I define a vue.config.js (even if empty), then the files are directly in the dist folder, instead of in dist/js and dist/css:
```
  dist/chunk-vendors.d99df5b7.js     1103.67 kb          344.56 kb
  dist/app.39f1f482.js               11.36 kb            4.65 kb
  dist/chunk-vendors.b8827354.css    277.19 kb           32.52 kb
  dist/app.7335e73a.css              0.07 kb             0.09 kb
```
