### ISSUE TITLE
transpileDependencies option doesn't work

### ISSUE THREAD

**Issue by dirknilius** [vuejs/vue-cli#1552]
### Version
3.0.0-beta.16

### Reproduction link
[https://codesandbox.io/s/1wn0368mv4](https://codesandbox.io/s/1wn0368mv4)

### Steps to reproduce
Add a package with modern browser syntax and add the `transpileDependencies: ["some-package"]` option in vue.config.js.

- Run the codesandbox example in IE 11 -> script error.
- Look and the source code -> not transpiled.

### What is expected?
The given package(s) should be transpiled.

### What is actually happening?
The option is ignored.

---
I have a npm dependency which uses ES6 features and is unfortunately not transpiled. So I added the `transpileDependencies: ["vue-moment"]` option to my vue.config.js. But the package ist not going to be transpiled. The build version contains all the const and let and spread operator stuff from the original. When I copy the file to the project source and use it all is fine. I also tried `transpileDependencies: [/.*/]` but not any single package is transpiled.

**Comment by yyx990803** [comment]
Sorry but that's not a valid repro since CodeSandbox is not using the latest CLI - please provide an actual repository.

**Comment by dirknilius** [comment]
@yyx990803 I created a new template and could not reproduce this issue. I made a diff with my current project setup and found that I had the babel config in `package.json` (as created by earlier cli beta). I moved the config to `babel.config.js` and now it's working. Shouldn't this be equal?

If this is the intended behavior please close this ticket.

**Comment by yyx990803** [comment]
Yep, `babel.config.js` must be used in order for `transpileDependencies` to work properly. Its behavior is different from `.babelrc` or babel in `package.json`.

**Comment by jessicarobins** [comment]
@dirknilius how did you get this to actually work?? I'm running into the same issue. Updated all vue cli dependencies to the latest versions and my babel.config.js looks just like one created by the newest version of the cli.

@yyx990803 here is a reproduction repo for you https://github.com/jessicarobins/vue-cli-bug-reproduction can this issue be reopened?

**Comment by App3x** [comment]
this can help, https://github.com/vuejs/vue-loader/issues/1411

**Comment by dodekeract** [comment]
@yyx990803 This should be added as a huge warning on the `vue-cli` docs. Perhaps, even `vue-cli` should warn when starting the app?
