### ISSUE TITLE
Static assets built using vue cli webpack results to MIME type issue. 

### ISSUE THREAD

**Issue by jofftiquez** [vuejs/vue-cli#1553]
### Version
2.9.3

### Reproduction link
[https://accounts-v4.mycure.md/](https://accounts-v4.mycure.md/)

### Steps to reproduce
Upload the dist folder and serve it to a Nginx web server.

### What is expected?
Files' mime type should be correct.

### What is actually happening?
I'm getting these errors:

Refused to apply style from <css url> because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

Refused to execute script from <js url> because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

---
I'm am sure that the problem is not within the nginx setup because I've tried uploading my old vue cli builds and they work perfectly fine with the same nginx configuration.

**Comment by yyx990803** [comment]
The files are not being found on your server so it's falling back to `index.html`. If the `dist` directory is working properly when previewed locally, then this is a deployment issue on your side. Closing unless a reproduction can be provided.

**Comment by jofftiquez** [comment]
@yyx990803 Yes, the `dist` folder does work locally. If the problem is within the deployment, why does the old build from old `vue cli` on the same webserver config?

**Comment by jefyisyous** [comment]
> @yyx990803 Yes, the `dist` folder does work locally. If the problem is within the deployment, why does the old build from old `vue cli` on the same webserver config?

Has the problem been finally solved?
