### ISSUE TITLE
Strange error "Unable to resolve path" during creating app with vue ui

### ISSUE THREAD

**Issue by Smekalin** [vuejs/vue-cli#1555]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/smekalin/test_babel_unit_linter](https://github.com/smekalin/test_babel_unit_linter)

### Steps to reproduce
1. Write <pre> vue ui </pre> in console
2. Create new project
3. Select npm package
4. Manually select features
5. Select babel, Linter and Unit testing
6. Next step select: ESLint   Airbnb config, Lint on save, Mocha   Chai
7. Click to create project

### What is expected?
There are no errors during application creation.

### What is actually happening?
<pre>
⠋  Running completion hooks...error: Unable to resolve path to module '@/components/HelloWorld.vue' (import/no-unresolved) at test/tests/unit/HelloWorld.spec.js:3:24:
  1 | import { expect } from 'chai';
  2 | import { shallowMount } from '@vue/test-utils';
> 3 | import HelloWorld from '@/components/HelloWorld.vue';
    |                        ^
  4 | 
  5 | describe('HelloWorld.vue', () => {
  6 |   it('renders props.msg when passed', () => {

1 error found.

</pre>

---
I investigated it and have found as to reproduce it: 
If I select Unit testing and Linter without Babel all is ok. If I select Unit testing, Linter, Babel I get error. 

I receive a error, but the application and unit tests works.

I'm using:
* macbook with High Sierra 10.13.5
* npm 5.6.0

**Comment by thejprice** [comment]
I can confirm this is happening to me as well.

**Comment by jp-sauve** [comment]
and me! It still says "running completion hooks" so I don't know whether it is stuck or still going.

**Comment by Akryum** [comment]
@jp-sauve This issue was fixed and closed a week ago. Please open a new issue with all the details necessary to understand your issue and to reproduce it.
