### ISSUE TITLE
[vue ui] Run tasks in vue ui, it adds `--mode` flag even I already have one in script command.

### ISSUE THREAD

**Issue by laomao800** [vuejs/vue-cli#1561]
### Version
3.0.0-beta.16

### Reproduction link
[https://codesandbox.io/s/yp18qom2kx](https://codesandbox.io/s/yp18qom2kx)

### Steps to reproduce
1\. Already have a `--mode` flag in script command.

```javascript
// package.json
{
  "scripts": {
    "build:dev": "vue-cli-service build --mode build-dev"
  },
  // ...
}
```

2\. Run the task in ui will get this:

```bash
$ vue-cli-service build --mode build-dev --mode development --dest dist --target app --dashboard
```

It still adds a `--mode` flag even the command has one.

### What is expected?
Use the correct mode value from command `--mode`.

### What is actually happening?
Have two `--mode` in the command.

**Comment by voluntadpear** [comment]
Shouldn't each Task check for existing flags before pushing new flags to the `args` array?

For this particular case, the [implementation of onBeforeRun](https://github.com/vuejs/vue-cli/blob/61662c49cc26732f2fd89cf7c54c4668314627dd/packages/%40vue/cli-ui/ui-defaults/tasks.js#L250) could check if each of the flags it's pushing already exists before trying to push them.

**Comment by Akryum** [comment]
What if you want to override an argument with the UI?

**Comment by voluntadpear** [comment]
I think having a checkbox on the UI to decide if we want to override arguments or not could be a good option. What do you think @Akryum?

Or maybe overriding arguments with the UI should be the correct behavior?

**Comment by Akryum** [comment]
I think putting checkboxes everywhere would really clutter the UX.

**Comment by laomao800** [comment]
@Akryum  I already install the rc5. 

In the UI tasks, it can remove the duplicate arguments now, but how could I use my own `--mode` value ?

I have some custom environment value in the `.env.build-dev` file.

**Comment by Akryum** [comment]
I've added `(unset)` options in the mode selects.
