### ISSUE TITLE
vue-cli 3.0.0-rc.1 vue ui serve and the new page console show [HMR] Hot Module Replacement is disabled

### ISSUE THREAD

**Issue by zhouxinyong** [vuejs/vue-cli#1569]
### Version
3.0.0-rc.1

### Steps to reproduce
1. install vue-cli@3.0.0-rc.1
2. run vue ui
3. create a new project
4. run serve

### What is expected?
open the new page show the app content

### What is actually happening?
the page show blank,and open dev console,there is show: Uncaught Error: [HMR] Hot Module Replacement is disabled.

###
when I not use vue ui and run yarn run serve in terminal it work well.

**Comment by Akryum** [comment]
This is already fixed.

**Comment by WustLCQ** [comment]
Have you solved it? I met this problem, too

**Comment by Akryum** [comment]
@WustLCQ The fix will be released in the next release.

**Comment by space87** [comment]
How do we fix this now ?

**Comment by Akryum** [comment]
Run `npm run serve` or `yarn serve` in a terminal.

**Comment by dohomi** [comment]
@Akryum I updated to rc-2 but the error inside the vue-cli serve command still persist.

If I run:
```
# npm run serve
[HMR] Waiting for update signal from WDS...
```
The entire chrome hangs up and I have to destroy the chrome session. Any idea where this error might comes from?

**Comment by Akryum** [comment]
@dohomi Did you upgrade all the plugins in your project as well?

**Comment by dohomi** [comment]
@Akryum sorry for the noise it was an issue on my computed variable - `npm run serve` works as expected-

**Comment by zhouxinyong** [comment]
3.0.0-rc.2 has fixed this problem,thanks

**Comment by HunderlineK** [comment]
rc.2 hasn't solved this problem for me. I'm using the custom build with yarn and all the options available on windows

**Comment by Akryum** [comment]
@HunderlineK Please open a new issue with a reproduction. Thanks!
