### ISSUE TITLE
name and author is default needed in meat.js?

### ISSUE THREAD

**Issue by bmxklYzj** [vuejs/vue-cli#1570]
### Version
2.9.3

### Reproduction link
[https://github.com/bmxklYzj/vue-template-test](https://github.com/bmxklYzj/vue-template-test)

### Steps to reproduce
background: I an using vue-cli to make my own template.But name and author in prompts is default in meta.js, how can i remove it ?

1. exec `vue init bmxklyzj/vue-template-test my-test` 

which  bmxklyzj/vue-template-test contains a simple empty meta.js like this:

```js
module.exports = {
    prompts: {
    },
    complete(data, {chalk}) {
        console.log('done');
    }
};
```

2. and then it prompts me to input name and author. But i didn't set name and author in prompts. Are these two key automatically added? How can i remove it?

### What is expected?
it only prompt what I have set in prompts in meta.js

### What is actually happening?
name and author is set automatically and I can't change it's default value.

**Comment by bmxklYzj** [comment]
I explain why i don't need name and author:

In general, I will keep the destDirName and name the same value, so i use destDirName and name is unnecessary. And sometimes i want to add author as the default value and don't prompt the user to confirm.

for example:

```js
metalsmith: function (metalsmith, opts, helpers) {
        metalsmith._metadata.date = formatDate(new Date());
        metalsmith._metadata.author = 'my-git-author';
 },
```

in this way, date and author is default value and will not prompt user to confirm.

If the vue-cli not add name and author to the prompts field, which i don't need, i can enter as less as `enter` to create my template.

**Comment by yyx990803** [comment]
Sorry but 2.x is in maintenance mode and we won't be making feature changes for that version anymore.
