### ISSUE TITLE
[Critical] hot-reload AND refreshing the page in iOS Safari does not show any updates

### ISSUE THREAD

**Issue by ethanchiu10** [vuejs/vue-cli#1571]
### Version
3.0.0-rc.1

### Reproduction link
[https://github.com/ethanchiu10/vuecli-basic-setup-bug](https://github.com/ethanchiu10/vuecli-basic-setup-bug)

### Steps to reproduce
1. run 'vue ui'
2. create a new project with the default preset
3. open the site in mobile safari (tested on iP7  and iPX on ios 11.3.1 and ios 12)
4. change something in HelloWorld and save (e.g. change the first word from "For guide" to "4 guide")
5. press refresh in safari

### What is expected?
a. Updates should be hot-reloaded
b. Refreshing the page should definitely show updates

### What is actually happening?
No updates are shown

---
Demo on 2 different machines

https://youtu.be/bqV2SWcixzo

https://youtu.be/knw53evSvdg

**Comment by Akryum** [comment]
Are you using the UI to run `serve`?

**Comment by ethanchiu10** [comment]
After deleting the .npm folder, and re-installing it, it worked again. I guess one of the cached modules was causing the issue.

**Comment by VetBoard** [comment]
@ethanchiu10 Where did you find the .npm folder? Which OS are you using?

Got the same isssue but can't figure out where the folder is.

**Comment by ethanchiu10** [comment]
@VetBoard On my mac, its at ~/.npm

**Comment by ethanchiu10** [comment]
@VetBoard On my mac its at ~/.npm
