### ISSUE TITLE
Javascript bundles referenced with invalid absolute paths in "index.html" when building app

### ISSUE THREAD

**Issue by TAGC** [vuejs/vue-cli#1572]
### Version
3.0.0-rc.1

### Reproduction link
[https://github.com/TAGC/vue-expandable-grid/commit/fe08cb83eae3a5a5a6c15cd03dd24e2270768b02](https://github.com/TAGC/vue-expandable-grid/commit/fe08cb83eae3a5a5a6c15cd03dd24e2270768b02)

### Steps to reproduce
After cloning and installing dependencies, run `$ ./node_modules/.bin/vue-cli-service build ./src/index.ts` in the project root directory. This should generate `dist/index.html` and app/vendor bundles under `dist/js`. Open `dist/index.html` in a browser and confirm it gets 404s trying to load the bundles.

### What is expected?
`dist/index.html` to be generated where it references the bundles as relative paths:

```html
<body>
    <div id=app></div>
    <script src=./js/chunk-vendors.0676a3e4.js></script>
    <script src=./js/app.1196cf87.js></script>
</body>
```

### What is actually happening?
The HTML file gets generated referencing the bundles at invalid absolute paths:

```html
<body>
    <div id=app></div>
    <script src=/js/chunk-vendors.0676a3e4.js></script>
    <script src=/js/app.1196cf87.js></script>
</body>
```

---
Manually changing the absolute paths to relative paths after generating the HTML file causes the JS bundles to be loaded successfully.

**Comment by Akryum** [comment]
Are you trying to open the page directly from your file explorer? If so, it won't work since you are not on a real HTTP server. To test your deploy locally, you can use for example [this small utility](https://github.com/zeit/serve) which can expose your files in an HTTP server on localhost just like if you would have uploaded them on a real server.

**Comment by TAGC** [comment]
Ah okay, that's awesome thanks.
