### ISSUE TITLE
api.onViewOpen is not a function

### ISSUE THREAD

**Issue by maple3142** [vuejs/vue-cli#1575]
### Version
3.0.0-beta.16

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
1. Enter `vue ui` in command line
2. Create a project (package manager: npm, preset: babel,eslint) in the ui interface
3. After project created, you will get a error: `api.onViewOpen is not a function`

### What is expected?
No error happening

### What is actually happening?
Error: `api.onViewOpen is not a function`

---
os: win10
node: 10.1.0
npm: 6.1.0

And sorry for wrong minimal reproduction link, I don't know how to create a reproduction about a `vue-cli`'s ui.

**Comment by Akryum** [comment]
Please upgrade to the latest release of `@vue/cli`.

**Comment by maple3142** [comment]
Thanks, it works after update to latest.
