### ISSUE TITLE
Vue-cli UI Code Editor

### ISSUE THREAD

**Issue by P9Q** [vuejs/vue-cli#1579]
### What problem does this feature solve?
It would be great if you also add a simple code editor to Vue-Cli UI, so the developer can also edit Vue codes using the Vue-cli UI.

### What does the proposed API look like?
The following code editors have been written in JavaScript and available on Github:

[ACE](https://github.com/ajaxorg/ace)
[CodeSandbox](https://github.com/CompuIves/codesandbox-client)

Many [projects ](https://ace.c9.io/#nav=production)use ACE as their code editors, it also has dark themes, an example project [LAEditor](https://github.com/dwijitsolutions/laeditor), [screenshot](http://laraadmin.com/img/laraadmin/laraadmin-online-code-editor.jpg) and [video](https://www.youtube.com/watch?v=emo9qmS_Q3s).

**Comment by Akryum** [comment]
I don't think we should and can maintain a code editor as a builtin feature of vue-cli, we already have a lot of work. But this should be possible to do as a community plugin.
