### ISSUE TITLE
vue-loader strip out html comments in <template> section?

### ISSUE THREAD

**Issue by cnweibo** [vuejs/vue-cli#158]
Under dev environment, i'd like to keep the comments information in both <template>and <style> and <script> section in .vue file.
Unfortunately, it seems that all the comments(html,js,css) are stripped out in webpack dev environment.
How can i disable that?
For example, in following del-container.vue file, i add html comments within the root div of the component, when inspecting in chrome dev tool, that comment 
`<!-- del-container -->`
 is not available
```
<template>
	<div :class=" containerClass ">
        <!-- del-container -->
		<slot></slot>
		<span class="m-del-container__close" @click="deleteIt"><span >x</span></span>
	</div>
</template>
```

**Comment by zigomir** [comment]
@cnweibo https://github.com/vuejs/vue-loader
