### ISSUE TITLE
Option or documentation to enable less javascript support

### ISSUE THREAD

**Issue by JCKodel** [vuejs/vue-cli#1586]
### What problem does this feature solve?
When compiling a LESS app with javascript, it fails (and there apparently no place to config the less loader to enable it):
ALSO, my app uses LESS and SASS (but the initial choice is a "select only one option" =\)

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                 14:38:58

 error  in ./src/assets/less/framework7.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


        background-size: 8px 13px;
        .ltr({
      ^
Inline JavaScript is not enabled. Is it set in your options?
```

### What does the proposed API look like?
1) Allow to choose one or more CSS pre-processors (SASS + LESS)

2) Ask if JavaScript should be enabled when LESS is chosen (alone or with SASS).

- OR -

Allow loaders settings somehow (may fix this and future issues with loaders).

```
{
        test: /\.less$/,
        use: [{
            loader: "style-loader"
        }, {
            loader: "css-loader"
        }, {
            loader: "less-loader",
            options: {
                javascriptEnabled: true
            }
        }]
}
```

Perhaps an section in packages.json?

```
{
    "loader-options":
    {
        "less-loader": { javasciptEnabled: true }
    }
}
```

**Comment by yyx990803** [comment]
Please read the docs... https://cli.vuejs.org/config/#css-loaderoptions
