### ISSUE TITLE
In the UI consider using a less-subtle color for the Cancel/Previous buttons

### ISSUE THREAD

**Issue by somascope** [vuejs/vue-cli#1588]
### What problem does this feature solve?
Once I learned where the Cancel button was, this was not as much of an issue, but initially I couldn't see where it was. On one hand, I appreciate the subtly of these buttons, but it did make the initial discovery of them by a new user slower than it could be.

### What does the proposed API look like?
This is a UI suggestion, nothing to do with API.

**Comment by Akryum** [comment]
You mean add a background color to them?

**Comment by rubenmoya** [comment]
If you mean this one:

![screen shot 2018-07-20 at 10 12 48](https://user-images.githubusercontent.com/905225/42991310-7ae9070a-8c05-11e8-82e3-9081e62b6d23.png)

for me is more a position problem than a color one, I think putting both the `next` and `cancel` buttons together would make a huge difference.

**Comment by Berkmann18** [comment]
It's indeed not very UX friendly, I can understand the green/lime theme applied to buttons but usually, users (mainly new ones) would expect it to be more noticeable, in other words, red-ish and closer to the "click zone" (I can't remember the exact UX term that describes the area of an app where the user would focus his/her attention more in regards to buttons).
