### ISSUE TITLE
Consider including a link to About in the Project Manager

### ISSUE THREAD

**Issue by somascope** [vuejs/vue-cli#1589]
### What problem does this feature solve?
I had seen the About page (as a new user of the UI) once after init'g a project using the UI, but had then deleted a project. At this point, back in the Project <anager, I was not able to access About. Perhaps including it  in the button bar along with Projects, Create and Import...?

I also found that, once in a project, it was a little cumbersome to use the "... More"  mechanism in the lower-left to access "Vue Project Manager" and essentially go back to the main screen. At the same time, it does keep the UI a bit cleaner & leaner. But perhaps since there aren't many options in a project's left-side bar, these don't have to be hidden in a tooltip kind of mechanism.

### What does the proposed API look like?
No coding API stuff with these suggestions.

**Comment by Akryum** [comment]
You have two other ways of accessing the project manager: the most left-side button on the status bar at the bottom (which I recently turned into a "home" icon) and the project selector on the left side of the top bar.
