### ISSUE TITLE
Add confirmation to Project Manager deletion of projects

### ISSUE THREAD

**Issue by somascope** [vuejs/vue-cli#1590]
### What problem does this feature solve?
I tried out the trash can icon, knowing it was a delete feature, to see how it would handle a project I had just created. I was surprised that the project was deleted immediately without any confirmation UX. I then realized that the files are still on my computer, and it was quick for me to import the folder. Please consider adding a confirmation to this experience.

For new users, it might also be helpful for them to see a message that says their files still exist, something to that effect.

### What does the proposed API look like?
No API stuff.

**Comment by Akryum** [comment]
See https://github.com/vuejs/vue-cli/issues/1582#issuecomment-397612513

**Comment by Akryum** [comment]
I changed the icon and tooltip to make it more clear that it doesn't delete the project files.
