### ISSUE TITLE
after upgrading to rc2, wrong package versions are installed on a new create

### ISSUE THREAD

**Issue by vesper8** [vuejs/vue-cli#1591]
I just upgraded to rc2 from  beta.16

@vue/eslint-config-airbnb

vue -V
```
3.0.0-rc.2
```

Then I created a new project

vue create rc2-test. I tried using a custom set of features as well as just choosing the 'default'. Below is the results of 'default'

after creating, upon inspection of the package.json

```
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-beta.15",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.15",
    "@vue/cli-service": "^3.0.0-beta.15",
    "vue-template-compiler": "^2.5.16"
  },
```

I would expect the following: 

```
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-rc.2",
    "@vue/cli-plugin-eslint": "^3.0.0-rc.2",
    "@vue/cli-service": "^3.0.0-rc.2",
    "vue-template-compiler": "^2.5.16"
  },
```

Despite this, if I import this project in the UI, it shows that the plugins are up-to-date

![screenshot 2018-06-16 00 38 16](https://user-images.githubusercontent.com/816028/41490662-c53081e4-70fd-11e8-88fa-aa8faf9dc981.png)

I edited the package.json manually and replaced beta.15 by rc.2

deleted the node_modules / lock file and ran npm install again and this time it shows the latest versions

perhaps this is only superficial but I found it odd

====================

Another thing, because I don't want to open another issue for this. I noticed something.. 

When I try to update the plugins via the UI

These two are never listed:

```
    "@vue/eslint-config-airbnb": "^3.0.0-beta.10",
    "@vue/test-utils": "^1.0.0-beta.10",
```

They are not listed if I browse for plugins either.. I am surprised the UI doesn't give me the option to update these ?

I updated them manually:

```
    "@vue/eslint-config-airbnb": "^3.0.0-rc.2",
    "@vue/test-utils": "^1.0.0-beta.16",
```

But I think the UI should assist in updating them.. since these are installed as a result of picking the features when running vue create

**Comment by Akryum** [comment]
See https://github.com/vuejs/vue-cli/issues/1582#issuecomment-397612513
