### ISSUE TITLE
baseUrl not support relative path

### ISSUE THREAD

**Issue by diaevd** [vuejs/vue-cli#1592]
### Version
3.0.0-rc.2

### Reproduction link
[https://github.com/diaevd/test-vue-cli-baseurl](https://github.com/diaevd/test-vue-cli-baseurl)

### Steps to reproduce
* vui-cli create project
* add baseUrl: '.' | './' | '' to vue.config.js
* yarn build

### What is expected?
dist folder is messy

### What is actually happening?
looks like:
```
 DONE  Compiled successfully in 4079ms                                                                                                                                                                    11:13:11 AM

  File                              Size                 Gzipped

  dist/chunk-vendors.f5381230.js    109.82 kb            38.06 kb
  dist/app.6cc08edc.js              5.97 kb              2.33 kb
  dist/0.0fd8cf39.js                0.54 kb              0.39 kb
  dist/app.1649cae2.css             0.42 kb              0.26 kb

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
```

**Comment by LinusBorg** [comment]
I hm don't understand, what's wrong with the outcome that you showed? 

And why would you expect the dist folder content to be "messy", whatever you mean by that?

**Comment by diaevd** [comment]
I expect as a result split by subfolders, as is done

baseUrl: './'

on out expected:
"./js/app.6cc08edc.js" but not "./app.6cc08edc.js"

for now we have cuted js/ css/ if relative path in baseUrl

i expected:

```
  dist/js/chunk-vendors.f5381230.js    109.82 kb            38.06 kb
  dist/js/app.6cc08edc.js              5.97 kb              2.33 kb
  dist/js/0.0fd8cf39.js                0.54 kb              0.39 kb
  dist/css/app.1649cae2.css             0.42 kb              0.26 kb
```

**Comment by yyx990803** [comment]
The docs explains: when using a relative baseUrl, assets have to be at the root in order urls in CSS to work as intended.

**Comment by diaevd** [comment]
Maybe you can add advanced option for split by subfolders with a relative baseUrl?

**Comment by LinusBorg** [comment]
No, probably not. 

There's technical limitations to this (with webpack / css-loader etc.) that we can't work around as far as we can yell.
