### ISSUE TITLE
Configuration Tab in UI (ESLint configuration) very buggy

### ISSUE THREAD

**Issue by marbuser** [vuejs/vue-cli#1593]
### Version
3.0.0-rc.2

### Reproduction link
[https://jsfiddle.net/pbvmzegc/](https://jsfiddle.net/pbvmzegc/)

### Steps to reproduce
1. Start UI with `vue ui`.
2. Setup a project that contains ESLint. (I use ESLint   Prettier).
3. Go to configure tab, eslint options, and click open "eslintrc". (This will give you an error `Could not open package.json in the editor.` in sudo or `Could not open package.json in the editor. The editor process exited with an error: spawn code ENOENT.` if not in sudo.
4. Configure options and click "Save" and nothing will happen.
5. Console error below appears.
`Unhandled promise rejection Error: GraphQL error: Cannot read property 'rules' of undefined`

### What is expected?
Upon configuring eslint and clicking save, it should configure it rather than doing nothing.

### What is actually happening?
Nothing. The page stays the same, no files are changed.

**Comment by Akryum** [comment]
> Go to configure tab, eslint options, and click open "eslintrc". (This will give you an error Could not open package.json in the editor. in sudo or Could not open package.json in the editor. The editor process exited with an error: spawn code ENOENT. if not in sudo.

It seems you have a problem with [launch-editor](https://github.com/yyx990803/launch-editor), open an issue there. Also check that your editor is supported.

> Console error below appears.
Unhandled promise rejection Error: GraphQL error: Cannot read property 'rules' of undefined

Fixed in https://github.com/vuejs/vue-cli/commit/5885dd52e2dc47df0bad75d94ab821459e074668

**Comment by liunewshine** [comment]
I have the same problem.
