### ISSUE TITLE
Add visible notification (or logging) when importing existing projects

### ISSUE THREAD

**Issue by glenndevenish** [vuejs/vue-cli#1594]
### What problem does this feature solve?
Run `vue ui` and import a project - there is no visible way of knowing that your project is importing (so you end up with lots of duplications after you keep pressing import)

The end user experience would be a notification that the project is loading and/or logging on the console to alert the user what is happening.

### What does the proposed API look like?
I propose changing the 'import a project' button to a disabled 'importing...' button in the current folder (so you can import others while it is happening). Logging would be nice too...

Open to suggestions though!

**Comment by Akryum** [comment]
You may have tried importing a project which didn't have the node_modules installed. Make sure to run `npm install` or `yarn` in it before importing (this will be done for you in a future release).
