### ISSUE TITLE
UI should prevent from entering an invalid project name

### ISSUE THREAD

**Issue by zoispag** [vuejs/vue-cli#1596]
### Version
3.0.0-rc.2

### Reproduction link
[https://jsfiddle.net/zoispag/rba9coxn/](https://jsfiddle.net/zoispag/rba9coxn/)

### Steps to reproduce
- Open vue-ui.
- Create project with any preset
- Choose either yarn or npm.

### What is expected?
To create/download the project

### What is actually happening?
Response in terminal
`{"type":"error","data":"package.json: Name contains illegal characters"}
command failed: yarn --json`

---
Package.json contains:

```json
{
  "name": "Projects/vueSpa",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-beta.15",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.15",
    "@vue/cli-service": "^3.0.0-beta.15"
  }
}
```

**Comment by Akryum** [comment]
You shouldn't put a `/` in your project name.

**Comment by zoispag** [comment]
Thanks for your immediate response. I didn't want to put a `/` in my project name, rather that creating the project inside `~/Projects/projectname/` but it wouldn't allow me to choose a path.

**Comment by zoispag** [comment]
Ok. I just realised how UI works. You have to run `vue ui` from dir where you want to create your project!

**Comment by zoispag** [comment]
I started UI in `~` and I couldn't navigate to child dirs from inside ui. Only to parent.
Maybe this is something worth investigating.

**Comment by Akryum** [comment]
Did you have any error in the browser console or the terminal?

**Comment by zoispag** [comment]
Unfortunately no errors.

**Comment by Akryum** [comment]
Could you try with ` vue ui -D` and see if there are errors?

**Comment by zoispag** [comment]
I get no errors in the console, but I get an "error" in the ui.
![image](https://user-images.githubusercontent.com/21138205/41502328-c23f0b26-71b7-11e8-838f-f1611e231c26.png)

I can't select my user to go to `~` path. 

Does this help?

**Comment by Akryum** [comment]
What's the error in the browser console?

**Comment by Akryum** [comment]
I added name validation in https://github.com/vuejs/vue-cli/commit/8957c3aff842295a839a7fc5db520180e57c9dcf

**Comment by Akryum** [comment]
Let's continue here: https://github.com/vuejs/vue-cli/issues/1599
