### ISSUE TITLE
Make --stdin flag of webpack available by vue-cli-service

### ISSUE THREAD

**Issue by LostKobrakai** [vuejs/vue-cli#1597]
### What problem does this feature solve?
Same rational which lead webpack to implement the flag in the first place: https://github.com/webpack/webpack/issues/1308

### What does the proposed API look like?
`vue-cli-service serve|build --stdin` or ``vue-cli-service serve|build --watch-stdin``

**Comment by sodatea** [comment]
The `--stdin` flag is added in 4.2.
