### ISSUE TITLE
Can't list home directory content

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue-cli#1599]
Version: 3.0.0-rc.2

Original messages:

> I started UI in ~ and I couldn't navigate to child dirs from inside ui. Only to parent.
Maybe this is something worth investigating.

> I get no errors in the console, but I get an "error" in the ui.
![image](https://user-images.githubusercontent.com/21138205/41502328-c23f0b26-71b7-11e8-838f-f1611e231c26.png)
> I can't select my user to go to `~` path.

See https://github.com/vuejs/vue-cli/issues/1596#issuecomment-397827603

**Comment by zoispag** [comment]
Unfortunately I get nothing on the browser console either.
![image](https://user-images.githubusercontent.com/21138205/41506205-d2ce0c0a-7219-11e8-9194-666fa973c082.png)

**Comment by Akryum** [comment]
Could you follow those steps to help me find the cause of the issue:
- open the Chrome devtools
- refresh the page
- reproduce the error in the UI
- go to the `/graphql` websocket request in the network tab
- open the `Frames` sub tab
- check for the message with a down red arrow, those are the server to client ones
- find the ones with the `errors` array
- paste the result here

**Comment by zoispag** [comment]
I identified the issue! It was cause by the wrong first try with the `/` in the path, inside json.
Although it is interesting the fact that it was "complaining" because of a project inside Trash Bin.

Here's the error frame from graphql:

```json
{
    "type": "data",
    "id": "19",
    "payload": {
        "errors": [
            {
                "message": "/Users/zoispag/.Trash/package.json: Unexpected token / in JSON at position 1047",
                "locations": [
                    {
                        "line": 18,
                        "column": 5
                    }
                ],
                "path": [
                    "folderOpen",
                    "children",
                    2,
                    "isVueProject"
                ]
            }
        ],
        "data": {
            "folderOpen": {
                "name": "zoispag",
                "path": "/Users/zoispag",
                "favorite": false,
                "isPackage": false,
                "isVueProject": false,
                "children": [
                    ...
                ],
                "__typename": "Folder"
            }
        }
    }
}
```
