### ISSUE TITLE
vue-cli脚手架能本地mock数据么？

### ISSUE THREAD

**Issue by yuweilan** [vuejs/vue-cli#160]

**Comment by zigomir** [comment]
Sorry, not `vue-cli`'s job to mock the data. But maybe you were looking for something like this: https://github.com/vuejs/vueify-example/blob/master/test/unit/a.spec.js#L22-L43

**Comment by lichinlichin** [comment]
I search the 'mock' end here too.
and the link by@zigomir is unreachable.

**Comment by ycshill** [comment]
I search the 'mock' end here too.
and the link by@zigomir is unreachable too！
