### ISSUE TITLE
enable showing of postcss warnings

### ISSUE THREAD

**Issue by franktopel** [vuejs/vue-cli#1601]
### What problem does this feature solve?
Especially autoprefixer postcss plugin generates meaningful, important warning messages. These should be shown on the console, or at least optionally enableable.

Test with this css:

```
.warn {
    grid-column-end: 3;
    grid: subgrid;
    grid-template-areas: "head head"
                         "nav  main"
                         "foot ....";
}
```

Using the postcss-cli along with this postcss.config.js

```
module.exports = {
    plugins: [
        require('autoprefixer')({grid: true})
    ]
}
```

will issue this warning:

```
2:5	⚠  Can not prefix grid-column-end (grid-column-start is not found) [autoprefixer]
4:5	⚠  Can not find grid areas: head, nav, main, foot [autoprefixer]
```

### What does the proposed API look like?
Make some config option available that allows showing of postcss warning in dev and prod build.

Andrey Sitnik (creator of postcss, autoprefixer etc) asked me to open this issue here.

**Comment by ai** [comment]
Every PostCSS runner must show warning you can take it from `result.warnings()`.

Maybe PostCSS plugins use warnings. For instance, Autoprefixer’s warnings were created to prevent most popular users mistakes.

**Comment by franktopel** [comment]
For some strange reason I am now getting those warnings, hence closing the issue.
