### ISSUE TITLE
vue-cli presets to be fully configurable 

### ISSUE THREAD

**Issue by ZainW** [vuejs/vue-cli#1603]
### What problem does this feature solve?
To be able to create a fully personally configured vue-cli project using the existing remote presets.

For example if there is project that I want to create with a preconfigured `.eslintrc.js` with certain rules I cant seem to find a way to do so.

It allows consistant project creation which is very important to users who create and maintain multiple projects

### What does the proposed API look like?
```json
{
  "useConfigFiles": true,
  "plugins": {
    "@vue/cli-plugin-babel": {},
    "@vue/cli-plugin-eslint": {
      "config": "standard",
      "lintOn": ["save"],
      "extends": ["plugin:vue/strongly-recommended"],
      "rules": {
        "no-console": "off",
        "no-debugger": "error",
        "vue/attribute-hyphenation": ["error", "always"],
        "vue/html-indent": ["error", 2],
        "vue/require-prop-types": "error",
        "vue/attributes-order": "error",
        "vue/html-quotes": ["error", "double"],
        "vue/order-in-components": "error",
        "vue/html-end-tags": "error",
        "vue/html-self-closing": "error"
      }
    },
    "@vue/cli-plugin-unit-mocha": {},
    "@vue/cli-plugin-e2e-cypress": {}
  },
  "router": true,
  "vuex": true,
  "cssPreprocessor": "sass"
}
```

or something similar to edit/inject things

**Comment by Akryum** [comment]
You can make a small vue-cli plugin which has a generator that use `api.extendPackage` to add new eslint rules.

**Comment by ZainW** [comment]
sounds good as a temp solution will do that in the meantime

**Comment by yyx990803** [comment]
https://cli.vuejs.org/guide/plugins-and-presets.html#presets

See the `configs` field in your preset - you can use that to inject pre-defined config for a few tools.

**Comment by lastobelus** [comment]
@yyx990803 I'm struggling to understand how to use this information to make a cli preset that sets up eslint to use `vue/recommended` (with prettier)  instead of `vue/essential`
