### ISSUE TITLE
使用vue-cli的创建项目命令出现vue-cli · connect ETIMEDOUT 192.30.252.137:443

### ISSUE THREAD

**Issue by skykobe** [vuejs/vue-cli#161]
怎么办，的确我的电脑ping不通github.com。。。。

**Comment by leohxj** [comment]
segmentfault 上有人提问过 [vue-cli 创建项目的时候出现connect ECONNREFUSED 错误，请问如何解决？](https://segmentfault.com/q/1010000005998968)， 我也回答了下。

**Comment by zigomir** [comment]
Closing because it's not `vue-cli` specific issue.
