### ISSUE TITLE
custom ENV variables are undefined all the time

### ISSUE THREAD

**Issue by VladPavliuk** [vuejs/vue-cli#1610]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/VladPavliuk/Client-games](https://github.com/VladPavliuk/Client-games)

### Steps to reproduce
1. Clone repository mentioned before.
2. npm run serve.
3. Look in the console of browser.

### What is expected?
I expect to use some variable wich defined in env files and see it value

### What is actually happening?
Instead, I see undefined every time when I try to usesome custom env variable

**Comment by yyx990803** [comment]
As the doc says, only env vars starting with VUE_APP will be exposed to your client code.

**Comment by damienmcd** [comment]
I was having the same issue but the issue I was having was that I did not rebuild the project by stopping the development environment and re-running 'npm run serve'.
After an hour of frustration I figured it out. I was having a bad morning. The same may be happening to others who are expecting that the environment variables will be available after a hot-reload instead of re-building.

**Comment by tomko80** [comment]
> I was having the same issue but the issue I was having was that I did not rebuild the project by stopping the development environment and re-running 'npm run serve'.
For me it took a cople of restarts for this to apply. Even emptied the browser cache. Is there some expiration time? Very annoying feature.

**Comment by ravindragaikwad** [comment]
I fixed it by running
npm run build
npm run dev
then it started reading the env values.

**Comment by hawkup** [comment]
I found this issue too. I fixed by restart my notebook and re-run project again.

**Comment by KStockton** [comment]
> I was having the same issue but the issue I was having was that I did not rebuild the project by stopping the development environment and re-running 'npm run serve'.
> After an hour of frustration I figured it out. I was having a bad morning. The same may be happening to others who are expecting that the environment variables will be available after a hot-reload instead of re-building.

This was my issue. Thank you.

**Comment by VusalShahbazov** [comment]
variables should start with VUE_APP_*

**Comment by syahioo** [comment]
> variables should start with VUE_APP_*

this solution, work for me

**Comment by viniciusrma** [comment]
this shit still not working for me

**Comment by Kane-R-G** [comment]
How can something so basic be so difficult to get aq straight answer?

**Comment by arepp23** [comment]
As of 2023:

Had to:

- Stop the app
- Run npm run build
- Restart app with npm run serve
