### ISSUE TITLE
Cannot create project with ESLint + Airbnb config using vue ui

### ISSUE THREAD

**Issue by bvanneerven** [vuejs/vue-cli#1611]
### Version
3.0.0-rc.3

### Reproduction link
[https://gist.github.com/bvanneerven/4998805642a85d9342643f0688877970](https://gist.github.com/bvanneerven/4998805642a85d9342643f0688877970)

### Steps to reproduce
Using the config listed in the gist, creating a project with `vue create` is succesful, while creating a project from `vue ui` with the same config throws 2 errors.

### What is expected?
The outcome of `vue create` should be the same as creating a project with `vue ui`.

### What is actually happening?
`vue ui` throws 2 errors.

---
This does not seem to happen with other ESLint config options. For example, using ESLint   Prettier runs fine.

**Comment by Akryum** [comment]
Fixed in https://github.com/vuejs/vue-cli/commit/4c69052a54a18f21899ea449ddf17a35ad015e38

**Comment by hectorj** [comment]
Ok, `vue invoke unit-jest` seems to fix it for me
