### ISSUE TITLE
vue-cli commands dont exit correctly in rc.3

### ISSUE THREAD

**Issue by leovanhaaren** [vuejs/vue-cli#1622]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/vuejs/vue-cli/releases/tag/v3.0.0-rc.3](https://github.com/vuejs/vue-cli/releases/tag/v3.0.0-rc.3)

### Steps to reproduce
When running either vue-cli-service build, vue-cli-service lint or vue-cli-service test:unit, both from a local terminal or from a CI, the process does not exit correctly so it will hang indefinitely. 

### What is expected?
The process should exit when finished without errors.

### What is actually happening?
The process doesn't finish.

**Comment by thetre97** [comment]
I also get this. This means that builds on netlify etc. fail as it exceeds maximum build time.

**Comment by leovanhaaren** [comment]
@thetre97 can you check the exact cause of this issue on your side with: https://github.com/mafintosh/why-is-node-running

My results are:
`There are 5 handle(s) keeping the process running

# PROMISE
/Users/Me/Documents/Development/Work/secret/node_modules/lodash/lodash.js:6069  - (Promise && getTag(Promise.resolve()) != promiseTag) ||
/Users/Me/Documents/Development/Work/secret/node_modules/lodash/lodash.js:17078 - var _ = runInContext();
/Users/Me/Documents/Development/Work/secret/node_modules/lodash/lodash.js:17105 - }.call(this));

# Timeout
/Users/Me/Documents/Development/Work/secret/vue.config.js:5 - setTimeout(function () {

# PROMISE
/Users/Me/Documents/Development/Work/secret/node_modules/bluebird/js/release/util.js:324   - var promise = new Promise(function(){});
/Users/Me/Documents/Development/Work/secret/node_modules/bluebird/js/release/schedule.js:7 - var NativePromise = util.getNativePromise();

# PROMISE
/Users/Me/Documents/Development/Work/secret/node_modules/@vue/cli-service/bin/vue-cli-service.js:22 - service.run(command, args, rawArgv).catch(err => {

# Timeout
/Users/Me/Documents/Development/Work/secret/node_modules/node-ipc/dao/client.js:193 - setTimeout(`

**Comment by leovanhaaren** [comment]
@thetre97 just add the dump to your `vue.config.js` in the project root

see;
```
const log = require('why-is-node-running');

 setTimeout(function () {
   log() // logs out active handles that are keeping node running
 }, 10000)

const config = {
    // your config here
};

module.exports = config;
```

**Comment by leovanhaaren** [comment]
Only related issue I can find is this one;
https://github.com/petkaantonov/bluebird/issues/626

**Comment by leovanhaaren** [comment]
Think i've found the source of the issue, when upgrading `vue-cli-plugin-apollo` from `v0.13.7` to `v0.13.8` the commands break. Are you using this library @thetre97 ?

**Comment by thetre97** [comment]
Ah - yes, I am... 👍
