### ISSUE TITLE
Missing the css serving one component

### ISSUE THREAD

**Issue by mailok** [vuejs/vue-cli#1624]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/mailok/wired](https://github.com/mailok/wired)

### Steps to reproduce
* Create a project with @ vue/cli
* Add Vuetify plugin
* Create new component called Buttons.vue
* Add 4 vuetify buttons to my component
* I navigate to the component folder
* I execute the command: vue serve Buttons.vue

### What is expected?
I expected to see my component with its css.

### What is actually happening?
My component is shown without css. My component consists of several buttons, something as simple as this:

```
<template>
  <div>
    <v-btn color="success">Success</v-btn>
    <v-btn color="error">Error</v-btn>
    <v-btn color="warning">Warning</v-btn>
    <v-btn color="info">Info</v-btn>
  </div>
</template>
```
but this component "v-btn" belongs to vuetify, and it is not showing as it should be. This same thing happens if I want to convert my component into a WebComponent, loses all the styles that come from vuetify

**Comment by mailok** [comment]
In the first image the component is shown when I run the full application:

![a](https://user-images.githubusercontent.com/3769277/41615444-4cd70064-73c9-11e8-8cf8-e780f28aaaa4.PNG)


This image shows how the component looks when it is served to him alone:

![b](https://user-images.githubusercontent.com/3769277/41615529-7d465b1e-73c9-11e8-860f-c5d34942f8d3.PNG)

**Comment by LinusBorg** [comment]
Vuetify does not include css in its components, they are all extracted in one separate css file. You will find that its imported in your main.js file (or in /plugins/vuetify.js ?)

When you run vue serve on your component directly, this css is not included. Because vue-cli can't know that you want it to be included.

**Comment by mailok** [comment]
@LinusBorg So this only works for isolated components with its own css?, It's a shame, thanks anyway.

**Comment by Akryum** [comment]
vue-cli can't guess all the external CSS file you want it to include. It's not magical. 😸
