### ISSUE TITLE
vue-cli-service suddenly crashed in the middle of a development session

### ISSUE THREAD

**Issue by tmcdos** [vuejs/vue-cli#1625]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/tmcdos/vuecli](https://github.com/tmcdos/vuecli)

### Steps to reproduce
Simply writing code and saving the Vue files before watching the result in the browser.
After a few hours of work `vue-cli-service` just crashed (`node.exe` was using more than 1 Gb RAM at that time). I am not sure how to reproduce it - the issue is complex and hard to trace.

### What is expected?
I expect the stability of Vue-CLI 2.x

### What is actually happening?
Random bugs

![shot-1](https://user-images.githubusercontent.com/19253115/41620184-9e64a696-7411-11e8-8b1a-d6f3de47b057.png)

[2018-06-19T19_25_54_919Z-debug.log](https://github.com/vuejs/vue-cli/files/2116664/2018-06-19T19_25_54_919Z-debug.log)

**Comment by yyx990803** [comment]
That looks like a webpack issue. Unfortunately there's nothing we can do with the information given.
