### ISSUE TITLE
After Build Prozess doesn't end...

### ISSUE THREAD

**Issue by mathe42** [vuejs/vue-cli#1626]
### Version
3.0.0-rc.3

### Reproduction link
[https://bitbucket.org/mathe42/vuecli3-issue/](https://bitbucket.org/mathe42/vuecli3-issue/)

### Steps to reproduce
vue create buildfails   
select no Items   
cd buildfails  
vue add apollo  
yarn build  

Or in Repro: 
yarn  
yarn build  

### What is expected?
Build does fails or is successfull but ENDs after that

### What is actually happening?
Build doesn't end

**Comment by andreydos** [comment]
Maybe you have build problem because of version mismatch (vue apollo beta-10 and vue cli rc-3) in your package.jsom

**Comment by mathe42** [comment]
I fixt it with install apollo-* directly and remove vue-cli-plugin-apollo from dependencies
