### ISSUE TITLE
Use start instead of serve as script name

### ISSUE THREAD

**Issue by alexrohleder** [vuejs/vue-cli#1632]
### Version
3.0.0-rc.3

### Steps to reproduce
My case is that I put my vue-cli app on gitlab and enabled the auto-devtools option.
Gitlab tried to use a heroku-like image, that failed on starting my app due to lack of a standard start command.

### What is expected?
We should rename the command `serve` to `start`. It is a standard command for package.json (https://docs.npmjs.com/cli/start) so it can be recognized by auto-deploy tools like heroku, making auto-deploy of vue-cli apps as simple as a drop in.

### What is actually happening?
Currently we have the command `serve` as the main dev server starter. It is not a standard command for package.json and as so, it is not automatically recognized by auto-deploy tools like Heroku.

**Comment by LinusBorg** [comment]
`vue-cli-service serve` starts a local development server, whereas `start`, regarding npm scripts, is usually/by convention used to start a production server.

I don't think you want to deploy your development server to a production environment like heroku, right?

So I don't think that would be a great idea.

**Comment by alexrohleder** [comment]
hey, I miss explained the issue. And yes, you have a good point.
I was wondering that after the issue creation as well. On the next I'll think more before creating :sweat_smile: .

As I have already solved my problem I'll be closing this issue.
I just defined my `Procfile` for who is interested.

Thanks :smiley:
