### ISSUE TITLE
how to use preset-stage-1

### ISSUE THREAD

**Issue by ccqiuqiu** [vuejs/vue-cli#1633]
### What problem does this feature solve?
how to use preset-stage-1

### What does the proposed API look like?
how to use preset-stage-1

**Comment by kazupon** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. The issue list only accepts bug reports and feature requests. Questions should be posted to the [Vue land](https://vue-land.js.org/),  [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
