### ISSUE TITLE
Explain how the option `--watch` works when `--target lib` is used.

### ISSUE THREAD

**Issue by phcoliveira** [vuejs/vue-cli#1635]
### What problem does this feature solve?
When using the option `--watch` combined with the option `--target lib`, a `demo.html` file is created inside the `dist/` folder. Unfortunately, I never got it to work. There always a missing dependency.

Moreover, that is not what I would expect for the option `--watch` in this use case. It appears that the resulting bundling files are meant to be used in a `hot devserver`, with CSS inline, while I was expecting a simple rebuild of the files, with an external CSS file, just like when we use `build --target lib` without `--watch`.

### What does the proposed API look like?
Not sure.

**Comment by Akryum** [comment]
Hi, GitHub issues are only for bug reports and feature requests. If you need help, please ask on the forums or the discord.

**Comment by nikugogoi** [comment]
Hi @phcoliveira 
Did you get an explanation on the behavior you mentioned?

**Comment by phcoliveira** [comment]
@nikugogoi, nope. I wish you better luck.
