### ISSUE TITLE
Cannot work multiple client addon

### ISSUE THREAD

**Issue by kazupon** [vuejs/vue-cli#1638]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/kazupon/vue-cli-plugin-issue-demo](https://github.com/kazupon/vue-cli-plugin-issue-demo)

### Steps to reproduce
- git clone git@github.com:kazupon/vue-cli-plugin-issue-demo.git
- vue create issue-app
- cd issue-app
- npm i --save ../vue-cli-plugin-issue-demo
- vue invoke issue-demo
- cd ../vue-cli-plugin-issue-demo/addon1
- npm run serve # serve addon1
- cd ../addon2
- npm run serve # serve addon2
- vue ui # Invoke Vue CLI UI

after that, import `issue-app` project

### What is expected?
- Scoped per client addon, and locale messages and Vue Components not conflict.
- Multiple client addon works

### What is actually happening?
- Not scoped per client addon: client addon author can overwrite resources (locale messsages and Vue components)
- All client addon don't work

**Comment by Akryum** [comment]
Not sure why you need two different addons for one plugin? You can register multiple components in your client addon.

**Comment by Akryum** [comment]
I'm afraid it's not currently possible, the plugin has to namespace his ids himself. The repro link works with those:

```js
// main.js for addon 1
import Comp from './components/Comp.vue'
import App from './App.vue'

ClientAddonApi.component('vue-issue-demo1-comp', Comp)

ClientAddonApi.addRoutes('vue-issue-demo1', [
  { path: '', name: 'test-issue-route1', component: App }
])

const locales = require.context('./locales', true, /[a-z0-9]+\.json$/i)
locales.keys().forEach(key => {
  const locale = key.match(/([a-z0-9]+)\./i)[1]
  ClientAddonApi.addLocalization(locale, locales(key))
})
```

```js
// main.js for addon 2
import Comp from './components/Comp.vue'
import App from './App.vue'

ClientAddonApi.component('vue-issue-demo2-comp', Comp)

ClientAddonApi.addRoutes('vue-issue-demo2', [
  { path: '', name: 'test-issue-route2', component: App }
])

const locales = require.context('./locales', true, /[a-z0-9]+\.json$/i)
locales.keys().forEach(key => {
  const locale = key.match(/([a-z0-9]+)\./i)[1]
  ClientAddonApi.addLocalization(locale, locales(key))
})
```

```js
// ui.js
module.exports = api => {
  api.addClientAddon({
    id: 'vue-issue-demo1',
    url: 'http://localhost:8043/index.js'
  })

  api.addClientAddon({
    id: 'vue-issue-demo2',
    url: 'http://localhost:8044/index.js'
  })

  api.addView({
    id: 'vue-issue-demo1-view',
    name: 'test-issue-route1',
    icon: 'pets',
    tooltip: 'issues'
  })

  api.addTask({
    name: 'demo-task1',
    command: "echo task2!",
    views: [{
      id: 'vue-issue-demo1-addon',
      label: 'Dashboard',
      icon: 'dashboard',
      component: 'vue-issue-demo1-comp'
    }],
    defaultView: 'vue-issue-demo1-addon'
  })

  api.addView({
    id: 'vue-issue-demo2-view',
    name: 'test-issue-route2',
    icon: 'info',
    tooltip: 'info'
  })

  api.addTask({
    name: 'demo-task2',
    command: "echo task2!",
    views: [{
      id: 'vue-issue-demo2-addon',
      label: 'Dashboard',
      icon: 'dashboard',
      component: 'vue-issue-demo2-comp'
    }],
    defaultView: 'vue-issue-demo2-addon'
  })
}
```

**Comment by Akryum** [comment]
I updated the docs with warnings about ids and a recommendation to use Reverse Domain Notation: https://cli.vuejs.org/dev-guide/ui-api.html

**Comment by kazupon** [comment]
I got it
