### ISSUE TITLE
Got 'Abort trap: 6' when I wake up MacOS

### ISSUE THREAD

**Issue by ryouaki** [vuejs/vue-cli#1643]
### Version
3.0.0-beta.15

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
npm run serve
sleep macos
wake up macos
get message "Abort trap: 6" and nodejs stoped

### What is expected?
nodejs does not stop

### What is actually happening?
nodejs stoped

---
macos 10.13.5

**Comment by yyx990803** [comment]
This is most likely a webpack-dev-server issue.
