### ISSUE TITLE
创建APP后引入iview ui组件（col） 报错

### ISSUE THREAD

**Issue by 531431988** [vuejs/vue-cli#1645]
### Version
3.0.0-rc.3

### Reproduction link
[https://codepen.io 暂无](https://codepen.io 暂无)

### Steps to reproduce
1、vue ui 创建项目
2、npm i iview
3、新建demo.vue  输 Col组件 
4、运行，ie 报错

### What is expected?
可能是babel.config.js配置问题，希望有相关配置例子

### What is actually happening?
希望有相关配置例子

**Comment by yyx990803** [comment]
请提供实际的重现。
