### ISSUE TITLE
vue-cli 2.3.1

### ISSUE THREAD

**Issue by GJean** [vuejs/vue-cli#165]
Hi,

I update vue-cli 2.2.0 to 2.3.1 and now on my all project I have this error when I launch npm run dev 

`ERROR in ./src/App.vue
Module not found: SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: /home/gjean/package.json (directory description file): SyntaxError: Unexpected end of JSON input
 @ ./src/App.vue 10:23-136
 @ ./src/main.js
 @ multi main
`
I use template webpack-simple-2.0 and my OS is Manjaro Linux

**Comment by zigomir** [comment]
@GJean this issue isn't `vue-cli` related. But it might be connected to this problem: https://github.com/vuejs-templates/webpack-simple-2.0/pull/18

**Comment by GJean** [comment]
No I try fix with add resolver in webpack.package.json but does'nt fix my problem.

**Comment by GJean** [comment]
If I copy/paste project package.json in /home/gjean it's work.

**Comment by GJean** [comment]
I uninstall all nodejs and vue cli. After install again nodejs, npm and vue cli and now it's work. thanks for your help.
