### ISSUE TITLE
HMR doesn't work when deleted node_modules and reinstall

### ISSUE THREAD

**Issue by Weiyu-Chen** [vuejs/vue-cli#1652]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/Weiyu-Chen/vue-cli-test.git](https://github.com/Weiyu-Chen/vue-cli-test.git)

### Steps to reproduce
1.  Create a simple project by  `vue create`,  delete the `node_modules`,  reinstall ,  HMR doesn't work any more.

2. Also,  HMR will not work when i clone an existed project which was created by `vue-cli`

### What is expected?
HMR should work at any time

### What is actually happening?
HMR is pending all the time , unless some error happen.

---
environment : 
- Mac  OS 10.12.3
- node v8.11.2  

```
// package.json
{
  "name": "test2",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "vue": "^2.5.16"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-beta.15",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.15",
    "@vue/cli-service": "^3.0.0-beta.15",
    "vue-template-compiler": "^2.5.16"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```

**Comment by yyx990803** [comment]
Closing stale issue that cannot be reproduced.

**Comment by zouhangwithsweet** [comment]
you can  do `npm config set registry https://registry.npmjs.org/`
