### ISSUE TITLE
CSS Pre-processors should have a better warning about PostCSS, Autoprefixer and CSS Modules already being supported.

### ISSUE THREAD

**Issue by VictorioBerra** [vuejs/vue-cli#1655]
### Version
3.0.0-rc.3

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
`vue create hello-world`
"Manually select features"
Select "CSS Pre-processors"

### What is expected?
As someone new to the CLI, I did not know PostCSS, Autoprefixer and CSS Modules are supported by default.

After learning this, I would like an option called "None". Instead, I have to ctrl-c and then redo the wizard.

### What is actually happening?
I am forced to choose from SCSS/SASS, LESS, or Stylus.

**Comment by LinusBorg** [comment]
It's prominently documented here: 

https://cli.vuejs.org/guide/css.html#pre-processors

What else would you expect to make this more approachable to beginners?

**Comment by VictorioBerra** [comment]
I was just detailing my personal experience following the getting started
guide as a complete beginner. And I already detailed what I think should be
done in this situation regarding a 'None' button. Most people will follow a
getting started guide before they do a deeper dive into the CSS and related
sections. If you guys think it's fine and want to throw the docs at us like
this then close the issue.

**Comment by Akryum** [comment]
Maybe we can rename "CSS Pre-processors" to "Additional CSS Pre-processors"?

**Comment by Akryum** [comment]
> I much prefer PostCSS + plugins to SASS/SCSS/LESS and I think that's the way most people are going now days.

It's included no matter what you chose in the CLI.

> Does the GUI and the CLI use the same wording or are they separate string files?

Those are the same.

**Comment by sodatea** [comment]
Fixed in https://github.com/vuejs/vue-cli/commit/9f9ddb133d47b3612cbf0550e4a37afc4183f78b
