### ISSUE TITLE
vuetify plugin broken

### ISSUE THREAD

**Issue by kakulukia** [vuejs/vue-cli#1657]
### Version
3.0.0-rc.3

### Reproduction link
[http://i.dont.know/how/this/could/be/shown/in/any/of/those/tools](http://i.dont.know/how/this/could/be/shown/in/any/of/those/tools)

### Steps to reproduce
Install a new project and add the vuetify plugin

### What is expected?
i get a working default project

### What is actually happening?
Home.vue gets destroyed with template code inserted between the script and styles blocks

    l>
                <em>&mdash;John Johnson</em>
                </small>
            </footer>
            </blockquote>
        </v-layout>
        </v-slide-y-transition>
    </v-container>
    </template>

**Comment by LinusBorg** [comment]
Then please open an issue in the plugin's repository...
