### ISSUE TITLE
用src引入ts文件报错

### ISSUE THREAD

**Issue by slipkinem** [vuejs/vue-cli#1658]
### Version
3.0.0-rc.3

### Reproduction link
[http://www.idontunderstand.com](http://www.idontunderstand.com)

### Steps to reproduce
将ts文件用```<script src='./index.ts' lang="ts"></script>```引入，报错： File 'xxx.vue' is not a module，改回去就好了。

### What is expected?
预期和写在script便签里面的一样运行。

### What is actually happening?
如果这样不能引入ts文件的话，那么我应该怎么去定义ref的类型

---
thx

**Comment by Alsmile** [comment]
+1

```<template>
  <div class="home">
    <img src="../../assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js + TypeScript App"/>
  </div>
</template>

<script lang="ts" src="./home.ts">
</script>
```

**Comment by ktsn** [comment]
Duplicate of #1104
