### ISSUE TITLE
[UI] [Node 10] File explorer unable to list folders and files

### ISSUE THREAD

**Issue by yuriy636** [vuejs/vue-cli#1659]
### Version
3.0.0-rc.3

### Reproduction link
[https://i.imgur.com/quspF8h.png](https://i.imgur.com/quspF8h.png)

### Steps to reproduce
OS: Windows 10 (1803)

Node version: v10.5.0

Vue CLI version: 3.0.0-rc.3

1. Run `vue ui`
1. Try navigating  through folders in the "Create" or "Import" sections
1. Open the console

### What is expected?
The file explorer correctly shows folders and files and no errors are logged into the console.

### What is actually happening?
When navigating through folders in the "Create" or "Import" sections, no files or folders are shown and multiple "**An error occured**" red messages, "**GraphQL error: File not found**" and "**TypeError: Cannot read property 'isVueProject' of undefined**" are logged into the console.

![Console errors screenshot](https://i.imgur.com/quspF8h.png)

---
Creating a new project works, the folder is created along with node_modules and other folders and it appears correctly at "Projects" section, but when navigating to its folder at "Create" or "Import" sections, none of its files or folders are shown. 

Also, everything works fine when on Node v8.11.3

**Comment by Akryum** [comment]
Could you try changing your Windows language settings to English?

**Comment by yuriy636** [comment]
Yeah, that fixed the issue!

**Comment by Akryum** [comment]
Okay, so that was fixed in https://github.com/vuejs/vue-cli/commit/4b44509e810415716695b7957ec990a50ba84e4f
