### ISSUE TITLE
When init a new project does not install the latest version of Vue

### ISSUE THREAD

**Issue by DannyFeliz** [vuejs/vue-cli#166]
When you run `vue-init webpack [project-name]` the CLI installs the version `1.0.21` of `Vue` instead of the latest version which is `1.0.26`

- OS: Windows 7 64-bit
- Node: v4.4.3
- NPM: 3.10.6

**Comment by posva** [comment]
The cli doesn't install Vue. That's npm. The package version is set to "^1.0.21" which will install the latest stable release of Vue, therefore v1.0.26. Don't worry you should have the last version. 
BTW this is something related to a [template](https://github.com/vuejs-templates/webpack) not to the cli 😄
