### ISSUE TITLE
"@vue/cli-service-global@3.0.0-rc.3" has no binaries

### ISSUE THREAD

**Issue by AaronNGray** [vuejs/vue-cli#1661]
### Version
3.0.0-rc.3

### Reproduction link
[http://invalid.org](http://invalid.org)

### Steps to reproduce
> npm install -g vue@2.5.16

> yarn global add @vue/cli-service-global

> vue serve

### What is expected?
vue to serve on loclhost:****

### What is actually happening?
C:\Users\Aaron\Tests\VueJS\infinite-scroll-vuejs>vue serve

  Command vue serve requires a global addon to be installed.
  Please run yarn global add @vue/cli-service-global and try again.

---
it appears Windows is stuck behind as usual.

**Comment by Akryum** [comment]
You are installing the Vue core library used in web pages instead of the cli.
Please uninstall it with `npm uninstall -g vue` and follow the instructions to install the cli:
https://cli.vuejs.org/guide/creating-a-project.html#installation

**Comment by ugurozturk** [comment]
If anybody come up here, use `yarn global add @vue/cli` ref :  https://cli.vuejs.org/guide/installation.html
