### ISSUE TITLE
There is no official vue-cli update / upgrade guide on cli.vuejs.org/guide

### ISSUE THREAD

**Issue by chengyiuchun** [vuejs/vue-cli#1662]
### What problem does this feature solve?
There should be a section in the guide to describe how to upgrade a project generated using older version of vue-cli to the latest version. This search term on Google yeilds no result '(update|upgrade) site:cli.vuejs.org'

### What does the proposed API look like?
A simple section to describe how to upgrade.

**Comment by yyx990803** [comment]
Unfortunately the old CLI allows you to make arbitrary changes to the config, which makes it near impossible to provide a universally applicable guide on upgrading. If you didn't make any modifications at all, simply copy your src directory over and it should work. Otherwise, read the docs of the new CLI to understand how to apply modifications to the config.

**Comment by chengyiuchun** [comment]
Actually this is about the new Vue CLI.  For example, there a few dependencies of a project generated by vue cli like `babel-core`, `@vue/cli-service`, `@vue/cli-plugin-babel`. I am looking for the official recommendation on how these should be updated. Should I generate a brand new project with the latest CLI and diff the package.json? Or there is a better way? Thanks.

**Comment by yyx990803** [comment]
Once generated, just bump everything to the latest version with `npm update`.

**Comment by motin** [comment]
> Once generated, just bump everything to the latest version with npm update.

I couldn't find this information in the guide on cli.vuejs.org/guide. Care to re-open this issue until the upgrade instructions are available there?

**Comment by motin** [comment]
This issue may be dependent on https://github.com/vuejs/vue-cli/issues/1507

**Comment by luzik** [comment]
hmm ...there is new [@vue/eslint-config-prettier](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/eslint-config-prettier/package.json) (4.0.1) but:

```
$ grep eslint-config-prettier package.json
    "@vue/eslint-config-prettier": "^4.0.0",
$ npm update
$ grep eslint-config-prettier package.json
    "@vue/eslint-config-prettier": "^4.0.0",
```

**Comment by viniciuskneves** [comment]
> hmm ...there is new [@vue/eslint-config-prettier](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/eslint-config-prettier/package.json) (4.0.1) but:
> 
> ```
> $ grep eslint-config-prettier package.json
>     "@vue/eslint-config-prettier": "^4.0.0",
> $ npm update
> $ grep eslint-config-prettier package.json
>     "@vue/eslint-config-prettier": "^4.0.0",
> ```
> How to get fresh version ?

`vue upgrade`. It will handle minor updates by default. If you want major/patch just specify it `vue upgrade major`.
