### ISSUE TITLE
Support exact baseUrl even without http: prefix

### ISSUE THREAD

**Issue by kenny26** [vuejs/vue-cli#1664]
### What problem does this feature solve?
Currently my setup serve .html file built on dist/ using Go server.

BaseUrl value is provided from Go server, and can be inserted to html with tag like so {{.baseUrl}}.

Doing so, we can change baseUrl without recompiling the asset.

My vue.config.js currently looks like this
```
module.exports = {
  baseUrl: '{{.baseUrl}}',
}
```
Unfortunately the script tag on built .html file has / appended to baseUrl, like this
```
  <script type="text/javascript" src="/{{.baseUrl}}/front.js"></script></body>
```

I understand if baseUrl is prefixed with http:, it won't be appended with slash, however, it's not working for my use case.

### What does the proposed API look like?
I expect we can put exact baseUrl even when it's not prefixed by http:

Perhaps, baseUrl can have object as value, with additional key, like so:
```
module.exports = {
  baseUrl: {
   url: '{{.baseUrl}}',
   raw: true,
  },
}
```

**Comment by yyx990803** [comment]
The baseUrl is used not only in the HTML
 It is used in js, CSS and the dev server as well, so no your use case probably can't be supported.
