### ISSUE TITLE
Typescript doesn't recognise plugins

### ISSUE THREAD

**Issue by eladcandroid** [vuejs/vue-cli#1666]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/eladcandroid/vue-cli-errors](https://github.com/eladcandroid/vue-cli-errors)

### Steps to reproduce
Create a new project with typescript and linter support
Install axios plugin with "vue ui"
Try to use this.$axios in HelloWorld.vue

### What is expected?
No errors

### What is actually happening?
Got a lint error - Property '$axios' does not exist on type 'HelloWorld' 
(Less important but also got warning errors about semi-colons)

**Comment by yyx990803** [comment]
That's an issue in the axios plugin, which isn't maintained by us. It needs to account for type shims when used with typescript.

**Comment by benjick** [comment]
@Robula do you know how to do it for `Store`?

`Property '$axios' does not exist on type 'Store<any>'`
