### ISSUE TITLE
Webpack Warning about not finding interface export from TypeScript

### ISSUE THREAD

**Issue by Leandros** [vuejs/vue-cli#1667]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/Leandros/vue-ts-warn-repro](https://github.com/Leandros/vue-ts-warn-repro)

### Steps to reproduce
1. Create a new Vue.js typescript project (using vue-cli)
2. Create a new typescript file, export an object, and the interface of the object
3. Import the interface to be used in Vue.js components (for example as a prop)

The repro steps from a fresh typescript project can be seen in this commit: https://github.com/Leandros/vue-ts-warn-repro/commit/98c4a60364fade00b2b5ff84dee42c00fb9e50a4

### What is expected?
No warnings are issued.

### What is actually happening?
Vue.js is warning me about a missing export. I'm assuming this is webpack complaining, since the import is only used by typescript for typechecking and has no other uses.

**Comment by yyx990803** [comment]
Looks like this only happens when the interface is used to type a property with the `@Prop` decorator. Something about the `@Prop` decorator is making the interface un-droppable in the TS output. I'd recommend opening an issue at `vue-property-decorators` instead.
