### ISSUE TITLE
如何在webpack中使用DefinePlugin注入全局变量

### ISSUE THREAD

**Issue by 547377507** [vuejs/vue-cli#1671]
### Version
3.0.0-rc.3

### Reproduction link
[https://jsfiddle.net/547377507/3a8vdjo6/](https://jsfiddle.net/547377507/3a8vdjo6/)

### Steps to reproduce
在配置文件中，这样写在js中始终访问不到config变量，谢谢所有的回答~
config
      .plugin('define')
      .init((Plugin, args) => {
        args.push({ config: JSON.stringify({ name: '789' }) });
        console.log(`init输出为：${JSON.stringify(args)}`);
        return new Plugin(...args);
      })
      .tap((args) => {
        args.push({ config: JSON.stringify({ name: '456' }) });
        console.log(`tap输出为：${JSON.stringify(args)}`);
        return args;
      });

### What is expected?
输出config变量的值

### What is actually happening?
输出undefined

**Comment by zhouxinyong** [comment]
```
config
  .plugin('define')
  .tap(args => {
     args[0]['config'] = JSON.stringify({ name: '789' }) 
     return args
})
```

**Comment by 547377507** [comment]
@zhouxinyong 谢谢你的回答~

**Comment by yyx990803** [comment]
不要用 issue 问问题。

**Comment by cksa** [comment]
> vue-cli 3.1.3
```js
chainWebpack: config => {
    config.plugin('define').tap(definitions => {
        Object.assign(definitions[0]['process.env'], {
            name: '"vuejs"',
        });
        return definitions;
    });
}
```

**Comment by 13714273163** [comment]
package.json:
    "dev:xiaomin": "cross-env ZONE=2021-03-01-xiaomin vue-cli-service serve --mode development",
    
vue.config.js:
 configureWebpack: {
        plugins: [
            new webpack.DefinePlugin({
                "process.env":{
                    ZONE:JSON.stringify(process.env.ZONE)
                }
            })
        ]
    }

**Comment by 13714273163** [comment]
```javascript

package.json:
"dev:xiaomin": "cross-env ZONE=2021-03-01-xiaomin vue-cli-service serve --mode development",

vue.config.js:
configureWebpack: {
   plugins: [
        new webpack.DefinePlugin({
            "process.env":{
                 ZONE:JSON.stringify(process.env.ZONE)
             }
      })
   ]
}
```
