### ISSUE TITLE
Generate readme.md

### ISSUE THREAD

**Issue by checktravis** [vuejs/vue-cli#1675]
### What problem does this feature solve?
Currently, every new project is generated with no readme.md file. Generating a readme.md with basic deployment information would help rapid prototyping. The end user will have a starting point to expand upon. Example:

```
# my-vue-project

## Build Setup

### dependencies:
npm install # Or yarn install

### spin up server with hot reload (npm run / yarn)
npm run serve

### build for production
npm run build

### review configuration
npm run inspect

## Made with [vue-cli](https://cli.vuejs.org/).

```

### What does the proposed API look like?
```
# client would either generate a generic readme.me or enhanced with provided details (project-name, selected plugins, etc)
vue create my-vue-project
```

**Comment by kazupon** [comment]
I think that's good too.

**Comment by arthurdenner** [comment]
If that's okay, I'd like to work on this.

**Comment by checktravis** [comment]
Just saw the new readme today. Looks great, thanks for implementing.
