### ISSUE TITLE
什么时候更新zh-cn文档

### ISSUE THREAD

**Issue by mirrorpal** [vuejs/vue-cli#1678]
### What problem does this feature solve?
需要中文文档，API，配置太多了，看英文还是有点吃力

### What does the proposed API look like?
中文文档

**Comment by zhaozhe0831** [comment]
目前是否有中文化的计划，开发者如何能参与其中？

**Comment by ipid** [comment]
已 Subscribe，英语不好的我能否参与中文化计划？

**Comment by chinanf-boy** [comment]
翻译文档，只有小数理解是技术活
   只要能把英语，译成亲民的中文，即便差字少句，也勿伤大雅，所以，当然每个中国人都能出一份力

**Comment by yyx990803** [comment]
等正式发布就会翻译。
