### ISSUE TITLE
multi-page template fallback differs from doc

### ISSUE THREAD

**Issue by MarvinXu** [vuejs/vue-cli#1679]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/MarvinXu/vue-cli-mpa-test](https://github.com/MarvinXu/vue-cli-mpa-test)

### Steps to reproduce
vue inspect > out.js

see this fragment:
```javascript
// out.js

/* config.plugin('html-subpage') */
    new HtmlWebpackPlugin(
      {
        templateParameters: function () { /* omitted long function */ },
        chunks: [
          'chunk-vendors',
          'chunk-common',
          'subpage'
        ],
        template: 'E:\\workspace2018\\vue-cli-mpa-test\\node_modules\\@vue\\cli-service\\lib\\config\\index-default.html',
        filename: 'subpage.html'
      }
    )
```

### What is expected?
https://cli.vuejs.org/config/#pages

"when using the entry-only string format, template is inferred to be `public/subpage.html` and falls back to `public/index.html` if not found."

### What is actually happening?
subpage's template did not fall back to 'public/index.html' but some other default template in node_modules.

**Comment by MarvinXu** [comment]
I'll try make a PR for this.

**Comment by MarvinXu** [comment]
@Akryum I see you added `docs` label. Are you going to modify the doc or should I make a PR to fix this?

**Comment by Akryum** [comment]
You can. :wink:
