### ISSUE TITLE
overrides in .eslintrc doesn't work

### ISSUE THREAD

**Issue by dcastil** [vuejs/vue-cli#1682]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/dcastil/vue-bug/blob/master/src/bug.spec.js](https://github.com/dcastil/vue-bug/blob/master/src/bug.spec.js)

### Steps to reproduce
Download my vue-bug repo (bootstrapped with `$ vue create vue-bug`), open the repo in VS Code, install ESLint extension for VS Code, navigate to bug.spec.js.

### What is expected?
No linting errors showing up.

### What is actually happening?
`describe()`, `it()` and `expect()` throws a linting error for rule no-undef, although jest env is specified in overrides of .eslintrc.js.

**Comment by LinusBorg** [comment]
So this does only happen in vscode, not when running `npm run lint`?

**Comment by dcastil** [comment]
The command outputs the same error.

```bash
➜  vue-bug git:(master) yarn lint
yarn run v1.7.0
$ vue-cli-service lint
error: 'describe' is not defined (no-undef) at src/bug.spec.js:4:1:
  2 | import HelloWorld from '@/components/HelloWorld.vue';
  3 |
> 4 | describe('HelloWorld.vue', () => {
    | ^
  5 |   it('renders props.msg when passed', () => {
  6 |     const msg = 'new message';
  7 |     const wrapper = shallowMount(HelloWorld, {


error: 'it' is not defined (no-undef) at src/bug.spec.js:5:3:
  3 |
  4 | describe('HelloWorld.vue', () => {
> 5 |   it('renders props.msg when passed', () => {
    |   ^
  6 |     const msg = 'new message';
  7 |     const wrapper = shallowMount(HelloWorld, {
  8 |       propsData: { msg },


error: 'expect' is not defined (no-undef) at src/bug.spec.js:10:5:
   8 |       propsData: { msg },
   9 |     });
> 10 |     expect(wrapper.text()).toMatch(msg);
     |     ^
  11 |   });
  12 | });
  13 |


3 errors found.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by LinusBorg** [comment]
Since your overrides don't work with the vs code plugin for eslint - which doesn'r know about or interact with vue-cli I dont see how this could be related to vue-cli.

Are you actually sure that your glob for the files works?

**Comment by dcastil** [comment]
I'm quite sure that it works. [Here](https://github.com/dcastil/concrete/blob/master/.eslintrc), in a small React app, it also works.

**Comment by dcastil** [comment]
But you're right, I didn't think about the fact that the ESLint plugin doesn't know anything about the vue-cli.

**Comment by dcastil** [comment]
I just found out that replacing the regex pattern
```js
'**/*.spec.(js|jsx|ts|tsx)'
```
with
```js
'**/*.spec.js'
```
makes ESLint work again. The parentheses aren't actual glob pattern syntax, but Jest supports that in its config, where I copied it from.

**Comment by knod** [comment]
I've actually found that the pipe breaks it too, not just the parens.

In package.json `"**/*.spec.js|**/*.test.js"` won't work while `"**/*.spec.js", "**/*.test.js"` does. Not that we need the `"**/*.test.js"` for the unit tests, it just proves the point. The relevant section from the working config in package.json:
```
"eslintConfig": {
  "env": {
    "node": true
  },
  "overrides": [
    {
      "files": [
        "**/*.spec.js",
        "**/*.test.js"
      ],
      "env": {
        "jest": true
      }
    }
  ]
}
```
