### ISSUE TITLE
Modern Mode Build failed with multiple-pages setup

### ISSUE THREAD

**Issue by WarWithinMe** [vuejs/vue-cli#1683]
### Version
3.0.0-rc.3

### Reproduction link
[https://codesandbox.io/s/k3ox9l4q05?module=%2Fvue.config.js&view=editor](https://codesandbox.io/s/k3ox9l4q05?module=%2Fvue.config.js&view=editor)

### Steps to reproduce
1. In `vue.config.js`, add a page config with directory in its "filename":
```
pages: {
    "privacy/index": {
      entry: "src/privacy.js",
      template: "privacy.html",
      filename: "privacy/index.html"
    }
}
```

2. Run `vue-cli-service build --modern`

### What is expected?
vue-cli will generate the page under "dist/privacy/index.html" (dist is default outputDir)

### What is actually happening?
vue-cli throws error and halts: (It seems like the issue exists only in Windows)
```
(node:15008) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '......\dist\legacy-assets-privacy\index.html.json'
```

---
If the filename attribute doesn't contain directory, vue-cli will build successfully.

**Comment by Akryum** [comment]
Please provide an actual reproduction, codesandbox doesn't support vue-cli 3.

**Comment by nparley** [comment]
I am getting the same error on a OSX build. Seems to work fine on an app that was init via RC2, but fails with RC3.

**Comment by rocwang** [comment]
I think it is the same as https://github.com/vuejs/vue-cli/issues/1791 which is fixed by https://github.com/vuejs/vue-cli/pull/1792

**Comment by nparley** [comment]
OK upgrading to RC4 the legacy bundles now build, but not the modern bundles. They fail with:

```
(node:96496) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/.../dist/legacy-assets-index.html.json'
```

**Comment by nparley** [comment]
My problem was with sub directories see https://github.com/vuejs/vue-cli/pull/1866

**Comment by yyx990803** [comment]
Can no longer reproduce with RC5 (working as expected).
