### ISSUE TITLE
@vue/cli-plugin-eslint does not lint templates in sepparate file

### ISSUE THREAD

**Issue by valyakin** [vuejs/vue-cli#1687]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/valyakin/vuecli-test](https://github.com/valyakin/vuecli-test)

### Steps to reproduce
`npm install`
`npm run lint`

### What is expected?
Errors found both in

`src\components\LintedComponent.vue`

and 

`src\components\NotLintedComponent\NotLintedComponent.html`

### What is actually happening?
Error found only in `src\components\LintedComponent.vue`

---
Greetings 

I use this approach to split my `.vue` file:

```
MyComponent /
 - MyComponent.css
 - MyComponent.html
 - MyComponent.js
 - MyComponent.vue
```

`MyComponent.vue` content:
```
<template src="./MyComponent.html"></template>
<script src="./MyComponent.js"></script>
<style scoped src="./MyComponent.css"></style>
```

But this way template files are not linted

Even if I specify `.html` extension for linter in `package.json` like this:

`vue-cli-service --ext .html lint`

**Comment by LinusBorg** [comment]
Please see https://github.com/vuejs/eslint-plugin-vue/issues/490
