### ISSUE TITLE
Vue rollup template

### ISSUE THREAD

**Issue by dangvanthanh** [vuejs/vue-cli#169]
Hi, 

I'm a new member use vue.js. I love vue.js because simple, easy to learn and especial build reusable components. Vue templates help me build quick prototyping and now I build new template using [rollup](https://github.com/rollup/rollup).

The repository I development is: https://github.com/dangvanthanh/vue-rollup-boilerplate

I hope every one using vue.js have more options about vue templates and suggestion from you.

**Comment by zigomir** [comment]
Hi @dangvanthanh !

Thanks, this looks cool, I like Rollup too! We usually advise template authors to open PR on https://github.com/vuejs/awesome-vue repository under `Boilerplates` section ;)

**Comment by dangvanthanh** [comment]
Thank you very much @zigomir
