### ISSUE TITLE
WebpackDashboard & WebpackAnalyzer components for custom commands

### ISSUE THREAD

**Issue by chymz** [vuejs/vue-cli#1690]
### What problem does this feature solve?
**Subject: Vue UI / Plugin API**

I'm currently making a Vue CLI plugin to add SSR easly on projects (https://github.com/vueneue/ssr) and I want to use these two components on my custom commands (`ssr:serve` and `ssr:build`) but I have found that `mode` only accept `serve` or `build`:

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-ui-addon-webpack/src/mixins/Dashboard.js#L46

ATM I've a found a workaround (https://github.com/vueneue/ssr/blob/master/ui-addon/src/components/WebpackDashboard.vue), but it's very dirty...

Maybe I've totally wrong and there is a simple way to use these beautifuls components ?

PS @Akryum : this is my very low priority feature request ;)

### What does the proposed API look like?
Maybe publish these components in another package to have the possibility to import and use them anywhere and send configuration via props ?

**Comment by Akryum** [comment]
You can import their sources from the `@vue/cli-ui-addon-webpack` package which is already on npm (or else it wouldn't currently work 😸).

**Comment by chymz** [comment]
Sorry I don't get it :(

This package has only `dist/index.js` and exports nothing, no ?

**Comment by Akryum** [comment]
Oh yes you are right, so maybe you can fork it and use the git URL as version range?

**Comment by chymz** [comment]
Ok, I tought It was simpler to expose this components than a fork.

I'll do that ! 
Thanks !

**Comment by Akryum** [comment]
The `src` folder will be published in the next release.
