### ISSUE TITLE
No tests found when running npm run test:unit

### ISSUE THREAD

**Issue by hajarrashidi** [vuejs/vue-cli#1691]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/hajarrashidi/Vue-test-utils-example](https://github.com/hajarrashidi/Vue-test-utils-example)

### Steps to reproduce
Windows 10 cmd: 
vue create app
cd app
npm run test:unit

### What is expected?
To run jest unit tests

### What is actually happening?
When i create a project with vue create and run test i get errors. Not what i expect from a new project.

---
Maybe has something to do with testMatch being wrong in windows

  testMatch: C:\Users\hajar.rashidi\repos\Vue-test-utils-example\app\(tests\unit\**\*.spec.(js|jsx|ts|tsx)|**\__tests__\*.(js|jsx|ts|tsx)) - 0 matches

Image
https://imgur.com/lW9IMZO

**Comment by sickp** [comment]
This may be a Jest bug: https://github.com/facebook/jest/issues/6546

**Comment by lmiller1990** [comment]
This is a dup of #1686 , see if that workaround helps you
