### ISSUE TITLE
HMR / Auto compiling Not working with no reason

### ISSUE THREAD

**Issue by VetBoard** [vuejs/vue-cli#1692]
### Version
3.0.0-rc.3

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
I can not reproduce it intentionally.

BUT

It happens when I'm working on a component and it suddenly stops hot-reloading or compiling (while npm run serve or vue ui task is running), but only for that component, the rest of the app still triggering the hot-realod/compiling.

### What is expected?
Hot-reloading/Compiling for every update to any component. 

### What is actually happening?
It doesn't hot-reload nor even compile the changes for a given component after doing a lot of changes on that component. I have to stops the serve service, restart it and refresh the page on my browser to get the changes reflected.

BUT, if I do make a copy of the same exactly component with another name, it works perfect and I can keep working until some point where it happens again. Looks like something with the cache could be worng.

**Comment by Akryum** [comment]
Do you have an auto-saving feature enabled? What IDE do you use?

**Comment by VetBoard** [comment]
Yes @Akryum I'm using WebStorm with auto-saving on

**Comment by Akryum** [comment]
https://webpack.js.org/configuration/watch/#saving-in-webstorm
