### ISSUE TITLE
Vue Project Manager file explorer ui is fantastic! Can it be used elsewhere?

### ISSUE THREAD

**Issue by kemalcany** [vuejs/vue-cli#1696]
### What problem does this feature solve?
The ui for the project manager's file explorer is amazing. The best file explorer interface I've seen. 

Would be amazing for the OSS and Vue community to be able to use it as a standalone gui repository.

Is this possible? If so are there any plans about exporting it? (Or any other gui components)

Would you need help for it?

### What does the proposed API look like?
Independent components such as VueCli_FileExplorer that can be imported to any vue project

**Comment by Akryum** [comment]
That's not in the near-future plan. However, it's open source and you can fork! 😸
