### ISSUE TITLE
How can i use different `vue.config.js` in different script?

### ISSUE THREAD

**Issue by JunreyCen** [vuejs/vue-cli#1697]
### What problem does this feature solve?
For example, i am going to output a library and demo, the `outputDir` of them is different.

### What does the proposed API look like?
```shell
vue-cli-service build [options]
--config the/path/of/vue.config.js
```

**Comment by wanecek** [comment]
Can you use environment variables for the specific settings, instead of separate files? E.g. like for [`baseUrl`](https://cli.vuejs.org/config/#baseurl)? Otherwise, you could do something like:

```js
const demoConfig = require('./vue.config.demo.js');
const libraryConfig = require('./vue.config.demo.js');

if (process.env.DEMO) {
  module.exports = demoConfig;
} else {
  module.exports = libraryConfig;
}
```

**Comment by JunreyCen** [comment]
That's a solution.Btw, how can i cover the `entry: { app }` setting when `--target app` since i want to custom the output.filename, and i don't want to use  `./src/main.ts` file either.
