### ISSUE TITLE
How can i cover the entry.app settings in `--target app`?

### ISSUE THREAD

**Issue by JunreyCen** [vuejs/vue-cli#1699]
### What problem does this feature solve?
1.I don't want to use `./src/main.ts`;
2.I don't need the `app` output;
Whether to empty `configureWebpack.entry.app` or to remove `./src/main.ts` will throw out error.

### What does the proposed API look like?
none.

**Comment by Akryum** [comment]
Hi, GitHub issues are only for bug reports and feature requests. If you need help, please ask on the forums or the discord.
