### ISSUE TITLE
vue create not working: Error: Failed to resolve plugin @vue/cli-plugin-babel

### ISSUE THREAD

**Issue by njbrunner** [vuejs/vue-cli#1701]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
`npm install -g @vue/cli`

`vue create <project-name>`

### What is expected?
Should create project and install dependencies

### What is actually happening?
Creates `package.json` and `package-lock.json` files but fails with error:
```
�  Invoking generators...
ERROR  Error: Failed to resolve plugin: @vue/cli-plugin-babel
Error: Failed to resolve plugin: @vue/cli-plugin-babel
    at Creator.resolvePlugins (C:\Users\brunnnj1\AppData\Roaming\npm\node_modules\@vue\cli\lib\Creator.js:302:15)
    at Creator.create (C:\Users\brunnnj1\AppData\Roaming\npm\node_modules\@vue\cli\lib\Creator.js:145:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

---
Operating system is Windows 7

**Comment by Akryum** [comment]
What are the value you used when creating the project?

**Comment by njbrunner** [comment]
What do you mean value? Do you mean the project name value?

**Comment by Akryum** [comment]
Well the cli should have asked you questions like if you wanted to use typescript or css-preprocessors.

**Comment by Akryum** [comment]
> That was the only option that it presented me.

Well you also had "Manually select features...". But it doesn't matter for the issue.

**Comment by Akryum** [comment]
@yyx990803 I don't have a Windows 7 os with me to try to reproduce.

**Comment by Akryum** [comment]
@njbrunner What is your node.js version?

**Comment by njbrunner** [comment]
@Akryum Node v8.11.3

**Comment by yyx990803** [comment]
Can't reproduce this on Windows 10 with Node v8.11.3... I don't have a Windows 7 machine to test with. Are you still running into the same issue with rc.5?

**Comment by njbrunner** [comment]
Just attempted on rc.5 and the problem seems to be fixed.

**Comment by m3alamin** [comment]
Rollback to older version works. I had this problem too. I installed vue 3.0.3, just published an hour ago but @vue/cli-plugin-babel is not updated yet (current version is 3.0.2), So I had to install vue version 3.0.2 and boom, it works.

Publishers should update dependency first then the cli tool.

**Comment by piotar** [comment]
@m3alamin for this case, clearing npm cache should help.
`npm cache clean --force`[[doc](https://docs.npmjs.com/troubleshooting/try-clearing-the-npm-cache)]

**Comment by m3alamin** [comment]
@piotar Thanks for the tip but the npm package was not updated, so clearing cache won't work. I checked npmjs.com and check all versions there for cli-plugin-babel.

Look at npmjs.com, Vue Cli was updated 2 hours ago but the cli-plugin-babel package was updated only 40 minutes ago.

**Comment by daundkarmangesh1109** [comment]
My Vue cli version is 3.1.0. Also, @vue/cli-plugin-babel is having same version. I am trying to make vue js as web component. But getting this error - Cannot find module '@vue/cli-plugin-babel'.
