### ISSUE TITLE
Watch vue.config.js change, auto rerun

### ISSUE THREAD

**Issue by auven** [vuejs/vue-cli#1704]
### What problem does this feature solve?
vue.config.js
``` js
module.exports = {
    pages: {
        index: {
            // entry for the page
            entry: 'src/index/main.js',
            // the source template
            template: 'public/index.html',
            // output as dist/index.html
            filename: 'index.html'
        },
        // when using the entry-only string format,
        // template is inferred to be `public/subpage.html`
        // and falls back to `public/index.html` if not found.
        // Output filename is inferred to be `subpage.html`.
        subpage: 'src/subpage/main.js',
        abc: 'src/abc/main.js'
    }
}
```

When i want to add new page, i had to rerun 'npm run serve'.

So I want to ask for this feature --> [watch vue.config.js change, auto rerun].

This feature for multi page is useful.

### What does the proposed API look like?
Vue-cli can watch vue.config.js change and auto rerun

**Comment by sodatea** [comment]
For now you can use `nodemon` as a workaround.

```
nodemon --watch vue.config.js --exec yarn serve
```

**Comment by LinusBorg** [comment]
Wouldn't this be good enough? Let's document it for people that need it now and then, instead of making `serve` ever more complex.

Because most of the time you edig vue.config.js only a few times, so restarting the server manually shouldn't be a big deal.
