### ISSUE TITLE
remove emitDecoratorMetadata from tsconfig.json

### ISSUE THREAD

**Issue by doppelreim** [vuejs/vue-cli#1708]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/kaorun343/vue-property-decorator/issues/107](https://github.com/kaorun343/vue-property-decorator/issues/107)

### Steps to reproduce
This is the initial bug-report: https://github.com/vuejs/vue-cli/issues/1498

There was nothing that could be done in `vue-cli` to fix it, but I was redirected to `vue-property-decorator`.

I opened https://github.com/kaorun343/vue-property-decorator/issues/107 and a new version was released.

The new version does not use `reflect-metadata` anymore. That means, it does not rely on `emitDecoratorMetadata` any more.
In fact, when `emitDecoratorMetadata` is enabled, warnings are thrown.

`vue-cli` enables `emitDecoratorMetadata` here: https://github.com/vuejs/vue-cli/blob/05391b6e9e51917437d79c46721548dc7038993a/packages/%40vue/cli-plugin-typescript/generator/template/tsconfig.json#L9

Could that be removed?

### What is expected?
There should be no warnings.

### What is actually happening?
There are warnings.

**Comment by silkentrance** [comment]
@doppelreim vue-router does not have an export called Route, there is just the default export which is VueRouter.

```
"export 'Route' was not found in 'vue-router'
```

**Comment by silkentrance** [comment]
@Akryum and please do not remove the default emitDecoratorMetadata=true as it is required by other packages.

**Comment by silkentrance** [comment]
@doppelreim 


from your augmented components/HelloWorld.vue:

```
import { Route } from 'vue-router';
```

@kaorun343 😀

**Comment by doppelreim** [comment]
I'm confused...

What I want to have is a watcher on `$route` with typed arguments.
Something like this:
```
@Watch('$route')
private async onParamChanged(newRoute: Route, oldRoute: Route) {
  ...
}
```
I think, that is a reasonable thing to want?

`vue-router` does export a named thing called `Route`. But you are right, it is an interface.
I do not understand why it being an interface means that I can not import it. The typescript compiler does not seem to care, as long as I do not use `Route` as the type for the function-arguments.
I can use it just fine inside of the function-body (as a type).

---

Apart from that:
Who else requires `emitDecoratorMetadata`? It is not a default for `vue-cli` to include it.
It is only included if `options.classComponent` is set (see linked code in the opening post).
I assume that flag gets set, when the user answers this question from the wizard `Use class-style component syntax? (Y/n) Y`.

**Comment by yyx990803** [comment]
The flag defaults to true because it was required by `vue-property-decorator` 6.x.

**Comment by silkentrance** [comment]
@doppelreim I then added the above method incl. the watch decorator to the HelloWorld component, ran `npm run build` and `npm run serve` without any problems.

**Comment by doppelreim** [comment]
I updated vue-cli to `rc10`.
It adds a dependency on `vue-property-decorator v7`. Before, that was `v6`.
`v6` depends on the flag `emitDecoratorMetadata` to be set, `v7` does not.
The flag was removed from `tsconfig`.

The issue is solved for me :)
