### ISSUE TITLE
add `--version` argument to vue-cli-service

### ISSUE THREAD

**Issue by johnwebbcole** [vuejs/vue-cli#1709]
### What problem does this feature solve?
Developers on my teams are not upgrading local copies of vue-cli.  When asked, they either run the global `vue --version` or the version listed in the package file.  

There have been several discussions on versions in vue-land #vue-cli about versions.  It would be nice to be able to run a command and see what version you really have installed without running `npm install`.

### What does the proposed API look like?
What happens now:

```
node_modules/.bin/vue-cli-service --version

  Usage: vue-cli-service <command> [options]

  Commands:

    serve     start development server
    build     build for production
    inspect   inspect internal webpack config
    lint      lint and fix source files
    test:unit run unit tests with jest
    test

  run vue-cli-service help [command] for usage of a specific command.
```

What would be nice to have:

```
$ node_modules/.bin/vue-cli-service --version
3.0.0-rc.3
```

**Comment by Akryum** [comment]
Npm and yarn already have commands to display the versions of both local and global packages.
