### ISSUE TITLE
Strategy for transitioning away from the -2.0 templates

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-cli#171]
@zigomir Before we delete [the `-2.0` template repos](https://github.com/vuejs-templates?utf8=%E2%9C%93&query=2.0), I think it'd be good to have a PR ready to either:

1. Alert people that they no longer exist, because the main repos serve 2.0, _or_
2. Just automatically strip `-2.0` from the user input for official template installs so that it Just Works

Not sure which is the best option. What do you think?

**Comment by posva** [comment]
A warning looks better imo because if it just works people may never stop from using them

**Comment by asantibanez** [comment]
Does this mean that 2.0 templates will be the the new default templates?

**Comment by posva** [comment]
@asantibanez Yes

**Comment by zigomir** [comment]
@asantibanez yes, the default, but you can always say append `#1.0` to template name and you'll get it for 1.0.

@chrisvfritz I agree with @posva and would add a warning.

**Comment by chrisvfritz** [comment]
Sounds good to me! 🙂
