### ISSUE TITLE
Load Vue as a bundler dependency when using wc mode

### ISSUE THREAD

**Issue by lennerd** [vuejs/vue-cli#1714]
### What problem does this feature solve?
First of all, great job with the client. Have used React and `create-react-app` for a while now, which I always needed to extract, to be able to have it the way I wanted to. Not with `vue-cli`, great job! Anyway.

---

I would like to be able to use the build with `wc` mode as a normal dependency loadable via a bundler.

As the [documentation](https://cli.vuejs.org/guide/build-targets.html#library) says:

> In lib mode, Vue is externalized. This means the bundle will not bundle Vue even if your code imports Vue. If the lib is used via a bundler, it will attempt to load Vue as a dependency through the bundler; otherwise, it falls back to a global Vue variable.

This is different to the `wc` or `wc-async` mode:

> In web component mode, Vue is externalized. This means the bundle will not bundle Vue even if your code imports Vue. The bundle will assume Vue is available on the host page as a global variable.

Is there a reason to only load Vue from the global variable? I already found the corresponding code and am now trying to customise the behaviour via `chainWebpack`, although I don't see why this isn't the default for both modes.

Thanks in advance!

---

Different topic: When using `vue build --watch`, `vue-cli` generates hot updates and includes the corresponding webpack HMR code in the build. Guess that is intended?

---

### What does the proposed API look like?
Using `vue build --mode wc` would extract a build file loadable as a normal page asset or bundler dependency.

**Comment by lennerd** [comment]
Just realised that linking a local dependency, using the ProviderPlugin from webpack to provide Vue (and to solve this issue somehow) does not work with `build --watch`, probably because generated code is wrapped in `eval` for the sourcemaps. 😕

**Comment by Akryum** [comment]
> Different topic: When using vue build --watch, vue-cli generates hot updates and includes the corresponding webpack HMR code in the build. Guess that is intended?

This is probably related to #1698

**Comment by lennerd** [comment]
Thanks for the hint. This looks indeed related. Any plans on realising a new RC version to include this fix?

Regarding the mode issue: any feelings about it? Creating a PR for unifying the dependency resolution for both modes should be an easy fix (including updating the documentation), no? Just wanted to make sure to get all infos about possible decisions behind it, before shooting PRs somewhere.

**Comment by philipfeldmann** [comment]
@lennerd Any new suggestions on the chainWebpack method? I'm running into the same issue currently.

**Comment by lennerd** [comment]
Sorry, I only used the the `wc` mode for trying out webcomponents with vue. Found a few bigger gotchas (like missing native slots for example to style wrapped elements) and started to use React for this again.

**Comment by shaydoc** [comment]
To add a little weight here, I would very much like this option to work also. I need to build vue components as webcomponents, but then import them into my main vue app bundle and do not want to rely on Vue having to be a global variable. Does using the ProviderPlugin work here ?

**Comment by seteam1** [comment]
We would like to see this capability as well when using a build target of Lib.

**Comment by shaydoc** [comment]
@Akryum 
The thing I really need actually is the ability to customize the name I externalize the alias  for Vue

e.g.

```
// externalize Vue in case user imports it
    config
      .externals({
        ...config.get('externals'),
        vue:  process.env.VUE_EXTERNAL_NAME || 'Vue'
      })

```

**Comment by shaydoc** [comment]
The glob build for webcomponents also only seems to build 1 component, had to do this:

https://github.com/vuejs/vue-cli/pull/4054

You may know a better solution!!1

**Comment by sodatea** [comment]
1. To not externalize Vue, there's a `--inline-vue` option available since v4 https://github.com/vuejs/vue-cli/pull/4261
2. To require Vue as a CommonJS dependency, put the following snippet into your `vue.config.js`:
```js
module.exports = {
  chainWebpack: config => {
    config.externals({ "vue": "commonjs vue" })
  }
}
```
