### ISSUE TITLE
Webpack DevServer configuration for Docker

### ISSUE THREAD

**Issue by sdzyba** [vuejs/vue-cli#1716]
### Version
3.0.0-rc.3

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
Generate a basic project using vue-cli.
Run `npm run serve` in docker container.

### What is expected?
App works and it's accessible, hot reload works

### What is actually happening?
App works and it's accessible, hot reload doesn't work

---
The issue is that it automatically starts the devserver using docker container's internal IP:
```
app_1  |   App running at:
app_1  |   - Local:   http://localhost:8080/
app_1  |   - Network: http://172.23.0.2:8080/
```
I can't access `172.23.0.2:8080` at all since Docker for Mac has limited networking [features](https://docs.docker.com/docker-for-mac/networking/).
It would be awesome to be able to configure devserver to use only 0.0.0.0 and tell it to not to listen also a LAN address.

**Comment by LinusBorg** [comment]
have you tried `npm run serve --host 0.0.0.0` ?

**Comment by sdzyba** [comment]
I believe you meant `vue-cli-service serve --host 0.0.0.0`.
No, this didn't help and I can't find any option that would disable listening on "external" address for hot module reload.
And the main problem that it seems there are no workaround for Docker as well.
Just to illustrate the behavior, here are requests when running devserver without docker, just on host machine:
![screen shot 2018-06-29 at 23 39 55](https://user-images.githubusercontent.com/5605160/42117477-5e8d80a0-7c05-11e8-9392-70d9ddb5c2f9.png)

and here's the same app running in Docker:
![screen shot 2018-06-29 at 23 38 14](https://user-images.githubusercontent.com/5605160/42117487-6a36a120-7c05-11e8-8048-bf7bcdf363fd.png)

There are just no possibility to access docker container by it's IP in Mac OS. It's available only through binding to 0.0.0.0.

**Comment by Garito** [comment]
build your app before serve in docker

**Comment by sdzyba** [comment]
@Garito I'm running the app in development environment, maybe I'm missing something but how hot reload is related to the built app?

**Comment by sdzyba** [comment]
I see that it is hardcoded to set LAN url if `0.0.0.0` host provided: https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/util/prepareURLs.js#L29

Can this be avoided in some way?

**Comment by vchaptsev** [comment]
Hmm, maybe this will help?
```js
// vue.config.js
module.exports = {
  devServer: {
    public: '0.0.0.0:8080'
  }
}
```

**Comment by Garito** [comment]
The development server activates hot reload
When you build the app doesn't use it
In the new webpack there are modes (development with hot reload and production without)

**Comment by DRoet** [comment]
I had the same issue, the workaround I used for this problem was setting "network_mode: host" in docker-compose.

**Comment by sdzyba** [comment]
@vchaptsev thanks, but that didn't help.
@Garito I'm working in development environment, I don't need to build the application.
@DRoet thanks, that might help if working with a single setup although I'm running a range of different services and they're configured to be in specific docker networks

I believe vue-cli should have some option that will either make devserver to communicate only with localhost or an option that would disable binding to LAN address at all.

**Comment by Garito** [comment]
You can change the mode from development to production without building the app
This should deactivate the hot reload
Besides that the new webpack configuration format will help you reconfigure webpack with your needs
Check the vue-cli 3 documentation

**Comment by sdzyba** [comment]
@Garito I think there are some miscommunication. Original post here says that hot reload isn't working and I want it to be working, not the opposite.

**Comment by sdzyba** [comment]
@vchaptsev I'm sorry, you were right. Setting `public: '0.0.0.0:8080'` in `vue.config.js` solves the issue but two moments here:
- it's a bit unclear at first that this change has affected the setup somehow. [Here](https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/commands/serve.js#L90) the LAN URL  affected the socks URL which, I believe, defines with which host devserver communicate. It would be great to have some additional info in the server start output regarding this.
- I have a very weird issue with `docker restart` command (and that's the primary reason I didn't notice any change at first). Suppose you run `docker start`, everything including hot reload works just fine and then you decide to `docker restart` a container, even without any change to configs or data. After that no matter what you do you would receive just previous application state, not mentioning hot reload. It just looks like previous devserver haven't been killed for some reason, but the new was just started on the same port... Sounds impossible but I just can't find any particular reason what is happening.
The interesting thing is that if you do `docker stop` and `docker start` everything works just as expected and the application served perfectly.

**Comment by vchaptsev** [comment]
@sdzyba glad to hear it :)
Yes, this is an unclear solution, but this is the best way I have found.

**Comment by Garito** [comment]
Sorry, my bad...
I'm using the cli with docker and hot reload comes and goes width the versions but I'm accessing it with the localhost:8080 without issues (no need to set the ip at all) when it works
Did you try that?
As I understand, docker toolbox bridges the ip of the container to your localhost exactly to avoid this kind of troubles
I could post here (if is ok) my dockerfile for the container and how I start it (so I shouldn't care if the container is destroyed or what and works for me)

**Comment by Joshfindit** [comment]
Thanks a lot for everyone who's contributed to this discussion. I came here having the same issue (also Docker, but on linux), and while I'm having difficulty getting `yarn serve` to pick up `vue.config.js`, this feels like a good temporary fix.

As a permanent fix, would it be reasonable to change whatever is hardcoded to the LAN IP, and have it respect `serve --host` with a default of the same IP used to serve the page?

**Comment by Harti** [comment]
I'm upset. How can we have a *release candidate 7* (seven!) that doesn't support what vue-cli 2.x (which is now deprecated) did out of the box?

My template installation _doesn't even have_ a `vue.config.js`. Am I supposed to put it in the app root, will it get recognized, and why do I have to do this in the first place? 

Anyone who maintains this project should really be looking into this before the release becomes official. It's not understandable to me how @Akryum can be putting "enhancement" labels on these issues while supporting them should be obligatory. What else would you use vue-cli for, if not for development with HMR?
Local web development _has_ indeed moved on from installing all the dependencies on your host machine to Docker-izing anything as well as possible. Please do look into this, people.

**Comment by yyx990803** [comment]
General note on using Vue CLI 3 with docker: you need to run the container with proper command:

``` sh
docker run \
  # run in interactive mode
  -it \
  # bind the port properly
  -p 8080:8080 \
  # mount your app volume so that changes trigger HMR
  -v $(pwd)/app:/app \
  your-image-name
```

When you try to access the app, you can ignore network address shown by the serve command (there's no way for us to know you are running inside docker). Use `localhost:<your container's externally bound port>` instead.

HMR issue should be fixed in da38ed4a (tested with Docker for mac).

**Comment by cstrat** [comment]
I spent way too much time on this one... 🤦🏻‍♂️😐

```
devServer: {
    host: '0.0.0.0',
....
```

**Comment by michaelscheurer** [comment]
On Windows we solved it using polling.

Adding the following code to vue.config.js

```
devServer: {
        watchOptions: {
            ignored: /node_modules/,
            aggregateTimeout: 300,
            poll: 500
        }
    }
```

See: https://daten-und-bass.io/blog/enabling-hot-reloading-with-vuejs-and-vue-cli-in-docker/

**Comment by itwara** [comment]
> I spent way too much time on this one... 🤦🏻‍♂️😐
> 
> ```
> devServer: {
>     host: '0.0.0.0',
>     ....
> }
> ```

this is ok! thanks!

**Comment by tlw-ray** [comment]
webpack-dev-server docker in windows no hot push need: 

devServer: {
        watchOptions: {
            ignored: /node_modules/,
            aggregateTimeout: 300,
            poll: 500
        }
    }

**Comment by weleoka** [comment]
Trying to run WebPack (express) server for development in a Docker container using Vue-cli? The output of `npm run serve` will probably look like:

```
node-dev        |   App running at:
node-dev        |   - Local:   http://localhost:8080/ 
node-dev        | 
node-dev        |   It seems you are running Vue CLI inside a container.
node-dev        |   Access the dev server via http://localhost:<your container's external mapped port>/

```
This output is wrong. The devServer always binds to `0.0.0.0`. 


Problem: want to bind server to the 0.0.0.0 interface in container?
Answer: you always do. All configurations and change always has same result:
`tcp        0      0 0.0.0.0:8787            0.0.0.0:*               LISTEN`

Problem: want to bind server to containers NIC internal IP address, or localhost?
Answer: you can't. The log output says `localhost` but it is always `0.0.0.0`.

Problem: want to reach container using name resolution like in docker-compose network?
Answer: the devServer will not respond correctly unless you specify `devserver: {public: "myhostname"}` in configuration.  - see ISSUE-1


The config file for Vue-cli `vue.config.js` can be used as follows (see comments):

```
  configureWebpack: {
    devServer: {
      public: "node-dev:7878", // works, will be reachable by hostname and ip address! BUT: specifying port has no effect here (ISSUE-2 docs are wrong)
      //public: "0.0.0.0:7878", // no effect.
      //host: "0.0.0.0:7878", // no effect.
      port: 7878, // works (and output reflects this)
   }
```

The following two points are possible issues which should be addressed in the project(s):

ISSUE-1) Only reachable by container ip for example: `curl http://172.21.21.8:7878`. Calling by a DNS like `curl http://node-dev:7878` fails with message: `Invalid Host Header`.

ISSUE-2) = Port does not have effect or is victim of override. Potentially docs are wrong at: https://webpack.js.org/configuration/dev-server/#devserverpublic
