### ISSUE TITLE
lintOnSave doesn't fail the build

### ISSUE THREAD

**Issue by affanshahid** [vuejs/vue-cli#1719]
### Version
3.0.0-rc.3

### Reproduction link
[http://www.not-relevant.com](http://www.not-relevant.com)

### Steps to reproduce
Set lintOnSave to true
Add an error in your code based on your eslint configuration
Run `npm run build`

### What is expected?
The eslint error should cause the build to fail

### What is actually happening?
The error gets printed to screen but the build proceeds.

---
Not sure what to add in link for a cli problem

**Comment by LinusBorg** [comment]
by default, the eslint-loader only emits warnings, so it doesn't break the build process during development.

But - and this is missing from the documentation - you can actually set it like this:
```
lintOnSave: 'error'
```

and it will throw an error now.

relevant source is here: 

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-eslint/index.js#L39

So you could do the following, for example:
```javascript
lintOnSave: process.env.NODE_ENV !== 'production' ? true : 'error'
```

I'll send a PR to update the docs for this.
