### ISSUE TITLE
Web Extension build target

### ISSUE THREAD

**Issue by andreasvirkus** [vuejs/vue-cli#1721]
### What problem does this feature solve?
A way to have a single repo and webpack setup, whose build outcome 
would be popup (html   script), background (html   script) and content script.

Also, what's a decent way to solve this need atm with the current vue-cli 3 RC3?
For now, I'm using `pages` in my vue config:
```
module.exports = {,
  pages: {
    popup: {
      entry: 'src/popup/main.js',
      template: 'public/index.html',
      filename: 'popup.html'
    },
    contentScript: 'src/content/main.js'
  }
}
```
Ideally `contentScript` would just have a `contentScript.js` - is this achievable in a clean way atm?
Atm I just use a bash script to strip the hash from the script name.

### What does the proposed API look like?
`vue-cli-service build --target [extension|web-extension]`
And ideally also a flag to target either Chrome (default?), Firefox or Opera (the latter 2 don't require a huge change, if any).

**Comment by LinusBorg** [comment]
What you have seems to do what you want, pretty much, no? 

Ideally contentScript would just have a contentScript.js - is this achievable in a clean way atm?
```
// vue.config.js

chainWebpack: config => {
  config.output.filename('[name].js')
}

// or
configureWebpack: {
  output: {
    filename: '[name].js'
  }
}
````

Providing this config and template for the html files etc could be easily done as a small plugin from the community.

I don't see this as na use case prominent and complicated enough to warrant an integration into core.

**Comment by andreasvirkus** [comment]
Sorry, forgot I opened this. Yeah, pages actually solves what I want and I was overthinking it a bit. The only thing I had to do was remove the default `div#app` from my content script's template file and just create it in `content/main.js`:

```
const rootId = '_my_widget_mount'
const root = document.createElement('div')
root.setAttribute('id', rootId)
document.body.appendChild(root)

new Vue({
  render: h => h(App)
}).$mount('#' + rootId)
```
