### ISSUE TITLE
Adjust documentation for using @vue/babel-preset-app in a non vue-cli environment

### ISSUE THREAD

**Issue by ChristianStornowski** [vuejs/vue-cli#1725]
### What problem does this feature solve?
Using ts-jest, babel, @vue/babel-preset-app and @babel/preset-typescript" together, causes tests failures even when setting typescript compiler option `"module"` to `"commonjs"` and `"allowSyntheticDefaultImports"` to `"true"`.

.babelrc

```
{
  "presets": [
    "@vue/app",
    "@babel/preset-typescript"
  ]
}
```

### What does the proposed API look like?
Documentation of setting environment variables before running ts-jest.

```
VUE_CLI_BABEL_TARGET_NODE = true
VUE_CLI_BABEL_TRANSPILE_MODULES = true
VUE_CLI_BUILD_TARGET = app
```

**Comment by LinusBorg** [comment]
I'm not sure that I can reproduce a project with the behaviouir you are seeing 

* which options did you choose when installing?
* What changes, if any, did you make to the clean project?
* What command did you run?
* What error did you recieve?

**Comment by ChristianStornowski** [comment]
I created this online project: https://codesandbox.io/s/7w5qrwpxnq

`npm test` will failure with

> import "core-js/modules/es6.promise";
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
>    SyntaxError: Unexpected string

`npm run test:working` is going to be fine. (maybe you have to delete jest tmp folder first (Linux: /tmp/jest_rs/).

**Comment by LinusBorg** [comment]
Oh, now i get it. Should have read your title more carefully.

So you are using the babel preset in an app not created with vue-cli, and had to dig into the yource to learn that you have to set some ENV variables to make it work the way you expect it to.

And your request would be that these env variables are documented in that preset's README.

Seems sensilbe. :)

**Comment by pikax** [comment]
I'm having the same issue with app installed with vue-cli
![image](https://user-images.githubusercontent.com/4620458/42166744-e5a14676-7e03-11e8-8eb8-2a1b7cde49a0.png)

if I run test:unit I get 
```
yarn run v1.7.0
$ vue-cli-service test:unit

No tests found
In C:\Dev\other\vue-cli-full
  75 files checked.
  testMatch: C:\Dev\other\vue-cli-full\(tests\unit\**\*.spec.(js|jsx|ts|tsx)|**\__tests__\*.(js|jsx|ts|tsx)) - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 75 matches
Pattern:  - 0 matches

 ERROR  jest exited with code 1.
```

If I change the testMatch to:
``` javascript
// jest.config.js
//...
  testMatch: [
    // '<rootDir>/(tests/unit/**/*.spec.(js|jsx|ts|tsx)|**/__tests__/*.(js|jsx|ts|tsx))',

    '**/tests/unit/**/*.spec.(js|jsx|ts|tsx)'
  ]
```

I get

![image](https://user-images.githubusercontent.com/4620458/42166894-4fb39f78-7e04-11e8-803d-4a3ea8c6374f.png)

**Comment by LinusBorg** [comment]
This is unrelated, your issue is discussed in #1686

**Comment by yyx990803** [comment]
`@vue/babel-preset-app` is **specifically designed to use with projects created via Vue CLI**. It does not consider uses cases outside of Vue CLI. We can make this more explicit in its README.

**Comment by victor71** [comment]
> `@vue/babel-preset-app` is **specifically designed to use with projects created via Vue CLI**. It does not consider uses cases outside of Vue CLI. We can make this more explicit in its README.

How to determine core-js3 in @vue/babel-preset-app? I add the 'corejs' option to preset '@vue/app', but it now work.

**Comment by sodatea** [comment]
@victor71, For now, use @vue/babel-preset-app v4.0.0-alpha.0. It's too much work for us to keep compatibility with both core-js versions, so we only bump the version in a new major release.

**Comment by victor71** [comment]
@sodatea Thank you!
