### ISSUE TITLE
Adding webpack plugin in chainWebpack mode failed

### ISSUE THREAD

**Issue by MarvinXu** [vuejs/vue-cli#1729]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/MarvinXu/vue-cli-mpa-test/commit/c5915751c2d98b4434908bc7e1b565007ab0a69c](https://github.com/MarvinXu/vue-cli-mpa-test/commit/c5915751c2d98b4434908bc7e1b565007ab0a69c)

### Steps to reproduce
https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-plugin

```javascript
module.exports = {
  chainWebpack: config => {
    config
      .plugin('html')
      .tap(args => {
        args[0].template = '/Users/username/proj/app/templates/index.html'
        return args
      })
  }
}
```

npm run serve

### What is expected?
no error

### What is actually happening?
`TypeError: Cannot read property '__expression' of undefined`

**Comment by LinusBorg** [comment]
Will take a look tonight, can't really imagine this is broken

**Comment by MarvinXu** [comment]
I tested it again on my home pc, broke still.
win7 ; npm5.6.0; 
reproduction steps:
1. vue create myproject
2. add vue.config.js
```
module.exports = {
  chainWebpack: config => {
    config
      .plugin('html')
      .tap(args => {
        return args
      })
  }
}
```
3. npm run serve

**Comment by LinusBorg** [comment]
Ok, your own project fails. But now I realize you are using the "pages" feature.

See the docs here: https://cli.vuejs.org/config/#pages

> TIP
> 
> When building in multi-page mode, the webpack config will contain different plugins (there will be multiple instances of html-webpack-plugin and preload-webpack-plugin). Make sure to run vue inspect if you are trying to modify the options for those plugins.

In other words: since you are using the `pages` option, there's no plugin called `html`.

**Comment by MarvinXu** [comment]
My bad, forgot the "minimal reproduction" basic... Thanks!

**Comment by jinwyp** [comment]
Thanks @LinusBorg .

**Comment by stephanepericat** [comment]
```shell
vue inspect --plugins
[
  'vue-loader',
  'define',
  'case-sensitive-paths',
  'friendly-errors',
  'hmr',
  'no-emit-on-errors',
  'progress',
  'html',
  'preload',
  'prefetch'
]
```

I get the same issue, here is my list of plugins...

looks like calling "config.plugin()" causes this error no matter what option you overwrite

**Comment by LinusBorg** [comment]
You might have the same issue but appearantly are nor using the pages feature. 

Hence: 

Open an issue and provide a reproduction. 

This issue is resolved and  closed.
