### ISSUE TITLE
New command: `vue build`

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-cli#173]
Ref: https://github.com/egoist/vbuild/issues/9#issuecomment-247859666

@egoist is the author of `vbuild` which is a zero-config tool for prototyping Vue projects. We'd like to fold that functionality into `vue-cli` as `vue build` with a sharper focus on prototyping experience.
### Summary
- if a user wants to build a production app, use `vue init`;
- if a user wants to quickly prototype an idea, use `vue build --dev` (and in most cases can later just copy the `src` files into a production scaffold generated with `vue init`)
### Technical Notes (open to discussion)
- Should support directly building a `*.vue` file, e.g. `vue build App.vue` and BOOM. Great for single-component prototyping. (Maybe even incorporate something like [react-storybook](https://github.com/kadirahq/react-storybook) if running in single-component mode)
- We want this to be clearly focused on prototyping, so the default setup should be minimal and fast. Probably better to use a lighter weight ES2015 transpiler e.g. `buble`.
- Users will still inevitably have their preferences, even for prototyping. But maybe we can make this config global, e.g. have one single `vue.config.js` in the user's home directory, which `vue build` will then use for all prototypes - configure once, run everywhere.
- Is there any smart way to transition a project using `vue build` to a proper scaffolded project created from `vue init`?
### Nice to Have
- auto-infer the npm dependencies in the files and `npm install` them automatically

**Comment by egoist** [comment]
> Is there any smart way to transition a project using vue build to a proper scaffolded project created from `vue init`?

It would be hard to adapt all vue templates, maybe make an offical vue template for this and use something like `vue init template my-project --source <prototype dir> `?

**Comment by yyx990803** [comment]
@egoist yeah, we can think about that later and focus on the core experience for now.

**Comment by egoist** [comment]
Intend to work on this today, two more questions:

- This function will introduce a bit more dependencies, like webpack, loaders, plugins, I'd like to separate them in another package and use it in `./bin/vue-build`
- If we use buble, does it support Vue jsx? Probably we should still use babel, or give babel as an option. I prefer the latter.

**Comment by egoist** [comment]
A quick implementation, still some issues... https://github.com/egoist/vue-prototype

**Comment by egoist** [comment]
I think `vue play` might be a better option, only focus on development experience, and when users want to go further, they can transit the prototype to a vue-cli template.

**Comment by kennetpostigo** [comment]
If you are looking to use buble its a good option but if you want less verbose output from babel try it in loose-mode to see how much it helps before trying buble.
