### ISSUE TITLE
Invoke plugin in an other folder than src

### ISSUE THREAD

**Issue by simonackermann** [vuejs/vue-cli#1730]
### What problem does this feature solve?
I am currently working on a project using symfony 4 and have put all the front-end part in the assets folder, it would be great to be able to change the directory in wich the new files are scafolded ex: './assets'.
Because for example when I run 'vue add @vue/pwa' the new js file goes into the src folder where the sources for symfony are.

### What does the proposed API look like?
Maybe add an option on the vue add & invoke command ?
ex: vue add @vue/pwa --folder assets

**Comment by pksunkara** [comment]
There are 2 things here:

1. The base folder vue-cli uses to run all the plugins.
2. The folder being created by @vue/pwa or other plugins when generating code.

In the second case, it's nice to add the folder option for each individual plugins, but what about the 3rd party ones? Who would make sure that they follow the standard. A better way to do this would be give the folder option for the first case.

Right now, `vue add` and `vue invoke` only allows the folder containing the `package.json` as the base folder. If we want to add folder option there, then we need to search for pkg json file going up parent folder by parent folder.

**Comment by LinusBorg** [comment]
We just recently had a lengthy discussion about support of changing defsult folders similar to this.

We concluded that we want to focus on one standard layout. Supporting change of all sorts of directories overcomplicates the system.
