### ISSUE TITLE
Template files starting with an underscore are renamed to a start with a period

### ISSUE THREAD

**Issue by SharpSeeEr** [vuejs/vue-cli#1732]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/buefy/vue-cli-plugin-buefy/issues/8#issuecomment-401846995](https://github.com/buefy/vue-cli-plugin-buefy/issues/8#issuecomment-401846995)

### Steps to reproduce
1. Create a new project: vue create <projectname> and choose to install support for SASS.
2. Install plugin: vue add buefy and select to add SCSS support.
3. The file located at
`src/assets/scss/.variables.scss` should be named
`src/assets/scss/_variables.scss`

### What is expected?
Should have a file at the following location:
`src/assets/scss/_variables.scss`

### What is actually happening?
The file is actually named:
`src/assets/scss/.variables.scss`

---
We believe the problem comes from https://github.com/vuejs/vue-cli/blob/05391b6e9e51917437d79c46721548dc7038993a/packages/%40vue/cli/lib/GeneratorAPI.js#L139 where files starting with an _ are renamed to start with a . due to .files not included in npm uploads.

Files starting with an underscore are standard syntax for SCSS partials.

**Comment by Akryum** [comment]
@yyx990803 any suggestion for this?

**Comment by LinusBorg** [comment]
Well, we need a workaround like this to  be able to work with dot-files in the generator. We can either change the "escape character" from `_` to something else, like `__` (2 underscores), or we can add another rule that says that files that should begin with an underscore should beginn with 2 underscores in templates, or something like this.


```
// either
__.mydotfile > .mydotfile
_variables.scss > _variables

// or
_.mydotfile > .mydotfile
__variables.scss > _variables
```

**Comment by Akryum** [comment]
That would be:

```
_mydotfile > .mydotfile
__variables.scss > _variables.scss
```

**Comment by LinusBorg** [comment]
Right, thanks - fixed my post above.

The latter variant:

```javascript
if (filename.charAt(0) === '_' && filename.chatAt(1) !== '_') {
  filename = `.${filename.slice(1)}`
}
if (filename.charAt(0) === '_' && filename.chatAt(1) === '_') {
  filename = `${filename.slice(1)}`
}
```

**Comment by SharpSeeEr** [comment]
Perfect.  Thanks!
