### ISSUE TITLE
Remote preset from any git repository

### ISSUE THREAD

**Issue by petr001** [vuejs/vue-cli#1738]
### What problem does this feature solve?
At the moment, only github / bitbucket / gitlab repositories are allowed. I'd like to add custom git url which contains my preset.

### What does the proposed API look like?
no proposed API

**Comment by Akryum** [comment]
You can already. Use the clone option.

**Comment by petr001** [comment]
Thanks.

I was creating project via `vue ui` and the option is missing there. Quite minor thing but can be added also to UI...

**Comment by Akryum** [comment]
It's the switch below the input.

**Comment by petr001** [comment]
OK, got it... I don't know why I was ignoring it... Works well, thanks!
