### ISSUE TITLE
vue-cli ，通过npm install zepto 时，在项目中require（'zepto'） 时，读不到zepto.js读不到window对象？

### ISSUE THREAD

**Issue by yang6701218** [vuejs/vue-cli#174]
如题：谢谢

**Comment by zigomir** [comment]
@yang6701218 can you please elaborate a bit more.

**Comment by egoist** [comment]
If you mean https://github.com/madrobby/zepto/issues/1210 I would suggest that you search before ask.

**Comment by yolo2013** [comment]
这个不是vue的问题，是zepto并不支持npm的方式引用，可以尝试[n-zepto](https://www.npmjs.com/package/n-zepto)
