### ISSUE TITLE
Native window.onerror handler doesn't work.

### ISSUE THREAD

**Issue by marlonbarcarol** [vuejs/vue-cli#1751]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/marlonbarcarol/vue-cli-reproduction-window-onerror](https://github.com/marlonbarcarol/vue-cli-reproduction-window-onerror)

### Steps to reproduce
run `npm run serve` and then open console(it was Chrome in my case).

### What is expected?
Should have an error stack in your console with the message `Oops! An error occurred` followed by it's line, column and error object.

### What is actually happening?
The error that was threw isn't in your console with the given message, instead you'll get `Script error.`  followed by 0 0 null

---
`Script error.` happens only when the webpack devtool is set to use anything that realizes eval, changing the devtool to `cheap-module-source-map` fixes the problem. 

I have found a related issue on vuejs-templates repo. https://github.com/vuejs-templates/webpack/issues/1350

**Comment by Akryum** [comment]
I don't think we can do anything about that as it looks like an issue related to webpack and browsers.

**Comment by marlonbarcarol** [comment]
As developers expect the event `window.onerror` to be working as usual, wouldn't be a case for changing the default devtool value from `cheap-module-eval-source-map` to `cheap-module-source-map`?

**Comment by Akryum** [comment]
@yyx990803 What do you think?

**Comment by LinusBorg** [comment]
`cheap-module-source-map` is *much* slower on rebuilds (according to webpack docs), so that would mean we deliver a slower development experience by default, I don't think that's a good alternative.

Couldn't we add some documentation about this so people can swich to a different devtool if they actually need to use that hook?

**Comment by marlonbarcarol** [comment]
I don't completely agree with having a global error event handler that doesn't work as expected. However, as we have noticed this issue has been going on for a while, and neither is something that people have been asking, nor would be fair for most of the developers that doesn't use this functionality to have their experience degraded due to making the build process slower as you have mentioned. 

I believe that adding it to the documentation would be great for the ones that will be looking to use this functionality.

**Comment by wcjr** [comment]
yes, what is the alternative to handling any unpredicted DOM Event in a Vue app?

**Comment by LinusBorg** [comment]
I don't understand that question

**Comment by wcjr** [comment]
I've learned more about the app running in "production" mode so I'm not going to worry about DOM Events, e.g., a `click` event or something from an `async` for now...Thanks @LinusBorg
