### ISSUE TITLE
Disabling hash from filename / build ignores assetsDir

### ISSUE THREAD

**Issue by CoolGoose** [vuejs/vue-cli#1753]
### Version
3.0.0-rc.3

### Reproduction link
[https://codepen.io/anon/pen/zaXgNz](https://codepen.io/anon/pen/zaXgNz)

### Steps to reproduce
Setup vue-cli , and use the setup of vue.config.js from the link above.

### What is expected?
To have dist/assets/app.css

### What is actually happening?
Without specifying the assets folder manually in the filename it ignores the assetsDir option.

**Comment by Akryum** [comment]
I'm not sure you can specify a path in the file names. Please try:

```js
module.exports = {
  css: {
    extract: {
      filename: '[name].css',
      chunkFilename: '[id].css'
    }
  }
}
```

**Comment by CoolGoose** [comment]
@Akryum actually it works, the example on codepen is working. Just that it's weird to hack around that way :)

**Comment by CoolGoose** [comment]
@Akryum Why is this closed ? The question remains on why a manual overwrite needs to happen since it doesn't respect the assetsDir setting

**Comment by Akryum** [comment]
You issue wasn't clear to me. You mean the extracted CSS isn't under `assetsDir`?

**Comment by CoolGoose** [comment]
@Akryum 
That's correct, the CSS and JS aren't under assetsDir. Hence the hack of adding assetsDir + filename in chainWebpack and configureWebpack.

It should just work with 
```
configureWebpack: {
    output: {
      filename: "[name].js",
      chunkFilename: "[name].js"
    }
  },
```

and not with 
```
configureWebpack: {
    output: {
      filename: assetsDir + "/[name].js",
      chunkFilename: assetsDir + "/[name].js"
    }
  },
```

Or is the assetsDir not supposed to apply anymore once you manually overwrite the filename / chunkFilename ?

**Comment by Akryum** [comment]
> Or is the assetsDir not supposed to apply anymore once you manually overwrite the filename / chunkFilename ?

Yes, because we don't know what you really want. By default we set `filename` to `assetsDir + '/css/[name].[contenthash:8].css'`, so if you overwrite it well it doesn't have `assetsDir` in it.

What you should do in `vue.config.js`:

```js
module.exports = {
  css: {
    extract: {
      filename: 'my-assets/[name].css',
      chunkFilename: 'my-assets/[id].css'
    }
  }
}
```

I'm not sure if it's a good idea to modify the options the developer set up in `vue.config.js` since maybe he wants to put the css somewhere else. @yyx990803 any thoughts?

**Comment by CoolGoose** [comment]
@Akryum 

Well i would assume that a setting called `assetsDir` , is still used when overwriting the `filename`
I understand your reasoning though. Maybe an heads up in the documentation ?

**Comment by Akryum** [comment]
> Maybe an heads up in the documentation ?

Feel free to PR! 😸
