### ISSUE TITLE
vue create error occured

### ISSUE THREAD

**Issue by daktwigim** [vuejs/vue-cli#1761]
### Version
3.0.0-rc.3

### Reproduction link
[http://thereisnorepro.com](http://thereisnorepro.com)

### Steps to reproduce
vue create project-name
manually select features: Babel, Router, Vuex, Linter
use yarn

### What is expected?
I just want to make project....

### What is actually happening?
yarn install v1.2.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error mini-css-extract-plugin@0.4.1: The engine "node" is incompatible with this module. Expected version ">= 6.9.0 <7.0.0 || >= 8.9.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 ERROR  command failed: yarn

**Comment by Akryum** [comment]
What is your node and OS version?

**Comment by revelt** [comment]
@daktwigim so the error message is telling that your node is incompatible with the module `mini-css-extract-plugin` and your node has to be between versions  ">= 6.9.0 <7.0.0 || >= 8.9.0". This raises a question — **which version is your Node?** To check that, type `node --version` in the terminal.

Having said that, maybe running `npm` instead of `yarn` will be more forgiving? Because I never get these kinds of messages using packaged `npm`...

**Comment by Akryum** [comment]
Yarn does have a `ignore-engines` flag: https://yarnpkg.com/fr/docs/cli/install#toc-yarn-install-ignore-engines

**Comment by daktwigim** [comment]
@Akryum
macOS 10.13.5 & node v8.6.0

**Comment by Akryum** [comment]
> error mini-css-extract-plugin@0.4.1: The engine "node" is incompatible with this module. Expected version ">= 6.9.0 <7.0.0 || >= 8.9.0".
> error Found incompatible module

**Comment by daktwigim** [comment]
@Akryum I didn't said that problem is solved...
I've updated my node to v.8.6.0 but there is still an error.

> Vue CLI v3.0.0-rc.3
> ✨  Creating project in /Users/daktwigim/_Dev/_xSync/scanner_admin.
> 🗃  Initializing git repository...
> ⚙  Installing CLI plugins. This might take a while...
> 
>  ERROR  command failed: yarn

**Comment by skprakash** [comment]
**I'm getting similarly issue on my system**

Version
3.3.0

System Info
$ yarn --version
1.13.0
$ node --version
v10.15.0
$ npm --version
6.4.1
Window System (64bit)

when I tried to create project using following commond (cli), got the error.
Please can any one help me in resolving this ?

 **vue create project-name**
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
error eslint@5.12.1: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0". Got "9.8.0"
errorinfo Found incompatible module
Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR command failed: yarn**
