### ISSUE TITLE
[cli-service] Update webpack to 4.11.1

### ISSUE THREAD

**Issue by rayfoss** [vuejs/vue-cli#1770]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/FranckFreiburger/vue-pdf/issues/97](https://github.com/FranckFreiburger/vue-pdf/issues/97)

### Steps to reproduce
1. set up vue cli
2. use a module with a window dependency such as vue-pdf/pdf-js
3. get errors about window not being defined while running the dev server mode

### What is expected?
Upstream fix should be applied downstream

### What is actually happening?
Webpack 4.8.x is still being used instead of 4.11.1, which addressed the issue

---
Very annoying bug while in dev as there is always an error in your console

**Comment by yyx990803** [comment]
4.11 is a minor version. Just delete your lockfile and reinstall.
