### ISSUE TITLE
How to use historyApiFallback in MPA mode?

### ISSUE THREAD

**Issue by gitivon** [vuejs/vue-cli#1778]
### What problem does this feature solve?
vue-cli 3 （3.0.0-rc.3）设定了 pages 属性并在开发环境下使用vue-router(history mode)时，刷新页面就会失效，但访问多页应用的每个根目录可以正常生效。

### What does the proposed API look like?
兼得 MPA 和 history route

**Comment by LinusBorg** [comment]
Your issue is a question, not a feature request.

If you think something is not working as intended, please create a bug report issue and provide a code repository that demonstrates the issue.
