### ISSUE TITLE
Dart Sass support as a stylesheet preprocessor option

### ISSUE THREAD

**Issue by rayfoss** [vuejs/vue-cli#1782]
### What problem does this feature solve?
node-sass is the most painful node dependency in the entirety of the npm ecosystem. Plus dart sass is faster, allows code sharing with docker (no binaries), never breaks installations after a system or node update...

I realize there will be limitations... which I'm willing to work around for the benefits

### What does the proposed API look like?
```
$ vue-cli generate foo

Sass ( node-sass )
Sass ( Dart Sass - Experimental ) *
Less
Stylus
```

**Comment by LinusBorg** [comment]
We don't have a hard dependency on node-sass - sass-loadee needs it. Does sass-loadee support dart-sass as well, or does a fork exist or something? 

At the end of the day we need a loader for it.

**Comment by Gnuk** [comment]
As I can see, in https://github.com/webpack-contrib/sass-loader/issues/435, it's not currently supported inside sass-loader.

The merge request https://github.com/webpack-contrib/sass-loader/pull/573 let `sass-loader` be "implementation-agnostic" but it's not currently merged.

I think it's a good idea to have `dart-sass` because it's the official package referenced in Sass lang as a npm provider:

* Installation page from Sass lang: https://sass-lang.com/install
* Referenced package is `dart-sass`: https://www.npmjs.com/package/sass

But I think you'll wait `sass-loader` support `dart-sass` if you want webpack support.

**Comment by LinusBorg** [comment]
Well I'm not sure how using dart sass would work without a loader supporting it, since the whole build process of vue-cli is built around webpack.

**Comment by rayfoss** [comment]
@LinusBorg https://github.com/webpack-contrib/sass-loader/pull/573 is the loader

it could be implemented as a generator time option... like fountainjs has been doing it... `Sass (dart-sass experimental)`

**Comment by LinusBorg** [comment]
Well, that PR hasn't been merged yet, so as of today there's no loader that supports dart -sass, right?

**Comment by rayfoss** [comment]
The prophecy is upon us:

> Rather than always loading Node Sass, this now requires users to pass in
> either Dart Sass or Node Sass as an option to the loader.

commit: bed9fb5799a90020d43f705ea405f85b368621d7

https://github.com/webpack-contrib/sass-loader/commit/bed9fb5799a90020d43f705ea405f85b368621d7

**Comment by Gnuk** [comment]
It's also my opinion but like I see after the merge request of the sass loader, `node-sass` still the default implementation proposed. It could be a choice during creation from vue cli I think.

**Comment by beary** [comment]
I tried to use `dart-sass` according `sass-loader`'s [example](https://github.com/webpack-contrib/sass-loader#examples)
```js
/* vue.config.js */
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        implementation: require('sass')
      }
    }
  }
}
```
But it's reports
```bash
> test@0.1.0 serve /home/beary/nodeWorkSpace/test
> vue-cli-service serve
 INFO  Starting development server...Starting type checking and linting service...
Using 1 worker with 2048MB memory limit 10% building modules 1/1 modules 0 activeevents.js:167
      throw er; // Unhandled 'error' event      ^
Error: ENOSPC: no space left on device, watch '/home/beary/nodeWorkSpace/test/public'
    at FSWatcher.start (internal/fs/watchers.js:164:26)    at Object.watch (fs.js:1232:11)
    at createFsWatchInstance (/home/beary/nodeWorkSpace/test/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/beary/nodeWorkSpace/test/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/beary/nodeWorkSpace/test/node_modules/chokidar/lib/nodefs-handler.js:232:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/beary/nodeWorkSpace/test/node_modules/chokidar/lib/nodefs-handler.js:414:19)    at FSWatcher.<anonymous> (/home/beary/nodeWorkSpace/test/node_modules/chokidar/lib/nodefs-handler.js:462:19)
    at FSWatcher.<anonymous> (/home/beary/nodeWorkSpace/test/node_modules/chokidar/lib/nodefs-handler.js:467:16)    at FSReqWrap.oncomplete (fs.js:155:5)
Emitted 'error' event at:
    at FSWatcher._handleError (/home/beary/nodeWorkSpace/test/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/beary/nodeWorkSpace/test/node_modules/chokidar/lib/nodefs-handler.js:39:5)
    at setFsWatchListener (/home/beary/nodeWorkSpace/test/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:155:5)
```

**Comment by beary** [comment]
I tried to use `dart-sass` according `sass-loader`'s [example](https://github.com/webpack-contrib/sass-loader#examples) and it works well.
```js
/* vue.config.js */
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        implementation: require('sass')
      }
    }
  }
}
```
```json
"devDependencies": {
  "@vue/cli-plugin-babel": "^3.0.4",
  "@vue/cli-plugin-typescript": "^3.0.4",
  "@vue/cli-service": "^3.0.4",
  "sass": "^1.14.1",
  "sass-loader": "^7.0.1",
  "typescript": "^3.0.0",
  "vue-template-compiler": "^2.5.17"
}
```
