### ISSUE TITLE
npm run build不能适配混合app相对路径"./"

### ISSUE THREAD

**Issue by lanxuebao** [vuejs/vue-cli#1784]
### Version
3.0.0-rc.3

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
修改vue.config.js中的baseUrl为'./'
module.exports = {
    baseUrl: './'
};
然后执行npm run build

### What is expected?
所有URL都应以“./”开头，成为相对路径，以便适配混合app开发。

建议一：
将node_modules\@vue\cli-service\lib\config\css.js中的`css/[name].[contenthash:8].css`
修改为`./css/[name].[contenthash:8].css`,

建议二：
将node_modules\@vue\cli-service\lib\config\prod.js中的`js/[name]${isLegacyBundle ? `-legacy` : ``}.[chunkhash:8].js`
修改为`./js/[name]${isLegacyBundle ? `-legacy` : ``}.[chunkhash:8].js`

### What is actually happening?
在混合APP开发中所有的路径都应以相对路径，或者给别人做案例时也应该以相对路径URL开头，以达到只要浏览器访问index.html就能看到内容。如果仅仅修改baseUrl为"./"或""，那么所有的编译的js和css都会生成在根目录下，很混乱。为了保证文件的可视阅读性，除index.html的文件都应该归类存储。

---
建议一：
将node_modules\@vue\cli-service\lib\config\css.js中的`css/[name].[contenthash:8].css`
修改为`./css/[name].[contenthash:8].css`,

建议二：
将node_modules\@vue\cli-service\lib\config\prod.js中的`js/[name]${isLegacyBundle ? `-legacy` : ``}.[chunkhash:8].js`
修改为`./js/[name]${isLegacyBundle ? `-legacy` : ``}.[chunkhash:8].js`

**Comment by zouhangwithsweet** [comment]
我记得之前beta10是可以的，rc3不知道为啥不行了~

**Comment by zouhangwithsweet** [comment]
如果改，configwebpack的output.publicPath的话，路由的异步组见还是有问题。

**Comment by lanxuebao** [comment]
@zouhangwithsweet

**Comment by lanxuebao** [comment]
@zouhangwithsweet 
按照我说的去修改，可以实现url都以./开头，和vue2一样的效果

**Comment by zouhangwithsweet** [comment]
我试了，但是有的写在css中的background-image会出现找不到，或者，js无法访问，而且和 assetDir 这个配置有冲突。

**Comment by lanxuebao** [comment]
@zouhangwithsweet 
加我微信www_lxb_com

**Comment by yyx990803** [comment]
想用相对路径，生成的资源，尤其是 CSS 就必须放在根目录下，否则你的 CSS 里面 url 引用路径无法正常工作。你这改得自作聪明，等到你 CSS 资源引用路径出错就明白了。

**Comment by lanxuebao** [comment]
我已经build成功了， 所有的css和js以及图片均加载正常，并且路径都是以"./"开头。
另外：2楼通过配置webpack也达到了同样的目的，我只能说你是死脑筋.....

**Comment by lanxuebao** [comment]
@yyx990803 
我已经build成功了， 所有的css和js以及图片均加载正常，并且路径都是以"./"开头，
而且文件资源来自不同的目录。

另外：2楼通过配置webpack也达到了同样的目的，我只能说你是【死脑筋】.....

**Comment by zouhangwithsweet** [comment]
我没有这个需求，我只是好奇之前为啥可以，现在不可以。哈哈哈，beta10的时候，baseURL设置为 './'的时候，不会被 解析成'/'。

**Comment by iizhangchao** [comment]
@lanxuebao  你是按照 楼主的建议 配置的webpack ？
