### ISSUE TITLE
vue-cli create a sample project, but can't run in ie

### ISSUE THREAD

**Issue by super-bobo** [vuejs/vue-cli#1789]
### Version
3.0.0-rc.3

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
npm run serve
an error in ie(SCRIPT1006: 缺少 ')')

### What is expected?
It works well in ie

### What is actually happening?
an error in ie(SCRIPT1006: 缺少 ')')
![image](https://user-images.githubusercontent.com/20234347/42441965-04a73556-839c-11e8-8e1e-9092a242fe58.png)

**Comment by sodatea** [comment]
Please provide a valid reproduction, thanks.

**Comment by revelt** [comment]
also, which IE and which Windows version are you using, @super-bobo ?

also, @super-bobo, you give JSFiddle link but your error contains Chinese characters which are not present in the code within that JSFiddle link. Please explain yourself where do those Chinese characters come (`缺少`) from?

thank you

**Comment by wandss** [comment]
Hello everyone!
Please forgive me if this shouldn't be posted here, but I'm using vue cli version 3.0.0-rc5, and just can't run my application in I.E 11.

I've tried out many unsuccessful things.
The error itself points to a SCRIPT1002 syntax error targeting the "ansi-regex" package (module).
I've already tried to set "transpileDependencies" in a "vue.config.js", thiking that "ansi-regex" is not been transpiled, but this did not solve as well.

Any suggestions?
Cheers!

**Comment by yyx990803** [comment]
Can not reproduce in latest RC8.

**Comment by w0q** [comment]
I have the same problem when running in ie11. 
> ![screen shot 2018-08-30 at 13 22 04](https://user-images.githubusercontent.com/11870513/44848620-c27e7600-ac57-11e8-92bb-3d3d0d5a1072.png)

I think the problem is related to the use of arrow function by the strip-ansi and ansi-regex libraries. Exactly the same problem in https://github.com/webpack/webpack-dev-server/issues/1278

**Comment by duanbowen** [comment]
thanks, @w0q ,it works perfect !!!
