### ISSUE TITLE
about css assert path ,two Solution(css路径的问题解决方案)

### ISSUE THREAD

**Issue by zhangbihua** [vuejs/vue-cli#179]
>  the CSS modules will be generated as Blobs, so relative paths don't work (they would be relative to > chrome:blob or chrome:devtools). In order for assets to maintain correct paths setting output.publicPath > property of webpack configuration must be set, so that absolute paths are generated.

style-loder 无法自己设置publicpath, 所以只能在ExtractTextPlugin后的css目录路径 和 webpack.base.conf做文章的，
解決的办法有两个，
 - 一个在办法是在webpack.base.conf 里设置assetsPublicPath:'/' 根目录，assetsSubDirectory: './在服务器中的相对路径/static',
config/index.js
```js
    assetsSubDirectory: 'AbsolutePath/projectPath/static',
    assetsPublicPath: '/',
```
============================
 - 还有一个是在ExtractTextPlugin,css目录路径，把脱离出来的css路径裸在项目路径，在webpack.prod.conf中设置,
```js
    // 不需要提到static/css 中
    //new ExtractTextPlugin(utils.assetsPath('css/[name].[contenthash].css')),  
    new ExtractTextPlugin('[name].[contenthash].css'),
```
config/index.js
```js
  assetsSubDirectory: 'static',
    assetsPublicPath: './',
```
============================
两种方法都可以解决css 中img问题，
============
在知道项目的绝对路径可以用一方法，
不知道项目的绝对路径可以用二方法，（只是css文件裸在youproject中)^-^

**Comment by zhangbihua** [comment]
issue,没想到--自问自答

**Comment by margox** [comment]
我正在用VueCli开发一个Electron应用，遇到了同样的问题，蛋疼至极
css文件里面通过src引入的字体文件，在编译后指向了static/icons/xxx.woff2，而正确的引用方式应该是'../icons/xxx/woff2',因为css/和icons/是staitc/下面的同级目录，只能用你提供的第二种方式来解决，找了半天没有其他的解决方案。。。。

**Comment by zhangbihua** [comment]
@margox 那你就点个赞吧

**Comment by margox** [comment]
已点赞，不过我还在继续找解决方案

**Comment by jrt324** [comment]
问题暂时可以解决，不过还是不够优雅....

**Comment by margox** [comment]
@jrt324 我后面写了个webpack的loader进行的硬替换。。。

**Comment by jrt324** [comment]
@margox 可以把代码贴出来看看吗？

**Comment by margox** [comment]
@jrt324 
在build目录下新建一个cssPathResolver.js，内容如下：
`
module.exports = function (source) {

  if (process.env.NODE_ENV === 'production') {
    return source.replace('__webpack_public_path__ + "static', '"..')
  } else {
    return source
  }

}
`
具体要替换的内容你可能得自己调整下，这个loader要用在被css引入的资源上，而不是css，例如在我的项目里是为了解决iconfont路径不对的问题，我是这样用的：
`
{
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loaders: [
          {
            loader: path.resolve(__dirname, 'cssPathResolver')
          },
          {
            loader: 'url-loader',
            query: {
              limit: 10000,
              name: utils.assetsPath('icons/[name].[hash:7].[ext]'),
            }
          }
        ]
      }
`

**Comment by jinshengwuosi** [comment]
@margox  此方案会造成在页面中img的路径一并被修改。

**Comment by jerry9926** [comment]
我用这个方法可以
1、不要在vue文件<style>里面写css，把css放进一个单独的css文件。
2、在vue文件<javascript>里面，使用require的方式引用css文件。

**Comment by surmon-china** [comment]
@margox 赞

```javascript

const meipaiConfig = require('../meipai.config')
module.exports = function (source) {
	if (process.env.NODE_ENV === 'production' && source.includes('src="/static/')) {
		return source.replace('src="/static/', `src="${meipaiConfig.cdn_url}/static/`) 
	} else {
		return source
	}
}
```

**Comment by BiYuqi** [comment]
```js
new ExtractTextPlugin({
      filename: utils.assetsPath('css/[name].[contenthash].css'),
      allChunks: false, // 官方的是true 改为false就好了
    }),
```

**Comment by stanleyxu2005** [comment]
@biyuqi 直接把css从路径里面去掉似乎就可以了
new ExtractTextPlugin({
      filename: utils.assetsPath('[name].[contenthash].css'),
      allChunks: false, // 官方的是true 改为false就好了
    }),

**Comment by HoweZhang** [comment]
请问用vue-cli3构建的项目，在data里如何使用图片路径呢
