### ISSUE TITLE
Asset URL Handling: @ alias not working when not in css module mode.

### ISSUE THREAD

**Issue by andreynazarov3** [vuejs/vue-cli#1797]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/andreynazarov3/asset-url-bug](https://github.com/andreynazarov3/asset-url-bug)

### Steps to reproduce
Create a basic project with Vue CLI. Add background: url(@/assets/logo.png); to App.vue to styles.

### What is expected?
Explected to resolve relative path to image with webpack.

### What is actually happening?
Error: Module not found: Error: Can't resolve './@/assets/logo.png' in 'C:\Users\me\Desktop\asset-url-bug\src'

---
Strange that it is working when use `module` mode.

**Comment by LinusBorg** [comment]
`background: url(~@/assets/logo.png)`

**Comment by andreynazarov3** [comment]
Thanks!

**Comment by imudin** [comment]
How to load global less file instead of importing it in every single component?

**Comment by imudin** [comment]
@LinusBorg I really need your help!

**Comment by LinusBorg** [comment]
Then you should follow the issue guidelines and ask for help on forum.vuejs.org, not on a closed issue that was something else.
