### ISSUE TITLE
import less issue

### ISSUE THREAD

**Issue by f2009** [vuejs/vue-cli#1799]
### Version
2.9.3

### Reproduction link
[https://github.com/vuejs/vue-cli/tree/v2.9.3](https://github.com/vuejs/vue-cli/tree/v2.9.3)

### Steps to reproduce
vue或者less里面import另一个less文件。
如：@import "assets/less/func.less"

### What is expected?
可以正常导入less文件。如 @import "assets/less/func.less"

### What is actually happening?
func.less
@import "assets/less/variable.less";

Error: Can't resolve 'assets/less/variable.less'

---
vue-cli@2.9.1版本都不存在这样的问题，更新到vue-cli@2.9.3后开始不能import less文件。

**Comment by yyx990803** [comment]
2.x H只负责拉模板，跟你生成的项目没有关系...
