### ISSUE TITLE
vue inspect is not returning anything

### ISSUE THREAD

**Issue by folmert** [vuejs/vue-cli#1802]
### Version
2.9.3

### Reproduction link
[https://cli.vuejs.org/guide/prototyping.html](https://cli.vuejs.org/guide/prototyping.html)

### Steps to reproduce
Just run `vue inspect --mode production`.

### What is expected?
It should return the final config.

### What is actually happening?
Nothing is returned.

---
Node version: 9.7.1.
OS: Windows 10.

**Comment by Akryum** [comment]
>2.9.3

You are using the old vue-cli.

**Comment by folmert** [comment]
But on npm 2.9.6 is listed as latest

```
λ npm view vue-cli

{ name: 'vue-cli',
  description: 'A simple CLI for scaffolding Vue.js projects.',
  'dist-tags': { latest: '2.9.6' },
  versions:      
   [ '1.0.0',    
     (...)
     '2.9.5',    
     '2.9.6' ],  
```

**Comment by Akryum** [comment]
It's the wrong package, please check https://cli.vuejs.org/guide/creating-a-project.html#installation

**Comment by folmert** [comment]
Ok, looks like I have to uninstall it first, because `npm install -g @vue/cli` didn't update it for me.

**Comment by Akryum** [comment]
> Please uninstall it and install the 3.x version
