### ISSUE TITLE
Source-maps not enabled by default 

### ISSUE THREAD

**Issue by lane-s** [vuejs/vue-cli#1806]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
1. Run vue create test-project
2. Choose default options
3. Change a `.vue` component so that the javascript code will throw an exception
4. run `npm run serve`

### What is expected?
The browser console should display the line number where the exception is being thrown in the `.vue` file

### What is actually happening?
The browser console displays an unhelpful error message referencing only `vue.runtime.esm.js`

---
When creating a new project using vue-cli via create or UI, no vue.config.js file is created by default. In order to see the line number of an exception in your source code, you have to manually create `vue.config.js` and add the following:
``` javascript
module.exports = {
    configureWebpack: {
        devtool: 'source-map'
    }
}
```
It seems to me that everyone would like to be able to source their errors, so I feel that this should be done by default.

**Comment by sodatea** [comment]
Can't reproduce.
Source maps are enabled by default in dev mode:
https://github.com/vuejs/vue-cli/blob/e17f78c6c5abb8547de8cc26d56659d846c65242/packages/%40vue/cli-service/lib/config/dev.js#L3-L5

![image](https://user-images.githubusercontent.com/3277634/42530368-922ae298-84b3-11e8-9364-3ddb2970eec4.png)

**Comment by LinusBorg** [comment]
Sourcemaps are enabled by default, but a different kind: 

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/dev.js

**Comment by LinusBorg** [comment]
What browser are you on?

**Comment by lane-s** [comment]
Chrome 67. The issue occurs consistently unless I add the config file I described.

**Comment by yyx990803** [comment]
Cannot reproduce. Working as intended in Chrome 67.

**Comment by cristianelias** [comment]
I'm having the same issue...

**Comment by motin** [comment]
Reproduced in Chrome 68. 
Adding the devtool configuration as per this issue's top post solved it. 
Happily seeing the real filenames of where errors occur now (albeit the line number corresponds to the js-compiled version of the .vue files and not the original .vue file)

**Comment by tvkit** [comment]
@lane-s  Modifying vue.config.js as you instructed works for me

My @vue/cli-service is @ 3.0.1

**Comment by tomchiverton** [comment]
No vue.config.js created here either. Latest vue-cli from npm, Linux Ubuntu 18.04 LTS.

Reopen.

**Comment by LinusBorg** [comment]
Just create one. Not every initial configuration combination requires one, so it's not necessarily created for you.

**Comment by MikeMitterer** [comment]
The right way to enable source-map

```js
module.exports = {
    configureWebpack: (config) => {
        config.devtool = 'eval'
    },
};
```

**Comment by nicooprat** [comment]
This config was pretty slow on file change, this one seems to work the same but a lot faster (we can also use the simpler object notation): 

```js
module.exports = {
  configureWebpack: {
    devtool: 'eval-source-map',
  }
}
```

Found here: https://github.com/symfony/webpack-encore/issues/214. More config for Webpack, didn't try others: https://webpack.js.org/configuration/devtool/

![image](https://user-images.githubusercontent.com/645641/61959181-2540d480-afc3-11e9-9131-f318a0548cd8.png)

*`+++ super fast, ++ fast, + pretty fast, o medium, - pretty slow, -- slow`*

**Comment by Drumstix42** [comment]
This was a huge help for me. Without `'source-map'` I wasn't able to inspect import modules during debugging without jumping through hoops. Now I can!

I do have to note that `'eval-source-map'` didn't seem to work for me. Unsure if that is the default value, but using that yielded the same results as not setting the `devtool` property.

**Comment by FoxDaxian** [comment]
@yarnball  could you resolved that?

**Comment by FoxDaxian** [comment]
@yarnball Has the problem been resolved?

**Comment by WhyNotHugo** [comment]
- The default yields no maps for my scss files, but does for my typescript files. 
- `"eval-source-map"` does not yield maps for either scss or typescript.
- `"source-map"` yields source maps for both scss and typescript.

**Comment by Obmorok070** [comment]
> Chrome 67. The issue occurs consistently unless I add the config file I described.

**Comment by ashishb** [comment]
> The right way to enable source-map
> 
> ```js
> module.exports = {
>     configureWebpack: (config) => {
>         config.devtool = 'source-map'
>     },
> };
> ```

Which file? vue.config.js? Or a different file?

**Comment by iloveitaly** [comment]
I've noticed that sourcemaps are generated for my ts/js code, but are **not** generated if I use the `--watch` option. If I add the `devtool = 'source-map'` line mentioned above, sourcemaps are generated when using `--watch`. Any ideas how to fix this issue?

**Comment by jomofrodo** [comment]
I was seeing source maps in my production build, but not in my development build. Adding the config.devtool = 'source-map' into vue.config.js has fixed it so that I am now getting source maps in both prod and development.

https://vuejs.org/v2/cookbook/debugging-in-vscode.html

**Comment by warmfire540** [comment]
not sure if ultimately fixed but we have the same exact repro as @jomofrodo 

we're going to add the fix to all of our Vue components which are all built using `vue-cli-service build --mode development`
this essentially is just setting `NODE_ENV` which according to @sodatea 's code snippet should add sourcemaps..

now we're getting them in dev too (prod was always ok) w/ the workaround
