### ISSUE TITLE
after installing a plugin from the ui, can't get back to "search" or "configuration" tabs

### ISSUE THREAD

**Issue by rclaretfx** [vuejs/vue-cli#1808]
### Version
3.0.0-rc.3

### Reproduction link
[http://localhost:8000/plugins/add](http://localhost:8000/plugins/add)

### Steps to reproduce
click "Plugins" in left sidebar.
click the "Add Plugin" button.
Search for an install a plugin (vue-cli-plugin-axios in my case).
Click the "Finish" button.
Try clicking on "Search" and "Configuration" tabs

### What is expected?
I expected to be able to get back to the "Search" tab so I could install another plugin.

### What is actually happening?
The "Search" and "Configuration" tabs seem to be disabled.

---
Refreshing the page still went back to the "Files Changed" tab, and would not allow me to click on the others.
Using the latest version of Chrome on Windows 7.

**Comment by Akryum** [comment]
This is intended. Click on Commit changes or Skip.
