### ISSUE TITLE
EACCES: permission denied error when trying to run 'npm install -g @vue/cli'

### ISSUE THREAD

**Issue by opensas** [vuejs/vue-cli#1809]
When trying to install vue-cli running `npm install -g @vue/cli` I get the following error:

```
$ npm install -g @vue/cli
Unhandled rejection Error: EACCES: permission denied, open '/home/sas/.npm/_cacache/index-v5/d6/4d/95351bd7b1c4630fa6590049d83b56ced950f5f2fd281f27e28527249cee'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sas/.npm/_logs/2018-07-11T04_26_40_866Z-debug.log
```

```
$ uname -a
Linux antergos 4.17.4-1-ARCH #1 SMP PREEMPT Tue Jul 3 15:45:09 UTC 2018 x86_64 GNU/Linux
$ node --version
v8.11.3
$ npm --version
5.6.0
$ which npm
/home/sas/devel/node/bin/npm
ls -la /home/sas/devel/
[...]
lrwxrwxrwx  1 sas users   26 jul 11 01:31 node -> opt/node-v8.11.3-linux-x64/
[...]
```

> Note: The node installation directory is symlinked with 'ln -s xxxx/node-v8.11.3-linux-x64 node'
I installed it from the linux binaries at 'https://nodejs.org/dist/v8.11.3/node-v8.11.3-linux-x64.tar.xz'

```
$ cat /home/sas/.npm/_logs/2018-07-11T04_35_02_866Z-debug.log | tail -n 5
98 silly resolveWithNewModule validate-npm-package-name@3.0.0 checking installable status
100 silly resolveWithNewModule yaml-front-matter@3.4.1 checking installable status
101 error cb() never called!
102 error This is an error with npm itself. Please report this error at:
103 error <https://github.com/npm/npm/issues>
```

> Note: I could not file the issue using 'https://new-issue.vuejs.org/?repo=vuejs/vue-cli' because I cannot install vue-cli in the first place

**Comment by opensas** [comment]
After some research I found I'm not the only one having this issue see [here](https://github.com/npm/npm/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+EACCES%3A+permission+denied)

For future reference, I could solve it running `npm cache clear --force`

**Comment by gabrielpapke** [comment]
Thank you @opensas ! It works. But, in my case, was necessary use `sudo`.

**Comment by PolymathWhiz** [comment]
sudo npm cache clear --force worked for me

**Comment by narkan** [comment]
> `sudo npm cache clear --force` worked for me

Me too - thanks!

**Comment by MEMEO-PRO** [comment]
Used `sudo npm install -g typescript` worked for me (M1 chip)
