### ISSUE TITLE
Fix the init message when init was done in same folder

### ISSUE THREAD

**Issue by chevdor** [vuejs/vue-cli#181]
### vue-cli version
2.4.0

### Steps to reproduce
- go into the folder of an existing non-vuejs project (ie projectname)
- do a `vue init` using vue-cli with whatever option (I used 'webpack').
- answer the questions and when is comes to the one asking whether to create in the current folder, pick the default: YES

### What is Expected?
The correct instructions/folder (see below).

### What is actually happening?

> To get started:
>    
>      cd projectname
>      npm install
>      npm run dev
>    
>    Documentation can be found at https://vuejs-templates.github.io/webpack

If the init is done in the 'same folder', the `cd projectname` should not be displayed.

**Comment by zigomir** [comment]
This is [webpack template](https://github.com/vuejs-templates/webpack) issue. We now support `inPlace` flag so you can provide better messages: https://github.com/vuejs/vue-cli#additional-data-available-in-metajsjson

You can open a pull request to webpack template and change this line https://github.com/vuejs-templates/webpack/blob/master/meta.json#L74 with support of `inPlace` flag ;)
