### ISSUE TITLE
Flow support

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/vue-cli#1810]
### What problem does this feature solve?
Adding [flow](https://flow.org/en/), for less advanced developers, might be tricky. There are several things to do: install npm dependencies, configure babel, configure ESlint (optional).

### What does the proposed API look like?
Flow should be available on the features selection step. It should be available only when  TypeScript is disabled (and the opposite: TypeScript should be disabled when Flow is enabled).

**Comment by andreydos** [comment]
Not a bad idea...

**Comment by Akryum** [comment]
Maybe in the next version, let's release 3.0.0 first! 😸

**Comment by LinusBorg** [comment]
I'm no sure if we should even maintain both type systems in cli core.

While we actually use flow in the vue core and router repositories, we are much in the process of switching over to typescript more and more (Vue 3 will be rewritten in TS, amongst other things), and I think our team's kowledge of typescript is much deeper with people such as @ktsn on board.

So I would even be inclined to say this should be provided by the community, and we focus on the type system that we "build" on in the future.

**Comment by sodatea** [comment]
And I don't think its a valid use case, as few "less advanced developers" would choose flow for their Vue projects...

**Comment by yyx990803** [comment]
We will not do this in core. Our typing focus will be on TS.
