### ISSUE TITLE
Lighthouse Audit fails for PWA if start_url contains any url parameters

### ISSUE THREAD

**Issue by vesper8** [vuejs/vue-cli#1813]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/vesper8/vue-cli-3-pwa-failed-service-worker](https://github.com/vesper8/vue-cli-3-pwa-failed-service-worker)

### Steps to reproduce
*1-create a brand new app from vue-cli RC3 

*2-npm run build 

*3-serve the dist folder with web server 

*4-visit the Lighthouse Audit from chrome debugger 

*5-notice the manifest's Start URL is /index.html 

*6-run audit (PWA section only) 

*7-see perfect 100 score

then

edit the manifest.json, change start_url from /index.html to /index.html?utm_source=landing&launcher=true repeats steps 2-6 above notice the score is now 91 and there's a failure from the service worker to serve the start_url

bonus: visit the start url from the manifest.json and notice that it loads just fine with the url parameters

### What is expected?
you should be able to use url parameters as part of the start_url, specially since a lot of tutorials recommend doing just that for analytics purposes

### What is actually happening?
service-worker fails to serve start_url which means that the "Add to homescreen" won't appear as a result

**Comment by vesper8** [comment]
![screenshot 2018-07-11 13 15 57](https://user-images.githubusercontent.com/816028/42566226-97cc3660-850e-11e8-9f67-21f3377c9de8.png)
![screenshot 2018-07-11 13 16 17](https://user-images.githubusercontent.com/816028/42566229-9ac49952-850e-11e8-97c0-51c14c249c1d.png)


![screenshot 2018-07-11 13 18 04](https://user-images.githubusercontent.com/816028/42566230-9ec40010-850e-11e8-9583-9cebb6701b0b.png)
![screenshot 2018-07-11 13 18 29](https://user-images.githubusercontent.com/816028/42566239-a45b9506-850e-11e8-9b14-76f9bb01d6ff.png)

**Comment by yyx990803** [comment]
This has nothing to do with Vue CLI.
