### ISSUE TITLE
[Feature Request]  Workspaces compatibility to allow shared config

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuejs/vue-cli#1815]
### What problem does this feature solve?
Hi,
Vue-cli@3.x brings a very interesting and exciting hope to shared config between projects.

A little bit of context: 
At our company we were using vue webpack template to power multiple apps that basically shared more or less the same build config. It was obviously very tedious to upgrade a config across the board at the time. We moved progressively these apps to the new vue-cli, it is now much easier to upgrade the config, but even then we would like to push it further by implementing a shared config for all projects.
Naively I thought: what about creating a submodule with a common vue.config.js (overidable in each project with a smart script) and additionally leverage yarn workspaces. BIM BAM BOUM, we could have full control of all projects in just one place!! Wouldn't it be great ?

PROBLEM:
Vue-cli service is not designed to be used with workspaces (at least I don't think so). The issue sits in the way the service is resolving plugins: https://github.com/vuejs/vue-cli/blob/8eb7fc3a972a3db2621f17e2af812ca6e8e8e889/packages/%40vue/cli-service/lib/Service.js#L125
The script runs in the right context (aka root project folder) but it resolve packages against the root package.json which does not contain any plugins (because they are in a subfolder).

### What does the proposed API look like?
One solution I can see is to be able to configure the path of the package.json from the CLI (with a flag).

I am sure this can benefit to others, so this issue can be a discussion. Any insights for achieving this ?

**Comment by AlexandreBonaventure** [comment]
Here's my project structure:

**.config/package.json (shared config)**
```js
{
  "name": "frontend-shared-config",
  "version": "1.0.0",
  "description": "Shared front end ressources",
  "private": true,
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-rc.3",
    "@vue/cli-plugin-eslint": "^3.0.0-rc.3",
    "@vue/cli-plugin-unit-jest": "^3.0.0-rc.3",
    "@vue/cli-service": "^3.0.0-beta.15",
    "@vue/eslint-config-standard": "^3.0.0-rc.3",
    "@vue/test-utils": "^1.0.0-beta.16",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^23.0.1",
    "git-revision-webpack-plugin": "^3.0.3",
    "postcss-apply": "^0.8.0",
    "postcss-preset-env": "^5.1.0",
    "postcss-smart-import": "^0.7.5",
    "workbox-webpack-plugin": "^3.3.0"
  }
}

```

**vue.config.js**
```js
const config = require('./.config/vue.config');
// for now just forward the shared config but we could write a smart script to override and merge vue.config files
module.exports = config
```
![](https://image.ibb.co/f3BwP8/Screen_Shot_2018_07_11_at_11_29_38_AM.png)

**Comment by AlexandreBonaventure** [comment]
Very nice ! Thank you !

**Comment by Akryum** [comment]
The option name changed to `vuePlugins.resolveFrom`.
