### ISSUE TITLE
Adding webpack plugins without installing webpack

### ISSUE THREAD

**Issue by truefalse10** [vuejs/vue-cli#1816]
### What problem does this feature solve?
I am currently adding any native webpack plugins by installing the webpack dependency and calling `new webpack.plugin()` in my `vue.config.js` file. Example:
```
const webpack = require('webpack');

module.exports = {
  configureWebpack: {
    plugins: [new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)],
  },
};
```
Installing and maintaining the webpack dependency kind of goes againt the idea behind vue-cli. As far as i understand the intention is to let vue-cli-service or plugins handle all the dependency management that is needed for building my application.
It would be nice if `configureWepack` could be called with an additional parameter `webpack` or some other function that lets me install native webpack plugins without having webpack installed.

### What does the proposed API look like?
```
module.exports = {
  configureWebpack: webpack => {
    plugins: [webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)],
  },
};
```

**Comment by yyx990803** [comment]
As long as you are using a package manager that does flat installs you should be able to just `require('webpack')` without explicitly listing/installing it.
