### ISSUE TITLE
compiler hooks should be support

### ISSUE THREAD

**Issue by lichnow** [vuejs/vue-cli#1817]
### What problem does this feature solve?
example,if i want to create a file named `hot` to determine if webpack in devserver proccess or has been builded,how I can do? now, i must to create a class to be webpack plugin ,and the use `compiler.hooks.afterEmit.tap` in `apply` function.then use `webpack-chain` get a pipe `config.plugin(xxx)` to do it.  this is very troublesome.so can create a api like `afterXXX` to listen `dev-server` and `build`'s `before` or `after` event?

suggest 

### What does the proposed API look like?
module.exports = {
      afterDev: config => {},
      afterBuild: config => {}
}

**Comment by yyx990803** [comment]
You can run anything in your npm scripts. This doesn't have to go through Vue CLI.

**Comment by lichnow** [comment]
@yyx990803 具体怎么弄？我想在webpack编译完毕的时候复制编译目录到其它目录。但是vue-cli里面用webpack-chain好像不行,不通过vue-cli怎么弄？

**Comment by lichnow** [comment]
@yyx990803 尝试了很多方法，只有加个匿名的webpack插件才可以，这种方式太麻烦了，看来只能在运行build后再&& 一个node脚本了。。。

**Comment by 150148313** [comment]
同问，找不到打包完成之后的回调

**Comment by 150148313** [comment]
不过有一个srcipt中命令执行完成的的回调

**Comment by 150148313** [comment]
node child_process 模块的

**Comment by 150148313** [comment]
process.on('exit', (code) => {
  console.log(`退出码: ${code}`);
});
