### ISSUE TITLE
Display a warning at least before overwriting the package.json

### ISSUE THREAD

**Issue by chevdor** [vuejs/vue-cli#182]
Currently `vue init` overwrites the package.json file without any warning.
It would be nice to warn the user or make a copy.

**Comment by zigomir** [comment]
How were you using it? If you're trying init in current dir it will ask you `Generate project in current directory?` or if you try to init into existing dir it will ask you: `Target directory exists. Continue?`.

**Comment by chevdor** [comment]
Generate project in current directory
