### ISSUE TITLE
Vue Project cloned from Repo fails on "npm run serve"

### ISSUE THREAD

**Issue by arunmettle** [vuejs/vue-cli#1823]
### Version
3.0.0-rc.3

### Reproduction link
[https://codesandbox.io/s/oop9z3lr1z](https://codesandbox.io/s/oop9z3lr1z)

### Steps to reproduce
Upload created vue project from local to github. 
Clone it back. 
navigate to the project folder via terminal/cmd
execute npm run serve 

### What is expected?
project to build and run 

### What is actually happening?
failing with below error :
console error: 

 vue-cli-service serve
'vue-cli-service' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! inthub@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the inthub@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\arunk\AppData\Roaming\npm-cache\_logs\2018-07-11T15_07_18_173Z-debug.log

npm debuglog:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle inthub@0.1.0~preserve: inthub@0.1.0
6 silly lifecycle inthub@0.1.0~preserve: no script for preserve, continuing
7 info lifecycle inthub@0.1.0~serve: inthub@0.1.0
8 verbose lifecycle inthub@0.1.0~serve: unsafe-perm in lifecycle true
9 verbose lifecycle inthub@0.1.0~serve: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Web\Vue\vueinthub\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Dart\dart-sdk\bin;C:\Program Files\nodejs\;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files\Git\cmd;C:\Program Files (x86)\OpenSSH\bin;C:\Program Files (x86)\Brackets\command;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\arunk\AppData\Local\Microsoft\WindowsApps;C:\Users\arunk\flutter\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 172.2273.8\jre64\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\arunk\AppData\Roaming\npm;C:\Users\arunk\AppData\Local\atom\bin;C:\Program Files\Heroku\bin;C:\Program Files\Git\bin;C:\Program Files (x86)\OpenSSH\bin;C:\Users\arunk\AppData\Local\GitHubDesktop\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
10 verbose lifecycle inthub@0.1.0~serve: CWD: D:\Web\Vue\vueinthub
11 silly lifecycle inthub@0.1.0~serve: Args: [ '/d /s /c', 'vue-cli-service serve' ]
12 silly lifecycle inthub@0.1.0~serve: Returned: code: 1  signal: null
13 info lifecycle inthub@0.1.0~serve: Failed to exec serve script
14 verbose stack Error: inthub@0.1.0 serve: `vue-cli-service serve`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid inthub@0.1.0
16 verbose cwd D:\Web\Vue\vueinthub
17 error Windows_NT 10.0.16299
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error inthub@0.1.0 serve: `vue-cli-service serve`
22 error Exit status 1
23 error Failed at the inthub@0.1.0 serve script 'vue-cli-service serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the inthub package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     vue-cli-service serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs inthub
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls inthub
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by LinusBorg** [comment]
How did you upload it? It sounds like you simply forgot to run `npm install`. Dependencies won't be uploaded to github usually since we `.gitignore`the `/node_modules` folder.

**Comment by arunmettle** [comment]
yep seems like a simple step got missed out in the process. Thanks for the time and replay. Much appreciated

**Comment by Jaimin-Patel30** [comment]
I also was getting same issue: I resolved it by cleaning cache of npm `npm cache clean -f` and removing package-lock.json file `rm -rf node-modules package-lock.json` and start fresh install.
