### ISSUE TITLE
Verify commit and commit generator script

### ISSUE THREAD

**Issue by Quadriphobs1** [vuejs/vue-cli#1827]
### What problem does this feature solve?
It allows users to easily create a commit message which abides by the vue-cli commit code, there is or might be a plan for this before with the logged out message on `/scripts/verifyCommitMsg.js` line 15 ` chalk.red(`  You can also use ${chalk.cyan(`npm run commit`)} to interactively generate a commit message.\n`)`.

This should provide a scrpt which allow for easily generation of the commit message

### What does the proposed API look like?
There is a package `https://www.npmjs.com/package/commitizen` which can be used to achieve this by setting simple configuration and it can easily generate the commit message and update the changelog as well for better comminucation.

**Comment by Quadriphobs1** [comment]
I have used the package before for several projects but if the approach would be allowed I could easily create a pull request for this from my own repo

**Comment by sodatea** [comment]
Feel free to create your own preset/plugin to include this feature.

IMHO it's too opinionated to include in the official Vue CLI. Most of our users may never need this feature.
