### ISSUE TITLE
Compiled and Ready hooks doesn't work

### ISSUE THREAD

**Issue by lluisd** [vuejs/vue-cli#183]
Today I've tried the vue-cli for the first time and I've being using the created, compiled and ready hooks for the Hello.vue component and it only works the Ready one. I put a console.log/alert on each hook and it only executes the created one. Then I've done the same example with vue.js and all the  hooks work.

**Comment by zigomir** [comment]
Which template have you tried? It's probably because all official templates are now Vue 2.0 which don't support all the hooks any more. See http://rc.vuejs.org/guide/migration.html#Lifecycle-Hooks
