### ISSUE TITLE
multi web component build

### ISSUE THREAD

**Issue by jgribonvald** [vuejs/vue-cli#1832]
### Version
3.0.0-beta.15

### Reproduction link
[https://github.com/GIP-RECIA/uPortal-web-components/tree/esco-content-menu/esco-content-menu](https://github.com/GIP-RECIA/uPortal-web-components/tree/esco-content-menu/esco-content-menu)

### Steps to reproduce
Deploy it into html and you will get an error with babel :
only one instance of babel-polyfill is allowed

### What is expected?
the rendering of the component

### What is actually happening?
at console :

index.js:10 Uncaught Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (index.js:10)
    at Object.201c (esco-content-menu.js?v=1531417175315:8145)
    at __webpack_require__ (bootstrap:19)
    at Module.WnQP (ActionFavorites.vue?40cb:2)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83

and without rendering

**Comment by yyx990803** [comment]
- with RC5, I no longer see the Babel polyfill error.
- With `vue-style-loader` 4.1.1 it should also fix the shadowDOM style injection error.

Then your project is left with an undefined `regeneratorRuntime`, which seems to be an issue of your `@uportal/open-id-connect` project and is not directly related to Vue CLI.

**Comment by ChristianMurphy** [comment]
Thanks @yyx990803!

**Comment by jgribonvald** [comment]
Thanks a lot @yyx990803 !
