### ISSUE TITLE
vue.config.js devServer before() arguments undefined

### ISSUE THREAD

**Issue by chasegiunta** [vuejs/vue-cli#1833]
### Version
3.0.0-rc.3

### Reproduction link
[https://webpack.js.org/configuration/dev-server/#devserver-before](https://webpack.js.org/configuration/dev-server/#devserver-before)

### Steps to reproduce
Add:
```
devServer: {
  before(app, server) {
      server.sockWrite(server.sockets, "content-changed");
  }
}
```

to `vue.config.js` file.

### What is expected?
sockWrite method on server is hit successfully

### What is actually happening?
`server` is undefined

**Comment by LinusBorg** [comment]
The webpack docs don't indicate that there is a second argument, what makes you think it should be there?

**Comment by LinusBorg** [comment]
Okay so I did some digging, it seems that the devserver indeed passes itself as the second argument, but that's undocumented:

https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L339

We can fix it here:

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/serve.js#L135-L147

**Comment by LinusBorg** [comment]
labelled as an enhancement since this devserver api is undocumented and not hence not a bug imho.

**Comment by TheJaredWilcurt** [comment]
Going from CLI 4 to CLI 5 and getting:
```
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
         - options has an unknown property 'before'. These properties are valid:
           object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }
```
Didn't see anything about `before` in the migration guide.
