### ISSUE TITLE
devServer config do not work correct on vue ui

### ISSUE THREAD

**Issue by fyAgent** [vuejs/vue-cli#1837]
### Version
3.0.0-rc.3

### Reproduction link
[https://jsfiddle.net/fyAgent/cmyjdsvf/](https://jsfiddle.net/fyAgent/cmyjdsvf/)

### Steps to reproduce
// edit vue.config.js;
module.exports = {
  assetsDir: undefined,
  baseUrl: undefined,
  outputDir: undefined,
  runtimeCompiler: undefined,
  productionSourceMap: undefined,
  parallel: undefined,
  css: undefined,
  devServer:{
    port:9000,
    host:"localhost"
  }
}
run vue ui 
run serve

### What is expected?
it will work correct when i change the configuration of devServer

### What is actually happening?
when use vue ui to start the server,it will still open at port 8080

**Comment by Akryum** [comment]
It's because in the parameters in the UI you have port set to 8080.
