### ISSUE TITLE
vue ui no longer runs after rc.4 update. Windows 10x64, Node 8.11.3

### ISSUE THREAD

**Issue by lyonsbp** [vuejs/vue-cli#1846]
### Version
3.0.0-rc.4

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
I updated `@vue/cli` from rc.2 to rc.4 Running `vue ui` no longer works, it gives the error message posted below. 

### What is expected?
vue ui will start when running `vue ui`

### What is actually happening?
I get an error "Error: Cannot find module 'read-pkg'"
PS C:\Users\Brandon> vue ui
🚀  Starting GUI...
 ERROR  Error: Cannot find module 'read-pkg'
Error: Cannot find module 'read-pkg'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Brandon\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\folders.js:5:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

---
I attempted to uninstall then reinstall the global @vue/cli package, same issue.

**Comment by SergeyMiracle** [comment]
Same with mac os

**Comment by schottey** [comment]
Exact same issue with latest macos release. Tried on node 8.11.3 and 10.11.
Manually installing read-pkg doesn’t solve the issue either.

**Comment by ndabAP** [comment]
Same applies to Linux.

**Comment by Akryum** [comment]
I didn't detect this because I have another global package that depends on `read-pkg`. :confused:

**Comment by Akryum** [comment]
As a workaround, `yarn global add read-pkg` worked for me. Also make sure to clear your browser cache.

**Comment by TUncleSan** [comment]
Same with Windows 10x64,Node v10.5.0

**Comment by schottey** [comment]
The workaround proposed by @Akryum fixed it for me!
I used `npm install -g read-pkg`
It hadn't worked previously, because I didn't clear my browser cache.
When doing that, it works!

**Comment by TUncleSan** [comment]
Because of my npm global path has a problem。After modification,it works

**Comment by TUncleSan** [comment]
Because of my npm global path has a problem. 
After modification, it works!
