### ISSUE TITLE
Short version tag not working

### ISSUE THREAD

**Issue by Sarke** [vuejs/vue-cli#185]
# vue -h

	  Usage: vue <command> [options]

	  Commands:

		init        generate a new project from a template
		list        list available official templates
		help [cmd]  display help for [cmd]

	  Options:

		-h, --help     output usage information
		-V, --version  output the version number

	# vue -v

	  error: unknown option `-v'

	# vue --version
	2.1.1

**Comment by egoist** [comment]
It's the uppercase `-V`

**Comment by Sarke** [comment]
Ah... why?

**Comment by egoist** [comment]
I also think we should use `-v` to be consistent with other cli tools.

We can omit the `program.version(pkg.version)` and use `program.option(-v, --version)` as a workaround.

**Comment by posva** [comment]
`-v` is usually reserved for verbose. It's actually quite common to have `-V` for the version
