### ISSUE TITLE
Provide baseUrl to App to use in Vue-router

### ISSUE THREAD

**Issue by infinity1975** [vuejs/vue-cli#1857]
If I use a baseUrl in vue.config.js eg. '/directory1' i also must have base: '/directory1' when setting up vue-router otherwise it will route to '/'. I want to be able to reference baseUrl in my vue app so I can have
base: baseUrl
in my vue router setup.

**Comment by Akryum** [comment]
See https://cli.vuejs.org/guide/mode-and-env.html#using-env-variables-in-client-side-code
