### ISSUE TITLE
This repo contains the most useless and silly requirements for issues

### ISSUE THREAD

**Issue by Gargo** [vuejs/vue-cli#1859]
### Version
3.0.0-rc.4

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
Just WTF? Why can't I post an issue using this useless template because it relates to vue-cli in general, not a concrete example?

### What is expected?
the new issue I created without your silly from is opened:
https://github.com/vuejs/vue-cli/issues/1858

### What is actually happening?
The issue I created without your silly from is closed. And in the same time I can't use this useless from because it requires a link to sources which is extra in my case

**Comment by blake-newman** [comment]
It may seem silly to you but we do this work for free. So by using the template issue system it makes our life easier. Please be more respectful.

**Comment by Akryum** [comment]
If you have an issue or a suggestion to improve the Issue Helper, please do so in [the correct repository](https://github.com/vuejs/vue-issue-helper/issues).

**Comment by yyx990803** [comment]
FYI, in your original issue:

- There's no mention of the version of Vue CLI you are using, and how you installed it
- No mention of the package manager or OS, Node.js version you were using
- Error messages in a language that we don't understand

And:

- You repeatedly posted issues unrelated to actual usage problems
- Your tone is very disrespectful to people who provides you free software and tries to help you in their free time.

**I'll tell you this: the issue form was created precisely to keep users like you from wasting our time**. Also, don't bother replying. You've blocked.
