### ISSUE TITLE
Need a link to "vue-issue-helper" in readme

### ISSUE THREAD

**Issue by Gargo** [vuejs/vue-cli#1860]
### Version
3.0.0-rc.4

### Reproduction link
[https://jsfiddle.net/chrisvfritz/50wL7mdz/](https://jsfiddle.net/chrisvfritz/50wL7mdz/)

### Steps to reproduce
Open any issue related to this submission form

### What is expected?
The issue is posted and then resolved. Or readme contains an explanation that such issues  are related to another repo and so shoud be posted there

### What is actually happening?
The issue closed as "not related here"

**Comment by LinusBorg** [comment]
The issue helper is linked to from within the text field that you see when writing a new issue. If you open end an issue, you already know the link and already used it. 

Where else would you need it and why? 

Or do you mean you want a link to the actual *repository* for the issue-helper?

No, we won't add a link to that in each README

**Comment by Gargo** [comment]
@LinusBorg I found a link when you mentioned it only. A link in the most bottom of the submission written with the smallest font you found. Is it user-friendly?

**Comment by LinusBorg** [comment]
Since this is a tool that is not focused on user contributions, it doesn't make sense to put the link into the middle in big letters.

So yeah, this is fine in my opinion. I still don't like your tone.
