### ISSUE TITLE
Config for crossorigin

### ISSUE THREAD

**Issue by yangmingshan** [vuejs/vue-cli#1867]
### What problem does this feature solve?
It's also a bug.

In modern build, `type="module"` script tag will be add `crossorigin="use-credentials"`. But it will be blocked if the value of the `Access-Control-Allow-Origin` header in the response is `*`.

![image](https://user-images.githubusercontent.com/13585043/42750433-c1a9ae2c-8919-11e8-877e-8d38c87ac439.png)

So, I need a way to config `crossorigin`, use it or not use it, `crossorigin="anonymous"` or `crossorigin="use-credentials"`. In both normal build and modern build (module tag and nomodule tag).

Add `crossorigin` in normal build or modern build's nomodule tag is for error report.

### What does the proposed API look like?
Mabe a field in vue.config.js?

**Comment by lincenying** [comment]
I have the same problem

**Comment by lincenying** [comment]
先手动把
node_modules/@vue/cli-service/lib/webpack/ModernModePlugin.js
里的46行和73行改了吧
