### ISSUE TITLE
Support for private npm registries.

### ISSUE THREAD

**Issue by serkanyersen** [vuejs/vue-cli#1868]
### What problem does this feature solve?
We have a custom vue-cli plugin for our companies code, which contains propriety code and we cannot publish it to NPM. We host this on Artifactory. We usually install packages with `.npmrc` files. but that file is also brought by the plugin. We need an initial way to tell vue cli where to find packages so that `vue add` command is also usable.

### What does the proposed API look like?
`vue add` command can use `--registry` flag to pass down the custom registry to either yarn or npm. That way can reduce the plugin installation to a single command

```
vue add @ourCompany/our-plugin --registry=https://artifactory.com/npm...
```
Same thing can be applied anywhere `vue-cli` interacts with `npm` or `yarn`

**Comment by sodatea** [comment]
😂Why not add the registry to `~/.npmrc`?

**Comment by serkanyersen** [comment]
> We usually install packages with .npmrc files. but that file is also brought by the plugin.

I don't want people to create this file manually, it's an unnecessary step. I would rather do the following.

```
yarn add @ourCompany/vue-cli-plugin-our-plugin --registry=https://artifactory.com/npm...
vue invoke @ourCompany/our-plugin
```

Compare 
```
echo "@ourCompany:registry = "https://artifactory.com/npm..." > .npmrc
vue add @ourCompany/our-plugin
```
to

```
vue add @ourCompany/our-plugin --registry=https://artifactory.com/npm...
```

**Comment by Akryum** [comment]
You can use `npm install` or `yarn add` to install the plugin with the necessary options, then `vue invoke`.

**Comment by serkanyersen** [comment]
yes, that's what we are doing right now. (You can see that in my previous message) I though it would be nicer to be able to tell `vue add` where to find the package and do everything in a single command and keep it more inlined with the regular usage.

This is akin to `--clone` for private repos. Vue-cli doesn't ask them to clone the repo themselves and use it locally. It's totally doable that way but there is `--clone` why not `--registry` ?

**Comment by ustbhuangyi** [comment]
@Akryum 
Although we can use  `npm install` --registry='my private registry' and then `vue invoke`. 
However,  if we use  `api.extendPackage` in our plugin and the `dependencies` is from private npm registries  will cause problems.
I hope this feature will be supported soon.
Thanks.

**Comment by markchagers** [comment]
> 😂Why not add the registry to `~/.npmrc`?
That doesn't seem to work. We have a private registry (using Verdaccio) and I can install anything from there using regular npm commands (after executing npm set registry, which adds this setting to the .npmrc file).
But when running vue ui none of our private packages are found when trying to install a dependency.
