### ISSUE TITLE
Readme file is updated after initial commit

### ISSUE THREAD

**Issue by serkanyersen** [vuejs/vue-cli#1869]
### Version
3.0.0-rc.5

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
vue create test

### What is expected?
project initializes with a clean git status

### What is actually happening?
after init, README.md file looks to be updated. Update should have happened before the initial commit.

**Comment by LinusBorg** [comment]
Please provide at least the list of options you chose...

**Comment by serkanyersen** [comment]
I selected `default (babel, eslint)`.

**Comment by yyx990803** [comment]
Looks like this was overlooked in the PR that introduced this feature (https://github.com/vuejs/vue-cli/commit/278e992)
