### ISSUE TITLE
Vue-cli creates project with runtime-only vue

### ISSUE THREAD

**Issue by gunzino** [vuejs/vue-cli#1875]
### Version
3.0.0-rc.5

### Reproduction link
[https://pastebin.com/srUKbUKC](https://pastebin.com/srUKbUKC)

### Steps to reproduce
I used vue-cli to create project with default setup. I use Babel   Lint and Vue router.

However, after build shows up that build was made with vue.runtime.esm.js without template compiler.

### What is expected?
Builder should include vue.esm.js

### What is actually happening?
Builder include vue.runtime.esm.js

**Comment by Akryum** [comment]
Read the docs? https://cli.vuejs.org/config/

**Comment by sodatea** [comment]
This is intended.
You can turn on `runtimeCompiler` option if you want to include the full build.
https://cli.vuejs.org/config/#runtimecompiler

**Comment by LuisHCK** [comment]
why this is disabled by default? This is required for development.

**Comment by Akryum** [comment]
No it's not required.

Le lun. 30 juil. 2018 à 05:53, Luis J. Centeno <notifications@github.com> a
écrit :

**Comment by aboutqx** [comment]
@Akryum what is the meaning of `open/close state`

**Comment by aboutqx** [comment]
The default example generated with vue-cli 3.0,it works without `runtimeCompiler` set to `true`,but it uses `template`, seems it shouldn't work.

**Comment by sodatea** [comment]
@aboutqx `runtimeCompiler` is for `template` option support https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only

Template blocks in single file components are already compiled by vue-loader at compile time.

**Comment by aboutqx** [comment]
Yes,i used the `template` like `template: '<App/>'`,while the generated one not.
