### ISSUE TITLE
Is there a way to specify what directory to look in for linting?

### ISSUE THREAD

**Issue by cssagogo** [vuejs/vue-cli#1884]
### What problem does this feature solve?
I posted the following question on StackOverflow...
https://stackoverflow.com/questions/51392974/how-to-change-the-lint-directory-in-a-vue-js-app

Wasn't sure if there was something that could be done in exclude? Maybe exclude everything that is not the directory I want?

exclude: !/src/vue-app,

### What does the proposed API look like?
include: '/src/vue-app',

**Comment by LinusBorg** [comment]
You can specify that in the command line, it accepts a glob.
