### ISSUE TITLE
vue-cli confilict with vue-router 

### ISSUE THREAD

**Issue by fanyer** [vuejs/vue-cli#189]
seems cannot work with vue-router 2.0

**Comment by yyx990803** [comment]
Please be more specific - which template are you using, what errors are you getting? No one can help you with a description like that.

**Comment by fanyer** [comment]
```
vue.common.js?e881:1137[Vue warn]: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option.warn @ vue.common.js?e881:1137checkComponentAttr @ vue.common.js?e881:1708checkComponent @ vue.common.js?e881:7505compileElement @ vue.common.js?e881:7300compileNode @ vue.common.js?e881:7256compileNodeList @ vue.common.js?e881:7443compileNodeList @ vue.common.js?e881:7444compileNodeList @ vue.common.js?e881:7444compileNodeList @ vue.common.js?e881:7444compile @ vue.common.js?e881:7008Vue._compile @ vue.common.js?e881:8775Vue.$mount @ vue.common.js?e881:9610(anonymous function) @ main.js?3479:50(anonymous function) @ VM5956:49(anonymous function) @ app.js:720__webpack_require__ @ app.js:556fn @ app.js:87(anonymous function) @ app.js:587__webpack_require__ @ app.js:556(anonymous function) @ app.js:579(anonymous function) @ app.js:582
vue-router.js?e71f:745[vue-router] <router-view> can only be used inside a router-enabled app.
```

vue-cli version is v2.1.0, vue router version is 0.7.13

**Comment by posva** [comment]
Did you follow the docs ? http://router.vuejs.org/en/essentials/getting-started.html
You seem to be missing the Vue.use(VueRouter) or the addition of the router to the Vue root instance

**Comment by fanyer** [comment]
@posva @yyx990803  I've used `Vue.use` 
However, seems vmy vue-cli version refered vue of v1.0.28 , and when I change it to v2.0.1 ,it works. Seems that vue toolchain is not up to time for only Evan You working leading it. As for me, there'd be a need to follow & focus the toolchain tightly.

**Comment by posva** [comment]
The cli installs a template which is what actually selects packages versions.
I'm having a lot of trouble understanding what you mean... the cli does not refer to a version of vue.
The webpack template already uses vue 2.

It looks to me that you had trouble  using the cli and instantly raised an issue here, am I wrong?

**Comment by fanyer** [comment]
@posva  for my local environment, vue-cli@2.1.0 will create a package.json with dependence of vue@1.0.28 , and the wepack tmplate use vue@2.0.1 , while vue-cli@2.4.0 do all right

**Comment by posva** [comment]
When you init a project it overrides the previous package.json file. So you need to do it the other way around: first init, then install everything you need.
You can also init in a different folder, copy the build and config files, then check with git what needs to be changed. Then merge the package.json file and check again with git. At the end you can `npm i` and then start working again
