### ISSUE TITLE
Improve NPM package search

### ISSUE THREAD

**Issue by linusg** [vuejs/vue-cli#1897]
### Version
3.0.0-rc.5

### Reproduction link
None, as this is not project specific at all.

### Steps to reproduce
- Run `vue ui` and open any project.
- Head over to "Dependencies".
- Press "+ Install dependency"
- Enter any popular package, let's say "vue-i18n".

### What is expected?
The `vue-i18n` package should be right at the top, not only because it's obviously the most downloaded of all the suggestions but also it fits exactly the search: "vue-i18n"!

### What is actually happening?
The `vue-i18n` package can be found just on **page 2**, fourth package counting from the top.

---
That seems not only inefficient (having to switch page and scroll just for installing any popular package) but also a bug. Let's do it again with "vue-i18n":

- First (on page one) is `vue-i18nt`, second is `vue-i18next2`, third `vue-i18next`.
- Then packages with an hyphen after "i18n" come: `vue-i18n-x...`, `vue-i18n-u...`, `vue-i18n-t...`, `...`, `vue-i18n-async`. Now we're already on page two.
- Next comes `vue-i18n`, finally! Followed by packages not starting with "vue-i18n" but having that *somewhere* in the name.

Looks like reversed sorting to me...

**Comment by Akryum** [comment]
This looks like an upstream issue in the Algolia npm index: https://yarnpkg.com/fr/packages?q=vue-i18n&p=1

**Comment by Akryum** [comment]
Search index settings are back up for now!

**Comment by sodatea** [comment]
The upstream issue was fixed.
