### ISSUE TITLE
No matter if I activate or deactivate the check box, a git repository is created every time a new project is created.

### ISSUE THREAD

**Issue by Okarin99** [vuejs/vue-cli#1899]
### Version
3.0.0-rc.5

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
1. Open the UI with "vue ui"
2. Create new Project
3. Deactivate Initialize git repository
4. Create Project with any options

### What is expected?
Git repository is not initialized.

### What is actually happening?
.git folder and .gitignore file are created.

**Comment by Okarin99** [comment]
Ok thank you now it's working in the ui.
But how do I not initialize a git repository with the command line.

I tried both:
```
vue create hello-world
vue create -g TestMessage hello-world
```
But in both cases the .git folder is created.
I think in the first case no .git folder should be created.

**Comment by Akryum** [comment]
CLI help: `vue create --help`

**Comment by Okarin99** [comment]
`vue create --help` outputs:
> -g, --git [message]             Force / skip git intialization, optionally specify initial commit message

As I understand, it means that when I add the -g option it initializes git. 
When I leave it out git will not be initialized.

I don't know how to initialize git without the commit message, because if I don't specify a message the app-name will be recognized as the message.

**Comment by Okarin99** [comment]
Ahh ok maybe the description should look like this:
> -g, --git <true | false | message> Force / skip git intialization, optionally specify initial commit message
