### ISSUE TITLE
npm run build命令报错

### ISSUE THREAD

**Issue by qq524007127** [vuejs/vue-cli#190]
执行npm run dev没有问题可以正常运行，当执行npm run build命令是报错信息如下：Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example

**Comment by zigomir** [comment]
Not a `vue-cli` related issue. Please open issue on a template you're using.

**Comment by yangpei425** [comment]
how to sovle this problem
