### ISSUE TITLE
Support tslint.yaml configuration file in vue-cli-service lint 

### ISSUE THREAD

**Issue by Jancat** [vuejs/vue-cli#1900]
### What problem does this feature solve?
`.yaml` configuration file is widely used.  And now it hasn't been supported by `vue-cli-service lint`, throw the error `Could not find config file at /path/to/project/tslint.json` 

### What does the proposed API look like?
vue-cli-service lint tslint.yaml

**Comment by algil** [comment]
It would also be great for `tslint.js` files

**Comment by sodatea** [comment]
Implemented in #3305
