### ISSUE TITLE
Serve: Error watching file for changes: UNKNOWN

### ISSUE THREAD

**Issue by ayush987goyal** [vuejs/vue-cli#1902]
### Version
3.0.0-rc.5

### Reproduction link
[https://github.com/vuejs/vue-cli/issues](https://github.com/vuejs/vue-cli/issues)

### Steps to reproduce
1. Create a new project using CLI.
2. Run `yarn serve`

### What is expected?
The CLI should build and serve the project

### What is actually happening?
Getting the below error:
```
yarn run v1.7.0
$ vue-cli-service serve
 INFO  Starting development server...
 10% building modules 1/1 modules 0 activeevents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: UNKNOWN
    at _errnoException (util.js:992:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1359:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ayush987goyal** [comment]
Yes. Just noticed.

**Comment by Akryum** [comment]
See: https://webpack.js.org/configuration/dev-server/#devserver-watchoptions-
