### ISSUE TITLE
vue-cli should support different NODE_ENV config for Webpack and Vue app

### ISSUE THREAD

**Issue by ouzman** [vuejs/vue-cli#1904]
### What problem does this feature solve?
I want to see warn logs of components on production build. Almost all `warn()` calls surrounded with `if (NODE_ENV !== 'production') { }`.

### What does the proposed API look like?
In `vue.config.js` 
```
{
  ..., 
  appEnv: "different",
  ...
}
```

**Comment by yyx990803** [comment]
Many dev-time warnings have a runtime performance cost. Enabling them for production pretty much defeats the purpose of the production build.

**Comment by ouzman** [comment]
In certain cases performance cost can be acceptable. This feature shouldn't affect any user if the environments are same.

**Comment by yyx990803** [comment]
You can add your own `webpack.DefinePlugin` to overwrite `NODE_ENV` for the app. We are not going to add an option for that though.

**Comment by alan-lhhy** [comment]
> though



> You can add your own `webpack.DefinePlugin` to overwrite `NODE_ENV` for the app. We are not going to add an option for that though.

The  `webpack.DefinePlugin`  doesn't seem to work in vue cli3：
In `vue.config.js`

> 
```
let config = {
   url:JSON.stringify('http://baidu.com/')
}
module.exports = {
   baseUrl: process.env.NODE_ENV === 'production' ? './' : './',
   configureWebpack:{
    plugins:[new webpack.DefinePlugin(config),]
   }
}
```
>

**Comment by alan-lhhy** [comment]
@yyx990803 
The  `webpack.DefinePlugin`  doesn't seem to work in vue cli3：
In `vue.config.js`

> 
```
let config = {
   url:JSON.stringify('http://baidu.com/')
}
module.exports = {
   baseUrl: process.env.NODE_ENV === 'production' ? './' : './',
   configureWebpack:{
    plugins:[new webpack.DefinePlugin(config),]
   }
}
```
>

**Comment by ouzman** [comment]
I solved this problem.

In `vue.config.js`:
```js

module.exports = {
    ...
    chainWebpack: config => {
        if (process.env.NODE_ENV === "production") {
            config.plugin('define')
                .tap(definitions => {
                    definitions[0] = Object.assign(definitions[0], {
                        'process.env': {
                            NODE_ENV: "'production-with-warns'"
                        }
                    });
                    return definitions
                });
        }
    },
    ...
};
```

**Comment by alan-lhhy** [comment]
@ouzman it work !!! thanks

**Comment by alan-lhhy** [comment]
@ouzman This is the official solution.
https://cli.vuejs.org/guide/mode-and-env.html#modes
