### ISSUE TITLE
Add a parameter to tell dev-server which network interface take the address from

### ISSUE THREAD

**Issue by padiazg** [vuejs/vue-cli#1905]
### What problem does this feature solve?
Under Windows and having Docker installed the dev-server takes the network address to initialize from the Docker's interface (DockerNAT), which doesn't works.

```bash
  App running at:
  - Local:   http://localhost:8082/
  - Network: http://10.0.75.1:8082/
```

### What does the proposed API look like?
Tracked the issue to ```node_modules\@vue\cli-service\lib\util\prepareURLs.js```, this line:
```javascript
// This can only return an IPv4 address
lanUrlForConfig = address.ip()
```
it's returning ```10.0.75.1``` wich is the address for ```DockerNAT```

Need to pass the interface's name to ```address.ip()```

### serve.js
node_modules\@vue\cli-service\lib\commands\serve.js

line ~18
```javascript
options: {
  '--open': `open browser on server start`,
  '--copy': `copy url to clipboard on server start`,
  '--mode': `specify env mode (default: development)`,
  '--host': `specify host (default: ${defaults.host})`,
  '--port': `specify port (default: ${defaults.port})`,
  '--interface': `specify network interface`,			// <== Added this option
  '--https': `use https (default: ${defaults.https})`
}
```
	
line ~72    
```javascript
// Add this line under the other inicializations
const networkInterface = args.interface || process.env.INTERFACE || projectDevServerOptions.interface
```

line ~74:
```javascript
const urls = prepareURLs(
	  protocol,
	  host,
	  port,
	  options.baseUrl,
	  networkInterface		// <== added this parameter
)
```

### prepareURLs.js
node_modules\@vue\cli-service\lib\util\prepareURLs.js

line ~13:
```javascript
// added parameter networkInterface
module.exports = function prepareUrls (protocol, host, port, pathname = '/', networkInterface) {
```

line ~35:
```javascript
// here finally we can especify wich network attatch to
lanUrlForConfig = address.ip(networkInterface)
```

### optionsSchema.json
node_modules\webpack-dev-server\lib\optionsSchema.json  

> Only necessary if we put ```interface``` under ```devServer``` at ```vue.config.js```, if passed as command line parameter or as environment variable you don't need this.

Add this somewhere   
```json
    "interface": {
      "description": "The interface the server attatch to.",
      "type": "string"
    },
```
To avoid webpack-dev-server complain about this:
```bash
 ERROR  WebpackDevServerOptionsValidationError: Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'interface'. These properties are valid:
```
After that, I can tell webpack from wich interface needs to obtain it's address to initialize the server
### vue.config.js
```javascript
...
devServer: {
  host: '0.0.0.0',
  port: 8082,
  interface: 'Ethernet'
}
```
### command line/package.json
```json
"scripts": {
  "serve": "vue-cli-service serve --progress --interface Ethernet",
  "build": "vue-cli-service build"
},
```

After that dev-server listens at the correct address:
```bash
App running at:
- Local:   http://localhost:8082/
- Network: http://10.9.100.111:8082/
```

**Comment by yyx990803** [comment]
Can you turn this into a PR please?

**Comment by padiazg** [comment]
Done, PR #1909

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue-cli/pull/1909#issuecomment-407440082
