### ISSUE TITLE
Jest plugin doesn't generate config, placeholder test files, or update package.json scripts

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue-cli#1906]
### Version
3.0.0-rc.5

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
1. Use vue-cli ui to add jest plugin

### What is expected?
I would expect the plugin (like the typescript one) to add the proper config file(s), modify package.json accordingly (adding a "test:unit" script), and adding placeholder Jest test files. Also, other packages related to Jest were not added (ts-jest, @types/jest, @vue/test-utils).

### What is actually happening?
None of the above happened.

**Comment by ffxsam** [comment]
Repro here: https://github.com/ffxsam/repro-jest-plugin-issue

1. Clone it
2. Run `vue ui` and add official Jest plugin
3. Proper dependencies mentioned above (@types/jest, @vue/test-utils) are not added.

In fact, an error gets thrown in my terminal:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Socket.child.stdout.on.buffer (/Users/samh/.nvm/versions/node/v8.10.0/lib/node_modules/@vue/cli/lib/util/installDeps.js:117:31)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:607:20)
```

This could be why it's failing to add the necessary packages and modify `package.json` to add the test running script.

I should point out that `vue add @vue/cli-plugin-unit-jest` works as expected. So only the Vue UI tool is failing.

**Comment by deepaksisodiya** [comment]
Yes, Same for me. using `vue ui` it is not reflecting changes.
But working well using `vue add @vue/cli-plugin-unit-jest` command
