### ISSUE TITLE
Detect if the plugin was already invoked in the project

### ISSUE THREAD

**Issue by pksunkara** [vuejs/vue-cli#1907]
### What problem does this feature solve?
Some plugins (for example: a plugin to setup a mini-framework) might want to differentiate when the plugin was run for the first time and when it isn't. Currently there's no way to do this.

### What does the proposed API look like?
We could probably do this by adding 2 hooks (#1754) but I would vote do separate them normally since some plugins might not want any common code between the 2 modes

**Comment by Akryum** [comment]
`vue add` and `vue invoke` are essentially the same commands. `vue add` just also installs the plugin.

**Comment by pksunkara** [comment]
Yes and this issue is about some plug-ins that might want to do different
things depending on whether it is the first time invocation or not

Pavan Kumar Sunkara

**Comment by yyx990803** [comment]
This is done in ba439006

**Comment by pksunkara** [comment]
@yyx990803 This hasn't been fixed. Your commit adds `invoking`, but the value of it is `true` for both `vue add` and `vue invoke`

**Comment by Akryum** [comment]
What's the problem? `vue add` runs `vue invoke` under the hood.

**Comment by pksunkara** [comment]
Yeah, so, this issue isn't fixed by that commit since there's still no way to differentiate between `vue add` and `vue invoke` programmatically.

**Comment by yyx990803** [comment]
As I understood your issue, "running for the first time" means the plugin was used as part of a preset during initial project creation, and both `vue add` and `vue invoke` are late invocations.

There's no way to tell whether a plugin has been invoked previously or not and I don't think that's something worth adding.

**Comment by pksunkara** [comment]
I would argue it is since I am working on a plugin which could use it instead of having workarounds. But hey, you are the maintainer 😄
