### ISSUE TITLE
Add jest watch-typeahead plugin 

### ISSUE THREAD

**Issue by serkanyersen** [vuejs/vue-cli#1908]
### What problem does this feature solve?
Jest lost it's typeahead mode due to some licensing problem. https://github.com/facebook/jest/issues/4931

This was a very useful feature for jest. Jest community later brought it back as a plugin https://github.com/jest-community/jest-watch-typeahead

It would be nice if vue-cli jest comes bundled with this plugin.

### What does the proposed API look like?

![jest-typeahead](https://user-images.githubusercontent.com/30582/43020390-bb692a94-8c14-11e8-86e2-5b75e34b7667.gif)

it should be as simple as installing the plugin and adding 

```
watchPlugins: [
    'jest-watch-typeahead/filename',
    'jest-watch-typeahead/testname',
],
```
in the `jest.config.js` file. 

I can provide a PR for this is you like.

**Comment by sodatea** [comment]
I think it is the time to add this plugin now that https://github.com/jest-community/jest-watch-typeahead/issues/20 is resolved.
