### ISSUE TITLE
npm run build之后，浏览器控制台Sources会有webpack文件夹，暴露了源代码

### ISSUE THREAD

**Issue by noderan** [vuejs/vue-cli#191]
![image](https://cloud.githubusercontent.com/assets/22747079/19238035/3e9bc20a-8f32-11e6-8747-54f184d6490d.png)
请问怎么去除这个webpack文件夹,使其vue源代码不被暴露出来？

**Comment by adonishong** [comment]
from Build? from Dev?

**Comment by noderan** [comment]
@adonishong npm run build

**Comment by LinusBorg** [comment]
the production build contains a sourcemap:

https://github.com/fundon/vue-admin/blob/master/build/webpack.prod.conf.js#L17

![image](https://cloud.githubusercontent.com/assets/1444526/19270858/581e31be-8fc2-11e6-8da6-01bd6cfd8921.png)

**Comment by adonishong** [comment]
@noderan run build has source-map... it is a feature, it is not a bug...

**Comment by loong-moon** [comment]
我已经关闭了productionSourceMap: false, 但还是资源中还是有webpack：//

![qq 20180706160041](https://user-images.githubusercontent.com/24216623/42367161-d1f021da-8135-11e8-844e-70d81dfe45c6.png)
