### ISSUE TITLE
How to add ssr to a vue-cli 3 project without webpack?

### ISSUE THREAD

**Issue by bachdgvn** [vuejs/vue-cli#1911]
I created my project with:
`vue create my-project`
But when my project was completed. I couldn't find the answer for "how to change my project to ssr without using webpack". 

Does anyone has a sample project or tutorial?

**Comment by EDiaos** [comment]
Hi , I write a project for cli3-ssr-project, see [here](https://github.com/EDiaos/vue-cli3-ssr-project)

**Comment by 1isten** [comment]
In project created via vue cli, you can use `configureWebpack` option ([see the doc](https://cli.vuejs.org/dev-guide/plugin-api.html#configurewebpack)) in the `vue.config.js` file to add your own webpack config during build process. With that, you can simply follow [the official ssr guide](https://ssr.vuejs.org/) to implement the vue cli project into an ssr app.

Or you can take a look at [my example repo](https://github.com/1isten/vue-cli-ssr) I just created yesterday with vue cli 4. The [first commit](https://github.com/1isten/vue-cli-ssr/commit/f251a41dbb5b9e86f9d2cf991538ab03f260ec06) is just an default setup with `vue create xxx`, the [second commit](https://github.com/1isten/vue-cli-ssr/commit/75fed43a3b2082b9c95f487bcffbfed557529930) is what I've done to implement the ssr following the official ssr guide. The `TARGET_ENV` in `package.json` scripts and the `vue.config.js` might be what you're interested.
