### ISSUE TITLE
Automatically set NODE_ENV to production when build

### ISSUE THREAD

**Issue by gluons** [vuejs/vue-cli#1912]
### What problem does this feature solve?
Currently, I have to add [cross-env](https://github.com/kentcdodds/cross-env) into `build` script every time. (`cross-env NODE_ENV=production vue-cli-service build`).  
If I don't add it, `build` script will not minify files and extract CSS. (My laptop set `NODE_ENV` to `development`.)

### What does the proposed API look like?
It should be great if **vue-cli** automatically define `NODE_ENV` to `production` when use [`vue-cli-service build`](https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-build) with `production` mode. (It's default)

**Comment by gluons** [comment]
@yyx990803 Because I use Node for development and I'm too lazy to set `NODE_ENV` in project manually. So, I set it globally. 😅

**Comment by gluons** [comment]
> Vue CLI respects existing env vars

Did you mean that `vue-cli-service build` will use `mode` to determine minimization?

But I can't make `vue-cli-service build` minimize all files for me via `vue-cli-service build` or `vue-cli-service build --mode production`.  
It alway output single `dist/app.js`

---

```powershell
Write-Host $env:NODE_ENV
> development
```

**Without `mode`:**
```
npx vue-cli-service build
> dist\app.js
```

**With `mode`:**
```
npx vue-cli-service build --mode production
> dist\app.js
```

**With [cross-env](https://github.com/kentcdodds/cross-env):**
```
npx cross-env NODE_ENV=production vue-cli-service build
> dist\js\chunk-vendors.34beec8f.js
  dist\js\app.77596ca4.js
  dist\css\app.fa853a0f.css
  dist\css\chunk-vendors.b30ce958.css
```

**Comment by Akryum** [comment]
[Relevant documentation](https://cli.vuejs.org/guide/mode-and-env.html)

**Comment by gluons** [comment]
@Akryum Thank you very much.  
That should be solution but it doesn't work. Weird 🤔

**`.env.production` (at project root):**
```
NODE_ENV=production
```

**Without `mode`:**
```
npx vue-cli-service build

dist\app.js
```

**With `mode`:**
```
npx vue-cli-service build --mode production

dist\app.js
```

**Comment by LinusBorg** [comment]
I assume you still have NODE_ENV defined globally on your system?

You can't overwrite an environment variable set on your system with one in an `.env` file. 

It's specifically designed like that so people can overwrite the other way around, which is quite often required in CI/CD environments.

**Comment by gluons** [comment]
@LinusBorg OK. It's clear. Thank you for clarification.  
I will use `cross-env` to overwrite it.

Thank very much, everyone. 🎉
