### ISSUE TITLE
Generated components do not follow vue style guide

### ISSUE THREAD

**Issue by makeupsomething** [vuejs/vue-cli#1914]
### What problem does this feature solve?
https://vuejs.org/v2/style-guide/#Single-file-component-top-level-element-order-recommended

It is recommended the order of single files component should be
```
<script>/* ... */</script>
<template>...</template>
<style>/* ... */</style>
```

But the order of the component generated is
```
<template>...</template>
<script>/* ... */</script>
<style>/* ... */</style>
```

### What does the proposed API look like?
Update the vue-cli generated components to follow the following order

```
<script>/* ... */</script>
<template>...</template>
<style>/* ... */</style>
```

**Comment by yyx990803** [comment]
Then this rule needs to be removed. I don't think that should be mandated.

/cc @chrisvfritz

**Comment by sodatea** [comment]
The recommended style is to always put `<style>` element after `<template>` & `<script>` because it is the only optional block.
`<template>` & `<script>` can be in any order as long as it is consistent.

**Comment by makeupsomething** [comment]
> <template> & <script> can be in any order as long as it is consistent

This is correct, my reading of the rule was wrong. Thank you for clearing that up!
