### ISSUE TITLE
UI i18n for Chinese not working

### ISSUE THREAD

**Issue by lincenying** [vuejs/vue-cli#1915]
### Version
3.0.0-rc.5

### Reproduction link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
执行 vue ui 后, 用中文浏览器打开, 在加载了语言文件后, 并没有切换到中文

### What is expected?
UI语言正确变成中文

### What is actually happening?
UI语言还是英文的

---
window.navigator.languages = ["zh", "zh-CN", "zh-TW", "ja"]

![image](https://user-images.githubusercontent.com/10840991/43056902-834006b0-8e71-11e8-81d9-c71239e891f2.png)
![image](https://user-images.githubusercontent.com/10840991/43056908-89884348-8e71-11e8-8a89-db8681223ad2.png)

**Comment by Akryum** [comment]
This is because the ids were changed to respect RNDN in one of the RC. https://github.com/SevenOutman/vue-cli-locale-zh needs to be updated.

**Comment by lincenying** [comment]
perfect, thks
