### ISSUE TITLE
module.id is incremented when add a new page

### ISSUE THREAD

**Issue by PanJiaChen** [vuejs/vue-cli#1916]
### Version
3.0.0-rc.5

### Reproduction link
[https://github.com/PanJiaChen/chunk-test](https://github.com/PanJiaChen/chunk-test)

### Steps to reproduce
1. npm install
2. add a new router (Don't add at the end)
3. npm run build
4. diff generated files

### What is expected?
I only added one file, so the final result should not change other `pages.xxx.js`.

### What is actually happening?
`About.vue` js file id has been changed. Caused the file `moduleId` behind it to change.

![image](https://user-images.githubusercontent.com/8121621/43062487-97132838-8e8b-11e8-92f5-00234653d4fc.png)

Every time I add a new page, it may cause the cache of other pages to become invalid.

**Comment by PanJiaChen** [comment]
webpack `records` can solved this.

**Comment by yyx990803** [comment]
The records file is only used for human inspection and not used during runtime... I don't think there really is a way to fix this in webpack at the moment, maybe you should open an issue for webpack instead.

**Comment by PanJiaChen** [comment]
[webpack 4.0 to 4.16: Did you know?](https://medium.com/webpack/webpack-4-0-to-4-16-did-you-know-71e25a57fa6b)

![image](https://user-images.githubusercontent.com/8121621/43112914-b4eda316-8f2a-11e8-8171-f14b59b0f736.png)


Maybe webpack5 will fix it. :dizzy_face:

**Comment by PanJiaChen** [comment]
Before the official release of `webpack5`, I found that `NamedChunksPlugin` can be used to solve this problem.

```js
new webpack.NamedChunksPlugin(chunk => {
  if (chunk.name) {
    return chunk.name
  }
  return Array.from(chunk.modulesIterable, m => m.id).join('_')
})
```

**Comment by yyx990803** [comment]
@PanJiaChen good find!
