### ISSUE TITLE
Dashboard Run Task Can't Use for Customize --mode

### ISSUE THREAD

**Issue by doopcl** [vuejs/vue-cli#1917]
### Version
3.0.0-rc.5

### Reproduction link
[https://codepen.io/](https://codepen.io/)

### Steps to reproduce
1,editor package.json , add new script attribute, for example " "testserve": "vue-cli-service serve --mode testserve" "
2,open vue-cli ui  ,show tasks tab
3,select testserve  task item  run task
4,see output content , you can see the task is not use --mode testserve

### What is expected?
run task use --mode testserve

### What is actually happening?
run task still use default mode

**Comment by Akryum** [comment]
This is already fixed in dev branch with a `(unset)` option in the parameters.
