### ISSUE TITLE
CLI-UI: Icon Generator

### ISSUE THREAD

**Issue by gimyboya** [vuejs/vue-cli#1918]
### What problem does this feature solve?
Having the possibility to provide a high-resolution icon and generate all the different icon resolutions for different devices to be used in both the  `manifest.json` and `index.html`

### What does the proposed API look like?
Input: a simple file picker that can point to a `png` file format and should throw a warning if the picture is not of a high enough resolution

Output: by default, it will point to `public\img\icons`.
here an example just for a getting an idea: https://www.favicon-generator.org/

**Comment by Akryum** [comment]
I think it could be a 3rd party plugin.

**Comment by yyx990803** [comment]
Yeah, image processing is going to be a big dependency and we don't want to force users who don't need this feature to download mbs of unrelated code.

**Comment by kandrejevs** [comment]
@yyx990803 it is a dev dependency and pretty much everyone rather would download few MB of dependencies than manually create 14 differently sized icons.

**Comment by alexcroox** [comment]
What did the author use to generate the files inside public/icons? I've tried various favicon generators but not one has saved out matching file name conventions or sizes yet.

**Comment by dev117uday** [comment]
I recently came across the same problem, so i create a small python script to generate icons.

[Github] https://github.com/dev117uday/learning_python/blob/master/scripts/Vuejs%20PWA%20icon%20generator.ipynb

it's not perfect, you have to do this manually, but i hope it will help any one in the future.
remember to create a folder called 'icons' where all the auto generate icons will be stored
