### ISSUE TITLE
TSLint command line and in-editor are out of sync

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue-cli#1924]
### Version
3.0.0-rc.5

### Reproduction link
[https://github.com/ffxsam/repro-tslint-sync-bug](https://github.com/ffxsam/repro-tslint-sync-bug)

### Steps to reproduce
1. Open shell
2. Open VS Code for project
3. Open HelloWorld.vue component in editor
4. Run "yarn lint"

### What is expected?
"yarn lint" output and VS Code tslint warnings/errors should be the same

### What is actually happening?
"yarn lint" displays one set of issues, and VS Code displays a different set of issues

![screenshot from 2018-07-23 12-51-35](https://user-images.githubusercontent.com/12532733/43093944-38ec98c0-8e77-11e8-9b0f-62544374bccf.png)

![screenshot from 2018-07-23 12-49-51](https://user-images.githubusercontent.com/12532733/43093887-03e4bafe-8e77-11e8-804a-8020221ba1a3.png)

**Comment by ffxsam** [comment]
Addendum: This only affects .vue files. .ts files behave as expected.

**Comment by ffxsam** [comment]
Actually, on second thought, it affects .ts files as well.

In `main.ts`, I can create the following function:

```js
function yo(something) {
  something += '!';
}
```

In VS Code, it will underline `something` in the func params and tell me I shouldn't use the implicit 'any' type (tsconfig.json strict mode is enabled), but when I run `yarn lint`:

```
yarn run v1.7.0
$ vue-cli-service lint
No lint errors found.

✨  Done in 1.02s.
```

Something is obviously not right here.

**Comment by mario-d-s** [comment]
Just for clarity, are you using **ES**Lint or **TS**Lint?

If I'm not mistaken, Vue CLI only supports ESLint via `vue-cli-plugin-eslint`. Do you have the ESLint extension installed in VSCode? And do you _not_ have the TSLint extension installed? VSCode works beautifully for me with that setup, both for `.vue` and `.ts` files.

**Comment by ffxsam** [comment]
This is TSLint. And yes, vue-cli 3 includes a [plugin](https://www.npmjs.com/package/@vue/cli-plugin-typescript) for TS support.

**Comment by yyx990803** [comment]
1. You need to use https://marketplace.visualstudio.com/items?itemName=prograhammer.tslint-vue instead of the default TSLint extension. This will make VSCode properly report the line length issue.

2. TSLint does not report type errors, it only reports stylistic errors. So there's no type error being reported when you run `yarn lint`.  The type error you are seeing in VSCode comes from the default TS integration, not from TSLint.

**Comment by mario-d-s** [comment]
@ffxsam the plugin you mention is typescript support. TSLint is a separate unofficial tool. As is ESLint which can actually lint typescript via a plugin.
