### ISSUE TITLE
Invalid options in vue.config.js: "org" is not allowed

### ISSUE THREAD

**Issue by gimyboya** [vuejs/vue-cli#1927]
### Version
3.0.0-rc.5

### Reproduction link
[https://no-link.com](https://no-link.com)

### Steps to reproduce
create a pwa application

### What is expected?
the serve command to work

### What is actually happening?
Error: Invalid options in vue.config.js: "org" is not allowed

**Comment by yyx990803** [comment]
What the error says. What makes you think org is an option?

**Comment by brocococonut** [comment]
... It may not be an option, but it's what's generated by the UI utility when creating a PWA compatible project using the interface.

**Comment by brocococonut** [comment]
From the interface of the 'Tasks' interface:
```bash
$ vue-cli-service serve --mode development --dashboard
 ERROR  Invalid options in vue.config.js: "org" is not allowed

 ERROR  Error: Process exited with code 1
Error: Process exited with code 1
    at exports.exit (.../node_modules/@vue/cli-shared-utils/lib/exit.js:7:11)
    at joi.validate.err (.../node_modules/@vue/cli-shared-utils/lib/validate.js:14:9)
    at internals.Object._validateWithOptions (.../node_modules/joi/lib/types/any/index.js:678:20)
    at module.exports.internals.Any.root.validate (.../node_modules/joi/lib/index.js:138:23)
    at exports.validate (.../node_modules/@vue/cli-shared-utils/lib/validate.js:8:7)
    at exports.validate (.../node_modules/@vue/cli-service/lib/options.js:44:3)
    at Service.loadUserOptions (.../node_modules/@vue/cli-service/lib/Service.js:317:5)
    at Service.init (.../node_modules/@vue/cli-service/lib/Service.js:72:30)
    at Service.run (.../node_modules/@vue/cli-service/lib/Service.js:188:10)
    at Object.<anonymous> (.../node_modules/@vue/cli-service/bin/vue-cli-service.js:22:9)

Total task duration: 0.41s
```

What's in the generated `vue.config.js` file after editing the PWA settings under `Configuration -> PWA`:
```javascript
module.exports = {
  org: {
    vue: {
      pwa: {
        msTileColor: '#CC00CC',
        themeColor: '#CC00CC'
      }
    }
  },

  baseUrl: undefined,
  outputDir: undefined,
  assetsDir: undefined,
  runtimeCompiler: undefined,
  productionSourceMap: undefined,
  parallel: undefined,
  css: undefined
}
```

**Comment by brocococonut** [comment]
I think this issue should be reopened

**Comment by Akryum** [comment]
Duplicate of #1890

**Comment by gimyboya** [comment]
I think this issue should be open again as this is related to the vue-cli Graphical interface.

just like @brocococonut  said when a pwa project is created via the graphical interface the `vue.config.js` will contain the following:
```
module.exports = {
  org: {
    vue: {
      pwa: {
        msTileColor: '#CC00CC',
        themeColor: '#CC00CC'
      }
    }
  }
```

then when running `npm run serve` from the graphical interface I get the error: ` ERROR  Invalid options in vue.config.js: "org" is not allowed` which was mentioned in the title and the description of the issue @yyx990803

and as #1890 solution suggest we need to delete the content of `vue.config.js` file which is not a solution in my humble opinion but rather, more or less of a hack which is needed every time a pwa is created via the graphical interface.

**Comment by Akryum** [comment]
![image](https://user-images.githubusercontent.com/2798204/43130085-20ab9b48-8f36-11e8-98fe-53fe7a43ba4a.png)
