### ISSUE TITLE
Use dynamic imports in routes config

### ISSUE THREAD

**Issue by LinusBorg** [vuejs/vue-cli#1928]
### What problem does this feature solve?
We generally recommend to use code-splitting route components when writing apps with vue-router, but the code generated by vue-cli when selecting the router feature does use static imports.

In order to make users adopt per-route code-splitting, we should demonstrate the necessary code in the generated `router.js` file

### What does the proposed API look like?
Rewriting static imports in [this file](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/generator/router/template/src/router.js) as dynamic imports.

----

I'll do a PR

**Comment by pksunkara** [comment]
@LinusBorg Mention me on PR please, am interested and will review

**Comment by yyx990803** [comment]
Done. Note I didn't make every route async because in some cases it's better to not split when the route has a high chance of being the initial view and the chunk is small.

**Comment by cybermerlin** [comment]
now this trouble is actual in latest version.
Look in https://github.com/vuejs/vue-router/issues/215#issuecomment-456791509

**Comment by cybermerlin** [comment]
fix to correct dependencies in package.json @vue/cli:

    "@babel/core": "=7.2.2",
    "@babel/generator": "=7.3.0",
    "@babel/plugin-proposal-class-properties": "=7.3.0",
    "@babel/plugin-proposal-decorators": "=7.3.0",
    "@babel/plugin-proposal-object-rest-spread": "=7.3.1",
    "@babel/plugin-syntax-dynamic-import": "=7.2.0",
    "@babel/plugin-transform-async-to-generator": "=7.2.0",
    "@babel/plugin-transform-block-scoping": "=7.2.0",
    "@babel/plugin-transform-exponentiation-operator": "=7.2.0",
    "@babel/plugin-transform-modules-commonjs": "=7.2.0",
    "@babel/plugin-transform-parameters": "=7.2.0",
    "@babel/plugin-transform-runtime": "=7.2.0",
    "@babel/preset-env": "=7.3.1",
    "babel-eslint": "=10.0.1",
    "babel-loader": "=8.0.5",
    "babel-plugin-minify-mangle-names": "=0.5.0",
    "babel-plugin-syntax-async-functions": "=6.13.0",
    "babel-plugin-syntax-trailing-function-commas": "=6.22.0",
    "babel-plugin-transform-es2015-constants": "=6.1.4",
    "babel-plugin-transform-inline-environment-variables": "=0.4.3",

OR just rever package.json to 3.1.3 version (https://github.com/vuejs/vue-cli/blob/9ab0fbde1cf87d888aa3d2c3c52176b8de464c59/packages/%40vue/cli/package.json)
