### ISSUE TITLE
Serve fails with Error Code 137

### ISSUE THREAD

**Issue by jappyjan** [vuejs/vue-cli#1929]
### Version
3.0.0-rc.5

### Reproduction link
[https://gitlab.com/JappyJan/GamePlay-V4](https://gitlab.com/JappyJan/GamePlay-V4)

### Steps to reproduce
Create a Vue-Cli 3 Project, with TS, TSLint, PWA, Router   Vuex
Fire "sudo yarn serve" (sudo because on my server (codeanywhere) "scandir" is restricted)

### What is expected?
Launching of the internal webpack live preview server

### What is actually happening?
The Server launches, but immediately dies with error code 137

---
 DONE  Compiled successfully in 43177ms 4:04:51 AM

No type errors found
No lint errors found
Version: typescript 2.8.3, tslint 5.10.0
Time: 37020ms

  App running at:
  - Local:   http://localhost:8080/
  - Network: undefined

Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
cabox@box-codeanywhere:~/workspace/GamePlay-V4$

**Comment by sodatea** [comment]
The reproduction link is broken.

It may be an memory allocation error as stated in 
 https://github.com/moby/moby/issues/21083

**Comment by jappyjan** [comment]
it's been exactly that! thanks a lot!
