### ISSUE TITLE
component is的组件第一次加载后无法触发activated事件，deactivated是可以的

### ISSUE THREAD

**Issue by lanxuebao** [vuejs/vue-cli#1931]
### Version
3.0.0-rc.5

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
`<keep-alive>`
`            <router-view>`
`                    <component :is="异步组件"></component>`
`            </router-view>`
`</keep-alive>`

const AsyncComponent = (path) => ({
    // 需要加载的组件 (应该是一个 `Promise` 对象)
    component: import('@/components'   path),
    // 异步组件加载时使用的组件
    loading: Loading,
    // 加载失败时使用的组件
    error: LoadingError,
    // 展示加载时组件的延时时间。默认值是 200 (毫秒)
    delay: 200,
    // 如果提供了超时时间且组件加载也超时了，
    // 则使用加载失败时使用的组件。默认值是：`Infinity`
    timeout: 3000
});

其中【异步组件】代码为() => AsyncComponent(path);

1.路由第一次进入时异步组件加载后异步组件无法触发activated事件
2.如果异步组件引用的方式改为import，html中改为<异步组件标签></异步组件标签>就没有以上问题

### What is expected?
不管异步组件加载方式如何，keep-alive内的任何组件都应该触发activated事件

### What is actually happening?
1.路由第一次进入时异步组件加载后异步组件无法触发activated事件
2.如果异步组件引用的方式改为import，html中改为<异步组件标签></异步组件标签>就没有以上问题

**Comment by sodatea** [comment]
1. 这个问题恐怕应该提到 Vue.js 的 issues 而不是 Vue CLI
2. 麻烦给出一个可运行的最小化复现，最好是一个 GitHub 仓库并附上重现步骤，不然的话复现成本对我们来说太大了，很难帮你定位问题……

**Comment by yyx990803** [comment]
1. 这个应该提交到 Vue core 仓库
2. 请带上重现。
