### ISSUE TITLE
Uncaught TypeError: Cannot set property 'render' of undefined, When using yarn workspaces

### ISSUE THREAD

**Issue by Simskii** [vuejs/vue-cli#1933]
### Version
3.0.0-rc.5

### Reproduction link
[https://jsfiddle.net/boilerplate/vue](https://jsfiddle.net/boilerplate/vue)

### Steps to reproduce
Build project and serve the dist folder.

### What is expected?
Bootstrap application.

### What is actually happening?
Uncaught TypeError: Cannot set property 'render' of undefined,

---
This only occurs when project is inside a yarn workspace.

**Comment by LinusBorg** [comment]
Please provide a reproduction of the actual problem. You can share a git repository that contains a created vue-cli project and configured yarn workspaces for that.

**Comment by Simskii** [comment]
I were not able to reproduce, probably something in my project causing this.
