### ISSUE TITLE
hot reload(HMR) not work when use other domain

### ISSUE THREAD

**Issue by sanderswang** [vuejs/vue-cli#1935]
### Version
3.0.0-rc.5

### Reproduction link
[http://www.baidu.com/no-url-here](http://www.baidu.com/no-url-here)

### Steps to reproduce
pls look the domain: 
``` 
http://192.168.1.113:8080/sockjs-node/info?t=1532447208549
ws://192.168.1.113:8080/sockjs-node/095/w330zyvl/websocket
http://www.dev..com/b0b2f0652cccee4c5b96.hot-update.json
``` 

when: 

*   my url is  "www.dev.com/test.htm",  and   ``` <script type="text/javascript" src="http://192.168.1.113:8080/js/pingjia4.js"></script>```  in test.htm.     
*  vue-cli-server, listen to "http://192.168.1.113:8080/"

### What is expected?
the domain is wrong

### What is actually happening?
the domain is wrong

---
sanderswang@gmail.com

**Comment by yyx990803** [comment]
Use `devServer.public` in `vue.config.js` to specify your public HMR URL:

``` js
module.exports = {
  devServer: {
    public: 'www.dev.com/test.htm'
  }
}
```

**Comment by chuanxd** [comment]
I upgrade vue-cli to 3.0.0-rc.11 was resolve this issue.

**Comment by acrolink** [comment]
@yyx990803 Thank you very much. That resolves an issue I was having.
