### ISSUE TITLE
TypeScript + Array prop type causes component type to become "corrupt"

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue-cli#1936]
### Version
3.0.0-rc.5

### Reproduction link
[https://github.com/ffxsam/repro-ts-array-prop-bug](https://github.com/ffxsam/repro-ts-array-prop-bug)

### Steps to reproduce
Clone repo and open HelloWorld.vue in VS Code (or run `yarn serve`)

### What is expected?
No TS errors

### What is actually happening?
Error: Property 'okProp' does not exist on type 'Vue'.

---
Try commenting out line 39 (fields prop def), and you'll notice the TS error go away

**Comment by Akryum** [comment]
This is an issue with Vue itself, see https://github.com/vuejs/vue/issues/6841
