### ISSUE TITLE
vue-ui do not reflect changes in package.json

### ISSUE THREAD

**Issue by David-Desmaisons** [vuejs/vue-cli#1939]
### Version
3.0.0-rc.5

### Reproduction link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
1- Create a project with vue-ui using default preset

2- Once the project is created, alter package.json changing "build": "vue-cli-service build" to "build": "vue-cli-service build --target lib"

3- Check in "project tasks" tab that the build task has been updated

4- Run the build task

### What is expected?
The task should be excecuted with option --target lib

### What is actually happening?
The task is excecuted with option --target app

![image](https://user-images.githubusercontent.com/524617/43174389-1dba5a28-8f90-11e8-9692-b8d2e634f56e.png)

**Comment by Akryum** [comment]
Currently, parameters in the UI overwrites arguments in the command.

**Comment by Akryum** [comment]
I may do something about this in the future but it's not in the immediate plans.
