### ISSUE TITLE
vue-cli-service build does not take into account modern mode when using the library target

### ISSUE THREAD

**Issue by David-Desmaisons** [vuejs/vue-cli#1940]
### Version
3.0.0-rc.5

### Reproduction link
[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce
1- Create a project with vue-ui using default preset

2- run the command "vue-cli-service build --target lib --modern"

### What is expected?
-legacy files should be generated just like when using --target app options.

### What is actually happening?
No legacy files are generated.

**Comment by yyx990803** [comment]
Modern mode only works for `--target app`. For a library, just specify the correct browserslist targets.

**Comment by David-Desmaisons** [comment]
Thanks for the quick answer. 
Did I miss something or this is already documented? If not it would be nice to add it. 
Also logging a warning when this combination of option is selected would be a nice improvement as well as not letting the user choose this combintaion in vue ui.
