### ISSUE TITLE
hot reload keep requesting localhost

### ISSUE THREAD

**Issue by jxcodetw** [vuejs/vue-cli#1942]
I use "vue create" to create a vue project
I cd to it and run "npm run serve"
![image](https://user-images.githubusercontent.com/5556203/43184192-546bf2e0-901a-11e8-9d6a-203e2bb270f4.png)
After I visit the website with other ip other than localhost
it still request for localhost sockjs to do hot reload
how can I fix this problem, making it request using another ip
![image](https://user-images.githubusercontent.com/5556203/43184251-8de4cf24-901a-11e8-94e5-23a8d51d2462.png)

**Comment by yyx990803** [comment]
Use devServer.public in our.config.js

**Comment by Humoyun** [comment]
Add this to your `vue.config.js  `

```
devServer: {
    disableHostCheck: true
  },
```
