### ISSUE TITLE
Css links on non-production builds

### ISSUE THREAD

**Issue by oh-yeah** [vuejs/vue-cli#1946]
### What problem does this feature solve?
Production and non-production builds do not produce the same styling elements.  Css links are created on production builds while inline styles are created on non-production builds.  Although this is ideal for most use cases, it can cause problems.  In our case we have a theming engine that is breaking because it is specifically looking for these css links.  In the vue cli 2.x we could fairly easily overwrite the default behavior and serve css links in non-production builds, but I've found it difficult, to say the least, to accomplish this in the the 3.0 version.

### What does the proposed API look like?
An additional config entry in the css options should do the trick for this, something like enableHotReload which is defaults to true.  Then line 25 of the [css config](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/css.js) would need to be altered to account for the new config entry.

**Comment by Akryum** [comment]
CSS extraction is disabled in development mode because it breaks HMR.

**Comment by oh-yeah** [comment]
@Akryum, can you please clarify if enabling css extraction would break all hmr or just for css changes?

**Comment by yyx990803** [comment]
What theming engine is it? Why does it need to crawl CSS links? Sounds like a big hack to me.

**Comment by oh-yeah** [comment]
Ouch!  The theming engine is home grown and was the best our team could do based on the styles provided by our vendor and direction from management.  We felt that having the theme engine perform the same in both production and non-production builds were better than having hmr for css.  I can put together a small sample project if you think that will help my case.

**Comment by oh-yeah** [comment]
Looks like it wasn't such a bad idea after all, fixed in rc-11 686ec2591a4e686e2aadf36ecf666167b7607333.  Thanks!
