### ISSUE TITLE
Bad production build when using conditional baseUrl based on environment variable 

### ISSUE THREAD

**Issue by DavidBarishev** [vuejs/vue-cli#1947]
### Version
3.0.0-rc.5

### Reproduction link
[https://github.com/DavidBarishev/vue-cli-3-bug](https://github.com/DavidBarishev/vue-cli-3-bug)

### Steps to reproduce
1. Run `npm install`
2. Run `npm run build`. This is the normal build behavior, notice the 28.29 kb Gzipped size.
3. Set `NODE_ENV` environmental variable to be `gitlab-page`, on windows using powershell   `$env:NODE_ENV = "gitlab-pages"`, on linux `export NODE_ENV="gitlab-pages"`.
4. Rerun `npm run build`, notice the 79.04 kb Gzipped

### What is expected?
Normal minified build that is prefixed using the baseUrl definition.  
Which is defined like this:
```
baseUrl: process.env.NODE_ENV === "gitlab-pages" ? "/test-prefix/" : "/"
```

### What is actually happening?
Getting a weird (In terms of structure and content),bloated non-minified (it seems) build.

---
### Normal
```
> vue-cli-service build


\  Building for production...

 DONE  Compiled successfully in 7444ms                                                                          17:09:59

  File                                 Size               Gzipped

  dist\js\chunk-vendors.af429676.js    78.17 kb           28.29 kb
  dist\js\app.e873a066.js              4.27 kb            1.59 kb
  dist\css\app.d63511e4.css            0.33 kb            0.23 kb

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 ```

### With environmental variable set
```
> vue-cli-service build


|  Building for production...

 DONE  Compiled successfully in 3932ms                                                                          17:14:09

  File           Size                          Gzipped

  dist\app.js    352.81 kb                     79.07 kb

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
```

**Comment by Akryum** [comment]
You should use an other environment variable than `NODE_ENV` for that.

**Comment by DavidBarishev** [comment]
Thanks ! I tested it and it worked.
I was following the official guide for vue cli 3, and this is what was recommended - so we need to update that: https://cli.vuejs.org/guide/deployment.html#gitlab-pages.

**Comment by Akryum** [comment]
The docs seem fine to me.

**Comment by yyx990803** [comment]
`NODE_ENV` by convention is only used for determining production vs development.

**Comment by DavidBarishev** [comment]
I finally understand now.
Thanks for the kind help !
