### ISSUE TITLE
Hot reloading doesn't work always on Windows

### ISSUE THREAD

**Issue by Pioruniasty** [vuejs/vue-cli#195]
Hi,

I have Windows 10 and i have kinda problem with Webpack and Vue. 
I made project using 

```
vue init webpack testing
```

and then run

```
npm run dev
```

and also edited few .vue files (and .js also) and nothing happen ( i mean page didn't hot reloaded and webpack stucked in cmd line). It happens cause Windows or I'm doing something wrong? I tested it few days ago on ubuntu and if i remember good  it worked fine.

**Comment by ahopkins** [comment]
I'm having the same problem on Ubuntu. It had been working. Then stopped. Then it worked again after a system restart. And again not working. Makes no sense. I have gone thru all of my running processes to kill anything that seems like it might be interfering.

**Comment by haycco** [comment]
I'm having the same problem~~

**Comment by xiaoke88** [comment]
I'm having the same problem~~

**Comment by zigomir** [comment]
Please report this to [webpack template repo](https://github.com/vuejs-templates/webpack/issues).

**Comment by breezefeng** [comment]
I'm having the same problem~~ but I can't see the solution width the problem

**Comment by ninahaack** [comment]
I'm having the same problem and I can't find a solution :(
