### ISSUE TITLE
Place JS directory in build output when Base URL use empty

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [vuejs/vue-cli#1950]
### What problem does this feature solve?
When Base URL uses empty([relative paths](https://cli.vuejs.org/config/#baseurl)), bulid output would be made not structured like below.

![image](https://user-images.githubusercontent.com/4844714/43235058-34acbbba-90ba-11e8-9485-6f0081e4a677.png)

### What does the proposed API look like?

Placing js directory under root of output directory would be elegance.

**Comment by yyx990803** [comment]
This is intended in order to ensure urls inside CSS can work properly.
