### ISSUE TITLE
Place JS directory in build output when Base URL use empty

### ISSUE THREAD

**Issue by LoveMeWithoutAll** [vuejs/vue-cli#1951]
### What problem does this feature solve?
When Base URL uses empty(relative paths), bulid output would be made not structured like below.

![image](https://user-images.githubusercontent.com/4844714/43235355-7fe59dda-90bb-11e8-99ed-c384d12779bc.png)

### What does the proposed API look like?
Placing js directory under root of output directory would be elegance.

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue-cli/issues/1950#issuecomment-407957402
