### ISSUE TITLE
vue-config.js does not stick to the rules of eslint config

### ISSUE THREAD

**Issue by rowild** [vuejs/vue-cli#1952]
### Version
3.0.0-rc.5

### Reproduction link
[https://codepen.io/rowild/pen/VBzvzr](https://codepen.io/rowild/pen/VBzvzr)

### Steps to reproduce
1. Open vue-config.js in your IDE
2. Inspect the errors caused by eslint.

### What is expected?
After a vanilla installation of a vue-cli project, I would assume, that everything works at is. So even vue.config.js should not show any problems with the eslint configuration.
Fazit: The file should not show any eslint-invoked error messages.

### What is actually happening?
The vue.config.js file shows errors, because it is not build according to the eslint rules.

---
If I add `"comma-dangle": 0` to the eslint rules, the problems disappear. But that configuration is in direct contradiction to the extended airbnb rule set, which requires trailing commas...

PS: There are problems, which cannot be produces on any of those coding platforms. Is there any chance to make that field int the "Issue Helper" form optional? You say, that you close the issue immediately, if there is a random link. But on the other hand, it really takes away much time for reporting...

**Comment by Akryum** [comment]
I cannot reproduce in a new project with babel and eslint + airbnb. The files are correctly linted after the generation. Please provide more information about what options did you choose and a project reproducing this issue in a repository.

**Comment by rowild** [comment]
@Akryum My steps:

1. Create a project via Terminal (iterm2, mac OS X 10.13.6), choosing the preset `default`. (for some reason it is configured to use `yarn`).
2. Open `vue ui` and choose `Import`
3. At `Configuration -> Vue Cli` change some settings (so the vue.config.js will be created). I added an `assets` folder and turned on `runtime compile` [my version is German, don't know how to change the language, so I hope `runtime compiler` is the proper translation])
4. Open vue-config.js in IDE: 'missing semicolon' error at end of file.

eslint is installed in project only, no global installation nor configuration.

Does this help? Would you like me to provide other info?

**Comment by Akryum** [comment]
I still can't reprroduce. The default eslint config is using `eslint:recommended` so it hasn't the `comma-dangle` rule. Also, whatever eslint config you choose when creating the project, it will be applied on generated files. I guess you must have some external configuration in your IDE that doesn't respect the eslint config in the project.
