### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found) app.c2115832.js:1 

### ISSUE THREAD

**Issue by VCodepp** [vuejs/vue-cli#1955]
I use 'vue ui' and create project . I run the build command without changing anything. When I run the index.html file from the generated dist folder, I get a few errors in the console

```
Failed to load resource: the server responded with a status of 404 (Not Found)
app.c2115832.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found)
chunk-vendors.fb29d323.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found)
app.c2115832.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found)
app.8d0d60ac.css:1 
Failed to load resource: the server responded with a status of 404 (Not Found)

```

the files are in the folder

```
dist
| - index.html
| - favicon.ico
|  css
|  | - app.8d0d60ac.css
|  js
|  | - app.c2115832.js
|  | - app.c2115832.js.map
|  | - chunk-vendors.fb29d323.js
|  | - chunk-vendors.fb29d323.js.map
|  img
|  | - logo.82b9c7a5.png
```

do I have to make extra adjustments?

**Comment by yyx990803** [comment]
You need to serve the directory over HTTP. It does not work over `file://`.

**Comment by VCodepp** [comment]
I tried using xampp localhost. the same problem

That's my url address
`'http://localhost/dist/'`

**Comment by yyx990803** [comment]
Use `baseUrl: ''` in that case.

**Comment by VCodepp** [comment]
thank so much. I used baseUrl '' and solved problem

**Comment by monsa12** [comment]
> thank so much. I used baseUrl '' and solved problem

How solve men?

**Comment by dirkteucher** [comment]
The config value is here FYI ... https://cli.vuejs.org/config/#global-cli-config ... You need to create a vue.config.js file next to the package.json in the root of the project. This is helpful to get Vue to build files that will work nicely with Cordova and Android builds.

**Comment by AurioPinto** [comment]
I solved this problem by removing the mode: "history" 
![Screenshot from 2019-10-23 19-24-14](https://user-images.githubusercontent.com/34268278/67388347-0d311f00-f5cb-11e9-8829-56b0b686297c.png)

**Comment by arfrix** [comment]
just add this line on vue.config.js
publicPath: ''

**Comment by ysndmr** [comment]
I have also same problem. 



> I solved this problem by removing the mode: "history"
> ![Screenshot from 2019-10-23 19-24-14](https://user-images.githubusercontent.com/34268278/67388347-0d311f00-f5cb-11e9-8829-56b0b686297c.png)

I also removed history and builded again but it doesnt work.

What they mean about baseUrl: ''. What does it mean? How we can configre like this.

But web site is not working on server. Css and js files 404 not found. Does anybody help me?

**Comment by eslamabdallah74** [comment]
> just add this line on vue.config.js
> publicPath: ''

where is vue.config.js ?
i don't have it

**Comment by fongziyjun16** [comment]
you have create it in you project folder

**Comment by MD7709** [comment]
sir i have create a music app using javascript all work javasrrip catch the songs folder song and show result in index html but when i upload its in github git not show my songs directry when try to see link  through song directrey
