### ISSUE TITLE
New project creation fails when selected airbnb eslint

### ISSUE THREAD

**Issue by vityas-off** [vuejs/vue-cli#1956]
### Version
3.0.0-rc.6

### Node and OS info
node v10.7.0, yarn 1.7.0, linux

### Steps to reproduce
1. vue create
2. select babel, router, linter
3. select 'ESLint   Airbnb config''
4. select 'lint on save'
5. select 'In package.json'

### What is expected?
new project created

### What is actually happening?
getting this error

```
⠋  Running completion hooks...error: Unexpected newline after '(' (function-paren-newline) at test5/src/router.js:20:30:
  18 |       // this generates a separate chunk (about.[hash].js) for this route
  19 |       // which is lazy-loaded when the route is visited.
> 20 |       component: () => import(
     |                              ^
  21 |         /* webpackChunkName: "about" */
  22 |         './views/About.vue'),
  23 |     },
```

**Comment by mauri870** [comment]
Same problem here
