### ISSUE TITLE
Uninstalling @vue/cli on Mac does not remove the actual cli in `/usr/local/lib/node_modules`

### ISSUE THREAD

**Issue by rowild** [vuejs/vue-cli#1958]
### Version
3.0.0-rc.5

### Node and OS info
Node 10.7, yarn, Mac os 10.13

### Steps to reproduce
On the Terminal:
1. npm uninstall -g -f @vue/cli
2. vue -V

### What is expected?
No vue should be found. 

### What is actually happening?
Still showing the old version.

---
In my scenario, I just wanted to update from @vue/cli rc5 to rc7. That didn't work by simply installing `npm i -g @vue/cli`, neither with `npm i -g @vue/cli@3.0.0-rc.7`. So I wanted to uninstall the current @vue/cli via `npm uninstall -g @vue/cli` in order to then reinstall it again. But that didn't work either.
It turns out that the uninstall process does not remove the alias at `/usr/local/bin/@vue` (original source: `/usr/local/lib/node_modules/@vue`).
I assume the uninstaller should handle that?
Further info, in case it is relevant: I use `Homebrew` and `oh-my-zsh`.

**Comment by rowild** [comment]
With rc.7 this seems to be fixed.

**Comment by LinusBorg** [comment]
Great, I'll close it.

**Comment by rajkeshwar** [comment]
I had the same issue. Neither npm upgrade or `npm uninstall -g @vue/cli` and `npm i -g @vue/cli` worked. Then I manually deleted `/usr/local/lib/node_modules/@vue` using `sudo rm -rf /usr/local/lib/node_modules/@vue` and then I installed `npm i -g @vue/cli`. That worked.

**Node and OS info**
Node      - v14.17.5, 
NPM       - 6.14.14
Mac OS  -  11.4
