### ISSUE TITLE
build的疑惑

### ISSUE THREAD

**Issue by wenchao-pc** [vuejs/vue-cli#196]
vue-cli生成的Vue.js2.0项目打包之后的dist目录只能放到服务器web容器的ROOT目录下才能运行吗？
怎么样修改打包配置文件 让他能放在非ROOT目录下运行呢？

**Comment by myst729** [comment]
YOUR_REPO/config/index.js

Set `build.assetsPublicPath` to a relative path: 

![image](https://cloud.githubusercontent.com/assets/519733/20128176/4d6fa74a-a681-11e6-90ab-528bf7fdffcf.png)
