### ISSUE TITLE
vue ui fails on 3.0.0-rc.7 and Win10

### ISSUE THREAD

**Issue by beatgrabe** [vuejs/vue-cli#1961]
### Version
3.0.0-rc.7

### Node and OS info
Node v8.11.3 / NPM 5.7.1 / Windows 10

### Steps to reproduce
`vue ui` fails on arbitrary projects with error:

```
ERROR  Error: EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at windowsConfigPath (C:\Users\beat.grabe\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\rcPath.js:30:35)
    at exports.getRcPath.file (C:\Users\beat.grabe\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\rcPath.js:41:3)
    at Object.<anonymous> (C:\Users\beat.grabe\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\util\db.js:18:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

### What is expected?
The vue-cli user interface will open

### What is actually happening?
The command is failing

**Comment by beatgrabe** [comment]
Running in dev mode `vue ui --dev` seems to bypass the code which is throwing the error.

**Comment by Samuell1** [comment]
I think its because it wants to read folder `.vue-cli-ui` but it should read only file.

**Comment by Akryum** [comment]
It seems it's trying to read and create the `.vue-cli-ui` folder in your `App Data` but fail for some reason, maybe it doesn't have the rights.

**Comment by beatgrabe** [comment]
What is the benefit of migrating vue config files from the homedir to the appdata dir on `win10`? I am aware of the related [Issue #1957](https://github.com/vuejs/vue-cli/issues/1957). For me it is totally fine (if it would or will work), but it is clearly missing a proper explanation, since `.npmrc` or `.bashrc` are localed in the home dir as well…

Generally speaking these are only my thoughts, but the code change apparently leads to a malfunction…

**Comment by Akryum** [comment]
cc @yyx990803

**Comment by yyx990803** [comment]
@beatgrabe good point. I don't use Windows very often so I'm not all that familiar with the conventions on Windows config files. The only upside I see is if the file is placed in `AppData/Roaming` you will be able to reuse it when you log onto another machine on the same domain. Although I'm not sure if that's a common need.

**Comment by Akryum** [comment]
@yyx990803 The migration should work with folders as well.

**Comment by yyx990803** [comment]
@Akryum I'm going to revert it because I don't see much benefit. The user who wants a different config location can use `VUE_CLI_CONFIG_PATH` anyway.
