### ISSUE TITLE
vue-cli-service test:unit / inspection fails on 3.0.0-rc.7 (typescript)

### ISSUE THREAD

**Issue by IMAMBAKS** [vuejs/vue-cli#1962]
After updating vue cli to rc.7. The testing and inspecting fails with the following message:

`Error: Cannot find module 'typescript/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)`

**Comment by yyx990803** [comment]
Please read the release notes of RC6.
