### ISSUE TITLE
Change public path in vue config, so all build files are in single folder

### ISSUE THREAD

**Issue by minkBoy** [vuejs/vue-cli#1966]
### Version
3.0.0-rc.5

### Node and OS info
Node: 8.9.0, Windows 10

### Steps to reproduce
Append   publicPath: '/Build1' in vue config and build 

### What is expected?
All build files are in /Build folder instead of dist

### What is actually happening?
Nothing, public path is being ignored

**Comment by Akryum** [comment]
`publicPath` [doesn't exist](https://cli.vuejs.org/config/)
