### ISSUE TITLE
Relative "vue.esm.js" causes "npm link"ed modules bundles additional "vue".

### ISSUE THREAD

**Issue by blackmiaool** [vuejs/vue-cli#1971]
### Version
2.9.3

### Node and OS info
Node 10.4.1/ubuntu

### Steps to reproduce
Generate a project A with vue-cli. Create a project B which depends on vue. 
Run "npm link" in proj B, run "npm link B" in proj A.

### What is expected?
B is using the "vue" module in A/node_modules

### What is actually happening?
B is using the "vue" module in B/node_modules

---
It's caused by https://github.com/vuejs/vue-cli/blob/8c4c96ef9349f7051dec334ee4169143f6cf2bd6/packages/%40vue/cli-service/lib/config/base.js#L34
which uses relative path to resolve vue module. The path means different for A and B, so the vue module is bundled twice.

Install B with "npm install B" won't cause this problem.

**Comment by blackmiaool** [comment]
Replace the relative path with `resolve('node_modules/vue/dist/vue.esm.js')` can solve the problem.

**Comment by blackmiaool** [comment]
@LinusBorg  Yeah, I use `externals` in B. But when A bundles B, A's webpack prepare a vue in B's node_modules folder for B.

The actual code location may be https://github.com/vuejs-templates/webpack/blob/f21376d6c3165a4cf6e5ae33f71b16dd47d213e3/template/build/webpack.base.conf.js#L38

B is a library.

**Comment by blackmiaool** [comment]
@LinusBorg  Reproduction:
https://github.com/blackmiaool/reproduce-issue
```bash
cd vue-form10
npm link
cd ../aaa
npm link vue-form10
npm run build
```
And the app.***.js file in the dist folder is 190KB or so.

Try to replace the line
https://github.com/blackmiaool/reproduce-issue/blob/master/aaa/build/webpack.base.conf.js#L28

with `'vue$': 'vue/dist/vue.esm.js'` which is currently used by vue-cli. And bundle the aaa again, and the app.***.js file is 270+KB now.

**Comment by blackmiaool** [comment]
@LinusBorg  Reproduction:
https://github.com/blackmiaool/reproduce-issue
```bash
cd vue-form10
npm link
cd ../aaa
npm link vue-form10
npm run build
```
And the app.***.js file in the dist folder is 190KB or so.

Try to replace the line
https://github.com/blackmiaool/reproduce-issue/blob/master/aaa/build/webpack.base.conf.js#L28

with `'vue$': 'vue/dist/vue.esm.js'` which is currently used by vue-cli. And bundle the aaa again, and the app.***.js file is 270+KB now.

**Comment by yyx990803** [comment]
This is how npm link works. It does not magically make B use the node modules in A. Prioritizing B's own node_modules is the correct behavior. Although you can fix the alias for Vue like this, you'd have to do the same for any other dependencies that are present in both A and B. This is not something that Vue CLI should be responsible for.
