### ISSUE TITLE
baseUrl not working

### ISSUE THREAD

**Issue by ademilter** [vuejs/vue-cli#1974]
### Version
3.0.0-rc.8

### Node and OS info
node 10 / npm 6.1.10 / yarn 1.7.0

### Steps to reproduce
```js
module.exports = {
  baseUrl: '/test/'
}
```
<img width="1347" alt="screen shot 2018-07-28 at 15 18 45" src="https://user-images.githubusercontent.com/187922/43356489-146e2caa-927a-11e8-8a94-d90ab904db60.png">

### What is expected?
-

### What is actually happening?
WebSocket is closed before the connection is established.

**Comment by yyx990803** [comment]
Cannot reproduce. Please provide a reproduction.

**Comment by ademilter** [comment]
### create
<img width="1034" alt="screen shot 2018-07-28 at 16 00 57" src="https://user-images.githubusercontent.com/187922/43356793-2b176a7e-9280-11e8-8f5f-3e6b2234b9d4.png">

### vue.config.js
```js
module.exports = {
  baseUrl: '/test/'
}
```

### npm run serve
<img width="1387" alt="screen shot 2018-07-28 at 16 06 08" src="https://user-images.githubusercontent.com/187922/43356807-5d66b084-9280-11e8-9783-523e797065dd.png">
