### ISSUE TITLE
Missing vue-cli binaries on Windows

### ISSUE THREAD

**Issue by moracabanas** [vuejs/vue-cli#1975]
### Version
3.0.0-rc.8

### Node and OS info
Node 10.7.0 / Yarn 1.9.2 / Windows 10

### Steps to reproduce
- Install Scoop windows package manager
- use Scoop to install nvm and yarn
- install node by nvm
- yarn global add @vue/cli 

### What is expected?
- By adding @vue/cli from yarn package manager you should be able to use vue-cli from CMD or Powershell

### What is actually happening?
- The Vue binaries are not found on youruser\node_modules\@vue\cli\bin so you cannot use vue-cli. You cannot type vue ui or any other vue-cli command because it is not recognised.

---
- All other Yarn installed packages are working fine.
- I install Yarn and nvm by Scoop windows package manager
- Then I install node by nvm

- When you are installing vue by yarn, it shows:
"vue-cli-plugin-apollo#apollo-client#graphql@^0.11.0 || ^14.0.0" doesn't satisfy found match of "graphql@0.13.2" but, inthink this warning is not related to the issue.

**Comment by moracabanas** [comment]
After some research I achieved to find the windows yarn global bin path and I found the vue binaries there, so It seems to be an actual yarn bug related to [this issue](https://github.com/yarnpkg/yarn/issues/3431#issuecomment-303399450) and you can follow the purposed temporary solution. (I don't know about external repo references)

Regards

**Comment by yyx990803** [comment]
Pretty sure there's nothing we can do in Vue CLI regarding this.
