### ISSUE TITLE
Clarify the license of example codes generated with `vue-cli create`

### ISSUE THREAD

**Issue by matiasdahl** [vuejs/vue-cli#1979]
### What problem does this feature solve?
When creating a new template using the vue-cli (v3) it would be helpful to have information about the software license for the generated example codes.

If I understand correctly, vue-cli is itself MIT licensed and outputs parts of itself when running `vue-cli create`. Thus, the templates would also be under the MIT license. (Or, does vue-cli also output code from some of its dependencies with another license?)

Having license information is useful if one initially sets up a project using `vue-cli create` and later would later like to release that project under an OSS license.

### What does the proposed API look like?
This could be implemented by adding a note to the documentation. One could also include a LICENSE file in the generated template.

**Comment by yyx990803** [comment]
Vue is used as an npm dependency and that does not affect the src code in a Vue CLI project. How to license your project is up to you.

**Comment by micgro42** [comment]
As I understand @yyx990803:
The code generated by `vue-cli` is public domain (i.e. not covered by copyright) and you are free to license your code that builds upon it in whatever way you wish.

Right?
