### ISSUE TITLE
feat: Add a switch for filename hashing

### ISSUE THREAD

**Issue by yhvicey** [vuejs/vue-cli#1981]
### What problem does this feature solve?
For server projects which needs index.html to take part in build process (like ASP.NET Razor), add this switch to avoid copying generated file to view folder.

### What does the proposed API look like?
```js
// vue.config.js
module.exports = {
    // ...
    filenameHashing: true
    // ...
}
```

**Comment by yhvicey** [comment]
PR: #1980

**Comment by yyx990803** [comment]
ce7b3945
