### ISSUE TITLE
Using Commonjs modules with vie-cli 3

### ISSUE THREAD

**Issue by purepear** [vuejs/vue-cli#1983]
### Version
3.0.0-rc.9

### Node and OS info
Node 8.11.1

### Steps to reproduce
Hi

I have a shared file used by Node and Vue

Node is still using commonjs (module.exports = ) and Vue is using ES6 modules

I just updated to cli 3 and the project is not working:

`"export 'default' (imported as 'common') was not found in...`

I believe i fixed this problem before by adding `modules: false` in .babelrc

```javascript
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": ["transform-vue-jsx", "transform-runtime"]
}
```

Do you know how and in which file (babel.config.js?) can i add `modules: false`?

### What is expected?
To work

### What is actually happening?
"export 'default' (imported as 'common') was not found in...

**Comment by LinusBorg** [comment]
Yes, babel.config.js

You pass the option to the @vue/app preset just like you passed it to the env preset before.

**Comment by purepear** [comment]
Hi @LinusBorg 
I'm not sure if this is the right place but i already created the issue.. so here is a very strange bug:

main.js
```
...
const test = require('./test')
...
```
test.js
``` javascript
// This works
module.exports = {
  a: function () {
    return 'a'
  }
}

// This works
module.exports = {
  a: function (num) {
    return String(num)
  }
}

// This does NOT work
// Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
module.exports = {
  a: function (num) {
    return num.toString()
  }
}

```

The error is the browser console (runtime)... no error while compiling
