### ISSUE TITLE
Make class-style components a "N" default, not "Y"

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue-cli#1989]
### What problem does this feature solve?
This is pretty subjective, but I think the default answer for class-based components when using TypeScript should be "no." I've discussed this with a few other devs in the Vue community who agree, and since Vue 3.0 won't be using classes either, I don't see the point. The syntax is more confusing, and there is less educational material out there for that format as opposed to the standard functional format.

**Comment by yyx990803** [comment]
This is subjective indeed, I'm afraid there's not sufficient data to back this up, so I'm inclined to leave it as-is.

**Comment by ffxsam** [comment]
@yyx990803 One could argue the initial decision was subjective, as well, no? So if that's the case, why the resistance to change it? Or is there some sort of rationale behind it?

**Comment by yyx990803** [comment]
Because from my impressions on Vue + TS users, a decent amount of them use the class-based syntax. This is not an objective improvement, so we can't just change it because **a few** users want it, we need more concrete data showing more TS users actually prefer the non-class-based syntax.

**Comment by ffxsam** [comment]
And my follow-up question to that is: are people using class-based syntax _because_ of [this section](https://vuejs.org/v2/guide/typescript.html) of the Vue guide? Or is that part of the Vue guide written that way because devs were already using class-based syntax with Vue+TS?

I ask out of curiosity. I'm trying to learn more about where this OOP style of Vue came from and why. Most of the learning materials out there use the functional/imperative style, which theoretically would make it hard for people new to Vue to follow along and learn if they're using classes. I'm on the #typescript channel on Discord, and some people don't realize they have other options and don't _have_ to use class style.

**Comment by yyx990803** [comment]
Because TS being a heavily OOP-influenced language, it performs type inference better on class-based codebases. In fact, TS type inference for the non-class-based API landed much later than the class-based version. Many TS users prefers the class-based API simply because their mental model is better tuned for classes when it comes to reasoning about types. It is relatively less common for someone to willingly opt-into TS and yet actively avoid classes.

**Comment by ffxsam** [comment]
Great, thanks for the detailed reply!
