### ISSUE TITLE
Unable to re-export imported interfaces

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue-cli#1990]
### Version
3.0.0-rc.9

### Node and OS info
Node 8.10.0, Yarn 1.7.0, macOS 10.13.6

### Steps to reproduce
Reproduction: https://github.com/ffxsam/repro-reexport-warning

Export an interface from file A, import it into file B, then re-export it from file B.

### What is expected?
It should work with no warnings or errors.

### What is actually happening?
Warnings are thrown.

**Comment by yyx990803** [comment]
You are exporting `Thing` - this is using it in a non-type-annotation position and thus cause it to be kept in emitted code - and causes webpack to attempt to look it up.

This has nothing to do with Vue CLI.

**Comment by ffxsam** [comment]
@yyx990803 I've searched far & wide on how to import an interface and re-export is, and found nothing. I assumed it was a Vue CLI issue since VS Code shows no warnings, and there are no TypeScript errors or TSLint issues either.

What is the correct way to import/re-export interfaces and types?

**Comment by yyx990803** [comment]
If you export an interface **but not use it**, TypeScript cannot safely remove the interface from emitted code.

Exporting it from `main.ts` doesn't make sense because you are not shipping raw TS.

**Comment by ffxsam** [comment]
I found the case in which this breaks down. It's when you also export/import defaults.

I've updated the repo, give it a look. AFAIK, all this syntax is legitimate. I'm trying to figure out where things are falling apart.

**Comment by ffxsam** [comment]
You're right, once I didn't export from `main.ts`, it's fine.

But then I don't understand why this code (my actual code) fails:

```
 warning  in ./src/store/index.ts

"export 'AuthState' was not found in './modules/auth'
```

### src/store/modules/auth/index.ts
```ts
export interface AuthState {
  email: string | null;
  firstName: string | null;
  lastName: string | null;
  loggingIn: boolean;
  loggingOut: boolean;
  orgId: number | null;
  orgName: string | null;
  refreshToken: string | null;
  token: string | null;
  userId: string | null;
  [key: string]: any;
}
// ...
export default module;
```

### src/store/index.ts
```ts
import auth, { AuthState } from './modules/auth';
// ...
export { AuthState };
export default store;
```

### src/views/TagList.vue
```vue
<script lang="ts">
import Vue from 'vue';
import { AuthState } from '@/store';
// ...
```

**Comment by ffxsam** [comment]
@yyx990803 There are some serious bugs in Vue + TypeScript. Here's another one:

https://stackoverflow.com/questions/51661909/how-to-get-unit-tests-in-vue-to-stop-going-up-the-import-hierarchy

There's a reproduction repo in there. Try it out, and you'll see that the thrown Jest error makes no sense. I created a plain JS project and used the exact same code (minus the TS annotations of course), and the test ran fine.

I have a feeling this is an edge case, related to this issue with re-importing types. It may not be the Vue CLI, but it is definitely Vue + TypeScript.

**Comment by sodatea** [comment]
@ffxsam 
See https://github.com/vuejs/vue-cli/issues/1895
Fixed in https://github.com/vuejs/vue-cli/commit/a352bdc4dae0032bcfd1f313097e73053e737d24
Shipped in rc.6.
Please update your `tsconfig.json`

**Comment by ffxsam** [comment]
@sodatea Thank you, that fixed it!

**Comment by ffxsam** [comment]
@sodatea Though, changing this setting introduced new errors:

```
ERROR in /Volumes/SuperData/Sites/onspot/onspot-v2-ui/src/store/modules/settings/maintenance.ts
1:8 Module '"/Volumes/SuperData/Sites/onspot/onspot-v2-ui/node_modules/moment/moment"' has no default export.
  > 1 | import moment from 'moment';
```

Synthetic imports was addressing this. Do I now have to do `import * as moment` everywhere in my codebase?

**Comment by ffxsam** [comment]
`import * as moment from 'moment'` also fails:

```
A namespace-style import cannot be called or constructed, and will cause a failure at runtime.
```

**Comment by sodatea** [comment]
@ffxsam 
That's weird.
Per the [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/compiler-options.html), turning on `esModuleInterop` will automatically enable `allowSyntheticDefaultImports` for type system compatibility.
But this issue does get fixed by re-enable this option…

**Comment by ffxsam** [comment]
@sodatea I just submitted a new issue: https://github.com/vuejs/vue-cli/issues/2062

**Comment by ffxsam** [comment]
It was a bug in the TS documentation: https://github.com/Microsoft/TypeScript-Handbook/commit/8e974c814d44381ed05a3b6203894e0f9e39d552

So `allowSyntheticDefaultImports` must remain `true` in the TS template tsconfig.json.
