### ISSUE TITLE
 Warning Message on Installation

### ISSUE THREAD

**Issue by leonardo-sj** [vuejs/vue-cli#1991]
### Version
3.0.0-rc.10

### Node and OS info
Node 8.11.3 / Npm 5.6.0 / Mac OSX High Sierra 10.13.6

### Steps to reproduce
Just install the package:
sudo npm install -g @vue/cli

### What is expected?
Installation without any warning messages.

### What is actually happening?
The warning message below is shown.

npm WARN apollo-client@2.3.7 requires a peer of graphql@^0.11.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by yyx990803** [comment]
Some packages specify their peer deps but we need to use them as a nested dependency when we know the peer dep is available higher in the tree. You can safely ignore it.

**Comment by yyx990803** [comment]
Nvm, this seems to be coming from https://github.com/Akryum/vue-cli-plugin-apollo

/cc @Akryum

**Comment by Akryum** [comment]
https://github.com/apollographql/apollo-client/issues/3737
