### ISSUE TITLE
the module ,apollo-client included by @vue/cli will warning.

### ISSUE THREAD

**Issue by djangozhou** [vuejs/vue-cli#1992]
### Version
3.0.0-rc.10

### Node and OS info
Node 8.11.3/ npm 6.2.0/OS 10.13.6

### Steps to reproduce
after run  'npm i @vue/cli@3.0.0-rc.10 -g',
run  'npm ls -g --depth==0',

### What is expected?
no warning

### What is actually happening?
run 'npm i -g graphql@14.0.0-rc.2'.

it's doesn't work

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue-cli/issues/1991#issuecomment-409057682
