### ISSUE TITLE
vue-cli will remain in the building state without displaying the compilation results when you  have more than 5 page entries(in my computer)

### ISSUE THREAD

**Issue by crown3** [vuejs/vue-cli#1996]
### Version
3.0.0-rc.10

### Node and OS info
Node 8.9.4 / yarn 1.7.0 / Windows 10

### Steps to reproduce
If you have more than 5 page entries, vue-cli will remain in the building state without displaying the compilation results.

Such as this in your `vue.config.js`:
```js
module.exports = {
    pages: {
        index1: 'src/index1.js',
        index2: 'src/index2.js',
        index3: 'src/index3.js',
        index4: 'src/index4.js',
        index5: 'src/index5.js',
        index6: 'src/index6.js',
    },
}
```

Each of `index*.js` has similar code, such as
```js
import Vue from 'vue'
import App from './Test.vue'

Vue.config.productionTip = false

new Vue({
    render: h => h(App),
}).$mount('#app')
```

```js
// Test.vue
<template>
  <div class="test">
    <h1>This is an testpage</h1>
  </div>
</template>
```

### What is expected?
Continue to compile...

### What is actually happening?
It will remain in the building state without displaying the compilation results

**Comment by crown3** [comment]
I did the same test on my mac and I encountered the same problem.

Node 8.11.2 / yarn 1.7.0 / Mac 10.13.6

**Comment by crown3** [comment]
[code.zip](https://github.com/vuejs/vue-cli/files/2244835/code.zip)
like this ... @LinusBorg

**Comment by LinusBorg** [comment]
A github repository would be easier, but a zip might do

**Comment by crown3** [comment]
Ok, next time I will... But can you reproduce my problem?

**Comment by yyx990803** [comment]
I think this may be a webpack issue, or a combination of multiple html-webpack-plugins...

**Comment by crown3** [comment]
@yyx990803 You are right, it seems to be the `webpack`'s bug...
I remember that I was able to use it normally in the `beta.15` version, so I checked the dependency of `@vue/cli-service` (mainly `webpack` & `html-webpack-plugins`), you used `webpack@4.8.2` in `rc3`, then you switch to `webpack@4.15.1`. This is the cause of this problem ...
When I switch back to the `rc3` version, the above build is working fine.

**Comment by murilobd** [comment]
I am running rc12 and switched to rc3 and 3.0.1 but didn't fix my issue!

Any other idea what I could do?

**Comment by sodatea** [comment]
It's a regression introduced in https://github.com/vuejs/vue-cli/commit/4b5a63441b385d5d7f9b92cf5ed4d61d4eae39c9

**Comment by sodatea** [comment]
For now, a workaround is to disable `named-chunks` plugin in `vue.config.js`:

```js
module.exports = {
  // ...
  chainWebpack: config => config.plugins.delete('named-chunks')
}
```
