### ISSUE TITLE
Error when using umd library in vue-cli3 project: Cannot redefine property: $router

### ISSUE THREAD

**Issue by mqhe2007** [vuejs/vue-cli#1997]
### Version
3.0.0-rc.10

### Node and OS info
node v8.11.2

### Steps to reproduce
example:
https://github.com/mqhe2007/vue-remote-module

Take the above project as an example:
1. yarn build(vue-cli-service build --target lib src/main.js)
2. Get umd.js in the dist folder
3. Use umd.js in another vue-cli3.0 project

### What is expected?
Get the exported window.yourLib.default correctly

### What is actually happening?
The console reports an error: Cannot redefine property: $router

---
When using vue-cli2.x and vue-loader13 to build the project, configure the vue-loader option esModule: false. The exported lib.js can be loaded normally by other projects.

What should I do when using vue-cli3 and vue-loader15?

**Comment by yyx990803** [comment]
You need to externalize Router and Vuex from your library. https://webpack.js.org/configuration/externals/#src/components/Sidebar/Sidebar.jsx
