### ISSUE TITLE
npm install error with chromedriver

### ISSUE THREAD

**Issue by zeng1990java** [vuejs/vue-cli#200]
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/zxb/.nvm/versions/node/v6.8.1/bin/node" "/Users/zxb/.nvm/versions/node/v6.8.1/bin/npm" "install"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.24.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@2.24.1 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zxb/Desktop/work/javascript-lean/vue-lean/simple/npm-debug.log

**Comment by posva** [comment]
Which template were you using. Tested with webpack template and everything worked well

**Comment by zeng1990java** [comment]
I am using the webpack template

**Comment by zeng1990java** [comment]
i am try the webpack-simple template and is ok.

**Comment by agusmba** [comment]
Hi,

I'm trying the webpack template, and I get the same error.

Running in an Ubuntu virtual box (vagrant under windows)

**Comment by meritozh** [comment]
me too
