### ISSUE TITLE
Jest failing to run tests "unexpected token"

### ISSUE THREAD

**Issue by gimyboya** [vuejs/vue-cli#2000]
### Version
3.0.0-rc.10

### Node and OS info
Node 10.5.0 || 8.11.3 / yarn 1.6.0 / npm 6.1.0 ||  5.6.0 / Windows 10

### Steps to reproduce
to reproduce this error you can clone [this repo](https://github.com/luxtagofficial/Catapult-Vue).

### What is expected?
Test to pass

### What is actually happening?
Test are failing with the following error:

```
tests/unit/HelloWorld.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    SyntaxError: Unexpected token ] in JSON at position 634
        at JSON.parse (<anonymous>)

      at parse (node_modules/tsconfig/src/tsconfig.ts:195:15)
      at readFileSync (node_modules/tsconfig/src/tsconfig.ts:181:10)
      at Object.loadSync (node_modules/tsconfig/src/tsconfig.ts:151:18)
      at loadTypescriptConfig (node_modules/vue-jest/lib/load-typescript-config.js:39:41)
      at compileTypescript (node_modules/vue-jest/lib/compilers/typescript-compiler.js:9:20)
      at processScript (node_modules/vue-jest/lib/process.js:22:12)
      at Object.module.exports [as process] (node_modules/vue-jest/lib/process.js:41:18)
```

---
This error is not consistent in the sense that sometimes instead of this portion of the error:
```
SyntaxError: Unexpected token ] in JSON at position 634
        at JSON.parse (<anonymous>)
```
I get a syntax error about a `core-js` import statement

My guess is that there is some problem with transpilation but I can't figure out how to fix it.

another thing is that I have created a fresh new repo from `vue-ui` where the tests where passing then copied my `src` my `tslint.config` and `tsconfig` where the test was passing perfectly. then the moment I migrated the `jest.config` file I got the same error but the mind-blowing thing is that I tried to revert the changes back and kept getting the same error.

**Comment by fourteenmeister** [comment]
I confirm the problem. The truth is I have a slightly different error.

```javascript
$ node --inspect-brk ./node_modules/.bin/vue-cli-service test:unit
Debugger listening on ws://127.0.0.1:9229/170adada-3120-4d04-97e9-2881670ea58e
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
D:\Projects\test2\node_modules\.bin\vue-cli-service:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:613:28)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
Waiting for the debugger to disconnect...
```

**Comment by sodatea** [comment]
The first error is fixed in rc.6, if your config file is generated by rc.5, please try update it.
https://github.com/vuejs/vue-cli/commit/a352bdc4dae0032bcfd1f313097e73053e737d24

The second error is due to an extraneous comma in your `tsconfig.json`
https://github.com/luxtagofficial/Catapult-Vue/blob/e107e35c68c0593f0cb9ddc5d4b6798dd413e2f8/tsconfig.json#L34

**Comment by sodatea** [comment]
@fourteenmeister it is not the same problem, please open a new issue to report.

**Comment by XmlmXmlmX** [comment]
@fourteenmeister I [found no issue](https://github.com/vuejs/vue-cli/issues/created_by/fourteenmeister) regarding your (and my) problem. Have you a solution?

**Comment by Niedzwiedzw** [comment]
same problem, same setup

**Comment by ux-engineer** [comment]
> The first error is fixed in rc.6, if your config file is generated by rc.5, please try update it.
> [a352bdc](https://github.com/vuejs/vue-cli/commit/a352bdc4dae0032bcfd1f313097e73053e737d24)
> 
> The second error is due to an extraneous comma in your `tsconfig.json`
> https://github.com/luxtagofficial/Catapult-Vue/blob/e107e35c68c0593f0cb9ddc5d4b6798dd413e2f8/tsconfig.json#L34

Thank you, I had extraneous comma in tsconfig as well and got this problem solved by removing it.

**Comment by oneMoreTime1357** [comment]
> The first error is fixed in rc.6, if your config file is generated by rc.5, please try update it.
> [a352bdc](https://github.com/vuejs/vue-cli/commit/a352bdc4dae0032bcfd1f313097e73053e737d24)
> 
> The second error is due to an extraneous comma in your `tsconfig.json`
> https://github.com/luxtagofficial/Catapult-Vue/blob/e107e35c68c0593f0cb9ddc5d4b6798dd413e2f8/tsconfig.json#L34

Thanks, removeing extraneous comma in tsconfig solved my problem

**Comment by amitleuva1987** [comment]
> The first error is fixed in rc.6, if your config file is generated by rc.5, please try update it. [a352bdc](https://github.com/vuejs/vue-cli/commit/a352bdc4dae0032bcfd1f313097e73053e737d24)
> 
> The second error is due to an extraneous comma in your `tsconfig.json` https://github.com/luxtagofficial/Catapult-Vue/blob/e107e35c68c0593f0cb9ddc5d4b6798dd413e2f8/tsconfig.json#L34

This worked for me. Thank You.

**Comment by davidAtInleague** [comment]
Hi, I had an (well, a few) trailing commas in a tsconfig.json file; as per above comments, removing them resolved this error.

I don't fully follow why trailing commas are disallowed (strict json syntax requirement it seems), but comments are supported (that's not strictly a JSON feature, right?).

**Comment by danieelbog** [comment]
I had that problem as well and the reason for it was the extra comma I had in tsconfig.json. After removing it, everything worked!
