### ISSUE TITLE
(update)build files hash are diffrent after build in diffrent machine

### ISSUE THREAD

**Issue by zhouxinyong** [vuejs/vue-cli#2006]
### Version
3.0.0-rc.10

### Node and OS info
node.js: v9.3.0     npm: v6.0.0      OS: ubuntu

### Steps to reproduce
npm i -g @vue/cli

vue ui

create a project

run build in diffrent machine (one os is ubuntu, the other os is also ubuntu)

### What is expected?
the file hash is same after build in diffrent machine

### What is actually happening?
the chunk build hash are not same in diffrent machine !?

---

Is there any solution to fix this problem?

I have updated vue-loader to 15.2.6, but the hash still change in diffrent machine.

**Comment by zhouxinyong** [comment]
same with the close  issue #1728

**Comment by Akryum** [comment]
See https://github.com/vuejs/vue-cli/issues/1728#issuecomment-408769957
