### ISSUE TITLE
[Question] displaying eslint warnings/errors

### ISSUE THREAD

**Issue by DRoet** [vuejs/vue-cli#2009]
### Version
3.0.0-rc.10

### Node and OS info
10.7.0

### Steps to reproduce
Create a bunch of eslint warnings/errors

### What is expected?
In vue-cli 2.x. it would always display the errors on my screen (not just in the console)

### What is actually happening?
@vue/cli 3.0.0.-rc10 only logs the warnings/errors in the console when I start my development server but doesn't display them in the browser

---
Is this behaviour no longer supported or am I missing a configuration flag somewhere?

**Comment by yyx990803** [comment]
https://cli.vuejs.org/config/#lintonsave
