### ISSUE TITLE
Available presets

### ISSUE THREAD

**Issue by thany** [vuejs/vue-cli#2011]
### What problem does this feature solve?
It's hard if not not impossible (at least for a beginner) to find which presets are available. Everyone talks about `vue init webpack` which, as a javascript expert, immediately makes me think "which other presets might be available?..." I personally don't like Webpack and are used to Gulp tasks and bundle my script with Rollup. I don't know how well I can transplant that kind of workflow to Vue.

At any rate, there seems to be no list of presets anywhere. And I haven't got the foggiest idea what any of the presets might be. Even Google doesn't seem to know - that's a bad sign to me.

### What does the proposed API look like?
This page: https://cli.vuejs.org/guide/plugins-and-presets.html
It mentions webpack very briefly. But under the heading Presets I would've hoped to see a list of what's available.

Otherwise, some command like `vue presets` to list them. This command currently outputs absolutely nothing, so it might as well output a list of available presets.

**Comment by yyx990803** [comment]
`vue init <template>` is a Vue CLI 2.x command, and the concept of a "template" is a 2.x only concept.

In Vue CLI 3, every project is webpack based and a preset is just a JSON containing the collection of Vue CLI 3 compatible plugins and their options, and you are responsible for creating your own preset.

**Comment by thany** [comment]
Okay, but clearly there are a couple of default ones, or "webpack" wouldn't work. So which are they?

**Comment by yyx990803** [comment]
In 3.x you just do `vue create`.

**Comment by Juan-G-04** [comment]
`vue create` does not show the available presets
