### ISSUE TITLE
How do I stop compiling when ESLint throws an error?

### ISSUE THREAD

**Issue by weihongyu12** [vuejs/vue-cli#2015]
### What problem does this feature solve?
For the specification of the team project, we used ESLint, but in the build project, ESLint errors can still be built.

I think we might need a strict mode so that when an ESLint error occurs, the project cannot be built.

And I hope that in the development mode, I can add the configuration of the original `showEslintErrorsInOverlay`.

In the @vue/cli 3.0 documentation, I can't find the relevant configuration. If you have related configuration items, please let me know.

Thanks!

### What does the proposed API look like?
In the `vue.config.js` file, add two configuration items, like this

```javascript
module.exports = {
  // If true,  when building a project, an eslint error occurs, then the console throws an error and the project cannot complete the build.
  eslintStrict: true,
  // If true,  eslint errors and warnings will also be shown in the error overlay in the browser.
  showEslintErrorsInOverlay: true
}
```

**Comment by LinusBorg** [comment]
You can set  `lintOnSave: 'error'` for this.

The [docs for this option](https://cli.vuejs.org/config/#lintonsave) make it seem like it's only fordevelopment, but the last sentence reads:

>  If you want it to emit errors instead (i.e. when building for production), set it like this: `lintOnSave: 'error'`.
