### ISSUE TITLE
Add vue-router to webpack and webpack simple templates

### ISSUE THREAD

**Issue by shusiwei** [vuejs/vue-cli#202]
在webpack-simple模板构建中，一个由路由懒加载的页面只会执行一次，第二次切换回来后这个页面将会是空白，而用webpack模板构建的代码却没有此问题，这是什么原因造成的？

**Comment by chenEdgar** [comment]
建议加上线上demo或者把你的“问题代码”，截图黏出来

**Comment by elliotlarson** [comment]
I'm not entirely sure what's being requested here, but from the title it looks like @shusiwei is asking for a template with the vue-router added.  I agree.  The webpack and webpack-simple templates are geared towards developing a SPA, which in my experience has generally involves a router system.  It would be nice to have a template with the router plumbed in.

**Comment by CalebKester** [comment]
I agree this would be good as well. I'm having issues trying to get vue-router to work with webpack.

**Comment by zigomir** [comment]
Please open an issue on [webpack template](https://github.com/vuejs-templates/webpack). It's not really related to `vue-cli`.
