### ISSUE TITLE
Can't set filenameHashing in vue.config.js

### ISSUE THREAD

**Issue by ommehaz** [vuejs/vue-cli#2020]
### Version
3.0.0-rc.3

### Node and OS info
Node 10.0.0, npm 5.6.0

### Steps to reproduce
Setthe property filenameHashing  inside the exported object in vue.config.js and build

### What is expected?
I expect that the filenameHashing works like described

### What is actually happening?
I am getting a build error => Invalid options in vue.config.js "filenameHashing" is not allowed

**Comment by LinusBorg** [comment]
That Option was Ad des in rc. 10, P Lease Update your packages

**Comment by LinusBorg** [comment]
That Option was Ad des in rc. 10, P Lease Update your packages
