### ISSUE TITLE
组件可以通过路由的异步操作按需加载，希望组件内的css可以被剥离粗来也跟每个模块的js一样按需加载，现生产环境下，css只能提取为一个整个的css

### ISSUE THREAD

**Issue by zhilianbi520** [vuejs/vue-cli#2023]
### What problem does this feature solve?
项目过大的时候，css文件太大了。。希望可以跟js一样按需加载，不加载多余的css。

### What does the proposed API look like?
希望可以通过对webpack配置的修改实现。

**Comment by yyx990803** [comment]
This is already the case. If it's not working, please provide a reproduction.
