### ISSUE TITLE
cache of cache-loader causes problems with worker-loader

### ISSUE THREAD

**Issue by Janekdererste** [vuejs/vue-cli#2028]
### Version
3.0.0-rc.5

### Node and OS info
node: 8.11.1, npm: 6.1.0, OS: Debian 9

### Steps to reproduce
I am using webpack worker-loader for web-workers. My vue.config looks like this

```
module.exports = {
  parallel: false,
  baseUrl: '/',
  configureWebpack: {
    /**
     * Setting the global object is necessary to make the loading of web-workers work. Otherwise, window is referenced
     * in the produced bundle, which is not accessable from a worker context. This seems to be a webpack 4 bug
     * https://github.com/webpack/webpack/issues/6642
     * https://github.com/webpack/webpack/issues/6629
     */
    output: {
      globalObject: 'self',
    },
    module: {
      rules: [
        {
          test: /\.worker\.js$/,
          use: [{ loader: 'worker-loader' }, { loader: 'babel-loader' }],
        },
        {
          test: /\.worker\.ts$/,
          use: [{ loader: 'worker-loader' }, { loader: 'babel-loader' }, { loader: 'ts-loader' }],
        },
      ],
    },
  },
}
```

### What is expected?
Worker-loader should generate bundle files ([hash].worker.js) which should be loaded on request.

### What is actually happening?
When <src>/node_modules/.cache is emptied everything works as expected. 

If webpack-dev-server is started again via ``` vue-cli-service serve ``` The server doesn't seem to have the requested worker script and serves index.html instead. 

This is probably the intended behaviour by historyApiFallback of webpack-dev-server.

**Comment by Janekdererste** [comment]
Is there any possibility to turn of caching as a temporary workaround?

**Comment by LinusBorg** [comment]
I'm not sure how this relates to cache-loader since you don't even use it in your config, and since your didn't provide a reproduction (which we generally ask you to provide), I can't say what'S going on, I have nothing to look at.

**Comment by yyx990803** [comment]
Note with rules added like this, both your loaders AND the internal loaders configured for `*.js` will be applied to `*.worker.js` files. You may want to use `chainWebpack` to add `*.worker.js` files to the exclude list of the built-in `js` rule:

``` js
chainWebpack: config => {
  config.module.rule('js').exclude.add(/\.worker\.js$/)
}
```

**Comment by Janekdererste** [comment]
Thanks a lot @yyx990803. Excluding worker files from default loaders solved my problem.

**Comment by tangxiaolang101** [comment]
@Janekdererste Can you give me a code example?

**Comment by Janekdererste** [comment]
Hi @tangxiaolang101, yes I can. What parts are you particularly interested in?

**Comment by andersrehn** [comment]
@yyx990803 Thank you sir! You just saved me from hours of headache :)

**Comment by qidaneix** [comment]
find a more concise way to config worker-loader, do not need add `configureWebpack` in vue.config.js, just add:
```javascript
chainWebpack: config => {
  config.module.rule('webWorker').post().test(/\.worker\.(j|t)s$/).use('worker-loader').loader('worker-loader');
}
```
