### ISSUE TITLE
Provide option to create blank App.vue without HelloWorld.vue

### ISSUE THREAD

**Issue by lloydjatkinson** [vuejs/vue-cli#2030]
### What problem does this feature solve?
Developers with Vue experience do not need the App.vue component to display Vue ecosystem links (as they are already familiar with them) and do not need the HelloWorld.vue component either.

Deleting them is an extra step to perform when the new project has been made. Implementing this feature removes this extra step.

### What does the proposed API look like?
An extra toggle option in the following menu:

```
Vue CLI v3.0.0-rc.10
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, Linter, Unit
? Pick a linter / formatter config: Basic
? Pick additional lint features: Lint on save
? Pick a unit testing solution: Jest
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No
? Scaffold ecosystem links and HelloWorld component? [Default: Yes]
```

**Comment by itzikbenh** [comment]
Thanks for opening this issue, I 100% agree.

**Comment by aryehof** [comment]
> Scaffold ecosystem links

Confusing terminology to a newcomer.  Most beginners will have no idea what this means. I think it better to leave things as they are.  The time taken to remove the default example boilerplate is trivial compared to the potential confusion to new users.

**Comment by lloydjatkinson** [comment]
> I think it better to leave things as they are. 

`Scaffold ecosystem links and HelloWorld component?` **[Default: Yes]**

**Comment by LinusBorg** [comment]
While of course the essage could be improved, I still think that it's more valuable to provide a good example setup for newcomers than it is to save seasoned devs from 30 seconds of deleting 2 files and 5 lines of code.

**If** we choose to implement this, I would rather to it as a cli flag, maybe? `--skip-default-scaffold` or something.

This moves it outside of the immediate focus of a beginner who follows the happy path of simply running `vue create [project name]`

**Comment by NiloCK** [comment]
Even in a world where I was making a new project every day I don't think that this trade-off would be worth the added confusion in onboarding new developers to the ecosystem. The onslaught of configuration questions is intimidating - it should be as short as possible.

**Comment by lloydjatkinson** [comment]
A flag sounds reasonable.

**Comment by Akryum** [comment]
Maybe `vue create name --bare`

Le jeu. 2 août 2018 à 15:06, Lloyd Atkinson <notifications@github.com> a
écrit :

**Comment by lloydjatkinson** [comment]
Decided against then?
