### ISSUE TITLE
npm i 安装依赖失败eslint版本问题

### ISSUE THREAD

**Issue by piluohen** [vuejs/vue-cli#2035]
### Version
3.0.0-rc.10

### Node and OS info
npm5.6.0   node8.11.2 windows10

### Steps to reproduce
npm i

### What is expected?
eslint版本不对

### What is actually happening?
npm WARN eslint-config-standard@12.0.0-alpha.0 requires a peer of eslint@>=5.0.0-alpha.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

---
eslint版本不对

**Comment by yyx990803** [comment]
warning 不是错误。确认跑不起来再来报 bug。

**Comment by piluohen** [comment]
eslint安装不上，跑不起来呀

**Comment by yyx990803** [comment]
跑不起来给重现。

**Comment by piluohen** [comment]
![_20180802141438](https://user-images.githubusercontent.com/22088874/43565749-68dd419e-965e-11e8-9c8a-25ed74b3a848.png)
