### ISSUE TITLE
How to integrate ueditor with Vue-cli？

### ISSUE THREAD

**Issue by bison1994** [vuejs/vue-cli#204]
后台管理类应用常常需要用到富文本编辑器，能否直接将ueditor文件夹复制到dist文件夹下，然后在.vue文件中手动引入相应的js？我尝试这么做时，发生了路径错误。我在component文件夹下的一个.vue中试图直接使用"/dist/umeditor/umeditor.config.js"，报错信息是无法获得：http://localhost:8080/dist/umeditor/umeditor.config.js 
如果不能直接引入，那么有没有别的方式行得通？

**Comment by posva** [comment]
You may find help on the [forums](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). However, this is unrelated to vue-cli
