### ISSUE TITLE
Escape code in vue ui page

### ISSUE THREAD

**Issue by run-ze** [vuejs/vue-cli#2041]
### Version
3.0.0-rc.10

### Node and OS info
node v10.7.0 / yarn 1.9.2 / macOS 10.13.3

### Steps to reproduce
1. `vue ui` and open the page
1. create a new project
1. choose 'Manual' in 'Presets' step
1. enable 'Router' in 'Features' step and click 'Next'

In 'Configuration' step, the prompt of router will be:  `Use history mode for router? [33m(Requires proper server setup for index fallback in production)[39m`  .

### What is expected?
`Use history mode for router? (Requires proper server setup for index fallback in production)`

### What is actually happening?
`Use history mode for router? [33m(Requires proper server setup for index fallback in production)[39m`

**Comment by run-ze** [comment]
<img width="1440" alt="snipaste_2018-08-02_20-12-25" src="https://user-images.githubusercontent.com/7091451/43582886-68a2995e-9690-11e8-9478-73d8eda0b775.png">

**Comment by yyx990803** [comment]
@Akryum I think we need to handle potential color codes in UI (maybe [strip-ansi](https://github.com/chalk/strip-ansi)?)

**Comment by Akryum** [comment]
Closed in 8c96c15682e9f616aa0f027185f3705a3ab66b81

**Comment by Akryum** [comment]
![capture d ecran du 2018-08-06 15 06 46](https://user-images.githubusercontent.com/2798204/43718249-5e821682-998a-11e8-9aa3-a4b9bbcbf9ab.png)
