### ISSUE TITLE
Can't set filenameHashing in vue.config.js

### ISSUE THREAD

**Issue by H1D** [vuejs/vue-cli#2043]
### Version
3.0.0-rc.10

### Node and OS info
node 8.11.3, npm 5.6, macOS High Sierra

### Steps to reproduce
Add `filenameHashing: false` to ` vue.config.js`

### What is expected?
No file hashes in build

### What is actually happening?
error in console:
` ERROR  Invalid options in vue.config.js: "filenameHashing" is not allowed`

---
I've seen this bug for rc.3, but I'm using rc.10. Just deleted  ./node_modules and reinstalled vue-cli with `npm install -g @vue/cli --force`
![image](https://user-images.githubusercontent.com/697625/43598978-c5c1cc74-968e-11e8-9eee-9ca53beba3a8.png)

**Comment by yyx990803** [comment]
Make sure @vue/cli-service in your project is also upgraded.

**Comment by H1D** [comment]
![image](https://user-images.githubusercontent.com/697625/43600430-38884194-9693-11e8-8003-21034d87e036.png)

**Comment by H1D** [comment]
for others:
 - how to check your global cli-service version: `npm list -g @vue/cli-service-global`
 - how to upgrade global package: `npm install -g @vue/cli-service-global@3.0.0-rc.11 --force`
