### ISSUE TITLE
cli-plugin-eslint+cli-plugin-typescript: "parser" nested in "parserOptions"?

### ISSUE THREAD

**Issue by ky-is** [vuejs/vue-cli#2044]
### Version
3.0.0-rc.10

### Node and OS info
Node 10.7.0 / npm 6.2 / MacOS 10.13

### Steps to reproduce
```bash
vue create test
```
(Choose: Babel, TypeScript, Linter / Formatter with ESLint)

### What is expected?
In the generated `.eslintrc.js` file, `parser: 'typescript-eslint-parser'` is described as a root-level option by https://github.com/eslint/typescript-eslint-parser and https://eslint.org/docs/user-guide/configuring.

### What is actually happening?
`parser` is nested under `parserOptions`:
https://github.com/vuejs/vue-cli/blob/795393e60cde92bbe66c1a15ecd9fef967ee30ff/packages/%40vue/cli-plugin-eslint/generator.js#L85-L87

---
May be a bug? Applying this change triggers other linting errors. I'm new to TS and trying to understand this configuration file to get the linter playing nicely, so I appreciate the help!

**Comment by sodatea** [comment]
See https://github.com/vuejs/eslint-plugin-vue/blob/master/README.md#what-is-the-use-the-latest-vue-eslint-parser-error
