### ISSUE TITLE
could not open in the editor

### ISSUE THREAD

**Issue by zhaozhe0831** [vuejs/vue-cli#2049]
### Version
3.0.0-rc.10

### Node and OS info
zh-cn

### Steps to reproduce
在 ui 界面中，不能通过 "在编辑器中打开"，打开项目。

![image](https://user-images.githubusercontent.com/12945873/43621383-b9e9a928-9709-11e8-894f-78c6fd0b3644.png)

命令行报错 

```bash
Could not open mapbox-demo in the editor.
The editor process exited with an error: spawn code ENOENT.

Unable to open '/Users/zhaozhe/Demo/mapbox-demo' spawn code ENOENT.
```

![image](https://user-images.githubusercontent.com/12945873/43621400-c7789cac-9709-11e8-92ef-229e088589d0.png)

### What is expected?
通过 ui 界面，在编辑器中打开项目

### What is actually happening?
不能便捷打开项目

**Comment by thearabbit** [comment]
+1

**Comment by Akryum** [comment]
Maybe try settings `EDITOR` env variable like described [here](https://github.com/yyx990803/launch-editor).

**Comment by paritosh149** [comment]
@Akryum The description is not clear in the given link. Moreover, it works fine if an editor window is already open. I have tested this successfully for VisualStudioCode. 
It tried to set System Variable having name = EDITOR and value = code. Then, closed all VisualStudioCode windows. In this scenario, the extected result did not happen.

**Comment by sodatea** [comment]
@zhaozhe0831 
It is due to the lack of `code` shell command while having a running instance of VS Code.
You can [install `code` command in `PATH`](https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line) and try again.

**Comment by paritosh149** [comment]
@zhaozhe0831  code is already a shell command. Still the scenario remains same.

**Comment by paritosh149** [comment]
After adding User variable EDITOR with value = code, the editor is launched with correct folder.

**Comment by juan251189** [comment]
@paritosh149 did you find a solution? im having the same issue, i believe i need to modify one of the files installed by Vue.js UI. perhabs it is pointing at your preferred  editor and not to the one you are using.( my case trying to use code and its opening Atom)

**Comment by konglingwen94** [comment]
+1

**Comment by Chinegoodman** [comment]
✅✅✅✅✅
我遇到的问题是 给老项目增加这个 vite-plugin-vue-devtools 的支持。增加了对应的配置依赖项安装好依赖后 点击页面里的✳️无法打开 编辑器文件。


解决方法就是 比对着官方脚手架起来的空白项目的 配置信息在我原有项目进行同步。把原有项目的node_modules 和 package_lock.json  删除候 重新安装依赖 
[期间我重启过webstorm 关闭了其他的编辑器 同时把 .vue文件默认打开工具设置为 webstorm]
即可正常使用了！

mac系统 node version:19+
