### ISSUE TITLE
Building project for production hangs at "Chunk asset optimization" or "Additional chunk assets processing"

### ISSUE THREAD

**Issue by jpoles1** [vuejs/vue-cli#2050]
### Version
3.0.0-rc.10

### Node and OS info
Node: v8.11.3; Bash on Win 10

### Steps to reproduce
Cannot figure out how to reproduce in my large project. Seems to result from code-splitting of my components for usage in the router.

### What is expected?
Should compile project to production. Serving the project works fine. 

### What is actually happening?
This occurred after I switched from: 
`import component from "component.vue"` over to let import("component.vue")
Build hangs around 90%, never finishes.
In vue 3.0.0-rc.3 this stage was called "Chunk asset optimization"
In vue 3.0.0-rc.10 this stage was called "Additional chunk assets processing"

**Comment by yyx990803** [comment]
Unfortunately if there's no production there's nothing we can do.
