### ISSUE TITLE
HMR (Hot module reload) not working with vue cli 3

### ISSUE THREAD

**Issue by vinaybedre** [vuejs/vue-cli#2051]
### Version
3.0.0-rc.10

### Node and OS info
Node 8.11.2 / Yarn 1.7.0 / Windows 10

### Steps to reproduce
* git clone https://github.com/vinaybedre/vue-cli-3-hmr-bug
* yarn install
* npm start serve
* Open server at http://localhost:8080/about
* Do changes to any src file eg. under views/About.vue change the text
* Under browser's console, I get error Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
* HMR is not working as expected and mentioned

### What is expected?
HMR should update the browser's content based on changes made on src file

### What is actually happening?
HMR is failing, any changes done to the src files are not being hot reloaded in browser.

**Comment by yyx990803** [comment]
Cannot reproduce on Windows 10 with a fresh install from RC10.

**Comment by Cycododge** [comment]
I was having the same issue. Please ensure that `NODE_ENV=development`.

**Comment by vinaybedre** [comment]
using cross_env and setting NODE_ENV worked. Thanks

**Comment by DamonCais** [comment]
I just change the script to 'cross-env NODE_ENV=development vue-cli-service serve',but it still can't reproduce

**Comment by season19840122** [comment]
@Cycododge Where is Vue Cli 3 set?

**Comment by Cycododge** [comment]
@season19840122 I'm not sure if I completely understand your question. I installed it with `npm install -g @vue/cli`, and run my app with `npm run dev` that actually calls `npm i --only=dev --no-audit && npm i --only=prod && cross-env NODE_ENV=development vue-cli-service serve --open`.

**Comment by yzhengaq** [comment]
got the same problem.
though in chrome console it print the messsage '[HMR] Waiting for update signal from WDS...' but it is still not working when i am changing my src file.
anyone had a solution?

**Comment by yzhengaq** [comment]
find a solution here [#1559](https://github.com/vuejs/vue-cli/issues/1559#issuecomment-404718936)
remove node_modules and reinstall through npm instead of cnpm and the problem solved!

**Comment by season19840122** [comment]
@yzhengaq You're right!

**Comment by andycrockett** [comment]
Here's another solution, add this under the exports.devServer in vue.config.js

```
watchOptions: {
      poll: true
}
```
https://webpack.js.org/configuration/dev-server/#devserver-watchoptions-

**Comment by ellakan** [comment]
//vue.config.js
  devServer: {
    proxy: 'http://localhost:8080',
    public: '10.190.81.79:8080',
  }
set the public url

**Comment by TheRubble** [comment]
Was having the same issue, it seems to serve fine on the external IP but no on localhost.

**Comment by Kordonme** [comment]
Just wanted to throw my experience out there.
When switching network (work/home) and my local IP changed, hot reload stopped working. It seems to use the public IP, and since that changes, hot reloading stops working.
Simply stop the server and type `npm run serve` again.

**Comment by Akryum** [comment]
You can also use `--host localhost`

Le jeu. 27 sept. 2018 à 08:46, Mark Jan Kordon <notifications@github.com> a
écrit :

**Comment by heihachi88** [comment]
I've noticing, hot load stopping to work when you manually refresh the browser window. It's a bug...

**Comment by DanielSharkov** [comment]
What I have noticed, is that it won't load anymore when I
- change the logic (So basically javascript)
- use Safari (In chrome it works fine)

I can only change stuff in the the templates and hit refresh every time, then it's still working.
But I found a temporary fix for that: When it's not working then just clear the cache in the browser and refresh once (Works for me)

**Comment by fakefarm** [comment]
My solution was to turn `poll: true` in `config/index.js` 

```
> vue --version
2.9.6
```

**Comment by skymakerolof** [comment]
@woodcoder's description applied to my situation (thank you!)

Run `npm ls webpack` to find out if you have different version of webpack:
```bash
$ npm ls webpack
app@0.1.0
+-- @cypress/webpack-preprocessor@3.0.1
| `-- webpack@4.18.1
`-- @vue/cli-service@3.1.2
  `-- webpack@4.25.1
```

I created a new app with `vue create` without Cypress (which is part of the multiple webpack problem, see above) and HMR works just fine now.

**Comment by barakbd-bluevine** [comment]
Getting the same issue:
Mac OS:  Mojave
Node version: 10.13.0
VUE CLI: 3.1.3

My vue.config.js (as per suggestions here):

```
module.exports = {
    configureWebpack: {
        devServer: {
            clientLogLevel: 'info',
            watchOptions: {
                poll: true
            }
        }
    }
}
```

Error in console:
`[HMR] Update failed: Error: Manifest request to /db59191d7a7aab69336f.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (http://localhost:8080/app.js:72:16)`


Search in Google for this error brought up this issue:
https://github.com/gaearon/react-hot-boilerplate/issues/120

I tried the solution from that issue, still not working.

**Comment by barakbd-bluevine** [comment]
Tried it on Ubuntu 18.04 - works fine.

**Comment by azl397985856** [comment]
it turns out to be the problem of proxy itself in my case.

just change the proxy setting of my browsers,  rocks~

**Comment by mayurishinde2** [comment]
reinstalling npm solved the problem :+1:

**Comment by netanyahuyasser** [comment]
If you are on linux, this can solves the issues. 

[Visual Studio Code is unable to watch for file changes in this large workspace" (error ENOSPC)](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc)

**Comment by Ibaeni** [comment]
Setting poll: true in index.js worked for me

**Comment by JessicaOPRD** [comment]
I'm having this problem too. I generated my first Vue app using Vue CLI 3 (`vue create`) a couple of days ago and this feature works whenever I type `npm run serve` in that app's directory. I thought I would start over today, so I generated a new Vue app using Vue CLI again. Noticed the content does not refresh in the browser (though the console does appear to update/refresh). No error messages in the browser console. I generated 5 additional apps (manually selected various settings) and cannot get it to work in any of those apps. Always works in the original app I made on Dec 19.

```
node --version
v8.11.4
```

```
vue -V
3.2.1
```

Windows 7

I think the apps I've made are in dev mode when I type `npm run serve`? Do I need to do anything special to ensure that they are?

In app that works:
```
npm ls webpack
-- @vue/cli-service@3.2.0
  -- webpack@4.28.0
```

In app that does not work:
```
npm ls webpack
-- @vue/cli-service@3.2.0
  -- webpack@4.28.1
```

I appreciate any help/tips for further investigation!

**Comment by wsugiri** [comment]
I had some problem with @JessicaOPRD , old generated working well but the new one doesn't work.
On my case app that doesn't work has version webpack@4.28.2

**Comment by Manop09** [comment]
same problem hot reload doesn't work with webpack@4.28.2. @JessicaOPRD

**Comment by jerrychen1013** [comment]
I also met this problem, after 6 hours try and error, finally to figure the problem: cors-origin block hot-reload.

This can be solved by add vue.config.js in project root (same level with package.json) as below:
```
module.exports= {
  devServer: {
    open: process.platform === 'darwin',
    headers: { 'Access-Control-Allow-Origin': '*' },
    disableHostCheck: true
    // proxy: 'http://localhost:8080'  // open it if you meet a problem in docker env.
    // https: false,
  }
}
```

**Comment by wsugiri** [comment]
thanks @jerrychen1013 your setting working perfectly in my case.
also working only set disableHostCheck: true

`module.exports = {
    devServer: {
        disableHostCheck: true
    }
}`

**Comment by jerrychen1013** [comment]
@wsugiri  That's true! It's the main setting to let HMR lives. 
According to the document, it's recommended to cancel it in prodution env.
[Link](https://webpack.js.org/configuration/dev-server/#devserver-disablehostcheck)

**Comment by favourori** [comment]
Here's the fix:

Create a vue.config.js file in your app's root. Then paste this code into it:

module.exports = {
    devServer: {
     disableHostCheck: true
    }
  }


Works well!

**Comment by lfl976** [comment]
> thanks @jerrychen1013 your setting working perfectly in my case.
> also working with set disableHostCheck: true
> 
> `module.exports = { devServer: { disableHostCheck: true } }`

solve my problem thanks

**Comment by dblazeski** [comment]
There was an issue with `webpack-dev-server,` it's fixed in `webpack-dev-server: 3.1.14`.
vue cli uses 3.1.13, so in the meantime, update your package.json and force the 3.1.14 version:
```
  "resolutions": {
	"webpack-dev-server": ">=3.1.14"
  }
```
and reinstall your node_modules.

https://github.com/webpack/webpack-dev-server/releases/tag/v3.1.14

**Comment by huenisys** [comment]
I had this issue and was already giving up until I read til the bottom. Thanks for the suggestion @dblazeski All I did was remove @vue/cli-service": "^3.0.4" temporarily then I reinstalled. The version I got @vue/cli-service@3.2.0 which came with webpack-dev-server@3.1.14.

So all is working now!

**Comment by barakbd-bluevine** [comment]
Turns out the problem is on Chrome and Safari.
Firefox works.

Here is my full env setup:
MacOS: Mojave 10.14.1
Node: v10.13.0

Browsers:
Chrome - Version 71.0.3578.98
Firefox - v64
Safari - Version 12.0.1

package.json:
```
  "dependencies": {
    "vue": "^2.5.17",
    "vue-router": "^3.0.1",
    "vuetify": "^1.3.0",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.2.0",
    "@vue/cli-plugin-eslint": "^3.2.0",
    "@vue/cli-service": "^3.2.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.8.0",
    "eslint-plugin-vue": "^5.0.0-0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "vue-cli-plugin-vuetify": "^0.4.6",
    "vue-template-compiler": "^2.5.17",
    "vuetify-loader": "^1.0.5"
  }
```
I get a network error:
```http://localhost:8080/ad221ea30cde880022f5.hot-update.json - request cancelled```

Any suggestions?

**Comment by JessicaOPRD** [comment]
Wow, I thought this was just me! Thank you all. @wsugiri @jerrychen1013 @dblazeski @huenisys 

I suspect I am not as versed in npm re-installing as others so I will share in detail how this worked out for me...

First checked `webpack-dev-server` per @dblazeski's tip:

```
npm ls webpack-dev-server
-- @vue/cli-service@3.2.0
  -- webpack-dev-server@3.1.11
```

Tried `npm install`, got `up to date`. Still `webpack-dev-server@3.1.11`.

Tried deleting node_modules, `npm install`, got `added 1358 packages`. Still `webpack-dev-server@3.1.11`.

Finally what **worked**:

1. Removed `"@vue/cli-service": "^3.2.0",` line from `package.json`, per suggestion of @huenisys.
2. Ran `npm install`, got `removed 577 packages`
3. Re-added `"@vue/cli-service": "^3.2.0",` line from `package.json`
4. Ran `npm install` again, got `added 578 packages`

Checked `webpack-dev-server` again:

```
npm ls webpack-dev-server
-- @vue/cli-service@3.2.0
  -- webpack-dev-server@3.1.14
```

Now HMR works swimmingly. Seriously thank you! :)

**Comment by huenisys** [comment]
@JessicaOPRD toldya. :)

**Comment by barakbd-bluevine** [comment]
```$ npm ls webpack-dev-server
└─┬ @vue/cli-service@3.2.0
  └── webpack-dev-server@3.1.14 
```

still not working.

**Comment by KamaMakh** [comment]
not working for me( 
`└─┬ @vue/cli-service@3.3.0
  └── webpack@4.28.1`

vue.config.js:
`module.exports = {
  lintOnSave: false,
  runtimeCompiler: true,
  devServer: {
    disableHostCheck: true
  }
}`

**Comment by barakbd-bluevine** [comment]
localhost is the issue.
When I open the link with my computer's ip address it works.

**Comment by daniandl** [comment]
Is there any way to get this working on localhost?
I've tried just about every solution in this thread :/

**Comment by JessicaOPRD** [comment]
Hello, I wanted to mention a side effect that I experienced from trying to resolve this issue. It took me a long time to figure out and this might help someone else! After all of this, my computer started running slowly whenever I ran `npm run serve` on the Vue app I had tried to fix HMR for. My CPU usage was jumping between 90-100%. I think it was getting worse as I was adding to my app. I finally tried upgrading Node.js and npm, and re-installing all of my local app dependencies using the method @huenisys shared in this thread. This step seemed to help a little, but my CPU usage was still at 50-60% just from running this app.

Finally I remembered that I had added this config to `vue.config.js`:

```
watchOptions: {
      poll: true
}
```

Removing it and restarting my app fixed the problem! I am now back to 5-20% when I run my app locally. HMR does still work for me with the `webpack-dev-sever` upgrade. I'm not sure if this is unique to my OS/version, and it might have been obvious to a lot of people, but I figured I'd share since I'm new to webpack and Vue and it got me pretty good.

**Comment by createdbyjurand** [comment]
you can also add
`module.exports = {
  devServer: {
    host: 'localhost'
  }
}
`
to
`vue.config.js`

**Comment by createdbyjurand** [comment]
My problem was HMR
Console displayed:
```
[HMR] Waiting for update signal from WDS...
[WDS] Disconnected!
GET http://ip:port/sockjs-node/info?t=some-number
net::ERR_CONNECTION_TIMED_OUT sockjs.js?some-number
```

Solution for me was:
in
`package.json`
change
`"serve": "vue-cli-service serve",`
to
`"serve": "vue-cli-service serve --host localhost",`

or add
```
module.exports = {
  devServer: {
    host: 'localhost'
  }
}
```
to
`vue.config.js`

**Comment by createdbyjurand** [comment]
My problem was WDS
Console displayed:
```
[HMR] Waiting for update signal from WDS...
[WDS] Disconnected!
GET http://ip:port/sockjs-node/info?t=some-number
net::ERR_CONNECTION_TIMED_OUT sockjs.js?some-number
```

Solution for me was:
in
`package.json`
change
`"serve": "vue-cli-service serve",`
to
`"serve": "vue-cli-service serve --host localhost",`
or
add
```
module.exports = {
  devServer: {
    host: 'localhost'
  }
}
```
to
`vue.config.js`
:)

**Comment by hfnabhyasi** [comment]
@createdbyjurand,

This worked so I've included two commands (to keep the default option):

...
{
  ...
  "scripts": {
    "serve-localhost": "vue-cli-service serve --host localhost",
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  }
  ...
}
...

**Comment by vojtapol** [comment]
@createdbyjurand This helped but I don't understand why. Can anyone explain?

**Comment by oswaldofreitas** [comment]
maybe this can help someone: https://webpack.js.org/configuration/watch/#changes-seen-but-not-processed

**Comment by Teknologica** [comment]
I just had this issue and tried every single solution proposed in the thread. None were successful until I considered that maybe the `webpack-dev-server` dependency was outdated _again_ with the particular combination I had.

My project is on Vue 2.6 with everything else updated using `vue upgrade`. 
After some investigation running: 
`npm list webpack-dev-server`
returned a list of packages at version `3.1.14`. The latest version at the time of this writing is `3.2.1`. So I added this to my `package.json` (for `yarn` only?):
```json
"resolutions": {
  "webpack-dev-server": "3.2.1"
}
```
and then ran `yarn install` again. This fixed the problem for me! :tada:

Do note that my `vue.config.js` does have:
```js
devServer: {
  disableHostCheck: true,
```

I hope this could help some of you.

**Comment by ndabAP** [comment]
I tried all of the above suggestions and no one helped. I'm using Linux, Chrome and `@vue/cli-plugin-babel` 3.4.1.

**Comment by minorbug** [comment]
Same issue as @ndabAP. None of the previous suggestions worked.

**Comment by Zver64** [comment]
I found out that my vpn extention was blocking vue hot reload. Might be helpfull for those who use vpn too.

**Comment by VictorCamargo** [comment]
The final solution to me was install with yarn.

**Comment by gavofih** [comment]
Can confirm, works perfectly with Yarn

**Comment by apavel3458** [comment]
This is still broken... after months of issues... this is very sad.

**Comment by AshrafBasry** [comment]
@apavel3458   if you using linux try  **sudo npm run serve** if it work here is the solution
https://github.com/vuejs-templates/webpack/issues/1054#issuecomment-344747332

**Comment by vuchl** [comment]
For me this issue surfaced when I installed Docker for Windows which added a virtual network adapter. Closing Docker does not resolve this issue. I started to disable docker to run on computer start and disabled the virtual network Adapter (something with Hyper-V in the description in my case).

Then the `npm run serve` started to listen again on the right IP addresses and not the virtual one.

**Comment by JackyChan** [comment]
It seems to be a problem with preload feature in Safari. Just remove preload plugin from webpack fixed the problem.
```
// vue.config.js
module.exports = { 
  chainWebpack: (config) => {
    config.plugins.delete('preload')
  }
}
```

**Comment by franciscolourenco** [comment]
This happened to me after `vue upgrade`. 

Updating `webpack-dev-server` fixed the problem for me:
`yarn upgrade --latest webpack-dev-server`

**Comment by ademilter** [comment]
I used yarn instead of npm and solved

**Comment by syedsimanta03** [comment]
I am also facing this issue

**Comment by apavel3458** [comment]
I was able to get it to work after creating a new project from scratch with vue init.  For those who are still struggling.  I recommend:

1. Make sure your local IP address hasn't changed.  When I move to a different wifi network with different IP address, HOT reload doesn't work.  I have to stop the service and re-launch to get new IP address. 
2. If above doesn't work, delete node_modules and run npm install. 
3. If that doesn't work, you will unfortunately need to create a new project with vue init, and then copy all your files over. 

Good luck, I hope it starts working!

**Comment by aislanmaia** [comment]
I'm having the same problem and I even know when this started to happen. Just noticed the browser doing full refreshes.
The error is the same as the op. `[HMR] Waiting for update signal from WDS...`

**Comment by eljaouharihamza** [comment]
This solved my problem :

[Visual Studio Code can't watch a large folder with many files](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc)

**Comment by aislanmaia** [comment]
@eljaouharihamza in my case, I already have this setting for `max_user_watches` configured to 99999999. I think the problem, in general, is not coming from only this.

**Comment by aislanmaia** [comment]
I don't know if this is related, but I'm getting this in the chrome console:

```
app.js:1008 Uncaught RangeError: Maximum call stack size exceeded
    at hotAddUpdateChunk (app.js:1008)
    at webpackHotUpdateCallback (app.js:37)
    at webpackHotUpdateCallback (app.js:38)
    at webpackHotUpdateCallback (app.js:38)
    at webpackHotUpdateCallback (app.js:38)
    at webpackHotUpdateCallback (app.js:38)
    at webpackHotUpdateCallback (app.js:38)
    at webpackHotUpdateCallback (app.js:38)
    at webpackHotUpdateCallback (app.js:38)
    at webpackHotUpdateCallback (app.js:38)
```

**Comment by eljaouharihamza** [comment]
This line is working perfectly for me (for the moment) 

`    "serve": "cross-env NODE_ENV=development vue-cli-service serve --open --host localhost",
`

**Comment by aislanmaia** [comment]
@eljaouharihamza but with that line you "lose" the local network capability, right ?

**Comment by embryCODE** [comment]
> Just wanted to throw my experience out there.
> When switching network (work/home) and my local IP changed, hot reload stopped working. It seems to use the public IP, and since that changes, hot reloading stops working.
> Simply stop the server and type `npm run serve` again.

Well, that's just embarrassing. That's what the problem was for me and I didn't even think of that. Face palm.

**Comment by Arsync** [comment]
I've spend a lot of time looking at my config and found another (undocumented) requirement:
Absolute path specified in `outputDir` breaks any HMR functionality.
All other things works as usual.

Ensure that `outputDir` contains relative path.

**Comment by patrickdavey** [comment]
If you're having issues with HMR and you're running your dev webserver on a different port, then, you will likely run into this issue with webpack-dev-server https://github.com/webpack/webpack-dev-server/issues/1385

**Comment by suyanhanx** [comment]
By add devServer pull on windows 10 1903, it works.

**Comment by QuantumInformation** [comment]
Getting that error today after upgrading

VUE [HMR] Waiting for update signal from WDS...

```js
  "dependencies": {
    "@mdi/font": "^3.8.95",
    "axios": "^0.19.0",
    "register-service-worker": "^1.6.2",
    "vue": "^2.6.10",
    "vue-analytics": "^5.17.0",
    "vue-router": "^3.0.7",
    "vuetify": "^2.0.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.9.2",
    "@vue/cli-plugin-e2e-nightwatch": "^3.9.2",
    "@vue/cli-plugin-eslint": "^3.9.2",
    "@vue/cli-plugin-pwa": "^3.9.0",
    "@vue/cli-plugin-unit-jest": "^3.9.0",
    "@vue/cli-service": "^3.9.3",
    "@vue/eslint-config-standard": "^4.0.0",
    "@vue/test-utils": "^1.0.0-beta.25",
    "babel-core": "^7.0.0-0",
    "babel-jest": "^24.8.0",
    "babel-plugin-transform-imports": "^2.0.0",
    "http-server": "^0.11.1",
    "less": "^3.9.0",
    "postcss-custom-properties": "^9.0.2",
    "postcss-nested": "^4.1.2",
    "postcss-smart-import": "^0.7.6",
    "prettier": "^1.18.2",
    "sass": "^1.22.7",
    "sass-loader": "^7.1.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "vue-cli-plugin-vuetify": "^0.6.1",
    "vue-template-compiler": "^2.6.10",
    "webpack-cli": "^3.3.6"
  },```

**Comment by VisonM** [comment]
Maybe accidentally upload the sourcemap in the development environment.

**Comment by Kamleshpaul** [comment]
I also had same issue with `@vue/cli 4.1.2`

i fixed this by creating a file `vue.config.js` and inside i added 

```javascript
module.exports = {
    devServer: {
        watchOptions: {
            poll: true
        }
    }
}

```

i search so many place didn't found the soultion so now i got it and comment it here with solution hope it may helps others

**Comment by EmilyRosina** [comment]
> find a solution here [#1559](https://github.com/vuejs/vue-cli/issues/1559#issuecomment-404718936)
> remove node_modules and reinstall through npm instead of cnpm and the problem solved!

This solved it for me :+1: 
- delete `node_modules`
- `npm i`

**Comment by feusebio** [comment]
> I also had same issue with `@vue/cli 4.1.2`
> 
> i fixed this by creating a file `vue.config.js` and inside i added

This solution works for me with @vue/cli 4.1.2
Thanks

**Comment by caffeines** [comment]
When you see this notification, it indicates that the VS Code file watcher is running out of handles because the workspace is large and contains many files. The current limit can be viewed by running:

```cat /proc/sys/fs/inotify/max_user_watches```
The limit can be increased to its maximum by editing /etc/sysctl.conf and adding this line to the end of the file:

```fs.inotify.max_user_watches=524288```
The new value can then be loaded in by running ```sudo sysctl -p.``` Note that Arch Linux works a little differently, See Increasing the amount of inotify watchers for details.

[https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc](https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc)

**Comment by RenanRossiDias** [comment]
After doing every purposed solution in this thread, it worked for me:

**1.** Deleted **`node_modules`**, then npm install.
**2.** At **vue.config.js** (if you don't have one, just create this file at your project root), added **`poll:true`**:
```
module.exports = {
  configureWebpack: {
    devServer: {
      watchOptions: {
        poll: true
      }
    }
  }
}
```
**3.** Changed start script to `vue-cli-service serve --open --host localhost`
**4.** Ensured i was at development env, running this command: `SET NODE_ENV=development`

Hope it works for you too.

**Comment by altrusl** [comment]
I have noticed that HMR stops working if you jump to some route and vue-router is in 'history' mode
In the 'hash' mode HMR works fine

**Comment by GzhiYi** [comment]
package.json 
```json
"serve":  "vue-cli-service serve --mode development"
```
It works for me.

**Comment by bhensonweb** [comment]
For me the problem was that it doesnt work in my virtual machine (Vagrant/Homestead). When running outside of the VM it works fine. 

I think the reason for this is that the VM uses a symlink to reference source files on the local machine, and I am guessing npm doesnt watch for changes through the symlink.

**Comment by sdwru** [comment]
None of these solutions worked for me.  My problem ended up being 

`"@vue/cli-service": "^4.5.8",`  downgrading to `3.11.0` fixed it.

**Comment by Guardado** [comment]
Anyone using WLS 2 (Windows Subsystem for Linux 2) and having problems with HMR not detecting file changes I solved the issue in the following way:

Instead of using a mount path `/mnt/c/Users/yourname/Documents/vueproject`  move everything to the Linux home directory `/home/yourname/vueproject`. 

It will not only detect the file changes, it will also increase the build speed.

**Comment by R-Slane** [comment]
> After doing every purposed solution in this thread, it worked for me:
> 
> **1.** Deleted **`node_modules`**, then npm install.
> **2.** At **vue.config.js** (if you don't have one, just create this file at your project root), added **`poll:true`**:
> 
> ```
> module.exports = {
>   configureWebpack: {
>     devServer: {
>       watchOptions: {
>         poll: true
>       }
>     }
>   }
> }
> ```
> 
> **3.** Changed start script to `vue-cli-service serve --open --host localhost`
> **4.** Ensured i was at development env, running this command: `SET NODE_ENV=development`
> 
> Remember to shut down your local server before performing this solution.
> 
> Hope it works for you too.

@RenanRossiDias  I confirm your fix worked for me. You saved my a*, thank u so much. Have a great day Sir.

**Comment by dele-corporate** [comment]
one way to solve this https://github.com/vuejs/vue-cli/issues/1132#issuecomment-803558661

**Comment by spaceofsn** [comment]
OS : Windows 10 64bit
App: Docker Desktop

Solved the problem after following the steps bellow:

1.  Turn off using WSL2 based engine in the configuration in Docker Desktop.
2.  Remove the containers by clicking the delete button in Docker Desktop.
3.  Rebuild and restart the containers using docker-compose command.

It seems using WSL2 based engine causing this problem.

**Comment by Matthewenderle** [comment]
> 
> 
> Anyone using WLS 2 (Windows Subsystem for Linux 2) and having problems with HMR not detecting file changes I solved the issue in the following way:
> 
> Instead of using a mount path `/mnt/c/Users/yourname/Documents/vueproject` move everything to the Linux home directory `/home/yourname/vueproject`.
> 
> It will not only detect the file changes, it will also increase the build speed.

This worked for me. I tried everything.

**Comment by 1937431577** [comment]
> 在这里找到解决方案[#1559](https://github.com/vuejs/vue-cli/issues/1559#issuecomment-404718936) 删除 node_modules 并通过 npm 而不是 cnpm 重新安装，问题解决了！

You're right!

**Comment by pravinweb** [comment]
> > Anyone using WLS 2 (Windows Subsystem for Linux 2) and having problems with HMR not detecting file changes I solved the issue in the following way:
> > Instead of using a mount path `/mnt/c/Users/yourname/Documents/vueproject` move everything to the Linux home directory `/home/yourname/vueproject`.
> > It will not only detect the file changes, it will also increase the build speed.
> 
> This worked for me. I tried everything.

Thank you it works!
