### ISSUE TITLE
Image path is error after run build and version is 3.0.0-rc.10

### ISSUE THREAD

**Issue by HighWarmModel** [vuejs/vue-cli#2054]
### What problem does this feature solve?
Image path error after packaging. What do I need to do that modify path in the config?
![image](https://user-images.githubusercontent.com/21271880/43631708-8f7b0ee8-9736-11e8-8cc2-3a11961bb5ea.png)

### What does the proposed API look like?
The background path is right after run build

**Comment by yyx990803** [comment]
Use the proper bug report format please.
