### ISSUE TITLE
Image path is error after run build

### ISSUE THREAD

**Issue by HighWarmModel** [vuejs/vue-cli#2056]
### Version
3.0.0-rc.10

### Node and OS info
Node 10.7.0 / npm 6.1.0

### Steps to reproduce
![image](https://user-images.githubusercontent.com/21271880/43633841-0864b920-973d-11e8-8732-940ce6719d68.png)

before:
![image](https://user-images.githubusercontent.com/21271880/43633719-a80a5120-973c-11e8-9980-09fb3c20f1b6.png)

npm run build

after:
![image](https://user-images.githubusercontent.com/21271880/43633812-e94683a2-973c-11e8-9430-151bc5135088.png)

### What is expected?
Image path is true

### What is actually happening?
Image path error after packaging.

**Comment by LinusBorg** [comment]
Closed until reproduction is provided.
