### ISSUE TITLE
Vue UI as a PWA

### ISSUE THREAD

**Issue by paritosh149** [vuejs/vue-cli#2057]
### What problem does this feature solve?
This feature would allow users to access Vue UI without browser window.

### What does the proposed API look like?
It would appear as shortcut on desktop.

**Comment by LinusBorg** [comment]
That would require to install the PWA to localhost, wouldn't it? 

...which in turn would provoke weird console errrors whenever you run any other app on localhost on the same port, I think... @Akryum  ?

**Comment by yyx990803** [comment]
Vue UI requires a local node.js process running, so this simply can't be done.
