### ISSUE TITLE
Permission issue when install on windows: npm install -g @vue/cli

### ISSUE THREAD

**Issue by dewitt-li** [vuejs/vue-cli#2060]
### Version
3.0.0-rc.10

### Node and OS info
node v9.11.1/ npm 5.6/ windows 10

### Steps to reproduce
run command npm install -g @vue/cli

### What is expected?
expect to install vue-cli

### What is actually happening?
C:\WINDOWS\system32>npm install -g @vue/cli
npm WARN rollback Rolling back kind-of@3.2.2 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\106319\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\is-accessor-descriptor\node_modules'
npm WARN rollback Rolling back is-extendable@1.0.1 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\106319\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\extend-shallow\node_modules'
npm WARN apollo-client@2.3.7 requires a peer of graphql@^0.11.0 || ^14.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path C:\Users\106319\AppData\Roaming\npm\node_modules\@vue\cli
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\106319\AppData\Roaming\npm\node_modules\@vue\cli' -> 'C:\Users\106319\AppData\Roaming\npm\node_modules\@vue\.cli.DELETE'
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\106319\AppData\Roaming\npm\node_modules\@vue\cli' -> 'C:\Users\106319\AppData\Roaming\npm\node_modules\@vue\.cli.DELETE'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, rename 'C:\Users\106319\AppData\Roaming\npm\node_modules\@vue\cli' -> 'C:\Users\106319\AppData\Roaming\npm\node_modules\@vue\.cli.DELETE'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path: 'C:\\Users\\106319\\AppData\\Roaming\\npm\\node_modules\\@vue\\cli',
npm ERR!      dest: 'C:\\Users\\106319\\AppData\\Roaming\\npm\\node_modules\\@vue\\.cli.DELETE' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, rename \'C:\\Users\\106319\\AppData\\Roaming\\npm\\node_modules\\@vue\\cli\' -> \'C:\\Users\\106319\\AppData\\Roaming\\npm\\node_modules\\@vue\\.cli.DELETE\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\106319\\AppData\\Roaming\\npm\\node_modules\\@vue\\cli',
npm ERR!   dest: 'C:\\Users\\106319\\AppData\\Roaming\\npm\\node_modules\\@vue\\.cli.DELETE' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\106319\AppData\Roaming\npm-cache\_logs\2018-08-03T15_09_24_281Z-debug.log

**Comment by Berkmann18** [comment]
Same as me (except that I use a different OS and more up-to-date versions of Node and NPM).
Cf.: #2061

**Comment by yyx990803** [comment]
This is not caused by Vue CLI itself, but try clearing your npm cache, and uninstall previous version before installing again.

**Comment by Berkmann18** [comment]
@dewitt-li (and anyone who may face this issue and come here) I managed to solve that problem by doing the following:
```bash
npm cache verify #I tried running npm cache clean but it wasn't necessary
npm i -g @vue/cli@latest
```

**Comment by dewitt-li** [comment]
@Berkmann18 I tried the same commands but no luck, still running into the same error.

**Comment by Berkmann18** [comment]
@dewitt-li Have you tried doing any of the following commands?
```bash
npm cache clean
npm-check -gu #or if you don't have that package then npm up or npm -g npm@latest
npm i -g vue-cli@latest
```

**Comment by dewitt-li** [comment]
@Berkmann18 The commands installed 2.9 instead of version 3 which what I need

**Comment by dewitt-li** [comment]
@Berkmann18 It's the antivirus software. Worked as soon as it is stopped. It's also noticeably faster.

**Comment by Berkmann18** [comment]
@dewitt-li Ah okay.

**Comment by Damanharneet** [comment]
> @dewitt-li (and anyone who may face this issue and come here) I managed to solve that problem by doing the following:
> 
> ```shell
> npm cache verify #I tried running npm cache clean but it wasn't necessary
> npm i -g @vue/cli@latest
> ```

can you please help me. I tried everything

**Comment by ellipticview** [comment]
I can confirm that disabling McAfee antivirus resolved the issue on my system.

**Comment by sfraise** [comment]
FYI, if npm won't work give yarn a try

**Comment by Berkmann18** [comment]
@akhil-c-k Seems like you tried to install it with `sudo` or `su` then running it without.
Try re-installing it without root permissions.

**Comment by gojkov** [comment]
> @dewitt-li (and anyone who may face this issue and come here) I managed to solve that problem by doing the following:
> 
> ```shell
> npm cache verify #I tried running npm cache clean but it wasn't necessary
> npm i -g @vue/cli@latest
> ```

This worked for me, thanks!

**Comment by Amro883** [comment]
all this solves not work in my sysem "ubuntu"

**Comment by Berkmann18** [comment]
> all this solves not work in my sysem "ubuntu"

Even with an up-to-date Node and NPM version and using an LTS version for Ubuntu (or more recent)?
