### ISSUE TITLE
The issue about baseUrl option in  vue.config.js

### ISSUE THREAD

**Issue by codesboy** [vuejs/vue-cli#2065]
### Version
3.0.0-rc.10

### Node and OS info
nodejs v8.11.3,windows7

### Steps to reproduce
Add the baseUrl option into vue.config.js ,then  do `npm run serve`, and then has many errors in browser.But when I remove the baseUrl option,No more Errors.

![image1](http://7xt4t7.com1.z0.glb.clouddn.com/vue-cli/1.png)
![image1](http://7xt4t7.com1.z0.glb.clouddn.com/vue-cli/2.png)
![image1](http://7xt4t7.com1.z0.glb.clouddn.com/vue-cli/3.png)

### What is expected?
No errors

### What is actually happening?
errors

**Comment by GuoQichen** [comment]
same issue, Is baseUrl a replacement for publicPath?

**Comment by yyx990803** [comment]
Cannot reproduce on Windows 10. Make sure you are using latest RC.
