### ISSUE TITLE
.eslintrc.js missing in default preset

### ISSUE THREAD

**Issue by yene** [vuejs/vue-cli#2066]
### Version
3.0.0-rc.10

### Node and OS info
v8.10.0

### Steps to reproduce
`vue create my-project`
`cat my-project/.eslintrc.js`

### What is expected?
That there is an `.eslintrc.js` file ready for adjustments.

### What is actually happening?
No, `.eslintrc.js`.

**Comment by yyx990803** [comment]
Did you create the project via UI? If not, what options did you choose?

**Comment by LinusBorg** [comment]
the default setting for config for any tool is to put it into package.json, if the tool supports it.

So you will find the config there.
