### ISSUE TITLE
Bug while building a web component: --port my-component?

### ISSUE THREAD

**Issue by katerlouis** [vuejs/vue-cli#2067]
### Version
3.0.0-rc.10

### Node and OS info
npm 6.2.0 / node 10.7.0

### Steps to reproduce
Use vue ui
Go to build 
Go to settings 
Change target to: webcomponent
Change Name to: my-component
Save settings
Press "build" 
Enjoy the error :(

### What is expected?
No error

### What is actually happening?
The following error is thrown:

```bash
$ vue-cli-service build --mode development --dest dist --target wc --port my-component--dashboard

 ERROR  --name must contain a hyphen when building a single web component.
```

---
Apparently the command that's being executed is wrong? (I'm a command line rookie)

`--port my-component` seems wrong to me
According to this link https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-build it should be 

```bash
--name my-component
```

right?

**Comment by katerlouis** [comment]
Oh yeah! I contributed :D:D

![image](https://user-images.githubusercontent.com/1983382/43824906-934366fe-9af3-11e8-96ed-cf00d85ab5fe.png)

**Comment by katerlouis** [comment]
Oh yeah! I contributed 8)

![image](https://user-images.githubusercontent.com/1983382/43824944-ae302466-9af3-11e8-89be-ef3a0919ba89.png)

**Comment by Akryum** [comment]
It's not released yet: https://github.com/vuejs/vue-cli/commits/dev

**Comment by katerlouis** [comment]
Oh okay– it was just a coincidence that rc.11 has come out after I posted the bug and before you fixed it– So I can expect the bug fixed rc.12? 

The always hated question: is there an ETA? :D
