### ISSUE TITLE
Custom plugin: changes to package.json in postProcessFiles are overwritten

### ISSUE THREAD

**Issue by ky-is** [vuejs/vue-cli#2072]
### Version
3.0.0-rc.10

### Node and OS info
Node 10.7.0, npm 6.2, Mac OS 10.13

### Steps to reproduce
Register a `postProcessFiles` hook in `generator.js` of a plugin, and overwrite the existing `files['package.json']` in the callback.

### What is expected?
Changes to `package.json` in the `postProcessFiles` callback should be written to disk.

### What is actually happening?
`postProcessFiles` passes a hash of `files` to the callback, including `package.json`. However, changes made to `package.json` are subsequently overwritten (unlike any other file).

**Comment by yyx990803** [comment]
You can't overwrite package.json. Use api.extendPackage.

**Comment by ky-is** [comment]
Thanks Evan. I want to modify the file structure not the field values, but I do understand the limitation.

It might be clearer to remove package.json from the files provided by api.render et al. as it can't be modified, though I suppose there are other reasons to want the file's contents.
