### ISSUE TITLE
"baseUrl" configuration does not work

### ISSUE THREAD

**Issue by mqhe2007** [vuejs/vue-cli#2073]
### Version
3.0.0-rc.10

### Node and OS info
8.11.2

### Steps to reproduce
> The following text is translated from Chinese into English through Google Translate. If there is any inaccuracy, please forgive me.

https://github.com/mqhe2007/vue-remote-module

1. Run the project in the github repository above.

2. Keep the existing values or modify the value of the "baseUrl" configuration in "vue.config.js".

3. Run "yarn build" to package.

4. Open the "dist/clkm.umd.js" file and find the "\_\_webpack_require\_\_.p" variable.

5. check the value of "\_\_webpack_require\_\_.p"

### What is expected?
The value of "\_\_webpack_require\_\_.p" should be equal to the value of the "baseUrl" configuration.

### What is actually happening?
The value of "\_\_webpack_require\_\_.p" is an empty string regardless of the value set in the "baseUrl" configuration.

**Comment by yyx990803** [comment]
It doesn't make sense to have a fixed `baseUrl` in a library. In library mode it is configured to dynamically determine public path based on the URL from which the main js file is loaded from.

**Comment by mqhe2007** [comment]
Thank you, this operation is cool! Meet the needs of remote static resource references.

**Comment by sodatea** [comment]
@wordythebyrd Use this polyfill: https://github.com/amiller-gh/currentScript-polyfill

**Comment by kvn29** [comment]
> It doesn't make sense to have a fixed `baseUrl` in a library. In library mode it is configured to dynamically determine public path based on the URL from which the main js file is loaded from: https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/commands/build/setPublicPath.js

If the library is a plugin installed with NPM and the plugin uses the lazy loading, webpack does not find the other pieces. :(

**Comment by lichenhao** [comment]
> It doesn't make sense to have a fixed `baseUrl` in a library. In library mode it is configured to dynamically determine public path based on the URL from which the main js file is loaded from: https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/commands/build/setPublicPath.js

Why don't support user define the publicPath with webpack configuration ?
