### ISSUE TITLE
Not responsive navbar

### ISSUE THREAD

**Issue by arin-kwak** [vuejs/vue-cli#2074]
### Version
3.0.0-rc.10

### Node and OS info
Chrome, MacOS High Sierra

### Steps to reproduce
When a browser window width of the web site is bigger than about 730px and is smaller than about 1050px, the top navbar is not quite good to see.

### What is expected?
seamless navbar

### What is actually happening?
overlapped elements

---
This may be not important issue, but it have scratched my mind. Could you guys fix this?

**Comment by arin-kwak** [comment]
Yes, navbar of vue-cli’s website

**Comment by LinusBorg** [comment]
Oh, so it's not about the CLI UI.

**Comment by yyx990803** [comment]
There's a pending fix in VuePress, closing here.
