### ISSUE TITLE
Ability to add prefix to filename generated

### ISSUE THREAD

**Issue by luaz** [vuejs/vue-cli#2075]
### What problem does this feature solve?
Usually `npm run build` will generate the following output:

```text
dist/static/pack/js/chunk-vendors.82e5bca0.js
dist/static/pack/js/console.c4f1ea0a.js
dist/static/pack/js/app.d18fb3c8.js
dist/static/pack/css/chunk-vendors.37ae32f6.css
dist/static/pack/css/app.7ae1ca78.css
dist/static/pack/css/console.915b5f85.css
```

It would be nice to have the ability to add `prefix` (e.g. `vue-`) to the generated filename, such as `vue-app.hash.*`, `vue-console.hash.*`, etc.

Reason is I am using another old build system which generate files of the same name (app, vendor, etc), and I wanted to add prefix to vue generated ones to avoid confusion.

I can overwrite `vue.config.js` to generate the filename, but it won't be easy or straightforward, as I also need to put in hash, different configuration for app, vendor, module and css.

```
  configureWebpack: {
    output: {
      filename: 'vue-[name].js', // this will change app.js only, not css, vendor and modules
    },
  }
```
I thought of changing the filename by renaming the file after it's generated, but on demand module loading will still use the original filename. `assetsDir` can specify directory of css/js, but not prefix filename.

### What does the proposed API look like?
vue.config.js

```javascript
module.exports = {
  filenamePrefix: 'vue-`',
}
```

**Comment by yyx990803** [comment]
I think this is too niche a use case for an extra config. You can just nest it under a directory instead.
