### ISSUE TITLE
Why configureWebpack instead of just webpack?

### ISSUE THREAD

**Issue by cbo317110** [vuejs/vue-cli#2077]
### What problem does this feature solve?
- I see `configureWebpack` very wordy.
- What you folks think about just `webpack`?
- I know that has also `chainWebpack` option but it can be solved with encapsulation...

### What does the proposed API look like?
```javascript
module.exports = {
  webpack: {
   config, // Object or Function
   chain // Function
  }
}
```

**Comment by LinusBorg** [comment]
because it's more expressive.
