### ISSUE TITLE
Add msg about possible existing file overwrite

### ISSUE THREAD

**Issue by whyvez** [vuejs/vue-cli#208]
I ran the cli over an existing folder with an index.html file and it was overwritten. Would be nice if there was a warning about this when the cli is invoked.

**Comment by zigomir** [comment]
@whyvez `vue-cli` will prompt you with `? Target directory exists. Continue? (Y/n)` question if you're trying to init a project into existing directory. Also, if you're trying to init it into current directory it will prompt you with: `? Generate project in current directory? (Y/n)`.
