### ISSUE TITLE
new typescript project without plugin-babel can't compile tsx

### ISSUE THREAD

**Issue by troy351** [vuejs/vue-cli#2081]
### Version
3.0.0-rc.10

### Node and OS info
Node 9.2.0 / npm 6.2.0 / Windows 10

### Steps to reproduce
- create project with only typescript plugin
- change `App.vue` into tsx render function
- build project

### What is expected?
build successful

### What is actually happening?
shows error
```
Module parse failed: Unexpected token
You may need an appropriate loader to handle this file type.
```

**Comment by sodatea** [comment]
TypeScript does not natively support transpiling jsx syntax to vue render functions, so we configured it to preserve jsx after transpilation. That's why babel is required.
