### ISSUE TITLE
How to delete, update and add ressources to the index.html through.

### ISSUE THREAD

**Issue by ommehaz** [vuejs/vue-cli#2084]
### What problem does this feature solve?
I am trying to figure out, how I can move favicon from the index.html file that the build outputs. I also want to add other ressources to the html file. I can't find any help from documentation and google.

### What does the proposed API look like?
I need to change the favicon or maybe i need to remove it. How can I accomplish this.

**Comment by yyx990803** [comment]
Edit `public/index.html`.
