### ISSUE TITLE
In vue.config.js,when baseUrl is set empty string( "" ), can the CSS file can be build into the css folder(not root folder)?

### ISSUE THREAD

**Issue by zhongyue2332** [vuejs/vue-cli#2088]
### What problem does this feature solve?
In multi-page application,there may be a lot of CSS files,it looks very messy if CSS files are not in the folder

### What does the proposed API look like?
Please add a css configuration item in vue.config.js whether build CSS files into folder or not!

**Comment by LinusBorg** [comment]
No it can't.
