### ISSUE TITLE
plugin to extend options vue.config.js

### ISSUE THREAD

**Issue by cuijing1031** [vuejs/vue-cli#2090]
### What problem does this feature solve?
we have a plugin.  This plugin will generate some data into vue.config.js when it is invoked.  we can't put this data into package.json, because it depend on some modules. for example:

```js
const path = require('path')
module.exports = {
   css: {
      extract: true,
      loaderOptions: {
        stylus: {
          'resolve url': true,
          import:  [path.resolve(__dirname, './src/theme')]
        }
      }
    }
}
```
if we use api.render to generate vue.config.js,  it can work. But if another plugin generate vue.config.js,  the old vue.config.js will be overwrited. 

### What does the proposed API look like?
maybe like api.injectImports  and  api.injectRootOptions

**Comment by Akryum** [comment]
Use `api.extendPackage({ vue: {} })`.

**Comment by cuijing1031** [comment]
@Akryum my config depend on some node modules.  like `import:  [path.resolve(__dirname, './src/theme')]`.  if we put this in package.json,  it won't work

**Comment by sodatea** [comment]
For such usages, you don't need to explicitly extract these configs to `vue.config.js`.
See [Service Plugin](https://cli.vuejs.org/dev-guide/plugin-dev.html#service-plugin)

**Comment by LinusBorg** [comment]
To me, it feels like we should not allow/encourage plugins to mess with the vue.config.js file.

This file is *not* a template, it's the config file for the cli and meant to hold options and customizations that users should do manually.

**Comment by Akryum** [comment]
`vue.config.js` should be used by plugins to expose settings:

```js
module.exports = {
  pluginOptions: {
    myPlugin: { /* ... */ }
  }
}
```

It's okay to initialize those options there, for example if you have prompts for invocation.

**Comment by cuijing1031** [comment]
Because the final vue.config.js depends on prompts result. Full template of vue.config.js is:
```js
<%_ if (theme) { _%>
const path = require('path')
<%_ } _%>
module.exports = {
  baseUrl: '/',
  productionSourceMap: false,
  css: {
    extract: true,
    loaderOptions: {
      stylus: {
        'resolve url': true,
        import: <%- theme ? `[path.resolve(__dirname, './src/theme')]` : `[]` %>
      }
    }
  },
 pluginOptions: {
    'myPlugin': {
     <%_ if (theme) { _%>
      theme: true<%_ } _%>
    }
  }
}

```
and when this plugin is called by vue-cli-service, it will use the 'theme' and 'css' config

**Comment by Akryum** [comment]
Don't do that, you will override user config.

**Comment by cuijing1031** [comment]
what's the correct method to generate this config? In this case, `path.resolve` isn't allow in package.json and template of vue.config.js will override user config

**Comment by Akryum** [comment]
See my previous comment. Also you can resolve the theme directory in your plugin. Why are you doing it in vue config?

**Comment by cuijing1031** [comment]
I got it. Thanks!

**Comment by Akryum** [comment]
👍
