### ISSUE TITLE
ERROR while running task C:\Users\xxxxxx\GitHub\xxxx-app:serve with message'spawn vue-cli-service ENOENT'

### ISSUE THREAD

**Issue by abarke** [vuejs/vue-cli#2096]
### Version
3.0.0-rc.10

### Node and OS info
Windows 10 Enterprise / Node 8.9.1 / Yarn 1.7.0 / GitBash (MINGW64)

### Steps to reproduce
1. Run default "serve" task
2. Stop default "serve" task

### What is expected?
A clean shutdown of the task without error

### What is actually happening?
ERROR while running task C:\Users\xxxx\GitHub\xxxx-app:serve with message'spawn vue-cli-service ENOENT'

{ Error: spawn vue-cli-service ENOENT
at notFoundError (C:\Users\xxxx\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:6:26)
at verifyENOENT (C:\Users\xxxx\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:40:16)
at ChildProcess.cp.emit (C:\Users\xxxx\AppData\Local\Yarn\Data\global\node_modules\cross-spawn\lib\enoent.js:27:25)
at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
code: 'ENOENT',
errno: 'ENOENT',
syscall: 'spawn vue-cli-service',
path: 'vue-cli-service',
spawnargs: [ 'serve', '--mode', 'development', '--dashboard' ] }

**Comment by yyx990803** [comment]
Are you using the UI?

**Comment by abarke** [comment]
Yes!

**Comment by focussing** [comment]
Creating a new Vue cli 3 project via commandline also crashes

**Comment by focussing** [comment]
Vue CLI v3.0.0-rc.10
✨  Creating project in /Users/raymond/stack/sites/xml.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/cli-plugin-babel@^3.0.0-rc.11
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'xml'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raymond/.npm/_logs/2018-08-07T15_32_34_730Z-debug.log
 ERROR  command failed: npm install --loglevel error

**Comment by Akryum** [comment]
@focussing Please create a new issue, yours is unrelated to this one.

**Comment by CraigHead** [comment]
Same is happening here. Using 3.0.0-rc.11. Stopping npm serve from the UI causes an error in the terminal.

**Comment by CraigHead** [comment]
Updated to 3.0.0 and this is still occurring.

**Comment by germsb** [comment]
w10 pro, node 10.5.0, vue/cli 3.0.0, vue ui.

Stopping server also causes an error
- in ui 
`Error while running task C:\dev\testssr10:serve with message 'spawn vue-cli-service ENOENT'`
- in terminal
`{ Error: spawn vue-cli-service ENOENT
    at notFoundError (C:\Users\germs\AppData\Roaming\npm\node_modules\@vue\cli\node_modu
les\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Users\germs\AppData\Roaming\npm\node_modules\@vue\cli\node_modul
es\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Users\germs\AppData\Roaming\npm\node_modules\@vue\cli\no
de_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn vue-cli-service',
  path: 'vue-cli-service',
  spawnargs: [ 'serve', '--mode', 'development', '--dashboard' ] }`

**Comment by NasirQrn** [comment]
win10, node 10.5.0, vue/cli 3.0.0, 
vue ui:
Stopping server/build:
:serve/build with message 'spawn vue-cli-service ENOENT'

in terminal:
serve-->
{ Error: spawn vue-cli-service ENOENT  at notFoundError (C:\Users\dell\AppData\Local\Yarn\Data\global\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:6:26) at verifyENOENT (C:\Users\dell\AppData\Local\Yarn\Data\global\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:40:16)  at ChildProcess.cp.emit (C:\Users\dell\AppData\Local\Yarn\Data\global\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn vue-cli-service',
  path: 'vue-cli-service',
  spawnargs: [ 'serve', '--mode', 'development', '--dashboard' ] }


build-->
{ Error: spawn vue-cli-service ENOENT at notFoundError (C:\Users\dell\AppData\Local\Yarn\Data\global\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:6:26) at verifyENOENT (C:\Users\dell\AppData\Local\Yarn\Data\global\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:40:16) at ChildProcess.cp.emit (C:\Users\dell\AppData\Local\Yarn\Data\global\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:27:25) at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn vue-cli-service',
  path: 'vue-cli-service',
  spawnargs:
   [ 'build', '--mode','production', '--dest', 'dist', '--target', 'app', '--dashboard' ] }

**Comment by admin00001** [comment]
what should i do? it happen after i remove the register-server-worker.js and the relative files.

**Comment by yyx990803** [comment]
ping @Akryum

**Comment by topcatarg** [comment]
Same is happening with the last release.. need any log info or something to help you with?

**Comment by Akryum** [comment]
Note happening on linux node 8.9.1 either, so looks like a Windows-related issue.

**Comment by Akryum** [comment]
I did some research but still don't have any idea why node is throwing this ENOENT error when killing the process... It's not a critical issue anyway, since the processes seem to be correctly killed.

**Comment by andrescellini** [comment]
happend to me also, windows 10. 

When i stop the serve task or when i try to build it... let me know if its helps to share something to solve it.

**Comment by cockneychops** [comment]
I'm getting the same issue but only when I run "npm run build" and I have a style (CSS) included in a component. It works fine without any styles in components.

Windows: 10
Node : 9.9.0
npm: 6.4.0
Vue: 2.5.17
VuuCLI: 3.0.0

**Comment by lbogdan** [comment]
Fixing this is not trivial, as we can't easily distinguish between this "false" `ENOENT` caused by Windows process behavior and a legitimate `ENOENT` - like when trying to execute a non-existing command or setting `cwd` to a non-existing folder (are there others?).

So what we could do:
- in the process error handler check if we're on Windows (`process.platform === 'win32'`) and if the error is `ENOENT`, if yes then
  - check if the command's stderr contains `'foo' is not recognized as an internal or external command,
operable program or batch file.` and
  - check if `cwd` exists and it's a folder
  - if both are false it means we have a "false" `ENOENT`, so call the `exit` handler with the `code` set to `null`.

**Comment by Akryum** [comment]
> check if the command's stderr contains 'foo' is not recognized as an internal or external command, operable program or batch file.

Except error message are localized.

**Comment by lbogdan** [comment]
Might not be, I just tested on a Romanian localized Windows, and that error is still in English.

**Comment by Akryum** [comment]
![image](https://user-images.githubusercontent.com/2798204/44313273-dc24ef80-a405-11e8-9107-37495447c0b3.png)

**Comment by lbogdan** [comment]
Yeah, sadly I get the same with French. Looks like they forgot to translate this to Romanian...

Ok, another option would be to look for the command in `PATH`, so that we're sure that it exists, and if we get a `ENOENT` it's not because the command doesn't exist.

**Comment by alfiesalano001** [comment]
1. delete "node_modules" folder
2. run - npm install
![2019-03-06_9-41-42](https://user-images.githubusercontent.com/48016132/53850786-69710f80-3ff7-11e9-8cdc-80b83d6fd2e6.png)

**Comment by Neoniq** [comment]
delete folder doesn't work for me.
What works is just basically remove & symbol from path.
