### ISSUE TITLE
Prompt description and author fields have become one

### ISSUE THREAD

**Issue by nblackburn** [vuejs/vue-cli#21]
When prompted for the description the script seems to display both the description and author fields at the same time blocking input for the description.

```bash
Project description: (A Vue.js project) Author: (Nathaniel Blackburn <support@nblackburn.uk>) this is a test
```

**This results in the description ending up the author field.**

**Comment by yyx990803** [comment]
Is this still happening?

**Comment by nblackburn** [comment]
I will take a look later on today and let you know

**Comment by chrisvfritz** [comment]
@nblackburn Just pinging on this. Is it fixed?

**Comment by chrisvfritz** [comment]
Closing for now, until/unless this happens for someone again.

**Comment by nblackburn** [comment]
@chrisvfritz Terribly sorry about this, never got chance to look but am going to check now and report back in a few.

**Comment by nblackburn** [comment]
Works without a hitch, nice job!
