### ISSUE TITLE
引用H5对象报错

### ISSUE THREAD

**Issue by fanly** [vuejs/vue-cli#210]
ready: function () {
    var file = new FileReader()
    file.readAsDataURL(this.files[0].file)
  }

error  no-undef  'FileReader' is not defined

**Comment by zigomir** [comment]
I really can't see how this is `vue-cli` related.

Otherwise, if you're using `FileReader` see browser compatibility table here: https://developer.mozilla.org/en-US/docs/Web/API/FileReader

**Comment by egoist** [comment]
I guess it's just an eslint error 😓
