### ISSUE TITLE
cannot create new project because there is no package of 3.0.0-rc.11 on npm registry now.

### ISSUE THREAD

**Issue by skatpgusskat** [vuejs/vue-cli#2100]
### Version
3.0.0-rc.10

### Node and OS info
node 8.9.0 / npm 6.1.0 / windows 10

### Steps to reproduce
vue create <project name>

### What is expected?
creating project well

### What is actually happening?
fail with error below
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/cli-plugin-babel@^3.0.0-rc.11
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'emote-sync-page'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-08-07T15_42_40_794Z-debug.log
 ERROR  command failed: npm install --loglevel error --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist

---
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/cli-plugin-babel@^3.0.0-rc.11
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'emote-sync-page'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-08-07T15_42_40_794Z-debug.log
 ERROR  command failed: npm install --loglevel error --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist

**Comment by Akryum** [comment]
We are aware of this issue. npm publish has problems right now, and @yyx990803 started a release that was interrupted half-way through because of this.

**Comment by Akryum** [comment]
Relevant status report from npm: https://status.npmjs.org/incidents/m6ysvwmc8k7l

**Comment by skatpgusskat** [comment]
It's successfully work now! Please confirm.

**Comment by yyx990803** [comment]
All packages should have been updated to rc11 now.

**Comment by focussing** [comment]
Confirmation it works. Good job guys!
