### ISSUE TITLE
Passing Options to Pre-Processor Loaders with less-loader doesn't work

### ISSUE THREAD

**Issue by JasenWu** [vuejs/vue-cli#2105]
### Version
3.0.0-rc.10

### Node and OS info
node : v8.11.3 ,npm : 6.3.0  ,OS:10.13.1 (17B1003)

### Steps to reproduce
1、下载vue-cli 3并安装
2、自定义安装Manually select features，选择了Babel、Router、Vuex、CSS Pre-processors、Linter / Formatter
3、Use history mode for router 选择 no
4、Pick a CSS pre-processor 选择 less
5、Pick a linter / formatter config 选择 ESLint   Standard config 
6、Pick additional lint features  两个全选 Lint on save &  Lint and fix on commit
7、Pick additional lint features 先择 In dedicated config files
8、保存配置，选 no ，直到自动安装完成。
9、在根目录增加vue.config.js 并写入如下内容：
module.exports = {
  css: {
    loaderOptions: {
    
      less: {
     
        data: `@import "@/variables.less";`
      }
    }
  }
}

10、新建  src/variables.less 并写入变量 @color:red; 在src/App.vue  style部分 #app{}里重写color为color:@color

11、重启 npm run serve

12、显示 报错信息，未定义变量 @color （特别试了下 预处理 scss 没有这种情况。）

### What is expected?
work well

### What is actually happening?
Failed to compile.

./src/App.vue?vue&type=style&index=0&lang=less& (./node_modules/css-loader??ref--10-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/lib??ref--10-oneOf-1-2!./node_modules/less-loader/dist/cjs.js??ref--10-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=less&)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):

  text-align: center;
  color: @color;
       ^
Variable @color is undefined
      in /Users/Jason/workspace/vuecli3/vuecli-test/src/App.vue?vue&type=style&index=0&lang=less& (line 17, column 9)

---
特别试了下 预处理 scss 没有这种情况。只出现在less

**Comment by LinusBorg** [comment]
```
data: `@import "~@/variables.less";`
```
See: https://github.com/webpack-contrib/less-loader#webpack-resolver

If that doesn't help, please provide a repository with an actual reproduction.

**Comment by Akryum** [comment]
`less-loader` doesn't have the `data` option. Please see [vue cli documentation](https://cli.vuejs.org/guide/css.html#automatic-imports).

**Comment by adwerrd** [comment]
how to handle less global variable in `vue.config.js`?

**Comment by LinusBorg** [comment]
see the link @akryum posted in the comment before yours.
