### ISSUE TITLE
静态图片大小在多少的以内会被处理为内联

### ISSUE THREAD

**Issue by yangtuantuan** [vuejs/vue-cli#2106]
### Version
3.0.0-rc.10

### Node and OS info
node 8.11.1 / npm 5.6.0 / windows 7

### Steps to reproduce
vue ui创建dome

### What is expected?
文档中写的是10kb内的会被处理为内联，
logo.png只有6.68kb应该是被处理为内联

### What is actually happening?
实际上logo.png作为了一个单独的请求

---
如何自主的配置如何处理图片？

**Comment by sodatea** [comment]
文档错了，rc.1 之后是 4KB 以上会被处理为内联。
可以自行在 `vue.config.js` 对 `url-loader` 作配置
```js
module.exports = {
  chainWebpack: config => {
    config.module
      .rule('images')
      .use('url-loader')
        .loader('url-loader')
        .tap(options => Object.assign(options, { limit: 10240 }))
  }
}
```
