### ISSUE TITLE
vue create 模板创建的meta标签在某些情况下有bug，导致浏览transform异常

### ISSUE THREAD

**Issue by 541595308** [vuejs/vue-cli#2107]
### Version
3.0.0-rc.11

### Node and OS info
Node 10.6.0/ npm 6.2.0

### Steps to reproduce
vim test.html

<!DOCTYPE html>
<html>
  <head>
    <meta name=viewport content="width=device-width,initial-scale=1.0">
    
    
    <style>
      body{
        overflow: hidden;
      }
      .xheader{
        height: 40px;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        right: 0;
        background-color: #3B4960;
        text-align: center;
      }
      .xpage{
        position: absolute;
        left: 0;
        top: 0;
        right: 0;
        bottom: 0;
        overflow: hidden;
        transform: translate3d(84%, 0, 0);
        background-color: rebeccapurple;
      }
      </style>
  </head>
  <body>
    <header class="xheader">xheader</header>
    <div class="xpage"></div>
  </body>
</html>

### What is expected?
移动端（pc模拟也一样）
.header(fixed定位)的宽度不等于body的宽度，body出滚动条 { overflow: hidden } 并不能隐藏溢出，查看body宽度确又是正确的宽度(html宽度)。
似乎transform的元素出现在了一个神奇的层里面，但同时这个层和fixed元素的父元素是同一层，fixed元素宽度计算出错

### What is actually happening?
因为vue-cli项目默认模板去掉了minimum-scale=1和user-scalable=no，导致webkit解析transform的时候出bug(可能是webkit的bug?)，viewport里面添加该字段解决该bug。

---
建议在meta字段里面添加minimum-scale=1或user-scalable=no，还有能否解答下这种怪异的行为。

**Comment by yyx990803** [comment]
这跟 Vue CLI 没有任何关系。你想添加的话自己添加就行了。

**Comment by 541595308** [comment]
但是vue create test创建的项目，默认的模板就是这样呀。

**Comment by yyx990803** [comment]
默认的模版可以按你的需要修改，user-scalable=no 通常被认为是 accessibility 的 bad practice.

**Comment by bigbanana** [comment]
什么鬼？你运行下那段代码呢，仔细分析一下，是移动端哦chrome模拟也行。和BFC Stacking Context感觉没啥关系。这段代码要的效果就是xpage的transform导致fixed元素的宽度变了,而且变得很神奇。

**Comment by bigbanana** [comment]
呃，貌似和transform无关，即使设置xpage宽度也会撑开fixed元素

**Comment by sodatea** [comment]
😂我不是很清楚你具体要达成什么效果，不过解释一下为什么提 BFC 和 Stacking Context：

1. 首先 fixed 元素是根据 viewport 或者最近的 transform 属性非 none 的元素定位的。
2. 然后 viewport 在你这个例子里被撑开了，所以 fixed 元素宽度不对。
3. viewport 不是被 body 撑开的，而是被 xpage 撑开的
4. 解决办法：把 xpage 限制在 body 里，不要影响 viewport
5. 这一步我误会了😂我以为你是想用 BFC，没反应过来 hidden 本来就有不让内容溢出的效果……不过 `overflow: hidden` 在移动端是会失效的，这个可以 Google 到很多问题……
6. 总之，给 body 加 transform 属性就可以为它创建新的 stacking context 了，然后页面就能正常了。

**Comment by bigbanana** [comment]
呃，非常感谢你的研究和讨论。body加transform会解决xheader的宽度问题，但是xpage又会出问题了。其实我想表达的意思就是执行上面的代码后，xheader的宽度还是变宽了（只有让浏览器重绘才能让他的宽度再正常回来），只是很困惑这种奇怪的现象，而且只有移动端会发生。添加user-scalable=no或minimum-scale=1就能解决这个bug，但是vue-cli默认模板是没有这句的😂，所以才有这个issus。
