### ISSUE TITLE
Provide Better Support for SVG's

### ISSUE THREAD

**Issue by RehanSaeed** [vuejs/vue-cli#2108]
### What problem does this feature solve?
SVG's can be used in a number of ways:

1. SVG's can be used in standard img tags, the same way png/jpg are used.

`<img src="assets/foo.svg"/>`

2. In CSS where the SVG should be inlined into the CSS itself. You might also want to provide a custom fill or stroke colour.

```
.foo {
  background-image: url("../assets/foo.svg?inline&fill=#fff");
}
```

3. SVG icons are very small and ideally should be merged into a sprite sheet, then the SVG icon sprite can be referred to using the svg  use tag. Once again, you might want to provide a custom fill or stroke colour for your icon.

```
  <svg aria-hidden="true" role="img">
    <use :xlink:href="/assets/sprite-sheet.svg#foo?fill=#fff" />
  </svg>
```

I've written a custom vue.config.js that allows all of this like so:

```
// WebPack loaders required in package.json
"svg-sprite-loader": "^3.8.0",
"svg-transform-loader": "^1.2.0",
"svg-url-loader": "^2.3.2",
"svgo-loader": "^2.1.0",
```

```
const SpriteLoaderPlugin = require("svg-sprite-loader/plugin");

function getSvgUrlLoaders() {
  const loaders = [
    {
      loader: "svg-url-loader"
    },
    {
      loader: "svg-transform-loader"
    }
  ];
  if (process.env.NODE_ENV === "production") {
    loaders.push({
      loader: "svgo-loader"
    });
  }
  return loaders;
}

function getSvgSpriteLoaders() {
  const loaders = [
    {
      loader: "svg-sprite-loader",
      options: {
        esModule: false,
        extract: true,
        spriteFilename: "assets/icons/icons.svg"
      }
    },
    {
      loader: "svg-transform-loader"
    }
  ];
  if (process.env.NODE_ENV === "production") {
    loaders.push({
      loader: "svgo-loader"
    });
  }
  return loaders;
}

module.exports = {
  chainWebpack: config => {
    // Delete the existing rule for svg.
    config.module.rules.delete("svg");
  },
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.(svg)(\?.*)?$/,
          oneOf: [
            {
              resourceQuery: /inline/,
              use: getSvgUrlLoaders()
            },
            {
              use: getSvgSpriteLoaders()
            }
          ]
        }
      ]
    },
    plugins: [new SpriteLoaderPlugin()]
  }
};
```

### What does the proposed API look like?
1. SVG's can be used in standard img tags, the same way png/jpg are used.

`<img src="assets/foo.svg"/>`

2. In CSS where the SVG should be inlined into the CSS itself. You might also want to provide a custom fill or stroke colour.

```
.foo {
  background-image: url("../assets/foo.svg?inline&fill=#fff");
}
```

3. SVG icons are very small and ideally should be merged into a sprite sheet, then the SVG icon sprite can be referred to using the svg  use tag. Once again, you might want to provide a custom fill or stroke colour for your icon.

```
  <svg aria-hidden="true" role="img">
    <use :xlink:href="/assets/sprite-sheet.svg#foo?fill=#fff" />
  </svg>
```

**Comment by yyx990803** [comment]
This seems to be [implementable via a plugin](https://cli.vuejs.org/dev-guide/plugin-dev.html).  I think it'd be nice to build one for this (`vue-cli-plugin-svg`)?

**Comment by dyingangel666** [comment]
I'm feeling with you... Run into the same issues with svg sprites which should be referenced dynamically via xlink:href and the path isn't resolved by webpack. But i also understand Evan's answer. Vue is a fucking lightweight framework optimized for best performance and what can i say... i like it :D I'm coming from angular 1.x and now 2+ and i like this completely new lightweight vue.js approach...
