### ISSUE TITLE
Cannot find module 'vue-template-compiler/package.json'

### ISSUE THREAD

**Issue by H1D** [vuejs/vue-cli#2109]
### Version
3.0.0-rc.11

### Node and OS info
node v10.8.0, npm 6.2.0, macOS High Sierra

### Steps to reproduce
create empty project and try to serve it
`vue create test -p default && cd test && vue serve src/main.js`

### What is expected?
serving empty project

### What is actually happening?

```
Error: Cannot find module 'vue-template-compiler/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at api.chainWebpack.webpackConfig (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/config/base.js:61:32)
    at webpackChainFns.forEach.fn (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/Service.js:209:40)
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/Service.js:209:26)
    at Service.resolveWebpackConfig (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/Service.js:213:48)
    at PluginAPI.resolveWebpackConfig (/usr/local/lib/node_modules/@vue/cli-service-global/node_modules/@vue/cli-service/lib/PluginAPI.js:115:25)
```

---
`npm run server` (which is linked to `vue-cli-service serve`) works, but `vue serve` should also work according to `vue serve --help`

**Comment by sodatea** [comment]
Since rc.11 we make `vue-template-compiler` a peer dependency of `@vue/cli-service`, so installing `@vue/cli-service-global` won't automatically install `vue-template-compiler`.

A temporary workaround is to manually run `npm i -g vue-template-compiler`

**Comment by yyx990803** [comment]
Closed via c42cb949

**Comment by zlab** [comment]
@yyx990803 
cli-service同样有这个问题

`@vue/cli-service/package.json`
```
 "peerDependencies": {
    "vue-template-compiler": "^2.0.0"
  },
```

**Comment by tommcclean** [comment]
I tried using Vue-CLI (@vue/cli@3.0.1) in vscode.

Creating a new project and then trying to run npm run serve doesn't work for me, I get the same error reported here, does this take some time to become available in the CLI?

The workaround doesn't work for me.

Error: Cannot find module 'vue-template-compiler/package.json'

**Comment by sodatea** [comment]
@zlab cli-service 的这个配置倒不会产生问题，因为 cli-service 肯定是在 Vue CLI 创建的项目里被引用的，而默认的项目模板里已经将 vue-template-compiler 作为 devDependencies 引入了

https://github.com/vuejs/vue-cli/blob/d0320eb8c2bc6959e242332b22081f2889b3e6c9/packages/%40vue/cli-service/generator/index.js#L12-L14

**Comment by zlab** [comment]
@sodatea 我不是用cli创建的默认模版

**Comment by sodatea** [comment]
@zlab 那请自行添加到项目的 `devDependencies` 中。
`@vue/cli-service-global` 之所以需要我们加上依赖是因为这种情况下用户并没有办法自己管理依赖。`@vue/cli-service` 的情况不同。

**Comment by OrenciucEvghenii** [comment]
I DONT SPEAK CHINESE FFS

**Comment by raphael10-collab** [comment]
@sodatea I added vue-template-compiler but the problem persists..


    (base) marco@pc01:~/webMatters/electronMatters/GGC-Electron$ yarn add vue-template-compiler
    yarn add v1.22.5
    warning ../package.json: No license field
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    info fsevents@2.1.3: The platform "linux" is incompatible with this module.
    info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
    info fsevents@1.2.13: The platform "linux" is incompatible with this module.
    info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning " > element-ui@2.13.2" has incorrect peer dependency "vue@^2.5.17".
    warning " > vue-class-component@7.2.5" has incorrect peer dependency "vue@^2.0.0".
    warning " > vuex@3.5.1" has incorrect peer dependency "vue@^2.0.0".
    warning " > vuex-class@0.3.2" has incorrect peer dependency "vue@^2.5.0".
    warning " > @vue/test-utils@1.0.5" has incorrect peer dependency "vue@2.x".
    warning " > vue-types@2.0.1" has incorrect peer dependency "vue@^2.0.0".
    [4/4] Building fresh packages...
    warning "vue-template-compiler" is already in "devDependencies". Please remove existing entry first before adding it to    
    "dependencies".
    success Saved 1 new dependency.
    info Direct dependencies
    └─ vue-template-compiler@2.6.12
    info All dependencies
    └─ vue-template-compiler@2.6.12
    $ electron-builder install-app-deps
      • electron-builder  version=22.7.0
      • rebuilding native dependencies  dependencies=better-sqlite3@5.4.3, fd-lock@1.1.1, integer@2.1.0, sodium-native@2.4.9,  
    utp-native@2.2.1, sodium-native@3.2.0, sodium-native@3.2.0, sodium-native@3.2.0, sodium-native@3.2.0
                                        platform=linux
                                        arch=x64
      • rebuilding native dependency  name=fd-lock version=1.1.1
      • rebuilding native dependency  name=better-sqlite3 version=5.4.3
      • rebuilding native dependency  name=integer version=2.1.0
      • rebuilding native dependency  name=sodium-native version=2.4.9
      • rebuilding native dependency  name=utp-native version=2.2.1
      • rebuilding native dependency  name=sodium-native version=3.2.0
      • rebuilding native dependency  name=sodium-native version=3.2.0
      • rebuilding native dependency  name=sodium-native version=3.2.0
      • rebuilding native dependency  name=sodium-native version=3.2.0
    Done in 49.53s.
    (base) marco@pc01:~/webMatters/electronMatters/GGC-Electron$ yarn electron:serve
    yarn run v1.22.5
    warning ../package.json: No license field
    $ vue-cli-service electron:serve
     INFO  Starting development server...
     ERROR  Error: Cannot find module '@vue/compiler-sfc/package.json'
    Require stack:
    - /home/marco/webMatters/electronMatters/GGC-Electron/node_modules/@vue/cli-service/lib/config/base.js
    - /home/marco/webMatters/electronMatters/GGC-Electron/node_modules/@vue/cli-service/lib/Service.js
    - /home/marco/webMatters/electronMatters/GGC-Electron/node_modules/@vue/cli-service/bin/vue-cli-service.js
    Error: Cannot find module '@vue/compiler-sfc/package.json'
    Require stack:
    - /home/marco/webMatters/electronMatters/GGC-Electron/node_modules/@vue/cli-service/lib/config/base.js
    - /home/marco/webMatters/electronMatters/GGC-Electron/node_modules/@vue/cli-service/lib/Service.js
    - /home/marco/webMatters/electronMatters/GGC-Electron/node_modules/@vue/cli-service/bin/vue-cli-service.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
        at Function.Module._load (internal/modules/cjs/loader.js:899:27)
        at Module.require (internal/modules/cjs/loader.js:1090:19)
        at require (internal/modules/cjs/helpers.js:75:18)
        at /home/marco/webMatters/electronMatters/GGC-Electron/node_modules/@vue/cli-service/lib/config/base.js:115:30
        at /home/marco/webMatters/electronMatters/GGC-Electron/node_modules/@vue/cli-service/lib/Service.js:236:40
        at Array.forEach (<anonymous>)
        at Service.resolveChainableWebpackConfig (/home/marco/webMatters/electronMatters/GGC-Electron/node_modules
    /@vue/cli-service/lib/Service.js:236:26)
        at Service.resolveWebpackConfig (/home/marco/webMatters/electronMatters/GGC-Electron/node_modules/@vue/cli-
    service/lib/Service.js:240:48)
        at PluginAPI.resolveWebpackConfig (/home/marco/webMatters/electronMatters/GGC-Electron/node_modules/@vue/cli-
    service/lib/PluginAPI.js:132:25)
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mirsella** [comment]
@raphael10-collab `npm i -g @vue/compiler-sfc` vue-template-compiler is deprecated for vue 3 i think

**Comment by lc-thomas** [comment]
> I DONT SPEAK CHINESE FFS

why not ?

**Comment by juresaht2** [comment]
> A temporary workaround is to manually run `npm i -g vue-template-compiler`

Installing this globally didn't fix it for me, but installing it locally did.

**Comment by chhaller** [comment]
running this worked for me (as said previously, not globally):
``npm i  vue-template-compiler``
