### ISSUE TITLE
是否考虑支持通过配置使得某些文件跳过模板替换，直接拷贝

### ISSUE THREAD

**Issue by crossjs** [vuejs/vue-cli#211]
假设一个模板库存在大量的 Components，就会有非常多的 `{{...}}` 需要手动修改为 `\{{...}}`，
如果可以支持通过配置使得某些文件跳过模板替换，直接拷贝，模板开发体验会更好。

如果能支持自定义 interpolate delimiter 也可以，但是据我所知 Handlebars 是不支持的。
或者能考虑支持自定义模板引擎？

**Comment by yyx990803** [comment]
可以在 `meta.json` 里面加一个 `skipInterpolation` 选项。
