### ISSUE TITLE
Customize or disable serve console message

### ISSUE THREAD

**Issue by chasegiunta** [vuejs/vue-cli#2115]
### What problem does this feature solve?
In non-SPA setups, the server may be operating on `localhost:8080` and serving assets from there, but the site is being viewed on a separate domain `my-php-site.test`. In order for HMR to work correctly we enabled things like `headers: { 'Access-Control-Allow-Origin': '*' }` & set our baseUrl as 
```
baseUrl: process.env.NODE_ENV === 'production'
  ? '/'
  : 'http://localhost:8080/',
```

This works great, except the dev will receive this message running `serve`:

```
App running at:
  - Local:   http://localhost:8080/http://localhost:8080/ 
  - Network: http://10.0.1.12:8080/http://localhost:8080/
```

### What does the proposed API look like?
Potentially, if a `serveMessage` is provided, it will override any console messages.

**Comment by yyx990803** [comment]
That's the wrong way to enable HMR. Use `devServer.public` for that purpose.

**Comment by chasegiunta** [comment]
@yyx990803 if you set `devServer.public` to `localhost:8080` it's ignored. Requests fallback to `window.location`

**Comment by yyx990803** [comment]
You should set `devServer.public` to `my-php-site.test` to make HMR work.

**Comment by chasegiunta** [comment]
@yyx990803 in the older `vue-webpack` template, we were able to set `devServer.publicPath` to `http://localhost:8080` to achieve what we needed since [it supports full URLs](https://webpack.js.org/configuration/dev-server/#devserver-publicpath), but that option is [being overridden](https://github.com/vuejs/vue-cli/blob/3894a4aba13c88d65319ff849e820ea7833ccb0b/packages/%40vue/cli-service/lib/commands/serve.js#L146) to `options.baseUrl` anyway (which may be a valid requirement), hence the reasoning for the FR.

**Comment by chasegiunta** [comment]
@yyx990803 Yeah, that's not going to work. Apologies if I'm not communicating thoroughly, but the devServer isn't running under my `my-php-site.test`. The site is being served from `my-php-site.test` and during development, loading `localhost:8080/app.js` from the devServer.

**Comment by yyx990803** [comment]
@chasegiunta I see. That's weird, because in this case it should just work without any configuration. If it's really not, I will need a reproduction. Or I'd suggest taking a look at https://github.com/yyx990803/laravel-vue-cli-3

**Comment by chasegiunta** [comment]
Hmmm. That approach is _going back_ to working from the dev server and _proxying_ your site. I think we've had issues with this in the past, and I've seen many folks from the Laravel community & mix users who have the same dev environment as I (work in `my-php-app.test`, but load your `app.js` from the dev server `localhost:8080`). Not saying it wouldn't work, and I can't quite recall why many people didn't do it this way. Will investigate further.

**Comment by csicky** [comment]
The title of this issue is about how to change the console message. The discussion is about something else. I understand that it was an AB problem and the discussion solves the real problem, but for people arriving here from Google there is no information about how to change the console messages from `npm run serve`.
I would like to be able to see only if there is a problem, if it's green, yellow or red. I don't want to give so much screen to the console, but in order to see what I want I have to see also the entire message which I know already:

```
 DONE  Compiled successfully in 24499ms      
  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.100.10:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.
```

I need a way to have the console say only:

```
 DONE  Compiled successfully in 24499ms      
```

**Comment by phistep** [comment]
I'm building an app against an API, which I mock locally, but sometimes run tests from my local setup against the public (staging) API endpoint. I can configure the endpoint URL using variables in `.env` files. So I have one to run locally against the mock, one to run locally against the public staging API and one to run on the staging server against the public staging API etc. I would like to see in the output not only the local and network URL, but also which API URL is configured, so I won't get confused which one I am targeting right now.
