### ISSUE TITLE
Can't use arrow keys to select options in Git Bash when running `vue create my-project`

### ISSUE THREAD

**Issue by regularmike** [vuejs/vue-cli#2117]
### Version
3.0.0-rc.11

### Node and OS info
Node 8.11.2 / npm 5.6.0 / Windows 10

### Steps to reproduce
In Git Bash:

`$ vue create my-project`

This produces the following output:

```
? Please pick a preset: (Use arrow keys)
> default (babel, eslint)
  Manually select features
```

Using the arrow keys does not move the angle bracket selector,  but just moves the cursor up and down, which can be moved anywhere on the screen. Pressing down once does result in selecting "Manually select features" but without visual feedback.

### What is expected?
Angle bracket selector should move up and down with arrow keys.

### What is actually happening?
Angle bracket selector does not move. Cursor moves but is free floating and there is no visual feedback to show you the current selection.

**Comment by yyx990803** [comment]
The default Git Bash is not an interactive terminal. You need to use something that is actually interactive.

**Comment by Lornakimani62** [comment]
You are God sent thank you

**Comment by Moyo75** [comment]
Thank you

**Comment by blade93ny** [comment]
This console emulator will have arrows working properly
https://cmder.net/

**Comment by xcurveballx** [comment]
Windows PowerShell also works.

**Comment by 8ivek** [comment]
Thanks

**Comment by symplytheo** [comment]
> The default Git Bash is not an interactive terminal. You need to use something that is actually interactive or use `winpty vue.cmd create hello-world`

Thanks man

**Comment by zhenyouliu** [comment]
λcmder is so cool, man!

**Comment by o2aya** [comment]
Try the integrated bash terminal on your IDE (I'm using vs code and it works for me)

**Comment by aldeny** [comment]
thanks sir.

> The default Git Bash is not an interactive terminal. You need to use something that is actually interactive or use `winpty vue.cmd create hello-world`

**Comment by htetwaiyantun258** [comment]
thank bro

**Comment by ronytacodev** [comment]
It worked perfectly

**Comment by ranieribt** [comment]
"The default Git Bash is not an interactive terminal."
Is there a setting to make Git Bash works as interactive?
I have Git Bash installed on two machines with Windows 10.
In the old machine, the arrows works when I issue yarn create astro, for example. But on the new machine it stoped working...

**Comment by rogbonbar** [comment]
You can just open it also from vs code and run the commands from the terminal directly there.
