### ISSUE TITLE
How to update vue-cli?

### ISSUE THREAD

**Issue by xrr2016** [vuejs/vue-cli#212]

**Comment by egoist** [comment]
Reinstall `npm i -g vue-cli` will do the favor.

**Comment by CharlesOkwuagwu** [comment]
@egoist how do you update a project built with a lower version of the cli?

**Comment by egoist** [comment]
@CharlesOkwuagwu you mean templates or `vue build`

**Comment by CharlesOkwuagwu** [comment]
I mean a project already set up with an older version of vue, how do we get the project updated via the cli

**Comment by LinusBorg** [comment]
You don't, currently. The templates+CLI don't support any kind of update process. Depending on what you changed in the template you are currently using, it might be easier to generate a new project, copy over `/src` & `/static`, and re-apply any changes you made to the webpack config & package.json scripts.

**Comment by posva** [comment]
I'd add to what @LinusBorg said that git is your friend 😄

**Comment by LinusBorg** [comment]
...and maybe that we are thinking about how to improve upgrades in the future, but that's nothing that will happen very soon.

**Comment by iamdubx** [comment]
Is it happening a year ago?

**Comment by LinusBorg** [comment]
Yes, actually. You can find an Alpha Version of vue-cli 3 in the `next` branch.

**Comment by bitbytebit1** [comment]
@LinusBorg, so can we update our projects now? or do we still have to do it the "manual way"

**Comment by LinusBorg** [comment]
Nothing changed for old projects, but new projects created with vue-cli 3 can be updated by simply updating the dependencies.

**Comment by muntac** [comment]
Note that if you're already on 3.0 and are trying to upgrade, `npm i -g vue-cli` will install 2.* (2.9.6 in my case). Instead, try `npm i -g @vue-cli`.

**Comment by rhkina** [comment]
Hi, @muntac, I suppose the command is npm i -g @vue/cli... I've tried this in Ubuntu, but when I type vue -V, the response is 2.9.3

**Comment by rhkina** [comment]
Hi @muntac,  I suppose the command is `npm i -g @vue/cli`... But after installing it I am getting 2.9.3 when input `vue --version` command...

**Comment by Akryum** [comment]
This means you have the old `vue-cli` package installed. You need to uninstall it.

**Comment by mak2014** [comment]
This worked for me:  

Uninstall first: 

`npm uninstall -g vue-cli`

Install:

`npm install -g @vue/cli`

**Comment by ZadaWu** [comment]
seems we need to install the latest, I worked when I add @latest:

`npm install -g @vue/cli@latest`

**Comment by LinusBorg** [comment]
It works without `latest` as well.

**Comment by typerory** [comment]
I ran `npm i -g vue-cli` and I went back to 2.96
I then ran `npm i -g @vue-cli` and got errors
I then ran `npm install -g @vue/cli@latest` and got 3.0.1
Strange but it worked.

**Comment by wcjr** [comment]
@typerory I think you meant to run `npm i -g @vue/cli` on your second attempt (`/` not `-`)

**Comment by xing00** [comment]
vue-cli has changed to vue/cli，can see this at https://cli.vuejs.org/guide/installation.html
uninstall vue-cli first with npm uninstall vue-cli -g or yarn global remove vue-cli, then run npm install -g @vue/cli or yarn global add @vue/cli, you will get it.
<img width="816" alt="1" src="https://user-images.githubusercontent.com/7943928/48208793-921d2b80-e3ae-11e8-987f-cc3727fafeda.png">

**Comment by sarngru** [comment]
Reinstall `npm i -g @vue/cli` will do the favor.

**Comment by PolymathWhiz** [comment]
sudo npm install -g @vue/cli@latest did the trick

**Comment by uke5tar** [comment]
i first uninstalled old vue globally
`npm uninstall -g vue-cli`
and then installed the new version
`npm install @vue/cli -g`
This was the only way it worked for me.

**Comment by MickaelBergem** [comment]
FYI on my end `vue upgrade` works fine:

```
$ vue upgrade --help
Usage: upgrade [options] [semverLevel]

upgrade vue cli service / plugins (default semverLevel: minor)

Options:
  -h, --help  output usage information
```

I'm not sure when this got introduced, but it should probably be in https://cli.vuejs.org/?

**Comment by ppKrauss** [comment]
Hello, why must use **sudo**?  The [solution above](https://github.com/vuejs/vue-cli/issues/212#issuecomment-256221209) is good, but only runs with sudo.

**Comment by UsmanJavedAttari** [comment]
d

**Comment by michealjroberts** [comment]
Is anyone else seeing an issue when updating the @vue/cli (with sudo) they're still getting a write permission error to the Missing write access to /usr/local/lib/node_modules/@vue/cli/node_modules/ folder?

**Comment by gustawdaniel** [comment]
First check which version are you using

```
which vue
```

In my case:

```
/home/daniel/.config/yarn/global/node_modules/.bin/vue
```

Then remove this version

```
cd /home/daniel/.config/yarn/global/
cat package.json
```

In my case

```
{
  "dependencies": {
    "@vue/cli-init": "^3.0.5",
    "@vue/cli-service-global": "^3.8.4",
    "bower-away": "^1.1.2",
    "node-gyp": "^3.7.0"
  }
}
```

Then

```
yarn global remove @vue/cli-init
yarn global remove @vue/cli-service-global
```

Now 

```
which vue
```

Indicates

```
/home/daniel/.nvm/versions/node/v12.6.0/bin/vue
```

So 

```
npm remove --global vue-cli
```

Then following after official docs

> https://cli.vuejs.org/

```
https://cli.vuejs.org/
```

If any cache disturb in this process type `bash`.

Now 

```
vue --version
@vue/cli 4.1.1
```

Before

```
vue --version
2.9.6
```

**Comment by greatgraphicdesign** [comment]
I'm fairly new to using npm, and I'd like to understand this better.

I read the above statement from @LinusBorg that says... 
> new projects created with vue-cli 3 can be updated by simply updating the dependencies.

Today `vue --version` returns `@vue/cli 4.3.1`.

I have projects that I created previously using `vue create <project>` when my @vue/cli version was older. I'm thinking I would like to update those projects, but I don't see `@vue/cli` listed in `package.json` as a dependency...
```
  "dependencies": {
    "core-js": "^3.6.4",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.3.0",
    "@vue/cli-plugin-eslint": "~4.3.0",
    "@vue/cli-service": "~4.3.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  },
```

Can someone explain more explicitly (for a newbie) what should I take to update those older projects, or if I don't need to, please explain why so I can understand?

**Comment by Chimney42** [comment]
@greatgraphicdesign @vue/cli now has experimental tools to upgrade your older projects
```
❯ vue --version
@vue/cli 4.4.6

❯ vue outdated
✔  Gathering package information...
  Name                        Installed       Wanted          Latest          Command to upgrade
  @vue/cli-service            4.2.3           4.2.3           4.4.6           vue upgrade @vue/cli-service
  @vue/cli-plugin-babel       4.2.3           4.2.3           4.4.6           vue upgrade @vue/cli-plugin-babel
  @vue/cli-plugin-unit-mocha  4.2.3           4.2.3           4.4.6           vue upgrade @vue/cli-plugin-unit-mocha
  @vue/cli-plugin-vuex        4.2.3           4.2.3           4.4.6           vue upgrade @vue/cli-plugin-vuex

❯ vue upgrade
✔  Gathering package information...
  Name                        Installed       Wanted          Latest          Command to upgrade
  @vue/cli-service            4.2.3           4.2.3           4.4.6           vue upgrade @vue/cli-service
  @vue/cli-plugin-babel       4.2.3           4.2.3           4.4.6           vue upgrade @vue/cli-plugin-babel
  @vue/cli-plugin-unit-mocha  4.2.3           4.2.3           4.4.6           vue upgrade @vue/cli-plugin-unit-mocha
  @vue/cli-plugin-vuex        4.2.3           4.2.3           4.4.6           vue upgrade @vue/cli-plugin-vuex
? Continue to upgrade these plugins? Yes
Upgrading @vue/cli-service from 4.2.3 to 4.4.6
+ @vue/cli-service@4.4.6
added 28 packages from 56 contributors, removed 2 packages, updated 35 packages and audited 1436 packages in 52.823s

39 packages are looking for funding
  run `npm fund` for details

found 14 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Upgrading @vue/cli-plugin-babel from 4.2.3 to 4.4.6
+ @vue/cli-plugin-babel@4.4.6
added 29 packages from 7 contributors, removed 2 packages, updated 84 packages and audited 1463 packages in 14.409s
🚀  Running migrator of @vue/cli-plugin-babel
✔  Successfully invoked migrator for plugin: @vue/cli-plugin-babel

Upgrading @vue/cli-plugin-unit-mocha from 4.2.3 to 4.4.6
+ @vue/cli-plugin-unit-mocha@4.4.6
added 4 packages from 3 contributors, removed 4 packages, updated 17 packages, moved 1 package and audited 1463 packages in 17.732s

Upgrading @vue/cli-plugin-vuex from 4.2.3 to 4.4.6
+ @vue/cli-plugin-vuex@4.4.6
updated 1 package and audited 1463 packages in 9.642s

 DONE  All plugins are up to date!
```

Hope this helps

**Comment by greatgraphicdesign** [comment]
Thank you very much! That does help.

**Comment by shirinzadeh** [comment]
I install the @vue/cli `npm i -g @vue/cli` , but before installing I didn't uninstall the vue-cli. 
WIll this become a problem or give errors in the future? Should I uninstall the vue-cli after installing @vue/cli
