### ISSUE TITLE
 Can I add some rules for eslint in the preset.json

### ISSUE THREAD

**Issue by leo-wj910729** [vuejs/vue-cli#2122]
### Version
3.0.0-rc.11

### Node and OS info
yarn 1.9.2/ mac

### Steps to reproduce
I don't see the options for rules in the vue-plugin-eslint documentation.

### What is expected?
Rules can be supported in options

### What is actually happening?
can not

**Comment by yyx990803** [comment]
In the next version presets can contain a generator file (`generator.js`), and you can do that with `api.extendPackage({ eslintConfig: { rules: { ... }})` when that is released.
