### ISSUE TITLE
按照文档创建多页应用出现的问题，访问必须要带.html才可以，如何加前缀就可以找到对应的页面上呢

### ISSUE THREAD

**Issue by Creamweiwei** [vuejs/vue-cli#2126]
### Version
3.0.0-rc.12

### Node and OS info
...

### Steps to reproduce
```
module.exports = {
  pages: {
    index: {
      entry: './src/index/main.js',
      template: './public/index.html',
      // 在 dist/index.html 的输出
      filename: 'index.html'
    },
    print: {
      entry: './src/print/print.js',
      template: './public/print.html',
      filename: 'print.html'
    }
  }
......
}
```

### What is expected?
访问localhost:8080/index/XXX 直接进index.html的页面
访问localhost:8080/print/XXX 直接进print.html页面

### What is actually happening?
访问时必须写localhost:8080/print.html才能进print页面，默认都是进index的，请问要实现预期的得如何做呢？

**Comment by sodatea** [comment]
只是需要去掉后缀的话把输出路径改成 `print/index.html` 就行了。更复杂的配置需要配置 `devServer` 的 `historyApiFallback` 选项：
```js
module.exports = {
  // ...
  devServer: {
    historyApiFallback: {
      rewrites: [
        { from: /print\/.*/, to: '/print.html' },
      ],
    }
  }
}
```

**Comment by lefreet** [comment]
@sodatea 通过rewrites配置之后，查看原有的api请求就也会被重定向到html页面了，是否有其它解决办法？我查看https://github.com/bripkens/connect-history-api-fallback/tree/master/examples/ignore-rules给出的例子，发现官方也没在中间件内部提供配置方式；比如有一个接口，我在开发调试时想双击直接访问接口内容，就没办法了
```js
     [
        {
          from: '/admin-app/*',
          to: '/pages/admin-app.html'
        },
        {
          from: '/admin/*',
          to: '/pages/admin.html'
        },
        {
          from: '^(?!\/rest).*',
          to: '/pages/index.html'
        }
      ]
```
