### ISSUE TITLE
Vue UI does not insert newline in package.json

### ISSUE THREAD

**Issue by duckness** [vuejs/vue-cli#2127]
### Version
3.0.0-rc.12

### Node and OS info
Node 10.8.0 / yarn 1.9.4 / Windows 10

### Steps to reproduce
1. Open any project in `vue ui`
2. Change a setting that affects `package.json` in the `vue ui` web GUI, for example, adding a package
3. Note that there is no new line present in `package.json`
4. Add any package via `yarn` e.g. `yarn add serve`
5. Note that the command adds a newline to `package.json`

### What is expected?
Consistent behavior with the `yarn` command, i.e, to leave a newline at the end of `package.json`

### What is actually happening?
Inconsistent behavior, which leads to newline/no newline commits without manual intervention if using both methods of adding things to `package.json`

**Comment by Akryum** [comment]
If you use `vue add` on the command line, is it also happening?

**Comment by duckness** [comment]
`vue add` adds a newline (expected since it just runs the `yarn add` command.

**Comment by Akryum** [comment]
This is expected, they use the same code 😸

**Comment by yyx990803** [comment]
@Akryum we should add a newline for files created by config transforms since we already have newlines for other files.
