### ISSUE TITLE
背景图片路径错误

### ISSUE THREAD

**Issue by Sliect** [vuejs/vue-cli#2129]
### Version
3.0.0-rc.11

### Node and OS info
node 8.11.1/windows 10/npm 6.2.0

### Steps to reproduce
样式里加载assets下的图片路径报404

### What is expected?
没有404

### What is actually happening?
404

---
@vue/cli-service/lib/config/css.js 中

```
rule
    .use('extract-css-loader')
    .loader(require('mini-css-extract-plugin').loader)
```
修改如下
```
rule
    .use('extract-css-loader')
    .loader(require('mini-css-extract-plugin').loader)
    .options({
        publicPath: '../'
    })
```

**Comment by Sliect** [comment]
虽然mini-css-extract-plugin官方说的是默认publicPath: '../'，不懂为什么还要自己手动设置

**Comment by Sliect** [comment]
求一个更优雅的解决方案

**Comment by sodatea** [comment]
麻烦提供一下问题复现，不要直接就给解决方案。我在本地并没有碰到你说的这个问题。

**Comment by Sliect** [comment]
恩，我明天上传个仓库地址

**Comment by Sliect** [comment]
仓库地址 https://github.com/Sliect/vue-cli3.0-pathBug

**Comment by Sliect** [comment]
对了，背景图片在开发环境下路径是正确的，只在生产环境下404

**Comment by yyx990803** [comment]
[文档](https://cli.vuejs.org/zh/config/#baseurl) 里写了：

> 请始终使用 `baseUrl` 而不要修改 webpack 的 `output.publicPath`

**Comment by Sliect** [comment]
看文档不仔细了！抱歉！感谢尤大！！！
