### ISSUE TITLE
webpack externals are still bundled in vue-cli

### ISSUE THREAD

**Issue by rjm0017** [vuejs/vue-cli#2134]
### Version
3.0.0-rc.11

### Node and OS info
node v8.11.3; npm v6.1.0; windows 10

### Steps to reproduce
Reproduction steps in the readme of this repo: https://github.com/rjm0017/external-bundle-issue

### What is expected?
vue-cli should be using the exports in vue.config.js to externalize three.js

### What is actually happening?
bundle size is massive when three.js is imported, even with the externalization referenced from the vue-cli docs

---
Reproduction can be done in https://github.com/rjm0017/external-bundle-issue and all of the steps are there

**Comment by yyx990803** [comment]
externals should be a package name, i.e. lowercase `three`, not `THREE`.
