### ISSUE TITLE
Vue Router Add Fails

### ISSUE THREAD

**Issue by gtalarico** [vuejs/vue-cli#2135]
### Version
3.0.0-beta.6

### Node and OS info
yarn 1.9.4

### Steps to reproduce
vue add router

### What is expected?
vue-router installs

### What is actually happening?
error No valid versions found for "vue-cli-plugin-router". The package may be unpublished.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
 ERROR  command failed: yarn add -D vue-cli-plugin-router

---
This might be an npm issue? Feel free to close if it's unrelated, but I thought I would post in case it's affecting others

![image](https://user-images.githubusercontent.com/9513968/43931384-2450e07c-9c0c-11e8-9332-671c16effdd4.png)

**Comment by yyx990803** [comment]
Upgrade to a newer version please.
