### ISSUE TITLE
如何配置cli3，类似cli2中的 showEslintErrorsInOverlay / emitWarning ？让warnings也在界面上显示报错

### ISSUE THREAD

**Issue by dficonfont** [vuejs/vue-cli#2139]
### What problem does this feature solve?
如何配置cli3，类似cli2中的 showEslintErrorsInOverlay / emitWarning ？让warnings也在界面上显示报错

作为略微有点强迫症的我必须要保持代码统一，研究了好久，还是只能报错才显示，求帮助！

### What does the proposed API look like?
可配置warning在界面中显示

**Comment by yyx990803** [comment]
https://cli.vuejs.org/config/#lintonsave
设置成 `error`

**Comment by dficonfont** [comment]
@yyx990803 设置成 error 也只能有报错时才显示，有warning时依然不显示
