### ISSUE TITLE
Eslint error listing  on vue files

### ISSUE THREAD

**Issue by jpkontreras** [vuejs/vue-cli#214]
Linting its only working in js files

The red line showing the error for "More than one blank line"

![](https://i.gyazo.com/22e5c2c0b269bca248577e1d4bb70f87.png)

But if i go to the vue file

Nothing happens
![](https://i.gyazo.com/6cefbddb2284e84074084fae6a82893f.png)

Although the error is visible on the screen. 

![](https://i.gyazo.com/2493272412b6a2b7eb6115fc9a87b926.png)

Keep the god's work guys !!

**Comment by posva** [comment]
that's a problem with the IDE 😀 . You should configure it properly, maybe you can find some help on the [forums](http://forum.vuejs.org/).
