### ISSUE TITLE
Add SSR webpack config

### ISSUE THREAD

**Issue by VitaliyLavrenko** [vuejs/vue-cli#2146]
Can you add to @vue/cli second webpack config for SSR and _build server\run server_ task? 

I know there is plugin for SSR like @vueneue/vue-cli-plugin-ssr but it add own dependencies to APP structure.

It would be good to have SSR mode.

**Comment by EDiaos** [comment]
Hi , I write a project for cli3-ssr-project, see [here](git@github.com:EDiaos/vue-cli3-ssr-project.git)
