### ISSUE TITLE
vue with ts-protoc-gen has Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by lionelee** [vuejs/vue-cli#2147]
### Version
3.0.0-rc.12

### Node and OS info
Node 10.7.0/yarn 1.7.0/macOS High Sierra

### Steps to reproduce
I have already push the project to  [github repo](https://github.com/lionelee/test-grpcweb-vue),
and you can clone it to reproduce

### What is expected?
I want no 'exports is not defined'

### What is actually happening?
Uncaught ReferenceError: exports is not defined

**Comment by yyx990803** [comment]
Use ES modules.

**Comment by lionelee** [comment]
But the plugin ts-protoc-gen can not generate ES module and I have to use it to invoke grpc.
