### ISSUE TITLE
Some assets put outside of folder specified in assetsDir

### ISSUE THREAD

**Issue by robertotru** [vuejs/vue-cli#2149]
### Version
3.0.0-rc.12

### Node and OS info
Node v8.11.0, npm 6.3.0

### Steps to reproduce
1) Create a project using command 
vue create frontend

2) Create a vue.config.js in folder containing package.json

3) define the following in file vue.config.js

module.exports = {
    outputDir: 'myfolder/dist',
    assetsDir: 'static'
}

4) run the following command:
 npm install

### What is expected?
All the assets are in the specified folder

### What is actually happening?
an img folder is outside the specified folder

---
It seems that the generated project does not work properly, but maybe it is a vue issue instead of a vue-cli issue. Not clear to me.

**Comment by yyx990803** [comment]
The config works as expected. Please provide a valid reproduction when opening issues.

**Comment by qidaneix** [comment]
meet the same problem

**Comment by qidaneix** [comment]
@robertotru update to v3.0.1
