### ISSUE TITLE
import / export issue

### ISSUE THREAD

**Issue by vanderlin** [vuejs/vue-cli#215]
Unable to use `export` in a index.js file when for example. 

Here I have a index.js that exports the Bar component in say main.js I can not import bar from /bar. ie: `import {Bar} from './components/bar'`
```javascript
/* in ./src/components/bar/index.js */
export Bar from './Bar.vue'



/* in ./src/components/bar/Bar.vue */
<template>
   <div>Hi</div>
</template>

export default {
}

<style>
</style>
```

I get this error?
```bash
ERROR in ./src/components/bar/index.js
Module build failed: SyntaxError: Unexpected token, expected { (1:7)

> 1 | export Bar from './Bar'
    |        ^
```

**Comment by zigomir** [comment]
@vanderlin this is not a `vue-cli` issue. Also, as error tells you, I think correct ES6 syntax for re-export would be something like:

```js
export { Bar } from './Bar'
```

See more [here](http://www.2ality.com/2014/09/es6-modules-final.html) under **Re-exporting** section.
