### ISSUE TITLE
Unneeded polyfills included in the bundle

### ISSUE THREAD

**Issue by astagi** [vuejs/vue-cli#2152]
### Version
3.0.0-rc.11

### Node and OS info
Node 8.9.3 / yarn 1.5.1 / MacOS Sierra 10.12.6

### Steps to reproduce
I tried to create a library with some reusable components with vue-cli. 

```
vue-cli-service build --target lib --name myLib
```

In my index.js file I register my components

```
import Vue from "vue";
import HelloWorld from "./HelloWorld.vue"

const Components = {
    HelloWorld
}

Object.keys(Components).forEach(name => {
    Vue.component(name, Components[name])
});

```

The problem is that targeting modern browser, babel loads some polyfills automoagically to support Object.keys, increasing the bundle size. I tried targeting only chrome 68 in my package.json

```
  "browserslist": [
    "chrome 68"
  ]
```

but babel still loads unneeded polyfills..

Any suggestions?

### What is expected?
Targeting modern browser, babel should load required polyfills 

### What is actually happening?
Babel loads unneeded polyfills

**Comment by yyx990803** [comment]
Looks like even for Chrome 68, `Object.keys` entails a polyfill for `web.dom.iterable`. This is the behavior of `babel-preset-env`.

You can explicitly disable polyfill injection with the following `babel.config.js`:

``` js
module.exports = {
  presets: [
    ['@vue/app', { useBuiltIns: false }]
  ]
}
```

**Comment by latel** [comment]
see #2594, option `useBuiltIns` is un-available
