### ISSUE TITLE
vue devtool: 'eval-source-map',  cannot debug breakpoint

### ISSUE THREAD

**Issue by lh8725473** [vuejs/vue-cli#216]
vue devtool: 'eval-source-map',  cannot debug breakpoint

**Comment by lh8725473** [comment]
devtool: 'cheap-module-eval-source-map' it also not work

**Comment by posva** [comment]
@lh8725473 Can you please be more specific on what is happening and what are you expecting?

**Comment by lh8725473** [comment]
![494e5b90-33fc-43a5-865d-ce258c67e453](https://cloud.githubusercontent.com/assets/6263383/19893556/8795f6ca-a084-11e6-869e-0bb34b30c2fb.png)

**Comment by lh8725473** [comment]
this config with devtool: '#cheap-module-eval-source-map',

**Comment by posva** [comment]
Please, spend a bit more time explaining what you're trying to achieve, how, what isn't meeting your expectations, what is the issue, which template, etc

**Comment by egoist** [comment]
And I believe this issue should be opened in relative template.

**Comment by posva** [comment]
@egoist yep, I wanted to make sure it's a real issue first 😆
