### ISSUE TITLE
lintOnSave 为 'error' 时也不能让warnings 在网页界面中显示，只能报错才显示。能否增加支持？

### ISSUE THREAD

**Issue by dficonfont** [vuejs/vue-cli#2162]
### What problem does this feature solve?
为了代码统一，希望完全要求按照eslint风格写代码，如果没有在网页界面中显示warning还是容易被忽略。
当设置为 lintOnSave 为 'error' 时，只有报错才会在网页界面中显示（显示包含了warning）。但仅有warning时就不会显示，希望增加支持！

### What does the proposed API look like?
例如：lintOnSave 为 'warning'

**Comment by sodatea** [comment]
配置 `devServer` 的 `overlay` 选项即可。
https://webpack.js.org/configuration/dev-server/#devserver-overlay
