### ISSUE TITLE
[QUESTION] how to run e2e test in development environment

### ISSUE THREAD

**Issue by renatosistemasvc** [vuejs/vue-cli#2164]
### Version
3.0.0-rc.12

### Node and OS info
8.11.3

### Steps to reproduce
I apologize for creating this topic here. I did not find in the documentation how to run the e2e test in development mode.

when I try to run: npm run test:e2e Vue cli is using .env.production variables and I want to use the: .env.development

Does anyone know how I can change this behavior?

### What is expected?
use the: .env.development

### What is actually happening?
use the: .env.production

**Comment by joelpro2** [comment]
Why is the question closed with no response?
i have the same issue.

I want to run e2e tests with test mode or development mode.

**Already done:**
vue-cli-service test:e2e --mode test

this throws an error
Error: watch /.../public ENOSPC
