### ISSUE TITLE
Validation Warnings on default build 

### ISSUE THREAD

**Issue by jasonbodily** [vuejs/vue-cli#2165]
### Version
3.0.0-rc.12

### Node and OS info
node 8.9.3 / npm 6.3.0 / macOS High Sierra

### Steps to reproduce
Run vue create project

? Please pick a preset: Manually select features

? Check the features needed for your project: Babel, Linter

? Pick a linter / formatter config: Standard

? Pick additional lint features: Lint on save, Lint and fix on commit

? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In package.json

? Save this as a preset for future projects? (y/N) n

cd project

*edit any file*

git init

git add .

git commit -m ""

### What is expected?
A clean lint run with a successful commit

### What is actually happening?
The following warning shows:

```
● Validation Warning:

  Unknown option "*.vue" with value ['vue-cli-service lint', 'git add'] was found in the config root.

  You are probably trying to mix simple and advanced config formats. Adding

  "linters": {
    "*.vue": ["vue-cli-service lint","git add"]
  }

  will fix it and remove this message.

Please refer to https://github.com/okonet/lint-staged#configuration for more information...
 ↓ Running tasks for *.js [skipped]
   → No staged files match *.js
 ↓ Running tasks for *.vue [skipped]
   → No staged files match *.vue
```

---
Following the recommendation's advice does not remove the warning. I recognize this is likely a dependency issue. Still wanted to report it in case it's a configuration issue on vue-cli's end. Any suggestions to remove the warning would be appreciated.

**Comment by sodatea** [comment]
Thanks for your report!
It is indeed an upstream issue. See https://github.com/okonet/lint-staged/issues/482
I'll submit a PR to upgrade the dependency to a newer version.

**Comment by jasonbodily** [comment]
Updating lint-staged from `^7.2.0` to `^7.2.2`  in the meantime fixes the problem
