### ISSUE TITLE
template on your local file system. 

### ISSUE THREAD

**Issue by robertolabarca** [vuejs/vue-cli#217]
hello

mkdir d:\sourcecode\personal\vue\ex1
mkdir d:\sourcecode\git\vue-templates
cd d:\sourcecode\git\vue-templates
git clone https://github.com/vuejs-templates/simple.git
cd d:\sourcecode\personal\vue\ex1

How to use the local template ?. Not internet conexion 

(FAIL)  vue init "d:\sourcecode\git\vue-templates\simple" example01

**Comment by zigomir** [comment]
Should be fixed with https://github.com/vuejs/vue-cli/pull/194.
