### ISSUE TITLE
configreWebpack not work

### ISSUE THREAD

**Issue by njleonzhang** [vuejs/vue-cli#2173]
### Version
3.0.0

### Node and OS info
Node 8.11.3 / npm 6.1.0 / Mac OS 10.13.6

### Steps to reproduce
1. add `html-webpack-inline-plugin` to vue.config.js

```
var HtmlWebpackInlinePlugin = require('html-webpack-inline-plugin');

module.exports = {
  lintOnSave: false,
  configureWebpack: {
    plugins: [
      new HtmlWebpackInlinePlugin()
    ]
  }
}
```

2. check if the plugin workable.
```
> vue inspect --plugins

[
  'vue-loader',
  'define',
  'case-sensitive-paths',
  'friendly-errors',
  'hmr',
  'no-emit-on-errors',
  'progress',
  'html',
  'preload',
  'prefetch',
  'copy',
  'fork-ts-checker',
  undefined
]
```

### What is expected?
it should added into the webpack plugin config

### What is actually happening?
it is show as undefined

**Comment by tangdw** [comment]
@njleonzhang 
  // 直接修改 或 return 配置对象
  configureWebpack(config) {
      config.plugins.push(new HtmlWebpackInlinePlugin())
  }

**Comment by sodatea** [comment]
The output of `vue inspect` could be optimized as it should not show `undefined` for those user-defined plugins.

But `configureWebpack` did work as expected.
It is this particular plugin that does not work with webpack 4.

**Comment by njleonzhang** [comment]
@sodatea [the plugin](https://github.com/QuellingBlade/html-webpack-inline-plugin) can work with webpack 4, it's sustained by our team, and already used in several webpack 4 projects.

**Comment by sodatea** [comment]
@njleonzhang 
Oh I'm sorry I have misused this plugin…

But as I tested locally, all the compilation hooks have been called successfully.
And `<script inline src="babel.config.js"></script>` did output the correct content to the html:
`<script>module.exports={presets:["@vue/app"]};</script>` 

Could you upload a test repo for reproduction?

**Comment by njleonzhang** [comment]
@sodatea I debugged and found that the inject failed due to the content in the js can not be compressed. a error log can be printed in the console when run `webpack` command.
```
webpack-dev-server --inline --progress --disableHostCheck --config build/webpack.dev.conf.js"
```
But when run through `vue-cli-service serve`,  no log can be printed. can I make `vue-cli-service` print this kind of log?

**Comment by sodatea** [comment]
What kind of log? For compilation failures, `vue-cli-service` do print error logs. In this case it is due to the plugin not emitting any errors.

https://github.com/QuellingBlade/html-webpack-inline-plugin/blob/ff6726cb33deb475730df5c9a8e5a111287233f7/index.js#L24

shoud be

``js
callback(err, htmlPluginData)
``

**Comment by njleonzhang** [comment]
@sodatea Tnx
