### ISSUE TITLE
非多页场景下，public目录下支持其他index.html资源。

### ISSUE THREAD

**Issue by moyuye** [vuejs/vue-cli#2174]
### What problem does this feature solve?
在不是多页面的场景下，public目录下有不需要打包静态展示的文件index.html，如docs/index.html、lib/docs/index.html。希望可以配置过滤的选项 ：).

### What does the proposed API look like?
publicCopyIgnore : ['index.html', '.DS_Store']

**Comment by tangdw** [comment]
@moyuye 通过 chainWebpack 修改 CopyWebpackPlugin 这个插件的参数

**Comment by moyuye** [comment]
@tangdw  好的，了解。

**Comment by moyuye** [comment]
已通过如下方式解决。
```
chainWebpack: config => {
    config.plugin('copy')
        .tap(args => {
          //修改对应配置即可...
```

**Comment by wosummerYink** [comment]
Which specific configuration should I change?
