### ISSUE TITLE
Webpack init throws peerDependency error

### ISSUE THREAD

**Issue by duckontheweb** [vuejs/vue-cli#218]
Running `npm install` within a project created by `vue init webpack my-project` results in a `peerDependency` error (full error trace can be found in [this gist](https://gist.github.com/duckontheweb/88c70eb3f2d2f2fdd5b9e6887838fe02).

System details:

```
Darwin jduckwor-28897s 14.5.0 Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64 x86_64
Node v4.6.1
npm 2.15.9
vue-cli 2.4.0
``` 

**UPDATE:** Switching to Node v5.x fixes the problem.

**Comment by zigomir** [comment]
Maybe it's because you were using npm v2 there. I see `webpack` template recommends using npm v3. Anyhow, feel free to open issue on [webpack template repo](https://github.com/vuejs-templates/webpack) because this issue isn't one of `vue-cli`.
