### ISSUE TITLE
Can vue-cli 3 remove completion git hook?

### ISSUE THREAD

**Issue by taoweicn** [vuejs/vue-cli#2182]
### What problem does this feature solve?
I use a Windows PC and set git config `core.autocrlf=input` and `core.safecrlf=true `. But on Windows, yarn will generate a CRLF style `yarn.lock` file by default, see [this](https://github.com/yarnpkg/yarn/issues/1061). So when I run `vue create my-project`, I will get a ERROR after the step 'Running completion hooks...', it shows: 
```bash
Error: Command failed: git add -A
fatal: CRLF would be replaced by LF in yarn.lock.
```
I try to solve it but fail to find a way to set `yarn.lock`'s eol to LF or make git convert CRLF to LF without converting LF to CRLF when checking out text files(If set `core.autocrlf=true`, it contradicts `.editorconfig`).
Therefore, I hope vue-cli will remove this hook or just jump this step when got a error.

### What does the proposed API look like?
remove or modify completion git hook.

**Comment by yyx990803** [comment]
`vue create --no-git my-project`
