### ISSUE TITLE
When multiple apps are running, "Launch App" button launches the wrong app.

### ISSUE THREAD

**Issue by chengluyu** [vuejs/vue-cli#2189]
### Version
3.0.0

### Node and OS info
Node 10.8.0 / yarn 1.9.4 / macOS High Sierra 10.13.6

### Steps to reproduce
Serve more than one project by Vue UI. For example, there are two projects named `app`, `manage`. Serve `app` first then serve `manage`. If you switch to the management panel of `app`. Click "Lanuch App" button will not open `app`, instead it will launch `manage`.

### What is expected?
The "Launch App" button should launch `app`.

### What is actually happening?
Click "Lanuch App" button will not open `app`, instead it will launch `manage`.

**Comment by chengluyu** [comment]
Attach several screenshots to make it clear.

1. First, have two project running. I run the `serve` task of `mange`. Then I run the `serve` task of `app`.

![image](https://user-images.githubusercontent.com/2239547/44061571-8edaa120-9f1e-11e8-8aae-5dd7bbf7b155.png)

2. Go to the dashboard of `manage`. But the right-hand-side panel shows the information of `app`.

![image](https://user-images.githubusercontent.com/2239547/44061763-57d8559a-9f1f-11e8-84c8-8f3ff4c1152d.png)

**Comment by chengluyu** [comment]
@Akryum I'm sorry? I've given the steps to reproduction. Why do you still attach this tag?

**Comment by Akryum** [comment]
It's different from [need reproduction]. Please read tag description.

**Comment by chengluyu** [comment]
@Akryum Got it. Thanks for explanation!
