### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by GaoQ1** [vuejs/vue-cli#219]
很费解，有了vue-cli初始化了一个项目，npm run dev后报"Unexpected token import"的错误。npm run build报Unexpected token: name(Vue).求解

**Comment by zigomir** [comment]
@GaoQ1 which template are you using?

**Comment by GaoQ1** [comment]
@zigomir I use webpack template.

**Comment by zigomir** [comment]
Please report your issue there. Also, more info (more stack/error trace, what you've tried, what's your `.babelrc`, what node and npm version do you use, ...) it can help others help you ;)

**Comment by yehuajin** [comment]
这个问题怎么解决的
