### ISSUE TITLE
初始化vue-cli3.0项目，修改项目.vue文件内容浏览器没有自动刷新

### ISSUE THREAD

**Issue by libin1991** [vuejs/vue-cli#2195]
### Version
3.0.0

### Node and OS info
8.11.1 / npm / mac

### Steps to reproduce
初始化vue-cli3.0项目，修改项目.vue文件内容浏览器没有自动刷新

### What is expected?
修改项目.vue文件内容浏览器自动刷新

### What is actually happening?
需要手动刷新

**Comment by sodatea** [comment]
能否提供一下代码以供我们排查？光看描述我们很难帮上忙

**Comment by season19840122** [comment]
我也是一样，不管是使用 vue ui 运行 npm run serve 还是直接运行 npm run serve 热更新一直是 wait 状态，我的 vue-cli 版本是 3.0.0

**Comment by libin1991** [comment]
@sodatea  你可以用vue cli3初始化一个Vue项目跑起来看看 ，修改vue文件的内容，看看浏览器会自动刷新吗？

**Comment by season19840122** [comment]
@libin1991 好的我试试，我再其他的 issues 中看到他们说要把 NODE_ENV=development 但我不知道在哪里设置

**Comment by sodatea** [comment]
@libin1991 会啊……所以才需要更多信息。

初始化选项是哪些？是否改过 vue.config.js？网页是否有报错？WebSocket 连接是否成功？浏览器是 Chrome 还是 Safari？是所有浏览器都有问题还是只有这一个？这些信息都能够帮助排查问题的

**Comment by sodatea** [comment]
@season19840122 `npm run serve` 时默认就是 `development`

**Comment by season19840122** [comment]
@sodatea 哦，我修改过 vue.config.js

**Comment by libin1991** [comment]
@sodatea   麻烦看看https://github.com/wanghanzhen/vue-multi-page这个项目

**Comment by AmosXu** [comment]
@sodatea  我把vue-cli3相关代码拷贝到我的项目中也无法热加载，后来我把自己项目中的代码拷到vue-cli3生成的项目中，就可以热加载了，不知道你和我情况是否相同

**Comment by sodatea** [comment]
@libin1991 都没办法复现……控制台是否有报错？

**Comment by libin1991** [comment]
@sodatea ，你的可以正常热加载？

**Comment by libin1991** [comment]
@AmosXu 我是从网上找了几个vue-cli的项目随便跑跑都不可以，

**Comment by sodatea** [comment]
@libin1991 是啊……所以需要你提供更多信息
**刚进入页面时发出的 WebSocket 连接是否成功？网页控制台是否有报错？**

**Comment by season19840122** [comment]
@libin1991 经我测试，重新创建一个 vue 项目是 HMR 是可以正常使用的，但是我把我现在的 vue.config.js 放进去后 HMR 就不正常了，但是我注释掉其中部分跟 webpack 有关的，还有 pages 选项部分就正常了。@sodatea

**Comment by season19840122** [comment]
@sodatea 控制台没报错，一切正常

**Comment by yyx990803** [comment]
@libin1991 现在的情况是热加载只有在你的机器上不工作，所以你不提供额外的信息我们做不了任何事情。

@season19840122 请不要在别人的 issue 下面让人看自己的问题，这样会让讨论很混乱。你们遇到的未必是同样的问题。

**Comment by twoer** [comment]
我也遇到了，使用 `cnpm` 安装的 node 模块 就是无法 HMR，换成 `npm` 安装 就正常，大家可以试试。

**Comment by season19840122** [comment]
@twoer 这么奇怪？

**Comment by sodatea** [comment]
`cnpm` 确实会导致热更新失效
https://github.com/vuejs/vue-cli/issues/1559

**Comment by qiaoqiao10001** [comment]
但是我是用的yarn 怎么还是失效了呢

**Comment by WeTis** [comment]
@qiaoqiao10001 使用yarn serve时 先执行一步 yarn  然后yarn serve 就可以了

**Comment by qiaoqiao10001** [comment]
> @qiaoqiao10001 使用yarn serve时 先执行一步 yarn 然后yarn serve 就可以了

试过。浏览器还是没反应，谷歌浏览器是系统默认

**Comment by sepld** [comment]
@vue/cli-service包中有webpack 和 webpack-dev-server这两个依赖. 而且webpack-dev-server这个包又依赖webpack, 此时. 这两个依赖的webpack包版本要相同. 随便改哪个都行,只要一样就可以.
