### ISSUE TITLE
Should not set public path in lib mode

### ISSUE THREAD

**Issue by riophae** [vuejs/vue-cli#2196]
### Version
3.0.0

### Node and OS info
Node 10.8.0 / yarn 1.9.4 / WSL

### Steps to reproduce
Run: `vue-cli-service build --target lib --name lib-name src/index.js`

### What is expected?
Should not set public path since this is a library build.

### What is actually happening?
I have seen this in the dist file:

```js
/***/ "fb15":
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);

// EXTERNAL MODULE: ./node_modules/@vue/cli-service/lib/commands/build/setPublicPath.js
var setPublicPath = __webpack_require__("1eb2");
```

And I didn't find any option to disable this behavior. I also suggest this to be automatically disabled when `--target` set to `lib`.

**Comment by sodatea** [comment]
This is intentional.
See:
https://github.com/vuejs/vue-cli/blob/7fd344376edbb67eca7d9295b859c57eb72a0e43/packages/%40vue/cli-service/lib/commands/build/resolveLibConfig.js#L110-L112
