### ISSUE TITLE
配置 js.sourceMap

### ISSUE THREAD

**Issue by zhaojh329** [vuejs/vue-cli#2200]
### What problem does this feature solve?
禁止 js.sourceMap

### What does the proposed API look like?
js.sourceMap: false

**Comment by sodatea** [comment]
webpack 中用 `devtool` 配置 JS 文件的 sourcemap
https://webpack.js.org/configuration/devtool/#devtool

开发环境下我们是默认开启的，你可以修改 vue.config.js 覆盖默认配置。
生产环境中修改 `productionSourceMap` 选项即可 https://cli.vuejs.org/zh/config/#productionsourcemap

```
module.exports = {
  productionSourceMap: false,  // 生产环境禁用
  configureWebpack: {
    devtool: false // // 开发环境禁用
  }
}
```
