### ISSUE TITLE
webpack-chain seems to conflict with some other limitations

### ISSUE THREAD

**Issue by AlphaCodeZero** [vuejs/vue-cli#2202]
### Version
3.0.0

### Node and OS info
Node 10.7.0 / npm 6.2.0 / macOS High Sierra

### Steps to reproduce
In vue.config.js, just write something like:
```javascript
const path = require('path')

module.exports = {
  // https://github.com/mozilla-neutrino/webpack-chain
  chainWebpack: (config) => {
    config.output.path(path.resolve('../backend/app/public'))
    config.output.publicPath('/public/')
    config.plugin('define').tap(() => [{
      'process.env': {
        NODE_ENV: '"production"',
        BASE_URL: 'window.location.origin + "/api/"',
      },
    }])
  },
}
```
Then run `vue inspect`, all is well. But after `npm run build`, the terminal said 'Configuration Error: Avoid modifying webpack output.path directly. Use the "outputDir" option instead.'

### What is expected?
The `output.path` and `output.publicPath` should be resolved correctly.

### What is actually happening?
The vue-cli rejected to build.

---
I saw the warning in the documentation:
> For example, instead of modifying output.path, you should use the outputDir option in vue.config.js; instead of modifying output.publicPath, you should use the baseUrl option in vue.config.js.

But I think it isn't suitable for [webpack-chain](https://github.com/mozilla-neutrino/webpack-chain), since there aren't any methods called outputDir or baseUrl in webpack-chain.

**Comment by sodatea** [comment]
`outputDir` & `baseUrl` are root level options.
```
module.exports = {
  outputDir: 'xxx',
  baseUrl: 'xxx',
  chainWebpack: () => {}
}
```
