### ISSUE TITLE
在组件的组件中使用mixin,会无法找到mixin中的方法或属性

### ISSUE THREAD

**Issue by big-pang** [vuejs/vue-cli#2207]
### Version
3.0.0

### Node and OS info
v8.11.3

### Steps to reproduce
在组件的组件的组件中 (多层), mixin中的方法或属性会无法找到

### What is expected?
本来应该是可以使用mimin中的方法

### What is actually happening?
提示没有找到方法

**Comment by sodatea** [comment]
这个恐怕跟 CLI 无关。
请提供可以运行的示例后（可以是一个包含最小可复现代码的 GitHub 仓库并附上相关说明）到 https://github.com/vuejs/vue/ 提交 Bug Report。

**Comment by big-pang** [comment]
好的
