### ISSUE TITLE
vue ui 的依赖管理  ‘正在卸载xxx’   写成    ‘正在写在xxx’

### ISSUE THREAD

**Issue by admin00001** [vuejs/vue-cli#2210]
### Version
3.0.0

### Node and OS info
Node 10.6.0   Windows 10

### Steps to reproduce
vue ui 的页面里面随便安装一个依赖，比如axios, 然后去卸载，发现页面上显示 ‘正在写在axios’

### What is expected?
去卸载某个依赖，应该显示的是‘正在卸载xxx’

### What is actually happening?
无

**Comment by yyx990803** [comment]
中文的翻译文件不在本仓库内，请反馈到 https://github.com/SevenOutman/vue-cli-locale-zh （你所说的问题已经修复）
