### ISSUE TITLE
Why not use vue-class-component, but vue-property-decorator?

### ISSUE THREAD

**Issue by skatpgusskat** [vuejs/vue-cli#2211]
### Version
3.0.0-rc.5

### Node and OS info
node 8.9.0 npm 6.1.0 windows 10

### Steps to reproduce
make project with class component, typescript using cli

### What is expected?
I expected using vue-class-component (https://github.com/vuejs/vue-class-component) that vuejs made for class componenet

### What is actually happening?
It uses vue-property-decorator(https://github.com/kaorun343/vue-property-decorator).

---
I just ask you why you chose vue-property-decorator than vue-class-component.
I think vue-class-component is made by vuejs. I want to ask you the reason.

**Comment by yyx990803** [comment]
`vue-property-decorator` uses `vue-classes-component` internally.
