### ISSUE TITLE
VueCli UI Launching Error: Cannot find module 'core-js/modules/es7.object.entries'

### ISSUE THREAD

**Issue by nunonux** [vuejs/vue-cli#2215]
### Version
3.0.0

### Node and OS info
8.11.3

### Steps to reproduce
The following error occurred when i launch the vue ui from command prompt.

### What is expected?
Vue Client UI to launch

### What is actually happening?
The following error shows in the browser console:

module.js:549
    throw err;
    ^

Error: Cannot find module 'core-js/modules/es7.object.entries'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Nuno\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\apollo-upload-server\lib\middleware.js:14:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by phil-scott-78** [comment]
if you are blocked by this, `npm -g i core-js` will get the required dependencies installed. Ran into this on a clean box just now.

**Comment by korziee** [comment]
Getting the same issue here, installing core-js globally worked as @phil-scott-78 said.

**Comment by sphism** [comment]
Same issue here on mac. 

npm install -g core-js

Fixed it for me

**Comment by Akryum** [comment]
This is an issue with `apollo-upload-server 5.0.0` which uses some babel polyfill, but babel removed the dependency to `core-js`. This should be fixed in [6.0.0](https://github.com/jaydenseric/apollo-upload-server/releases/tag/v6.0.0-alpha.1) once it gets stable and released in `apollo-server`, or if https://github.com/apollographql/apollo-server/issues/1536 is fixed we can just skip the whole module.

**Comment by viztor** [comment]
it happened to us while using apollo as well. it is probably unrelated to vue-cli.

**Comment by aayush420** [comment]
I did `npm -g install core-js` multiple times, but it did not work for me.
Turns out I'm using yarn for the project and `yarn global add core-js` did the trick for me.
Thanks @phil-scott-78

**Comment by ChasLui** [comment]
I tried `npm -g install core-js` and `yarn global add core-js` have no effect

**Comment by Palec** [comment]
Use version 2.6.5 not 3.0.0
