### ISSUE TITLE
vue create doesn't allow upper-case letters

### ISSUE THREAD

**Issue by JandosKh** [vuejs/vue-cli#2219]
In v3.0, I tried to create a project with name "VueApp" like below:

    vue create VueApp

It complains: "Invalid project name". But name "vueapp" goes without an error. Also, vue ui allows capital letters; I was able to create a project with name "VueApp".

**Comment by HamedFathi** [comment]
Yes, I have this problem too please check this I should use `client-app` instead of `ClientApp`. it is ridiculous.
After creating I should transfer the whole project to a new folder I want.

**Comment by sodatea** [comment]
https://github.com/vuejs/vue-cli/issues/2547#issuecomment-422382882

**Comment by mPyth** [comment]
It would be nice to make it possible to have a project directory with Camel Case name.
