### ISSUE TITLE
cli3 创建的项目导入webpack library 会报错

### ISSUE THREAD

**Issue by varjay** [vuejs/vue-cli#2224]
### Version
3.0.0-rc.12

### Node and OS info
Node v8.11.2 / 6.1.0 / macOS 10.13.4

### Steps to reproduce
cli3 创建的项目导入一个dist出来的library会报错（library 是 export default function）
是这里的/dist/webpack-numbers.js（入口为index.js，作为测试只有index.js）:
https://github.com/varjay/webpack-library-example

在cli3创建的项目main.js中：
```
let b = require('./js/webpack-numbers.js')
console.log(b)
```
报错：webpack-numbers.js?000f:1 Uncaught TypeError: Cannot set property 'webpackNumbers' of undefined

但是使用webpack4 创建出来的项目就可以正常require，并且打印出b是一个function 

即使修改配置不报错，导出来的b是：Module {__esModule: true, Symbol(Symbol.toStringTag): "Module"}，不能用b这个变量。

甚是疑惑，求解！

### What is expected?
let b 中的b即为方法，能直接使用。

### What is actually happening?
let b的b是一个Module

**Comment by Justineo** [comment]
You can try anyone from the following:

1. `import b from './js/webpack-numbers.js`
2. `const b = require('./js/webpack-numbers.js').default`
3. Use `babel-plugin-add-module-exports` to transpile your library before using it as a CommonJS module.

**Comment by varjay** [comment]
@Justineo Thank you.
I am getting an error when importing webpack-numbers.js, showing: Uncaught TypeError: Cannot set property 'webpackNumbers' of undefined.
Is there any way to solve this?
Address: https://github.com/varjay/webpack-library-example.

**Comment by sodatea** [comment]
在 Webpack 4 中不要混用 ES Module 和 CommonJS Module。
你的项目能跑起来是因为配置了 `@babel/preset-env`，它的默认配置包含了 `module: commonjs`，也就是说项目中的所有模块都已经被 babel 编译成 CommonJS Module 了再交给

**Comment by dficonfont** [comment]
@sodatea 请问如何解决报错这个问题？

**Comment by zhuqingguang** [comment]
@sodatea 这个问题有办法解决吗？

**Comment by icrisman** [comment]
@varjay  请问这个问题解决了吗
