### ISSUE TITLE
webstrom2018.2中，ts报错

### ISSUE THREAD

**Issue by ccqiuqiu** [vuejs/vue-cli#2226]
### Version
3.0.0

### Node and OS info
node8

### Steps to reproduce
1. 用vue-cli3脚手架生成一个typescript的项目
2. 在shilm.s.ts文件中定义一个interface     declare interface A {  a: string  }
3. 在src/components/HelloWord.vue中添加一个属性，指定类型为刚刚定义的接口A     private a: A = {a: ''}
4. 用webstrom2018.2打开，会提示 Corresponding file is not included in tsconfig.json
5. 运行和编译都不会有问题，就webstrom2018.2会提示错误，vscode和webstrom2018.1都不会提示错误

### What is expected?
webstrom2018.2不要报错

### What is actually happening?
用webstrom2018.2打开，会提示 Corresponding file is not included in tsconfig.json

---
我知道这个应该不算vue-cli3的bug，但是这个问题困扰我很久了，希望能帮我看看

最小重现代码在这：  https://github.com/ccqiuqiu/issue

**Comment by yyx990803** [comment]
... 这个我们也无能为力的，请去 webstorm 那边报 bug
