### ISSUE TITLE
Inconsistent semicolons style in extracted config files 

### ISSUE THREAD

**Issue by jingsam** [vuejs/vue-cli#2228]
### Version
3.0.0

### Node and OS info
yarn

### Steps to reproduce
When extract config files using `vue create`, we have 3 config files:

```
// vue.config.js
module.exports = {
  lintOnSave: false
}; <----
```

```
// babel.config.js
module.exports = {
  presets: ["@vue/app"]
}; <------
```

```
// .postcssrc.js
module.exports = {
  plugins: {
    autoprefixer: {}
  }
} <------
```

```
// .eslintrc.js
module.exports = {
  root: true,
  env: {
    node: true
  },
  'extends': [
    'plugin:vue/essential',
    '@vue/prettier'
  ],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off'
  },
  parserOptions: {
    parser: 'babel-eslint'
  }
} <-------
```

### What is expected?
3 config files should all have semicolons or not.

### What is actually happening?
`vue.config.js` and `babel.config.js` have semicolons. `.eslintrc.js` and `.postcssrc.js` have no semicolons.

---
It seems that `recast` always print ast code with semicolons.

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli/lib/util/extendJSConfig.js#L59

**Comment by Akryum** [comment]
Do you have an ESLint config selected? If so, it should be applied to the generated files.
