### ISSUE TITLE
build之后，style中中文名字体转义多一个反斜杠

### ISSUE THREAD

**Issue by sjmlsxp** [vuejs/vue-cli#223]
在.vue文件的style部分下
比如：
body {
    font: 12px/1.5  '微软雅黑';
}
build后结果为
body{font: 12px/1.5 \\\\5FAE\8F6F\96C5\9ED1}

造成设置中文字体无效

**Comment by myst729** [comment]
Maybe try `'Microsoft Yahei'` in your font stack?

**Comment by posva** [comment]
Please follow the [contribution guidelines](https://github.com/vuejs/vue-cli/blob/master/CONTRIBUTING.md) and ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
