### ISSUE TITLE
Custom ignore pattern for public folder copy

### ISSUE THREAD

**Issue by miljan-aleksic** [vuejs/vue-cli#2231]
### What problem does this feature solve?
I have assets that are used exlusively for the development and currently I am deleting those after build, but that approach is not ideal. Among others because cli analytics is taking those into account and providing missleading information.

### What does the proposed API look like?
```js
// vue.config.js
module.exports = {
  publicIgnore: [] // glob pattern
]
```

**Comment by LinusBorg** [comment]
I don't think that we should add *yet another* config option for this use case, it doesn't seem common to me, but I may be mistaken. Can you elaborate on your use case a bit?

In any case, you can easily tweak the webpack config for this:

```javascript
chainwebpack: config => {
  config.plugin('copy').tap([options] => {
    // we concat because we already have some default values set by cli-service
    options.ignore.concat([/* your globs here*/])
    return [options]
  })
}
```

https://github.com/webpack-contrib/copy-webpack-plugin#ignore

**Comment by yyx990803** [comment]
What @LinusBorg said - but make sure to use push as concat is non-mutating ;)

**Comment by miljan-aleksic** [comment]
That works perfectly. Thank you guys!

**Comment by janrode** [comment]
@miljan-aleksic did the example above work for you? 
I always get an empty object for `options[0]`

**Comment by miljan-aleksic** [comment]
Probably you omited the destructuring. This is my code:

```js
config.plugin('copy').tap(([options]) => {
  options[0].ignore.push('somefolder/**/*')
  return [options]
})
```

**Comment by tomknappramos** [comment]
Thinking maybe my version of node is outdated, but the [options] syntax gave me an error. 😮 

This worked for me:
```js
chainWebpack: config => {

  config.plugin('copy').tap(options => {
    options[0][0].ignore.push('/**/*');
    return options;
  });

}
```
'/**/*' is for ignoring everything in public/. 👍

**Comment by cpietsch** [comment]
@tomknappramos code works but is missing a ``return options;``
```
chainWebpack: config => {
  config.plugin('copy').tap(options => {
    options[0][0].ignore.push('folderToExclude/**/*');
  });
}
```

**Comment by mamsori** [comment]
> @miljan-aleksic did the example above work for you?
> I always get an empty object for `options[0]`

I've noticed that this error is happening if I add a --modern option

**Comment by dByler1** [comment]
I want to exclude a folder from build, but include it in serve. When I use 
```
config.plugin('copy').tap(([options]) => {
  options[0].ignore.push('somefolder/**/*')
  return [options]
})
```
it ignores the directory on both build and serve. When I use 
```
chainWebpack: config => {
  config.plugin('copy').tap(options => {
    options[0][0].ignore.push('folderToExclude/**/*');
    return options;
  });
}
```
It ignores on build, but gives an error on serve "Path must be a string. Received undefined"

**Comment by Monakiel** [comment]
> 
> 
> I want to exclude a folder from build, but include it in serve.
> When I use the snippet below the directory is ignored on both build and serve.
> 
> ```
> config.plugin('copy').tap(([options]) => {
>   options[0].ignore.push('somefolder/**/*')
>   return [options]
> })
> ```
> 
> When I use the snippet below the directory is ignored on build, but gives an error on serve "Path must be a string. Received undefined"
> 
> ```
> chainWebpack: config => {
>   config.plugin('copy').tap(options => {
>     options[0][0].ignore.push('folderToExclude/**/*');
>     return options;
>   });
> }
> ```

Have you found a solution ?
I'm trying to ignore one folder in my public directory (it's a heavy folder with pictures) but that I don't use (it's from the backend). Since this folder grew, emitting copyPlugin is soooooo long now.
I'm looking on Google since hours without proper solutions. Strange.

**Comment by baxino** [comment]
Does anybody solve this problem?
I have also large folder with pictures in public and when i am developing a site , i need to see a changes when I do changes in a code.. but waiting 5 or more minutes to refresh a view..... is unacceptable.... really there is no viable solution on this problem???

**Comment by damianosz** [comment]
Maybe:
```
options.patterns[0].globOptions.ignore.push('Images/**/*') 
```

**Comment by renzhezhilu** [comment]
my `public` folder contains the `editor` folder, which contains a lot of `node_modules`, so I looked here, but the above method did not work, I tried to analyze the structure of `config.plugins`
and finally found a valid method, the `dist` folder excludes the `editor` folder

@vue2.6.11
@vue/cli 5.0.8
`vue.config.js`
```javascript
module.exports = {
  configureWebpack: (config) => {
    if (process.env.NODE_ENV == "production") {
      let copyIndex = config.plugins.findIndex(
        (f) => f.constructor.name === "CopyPlugin"
      );
      config.plugins[copyIndex].patterns[0].ignore.push("editor/**/*");
      /*
      [
          '.DS_Store',
          { glob: 'index.html', matchBase: false },
          'editor/**/*'
      ]
      */

    }
  };
}


```
