### ISSUE TITLE
it warning that can not find the export function 'getErrorTip'  with the import path `@/public/js/utils`

### ISSUE THREAD

**Issue by admin00001** [vuejs/vue-cli#2232]
### Version
3.0.0

### Node and OS info
node 10.6.0/ npm /windows10

### Steps to reproduce
i defined a function which named `getErrorTip` in the js file :   'src/public/js/utils.js'   like this:
```
getErrorTip() {
// some code
}
module.exports = {getErrorTip}
```

and  i import it into an *.vue file like this: 

```
import {getErrorTip} from '@/public/js/utils'
```
then and i run the serve in the development mode ,

it will tip a warning :
```
warning in .src/xxx/xxxx/x.vue &type=script&lang=js&"export 'getErrorTip' was not found in  '@/public/js/utils' "

```

### What is expected?
no warning

### What is actually happening?
it has warning that can not find the function

---
i think it may be has conflict  when i use the 'public' dir under the 'src' dir  because i import another function that is not under the dir of `src/public` is no problem.

**Comment by Akryum** [comment]
Please use ES modules.
