### ISSUE TITLE
Deployment: 'Unexpected token <' after firebase deploy

### ISSUE THREAD

**Issue by trenoncourt** [vuejs/vue-cli#2233]
### Version
3.0.0

### Node and OS info
Node 9.5.0 / yarn 1.9.4 / Windows 10

### Steps to reproduce
`vue create app` with default (babel/eslint)
`cd app`
`firebase init` with same configuration as [https://cli.vuejs.org/guide/deployment.html#firebase](https://cli.vuejs.org/guide/deployment.html#firebase)
`yarn build`
`firebase deploy`

### What is expected?
App must load normaly with default vue template

### What is actually happening?
Only index.html is loaded, other js/css files are replaced by index.html.
That causes `Uncaught SyntaxError: Unexpected token <` for js files

**Comment by yyx990803** [comment]
Does the app dist build work locally?

**Comment by trenoncourt** [comment]
Yes, and firebase serve works too.

**Comment by yyx990803** [comment]
I'm afraid that's a Firebase problem then. Maybe they have some production only optimization that is rewriting the served files and accidentally breaking things. If the built files work correctly locally, there's nothing we can do in Vue CLI.

**Comment by trenoncourt** [comment]
Okay, I think that too, I'll try to talk it over with them.
thank you

**Comment by topvis** [comment]
@trenoncourt this is a firebase issue. see: https://github.com/firebase/firebase-tools/issues/870
