### ISSUE TITLE
使用 vue ui 指令打开项目一直处于加载中无法展示页面

### ISSUE THREAD

**Issue by TaroXin** [vuejs/vue-cli#2236]
### Version
3.0.0

### Node and OS info
Node v8.11.1 / Yarn 1.6.0 / Windows 10

### Steps to reproduce
运行命令 vue ui

### What is expected?
成功打开UI界面

### What is actually happening?
无法打开UI界面，Loading动画一直加载中，控制台报错

```
TypeError: Object.entries is not a function
    Ze @ vue.runtime.esm.js:1737

```

**Comment by sodatea** [comment]
网页控制台还是终端的控制台？
网页的话，不应该是这个报错啊，`vue.runtime.esm.js` 中并没有用到 `Object.entries`，应该在 `vue-apollo.esm.js` 才对。另外你的浏览器是什么版本号？是否符合这里的兼容性表格？https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#Browser_compatibility

终端报错的话，请看一下是否和 #2215 是一个问题。

**Comment by TaroXin** [comment]
不好意思，是兼容性问题，默认浏览器打开就会报错了，Chrome打开正常，不过错误代码还是在 `vue.runtime.esm.js` 中触发的，具体细节我贴张图片，这个 issues 就没必要了


![tim 20180815234541](https://user-images.githubusercontent.com/19855713/44157572-5cd1ac00-a0e5-11e8-85f4-6a7a1a3333a0.jpg)

**Comment by TaroXin** [comment]
@498184609 你和我不是一个问题 你先看看是不是兼容性问题 不是的话就提一个新的issues去吧

**Comment by shauryshen** [comment]
@498184609 我和你一样的问题，重装了node还是不行，请问你解决了吗
