### ISSUE TITLE
Mac Vue UI界面无法下载远程Preset

### ISSUE THREAD

**Issue by TaroXin** [vuejs/vue-cli#2237]
### Version
3.0.0

### Node and OS info
Node v8.11.1 / Yarn 1.6.0 / MacOS 10.13.5

### Steps to reproduce
1. 使用Vue UI创建项目，输入项目名称，下一步
2. 点击配置远程预设
3. 输入 `https://github.com/TaroXin/vue-cli-creator-preset.git`, 并开启私有仓库选项，点击完成
4. 点击创建项目

### What is expected?
成功根据预设内容创建项目

### What is actually happening?
无法创建项目，并且报错
```
✔  Fetching remote preset https://github.com/TaroXin/vue-cli-creator-preset.git...
 ERROR  Failed fetching remote preset https://github.com/TaroXin/vue-cli-creator-preset.git:
Error: 'git clone' failed with status 128
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/git-clone/index.js:33:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
```

直接运行 `git clone https://github.com/TaroXin/vue-cli-creator-preset.git`可以clone项目

**Comment by sodatea** [comment]
公开仓库请不要勾选私有仓库选项

这个评论可以参考下
https://github.com/flipxfx/download-git-repo/issues/19#issuecomment-365971553

我现在没有私有仓库供测试实际碰到私有仓库时会怎样，等我明天升级下付费账户试试

**Comment by sodatea** [comment]
刚搞清楚了……
对于 GitHub 的私有仓库，download-git-repo 要求传 SSH 地址进去，但是要去掉开头的 `git@` 和最后的 `.git`。
`github.com:TaroXin/vue-cli-creator-preset` 这样的地址才能被正确解析。

这个可以考虑在文档里提一下这点或者在代码里调用 download-git-repo 前优化一下。

**Comment by TaroXin** [comment]
如果不勾选这是私有仓库选项，完成按钮是无法点击的


![image](https://user-images.githubusercontent.com/19855713/44181402-369d1380-a0c7-11e8-9e3b-3552ea65c03e.png)

**Comment by sodatea** [comment]
嗯，公开仓库格式是 user/repo 或者 gitlab:user/repo，私有仓库格式是 github.com:user/repo

**Comment by jeffhuang2086** [comment]
@sodatea    您好，我也遇到了相同的问题，但是还没有解决，请问这个远程拉取的git地址应该怎样写？感谢

**Comment by sodatea** [comment]
@jeffhuang2086 请参考 [download-git-repo 的文档](https://github.com/flipxfx/download-git-repo#examples)

**Comment by tomieric** [comment]
3Q，测试可用 👍 

 ```
> vue create --preset direct:https://gitlab.xxx.xx/vue-preset.git --clone 项目名称
```

**Comment by haitaodesign** [comment]
文档里面说的不是很清楚呀，搞了好久呀！
