### ISSUE TITLE
build produces code with `const` in it

### ISSUE THREAD

**Issue by katerlouis** [vuejs/vue-cli#2238]
### Version
3.0.0-rc.12

### Node and OS info
node 10.7.0, npm 6.3.0

### Steps to reproduce
– Download the project http://dumbo.design/vue-cli-bug.zip 
   [please tell me when you've downloaded this, I want to remove it]
– open vue-cli ui, and build a "normal" webapp in production mode
– open project in IE11 or Safari 9.1 for instance
– observe the bug in the console
– look at the `chunk-vendors.js` and in `/dist`

### What is expected?
That vue-cli / webpack handles es6 features (like `const`) 

### What is actually happening?
My guess: somehow the plugins from gsap-bonus folder are ignored when it comes to babeling? All I know is the code is breaking in IE11 and Safari 9.1, probably more browsers

---

I've set up the project with vue-cli ui, serve and build using the ui aswell. 
I installed GreenSocks GSAP via npm, alongside with jquery. 

GreenSock offers plugins, which you only get by joining their Club Green– these plugins obviously cannot be served via npm; which is why you have to download them separately. I've put them in `gsap-bonus` in the root folder and import them like any other import– 

I of course have babel installed–

```js
// package.json
// ...
"browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```

Some screenshots to make things more clear

![image](https://user-images.githubusercontent.com/1983382/44156350-029e6834-a0b0-11e8-89da-b3f89f9e03b8.png)

![image](https://user-images.githubusercontent.com/1983382/44156367-057affd6-a0b0-11e8-904e-b6a2569e1223.png)

![image](https://user-images.githubusercontent.com/1983382/44156444-293fc456-a0b0-11e8-9d76-20f33022c2b9.png)

![image](https://user-images.githubusercontent.com/1983382/44156538-680a7d66-a0b0-11e8-9ea3-18d6ee0e6c76.png)

**Comment by sodatea** [comment]
It's the `gsap/CSSPlugin` module required by `gsap-bonus` that did not get transpiled.

To solve this problem, add the following config to `vue.config.js`:
```
transpileDependencies: ['gsap']
```

**Comment by katerlouis** [comment]
Thank you!
Found a simliar explanation in the GSAP docs

https://greensock.com/docs/NPMUsage
