### ISSUE TITLE
Vue-cli 3 how to integrate karma ?

### ISSUE THREAD

**Issue by BengBu-YueZhang** [vuejs/vue-cli#2241]
### What problem does this feature solve?
karma Unit Testing

### What does the proposed API look like?
Vue-cli 3 integration karma

**Comment by sodatea** [comment]
It is supported by a third party plugin https://github.com/davidwallacejackson/vue-cli-plugin-unit-karma

**Comment by mcshaz** [comment]
Note that this plugin seems to be failing [vue-cli ≥ 3.1](https://github.com/davidwallacejackson/vue-cli-plugin-unit-karma/issues/9) & I cannot see anything from the author in 6 months at the time of writing.

**Comment by mcshaz** [comment]
*update*
new project here: https://github.com/tushararora/vue-cli-plugin-unit-karmajs

**Comment by k186** [comment]
with vue cli3 and  @vue/test-utils ;base on @mcshaz ,gen repoert fine with https://github.com/k186/vue-cli-plugin-unit-karmajs
