### ISSUE TITLE
npm run build is placing images under dist root

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-cli#2242]
### Version
3.0.0

### Node and OS info
node v8.11.1 yarn 1.7.0 window 10

### Steps to reproduce
npm run build 超过4KB大小图片生成的位置在dist根目录下。

### What is expected?
期望：生成的图片放在img 文件夹下。

### What is actually happening?
生成的图片在dist根目录下。

**Comment by thomasyus** [comment]
遇到了同样的问题，此问题只存在windows系统下，Mac下无此问题

**Comment by zz12313** [comment]
@thomasyus ……

**Comment by panjiang** [comment]
The same bug happening in my MacOS.

**Comment by julytian** [comment]
The same bug happening in windows

**Comment by yyx990803** [comment]
This is a regression in `url-loader` 1.1.0...

**Comment by yyx990803** [comment]
This has been fixed in https://github.com/webpack-contrib/url-loader/commit/401be635da13ed19be389af2b28764302a3e5cdc. Waiting for their release...

**Comment by kevinfaguiar** [comment]
any prediction for the release of the next version containing this fix? is there a way that I can make this fix with vue.config.js?

**Comment by yyx990803** [comment]
If you use yarn you can explicit pin `url-loader` to 1.0.1 using `resolutions` field in your package.json.

**Comment by RequireSun** [comment]
我也遇到了这个问题，现在 `build` 命令形成的目录结构是 ok 的，`build --watch` 命令形成的目录结构是错误的，而且还不会生成 source-map（系统是 win10）。

错误的（build --watch）：
![image](https://user-images.githubusercontent.com/7576691/46348022-2e516580-c680-11e8-8684-4728a236604b.png)

正确的（build）：
![image](https://user-images.githubusercontent.com/7576691/46347956-e7637000-c67f-11e8-8d63-fcd9cc796fb0.png)

最后再弱弱的问一句，默认的图片输出目录是 `img/`，假如说我想给他改成 `image/`，该修改哪个参数呢
