### ISSUE TITLE
When there are errors during compiling, the compile stuck at 94% and didn't show errors' detail.

### ISSUE THREAD

**Issue by smalllong** [vuejs/vue-cli#2244]
### Version
3.0.0

### Reproduction link
https://github.com/smalllong/vue-cli-issue

### Node and OS info
node 8.9.4 / yarn 1.2.1 / windows 8.1

### Steps to reproduce
Create a new project use @vue/cli 3.0, then make some errors in code so that compile error happens

### What is expected?
the errors' details are shown in console

### What is actually happening?
the console only shows "Failed to compile with 1 errors" without any detail

**Comment by sodatea** [comment]
https://github.com/geowarin/friendly-errors-webpack-plugin/issues/69#issuecomment-394142242

**Comment by q569608465** [comment]
I have also encountered this problem. Has this problem been solved?

**Comment by qinkaiyuan** [comment]
@sodatea how i can solve this problem?Now my project cannot run on mac
