### ISSUE TITLE
Cannot import project via "import project" button

### ISSUE THREAD

**Issue by BlitZz96** [vuejs/vue-cli#2247]
### Version
3.0.0

### Node and OS info
Node 10.6.0 / NPM 6.1.0 / macOS 10.13.6

### Steps to reproduce
install vue cli
run command `vue ui`, get `Error: Cannot find module 'core-js/modules/es7.object.entries' `
fix this by doing `npm i core-js -g`
run command `vue ui` again, and it works.
Find project and click "import this folder"

### What is expected?
Project to be imported to vue cli

### What is actually happening?
Nothing

---
The "import this folder" button is active(green).

If I try to import an vue plugin(eg vuejs-datepicker), it works.

The project has not been generated by a previous vue-cli. Is this the issue? If so, how does one import a "rouge" project?

**Comment by Akryum** [comment]
The cli ui can only import Javascript projects that contains a `package.json` file. Do you have a minimal reproduction of a project you can't import?

**Comment by mhldtna** [comment]
I had this problem - turned out to be syntax errors in the package.json file.  Would be nice to have an error message....

BUT - after I fixed the syntax errors, the import function ran "forever".

**Comment by mhldtna** [comment]
I had this problem.  Turned out to be syntax errors in the package.json file.  Would be nice to have an error message....

**Comment by LinusBorg** [comment]
Closing for inativity.
