### ISSUE TITLE
建议增加静态资源CDN地址配置项

### ISSUE THREAD

**Issue by libin1991** [vuejs/vue-cli#2250]
### Version
3.0.0

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Node and OS info
8.11.1 / npm / mac

### Steps to reproduce
官网建议:请始终使用 baseUrl 而不要修改 webpack 的 output.publicPath。

但是一般网站静态资源都放置CDN上，建议增加静态资源CDN地址配置项，

### What is expected?
增加静态资源CDN配置项

### What is actually happening?
没有对应设置静态资源CDN地址

**Comment by yyx990803** [comment]
baseUrl 就是。

**Comment by hank2718** [comment]
能不能给我demo

**Comment by rushairer** [comment]
@yyx990803 
Vue Cli v3.0.1
Vue v2.5.17
VueRouter v3.0.1 use HTML5 history

设置baseUrl为CDN域名，在生产环境下，使用 `this.$router.push('/login')` 调整后浏览器地址栏变成 http://生产域名/http://cdn域名/login

**Comment by erniu** [comment]
> baseUrl 就是。

baseUrl 后来被publicPath取代，cli3之前是直接作用于webpack.output.publicPath本身的，但是目前publicPath和Router的base选项冲突了。

特别不好描述，如果需要，我回头可以补一个仓库

**Comment by wh469012917** [comment]
@erniu 这个问题请问你解决了吗？我也碰到这个问题了

**Comment by erniu** [comment]
尝试去掉router的base选项试试------------------ 原始邮件 ------------------
发件人: "翁航"<notifications@github.com>
发送时间: 2020年2月18日(星期二) 上午8:38
收件人: "vuejs/vue-cli"<vue-cli@noreply.github.com>;
抄送: "erniu"<25457788@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [vuejs/vue-cli] 建议增加静态资源CDN地址配置项 (#2250)



@erniu 这个问题请问你解决了吗？我也碰到这个问题了
 
&mdash;
