### ISSUE TITLE
transpileDependencies doesn't work on windows

### ISSUE THREAD

**Issue by MarvinXu** [vuejs/vue-cli#2251]
### Version
3.0.1

### Reproduction link
https://github.com/MarvinXu/vue-cli-transpile-test

### Node and OS info
Node 9.6.1 / npm 5.6.0 / window 7

### Steps to reproduce
```javascript
// vue.config.js
module.exports = {
  transpileDependencies: ['@my/module']
}
// node_modules/@my/module/index.js
let somevar = '@my/module';
document.writeln(somevar);

```
```
npm run build
```

### What is expected?
transpile specified node_module correctly

### What is actually happening?
not transpile node_module 
![image](https://user-images.githubusercontent.com/7382357/44700636-d17cf100-aabc-11e8-8283-da831736d488.png)

**Comment by yyx990803** [comment]
Cannot reproduce, it's working as intended. Closed until a valid reproduction is provided.

**Comment by MarvinXu** [comment]
@yyx990803 I kind of figured it out. This problem has nothing to do with 'dev mode' but with OS. I'm using Windows and the compiler machine is Linux.

https://github.com/vuejs/vue-cli/blob/b20f624c32a5a82e7ae5b48369068039be881251/packages/%40vue/cli-plugin-babel/index.js#L20
On windows, modules with a namespace (eg: @my/module) won't match in the above code.

**Comment by yyx990803** [comment]
@sodatea should be an easy fix
