### ISSUE TITLE
vue cli3打包test环境,样式不打包,

### ISSUE THREAD

**Issue by UvDream** [vuejs/vue-cli#2252]
### Version
3.0.0

### Reproduction link
[https://github.com/UvDream/at-admin](https://github.com/UvDream/at-admin)### Node and OS info
yarn,npm

### Steps to reproduce
我发现vue cli3打包test的时候样式不打包,同样development也是,只有production才会打包样式

### What is expected?
期望打包分环境打包样式都能打包

### What is actually happening?
现在只有production打包才会这样

**Comment by yyx990803** [comment]
只要是打包就应该用 NODE_ENV=production。你没理解 mode 的用法。

**Comment by UvDream** [comment]
现在打包选择test,dist文件夹找不到css,丢到服务器没有样式,不知道为什么

**Comment by sodatea** [comment]
前面回复过了，**只要是打包就应该用 `NODE_ENV=production`**
`mode = 'test'` 是给 unit test 之类的场景用的

**Comment by sodatea** [comment]
前面回复过了，**只要是打包就应该用 `NODE_ENV=production`**
`mode = 'test'` 是给 unit test 之类的场景用的

**Comment by UvDream** [comment]
好吧,那就是打包不区分环境
