### ISSUE TITLE
Build fails when using Standard for eslint

### ISSUE THREAD

**Issue by ErikBrown** [vuejs/vue-cli#2255]
### Version
3.0.0

### Node and OS info
Node 10.4.1 / npm 6.1.0 / Ubuntu 16.04

### Steps to reproduce
$ vue create hello-world
Select the `Standard` linter then build the project.

### What is expected?
Project builds as expected.

### What is actually happening?
Throws the following error:

> npm ERR! notarget No matching version found for @vue/eslint-config-standard@^3.0.1

There is no version 3.0.1 for the standard config in the npm repo.

**Comment by ErikBrown** [comment]
Your issue helper utility is not currently functioning: https://github.com/vuejs/vue-cli/issues/2255

**Comment by yyx990803** [comment]
Looks like 3.0.1 release got messed up by lerna... missing some packages. Looking into it now.

**Comment by yyx990803** [comment]
All missing packages have been published.
