### ISSUE TITLE
Invalid src:url for font-face when building a library

### ISSUE THREAD

**Issue by qspoerri** [vuejs/vue-cli#2260]
### Version
3.0.1

### Reproduction link
[https://github.com/qspoerri/vue-cli-font](https://github.com/qspoerri/vue-cli-font)

### Node and OS info
Yarn 1.6.0 / Node 8.11.3 / Windows 7 professional

### Steps to reproduce
run ```yarn build-lib``` to generate a library build

### What is expected?
The font-face's ```src:url``` should be set correctly.

### What is actually happening?
When generating a library containing fonts, the **dist** directory has the following structure:

```
.
 -- fonts
|    -- FiraSans-Bold.bf0aaa9c.woff
|    -- FiraSans-Book.6d4e4a15.woff
|    -- FiraSans-Light.29430787.woff
|-- img
|     -- logo.82b9c7a5.png
 -- logo.82b9c7a5.png
 -- myLib.common.js
 -- myLib.css
 -- myLib.umd.js
```

Unfortunately, in ```myLib.css``` the urls for the font-faces seems incorrect moving to the parent directory: 

```css
@font-face{font-family:FiraSans-Book;font-style:normal;font-weight:400;src:url(../fonts/FiraSans-Book.6d4e4a15.woff)} 
```
    
Therefore, when using the library the font-face is not loaded correctly.

---
The problem occured when I was trying to create a library of shared components to be reused across serveral different application. 

For consistency, the fonts should be included in the library

**Comment by yyx990803** [comment]
This is fixed, but it may not be the best idea in bundle fonts in a library...

**Comment by qspoerri** [comment]
Thank you very much for the quick fix!!

Your advice would be importing the fonts directly in the projects that needs them?

**Comment by crazyxhz** [comment]
@yyx990803 can you release this bug fix? I'm also having a library who's font is broken now 😂

**Comment by katerlouis** [comment]
Does this fix solve the same issue for static images?
And background-images in css?

I use it with the `@` alias (`~@` in css) – 

I have a major release on monday and really need this library to work. If there is no chance releasing this bug fix, could you maybe tell us what / how to fix it ourselves? 🤕 

Or maybe another workaround to get the assets working?

Thank you!

**Comment by sodatea** [comment]
@katerlouis in `vue.config.js`:
```js
module.exports = {
  chainWebpack: config => {
    if (process.env.VUE_CLI_BUILD_TARGET === "lib") {
      const langs = ["css", "postcss", "scss", "sass", "less", "stylus"];
      const matches = ["vue-modules", "vue", "normal-modules", "normal"];

      langs.forEach(lang =>
        matches.forEach(match =>
          config.module
            .rule(lang)
            .oneOf(match)
            .use("extract-css-loader")
            .loader(require("mini-css-extract-plugin").loader)
            .options({
              publicPath: "./"
            })
        )
      );
    }
  }
};
```

**Comment by katerlouis** [comment]
Could it be that the commited changes (https://github.com/vuejs/vue-cli/commit/1973e2de2c7d7cebed38e037ccae9331ff849841) are still not shipped yet?

I have the latest vue-cli version installed (3.0.1) 
![image](https://user-images.githubusercontent.com/1983382/45354598-46bceb80-b5be-11e8-9184-8a31c1e28506.png)

When I create a fresh vue-cli project
![image](https://user-images.githubusercontent.com/1983382/45354665-78ce4d80-b5be-11e8-89b3-c37e6deccf94.png)

![image](https://user-images.githubusercontent.com/1983382/45354717-a0bdb100-b5be-11e8-9aa7-c3c2016d791f.png)


The changes are not there yet:
![image](https://user-images.githubusercontent.com/1983382/45354772-cd71c880-b5be-11e8-9f00-ed9bc6a76ac6.png)
![image](https://user-images.githubusercontent.com/1983382/45354792-dbbfe480-b5be-11e8-8f02-5690603dcdc5.png)

**Comment by katerlouis** [comment]
Bam, and then why not go straight to 3.0.3 :D 
<img width="151" alt="image" src="https://user-images.githubusercontent.com/1983382/45410861-17b48180-b673-11e8-8df8-c6d5e30201ff.png">

So the change wasn't in there although it got commited before 3.0.1? Crazy! Just when I think I started to understand Git :D
