### ISSUE TITLE
Projects are not visible on GUI

### ISSUE THREAD

**Issue by samarkandiy** [vuejs/vue-cli#2264]
### Version
3.0.1

### Node and OS info
latest node

### Steps to reproduce
The projects are not visible 

### What is expected?
See the project list

### What is actually happening?
Empty page

**Comment by LinusBorg** [comment]
This description is not nearly enough to work on this in any way.

Please at least provide a step-by-step process to reproduce what you are seeing.

Also provide more environment information than "latest node"

**Comment by yyx990803** [comment]
Sorry but we don't triage issues like this. Please respect maintainers' time.
