### ISSUE TITLE
'vue' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by allenshaji** [vuejs/vue-cli#2268]
Node version : v8.11.4
npm version: 5.6.0
Commands fired

npm install -g vue-cli
npm install -g vue
vue install wepack test
Following error is thrown

'vue' is not recognized as an internal or external command,operable program or batch file.

When I type vue -v also, I am getting the above error

I also added to  windows the path of Vue.js
![screenshot 10](https://user-images.githubusercontent.com/29088559/44297838-199a5780-a2f6-11e8-8771-eecb0434b332.png)

I also noticed that vue.cmd is not coming the following directory
C:\Users\HP\AppData\Roaming\npm

Can anybody please help me to sort the problem

**Comment by hquangthien** [comment]
The package name changed from vue-cli to @vue/cli. If you have the previous vue-cli (1.x or 2.x) package installed globally, you need to uninstall it first with npm uninstall vue-cli -g or yarn global remove vue-cli.

**Comment by allenshaji** [comment]
Sure sir, thanks for the same. I have downloaded and provided that path in windows and it worked for me

**Comment by Attory** [comment]
Hi allenshaji, I'm getting the same error. Can you tell me what you have downloaded and which path you provided in windows that helped you? Thank you!

**Comment by gomnamserri** [comment]
Please make sure 

> C:\Users\Your_User_Name\AppData\Roaming\npm
is added to System Variable Paths

**Comment by beldrevo** [comment]
Try to search vue.cmd on your machine, then add this path to evn variables. This worked for me.

**Comment by nanitkatipunan** [comment]
hi! i would like to ask on how to fix this issue  'vue-cli-service' is not recognized as an internal or external command,
operable program or batch file. I try to use npm install --global @vue/cli but it doesn't work

**Comment by adityar003** [comment]
> Node version : v8.11.4
> npm version: 5.6.0
> Commands fired
> 
> npm install -g vue-cli
> npm install -g vue
> vue install wepack test
> Following error is thrown
> 
> 'vue' is not recognized as an internal or external command,operable program or batch file.
> 
> When I type vue -v also, I am getting the above error
> 
> I also added to windows the path of Vue.js
> ![screenshot 10](https://user-images.githubusercontent.com/29088559/44297838-199a5780-a2f6-11e8-8771-eecb0434b332.png)
> 
> I also noticed that vue.cmd is not coming the following directory
> C:\Users\HP\AppData\Roaming\npm
> 
> Can anybody please help me to sort the problem

Please make sure
 to add
C:\Users\Your_User_Name\AppData\Roaming\npm
to the Paths in Environment Variables.

**Comment by abhinavsri360** [comment]
thanks this helped 😄

**Comment by Michal-Dziedzinski** [comment]
One thing, if You are using Yarn use 
`C:\Users{YourAccount}\AppData\Local\Yarn\bin` instead
