### ISSUE TITLE
error in documentation

### ISSUE THREAD

**Issue by akarelas** [vuejs/vue-cli#2272]
### Version
3.0.1

### Reproduction link
[https://cli.vuejs.org/guide/css.html#pre-processors](https://cli.vuejs.org/guide/css.html#pre-processors)

### Node and OS info
N/A

### Steps to reproduce
Look at the above link, where it says $color = red

### What is expected?
It should say $color: red;

### What is actually happening?
It says $color = red;

**Comment by yyx990803** [comment]
Tip: for small errors in docs, it's better to directly submit a PR to fix it.
