### ISSUE TITLE
@vue/cli 3.x 创建项目失败

### ISSUE THREAD

**Issue by forest-green** [vuejs/vue-cli#2274]
### Version
3.0.1

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue-cli](https://new-issue.vuejs.org/?repo=vuejs/vue-cli)

### Node and OS info
node: v8.11.1   npm: 5.8.0    windows

### Steps to reproduce
1.使用npm install -g @vue/cli安装全局包
2.使用vue --version检测版本，确认安装成功欧冠
3.使用vue create demo 来创建项目
4.使用非默认的来创建，中间到某个包的时候，提示安装失败
5. 使用npm cache clean --force清除包缓存
6.再次创建项目，无论是默认的还是非默认的 都提示失败

### What is expected?
能够使用非默认模式来创建项目框架

### What is actually happening?
创建失败

**Comment by sodatea** [comment]
请提供详细错误信息，并排除是网络问题，按目前的描述我们并没有办法帮上忙……

**Comment by yyx990803** [comment]
报错信息至少提供一下吧？某个包到底是哪个包？你这种问题显然不是人人都会遇到，我们 debug 难道用猜的吗。

**Comment by forest-green** [comment]
首先，很抱歉，当时没有把报错信息，粘贴上来。今天上午我又重新安装了一下，使用非默认的配置来进行，选项如下
`Vue CLI v3.0.0
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, PWA, Router, Vuex, CSS Pre-processors, Linter, Unit, E2E
? Use history mode for router? (Requires proper server setup for index fallback in production) Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): SCSS/SASS
? Pick a linter / formatter config: Prettier
? Pick additional lint features: Lint on save
? Pick a unit testing solution: Jest
? Pick a E2E testing solution: Nightwatch
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? Yes
? Save preset as:`

报错信息如下：
`npm ERR! Unexpected end of JSON input while parsing near '...":"^2.0.2","babel-loa'

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\User\XXXXXX\AppData\Roaming\npm-cache\_logs\2018-08-20T00_54_52_411Z-debug.log
 ERROR  command failed: npm install --loglevel error --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist`

网上查询，报上述错误，是因为npm缓存导致，使用`npm cache clean --force` 清除缓存，再次安装，就会卡在这里
` fetchMetadata: sill fetchPackageMetaData error for caniuse-lite@^1.0.30000864 Unexpected end of JSON input while parsing near '...ster":"^6.18.0`
我估计可能是由于网络的原因，然后改为4G网络进行安装，依然不能完整的安装。
在安装过程中只要出现一次报错，后面清除npm缓存，和删除起npm-cache文件夹，重启电脑，重新全局安装cli，都不能使用非默认的配置进行

**Comment by forest-green** [comment]
这个是从早上开始 安装 一直到下午四点半的报错信息
`Vue CLI v3.0.0
✨  Creating project in D:\workSpace\demo-cli3.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUNDnear '...ster":"^6.18.0
npm ERR! network request to https://registry.npm.taobao.org/caniuse-lite failed, reason: getaddrinfo ENOTFOUND registry.npm.taobao.org registry.npm.taobao.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\User\dongzhiwen\AppData\Roaming\npm-cache\_logs\2018-08-20T07_57_43_450Z-debug.log
 ERROR  command failed: npm install --loglevel error --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist`

**Comment by sodatea** [comment]
> This is a problem related to network connectivity

很明确是网络问题了。
getaddrinfo 错误有可能是跟你的 DNS 有关，也可能是其他问题。

可以尝试一下使用官方 registry 而不是淘宝镜像：

修改用户根目录下的 `.vuerc` 文件
其中的 `useTaobaoRegistry` 字段设置为 `false`

**Comment by forest-green** [comment]
好的，谢谢

**Comment by liujiabin522** [comment]
@yyx990803 我得到了这样的三个error：
<img width="692" alt="wechatimg50" src="https://user-images.githubusercontent.com/41563246/47074595-481cac00-d22d-11e8-81e9-e65b7457e9ad.png">
这是我初始化项目的配置：
![wechatimg51](https://user-images.githubusercontent.com/41563246/47074748-9f228100-d22d-11e8-988f-6789accc3d3a.jpeg)

**Comment by sodatea** [comment]
@liujiabin522 See https://github.com/vuejs/vue-cli/issues/2709#issuecomment-428928462

**Comment by liujiabin522** [comment]
@sodatea OK, I got it and why?

**Comment by liujiabin522** [comment]
> @liujiabin522 See [#2709 (comment)](https://github.com/vuejs/vue-cli/issues/2709#issuecomment-428928462)

@sodatea OK, I got it and why?

**Comment by 136shine** [comment]
![image](https://user-images.githubusercontent.com/17799685/59351626-6b164600-8d51-11e9-975b-1ff581549a8e.png)
I didn't have error, but just three files, I try to `npm cache clean --force` and restart the win10 ,  has anyone ever made a mistake like this? thanks~

**Comment by umono** [comment]
@sodatea 

getaddrinfo ENOTFOUND false 

![image](https://user-images.githubusercontent.com/12220933/59939371-53923800-948a-11e9-823a-d2f561ac6847.png)

**Comment by sodatea** [comment]
@umono 
1. This issue is unrelated to your problem and has been closed for a long time, please open a new issue
2. Please provide actual code for reproduction purpose. We can't debug with a screenshot.
3. In this case, it's likely that you have an environment variable called `$HOST` and its value set to `false`. Please unset it and try again. Otherwise you'll have to [explicitly set the host](https://webpack.js.org/configuration/dev-server/#devserverhost) in `vue.config.js`

**Comment by yeru130** [comment]
安装没有问题，怀疑你的网络问题，自己配置安装的

**Comment by LEOChenZF** [comment]
![image](https://user-images.githubusercontent.com/49238161/75665797-b1c91900-5caf-11ea-88c4-7ad55294b892.png)
您好,我的报错为什么和你们的不一样? 一直找不到原因,能否有知情人透露一下我是哪里的问题?

**Comment by sodatea** [comment]
@LEOChenZF 你的问题是用了 root 用户，参见 https://cli.vuejs.org/guide/troubleshooting.html#running-installation-with-sudo-or-as-root

**Comment by LEOChenZF** [comment]
> @LEOChenZF你的问题是用了root用户，参见https://cli.vuejs.org/guide/troubleshooting.html#running-installation-with-sudo-or-as-root
谢谢你的提醒 我已解决了问题

**Comment by LEOChenZF** [comment]
@sodatea  谢谢您的提醒 , 我已经您给的提示解决了我的问题
