### ISSUE TITLE
[worker-loader] window is not defined

### ISSUE THREAD

**Issue by screendriver** [vuejs/vue-cli#2276]
### Version
3.0.1

### Reproduction link
[https://github.com/screendriver/vue-cli-worker-loader-bug](https://github.com/screendriver/vue-cli-worker-loader-bug)

### Node and OS info
Node 10.9.0 / yarn 1.9.4 / macOS high sierra

### Steps to reproduce
Just do a `yarn serve` and open http://localhost:8080 in your browser. You can see the error immediately.

### What is expected?
Should not throw `Uncaught ReferenceError: window is not defined`.

### What is actually happening?
Throws the error and doesn't work.

**Comment by Hebilicious** [comment]
I ran into similar issues in a worker-loader + webpack-worker-wrapper setup. You can work around it by adding this to your vue.config.js : 
```js
module.exports = {
  chainWebpack: config => {
    config.output.globalObject('this')
  }
}
```
... and doing something like this in your worker.js files :

```js
import workerGlobals from './workerGlobals.js'
```

and in workerGlobals.js
```js
//Comment the lines you don't need.
global.process = process
window = undefined
```

**Comment by ngohuunam** [comment]
this work for me, add to vue.config.js
`  configureWebpack: {
    output: {
      globalObject: 'this',
    },
  },`

**Comment by screendriver** [comment]
Oh it works. Great! 
Maybe it would be a good idea to include that webpack loader directly into vue cli? 🤔

**Comment by Kocal** [comment]
Take a look to #2286!

**Comment by screendriver** [comment]
@Kocal that "just" fixes the issue where I have to add `configureWebpack: { output: { globalObject: 'this', }, }` manually to my project but **not** that [worker-loader](https://github.com/webpack-contrib/worker-loader) will be add by `vue-cli` automatically (or via propmt) 😉
