### ISSUE TITLE
 ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

### ISSUE THREAD

**Issue by Deviad** [vuejs/vue-cli#2277]
### Version
3.0.1

### Reproduction link
[https://github.com/Deviad/vuejs-typescript-playground](https://github.com/Deviad/vuejs-typescript-playground)

### Node and OS info
npm 9.9.0

### Steps to reproduce
run npm run serve --port 6000 --host "0.0.0.0" or any port working on your system

### What is expected?
The dev web server should be running using the given parameters without throwing the aforementioned error. 

### What is actually happening?
The dev web server throws  ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

### Additional notes

The problem is happening with or without Babel and with our without Jest.

**Comment by sodatea** [comment]
https://docs.npmjs.com/cli/run-script

`--` is required to pass arguments to npm scripts.

So the correct command is: `npm run serve -- --port 6000 --host "0.0.0.0"`

**Comment by Deviad** [comment]
Thank you @sodatea.
