### ISSUE TITLE
Docs: Support to pt-br lang

### ISSUE THREAD

**Issue by hericlesme** [vuejs/vue-cli#2279]
### What problem does this feature solve?
Add support to pt-br language in the documentation. 

### What does the proposed API look like?
The current documentation on https://cli.vuejs.org/guide/ is only available in English, Russian and Chinese. After this change, this will also be available in Portuguese.

**Comment by yyx990803** [comment]
We are open to translations, but we can't do it ourselves.

**Comment by hericlesme** [comment]
I can translate. I'm already working on it.
