### ISSUE TITLE
Question : Packaging Single Component or Library of Components for Use

### ISSUE THREAD

**Issue by rwatts3** [vuejs/vue-cli#228]
Greetings, 

What is the simplest way using the vue-cli to package a library of components or a single component for external use.

-V/R

Ryan

**Comment by posva** [comment]
There's no simplest way 😄  It depends on what you know already. You can do it with rollup or with webpack using the existing templates but make it a UMD by passing the right option to the bundler

**Comment by rwatts3** [comment]
Hi thank you for the reply do you have an example if how to do this with webpack . such as how are the devs on vuecomponents.com bundling their contributions for distribution.

**Comment by posva** [comment]
Something like this: https://github.com/posva/vue-mdl/blob/develop/build/webpack.dist.prod.conf.js
But this is unrelated to vue so you can find information really easily searching other keywords 😉

**Comment by rwatts3** [comment]
Thank you I appreciate your time.
