### ISSUE TITLE
when i change the files , the webpack can't recompile sometime

### ISSUE THREAD

**Issue by githubmann** [vuejs/vue-cli#229]
environment: westorm 2016.2.4,win10, webpack template

**Comment by githubmann** [comment]
webstorm have safe write mode,this will save changes to a temporary file first[http://stackoverflow.com/questions/34213253/webpack-watch-not-working-on-webstorm-on-windows](url)

**Comment by posva** [comment]
I fixed the link on your comment 🙂

**Comment by joaoprado** [comment]
I'm having the same issue for a few days and can't figure out how to fix it. My environment is Fedora 24 + Sublime. Node 6.9.1 and NPM 3.10.8.

When I run `npm run dev` it compiles the files but doesn't watch for changes ever. This is from a fresh install, no custom dependencies were added.
