### ISSUE TITLE
Can't run project during production mode in vue-cli3

### ISSUE THREAD

**Issue by Sukhpal-Singh** [vuejs/vue-cli#2298]
I had created a project using vue-cli3. It running smoothly on development mode without any error but in production mode ,page is not redirecting. It shows console error as follows:
```
Uncaught SyntaxError: Unexpected token <
vue-router.esm.js:1905 Error: Loading chunk chunk-ccb2 failed.
(missing: http://localhost:5000/default/dashboard/js/chunk-ccb2.8d835f25.js)
    at HTMLScriptElement.c (bootstrap:176)
```
What will be the issue in it? Anyone knows?

**Comment by wangyajundev** [comment]
output: {
        publicPath: '/', // FIX: Uncaught (in promise) Error: Loading chunk # failed. async
}

**Comment by wangyajundev** [comment]
> I had created a project using vue-cli3. It running smoothly on development mode without any error but in production mode ,page is not redirecting. It shows console error as follows:
> 
> ```
> Uncaught SyntaxError: Unexpected token <
> vue-router.esm.js:1905 Error: Loading chunk chunk-ccb2 failed.
> (missing: http://localhost:5000/default/dashboard/js/chunk-ccb2.8d835f25.js)
>     at HTMLScriptElement.c (bootstrap:176)
> ```
> What will be the issue in it? Anyone knows?

output: {
        publicPath: '/', // FIX: Uncaught (in promise) Error: Loading chunk # failed. async
}

https://blog.francium.tech/vue-lazy-routes-loading-chunk-failed-9ee407bbd58

**Comment by wangyajundev** [comment]
> I had created a project using vue-cli3. It running smoothly on development mode without any error but in production mode ,page is not redirecting. It shows console error as follows:
> 
> ```
> Uncaught SyntaxError: Unexpected token <
> vue-router.esm.js:1905 Error: Loading chunk chunk-ccb2 failed.
> (missing: http://localhost:5000/default/dashboard/js/chunk-ccb2.8d835f25.js)
>     at HTMLScriptElement.c (bootstrap:176)
> ```
> What will be the issue in it? Anyone knows?

output: {
        publicPath: '/', // FIX: Uncaught (in promise) Error: Loading chunk # failed. async
}

https://blog.francium.tech/vue-lazy-routes-loading-chunk-failed-9ee407bbd58
