### ISSUE TITLE
Invalid component markup works in dev but fails silently in production

### ISSUE THREAD

**Issue by rjoo** [vuejs/vue-cli#23]
````html
<component v-bind:attr="..." attr-one="..." attr-two="..." /></component>
````

Using the full webpack template. The above might be a silly typo but it's easy to overlook and I'm quite surprised that it works perfectly fine in the dev server. I had a real head scratcher when I ran the production build and everything after the above would not render without any warnings.

**Comment by yyx990803** [comment]
This will be now get caught by `vue-template-validator@1.1.4`. Update `vue-loader` and you should no longer run into this.
