### ISSUE TITLE
我按照官网一步一步执行，却还是报错npm install --save ~entry

### ISSUE THREAD

**Issue by qinkaiyuan** [vuejs/vue-cli#2305]
### Version
3.0.1

### Reproduction link
[https://cli.vuejs.org/zh/guide/prototyping.html](https://cli.vuejs.org/zh/guide/prototyping.html)

### Node and OS info
Node 8.11.4/npm 5.6.0/Windows 10

### Steps to reproduce
npm install -g @vue/cli-service-global

新建txt
<template>
  <h1>Hello!</h1>
</template>
改名为 app.vue

目录下执行vue serve

$ vue serve
 INFO  Starting development server...
 10% building modules 0/1 modules 1 active …vue\cli-service-global\template\main 10% building modules 1/2 modules 1 active …vue\cli-service-global\template\main 10% building modules 1/3 modules 2 active …\node_modules\webpack\hot\dev-server 10% building modules 1/4 modules 3 active …s?http://192.168.1.107:8080/sockjs-n 10% building modules 2/4 modules 2 active …s?http://192.168.1.107:8080/sockjs-n 10% building modules 3/4 modules 1 active …s?http://192.168.1.107:8080/sockjs-n 10% building modules 4/5 modules 1 active …-global\node_modules\webpack\hot\log 10% building modules 4/6 modules 2 active …modules\webpack\hot\log-apply-result 10% building modules 4/7 modules 3 active …bal\node_modules\webpack\hot\emitter 10% building modules 4/8 modules 4 active …les\webpack-dev-server\client\socket 10% building modules 4/9 modules 5 active …es\webpack-dev-server\client\overlay 10% building modules 5/9 modules 4 active …es\webpack-dev-server\client\overlay 10% building modules 6/9 modules 3 active …es\webpack-dev-server\client\overlay 10% building modules 7/9 modules 2 active …es\webpack-dev-server\client\overlay 10% building modules 7/10 modules 3 active …bpack\hot sync nonrecursive /^\.\/l 10% building modules 7/11 modules 4 active …ode_modules\vue\dist\vue.runtime.es 10% building modules 8/11 modules 3 active …ode_modules\vue\dist\vue.runtime.es 10% building modules 8/12 modules 4 active …-service-global\node_modules\url\ur 11% building modules 9/12 modules 3 active …-service-global\node_modules\url\ur 11% building modules 10/12 modules 2 active …-service-global\node_modules\url\u 11% building modules 11/12 modules 1 active …-service-global\node_modules\url\u 11% building modules 12/13 modules 1 active …ce-global\node_modules\events\even 11% building modules 12/14 modules 2 active …\node_modules\webpack\buildin\glob 11% building modules 12/15 modules 3 active …service-global\node_modules\url\ut 11% building modules 13/15 modules 2 active …service-global\node_modules\url\ut 11% building modules 13/16 modules 3 active …server\node_modules\strip-ansi\ind 11% building modules 14/16 modules 2 active …server\node_modules\strip-ansi\ind 11% building modules 14/17 modules 3 active …l\node_modules\loglevel\lib\loglev 11% building modules 15/17 modules 2 active …l\node_modules\loglevel\lib\loglev 11% building modules 15/18 modules 3 active …l\node_modules\querystring-es3\ind 11% building modules 15/19 modules 4 active …de_modules\sockjs-client\dist\sock 11% building modules 15/20 modules 5 active …-global\node_modules\ansi-html\ind 11% building modules 16/20 modules 4 active …-global\node_modules\ansi-html\ind 11% building modules 16/21 modules 5 active …owser\node_modules\punycode\punyco 12% building modules 17/21 modules 4 active …owser\node_modules\punycode\punyco 12% building modules 17/22 modules 5 active …bal\node_modules\html-entities\ind 12% building modules 18/22 modules 4 active …bal\node_modules\html-entities\ind 12% building modules 19/22 modules 3 active …bal\node_modules\html-entities\ind 12% building modules 20/22 modules 2 active …bal\node_modules\html-entities\ind 12% building modules 21/22 modules 1 active …bal\node_modules\html-entities\ind 12% building modules 21/23 modules 2 active …\node_modules\webpack\buildin\modu 12% building modules 22/23 modules 1 active …bal\node_modules\html-entities\ind 12% building modules 23/24 modules 1 active …\node_modules\querystring-es3\deco 12% building modules 23/25 modules 2 active …\node_modules\querystring-es3\enco 12% building modules 24/25 modules 1 active …\node_modules\querystring-es3\enco 13% building modules 25/26 modules 1 active …dules\html-entities\lib\xml-entiti 13% building modules 25/27 modules 2 active …les\html-entities\lib\html4-entiti 13% building modules 25/28 modules 3 active …les\html-entities\lib\html5-entiti 13% building modules 26/28 modules 2 active …les\html-entities\lib\html5-entiti 13% building modules 27/28 modules 1 active …les\html-entities\lib\html5-entiti 13% building modules 28/29 modules 1 active …server\node_modules\ansi-regex\ind 94% after seal ERROR  Failed to compile with 1 errors22:19:42

This dependency was not found:

* ~entry in C:/Users/qinkaiyuan/AppData/Roaming/npm/node_modules/@vue/cli-service-global/template/main.js

To install it, you can run: npm install --save ~entry

我执行npm install --save ~entry

依旧报这个错误

### What is expected?
项目正常启动

### What is actually happening?
项目无法启动

**Comment by qinkaiyuan** [comment]
我在这个地方找到了个答案
https://forum.vuejs.org/t/uninstalling-vue-js-and-starting-again/40786/2

执行vue serce app.vue 而不是  vue serve  

![image](https://user-images.githubusercontent.com/14007972/44409036-276d0880-a594-11e8-85db-6387c697723c.png)
但是文档中明明是写的vue serve

**Comment by huixisheng** [comment]
@qinkaiyuan   按照你的操作流程，可以正常运行。
![image](https://user-images.githubusercontent.com/1518967/44776164-0450e300-abaa-11e8-9969-e364c50a651a.png)

代码 https://github.com/huixisheng/lab/tree/master/issues/vue-cli-issues-2305

`vue-cli`源码 https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service-global/index.js#L14-L18 有实现 
>...它会在当前目录自动推导入口文件——入口可以是 main.js、index.js、App.vue 或 app.vue 中的一个。

根据`vue serve --help` 可以自定义`entry`，也可以快速原型开发直接用`vue serve`, 使用默认的`entry`。另外`vue serve app.vue`, 不是`vue serce app.vue`

以下是相关版本信息
```
➜  ~ node -v
v8.11.1
➜  ~ vue serve -V
3.0.1
➜  ~ vue -V
3.0.1
```
