### ISSUE TITLE
vue cil3 创建项目失败

### ISSUE THREAD

**Issue by zoesusu** [vuejs/vue-cli#2310]
### Version
3.0.1

### Node and OS info
node/8.11.4   npm/5.4.1

### Steps to reproduce
vue create test 

### What is expected?
希望能建立项目

### What is actually happening?
实际test文件夹内只有 node_modiles 文件夹和 package.json文件。
报错如下
Vue CLI v3.0.1
? Please pick a preset: default (babel, eslint)

Vue CLI v3.0.1
✨  Creating project in E:\front_work\zoe\test.
⚙  Installing CLI plugins. This might take a while...

> yorkie@2.0.0 install E:\front_work\zoe\test\node_modules\yorkie
> node bin/install.js

setting up Git hooks
can't find .git directory, skipping Git hooks installation
npm ERR! path E:\front_work\zoe\test\node_modules\fsevents\node_modules
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall scandir
npm ERR! Error: EPERM: operation not permitted, scandir 'E:\front_work\zoe\test\
node_modules\fsevents\node_modules'
npm ERR!  { Error: EPERM: operation not permitted, scandir 'E:\front_work\zoe\te
st\node_modules\fsevents\node_modules'
npm ERR!   stack: 'Error: EPERM: operation not permitted, scandir \'E:\\front_wo
rk\\zoe\\test\\node_modules\\fsevents\\node_modules\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'scandir',
npm ERR!   path: 'E:\\front_work\\zoe\\test\\node_modules\\fsevents\\node_module
s' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-08-22T0
1_39_50_529Z-debug.log
 ERROR  command failed: npm install --loglevel error

**Comment by troy351** [comment]
管理员身份打开cmd再执行

**Comment by zoesusu** [comment]
已经是管理员身份 
![image](https://user-images.githubusercontent.com/29087026/44438668-ba3c9000-a5f2-11e8-81f5-d5360ff9b7ee.png)

**Comment by troy351** [comment]
不是管理员账户，是右键“以管理员身份运行”，这俩不是一回事

**Comment by zoesusu** [comment]
仍报错

![image](https://user-images.githubusercontent.com/29087026/44438871-c117d280-a5f3-11e8-9557-1e050fbb7123.png)

**Comment by troy351** [comment]
你这不是cmd吧

**Comment by troy351** [comment]
查了下不是vue的问题，是npm的问题。
你可以尝试换个名称（换个目录），或者把node_modules删了重新install。
或者参考下这个 npm/npm#17671

**Comment by zoesusu** [comment]
感谢，解决了，更新了下npm版本
