### ISSUE TITLE
public目录不会打包名称为index.html文件

### ISSUE THREAD

**Issue by keerge** [vuejs/vue-cli#2312]
### Version
3.0.0

### Node and OS info
v8.10.0/npm 5.6.0/window 7

### Steps to reproduce
在public文件夹里在根目录或者二级目录创建index.html。 public/customDirectory/index.html , 运行 npm run build ，查看 dist 文件夹
找不到customDirectory/index.html文件，把index.html改成其他名字就可以打包

### What is expected?
名称为index.html的文件打包到 dist 目录

### What is actually happening?
没有被打包

**Comment by sodatea** [comment]
Duplicate of https://github.com/vuejs/vue-cli/issues/2144
