### ISSUE TITLE
typescript lint with eslint is no effect

### ISSUE THREAD

**Issue by yoyoys** [vuejs/vue-cli#2313]
### Version
3.0.1

### Reproduction link
[https://github.com/yoyoys/vue-eslint-ts-bug](https://github.com/yoyoys/vue-eslint-ts-bug)

### Node and OS info
node 8.11.3 / yarn 1.9.2 / macOS lastest / vscode 1.26.1

### Steps to reproduce
just run `yarn run lint`, and got nothing lint error.

### What is expected?
at least, eslint should find format errors, like `interface not startwith I`, and IDE will got warning or error.

### What is actually happening?
lint pass, and ide got nothing warning message.

---
other eslint rule and vue rule works fine.

**Comment by sodatea** [comment]
It's due to the incorrect rule format in `.eslintrc.js`.

It should be:
```
'typescript/interface-name-prefix': ['error', 'always'],
```

rather than
```
'typescript/interface-name-prefix': 'always',
```
