### ISSUE TITLE
Starter with Typescript Babel Plugins cannot be served

### ISSUE THREAD

**Issue by uzumakinaruto123** [vuejs/vue-cli#2314]
### Version
3.0.1

### Reproduction link
[https://github.com/uzumakinaruto123/vue-starter](https://github.com/uzumakinaruto123/vue-starter)

### Node and OS info
Node v8.9.0 / npm 5.2.0 / Windows 10

### Steps to reproduce
1. vue create test-vue
   - Manual Selection
   - Selection as below
      ![Config Selection](https://raw.githubusercontent.com/uzumakinaruto123/vue-starter/master/vue2.PNG)
   - Class Style Syntax - Yes
   - Use Babel alongside Typescript - Yes
   - History mode- Yes
   - SASS - Yes
   - Linter - Tslint
   - Lint on save
   - Config Preference - Dedicated Files

2. cd test-vue
3. npm run serve

<b>Result:</b>

<img src="https://raw.githubusercontent.com/uzumakinaruto123/vue-starter/master/vue1.PNG" width="600" />

### What is expected?
Project started with CLI to be served successfully.

### What is actually happening?
1. If Babel is not selected in the plugins along with Typescript, then the project is served successfully.

2. For Babel Typescript, CLI throws error as below:

```
PS D:\vue\test-vue> npm run serve

> test-vue@0.1.0 serve D:\vue\test-vue
> vue-cli-service serve

 INFO  Starting development server...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
 94% after seal

 ERROR  Failed to compile with 1 errors                                                                                                    10:51:20
Failed to resolve loader: babel-loader
You may need to install it.                                                                                                         Type checking and linting in progress...
No type errors found
No lint errors found
Version: typescript 3.0.1, tslint 5.11.0
Time: 7338ms

```

---
<b>PS:</b>  This is my first time with Vue, so trying to keep project structure similar to Angular as much as possible and trying to run CLI out of the box starter.

**Comment by sodatea** [comment]
For some unknown reason `babel-loader` is not hoisted to the root level `node_modules`.

Delete `package-lock.json` & `node_modules` and try again will fix this issue.

**Comment by uzumakinaruto123** [comment]
I already had tried that twice. I tried it again. Same issue. I deleted `package-lock.json and node_modules` completely then `npm install`. Same result.

**Comment by sodatea** [comment]
How about updating npm to 6? I believe it’s a package manager issue.
