### ISSUE TITLE
'webpackChunkName'  lazy loading routes not working

### ISSUE THREAD

**Issue by panjiang** [vuejs/vue-cli#2317]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vue-cli/releases/tag/v3.0.1](https://github.com/vuejs/vue-cli/releases/tag/v3.0.1)

### Node and OS info
npm

### Steps to reproduce
I have upgraded my project from cli2 to cli3, then I found the lazy loading routes not working any more. Every route loads all chunks now.

```
const Foo = () => import(/* webpackChunkName: "group-foo" */ './Foo.vue')
const Bar = () => import(/* webpackChunkName: "group-bar" */ './Bar.vue')
```

### What is expected?
lazy loading routes

### What is actually happening?
load all chunks at once

**Comment by LinusBorg** [comment]
You don't provide any information that would enable us to help you or inspect your problem.

**Comment by panjiang** [comment]
You are right, I have a misunderstanding about `prefetch`.
