### ISSUE TITLE
配置多页应用 pages，当入口多时无法编译

### ISSUE THREAD

**Issue by itxuye** [vuejs/vue-cli#2318]
### Version
3.0.1

### Reproduction link
[https://cli.vuejs.org/config/#pages](https://cli.vuejs.org/config/#pages)

### Node and OS info
Node  >=8.11.3

### Steps to reproduce
```javascript
const fs = require('fs');
const path = require('path');
const MOD_PATH = path.resolve(__dirname, './src/views');
const files = fs.readdirSync(MOD_PATH);

const pages = {};
files.forEach(file => {
  if (file.indexOf('.') !== 0) {
    pages[file] = {
      entry: `src/views/${file}/index.ts`,
      template: 'public/index.html',
      filename: `${file}/index.html`
    };
  }
});
```
设置入口如上，然后当views目录下入口超过5个时，无法编译，编译卡在开始进度

### What is expected?
正常编译

### What is actually happening?
无法编译

**Comment by zaxlct** [comment]
刚刚也遇到了这个问题，一旦超过 6 个，build  会一直卡着不动，改为 5 个后正常

**Comment by sodatea** [comment]
Duplicate of https://github.com/vuejs/vue-cli/issues/1996#issuecomment-415022624

------

暂时可以通过禁用 `named-chunks` plugin 解决
```js
module.exports = {
  // ...
  chainWebpack: config => config.plugins.delete('named-chunks')
}
```
