### ISSUE TITLE
Move to Eslint 5

### ISSUE THREAD

**Issue by pksunkara** [vuejs/vue-cli#2322]
### What problem does this feature solve?
We are currently using eslint 4 and lot of people have moved to eslint 5. So, we should do that too.

### What does the proposed API look like?
Update the cli-plugin-eslint package

**Comment by bviala** [comment]
Also _@vue/cli-plugin-eslint_ needs _eslint@^4.19.1_, and _@vue/eslint-config-standard_ needs _eslint@^5.0.0-alpha.2_ 

Which means you get a peer dependency incompatibility if you generate a project chosing standard config for eslint.

**Comment by pksunkara** [comment]
Well, this issue is about fixing that.

**Comment by silentHoo** [comment]
As this is related to my problem I'll append the log I get when I run `vue create example`:

This is my config I chose:

```
vue create example

Vue CLI v3.0.1
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, TS, Router, CSS Pre-processors, Linter, Unit, E2E
? Use class-style component syntax? Yes
? Use Babel alongside TypeScript for auto-detected polyfills? Yes
? Use history mode for router? (Requires proper server setup for index fallback in production) Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): SCSS/SASS
? Pick a linter / formatter config: Standard
? Pick additional lint features: Lint on save
? Pick a unit testing solution: Jest
? Pick a E2E testing solution: Nightwatch
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? Yes
```

The setup works surpesses all the peer dependency warnings, but when I remove all the modules (`rm -rf ./node_modules`) I get this issues:

```
yarn install
yarn install v1.5.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@vue/cli-plugin-babel > babel-loader@8.0.2" has incorrect peer dependency "@babel/core@^7.0.0".
warning "@vue/cli-plugin-babel > babel-loader@8.0.2" has unmet peer dependency "webpack@>=2".
warning "@vue/cli-plugin-eslint > eslint-loader@2.1.0" has unmet peer dependency "webpack@>=2.0.0 <5.0.0".
warning "@vue/cli-plugin-typescript > fork-ts-checker-webpack-plugin@0.4.9" has unmet peer dependency "webpack@^2.3.0 || ^3.0.0 || ^4.0.0".
warning "@vue/eslint-config-standard > eslint-config-standard@12.0.0" has unmet peer dependency "eslint@>=5.0.0".
warning "@vue/eslint-config-standard > eslint-config-standard@12.0.0" has incorrect peer dependency "eslint-plugin-node@>=7.0.0".
warning "@vue/eslint-config-standard > eslint-config-standard@12.0.0" has incorrect peer dependency "eslint-plugin-promise@>=4.0.0".
warning "@vue/eslint-config-standard > eslint-config-standard@12.0.0" has incorrect peer dependency "eslint-plugin-standard@>=4.0.0".
warning "@vue/eslint-config-standard > eslint-plugin-import@2.14.0" has unmet peer dependency "eslint@2.x - 5.x".
warning "@vue/eslint-config-standard > eslint-plugin-node@6.0.1" has unmet peer dependency "eslint@>=3.1.0".
warning "@vue/eslint-config-standard > eslint-plugin-standard@3.1.0" has unmet peer dependency "eslint@>=3.19.0".
warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > sass-loader@7.1.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > ts-jest@23.1.4" has unmet peer dependency "babel-jest@^23.0.0 || ^24.0.0".
warning " > ts-jest@23.1.4" has unmet peer dependency "jest@^23.0.0 || ^24.0.0".
[4/4] 📃  Building fresh packages...
✨  Done in 30.26s.
```

I can fix this by adding the missing devDeps, but that's not the proper way.

**Comment by reassured-jy** [comment]
Is there any news on this? I'm trying to have `vue-cli-service lint` run as a pre-commit hook, but it's failing on the following line in my .eslintrc:

```
'array-element-newline': ['warn', 'consistent'],
```

with the following error:

```
Configuration for rule "array-element-newline" is invalid:
Value "consistent" should be equal to one of the allowed values.
Value "consistent" should be object.
Value "consistent" should match exactly one schema in oneOf.
```

It's really frustrating to have stuff that's valid according to the eslint documentation be rejected because of a hard dependency on an old version of eslint…

**Comment by unikitty37** [comment]
Is there any news on this? I'm trying to have vue-cli-service lint run as a pre-commit hook, but it's failing on the following line in my `.eslintrc`:

```
'array-element-newline': ['warn', 'consistent'],
```

with the following error:

```
Configuration for rule "array-element-newline" is invalid:
Value "consistent" should be equal to one of the allowed values.
Value "consistent" should be object.
Value "consistent" should match exactly one schema in oneOf.
```

It's really frustrating to have stuff that's valid according to the eslint documentation be rejected because of a hard dependency on an old version of eslint…

**Comment by sodatea** [comment]
@unikitty37 See https://github.com/vuejs/vue-cli/pull/2560
We'd also like to bump ESLint version in the next minor release.

**Comment by gassius** [comment]
I am missing something regarding this issue?
Because in [these](https://github.com/vuejs/vue-cli/blob/99a06d1758183e671928af7dc6ae3eec47d58180/packages/%40vue/cli-service-global/package.json#L31) [lines](https://github.com/vuejs/vue-cli/blob/99a06d1758183e671928af7dc6ae3eec47d58180/packages/%40vue/cli-plugin-eslint/package.json#L33) from 3.6.0 still appears a dependency for eslint 4

This still causes a warning with yarn install
```
warning @vue/cli-plugin-eslint > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
```
eslint 5 resolves that bring from upstream a flat-cache package that does not require CircularJSON and use flatted.

Please advice

**Comment by sodatea** [comment]
@gassius In more recent scaffolded projects we've added eslint v5 to the projects' root `devDependencies` and use that by default. But we have to keep the v4 in the dependency chain as a fallback for compatibility reasons.

**Comment by gassius** [comment]
Thanks @sodatea 
In the package.json for my project, which was scaffolded before 3.6.0 release, I am explicitly defining `"eslint": "^5.16.0",` in devDependencies, but still got the aforementioned warning.

Any idea or workaround I could apply? tried with resolutions with no success

**Comment by sodatea** [comment]
Considering it's a warning rather than an error, I think you can safely ignore it.
