### ISSUE TITLE
Debugger statements quit working with unit tests when there is more than one unit test file

### ISSUE THREAD

**Issue by EricRohlfs** [vuejs/vue-cli#2325]
### Version
3.0.1

### Reproduction link
[https://github.com/EricRohlfs/vue-cli-unit-debug-issue/](https://github.com/EricRohlfs/vue-cli-unit-debug-issue/)

### Node and OS info
Node 8.11, NPM 5.6, Vue3.0.1, Windows 10, Jest

### Steps to reproduce
1. Create a new project or just clone this repo and skip to step 5

```
vue create hello1
```

2. Choose manual config and add unit tests and choose Jest as the runner.

3. add debugger statement in the HelloWorld.js test file.

3. Run the current test to see if it works - it should 

```
node --inspect-brk ./node_modules/@vue/cli-service/bin/vue-cli-service.js test:unit
```

4. Add a new unit test in the tests/unit folder. (I just copied the existing test and changed a few strings)

5. Run the tests again using

```
node --inspect-brk ./node_modules/@vue/cli-service/bin/vue-cli-service.js test:unit
```

Now the debugger does not stop on the debugger statements.

### What is expected?
Debugger statements work when debugging unit tests.

### What is actually happening?
Debugger statements are passed over in unit tests.

**Comment by LinusBorg** [comment]
Jeder runs tests in parallel in multiple child processes - if there sis more than or test to run. 

You will have to use the jest flag `--runInBand` to make them run synchronously in one process. 

Then debug statements should work again.

**Comment by EricRohlfs** [comment]
Command below is works. Thanks @LinusBorg 
```
node --inspect-brk ./node_modules/@vue/cli-service/bin/vue-cli-service.js test:unit --runInBand
```
