### ISSUE TITLE
Allow `vue-cli-service build` to specify a config file

### ISSUE THREAD

**Issue by octref** [vuejs/vue-cli#2328]
### What problem does this feature solve?
I want to build two targets with different `baseUrl`. This is currently impossible because `baseUrl` can only be specified in `vue.config.js`, not through CLI arguments.

### What does the proposed API look like?

One more option for `vue-cli-service build`:

-c | --config specify the config file (default: vue.config.js)

**Comment by Akryum** [comment]
You can use env vars.

**Comment by octref** [comment]
Thanks, that works. Although I would prefer to have `vue-lib.config.js` and `vue.config.js` etc, each for a different build target.

**Comment by darrenjennings** [comment]
This would be helpful in monorepos, for instance if you run `lerna exec` in all packages to build a component library, but only want to maintain a single vue.config.js.
