### ISSUE TITLE
打包后每个.vue文件都被单独打包成一个css文件，即使里面没有css也被打包成一个空的css

### ISSUE THREAD

**Issue by liuchihanxiang** [vuejs/vue-cli#2329]
### Version
3.0.1

### Reproduction link
[https://github.com/liuchihanxiang/test](https://github.com/liuchihanxiang/test)

### Node and OS info
Node.js 8.11.2 /npm 5.6.0 / Windows 7

### Steps to reproduce
直接运行npm run build 就行，我尝试用vue.config.js 中的css.extract 去解决  单是这个为false后 一个css都没了 我最开始新建项目打包好没有这个问题  但是写了一些代码之后  在打包就会出现

### What is expected?
不需要每个.vue 文件都单独打包为css文件

### What is actually happening?
css打包为一个css

**Comment by sodatea** [comment]
这是因为你用了 split chunks https://github.com/liuchihanxiang/test/blob/master/src/router/constant-route.js
每个异步加载的 js 都会有一个对应的 css
