### ISSUE TITLE
iview 按需引入 ie浏览器报语法错误；但是vue-cli2.0按同样规则没有问题

### ISSUE THREAD

**Issue by qq986063761** [vuejs/vue-cli#2330]
### Version
3.0.1

### Reproduction link
[https://github.com/qq986063761/iview-demand-bug/tree/master](https://github.com/qq986063761/iview-demand-bug/tree/master)

### Node and OS info
node版本8.9.1；npm版本6.2.0；windows 10；

### Steps to reproduce
1、下载重现链接中的仓库代码；
2、安装默认依赖后执行npm run dev；
3、使用谷歌浏览器和ie11浏览器分别访问本地链接；

### What is expected?
都能正常显示iview组件样式

### What is actually happening?
1、谷歌可以正常显示；
2、ie（非edge，edge正常显示）无法正常显示报错语法错误；但是尝试以2.x方式在3.x脚手架中通过include.add追加iview/src目录到js rule规则中，但是还是语法报错，原因应该是es6语法兼容问题导致；

---
无业务场景，全新@vue/cli demo项目尝试；

**Comment by Justineo** [comment]
这属于第三方库的使用问题，建议去 iView 项目下提问。

**Comment by sodatea** [comment]
这个问题出在 iView，请给他们提 bug。

------

改编译范围请用 `transpileDependencies: ['iview']`，不要用 `include.add`，因为默认配置里用了 `exclude`，在 webpack 中 `exclude` 的优先级高于 `include`。

但是加了这个选项后在所有浏览器里都会报错，因为 iView 里[这个文件](https://github.com/iview/iview/blob/341e73ce4363649ffa8544376f04a22ef15a7f0b/src/utils/date.js )不兼容 ES Module。该文件是用很旧版本的 UMD 格式打包的，新版本 UMD [修复了报错的问题](https://github.com/umdjs/umd/pull/125)，但没有解决和 ES Module 互操作的问题。在 Webpack 4 中，ES Module 不能和 CommonJS / UMD 混用。

所以这里本质上是 iView 对 Webpack 4 支持的问题，让他们把源码全部转成 ES Module 就好了。
