### ISSUE TITLE
"vue-cli-service build --mode staging" not minifying app.js

### ISSUE THREAD

**Issue by AmosXu** [vuejs/vue-cli#2333]
### Version
3.0.1

### Node and OS info
Node 10.6.0 / npm 6.4.0 / Windows 10

### Steps to reproduce
vue-cli-service build --mode staging

### What is expected?
Split CSS from JS, and minify everything.

### What is actually happening?
app.js to large

---
I use `vue-cli-service build` , CSS and JS are minify, I hope to use `vue-cli-service build --mode staging`, css and JS are also minify, what should I do?

**Comment by sodatea** [comment]
Have you included this line in `.env.staging`?:
```
NODE_ENV=production
```

**Comment by AmosXu** [comment]
@sodatea no

**Comment by sodatea** [comment]
Then add it.
`NODE_ENV=production` is required for packaging purpose.

**Comment by vagrantir** [comment]
Why staging must be a production?
If I need dev-tools on stage, it would be disabled with NODE_ENV=production

**Comment by sodatea** [comment]
@vagrantir If you need devtools, add `Vue.config.devtools = true` to `main.js`.
