### ISSUE TITLE
初始化时，eslint检查报错，导致中断

### ISSUE THREAD

**Issue by xxwade** [vuejs/vue-cli#2338]
### Version
3.0.1

### Node and OS info
node v9.2.1/npm v6.1.0/mac 0.13.6

### Steps to reproduce
1. vue create project
2. select demo
3. 5 errors,
Running completion hooks...error: Parsing error: The keyword 'import' is reserved at cli3-custom/src/main.js:1:1:
error: Parsing error: The keyword 'import' is reserved at cli3-custom/src/registerServiceWorker.js:3:1:
error: Parsing error: The keyword 'import' is reserved at cli3-custom/src/router.js:1:1:
error: Parsing error: The keyword 'import' is reserved at cli3-custom/src/store.js:1:1:
error: Parsing error: The keyword 'import' is reserved at cli3-custom/tests/unit/HelloWorld.spec.js:1:1:

but, the project can still run 
when I commit, eslint check is trigged again, and the errors occur again

### What is expected?
no eslint error

### What is actually happening?
can't commit normally

**Comment by cokeknight** [comment]
yew,just now, I Encounter this problem
![image](https://user-images.githubusercontent.com/3762423/44562079-68c70900-a78a-11e8-8aa3-8374b6da91a6.png)

**Comment by sodatea** [comment]
@cokeknight 请提供复现代码，仅一张报错截图并不能帮助排查问题。

**Comment by cokeknight** [comment]
@sodatea my vue version is 3.0.1
I just run command vue create hello-world
then 
![qq 20180824143422](https://user-images.githubusercontent.com/3762423/44568832-fdd9fa00-a7aa-11e8-8c1a-1531879e6149.png)

![qq 20180824143427](https://user-images.githubusercontent.com/3762423/44568838-00d4ea80-a7ab-11e8-99c0-31bc0d46b604.jpg)

**Comment by sodatea** [comment]
`eslint` is your custom preset which we don't know what the actual config is.
So please provide the content of `~/.vuerc`.

**Comment by xxwade** [comment]
just select demo presets
![image](https://user-images.githubusercontent.com/1948312/44627944-b9488d00-a969-11e8-9fe0-c7994e8823cd.png)

my  .vuerc content in home directory is:
```
{
  "packageManager": "npm",
  "useTaobaoRegistry": false,
  "presets": {
    "demo": {
      "useConfigFiles": false,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-pwa": {},
        "@vue/cli-plugin-eslint": {
          "config": "standard",
          "lintOn": [
            "save",
            "commit"
          ]
        }
      },
      "router": true
    },
    "standard-vue-template": {
      "useConfigFiles": false,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-pwa": {},
        "@vue/cli-plugin-eslint": {
          "config": "standard",
          "lintOn": [
            "save",
            "commit"
          ]
        },
        "@vue/cli-plugin-unit-jest": {}
      },
      "router": true,
      "routerHistoryMode": false,
      "vuex": true,
      "cssPreprocessor": "sass"
    }
  }
}
```

no other eslint config expect in package.json which is generated by default

```
"eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "@vue/standard"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
```

I don't have global eslint, and I think vue-cli should read the config in package.json
what's wrong with configuration?

**Comment by sodatea** [comment]
Now that we can't reproduce this problem and there's no report of similar issues in 5 months, I'll close issue for now. (BTW it's most likely related to your node / node version manager, rather than vue-cli)
Please open a new issue with a reference to this one if you can follow up with more information.
