### ISSUE TITLE
Show module name or line number when reporting relative module not found error

### ISSUE THREAD

**Issue by initialdmg** [vuejs/vue-cli#2344]
### What problem does this feature solve?
user cannot find out which module hasn't installed, or at which line the error occurred

like the error below 

```
 ERROR  Failed to compile with 1 errors

This relative module was not found:

* ./componets/editor/editor.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
```
The error information indicate that in the file` ./src/App.vue` cannot find module  `./componets/editor/editor.vue`, (just for example : ), correct path is `compone*n*ts`).
But it's still hard to read, especially when the information is more than 3 lines and errors stacks

### What does the proposed API look like?
source-file-name
Line: lineNumber

**Comment by LinusBorg** [comment]
Well, that's a webpack error, when a module was not found in a .vue file. If at all, we can only solve this in vue-loader. Please consider opening an issue there.

Thanks!
