### ISSUE TITLE
element-ui font-face were not found

### ISSUE THREAD

**Issue by souse** [vuejs/vue-cli#2349]
### Version
3.0.1

### Reproduction link
[https://github.com/souse/collage-app.git](https://github.com/souse/collage-app.git)

### Node and OS info
npm

### Steps to reproduce
npm install
npm run serve

### What is expected?
font-face can be use

### What is actually happening?
> code
```
import { Button } from 'element-ui'
Vue.use(Button)
```
```
"plugins": [
    [
      "component",
      {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-chalk"
      }
    ]
  ]
```
```
module.exports = {
  css: {
    modules: true,
    sourceMap: true
  },
......
```

> error message
```
These dependencies were not found:

* fonts/element-icons.ttf in ./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/lib??ref--6-oneOf-3-2!./node_modules/element-ui/lib/theme-chalk/base.css
* fonts/element-icons.woff in ./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/lib??ref--6-oneOf-3-2!./node_modules/element-ui/lib/theme-chalk/base.css

To install them, you can run: npm install --save fonts/element-icons.ttf fonts/element-icons.woff
```

**Comment by souse** [comment]
换组件库了， 后续等业务做完自己在看看这个问题。如果解决了会贴出处理方案

**Comment by jorgejesus** [comment]
In my case, the solution was not to use `npm` but simplely install everything with vue add:

```
vue add element-ui
```

**Comment by LazyCat1234** [comment]
module.exports = {
  css: {
    modules: false,
    sourceMap: true
  },
......
把modules改为false

**Comment by LazyCat1234** [comment]
出现错误的主要原因是在 vue.config.js 配置文件中设置了 css.modules = true，这个默认的值为 false ，只要把这个设置去掉问题即可得到解决
