### ISSUE TITLE
Console window closes after any command starting with Vue

### ISSUE THREAD

**Issue by nkostadinov** [vuejs/vue-cli#235]
I'm using windows 10 and installed vue-cli with yarn (tried with npm also). Whenever I type a command starting with vue e.g. vue init, vue ... the console window closes without any error. Any idea why this is happending ? I have a laptop with the same windows and there I have the same issue.

**Comment by Promixius** [comment]
Using normal cmd or gut bash or cmder or power shell ? 
Your not leaving much information or logs of any kind.

**Comment by nkostadinov** [comment]
It was a problem with NPM/nodejs. After I reinstalled both of them and deleted all their folders and caches I fixed the issue.
