### ISSUE TITLE
在自定义mode情况下如何打production环境下的包

### ISSUE THREAD

**Issue by snake-developers** [vuejs/vue-cli#2351]
### Version
3.0.1

### Node and OS info
npm

### Steps to reproduce
  因为公司测试环境需要自动化打包，固用 vue-cli-service build --mode testing   来区分测试环境，虽然环境变量变成了test环境下的，但是这样打包的话，包体积会过大，应该是development环境的包体积，请问有没有解决办法

### What is expected?
自定义 mode  场景下，可以打出与production模式大小相同的包

### What is actually happening?
自定义 mode  场景下，打出的是development模式大小相同的包

**Comment by sodatea** [comment]
在自定义 mode 里配置 NODE_ENV=production 即可
