### ISSUE TITLE
Inline preset is not working properly

### ISSUE THREAD

**Issue by alexbruno** [vuejs/vue-cli#2354]
### Version
3.0.1

### Node and OS info
Node.js v10.9.0 / NPM v6.4.0 / Manjaro Linux.

### Steps to reproduce
npx @vue/cli create project -i {"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-pwa":{},"@vue/cli-plugin-eslint":{"config":"standard","lintOn":["save","commit"]},"@vue/cli-plugin-unit-jest":{}},"router":true,"routerHistoryMode":true,"vuex":true,"cssPreprocessor":"stylus"}

### What is expected?
Command works properly like documentation suggest.

### What is actually happening?
ERROR  CLI inline preset is not valid JSON: useConfigFiles:false

Exit with code: 1

But the JSON is valid and was copied from `.vuerc`
---
I'm developing a customized CLI at my job to bootstrap Vue and React projects with standardized presets choosed in menu. I need a way to give a preset to @vue/cli and bootstrap a project with its configs.

**Comment by sodatea** [comment]
The JSON config needs to be quotes:

```
npx @vue/cli create project -i {"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-pwa":{},"@vue/cli-plugin-eslint":{"config":"standard","lintOn":["save","commit"]},"@vue/cli-plugin-unit-jest":{}},"router":true,"routerHistoryMode":true,"vuex":true,"cssPreprocessor":"stylus"}
```

**Comment by sodatea** [comment]
The JSON config needs to be quoted:

```
npx @vue/cli create project -i '{"useConfigFiles":false,"plugins":{"@vue/cli-plugin-babel":{},"@vue/cli-plugin-pwa":{},"@vue/cli-plugin-eslint":{"config":"standard","lintOn":["save","commit"]},"@vue/cli-plugin-unit-jest":{}},"router":true,"routerHistoryMode":true,"vuex":true,"cssPreprocessor":"stylus"}'
```

**Comment by alexbruno** [comment]
Ok, thanks! It worked here.
