### ISSUE TITLE
npm run serve -s dist fails: dependency was not found: sockjs-node

### ISSUE THREAD

**Issue by DrGo** [vuejs/vue-cli#2362]
### Version
3.0.1

### Node and OS info
node v10.9.0; npm@6.4.0; ProductName:	Mac OS X ProductVersion:	10.13.6 BuildVersion:	17G65

### Steps to reproduce
vue create vrm --> preset (pwa; vuex, vue router; unit and integrated testing)

cd vrm

npm install 

npm run build 

npm run serve -s dist

### What is expected?
newly created website open in browser

### What is actually happening?
 ERROR  Failed to compile with 1 errors                                                                               11:41:07 PM

This dependency was not found:

*/prj/vrm/dist in multi (webpack)-dev-server/client?http://192.168.1.48:8080/sockjs-node (webpack)/hot/
dev-server.js ./dist

To install it, you can run: npm install --save /prj/vrm/dist

---
website works if -S is omitted
npm run serve

> vrm@0.1.0 serve /prj/vrm
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin

 DONE  Compiled successfully in 2073ms                                                                                11:42:17 PM

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.1.48:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

**Comment by sodatea** [comment]
But what do you want to achieve by adding the `-s dist` argument?

In your case, `npm run serve -s dist` runs `vue-cli-service serve "dist"` under the hood.
`-s` is interpreted as a flag for `npm run-script`, as a shorthand of `--silent`.
`dist`, which certainly does not exist at the moment, is specified as the entry point for `vue-cli-service` to serve, therefore the error is shown.

**Comment by DrGo** [comment]
Thanks but even without the -s,  `npm run serve dist `still fails with the same error. My purpose is to serve the built site from localhost. Is there another way of doing that?
