### ISSUE TITLE
The style scoped can not work when I import css file and run serve.

### ISSUE THREAD

**Issue by GuangTianLi** [vuejs/vue-cli#2363]
### Version
3.0.1

### Node and OS info
Node v8.11.3/ npm 6.4.0/MacOS 10.13

### Steps to reproduce
<style scoped>
@import '../../css/creative.css';
</style>

### What is expected?
section[data-v-1eed3935] {
    padding: 8rem 0;
}

### What is actually happening?
section {
    padding: 8rem 0;
}

**Comment by sodatea** [comment]
Try `<style scoped src="../../css/creative.css"></style>`
