### ISSUE TITLE
css中background-image中url引用的是public文件夹里面的图片，打包之后baseUrl丢失

### ISSUE THREAD

**Issue by snake-developers** [vuejs/vue-cli#2364]
### What problem does this feature solve?
css中 background-image url("/images/test.png")  ，vue.config.js中 baseUrl设置为 '/aaa/'  ，打包之后 baseUrl设置无效

### What does the proposed API look like?
css中 background-image url("/images/test.png")  ，vue.config.js中 baseUrl设置为 '/aaa/'  ，打包之后 baseUrl设置无效，期望baseUrl设置在打包之后可以对生效public文件夹生效

**Comment by yyx990803** [comment]
绝对路径是不会被转换的。

https://cli.vuejs.org/zh/guide/html-and-static-assets.html#url-%E8%BD%AC%E6%8D%A2%E8%A7%84%E5%88%99
