### ISSUE TITLE
Vue project is not deployed correctly

### ISSUE THREAD

**Issue by boussadjra** [vuejs/vue-cli#2365]
### Version
3.0.1

### Node and OS info
Node 10.8.0 /npm 6.1.0 / Windows 10

### Steps to reproduce
i had created my project using vue cli 3, it works fine when i run the `npm run serve`, but when i run the other command to build my project and to deploy it `npm run build` it generates a blank page when i serve my built project using 'serve -s dist'.

### What is expected?
my project would  work in deployment  by running `serve -s 
 dist` like in the development phase  

### What is actually happening?
i'm getting a blank page when i serve my built project using `serve -s dist` and when i check the console i find these errors:

*Uncaught SyntaxError: Unexpected token <        chunk-vendors.490af48e.js:1* 

*Uncaught SyntaxError: Unexpected token < pp.205842cb.js:1*

**Comment by sodatea** [comment]
Please make sure you have not modified `baseUrl`.

**Comment by boussadjra** [comment]
@sodatea, yes it a problem of the `baseUrl` i had changed it and it now works fine
