### ISSUE TITLE
Git hooks not installed when git repo initiazlized in parent folder of package.json

### ISSUE THREAD

**Issue by pavelda2** [vuejs/vue-cli#2366]
### Version
3.0.1

### Reproduction link
[https://github.com/pavelda2/yorkie-git-recognition-bug](https://github.com/pavelda2/yorkie-git-recognition-bug)

### Node and OS info
Node v8.11.1 / Windows 10

### Steps to reproduce
1. Initialize git repository
2. Create subfolders "client" and "server"
3. Create Vue.js app in "client" folder using Vue CLI with "Lint and fix on commit" feature enabled

### What is expected?
Git hooks installed by [yorkie](https://github.com/yyx990803/yorkie) library in root folder with git repository

### What is actually happening?
Error "setting up Git hooks", "can't find .git directory ..."
![image](https://user-images.githubusercontent.com/32357716/44672217-173baa00-aa28-11e8-8d72-6e4e96d3f446.png)

---
Library [yorkie](https://github.com/yyx990803/yorkie) search for '.git' folder only in the folder where 'package.json' is located. But my project has git repository initialized somewhere in parent folders.

**Comment by sodatea** [comment]
It is intended: https://github.com/vuejs/vue-cli/issues/2131
