### ISSUE TITLE
Separate max-len eslint rule for Vue template tag

### ISSUE THREAD

**Issue by guirreri** [vuejs/vue-cli#2367]
### What problem does this feature solve?
When using ESLint's max-len rule, it is applied to all of a vue single-file component. It would be better to provide separate max-len for an SFCs template tag vs the script.

It is very common to use the default max-len of 80 characters in a javascript file, but markup typically will have much longer lines.

At the moment, the default Vue CLI template fails max-len on HelloWorld.vue. This would fix that if the default for the vue rule was set to something higher.

### What does the proposed API look like?
Add a rule called vue/max-len-template reusing the same settings for ESLint's normal max-len:
https://eslint.org/docs/rules/max-len

In .eslintrc.config:
```
module.exports = {
  'rules': {
    '@vue/max-len-template': ["error", { "code": 200 }],
    'max-len': 80
  }
}
```

**Comment by sodatea** [comment]
See:
https://github.com/mysticatea/vue-eslint-parser#%EF%B8%8F-known-limitations
https://github.com/mysticatea/vue-eslint-parser/issues/15#issuecomment-322093990

🙁

**Comment by nino-vrijman** [comment]
A proposal for a '@vue/max-len' rule has been accepted in [eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue/issues/731)

**Comment by SYNTAG** [comment]
@nino-vrijman That's great news! Any estimate on how long the process might take to fully integrate the new rule? Thanks!

**Comment by nino-vrijman** [comment]
> @nino-vrijman That's great news! Any estimate on how long the process might take to fully integrate the new rule? Thanks!

I'm not sure since I don't contribute to `eslint-plugin-vue`, I would subscribe to the issue I linked to in my previous message so you will be notified as soon as more is known.
