### ISSUE TITLE
vue-cli-service build: entry pattern "'src/components/*.vue'" did not match any files.

### ISSUE THREAD

**Issue by julian-ayu** [vuejs/vue-cli#2369]
### Version
3.0.1

### Node and OS info
Node 10.9.0 / npm 6.2.0 / Windows 10

### Steps to reproduce
Using Cmder, create a new app with TypeScript and Jest testing and try to build it with web components.

```sh
λ vue create my-app
λ cd my-app
λ npx vue-cli-service build --target wc --name myapp 'src/components/*.vue'
λ ls src\components\
```

* ls displays `HelloWorld.vue`

### What is expected?
The web components to be built.

### What is actually happening?
Output:
```
-  Building for production as web component...
 ERROR  entry pattern "'src/components/*.vue'" did not match any files.
```

**Comment by LinusBorg** [comment]
why did you wrap the glob in single quotes? I don'T think that's valid

**Comment by julian-ayu** [comment]
@LinusBorg I wrapped the glob in double quotes and it now works. Thanks!

I had wrapped it in single quotes because I copied the line from here https://cli.vuejs.org/guide/build-targets.html#bundle-that-registers-multiple-web-components
