### ISSUE TITLE
Tree shaking not working with external dependencies

### ISSUE THREAD

**Issue by clemgrim** [vuejs/vue-cli#2370]
### Version
3.0.0

### Reproduction link
[https://github.com/clemgrim/tree-shaking-vue](https://github.com/clemgrim/tree-shaking-vue)

### Node and OS info
Node 8.11.3 / Yarn 1.7.0 / Windows 10

### Steps to reproduce
1. Create a new basic CLI project (Vue CLI 3.0.0, default configuration)
2. Add `boostrap-vue` to the project dependencies
3. Import one component from this module in your app and register it globally (https://github.com/clemgrim/tree-shaking-vue/blob/master/src/App.vue#L10)
4. Run `yarn build` (production mode)

### What is expected?
 The generated build should contain only the `Button` component

### What is actually happening?
The vendor bundle is huge. If we inspect the file, we can see that all bootstrap components are there (we should have only the `Button` one)

I tested with local files, with almost the same structure boostrap vue uses, and it looks ok.. Tree shaking works fine with my own files, but not with my dependencies (https://github.com/clemgrim/tree-shaking-vue/tree/master/src/utils)

---
I tried to use the sideEffect option in vue.config.js, but I have the same result (https://github.com/clemgrim/tree-shaking-vue/blob/master/vue.config.js#L6)

In my opinion, tree shaking should work with this scenario, here is what `bootstrap-vue/es/components/index.js` looks like:

```js
import Alert from './alert';
import Badge from './badge';
import Button from './button';
// etc...

export { Alert, Badge, Button, /* ... */};
```

**Comment by ematipico** [comment]
The `sideEffect` option must be implemented by the library, not by you. This means that `bootstrap-vue` library should have it inside their `package.json`

**Comment by clemgrim** [comment]
No, this is possible since https://github.com/webpack/webpack/pull/6129, inside the `module.rules` configuration

I changed my vue config to 

```js
const path = require('path');

module.exports = {
  configureWebpack: {
    module: {
      rules: [
        {
          include: path.resolve('node_modules', 'bootstrap-vue'),
          sideEffects: false,
        }
      ]
    }
  }
};
```

and it works now 👍

Anyway, thank you for your time, it was not related to vue cli

**Comment by TitanFighter** [comment]
Hi @clemgrim . Thanks for the code.
Just want to mention, that according to [StackOverflow answer](https://stackoverflow.com/a/49776306/4992248) it would be better to set `sideEffects` as `sideEffects: ["*.css"]`, because we need to `import 'bootstrap-vue/dist/bootstrap-vue.css'`
