### ISSUE TITLE
[@vue/cli-plugin-typescript] Offer @babel/typescript as an alternative option to ts-loader

### ISSUE THREAD

**Issue by nklayman** [vuejs/vue-cli#2371]
### What problem does this feature solve?
With the release of [babel 7](https://babeljs.io/blog/2018/08/27/7.0.0), there is a [typescript preset](https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/). Would this be a better option over ts-loader?

### What does the proposed API look like?
In the @vue/typescript plugin, replace ts-loader with [@babel/preset-typescript](https://babeljs.io/docs/en/next/babel-preset-typescript.html).

**Comment by ktsn** [comment]
I remember babel's parser does not support all of typescript syntax such as namespace. But I guess it may be fine having an option using babel for transform typescript.

**Comment by LinusBorg** [comment]
Agree with @ktsn, changed issue title accordingly.

**Comment by yyx990803** [comment]
We have tried this before but it's still unstable.

**Comment by msdlisper** [comment]
Now, `preset-typescript` is stable... any idea? @yyx990803

**Comment by LinusBorg** [comment]
Please open a new feature request.
