### ISSUE TITLE
serve with message'spawn vue-cli-service ENOENT'

### ISSUE THREAD

**Issue by DaoCaGit** [vuejs/vue-cli#2374]
### Version
3.0.1

### Node and OS info
Node 8.11.2 / Windows 10

### 运行的时候不会报错，点击停止之后出现以下错误

```
Error while running task D:\web\YgShop:serve with message'spawn vue-cli-service ENOENT'
```

### What is expected?
能正常停止运行项目，不报错

### What is actually happening?
能正常停止运行项目，报错

**Comment by sodatea** [comment]
Duplicate of https://github.com/vuejs/vue-cli/issues/2096#issuecomment-414127488

这个错误应该不影响使用

**Comment by SteenGuo** [comment]
我也遇到了相同的问题，求真相

**Comment by DoubleRayWang** [comment]
亲测：node_modules删了重新 install 即可解决问题
