### ISSUE TITLE
But I just do not want to use webpack, because I used to write a service node, only need to integrate vue only

### ISSUE THREAD

**Issue by yuchonghua** [vuejs/vue-cli#238]
如果我只是想编译.vue，并不需要打包，我改怎么做呢

**Comment by Yakima-Teng** [comment]
那你不应该用vue-cli，自己用webpack+vue-loader写起来会比较方便。

**Comment by yuchonghua** [comment]
可是我就是不想用webpack，因为我自己用node写了一套服务，仅仅需要集成vue而已

**Comment by yuchonghua** [comment]
But I just do not want to use webpack, because I used to write a service node, only need to integrate vue only

**Comment by LinusBorg** [comment]
If you don'T want to use webpack, don't use the webpack template.
