### ISSUE TITLE
vagrant box: No command 'vue' found

### ISSUE THREAD

**Issue by TheSycamore** [vuejs/vue-cli#2382]
### Version
3.0.1

### Reproduction link
[https://github.com/TheSycamore/vue-issue](https://github.com/TheSycamore/vue-issue)

### Node and OS info
Node 10.9.0 / yarn 1.9.4 / Ubuntu 16.04

### Steps to reproduce
```
    vagrant up
    vagrant ssh

```
Then install vue CLI 3 dependencies:  
Found inside "provisioning-commands.txt"

```
yarn global add @vue/cli

vue --version

```

### What is expected?
vue --version should show me which version is installed

### What is actually happening?
```
vagrant@cc:~$ vue --version
No command 'vue' found, did you mean:
 Command 'vpe' from package 'texlive-latex-extra' (universe)
vue: command not found

```

---
I have posted this on StackOverflow which may be helpful to see an overview of this issue:
https://stackoverflow.com/questions/52060070/vagrant-local-development-environment-ubuntu-yarn-vue-cli-3-issues

**Comment by hohotyn01** [comment]
Men. Install vue-cli on windows
