### ISSUE TITLE
vagrant box: "/bin/sh: 1: vue-cli-service: Permission denied"

### ISSUE THREAD

**Issue by TheSycamore** [vuejs/vue-cli#2383]
### Version
3.0.1

### Reproduction link
[https://github.com/TheSycamore/vue-issue](https://github.com/TheSycamore/vue-issue)

### Node and OS info
Node 10.9.0 / yarn 1.9.4 / Ubuntu 16.04

### Steps to reproduce
```
    vagrant up
    vagrant ssh

```
Then install vue CLI 3 dependencies:  
Found inside "provisioning-commands.txt"

```
yarn global add @vue/cli

vue --version

```

### What is expected?
vue --version should show me which version is installed

### What is actually happening?
```
vagrant@cc:~$ vue --version
No command 'vue' found, did you mean:
 Command 'vpe' from package 'texlive-latex-extra' (universe)
vue: command not found

```

---
I have posted this on StackOverflow which will be helpful to see an overview of this issue and what I am trying to achieve:
https://stackoverflow.com/questions/52060070/vagrant-local-development-environment-ubuntu-yarn-vue-cli-3-issues

**Comment by TheSycamore** [comment]
I have found that yarn wasn't added to the vagrant users $PATH by default. So I have added the following to `/home/vagrant/.bashrc`

```
export PATH=$PATH:/home/vagrant/.config/yarn/global/node_modules/.bin
```
Now the problem is when running `yarn run serve` I get the same permissions error as described in: https://stackoverflow.com/questions/52060070/vagrant-local-development-environment-ubuntu-yarn-vue-cli-3-issues

```
yarn run v1.9.4
$ vue-cli-service serve
/bin/sh: 1: vue-cli-service: Permission denied
error Command failed with exit code 126.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by LinusBorg** [comment]
Well, according to that SO topic, the reason is that yarn was installed with sudo, so execuables installed by yarn (like vue-cli-service) require sudo as well.

You will probably have to adjust permissions to allow the current user to run this execuable `node_modules/.bin/vue-cli-service`

This can't be solved in this repository, so I will close the issue.

**Comment by TheSycamore** [comment]
Yes after doing further troubleshooting I have found the problem is certainly a permissions related issue.
I think that as my vagrant is using virtualbox, there is a virtualbox issue with symbolic links from my synced folder from my host, which changes the permissions (I am not 100% that this **is** whats causing the issue).

For anyone with similar issues here is my current workaround to this issue:
1) copy the projects `package.json` to: the yarn global directory: `/home/vagrant/.config/yarn/global/`

    cp /var/www/project/package.json /home/vagrant/.config/yarn/global

2) Install the projects dependencies globally in the yarn users directory:

    cd /home/vagrant/.config/yarn/global
    yarn install

3) Now returning to the project and running `yarn run serve` works by using the node_modules from `/home/vagrant/.config/yarn/global/node_modules/.bin/`

    cd /var/www/project/package.json
    yarn run serve

**Comment by TheSycamore** [comment]
I found a much better fix to this issue by following the instructions here: https://github.com/hashicorp/vagrant/issues/713#issuecomment-17296765

Adding to the Vagrantfile:

    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant", "1"]

**Comment by smilevietnam** [comment]
npm i  @vue/cli -g
easy
