### ISSUE TITLE
ios手机端 经常要关闭页面重开才能刷新到最新，点击刷新按钮还是旧版

### ISSUE THREAD

**Issue by dficonfont** [vuejs/vue-cli#2391]
### Version
3.0.1

### Node and OS info
v8.11.2/npm 6.1.0

### Steps to reproduce
在手机上（ios11/ios12）测试的时候，如果点击刷新按钮，会恢复到之前修改的版本，要关闭网页重新打开才是最新版。这在测试的时候就有点不方便了，怎么解决，或者你们有没有遇到过这种情况？

### What is expected?
得到正确的更新

### What is actually happening?
得到的不是最新版

**Comment by sodatea** [comment]
可能是 Safari 的 bug。
可以参考这个回复试试：https://github.com/vuejs/vue-cli/issues/1132#issuecomment-409916879

**Comment by dficonfont** [comment]
用了楼上的方法解决了，看样子是app.js被缓存了
