### ISSUE TITLE
webpack-chain在vue.config.js中链式配置的时候如何增加query的配置呢？

### ISSUE THREAD

**Issue by innocces** [vuejs/vue-cli#2392]
### Version
3.0.0

### Node and OS info
node 8.11.3  npm 5.6.0

### Steps to reproduce
module.exports = {
  chainWebpack: config => {
    config.module
      .rule('scss')
      .test(/\.scss$/)
      .use('webpack-px-to-rem')
        .loader('webpack-px-to-rem')
        // .query({
        //     // 1rem=npx 默认为 10
        //     basePx:10,
        //     // 只会转换大于min的px 默认为0
        //     // 因为很小的px（比如border的1px）转换为rem后在很小的设备上结果会小于1px，有的设备就会不显示
        //     min:1,
        //     // 转换后的rem值保留的小数点后位数 默认为3
        //     floatWidth:3
        //   })
        .end()
  }
}

这里注释的query的选项不知道该怎么加，直接.query()会报错query is not a function

### What is expected?
希望可以配置上query

### What is actually happening?
直接.query()会报错query is not a function

**Comment by travelk** [comment]
感觉vue-cli 3使用vue.config还不如直接修改webpack.config来的方便。

**Comment by LinusBorg** [comment]
请使用论坛提问

https://forum.vuejs.org/c/chinese

**Comment by yyx990803** [comment]
webpack 4 只有 option 没有 query。
