### ISSUE TITLE
something about  Build Targets

### ISSUE THREAD

**Issue by huixisheng** [vuejs/vue-cli#2396]
### Version
3.0.1

### Reproduction link
[https://github.com/huixisheng/lab/tree/master/vue/vue-cli-build-target](https://github.com/huixisheng/lab/tree/master/vue/vue-cli-build-target)

### Node and OS info
Node 8.11.1 macOS10.13.6

### Steps to reproduce
1. set `vue.config.js css.extract = false`
2. npm run build:nocss

### What is expected?
1. `dist/nocss-build-vue/demo.html`  has no `<link rel="stylesheet" href="./vueCliBuildTarget.css">`
2. inline css with  prefix flex
```
// module
exports.push([module.i, "\n.flex[data-v-2e244fda] { display: -webkit-box; display: -webkit-flex; display: -moz-box; display: flex; -webkit-box-pack: center; -webkit-justify-content: center; -moz-box-pack: center; justify-content: center; -webkit-box-align: center; -webkit-align-items: center; -moz-box-align: center; align-items: center;\n}\n", ""]);
```

### What is actually happening?
vueCliBuildTarget.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND

```
// module
exports.push([module.i, "\n.flex[data-v-565f34ea]{align-items:center;display:flex;justify-content:center\n}", ""]);
```
---
there are errors when I set  `build --name=vue-cli-build-target` or `package.json`  `name=vue-cli-build-target`

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/issues/2451#issuecomment-420290641
Fixed in 3.0.2
