### ISSUE TITLE
vue-router hooks will not automatic register  when use vue-property-decorator module

### ISSUE THREAD

**Issue by rover5056** [vuejs/vue-cli#2399]
### What problem does this feature solve?
If use vue-cli 3 create a new project with TS option, it will use vue-property-decorator module in project. But developer will find that they can not use beforeRouteEnter or beforeRouteUpdate functions because these do not register in this default structure.
It puzzled me  at long time,I use vue at first and I found up lots of router and vues' official documents and guides, but still have no idea about why  these functions do not fired when I come into any component. I was trying to  ask at stackoverflow and other forums  but no result.
Until I read the code ...I found that I must register hook by my self...
It is a really bad experience for new Vue developer who use cli...

### What does the proposed API look like?
Just add some tips or example code in default project created by cli

···
import { Component, Vue } from 'vue-property-decorator';
// just add this functions to hint new developers that they should do it by themselves...
Component.registerHooks([
  'beforeRouteEnter',
  'beforeRouteUpdate',
  'beforeRouteLeave'
])
···

**Comment by LinusBorg** [comment]
Please open an issue in the property decorator repository, *with* a link to a repo that reproduces the issue you are seeing.
