### ISSUE TITLE
How to init in current folder?

### ISSUE THREAD

**Issue by djyde** [vuejs/vue-cli#24]
I want to init a webpack template in my current project `my/project` folder by running

```bash
➜  my/project vue init webpack
```

instead of jumping out and run `$ vue init webpack my/project`.

How to do it?

**Comment by yyx990803** [comment]
It's currently not supported. You can make a pull request for it though!

**Comment by nblackburn** [comment]
You could do this to initialize a project in the current folder.

```
vue init webpack .
```

**Comment by djyde** [comment]
@nblackburn I'd tried before opening this issue. It got `vue-cli · "." already exists.`

**Comment by nblackburn** [comment]
Hmm, works for me, try going up one in the directories and doing this...

```bash
vue init webpack test
```

**Comment by djyde** [comment]
@nblackburn Of course it should work in that way.

**Comment by yyx990803** [comment]
Now supported in 1.4.0.
