### ISSUE TITLE
Here is a problem with remote preset

### ISSUE THREAD

**Issue by huxianghe** [vuejs/vue-cli#2402]
### What problem does this feature solve?
when I tried to load remote preset from my own repo which only includes preset.json file，the command is ‘’vue create -p https://github.com:huxianghe/preset vue-cli3‘’，but  a TypeError is throwed by Creator.js：‘’Cannot set property '@vue/cli-service' of undefined‘’ ，so，i  doubt that the preset don`t be loaded correctly? Here is my remote preset：
```json
{
  "packageManager": "yarn",
  "presets": {
    "VuePreset": {
      "useConfigFiles": true,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-pwa": {},
        "@vue/cli-plugin-eslint": {
          "config": "standard",
          "lintOn": ["save"]
        }
      },
      "configs": {
        "vue": {
          "css": {
            "modules": false,
            "sourceMap": false,
            "loaderOptions": {}
          },
          "productionSourceMap": false,
          "transpileDependencies": [],
          "configureWebpack": {},
          "devServer": {
            "host": "localhost",
            "port": 2019,
            "hot": true,
            "hotOnly": false,
            "open": true,
            "https": false,
            "overlay": {
              "warnings": false,
              "errors": true
            }
          }
        }
      },
      "router": true,
      "routerHistoryMode": true,
      "vuex": true,
      "cssPreprocessor": "stylus"
    }
  }
}
```

**Comment by sodatea** [comment]
Github issues are for bug reports and feature requests only. Next time please consider asking questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) first.

------

The preset format is incorrect.
See https://cli.vuejs.org/guide/plugins-and-presets.html#presets

A proper preset should only include the content of `VuePreset`, like:
```
{
  "useConfigFiles": true,
  "plugins": {
  ...
```

**Comment by ranwawa** [comment]
赞
