### ISSUE TITLE
cli-plugin-e2e-nightwatch -> dependency versions

### ISSUE THREAD

**Issue by MartinX3** [vuejs/vue-cli#2407]
### Version
3.0.1

### Reproduction link
[https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-e2e-nightwatch/package.json](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-e2e-nightwatch/package.json)

### Node and OS info
10.9.0

### Steps to reproduce
Install the plugin.

Look into the package-lock.json

### What is expected?
Not so old dependencies.

### What is actually happening?
It includes old dependencies.

**Comment by sodatea** [comment]
Nightwatch 1.x is currently in beta.  So v0.9.21 is the latest stable version.

```
> npm view nightwatch dist-tags
{ beta: '1.0.10',
  dev: '0.5.7',
  latest: '0.9.21',
  'v0.5.0': '0.5.16' }
```

Also, `"chromedriver": "^2.40.0"` will resolve to `2.41.0` when you actually runs `npm install` or `npm update`, as it is a [caret dependency](https://docs.npmjs.com/cli/update#caret-dependencies).

And we do sync dependency versions before releasing a new version: https://github.com/vuejs/vue-cli/blob/dev/scripts/syncDeps.js

**Comment by MartinX3** [comment]
Thank you!

**Comment by toddgallimore** [comment]
Is there any update on this?

Nightwatch GitHub repo website states

> We're delighted to announce the release of Nightwatch v1.0. Please see the upgrade guide if you are upgrading from an earlier version.

This is the first time I'm setting up our e2e tests. I was getting a console error saying `client.page.navigate()` is not a function. Manually changing the Nightwatch package in `@vue/cli-plugin-e2e-nightwatch` to version `1.0.18` fixes the issue.
