### ISSUE TITLE
增加生成资源hash配置，hash允许配置在url参数上面，而不是文件hash,减少冗余文件

### ISSUE THREAD

**Issue by agileago** [vuejs/vue-cli#2413]
### What problem does this feature solve?
允许 hash配置在 文件的url参数上来进行破除缓存，类似  [name].js?[hash:8] ,然后打包后生成的文件都是一样的，然后上传到服务器不会造成大量的冗余文件，也解决了缓存问题。

现在打包后：
&lt;script src="app.[hash].js"&gt;&lt;/script&gt;  <br>
期望的结果：
&lt;script src="app.js?[hash]"&gt;&lt;/script&gt;  <br>

### What does the proposed API look like?
urlHash: true

**Comment by sodatea** [comment]
一般认为在文件名中加 hash 比在 query parameter 中加 hash 更合理。
如果真的有需要，请自行修改 webpack 的 `filename` 和 `chunkFilename` 配置。

**Comment by agileago** [comment]
怎么合理了？这就关了？

**Comment by sodatea** [comment]
1. 这个功能现在自己写配置就能做到；

**Comment by sodatea** [comment]
2. 为什么合理在网上能搜到很多文章，这里给一个 webpack 官方的说法：https://github.com/webpack/webpack/issues/2329#issuecomment-210433116

**Comment by agileago** [comment]
js好处理，css那里就有点绕了吧

**Comment by sodatea** [comment]
http://www.infoq.com/cn/articles/front-end-engineering-and-performance-optimization-part1
中文文章也有。这篇文章对为什么不建议用 query、资源冗余的问题都有解答。

**Comment by agileago** [comment]
我也理解这样做的原因，但现在发布部署的时候会产生很多历史遗留文件，清理起来有点麻烦，所以才产生这个需求的

**Comment by sodatea** [comment]
原文评论里有说
> 3. 我们跟踪统计过实际的开发情况，一个重点业务模块，持续使用 fis 1年之后，当前静态资源源码总计5.36M，线上冗余的总量是41.4M，有了这样的实际数据，或许就不会那么担心了吧 
> 4. 退一步说，如果真的因为“看着舒服”需要清理线上冗余，可以写一个脚本，对相同文件的不同版本做最后访问时间排序，把历史版本删除即可

**Comment by agileago** [comment]
thank you
