### ISSUE TITLE
npm run build --no-clean is not working

### ISSUE THREAD

**Issue by gileneusz** [vuejs/vue-cli#2415]
### Version
3.0.0

### Node and OS info
npm 5.6.0

### Steps to reproduce
Following documentation: https://cli.vuejs.org/config/#outputdir

by using new configuration file `vue.config.js` I defined output dir:

outputDir: path.resolve(__dirname, "../wwwFolder/public"),

I also used `npm run build --no-clean`  to not delete previous folder files

### What is expected?
all should work!

### What is actually happening?
aaaaand all my previous files are gone

**Comment by sodatea** [comment]
For `npm run(-script)`, a `--` is required to prepend your custom arguments.
https://docs.npmjs.com/cli/run-script

The correct command is:
```
npm run build -- --no-clean
```

**Comment by gileneusz** [comment]
@sodatea isn't possible to define this `--no-clean` parameter as a custom default inside `vue.config.js`?

**Comment by sodatea** [comment]
No, currently it is not possible to define it in `vue.config.js`.
