### ISSUE TITLE
does proxyTable can only add one 'api' ?

### ISSUE THREAD

**Issue by ringcrl** [vuejs/vue-cli#242]
<img width="486" alt="qq20161117-1 2x" src="https://cloud.githubusercontent.com/assets/16740021/20379196/e3160384-acd5-11e6-8e40-91b912fe01fe.png">
<img width="486" alt="qq20161117-0 2x" src="https://cloud.githubusercontent.com/assets/16740021/20379198/e36c9bea-acd5-11e6-8de4-89480948d855.png">

like that...

api is valid
api2 is not valid...

**Comment by LinusBorg** [comment]
1. This should work. If it doesn't provide a reproduction
2. This is the wrong repo. you want to open a new issue [in the right one](https://github.com/vuejs-templates/webpack/issues) (with a reproduction of the issue)

**Comment by zhang14725804** [comment]
have you resoled the problem？？
