### ISSUE TITLE
Multi part library

### ISSUE THREAD

**Issue by VdustR** [vuejs/vue-cli#2420]
Thanks for the wonderful CLI first!

### What problem does this feature solve?

I'm trying to build libraries with `@vue/cli`. I wanna know if it's possible to build a multi part library that can import sub-library directly like `import subLib from 'my-lib/sub-lib' `?

For now I can only build single file library with `common` and `umd` by using `--target lib`.

### What does the proposed API look like?
Maybe determine this from webpack entry?

**Comment by LinusBorg** [comment]
you will have to run separate build commands for those sub libs, with a different entry and output path.

the `build` command has a `--no-clean` flag so that the other build commands won't remove the results of the previous ones.
