### ISSUE TITLE
Option to specify custom tsconfig.json

### ISSUE THREAD

**Issue by georgyfarniev** [vuejs/vue-cli#2421]
### What problem does this feature solve?
Would be nice to have ability to specify custom tsconfig.json. For example, we have two different tsconfig files: backend.tsconfig.json and frontend.tsconfig.json files and we need to tell vue-cli-service to use frontend.tsconfig.json

### What does the proposed API look like?
tsconfig: 'frontend.tsconfig.json' - in vue.config.js

**Comment by LinusBorg** [comment]
You can use the `chainWebpack` option to adjust the config for ts-loader ans fork-ts-checker-plugin accordingly.

**Comment by vanhumbeecka** [comment]
Example code would be nice though...

**Comment by LinusBorg** [comment]
We have a very active forum and chat for support. 

Issues are not meant for that, as explained in the isssue guidelines.

**Comment by remidenele** [comment]
For those who might be interested as I was, you have to create a `vue.config.js` file at the root of your project to set the path of your tsconfig file (tsconfig.app.json in my case) in the `fork-ts-checker` Webpack plugin:
```javascript
module.exports = {
  chainWebpack: config => {
    config
      .plugin('fork-ts-checker')
      .tap(args => {
        args[0].tsconfig = './tsconfig.app.json';
        return args;
      });
  }
};
```

**Comment by jaxrtech** [comment]
For future viewers, I would add that you also need to also tell `ts-loader` to use your non-default `tsconfig.json` file since otherwise `fork-ts-checker` will typecheck using the alternative tsconfig but then your project will still get transpiled with the incorrect default `tsconfig.json`.

Use the following within your `vue.config.js` instead (replacing `tsconfig.vue.json` with the tsconfig file you want):
 
```js
module.exports = {
  chainWebpack: (config) => {
    config.module
      .rule('ts')
      .use('ts-loader')
      .merge({
        options: {
          configFile: './tsconfig.vue.json',
        }
      });

    config
      .plugin('fork-ts-checker')
      .tap(args => {
        args[0].typescript.configFile = './tsconfig.vue.json';
        return args;
      });
  }
}
```
