### ISSUE TITLE
favicon does not appear in vue cli docs

### ISSUE THREAD

**Issue by ushau97** [vuejs/vue-cli#2423]
### Version
3.0.1

### Reproduction link
[https://cli.vuejs.org/](https://cli.vuejs.org/)

### Node and OS info
all

### Steps to reproduce
1. Go to https://cli.vuejs.org/

### What is expected?
Favicon to be present

### What is actually happening?
Favicon is absent

**Comment by Kocal** [comment]
This can be closed
