### ISSUE TITLE
wc-async components are actually called `foo`

### ISSUE THREAD

**Issue by alexandernst** [vuejs/vue-cli#2425]
### Version
3.0.1

### Reproduction link
[N/A]

### Node and OS info
yarn 1.9.4, Mac Os High Sierra, node 10

### Steps to reproduce
I tried to build my project targeting wc-async as the docs say (`vue-cli-service build --target wc-async --name foo 'src/components/*.vue'`) and found out that the resulting files in the `dist` folder were actually called `foo` (foo1, foo2, foo3...).

Is this expected?

### What is expected?
I'd expect to see the names of my components.

### What is actually happening?
The dist files are called `foo`.

**Comment by LinusBorg** [comment]
> Is this expected?

Yes. You can see it in the code demo in the documentation:

https://cli.vuejs.org/guide/build-targets.html#async-web-component
