### ISSUE TITLE
these dependencies not found but it actually not dependencies

### ISSUE THREAD

**Issue by erwinwahyura** [vuejs/vue-cli#2426]
### Version
3.0.1

### Node and OS info
node v8.9.0 / yarn 1.9.0 / mac os

### Steps to reproduce
i actually just git pull from other branch
and run yarn serve

### What is expected?
expected run well when try to yarn serve vue-project

### What is actually happening?
These dependencies were not found:

@/views/warehouse/delivery/DeliveryDetail.vue in ./src/router/warehouse-delivery/index.js
@/views/warehouse/delivery/DeliveryMain.vue in ./src/router/warehouse-delivery/index.js
@/views/warehouse/delivery/DeliveryParent.vue in ./src/router/warehouse-delivery/index.js
@/views/warehouse/label/LabelDetail.vue in ./src/router/label/index.js
@/views/warehouse/label/LabelMain.vue in ./src/router/label/index.js
@/views/warehouse/label/LabelParent.vue in ./src/router/label/index.js
@/views/warehouse/order/OrderDetail.vue in ./src/router/warehouse-order/index.js
@/views/warehouse/order/OrderMain.vue in ./src/router/warehouse-order/index.js
@/views/warehouse/order/OrderParent.vue in ./src/router/warehouse-order/index.js
To install them, you can run: npm install --save @/views/warehouse/delivery/DeliveryDetail.vue @/views/warehouse/delivery/DeliveryMain.vue @/views/warehouse/delivery/DeliveryParent.vue @/views/warehouse/label/LabelDetail.vue @/views/warehouse/label/LabelMain.vue @/views/warehouse/label/LabelParent.vue @/views/warehouse/order/OrderDetail.vue @/views/warehouse/order/OrderMain.vue @/views/warehouse/order/OrderParent.vue

---
the error says these dependencies were not found, but actually is not a dependencies it just some router in my vue project.

**Comment by LinusBorg** [comment]
This seems to be a problem with your specific project, which you don't share. 

Please use forum.vuejs.org or chat.vuejs.org to ask for help with your project.

**Comment by atilkan** [comment]
I have the same problem. Trying to switch from cli 2 to 3.

**Comment by atilkan** [comment]
@LinusBorg 
This is caused because components inside a folder import another component from another folder. Path resolving seems to have an issue.
I moved the file to src folder and fixed paths, it worked. 
For Example:
In @/pages/Login.vue  -> import LoginForm from "@/components/forms/LoginForm.vue"
This works but can't leave files there.
In @/pages/Login.vue  -> import LoginForm from "@/LoginForm.vue"

**Comment by atilkan** [comment]
@LinusBorg 
I just moved files back and forth, it doesn't throw error anymore. I swear i did not change the code, just undo what i did. This is weird.

**Comment by bam-tbf** [comment]
I experienced this as well. I had to make a change to the file that contained the import statement while vue-cli-service serve was running (even adding and removing whitespace worked), and then the issue went away. Seems like there was some kind of caching happening using vue-cli-service serve that persisted even between restarts.
