### ISSUE TITLE
vue-cli-service build --dest

### ISSUE THREAD

**Issue by vovek** [vuejs/vue-cli#2429]
### Version
3.0.1

### Node and OS info
Node 8.11.4 / npm 6.4.1 / Ubuntu 18.04

### Steps to reproduce
Create new project and run
vue run build --dest directory

### What is expected?
All generated files are in "directory"

### What is actually happening?

> zverev@work:~/workspace/vue-test$ npm run build --dest directory
> vue-test@0.1.0 build /home/zverev/workspace/vue-test
> vue-cli-service build "directory"
> ⠋  Building for production... 
>  ERROR  Failed to compile with 1 errors                                                                                                                                          18:16:04
>  error  
> Entry module not found: Error: Can't resolve '/home/zverev/workspace/vue-test/directory' in '/home/zverev/workspace/vue-test'
>  ERROR  Build failed with errors.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! vue-test@0.1.0 build: `vue-cli-service build "directory"`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the vue-test@0.1.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by vovek** [comment]
My fault
If you want to use custom arguments on `npm run` you should use such command with additional `--`(https://docs.npmjs.com/cli/run-script#synopsis)
`npm run build -- --dest folder`

Or you can use npx:
`npx vue-cli-service build --dest folder`

**Comment by cench** [comment]
> My fault
> If you want to use custom arguments on `npm run` you should use such command with additional `--`(https://docs.npmjs.com/cli/run-script#synopsis)
> `npm run build -- --dest folder`
> 
> Or you can use npx:
> `npx vue-cli-service build --dest folder`

npm run-script <command> [--silent] [-- <args>...]

should be .... npm run build -- dest ?

but doesn`t work,  it works normal  in other not use vue-cli-service

**Comment by rockie-yang** [comment]
in the case of github pages. it will either use root folder or `docs` folder. Change a bit in package.json to have consistency syntax.  

    "scripts": {
      "serve": "vue-cli-service serve",
      "build": "vue-cli-service build --prefix docs --dest docs",
      "lint": "vue-cli-service lint"
    },
