### ISSUE TITLE
no matches found: webpack#1.0

### ISSUE THREAD

**Issue by syaka-yin** [vuejs/vue-cli#243]
when i use `vue init webpack#1.0`, i get an error

`no matches found: webpack#1.0`

vue-cli 2.5.1

How could i use vue1.x ? thanks

**Comment by collins401** [comment]
the same problem as mine

**Comment by posva** [comment]
The `#` is a special character for zsh. Just use quotes around `webpack#1.0`

**Comment by zigomir** [comment]
Thanks @posva for checking this out. I use `zsh` myself but haven't had any similar issues getting vue 1.0 with `vue-cli`. 

@syaka-yin or @collins401 can you please confirm that `vue init "webpack#1.0"` work for you?
