### ISSUE TITLE
Add tslint-config-airbnb and tslint-config-standard TSlint presets

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/vue-cli#2434]
### What problem does this feature solve?
At the moment there's only a basic TSlint config available, it would be good to have more TSlint presets.

### What does the proposed API look like?
There would be tslint-config-airbnb and tslint-config-standard selection when Typescript is selected on the first CLI wizard step.

**Comment by pikadun** [comment]
@LinusBorg Was it forgotten?

**Comment by LinusBorg** [comment]
Tslint will be discontinued and integrated with eslint soon, so I'm not sure how much effort this is worth for the short time in-between.

**Comment by sodatea** [comment]
Now that TSLint [is officially deprecated](https://github.com/palantir/tslint/pull/4906/files), we no longer consider adding new features with regard to the TSLint option.
