### ISSUE TITLE
what's wrong in my vue.config.js

### ISSUE THREAD

**Issue by boot-vue** [vuejs/vue-cli#2440]
### Version
3.0.1

### Reproduction link
[https://github.com/boot-vue/dashboard](https://github.com/boot-vue/dashboard)

### Node and OS info
Node 10.8.0 / yarn 1.9.4 / Windows 10

### Steps to reproduce
git clone https://github.com/boot-vue/dashboard.git

cd dashboard

yarn install 

vue serve

### What is expected?
start normal

### What is actually happening?
Failed to locate entry file in D:\Codes\dashboard.
Valid entry file should be one of: main.js, index.js, App.vue or app.vue.

---
vue.config.js
module.exports = {
    devServer: {
        host: '0.0.0.0',
        port: 8080,
        disableHostCheck: true,
        open: true
    }
}

**Comment by sodatea** [comment]
`yarn serve` not `vue serve`

GitHub issues are for bug reports & feature requests. Next time please consider using forum.vuejs.org or chat.vuejs.org for questions.

**Comment by whygithub7** [comment]
i hame same problem. after creating project with vue create, i try vue serve, end recieve Valid entry file should be one of: main.js, index.js, App.vue or app.vue.

**Comment by sodatea** [comment]
Please use `npm run serve`, not `vue serve`

**Comment by whygithub7** [comment]
why ? vue serve deprecated ?

**Comment by sodatea** [comment]
Have you ever read the documentation?
`vue serve` was originally designed for the instant prototyping of a single component, not for projects. You need to run the `serve` script in `package.json` to start the dev server.

In v5 `vue serve` will be aliased to `yarn serve` or `npm run serve` to avoid further confusions, but in v4 it's kept as is.

**Comment by whygithub7** [comment]
Yes, I came here after the documentation. one component? mean one vue file, even without html? More ?
npm run serve and vue serve the same command?

**Comment by sodatea** [comment]
`npm run serve` runs `vue-cli-service serve`, which is the actual command used to run the project dev server.

`vue serve` in the current version (4.5.12) runs the instant prototyping functionality, it looks for `App.vue` or `main.js` in the current directory as the entry file, then serves it within a built-in HTML page.
This allows the user to prototype a Vue component without creating a project.

`vue serve` in the next version (5.0) will simply run `npm run serve`, so as to avoid confusion.

**Comment by whygithub7** [comment]
1 what is this inline html page?
2 why do you say "vue serve" won't start the development server?
3 What does it mean to prototype a vue component? in the case of native js, I know what a prototype is.

**Comment by sodatea** [comment]
> pro·to·type
/ˈprōdəˌtīp/
verb
make a prototype of (a product).
"Mercedes is prototyping a car sunroof which changes from clear to tinted"

**Comment by sodatea** [comment]
> 2 why do you say "vue serve" won't start the development server?

I mean, it starts a different server than the one you needed for your project.

**Comment by sodatea** [comment]
> 1 what is this inline html page?

I don't think you need to know the implementation detail to understand what `vue serve` does.

**Comment by whygithub7** [comment]
This means that I can create a vue file, and then the vue serve command will create an application from this file? one more question - is html added automatically or generated from vue file?
