### ISSUE TITLE
Unable to force hashing for dev bundle with modern mode

### ISSUE THREAD

**Issue by sergiocastrovale** [vuejs/vue-cli#2443]
### Version
3.0.1

### Node and OS info
Node: v8.11.3, npm: 5.6.0, Windows 10

### Steps to reproduce
Change vue.config.js to force hashing in every environment:

```
module.exports = {
  configureWebpack: {
    output: {
      filename: '[name].[hash:8].js'
    }
}
```

Run vue-cli-service build --mode development --modern.

### What is expected?
The [name] parameter should be enough for the build to understand "app-legacy" and "app" as different bundles.

### What is actually happening?
Both the legacy and the regular bundles are written with the same name, therefore the former is overridden by the latter.

**Comment by LinusBorg** [comment]
During modern mode, vue-cli runs two build with two different webpack setups.

And each time, your config, the user config, ius applied *after* the cli has created its own config. That's normal and of course desirable - your config should alsways have the last "say", right?

So essentially what happens is that while vue-cli creats different output names for both build runs, you overwrite them with the same one each time.

You will have to look at the source and use `process.env.VUE_CLI_MODERN_BUILD` like vue-cli does to differenciate between both runs.

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/prod.js#L4-L8

We could think about makin an exception here, namely that only for the modern run, vue-cli would somehow change the webpack config a second time after the user config has been applied, but I don't like it.

**Comment by sergiocastrovale** [comment]
@LinusBorg wouldn't it make sense to derive the name for both bundles and inject it under whatever `[name]` is? So for example, instead of `app.js` + `app-legacy.js`, we'd have `app.1036cf1d.js` and `app-legacy.1036cf1d.js`. That's what I was expecting out of the box, at least.

**Comment by sergiocastrovale** [comment]
@LinusBorg I'm sorry, I might have explained myself wrong. I'm working on a pretty large app that has 3 server environments _and_ the local environment. So:

* npm run dev is what you'd usually expect
* npm run build-dev runs `vue-cli-service build --mode development`
* npm run build-staging runs `vue-cli-service build --mode staging` - for this example, let's assume it does the same as `build-dev`
* npm run build-production runs `vue-cli-service build --mode production`

Thing is, all these servers have a caching mechanism, so I need a hashed bundle. Therefore, I'm forcing hashing everywhere (this means that _even the local build is hashed_ and HMR seems to work fine):

```
  configureWebpack: {
    output: {
      filename: '[name].[hash:8].js'
    },
    ...
```

All of this is fine but I can't use --modern, because if I do, the legacy file is overriden by the "normal" one (because they will both have the same name). Does this make sense?

**Comment by sergiocastrovale** [comment]
I've modified things a bit:

*package.json*:

```
```

*vue.config.js* 
"build-dev": "vue-cli-service build --mode development --modern",
```

After running `npm run build-dev` with this config ...:

  configureWebpack: {
    output: {
      filename: (process.env.VUE_CLI_MODERN_MODE && !process.env.VUE_CLI_MODERN_BUILD) ? '[name].[hash:8].js' : '[name]-legacy.[hash:8].js'
    },
```

I was expecting this to build `app-legacy.c8a9bed3.js` + `app.c8a9bed3.js`, but instead it built `app-legacy.c8a9bed3.js` twice. What am I missing?

**Comment by sodatea** [comment]
It is because `vue.config.js` is required only once during compilation. So `filename` is determined on the first run as it is a static field.

But when you use `chainWebpack` to override webpack config, we will resolve it (i.e., run the config function) on each build.
For the same reason, a functional `output.filename` also works.

Examples:

```js
module.exports = {
  chainWebpack: config =>
    config.output.filename((process.env.VUE_CLI_MODERN_MODE && !process.env.VUE_CLI_MODERN_BUILD) ? '[name].[hash:8].js' : '[name]-legacy.[hash:8].js')
}

```

or

```js
module.exports = {
  configureWebpack: {
    output: {
      filename: () => (process.env.VUE_CLI_MODERN_MODE && !process.env.VUE_CLI_MODERN_BUILD) ? '[name].[hash:8].js' : '[name]-legacy.[hash:8].js'
    }
  }
}
```

**Comment by sergiocastrovale** [comment]
Right! Thanks a lot for the detailed explanation @sodatea.

Just as a final question, is there any way we can tell apart a local build and a bundle built with `--mode development`? What @LinusBorg about HMR not working properly locally is actually true so I'd like _not_ to hash my local build.

```
    "dev": "vue-cli-service serve",
    "build-dev": "vue-cli-service build --mode development",
```

**Comment by sodatea** [comment]
Seems no but you can define your own env variable for the build script and then reference it in the config function:

```
"dev": "vue-cli-service serve",
"build-dev": "PROJECT_SPECIFIC_ENV=true vue-cli-service build --mode development"
```

**Comment by sergiocastrovale** [comment]
@sodatea Yeah, that was my hack-y idea if we couldn't tell it apart otherwise. Thanks for the help!

**Comment by BartusZak** [comment]
I used different approach:
```
const developmentConfig = {
  runtimeCompiler: true,
  filenameHashing: true,
  outputDir: process.env.BUILD_DIR ? process.env.BUILD_DIR : 'dist',
  configureWebpack: {
    devtool: 'source-map',
    output: {
      filename: '[name].[hash:8].js'
    }
  }
}
```
![image](https://user-images.githubusercontent.com/16143176/73652216-a66dd800-4686-11ea-983b-ae013d0a8aef.png)

**Comment by dandee** [comment]
> It is because `vue.config.js` is required only once during compilation. So `filename` is determined on the first run as it is a static field.
> 
> But when you use `chainWebpack` to override webpack config, we will resolve it (i.e., run the config function) on each build.
> For the same reason, a functional `output.filename` also works.
> 
> Examples:
> 
> ```js
> module.exports = {
>   chainWebpack: config =>
>     config.output.filename((process.env.VUE_CLI_MODERN_MODE && !process.env.VUE_CLI_MODERN_BUILD) ? '[name].[hash:8].js' : '[name]-legacy.[hash:8].js')
> }
> ```
> 
> or
> 
> ```js
> module.exports = {
>   configureWebpack: {
>     output: {
>       filename: () => (process.env.VUE_CLI_MODERN_MODE && !process.env.VUE_CLI_MODERN_BUILD) ? '[name].[hash:8].js' : '[name]-legacy.[hash:8].js'
>     }
>   }
> }
> ```

There's an error in filename condition, it should read:

```js
(process.env.VUE_CLI_MODERN_MODE && process.env.VUE_CLI_MODERN_BUILD)
```

(no negation before VUE_CLI_MODERN_BUILD)
