### ISSUE TITLE
How to switch typescript version ?

### ISSUE THREAD

**Issue by gyc1299339354** [vuejs/vue-cli#2446]
### Version
3.0.1

### Node and OS info
Node 8.11.4 / yarn 1.9.4 / MacOS

### Steps to reproduce
yarn serve / npm run serve

### What is expected?
The Version of Typescript can be switched to the global version ( now is 3.0.3 ) when I run the script 'serve' or 'build'.

### What is actually happening?
I have updated the Typescript globally ( v.3.0.3 ) cause some typescript problem. However the 'server' script was still run in ts2.9.2 ...

**Comment by LinusBorg** [comment]
typescript is only a peerDependency of `@vue/cli-plugin-typescript`, so you can simply install the version you want with `npm install`.
