### ISSUE TITLE
webpack config mainFiles not work

### ISSUE THREAD

**Issue by YvanY** [vuejs/vue-cli#2454]
### Version
3.0.0

### Node and OS info
yarn 1.9.4 / mac os high sierra 10.13.6

### Steps to reproduce
in `vue.config.js`

```javascript
configureWebpack: {
    resolve: {
      mainFiles: ['index', 'Index']
    }
  }
},
```

in other files:

```javascript
import Home from '@/views/Home'
``` 

file structure:

```
.
└── views
    └── Home
        └── Index.vue
```

### What is expected?
Index.vue can be resolved

### What is actually happening?
This dependency was not found:

* @/views/Home in ./src/router.js

**Comment by dobromir-hristov** [comment]
Could you show your `router.js`? Are you async importing that page? I may be the case.

**Comment by LinusBorg** [comment]
https://github.com/YvanY/vue-cli-mainFiles/blob/master/src/App.vue#L9

This:
```javascript
import HelloWorld from './components/HelloWorld/HelloWorld'
```
should be this:
```javascript
import HelloWorld from './components/HelloWorld'
```

**Comment by LinusBorg** [comment]
Ran this, and the error persists even with the correct path.

However, `inspect` shows that the setting is correctly applied, so if anything, this is related to webpack, not vue-cli
