### ISSUE TITLE
Cannot remove puglin

### ISSUE THREAD

**Issue by nunonux** [vuejs/vue-cli#2457]
### Version
3.0.1

### Node and OS info
v8.11.3

### Steps to reproduce
Install a plug-in using Vue-Cli 3.
Cannot remove it.

### What is expected?
Remove plug-in

### What is actually happening?
Cannot remove plug-in

**Comment by LinusBorg** [comment]
Please follow the issue guidelines. No one can understand what you mean with a one-line description like this
