### ISSUE TITLE
change baseUrl not work

### ISSUE THREAD

**Issue by ycshill** [vuejs/vue-cli#2458]
### What problem does this feature solve?
when I change `baseUrl:` './' `，but It is not work . The file packaging path is still ``'css/chunk-vendors.92e039b5.css'.``Then I found source code write like this ``resolved.baseUrl = resolved.baseUrl.replace(/^\.\//, '')``, I don't know why ? 

### What does the proposed API look like?
I want to the file packaging path  will change when I configure the ``baseUrl: './' ``

**Comment by vainamov** [comment]
Can you specifiy the current version you are using? With vue-cli 3.0.0-rc.10 it works perfectly fine.

**Comment by LinusBorg** [comment]
I don't understand the problem. `./` means: a relative path. 

In terms of a src path for assets in an html page, that's the same as starting the path with "nothing".

So I do t understand what behaviour you want to change - this change wouldn't do anything.

**Comment by yyx990803** [comment]
`./` is the same as empty in URL paths.

**Comment by ycshill** [comment]
I want to get the  './css/chunk-vendors.92e039b5.css' after packged by change the`baseUrl: './' `

**Comment by LinusBorg** [comment]
Why? That has no effect whatsoever.

**Comment by ycshill** [comment]
Thank you all，i see.
