### ISSUE TITLE
this.$store is undefined in the «library» mode

### ISSUE THREAD

**Issue by netstuff** [vuejs/vue-cli#2464]
### Version
3.0.0

### Reproduction link
[https://gitlab.com/netstuff/umd-store](https://gitlab.com/netstuff/umd-store)

### Node and OS info
Node 10.9.0 / yarn 1.9.4 / MacOS 10.13.6

### Steps to reproduce
yarn install
yarn run build --target lib --name Hello 'src/components/HelloWorld.vue'

open dist/demo.html
see devtools: [Vue warn]: Error in render: "TypeError: Cannot read property 'getters' of undefined

### What is expected?
Expected that this.$store attribute will give access to application global Vuex-store object. 

### What is actually happening?
this.$store is undefined

---
Want to use this.$store transparently without need to know what kind of build I will use.

**Comment by sodatea** [comment]
You don't have a global vuex-store object when building as a library. The setup logic of global vuex store is in `main.js`, which, is certainly not included in the library build.

**Comment by netstuff** [comment]
@sodatea, what the best way to use it in library build?

**Comment by sodatea** [comment]
@netstuff 
It's not recommended to use vuex in a standalone component.

But if you do need it, just initialize the store in the component that you want to ship as a library:

```js
import store from './store'

// ...

export default {
  store,
  name: 'HelloWorld',
  // ...
}
```

**Comment by netstuff** [comment]
@sodatea, goddamn! It's what I need, man! Thank you very much!
