### ISSUE TITLE
Vue Resource Installation Error

### ISSUE THREAD

**Issue by donPuerto** [vuejs/vue-cli#247]
"vue": "^2.0.1"

![vue-resource](https://cloud.githubusercontent.com/assets/9329005/20460734/a6fe921c-af28-11e6-818f-81b88b53edb3.PNG)

**Comment by CYBAI** [comment]
Your `name` in `package.json` might be as same as `vue-resouece`?

ref: [Node Newbie Error – NPM Refusing to Install Package as a Dependency of Itself](http://thisdavej.com/node-newbie-error-npm-refusing-to-install-package-as-a-dependency-of-itself/)

**Comment by egoist** [comment]
Yep, just as @CYBAI said.
