### ISSUE TITLE
自定义的 vue 项目初始化模版插件，尝试利用 generator 来完成「删除项目中 src」的操作时失败

### ISSUE THREAD

**Issue by zoux** [vuejs/vue-cli#2470]
### Version
3.0.1

### Reproduction link
[https://github.com/zoux/vue-cli-plugin-template](https://github.com/zoux/vue-cli-plugin-template)

### Node and OS info
Node 10.9.0 / npm 6.2.0 / macOS 10.13.4

### Steps to reproduce
1. `vue create my-app` 初始化任意一个新的项目；
2. `vue add @zouxin/template` 使用插件时，期望插件中 generator 先尝试删除项目中的 src，然后 api.render('./template') 来粘贴模版文件。但删除 src 的操作失败，导致最终得到的 src 是初始模版和 render 模版的混合结果。

### What is expected?
期望能在 api.render 前，完成删除 src 的操作

### What is actually happening?
先尝试删除项目中的 src，然后 api.render('./template') 来粘贴模版文件。但删除 src 的操作失败，最终得到的 src 是初始模版和 render 模版的混合结果

**Comment by sodatea** [comment]
其实你不需要自己实现 `__remove` 函数，这是 `api.render` 最后的回写代码：
https://github.com/vuejs/vue-cli/blob/3def765ba438638b09c6e76547b85a29ddde3ba6/packages/%40vue/cli/lib/util/writeFileTree.js#L19-L21
`files` 对象中被删除的字段，对应的实际文件都会被删掉。

所以
```js
__remove(api.resolve('./src'))
```

可以写成
```js
api.render(files => {
  Object.keys(files)
    .filter(name => name.startsWith("src/"))
    .forEach(name => delete files[name])
})
```

**Comment by screetBloom** [comment]
> 其实你不需要自己实现 `__remove` 函数，这是 `api.render` 最后的回写代码：
> https://github.com/vuejs/vue-cli/blob/3def765ba438638b09c6e76547b85a29ddde3ba6/packages/%40vue/cli/lib/util/writeFileTree.js#L19-L21
> 
> 
> `files` 对象中被删除的字段，对应的实际文件都会被删掉。
> 所以
> 
> ```js
> __remove(api.resolve('./src'))
> ```
> 
> 可以写成
> 
> ```js
> api.render(files => {
>   Object.keys(files)
>     .filter(name => name.startsWith("src/"))
>     .forEach(name => delete files[name])
> })
> ```

@sodatea  
我查看了一下自己的vue cli版本，是3.x
`
// 3.10.0

vue --version
`
目前我这边在测试利用api.render 来实现delete的时候，发现即使当前工程已存file被delete了，文件还是会被merge，比如package.json
<br/>
可以简单的通过如下代码测试
`
// generator.js
api.render(files => {
  Object.keys(files).forEach(path => delete files[path])
})
api.render('./template')

//  ./template/package.json
{
  "name": "test-demo",
  "version": "0.1.0",
  "description": "研发框架组件",
}
`
