### ISSUE TITLE
Vue Cli 3 seems to be removing styles from assets

### ISSUE THREAD

**Issue by ChadTaljaardt** [vuejs/vue-cli#2475]
### Version
3.0.1

### Reproduction link
[https://github.com/ChadTaljaardt/BootstrapTest](https://github.com/ChadTaljaardt/BootstrapTest)

### Node and OS info
node 10.9.0 / yarn 1.9.4 / windows 7

### Steps to reproduce
When you view the buttons from bootstrap, they should have a margin.

you can see a working version (without vue cli 3) here: 

### What is expected?
you can see a working version (without vue cli 3) here: https://jsfiddle.net/krq18pej/2/

### What is actually happening?
There is no margin between the buttons.
Top version is Vue Cli 3 and bottom which is correct is the JSFiddle version
![untitled22222](https://user-images.githubusercontent.com/13891249/45291649-aa75e480-b4ea-11e8-96a4-dd6d2689b479.png)

**Comment by funkydunc** [comment]
:+1:

**Comment by Justineo** [comment]
See #1020.

**Comment by sodatea** [comment]
> however it didn't work

Works on my machine: https://asciinema.org/a/x0BYCcnRil3anJjL1EdQVLKoZ

**Comment by ChadTaljaardt** [comment]
Was able to get this working, thanks :+1:

**Comment by hellomrbigshot** [comment]
> @Justineo I tried to do the suggested fix of adding this to the vue.config.js, however it didn't work.
> 
> ```
> chainWebpack: config => {
>     config.module
>       .rule('vue')
>       .use('vue-loader')
>       .loader('vue-loader')
>       .tap(options => {
>         options.compilerOptions.preserveWhitespace = true
>         return options
>       })
>   }
> ```

It does not work for me. But when i delete ```return options```, it works.

**Comment by hjelperne** [comment]
Same here: It only works after removing "**return options**".
