### ISSUE TITLE
ES6 version of vue should be used for the modern mode

### ISSUE THREAD

**Issue by xorik** [vuejs/vue-cli#2477]
### Version
3.0.1

### Reproduction link
[https://github.com/xorik/vue-es5](https://github.com/xorik/vue-es5) (default project with the babel checkbox selected only)

### Node and OS info
node 8.11.4 / yarn 1.9.4 / Mac OS 10.13.6

### Steps to reproduce
1. Run `yarn run build --modern --report` on a clean vue-cli project
2. Open `dist/report.html`

### What is expected?
3. ES6 version of vue should be used for the modern mode

### What is actually happening?
3. ES5 version is used (`vue.runtime.esm.js`)

---
This is probably also true for other dependencies (vuex, router, external libs)

**Comment by sodatea** [comment]
But this *is* the ES6 version… (Or, precisely speaking, the ES Module version, as specified in the `module` field in [`package.json`](dist/vue.runtime.common.js))

**Comment by xorik** [comment]
@sodatea no, it's compiled es5 code, just open the file in any editor:
- it doesn't contain arrow functions
- it doesn't contain `let` keyword
- it doesn't contain any es6 code
- Your documentation said: _These transpiled bundles are often more verbose than the original native ES2015+ code, and also parse and run slower_

So whole point of using es6 features (modern mode) is useless, because  quite big part of code is es5 code.

**Comment by sodatea** [comment]
@xorik
There are two parts of the problem:
1. How we decide what to import for the *modern* build with regard to a third party dependency:
    1. Some third party libraries ship ES5 code, some also ship ES6 version along with ES5 one.
    2. So there has to be a way to differentiate the two versions. The most widely adopted community 
standard is [pkg.module](https://github.com/rollup/rollup/wiki/pkg.module)
    3. In Vue's [package.json](https://unpkg.com/vue@2.5.17/package.json), the `module` field points to `dist/vue.runtime.esm.js`, so we imported it.
2. Why Vue ships the ESM version with compiled code:
    1. The biggest reason for this is that Vue does not use Babel & Webpack to transpile its source code. The `vue` package is built with **rollup** and **bubble**. By carefully picking up what modern language feature to use in the source code, Vue managed to have a rather small compiled version while still being compatible with most browsers. If users compiles Vue themselves, they would lose this benefit.
    2. While the inner implementation is the same, `vue.runtime.esm.js` exports the `Vue` object in ES Module syntax. This makes a lot of modern web toolings easier to interop with it.

**Comment by xorik** [comment]
@sodatea thank you for the explaining.

>Some third party libraries ship ES5 code, some also ship ES6 version along with ES5 one.
I completely understand that, we can't do much about external libs.

But maybe it is possible to make a new pure ES6 bundle for vue.js, and use it for the modern build (with custom webpack rules for example)?

I understand, that this is a workaround, but it could increase performance for modern browsers.

What do you think?
