### ISSUE TITLE
sass文件中加入rgba编译报错

### ISSUE THREAD

**Issue by baixiaosh** [vuejs/vue-cli#248]
问题很奇怪，背景色设置rgba就会编译出错，其他则不会
vue 2.0
vue-loader 9.4.0
sass-loader 4.0.2
node v6.9.1

**Comment by baixiaosh** [comment]
10 verbose lifecycle zwl@1.0.0~dev: CWD: E:\baixiaosh\zwl
11 silly lifecycle zwl@1.0.0~dev: Args: [ '/d /s /c', 'node build/dev-server.js' ]
12 silly lifecycle zwl@1.0.0~dev: Returned: code: 3221225501  signal: null
13 info lifecycle zwl@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: zwl@1.0.0 dev: `node build/dev-server.js`
14 verbose stack Exit status 3221225501
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid zwl@1.0.0
16 verbose cwd E:\baixiaosh\zwl
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error zwl@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 3221225501
23 error Failed at the zwl@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the zwl package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs zwl
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls zwl
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by egoist** [comment]
这和 vue-cli 似乎没有关系。

**Comment by baixiaosh** [comment]
好像是的，但是不知道是node 还是sass-loader的问题 配置都是vue-cli默认的呀
