### ISSUE TITLE
vue ui &  install bug

### ISSUE THREAD

**Issue by xgqfrms** [vuejs/vue-cli#2481]
# vue ui &  install bug

```json

{
  "name": "dev",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.1",
    "@vue/cli-plugin-eslint": "^3.0.1",
    "@vue/cli-service": "^3.0.1"
  }
}

```
![image](https://user-images.githubusercontent.com/7291672/45347073-b7273500-b5dd-11e8-91f5-0e1b401c7f55.png)

![image](https://user-images.githubusercontent.com/7291672/45348646-cb6d3100-b5e1-11e8-958d-0a5b711fc121.png)

**Comment by LinusBorg** [comment]
you are using an npm mirror (taobao?) which served you a corrupt file.

* reinstall node_modules
* if that doesn't work: use another registry with `vue create --registry `
* or try installing with `yarn` instead.

**Comment by xgqfrms** [comment]
# still bug

![image](https://user-images.githubusercontent.com/7291672/45395475-dcad5080-b668-11e8-8ca1-d9a54ea8d0d1.png)

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/45396092-12076d80-b66c-11e8-9cea-444b461dc541.png)

**Comment by xgqfrms** [comment]
![image](https://user-images.githubusercontent.com/7291672/45399590-37e83e80-b67b-11e8-8725-27fa093d88bc.png)
 
# `Yarn` is OK

![image](https://user-images.githubusercontent.com/7291672/45399656-7e3d9d80-b67b-11e8-91c1-ba9abe7aaad0.png)

**Comment by xgqfrms** [comment]
# shit TB npm & shit @vue/cli-service
