### ISSUE TITLE
yorkie npm_config_prefix: git cz and then gitHooks pre-commit npm run lint fail

### ISSUE THREAD

**Issue by IndexXuan** [vuejs/vue-cli#2484]
### Version
3.0.1

### Node and OS info
Node 8.11.3 / yarn 1.9.4 / OSX

### Steps to reproduce
husky works well

### What is expected?
git cz and pre-commit works well

### What is actually happening?
fail with nvm npm_config_prefix error

---
```bash
nvm is not compatible with the "npm_config_prefix" environment variable: currently set to "/Users/indexxuan/.nvm/versions/node/v8.11.3"
Run `unset npm_config_prefix` to unset it.
.git/hooks/pre-commit: line 45: node: command not found

pre-commit hook failed (add --no-verify to bypass)
git exited with error code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-cli-project@0.0.1 commit: `git cz`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-cli-project@0.0.1 commit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by sodatea** [comment]
Would you please provide a reproduction for this issue?
The description is too vague and I can't reproduce this problem locally.

**Comment by nullfame** [comment]
(posting in case anyone else comes across this)

I think I blame yorkie here and how it handles nvm (though in my case I'm using asdf) and a git client (GUI).  Definitely there are some differences in how husky and yorkie generate commit hooks.

yorkie + nvm + GUI = FAIL
yorkie + nvm + git cli = pass
husky + nvm + git cli = pass
husky + nvm + GUI = pass

I'm not using Vue at all in my project, but I'm trying to exactly mimic what vue-cli produces.  The choice between yorkie and husky may, however, be relevant to vue-cli.
