### ISSUE TITLE
fail to connect websocket, Invalid frame header

### ISSUE THREAD

**Issue by liuhanqu** [vuejs/vue-cli#2486]
### Version
3.0.1

### Reproduction link
[https://github.com/liuhanqu/vuecli-demo](https://github.com/liuhanqu/vuecli-demo)

### Node and OS info
npm: 6.2.0, os: mac

### Steps to reproduce
1. cd client && npm i && npm run serve
2. cd server && npm i && npm start
3. open browser to 'http://localhost:8888/laboratory'

### What is expected?
websocket connect success

### What is actually happening?
websocket fail to connect

### bug image
![1536672681591](https://user-images.githubusercontent.com/13450124/45363476-36caf900-b60a-11e8-9e43-5a2cd242ca7d.jpg)

**Comment by LinusBorg** [comment]
You are runing your app server in front of the dev-server, while the usual setup is the other way around. Why would you do that?

If you want to keep doing that, you will have to proxy websocket connections from your app server through to your devserver with a middle ware. That's not a problem for us to solve, though.

**Comment by liuhanqu** [comment]
render a html, sometimes u would output some variable to html.
when use dev-server, it can not do that.
maybe my implementation is wrong.
thanks.

**Comment by Tech-Nomad** [comment]
"Why would you do that?" 
Server-Side-Rendering with PHP for example like in my case? 
As far as I know is SSR part of the Vue project. Or am I wrong?
