### ISSUE TITLE
Error: ENAMETOOLONG on building

### ISSUE THREAD

**Issue by ndabAP** [vuejs/vue-cli#2488]
### Version
3.0.2

### Node and OS info
Node 10.9.0 / npm 6.4.0 / Ubuntu 18.04

### Steps to reproduce
Run `NODE_ENV=production vue-cli-service build` on my code.

### What is expected?
Application is built like yesterday.

### What is actually happening?
Error:

> Error: ENAMETOOLONG: name too long, open '/mnt/Entwicklung/docemur/public/js/chunk-0621_0f05_0f0f_1041_111b_1257_1a2d_1bac_220e_242e_25b4_285e_29fb_30c8_3414_3789_3818_3eda_46b4_470f_48a0_4d8c_4fcb_54eb_57d6_5b01_5c69_5d89_6286_6b5c_6b9a_6dee_6f6c_7168_8057_833e_8860_89ea_8db3_9380_950a_97d3_9f74_a029_a2db_a738_ab74_b190_b343_b6da_b767_b8ce_b92f_ba51_bcdf_bfcb_c2b6_c2e4_c3fc_c452_c6cf_c87c_cb84_cc45_d000_d018_d7ee_da53_dc46_dd61_e6c3_e7a6_e8a9_e93d_e9a7b_f7d3_fe50.d8c0742b.js'

---
Everything went fine yesterday and I didn't touch any client specific code. There are many long files like that at the built directory.

**Comment by LinusBorg** [comment]
have you whiped node_modules and reinstalled?

**Comment by ndabAP** [comment]
Yes!

**Comment by LinusBorg** [comment]
any changes to the default configuration?

this doesn't happen in our CI, so we have to get something to reproduce this from you.

**Comment by oddmouse** [comment]
I'm having the exact same issue on node 10.10.0 / yarn 1.9.4 / MacOS 10.13.6. I reverted the `cli-service` package back to 3.0.1 and builds correctly again, all other packages are upgraded to latest. 

Creating a project from scratch using `vue create` and using my project's `vue.config.js` builds just fine as well. I'll keep trying to dissect my code base to find the culprit.

**Comment by LinusBorg** [comment]
Closing on favor of #2490

**Comment by rzp1** [comment]
Has it been solved
