### ISSUE TITLE
Chunk file names are excessively long

### ISSUE THREAD

**Issue by phil-scott-78** [vuejs/vue-cli#2490]
### Version
3.0.2

### Reproduction link
[https://github.com/phil-scott-78/showplan.js](https://github.com/phil-scott-78/showplan.js)

### Node and OS info
Node v8.11.2, Windows 10 (deploying to Azure)

### Steps to reproduce
npm run build

check the size of the file names of the chunks

### What is expected?
Files created have names > 250 characters. This becomes an issue when deploying to Windows servers and Azure

### What is actually happening?
Files such as this are being created. 

dist\js\chunk-006c_0410_075d_0fde_1111
  _12c9_2f08_346d_36f6_436c_47d3_5844_62
  d8_62eb_7423_7aa1_7daa_85ac_85be_89b1_
  8ddc_95ec_b9a6_bccc_bdfc_6_13_10_8_14_
  18_11_15_7_9_16_17_12_c197_c578_d7a2_e
  031_f41f_f817.15e205eb.js

---
This stems from 3933187f7339e9e71ae1bcdb9f3e7e98ae39eb6d which is now creating chunk names with all the ids contacted together.

**Comment by rlightner** [comment]
This is breaking our windows build enviroment with a `Error: ENOENT: no such file or directory`

**Comment by FFxSquall** [comment]
I also have the same thing in Ubuntu

**Comment by LinusBorg** [comment]
According to reports in #2488 reverting to 3.0.1 fixes it for the moment. 

We will investigate and fix asap.

**Comment by rzp1** [comment]
Has it been solved

**Comment by rzp1** [comment]
@FFxSquall @rlightner @phil-scott-78 Have you solved it yet?

**Comment by sodatea** [comment]
@rzp1 fixed in v3.0.3

**Comment by rlightner** [comment]
@rzp1 fixed for me in v3.0.3 as well

**Comment by rzp1** [comment]
thanks
