### ISSUE TITLE
"Vue create" tries to get "@vue/cli-plugin-babel": "^3.0.3" which does not exist

### ISSUE THREAD

**Issue by dietervy** [vuejs/vue-cli#2494]
### Version
3.0.3

### Node and OS info
npm

### Steps to reproduce
- install vue-cli 3
- "vue create [project]" with default settings (babel eslint)

### What is expected?
The project is created 

### What is actually happening?
npm ERR! notarget No matching version found for @vue/cli-plugin-babel@^3.0.3

**Comment by atiasdudi** [comment]
vue create also broken in cli v3.0.1 and v3.0.2 (same issue)

**Comment by sodatea** [comment]
Fixing it now. Seems a bug in lerna leads to a partial release.

**Comment by sodatea** [comment]
Should have been fixed now.

**Comment by ndabAP** [comment]
I have a similar issue at my CI with the service:

> No matching version found for @vue/cli-service@^3.0.3

Have no problem installing it locally, though.

**Comment by ndabAP** [comment]
**Update**: Works fine now!
