### ISSUE TITLE
 notarget No matching version found for @vue/cli-plugin-babel@^3.0.3

### ISSUE THREAD

**Issue by JanChw** [vuejs/vue-cli#2495]
IMPORTANT: Pl
![snipaste_2018-09-12_15-36-28](https://user-images.githubusercontent.com/14163060/45409435-b5bf4080-b6a1-11e8-81bd-cfd35b341c06.png)
ease use the following link to create a new issue:

https://new-issue.vuejs.org/?repo=vuejs/vue-cli

If your issue was not created using the app above, it will be closed immediately.

中文用户请注意：
请使用上面的链接来创建新的 issue。如果不是用上述工具创建的 issue 会被自动关闭。

**Comment by ndabAP** [comment]
See https://github.com/vuejs/vue-cli/issues/2494.
