### ISSUE TITLE
vue/no-unused-vars: "off" 无效, 需要设置为 no-unused-vars: "off"

### ISSUE THREAD

**Issue by geshansuiyue** [vuejs/vue-cli#2499]
### Version
3.0.3

### Reproduction link
[https://github.com/geshansuiyue](https://github.com/geshansuiyue)

### Node and OS info
8.11.3

### Steps to reproduce
vue ui打开后的eslint配置 vue/no-unused-vars: "off"后并没有效果

### What is expected?
希望能解决这个问题

### What is actually happening?
vue/no-unused-vars: "off" 无效

**Comment by sodatea** [comment]
请问没有效果具体是什么表现？
这个规则的作用是提示模板中的未使用变量 https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-unused-vars.md

**Comment by geshansuiyue** [comment]
就是配置这个选项后，eslint还是会报已定义未使用的错误。

**Comment by geshansuiyue** [comment]
> 请问没有效果具体是什么表现？
> 这个规则的作用是提示模板中的未使用变量 https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/no-unused-vars.md

就是配置这个选项后，eslint还是会报已定义未使用的警告。

**Comment by sodatea** [comment]
会针对怎样的代码报错？如果是针对 js 代码的话，那是正常的，你可能理解错这个规则的用途了

**Comment by geshansuiyue** [comment]
我是通过vue ui配置的。报错的代码是js的。

**Comment by sodatea** [comment]
那就是正常的。请仔细看文档
no-unused-vars 规则作用于 js 代码
vue/no-unused-vars 作用于 vue 模板

**Comment by geshansuiyue** [comment]
是vue模板，我用vuecli创建的项目。

**Comment by sodatea** [comment]
这里的 vue 模板说的是 template 部分的代码

**Comment by geshansuiyue** [comment]
好的，多谢解答。
