### ISSUE TITLE
hot module reload not work

### ISSUE THREAD

**Issue by agileago** [vuejs/vue-cli#25]
i use webpack

when i `$mount` a root vue instance. hot module reoad is not work

see example

``` html
   <div id="app"></div>
```

```javascript
import Vue from 'vue'
import App from './App.vue'

var AppConstructor = Vue.extend(App)
var app = new AppConstructor
app.$mount('#app')
```

now edit `App.vue` some words. browser seems not work

and i find this breakpoint
![image](https://cloud.githubusercontent.com/assets/11799110/12581533/278a4676-c472-11e5-8bba-dd59827f1f25.png)

![image](https://cloud.githubusercontent.com/assets/11799110/12581543/3e3d7726-c472-11e5-8f36-bb9b62f5d7c5.png)

**Comment by yyx990803** [comment]
Imperatively mounted instances are not hot-reloadable. You can wrap it inside a root though:

``` js
new Vue({
  el: '#app',
  components: { App }
})
```
``` html
<div id="app>
  <app></app>
</div>
```
