### ISSUE TITLE
command vue not found

### ISSUE THREAD

**Issue by mr-ant** [vuejs/vue-cli#2507]
### Version
3.0.3

### Node and OS info
yarn 1.9.4

### Steps to reproduce
系统：Windows10 wsl
使用的nvm安装的node 版本是 8.12.0。之后使用npm安装了yarn，设置了淘宝镜像，然后使用 yarn 来安装`yarn global add @vue/cli`,然后提示 `command vue not found`。使用npm方式安装没有问题！

### What is expected?
能够使用yarn来安装vue

### What is actually happening?
不能执行！

**Comment by sodatea** [comment]
这是 yarn 的问题，不是 Vue CLI 的问题。
请确保 yarn 的全局命令安装目录已经加在你的 $PATH 变量中。
可以用 `yarn global bin` 获得通过 yarn 安装的命令行工具所在的目录。
