### ISSUE TITLE
Multi-page shouldn't preload/prefetch resources that do not belong to it

### ISSUE THREAD

**Issue by Binaryify** [vuejs/vue-cli#2508]
### Version
3.0.3

### Node and OS info
Node v8.11.4/yarn 1.9.4/MacOS 10.11.6

### Steps to reproduce
vue.config.js
```
 pages: {
    index: {
      entry: 'src/main.js',
      template: 'public/index.html',
      filename: 'index.html'
    },
    download: {
      entry: 'src/multiPage/download/main.js',
      template: 'src/multiPage/download/index.html',
      filename: 'download.html'
    }
  },
```

### What is expected?
the download page is mobile page, it should just load the resources of itself

### What is actually happening?
in the dist/download.html file it does load chunk-vendors, chunk-common, download.js, but it also preload/prefetch the resources of the index pages' CSS and js files 

---
what should I do now, it this feature or bug

**Comment by Binaryify** [comment]
## Added
![image](https://user-images.githubusercontent.com/12221718/45473970-0ea6db80-b76b-11e8-9c9c-f4ff35aca3a7.png)
![image](https://user-images.githubusercontent.com/12221718/45473997-1f575180-b76b-11e8-8b9d-3dbea93e9d6e.png)
I also have use vue-router lazy load feature

**Comment by sodatea** [comment]
It's a feature.

> Prefetch is a hint to the browser that a resource might be needed, but delegates deciding whether and when loading it is a good idea or not to the browser.
> Prefetch focuses on fetching resources for the next navigation which are low priority.

So async chunks are prefetched.

**Comment by Binaryify** [comment]
@sodatea 
but in other pages, they maybe don't need that chunks, have any options to disabled that? I don't want mobile pages download PC resources

**Comment by bskimball** [comment]
Vue-cli guidance for prefetching https://cli.vuejs.org/guide/html-and-static-assets.html#prefetch
