### ISSUE TITLE
i have write a scaffold for vue-cli,can you add it to this readme?

### ISSUE THREAD

**Issue by qxl1231** [vuejs/vue-cli#251]
i have write a full stack of loopback+vue scaffold,can you add it to this readme?
for help user use loopback+vue much easy. one more choose ,is better for CLI maybe
https://github.com/qxl1231/loopback-vue/tree/master

any issue, please feel free to contract me  ~

**Comment by qxl1231** [comment]
and my question is: how to add my scaffold to your cli tool? the yeoman is use NPM ,for example i only need to publish ,and add key words yeoman , but how to add my custom scaffold to your CLI tool?

**Comment by egoist** [comment]
vue init github-username/repo-name

**Comment by egoist** [comment]
The readme is only for official templates, I guess you can add yours to https://github.com/vuejs/awesome-vue#boilerplates
