### ISSUE TITLE
Lint task fails in Vue UI [invalid options in vue.config.js: "assetsDir" is not allowed to be empty]

### ISSUE THREAD

**Issue by jamesalways** [vuejs/vue-cli#2511]
### Version
3.0.3

### Node and OS info
Node v8.10.0 / yarn 1.9.4 / macOS High Sierra 10.13.6

### Steps to reproduce
- Run vue ui.
- Go to your project.
- Go to tasks.
- Run lint task.

### What is expected?
Linter errors.

### What is actually happening?
The output show next error a lot of times:

 ERROR  Invalid options in vue.config.js: child "assetsDir" fails because ["assetsDir" is not allowed to be empty]

**Comment by sodatea** [comment]
Please, do provide a reproduction.

What's in your `vue.config.js`?

**Comment by jamesalways** [comment]
```
module.exports = {
    lintOnSave: false,

    pluginOptions: {
        i18n: {
            locale: 'es',
            fallbackLocale: 'es',
            localeDir: 'locales',
            enableInSFC: false
        }
    },
    baseUrl: './'
}

```

**Comment by jonaskuske** [comment]
I had the same issue a few days ago!  
Only way to get rid of the error was to actually define `assetsDir`, if I removed it again, the error reappeared. Then a day later or so, I removed `assetsDir` and somehow it still worked, error was gone.  
Still non the wiser about what causes it, though :(

**Comment by jamesalways** [comment]
Hi!

Today, it's working for me, last week don't. I don't understand it... It's very weird, I haven't changed anything.

thanks!

**Comment by assembledadam** [comment]
Got this too, same process as OP to reproduce.

**Comment by Roscoe93** [comment]
same issue，only when running lint task in ui, `npx vue-cli-service lint` always works well.
I have this config to make eslint work with webpack alias, ui lint task works well when it's removed
```javascipt
  settings: {
    'import/resolver': {
      webpack: {
        config: path.resolve(__dirname, 'node_modules/@vue/cli-service/webpack.config.js'),
      },
    },
  },
```

here's my vue.config.js
```javascript
const path = require('path');
const fs = require('fs');

module.exports = {
  configureWebpack: {
    resolve: {
      alias: {
        vue$: 'vue/dist/vue.esm.js',
        '@': resolve('src'),
        _index: resolve('src/pages/index'),
        _acti: resolve('src/pages/activity'),
      },
    },
  },
  css: {
    loaderOptions: {
      sass: {
        data: fs.readFileSync(path.join(__dirname, './src/assets/style/variables.scss'), 'utf8'),
      },
    },
  },
  devServer: {
    proxy: {
      '/api': {
        target: 'http://localhost:8666',
        pathRewrite: {
          '^/api': '/api',
        },
      },
    },
  },
};
```

**Comment by FFxSquall** [comment]
@sodatea reproduce repo https://github.com/FFxSquall/vue-ui-bug

**Comment by imudin** [comment]
I have the same  issue, how to fix?

**Comment by sodatea** [comment]
@imudin It's fixed in @vue/cli v3.1.3

**Comment by imudin** [comment]
@sodatea Thanks I thought the latest one is 3.1.1

**Comment by imudin** [comment]
@sodatea Still happening in version 3.1.3

**Comment by imudin** [comment]
@sodatea it is working well after updating @vue/cli-plugin-eslint, @vue/cli-service and dev dependencies related to eslint. Now output is showing real issue in my code instead of long webpack error issue. Thanks a lot!
