### ISSUE TITLE
how to import env variables into vue-router

### ISSUE THREAD

**Issue by CharlesSong** [vuejs/vue-cli#2513]
### Version
3.0.0

### Node and OS info
npm 5.6.0 /node 8.11.2/windows 10

### Steps to reproduce
```
const base= process.env.CUSTOM_BASE
console.log(base)
const router = new VueRouter({
  base: base,
  mode: 'history',
  routes: [{
    path: '/',
    name: '首页',
    component: _import('HelloWorld')
  }
  ]
})
```

### What is expected?
在vue-router中引入env自定义参数，实现根据环境定义vue-router#base配置，构建并部署到多个不同的子文件夹下

### What is actually happening?
CUSTOM.BASE is undefined

**Comment by LinusBorg** [comment]
https://cli.vuejs.org/zh/guide/mode-and-env.html
