### ISSUE TITLE
Suggest: add 'blank' vue.config.js file with comment/link to documentation about extending webpack

### ISSUE THREAD

**Issue by easherma** [vuejs/vue-cli#2519]
### What problem does this feature solve?
As a new cli user, a first impression after creating a new project with vue cli is the missing webpack config. A glance at the docs can clear this up, but I'd advocate for creating a default vue.config (or webpack file?) with a comment explaining why a webpack config file isn't there, what a vue.config file is, etc. 

### What does the proposed API look like?
Something like commented out examples of the general settings seen in the Vue UI, link to dos about extending vue config, etc.

**Comment by LinusBorg** [comment]
Well we already generate a README.md file, I think that would be a good place to include some links to the docs. :+1: 

I don't think that rendering some empty config files with a link would offer any better experience then that. I also would not want these comments to go much further than linking to the docs, I feel like this is already too much:

> with a comment explaining why a webpack config file isn't there, what a vue.config file is, etc.

All of that is covered in the docs, so I don't feel like it's a good idea to add a "documentation light" to any config file within the project. A Link to the docs should suffice. People unwilling to read docs are on their own as far as my personal opinion is concerned.

**Comment by sodatea** [comment]
@easherma Actually that's the right place. Feel free to go ahead.
