### ISSUE TITLE
Add `vue` to lintConfig choices

### ISSUE THREAD

**Issue by tamilsweet** [vuejs/vue-cli#252]
After creating vue project using vue-cli, if we try the examples from Vuex, the eslint throws lots of warnings/errors.
Reason:
Vuex examples uses 'eslint-config-vue' for linting
vue-cli doesn't provide the same option when creating new project.

**Comment by egoist** [comment]
eh, why do you lint the code if you are just trying the Vuex example ?

**Comment by LinusBorg** [comment]
1. Please open such issues in the repository of the template in question
2. Yes, PRs are welcome
