### ISSUE TITLE
Cannot save any configuration via Vue UI after updating to Vue 3.0.3 from 3.0.1 changes in fields don't tracked. Button freezes in refresh state and don't react on changes

### ISSUE THREAD

**Issue by mikefaraponov** [vuejs/vue-cli#2522]
### Version
3.0.3

### Node and OS info
node 8.12.0, npm 6, macos high sierra

### Steps to reproduce
Create basic project via vue ui with default configurations or any other then you cannot change options in configurations. Buttons don't react in configurations tab

### What is expected?
save changes button appear

### What is actually happening?
refresh stucks

**Comment by dannykhoo** [comment]
i'm face the same problem ...

**Comment by CharlesOkwuagwu** [comment]
same problem

**Comment by mikefaraponov** [comment]
Also can reproduce it even in clean docker image node:alpine

**Comment by navicstein** [comment]
Me too!
