### ISSUE TITLE
Can't use lang="postcss" in *.css loaded via style tag

### ISSUE THREAD

**Issue by kovalyovkirill** [vuejs/vue-cli#2523]
### Version
3.0.3

### Reproduction link
[https://github.com/kovalyovkirill/vue-cli-css-file-bug](https://github.com/kovalyovkirill/vue-cli-css-file-bug)

### Node and OS info
Node 10.10.0 / yarn 1.9.4 / Linux 18.04.1 LTS

### Steps to reproduce
1. Init base project
2. Create empty file named some.css file in `components` folder. 
3. Add style tag `<style src="./some.css" lang="postcss" scoped></style>`
4. Type in terminal `yarn run serve`

### What is expected?
Working development server

### What is actually happening?
Failed to compile with 1 errors                             

 error  in ./src/components/some.css?vue&type=style&index=1&id=469af010&lang=postcss&scoped=true&

Module build failed (from ./node_modules/postcss-loader/lib/index.js):
Syntax Error 
(5:1) Unknown word

---
I suppose that is problem about parsing of vue files. But can't find correct solution.

**Comment by sodatea** [comment]
`lang="postcss"` is extraneous. Vue CLI enabled postcss by default.
