### ISSUE TITLE
how can i inject new parameter to templateParameters in vue.config.js

### ISSUE THREAD

**Issue by moshe-pinhasi** [vuejs/vue-cli#2528]
IMPORTANT: Please use the following link to create a new issue:

https://new-issue.vuejs.org/?repo=vuejs/vue-cli

If your issue was not created using the app above, it will be closed immediately.

中文用户请注意：
请使用上面的链接来创建新的 issue。如果不是用上述工具创建的 issue 会被自动关闭。

**Comment by my9074** [comment]
+1

**Comment by hawtim** [comment]
I stuck at this issue for a while, and finally found that is easy, just add your custom params on args[0]
```js
    config.plugin('html').tap(args => {
      args[0].title = 'Mock Title';
      args[0].customParams = customParams;
      return args
    })
```

after that, you can access the value in the HTML via `const customParams = JSON.parse('<%= htmlWebpackPlugin.options.customParams %>');`
