### ISSUE TITLE
Use prompt on a preset level

### ISSUE THREAD

**Issue by arnedesmedt** [vuejs/vue-cli#2529]
### What problem does this feature solve?
Now, if you want to share answers from prompts over multiple vue cli plugins, you need to ask the same question again in each plugin, because prompts are asked on plugin level. Wouldn't it be nice to make this available on preset level, so every plugin in the preset could use the ansers of the preset prompts

### What does the proposed API look like?
add a prompst property to the presets json.

**Comment by sodatea** [comment]
https://cli.vuejs.org/guide/plugins-and-presets.html#remote-presets
You can have a `prompt.js` in a preset repo and then add plugins using the prompt answers in `generator.js`.

**Comment by yuicer** [comment]
@sodatea 
excuse me , but how can i add plugins like `@vue/cli-plugin-eslint` in `generator.js`, i can't find the way to get that done

**Comment by yuicer** [comment]
@sodatea 
thanks ! it does get it done ! 
anyway, will we have this feature later? it just takes extra time to do this in this way

再次感谢～
