### ISSUE TITLE
Network: unavailable

### ISSUE THREAD

**Issue by SaveRockAndRoll** [vuejs/vue-cli#2534]
### Version
3.0.3

### Node and OS info
Node v8.11.3 / yarn 1.9.2 / MacOS 10.13

### Steps to reproduce
最近练习使用Vue CLI 3，根据官方文档配置了一番后，启动出现这种情况，不确定是bug还是我哪里配置错了

### What is expected?
  App running at:
  - Local:   http://127.0.0.1:9999/
  - Network: http://192.x.x.x:9999/

### What is actually happening?
  App running at:
  - Local:   http://127.0.0.1:9999/
  - Network: unavailable

**Comment by tomjdickson** [comment]
You work it out?

**Comment by Somprasit** [comment]
I have the same problem too. need solution

**Comment by Symbolk** [comment]
Though this answer does not helps me, maybe it can be useful:

https://stackoverflow.com/questions/52829363/how-do-i-disable-running-an-app-on-the-local-network-when-using-vue-cli

**Comment by zhoufanglu** [comment]
请问解决了吗，求问是什么问题
网卡只有一个
ipconfig也有信息
host已经改了0.0.0.0

**Comment by zhoufanglu** [comment]
> ### Version
> 3.0.3
> 
> ### Node and OS info
> Node v8.11.3 / yarn 1.9.2 / MacOS 10.13
> 
> ### Steps to reproduce
> 最近练习使用Vue CLI 3，根据官方文档配置了一番后，启动出现这种情况，不确定是bug还是我哪里配置错了
> 
> ### What is expected?
> App running at:
> 
> * Local:   http://127.0.0.1:9999/
> * Network: http://192.x.x.x:9999/
> 
> ### What is actually happening?
> App running at:
> 
> * Local:   http://127.0.0.1:9999/
> * Network: unavailable

请问你解决了吗？

**Comment by danieljbrennan** [comment]
Same problem for me. Has anyone figured this out?

**Comment by danieljbrennan** [comment]
If anyone stumbles across this, I was able to get it working by adding to my vue.config.js `host: '127.0.0.1'`
This didn't solve my actual problem of the proxy server not working locally, but I got it to work with this vue.config.js:
```
module.exports = {
  productionSourceMap: false,
  devServer: {
    host: '127.0.0.1',
    proxy: {
      "^/api": {
        target: "http://127.0.0.1:xxxx/"
      }
    }
  }
};

```

**Comment by daucong** [comment]
Please check in container app with: node -e "console.log(require('default-gateway').v4.sync())", if error run: apt update && apt install -y iproute2. Problem resolve.

**Comment by 0necloud** [comment]
In my case, WMIC was not installed on my system, and I suggest that those facing this issue (especially on Windows 11) check the following:

1. In Settings -> System -> Optional Features, ensure that WMIC is added, and add it if it is not installed.
2. Ensure that Wbem is added to the System PATH. You can do this by searching for "Edit the system environment variables" in Windows Search, click on the "Environment Variables" button, then edit "Path" under "System variables" and add the following: `%SystemRoot%\System32\Wbem`.

Hope this helps.
