### ISSUE TITLE
HMR doesn't seem to be working properly.

### ISSUE THREAD

**Issue by DanielPe05** [vuejs/vue-cli#2543]
### Version
3.0.3

### Node and OS info
Node: v10.7.0, Npm: 6.1.0, MacOs High Sierra 10.13.4

### Steps to reproduce
This is a new project. Here are all my dependencies at the moment:
```
"dependencies": {
    "axios": "^0.18.0",
    "glob-loader": "^0.3.0",
    "lodash": "^4.17.11",
    "vue": "^2.5.17"
  },
  "devDependencies": {
    "@types/jest": "^23.3.2",
    "@vue/cli-plugin-babel": "^3.0.3",
    "@vue/cli-plugin-eslint": "^3.0.3",
    "@vue/cli-plugin-unit-jest": "^3.0.3",
    "@vue/cli-service": "^3.0.3",
    "@vue/eslint-config-prettier": "^3.0.3",
    "@vue/test-utils": "^1.0.0-beta.25",
    "babel-core": "7.0.0-bridge.0",
    "babel-jest": "^23.6.0",
    "lint-staged": "^7.2.2",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.1",
    "vue-cli-plugin-styleguidist": "^0.1.4",
    "vue-template-compiler": "^2.5.17"
  }
```

These are my scripts, and I see the behavior when I simply run `serve` (which I point to that file which is basically to render the components in the library (this is for a library of internal components):
```
  "scripts": {
    "build": "vue-cli-service build --target lib src/main.js --name component-lib",
    "lint": "vue-cli-service lint",
    "prepare": "npm run build",
    "dev": "vue-cli-service serve --open src/__DevSandbox__/index.js",
    "styleguide": "vue-cli-service styleguidist",
    "styleguide:build": "vue-cli-service styleguidist:build",
    "test": "vue-cli-service test:unit",
    "test:watch": "vue-cli-service test:unit --watch"
  }
```

I'm not sure if anyone else is seeing this issue as well but basically adding 
```
devServer: {
    watchOptions: {
      poll: true
    }
  }
```
fixes the issue.

### What is expected?
HMR should be working.

### What is actually happening?
I needed to add 
```
devServer: {
    watchOptions: {
      poll: true
    }
  }
```
In order to get hmr working as expected.

**Comment by LinusBorg** [comment]
This issue exist for any project using webpack, basically. Webpack's file watch mechanism can fail to pick up changes under various circumstances. Their docs say this:

> If watching does not work for you, try out this option. Watching does not work with NFS and machines in VirtualBox.

From my experience maintaining our previous webpack template, there also are or were other factors that could be problematic for *some* users, like file paths with special characters, folders watched by tools like Google Drive / Dropbox, folders within a vm, etc.

There's nothing we can do about this, really.
