### ISSUE TITLE
Pass meta for multi-page build into html-webpack-plugin

### ISSUE THREAD

**Issue by wuservices** [vuejs/vue-cli#2544]
### What problem does this feature solve?
https://github.com/jantimon/html-webpack-plugin supports a `meta` object to inject meta tags into a page. This might be useful for setting robots, viewport, og:image or other meta tags depending on the page in a multi-page build.

By just adding `meta,` on 2 lines of `cli-service/lib/config/app.js` this seems to work fine:

```
      pages.forEach(name => {
        const {
          title,
          meta,
          entry,
          template = `public/${name}.html`,
          filename = `${name}.html`,
          chunks
        } = normalizePageConfig(multiPageConfig[name])
        // inject entry
        webpackConfig.entry(name).add(api.resolve(entry))

        // resolve page index template
        const hasDedicatedTemplate = fs.existsSync(api.resolve(template))
        if (hasDedicatedTemplate) {
          publicCopyIgnore.push(template)
        }
        const templatePath = hasDedicatedTemplate
          ? template
          : fs.existsSync(htmlPath)
            ? htmlPath
            : defaultHtmlPath

        // inject html plugin for the page
        const pageHtmlOptions = Object.assign({}, htmlOptions, {
          chunks: chunks || ['chunk-vendors', 'chunk-common', name],
          template: templatePath,
          filename: ensureRelative(outputDir, filename),
          title,
          meta
        })
```

### What does the proposed API look like?
A config like this should allow you to inject a viewport into a layout. This way you can use the same layout with different meta information, injected in via `vue.config.js`:
```
module.exports = {
  pages: {
    index: {
      entry: 'src/pages/index/main.js',
      meta: {
        viewport: 'width=device-width, initial-scale=1, shrink-to-fit=no'
      }
    }
  }
}
```

**Comment by RaphaelDDL** [comment]
Nice, with sodatea's change, I can finally use `html-webpack-template` correctly. Example:

    pages: {
        index: {
            entry: "src/main.js",
            template: require('html-webpack-template'),
            //specific html-webpack-template options
            appMountId: 'app',
            mobile:  true,
            googleAnalytics: {
                trackingId: '#####',
                pageViewOnLoad: true
            }
        },

Looking forward to 3.1.0 👍
