### ISSUE TITLE
any plan for webpack2 teampate

### ISSUE THREAD

**Issue by yuu2lee4** [vuejs/vue-cli#255]
什么时候有webpack2的template呢

**Comment by egoist** [comment]
https://github.com/vuejs-templates/webpack-simple

**Comment by posva** [comment]
It shouldn't be very hard to update to webpack 2 on your project although we'll probably just wait for webpack 2 to became stable to do the update on the templates

**Comment by allentong** [comment]
Looks like its out now:

https://github.com/vuejs-templates/webpack/commit/49456eb8c53252d6d238cc0e27e3bcfd6732e1a5
