### ISSUE TITLE
the babel-preset-app may be not working for es6 class properties

### ISSUE THREAD

**Issue by luxueyan** [vuejs/vue-cli#2550]
### Version
3.0.1

### Reproduction link
[http://thereisnolink.ok](http://thereisnolink.ok)

### Node and OS info
nodejs v8.10.0 yarn v1.9.4

### Steps to reproduce
定义

### What is expected?
class properties can be right loaded

### What is actually happening?
throw a error 

![image](https://user-images.githubusercontent.com/1555552/45728466-b6545b80-bbfa-11e8-9714-01e577364ac3.png)

**Comment by LinusBorg** [comment]
Please provide a reproduction, as explained in the issue template.

**Comment by LinusBorg** [comment]
@sodatea I think the Class properties transform is one of 3 we inlcude with @vue/babel-preset-app:

https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/babel-preset-app

**Comment by sodatea** [comment]
Do not use `includes.add`, use [`transpileDependencies`](https://cli.vuejs.org/config/#transpiledependencies) instead.

Because we've added a default `exclude` condition to `babel-loader` to exclude `node_modules`.
https://webpack.js.org/configuration/module/#rule-conditions
> When using multiple conditions, all conditions must match.

**Comment by luxueyan** [comment]
Oh! vue-cli(3.0.0-beta.6) depend on webpack3.,vue-cli(3.0.1) depend on webpack4。 Maybe that webpack4 match strategy is different from webpack3？
