### ISSUE TITLE
Error when I use async/await:  regenerator-runtime/runtime was not found

### ISSUE THREAD

**Issue by veah** [vuejs/vue-cli#2551]
### Version
3.0.3

### Reproduction link
[https://github.com/veah/blogs](https://github.com/veah/blogs)

### Node and OS info
Node 8.9.4 / NPM 5.8.0/ Mac OS

### Steps to reproduce
1. download
2. npm install
3. npm run serve

### What is expected?
Everything goes well

### What is actually happening?
Error in  command line： 
```
This dependency was not found:

regenerator-runtime/runtime in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js&
```

---
I thought regenerator-runtime has already been installed in ./node_modules/@vue/babel-preset-app. Shouldn't this regenerator-runtime be found in @vue/babel-preset-app ?

**Comment by sodatea** [comment]
Removing `node_modules` & `package-lock.json` and rerunning `npm install` fixes this issue.

**Comment by veah** [comment]
> Removing `node_modules` & `package-lock.json` and rerunning `npm install` fixes this issue.

Great, it works, thx

**Comment by smelike** [comment]
RT, this issue happen suddently.  It is so weired.

**Comment by mhluska** [comment]
Yeah, nuking `package-lock.json` and updating all versions just to fix this probably isn't the best idea. Not sure why that is so upvoted.

**Comment by mfickett** [comment]
Deleting `node_modules` and `package-lock.json` did not fix it for me. I'm using `pnpm`, maybe its stricter handling of dependencies caused that not to work? I did `pnpm i --save regenerator-runtime` and that fixed it (I tried `pnpm install --save regenerator-runtime/runtime` as indicated by the error message but that failed to install).
