### ISSUE TITLE
create project fail by vue ui

### ISSUE THREAD

**Issue by BingKui** [vuejs/vue-cli#2554]
### Version
3.0.3

### Node and OS info
Node 10.10.0 / NPM 6.4.1/ MacOS 10.13.6

### Steps to reproduce
Create Project

- select all feature, next step
- use class-style, use babel, use history mode for router
- select less, select ESLint   Airbnb config, lint on save & lint and fix on commit
- unit test select Jest
- E2E test select Cypress
- click create project button

### What is expected?
project created success

### What is actually happening?
Running completion hooks...error: '@vue/test-utils' should be listed in the project's dependencies, not devDependencies (import/no-extraneous-dependencies) at vueDemo/tests/unit/example.spec.ts:1:1:
> 1 | import { shallowMount } from '@vue/test-utils';
    | ^
  2 | import HelloWorld from '@/components/HelloWorld.vue';
  3 |
  4 | describe('HelloWorld.vue', () => {

**Comment by BingKui** [comment]
No error will be reported if you do not use the test tool

**Comment by jacekkarczmarczyk** [comment]
This looks like a quite recent bug, afair I haven't seen it in 3.0.0 or 3.0.1
