### ISSUE TITLE
vue-cli在配置代理之后报错：Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by caozhong1996** [vuejs/vue-cli#2555]
### Version
3.0.3

### Node and OS info
Node8.11.4 / npm5.6.0 / Windows 7

### Steps to reproduce
1使用vue-cli 3.03搭建项目
2在vue.config.js里面配置devServer

### What is expected?
重新运行npm run serve之后报错：Tapable.plugin is deprecated. Use new API on `.hooks` instead，查阅资料之后更新了extract-text-webpack-plugin插件到最新版，npm i -D extract-text-webpack-plugin@next，依旧无法解决问题

### What is actually happening?
vue-cli配置代理之后报错：Tapable.plugin is deprecated. Use new API on `.hooks` instead

---
希望可以帮忙解决，万分感谢！

**Comment by sodatea** [comment]
能否提供一下具体配置或者项目仓库？
Vue CLI 并没有用到 extract-text-webpack-plugin，应该跟这个无关。
