### ISSUE TITLE
Does webpack template currently support jsx in render functions?

### ISSUE THREAD

**Issue by kennetpostigo** [vuejs/vue-cli#256]
I was wondering if the webpack template supports jsx in the render function as it wasn't working for me when I attempted to use it.

**Comment by LinusBorg** [comment]
Not our of the box. But following the install instructions for [babel-plugin-transform-vue-jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx) will be enough to enable it.

**Comment by savokiss** [comment]
Found an official repo that supports JSX with almost zero config : https://github.com/vuejs/babel-preset-vue-app 😃
