### ISSUE TITLE
 vue invoke error

### ISSUE THREAD

**Issue by aymonYU** [vuejs/vue-cli#2562]
### Version
3.0.3

### Node and OS info
yarn

### Steps to reproduce
i create a vue-cli plugin,and a generator in it , and i run vue-cli-service invoke test ,the generator not worlk in exist project

like this

![image](https://user-images.githubusercontent.com/16128068/45820924-88fecf00-bd1a-11e8-9b52-ab8f75ff8a3e.png)
the exist package.json   file in my project do not change 

![image](https://user-images.githubusercontent.com/16128068/45821061-e135d100-bd1a-11e8-907d-f003e36a16ca.png)

### What is expected?
vue invoke generator can change exist file

### What is actually happening?
it not work

**Comment by sodatea** [comment]
It's `vue invoke`, not `vue-cli-service invoke`.
