### ISSUE TITLE
Can you provide such a way?

### ISSUE THREAD

**Issue by zhangenming** [vuejs/vue-cli#2563]
### What problem does this feature solve?
![2018920-221327](https://user-images.githubusercontent.com/21235555/45824536-cc5d3b80-bd22-11e8-839d-917cc5150038.jpg)

vue.runtime.esm.js?2b0e:3370  
that is a single file
can we use vue from 'node_modules\vue\src' that  Multiple file?
thanks

### What does the proposed API look like?
none

**Comment by sodatea** [comment]
No.
Vue 2.x uses a quite customized compilation pipeline to build the final output so it's incompatible with the app build config.
