### ISSUE TITLE
css url() relative path can't build as expected

### ISSUE THREAD

**Issue by CXY037** [vuejs/vue-cli#2564]
### Version
3.0.3

### Node and OS info
v8.11.2 / yarn 1.9.4 / debian

### Steps to reproduce
1. background: url("./assets/back.png") no-repeat;
2.assetsDir: 'vassets/mobile',
   baseUrl: '/'

### What is expected?
build finish:
 background: url("/vassets/mobile/img/back.cec8de61.png") no-repeat;

### What is actually happening?
background:url(../../../vassets/mobile/img/back.cec8de61.png) no-repeat;

**Comment by CXY037** [comment]
@sodatea the file exist. I now hack the css.js solve the problem.

**Comment by CXY037** [comment]
I change the below file.
// use relative publicPath in extracted CSS based on extract location
    /* const cssPublicPath = process.env.VUE_CLI_BUILD_TARGET === 'lib'
      // in lib mode, CSS is extracted to dist root.
      ? './'
      : '../'.repeat(
        extractOptions.filename
            .replace(/^\.[\/\\]/, '')
            .split(/[\/\\]/g)
            .length - 1
      ) */
    const cssPublicPath = '/'

**Comment by CXY037** [comment]
@sodatea I need the output is absolute address. Because my vue is working with yii2. The assets separate with the html.

**Comment by sodatea** [comment]
Then you might need to place the assets in the `public` folder and reference them as absolute paths.
For more details: https://cli.vuejs.org/guide/html-and-static-assets.html#static-assets-handling

**Comment by CXY037** [comment]
@sodatea I know the problem that I am multi-page-app.  The file 'css.js' 'extractOptions.filename' has wrong depth. Because the [name] has one depth.
