### ISSUE TITLE
Maximum call stack size exceeded when creating new vue cli 3 project

### ISSUE THREAD

**Issue by ilrock** [vuejs/vue-cli#2567]
### Version
3.0.3

### Node and OS info
Node 8.12.0 / npm 6.4.1 / OSx 10.13.4

### Steps to reproduce
vue create project_name

### What is expected?
Project being created

### What is actually happening?
The following error:

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ilrock/.npm/_logs/2018-09-21T12_44_37_935Z-debug.log
 ERROR  command failed: npm install --loglevel error

**Comment by timfcsm** [comment]
i have same issue 
node 8.11.4 / npm 5.6.0 / vue  3.0.3 / win10

**Comment by sodatea** [comment]
Can't reproduce. Could you provide a more detailed error log?

**Comment by fer22f** [comment]
Here are two:

* [When trying to create a new project](https://github.com/vuejs/vue-cli/files/2492600/install.log)
* [Trying to add vuetify to a project created with yarn (can I use yarn here?)](https://github.com/vuejs/vue-cli/files/2492599/add_vuetify.log)

**Comment by sodatea** [comment]
```
4780 http fetch GET 200 https://registry.npmjs.org/@webassemblyjs%2fwast-printer 2ms (from cache)
4781 silly fetchPackageMetaData error for @webassemblyjs/wast-printer@1.7.8 Unexpected end of JSON input while parsing near '..."}},"1.7.8":{"name":"'
```

Network issue or broken cache. Try to run `npm cache verify` and then run installation again.

**Comment by fer22f** [comment]
Ok yea, broken cache. `npm cache clean --force` worked. And they advertise this cache as "self-healing", mhm

**Comment by VadimIzmalkov** [comment]
Same issue

`npm cache clean --force` does not help

![default](https://user-images.githubusercontent.com/6684336/49364435-fd77c600-f6ec-11e8-93bc-21ee4be64818.png)

![default](https://user-images.githubusercontent.com/6684336/49364503-25672980-f6ed-11e8-9264-ae8c7bd3128a.png)

![default](https://user-images.githubusercontent.com/6684336/49364556-3fa10780-f6ed-11e8-8d61-a63bf10bca4b.png)

![default](https://user-images.githubusercontent.com/6684336/49364579-4b8cc980-f6ed-11e8-9475-df0d39b0ae9d.png)
