### ISSUE TITLE
Import css error in a project created with yarn workspaces

### ISSUE THREAD

**Issue by mqhe2007** [vuejs/vue-cli#2572]
### Version
3.0.3

### Reproduction link
[https://github.com/mqhe2007/error-yarn-workspaces](https://github.com/mqhe2007/error-yarn-workspaces)

### Node and OS info
Node 8.11.2/ yarn 1.9.4 / macOS 10.13.6

### Steps to reproduce
in project root directory run:
1. yarn install
2. yarn workspace frame run serve

### What is expected?
no error

### What is actually happening?
![image](https://user-images.githubusercontent.com/13450661/45914017-1eac7280-be71-11e8-961d-3c56f492fe38.png)

---
used [iView ui](https://github.com/iview/iview)

**Comment by sodatea** [comment]
As a workaround, add these lines to `vue.config.js`

```js
module.exports = {
  css: {
    loaderOptions: {
      postcss: {
        path: __dirname
      }
    }
  }
}
```

**Comment by mqhe2007** [comment]
@sodatea 果然是配置问题，但是当时没有找到具体改哪个地方，非常感谢！Thank you very much!

**Comment by EnSabanNur** [comment]
@sodatea, you just saved me from a major migraine after running around in circles trying to solve this issue. Thank you so much 👍
