### ISSUE TITLE
VUE UI unable to configure eslint

### ISSUE THREAD

**Issue by 2mod** [vuejs/vue-cli#2575]
### Version
3.0.3

### Node and OS info
npm 3.5.2 / kubuntu 18.04 / @vue/cli-plugin-eslint 3.0.3 / eslint 5.6.0

### Steps to reproduce
sudo vue create test
sudo vue ui
navigate: configuration -> eslint
then: try to change any of the settings in either the general and/or rules tab

### What is expected?
setting should change
eg: "selected config" from "essential" to "recommended"

### What is actually happening?
the settings wont change, no matter if its a drop down or checkbox

---
.eslintrc.js
-----------------------------------------------------------------------------------------------------------------------
module.exports = {
  root: true,
  env: {
    node: true
  },
  'extends': [
    'plugin:vue/essential',
    '@vue/standard'
  ],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off'
  },
  parserOptions: {
    parser: 'babel-eslint'
  }
}

**Comment by sodatea** [comment]
Fixed in v3.0.4
