### ISSUE TITLE
Unsupported platform for fsevents@1.2.4

### ISSUE THREAD

**Issue by whatTheHellDie** [vuejs/vue-cli#2578]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@vue\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by whatTheHellDie** [comment]
no support win10

**Comment by smares** [comment]
It's only a warning, fsevents only works on Linux and macOS.
