### ISSUE TITLE
Add support for nested tslint configuration files

### ISSUE THREAD

**Issue by MantasPauliukonis** [vuejs/vue-cli#2579]
### What problem does this feature solve?
Suppose I want to have a separate or albeit slightly different `tslint.json` config for my `tests` folder, currently it's not possible because config is only read from the project root directory.

### What does the proposed API look like?
Nested `tslint.json` would be read and rules would be applied from the closest `tslint.json` file, starting from the file where linting is checked.

**Comment by sodatea** [comment]
Now that TSLint [is officially deprecated](https://github.com/palantir/tslint/pull/4906/files), TSLint support will be [fully dropped in the next major version](https://github.com/vuejs/vue-cli/pull/5065); as for the current major version, no more bug fixes or features will be implemented except for security reasons. So I'm closing this issue now.
