### ISSUE TITLE
vue configuration when behind proxy

### ISSUE THREAD

**Issue by tomvdk** [vuejs/vue-cli#258]
Hi,

We are having lots of trouble configuring the vue-cli. We are behind a proxy and get the following error when installing a template:

**vue-cli · Failed to download repo vuejs-templates/simple: unable to verify the first certificate**

We think this is due to our proxy and misconfiguration of our gitconfig. Also, our proxy has a certificate configured. Does anyone know, how to troubleshoot this because I find this very cumbersome. 

Our .gitconfig file looks like this:
```
# This is Git's per-user configuration file.
[user]
# Please adapt and uncomment the following lines:
name = myusername
email = myemail@domain.com
[http] 
sslVerify = false 
	proxy = http://<username>:<password>@<proxy>:8080
[https] 
[url "https://github.com/"]
insteadOf = git://github.com/

```
Thanks a lot in advance.

**Comment by posva** [comment]
It has actually nothing to do with your gitconfig. Your proxy is actually an insecure man in the middle... Not verifying the ssl certificate is a bad idea.

To debug further this problem you should check https://github.com/flipxfx/download-git-repo/blob/master/package.json and its dependencies. That's what vue-cli uses under the hood to fetch the template

**Comment by tomvdk** [comment]
Thanks a lot for pointing this out. I'll investigate the dependencies.

**Comment by Akryum** [comment]
`download-git-repo` should allow passing options to `download`/`got` so we could use [these proxy settings](https://github.com/sindresorhus/got#proxies).

**Comment by Jecoms** [comment]
I'm able to clone from git manually, but when trying to vue init a template, I get "unable to get local issuer certificate." I've already added our cert similar to this [vscode/git issue method](https://blogs.msdn.microsoft.com/phkelley/2014/01/20/adding-a-corporate-or-self-signed-certificate-authority-to-git-exes-store/) and I've added our proxy in the config for node/git. 

Is there an avenue to config vue-cli or the under-the-hood download-git-repo to cooperate with our proxy?

**Comment by traeblain** [comment]
For anyone still having issues with this here's a band-aid fix:

```bash
git clone https://github.com/vuejs-templates/simple ~/.vue-templates/simple
vue init simple my-project --offline
cd my-project
npm install
npm run dev
```

So like the commenters git works fine by itself, so clone the template you want into your `HOME/.vue-templates` folder, then use the --offline switch to skip the non-functioning git clone that vue-cli uses.  Then npm install works just fine and you are ready to go.

_(NOTE: If you are on Windows machine using cmd, you'll need to change your folder commands appropriately.)_

**Comment by niallobrien** [comment]
@traeblain Thanks for sharing.
Windows example: `git clone https://github.com/nuxt-community/starter-template.git C:\Users\niallobrien\.vue-templates\nuxt-starter-template` - just swap out the username for example

**Comment by grunlowen2** [comment]
Thanks! Worked for me on my corporate Windows machine. Had to set some env variables, like HTTPS_PROXY to point at our proxy server, but after that it worked.

**Comment by artzub** [comment]
Maybe it will be useful someone
```
npm_config_strict_ssl=false vue init webpack my-project
```

**Comment by kreig303** [comment]
@yyx990803 not sure why you're closing this out... it is an issue that is not resolved.  The workaround @traeblain specifies is the only method for some of us using corp proxies with man-in-the-middle certs.

**Comment by yyx990803** [comment]
@kreig303 unfortunately, we will no longer be adding new features to vue-cli 2.x. We will try to address this if the similar issue persists in 3.0.

**Comment by Mojoejojo** [comment]
hi @traeblain, where can I find the HOME/.vue-templates folder?

**Comment by traeblain** [comment]
@Mojoejojo you may have to create it, or let git create it when you clone.  

If you are on Linux create `~\.vue-templates` if you are on Windows create `C:\Users\USER\.vue-templates`  where USER is specific to your user folder.

**Comment by netqyq** [comment]
this works 
```
git clone https://github.com/vuejs-templates/webpack ~/.vue-templates/webpack
vue-init --offline webpack nongcaiyuan-front
cd my-project
npm install
npm run dev
```

**Comment by Gargo** [comment]
WTF? The issue still exists - why not to fix it?

**Comment by Gargo** [comment]
In my case helped a strange solution - I updated git and disabled Kaspersky mall Office Security (I work on windows)

**Comment by charlesx163** [comment]
@traeblain

> For anyone still having issues with this here's a band-aid fix:
> 
> ```shell
> git clone https://github.com/vuejs-templates/simple ~/.vue-templates/simple
> vue init simple my-project --offline
> cd my-project
> npm install
> npm run dev
> ```
> 
> So like the commenters git works fine by itself, so clone the template you want into your `HOME/.vue-templates` folder, then use the --offline switch to skip the non-functioning git clone that vue-cli uses. Then npm install works just fine and you are ready to go.
> 
> _(NOTE: If you are on Windows machine using cmd, you'll need to change your folder commands appropriately.)_

this works

**Comment by felix-cao** [comment]
> this works
> 
> ```
> git clone https://github.com/vuejs-templates/webpack ~/.vue-templates/webpack
> vue-init --offline webpack nongcaiyuan-front
> cd my-project
> npm install
> npm run dev
> ```

This works
