### ISSUE TITLE
Issue with chunk count limiting and compression plugins

### ISSUE THREAD

**Issue by ChadTaljaardt** [vuejs/vue-cli#2581]
### Version
3.0.3

### Reproduction link
[https://github.com/ChadTaljaardt/TestRepo](https://github.com/ChadTaljaardt/TestRepo)

### Node and OS info
node v10.10.0 / yarn 1.9.4 / OSX 10.14

### Steps to reproduce
```
git clone https://github.com/ChadTaljaardt/TestRepo.git
cd TestRepo
yarn
yarn build
``` 

### What is expected?
Compressed with a smaller chunk count.

### What is actually happening?
Error 

```
/Users/chadtaljaardt/Documents/Sites/testerrrr/node_modules/@gfx/zopfli/dist/libzopfli.js:1
(function (exports, require, module, __filename, __dirname) { var Module=typeof Module!=="undefined"?Module:{};const base64=require("base64-js");const base64EncodedBinary=require("./libzopfli-wasm");var Module={};Module.noInitialRun=true;Module.wasmBinary=base64.toByteArray(base64EncodedBinary);var moduleOverrides={};var key;for(key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}Module["arguments"]=[];Module["thisProgram"]="./this.program";Module["quit"]=(function(status,toThrow){throw toThrow});Module["preRun"]=[];Module["postRun"]=[];var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONM
```

---
Im not sure if this is a Vue cli 3 specific error, but i thought this would work and it doesn't seem to be.

**Comment by LinusBorg** [comment]
Hi @ChadTaljaardt, 

Your reproduction link is broken. Can you take a look and fix it so we can use the reproduction?

**Comment by ChadTaljaardt** [comment]
@LinusBorg Fixed, it was a private repo by mistake 👍

**Comment by ChadTaljaardt** [comment]
Any update on this?

**Comment by LinusBorg** [comment]
Sorry, this got a bit burried. Will try and take a look asap.

**Comment by sodatea** [comment]
Seems a bug in webpack as the error disappears once I remove the `[contenthash:8]` part from `output.filename`.
Please raise an issue there. (There was a similar issue for earlier versions of webpack https://github.com/webpack/webpack/issues/7185 but I'm not sure if they are related)
