### ISSUE TITLE
import umd module is undefined except file in node_modules

### ISSUE THREAD

**Issue by yangblink** [vuejs/vue-cli#2586]
### Version
3.0.1

### Reproduction link
[https://github.com/yangblink/vue-cli-umd-test](https://github.com/yangblink/vue-cli-umd-test)

### Node and OS info
Node v9.3.0 / npm 6.0.1/ macOS 10.13.1

### Steps to reproduce
use vue-cli create a default project, and import a simple umd module `umd.js`,  

**umd.js**

```javascript
/* eslint-disable */
(function webpackUniversalModuleDefinition(root, factory) {
  if(typeof exports === 'object' && typeof module === 'object')
    module.exports = factory();
  else if(typeof define === 'function' && define.amd)
    define("bxs", [], factory);
  else if(typeof exports === 'object')
    exports["bxs"] = factory();
  else
    root["bxs"] = factory();
})(window, function() {
  return 'umd';
});
```

when the file in `/node_modules` it's work fine,
copy it to other folder except `/node_modules`, it's undefined

```javascript
import localumd from './umd.js'
import moduleumd from '../node_modules/umd.copy.js'
console.log(localumd);  // undefined
console.log(moduleumd); // umd
```

### What is expected?
umd module can be recognize in any floder

### What is actually happening?
umd module can be recognize only in path `/node_modules`

**Comment by yangblink** [comment]
It's because of the helpers config of `@@babel/plugin-transform-runtime`  in `@vue/app`
```javascript
plugins: [
  [
    '@babel/plugin-transform-runtime', { helpers: ture }
  ]
]
```

`helpers: true` will inject  some top at the top like follow

![image](https://user-images.githubusercontent.com/2688285/46398644-3a90fd80-c728-11e8-8b89-38e6f5e2a94e.png)

webpack will parse it as **Harmony**

**Comment by q569608465** [comment]
Is this problem solved? How to solve it?

**Comment by prettyCoders** [comment]
@yangblink  i have the same problem in my project , can you help me to solve the problem .

**Comment by yangblink** [comment]
> @yangblink i have the same problem in my project , can you help me to solve the problem .

replace `babel.config.js ` below
```
module.exports = {
  presets: [
    '@vue/app'
  ],
  ignore: [ './src/umd.js' ]
}
```
just ignore the umd module file

**Comment by erisman20** [comment]
This error wont occur if you set useBuiltIns to 'entry' in your babel config. That is what determines if helpers @yangblink mentioned are included.

Does anyone have a better solution than that?

**Comment by huyansheng3** [comment]
vue cli default import umd which not in node_module will occur some error. Maybe it should add some tip for user ?
