### ISSUE TITLE
Vue styled components not getting compiled to web components 

### ISSUE THREAD

**Issue by kushalmahajan** [vuejs/vue-cli#2587]
### Version
3.0.3

### Reproduction link
[https://github.com/kushalmahajan/vuejs_form.git](https://github.com/kushalmahajan/vuejs_form.git)

### Node and OS info
8.12.0, npm 6.4.1 and Windows 10

### Steps to reproduce
1.git clone https://github.com/kushalmahajan/vuejs_form.git
 default branch must be styled_components
2. vue build--target wc--name my-custom-element./ src / main.js
3. run the demo.html and there is no styling to header displayed.

### What is expected?
Styling should be applied to web component generated

### What is actually happening?
No styles getting applied.

**Comment by LinusBorg** [comment]
`styled-components` manage their styles themselves - and they inject them as global styles into the page head. you should be able to find them in the page's head if i understand what they do correctly.

However, these styles won't apply to a component's shadow DOM, which is designed to be independent from the global styles.

So IMHO this is expected behanviour, or in other words: the ways that `vue-styled-components` and web components handle their styles are incompatible.
