### ISSUE TITLE
Vue UI - Settings are read only

### ISSUE THREAD

**Issue by botmaster** [vuejs/vue-cli#2588]
### Version
3.0.3

### Node and OS info
Node 8.11.4 / npm: 5.6.0 / macOS 10.13.6

### Steps to reproduce
Start 'vue ui'
Go to 'project settings > Vue CLI > General settings

### What is expected?
Be able to interact with form inputs 

### What is actually happening?
Form inputs are read only. Unable to change settings.

**Comment by sodatea** [comment]
Fixed in v3.0.4
