### ISSUE TITLE
Error status 128 restoring a public github project

### ISSUE THREAD

**Issue by ingodahn** [vuejs/vue-cli#2591]
### Version
3.0.1

### Reproduction link
[https://github.com/ingodahn/testanalyzer.git](https://github.com/ingodahn/testanalyzer.git)

### Node and OS info
Node 8.11.2 / npm 5.6.0 / Windows 10

### Steps to reproduce
vue create --preset ingodahn/testanalyzer --clone testanalyzer 

### What is expected?
Clone success

### What is actually happening?
 Fetching remote preset ingodahn/testanalyzer...
 ERROR  Failed fetching remote preset ingodahn/testanalyzer:
 ERROR  Error: 'git clone' failed with status 128
Error: 'git clone' failed with status 128
    at ChildProcess.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\git-clone\index.js:33:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)

---
I was trying to follow https://cli.vuejs.org/guide/creating-a-project.html#vue-create. Detailed examples of how to use vue create options might be helpful.

**Comment by ngopal1995** [comment]
The file `preset.json` containing the preset data is required in the repo. You are missing this.

Try with `vue create --preset ingodahn/testanalyzer testanalyzer`, since this is not a private repo.

**Comment by sodatea** [comment]
Can't reproduce. The only error I've got is `Error: remote / local preset does not contain preset.json!`.

Alos, you don't need the `--clone` option to download a public repo. Direct HTTP download would be faster.
