### ISSUE TITLE
element 升级到vue-cli以后，table表格横向滚动条没有了，且打包以后也没有

### ISSUE THREAD

**Issue by LuckyTaoTao** [vuejs/vue-cli#2592]
### Version
3.0.3

### Node and OS info
10.10.0

### Steps to reproduce
升级到vue-cli3.0以后，对于element table组件并不是特别友好，出现了横向滚动条无法显示的问题，导致不能拖动

### What is expected?
尽快修复

### What is actually happening?
尽快修复

**Comment by sodatea** [comment]
请提供复现。就目前描述看起来不大可能是 Vue CLI 的问题。

**Comment by sodatea** [comment]
1. 你的链接是坏的。
2. 建议定位到详细问题之后再去合适的 repo 提 issue。就目前描述来看样式问题的可能性比较大，请检查是否有样式覆盖或者引入顺序之类的问题。
