### ISSUE TITLE
vue add element后编译报错，package.json文件添加了element-ui，但node_modules中并没有下载

### ISSUE THREAD

**Issue by Archmee** [vuejs/vue-cli#2593]
### Version
3.0.3

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Node and OS info
node v8.11.4, npm 5.6.0, win10

### Steps to reproduce
vue create myprojct
cd myprojct
vue add element
npm run serve

### What is expected?
element-ui被正确安装

### What is actually happening?
node_modules中并没有下载element-ui

---
重新手动运行npm命令：npm i element-ui -S 就可以解决了，那用vue add的意义何在

**Comment by sodatea** [comment]
vue add 是用于加 plugin 的部署加普通依赖用的，请仔细看文档
