### ISSUE TITLE
Failed to resolve babel-loader

### ISSUE THREAD

**Issue by forehalo** [vuejs/vue-cli#2599]
### Version
3.0.4

### Node and OS info
Node 10.8.0 / yarn 1.9.4 / macOS 10.13.6

### Steps to reproduce
vue create testing
select the all given plugins
yarn run build

### What is expected?
generate built files

### What is actually happening?
Failed to resolve loader: babel-loader
You may need to install it.

**Comment by sodatea** [comment]
Both `@vue/cli-plugin-babel` & `@vue/cli-plugin-e2e-cypress` depends on `babel-loader`, but somehow yarn does not hoist the common dependency and installs them in a nested folder instead.
For now you can manually run `yarn add -D babel-loader` to solve the problem.

**Comment by sodatea** [comment]
Possible related:
https://github.com/yarnpkg/yarn/issues/5807
https://github.com/yarnpkg/yarn/issues/5823

**Comment by frederikhors** [comment]
Same here!
