### ISSUE TITLE
error while create a demo

### ISSUE THREAD

**Issue by limbodan** [vuejs/vue-cli#2600]
### Version
3.0.2

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue-cli&lang=zh-cn](https://new-issue.vuejs.org/?repo=vuejs/vue-cli&lang=zh-cn)

### Node and OS info
node 8.11.3

### Steps to reproduce
vue create demo

✨  Creating project in E:\dev\hello-world.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

'yarn' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
 ERROR  command failed: yarn

### What is expected?
create a demo success

### What is actually happening?
error

**Comment by limbodan** [comment]
i create demo according to the official document

**Comment by limbodan** [comment]
the error is : 'yarn' is not recognized as an internal or external command, operable program or batch file.

**Comment by sodatea** [comment]
Did you installed yarn after the current cmd window is opened? If that is the case, try to close and reopen the cmd window.
https://github.com/yarnpkg/yarn/issues/2504#issuecomment-320648293

**Comment by LinusBorg** [comment]
Not related to vue-cli
