### ISSUE TITLE
期望可以设置htmlWebpackPlugin中的模板为pug模板

### ISSUE THREAD

**Issue by fengxinming** [vuejs/vue-cli#2601]
### What problem does this feature solve?
目前的index.html和多页配置的扩展名.html都是写死的，这样不方便迁移项目。因为项目初期都是用pug开发

### What does the proposed API look like?
可以增加一个设置模板扩展名的参数。比如：.ext或者.extname之类的

**Comment by fengxinming** [comment]
@sodatea you couldn't close this issues, because the last issues you didn't resolve and vue-cli 3.0 still does't support pug template

**Comment by sodatea** [comment]
```
yarn add -D pug-loader
```


```js
// vue.config.js
module.exports = {
  pages: {
    app: {
      entry: resolve('./src/main.js'),
      template: 'public/index.pug',
      filename: 'index.html',
      title: 'vuecli3.0'
    }
  },
  chainWebpack: config =>
    config.module
      .rule('pug')
      .test(/\.pug$/)
        .uses
          .delete('pug-plain-loader')
          .end()
        .use('pug-loader')
          .loader('pug-loader')
}
```

**Comment by sodatea** [comment]
It will be false when using webpack inline loader syntax like `template: '!!pug-plain-loader!public/index.pug'`. This issue is being tracked at https://github.com/vuejs/vue-cli/issues/2697

But with the above-mentioned config you should have been able to use `.pug` files as templates.

**Comment by fengxinming** [comment]
@sodatea  what's the difference between `pug-plain-loader` and `pug-loader`?

**Comment by sodatea** [comment]
`pug-plain-loader` compiles a pug file to a plain html string while `pug-loader` compiles it to a js module. 

https://github.com/yyx990803/pug-plain-loader/blob/d2bc7c4ee84096fe94dd0c8778f3f6d860c2d6c3/index.js#L13

https://github.com/pugjs/pug-loader/blob/99e7e1240e312d735f8de3e40e70ca5adb6ace7d/index.js#L159-L160
