### ISSUE TITLE
当配置Assets directory为url时候（比如cdn url），build命令会一直执行，无报错无结束

### ISSUE THREAD

**Issue by paul-xia** [vuejs/vue-cli#2606]
### Version
3.0.4

### Reproduction link
[https://github.com/paul-xia/vue-cli-issue](https://github.com/paul-xia/vue-cli-issue)

### Node and OS info
node8.9.3/5.5.1/windows 10

### Steps to reproduce
vue ui
change Assets directory to a link url
run build

### What is expected?
编译成功

### What is actually happening?
一直编译，无报错无成功

**Comment by sodatea** [comment]
请仔细看文档：
https://cli.vuejs.org/zh/config/#assetsdir
> 放置生成的静态资源 (js、css、img、fonts) 的 (相对于 outputDir 的) **目录**。

`assetsDir` 应该是一个相对路径，不能是 url
