### ISSUE TITLE
outputDir recursively repeating endlessly on build --watch

### ISSUE THREAD

**Issue by vhanla** [vuejs/vue-cli#2615]
### Version
3.0.4

### Node and OS info
Node 10.0.0 / yarn 1.10.0 / Windows 10

### Steps to reproduce
1. Create a TypeScript Vue project using Vuecli, not matter which.
2. Configure vue.config.js outputDir to **'public/dist'**
3. Run node cli-service build --watch --mode production
4. public directory will create dist directories with contents repeatedly

### What is expected?
Just stop compiling, wait changes in vue source code and update (compile again).

### What is actually happening?
Keeps compiling endlessly. 
It creates `dist` directory inside `public` recursively. i.e. **public/dist/dist/dist/dist/dist/...** and so on.

---
I tried to chainWebpack the plugin copy.

```javascript
chainWebpack: config => {
    config.plugin('copy')
      .use(require('copy-webpack-plugin'),[[{
        from: __dirname + '/public',
        to: 'public/dist',
        toType: 'dir',
        ignore: ['index.html', '.DS_Store', 'dist']
      }]])
  }
```

It stopped copying dist directory. However, PWA plugin kept creating many precache-manifest.* files, also output was showing incorrect information, like:

`Assets: public/dist/public/dist/public/dist/js/app.js`

Still, it was compiling endlessly.

NOTICE: if outputDir is set to "public" directory, i.e. without subdirectories, it works fine.

Sample vue.config.js file:

```javascript
module.exports = {
  // options...
  outputDir: 'public/dist/',
  baseUrl: process.env.NODE_ENV === 'production' ? '/dist/' : '/',
  filenameHashing: false,
  configureWebpack: {
    resolve: {
      alias: {
        '@': __dirname + '/resources/src'
      }
    },
    entry: {
      app: './resources/src/main.ts'
    },
  }
}
```

**Comment by LinusBorg** [comment]
Why would you want to do that?

**Comment by vhanla** [comment]
Sorry, I was incorrectly "modifying" the default static assets directory (`public`), it was copying again and again because of that (output directory was the same as static assets directory) since I modified `outputDir` to `public` and previous `chainWebpack` was not correct.

```js
chainWebpack: config => {
  config.plugin('copy')
  .tap(args => [[{
    from: __dirname + '/mycustom/staticassetspath',
    to: __dirname + '/public',
    toType: 'dir'
  }]])
}
```
