### ISSUE TITLE
Prefetch links presents in html even if prefetch plugin deleted

### ISSUE THREAD

**Issue by KleinMaximus** [vuejs/vue-cli#2616]
### Version
3.0.4

### Node and OS info
Node 10.10.0 / yarn 1.9.4

### Steps to reproduce
```
// Resulting VUE config
module.exports = {
  chainWebpack: (config) => {
    config.plugins.delete('prefetch');
  },
};

```

### What is expected?
No any `<link rel="prefetch" href="/js/XXX.js">` of async components in html head section.

### What is actually happening?
Tags `<link rel="prefetch" href="/js/XXX.js">` present in head.

### Notes
This code disappears from the configuration (vue inspect):
```
new PreloadPlugin({
  rel: 'prefetch',
  include: 'asyncChunks'
}),
```
The strange thing is that even in the absence of a plugin in `vue inspect`, `<link>` tags still appear in html.

**Comment by KleinMaximus** [comment]
In issue #979 described the config I applied the method to disable prefetch, but it didn't work.

**Comment by KleinMaximus** [comment]
I found my mistake. I used the third-party package features incorrectly.

**Comment by yangning10000** [comment]
may I ask which third-party package features did you use incorrectly? I am currently facing the same issue

**Comment by yangning10000** [comment]
did you use server side rendering for you project?

**Comment by KleinMaximus** [comment]
@yangning10000, if this question to me, then Yes

**Comment by yangning10000** [comment]
@KleinMaximus yeah I use vue-cli-plugin-ssr. in createBundleRenderer, there seems to be a inject: false which suppose to control the behavior but nothing works. I'm so confused right now
