### ISSUE TITLE
cli-plugin-pwa uses pwa.name from manifest.json but pwa.themeColor not.

### ISSUE THREAD

**Issue by frederikhors** [vuejs/vue-cli#2620]
### What problem does this feature solve?
`cli-plugin-pwa` uses in `vue.config.js`:

- `pwa.name` from `/public/manifest.json` but
- `pwa.themeColor` not.

**Why?**

**Comment by LinusBorg** [comment]
You seem to want to submit a bug report, not a feature request. 

Please use the issue helper and create a big request. 

Also make sure to include a reproduction that demonstrates your problem.
