### ISSUE TITLE
Cannot run anything if extension is .mjs or .wasm

### ISSUE THREAD

**Issue by koresar** [vuejs/vue-cli#2626]
Version
3.0.4

Reproduction link
https://github.com/jaydenseric/apollo-upload-client/issues/117#issuecomment-424968017

Node and OS info
node 8.11.4 / npm 6.4.1 / OS X

Steps to reproduce
Have a simple vue cli 3 project.

npm i -S extract-files And use this module anywhere in your application or config.

npm run serve

What is expected?
It starts.

What is actually happening?
error in ./node_modules/extract-files/lib/index.mjs

Can't reexport the namespace object from non EcmaScript module (only default export is available)

VUE CLI resolvers supports only: ['.js', '.jsx', '.vue', '.json'] https://github.com/vuejs/vue-cli/blob/v3.0.4/packages/%40vue/cli-service/lib/config/base.js#L41

Whereas it should be: ['.wasm', '.mjs', '.js', '.jsx', '.json'] https://github.com/zeit/next.js/blob/7.0.1-canary.0/build/webpack.js#L155

**Comment by koresar** [comment]
You got to be kidding me!

**Comment by sodatea** [comment]
It's customizable anyway. Add these lines to `vue.config.js`:
```
// vue.config.js
module.exports = {
  chainWebpack: config => config.resolve.extensions.prepend('.mjs').prepend('.wasm')
}

**Comment by ScreamZ** [comment]
@koresar Did you used the issue builder ? https://new-issue.vuejs.org/?repo=vuejs/vue-cli

I'll use @sodatea patch awaiting for this thanks

**Comment by dagadbm** [comment]
shouldn't this just be default behavior by  default? or is it because  im using an older version (3.1.1)
