### ISSUE TITLE
Provide a vue-cli-plugin to write vue plugin out of box

### ISSUE THREAD

**Issue by zhangbobell** [vuejs/vue-cli#2630]
### What problem does this feature solve?
Vue-cli 3.x is really a big progress for start a vue program instantly, but today when I want to write a vue plugin, things seems still tough. Since vue plugin is not the same with vue program, I need to config webpack, postcss, etc. The documents in vuejs.org says that how to write a plugin, but there was no docs about how to config when I am writing plugin. 

I've find a vue-cli 2.0 template for this purpose: https://github.com/posva/vue-plugin-template . In Vue-cli 3.x, It seems we can provide a vue-cli-plugin to solve this problem. Could anyone give me some advice? Thank you very much!

### What does the proposed API look like?
Provide a vue-cli-plugin, we could select it in the prompt when we use `vue create awesome-plugin`.

**Comment by LinusBorg** [comment]
vue-cli 3 gives you all of the basic tools to compile a plugin as a lib, see here:

https://cli.vuejs.org/guide/build-targets.html#library

For additional boilerplate / preconfiguration, a plugin from the *community* can be provided - especially using rollup to compile the plugin, like the template that you linked to does, is out of scope of vue-cli itself - we focus on webpack.

**Comment by zhangbobell** [comment]
I also find out that vue-cli build-target could do that, thank you for your patiently answer.
