### ISSUE TITLE
cli3中怎么全局的引入less的变量

### ISSUE THREAD

**Issue by triggerlife** [vuejs/vue-cli#2635]
### What problem does this feature solve?
less

### What does the proposed API look like?
less

**Comment by sodatea** [comment]
感谢关注，但是我们的 GitHub issues 只用于 Bug 反馈和特性请求，如果有使用上的问题建议到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问。

------

虽然[文档](https://cli.vuejs.org/zh/guide/css.html#%E5%90%91%E9%A2%84%E5%A4%84%E7%90%86%E5%99%A8-loader-%E4%BC%A0%E9%80%92%E9%80%89%E9%A1%B9)里只给出了 sass 的配置示例，但也说了，使用 `css.loaderOptions` 配置各个 CSS 预处理器，对于 less 可以去看 [`less-loader` 的文档](https://github.com/webpack-contrib/less-loader)，里面链接到了 [less 的文档页面](http://lesscss.org/usage/#less-options-global-variables)，可以看到，引入全局变量是通过配置 `globalVars` 选项实现的。所以最终的配置就是

```js
// vue.config.js
module.exports = {
  css: {
    loaderOptions: {
      less: {
        globalVars: {
          primary: '#fff'
        }
      }
    }
  }
}
