### ISSUE TITLE
构建超过5个页面的多页面应用，执行build 指令就会卡住

### ISSUE THREAD

**Issue by LgnMs** [vuejs/vue-cli#2636]
### Version
3.0.4

### Node and OS info
node 8.11.4/npm 5.6.0/windows10

### Steps to reproduce
1.书写超过5个入口文件
2.在vue.config.js中进行配置多页面应用
3.小于等于5个入口文件可以正常构建，超过5个入口文件，就会在构建界面卡住，不在往下执行

### What is expected?
希望这个问题能够被解决，或者指出问题方向

### What is actually happening?
构建超过5个页面的多页面应用，执行build 指令就会卡住

**Comment by sodatea** [comment]
请确认下 node_modules/@vue/cli-service/package.json 里的版本号，这个问题应该在 3.0.2 就修复了的

**Comment by LgnMs** [comment]
> 请确认下 node_modules/@vue/cli-service/package.json 里的版本号，这个问题应该在 3.0.2 就修复了的

感谢，局部版本是 3.0.0，更新版本后问题已经解决
