### ISSUE TITLE
build target lib should merge externals in vue.config

### ISSUE THREAD

**Issue by mattwmj** [vuejs/vue-cli#2646]
### What problem does this feature solve?
I find that if build with vue-cli-service build --target lib, externals in vue.config.js is ignored.
Dig into the vue-cli source I find below code in resolveLibConfig.js which ignores externals in vue.config.js.
Is this intended or not?

        // externalize Vue in case user imports it
        config
            .externals({
                vue: {
                    commonjs: 'vue',
                    commonjs2: 'vue',
                    root: 'Vue'
                }
            })

### What does the proposed API look like?
```
// externalize Vue in case user imports it
        config
            .externals({
                ...config.get('externals')
                vue: {
                    commonjs: 'vue',
                    commonjs2: 'vue',
                    root: 'Vue'
                }
            }) 
```

**Comment by LinusBorg** [comment]
Thanks, this looks like a bug. Up for a PR?

**Comment by mattwmj** [comment]
@LinusBorg Thanks. I am not quite familiar with the PR thing yet. I tried to create  #2653 . Please review it and give me some suggestions.

**Comment by LinusBorg** [comment]
This looks good :)

**Comment by LinusBorg** [comment]
Congrats on your first contribution.

**Comment by rikbrowning** [comment]
Sorry to comment on an old issue but the fix does not work if your webpack externals is an array of options.
The use of the spread operator here converts the incoming array to an object:
```
{ '0': [Function],
  '1': [Function],
  vue: { commonjs: 'vue', commonjs2: 'vue', root: 'Vue' } }
```
Which then breaks when we try to validate the webpack config.

**Comment by LinusBorg** [comment]
https://webpack.js.org/configuration/externals/#root

The externals option doesn't accept an array.

**Comment by rikbrowning** [comment]
https://webpack.js.org/configuration/externals/#combining-syntaxes

When trying to combine types you can use an array

**Comment by LinusBorg** [comment]
Now would be a good time to provide the actual code you have issues with
