### ISSUE TITLE
why the babel verion is coercion not range

### ISSUE THREAD

**Issue by mengxiong10** [vuejs/vue-cli#2647]
### Version
3.0.4

### Node and OS info
Node 8.11.3

### Steps to reproduce
the source code

### What is expected?
expect the babel is official version instead of beta version.

### What is actually happening?
the babel version in @vue/babel-preset-app is coercion(7.0.0-beta.47)

**Comment by sodatea** [comment]
Because there are breaking changes between each beta versions of babel. Will be upgraded in the next minor release. Keep an eye on https://github.com/vuejs/vue-cli/pull/2642
