### ISSUE TITLE
`vue server` can not `use async/await`

### ISSUE THREAD

**Issue by githoniel** [vuejs/vue-cli#2648]
### Version
3.0.4

### Node and OS info
Node 8.11.4/ Npm 6.4.1 / Windows 10

### Steps to reproduce
```bash
npm i @vue/cli @vue/cli-service-global -g
```

I got warning below
```
npm WARN babel-loader@8.0.4 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
```

then create a vue file `index.vue`
```html
<template>
<div></div>
</template>
<script>
export default {
    methods: {
        async test(){}
    }
}
</script>
```

atfer run `vue serve index.vue`  get compile error

```
 ERROR  Failed to compile with 1 errors                                                                     
This dependency was not found:

* regenerator-runtime/runtime in C:/Users/xxxx/AppData/Roaming/npm/node_modules/@vue/cli-service-global/node_modules/babel-loader/lib??ref--12-0!C:/Users/xxxx/AppData/Roaming/npm/node_modules/@vue/cli-service-global/node_modules/cache-loader/dist/cjs.js??ref--0-0!C:/Users/xxxx/AppData/Roaming/npm/node_modules/@vue/cli-service-global/node_modules/vue-loader/lib??vue-loader-options!./src/index.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save regenerator-runtime/runtime   
```

### What is expected?
`vue serve` support `async/await`

### What is actually happening?
failed to compile

**Comment by LinusBorg** [comment]
1. I don't get such a warning for babel-loader, just updated my cli and cli-service-global installs to `3.0.4`

2. Your example code is wrong, this is not valid javascript

```javascript
export default () {
```
It should look like this:

```javascript
export default {
```

3. Once that it fixed, the app compiles fine for me, except for some eslint warnings:

![image](https://user-images.githubusercontent.com/1444526/46244872-ddbedb80-c3e5-11e8-861e-d25ce4f2ca0e.png)

So we could discuss if eslint-loader should really be used in this scenario, but the app works.

**Comment by sodatea** [comment]
Reproduced on my machine.

**Comment by githoniel** [comment]
@LinusBorg 
1. Sorry that wrong code was cause when I simplify my code, I have edit this issue.

Is it necessary to manualy install babel ？ my npm global node_modules is below

![tim 20180929205309](https://user-images.githubusercontent.com/17848159/46245985-bab61b00-c429-11e8-8b47-30504f777ab1.png)

there is only @vue/cli@3.0.4 and @vue/cli-service-global@3.0.4 install in @vue

I just uninstall them and reinstall this two.

@vue/cli seem all right.
```bash
npm i @vue/cli
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@vue\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
```

but @vue/cli-service-global warn again like blew
```
C:\Users\xxxx>npm install -g @vue/cli-service-global
npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!

> yorkie@2.0.0 install C:\Users\xxxx\AppData\Roaming\npm\node_modules\@vue\cli-service-global\node_modules\yorkie
> node bin/install.js

setting up Git hooks
trying to install from sub 'node_module' directory, skipping Git hooks installation
npm WARN babel-loader@8.0.4 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@vue\cli-service-global\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
```

2. I think it is cause by 1.
I temporarily resolve this by add a `babel.config.js` in my project and install @vue/cli-plugin-babel for my project 
```js
/// babel.config.js
module.exports = {
    presets: [
        '@vue/app',
    ],
}
```

**Comment by HoweZhang** [comment]
So how do you use it?How did you configure it in babel.config.js

**Comment by HoweZhang** [comment]
So how do you use it? How did you configure it in babel.config.js @githoniel
