### ISSUE TITLE
Adding PWA plug-in does not generate HTML configuration.

### ISSUE THREAD

**Issue by lzxb** [vuejs/vue-cli#2649]
### What problem does this feature solve?
I used SSR rendering, but PWA always creates a index.html file in the dist directory.

### What does the proposed API look like?
**vue.config.js**
```javascript
module.exports = {
    pluginOptions: {
        pwd: {
            createHtml: false
        }
    }
};

```

**Comment by LinusBorg** [comment]
> I used SSR rendering, but PWA always creates a index.html file in the dist directory.

1. vue-cli doesn't support SSR out of the box, so you will have to give us a little more than that. How did you implement it?
2. vue-cli always generates an index.html, that's not dependent on the pwa plugin
3. Why is that a problem? Or to ask a different way: Doesn't your app still need an index.html file for the clients?

In short: Your problem description, and thereby your feature request, is not clear, please explain in more detail.

**Comment by lzxb** [comment]
I found a solution.

**Comment by rizwanzaheer** [comment]
@izxb what's the solution?

**Comment by lzxb** [comment]
I wrote an webpack plug-in myself

```javascript
module.exports = class RemovePwaHtmlPlugin {
	apply(compiler) {
		compiler.hooks.emit.tapAsync('webpack', (compilation, callback) => {
			delete compilation.assets['index.html'];
			callback();
		});
	}
};
```
