### ISSUE TITLE
Run task after complete

### ISSUE THREAD

**Issue by erguotou520** [vuejs/vue-cli#265]
*Not issue but question*
### Question
My template gives the choice of `using i18n`, and my template file contains many syntax like `$t('xxx')`, `this.$t('xxx')`, `:prop="$t('xxx')"`, if people chose not use i18n, I must replate this syntax with default text.

If I change the template file using the `{{#if i18n}}xxx{{/if}}`, this will be a large work. My idea is replace the template file with default i18n config, but this could be difficult because `vue-cli` does not support this feature, and it does't show me the use's choice after user's init option.

**Comment by OmgImAlexis** [comment]
@egoist this can be closed.
