### ISSUE TITLE
vue-cli 3 使用mode特定模式打包时，.js文件如何才能独立放在js文件夹内

### ISSUE THREAD

**Issue by LiuYuLu** [vuejs/vue-cli#2658]
### What problem does this feature solve?
项目需要区分环境，所以使用了mode模式，但是在打包的时候发现生成的文件目录和默认的production不一致，css文件已经通过配置css.extract 解决，那么js文件该怎么配置，或者说我该怎么复用production的默认配置呢？

### What does the proposed API look like?
仅仅是寻求帮助

**Comment by sodatea** [comment]
一般来说我们是建议凡是打包都配置 `NODE_ENV=production` 的，再用其他环境变量区分不同环境。
可以参考这个 issue 里的讨论 https://github.com/vuejs/vue-cli/issues/2625

但如果一定得在 `NODE_ENV=development` 的环境下打出和 production 一样的包的话，参考 https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/prod.js
