### ISSUE TITLE
package.json 能否指定 vue配置路径？

### ISSUE THREAD

**Issue by dficonfont** [vuejs/vue-cli#2659]
### What problem does this feature solve?
默认的配置是vue.config.js，因为当前的项目可能同时存在于二级目录下和一级目录下还需要指定固定域名，需要两个不同的配置，请问怎么配置package的scripts。官方文档没有看到。谢谢！

### What does the proposed API look like?
配置第二个vue.config.js 的方法

**Comment by sodatea** [comment]
vue.config.js 是一个会被执行到的 js 文件，你可以在其中使用任何 Node.js API 作出判断并返回不同配置，包括但不限于 process.cwd() 或设置环境变量等。
