### ISSUE TITLE
vue.config.js，assetsDir设置为网址时，前面会多一个'/'

### ISSUE THREAD

**Issue by dficonfont** [vuejs/vue-cli#2660]
### Version
3.0.1

### Node and OS info
v8.11.2

### Steps to reproduce
因为程序嵌入别的网站，不在一级目录等各种原因，需要对资源路径设置网址，但是设置assetsDir为网址时，生成的index.html变成src=/http://......，这个是不是bug？

### What is expected?
得到正确的路径

### What is actually happening?
路径前面多了/

**Comment by insipidness** [comment]
现在我也碰到了此类问题，我现在想将项目通过cordova打包生成app，但是路径是生成‘/’开头的，这就变成了绝对路径，这并不是我想要的啊。
所以说我改如何想路径变成我想要的相对路径。
