### ISSUE TITLE
Issue with router-link-exact-active class in router after vue-cli installed all dependencies

### ISSUE THREAD

**Issue by archimed3s** [vuejs/vue-cli#2665]
### Version
3.0.4

### Reproduction link
[https://jsfiddle.net/8xrk1n9f/](https://jsfiddle.net/8xrk1n9f/)

### Node and OS info
Last version of node 10 and npm on MAC OS

### Steps to reproduce
Vue CLI v3.0.4
? Please pick a preset: Manually select features
? Check the features needed for your project: TS, Router, Vuex, CSS Pre-processo
rs, Linter, Unit
? Use class-style component syntax? Yes
? Use Babel alongside TypeScript for auto-detected polyfills? No
? Use history mode for router? (Requires proper server setup for index fallback 
in production) Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported 
by default): Sass/SCSS
? Pick a linter / formatter config: TSLint
? Pick additional lint features: Lint on save, Lint and fix on commit
? Pick a unit testing solution: Jest
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedica
ted config files
? Save this as a preset for future projects? (y/N) 

### What is expected?
https://jsfiddle.net/8xrk1n9f/

### What is actually happening?
router-link to="/"
router-link to="/" exact

This is work as equal. And it is wrong according to documentation about exact prop

**Comment by LinusBorg** [comment]
I'm not sure I understand. Does the jsfiddle reproduce the problem, or does it show the correct, expected behaviour?

If it's the latter: Please provide a git reporsitory with a vue-cli project that demonstrates the problem. Because right now, I don't see what the problem is supposed to be and, if it is a real problem, how it should be related to vue-cli instead of vue-router itself.

**Comment by LinusBorg** [comment]
> Vue-cli has an issue with it. 

What is that issue, exactly? Earlier, you say:

> router-link to="/"
> router-link to="/" exact
> 
> This is work as equal. And it is wrong according to documentation about exact prop

But I don't see what you seem to be seeing. What exactly do you mean by "This is work as equal".
Please explain in more detail: Tell me what you expect to see when you click each pf the first 3 links. Provide screenshots if you must.

Although, I can spot *one* difference:

* In the fiddle, you style `.router-link-active`, which is applied both for normal and exact matches.
* In your vue-cli repository, you only style `.router-link-exact-active`, which is *only* applied to exact matches.

However the classes as they are applied to the DOM elements when clicking links are behaving exactly the same in both examples. So maybe you just misunderstand how this feature is supposed to work?

**Comment by archimed3s** [comment]
> > Vue-cli has an issue with it.
> 
> What is that issue, exactly? Earlier, you say:
> 
> > router-link to="/"
> > router-link to="/" exact
> > This is work as equal. And it is wrong according to documentation about exact prop
> 
> But I don't see what you seem to be seeing. What exactly do you mean by "This is work as equal".
> Please explain in more detail: Tell me what you expect to see when you click each pf the first 3 links. Provide screenshots if you must.
> 
> Although, I can spot _one_ difference:
> 
> * In the fiddle, you style `.router-link-active`, which is applied both for normal and exact matches.
> * In your vue-cli repository, you only style `.router-link-exact-active`, which is _only_ applied to exact matches.
> 
> However the classes as they are applied to the DOM elements when clicking links are behaving exactly the same in both examples. So maybe you just misunderstand how this feature is supposed to work, and got confused by the two different styles you applied in the examples?

Oh, you right! I'm used to think that is "router-link-exact-active" is that class that isn't work.
But I'm confused with "router-link-active". 
I'm so sorry that created this issue at all. Thanks for Ur help!!
