### ISSUE TITLE
Vue create broken when selecting cypress for E2E testing 

### ISSUE THREAD

**Issue by assembledadam** [vuejs/vue-cli#2667]
### Version
3.0.4

### Reproduction link
[https://github.com/vuejs/vue-cli/tree/v3.0.4](https://github.com/vuejs/vue-cli/tree/v3.0.4)

### Node and OS info
Node v10.11.0 / Tested on MacOS High Sierra 10.13.6 and Debian Jessie (Docker node:latest)

### Steps to reproduce
Run $ vue create hello-world

With the following settings:
Vue CLI v3.0.4
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, Router, Vuex, CSS Pre-processors, Linter, Unit, E2E
? Use history mode for router? (Requires proper server setup for index fallback in production) Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Sass/SCSS
? Pick a linter / formatter config: Airbnb
? Pick additional lint features: Lint on save
? Pick a unit testing solution: Mocha
? Pick a E2E testing solution: Cypress
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files

### What is expected?
Successful installation

### What is actually happening?
```
⠋  Running completion hooks...error: '@cypress/webpack-preprocessor' should be listed in the project's dependencies. Run 'npm i -S @cypress/webpack-preprocessor' to add it (import/no-extraneous-dependencies) at claimer-app/tests/e2e/plugins/index.js:2:17:
  1 | // https://docs.cypress.io/guides/guides/plugins-guide.html
> 2 | const webpack = require('@cypress/webpack-preprocessor');
    |                 ^
  3 | 
  4 | module.exports = (on, config) => {
  5 |   on('file:preprocessor', webpack({


error: Unexpected require() (global-require) at claimer-app/tests/e2e/plugins/index.js:6:21:
  4 | module.exports = (on, config) => {
  5 |   on('file:preprocessor', webpack({
> 6 |     webpackOptions: require('@vue/cli-service/webpack.config'),
    |                     ^
  7 |     watchOptions: {},
  8 |   }));
  9 | 


error: '@vue/cli-service' should be listed in the project's dependencies, not devDependencies (import/no-extraneous-dependencies) at claimer-app/tests/e2e/plugins/index.js:6:21:
  4 | module.exports = (on, config) => {
  5 |   on('file:preprocessor', webpack({
> 6 |     webpackOptions: require('@vue/cli-service/webpack.config'),
    |                     ^
  7 |     watchOptions: {},
  8 |   }));
  9 | 


3 errors found.
```

**Comment by LinusBorg** [comment]
Hm, those are eslint errors, it seems the way that this file is written breaks a few rules fo the airbnb preset (personal sidenote: much too strict, don't like this preset at all for a boilerplate like ours)

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-e2e-cypress/generator/template/tests/e2e/plugins/index.js

We could disable these rules for the file
```javascript
/* eslint-disable import/no-extraneous-dependencies global-require */
```

We could also try and conform this file to the rules, but that will require to adjust a few rules of `eslint-plugin-import` with globs to not match for certain files. We would have to do something like this:
```
"import/no-extraneous-dependencies": [
  "error", 
  {
    "devDependencies": ["**/*.test.js", "**/*.spec.js"], // glob is taken from plugin docs, probably not what we need
    "peerDependencies": ["**/*.test.js", "**/*.spec.js"],
    "optionalDependencies": ["**/*.test.js", "**/*.spec.js"]
  }
]
```
or include the dirs of all possible @vue plugins as locations fore package.json files:
```
"import/no-extraneous-dependencies": [
  "error", 
  {
    "packageDir": [
      './node_modules/@vue/cli-plugin-e2e-cypress',
      './node_modules/@vue/cli-plugin-e2e-nightwatch',
      './node_modules/@vue/cli-plugin-unit-mocha',
      './node_modules/@vue/cli-plugin-unit-jest',
      './node_modules/@vue/cli-service',
      // ...
    ]
  }

]
```

Which I would consider pretty verbose and confusing to newcomers.

Thoughts?

**Comment by assembledadam** [comment]
Gotcha. 

Messing with things to conform when lint presets are transient and subject to change = waste of life. IMO disable rules for the file.

**Comment by sodatea** [comment]
@macdaddyaz 
It is caused by a missing comma in the generated file (will be fixed in the next release). Please manually add that comma to your file: https://github.com/vuejs/vue-cli/commit/4e90afe18980f0f288908a7f7ef0974dc5a4545f#diff-1c4d741ece51a603d9d28f55c9d1e306
