### ISSUE TITLE
Request for better documentation on differences between build target library and web component

### ISSUE THREAD

**Issue by mrodal** [vuejs/vue-cli#2669]
### What problem does this feature solve?
I dont fully get the difference from building with library target and web component, so I dont know which one to use. It would be helpful to add to the documentation what is the difference between them, maybe with some examples, because it only explains how to use them

**Comment by sodatea** [comment]
I don't know how we can further explain this issue -- if you know the differences between standard [web components](https://www.webcomponents.org/introduction) and [vue components](https://vuejs.org/v2/guide/components.html), you should have known that between the two targets.
