### ISSUE TITLE
Is it possible to re-run the 'init' script again to add testing?

### ISSUE THREAD

**Issue by gkatsanos** [vuejs/vue-cli#267]
When I created my application I chose "no" to testing frameworks etc.

Is it possible to add this now - without going through all the manual steps needed? (webpack configs, other settings etc)

I'm clueless when it comes to webpack and would like to have a starting point.

Thanks

**Comment by egoist** [comment]
Seems you want something like `skip existing`?

**Comment by gkatsanos** [comment]
uhm, maybe? can you point me to a doc ?

**Comment by egoist** [comment]
not yet a feature 😃 but we should add this! IMO

**Comment by gkatsanos** [comment]
well I mean if you see yeoman generator there's plenty of stuff we need to add :) for example vue component 'name-of component' to add a new component folder with .vue / .css / .test etc etc.. 
Okay so I will go the hard way, bootstrap a new vue-cli project and copy/paste stuff :(

**Comment by gkatsanos** [comment]
@yyx990803 did I miss something, was this implemented?
