### ISSUE TITLE
Warning in size limit

### ISSUE THREAD

**Issue by p-adams** [vuejs/vue-cli#268]
Recently I noticed that projects generated with webpack-simple template generate the following:

        WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB).
        This can impact web performance.
        Assets:
           build.js (1.4 MB)

        WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the       recommended limit (250 kB). This can impact web performance.
        Entrypoints:
        main (1.41 MB)
        build.js
        0.5e82a6ff665ce85050db.hot-update.js

This the the first time seeing these warnings. How do I fix this?

**Comment by p-adams** [comment]
This seemed to fix it:

performance: {
  hints: process.env.NODE_ENV === 'production' ? "warning" : false
},

**Comment by posva** [comment]
Looks pretty clear imo. Having such a big file is not a good idea, you should split that file. Check the webpack template to get an idea about how to do it
