### ISSUE TITLE
HMR fails if --public parameter ends with `/'

### ISSUE THREAD

**Issue by kissge** [vuejs/vue-cli#2683]
### Version
3.0.4

### Node and OS info
Node v8.12.0 on Amazon Linux 2018.03

### Steps to reproduce
1. Set up a project using `vue init`
2. Start a server using `npm run serve -- --public http://example.com/`

### What is expected?
HMR works

### What is actually happening?
HMR fails because ws://example.com//sockjs-node/404/udld1ch2/websocket returns 404.

**Comment by sodatea** [comment]
Seems the bug has been gone now.
