### ISSUE TITLE
ERROR when Creating A new Project  based on Babel and Linter

### ISSUE THREAD

**Issue by xdnloveme** [vuejs/vue-cli#2689]
### Version
3.0.4

### Node and OS info
node v8.11.4; npm v5.6.0; Mac OS 10.12.6

### Steps to reproduce
```
vue create demo   
```

### What is expected?
**SUCCESS to BUILD**

### What is actually happening?
ERROR is showed following:
```
npm ERR! peerinvalid The package @babel/core@7.0.0-beta.47 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer babel-loader@8.0.4 wants @babel/core@^7.0.0
```
**It occured when I chose Babel && Linter**

---
ERROR details:
```
> fsevents@1.2.4 install /Users/tanghaoyi/Documents/work/VueSingle/demo/node_modules/@vue/cli-plugin-babel/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents
> node install

[fsevents] Success: "/Users/tanghaoyi/Documents/work/VueSingle/demo/node_modules/@vue/cli-plugin-babel/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/tanghaoyi/node_modules/node/bin/node" "/Users/tanghaoyi/node_modules/.bin/npm" "install" "--loglevel" "error"
npm ERR! node v9.0.0
npm ERR! npm  v2.15.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @babel/core@7.0.0-beta.47 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer babel-loader@8.0.4 wants @babel/core@^7.0.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tanghaoyi/Documents/work/VueSingle/demo/npm-debug.log
 ERROR  command failed: npm install --loglevel error
```

**Comment by LinusBorg** [comment]
Please include a reproduction so we can see what exactly you chose for the options etc.

**Comment by xdnloveme** [comment]
My options:
```
Feature: Babel,Vuex,Linter
Lint config: standard
```
![image](https://user-images.githubusercontent.com/25051594/46618811-0c118900-cb53-11e8-9bb6-e94a661fe884.png)

Then start running......
**And Program crashed, the all information(processes) is included in the image below**

<img width="1053" alt="2018-10-08 11 33 42" src="https://user-images.githubusercontent.com/25051594/46618726-e2586200-cb52-11e8-8f4a-d3b109e3153b.png">

**Comment by tborja** [comment]
I too am getting the same error. I am on:
ubuntu 16.04
vue 3.0.5

Steps:
sudo npm install -g @vue/cli
vue create cli-test

Error:
487523 verbose unlock done using /home/user/.npm/_locks/vue-cli-service-466a9d1165843033.lock for /home/user/vuejs/samples/cli-test/node_modules/@vue/cli-service
487524 info build /home/user/vuejs/samples/cli-test
487525 info linkStuff cli-test@0.1.0
487526 silly linkStuff cli-test@0.1.0 has /home/user/vuejs/samples as its parent node_modules
487527 verbose linkBins cli-test@0.1.0
487528 verbose linkMans cli-test@0.1.0
487529 verbose rebuildBundles cli-test@0.1.0
487530 verbose rebuildBundles [ '.bin', '@vue', 'vue-template-compiler' ]
487531 info install cli-test@0.1.0
487532 info postinstall cli-test@0.1.0
487533 info prepublish cli-test@0.1.0
487534 verbose validateInstall loading /home/user/vuejs/samples/cli-test/package.json for validation
487535 verbose stack Error: The package @babel/core@7.0.0-beta.47 does not satisfy its siblings' peerDependencies requirements!
487535 verbose stack     at /home/user/node_modules/npm/lib/install.js:125:32
487535 verbose stack     at /home/user/node_modules/npm/lib/install.js:268:7
487535 verbose stack     at /home/user/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
487535 verbose stack     at /home/user/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
487535 verbose stack     at cb (/home/user/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
487535 verbose stack     at /home/user/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
487535 verbose stack     at cb (/home/user/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
487535 verbose stack     at /home/user/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
487535 verbose stack     at cb (/home/user/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
487535 verbose stack     at /home/user/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
487536 verbose cwd /home/user/vuejs/samples/cli-test
487537 error Linux 4.4.0-137-generic
487538 error argv "/usr/bin/node" "/home/user/node_modules/.bin/npm" "install" "--loglevel" "error"
487539 error node v8.12.0
487540 error npm  v2.15.12
487541 error code EPEERINVALID
487542 error peerinvalid The package @babel/core@7.0.0-beta.47 does not satisfy its siblings' peerDependencies requirements!
487542 error peerinvalid Peer babel-loader@8.0.4 wants @babel/core@^7.0.0
487543 verbose exit [ 1, true ]

**Comment by sodatea** [comment]
This issue should have been resolved by v3.1.0

**Comment by introrse** [comment]
I just got a similar (but slightly different) peer dependency error attempting to vue 3.3.0.  MacOS 10.14.1 (Mojave)

To reproduce:

    npm install -g @vue/cli
    vue create <projectname>
    Press enter to accept default preset "default (babel, eslint)"

Error:

    npm ERR! Darwin 18.2.0
    npm ERR! argv "/Users/jasonc/.nvm/versions/node/v11.6.0/bin/node" "/Users/jasonc/node_modules/.bin/npm" "install" "--loglevel" "error"
    npm ERR! node v11.6.0
    npm ERR! npm  v2.15.12
    npm ERR! code EPEERINVALID

    npm ERR! peerinvalid The package @vue/babel-helper-vue-jsx-merge-props@1.0.0-beta.1 does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer @vue/babel-plugin-transform-vue-jsx@1.0.0-beta.1 wants @vue/babel-helper-vue-jsx-merge-props@^0.1.0

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/jasonc/Documents/Dev/Conference/Oakland/four/npm-debug.log
    ERROR  command failed: npm install --loglevel error

I tried uninstalling all vue modules and reinstalling only @vue/cli and still get the same error the same way as above. 

I tried also installing vue (globally) as well as @vue/cli, and still got the same error the same way as above.

I tried deselecting Babel and Linter at the config prompt, but get a different dependency error when launching npm run serve:

    vue create <projectname>
    Select "manual" config, deselect Babel, deselect Linter, and proceed.
    cd projectname
    npm run serve

The error:

     ERROR  Error: Cannot find module '@vue/component-compiler-utils/package.json'

Any ideas? Thanks!

**Comment by sodatea** [comment]
@introrse This should be a bug on the jsx plugins. Will fix it soon.
But I noticed that you are still using npm 2.x, the errors should turn into warnings once you upgrade your npm version, if I'm not mistaken.

**Comment by introrse** [comment]
**Thank you very much for pointing out the outdated npm in the log!**

A much older npm was somehow getting used by ```vue create``` rather than v 6.5.0 which was what ```npm -v``` showed.  Once I removed the 2.x version the vue commands worked fine. 

For anyone else encountering something similar: I suggest looking at the ```argv``` line in your error output.  The second arg is the npm being used by vue-cli.  Compare that with the output of ```which npm```, or the first line of ```which -a npm```.  If they differ you may need to clean up old versions of npm.
