### ISSUE TITLE
Object spread operator not working when using into SFC templates

### ISSUE THREAD

**Issue by IlCallo** [vuejs/vue-cli#2690]
### Version
3.0.4

### Node and OS info
Node 9.3.0 / yarn 1.9.4 / Windows 10

### Steps to reproduce
Use object spread operator inside a SFC template (eg. costructing event payload inline).

```vue
<button @click="$emit('event-name', {...localVariable, optionToMerge: true})"></span>
```

### What is expected?
Object spread operator working both in template bindings and script

### What is actually happening?
It works fine in script tag, firing off `Object spread operator requires specified objectAssign option with 'Object.assign' or polyfill helper` error when used into templates.

---
The problems seems to lay on "buble" transpiler in which object spread operator is not enabled by default as considered "risky" (but can be enabled).

I guess that template bindings and script tags of an SFC are transpiled/compiled by different webpack loaders and the template one causes the problem.

**Comment by guilhermemj** [comment]
Same here. There used to be a workaround on it (as seen [here](https://github.com/vuejs-templates/webpack/issues/1005)) but i'm not quite sure on how to properly configure it with the new cli.

**Comment by sodatea** [comment]
Added in v3.4 with https://github.com/vuejs/vue-cli/pull/3281
