### ISSUE TITLE
Make the current command's name available to plugins

### ISSUE THREAD

**Issue by m0dch3n** [vuejs/vue-cli#2692]
### What problem does this feature solve?
I'm currently developing a vue cli 3 plugin, to add cordova, to a vue project. For the serve and build, I created new commands in my generator.js

```
api.extendPackage({
    scripts: {
      'cordova-serve-android': 'vue-cli-service cordova-serve-android',
      'cordova-build-android': 'vue-cli-service cordova-build-android',
      'cordova-serve-ios': 'vue-cli-service cordova-serve-ios',
      'cordova-build-ios': 'vue-cli-service cordova-build-ios',
      'cordova-serve-browser': 'vue-cli-service cordova-serve-browser',
      'cordova-build-browser': 'vue-cli-service cordova-build-browser'
    },
```

And in my index new defaultModes for theses commands:

```
const defaultModes = {
  'cordova-serve-android': 'cordova-serve-android',
  'cordova-build-android': 'cordova-build-android',
  'cordova-serve-ios': 'cordova-serve-ios',
  'cordova-build-ios': 'cordova-build-ios',
  'cordova-serve-browser': 'cordova-serve-browser',
  'cordova-build-browser': 'cordova-build-browser'
}
```

The problem is now, if I ran `vue-cli-service cordova-build-android`, my process.env.NODE_ENV is development, because of [loadEnv](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/Service.js#L91).

Setting my defaultModes to :

```
const defaultModes = {
  'cordova-serve-android': 'development',
  'cordova-build-android': 'production',
  'cordova-serve-ios': 'development',
  'cordova-build-ios': 'production',
  'cordova-serve-browser': 'development',
  'cordova-build-browser': 'production'
}
```

would correctly set the mode, however, in my plugin, during

```
api.chainWebpack(webpackConfig => {
}
```
and
```
api.configureDevServer(app => {
}
```

I no longer know, which mode (android, ios, browser), I'm using then.

My Plugin is available under https://github.com/m0dch3n/vue-cli-plugin-cordova to better understand, what I'm talking here about.

### What does the proposed API look like?
It would be great, to have:

`api.service.commandName = 'cordova-build-android'`

i.e. if I ran `vue-cli-service cordova-build-android`

**Comment by m0dch3n** [comment]
PS: I know I could create a file .env.cordova-build-android with NODE_ENV=production, however I prefer, if my plugin can solve this, without having to create additional files during generator.js...

What do you think, if the constructor of Service is refactored, to something like :

```
  constructor (context, commandName, { plugins, pkg, inlineOptions, useBuiltIn } = {}) {
  this.commandName = commandName
  ...
}
```
and then in [vue-cli-service.js](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/bin/vue-cli-service.js)

```
const service = new Service(process.env.VUE_CLI_CONTEXT || process.cwd(), command)
```

**Comment by LinusBorg** [comment]
You can call `api.chainWebpack` *inside of the registered command. 

That way you have all The bro you need...

**Comment by m0dch3n** [comment]
Thanks, this was also solving my problem. 

I thought, chainWebpack i.e needed to be registered before the command is executed, so I didn't try this.

You can close the issue, if you want, or if you still find this feature useful in other scenarios, you can keep it open...

**Comment by LinusBorg** [comment]
So this doesn't gain any traction by uers it seems, and I didn't come across a real usecase myself, so I'll close it.
