### ISSUE TITLE
Dashboard fails to load

### ISSUE THREAD

**Issue by mekhami** [vuejs/vue-cli#2693]
### Version
3.0.4

### Node and OS info
Yarn 1.10.1, Ubuntu 16.04

### Steps to reproduce
I load my application with Vue UI and the dashboard for the serve task hangs on the spinner. Even if I successfully run serve, both Dashboard and Analyzer fail to load.

### What is expected?
I expect Dashboard and Analyzer to load.

### What is actually happening?
They are stuck on the loading spinner.

---
VM35:1 Uncaught TypeError: Illegal invocation
    at l (<anonymous>:1:1911)
    at l (<anonymous>:1:1912)
    at l (<anonymous>:1:1912)
    at l (<anonymous>:1:1912)
    at l (<anonymous>:1:1912)
    at l (<anonymous>:1:1912)
    at l (<anonymous>:1:1912)
    at i (<anonymous>:1:2190)
    at Object.n.once.t (<anonymous>:1:2698)
    at Object.r (<anonymous>:1:378)

I see that in the console.

**Comment by sodatea** [comment]
Since the line number is prefixed with `VM`, it might be related to your Chrome extensions. Try to disable all your extensions and reopen the page.

By searching for `"Object.n.once.t"` I found this issue: https://github.com/vuejs/vue-devtools/issues/770, so please also try to upgrade the vue-devtools extension.

**Comment by mekhami** [comment]
This seems to have fixed itself in the update to the most recent version. Thanks for looking for me though!

**Comment by mekhami** [comment]
I closed this cause I thought it was fixed, but it wasn't. The problem is in vuejs/vue-devtools, and it's failing 5.0.0 beta 3.

**Comment by yft** [comment]
try empty cache & hard reload

**Comment by Akryum** [comment]
@mekhami Please try again with both Vue CLI and Vue devtools updated to their respective latest versions.
