### ISSUE TITLE
It always uses `index-default.html` when give `template` property

### ISSUE THREAD

**Issue by fengxinming** [vuejs/vue-cli#2697]
### Version
3.0.4

### Reproduction link
[https://github.com/fengxinming/vuecli3-demo](https://github.com/fengxinming/vuecli3-demo)

### Node and OS info
node v8.11.1, npm 6.4.1, macOS

### Steps to reproduce
npm i
npm run build

### What is expected?
`public/index.pug` is compiled to `dist/index.html`

### What is actually happening?
`index-default.html` is compiled to `dist/index.html`

---
190  // resolve page index template
191  const hasDedicatedTemplate = fs.existsSync(api.resolve(template))
192  if (hasDedicatedTemplate) {
193         publicCopyIgnore.push(template)
194  }

if I use pug template as property `template`, then `hasDedicatedTemplate` still can be `false`

**Comment by KancerEzeroglu** [comment]
Hi, is somebody working on this issue? If not, I would like to work on it.

**Comment by LinusBorg** [comment]
It seems to be free, so go ahead!

Thanks! :)

**Comment by KancerEzeroglu** [comment]
Hi @LinusBorg ,

Do you have any suggestion for a starting point?
Today I have a chance to have a look.

**Comment by fengxinming** [comment]
@KancerEzeroglu 看这个文件 `packages/@vue/cli-service/lib/config/app.js` 里的第148行代码，有两部分配置，一部分是多页配置；另一部分是单页配置。

**Comment by fengxinming** [comment]
@KancerEzeroglu You may find the line 148 of that file `packages/@vue/cli-service/lib/config/app.js` which starts to resolve HTML files.

**Comment by jeneser** [comment]
Any progress? @fengxinming Can you update the reproduction link?
