### ISSUE TITLE
pnpm error

### ISSUE THREAD

**Issue by liangjl76** [vuejs/vue-cli#2703]
### Version
3.0.5

### Node and OS info
node 8.9.4 npm 5.6.0  pnpm 2.16.3 win7 sp3 (Microsoft Windows [版本 6.1.7601])

### Steps to reproduce
Install and run dependencies after creating projects
pnpm install --shamefully-flatten
pnpm run serve

### What is expected?
 App running at:
 - Local:   http://localhost:8080/
 - Network: http://192.168.0.218:8080/

### What is actually happening?
......
ERROR Failed to compile with 1 errors 08:39:15

This dependency was not found:

-!../node_modules/.registry.npm.taobao.org/cache-loader/1.2.2/webpack@4.20.2/n
ode_modules/cache-loader/dist/cjs.js??ref--13-0!../node_modules/.registry.npm.ta
obao.org/babel-loader/8.0.4/@babel!core@7.0.0-beta.47/node_modules/babel-loader/
lib/index.js!../node_modules/.registry.npm.taobao.org/ts-loader/4.5.0/node_modul
es/ts-loader/index.js??ref--13-2!../node_modules/.registry.npm.taobao.org/cache-
loader/1.2.2/webpack@4.20.2/node_modules/cache-loader/dist/cjs.js??ref--0-0!../n
ode_modules/.registry.npm.taobao.org/vue-loader/15.4.2/css-loader@1.0.0/node_mod
ules/vue-loader/lib/index.js??vue-loader-options!./App.vue?vue&type=script&lang=
ts& in ./src/App.vue?vue&type=script&lang=ts&
To install it, you can run: npm install --save -!../node_modules/.registry.npm.t
aobao.org/cache-loader/1.2.2/webpack@4.20.2/node_modules/cache-loader/dist/cjs.j
s??ref--13-0!../node_modules/.registry.npm.taobao.org/babel-loader/8.0.4/@babel!
core@7.0.0-beta.47/node_modules/babel-loader/lib/index.js!../node_modules/.regis
try.npm.taobao.org/ts-loader/4.5.0/node_modules/ts-loader/index.js??ref--13-2!..
/node_modules/.registry.npm.taobao.org/cache-loader/1.2.2/webpack@4.20.2/node_mo
dules/cache-loader/dist/cjs.js??ref--0-0!../node_modules/.registry.npm.taobao.or
g/vue-loader/15.4.2/css-loader@1.0.0/node_modules/vue-loader/lib/index.js??vue-l
oader-options!./App.vue?vue&type=script&lang=ts&
No type errors found
No lint errors found
Version: typescript 3.1.2, tslint 5.11.0
Time: 3989ms

---
App.vue
Remove the <script> node and work normally

**Comment by liangjl76** [comment]
安装配置"zouhir/jarvis"后显示无法加载模块"../node_modules/.registry.npm.taobao.org/babel-loader/8.0.4/@babel"
实际目录如下
../node_modules/.registry.npm.taobao.org/babel-loader/8.0.4/@babel!core@7.0.0-beta.47/node_modules/babel-loader/lib/index.js
猜测"@babel!core"应该是"@babel/core",猜测无法加载的模块是"babel-loader"
删除相关的目录后，单独安装模块"babel-loader"后解决问题

**Comment by liangjl76** [comment]
reproduction
https://github.com/liangjl76/vue-cli-3.0.5-pnpm.git

**Comment by liangjl76** [comment]
@babel/core正式版已经出来了，为什么引用beta版?
"babel-loader":"^8.0.0",要求引用"@babel/core": "^7.0.0"，引用beta版与之产生了冲突。

**Comment by pixelyunicorn** [comment]
this issue is also reported on glitch.com, which uses pnpm by default: https://support.glitch.com/t/unsure-how-to-read-these-error-messages/6356/6

**Comment by TemaSM** [comment]
Probably, this problem comes from `babel-loader` paths resolving, because `babel-loader` is dependency of `@vue/cli-plugin-babel`
#### Solved by this way:

1. Delete whole `node_modules`  folder
2. Run `pnpm i -D babel-loader --shamefully-flatten` (will install `babel-loader` as your project's local dev-dependency instead of dependency of `@vue/cli-plugin-babel`)
3. Run `pnpm i --shamefully-flatten` (the important thing here is `shamefully-flatten` [option](https://pnpm.js.org/docs/en/pnpm-install.html#shamefully-flatten))
4. (optional):
Create `.npmrc` file and paste into it: `shamefully-flatten=true` - this will force `pnpm` to use `shamefully-flatten` each time you use `pnpm` in your project's directory (where `.npmrc` located in)

**Comment by sodatea** [comment]
https://github.com/pnpm/pnpm/issues/1678#issuecomment-469981972
It's a bug in pnpm v2.
A fix has been landed in `pnpm@next-major`.

**Comment by sodatea** [comment]
pnpm v3 was released a day ago.
