### ISSUE TITLE
file path goes wrong after build

### ISSUE THREAD

**Issue by Krispomoho** [vuejs/vue-cli#271]
I have crate a simplest demo and I haven't wrote code. It works fine when I run `npm run dev`. however, it can't work after I run 'npm run build'.

index.html can't work by open directly or through a server port;
![direct](https://cloud.githubusercontent.com/assets/6927337/21353718/3a3c97d6-c702-11e6-9c73-8c9c9a243e2d.png)

**Comment by egoist** [comment]
1. open issues in relevant repo
2. load index.html with a server

**Comment by Krispomoho** [comment]
It still can't work even I load index.html with a server, but I have already solved this problem through change `config/index.js` ,

`assetsPublicPath: '/',` => `assetsPublicPath: './',`.
