### ISSUE TITLE
Couldn't find package "@babel/types@7.0.0-beta.47" required by "@babel/helper-explode-assignable-expression@7.0.0-beta.47" on the "npm" registry.

### ISSUE THREAD

**Issue by jiankafei** [vuejs/vue-cli#2710]
### Version
3.0.5

### Reproduction link
[https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-babel/package.json](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-babel/package.json)

### Node and OS info
node 8 / yarn 1.9.4 / windows 10

### Steps to reproduce
更新 cli-plugin-babel 到 3.0.5，但更新失败

### What is expected?
更新 cli-plugin-babel 到 3.0.5

### What is actually happening?
更新失败

---
我想应该是 cli-plugin-babel 依赖 "@babel/core": "7.0.0-beta.47" 导致上述问题

**Comment by sodatea** [comment]
可否详细描述一下复现步骤？

**Comment by jiankafei** [comment]
使用 vue ui 更新 cli-plugin-babel 到 3.0.5 ，更新失败，没什么详细步骤，报错信息就是在npm仓库中无法找到包
