### ISSUE TITLE
Invalid options in vue.config.js: "baseURL" is not allowed

### ISSUE THREAD

**Issue by jackiezero** [vuejs/vue-cli#2711]
### Version
3.0.5

### Reproduction link
[https://github.com/jackiezero/sa.git](https://github.com/jackiezero/sa.git)

### Node and OS info
node:v10.12.0 ; npm:6.4.1 ; mackos mojave

### Steps to reproduce
 npm run serve

### What is expected?
build success

### What is actually happening?

``` ERROR  Invalid options in vue.config.js: "baseURL" is not allowed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! autotestclent@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the autotestclent@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by LinusBorg** [comment]
the option is called `baseUrl`
