### ISSUE TITLE
keyword "super" is not effective on ie9&ie10, how to solve it?

### ISSUE THREAD

**Issue by w3stone** [vuejs/vue-cli#2722]
### Version
3.0.5

### Node and OS info
yarn 1.10.1

### Steps to reproduce
class Parent{
    constructor(data){
        this.title = data.title || ""; //标题
    } 
}

class Child extends Parent{
    constructor(data){
        super(data);
    } 
}

var obj = {title: "title"};
var  child = new Child(data);
console.log(child.title); //undifined

### What is expected?
console.log(child.title); //"title"

### What is actually happening?
console.log(child.title); //undifined

---
I think maybe "babel" in vue-cli has some problem

**Comment by LinusBorg** [comment]
This is not related to vue-cli
