### ISSUE TITLE
New project does not work on Safari 9.1

### ISSUE THREAD

**Issue by koendeschacht** [vuejs/vue-cli#2733]
### Version
3.0.5

### Reproduction link
[https://github.com/koendeschacht/vue-cli-safari-error](https://github.com/koendeschacht/vue-cli-safari-error)

### Node and OS info
developer machine: Node 9.11.2 / Ubutu Mate 17.10, browser machine: El Capitaine with Safari 9.1.3

### Steps to reproduce
Checkout project in https://github.com/koendeschacht/vue-cli-safari-error

Run 

> npm install 
> npm run serve

Visit localhost:8080 in Safari 9.1.3 on El Capitaine (e.g. using browser stack)

### What is expected?
To see the hello-world vue page. 

### What is actually happening?
Empty page, and the error console shows:

ReferenceError: Can't find variable: Reflect

---
Started with a new project, using

vue create hello-world
 
and then modified .browserslistrc to include Safari >=9

**Comment by sodatea** [comment]
Fixed in vue-class-component v6.3.2
