### ISSUE TITLE
Babel plugins are ignored

### ISSUE THREAD

**Issue by Yovar** [vuejs/vue-cli#2734]
### Version
3.0.5

### Reproduction link
[https://github.com/Yovar/vue-babel-plugins](https://github.com/Yovar/vue-babel-plugins)

### Node and OS info
Node 8.12.0 / yarn 1.10.1 / Windows 10

### Steps to reproduce
1. Create a fresh vue-cli project.
2. Add the @babel/plugin-proposal-pipeline-operator plugin to your Babel configuration.
3. Use the pipeline operator in your code.
4. Start your app.

### What is expected?
The operator is working as specified in the proposal.

### What is actually happening?
I get the following message :

Syntax Error: SyntaxError: D:\projets\vue-babel-plugins\src\main.js: Support for the experimental syntax 'pipelineOperator' isn't currently enabled (10:16):t currently enabled (10:16):

[...]

Add @babel/plugin-proposal-pipeline-operator (https://git.io/vb4SU) to the 'plugins' section of your Babel config to enable transformation.

---
The plugin is working as intended in a project without vue-cli.

**Comment by Neonunux** [comment]
It seems to be serious bug with babel

**Comment by Yovar** [comment]
It appears that installing Babel manually via `yarn add --dev @babel/core` solved my issue. I suspect vue-cli is using a babel version that is incompatible with the tested plugin so I had to change it manually. It was not obvious because the plugin didn't emit any error and the provided error from Babel was very misleading.
