### ISSUE TITLE
“baseUrl” will change the router-link url of the link, expected keep origin

### ISSUE THREAD

**Issue by hookszhang** [vuejs/vue-cli#2747]
### Version
3.0.5

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Node and OS info
Node 8.12.0 / yarn 1.9.4 / macOS Mojave

### Steps to reproduce
```
// vue.config.js
module.exports = {
  baseUrl: 'http://localhost:8080'
}
```

```
<router-link to=“/workbench”></router-link>
// run yarn serve, it turned out to be
<a data-v-a83bd3b0="" href="/http:/localhost:8080/workbench" class=""></a>
```

### What is expected?
Setting up baseUrl only wants to change the prefix of the static resource, not the url of the link

### What is actually happening?
The link to the address has been changed

---
Different to attribute values have been tried without exception, for example:

```
to="'/workbench'"
to="{path: '/workbench'}"
```

**Comment by LinusBorg** [comment]
just correct the `base` setting in router.js to whatever you want it to be.

**Comment by hookszhang** [comment]
It works for me. Thanks.
