### ISSUE TITLE
No command 'vue' found - Ubuntu 16.04

### ISSUE THREAD

**Issue by francisco-gamonal** [vuejs/vue-cli#275]
Step by step

1.- Tech: node v7.0.0, npm v3.10.8.
2.- Installation $sudo npm i -g vue-cli
/usr/local/bin/bin/vue -> /usr/local/bin/lib/node_modules/vue-cli/bin/vue
/usr/local/bin/bin/vue-list -> /usr/local/bin/lib/node_modules/vue-cli/bin/vue-list
/usr/local/bin/bin/vue-init -> /usr/local/bin/lib/node_modules/vue-cli/bin/vue-init
/usr/local/bin/lib
└── vue-cli@2.6.0 

3.- Create project
$vue init webpack-simple vue-cli

4.- Error:
No command 'vue' found, did you mean:
 Command 'vpe' from package 'texlive-latex-extra' (universe)
vue: command not found

Any suggestions?
Regards.

**Comment by kazupon** [comment]
In your enviroment, I seem that vue-cli don't through a path.
Did you check vue-cli with `which` command?

**Comment by francisco-gamonal** [comment]
@kazupon thanks for replying, when I type which vue-cli does not display information on the terminal, just like with vue-cli.

**Comment by kazupon** [comment]
I hope you will try to check other CLI tools (`browserity` etc ) which implemented with node.js

**Comment by francisco-gamonal** [comment]
I was able to solve the problem configuring npm of global packages in my home folder.

https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory

Please close.
