### ISSUE TITLE
use `--project tsconfig.json` to suppress lint error

### ISSUE THREAD

**Issue by karlos1337** [vuejs/vue-cli#2755]
### Version
3.0.3

### Node and OS info
Node v10.11.0 / npm 6.4.1 / ArchLinux

### Steps to reproduce
In any vue-cli typescript project with any of this tslint rules ("await-promise", "no-unused-variable", "no-use-before-declare", "return-undefined", "no-floating-promise"...) :

npm run lint

### What is expected?
Not shows any warning

### What is actually happening?
Warning: The 'await-promise' rule requires type information.

Warning: The 'no-unused-variable' rule requires type information.

Warning: The 'no-use-before-declare' rule requires type information.

Warning: The 'return-undefined' rule requires type information.

Warning: The 'no-floating-promises' rule requires type information.

Warning: The 'no-unnecessary-qualifier' rule requires type information.

Warning: The 'no-unnecessary-type-assertion' rule requires type information.

Warning: The 'strict-type-predicates' rule requires type information.

---
https://github.com/alexjoverm/typescript-library-starter/issues/227

**Comment by LinusBorg** [comment]
No reproduction provided.

**Comment by j0h** [comment]
@LinusBorg I am able to replicate this error with the information in *Steps to reproduce* section. I think this is related to https://github.com/vuejs/vue-cli/issues/2712 where a reproduction link is provided.
