### ISSUE TITLE
How do I set the component to be builded like a WebComponent

### ISSUE THREAD

**Issue by luiguild** [vuejs/vue-cli#2758]
### Version
3.0.5

### Node and OS info
node v8.11.4 / yarn v1.9.4  / ubuntu 16.10

### Steps to reproduce
1 - Create a project
2 - Reorganize the components files, rename at all
3 - Run build task

### What is expected?
Build the component set on render function inside main.js into a single JS WebComponent

### What is actually happening?
 ERROR  entry pattern "src/App.vue" did not match any files.

---
I'm not have an "App.vue" file in my "src" folder. I renamed it. I just want an option to set what is my component to be builded

**Comment by LinusBorg** [comment]
Thy snowball explained in the docs. 

If you need help, use forum.vuejs.org to ask for it. 

Closing as it's not a big
