### ISSUE TITLE
Restart vue-cli-service on .env file change

### ISSUE THREAD

**Issue by tecfu** [vuejs/vue-cli#2759]
### What problem does this feature solve?
There is no built-in way to listen for changes to .env files to trigger a reload of the dev server. 

This is especially frustrating when developing withing a docker environment where `npm run server` is the entrypoint. 

### What does the proposed API look like?
vue-cli-service serve --restart-on-env=true

**Comment by LinusBorg** [comment]
> This is especially frustrating when developing withing a docker environment where npm run server is the entrypoint.

I don't understand that specific point.

Also, I have a hard time imagining a scenario where I have to constantly change env variables. rebooting the dev server can't be such a hassle if it's once or twice a day or so?
