### ISSUE TITLE
How the vue-cli ui page search package by algolia?

### ISSUE THREAD

**Issue by lefreet** [vuejs/vue-cli#2761]
### What problem does this feature solve?
it's only a question for help.

I see the code use use algolia in conponent `<NpmPackageSearch />`.

And then I try create a acount, and create a Index, but I found that it only manually data, data file, api three way to create my data.

So, how the algolia fetch npm packages data in vue-cli ?

In my project, I want to create a service to search packages in my privately-npm-registry.

I have try to ask on th forums, but no anwser, have someone can tell me, ? thanks.

### What does the proposed API look like?
no thing

**Comment by LinusBorg** [comment]
As far as I know, this was customized by algolia for us. They do that kind of thing for OSS projects, they're pretty awesome.

You would have to contact algolia to ask if/how/at what price you can get something like that for a private repository.

However I think it would be hard for algolia to index your private repository, as it's, well - private.

**Comment by lefreet** [comment]
@LinusBorg it's too bad. We have a web project like [verdaccio](https://github.com/verdaccio/verdaccio)，and some plugin like `vue-cli-plugin-istrong-publish` for store package into company's register with audit.  In my team，we have some api like `/package/{name}/{version}` develop from ProGet's DB in our server， but there area some workload for us to create a flexible search module，in different page(cli plugin or website),  just like it do in `@vue/cli ui`.  

any way, thanks your anwer.
