### ISSUE TITLE
Not loading scss files globally

### ISSUE THREAD

**Issue by peyman3d** [vuejs/vue-cli#2762]
### Version
3.0.5

### Reproduction link
[https://github.com/peyman3d/config-test](https://github.com/peyman3d/config-test)

### Node and OS info
npm@6.4.1 / macOS 10.14

### Steps to reproduce
npm run dev

### What is expected?
It's expected to load sass files (contains variables) globally and use them in components

### What is actually happening?
Nothing is loaded.

---
First I thought it doesn't load vue.config.js. but when I create an empty project it show an error for not installing sass-loader. Should I register this anywhere or do something more?

I followed this links, but no solutions:

https://cli.vuejs.org/guide/css.html#passing-options-to-pre-processor-loaders
https://vueschool.io/articles/vuejs-tutorials/globally-load-sass-into-your-vue-js-applications/

Thanks.

**Comment by sodatea** [comment]
Your project was bootstrapped by the webpack template for Vue CLI 2 and the documentations are for Vue CLI 3.

For this specific project you need to configure sass-loader manually in the webpack config https://github.com/peyman3d/config-test/blob/master/build/webpack.base.conf.js

**Comment by peyman3d** [comment]
@sodatea Are you saying I should update webpack template?

**Comment by sodatea** [comment]
You should configure webpack by yourself.
A vue-cli-2-inited project is simply a normal project with a few pre-configured webpack config files. Once it's set up, it has nothing to do with vue-cli itself.

If you want to use the utilities provided by Vue CLI 3, you need to install `@vue/cli` and use `vue create project-name` to setup a new project.
