### ISSUE TITLE
Vue cli UI console and create project interface is blank

### ISSUE THREAD

**Issue by xby020** [vuejs/vue-cli#2763]
### Version
3.0.5

### Node and OS info
node V10.11.0/npm V6.4.1/windows 10

### Steps to reproduce
1.  open vue UI interface with cmd "vue ui".
2. Go to Vue Project Manager for create new project,found that the creation interface is blank.
3. Use cmd "vue create project" to create new project;
4. use UI "serve" to start project;
5. The project is running normally,but there is no output on the Output, Console, and Analysis interfaces of the UI interface.

### What is expected?
It seems that it has no effect on project running and hot update, but I don't see any error prompts and running prompts in the UI interface of VUE CLI (even if it still has a pop-up prompt in the lower right corner on win10)

### What is actually happening?
When using vue ui's web interface, the creation project interface is blank, and there is no output in the console part of the project runtime, the project is running normally and can be hot updated. Even CSS is a bit strange.

---
This problem has not been reproduced on my other computer, but I have reinstalled node, npm and vue Cli on this problematic computer. The problem still exists.

**Comment by xby020** [comment]
![20181017155812](https://user-images.githubusercontent.com/26197465/47071179-7eeec400-d225-11e8-81e3-448689ad3d8b.png)

**Comment by sodatea** [comment]
Which browser are you using?

**Comment by xby020** [comment]
> Which browser are you using?

ChromeWebKit 537.36  Chrome 55.0.2883.87
or 360 EXTREME browser

**Comment by xby020** [comment]
Maybe it's a browser issue, the test is normal in the EDGE browser. I will come back to close the issue after I have identified the problem. Shame.

**Comment by allybi-design** [comment]
I Having the same problem...

Vue ui  ->  there's no interface on Chrome

but,

if I use  Vue create<project> ....all's good

any one any idea.
Ps. I've  reinstalled Node & @vue/c;li@3.2.1

Thanks for any help

**Comment by c0h1b4** [comment]
Same here
