### ISSUE TITLE
Unable to install vue-cli.

### ISSUE THREAD

**Issue by adjeteyadjei** [vuejs/vue-cli#277]
npm install --global vue-cli fails

npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-serve@0.1.6 wants grunt@~0.4.0

**Comment by kazupon** [comment]
vue-cli don't have dependency with `grunt`.
I seem there is grunt peerDependencies issue in your npm enviroment.
