### ISSUE TITLE
vue-cli3.0 build请教

### ISSUE THREAD

**Issue by lihrs** [vuejs/vue-cli#2773]
### What problem does this feature solve?
build后index.html文件中会创建很多更页面相关的 link标签
`<link href=css/about.c7d84b65.css rel=prefetch><link href=css/home.72692811.css rel=prefetch><link href=js/about.4039bd28.js rel=prefetch><link href=js/home.50f3d941.js rel=prefetch><link href=css/main.955b4112.css rel=preload as=style><link href=js/chunk-vendors.fa3a8eef.js rel=preload as=script><link href=js/main.9b0a4f3b.js rel=preload as=script>`这是处于什么样的考虑加入这些？

### What does the proposed API look like?
并不需要这些标签

**Comment by zlab** [comment]
```js
config.plugins.delete('preload');
config.plugins.delete('prefetch');
```

**Comment by lihrs** [comment]
OK! 了解了，谢谢!

**Comment by wangyajundev** [comment]
怎样生成这样的文件格式的？vue.condig.js又怎样配置呢？
