### ISSUE TITLE
history模式 publicPath如何配置？（js等静态资源都在别的服务器）

### ISSUE THREAD

**Issue by xuerongzhao** [vuejs/vue-cli#2774]
### Version
3.0.5

### Node and OS info
Node v8.11.1/npm 6.1.0/OSX 10.13.6

### Steps to reproduce
build后的js等文件会放在别的服务器 这类静态资源的路径该如何修改？
在history模式下 修改baseUrl 会影响路由的路径。
之前都是直接修改 webpack的 output.publicPath来达到目的
现在单独修改publicPath 又被禁止 求教怎么解决?

### What is expected?
期待能修改publicPath

### What is actually happening?
无法单独修改output.publicPath

**Comment by LinusBorg** [comment]
router.js -> `base: process.env.BASE_URL` -> `base: '/'` (or similar path)
