### ISSUE TITLE
@vue/cli-plugin-unit-mocha: Module parse failed: Unexpected character '#'

### ISSUE THREAD

**Issue by carlopolisini** [vuejs/vue-cli#2775]
### Version
3.0.5

### Reproduction link
[https://github.com/carlopolisini/bugs-report-code/tree/master/miavue](https://github.com/carlopolisini/bugs-report-code/tree/master/miavue)

### Node and OS info
Node v10.12.0 / npm 6.4.1 / Ubuntu 18.04.1 LTS

### Steps to reproduce
```bash
$ git clone https://github.com/carlopolisini/bugs-report-code.git
$ cd miavue && npm install
$ npm run test:unit
```
### What is expected?
I expect the test passes!

### What is actually happening?

I simply added the mqtt package https://www.npmjs.com/package/mqtt as dependency in HelloWorld.vue and the default HelloWordl test fails.

I load the mqtt in Helloworld.vue:

```javascript
var mqtt = require('mqtt')
export default {
  name: 'HelloWorld',
  props: {
    msg: String
  }
}
```
#### Test output:

WEBPACK  Failed to compile with 1 error(s)

Error in ./node_modules/mqtt/mqtt.js

  Module parse failed: Unexpected character '#' (1:0)
  You may need an appropriate loader to handle this file type.
  > #!/usr/bin/env node
  | 'use strict'
  | 

 ERROR  mocha-webpack exited with code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! miavue@0.1.0 test:unit: `vue-cli-service test:unit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the miavue@0.1.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/carlo/.npm/_logs/2018-10-19T09_55_00_025Z-debug.log

---
npm run serve command is ok, but test:unit it isn't as reported.

**Comment by LinusBorg** [comment]
The package's main file `mqtt.js` is marked as an executable with this first line:
```
#!/usr/bin/env node
```
That's a non-standard line used to mark .js files as executables. So this file doesn't work in a browser.

However there's `"browser"` field hat should give you a different export when used in a browser environment but appearantly webpack doesn't pick it up:
```
"browser": {
    "./mqtt.js": "./lib/connect/index.js",
    "fs": false,
    "tls": false,
    "net": false
},
```

So just do this:
```
var mqtt = require('mqtt/lib/connect/index.js')
```
