### ISSUE TITLE
Travis-CI and Netlify Build Failure Due to environment virables

### ISSUE THREAD

**Issue by medmin** [vuejs/vue-cli#2789]
### Version
3.0.0

### Reproduction link
[https://github.com/whizjs/superjs](https://github.com/whizjs/superjs)

### Node and OS info
yarn 1.2
node v8.12

### Steps to reproduce
You just add `env` part to travis.yml or add Build environment variables on netlify, the build will be failed.

It's not about npm or yarn. I tried both, and builds will be failed as long as the repo has enviroment variables.

And if you delete these virables, the build will be successful, magically. Not a single line of code needs to be changed.

### What is expected?
7:56:02 PM: yarn run v1.3.2
7:56:03 PM: $ vue-cli-service build
7:56:03 PM: /bin/sh: 1: vue-cli-service: not found
7:56:03 PM: error Command failed with exit code 127.

### What is actually happening?
build will be failed

**Comment by medmin** [comment]
I really need to set some env variables.  Please fix it.

**Comment by sodatea** [comment]
Well, I'm no expert on Traivs but I guess it's related to `sudo: enabled` and the user env being overridden.

**Comment by medmin** [comment]
No, sir , sudo is not the culprit.

**Comment by sodatea** [comment]
I mean, don't use sudo for any of your commands…

**Comment by LinusBorg** [comment]
The error that you shared indicates that Travis can't find the vue-cli-service executable when you enable env variables. 

This seems to be a problem with Travis/npm/yarn. We can't solve this in vue-cli-service since our executable isn't even begin run.

**Comment by amejiarosario** [comment]
I ran into the same issue. I had the NODE_ENV=production on Netlify. After, I removed the env variable it worked fine.
