### ISSUE TITLE
关于打包慢的问题

### ISSUE THREAD

**Issue by chaiyanlin** [vuejs/vue-cli#279]
随着项目变大，第三方依赖多以后，打包就越来越慢。
看了网上几种普遍的方式，比如webpack.DllPlugin或者使用happypack等。
但最终好是希望大大能官方提供一个通用方案~

**Comment by egoist** [comment]
webpack 的问题请到相关 template 提出或者 PR，使用问题请利用社区和 Google

**Comment by yyx990803** [comment]
第三方依赖多这就不是 Vue 能管的范围了啊。这是 Webpack 的问题
