### ISSUE TITLE
怎么在vue.config.js中配置引入第三方js全局引入

### ISSUE THREAD

**Issue by yamateH-ch** [vuejs/vue-cli#2799]
### Version
3.0.1

### Node and OS info
10.7.0 / yarn 1.7.0 / Windows 10

### Steps to reproduce
看了官网的config。js配置，发现还是没明白怎么配，
之前版本可以在base。js里面配置别名，在全局引入
 esolve: {
      extensions: ['.js', '.vue', '.json'];
      alias: {
        cmap: path.resolve(__dirname, '../src/utils/cmap')
      }
    };
    plugins: [
      new webpack.ProvidePlugin({
        L: 'leaflet',
        'cmap': 'cmap'
      })
    ]

### What is expected?
可以跟原来引入的效果相同

### What is actually happening?
我在config。js里面
试过在chainWebpack配
config.resolve.alias
     .set('cmap', path.resolve(__dirname, '../src/utils/cmap'))
     .set('L', resolve('leaflet'))
但是在组件直接cmap还是 undefiend
在configureWebpack配
return {
      resolve: {
        alias: {
          'lmap': path.resolve(__dirname, '../src/utils/lmap')
        }
      },
      plugins: [
        new webpack.ProvidePlugin({
          L: 'leaflet',
          'lmap': 'lmap'
        })
      ]
报 This dependency was not found:
To install it, you can run: npm install --save lmap

**Comment by lefreet** [comment]
```
  configureWebpack: {
    plugins: [
      new webpack.ProvidePlugin({
        'L': 'leaflet'
      })
    ]
  }
```

另外注意是不是eslint报错，关闭`package.json`中
```
"eslintConfig": {
  "globals": {
    "L": false    
  }
}
```

**Comment by lefreet** [comment]
Imap已经在全局变量里面了，不用需再`import`,  `console.log(Imap)`试试

**Comment by yamateH-ch** [comment]
![qq 20181024115220](https://user-images.githubusercontent.com/15885021/47405279-6d586f80-d783-11e8-8d7f-10fc4e54c462.png)
![qq 20181024115246](https://user-images.githubusercontent.com/15885021/47405289-72b5ba00-d783-11e8-9e0e-2d1dd4fd8964.png)
还是不行，一直让我npm lmap

**Comment by yamateH-ch** [comment]
(⊙﹏⊙)，我的错，路径些的有问题
