### ISSUE TITLE
`npm install -g vue-cli` is not working?

### ISSUE THREAD

**Issue by Gaohaoyang** [vuejs/vue-cli#28]
when I use `npm install -g vue-cli`, there are some errors and a warning.

```
npm WARN deprecated metalsmith-templates@0.7.0: This package was split into two simpler plugins: metalsmith-layouts and metalsmith-in-place
npm ERR! git -c core.longpaths=true clone --template=C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://github.com/ianstormtaylor/to-camel-case C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\http-github-com-ianstormtaylor-to-camel-case-f206d7eb
npm ERR! git clone --template=C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://github.com/ianstormtaylor/to-camel-case C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\http-github-com-ianstormtaylor-to-camel-case-f206d7eb: Cloning into bare repository 'C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\http-github-com-ianstormtaylor-to-camel-case-f206d7eb'...
npm ERR! git clone --template=C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://github.com/ianstormtaylor/to-camel-case C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\http-github-com-ianstormtaylor-to-camel-case-f206d7eb: fatal: Unable to find remote helper for 'http'
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "vue-cli"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://github.com/ianstormtaylor/to-camel-case C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\http-github-com-ianstormtaylor-to-camel-case-f206d7eb
npm ERR! Cloning into bare repository 'C:\Users\admin\AppData\Roaming\npm-cache\_git-remotes\http-github-com-ianstormtaylor-to-camel-case-f206d7eb'...
npm ERR! fatal: Unable to find remote helper for 'http'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\GitWorkSpace\learn-vue\npm-debug.log
```

So, how to do with this situation?

**Comment by ifrac** [comment]
On Windows 7 I repeated installation three times and it worked for me.

**Comment by yyx990803** [comment]
Upgrade your git version?

**Comment by jbruni** [comment]
Yep. It is a git error: [`Unable to find remote helper for 'http'`](https://www.google.com.br/search?q=Unable+to+find+remote+helper+for+%27http%27&oq=Unable+to+find+remote+helper+for+%27http%27&aqs=chrome..69i57&sourceid=chrome&es_sm=93&ie=UTF-8)

**Comment by looterz** [comment]
I was getting `Error: Cannot find module 'khaos'`. Installing khaos manually worked `npm i -g khaos`.

**Comment by Gaohaoyang** [comment]
Yes, after I upgrade my git version, the problem solved!

I used git version 1.9.5 before, and now is v2.7.0.

Thx. \(^o^)/~

**Comment by danjsul3** [comment]
after installing vue and vue-cli globally, when i run:

vue init webpack my-project

terminal says:

-bash: vue: command not found

others having same issue. any ideas?

**Comment by nagarajanewlife** [comment]
vue init webpack myproject 
but it can say.

bash: vue: command not found

**Comment by antiformatiker** [comment]
> -bash: vue: command not found

Same issue here. I already cleared the npm cache and updated nodejs and npm. Packages were installed inside home directory to avoid permission error. I've run out of ideas...

- nodejs: v8.9.2
- npm: v5.5.1
- os: macosx

Everything works fine on my windows machine.

**Comment by chiholiu** [comment]
I also have the same issue here on my mac. 

NodeJS: v8.9.4
NPM: 5.6.0
Git version 2.14.3 (Apple Git-98)

Anyone here who has the same problem.

**Comment by nagarajanewlife** [comment]
restart your system.




<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by chiholiu** [comment]
I had removed the node_modules and packages.json from my mac and reinstalled vue again.

**Comment by Gargo** [comment]
it is still not fixed

**Comment by roliod** [comment]
@Gargo try using yarn instead `yarn global add @vue/cli`, that worked for me.

**Comment by ConstantFun** [comment]
After nuking my cache, restarting my computer, uninstalling and reinstalling and trying all sorts of other things this is the command that worked for me. 
Thanks

**Comment by roliod** [comment]
@Gaohaoyang Good 👍
