### ISSUE TITLE
全局插件支持

### ISSUE THREAD

**Issue by lefreet** [vuejs/vue-cli#2800]
### What problem does this feature solve?
每次安装插件，除了`cli`内置的外，第三方插件都是针对当前项目，即时安装的，项目量比较多的时候这个过程会很繁琐，需要反复安装，比如有多个`ui-addon`存在时

![image](https://user-images.githubusercontent.com/25679627/47403833-94ac3e00-d77d-11e8-9400-9e4a758cc541.png)

希望支持两个特性：
1. 支持默认加载全局插件，比如：`npm i vue-cli-plugin-istrong -g`  ， 当项目创建后插件，能直接加载插件，`view/addon/service`能被直接调用
2. 通过全局加载的插件，支持ui界面手动调用，以便执行`prompts/generator`

### What does the proposed API look like?
null

**Comment by sodatea** [comment]
谢谢建议，不过这种特性暂无法支持。
1. 插件是项目运行必须的依赖（插件会包含 webpack 配置等），如果从全局安装包里加载的话，会无法保证项目的其他合作者能在他们的机器上重现同样的项目环境。
2. 现在包管理器一般都有全局缓存，多个项目重复安装同一个依赖的速度应该会很快。

**Comment by lefreet** [comment]
@sodatea  无法保障多个项目对不同版本插件的依赖一致，安装到全局的确不太合理；之前收到同事包安装较慢的反馈，大概是因为版本迭代太快导致没缓存。 多谢解答
