### ISSUE TITLE
SyntaxError: Unexpected token ... when yarn run test:e2e with vue-cli

### ISSUE THREAD

**Issue by tea7day** [vuejs/vue-cli#2801]
### Version
3.0.5

### Reproduction link
[https://github.com/tea7day/vuecli-cypress-issue](https://github.com/tea7day/vuecli-cypress-issue)

### Node and OS info
node-v10.0.9, yarn-v1.10.1, macOS High Sierra

### Steps to reproduce
1. create vue project by vue-cli ($vue create myapp -> Manually select features -> add e2e testing(cypress))
2. add vue-apollo plugin ($vue add apollo, default choice)
3. run e2e testing ($yarn test:e2e)

### What is expected?
Tests work

### What is actually happening?
Tests failed because of unknown syntax

**Comment by LinusBorg** [comment]
If that's a problem with the Apollo plugin, please close this issue and open a new one in that plugin's repo. 

Thanks!
