### ISSUE TITLE
must use `entry` when set `title`

### ISSUE THREAD

**Issue by chiaweilee** [vuejs/vue-cli#2816]
### Version
3.0.5

### Node and OS info
Node 8.12

### Steps to reproduce
```
// vue.config.js
module.exports = {
  pages: {
    index: {
      // entry: 'src/main.js' // Error if without 'entry'
      title: 'title here'
    }
  }
}
```

TypeError: Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined

### What is expected?
* use default if entry set is undefined

### What is actually happening?
* Intent to change a title
* Intent to use default entry without set
* And an error told you that you must set entry

**Comment by sodatea** [comment]
It is documented:
> An object that specifies its entry, template, filename, title and chunks (**all optional except entry**);

Nonetheless, the error message could be improved by revising the `vue.config.js` API schema.
