### ISSUE TITLE
Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by jinan5694** [vuejs/vue-cli#2817]
### Version
3.0.5

### Reproduction link
[https://github.com/jinan5694/issue](https://github.com/jinan5694/issue)

### Node and OS info
node v8.12.0 / npm 6.4.1 /windows 8.1

### Steps to reproduce
npm run serve
error on console

### What is expected?
how to fixed this issue?

### What is actually happening?
jsx is not work

---
i see jsx is a default option form vue cli 3.

**Comment by LinusBorg** [comment]
```javascript
// wrong:
return h(<div>hello world</div>)

// right:
return <div>hello world</div>
```

**Comment by jinan5694** [comment]
thanks you!
