### ISSUE TITLE
 vue create --preset  error

### ISSUE THREAD

**Issue by lisiyizu** [vuejs/vue-cli#2823]
vue create --preset git@gitee:lisiyizu/helloworld --clone my-project

![image](https://user-images.githubusercontent.com/12014252/47601979-99395680-da0a-11e8-8653-d760dc59905c.png)

**Comment by lefreet** [comment]
![image](https://user-images.githubusercontent.com/25679627/47611121-a94c4700-da99-11e8-996c-26b1e7e46869.png)
`console`一下应该能分析到原因

**Comment by lisiyizu** [comment]
已经问题都解决了～～～

**Comment by redgang** [comment]
> 了

请问怎么解决的，谢谢！
