### ISSUE TITLE
Error loading saved preferences: ~/.vuerc may be corrupted or have syntax errors. Please fix/delete it and re-run vue-cli in manual mode. (Unexpected end of JSON input)

### ISSUE THREAD

**Issue by Kishor-Kumar-Namdeo** [vuejs/vue-cli#2826]
anyone please give me solution for that
![screenshot from 2018-10-27 18-10-56](https://user-images.githubusercontent.com/38028353/47604288-27b2d580-da15-11e8-9b52-93a99b3fa44a.png)

**Comment by lefreet** [comment]
@Kishor-Kumar-Namdeo try  find the .vuerc file in `~` folder， delete it;  or `uninstall @vue/cli -g` and `install` it again.

**Comment by moh-salah21** [comment]
@lefreet i have the same problem and i tried all of the steps that you says  then the problem  has been not solved.
