### ISSUE TITLE
怎么在vue里面使用blockly(https://github.com/google/blockly)这个库

### ISSUE THREAD

**Issue by wooden1985** [vuejs/vue-cli#2832]
### What problem does this feature solve?
我在index.html里面加入了blockly(https://github.com/google/blockly)库，<script src="../libs/blockly/blockly_compressed.js"></script>
    <script src="../libs/blockly/blocks_compressed.js"></script>
    <script src="../libs/blockly/javascript_compressed.js"></script>
    <script src="../libs/blockly/msg/js/zh-hans.js"></script>,然后在app.vue里面使用blockly里面的接口，报 Blockly is not defined，怎么解决？

### What does the proposed API look like?
是不是要等vue-cli支持blockly库才行？

**Comment by wooden1985** [comment]
库文件要放在public目录下才行

**Comment by qm88888888** [comment]
这种引用blockly会挂载到window对象下面
