### ISSUE TITLE
PWA Android Firefox child components not mounted

### ISSUE THREAD

**Issue by s0By** [vuejs/vue-cli#2833]
### Version
3.0.5

### Node and OS info
yarn 1.9.4

### Steps to reproduce
Install basic template with vue-cli and check PWA. 
Launch on android firefox.
Firefox sees app as PWA and offers to add it to home screen. 
Add it to home screen.

### What is expected?
When you add app to home screen and launch, you should be able to see exactly the same thing that you see on the web.

### What is actually happening?
When you add app to home screen and launch you only see a header nav, which is written straight in App.vue, you don't see any child components until you click on something. Then app launches fully. In case you erase this nav or put it to a child component, then app will be blank.

---
Couldn't find anything related to this issue on the internet and not sure if it's a Vue.js bug in general or Vue-cli bug. I know exactly that this is not Firefox'es issue, because if you go to mobile.twitter.com and add it to home screen as an App, it works nicely.

**Comment by LinusBorg** [comment]
Please provide an actual reproduction. 

Your description is incomplete and not suited to reproduce the problem.
