### ISSUE TITLE
when vue-cli3 use eslint，the warning information is not displayed in the browser console

### ISSUE THREAD

**Issue by 15992033543** [vuejs/vue-cli#2835]
### Version
3.0.5

### Node and OS info
npm6.4.1

### Steps to reproduce
Whether using default configuration or manual configuration：

vue.config.js：

module.exports = {
  lintOnSave: true
}

the warning information is not displayed in the browser console

### What is expected?
show

### What is actually happening?
is not show

**Comment by foxymoron** [comment]
To enable warnings in the overlay. Use vue.config.js as below:
```javascript
module.exports = {
  configureWebpack: {
    devServer: {
      overlay: { warnings: true, errors: true },
    },
  },
};
```
