### ISSUE TITLE
Get remote package version for Plugin Development

### ISSUE THREAD

**Issue by Aircity** [vuejs/vue-cli#2836]
### What problem does this feature solve?
Share get npm package latest version method for Plugin Dev

### What does the proposed API look like?

// generator.js

```
const { getVersionSync } = require('@vue/cli-shared-utils')
module.exports = api => {
  api.extendPackage({
    devDependencies: {
      'cross-env': `^${getVersionSync('cross-env')}`
    }
  })
}
```

**Comment by Akryum** [comment]
I'm honestly not sure it's a good idea. Imagine a new version is out with breaking changes, the user apps may break because a plugin blindly installing the latest version.

**Comment by Aircity** [comment]
Maybe you are right. I am not sure.
