### ISSUE TITLE
VueCli transpileDependencies don't working with custom quilljs blots

### ISSUE THREAD

**Issue by Kolobok12309** [vuejs/vue-cli#2838]
### Reproduction link
[https://github.com/Kolobok12309/quillVue-trouble](https://github.com/Kolobok12309/quillVue-trouble)

### Node and OS info
Node 9.6.1 / Windows 10

### Steps to reproduce
```
npm run serve
```
Go to localhost:8080 and in toolbar click on 'audio file' icon, type something

I try to do some custom blots for quilljs, i import base blots and try extend them, but babel not transpile them, only my customs
and i can't fix it

### What is expected?
After this we must see "audio" block with file (you type link)

### What is actually happening?
Fail in console
``` javascript
Uncaught TypeError: Class constructor L cannot be invoked without 'new'
```
---
Trouble with babel 7, i try fix it a lot of times, but can't, i fix it on custom images and video, by use old class syntax

working
``` javascript
function Image() {}

Image.prototype = Object.create(BaseImage);

Image.prototype.format = function format(name, value) {
    if (~ATTRIBUTES.indexOf(name)) {
        if (value) {
            if (name === 'style') {
                value = sanitizeStyle(value);
            }
            this.domNode.setAttribute(name, value);
        } else {
            this.domNode.removeAttribute(name);
        }
    } else {
        BaseImage.format(name, value);
    }
};
```

not working
``` javascript
export default class Image extends BaseImage {
    static formats(domNode) {
        return ATTRIBUTES.reduce((formats, attribute) => {
            if (domNode.hasAttribute(attribute)) {
                formats[attribute] = domNode.getAttribute(attribute);
            }
            return formats;
        }, {});
    }

    format(name, value) {
        if (~ATTRIBUTES.indexOf(name)) {
            if (value) {
                if (name === 'style') {
                    value = sanitizeStyle(value);
                }
                this.domNode.setAttribute(name, value);
            } else {
                this.domNode.removeAttribute(name);
            }
        } else {
            super.format(name, value);
        }
    }
}
```

But i can't do it in audio/modal modules

**Comment by Kolobok12309** [comment]
Forget say
All working perfectly on quill/master
But quill/master hasn't tables
After going to quill/dev i have this, partly this trouble from quill/dev, but i think babel anyway should transpile

**Comment by LinusBorg** [comment]
I don't understand. ew you saying you are using a development branch of quill? That's likely not guaranteed to be stable so I don't think it makes sense for us to try and make it work.

**Comment by Kolobok12309** [comment]
Yea i know it, but i think babel anyway should transpile es6 classes, mb i'm wrong, sor for it
