### ISSUE TITLE
希望能增加 eslint 配置，使得错误/警告能输出到浏览器控制台的 Console 中

### ISSUE THREAD

**Issue by zoux** [vuejs/vue-cli#2842]
### Version
3.0.5

### Node and OS info
Node 8.11.2 / yarn 5.6.0 / Windows 10

### Steps to reproduce
------

### What is expected?
希望能增加 eslint 配置，使得错误/警告能输出到浏览器控制台的 Console 中

### What is actually happening?
目前的 eslint 配置只能实现输出命令行，或者通过配置 overlay 输出到视图窗口（但阻隔了开发）

---
似乎 vue-cli 2.x 的 eslint-standard 下默认支持这种错误输出方式，希望在 vue-cli 3.x 中也能实现~

**Comment by LinusBorg** [comment]
https://cli.vuejs.org/zh/config/#lintonsave

```
module.exports
 = {
  lintonsave: 'error'
}
```
??
