### ISSUE TITLE
添加 .eslintignore 文件后，git commit -m 'msg' 报错

### ISSUE THREAD

**Issue by luckymore** [vuejs/vue-cli#2846]
### Version
3.0.5

### Reproduction link
Node and OS info
node v8.11.4 / npm 5.6.0 / macOS 10.13.1

### Steps to reproduce
当前.gitignore 
```
/dist
```
现需要把dist整个目录提交到git仓库，同时需要eslint不检查dist目录下的文件，所以新建一个.eslintignore文件
```
/dist
```
但是，git commit -m 'msg'报错
```
> running pre-commit hook: lint-staged
 ❯ Running tasks for *.js
   ✔ vue-cli-service lint
   ✖ git add
     → Use -f if you really want to add them.
 ✔ Running tasks for *.vue
✖ git add found some errors. Please fix them and try committing again.

The following paths are ignored by one of your .gitignore files:
dist
Use -f if you really want to add them.

pre-commit hook failed (add --no-verify to bypass)
```
### What is expected?
期望能正常提交

### What is actually happening?
实际报错
✖ git add
     → Use -f if you really want to add them.

**Comment by sodatea** [comment]
这是 git 的报错，不是 eslint 的报错。
