### ISSUE TITLE
Vue ui open in browser is emtpy

### ISSUE THREAD

**Issue by zuoez02** [vuejs/vue-cli#2849]
### Version
3.0.5

### Node and OS info
Node 8.11.1 / npm 6.1.0 / yarn 1.10.1 / macOS Mojave 10.14

### Steps to reproduce
1. Install @vue/cli and @vue/cli-ui with `$ npm install -g @vue/cli @vue/cli-ui`
2. Start vue ui with `$ vue ui`
3. The browser open a new tab with http://localhost:8000
4. The page is empty. Open the dev tools and see that all js and css file response data is HTML.

### What is expected?
Open the ui

### What is actually happening?
Nothing is displayed

---
I tried to find the homepage and found the route is /dashboard, but the browser open the / automatically. Do we need a redirect?

**Comment by zuoez02** [comment]
The same on task detail page
http://localhost:8000/tasks/*************:serve

**Comment by sodatea** [comment]
I'm sorry but I can't reproduce it locally. Does this still happens with the latest v3.1.1? (BTW you don't have to install `@vue/cli-ui` separately, it's included in `@vue/cli`)

**Comment by Aelentel** [comment]
exactly same behavior from clean install of npm v6.4.1 /Node v10.13.0

> I'm sorry but I can't reproduce it locally. Does this still happens with the latest v3.1.1? (BTW you don't have to install `@vue/cli-ui` separately, it's included in `@vue/cli`)

please don't say something like that without proofs, i'm collecting traces from pristine install and i get exactely the same bug (i'll put a gist i a few minutes time to reproduce from scratch intall)

`PS H:\work\git> node --version
v10.13.0
PS H:\work\git> npm --version
6.4.1
PS H:\work\git> npm install -g @vue/cli
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
E:\Appl\nodejs\vue -> E:\Appl\nodejs\node_modules\@vue\cli\bin\vue.js

> protobufjs@6.8.8 postinstall E:\Appl\nodejs\node_modules\@vue\cli\node_modules\protobufjs
> node scripts/postinstall


> nodemon@1.18.5 postinstall E:\Appl\nodejs\node_modules\@vue\cli\node_modules\nodemon
> node bin/postinstall || exit 0

npm WARN graphql-subscriptions@0.5.8 requires a peer of graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-link-persisted-queries@0.2.1 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-subscriptions@0.5.8 requires a peer of graphql@^0.10.5 || ^0.11.3 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN graphql-tools@3.1.1 requires a peer of graphql@^0.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN @apollographql/apollo-upload-server@5.0.3 requires a peer of graphql@^0.13.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@vue\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @vue/cli@3.1.1
added 668 packages from 501 contributors in 75.093s
PS H:\work\git>`

then running vue ui 
`PS H:\work\git> vue ui
🚀  Starting GUI...
🌠  Ready on http://localhost:8000
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Proxy.join (path.js:432:7)
    at Object.readPackage (E:\Appl\nodejs\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\folders.js:103:24)
    at readPackage (E:\Appl\nodejs\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\dependencies.js:86:20)
    at getLink (E:\Appl\nodejs\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\dependencies.js:194:15)
    at Object.keys.filter.map.id (E:\Appl\nodejs\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\dependencies.js:66:16)
    at Array.map (<anonymous>)
    at findDependencies (E:\Appl\nodejs\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\dependencies.js:61:5)
    at Object.list (E:\Appl\nodejs\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\dependencies.js:44:5)
    at dependencies (E:\Appl\nodejs\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\schema\dependency.js:56:57)
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Proxy.join (path.js:432:7)
    at Object.readPackage (E:\Appl\nodejs\node_modules\@vue\cli\node_modules\@vue\cli-ui\apollo-server\connectors\folders.js:103:24)`

**Comment by zuoez02** [comment]
@sodatea I installed the latest node and npm, then installed the @vue/cli:3.1.1, still reproduced. Open localhost:8000 display nothing. But it resolved the problem when I open task detail page and after refreshed it display othing, while it displays the tasks without details.

It looks like this:
Before refresh: 
http://localhost:8000/tasks/%2FUsers%2Fzuoenzhen%2Fworkspace%2Ffrontend:serve
After refresh
http://localhost:8000/tasks


What I expect is it should redirect to /dashboard when you go to /, and the task detail page is sill displayed after refresh 

------------------------------------
Node Version: v10.13.0
NPM version: 6.4.1
@vue/cli version: 3.1.1
OS: macOS Mojave 10.14
Browser: Chrome 70.0.3538.77

**Comment by Aelentel** [comment]
okay now it worked for me, so either it's a browser cache vs version or something related to updating vue-ui. anyway sorry for the inconvenience.

**Comment by gg4u** [comment]
@zuoez02 did not understand how you solved the issue, I still have black page for javascript enabled is not detected?

(this tools are so powerful but requires an outstanding amount of times to set up thing to actually get them working ... )

**Comment by manojmkv** [comment]
I am also facing the same issue and have no clue from last 2 days. I created the new vue application many times using Vue cli but end result is always same. yarn serve runs perfect but when we build the application using yarn build the index.html inside dist folder contains this error message "We're sorry but test-project doesn't work properly without JavaScript enabled. Please enable it to continue.". let me know if anyone has any idea.

**Comment by LinusBorg** [comment]
> the index.html inside dist folder contains this error message "We're sorry but test-project doesn't work properly without JavaScript enabled. Please enable it to continue.". 

That text is in a `<noscript>` element and just a fallback for visitors that have JS disabled. Nothing is wrong with this, it's supposed to be there in this file.

If you mean something else, please open a proper new issue. This one is over a year old, closed and *not* really describing the same problem.

**Comment by zc3212521** [comment]
Change the port from 8080 to 8081，it worked for me. I opened another program with port 8080.May cause hash conflict

**Comment by Laurent115** [comment]
For me, the page was appearing blank.  But I noticed I had a menu at the bottom of my page.  Clicking on the home icon made it work for me.  

Try going to 'http://localhost:8000/project/select'
