### ISSUE TITLE
vue-cli 3，构建lib模式的时候，怎么才能做到把包按组件进行分割，在使用的时候能按需加载

### ISSUE THREAD

**Issue by xiongxt** [vuejs/vue-cli#2851]
### What problem does this feature solve?
使用公共库的时候，能按需加载

### What does the proposed API look like?
无

**Comment by rockyxia** [comment]
> ### What problem does this feature solve?
> 使用公共库的时候，能按需加载
> 
> ### What does the proposed API look like?
> 无

能解决吗？

**Comment by leafiy** [comment]
babel-plugin-component 做到

**Comment by rockyxia** [comment]
> `babel-plugin-component` 可以做到

这是使用的时候，我是说我自己开发组件库怎么打包成可以被按需加在的

**Comment by minteliuwm** [comment]
楼主解决了吗？我现在也在头疼这个问题。

**Comment by xiongxt** [comment]
> 楼主解决了吗？我现在也在头疼这个问题。
使用babel-plugin-component去加载源码，我是这么解决的

**Comment by leafiy** [comment]
> > `babel-plugin-component` 可以做到
> 
> 这是使用的时候，我是说我自己开发组件库怎么打包成可以被按需加在的

不存这种方式，按需加载是在引用时完成的，`babel-plugin-lodash`和`babel-plugin-antd` 写的比较清楚

**Comment by elvis5** [comment]
> > 楼主解决了吗？我现在也在头疼这个问题。
> > 使用babel-plugin-component去加载源码，我是这么解决的

加载源码打包后体积一样大啊，虽然能实现按需加载，打包后体积没变化

**Comment by leafiy** [comment]
> > > 楼主解决了吗？我现在也在头疼这个问题。
> > > 使用babel-plugin-component去加载源码，我是这么解决的
> 
> 加载源码打包后体积一样大啊，虽然能实现按需加载，打包后体积没变化

tree shaking

**Comment by rockyxia** [comment]
> > > `babel-plugin-component` 可以做到
> > 
> > 
> > 这是使用的时候，我是说我自己开发组件库怎么打包成可以被按需加在的
> 
> 不存这种方式，按需加载是在引用时完成的，`babel-plugin-lodash`和`babel-plugin-import` 写的比较清楚

我说的是比如我是element的开发者，我要用vue cli3来开发一个新的ui组件库，怎么打包成可以被使用者以按需加载的方式使用，不是自己使用，可明白了？

**Comment by leafiy** [comment]
> > > > `babel-plugin-component` 可以做到
> > > 
> > > 
> > > 这是使用的时候，我是说我自己开发组件库怎么打包成可以被按需加在的
> > 
> > 
> > 不存这种方式，按需加载是在引用时完成的，`babel-plugin-lodash`和`babel-plugin-import` 写的比较清楚
> 
> 我说的是比如我是element的开发者，我要用vue cli3来开发一个新的ui组件库，怎么打包成可以被使用者以按需加载的方式使用，不是自己使用，可明白了？

文档都不看全就来？？？

element使用的是自己的开发的`babel-plugin-component` ，对应element的项目结构配置按需引用
https://element.eleme.io/#/zh-CN/component/quickstart 
https://github.com/ElementUI/babel-plugin-component

比如
```
import {Dialog} from  'element'
```

babel插件会自动转成这样，达到按需加载

```
import Dialog from 'element/packages/dialog'
import dialog.css from 'element/css/***'
```

自己照`babel-plugin-component`抄一套不会？

**Comment by minteliuwm** [comment]
> > > > > `babel-plugin-component` 可以做到
> > > > 
> > > > 
> > > > 这是使用的时候，我是说我自己开发组件库怎么打包成可以被按需加在的
> > > 
> > > 
> > > 不存这种方式，按需加载是在引用时完成的，`babel-plugin-lodash`和`babel-plugin-import` 写的比较清楚
> > 
> > 
> > 我说的是比如我是element的开发者，我要用vue cli3来开发一个新的ui组件库，怎么打包成可以被使用者以按需加载的方式使用，不是自己使用，可明白了？
> 
> 文档都不看全就来？？？
> 
> element使用的是自己的开发的`babel-plugin-component` ，对应element的项目结构配置按需引用
> https://element.eleme.io/#/zh-CN/component/quickstart
> https://github.com/ElementUI/babel-plugin-component
> 
> 比如
> 
> ```
> import {Dialog} from  'element'
> ```
> 
> babel插件会自动转成这样，达到按需加载
> 
> ```
> import Dialog from 'element/packages/dialog'
> import dialog.css from 'element/css/***'
> ```
> 
> 自己照`babel-plugin-component`抄一套不会？

或者就用element的这个组件，自己写webpack，把每个组件都打包成js文件，具体可以参照element的打包配置

**Comment by leafiy** [comment]
> > > > > > `babel-plugin-component` 可以做到
> > > > > 
> > > > > 
> > > > > 这是使用的时候，我是说我自己开发组件库怎么打包成可以被按需加在的
> > > > 
> > > > 
> > > > 不存这种方式，按需加载是在引用时完成的，`babel-plugin-lodash`和`babel-plugin-import` 写的比较清楚
> > > 
> > > 
> > > 我说的是比如我是element的开发者，我要用vue cli3来开发一个新的ui组件库，怎么打包成可以被使用者以按需加载的方式使用，不是自己使用，可明白了？
> > 
> > 
> > 文档都不看全就来？？？
> > element使用的是自己的开发的`babel-plugin-component` ，对应element的项目结构配置按需引用
> > https://element.eleme.io/#/zh-CN/component/quickstart
> > https://github.com/ElementUI/babel-plugin-component
> > 比如
> > ```
> > import {Dialog} from  'element'
> > ```
> > 
> > 
> > babel插件会自动转成这样，达到按需加载
> > ```
> > import Dialog from 'element/packages/dialog'
> > import dialog.css from 'element/css/***'
> > ```
> > 
> > 
> > 自己照`babel-plugin-component`抄一套不会？
> 
> 或者就用element的这个组件，自己写webpack，把每个组件都打包成js文件，具体可以参照element的打包配置

我猜你们是想要0配置的即可以 `import ABC from ABC` , 又想`import {B} from 'ABC'` ，不配置插件是不存在的

**Comment by minteliuwm** [comment]
> > > > > > > `babel-plugin-component` 可以做到
> > > > > > 
> > > > > > 
> > > > > > 这是使用的时候，我是说我自己开发组件库怎么打包成可以被按需加在的
> > > > > 
> > > > > 
> > > > > 不存这种方式，按需加载是在引用时完成的，`babel-plugin-lodash`和`babel-plugin-import` 写的比较清楚
> > > > 
> > > > 
> > > > 我说的是比如我是element的开发者，我要用vue cli3来开发一个新的ui组件库，怎么打包成可以被使用者以按需加载的方式使用，不是自己使用，可明白了？
> > > 
> > > 
> > > 文档都不看全就来？？？
> > > element使用的是自己的开发的`babel-plugin-component` ，对应element的项目结构配置按需引用
> > > https://element.eleme.io/#/zh-CN/component/quickstart
> > > https://github.com/ElementUI/babel-plugin-component
> > > 比如
> > > ```
> > > import {Dialog} from  'element'
> > > ```
> > > 
> > > 
> > > babel插件会自动转成这样，达到按需加载
> > > ```
> > > import Dialog from 'element/packages/dialog'
> > > import dialog.css from 'element/css/***'
> > > ```
> > > 
> > > 
> > > 自己照`babel-plugin-component`抄一套不会？
> > 
> > 
> > 或者就用element的这个组件，自己写webpack，把每个组件都打包成js文件，具体可以参照element的打包配置
> 
> 我猜你们是想要0配置的即可以 `import ABC from ABC` , 又想`import {B} from 'ABC'` ，不配置插件是不存在的

https://github.com/minteliuwm/ndc-ui

这是我自己用vue-cli3 搭建的一个组件库，借鉴了element的代码，可以实现按需加载。
