### ISSUE TITLE
vue.config.js配置fs.writeFile写入文件失败问题

### ISSUE THREAD

**Issue by ChasonHong** [vuejs/vue-cli#2852]
### Version
3.1.0

### Node and OS info
npm

### Steps to reproduce
打包生成dist文件成功后fs.writeFile生成一个js文件到dist目录中，现在问题是在vue.config.js配置时先执行了fs.writeFile而dist目录还没生成，提示没有找到目录，无法写入这个js文件？

**Comment by BolinWang** [comment]
@ChasonHong 请问解决了么？这两天我在升级项目配置，vue-cli3我也遇到这个问题

**Comment by woleicom** [comment]
@BolinWang  https://segmentfault.com/a/1190000012840742  可以尝试写webpack插件
