### ISSUE TITLE
Create  a vue project failed with @vue/cli 3.0.5

### ISSUE THREAD

**Issue by kylewell** [vuejs/vue-cli#2855]
### Version
3.0.5

### Node and OS info
node version 10.13.0,npm version 6.4.1 and OS Win10

### Steps to reproduce
Step1:
? Please pick a preset: Manually select features
? Check the features needed for your project:
 (*) Babel
 ( ) TypeScript
 ( ) Progressive Web App (PWA) Support
 (*) Router
 (*) Vuex
(*) CSS Pre-processors
 (*) Linter / Formatter
 ( ) Unit Testing
 ( ) E2E Testing

Step 2:
? Use history mode for router? (Requires proper server setup for index fallback in production) Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Sass/SCSS
? Pick a linter / formatter config: Prettier
? Pick additional lint features: Lint on save
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? (y/N) n

Step3:
✨  Creating project in e:\example\ssomc.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

> yorkie@2.0.0 install e:\example\ssomc\node_modules\yorkie
> node bin/install.js

setting up Git hooks
done

added 1118 packages from 737 contributors in 134.875s
🚀  Invoking generators...
📦  Installing additional dependencies...

> node-sass@4.9.4 install e:\example\ssomc\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\kyle\AppData\Roaming\npm-cache\node-sass\4.9.4\win32-x64-64_binding.node

> node-sass@4.9.4 postinstall e:\example\ssomc\node_modules\node-sass
> node scripts/build.js

Binary found at e:\example\ssomc\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine
added 127 packages from 106 contributors, updated 2 packages and moved 1 package in 55.58s
 ERROR  Error: No files matching 'tests' were found.
Error: No files matching 'tests' were found.
    at resolvedPathsByGlobPattern.reduce (e:\example\ssomc\node_modules\eslint\lib\util\glob-utils.js:244:19)
    at Array.reduce (<anonymous>)
    at Object.listFilesToProcess (e:\example\ssomc\node_modules\eslint\lib\util\glob-utils.js:242:59)
    at CLIEngine.executeOnFiles (e:\example\ssomc\node_modules\eslint\lib\cli-engine.js:513:36)
    at lint (e:\example\ssomc\node_modules\@vue\cli-plugin-eslint\lint.js:47:25)
    at api.onCreateComplete (e:\example\ssomc\node_modules\@vue\cli-plugin-eslint\generator\index.js:106:25)
    at Creator.create (C:\Users\kyle\AppData\Roaming\npm\node_modules\@vue\cli\lib\Creator.js:176:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)

### What is expected?
The error should not occur.

### What is actually happening?
There was error occured

**Comment by donbot-inc** [comment]
Dublicate of #2854
