### ISSUE TITLE
【typescript】在vue单文件组件下识别不了node_modules 里@types中的index.d.ts

### ISSUE THREAD

**Issue by isenlover** [vuejs/vue-cli#2859]
### Version
3.1.0

### Node and OS info
node v8.9.3   npm v6.4.1

### Steps to reproduce
1、create vue xxx <br/>
2、npm i echarts -D <br/>
3、npm i @types/echarts <br/>

IDE：webstorm  <br/>
问题：在vue单文件里 import * as echarts from 'echarts'是无法获得代码提示的，例如echarts.init
但是在单独的ts文件里就可以 <br/>
另外，如果把echarts @types的index.d.ts移动到项目里，import echarts才能获得代码提示 <br/>

请问下需要怎么设置才能让npm @types/xxx 在vue单文件里获得webstorm提示   <br/>

ps：echarts只是举例，任意npm @types/xxx 都无法获得提示，开发速度大大降低

### What is expected?
需要怎么设置才能让npm @types/xxx 在vue单文件里获得webstorm提示

### What is actually happening?
目前没有任何代码提示

**Comment by sodatea** [comment]
如果只是没有代码提示，而编译一切正常的话，那这是 WebStorm 的问题，与 Vue CLI 无关，请给 WebStorm 反馈意见。
