### ISSUE TITLE
关于vue.config.js的生成问题,是要自己生成一个vue.config.js文件么

### ISSUE THREAD

**Issue by liucien** [vuejs/vue-cli#2867]
### Version
3.1.1

### Node and OS info
Node.js 8.10.0

### Steps to reproduce
使用vue ui指令，默认配置，生成项目后无vue.config.js文件

### What is expected?
应该是有的

### What is actually happening?
无

**Comment by liucien** [comment]
![image](https://user-images.githubusercontent.com/32785166/47844497-91f4bd00-ddfd-11e8-9f38-4c5ffda4cdd7.png)
完成后一直这样，缺少vue.config.js文件

**Comment by liucien** [comment]
![image](https://user-images.githubusercontent.com/32785166/47844613-c9636980-ddfd-11e8-8a2f-a50596f6c28d.png)
wan完成后就这样，没有vue.config.js文件

**Comment by haitaodesign** [comment]
自己创建

**Comment by sodatea** [comment]
使用默认配置的话不需要 vue.config.js 文件，否则自行创建一个。

> vue.config.js 是一个可选的配置文件，如果项目的 (和 package.json 同级的) 根目录中存在这个文件，那么它会被 @vue/cli-service 自动加载。

文档如果不够清楚的话可以给我们提一下哪里可以改进……

**Comment by sodatea** [comment]
随时都能创建。它是可选的。

**Comment by liucien** [comment]
能具体说一下么，通过ui界面的方式半天没找着，谷歌也谷歌不出来[捂脸]

**Comment by sodatea** [comment]
我的意思是你自己创建一个……

**Comment by sodatea** [comment]
自己创建的意思就是自己在项目目录下新建一个文件……

**Comment by sodatea** [comment]
UI 的话除非你改了某些只能通过 vue.config.js 进行设置的开关项不然我们也不会帮你自动创建的。

**Comment by liucien** [comment]
好吧，我还以为能够一站式服务......麻烦你了...

**Comment by xiaomizhou66** [comment]
文档没有说明是自己创建的，查阅网上的文章才知道是自己创建的
