### ISSUE TITLE
Uncaught SyntaxError: Use of const in strict mode. at http://xxx.com/js/chunk-vendors.b186bd1a.js:1

### ISSUE THREAD

**Issue by tkggusraqk** [vuejs/vue-cli#2870]
### Version
3.0.5

### Reproduction link
[https://github.com/tkggusraqk/test](https://github.com/tkggusraqk/test)

### Node and OS info
node:10.4.0,npm:6.1.0,android:4.4.3

### Steps to reproduce
1. npm run build
2. 手机浏览器打开，页面空白（错误：Uncaught SyntaxError: Use of const in strict mode.）

### What is expected?
调试的时候，手机浏览是正常的

### What is actually happening?
打包后，手机浏览不正常

**Comment by sodatea** [comment]
You should use [`jquery`](https://www.npmjs.com/package/jquery) instead of [`jQuery`](https://www.npmjs.com/package/jQuery)

**Comment by tkggusraqk** [comment]
@sodatea Thank you

**Comment by miduoN** [comment]
我没使用jquery 也出现这问题
