### ISSUE TITLE
创建新项目时，如果选用自定义配置，项目就无法热更新。

### ISSUE THREAD

**Issue by yangzhuq** [vuejs/vue-cli#2873]
### Version
3.0.0-rc.10

### Node and OS info
node 8.11.3/  npm 5.6.0

### Steps to reproduce
创建项目时选用自定义配置，在选用babel、routeres、CSS Pre-processor 后再加上Linter / Formatter配置的话，就无法热更新。如果没有选用Linter / Formatter配置则正常

### What is expected?
项目创建完以及运行时都没有给出错误提示。在运行vue ui后才发现有个警告 Couldn't parse bundle asset "E:\worker\colorlife-wap\dist\about.e9d3e2ce69799effc7d1.hot-update.js".
Analyzer will use module sizes from stats file.

**Comment by sodatea** [comment]
请更新到最新版本后再确认是否有问题。如果还有问题请提供可以复现的代码仓库。

**Comment by yangzhuq** [comment]
重装并更新了版本node v8.12.0/ npm v6.4.1/vue v3.1.0并且重装过编辑器VSCode依然没有解决问题，
项目在另外的电脑上测试也是同样的问题，这是可以复现问题的仓库[demo](https://github.com/yangzhuq/demo.git)。

**Comment by haoyinag** [comment]
请问解决了吗，我也遇到同样的问题

**Comment by CaiPeng1989** [comment]
> 重装并更新了版本node v8.12.0/ npm v6.4.1/vue v3.1.0并且重装过编辑器VSCode依然没有解决问题，
> 项目在另外的电脑上测试也是同样的问题，这是可以复现问题的仓库[demo](https://github.com/yangzhuq/demo.git)。

拉取你的项目，用 `npm` 安装依赖后，发现确实不能热更新，不管 `vue.config.js` 里面 `derServer.hot` 为 `true` 和 `false`，都不行。
但是让我迷惑的是，删除 `node_modules` 后，用 `yarn` 重新安装依赖，就能够热更新了。
我又把  `node_modules` 和 `package-lock.json` 删掉，用 `npm` 安装了依赖，又不行了。
迷茫ing...

**Comment by haoyinag** [comment]
官方修复了

**Comment by yangzhuq** [comment]
> 
> 
> 官方修复了

升级vue cli的3.1.1版本吗？

**Comment by haoyinag** [comment]
> > 官方修复了
> 
> 升级vue cli的3.1.1版本吗？

我刚又不行了，因为项目有报错或者警告就不能热更新，然后修正之后也不行；
然后推出，重新npm run dev又可以了，所以初步怀疑是跟eslint关联之后做的处理

**Comment by yangzhuq** [comment]
> > 重装并更新了版本node v8.12.0/ npm v6.4.1/vue v3.1.0并且重装过编辑器VSCode依然没有解决问题，
> > 项目在另外的电脑上测试也是同样的问题，这是可以复现问题的仓库[demo](https://github.com/yangzhuq/demo.git)。
> 
> 拉取你的项目，用 `npm` 安装依赖后，发现确实不能热更新，不管 `vue.config.js` 里面 `derServer.hot` 为 `true` 和 `false`，都不行。
> 但是让我迷惑的是，删除 `node_modules` 后，用 `yarn` 重新安装依赖，就能够热更新了。
> 我又把 `node_modules` 和 `package-lock.json` 删掉，用 `npm` 安装了依赖，又不行了。
> 迷茫ing...
我这边试过用yarn 安装同样不行。

**Comment by yangzhuq** [comment]
> 请更新到最新版本后再确认是否有问题。如果还有问题请提供可以复现的代码仓库。

我这边升级到最新3.1.1版本后 ，安装eslint没有问题了，但是加上e2e测试又是同样的问题。

**Comment by sodatea** [comment]
刚找到原因，是因为 @vue/cli-service v3.1.0 升级了 webpack 的最低版本要求，而 @cypress/webpack-preprocessor 的 webpack 依赖是固定版本号的，最终导致项目中出现两个 webpack 实例，因此热更新失败……
稍晚些时候会修复这个问题。

**Comment by zicong-zhang** [comment]
静候修复

**Comment by 269378737** [comment]
这个问题修复了么？我今天将vue cli3 更新到最新版本，新创建的项目仍然无法热更新。

**Comment by QiangDongxiao** [comment]
版本3.2.1，手动选择配置。依旧无法热更新

**Comment by 269378737** [comment]
@sodatea 谢谢你的帮助，确实帮我解决了这个问题！

**Comment by QiangDongxiao** [comment]
@sodatea 使用yarn 修改了webpack-server版本还是不能实现热更新，版本3.2.1，vs code开发

**Comment by sodatea** [comment]
@QiangDongxiao 请提供复现并另开 issue

**Comment by nan1010082085** [comment]
我更新了我项目中所有的包， 本地vue/cli 和 vue/cli-serivce 但是webpack 依然不能热更新， 我需要怎么做？

**Comment by xiaojinwen** [comment]
devServer: {
		disableHostCheck: true, // 禁用webpack热重载检查 解决热更新失效问题
}

**Comment by xiaojinwen** [comment]
https://github.com/vuejs/vue-cli/issues/3173

**Comment by aiyuchen** [comment]
![image](https://user-images.githubusercontent.com/578141/60668432-8bdc4200-9e9e-11e9-8e04-08d4ffa3a7cf.png)
@xiaojinwen 没用啊

**Comment by sodatea** [comment]
@aiyuchen 你截图里的警告信息应该和热更新没有关系

**Comment by innnnii** [comment]
> ![image](https://user-images.githubusercontent.com/578141/60668432-8bdc4200-9e9e-11e9-8e04-08d4ffa3a7cf.png)
> @xiaojinwen 没用啊
请问这个问题你解决了吗是怎么解决的呀~

**Comment by chinaborg** [comment]
还是存在这个问题呢

**Comment by bkkkd** [comment]
还存在

**Comment by AndersonYTD** [comment]
> > ![image](https://user-images.githubusercontent.com/578141/60668432-8bdc4200-9e9e-11e9-8e04-08d4ffa3a7cf.png)
> > @xiaojinwen 没用啊
> > 请问这个问题你解决了吗是怎么解决的呀~
我把后面3个从下往上全运行一遍就好了

**Comment by chinaborg** [comment]
已经放弃了，不影响运行



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AndersonYTD"<notifications@github.com&gt;; 
发送时间: 2020年3月3日(星期二) 下午4:09
收件人: "vuejs/vue-cli"<vue-cli@noreply.github.com&gt;; 
抄送: "borg"<827651350@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [vuejs/vue-cli] 创建新项目时，如果选用自定义配置，项目就无法热更新。 (#2873)



  

 @xiaojinwen 没用啊
 请问这个问题你解决了吗是怎么解决的呀~
 我把后面3个从下往上全运行一遍就好了

**Comment by AndersonYTD** [comment]
> > ![image](https://user-images.githubusercontent.com/578141/60668432-8bdc4200-9e9e-11e9-8e04-08d4ffa3a7cf.png)
> > @xiaojinwen 没用啊
> > 请问这个问题你解决了吗是怎么解决的呀~
![image](https://user-images.githubusercontent.com/59470222/75755408-8276e280-5d69-11ea-94bf-4cdc84e14a9d.png)
我把后面三个从下往上运行一遍就好了

**Comment by AndersonYTD** [comment]
> 已经放弃了，不影响运行
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "AndersonYTD"<notifications@github.com&gt;; 发送时间: 2020年3月3日(星期二) 下午4:09 收件人: "vuejs/vue-cli"<vue-cli@noreply.github.com&gt;; 抄送: "borg"<827651350@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [vuejs/vue-cli] 创建新项目时，如果选用自定义配置，项目就无法热更新。 (#2873) @xiaojinwen 没用啊 请问这个问题你解决了吗是怎么解决的呀~ 我把后面3个从下往上全运行一遍就好了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好吧

**Comment by kely2019** [comment]
> > > ![image](https://user-images.githubusercontent.com/578141/60668432-8bdc4200-9e9e-11e9-8e04-08d4ffa3a7cf.png)
> > > @xiaojinwen 没用啊
> > > 请问这个问题你解决了吗是怎么解决的呀~
> > > ![image](https://user-images.githubusercontent.com/59470222/75755408-8276e280-5d69-11ea-94bf-4cdc84e14a9d.png)
> > > 我把后面三个从下往上运行一遍就好了

全部运行一遍还是没解决警告

**Comment by sodatea** [comment]
这个警告不会影响使用。
根源是 fork 的这份代码 https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/webpack/analyzeBundle.js 继承了上游的这个问题 https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/147 各位如果有兴趣可以研究一下怎么解决，欢迎提 PR

**Comment by Anymo123** [comment]
你好，这个问题解决了吗？因为我刚刚又遇到了这个问题

**Comment by Anymo123** [comment]
> 官方修复了

重复遇到？是又出问题了吗

**Comment by AcquireKnown** [comment]
> > > > ![image](https://user-images.githubusercontent.com/578141/60668432-8bdc4200-9e9e-11e9-8e04-08d4ffa3a7cf.png)
> > > > @xiaojinwen 没用啊
> > > > 请问这个问题你解决了吗是怎么解决的呀~
> > > > ![image](https://user-images.githubusercontent.com/59470222/75755408-8276e280-5d69-11ea-94bf-4cdc84e14a9d.png)
> > > > 我把后面三个从下往上运行一遍就好了
> 
> 全部运行一遍还是没解决警告

所以这个问题怎么解决啊？

**Comment by Anymo123** [comment]
忽视或者等待3.0。

**Comment by AcquireKnown** [comment]
我创建项目配置的时候选的就是vue3.x啊
