### ISSUE TITLE
How can i add preload/prefetch for img,font,or other files?

### ISSUE THREAD

**Issue by Trendymen** [vuejs/vue-cli#2874]
### What problem does this feature solve?
The preload-plugin can add preload/prefetch hint for js and css, and i can see outher types's default 'as' properties in this plugin's resources code, but i didn't find files that is not type of js and css in compilation.chunks[chunk].files when i debug.

The plugin's documents also dont show how to handle this problem.

I know i can set the options.include to "allAsstes" to add hints for all files,but i don't want to add hints for all files,just for some files that need to be rendered first.

### What does the proposed API look like?
I suggest there are should be a options in this plugin to resolve this problem.

**Comment by LinusBorg** [comment]
I'm not awware of a feature to do this with webpack, and I personally don't feel we need it.

**Comment by Trendymen** [comment]
> I'm not awware of a feature to do this with webpack, and I personally don't feel we need it.

**Comment by Trendymen** [comment]
All right, i think i have figure out it,just use include:"all Assets" and fileWhitelist to filter files that i want to add hints on.
