### ISSUE TITLE
baseUrl should handle full urls

### ISSUE THREAD

**Issue by dsanders11** [vuejs/vue-cli#2877]
### What problem does this feature solve?
Per the docs, "The base URL your application bundle will be deployed at. This is the equivalent of webpack's output.publicPath". In the [webpack docs](https://webpack.js.org/configuration/output/#output-publicpath) it's clear full urls are valid, one of the examples is 'https://cdn.example.com/assets/'.

From the [docs for `devServer.publicPath`](https://webpack.js.org/configuration/dev-server/#devserver-publicpath-): "It is also possible to use a full URL. This is necessary for Hot Module Replacement." The point about HMR is clear when you look at [issue 2525](https://github.com/vuejs/vue-cli/issues/2525#issuecomment-421573105), where the HMR is using the wrong URL for updates.

Setting `baseUrl` to a full URL results in a message from `vue-cli-service serve` such as:

>   App running at:
>  - Local:   https://localhost:8443/https://other-address.local/

It *does* fix the HMR issue, since it plumbs down correctly, but `vue-cli` isn't treating it as the full URL that it is.

If `baseUrl` is the equivalent of webpack's `output.publicPath` as the docs say, then it must correctly handle full URLs. Otherwise they are not equivalent.

### What does the proposed API look like?
N/A

**Comment by LinusBorg** [comment]
Thanks for bringing this up. It should be a bug report though - quite obviously, at least the console output is not right.

**Comment by sodatea** [comment]
Fixed in https://github.com/vuejs/vue-cli/pull/2900
