### ISSUE TITLE
Conditional prompt questions

### ISSUE THREAD

**Issue by erguotou520** [vuejs/vue-cli#289]
I have a `list` prompt in the question, choices are `A` and `B`. I want to show the following 2 prompts when user chose `A` and to show the next following 2 question when user chose `B`, how to do this?  
It seems that `vue-cli` doesn't support functional `when`? In the following code, I just return false in `when` function, but it still prompts.
```
when: function (answer) {
  return false
}
```

**Comment by posva** [comment]
You should be able to do `when: 'lint === true'`
ref https://github.com/vuejs/vue-cli#conditional-prompts

**Comment by erguotou520** [comment]
The doc doesn't tell this function, I'll try it.
