### ISSUE TITLE
Option to run webpack plugin at the end od build

### ISSUE THREAD

**Issue by lukchojnicki** [vuejs/vue-cli#2890]
### What problem does this feature solve?
I want to run plugin, CopyWebpackPlugin to be precise (but not only), at the end of build process so I could manipulate with build assets. Now if use configureWebpack: { plugins: [] } my copy plugin will run at beginning, and it cannot find my assets because their are not build yet.

When I do "inspect > inspect.js" then I can see that generaated config already uses CopyWebpackPlugin at the end, and it copies public directory to dist directory. So I want run another CopyWebpackPlugin AFTER that. How I can achieve that?

### What does the proposed API look like?
I do not know

**Comment by LinusBorg** [comment]
> How I can achieve that?

Please use forum.vuejs.org or chat.vuejs.org for questions.
