### ISSUE TITLE
HMR stopped working with update to cli 3.1.0

### ISSUE THREAD

**Issue by katonada** [vuejs/vue-cli#2892]
### Version
3.1.1

### Reproduction link
[fake url: https://create_new_project from cli_or_ui](https://create_new_project from cli_or_ui)

### Node and OS info
win 10, chrome 70, node 8.12.0, (node 10.13.0, npm 6.4.1 four different PCs)

### Steps to reproduce
Create a new project with Vue CLI ur UI (UI/Create, VUE create), start the project with either `npm run serve` or vue UI > tasks > serve

### What is expected?
Hot reload after any file (JS, VUE, SCSS) changed

### What is actually happening?
Nothing happens, no errors in chrome, no hot injection or reload

---
Stopped to inject/reload after updating to Vue-Cli 3.1.0

**Comment by LinusBorg** [comment]
Works for me.

Have you completely whiped node_modules an reinstalled anything? Did you change the location of your project, i.e. moved it to dropbox or anything?

**Comment by sodatea** [comment]
Did you choose e2e testing with cypress when creating the project?

**Comment by sodatea** [comment]
As @vue/cli-service v3.1 updated its webpack version resolution, it conflicts with @cypress/webpack-preprocessor's webpack dependency version, leading to 2 instances of webpack in the project dependency tree. That's why the HMR fails. This will be fixed in the next patch release.

**Comment by katonada** [comment]
@LinusBorg yes, I tried everything I can imagine.
- delete node_modules, a new folder for the project
- delete all global npm & npm_cache
- updated node & npm

I'm not sure (i had many variants ...), some test app templates (test, default, custom) have hot-reload and some not, I wasn't careful so I'll try one by one again.

One thing I notice in the console (when hot-reload is not working) is:
```
Couldn't parse bundle asset "E:\-----projects\frontend_app\dist\0.js".
Analyzer will use module sizes from stats file.
```
I think that is webpack-bundle-analyzer problem.

@sodatea - yes, I have cypress installed, should I uninstall it?

**Comment by katonada** [comment]
After removing Cypress and downgrade cli-service to 3.0.5 (just removing Cypress, `webpack` dependency is removed too) HMR is working again.
@LinusBorg @sodatea thnx for the hints. I am waiting for the next update now.

**Comment by katonada** [comment]
@LinusBorg : my bad, I wasn't sure why some test projects works and other not so I instaled a fresh copy of test app on a new virtual machine and its work, on normal windows and on my wife's PS test app didn't work, my project didn't work on all three environments and I was not sure what is wrong and witch repo to send.
