### ISSUE TITLE
Redundant JS file is being generated

### ISSUE THREAD

**Issue by dvlden** [vuejs/vue-cli#2898]
### Version
3.1.1

### Node and OS info
node 11.0.0 / npm 6.4.1 / macOS 10.14.1

### Steps to reproduce
I'd hate creating a dummy repository just to reproduce this. 
It's fairly simple to do so... 

• Generate a project using Vue CLI
• Create a `vue.config.js` file
• Add the following snippet into the config file

```
module.exports = {
  chainWebpack: config => {
    config
      .entry('app')
        .add('./src/assets/styles/app.scss')
        .end()
      .entry('vendor')
        .add('./src/assets/styles/vendor.scss')
      .end()
  }
}
```

* P.S. Of course, you'll need to create `assets/styles/app.scss` and `assets/styles/vendor.scss` files within the `src` directory.

App is being generated perfectly, as by default our `main.js` file is an entry for `app` as well.
However, the vendor part has issues...

### What is expected?
It should only generate the vendor CSS file as specified in the entry point.

### What is actually happening?
It generates both CSS and JS vendor files.  
The JS file contains only module boilerplate and is being injected to the `html` template, but we did not specify such file in entry point.

**Comment by LinusBorg** [comment]
That's because webpack can only handle JavaScript for entry points. 

In other words: for every entry, the resulting bundle will have a JavaScript file as the main entry. 

The webpack team announced that css files should become "first classes citizens" in some way in one of the next majors.
