### ISSUE TITLE
hi，关于vue-cli的建议想法

### ISSUE THREAD

**Issue by AnyGong** [vuejs/vue-cli#29]
目前看到所有的vue工具都是基于单页应用的模式构建，想问一下，能不能有一个多页项目的应用，目前在这块用vue和webpack，构建多页应用的的时候遇到了瓶颈，希望作者有好的方案和建议，不甚感激~

**Comment by yyx990803** [comment]
具体瓶颈可以到论坛上讨论，也可以 fork 官方的 webpack 模板加上针对多页的改动。vue-cli 只是负责拉模板而已。

**Comment by AnyGong** [comment]
@yyx990803 very tks!
