### ISSUE TITLE
vue-cli-service serve --mode kaifa  is't expected?

### ISSUE THREAD

**Issue by lisiyizu** [vuejs/vue-cli#2901]
### Version
3.1.1

### Reproduction link
[http://localhost](http://localhost)

### Node and OS info
node 8.9

### Steps to reproduce
scripts:{
     "build-kaifa": "vue-cli-service serve --mode kaifa"
}

vue ui -> build-kaifa

### What is expected?
$ vue-cli-service serve --mode kaifa --open --dashboard
 INFO  Starting kaifa server...

### What is actually happening?
$ vue-cli-service serve --mode kaifa --open --dashboard
 INFO  Starting development server...

**Comment by LinusBorg** [comment]
It's starting a development server in mode "kaifa", so I don't see anything wrong.
