### ISSUE TITLE
`vue upgrade` asks user to install `@vue/cli-upgrade`  globally, but `@vue/cli-upgrade` is not available on NPM. 

### ISSUE THREAD

**Issue by zerkz** [vuejs/vue-cli#2909]
### Version
3.1.1

### Node and OS info
node 10.10, npm  6.4.1, Ubuntu 18.10

### Steps to reproduce

1) `vue upgrade`
2) `npm install -g @vue/cli-upgrade`

Produces:
```
npm ERR! code E404
npm ERR! 404 Not Found: @vue/cli-upgrade@latest
```

### What is expected?
It is expected that this module would exist on NPM. 

### What is actually happening?
We are told to install a module that is not published on NPM, so NPM 404s and `vue upgrade` results in the same message about installing `@vue/cli-upgrade` .

**Comment by CaiPeng1989** [comment]
Now `npm` has this package.
