### ISSUE TITLE
auto remove the space of Enter key, How do I cancel it?

### ISSUE THREAD

**Issue by libbGit** [vuejs/vue-cli#2910]
vue cli 2.0+
<template>
       <span>1</span>
       <span>2</span>
</template>
now i open browser, found the **separation** between first span and second span.  it caused by Enter key. it's normal performance.

vue cli 3.0+
<template>
       <span>1</span>
       <span>2</span>
</template>
now i open browser, found the **no separation** between first span and second span.  it seems like remove the Enter key. and second span directly float.   why?

so can i remove this **Feature** by vue.config.js or any others configuration? 
I'm glad to accept you reply. thank you.

**Comment by sodatea** [comment]
https://github.com/vuejs/vue-cli/issues/1020#issuecomment-412338405
