### ISSUE TITLE
Question ：about 'vue list'

### ISSUE THREAD

**Issue by zhaozhe0831** [vuejs/vue-cli#292]
使用 vue list 命令时，得到的结果跟预期不一致。貌似是 github api 屏蔽了我的 IP 吗？

I have a question about 'vue list'.

![image](https://cloud.githubusercontent.com/assets/12945873/21922647/9f76ad84-d9aa-11e6-8e25-9f884e25411e.png)

**Comment by egoist** [comment]
try it later, github api has rate limit.

**Comment by zhaozhe0831** [comment]
可以用 vue init，但是 vue list 不能用。
![image](https://cloud.githubusercontent.com/assets/12945873/22097822/19f3100e-de5e-11e6-9f73-5845e18f7939.png)
