### ISSUE TITLE
使用vue ui安装lodash（大）依赖包时，一直处于安装中

### ISSUE THREAD

**Issue by Blueria** [vuejs/vue-cli#2926]
### Version
3.0.5

### Node and OS info
Node 8.12.0 / npm 6.4.1 / Windows 10

### Steps to reproduce
使用vue ui安装依赖包，搜索到lodash官方依赖包（体积大概60多M），然后安装此依赖时，一直处于安装中，无法退出，无法放弃，后来重试刷新网页也不行。

最后的解决办法是：终止vue ui，去掉package.json中的依赖项，重新运行vue ui才得以放弃。

不知道安装其他大的依赖包时，会不会也出现这样的情况。

### What is expected?
如果迟迟无法安装完，是不是得有个中途放弃按钮？

### What is actually happening?
足足有半小时以上都没安装结束！

**Comment by RyanLiu0235** [comment]
建议更换一个npm源，lodash是一个非常常用的工具库。

**Comment by Blueria** [comment]
@RyanLiu0235 @CaiPeng1989 
一直用的就是taobao的源
vue ui 是可以选择taobao源的

**Comment by CaiPeng1989** [comment]
@Blueria 我这边不会出现卡住的情况，你解决了吗？

**Comment by Blueria** [comment]
@CaiPeng1989 我目的是提建议，问题肯定不能因为我解决了就终止了
如果别人碰到了类似的问题，中途也不能放弃，还得来问这个问题。
