### ISSUE TITLE
Integrate fast-sass-loader as an optional SASS loader

### ISSUE THREAD

**Issue by ipartola** [vuejs/vue-cli#2928]
### What problem does this feature solve?
fast-sass-loader (https://github.com/yibn2008/fast-sass-loader) is claimed to be significantly faster than the standard sass-loader. It would be great to have it as an option for production builds.

### What does the proposed API look like?
I think it should be an option you select when initializing a new project. It should be controlled by a setting in vue.config.js.

**Comment by LinusBorg** [comment]
That's too specific. Either we switch to this loader or we keep the current one. 

Offering this a choice would be another level in the decision tree whelm sting a project that makes it too complicated imho.
