### ISSUE TITLE
transition无过度效果

### ISSUE THREAD

**Issue by wanghaolu** [vuejs/vue-cli#293]
使用vue-cli初始化项目后copy [https://cn.vuejs.org/v2/guide/transitions.html](https://cn.vuejs.org/v2/guide/transitions.html) 的代码到hello.vue中然后运行，发现没有任何过度效果。不知道这个问题属于vue-cli的还是vuejs的，就先发到这里来

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted on the [forum](https://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.
