### ISSUE TITLE
源码疑惑

### ISSUE THREAD

**Issue by choukin** [vuejs/vue-cli#2933]
### Version
3.1.1

### Node and OS info
Node 10.7.0 / yarn 1.7.0 / Windows 10

### Steps to reproduce
源码学习

### What is expected?
不明白源码里 

```js
 // vue-cli/packages/@vue/cli/lib/Creator.js 中
    this.emit('creation', { event: 'plugins-install' })
   .....
   this.emit('creation', { event: 'invoking-generators' })
```
这个触发的事件在哪里执行的？

### What is actually happening?
没读懂，希望有人给解答下

**Comment by sodatea** [comment]
用于 @vue/cli-ui
https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-ui/apollo-server/connectors/projects.js#L95
