### ISSUE TITLE
vue create FrontDemo  error occured

### ISSUE THREAD

**Issue by lisiyizu** [vuejs/vue-cli#2936]
### Version
3.1.1

### Reproduction link
[http://localhost:8080](http://localhost:8080)

### Node and OS info
node 8.9

### Steps to reproduce
vue create FrontDemo 

![image](https://user-images.githubusercontent.com/12014252/48347191-81272f80-e6b8-11e8-86c1-bb2fdda54a75.png)

### What is expected?
vue create FrontDemo, success

### What is actually happening?
vue create FrontDemo ,  error

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/issues/2547
