### ISSUE TITLE
Unknown option: .polyfills when trying to add polyfills

### ISSUE THREAD

**Issue by abreitenfeld** [vuejs/vue-cli#2938]
### Version
3.1.1

### Reproduction link
[https://github.com/abreitenfeld/vue-polyfills](https://github.com/abreitenfeld/vue-polyfills)

### Node and OS info
Node v8.11.4
NPM v.5.6.0

### Steps to reproduce
1. Create a fresh Vue project via the CLI 
2. Extend the `babel.config.js` with the preset `polyfills` (according to the CLI documentation)
3. Try to build the project

### What is expected?
Build succeeds with the given polyfills

### What is actually happening?
Build fails with the error `Unknown option: .polyfills`

---
I used the example from https://cli.vuejs.org/guide/browser-compatibility.html#polyfills

**Comment by sodatea** [comment]
```diff
module.exports = {
  presets: [
-    '@vue/app', {
+    ['@vue/app', {
      polyfills: [
        'es6.promise',
        'es6.symbol'
      ]
-    }
+    }]
  ]
}
```
