### ISSUE TITLE
Question about code coverage with istanbul

### ISSUE THREAD

**Issue by Whax** [vuejs/vue-cli#294]
Hi,

let's suppose the following code 

```javascript
<script>
    export default {
        template: '<div>a  simple test of code coverage with {{someProp}}</div>',
        data () {
            return { // Istanbul says the statement is not covered
                someProp: 'a value'
            }
        }
    }
</script>
```

Any idea ? 

Thanks for you help.

**Comment by posva** [comment]
You should ask questions like this on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Providing a repo would help 😉 

---
You probably never used the component
