### ISSUE TITLE
 91% additional chunk assets processing

### ISSUE THREAD

**Issue by mudin** [vuejs/vue-cli#2943]
### Version
3.1.3

### Node and OS info
node 10.7.0/npm 6.4.1/masOs Mojave 10.14.1

### Steps to reproduce
vue-cli-service serve 

### What is expected?
success

### What is actually happening?
 91% additional chunk assets processing ERROR  Failed to compile with 1 errors

**Comment by imudin** [comment]
hello @LinusBorg ,

Sorry. I have been changing my code for 8 hours and I already lost the code with this issue. Cant reproduce it now :( I think the problem was because of i18n or iview plugins.
