### ISSUE TITLE
Dynamic configuration publicpath

### ISSUE THREAD

**Issue by gd2016** [vuejs/vue-cli#2944]
### What problem does this feature solve?
How to configure baseUrl to make__webpack_public_path__ to take effect ? I want  to config publicpath dynamically

**Comment by gd2016** [comment]
config publicpath dynamically  need to set  __webpack_public_path__  in  entry file ,  But the default value of baseurl is  ‘/’ ,   caused the value of __webpack_public_path__ is covered  by  '/'.   so  i need to need to delete the publicPath attribute 。  Then  how to delete it ?

**Comment by gd2016** [comment]
![image](https://user-images.githubusercontent.com/20918582/48401642-92c61100-e764-11e8-8428-7bf7fabe318e.png)
https://webpack.js.org/concepts/output/#advanced

**Comment by LinusBorg** [comment]
So just so that...

**Comment by DousyBox** [comment]
Find in [https://cli.vuejs.org/config/#baseurl](https://cli.vuejs.org/config/#baseurl)
```
module.exports = {
  baseUrl: process.env.NODE_ENV === 'production'
    ? '/production-sub-path/'
    : '/'
}
```
Hope it can help you.

**Comment by gd2016** [comment]
I know. It's my fault. thanks

**Comment by jnrdt** [comment]
Hi,

As said in your previous comment, __webpack_public_path__ aims at setting **at runtime** the public path. With the last solution, publicPath is still set at compile time.

For example, if you build once your app in "production" mode, you may deploy your (artifact) app in several environments, each environment setting his own publicPath as runtime.

The the first problem is to me still unsolved. How to use __webpack_public_path__ with vueJS?

Thanks

**Comment by luo772435545** [comment]
How to use webpack_public_path with vue-cli

**Comment by LinusBorg** [comment]
The webpack docs [explain it here](https://webpack.js.org/guides/public-path/#on-the-fly) - you set it as the very first thing in the entry file. 

```
__webpack_public_path__ = 'whatever/path/you/want/to/set/at/runtime'
```

There's nothing Vue.js or Vue CLI specific to take into concideration, as far as I can see.

**Comment by lichenhao** [comment]
Why don't support the dynamic public path for different deploy path with different backend.
