### ISSUE TITLE
Module build failed. No ESLint configuration found.

### ISSUE THREAD

**Issue by Syler921** [vuejs/vue-cli#2948]
### Version
3.0.0

### Node and OS info
NodeJS - 9.5.0, Windows 10 

### Steps to reproduce
I have the following issue when i try to build my vue-cli 3.0 project :

Building for production...

 ERROR  Failed to compile with 1 errors                                                                                                                                                                             
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
No ESLint configuration found.

    at Config.getLocalConfigHierarchy (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint\lib\config.js:255:39)
    at Config.getConfigHierarchy (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint\lib\config.js:179:43)
    at Config.getConfigVector (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint\lib\config.js:286:21)
    at Config.getConfig (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint\lib\config.js:329:29)
    at processText (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint\lib\cli-engine.js:163:33)
    at CLIEngine.executeOnText (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint\lib\cli-engine.js:620:17)
    at lint (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint-loader\index.js:253:17)
    at transform (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\eslint-loader\index.js:231:18)
    at C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\loader-fs-cache\index.js:127:18
    at ReadFileContext.callback (C:\_APP\projects\vuePreviewProject\vue-preview\node_modules\loader-fs-cache\index.js:31:14)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! preview@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the preview@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\stsankov\AppData\Roaming\npm-cache\_logs\2018-11-13T15_16_14_357Z-debug.log

Тhe problem occurs when i install one of the dependencies from my local machine ( not from github ) :

![image](https://user-images.githubusercontent.com/23247064/48425713-0ae50480-e76e-11e8-8dc0-deae1a75de01.png)

Аnyone who has encountered the problem ?

Thanks,

### What is expected?
Successfull build 

### What is actually happening?
Error during the build process. ( vue-cli build )

**Comment by DousyBox** [comment]
At first, your `column` module should not install manually in the `package.json`. That is npm's work.
Just put your `column` module in your project's `src/components` directory, and import it like below:
``` javascript
// some.js or some.vue's script parts
import Column from '@/components/column/column-component.vue'
```
`@` is the webpack resolve alias set default by Vue Cli 3.x.

Hope this is useful for you.

**Comment by LinusBorg** [comment]
@syler921 have you tried adding the path to an `.eslintignore` file?

**Comment by Syler921** [comment]
@DousyBox - All my modules are in different Github repositories because they are reused in other projects. I cant import all of them through the way that you explain. 

@LinusBorg - I have ignored the whole node_modules folder, but the build process fails again.

**Comment by DousyBox** [comment]
@Syler921 Just a small reporduction, not need the full version.

**Comment by sodatea** [comment]
For linked modules, do this:

```js
// vue.config.js
module.exports = {
  chainWebpack: config => config.resolve.symlinks(false)
}
```

(Note: there might be issues with HMR when `symlinks` is disabled)

**Comment by Syler921** [comment]
@sodatea Thank you, it works.

**Comment by SirAuron** [comment]
For others who want to try a different solution, for me the one provided here (https://github.com/webpack-contrib/eslint-loader/issues/202) worked.

**Comment by trusktr** [comment]
@sodatea What's the trick do? Can it break anything else that we should be aware of?

**Comment by xxholly32** [comment]
it works ~~~~~

**Comment by pairmix** [comment]
Hi there,
I get this issue with lastest vuejs install.
I created a file vue.config.js with 
````
module.exports = {
    chainWebpack: config => config.resolve.symlinks(false)
}
````
but it doesn't work.

**Comment by 2heal1** [comment]
thanks

**Comment by HenryTSZ** [comment]
@pairmix I also met this problem, I because of the introduction of external js file, result in an error. If you want to introduce an external file, then the file must be in a project. So I finally built a project for external resources.  I hope it can help you

**Comment by karolsw3** [comment]
> For linked modules, do this:
> 
> ```js
> // vue.config.js
> module.exports = {
>   chainWebpack: config => config.resolve.symlinks(false)
> }
> ```
> 
> (Note: there might be issues with HMR when `symlinks` is disabled)

You, sir, are an absolute magician. Thank you!

**Comment by santiagofs** [comment]
In my case, working with external files as well, solved the problem adding an .eslintrc.js file on the same folder of the external file

**Comment by fireairforce** [comment]
thx

**Comment by akashingole1** [comment]
In my case there were these hidden files .babelrc, editorconfig, .eslintignore, .eslintrc.js and .postcssrc.js(in case you have installed bootstrap). These files were not commited so when I took pull these files were missing. I resolved my problem by copying back these files.
Hope that helps.

**Comment by pdsuwwz** [comment]
> For linked modules, do this:
> 
> ```js
> // vue.config.js
> module.exports = {
>   chainWebpack: config => config.resolve.symlinks(false)
> }
> ```
> 
> (Note: there might be issues with HMR when `symlinks` is disabled)

Amazing! I'm curious how it works 🧐
