### ISSUE TITLE
There is a bug in vue-cli when I am running the script "vue-cli-service lint"

### ISSUE THREAD

**Issue by zhoucumt** [vuejs/vue-cli#2951]
### Version
3.1.1

### Node and OS info
Node 10.6.0 / npm 6.1.0 / Mac 10.13.3

### Steps to reproduce
My system node version is 6.10.3 and I use vue-cli3 to create a project.But when I run the script "git commit - 'xxx'",it shows "ERROR  You are using Node v6.10.3, but vue-cli-service requires Node >=8.Please upgrade your Node version."Actually, I have already used nvm to switch the node version to v10.6.0.

### What is expected?
There should be no error when I am committing the code because the node version was v10.6.0 after switching the version by nvm

### What is actually happening?
There is an error
![image](https://user-images.githubusercontent.com/6021846/48457294-23e8c680-e7fd-11e8-81a2-987d680358a7.png)

**Comment by lovetingyuan** [comment]
可以尝试重新运行一下npm install 然后再试下

**Comment by zhoucumt** [comment]
@lovetingyuan 我现在已经安装了n,然后把系统的nodejs的版本已经升级到11了，无法复现了，但是感觉不是npm install就能解决的，这里的原理应该是执行git commit -m 'xxx'之后，会去系统里和node安装的文件夹去获取node的版本，但是并不是获取我当前切换后的node的版本，始终是去获取了默认的那个node版本
