### ISSUE TITLE
documentation wrong about when vue.config.js configureWebpack is a function with return value

### ISSUE THREAD

**Issue by magicdawn** [vuejs/vue-cli#2958]
According to this https://github.com/vuejs/vue-cli/blob/7d2b345af3b029205675366b725c521e5ccd0495/packages/%40vue/cli-service/lib/Service.js#L241

configureWebpack() return value will be merge to config, and do not need manual merge in vue.config.js
But the documentation says that
https://cli.vuejs.org/config/#configurewebpack

>  If the value is a function, it will receive the resolved config as the argument. The function can either mutate the config and return nothing, OR return a cloned or merged version of the config.

this will make developer to manual merge the config and return.
and will result error like this

```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   function | object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string]
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry should be an instance of function
      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.
    * configuration.entry['app'] should be a string.
      -> The string is resolved to a module which is loaded upon startup.
    * configuration.entry['app'] should not contain the item './src/main.js' twice.
    * configuration.entry should be a string
```

configuration.entry['app'] should not contain the item './src/main.js' twice.

BTW, the issue tool also has issues, the version can not be filled
![image](https://user-images.githubusercontent.com/4067115/48537364-57564e80-e8ec-11e8-8702-843a85e95dad.png)

**Comment by Kingong** [comment]
i have a similar issue, because i return a self merged webpack config, then i directly return self-configed webpack-config object, it's resolved.

**Comment by wilsonwangdev** [comment]
in configureWebpack just mutate configs and don't need return anything, otherwise you will get this error.
just do as the [sample config](https://cli.vuejs.org/guide/webpack.html#simple-configuration)
