### ISSUE TITLE
Vue not loading .env variables

### ISSUE THREAD

**Issue by peyman3d** [vuejs/vue-cli#2959]
### Version
3.0.5

### Reproduction link
[https://github.com/peyman3d/test-env](https://github.com/peyman3d/test-env)

### Node and OS info
Node 8.12.0 / npm 6.4.1

### Steps to reproduce
Run the app

### What is expected?
`console.log( process.env.VUE_APP_HOME_URL )` in `created()` method in `App.vue` should return variable value.

### What is actually happening?
It returns `undefined`

---
I created an '.env' file in root and add an variable with `VUE_APP` prefix

**Comment by LinusBorg** [comment]
Your projet isn't created with vue-cli 3. Only vue-cli 3 loads .env files
