### ISSUE TITLE
External postcss configs are not working

### ISSUE THREAD

**Issue by ianbrode** [vuejs/vue-cli#2967]
### Version
3.1.1

### Node and OS info
vue-cli 3.1.3 (form doesn't let me choose this version) / node 10.6.0 / npm 6.4.1 / MacOS 10.13.4

### Steps to reproduce
1. Create blank project with vue-cli;
2. Add postcss plugin  (for example, "postcss-css-variables") to external config ```.postcssrc```, ```.postcssrc.js``` or ```postcss.config.js```;
3.  Require file with css variables in you app and use variables in component;

### What is expected?
In case of postcss-css-variables variables are resolved. Plugins are used.

### What is actually happening?
In case of postcss-css-variables I get "variable undefined" error. Other plugins are just not resolved and nothing happens.

---
There is a workaround to tweak postcss loader in vue.config.js. 

```
module.exports = {
	css: {
		loaderOptions: {
			postcss: {
				options: { plugins: 'postcss-css-variables': {}}
			},
		},
	},
};

```
UPD: 
reproduction repo https://github.com/ianbrode/external_postcss_reproduction

**Comment by sodatea** [comment]
Do you have a reproduction repo?

External postcss configs might have been overridden by the config in `package.json`. It's recommended to choose **placing config in dedicated config files** during project creation, if they are likely to be customized later.

**Comment by ianbrode** [comment]
@LinusBorg 
By blank I mean what you get after executing ``` vue create myProject``` in terminal. 

@sodatea 
Here it is https://github.com/ianbrode/external_postcss_reproduction .
There is ```.postcssrc``` that doesn't work and I have commented out a ```vue.config.js``` file. 
```Package.json``` has no configs touching postcss.

**Comment by LinusBorg** [comment]
So I took a look at the provided reproduction.

This repository doesn't seem to be a vue-cli 3 project, so I don't understand what I should do with that-

**Comment by ianbrode** [comment]
@LinusBorg thank you for checking out my code during weekend.

Could you explain to me how did you figure out it is not vue-cli 3? I made this project according documentation here: https://cli.vuejs.org/guide/creating-a-project.html#vue-create with vue-cli installed globally. During the project creation in terminal I also had a message it was created with Vue CLI v3.1.3 (no other versions exist in my system), also I tried looking at it with ``vue ui`` and there is dependency of 3.*.* vue-cli-service.

Also looked through my repo and it doesn't have any mentions of ```/playground```. ```vue build``` command creates compiled app in dist folder. No hidden folders exist there also. It is true I have postcss config in root of a project, the same place where other config files are stored.

**Comment by LinusBorg** [comment]
Simple explanation: I looked at the ring repository, namely the one you shared with sodatea. 

Didn't look at the urls carefully enough, sorry about that. 

Will check out the right one later

**Comment by LinusBorg** [comment]
Oo, now no took a look at the right repository. And the reason is simple: 

You require the variables file in main.ts, but those variables woll my be available in the process that later converts App.vue, where you try and use one of the variables. 

In other words: you would have to @import the variables file in each style block that needs access to one of the variables.

**Comment by ianbrode** [comment]
@LinusBorg thank you for your time. I just want to add that there is a config file in repo ```_vue.config.js```. In it I injected postccs plugins in config manually. If you remove the underscore in its name - everything works like a charm. Variable are added globally and only with one import. Because of this, I think the problem with how external config files are resolved.

**Comment by batmanhit** [comment]
@ianbrode can you please show me the configurations you have made?
I cannot access the repo at the moment.
Thanks.

**Comment by ianbrode** [comment]
@batmanhit the issue is close, so I removed repo to keep my github tidy.
