### ISSUE TITLE
vue-cli build output filename always 'app'.  How to specify custom name while building --modern?

### ISSUE THREAD

**Issue by peacechen** [vuejs/vue-cli#2969]
### Version
3.1.1

### Node and OS info
Node 9.3.0, npm 5.5.1, OSX 10.14.1

### Steps to reproduce
When building a bundle with vue-cli, the output filename is always app.js.  I was able to force it to another, fixed filename in the vue.config.js:

```
// vue.config.js
module.exports = {
  configureWebpack: {
    output: {
      filename: 'myAppName.js'
    },
    optimization: {
      splitChunks: false
    },
  },
  filenameHashing: false
}
```

However this breaks building with `--modern`.  Modern builds create 2 bundles, one with suffix `-legacy`.  Specifying a fixed filename in vue.config causes both bundles to be named the same, with one overwriting the other.

What is a good way to change the output filename (the variable `[name]`) in vue.config?

### What is expected?
output filename myAppName.js

### What is actually happening?
output filename is always app.js

**Comment by peacechen** [comment]
Nice idea @LinusBorg .   Unfortunately it creates both bundles with filename `myAppName-legacy.js` (one overwriting the other).   I'm guessing that environment variable is always set.

Using your idea, we just need to figure out if there's a runtime variable that's dynamically exposed during the modern build phase.

**Comment by LinusBorg** [comment]
that variable would be that environment variable.

The names must be changed again in some other spot i didn't check out.

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/issues/2443#issuecomment-419158280

**Comment by diogosalazar** [comment]
This issue has been closed already but this is my approach to renaming the output bundle file:

```javascript
// vue.config.js
module.exports = {
  // Modify Webpack config
  // https://cli.vuejs.org/config/#chainwebpack
  chainWebpack: config => {
    // Not naming bundle 'app'
    config.entryPoints.delete('app');
  },

  // Overriding webpack config
  configureWebpack: {
    // Naming bundle 'bundleName'
    entry: {
      bundleName: './src/main.js'
    }
  }
};
```

Hope this helps

**Comment by LinusBorg** [comment]
This doesn't work in modern mode, which is the problem of OP.

**Comment by NLNicoo** [comment]
Somehow I found this in Google on an unrelated issue and not sure if OP still needs it. But AFAIK you can do this with pages:

```
module.exports = {
  configureWebpack: {
    optimization: {
      splitChunks: false
    }
  },
  filenameHashing: false,
  pages: {
    myAppName: {
      entry: 'src/main.js'
    }
  }
}
```

**Comment by peacechen** [comment]
Thanks @NLNicoo .  I'm not actively using Vue at the moment so can't test your suggestion.  Hopefully this will help someone else, and if I return to using Vue it may be valuable.
