### ISSUE TITLE
打包package.json 带有jsnext:main 的第三方库 会有问题

### ISSUE THREAD

**Issue by Qymh** [vuejs/vue-cli#2979]
### Version
3.0.5

### Node and OS info
Node 10.8.0 / yarn 1.9.4 / macOs 10.13.6

### Steps to reproduce
直接运行 vue-cli-service build --modern

### What is expected?
应该选用第三方的package.json下的main包 es5的语法

### What is actually happening?
选用了第三方仓库的package.json jsnext:main 包下的es6语法

---
出现异常的包为swiper https://github.com/nolimits4web/swiper ，想请教下选择了package.json 下的jsnext:main包 这是vue-cli的特性还是bug 特性的话有什么配置可以去掉吗 目前采用了一个hack的手法 在vue.config.js 里使用 这个 config.resolve.mainFields = ['main'];

**Comment by Qymh** [comment]
如果默认选用jsnext的包在ios10以下的浏览器会出现关于const的报错，网页会出现白屏

**Comment by sodatea** [comment]
默认使用的不是 `jsnext:main`，而是 `module`。
这是 webpack 的默认设置：https://webpack.js.org/configuration/resolve/#resolve-mainfields
你的修改是对的，不算 hack。
