### ISSUE TITLE
VUE CLI UI support VS Code as default editor

### ISSUE THREAD

**Issue by johnpapa** [vuejs/vue-cli#2982]
### What problem does this feature solve?
when clicking on the "open in editor" button in the UI, should allow configuring which editor we want to open. For example, Sublime, VS Code, Atom

### What does the proposed API look like?
Add a configuration button in the UI to allow setting of the default editor

**Comment by johnpapa** [comment]
Found the solution 

1. `npm install --save-dev launch-editor-middleware`

2. create `vue.config.js`

3. paste the following code 

```
const openInEditor = require("launch-editor-middleware");

module.exports = {
  configureWebpack: {
    devServer: {
      before(app) {
        app.use("/__open-in-editor", openInEditor("code"));
      }
    }
  }
};
```


references: 

- https://cli.vuejs.org/guide/webpack.html#simple-configuration

- https://github.com/vuejs/vue-devtools/blob/master/docs/open-in-editor.md

- https://github.com/yyx990803/launch-editor

**Comment by Akryum** [comment]
You can also just set `EDITOR` env variable to `code`

**Comment by johnpapa** [comment]
How can it be set for a users machine?

**Comment by johnpapa** [comment]
Could this be set in the ~/.vuerc ?

The use case is for users who want to set it and forget it, for their computer

**Comment by johnpapa** [comment]
I found that if I run `EDITOR=code vue ui` and then open a project in my editor via the UI, it opens it in sublime if it is open. If I close sublime, it will open it in code.

**Comment by Akryum** [comment]
This is how launch-editor works, maybe open an issue here if you want the env var to have priority over running processes.

**Comment by mikeerickson** [comment]
@johnpapa Did you ever get this working?  I have been trying but can't find a working solution?

I have defined the EDITOR variable and am able to properly view it

![image](https://user-images.githubusercontent.com/183153/57054988-fc6fa400-6c4c-11e9-8565-5a598b5847af.png)

**Comment by Akryum** [comment]
The value is wrong, it should be the name of the VS Code executable, `code` on Linux

**Comment by mikeerickson** [comment]
@akryum after I posted this message, I realized the value was wrong, so I chanced to `code` but still not able to get it working.

**Comment by Akryum** [comment]
Did you try restarting `vue ui` in a new terminal, logout/login again or restarting the whole computer?

**Comment by ryanjagar** [comment]
Solution for MacOS:
1. Install VS Code as per this page:https://vscode-eastus.azurewebsites.net/docs/setup/mac (ensure you setup _"launching from the command line"_)
2. Add the EDITOR env variable to ~/.bash_profile something like this:
`EDITOR=code`
`export EDITOR`
3. Test your settings by opening a new Terminal window and running:
 `printenv EDITOR`
_Note: When Terminal.app opens a new window, it will run .bash_profile. Not, as users familiar with other Unix systems would expect, .bashrc._

**Comment by evgenijchul** [comment]
In Windows 10: add
`EDITOR=code`
in *.env file

**Comment by zhan2309** [comment]
cd ~ in .zshrc file
export EDITOR=code

**Comment by billmorgan123** [comment]
set the env variable "EDITOR=code"

**Comment by kingma-sbw** [comment]
Setting editor to code didn't help in my case:

![grafik](https://user-images.githubusercontent.com/50140049/168599161-b12e289c-0ce7-4b40-b761-0510ddcb66d0.png)

**Comment by dginovker** [comment]
Doesn't work for me either

I did

```
export EDITOR=cursor 
echo $EDITOR 
> cursor
```

But when clicking a code link in the UI, it opens vs code

**Comment by dginovker** [comment]
Brute force fixed it by doing

```
which code
> /usr/bin/code
rm -rf /usr/bin/code
which cursor
> /tmp/.mount_cursorCzRS0Z/cursor
sudo ln -s /tmp/.mount_cursorCzRS0Z/cursor /usr/bin/code
```

Btw don't do this if you don't know how to fix your system after
