### ISSUE TITLE
TypeScript project doesn't support devServer.proxy configuration

### ISSUE THREAD

**Issue by DerekLiang** [vuejs/vue-cli#2986]
### Version
3.1.1

### Reproduction link
[https://github.com/Armour/vue-typescript-admin-template](https://github.com/Armour/vue-typescript-admin-template)

### Node and OS info
node v8.11.3, npm 5.6.0, Windows 10

### Steps to reproduce
1) create/modify vue.config.js file as the following:
```
module.exports = {
  baseUrl: process.env.NODE_ENV === 'production' ? '/vue-typescript-admin-template/' : '/',
  pwa: {
    name: 'vue-typescript-admin-template'
  },
  devServer: {
      proxy: {
          '/api': {
              target: 'http://localhost:8081',
              ws: true,
              changeOrigin: true,
           }
      },
  },
}
```
Configure target to any of API server runs on your localhost.

2) launch local dev server `yarn serve`

3) run `curl 'http://localhost:8080/api/parts' -H 'Accept: application/json'` where localhost:8080 is your local dev server address.

### What is expected?
I will expect the return result from the API server.

### What is actually happening?
The actually API call to the local dev server will NOT pass through the target API server (in our example  localhost:8081). 

It fetches the index.html or an error html page depends your client.

**Comment by sodatea** [comment]
Can't reproduce.
(Screencast: https://asciinema.org/a/ETdTjSf8eTst8Pb9pfEw7ceYY Note the outputs are from the server on port 8081)

BTW if your request's `accept` header includes the string `text/html`, it is expected to skip the proxy. See https://github.com/vuejs/vue-cli/issues/2514#issuecomment-431656360

**Comment by DerekLiang** [comment]
Right, it worked as expected. Thank you for looking into it so quickly.
