### ISSUE TITLE
建议将 vue.config.js 中 filenameHashing 配置字段转变为 filename 配置字段

### ISSUE THREAD

**Issue by AidanDai** [vuejs/vue-cli#2987]
### What problem does this feature solve?
打包出来的文件命名有时候需要特定的名字，现在的命名模式约束太大；通过插件机制来重载也比较复杂，建议将 filenameHashing 配置字段改为 filename 配置字段，或者增加一个 filename 的配置字段，这样更加灵活

### What does the proposed API look like?
```javascript
// vue.config.js
module.exports = {
  filename: `[name].[contenthash:8]`, // 这样命名更加灵活，至于 css 和 js 文件的不同可以下层兼容
}
```

**Comment by fgsdfger** [comment]
请问一下，现在需要怎样来指定名字

**Comment by AidanDai** [comment]
> 请问一下，现在需要怎样来指定名字

比如去掉文件夹的嵌套等，每次打包可能需要不同的文件名，不论内容有没有变（方便 cdn 上传）觉得暴露出来比较灵活

**Comment by sodatea** [comment]
暂时不考虑这个功能，收益不大而维护成本过高。
真的有需要的，还是建议在 vue.config.js，参照 [base.js](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/base.js) 和 [prod.js](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/prod.js) 自行覆盖配置实现。
