### ISSUE TITLE
更加完善的约定优于配置

### ISSUE THREAD

**Issue by cn-src** [vuejs/vue-cli#2988]
### What problem does this feature solve?
vue-cli 3 中依然有需要生成的配置（无论是单独的文件还是在 package.json 中），特别是  eslint, jest 等第三方框架的配置，既然是存在默认配置那么直接内置即可，提供覆盖的配置方式就行。后端自动化工具已经比较完善了，有很多经验可以直接借鉴，像 webpack 已经向这些工具一样越来越完善，我觉得 vue-cli 3 既然是那么大的改动，不如做的更好。

说实话，生成的那些配置项真心不少了，很多都是不会改动的。

### What does the proposed API look like?
约定优于配置

**Comment by sodatea** [comment]
谢谢建议，不过默认生成的这些配置多半是因为第三方库目前没有提供隐藏配置的方法，或者隐藏配置后会不方便与编辑器、IDE 整合，所以不得不加的。比如：
1. babel 必须要通过 babel.config.js 的存在来判断配置的根目录
2. eslint 配置如果从 package.json 和根目录隐藏的话，编辑器 / IDE 的内置 lint 插件会无法确定用什么配置

至于其他单独某个插件生成的配置，如果你有更具体的建议的话，欢迎另开 issue 或 PR 详细描述改进方案，只要开发成本可控我们都很乐意实现。
