### ISSUE TITLE
Cannot update vue-cli from 2.9.6 to latest

### ISSUE THREAD

**Issue by Anti-Antidote** [vuejs/vue-cli#2989]
### Version
2.9.6

### Node and OS info
npm 6.4.1

### Steps to reproduce
See [this screenshot](https://imgur.com/BUqJFfn) for full output

Install `vue-cli` at version 2.9.6

Following steps to update:

    $ npm uninstall -g vue-cli
    $ npm install -g @vue/cli

`vue-cli`appears to be updated based on `npm`'s output.

Attempt to make a new project:

    $ vue create myproject

### What is expected?
A new project is created

### What is actually happening?
Vue tells me that `create` is a v3 command only, and to upgrade.

**Comment by AkemiHomuraa** [comment]
I have the same problem...

**Comment by Akryum** [comment]
What is the output of:

```js
vue --version
npm uninstall -g vue-cli
yarn global remove vue-cli
vue --version
```
?

**Comment by AkemiHomuraa** [comment]
> It seems you have multiple installations of `vue-cli`.
> 
> What is the output of:
> 
> ```js
> vue --version
> npm uninstall -g vue-cli
> yarn global remove vue-cli
> vue --version
> ```
> 
> ?

[![vue-cli.jpg](https://i.loli.net/2018/11/22/5bf65c9549c87.jpg)](https://i.loli.net/2018/11/22/5bf65c9549c87.jpg)

**Comment by Akryum** [comment]
So it's still installed somewhere...

**Comment by AkemiHomuraa** [comment]
I using the nvm so my global node modules was under whatever version of node using.
But I still have an older version of npm at `/usr/local/lib/node_modules`, so I just delete the old node_modules and reinstall vue again.

**Comment by Anti-Antidote** [comment]
@Akryum I do not have `yarn` installed, so I don't think I have it installed in multiple places. However, I'm going to try @AkemiHomuraa's idea of deleting the global `node_modules` and reinstalling from there, so we'll see how that goes.

**Comment by Anti-Antidote** [comment]
I ended up breaking everything involving `node` and `npm` by deleting my global `node_modules`, so I reinstalled using [`nvm`](https://github.com/creationix/nvm) and was finally able to upgrade Vue.

**Comment by guillaumeagile** [comment]
Same problem,  cannot understand why 

PS C:\tmp\FOOOO> npm list -g vue/cli
C:\Users\gsaintet\AppData\Roaming\npm
`-- (empty)

PS C:\tmp\FOOOO> npm list -g @vue/cli
C:\Users\gsaintet\AppData\Roaming\npm
`-- @vue/cli@3.5.1

PS C:\tmp\FOOOO> vue --version
2.9.6
PS C:\tmp\FOOOO> npm list -g -depth=0
C:\Users\gsaintet\AppData\Roaming\npm
+-- @vue/cli@3.5.1
+-- bower@1.8.4
+-- generator-aspnet@0.3.3
+-- npm-check@5.9.0
`-- yo@2.0.4

PS C:\tmp\FOOOO> vue create toto

  vue create is a Vue CLI 3 only command and you are using Vue CLI 2.9.6.

**Comment by dev7ch** [comment]
useing a > 3 explicit version helped  me, e.g. `npm i -g  @vue/cli@v3.5.5`

**Comment by TingAli** [comment]
I'm also having this issue and none of the above has helped. Slightly annoying, but hoping someone knows how to fix this. :)

**Comment by TingAli** [comment]
**Using Yarn**

After spending a long hour trying to figure this out, this is how I fixed it:

Delete the folder:
> C:\Users\Imdad Ali\AppData\Local\Yarn\Data\global\node_modules\vue-cli

From the file:
> C:\Users\Imdad Ali\AppData\Local\Yarn\Data\global\package.json
Delete the line:
> "vue-cli": "2.9.6",

Then in your terminal, run the cmd:
> yarn global add @vue/cli@latest

**Comment by idohertyr** [comment]
I deleted my node_modules folder and package.json in
`~/.config/yarn/global`
then installed with
`yarn global add @vue/cli`
worked for me

**Comment by BenRichter** [comment]
I've got this problem when using **NVM** (node version manager). When you install a package globally, it's usually installed on the system node version. List installed packages in current version, when not found, switch to system and remove ot there:
```
npm ls -g --depth=0
nvm use system
npm uninstall -g vue-cli
```

https://stackoverflow.com/questions/47763783/cant-uninstall-global-npm-packages-after-installing-nvm#answer-47849940

**Comment by archer247** [comment]
This thread helped me fix my issue, it seems npm was underway when trying to use it with yarn, so just removed node with uninstall and used this commands with SUDO in yarn so It fixes

https://stackoverflow.com/a/54087077/3047920

**Comment by grunlowen2** [comment]
On Linux with version 2.9.6 of Vue, uninstall did not work. I ended up running >which vue, then deleting the vue executable, along with 2 other vue files in that folder. Ran >npm install -g @vue/cli and all is well.

**Comment by bormisov1** [comment]
> On Linux with version 2.9.6 of Vue, uninstall did not work. I ended up running `which vue`, then deleting the vue executable, along with 2 other vue files in that folder. Ran `npm install -g @vue/cli` and all is well.

Worked for me as well. But we now probably have some other files of the old vue somewhere, I guess

**Comment by mmamoonkhan** [comment]
I tried to many times to update the `vue/cli `but unfortunately i am unable to update it furthermore neither able to create the project in vue js not able to create to uninstall the the` vue/cli` in ubuntu 20. when i write this command

> `npm uninstall -g @vue/cli`

 it throws only this ( up to date in 0.037s)  when i try to update it it shows 

> npm ERR! A complete log of this run can be found in:/home/mamoon/.npm/_logs/2020-07-10T07_19_38_543Z-debug.log

at the end when i try to create the project it illustrates 

> Command vue init requires a global addon to be installed.Please run npm install -g @vue/cli-init and try again.

 Can anyone guide me what to do now and whats the issue is there any way to remove the `vue/cli `manually.

my node version is 12.0.0 and npm version is 6.9.0. i shall be thankful to you if you guys will help me to sort these issues
@BenRichter @idohertyr @Akryum

**Comment by Maryna-mart** [comment]
in my case this one helped https://stackoverflow.com/questions/58832705/how-can-i-update-vue-cli-version
