### ISSUE TITLE
Webpack configuration for multiple targets

### ISSUE THREAD

**Issue by GaragusoPD** [vuejs/vue-cli#2993]
### What problem does this feature solve?
Some of my applications use "web workers", and with the previous version of the vue-cli I could create directly multiple entry points with different targets (node-webkit, node, etc). The webpack.config.js file then had multiple objects to be exported with `module.exports = [mainapp, webworker1, ...]`. This allowed fine control on the code for each web worker, however, the new vue.confij.js file doesn't seem to work the same way.

### What does the proposed API look like?
The attribute `configureWebpack` in vue.config.js seems to take in only an object, even when using a function. It would be profitable that it takes also an array of webpack configuration objects.

**Comment by sodatea** [comment]
Current workaround: https://github.com/jkzing/vue-cli-plugin-multi-compiler

**Comment by sodatea** [comment]
Closing in favor of https://github.com/vuejs/vue-cli/issues/2613
