### ISSUE TITLE
vue-cli won't start http server with "npm run dev" for Windows

### ISSUE THREAD

**Issue by JSmith01** [vuejs/vue-cli#30]
vue-cli incorrectly handles "dev" command in Windows environment.
When I try to start:
npm run dev

it hangs before http server starts. It's because of "&" sign to run browserify-hmb in background and then run http-server. Windows command-line interpreter doesn't allow to chain commands that way, it should be two separate lines, first one should be preceeded by start /b following-command-line.

As a solution you could create two scripts with the same name, but first one without extension for unix-likes, second with '.cmd' on the end for windows. 

Hope you can fix this.

**Comment by yyx990803** [comment]
Feel free to submit a PR to the related template repo (looks like you are using [this](https://github.com/vuejs-templates/browserify)). This is not related to `vue-cli` itself though.
