### ISSUE TITLE
Exceptions in async functions may not have being logged

### ISSUE THREAD

**Issue by linden5** [vuejs/vue-cli#3003]
### Version
3.0.4

### Reproduction link
[https://github.com/linden5/vue-cli-not-logging-error-reproduce](https://github.com/linden5/vue-cli-not-logging-error-reproduce)

### Node and OS info
Node 8.12.0 / yarn 1.12.3 / Windows 10

### Steps to reproduce
1. yarn install
2. yarn serve

and the console would log 'Failed to compile with 1 errors' without error details

### What is expected?
Error details can be properly logged

### What is actually happening?
Error details are not logged

---
This problem is actually caused by [friendly-errors-webpack-plugin](https://github.com/geowarin/friendly-errors-webpack-plugin/issues/79), but I think vue-cli should log error details to help users locating problems quickly. 

After having a glance of vue-cli-service source code, this problem may be related to error handling of async functions such as service#run.

**Comment by LinusBorg** [comment]
So it's an upstream problem? we can see if we can work around it, but I don't really think so right now.
