### ISSUE TITLE
Missing dependencies on default template install on windows

### ISSUE THREAD

**Issue by badpunman** [vuejs/vue-cli#3009]
### Version
3.1.1

### Node and OS info
node 11.2, npm 6.4.1, windows 2012 

### Steps to reproduce
vue create project
go with default options: babel eslint

### What is expected?
No missing dependencies

### What is actually happening?
Missing dependencies
![image](https://user-images.githubusercontent.com/937289/49013261-cea99f00-f184-11e8-992f-2fa8e8e90623.png)

Requires different versions of ajv, is this an issue? (version 5 required by eslint, 6 by the rest.)
![image](https://user-images.githubusercontent.com/937289/49013423-5f807a80-f185-11e8-8042-b378914f853e.png)

**Comment by philBrown** [comment]
I'm getting the same warnings on a fresh Linux install

Node v10.14.0, NPM 6.4.1 Vue CLI 3.2.1

```bash
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
```
