### ISSUE TITLE
Does the vue-cli support read json file without other plugins?

### ISSUE THREAD

**Issue by cosnyang** [vuejs/vue-cli#301]
By default,I use code blow:
` import config from 'config/config.json'`
It  does not work.

and I install json-loader by npm,
It does not work too.

My question is how to read locate json file?

**Comment by apertureless** [comment]
Try `const cfg = require('../config.json');`

Or 

`import * as cfg from 'config.json'`

**Comment by posva** [comment]
I never saw this issue. Since it runs on node, you cannot `import` filse but you can `require` them
