### ISSUE TITLE
unable to shallowmount with vue component

### ISSUE THREAD

**Issue by Kishor-Kumar-Namdeo** [vuejs/vue-cli#3011]
### Version
3.1.1

### Reproduction link
[https://github.com/facebook/jest/issues/7413](https://github.com/facebook/jest/issues/7413)

### Node and OS info
yarn

### Steps to reproduce
Hi, i am using @vue/cli-plugin-unit-jest : "^3.1.1" and when i run src/view/* component test script file then shallowMount working fine but when i run src/components/* component test script file then its show bellow error.

### What is expected?
shallowMount work fine with component

### What is actually happening?
not working

Hi, please help me to solve such issue. my component & test file content are below....

register.vue

-----------------------------------
<pre><code>
<template>
    <form @submit.prevent="registerUser" class="modal-card has-text-centered">
        <header class="modal-card-head  justify-content-center ">
            <p class="subtitle is-size-4 has-text-warning has-text-centered is-marginless">REGISTER</p>
        </header>
        <section class="modal-card-body">
            <div class="columns is-marginless justify-content-center">
                <div class="content column is-7">
                    <div class="field">
                        <div class="control">
                            <input class="input" id="name" autocomplete='given-name' type="text" placeholder="Name" v-model="user.name" :class="{'is-danger': $v.user.name.$error}" @input="$v.user.name.$touch()">
                            <p v-if="$v.user.name.$error" class="help is-danger">Name Field should be minimum 3 letters</p>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <input class="input" id="email" autocomplete='email' type="text" placeholder="Email"  v-model="user.email" :class="{'is-danger': $v.user.email.$error}" @input="$v.user.email.$touch()">
                            <p v-if="$v.user.email.$error" class="help is-danger">Enter valid email address</p>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <input class="input" id="password" type="text" autocomplete='current-password' placeholder="Password" v-model="user.password" :class="{'is-danger': $v.user.password.$error}" @input="$v.user.password.$touch()">
                            <p v-if="$v.user.password.$error" class="help is-danger">Password should be minimum 6 digit</p>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <input class="input" id="confirmPassword" type="text" placeholder="Confirm Password" v-model="user.confirm_password" :class="{'is-danger': $v.user.confirm_password.$error}" @input="$v.user.confirm_password.$touch()">
                            <p v-if="$v.user.confirm_password.$error" class="help is-danger">Password and confirm password should be same</p>
                        </div>
                   </div>
                </div>
            </div>
        </section>
        <footer class="modal-card-foot justify-content-center is-paddingless">
            <div class="has-text-centered">
                <button type="submit" class="button is-primary" id="btnRegister">REGISTER</button><br>
                <p class="help has-text-centered has-text-white">Already have an account? <a id="btnLogin" class="has-text-warning" @click="$parent.cancel(),$emit('changeModal','login')">Log In</a> </p>
            </div>
        </footer>
    </form>
</template>
<script>

import { required, minLength, maxLength, email, sameAs } from 'vuelidate/lib/validators'
import { REGISTER_WITH_EMAIL_PASSWORD, UPDATE_USER_NAME, UPDATE_USER_PHOTO } from '../../../../resource/firebase'
import EventBus from '../../../../helpers/event-bus'
export default { 
  name: 'Register',
  data () {
    return {
      user: {
        email: '',
        password: '',
        confirm_password: '',
        name: ''
      }
    }
  },
  validations: {
    user: {
      name: {
        required,
        minLength: minLength(3),
        maxLength: maxLength(40)
      },
      email: {
        required,
        email
      },
      password: {
        required,
        minLength: minLength(6)
      },
      confirm_password: {
        sameAsPassword: sameAs('password')
      }
    }
  },
  methods: {
    registerUser () {
      this.$v.user.$touch()
      if (this.$v.user.$invalid) {
        return false
      }
      EventBus.$emit('pageLoading', true)
      REGISTER_WITH_EMAIL_PASSWORD({ email: this.user.email, password: this.user.password }, (data) => {
        // console.log(data)
        this.updateDetails()
      }, (error) => {
        EventBus.$emit('pageLoading', false)
        // console.log(error)
        this.$swal({
          type: 'error',
          title: error.message,
          showConfirmButton: false,
          timer: 1500
        })
      })
    },
    async updateDetails () {
      let photo = process.env.VUE_APP_BASE_URL + '/images/default_user.png'
      await UPDATE_USER_NAME(this.user.name)
      await UPDATE_USER_PHOTO(photo)
      EventBus.$emit('pageLoading', false)
      this.$emit('changeModal', 'login')
      this.$swal({
        position: 'top-end',
        type: 'success',
        title: 'Your Account created successfully.... Please Login',
        showConfirmButton: false,
        timer: 2000
      })
    }
  }
}
</script>
</code></pre>
----------------------------------
register.spec.js
-------------------------------
<code><pre>

import { shallowMount } from '@vue/test-utils'
import Register from '@/components/commons/modals/auth/Register.vue'

describe('Register', () => {  
  it('check login with email & password', () => {
    console.log('dsfasfsd');
    const wrapper = shallowMount(Register, {
      data() {
        return{
          user: {
            email: 'unittest@test.com',
            password: 'test123',
            confirm_password: 'test123',
            name: 'unit test'
          }
        }
      }
    })
  })
})
</code></pre>

----------------------------------
error while run test
![screenshot_2018-11-26_18-01-48](https://user-images.githubusercontent.com/38028353/49014218-6c14cb00-f1a5-11e8-8699-bd4fec2ca3ff.png)

**Comment by Kishor-Kumar-Namdeo** [comment]
@sodatea please comment on this issue....

**Comment by sodatea** [comment]
See: https://github.com/vuejs/vue-test-utils/issues/1023
