### ISSUE TITLE
Malicious code used in dependency

### ISSUE THREAD

**Issue by aparajita** [vuejs/vue-cli#3014]
### Version
3.1.3

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Node and OS info
Node 10.13.0 / npm 6.4.1 / macOS 10.14.1

### Steps to reproduce
npm i -g @vue/cli@3.1.3
npm ls | grep event-stream

### What is expected?
A version of event-stream that is not 3.3.6, as this is a malicious version.

### What is actually happening?
vue-cli depends on @vue/cli-ui@3.1.2, which depends on terminate@2.1.0, which depends on ps-tree@1.1.0, which depends on event-stream@3.3.6.

---
Please see https://www.zdnet.com/article/hacker-backdoors-popular-javascript-library-to-steal-bitcoin-funds/ for a summary of why it's a real bad idea to have event-stream@3.3.6 anywhere in the dependency tree.

**Comment by virtuoushub** [comment]
Looks like [terminate@2.1.2](https://github.com/dwyl/terminate/tree/v2.1.2) has a fix for this.
See: https://github.com/dwyl/terminate/issues/35

However, it also looks like the dependency on terminate has been removed. See:
https://github.com/vuejs/vue-cli/commit/2baddaa35eda4f51404e28ba05fdf63cd10b1ae3 and 
https://github.com/vuejs/vue-cli/commit/8fd8082f4becc7fa07097ff2fb0bfc4c353be9cf#diff-3e40e81d7f4e7bd8a8f9e819c8fa747a

**Comment by aparajita** [comment]
I figured a fix would come quickly, thanks.

**Comment by virtuoushub** [comment]
To confirm, I ran `npm ls event-stream flatmap-stream` on 2baddaa35eda4f51404e28ba05fdf63cd10b1ae3
```
~/vue-cli   dev ≣                                            [10:01:15 PM]
❯ 
git rev-parse HEAD
2baddaa35eda4f51404e28ba05fdf63cd10b1ae3
```

```
~/vue-cli   dev ≣                                            [10:01:18 PM]
❯ 
npm ls event-stream flatmap-stream
F:/oo/vue-cli
`-- (empty)
```
