### ISSUE TITLE
Need build without any file output for typescript compilation

### ISSUE THREAD

**Issue by zuoez02** [vuejs/vue-cli#3015]
### What problem does this feature solve?
I opened an issue [How can I get compilation error without build?](https://github.com/vuejs/vue-cli/issues/2950) 2 weeks ago but we didn't got a good answer. After searching about if tslint can do compile error checking, I found that they can't do it, either.

Now I can only get compilation error when I run `vue-cli-service build` and I think it is important to do compilation error checking in CI/CD. So I need this feature to do compilation error check.

### What does the proposed API look like?
`vue-cli-service build --no-output`

**Comment by sodatea** [comment]
Since it's a duplication I'm closing this issue.
