### ISSUE TITLE
Environment Variables can be expand

### ISSUE THREAD

**Issue by IndexXuan** [vuejs/vue-cli#3017]
### What problem does this feature solve?
like dotenv expand
```js
PORT=3000
VUE_APP_API_HOST=http://localhost:${PORT}
```
https://github.com/motdotla/dotenv-expand/blob/master/test/.env

### What does the proposed API look like?
NODE_ENV=test
BASIC=basic
BASIC_EXPAND=$BASIC
MACHINE=machine_env
MACHINE_EXPAND=$MACHINE
UNDEFINED_EXPAND=$UNDEFINED_ENV_KEY
ESCAPED_EXPAND=\$ESCAPED
MONGOLAB_DATABASE=heroku_db
MONGOLAB_USER=username
MONGOLAB_PASSWORD=password
MONGOLAB_DOMAIN=abcd1234.mongolab.com
MONGOLAB_PORT=12345
MONGOLAB_URI=mongodb://${MONGOLAB_USER}:${MONGOLAB_PASSWORD}@${MONGOLAB_DOMAIN}:${MONGOLAB_PORT}/${MONGOLAB_DATABASE}

MONGOLAB_USER_RECURSIVELY=${MONGOLAB_USER}:${MONGOLAB_PASSWORD}
MONGOLAB_URI_RECURSIVELY=mongodb://${MONGOLAB_USER_RECURSIVELY}@${MONGOLAB_DOMAIN}:${MONGOLAB_PORT}/${MONGOLAB_DATABASE}

WITHOUT_CURLY_BRACES_URI=mongodb://$MONGOLAB_USER:$MONGOLAB_PASSWORD@$MONGOLAB_DOMAIN:$MONGOLAB_PORT/$MONGOLAB_DATABASE
WITHOUT_CURLY_BRACES_USER_RECURSIVELY=$MONGOLAB_USER:$MONGOLAB_PASSWORD
WITHOUT_CURLY_BRACES_URI_RECURSIVELY=mongodb://$MONGOLAB_USER_RECURSIVELY@$MONGOLAB_DOMAIN:$MONGOLAB_PORT/$MONGOLAB_DATABASE

**Comment by IndexXuan** [comment]
it seems in @vue/cli-service/lib/util/loadEnv.js

**Comment by misenhower** [comment]
I agree this would be a nice addition. In the meantime, one workaround I'm using is setting the variables within `vue.config.js` -- you can just put something like this in there:

```js
process.env.VUE_APP_API_HOST = `http://localhost:${process.env.PORT}`
```

This seems to work properly and the expanded variable is made available within the app, etc.

You might even be able to use dotenv-expand this way.

**Comment by cmush** [comment]
This feature was added by this merge: https://github.com/vuejs/vue-cli/pull/3534/commits
Someone close this issue.
