### ISSUE TITLE
vue-cli 版本 3.2.1 获取中文 json 404，诱导出各种错误 

### ISSUE THREAD

**Issue by JuntingLiu** [vuejs/vue-cli#3022]
### Version
3.2.1

### Node and OS info
Node 10.13.0 / Npm 6.4.1 / macOs 10.13.6

### Steps to reproduce
全局安装， 运行 `vue ui` 就出现了

### What is expected?
出现原因可以描述告知下嘛，是缺少了 语言包嘛？

### What is actually happening?
报错异常，导致 `vue ui` 无法正常使用

**Comment by sodatea** [comment]
请问具体是什么样的错误？我看了一下虽然有报错但应该不影响使用啊。

**Comment by sodatea** [comment]
@CaiPeng1989 如果我没搞错的话，你用的是旧版本的 Vue CLI UI，请更新到最新版再试。

**Comment by CaiPeng1989** [comment]
@sodatea 很奇怪，在家里的电脑上3.2.1 `vue ui` 是可以打开了，周一去公司的时候再看看。

**Comment by CaiPeng1989** [comment]
@sodatea 公司电脑还是不行，卸载重装过后也不行。

**Comment by sodatea** [comment]
@CaiPeng1989 这样的话，1. 检查缓存 2. 检查浏览器版本 3. 检查是否全局 node_modules 目录下 @vue/cli-ui 版本并没有成功升级
再不行的话请把详细的报错贴出来。看截图无法判断是什么问题。

**Comment by CaiPeng1989** [comment]
@sodatea 应该是浏览器缓存导致的，新开无痕模式就能正常打开了。😂
