### ISSUE TITLE
nginx部署vue项目报错

### ISSUE THREAD

**Issue by okaxuan** [vuejs/vue-cli#3025]
### Version
3.2.1

### Reproduction link
[https://github.com/okaxuan/Test.git](https://github.com/okaxuan/Test.git)

### Node and OS info
node8.11.3/window10

### Steps to reproduce
新建了一个vue的模板项目，然后npm run build  再nginx部署报错。。。以前建的实际项目也通样操作都可以部署打开，现在总是报500，即使修改了vue.config.js中生产环境baseurl仍旧500

### What is expected?
location  / {
            root  F:\tsTest\test1\dist;
            index  index.html index.htm;
            try_files $uri $uri/ /index.html;  
		        }

### What is actually happening?
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
nginx 中error.log:rewrite or internal redirection cycle while internally redirecting to "/index.html"

**Comment by okaxuan** [comment]
解决了，地址变为F:/tsTest/test1/dist;以前反过来也识别

**Comment by okaxuan** [comment]
配置了vue.config.js module.exports = {
    baseUrl: '/ibuild/',
      outputDir: 'ibuild',
      assetsDir:"assets"
  }
部署后报错Uncaught SyntaxError: Unexpected token <   chunk-vendors.db3a0695.js:

**Comment by sodatea** [comment]
1. 大概率是 nginx 配置问题；
2. 复现链接里并没有任何实质内容，恕无法提供帮助。

**Comment by martinko2009** [comment]
用vue-cli3打包后，部署到nginx后，用浏览器访问页面，也爆出了Uncaught SyntaxError: Unexpected token <这个错误
