### ISSUE TITLE
log a warning when running `vue-cli-service serve [entry]` in a multi-page setup

### ISSUE THREAD

**Issue by chiaweilee** [vuejs/vue-cli#3031]
### Version
3.2.0

### Reproduction link
[https://github.com/chiaweilee/vidget/blob/dev/scripts/serve.js](https://github.com/chiaweilee/vidget/blob/dev/scripts/serve.js)

### Node and OS info
Node 10.13.0 / npm 6.4.1 / MacOS Mojave 10.14.1

### Steps to reproduce
- add "vue-cli-service serve src/main.js" to "scripts"
- npm run "scripts"
- serve works
- open serve url in browser

### What is expected?
- serve website works good

### What is actually happening?
- serve website works nothing
- no js file have injected into DOM

---
1. Entry been set

check @vue/cli-service/lib/commands/serve.js:69

```JavaScript
// entry arg
    const entry = args._[0]
    if (entry) {
      webpackConfig.entry = {
        app: api.resolve(entry)
      }
    }
```

webpackConfig.entry is expected of resolved "src/main.js"

2. usage: 'vue-cli-service serve [options] [entry]'

```JavaScript
api.registerCommand('serve', {
    description: 'start development server',
    usage: 'vue-cli-service serve [options] [entry]',
    options: {
      '--open': `open browser on server start`,
      '--copy': `copy url to clipboard on server start`,
      '--mode': `specify env mode (default: development)`,
      '--host': `specify host (default: ${defaults.host})`,
      '--port': `specify port (default: ${defaults.port})`,
      '--https': `use https (default: ${defaults.https})`,
      '--public': `specify the public network URL for the HMR client`
    }
  }
```

3. fine when use vue.config.js

```JavaScript
// vue.config.js
module.exports = {
  pages: {
    index: {
      entry: 'src/main.js'
    }
  }
}
```

**Comment by LinusBorg** [comment]
> It seems like vue-cli-service serve [options] [entry] can not work with vue.config.js's pages together?

Yes, naturally. having many pages means there is not one entry file, but many. So you can't provide *one* specific entry file when calling `serve`.

If you only have one page, don't use the `pages` option.

**Comment by LinusBorg** [comment]
> dozen ways of improvement could be made.

Enlighten us, please

> should it console a warning?

Certainly a good idea.

**Comment by chiaweilee** [comment]
```JavaScript
// lib/command/serve.js
const webpackConfig = api.resolveWebpackConfig() // line 48
// ...
// entry arg
    const entry = args._[0] // line 68
    if (entry) {
      webpackConfig.entry = {
        app: api.resolve(entry)
      }
    }
```

```JavaScript
// lib/config/app.js
const multiPageConfig = options.pages // line 140
// ...
// multi-page setup
      webpackConfig.entryPoints.clear()

      const pages = Object.keys(multiPageConfig)
      const normalizePageConfig = c => typeof c === 'string' ? { entry: c } : c

      pages.forEach(name => {
        const pageConfig = normalizePageConfig(multiPageConfig[name])
        const {
          entry,
          template = `public/${name}.html`,
          filename = `${name}.html`,
          chunks = ['chunk-vendors', 'chunk-common', name]
        } = pageConfig
```

queue: `api.resolveWebpackConfig()` -> `multi-page setup` -> if args._[0] modify `webpackConfig.entry`

`resolve config` -> `use config.pages` -> `modify config`?

this make no sense

**Comment by LinusBorg** [comment]
Well, it's common practice in CLI tools that command line arguments have priority over settings from a config file. 

`[entry]` in the CLI is defined as `the entry file`, not `an additional entry file`.

If you overwrite the entry in the CLI, then the entries from `config.pages` are no longer considered.

However a warning when `pages` is set might be useful.

**Comment by chiaweilee** [comment]
and it's not only in multi-page mode.

e.g

```JavaScript
// vue.config.js
module.exports = {
  pages: {
    index: {
      entry: 'example/main.js'
    }
  }
}
```

this also is not compatible with `vue-cli-service serve [entry]`

`vue.config.js` results `entry: { index: '...' }`
`vue-cli-service serve [entry]` results `entry: { app: '...' }`
