### ISSUE TITLE
Can't install package through Yarn (Windows)

### ISSUE THREAD

**Issue by petterw03** [vuejs/vue-cli#3035]
### Version
3.2.1

### Node and OS info
Node 8.12.0 / yarn 1.9.4 / Windows 7

### Steps to reproduce
Run `yarn add @vue/cli` or `yarn global add @vue/cli`

### What is expected?
The package should be added and installed.

### What is actually happening?
Gives error
```
[1/4] Resolving packages...
error Couldn't find package "@vue/cli" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

---
https://status.npmjs.org/ shows no errors, other packages install without problems. I have tried cleaning my yarn cache.

**Comment by deniszavadskiy** [comment]
For me **401 Unauthorized: @vue/cli-ui-addon-webpack@^3.2.1** error appears

**Comment by petterw03** [comment]
Tested on a Linux environment, it seems to be working fine there.

**Comment by deniszavadskiy** [comment]
> For me **401 Unauthorized: @vue/cli-ui-addon-webpack@^3.2.1** error appears

Seems to be not relative to this issue, sorry

**Comment by petterw03** [comment]
Trying to install through npm also gives errors, here's the log. It seems to be looking in the right registry (registry.npmjs.org) but for some reason it's Unauthorized.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@vue/cli' ]
2 info using npm@6.4.1
3 info using node@v8.12.0
4 verbose npm-session 2ef2fcec5c734d54
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 401 https://registry.npmjs.org/@vue%2fcli 211ms
8 silly fetchPackageMetaData error for @vue/cli@latest 401 Unauthorized: @vue/cli@latest
9 timing stage:rollbackFailedOptional Completed in 0ms
10 timing stage:runTopLevelLifecycles Completed in 673ms
11 verbose stack Error: 401 Unauthorized: @vue/cli@latest
11 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
11 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
11 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
11 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
11 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
11 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
11 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
11 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
11 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
11 verbose stack     at runCallback (timers.js:810:20)
11 verbose stack     at tryOnImmediate (timers.js:768:5)
11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
12 verbose cwd C:\jobb
13 verbose Windows_NT 6.1.7601
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@vue/cli"
15 verbose node v8.12.0
16 verbose npm  v6.4.1
17 error code E401
18 error 401 Unauthorized: @vue/cli@latest
19 verbose exit [ 1, true ]
```

**Comment by deniszavadskiy** [comment]
> Trying to install through npm also gives errors, here's the log. It seems to be looking in the right registry (registry.npmjs.org) but for some reason it's Unauthorized.
> 
> ```
> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'install',
> 1 verbose cli   '-g',
> 1 verbose cli   '@vue/cli' ]
> 2 info using npm@6.4.1
> 3 info using node@v8.12.0
> 4 verbose npm-session 2ef2fcec5c734d54
> 5 silly install loadCurrentTree
> 6 silly install readGlobalPackageData
> 7 http fetch GET 401 https://registry.npmjs.org/@vue%2fcli 211ms
> 8 silly fetchPackageMetaData error for @vue/cli@latest 401 Unauthorized: @vue/cli@latest
> 9 timing stage:rollbackFailedOptional Completed in 0ms
> 10 timing stage:runTopLevelLifecycles Completed in 673ms
> 11 verbose stack Error: 401 Unauthorized: @vue/cli@latest
> 11 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
> 11 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
> 11 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
> 11 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
> 11 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
> 11 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
> 11 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
> 11 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
> 11 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
> 11 verbose stack     at runCallback (timers.js:810:20)
> 11 verbose stack     at tryOnImmediate (timers.js:768:5)
> 11 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
> 12 verbose cwd C:\jobb
> 13 verbose Windows_NT 6.1.7601
> 14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@vue/cli"
> 15 verbose node v8.12.0
> 16 verbose npm  v6.4.1
> 17 error code E401
> 18 error 401 Unauthorized: @vue/cli@latest
> 19 verbose exit [ 1, true ]
> ```

removing .npmrc helps me to solve this problem

**Comment by petterw03** [comment]
Indeed, there seemed to have been an expired authToken in my .npmrc. Removing it solved the issue. Closing this but it's probably a good reference for others!
