### ISSUE TITLE
Bulk run command

### ISSUE THREAD

**Issue by imudin** [vuejs/vue-cli#3038]
### What problem does this feature solve?
I have few projects which are depending on each other. I would like run serve/build/lint and etc. commands in one time. 
Currently I need to open one by one and run each commands.

### What does the proposed API look like?
it could make group or selected projects and run command for all of them

**Comment by LinusBorg** [comment]
I'm not in fav our of this. 

This would add a whole new level if abstract up to the cli and complicate things even further, maintenance-wise.

I think vue-cli should be focussed on individual projects, not on orchestrating multiple projects together. 

Such a tool could be written by the community, though
