### ISSUE TITLE
警告：vue-cli3的event-stream依赖库包含病毒

### ISSUE THREAD

**Issue by tinhour** [vuejs/vue-cli#3039]
### Version
3.2.1

### Reproduction link
[https://github.com/dominictarr/event-stream/issues/116](https://github.com/dominictarr/event-stream/issues/116)

### Node and OS info
npm

### Steps to reproduce
https://github.com/dominictarr/event-stream/issues/116

### What is expected?
https://github.com/dominictarr/event-stream/issues/116

### What is actually happening?
https://github.com/dominictarr/event-stream/issues/116

**Comment by sodatea** [comment]
![3765f8e6-36c0-40d1-90de-ad79bbaed68d](https://user-images.githubusercontent.com/3277634/49195697-20d80380-f3c3-11e8-86a7-e307e7ab9f08.jpeg)

另外 npm 周二已将该恶意模块移除，所以周二以后新安装的用户不受影响。
