### ISSUE TITLE
`vue build` for components and plugins using TypeScript

### ISSUE THREAD

**Issue by xpepermint** [vuejs/vue-cli#304]
I believe we can not ignore Typescript anymore so having `vue build` command with support for TypeScript would be really helpful. 
For start I would appreciate if someone would explain or provide an example on how to write components and plugins using TypeScript together with this new `build` tool. 

Ref: @egoist

**Comment by egoist** [comment]
you can direclty add ts-loader in the config file.

**Comment by xpepermint** [comment]
Thanks for a quick answer. So you are talking about a custom configuration file?

**Comment by egoist** [comment]
Yep, check out https://github.com/vuejs/vue-cli/blob/master/docs/build.md#webpack

**Comment by xpepermint** [comment]
Works! This is feature is awesome! Thanks!
