### ISSUE TITLE
Cannot run npm run serve

### ISSUE THREAD

**Issue by alexxsexotic** [vuejs/vue-cli#3043]
### Version
3.2.1

### Node and OS info
Node v10.14.0/ npm 6.4.1

### Steps to reproduce
npm run serve

### What is expected?
vue-cli service serve open

### What is actually happening?
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'serve' ]
2 info using npm@6.4.1
3 info using node@v10.14.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle client@0.1.0~preserve: client@0.1.0
6 info lifecycle client@0.1.0~serve: client@0.1.0
7 verbose lifecycle client@0.1.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle client@0.1.0~serve: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/alexsexotic/Desktop/work/Test - mongod:node/client/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/alexsexotic/.npm-global/bin
9 verbose lifecycle client@0.1.0~serve: CWD: /Users/alexsexotic/Desktop/work/Test - mongod:node/client
10 silly lifecycle client@0.1.0~serve: Args: [ '-c', 'vue-cli-service serve' ]
11 info lifecycle client@0.1.0~serve: Failed to exec serve script
12 verbose stack Error: client@0.1.0 serve: `vue-cli-service serve`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:962:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
13 verbose pkgid client@0.1.0
14 verbose cwd /Users/alexsexotic/Desktop/work/Test - mongod:node/client
15 verbose Darwin 17.2.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
17 verbose node v10.14.0
18 verbose npm  v6.4.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error client@0.1.0 serve: `vue-cli-service serve`
23 error spawn ENOENT
24 error Failed at the client@0.1.0 serve script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by LinusBorg** [comment]
Can't reproduce this, can you provide a repository that fails for you?

**Comment by LinusBorg** [comment]
Nop reproduction provided
