### ISSUE TITLE
Can vue-cli-plugin(s) working together with one commond

### ISSUE THREAD

**Issue by xxholly32** [vuejs/vue-cli#3044]
### Version
3.2.1

### Reproduction link
[https://cli.vuejs.org/](https://cli.vuejs.org/)

### Node and OS info
Node 10.7.0 / yarn 1.7.0 / Windows 10

### Steps to reproduce
i have some cli-pluign，like vue-cli-plugin-vuepress and vue-cli-plugin-element ;

now I want to install both plug-ins at the same time with one command

like 

```
yarn add vue-cli-plugin-all

vue invoke all
```
or like vue create

```
vue create all
```

### What is expected?
 I want to install both plug-ins at the same time with one command

### What is actually happening?
none

---
就是我想做个插件，包含了一些插件比如包含vue-cli-plugin-vuepress and vue-cli-plugin-element ;

想一个命令安装，类似
```
yarn add vue-cli-plugin-all

vue invoke all
```
或者像vue创建的步骤类似
```
vue create all
```

**Comment by sodatea** [comment]
1. Use preset https://cli.vuejs.org/zh/guide/plugins-and-presets.html#preset
2. Plugin depending on another plugin is not supported currently, but there's a workaround https://github.com/vuejs/vue-cli/issues/2529#issuecomment-438577411
