### ISSUE TITLE
Yorkie installation fails which causes Vue CLI to fail

### ISSUE THREAD

**Issue by dentych** [vuejs/vue-cli#3056]
### Version
3.2.1

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (4) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
  Binaries:
    Node: 11.3.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: 3.2.1
```

### Steps to reproduce
vue create myapp

choose "default" setup

(Also tried the manual setup, which doesn't work either...)

### What is expected?
Vue installs successfully

### What is actually happening?
> yorkie@2.0.0 install /data/denni/Documents/git/cateroo-frontend/what/node_modules/yorkie
> node bin/install.js
>
> fs.js:122
>    throw err;
>    ^
>
> Error: EINVAL: invalid argument, open '/data/denni/Documents/git/cateroo-frontend/what/node_modules/yorkie/package.json'
>
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! yorkie@2.0.0 install: `node bin/install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the yorkie@2.0.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### Comments
I tried to install yorkie with `npm install yorkie`. That fails with the same error message, so it seems it is a problem with yorkie. Why is Vue depending on this? Yorkie doesn't even have an issues tab on GitHub. I am quite disappointed stuff like this can even happen... Is Vue just using latest available version of dependencies? Seems like a great cause for failure.

**Comment by ginomempin** [comment]
@dentych 

Why was this closed?
Did you find a solution?

**Comment by dentych** [comment]
@ginomempin Hey there! As far as I remember, I was trying to run VueCLI in a Docker container running either Alpine or Ubuntu (most likely I was using Alpine, but can't remember for certain). I tried installing Node on my system instead, without using Docker, and it seemed to work.

**Comment by ginomempin** [comment]
> I tried installing Node on my system instead, without using Docker, and it seemed to work.

You mean you installed it globally?
It does seem to work if you install packages globally.
I got the same error and it is still not working for me, though.
In case you are interested, I created a new ticket at #3466.

**Comment by dentych** [comment]
> You mean you installed it globally?

I mean, instead of installing Node inside a Linux Docker container, I installed it on the Windows host (the system that was running Docker). It seemed to work.

The architecture I used in the Docker container was Linux amd64

**Comment by dlencer** [comment]
I am facing the same issue trying to run vue-cli inside a container if I let `vue create` use npm; it works with yarn, though. I could confirm that `npm install yorkie@2.0.0` fails, while `yarn add yorkie@2.0.0` works. If relevant, I am not working as `root` in the container, but as a simple user.

**Comment by Soviut** [comment]
The same error occurs using `node:10.15.1-slim` (note the `-slim`) while `node:10.15.1` does not.

**Comment by stepansib** [comment]
Solved issue by using latest node image for container `FROM node:latest`

**Comment by alexisrolland** [comment]
I was facing the same error while trying to create a Vue project from inside a Docker container. My Dockerfile was as follow:
```
FROM node:lts-alpine

# Working directory and mount volume
ARG PROJECT_DIR=/srv/app
RUN mkdir -p $PROJECT_DIR
WORKDIR $PROJECT_DIR
VOLUME $PROJECT_DIR

# Install Vue CLI
RUN npm install -g @vue/cli
```

I build the Docker image and connect to the Docker container with these commands:
```
$ docker build -t vue-app-setup:latest .
$ docker run -it --rm -v "C:\my_path\vue-app-setup:/srv/app" vue-app-setup sh
```

In the Docker container, I run `vue create my_project`.
I got the error message: 
> Failed at the yorkie@2.0.0 install script

Same as @stepansib, I solved my issue with `FROM node:latest` instead of `FROM node:lts-alpine` in my Dockerfile

**Comment by rodrigogs** [comment]
No idea why it's closed if it is still failing on Docker

**Comment by Cebape** [comment]
This error (Yorkie@2.0.0) is related to the security attributes of the project-vuejs folder. So, create your projects outside the root / folder, make Linux updates (Ubuntu ...) and success to everyone!

**Comment by LiamKarlMitchell** [comment]
Updating npm to latest fixed it for me.
```bash
npm install -g npm@latest
```

When trying to use in a Dockerfile FROM php:7.3-fpm

**Comment by thenovacreator** [comment]
I had the same problem with `Error: Cannot find module '../../package.json'`. Was using the linux subsystem. This article says it might be a problem with permissions: https://www.programmersought.com/article/58086441997/

Switching user in the subsystem did not get me along. Running the vue create command in the plain windows cmd with newest npm version solved it.
