### ISSUE TITLE
How to add more than one index file

### ISSUE THREAD

**Issue by fega** [vuejs/vue-cli#306]
Hello, I have in my project two parts, the index.html, and the admin.html 

I want to keep it separate but, also share some components, how can I achieve that?

**Comment by posva** [comment]
Please make sure to read the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening new issues. Questions should be posted on the [forum](https://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Thanks.

---

You should provide more info on the forum post, like the kind of application you're building, if you are using a bundler, laravel or something else.

**Comment by fega** [comment]
thanks so much!, I forgot read the guidelines first, Sorry!

**Comment by appsparkler** [comment]
Here are two links that might be helpful to someone:

MULTIPLE-PAGES
https://stackoverflow.com/questions/51692018/multiple-pages-in-vue-js-cli
https://cli.vuejs.org/config/#pages
