### ISSUE TITLE
构建为一个库

### ISSUE THREAD

**Issue by xushuailing** [vuejs/vue-cli#3064]
### Version
3.2.0

### Environment info
```
mac/ vue-cli-service build  --target lib --name index src/index.js
```

### Steps to reproduce
打包出来体积过大，其中里面包含 `node_modules/@vue/cli-service/lib/commands/build`，是否正常.

```js
// index.js
import HelloWorld from './components/HelloWorld.vue';
```

```js
// chartData
[{
	"label": "index.umd.js",
	"statSize": 8605,
	"parsedSize": 13979,
	"gzipSize": 3634,
	"groups": [{
		"label": "src/components",
		"path": "./src/components",
		"statSize": 1213,
		"groups": [{
			"id": "",
			"label": "HelloWorld.vue?vue&type=style&index=0&id=379548a4&scoped=true&lang=css&",
			"path": "./src/components/HelloWorld.vue?vue&type=style&index=0&id=379548a4&scoped=true&lang=css&",
			"statSize": 1213,
			"parsedSize": 2162,
			"gzipSize": 436
		}],
		"parsedSize": 2162,
		"gzipSize": 436
	}, {
		"label": "node_modules/@vue/cli-service/lib/commands/build",
		"path": "./node_modules/@vue/cli-service/lib/commands/build",
		"statSize": 7392,
		"groups":[...]
		"parsedSize": 7688,
		"gzipSize": 2313
	}]
}]
```

### What is expected?
打包出来不包含开发依赖

### What is actually happening?
打包出来体积过大，包含开发依赖

**Comment by sodatea** [comment]
1. 请提供复现
2. 准确地说，我们引入的是 `@vue/cli-service/lib/commands/build/entry-lib.js` 和 `@vue/cli-service/lib/commands/build/setPublicPath.js` 这两个文件，不是开发依赖而是打包 library 所必须的入口文件和依赖。

**Comment by unhappy224** [comment]
> 1. 请提供复现
> 2. 准确地说，我们引入的是 `@vue/cli-service/lib/commands/build/entry-lib.js` 和 `@vue/cli-service/lib/commands/build/setPublicPath.js` 这两个文件，不是开发依赖而是打包 library 所必须的入口文件和依赖。

有没有办法将entry-lib.js和@babel/runtime从打包分离出来呢？我想每个组件都打包成一个js，然后再共用这2个依赖，不然打出来一个js里面99%是这2个依赖

**Comment by lihaonanGY** [comment]
@sodatea 
@vue/cli-service/lib/commands/build/entry-lib.js 是不是过大，150k
![image](https://user-images.githubusercontent.com/19931285/68754327-6d9f0380-0641-11ea-91e8-aaf001f807fd.png)
