### ISSUE TITLE
tsx custom tag name error

### ISSUE THREAD

**Issue by troy351** [vuejs/vue-cli#3067]
### Version
3.2.1

### Reproduction link
no need

### Environment info
```
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Node: Not Found
    Yarn: Not Found
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-preset-app:  3.2.0
    @vue/cli-overlay:  3.2.0
    @vue/cli-plugin-babel: ^3.2.0 => 3.2.0
    @vue/cli-plugin-typescript: ^3.2.0 => 3.2.0
    @vue/cli-service: ^3.2.0 => 3.2.0
    @vue/cli-shared-utils:  3.2.0
    @vue/component-compiler-utils:  2.3.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    vue: ^2.5.17 => 2.5.17
    vue-class-component: ^6.3.2 => 6.3.2
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.4.2
    vue-property-decorator: ^7.2.0 => 7.2.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.17 => 2.5.17
    vue-template-es2015-compiler:  1.6.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
- create a new project with only babel and typescript (use class style component).
- update dependencies to the lateset version. **this is important !!!**
- remove `template` and add render code in `App.vue`
```tsx
render() {
    const obj = {
      tag: "HelloWorld"
    };

    const TagName = obj.tag;
    return <TagName class="name" />;
  }
```

### What is expected?
No Error

### What is actually happening?
Error `Type '{ class: string; }' is not assignable to type '{}'`

---
However, the codes below works fine
```tsx
render() {
    // this works
    const TagName = "HelloWorld";
    return <TagName class="name" />;
  }
```
```tsx
render() {
    // this also works
    const obj = {
      tag: "HelloWorld"
    };

    const TagName = obj.tag;
    return <TagName />;
  }
```

**Comment by LinusBorg** [comment]
This also happens in .tsx files, I came across this in a project of mine. It seems to be related to changes within Typescript as it worked with TS 2.*, but not TS 3.*

This is however not directly related to vue-cli, it's likely related to the way that [babel-plugin-transform-vue-jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx) works differently than React JSX. We might need some extra JSX Typings?

I would kindly ask you to re-open our issue in thei repository.

**Comment by troy351** [comment]
But that is a pure js repo, could it solve or deal with a ts problem?
btw, is there any workaround?

**Comment by LinusBorg** [comment]
Yes and no. 

* To transform JSX for Vue, you have to use babel and this plugin alongside typescript.
* Typescript itself has `jsx: preserve` set
* I suspect that this is either
  * a typing problem, in which case we might consider adding JSX types for Vue-JSX to this babel-plugin
  * a problem with the way that vue-jsx differs in terms of Syntax/Semantics to React, which confuses Typescript - which would also be evaluated/considered by the maintainers of that plugin.
