### ISSUE TITLE
I can't update vue-cli 

### ISSUE THREAD

**Issue by Gonzalo2683** [vuejs/vue-cli#307]
I recently installed vue-cli and when a new project started a message appeared that there is a new version of vue-cli, but when I want to update it is not updated.

The steps you take are as follows:

npm install -g vue-cli // ok installed
vue init webpack testproj
Message tells me that there is a newer version of vue-cli
Latest 2.8.0
Current 2.3.1
Stopped the creation of the project
Execute npm update -g vue-cli // but is not updated

How can I update with latest version?

Thanks

**Comment by zigomir** [comment]
I had similar issue and then ran `npm install -g vue-cli@2.8.0` to get the latest one.

**Comment by posva** [comment]
You can also do `npm i -g vue-cli@latest` to install the latest version

**Comment by chengkoon** [comment]
To anyone who might still be stuck in a version 2.x after uninstalling and reinstalling version 3.x a few times, try closing your terminal and "vue --version" on a new terminal. That might do the trick.
