### ISSUE TITLE
Make module transpiling for Vue CLI Service part of the public API

### ISSUE THREAD

**Issue by masonheverett** [vuejs/vue-cli#3073]
### What problem does this feature solve?
I found that when writing unit tests for my pure JS files using mocha and sinon, I could not run the tests with vue cli because sinon cannot mock es6 imports. I did not want to switch to commonjs or to run unit tests outside of the Vue CLI, so I found a workaround is to set VUE_CLI_BABEL_TRANSPILE_MODULES=true so that sinon is interfacing with commonjs modules rather than es6 modules. This solution, of course, uses internal features of Vue CLI, not a public facing configuration. I think it would be worth making this configuration and other babel configurations public so that developers can use Vue CLI and @vue/babel-preset-app even when they have specific transpiling needs.

### What does the proposed API look like?
The workaround I found works for me, so if this is something that the core team finds worth pursuing, I'd be happy to discuss what more fine grained babel configuration might look like. But I have no thought about what the proposed API might look like thus far.

**Comment by LinusBorg** [comment]
you can simply use what babel gives you:
``` 
presets: ['@vue/app'],
env: {
  test: {
    presets: [['@vue/app', { modules: 'commonjs' }]]
  }
}
```

**Comment by masonheverett** [comment]
Ah, thanks. I couldn't get the right syntax for that to work, but what you have works perfectly. I appreciate your time.
