### ISSUE TITLE
Can I tell the difference rootpath between the --preset mode and invoke mode

### ISSUE THREAD

**Issue by xxholly32** [vuejs/vue-cli#3081]
### Version
3.2.1

### Reproduction link
[https://github.com/xxholly32/vue-cli-plugin-xx-demo](https://github.com/xxholly32/vue-cli-plugin-xx-demo)

### Environment info
```
node10 win10
```

### Steps to reproduce
```
vue create -p xxholly32/vue-cli-plugin-xx-demo my-project

// check default option
```

### What is expected?
I want docs that automatically generated files is install my-project folder

### What is actually happening?
docs file is outside

---
```
cd my-project

vue invoke vuepress
```

is working

so 

Can I tell the difference rootpath between the --preset mode and invoke mode

**Comment by LinusBorg** [comment]
this has to be solved in `vue-cli-plugin-vuepress`, you should open an issue there. the should use `api.resolve()` to get the correct path:

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli/lib/GeneratorAPI.js#L64-L72

...or use `api.render()` istead of manually copying files.

**Comment by xxholly32** [comment]
thx a lot
