### ISSUE TITLE
https://new-issue.vuejs.org/?repo=vuejs/vue-cli

### ISSUE THREAD

**Issue by lanmei** [vuejs/vue-cli#3082]
### Version
3.2.1

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Environment info
```
all
```

### Steps to reproduce
npm run build

### What is expected?
Automatic deal with sprite img

### What is actually happening?
I should config webpack sprite plugin like webpack-spritesmith manual in vue-cli 3.0  ?

**Comment by LinusBorg** [comment]
Sorry but you're not making any sense
