### ISSUE TITLE
vue-cli创建项目时出现问题

### ISSUE THREAD

**Issue by oygrape** [vuejs/vue-cli#3086]
https://new-issue.vuejs.org/?repo=vuejs/vue-cli

我安装了vue-cli 后，执行“vue create hello”
运行完成后，hello项目下只有三个文件
![1](https://user-images.githubusercontent.com/20414366/49559934-78d6b300-f94b-11e8-8964-231470e91639.png)

![2](https://user-images.githubusercontent.com/20414366/49559976-a7ed2480-f94b-11e8-8870-16caf87525c6.png)
请问是什么问题

**Comment by sodatea** [comment]
现在 Vue CLI 最新版是 3.2.1，你更新一下版本试试？
