### ISSUE TITLE
URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'

### ISSUE THREAD

**Issue by jhechtf** [vuejs/vue-cli#3089]
### Version
3.1.1

### Node and OS info
yarn 1.12.3, windows 10 pro, node 10.11.0

### Link to repository
https://github.com/jhechtf/vue-issue-3089

### Steps to reproduce
run yarn serve in repository

### What is expected?
No error, webpage / application is displayed

### What is actually happening?
receive error URIError: Failed to decode param '/%3c%=%20BASE_URL%20%3Efavicon.ico' followed by what appears to be errors with the express framework

---
This had happened to me once before, but deleting node_modules and reinstalling fixed it. That has not been the case with this current iteration -- I've deleted node_modules twice and still am running into the issue. From what I read of other similar issues, the issue was caused by a hash symbol in their directory structure, which I do not have. Another one mentioned something about a baseUrl option in their vue.config.js, which I did not have, and a third mentioned scss imports that are invalid being the cause. I removed _all_ `@import` statements within the application itself and nothing changed. 

Up until a few days ago, it worked just fine. I can't say I did anything particularly out of the ordinary for the project either, I just created a new component, tested it out, exited the server as I had to go somewhere for a bit. When I came back, however, I couldn't get the app to work.

The whole error block I receive is:

```URIError: Failed to decode param '/%3C%=%20BASE_URL%20%%3Efavicon.ico'
    at decodeURIComponent (<anonymous>)
    at decode_param (C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\router\layer.js:172:12)
    at Layer.match (C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\router\layer.js:123:27)
    at matchLayer (C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\router\index.js:574:18)
    at next (C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\router\index.js:220:15)
    at expressInit (C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\router\index.js:275:10)
    at query (C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\Jim\projects\alert-logic\code\node_modules\express\lib\router\index.js:335:12)
```

I unfortunately cannot share a repo link as some of the code is necessary to run is API credentials that even if I deleted would be easily visible in the history of the files. I could maybe create a fresh repo and submit my current code to it (that obviously wouldn't have my credentials in it), but I'm unsure just how well that is going to help if I'm honest.

**Comment by LinusBorg** [comment]
We can't do anything to help you with this issue if we know nothing about the project.

**Comment by LinusBorg** [comment]
The only tip I can give you is that it has something to do with html webpack plugin, as this plugin is responsible to transform the template for `index.html` (located in `/public/index.html`. 

In this file we use EJS (the template syntax supported by html-webpack-plugin). This template syntax seems to not be compiled in your project, for whatever reason.

**Comment by jhechtf** [comment]
Updated original post with URL that can be used for reproduction.

**Comment by sodatea** [comment]
The reproduction repo is not runnable
![image](https://user-images.githubusercontent.com/3277634/49989593-ae1b7a80-ffb5-11e8-8ade-503fe713f507.png)

![image](https://user-images.githubusercontent.com/3277634/49989538-76143780-ffb5-11e8-89ef-66f18e75ed2f.png)

**Comment by jhechtf** [comment]
I'm looking into it right now, but even with editing that line I am still getting the decode URI error.

**Comment by jhechtf** [comment]
Alright so after awhile, I've got it.

The answer is that it _does_ seem to have something to do with SCSS. 

at some point or another I apparently deleted the import of bootstrap in my `App.vue` file, and one of the elements in there was calling `@extend .pt-4`, which could obviously no longer be found. Unfortunately due to the ridiculously long output by TSLint, I couldn't ever see either of those two errors.

**Comment by xanxuz** [comment]
The system threw me an error when trying to open the landing page.

![image](https://user-images.githubusercontent.com/11968584/64873851-f84e8c80-d617-11e9-87cb-9c41f608e9ce.png)

![image](https://user-images.githubusercontent.com/11968584/64873794-da812780-d617-11e9-8e36-58bfddbefc68.png)

**Comment by mcasto** [comment]
I rammed my head against this particular wall for about twelve hours before stumbling on the problem. I had set "publicPath" in vue.config.js

I don't know *why* it caused this problem, but when I removed that setting, everything worked.

**Comment by AlanKnightly** [comment]
> The system threw me an error when trying to open the landing page.
> 
> ![image](https://user-images.githubusercontent.com/11968584/64873851-f84e8c80-d617-11e9-87cb-9c41f608e9ce.png)
> 
> ![image](https://user-images.githubusercontent.com/11968584/64873794-da812780-d617-11e9-8e36-58bfddbefc68.png)

Hi @xanxuz  I met the same problem, wonder how to solve this? I dont have baseUrl or publicPath in my vue.config.js

**Comment by onorao1** [comment]
The problem I encountered was when inputting double slashes to redirect an error message. The three slashes matched normally to the 404 page
<img width="609" alt="err1" src="https://github.com/vuejs/vue-cli/assets/161396998/3ff19a94-7443-4c62-9658-2540cbed7358">
