### ISSUE TITLE
Vue UI serve task generating "Couldn't parse bundle asset" warning for async component

### ISSUE THREAD

**Issue by daniel-bolton** [vuejs/vue-cli#3093]
### Version
3.2.1

### Reproduction link
[https://github.com/daniel-bolton/lazy-load-example](https://github.com/daniel-bolton/lazy-load-example)

### Environment info
```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
  Binaries:
    Node: Not Found
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-preset-app:  3.2.0
    @vue/cli-overlay:  3.2.0
    @vue/cli-plugin-babel: ^3.2.0 => 3.2.0
    @vue/cli-plugin-eslint: ^3.2.0 => 3.2.1
    @vue/cli-service: ^3.2.0 => 3.2.0
    @vue/cli-shared-utils:  3.2.0
    @vue/component-compiler-utils:  2.3.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    eslint-plugin-vue: ^5.0.0-0 => 5.0.0
    vue: ^2.5.17 => 2.5.17
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.4.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.17 => 2.5.17
    vue-template-es2015-compiler:  1.6.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Clone the *lazy-load-example* repo locally
2. Open the Vue UI
3. Import the project
4. In *Tasks*, run the serve task with the default parameters
5. Switch to the *Output* view to see the warning after the task has run

### What is expected?
No warning to appear.

### What is actually happening?
The following warning is displayed in the output.

```
Couldn't parse bundle asset "{path-to-project}\lazy-load-example\dist\0.js".
Analyzer will use module sizes from stats file.
```

---
~~I'm using a windows machine, so not sure if the issue could be path/permissions related.~~

**Update:** just tested on Linux and the same thing happens.

**Comment by stefann-sasori** [comment]
I solved the same issue by updating vue-template-compiler

**Comment by daniel-bolton** [comment]
> I solved the same issue by updating vue-template-compiler

Thanks for replying @stefann-sasori -- just tried updating the vue-template-compiler to 2.5.20 and still had the same warning. Would you be able to run **vue info** and post the results, so I could compare your environment with mine?

**Comment by torbenjk** [comment]
I get this error - with the latest version of vue-template-compiler.
What was the solution that worked for you?

**Comment by hooray** [comment]
I used vue-template-complier 2.5.22 and the problem still exists

**Comment by daniel-bolton** [comment]
@MartinMa kindly pointed out in another [issue](https://github.com/vuejs/vue-cli/issues/3094#issuecomment-446604369) that there is a reference to this on the Webpack Bundle Analyzer repo [here](https://github.com/webpack-contrib/webpack-bundle-analyzer#i-dont-see-gzip-or-parsed-sizes-it-only-shows-stat-size). As the problem appears to relate to that and not the vue ui, I'm going to close this issue.

**Comment by s547926509s** [comment]
I have the same warning displayed. But the HMR is working . I also have no idea why it warn

**Comment by barayuda** [comment]
Same here, with latest version I have updated one week ago

**Comment by sirber** [comment]
I don't have vue-template-complier and I get the issue.

**Comment by Pluto1010** [comment]
Same here. 

> WARN  Couldn't parse bundle asset "/Users/home/projectpath/dist/about.283637433f63f2d405e1.js".
> Analyzer will use module sizes from stats file.

Interesting for me is that this file is not existing. 

The file existing is called dist/js/about.7465cdb5.js
You see the different hash I think.

**Comment by rodrigoaraujolima92** [comment]
Alguem tem alguma resposta?

**Comment by gitKon** [comment]
Hey, i'm getting this error
`Couldn't parse bundle asset "....\dist\js\app.dbdaa6cd.js"`
which I think is related to your error. Anything that worked?
