### ISSUE TITLE
Vue UI serve task generating "Couldn't parse bundle asset" warning for async component

### ISSUE THREAD

**Issue by daniel-bolton** [vuejs/vue-cli#3094]
### Version
3.2.1

### Reproduction link
[https://github.com/daniel-bolton/lazy-load-example](https://github.com/daniel-bolton/lazy-load-example)

### Environment info
```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
  Binaries:
    Node: Not Found
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-preset-app:  3.2.0
    @vue/cli-overlay:  3.2.0
    @vue/cli-plugin-babel: ^3.2.0 => 3.2.0
    @vue/cli-plugin-eslint: ^3.2.0 => 3.2.1
    @vue/cli-service: ^3.2.0 => 3.2.0
    @vue/cli-shared-utils:  3.2.0
    @vue/component-compiler-utils:  2.3.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    eslint-plugin-vue: ^5.0.0-0 => 5.0.0
    vue: ^2.5.17 => 2.5.17
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.4.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.17 => 2.5.17
    vue-template-es2015-compiler:  1.6.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Clone the *lazy-load-example* repo locally
2. Open the Vue UI
3. Import the project
4. In *Tasks*, run the serve task with the default parameters
5. Switch to the *Output* view to see the warning after the task has run

### What is expected?
No warning to appear.

### What is actually happening?
The following warning is displayed in the output.

```
Couldn't parse bundle asset "{path-to-project}\lazy-load-example\dist\0.js".
Analyzer will use module sizes from stats file.
```

---
I'm using a windows machine, so not sure if the issue could be path/permissions related.

**Comment by MartinMa** [comment]
@daniel-bolton I have the same problem with a hello world vue app generated using the vue cli. Why did you close this issue? I'm wondering what I'm doing wrong.

**Comment by MartinMa** [comment]
I guess this is "normal behaviour"? See [I don't see gzip or parsed sizes, it only shows stat size](https://github.com/webpack-contrib/webpack-bundle-analyzer#i-dont-see-gzip-or-parsed-sizes-it-only-shows-stat-size).

**Comment by daniel-bolton** [comment]
Hi @MartinMa, I accidentally created two issues for this, so closed this one. The 'open' one is available [here](https://github.com/vuejs/vue-cli/issues/3093).

> I guess this is "normal behaviour"? See [I don't see gzip or parsed sizes, it only shows stat size](https://github.com/webpack-contrib/webpack-bundle-analyzer#i-dont-see-gzip-or-parsed-sizes-it-only-shows-stat-size).

Hadn't seen that section in the Webpack Bundle Analyzer's docs -- thanks for pointing that out!

**Comment by N1Mirzo** [comment]
Hey run this code in a terminal in your project to make it working "npm run build". Bsically it is not a problem!

**Comment by arajay** [comment]
This is still an issue and running a build does not resolve it.

**Comment by sabbir420** [comment]
I am also facing the same issue. 
`Couldn't parse bundle asset "~\vue\vue-travel-app\dist\js\chunk-vendors.js".
Analyzer will use module sizes from stats file.`

**Comment by katzcentrality** [comment]
Me as well. I don't look to have the chunk-vendors.js file in the path. I can try to run this in the terminal, but if I want to stick with the GUI, what's the alt? 

Couldn't parse bundle asset "/vue/to-do/dist/js/chunk-vendors.js".
Analyzer will use module sizes from stats file.

**Comment by marissagroves** [comment]
Guys, I have the same problem. Has anyone solved this?

**Comment by yoshwata** [comment]
Me too

**Comment by marcvan-dijk** [comment]
I get the following message, seems to be related?

```
 WARN  
Couldn't parse bundle asset "....\dist\1.959fba9063e8854d51c8.hot-update.js".
Analyzer will use module sizes from stats file.
```

**Comment by MentalGear** [comment]
Same for me after running the default hello world app from vue ui.

>  WARN  
Couldn't parse bundle asset "/Users/Tom/Desktop/Task Manager/code/dist/js/about.js".
Analyzer will use module sizes from stats file.

`
{
"version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.4",
    "register-service-worker": "^1.7.1",
    "vue": "^2.6.11",
    "vue-router": "^3.1.6"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.3.0",
    "@vue/cli-plugin-eslint": "~4.3.0",
    "@vue/cli-plugin-pwa": "^4.3.1",
    "@vue/cli-plugin-router": "~4.3.0",
    "@vue/cli-plugin-unit-jest": "~4.3.0",
    "@vue/cli-service": "~4.3.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/test-utils": "1.0.0-beta.31",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.1.1",
    "eslint-plugin-vue": "^6.2.2",
    "node-sass": "^4.12.0",
    "prettier": "^1.19.1",
    "sass-loader": "^8.0.2",
    "vue-cli-plugin-pug": "^1.0.7",
    "vue-template-compiler": "^2.6.11"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended",
      "@vue/prettier"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {},
    "overrides": [
      {
        "files": [
          "**/__tests__/*.{j,t}s?(x)",
          "**/tests/unit/**/*.spec.{j,t}s?(x)"
        ],
        "env": {
          "jest": true
        }
      }
    ]
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ],
  "jest": {
    "preset": "@vue/cli-plugin-unit-jest"
  }
}`

**Comment by UbaldoRosas** [comment]
Reinstall node_modules has worked for me

**Comment by yjwuws** [comment]
Try this
npm install node-sass --save

**Comment by Kyawkhaing444** [comment]
> I get the following message, seems to be related?
> 
> ```
>  WARN  
> Couldn't parse bundle asset "....\dist\1.959fba9063e8854d51c8.hot-update.js".
> Analyzer will use module sizes from stats file.
> ```

Have you fixed this? Can I get your solution?

**Comment by mnbarinov** [comment]
just change path  in  plugins\element.js 
//import 'element-plus/lib/theme-chalk/index.css'
import 'element-plus/theme-chalk/index.css'

**Comment by diskodenso** [comment]
im facing the same issue - is there a way to fix this ? pls help :S

**Comment by 6e5** [comment]
Guys for my side the problem was from the code I wrote. Make sure you guys check the console logs in the dev tools in your browser. It showed where the logic error was and worked fine after I fixed it. So, it's not related to the GUI.

**Comment by DEZRUSSELL** [comment]
I'll check it out now

**Comment by DEZRUSSELL** [comment]
Looks like a problem with Vue 2 itself

**Comment by awulkan** [comment]
> I get the following message, seems to be related?
> 
> ```
>  WARN  
> Couldn't parse bundle asset "....\dist\1.959fba9063e8854d51c8.hot-update.js".
> Analyzer will use module sizes from stats file.
> ```

Did you manage to solve it? I'm running into the same issue.
