### ISSUE TITLE
Allow async web components to pass credentials

### ISSUE THREAD

**Issue by jfuehner** [vuejs/vue-cli#3095]
### What problem does this feature solve?
It would be awesome if a web component bundle that loads components asynchronously could also pass credentials when appropriate.

Presently when bundling a series of components up with a build target such as:

vue-cli-service build --target wc-async --name foo 'src/components/*.vue'

A number of files are created which Vue loads as needed. It would be awesome if we could tell Vue to also pass credentials when loading the additional .js files from the bundle.

Thanks!

### What does the proposed API look like?
Unsure, a simple boolean true/false property which would allow the dynamic script tags to be generated with the crossOrigin property perhaps?

**Comment by sodatea** [comment]
There's a webpack config for this
```js
module.exports = {
  chainWebpack: config => config.output.crossOriginLoading('use-credentials')
}
```
