### ISSUE TITLE
All imported files (inside project) aren't transpiled by babel

### ISSUE THREAD

**Issue by jgribonvald** [vuejs/vue-cli#3096]
### Version
3.2.1

### Reproduction link
[https://github.com/uPortal-contrib/uPortal-web-components/tree/master/%40uportal/eyebrow-user-info](https://github.com/uPortal-contrib/uPortal-web-components/tree/master/%40uportal/eyebrow-user-info)

### Environment info
```
Environment Info:

  System:
    OS: Linux 3.13 Ubuntu 14.04.5 LTS, Trusty Tahr
    CPU: (8) x64 Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
  Binaries:
    Node: 10.14.0 - ~/.npm/bin/node
    Yarn: 1.12.3 - /usr/bin/yarn
    npm: 6.4.1 - ~/.npm/bin/npm
  Browsers:
    Chrome: 71.0.3578.80
    Firefox: 63.0.3
  npmPackages:
    @kazupon/vue-i18n-loader: ^0.3.0 => 0.3.0 
    @vue/babel-preset-app:  3.2.0 
    @vue/cli-overlay:  3.2.0 
    @vue/cli-plugin-babel: ^3.2.0 => 3.2.0 
    @vue/cli-plugin-eslint: ^3.2.1 => 3.2.1 
    @vue/cli-service: ^3.2.0 => 3.2.0 
    @vue/cli-shared-utils:  3.2.0 
    @vue/component-compiler-utils:  2.3.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    babel-plugin-transform-vue-jsx:  4.0.1 
    eslint-plugin-vue:  4.7.1 
    vue: ^2.5.17 => 2.5.17 
    vue-cli-plugin-i18n: ^0.5.1 => 0.5.1 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.1 
    vue-i18n: ^8.4.0 => 8.4.0 
    vue-loader:  15.4.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.17 => 2.5.17 
    vue-template-es2015-compiler:  1.6.0 
  npmGlobalPackages:
    @vue/cli: 3.2.1

```

### Steps to reproduce
npm run build
open dist/eyebrow-user-info.js
and search "=>" the only part having it come from /src/i18n.js which isn't transpiled in es5.

### What is expected?
all local file imported should be transpiled

### What is actually happening?
one file imported isn't transpiled

**Comment by sodatea** [comment]
Though I haven't found the root cause, it seems to be related to vue-cli-plugin-i18n as the file gets compiled correctly once I remove that plugin.

**Comment by ChristianMurphy** [comment]
https://github.com/Jasig/NotificationPortlet/pull/139 is seeing the same issue in the `notification-icon` component, which is not currently using `vue-cli-plugin-i18n`.

**Comment by sodatea** [comment]
Just realized it was by design:
https://github.com/vuejs/vue-cli/blob/ad9ef4cea79fcbc82060316304b1348e09cb760f/packages/%40vue/babel-preset-app/index.js#L64-L76

**Comment by sodatea** [comment]
https://github.com/vuejs/vue-web-component-wrapper#compatibility

**Comment by jgribonvald** [comment]
Thanks for the response but is there a way to unlock that ?, because if you run before a build ` "prebuild": "babel node_modules/@vue/web-component-wrapper/dist/vue-wc-wrapper.js -o node_modules/@vue/web-component-wrapper/dist/vue-wc-wrapper.js"`it's OK !

**Comment by ChristianMurphy** [comment]
@jgribonvald using `@babel/preset-env` directly will bypass the overrides applied by `@vue/babel-preset-app`.
