### ISSUE TITLE
The project can't build, character error

### ISSUE THREAD

**Issue by urameshibr** [vuejs/vue-cli#310]
Hello, today im trying to craft a new project, the npm and node are updated.
i had followed this steps:

```
npm install -g vue-cli
vue init webpack up
cd up
npm install
npm run dev
```

After this i receive an error...
![image](https://cloud.githubusercontent.com/assets/5429620/22392308/c1f1139c-e4de-11e6-8db7-3685e3586f1e.png)

Any about unknow character, following the line i discover:

![image](https://cloud.githubusercontent.com/assets/5429620/22392317/e688e9aa-e4de-11e6-8de9-b1264ec5d77d.png)

See the cursor shining, maybe the character **>** have an error. idk.

My enviroment:
Windows 10 PRO
Laragon Full (apache+mariadb myqsl + php+ cmder + notepad++ and sublime text 2)
node version: v6.9.4
npm version: 4.1.2
vue-cli version: 2.8.0

**Comment by posva** [comment]
I couldn't reproduce the error. Are you sure you don't added any special character to the App.vue file?

**Comment by urameshibr** [comment]
@posva the special character was a **>** , a friend give me solution for this, just to install the yarn dependencies. Is working now.
