### ISSUE TITLE
Localization route - overflow-y is not scrollable

### ISSUE THREAD

**Issue by aljaxus** [vuejs/vue-cli#3103]
### Version
3.2.1

### Environment info
```
info not needed - would like to keep things private
important: using i18n package
```

### Steps to reproduce
> Create a demo project
> install i18n (https://kazupon.github.io/vue-i18n/)
> go to http://localhost:8000/addon/org.kazupon.vue-i18n/
> create enough messages to fill your screen height
> try to scroll

### What is expected?
The window should be scrollable

### What is actually happening?
The window is not scrollable

---
It is fixable by adding `overflow-y: scroll;` to element 
```<div data-v-7ba5bd90="" data-v-2a0d3bdd="" class="project-localizations router-view">```

**Comment by LinusBorg** [comment]
From what I can decipher from the description, this has nothing to do with vue-cli.

**Comment by aljaxus** [comment]
Alright, could you link me to the correct repo to create the issue at? 
I assumed it's this one, since the only GitHub repo link I found on the dashboard while in `vue ui` was pointing to VueCLI's one, so I created the issue here.

**Comment by sodatea** [comment]
That component was rendered by vue-cli-plugin-i18n so please raise an issue there.
