### ISSUE TITLE
Any way to use hashed static assets in index.html?

### ISSUE THREAD

**Issue by georgyfarniev** [vuejs/vue-cli#3112]
### What problem does this feature solve?
I would like to add hashed assets to statically generated top level html file for favicon and loading indicator instead of setting fixed path manually because I use long term caching on http proxy side.  I didn’t find any way to do it after studying html-webpack-plugin, did I missed something? It seems to be very common use case for favicon and logo embedded in html file. 

### What does the proposed API look like?
Maybe we can wrap  needed image files with some function in vue.config.js to generate hashed representation and then pass it somehow to Webpack html plug-in via parameters? Also I think this part should be documented

**Comment by sodatea** [comment]
This can be done by adding plugins for html-webpack-plugin, like https://github.com/jantimon/favicons-webpack-plugin

Anyway, I think this is out of the scope of Vue CLI and should be done in user land.
