### ISSUE TITLE
 asyncWrite is not a function

### ISSUE THREAD

**Issue by zxysilent** [vuejs/vue-cli#3114]
### Version
3.2.1

### Environment info
```
C:\Users\zxysilent>node -v
v10.14.1
```

### Steps to reproduce
npm install -g @vue/cli
npm ERR! asyncWrite is not a function
npm ERR! pna.nextTick is not a function

npm ERR! A complete log of this run can be found in:

### What is expected?
安装@vue/cli

### What is actually happening?
npm ERR! asyncWrite is not a function

**Comment by sodatea** [comment]
It’s an issue with `n` https://github.com/tj/n/issues/508
