### ISSUE TITLE
can't disabled prefetch when project has multi page

### ISSUE THREAD

**Issue by martSforever** [vuejs/vue-cli#3116]
my english is not good, please forgive my english.
if you have multi page in your project which base on vue-cli3, you  might find that lazy load chunk is not work, demo code just like this(in main.js):
`function load() {
    import('demo/components/demo-icon').then(module => {
        console.log(module.default)
    })
}

setTimeout(() => {
    load()
}, 2000)`

the demo-icon.vue chunk will be requested when page is initialized, and will be requested after two seconds, we just want to request after 2 seconds.
finally i find that the reason for the first time request is a script node in head, like this:
`<link href="0.js" rel="prefetch">`
we just need to disabled prefetch,
in vue.config.js:

`chainWebpack: config => {
        config.plugins.delete('preload-index')
        config.plugins.delete('prefetch-index')
        config.plugins.delete('prefetch-portal')
        config.plugins.delete('preload-portal')
    }`

preload-* and prefetch-* is a plugin name, and the * is your page config in pages,my is:

`pages: {
        index: {
            // page 的入口
            entry: 'demo/main.js',
            ……
        },
        portal: {
            // page 的入口
            entry: 'portal/main.js',
            ……
        },
    },`

**Comment by LinusBorg** [comment]
Your issue doesn't say what your problem is, it seems you solved it yourself?

**Comment by martSforever** [comment]
yes, i just leave a solution for the people who meet the same problem

**Comment by Dragon-Rider** [comment]
@martSforever thanks for your help. Your solution works! 
@LinusBorg The guidebook doesn't explain it very well. Please consider rewriting the **Prefetch** chapter(https://cli.vuejs.org/guide/html-and-static-assets.html#prefetch).

**Comment by xiaoyouyu** [comment]
> yes, i just leave a solution for the people who meet the same problem

very well😊
