### ISSUE TITLE
vue-cli update to version 3.2.1，but the devDependencies is not deploy the newest version.

### ISSUE THREAD

**Issue by Yechuanjie** [vuejs/vue-cli#3120]
### Version
3.2.1

### Environment info
```
windows10, node8.11.4
```

### Steps to reproduce
```javascript
vue create project

vue-cli will create a package.json in 'project' folder,   

package.json:
{
  "name": "project",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.2.1",
    "@vue/cli-plugin-eslint": "^3.2.1",
    "@vue/cli-plugin-unit-jest": "^3.2.1",
    "@vue/cli-service": "^3.2.1"
  }
}
```
![错误信息](https://i.bmp.ovh/temp/1812/76c97f77da1a4a02.png)

> search packages on npm

![](https://i.bmp.ovh/temp/1812/1e6fc5549e00a9ce.png)

### problem
**@vue/cli-plugin-babel**
**@vue/cli-plugin-unit-jest**
**@vue/cli-service**

Above three devDependencie's latest version is not **3.2.1**

### What is expected?
please update the npm packages to the newest version

### What is actually happening?
can not create peoject success. must  change the version to which version exist on npm

**Comment by sodatea** [comment]
Please upgrade your global @vue/cli version. There’re breaking changes between rc releases and stable releases including the versioning strategy so the failure is expected.
