### ISSUE TITLE
Error creating new vue project

### ISSUE THREAD

**Issue by gopalvirat** [vuejs/vue-cli#3124]
### Version
3.2.1

### Reproduction link
[https://npm.runkit.com/@vue/cli-overlay](https://npm.runkit.com/@vue/cli-overlay)

### Environment info
```
System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
Binaries:
    Node: 9.10.1 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
Browsers:
    Chrome: 70.0.3538.77
    Firefox: 63.0.3
npmGlobalPackages:
    @vue/cli: 3.2.1

```

### Steps to reproduce
- Install vue-cli using  `npm install -g @vue/cli`
- Create project using `vue create hello-world`
- Proceed further with the options
- See error 
`npm ERR! Unexpected end of JSON input while parsing near '...diFuiWesJ W0VLnir6b3X'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-12-13T06_18_24_646Z-debug.log`

### What is expected?
Project created successfully

### What is actually happening?
npm ERR! Unexpected end of JSON input while parsing near '...diFuiWesJ W0VLnir6b3X'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-12-13T06_18_24_646Z-debug.log

---
The issue seems to be with @vue/cli-overlay

Tried running cli-overaly in runkit https://npm.runkit.com/@vue/cli-overlay, throwing an error.

[2018-12-13T06_21_01_142Z-debug.log](https://github.com/vuejs/vue-cli/files/2674757/2018-12-13T06_21_01_142Z-debug.log)

**Comment by gopalvirat** [comment]
Tried running other projects and same kind of error with another package, this may be related to `npm`.
used `yarn` to install the dependencies and it is working fine.

**Comment by sodatea** [comment]
Errors like `Unexpected end of JSON input while parsing…` are typically due to incomplete network responses, which means it's an `npm` issue.

**Comment by williamz6** [comment]
> Errors like `Unexpected end of JSON input while parsing…` are typically due to incomplete network responses, which means it's an `npm` issue.

so how do you solve this issue
