### ISSUE TITLE
vue-cli3.x版本初次渲染问题

### ISSUE THREAD

**Issue by baobaoqi** [vuejs/vue-cli#3128]
### Version
3.2.1

### Environment info
```
开发环境
```

### Steps to reproduce
new Vue({
  el: '#app',
  router,
  store,
  components: { App },
  template: '<App/>'
})

### What is expected?
页面正常

### What is actually happening?
控制台：You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

---
// new Vue({
//     router,
//     store,
//     render: h => h(App)
// }).$mount('#app')  这种写法没问题

**Comment by sodatea** [comment]
https://cli.vuejs.org/zh/config/#runtimecompiler
