### ISSUE TITLE
command failed: yarn

### ISSUE THREAD

**Issue by Ariunsanaa** [vuejs/vue-cli#3136]
Hi. I first installed vue cli with yarn. 
Then i tried 'vue create hello'. It gave many errors. 
Then i uninstalled yarn and tried to install vue cli with npm. 
It installed. WIth npm warn: deprecated hoek@5.03. ...etc.
Then tried again 'vue create hello2'
Now it is giving the above mentioned: Error command failed yarn. 
Now what should i do? 
Why does 'vue create hello' command still require Yarn?

**Comment by sodatea** [comment]
Please delete `~/.vuerc` and try again.

**Comment by Ariunsanaa** [comment]
Thank you for reply. I updated Node to the current version. It worked.
