### ISSUE TITLE
Unknown command info.

### ISSUE THREAD

**Issue by dousybox** [vuejs/vue-cli#3137]
### Version
3.1.0

### Environment info
```
N/A
```

### Steps to reproduce
 Run the following command in any vue-cli 3.1.0 project's folder in terminal:
 
 vue info

### What is expected?
get `Environment Info`

### What is actually happening?
```bash
Unknown command info.
```

**Comment by dousybox** [comment]
It's' fine after the update vue-cli to 3.2.1.

**Comment by ligne13** [comment]
Not working with 3.12.1
