### ISSUE TITLE
vue-cli-service lint error with none .js or .vue file in src directory

### ISSUE THREAD

**Issue by dousybox** [vuejs/vue-cli#3138]
### Version
3.2.1

### Reproduction link
[https://github.com/dousybox/vue-cli-service--lint--none-file-error](https://github.com/dousybox/vue-cli-service--lint--none-file-error)

### Environment info
```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
  Binaries:
    Node: Not Found
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-preset-app:  3.2.0
    @vue/cli-overlay:  3.2.0
    @vue/cli-plugin-babel: ^3.2.0 => 3.2.0
    @vue/cli-plugin-eslint: ^3.2.0 => 3.2.1
    @vue/cli-service: ^3.2.0 => 3.2.0
    @vue/cli-shared-utils:  3.2.0
    @vue/component-compiler-utils:  2.3.1
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    eslint-plugin-vue: ^5.0.0-0 => 5.0.0
    vue: ^2.5.17 => 2.5.21
    vue-eslint-parser:  4.0.3
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.4.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.17 => 2.5.21
    vue-template-es2015-compiler:  1.6.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. git clone https://github.com/dousybox/vue-cli-service--lint--none-file-error.git
2. cd vue-cli-service--lint--none-file-error
3. yarn install
4. yarn lint 

### What is expected?
` DONE ` No lint errors found!

### What is actually happening?
` ERROR ` Error: No files matching 'src' were found.

**Comment by LinusBorg** [comment]
Well if there's no code, there's nothing to lint - but nobody *wants* to lint an empty folder. 

So  throw an error to let you know, in case you accidentally linted the wrong directory. 

I don't see this as a bug.
