### ISSUE TITLE
vue ui generate project package.json with correct name property.

### ISSUE THREAD

**Issue by iliyaZelenko** [vuejs/vue-cli#3140]
### What problem does this feature solve?

Recently, I generated a project in the "Vue-CLI-3-test" folder, everything went fine, but the `"name": "Vue-CLI-3-test"` property seems to be wrong.

I get this warning from my IDE: "String is violating the pattern: `^(?:@[a-z0-9-~][a-z0-9-._~]*/)?[a-z0-9-~][a-z0-9-._~]*$` (This inspection checks that JSON files conform to JSON Schemas assigned to them).

### What does the proposed API look like?

Simply turn the words into lower case: `"name": "vue-cli-3-test"`. This helped me correct the warning.

**Comment by rubenmoya** [comment]
I'd love to work on this, looks like a good first issue :)
