### ISSUE TITLE
PurifyCSS Support

### ISSUE THREAD

**Issue by weihongyu12** [vuejs/vue-cli#3144]
### What problem does this feature solve?
Webpack has a plugin, PurifyCSS, which filters out unused CSS and uses it to provide significant application performance. I think if @vue/cli can support this feature, maybe it's a good idea.

[PurifyCSS](https://github.com/purifycss/purifycss)

[PurifyCSSPlugin](https://github.com/webpack-contrib/purifycss-webpack)

But my local attempt is not successful, it will remove some of my used CSS, maybe my configuration is wrong.

```javascript
// vue.config.js

// npm install glob-all purify-css purifycss-webpack -D
const path = require('path');
const glob = require('glob-all');
const PurifyCSSPlugin = require('purifycss-webpack');

module.exports = {
  configureWebpack: {
    plugins: [
      // FIXME: This code is not working properly.
      new PurifyCSSPlugin({
        paths: glob.sync([
          path.join(__dirname, './src/index.html'),
          path.join(__dirname, './**/*.vue'),
          path.join(__dirname, './src/**/*.js'),
        ]),
      }),
    ],
  },
};
```

### What does the proposed API look like?
I think it would be best if you could provide a simple API to support this feature.

```javascript
// vue.config.js

module.exports = {
  purifycss: true, // If true, then PurifyCSS is supported.
};
```

**Comment by LinusBorg** [comment]
This shuld be solved with a community plugin.

**Comment by Tofandel** [comment]
PurifyCSS is unsupported, there is a new plugin with some informations to integrate it with vue https://www.purgecss.com/guides/vue

**Comment by llyxietan** [comment]
> PurifyCSS is unsupported, there is a new plugin with some informations to integrate it with vue https://www.purgecss.com/guides/vue

thanks!
