### ISSUE TITLE
Template execution failed: ReferenceError: BASE_URL is not defined

### ISSUE THREAD

**Issue by richex-cn** [vuejs/vue-cli#3156]
### Version
3.2.1

### Reproduction link
[https://github.com/richex-cn/vue-cli-demo/commit/8be83a87cfeac1b16f3fe39ca3e570c21ac7aa27](https://github.com/richex-cn/vue-cli-demo/commit/8be83a87cfeac1b16f3fe39ca3e570c21ac7aa27)

### Environment info
```
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  Binaries:
    Node: Not Found
    Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-preset-app:  3.2.0
    @vue/cli-overlay:  3.2.0
    @vue/cli-plugin-babel: ^3.2.0 => 3.2.0
    @vue/cli-plugin-eslint: ^3.2.0 => 3.2.1
    @vue/cli-service: ^3.2.0 => 3.2.0
    @vue/cli-shared-utils:  3.2.0
    @vue/component-compiler-utils:  2.3.1
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    eslint-plugin-vue: ^5.0.0-0 => 5.0.0
    vue: ^2.5.17 => 2.5.21
    vue-eslint-parser:  4.0.3
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.4.2
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.17 => 2.5.21
    vue-template-es2015-compiler:  1.6.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Run `yarn serve` after:

```
 ERROR  Failed to compile with 2 errors                                                                         10:49:42

 error

Template execution failed: ReferenceError: BASE_URL is not defined

  ReferenceError: BASE_URL is not defined

  - index.html:4 eval
    [.]/[html-webpack-plugin]/lib/loader.js!./public/index.html:4:11

  - index.html:9 module.exports
    [.]/[html-webpack-plugin]/lib/loader.js!./public/index.html:9:3

  - index.js:284 Promise.resolve.then
    [vue_cli_demo]/[html-webpack-plugin]/index.js:284:18
```

### What is expected?
Good running.

### What is actually happening?
Couldn't run serve.

---
see this github repositories: https://github.com/richex-cn/vue-cli-demo/commit/8be83a87cfeac1b16f3fe39ca3e570c21ac7aa27

**Comment by LinusBorg** [comment]
Why are you adding HTMLWebpack Template? Vue-cli already has one in its config.

that new plugin is the reason you are seeing an error: The index.html template expects a BASE_URL variable, but your own HTMLWebpack Plugin doesn't provide that variable (our own does).

**Comment by TheMaikXX** [comment]
Hello, can I whether there is a way to add additional configuration to your html-webpack-plugin?
I just need to exclude one module/bundle from being imported as script tag in html (Im talking about service worker script)

**Comment by richex-cn** [comment]
> Hello, can I whether there is a way to add additional configuration to your html-webpack-plugin?
> I just need to exclude one module/bundle from being imported as script tag in html (Im talking about service worker script)

@TheMaikXX 
What do you mean I should do?

**Comment by TheMaikXX** [comment]
Oh sorry, I meant to ask @LinusBorg
He says that Vue has its own html-webpak-plugin implementation but I would just need to skip one script (service worker) from being injected into HTML..
So I'd like to enrich existing configuration of Vue's html-webpak-plugin and I don't know how.. (whether it is possible)

**Comment by LinusBorg** [comment]
To get alist of plugins:
```js
npm run vue-cli-service inspect --plugins
```
In the returned list you will find that there's a plugin called 
To get the config of that one plugin:
```js
npm run vue-cli-service inspect --plugin html
```

To change that plugin's config ([relevant docs](https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-plugin)):

```js
// vue.config.js
module.exports = {
  chainWebpack: config => {
    config
      .plugin('html')
      .tap(args => {
        args[0].template = '/Users/username/proj/app/templates/index.html'
        return args
      })
  }
}
```

**Comment by TheMaikXX** [comment]
Thank you @LinusBorg :)

**Comment by alex700** [comment]
@LinusBorg , I have follow error when use this solution:
```
Cannot GET /
```
This is what I can see in browser after opening the application.

**Comment by LinusBorg** [comment]
I can't help you with such a one-sentence description and zero code.

Also, this is resolved for half a year so please use the proper channels (forum.vuejs.org / chat.vuejs.org) to ask for help with configuration.

**Comment by richard-fairthorne** [comment]
Removing publicPath from vue config. Am I accidentally overriding this somehow?

**Comment by ahmadfh** [comment]
@LinusBorg How can i add multiple html plugins in **chainWebpack** ?

i am currently adding plugins like this under **chainWebpack**

```
config.plugin('control-html').use(HtmlWebpackPlugin, [{
            filename: 'control/content/index.html',
            minify: {removeComments: true, collapseWhitespace: true},
            template: path.join(__dirname, 'src/control/content/public/index.html'),
            chunks: ['control/content/content']
 }]);

config.plugin('widget-html').use(HtmlWebpackPlugin, [{
            filename: 'widget/index.html',
            minify: {removeComments: true, collapseWhitespace: true},
            template: path.join(__dirname, 'src/widget/public/index.html'),
            chunks: ['widget/widget']
}]);
```

But i understand there is another way to add them, so we can avoid having **ReferenceError: BASE_URL is not defined Error**.
