### ISSUE TITLE
polyfills make vue-router error on IE

### ISSUE THREAD

**Issue by CaiPeng1989** [vuejs/vue-cli#3158]
### Version
3.2.1

### Reproduction link
[https://github.com/CaiPeng1989/polyfills-make-vueRouter-error-on-IE](https://github.com/CaiPeng1989/polyfills-make-vueRouter-error-on-IE)

### Environment info
```
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
  Binaries:
    Node: 11.4.0
    Yarn: 1.12.3 - C:\Users\MengQing\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    @vue/babel-preset-app:  3.2.0
    @vue/cli-overlay:  3.2.0
    @vue/cli-plugin-babel: ^3.2.0 => 3.2.0
    @vue/cli-plugin-eslint: ^3.2.0 => 3.2.1
    @vue/cli-service: ^3.2.0 => 3.2.0
    @vue/cli-shared-utils:  3.2.0
    @vue/component-compiler-utils:  2.3.1
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    eslint-plugin-vue: ^5.0.0-0 => 5.0.0
    vue: ^2.5.17 => 2.5.21
    vue-eslint-parser:  4.0.3
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.4.2
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.17 => 2.5.21
    vue-template-es2015-compiler:  1.6.0
  npmGlobalPackages:
    @vue/cli: 3.2.1
```

### Steps to reproduce
`yarn`
`yarn serve`

### What is expected?
Vue-router navigates normally on IE

### What is actually happening?
Vue-router does not navigate properly on IE

[vue-router] Failed to resolve async component default: TypeError: [object Object] is not iterable!
[vue-router] uncaught error during route navigation:
[object Error]{message: "[object Obj...", name: "TypeError", stack: "TypeError: ..."}

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/issues/1642#issuecomment-399791857
https://github.com/vuejs/vue-cli/blob/be5653794a429b23f1b2200a6d9784784f77e773/packages/%40vue/babel-preset-app/index.js#L3-L11
