### ISSUE TITLE
Change implementation of vue-webcomponent-wrapper

### ISSUE THREAD

**Issue by coco1979ka** [vuejs/vue-cli#3163]
### What problem does this feature solve?
I want to change the implementation of the vue-webcomponent-wrapper, as the project seems to be inactive. To use our Vue Components as Web Components, we need e.g. support for array and object properties.
Although there is an open PR in the wrapper repository, it seems not to be merged. Maybe you can provide an additional parameter or use a configuration to switch between implementations.

### What does the proposed API look like?
-

**Comment by LinusBorg** [comment]
An idea for you to switch implementations yourself:

1. Fork the library
2. add a webpack alias to map to your own implementation:

```
"@vue/vue-webcomponent-wrapper": path.join(__dirname, "path/to/your/fork")
```

untested, but *should* work.

**Comment by coco1979ka** [comment]
In my vue.config.js I tried to do the following:
```
 configureWebpack: {
    resolve: {
      alias: {
        '@vue/vue-webcomponent-wrapper': path.join(__dirname, '../vue-web-component-wrapper'),
      },
    },
  },
```

Anyway it still uses the original implementation. Any help appreciated!

**Comment by sodatea** [comment]
It's `@vue/web-component-wrapper`, not `@vue/vue-webcomponent-wrapper`.

Also, we didn't accept that PR for a reason.
See https://developers.google.com/web/fundamentals/web-components/best-practices#aim-to-only-accept-rich-data-objects-arrays-as-properties
Using rich data as component attributes is an anti-pattern in web components.

Anyway, I don't think it worth a new first-class option in Vue CLI now that it's already doable by simply adding an alias.
