### ISSUE TITLE
vue-cli-service asks for unneeded dependencies

### ISSUE THREAD

**Issue by DarkSuniuM** [vuejs/vue-cli#3164]
### Version
3.2.1

### Reproduction link
[https://github.com/DarkSuniuM/VueCLI-UnneededDependencies](https://github.com/DarkSuniuM/VueCLI-UnneededDependencies)

### Environment info
```
  System:
    OS: Linux 4.19 Arch Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
  Binaries:
    Node: 11.5.0 - /bin/node
    Yarn: 1.12.3 - /bin/yarn
    npm: 6.5.0 - /bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 64.0
  npmPackages:
    @fortawesome/vue-fontawesome: ^0.1.3 => 0.1.3 
    @vue/babel-preset-app:  3.2.0 
    @vue/cli-overlay:  3.2.0 
    @vue/cli-plugin-babel: ^3.2.0 => 3.2.0 
    @vue/cli-plugin-eslint: ^3.2.0 => 3.2.1 
    @vue/cli-service: ^3.2.0 => 3.2.0 
    @vue/cli-shared-utils:  3.2.0 
    @vue/component-compiler-utils:  2.3.1 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    babel-plugin-transform-vue-jsx:  4.0.1 
    eslint-plugin-vue: ^5.0.0-0 => 5.0.0 
    vue: ^2.5.17 => 2.5.21 
    vue-cli-webpack:  1.0.0 
    vue-eslint-parser:  4.0.3 
    vue-hot-reload-api:  2.3.1 
    vue-loader:  15.4.2 
    vue-router: ^3.0.1 => 3.0.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.17 => 2.5.21 
    vue-template-es2015-compiler:  1.6.0 
    vuex: ^3.0.1 => 3.0.1 
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
Run the `yarn serve` or `npm run serve`

### What is expected?
Project should run since `pg-hstore` and `tedious` packages are only needed if I wanna use PostgreSQL or MSSQL

### What is actually happening?
Project fails to compile with 2 errors

These dependencies were not found:
* pg-hstore in ./node_modules/sequelize/lib/dialects/postgres/hstore.js
* tedious in ./node_modules/sequelize/lib/dialects/mssql/query.js

---
I can run database file with `nodemon` command without having any dependency problem,
Maybe a workaround would be installing both dependencies as DevDependencies, but that just won't work because `tedious` needs another package named `dns` and it is incompatible with my node version.

**Comment by sodatea** [comment]
1. Please provide a valid reproduction.
2. It seems like a problem in sequelize rather than Vue CLI: https://github.com/sequelize/sequelize/issues/7509

**Comment by DarkSuniuM** [comment]
>     1. Please provide a valid reproduction.
> 
>     2. It seems like a problem in sequelize rather than Vue CLI: [sequelize/sequelize#7509](https://github.com/sequelize/sequelize/issues/7509)

First question => What else u need? here is what I do to create the project:
1. `vue create some-project`
2. `cd some-project`
3. `yarn add sequelize sqlite3`
4. create src/database.js and put the code into it
5. import connection and TestModel from database into main.js and add `connection.sync()` to create database file
6. `yarn serve`

Second question => Then why it just gives me the error when I use `yarn serve` or `npm run serve` or `./node_modules/.bin/vue-cli-service serve`?
It works fine when I use `nodemon`, simply I did this before I use connection inside `main.js`
1. `yarn add -D babel-cli babel-preset-env babel-preset-stage-2 nodemon`
2. I added a custom command => `"db:init": "npx nodemon --exec babel-node --presets env,stage-2 ./src/database.js"`
3. when I use `npm run db -- --init` or `yarn db:init` it works pretty well and doesn't ask for dependencies

**Comment by sodatea** [comment]
1. There's no `src/database.js` or `db:init` script in the provided reproduction repo so I've no idea what code you are referring to.
2. By running `npx nodemon --exec babel-node --presets env,stage-2 ./src/database.js` you are executing the script in babel-node, while `vue-cli-service serve` runs `webpack-dev-sever` internally to serve static files used by the frontend page, it should have nothing to do with the backend sever/database, why import into `main.js`?

**Comment by DarkSuniuM** [comment]
>     1. There's no `src/database.js` or `db:init` script in the provided reproduction repo so I've no idea what code you are referring to.
> 
>     2. By running `npx nodemon --exec babel-node --presets env,stage-2 ./src/database.js` you are executing the script in babel-node, while `vue-cli-service serve` runs `webpack-dev-sever` internally to serve static files used by the frontend page, it should have nothing to do with the backend sever/database, why import into `main.js`?

Sorry for that, I forgot to commit the files I wrote 
https://github.com/DarkSuniuM/VueCLI-UnneededDependencies/blob/master/src/database.js

I found a workaround from the issue you referenced to
I created a file named `vue.config.js` in project main directory:

```
module.exports = {
  configureWebpack: config => {
    config.externals = ['pg', 'tedious', 'pg-hstore']
  }
}
```
After using this it works well
