### ISSUE TITLE
configureWebpack don't work

### ISSUE THREAD

**Issue by hezhongfeng** [vuejs/vue-cli#3169]
Version
3.2.1

Node and OS info
Node: v10.14.1, yarn: 1.12.3, Windows 10

Steps to reproduce
Change vue.config.js
```
// vue.config.js
const FilterWarningsPlugin = require('webpack-filter-warnings-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin')

module.exports = {
  assetsDir: 'static',
  productionSourceMap: false,
  configureWebpack: {
    plugins: [
      new FilterWarningsPlugin({
        exclude: /mini-css-extract-plugin/
      }),
      new CopyWebpackPlugin([{}])
    ]
  }
};
```

What is expected?
I want to use webpack-filter-warnings-plugin to filter mini-css-extract-plugin's warning.`chunk vendors [mini-css-extract-plugin] Conflicting order between:` [link](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250). I use CopyWebpackPlugin to  test(don't work too)  But I found that the configureWebpack no't work. I have tested used configureWebpack as a function.

What is actually happening?
Don't work

**Comment by LinusBorg** [comment]
> Don't work

Meaning what, exactly?
