### ISSUE TITLE
Hot-reloading does not work in Virtual machine

### ISSUE THREAD

**Issue by libragold** [vuejs/vue-cli#317]
Hi there,

Happy Chinese New year! 鸡年吉祥！

I am using vuejs for a project. We use vagrant box to set up our development environment. However, we have the following problem with hot-reloading.

After I make changes to files in the host machine, the guest machine does not seem to detect the changes if the dev server runs on the guest machine.
On the other hand, hot-reloading works just fine if I start the dev server on the host machine.
This might be a problem with the configuration, and changes need to be made .

I am also wondering if there is an "official" suggestion on development enviroment.

Thanks,

J.

**Comment by egoist** [comment]
I  can't really see any vue-cli related  stuffs here, you may search `vagrant webpack` instead.

**Comment by libragold** [comment]
If the purpose of vue-cli is to have vue working (including hot reloading) out of the box and to provide developers a smooth experience, I think this issue is relevant. Especially, if this is a problem with webpack configuration (as is suggested in your comment), then it seems that an improvement of vue-cli should be considered.

**Comment by egoist** [comment]
You can reopen this issue in relevant template repo you use.

**Comment by LinusBorg** [comment]
vuejs-templates/webpack#432

**Comment by libragold** [comment]
Thanks @LinusBorg. Modifying `devMiddleware` in `dev-server.js` works!

**Comment by Tarasovych** [comment]
Is there any solution without `webpack-dev-middleware`? Maybe some argument for `npm run serve`?

I've just created CLI "hello-world" project inside VirtualBox, trying to make hot reload work.
