### ISSUE TITLE
hot reload isnot work when a create a new project;

### ISSUE THREAD

**Issue by qiaoqiao10001** [vuejs/vue-cli#3177]
when I use vue create project ,then I change my file , the command line is reloaded; but the browser did not reload anymore;   my vue-cli version is 3.2.1  webpack in my machine is  version 4.23.1;nodejs is 10.7.1,npm is 6.1.0  ,yarn is 1.10.1;  my computer is win10

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/issues/3173#issuecomment-449573901
