### ISSUE TITLE
Problem with using target lib in nuxt

### ISSUE THREAD

**Issue by dschewchenko** [vuejs/vue-cli#3182]
### Version
3.2.0

### Environment info
```
macOS 10.14.2
node 10.14.1
vue-cli-servise 3.2.0
```

### Steps to reproduce
- build components using `vue-cli-service build --target lib ./src/index.ts` and in vue.config.js `css.extract=false`
- import builded component in nuxt page (universal mode)

### What is expected?
- all works as expected

### What is actually happening?
- error in browser http://joxi.ru/LmGap0bCwwRW0A

---
I have private repository with vue components. And cannot provide source code
It is simple SFC with template(html), script(lang=ts) and style(lang-scss)

**Comment by LinusBorg** [comment]
You're accessing `document`, which is not available during SSR. 

This is not a problem with vue-cli - you just have to write  our component in a way that works with SSR. 

since you can't share source, i can't tell you how to do that either.

**Comment by LinusBorg** [comment]
Well, you can always wrap your component in a `<no-ssr>` component: 

https://nuxtjs.org/api/components-no-ssr

Or you fix your component's business logic/implementation to only access `document` when it actually exists.

**Comment by dschewchenko** [comment]
It's added by `vue-cli-service build --target`
I don't extract css, for minimal project build, when I don't use all components.
I have repo with minimal build https://github.com/dschewchenko/vue-components

**Comment by dschewchenko** [comment]
Maybe I may to have 2 bulid targets. One for node([vue-style-loader](https://github.com/vuejs/vue-style-loader#server-side-rendering-support)) and second for browser. And how I can do it with vue-cli?

**Comment by sodatea** [comment]
It's as easy as
```
// vue.config.js
module.exports = {
  configureWebpack: {
    target: 'node'
  }
}
```

**Comment by dschewchenko** [comment]
@sodatea I know that it's easy. But I don't know to make 2 different builds using vue-cli

**Comment by sodatea** [comment]
1. use an environment variable and run the command twice
2. use this plugin: https://github.com/jkzing/vue-cli-plugin-multi-compiler/

**Comment by wargt** [comment]
@dschewchenko Please нelp me solve this problem! I'm very upset

**Comment by Hulkmaster** [comment]
up?
