### ISSUE TITLE
vue cli  升级后 老项目的package.json 能自动升级

### ISSUE THREAD

**Issue by nailfar** [vuejs/vue-cli#3187]
### What problem does this feature solve?
vue  update self    更新vue cli 本身
vue  update project   更新项目里的package.josn 依赖 并安装

### What does the proposed API look like?
vue  update self    更新vue cli 本身
vue  update project   更新项目里的package.josn 依赖 并安装

**Comment by sodatea** [comment]
有个目前还没公开的命令 `vue upgrade` 就是用来升级项目的。等我们把想做的功能完善后会写相关文档说明的。
