### ISSUE TITLE
想在  devserver  里 装一个 websocket 服务  需要webpack 的配置 该如何操作

### ISSUE THREAD

**Issue by nailfar** [vuejs/vue-cli#3188]
### What problem does this feature solve?
 本地测试的时候启动一个带 自己定义的websocket 服务的 devserver  ,  需要用到webpack 的配置 。本地测试的时候 希望 my-dev-socket-server.js 可以 引入wepack 的配置 并启动本地服务，在正式环境的时候  我希望my-dev-socket-server.js 可以不加wepack 配置 直接在正式环境里启动一个node 服务 。   该如何操作；
是否提供导出一个 webpack.dev.js 的配置的文件 ；cli-3 里失去了很多灵活性 ，在设计上希望提供更多的灵活性 ，可定制。

### What does the proposed API look like?
vue  generate   ./build     
在build 目录里 创建一个跟 vuecli2 里生成的构建脚本一样 
build.js 
check-versions.js
utils.js
vue-loader.conf.js
webpack.dev.conf.js
webpack.prod.conf.js
...
这样可以极大的增强灵活性和可定制化

**Comment by sodatea** [comment]
1. 针对 webpack-dev-server 的自定义配置，可以写个插件，调用 [configureDevServer](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/PluginAPI.js#L104)
2. 如果确实有需要，我们有暴露 webpack.config.js，位置在 [`@vue/cli-service/webpack.config.js`](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/webpack.config.js)
