### ISSUE TITLE
Using vue-cli with a custom registry or behind proxy.

### ISSUE THREAD

**Issue by leogouveia** [vuejs/vue-cli#3193]
### What problem does this feature solve?
Hi, 

I am trying to use vue-cli in my company, but i just discovered it make a request to internet in the file @vue/cli/lib/util/getPackageVersion.js.
I'm behind a proxy and we use Nexus OSS as registry to use NPM.
Is it possible to get the registry configured in my .npmrc?

### What does the proposed API look like?
const { request } = require("@vue/cli-shared-utils");
const fs = require("fs");
const join = require("path").join;

module.exports = async function getPackageVersion(id, range = "") {

  const registry = (await require("./shouldUseTaobao")())
    ? `https://registry.npm.taobao.org`
    : (await getRegistry());

  let result;
  try {
    result = await request.get(
      `${registry}/${encodeURIComponent(id).replace(/^%40/, "@")}/${range}`
    );
  } catch (e) {
    return e;
  }
  return result;
};

async function getRegistry() {
  const execa = require("execa");
  const registry = (await execa("npm", ["config", "get", "registry"])).stdout;
  return registry || `https://registry.npmjs.org`;
}

**Comment by LinusBorg** [comment]
`vue create -r`

There's already an option for this, see the docs or run `vue create --help`

**Comment by sodatea** [comment]
In v4 the logic has been fixed, now it is:

1. if the `useTaobaoRegistry` config is `true`, then use the taobao registry (in case novice users in China haven't manually set the registry before).
2. then fall back to the result of `npm config get registry` (which can be set in `~/.npmrc`) (or `yarn config get registry`, or `pnpm`, depending on user's default package manager).

So I think this issue could be considered fixed.
