### ISSUE TITLE
Relative path can't set in vue cli 2.5 

### ISSUE THREAD

**Issue by shahzaibanwar009** [vuejs/vue-cli#3197]
### Version
3.0.5

### Reproduction link
[https://github.com/vuejs/vue-cli/issues/3196](https://github.com/vuejs/vue-cli/issues/3196)

### Node and OS info
npm

### Steps to reproduce
when i setting
module.exports = {
configureWebpack: {
baseUrl: './'
}
}
or publicPath is show unknown property of configration please help he i wanna set the url of assets /root/fodd/user/

### What is expected?
when i setting
module.exports = {
configureWebpack: {
baseUrl: './'
}
}
or publicPath is show unknown property of configration please help he i wanna set the url of assets /root/fodd/user/

### What is actually happening?
when i setting
module.exports = {
configureWebpack: {
baseUrl: './'
}
}
or publicPath is show unknown property of configration please help he i wanna set the url of assets /root/fodd/user/

**Comment by sodatea** [comment]
baseUrl is a root level option.

```
module.exports = {
  baseUrl: './'
}
```

**Comment by shahzaibanwar009** [comment]
not working

**Comment by sodatea** [comment]
Now idea what you mean by "not working". Please provide an actual reproduction.
