### ISSUE TITLE
Module build failed: ReferenceError: Promise is not defined at LazyResult.async

### ISSUE THREAD

**Issue by andersonfelix** [vuejs/vue-cli#32]
First run on terminal: `npm install es6-promise --save-dev`
Edit /buid/webpack.base.conf.js adding `require('es6-promise').polyfill();`

Solution from [here](https://github.com/postcss/postcss-nested/issues/30#issuecomment-136026135)

**Comment by yyx990803** [comment]
Or upgrade to Node 0.12+...
