### ISSUE TITLE
Add option to turn off auto-fix in eslint

### ISSUE THREAD

**Issue by justin-lau** [vuejs/vue-cli#3204]
### What problem does this feature solve?
Autofix is turned on by default, which is cool. However, there are always people (such as myself) who would prefer opting out.

Besides using `vue-cli-service lint --no-fix`, currently there is no easy way to do so. And if I use a npm script to do this, when I actually want to use `--fix` the interpreted command would become `vue-cli-service --no-fix --fix`... It works, but not pretty.

### What does the proposed API look like?
Like `lintOnSave`, I suggest adding an option (e.g. `lintAutofix`) for easy opt-out.

**Comment by yyx990803** [comment]
I don't think this is worth if appending `--fix` already works.

**Comment by NeonWizard** [comment]
Sorry to necropost, but I completely agree with Justin. ESLint default behavior is to lint without fixing, and you include the `--fix` flag when you want to fix. It makes no sense that this behavior is backwards for `vue-cli-service`.

**Comment by dland512** [comment]
Modifying people's code should not be the default behavior.

**Comment by TDola** [comment]
I was struggling with this too.  Why adding --fix was causing it to *not* fix changes.  But not adding --fix caused it to fix things.  This is really bizarre behavior.
