### ISSUE TITLE
modern mode doesn't work when parallel be false

### ISSUE THREAD

**Issue by lili21** [vuejs/vue-cli#3208]
### Version
3.2.1

### Reproduction link
[https://github.com/lili21/vue-cli-issue](https://github.com/lili21/vue-cli-issue)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 8.11.1 - /usr/local/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: Not Found
    Safari: 12.0
  npmGlobalPackages:
    @vue/cli: 3.2.1
```

### Steps to reproduce
- yarn
- yarn build --modern

### What is expected?
should generate two versions bundle, one for modern, and other for legacy.

### What is actually happening?
only the legacy bundle be generated. 

---
I think the problem is babel-loader using the cached `babel.config.js`. when building the  modern version, it still use the legacy babel config, so the output bundle is same as legacy bundle.

![image](https://user-images.githubusercontent.com/4456380/50508714-f78fbd80-0abd-11e9-8ebd-5adc169beba1.png)
the hash is same.

**Comment by sodatea** [comment]
Thank you for your reporting! I should have seen this earlier…
Anyway, it was fixed in https://github.com/vuejs/vue-cli/pull/3477
