### ISSUE TITLE
vue-cli 3.0生成的template元素比2.0的少一个空格

### ISSUE THREAD

**Issue by GitHdu** [vuejs/vue-cli#3209]
### Version
3.2.1

### Environment info
```
System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  Binaries:
    Node: 10.14.1 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: Not Found
    Safari: 12.0.2
  npmGlobalPackages:
    @vue/cli: 3.2.1
```

### Steps to reproduce
1 分别用vue-cli2和3新建工程
2 在template中写两个button
```
<template>
  <div>
    <button data-v-9fa485f6="">a</button>
    <button data-v-9fa485f6="">b</button>
  </div>
</template>
```
3. 控制台检查元素

### What is expected?
<button data-v-9fa485f6="">a</button> <button data-v-9fa485f6="">b</button>
两个button之间有个空格

### What is actually happening?
<button data-v-9fa485f6="">a</button><button data-v-9fa485f6="">b</button>

---
有没有空格可能影响display：inline-block元素的样式

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/issues/1020#issuecomment-412338405
