### ISSUE TITLE
Allow `vue.config.js` to export a function

### ISSUE THREAD

**Issue by jkzing** [vuejs/vue-cli#3213]
### What problem does this feature solve?
Currently `vue.config.js` only allowed to export an object containing options.

When user want to have more complicated configuration, they have to do:

```js
const baseConfig = {
  // basic configurations
}

if (something) {
  module.exports = {
    ...baseConfig,
    // specific configurations
    baseUrl: '/foo/'
  }
} else {
  module.exports = {
    ...baseConfig,
    // specific configurations
    baseUrl: '/bar/'
  }
}
```

Moreover, we have received several issues asking about how to build with different configurations. (Like this one: https://github.com/vuejs/vue-cli/issues/2861) Although this can be done with current api, I thinks it's not intutive enough so that people with limited nodejs knowledge couldn't figure it out.

### What does the proposed API look like?
Like [what `babel.config.js` did](https://babeljs.io/docs/en/config-files#root-babelconfigjs-files), let user use function to generate configuration:

```js
module.exports = function () {
  const baseConfig = {
    // basic configurations
  }
  if (something) {
    return {
      ...baseConfig,
      // specific configurations
      baseUrl: '/foo/'
    }
  } else {
    return {
      ...baseConfig,
      // specific configurations
      baseUrl: '/foo/'
    }
  }
}
```

Further more, we can pass some useful information/api as arguments into the configuration function, for example:

```js
module.exports = function (options, api) {
  const {
    args, // command line arguments parsed with cli
    env // project default ENV
    // any other ones ?
  } = options

  // like chainWebpack and configureWebpack inside PluginAPI
  api.chainWebpack(fn)
  api.configureWebpack(config)

  // this could solve the problem met in:
  // https://github.com/vuejs/vue-cli/issues/2506
  // https://github.com/vuejs/vue-cli/pull/3135
  api.loadEnvDir(pathToDir)
  api.loadEnvFile(pathToFile)
  // then user can use ENV variables below
}
```

**Comment by sodatea** [comment]
While I appreciate this idea very much, I think the API should be minimal as compared to the proposed ones in the OP.

We already have a [project local plugin mechanism](https://cli.vuejs.org/guide/plugins-and-presets.html#project-local-plugin), so it seems redundant to replicate this logic in the config file.
Also, `vue.config.js` is a higher abstraction layer over webpack, we should distinguish it from plain webpack config IMHO.
As for the `loadEnv*` API, it's against out guideline as stated by Evan: https://github.com/vuejs/vue-cli/issues/2506#issuecomment-457960976

So I think we can divide this proposal into 2 PRs: one for support of functional export, one for the minimal API interface (yet to be designed and discussed).

**Comment by jkzing** [comment]
@sodatea , nice to see progress on this FR, support for functional export would be a good start!
