### ISSUE TITLE
vue-cli-service serve error no error message

### ISSUE THREAD

**Issue by qinkaiyuan** [vuejs/vue-cli#3219]
### Version
3.2.2

### Reproduction link
[https://github.com/qinkaiyuan/vue-cli-issues-no-error-info](https://github.com/qinkaiyuan/vue-cli-issues-no-error-info)

### Environment info
```
mac webstorm

bogon:limpid_front qinky$ vue --version
3.2.2
bogon:limpid_front qinky$ node -v
v8.11.1
bogon:limpid_front qinky$ node info
module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/qinky/WebstormProjects/limpid_front/info'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
bogon:limpid_front qinky$ 

```

### Steps to reproduce
clone,
npm install,
npm run serve

### What is expected?
serve success

### What is actually happening?
serve error
> qingchi@0.1.0 serve /Users/qinky/WebstormProjects/vue-cli-issues-no-error-info
> vue-cli-service serve

 INFO  Starting development server...
 94% after seal                                                                           

 ERROR  Failed to compile with 4 errors   

---
this program run success in win10

run error  in mac

run this program before i new add one plugins -> sass-resources-loader

**Comment by sodatea** [comment]
See https://github.com/geowarin/friendly-errors-webpack-plugin/issues/79
After applying this fix: https://github.com/geowarin/friendly-errors-webpack-plugin/commit/84eee7d8800f620478767012c1fc40fffc411410
The actual error is:

```
* @/assets/img in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"e20d7bae-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/chat/index.vue?vue&type=template&id=71064116&scoped=true&, ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"e20d7bae-vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/match/index.vue?vue&type=template&id=54ebbbde&scoped=true& and 2 others
```

Since this is an upstream issue and we have already got a similar issue report at https://github.com/vuejs/vue-cli/issues/2244 I'll close this one.

**Comment by qinkaiyuan** [comment]
how i can solve this problem?Now my project cannot run on mac

**Comment by sodatea** [comment]
@qinkaiyuan
The error message is clear. Search for `@/assets/img` in your project and replace them with a valid path.
