### ISSUE TITLE
pages 能否加个key   比如commonJS

### ISSUE THREAD

**Issue by AlanSean** [vuejs/vue-cli#3221]
### What problem does this feature solve?
最近在做，node服务端渲染。
开发环境用的cli3 node express

在开发环境中的热更新 
需要在js中require('webpack-hot-middleware/client')
或
```
let service = process.VUE_CLI_SERVICE

if (!service || process.env.VUE_CLI_API_MODE) {
  const Service = require('@vue/cli-service/lib/Service')
  service = new Service(process.env.VUE_CLI_CONTEXT || process.cwd())
  service.init(process.env.VUE_CLI_MODE || process.env.NODE_ENV)
}
#var config =  require(''@vue/cli-service/webpack.config.js') 
# webpack(config ) 会进行报错    大概是因为 没有带 serve 命令把。
#所以使用了以下的方法
config = service.resolveChainableWebpackConfig();
finalConfig = config.toConfig();

for(var item in finalConfig.entry){
    finalConfig.entry[item].unshift(resolve(`${__dirname}/node_modules/webpack-hot-middleware/client?name=${item}`));
}

````

以上的两个方法，我觉得过于拘束，因为以后将不仅仅于`webpack-hot-middleware` 甚至还会更多。
虽然可以做cli-template 但是我依然觉得很麻烦，维护方面也很不利。

webpack本身是这么支持的。
我接触cli3时间也不是很长，但是我查阅了文档很久没有发现这个功能。
所以我希望有这样的一个扩展。

### What does the proposed API look like?
emmmmmm  木有

**Comment by sodatea** [comment]
抱歉，你的 issue 描述不是太清晰，我可能没有 100% 理解你的需求。
首先，如果我没理解错的话的，这个 feature request 应该是一个 [X-Y Problem](https://coolshell.cn/articles/10804.html)？
真正问题是服务端渲染中的热重载，而不是 pages 的配置？
如果只是为了这个的话，并不需要 Vue CLI 增加 API，参考 https://github.com/eddyerburgh/vue-cli-ssr-example 这个项目即可。

**Comment by AlanSean** [comment]
抱歉，我表达的的确不太明确。
我做的是多页面，然后每个页面都需要引入一个公共的库。


我真正需要的是所有页面，都要引入某个js 比如某个JSDK和一些早已封装好的方法。
我可以把JSDK 和这些方法， 提取成单独一个文件。
用CDN的方式使用 或者 做成cli-template.

上面只是需求场景。
而且这种做法，以后的维护很不便利。

类似于这种功能。虽然用webpack本身的方法也可以做，但是我就是想用cli嘛

下面是局部webpack配置。
```
const devMode = process.env.NODE_ENV !== 'production';
const entrys = {};
const htmlConfs = [];
glob.sync('./activity_src/pages/**/index.js').forEach(path => {
    const chunk = path.split('./activity_src/pages/')[1].split('.js')[0];
    const htmlConf = {
        filename: chunk+'.html',
        template: 'public/index.html',
        chunks: ["common", chunk],
        inject: 'body',
    }
    if(path.indexOf('lib') == -1 || devMode){
        entrys[chunk] = ['./install.js',path];
        htmlConfs.push(new HtmlWebpackPlugin(htmlConf))
    }
});

const config = {
    entry: entrys,
   plugins:[ ...htmlConfs ]
```

不知道我是否表达的足够清楚。如果还是不够清楚。那么我沉淀沉淀再来。

**Comment by sodatea** [comment]
这个配置 webpack 就可以吧
1. pages 里面是可以放额外的 html-webpack-plugin 相关的配置的
https://github.com/vuejs/vue-cli/blob/0ac5169795cb4297c9104227e12ea5e806b2ac3b/packages/%40vue/cli-service/lib/config/app.js#L192-L199
2. 你这个场景好像更适合做成插件？https://github.com/jharris4/html-webpack-include-assets-plugin 这个不知道够不够用

**Comment by AlanSean** [comment]
emmmm 我所提的问题与  html-webpack-plugin 基本无关。

```
webpack的多页面配置,我就直接展开的形式来做了

    entry:{
        index:['install.js','src/pages/home/index.js'']，
        ...
   },
  plugins:[
    new HtmlWebpackPlugin({
        filename: index.html,
        template: 'pulic/index.html',
        chunks: ["common", index],
        inject: 'body',
    })
],
  optimization:{
        splitChunks:{
            cacheGroups:{
                common:{
                    minChunks: 多少chunk写多少,
                    name: 'common',
                    chunks: "initial",
                }
            }
        }
    }


重点在entry,我可以写多个依赖,  来一起编译
但是好像cli3没有这个功能

我在pages entry中写多个依赖 会报错
Invalid options in vue.config.js: child "pages" fails because [child "home" fails because [child "entry" fails because ["entry" must be a string]]]
```

**Comment by sodatea** [comment]
有道理，应该在 page 里支持更多形式的 entry 格式。

就现在来说，pages 里的 entry 就是往 webpack config 里塞了一个同名 entry，用 chainWebpack 也可以很方便地操作
https://github.com/vuejs/vue-cli/blob/4070507de64bee83c8e019e96c336068e3e950b9/packages/%40vue/cli-service/lib/config/app.js#L202

```js
// vue.config.js
const pages = {
  index: './src/main.js'
}
module.exports = {
  pages,
  chainWebpack: config => {
    Object.keys(pages).forEach(name => config.entry(name).add('./install.js'))
  }
}
```
