### ISSUE TITLE
npm High severity vulnerability from webpack-dev-server

### ISSUE THREAD

**Issue by Sceat** [vuejs/vue-cli#3223]
### Version
3.2.2

### Environment info
```
Unknown command info. ¯\_(ツ)_/¯
```

### Steps to reproduce
`npm update`

### What is expected?
to run without problems

### What is actually happening?
![](https://i.imgur.com/1GDJwrh.png)

**Comment by larkin-nz** [comment]
Also having this issue too - installing or updating any npm package will produce this error.

**Comment by larkin-nz** [comment]
For more details on the issue see:
https://github.com/webpack/webpack-dev-server/issues/1604
https://github.com/webpack/webpack-dev-server/issues/1615

The issue is related to some changes required to be done in sockjs (see https://github.com/sockjs/sockjs-node/pull/247)

For a temporary workaround put this in your 'devServer' property in webpack.config.js (or your webpack config file)

`disableHostCheck: true`

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/blob/0fc972ed1a9929e7b4bb6daa251e3a610f92d215/packages/%40vue/cli-service/package.json#L71

Already fixed.

**Comment by larkin-nz** [comment]
> See
> 
> [vue-cli/packages/@vue/cli-service/package.json](https://github.com/vuejs/vue-cli/blob/0fc972ed1a9929e7b4bb6daa251e3a610f92d215/packages/%40vue/cli-service/package.json#L71)
> 
> Line 71 in [0fc972e](/vuejs/vue-cli/commit/0fc972ed1a9929e7b4bb6daa251e3a610f92d215)
> 
>  "webpack-dev-server": "^3.1.14", 
> Already fixed.

Yes, I noticed this earlier, but there seems to still be a bug occurring for some users of this package (see https://github.com/webpack/webpack-dev-server/issues/1604)

I have also checked my local package and it is 3.1.14, so maybe this is a problem with NPM's audit tool rather?

**Comment by usercao** [comment]
> vue-cli/packages/@vue/cli-service/package.json

## Overview
```txt
Versions of webpack-dev-server before 3.1.6 are missing origin validation on the websocket server. This vulnerability allows a remote attacker to steal a developer's source code because the origin of requests to the websocket server that is used for Hot Module Replacement (HMR) are not validated.
```

## Remediation
```txt
Update to version 3.1.6 or later.
```

**Comment by usercao** [comment]
@iainbeeston when I install @vue/cli@3.2.2,I saw the Remediation in this link [https://www.npmjs.com/advisories/725](https://www.npmjs.com/advisories/725),until the version of 3.1.14,this bug  still persist,I don't know what happend.

**Comment by iainbeeston** [comment]
Thanks @usercao that's interesting... The same page also lists 3.1.14 as affected on the "Versions" tab, even though the advisory from npm audit says 3.1.14 is fixed.

<img width="273" alt="screenshot 2019-01-02 at 09 35 13" src="https://user-images.githubusercontent.com/111963/50586538-ba3a7f80-0e71-11e9-856c-2aa264d2f005.png">
