### ISSUE TITLE
打包后的静态文件需要上传到CDN，如何设置静态文件域名？

### ISSUE THREAD

**Issue by jiankafei** [vuejs/vue-cli#3234]
### What problem does this feature solve?
静态文件需要上传到CDN，所以需要设置静态文件域名，但目前不被允许

### What does the proposed API look like?
目前的cli不允许设置 output > publicPath 应该提供一种方式来支持这种需求

**Comment by jiankafei** [comment]
比较急，希望大佬快看看，帮忙解决

**Comment by longshihui** [comment]
这个插件能帮到你吗vue-cli-plugin-publicpath ?

**Comment by jkzing** [comment]
See https://cli.vuejs.org/config/#baseurl

**Comment by jiankafei** [comment]
现在遇到一个问题：
使用 cdn 地址作为 baseUrl， 但router里也有 base 的使用，导致 router 里的base 是 cdn 地址，这个怎么解决？

**Comment by jiankafei** [comment]
vue.config.js, router 都是使用 process.env.BASE_URL 变量

**Comment by libin1991** [comment]
```
module.exports = {
	baseUrl: process.env.NODE_ENV === "production" ? '//cdn.sinajs.cn/haha/' : '/',
	productionSourceMap: false, 
	devServer: {
		open: process.platform === 'darwin',
		host: '',
		port: 8089,
		// https: false,
		hotOnly: false,
		disableHostCheck: true,
		before: app => {},
	},
	configureWebpack: {
		resolve: {
			alias: {
				vue$: 'vue/dist/vue.runtime.esm.js'
			}
		}
	}
}

 
```
可以看看这个

**Comment by jiankafei** [comment]
vue-cli 会根据 baseUrl 设置 process.env.BASE_URL 而我的路由也使用到了 process.env.BASE_URL，所以不能使用上面的配置，我使用 process.env.BASE_PATH避开这个问题，文档里说的使用 VUE_APP_XX  这种形式，在我看来并不可取，因为有的环境变量是客户端代码和服务端代码都要使用的，而服务端代码使用带有特殊前缀的环境变量总是看不过去的，所以只能按照我现有的方式了。

**Comment by TimRChen** [comment]
```
你可以在 vue.config.js 文件中计算环境变量。
它们仍然需要以 VUE_APP_ 前缀开头。
这可以用于版本信息 process.env.VUE_APP_VERSION = require('./package.json').version。
```
[点击查看文档](https://cli.vuejs.org/zh/guide/mode-and-env.html#%E5%9C%A8%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BE%A7%E4%BB%A3%E7%A0%81%E4%B8%AD%E4%BD%BF%E7%94%A8%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F)
