### ISSUE TITLE
some axios request CORS not working

### ISSUE THREAD

**Issue by shahzaibanwar009** [vuejs/vue-cli#3235]
### Version
3.0.4

### Reproduction link
[https://github.com/vuejs/vue/issues/9274](https://github.com/vuejs/vue/issues/9274)

### Node and OS info
npm

### Steps to reproduce
some axios request CORS not working

### What is expected?
some axios request CORS not working

### What is actually happening?
some axios request CORS not working

**Comment by LinusBorg** [comment]
This is a usage problem, not a bug. 

Go yo forum.vuejs.org and *explain* your problem there
