### ISSUE TITLE
Add documentation for test:unit

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/vue-cli#3237]
### What problem does this feature solve?
CLI3 creates `"test:unit": "vue-cli-service test:unit",` but there is no documentation on:

* https://cli.vuejs.org/guide/cli-service.html

to explain what that is doing behind the scenes.

### What does the proposed API look like?
Add docs

**Comment by LinusBorg** [comment]
To chose either "jest" or "mocha-webpack" as your unit test setup. 

Both plugins have documentation on the form if READMEs on github, linked from the the official docs here: 

https://cli.vuejs.org/config/#unit-testing

Or right from the "plugins" menu in the top navigation. 

You can also, as with all other commands, use `--help` to get info in the command line.

**Comment by TheJaredWilcurt** [comment]
I assumed that this was documented somewhere else, my point was that there is no link to it in the obvious place to look for it in the documentation.
