### ISSUE TITLE
vue ui not working

### ISSUE THREAD

**Issue by leerlemoniii** [vuejs/vue-cli#3239]
### Version
3.2.2

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.9.4 - C:\Program Files (x86)\Nodist\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
install vue cli as described https://cli.vuejs.org/guide/installation.html
try to run vue ui
server starts fine
browser window is empty
2 errors in dev tools
﻿
chunk-vendors.7c4987ce.js:1 Uncaught SyntaxError: Unexpected token <
app.66d7957d.js:1 Uncaught SyntaxError: Unexpected token <

### What is expected?
should start the vue ui with the expected screen for setting up projects etc.

### What is actually happening?
NOTHING!
server starts fine
browser window is empty
2 errors in dev tools
﻿
chunk-vendors.7c4987ce.js:1 Uncaught SyntaxError: Unexpected token <
app.66d7957d.js:1 Uncaught SyntaxError: Unexpected token <

**Comment by Akryum** [comment]
Clear your browser cache.

**Comment by navicstein** [comment]
`Ctrl` + `Shift` + `r` [ hard reload ] solved this for me
