### ISSUE TITLE
`build --prod --serve` for serving the compiled dist folder in production

### ISSUE THREAD

**Issue by xpepermint** [vuejs/vue-cli#324]
I would love to see this tool offering some sort of `serve compiled static site` feature.  

Currently running the `vue build ./src/index.js` command start a development server. It would be great if you could add `--prod --serve` option or similar, which would build your application into the `dist` folder and then start a production server (like the [serve](https://www.npmjs.com/package/serve) package does).

**Comment by egoist** [comment]
why not just use serve then?

**Comment by xpepermint** [comment]
Well I use it, yes, but because this tool is getting awesome with your `build` feature I hope we'll get a all-in-one package one day ;).

**Comment by egoist** [comment]
no, I think we should keep vue-cli as small as possible. It's not a good idea to maintain an unneccessary feature which is well maintained by a 3rd-party library.
