### ISSUE TITLE
vue-cli3 scoped priority

### ISSUE THREAD

**Issue by matisha001** [vuejs/vue-cli#3247]
### Version
3.2.1

### Reproduction link
[https://matisha001.gitee.io/demo/vue-cli3/](https://matisha001.gitee.io/demo/vue-cli3/)

### Environment info
```
production
```

### Steps to reproduce
<template>
  <div id="app">
    <img src="./assets/logo.png">
    <HelloWorld class="test"/>
  </div>
</template>

### What is expected?
https://matisha001.gitee.io/demo/vue-cli2/

### What is actually happening?
https://matisha001.gitee.io/demo/vue-cli3/

---
Add "scoped" attribute to limit CSS to this component only in vue-cli2 ,but it doesn't work in vue-cli3.

**Comment by LinusBorg** [comment]
Please share the spice encode for these two demos.

**Comment by matisha001** [comment]
> Please share the source code for these two demos.
> 
> If I had to guess, the change maybe comes from two different versions of vue-loader( 14 vs. 15), which had a change that could affect the order of CSS in some cases.
> 
> But I can't really tell without code.

![image](https://user-images.githubusercontent.com/19816700/50681588-0f7bba00-1047-11e9-81d3-13617bd997e3.png)
![image](https://user-images.githubusercontent.com/19816700/50681626-2fab7900-1047-11e9-801e-6e94a7701c1f.png)
![image](https://user-images.githubusercontent.com/19816700/50681637-36d28700-1047-11e9-9f68-8c3e49752c4f.png)

**Comment by LinusBorg** [comment]
not a screenshots (which I can't edit) of one component. The source code of those two demo repositories.

**Comment by LinusBorg** [comment]
But I'll improve my guess:

This is indeed about CSS inject order of vue-loader 15. The new behaviour is correct and desirable beause it gives the parent the ability to override styles of the child. the behaviour in vue-cli 2 comes from vue-loader ~11-14 and was undesirable.

Please also note this Tip from the docs:

> With `scoped`, the parent component's styles will not leak into child components. However, a child component's root node will be affected by both the parent's scoped CSS and the child's scoped CSS. This is by design so that the parent can style the child root element for layout purposes.

https://vue-loader.vuejs.org/guide/scoped-css.html#child-component-root-elements

It's been discussed at length in the vue-loader repository in a bunch of issues. Yes, this means scoped styles are not fully isolated when talking about root nodes, but it was a deisgn choice to allow that.

For better isolation, use CSS modules.
