### ISSUE TITLE
prettier version mismatch

### ISSUE THREAD

**Issue by zhuscat** [vuejs/vue-cli#3249]
### Version
3.2.3

### Environment info
```

Environment Info:

  System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.5.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 62.0.3
    Safari: 12.0
  npmPackages:
    @vue/babel-preset-app:  3.2.2 
    @vue/cli-overlay:  3.2.0 
    @vue/cli-plugin-babel: ^3.2.0 => 3.2.2 
    @vue/cli-plugin-eslint: ^3.2.0 => 3.2.2 
    @vue/cli-service: ^3.2.0 => 3.2.3 
    @vue/cli-shared-utils:  3.2.2 
    @vue/component-compiler-utils:  2.4.0 
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    babel-plugin-transform-vue-jsx:  4.0.1 
    eslint-plugin-vue: ^5.0.0 => 5.1.0 
    vue: ^2.5.21 => 2.5.21 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.1 
    vue-loader:  15.4.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.5.21 
    vue-template-es2015-compiler:  1.6.0 
  npmGlobalPackages:
    @vue/cli: 3.2.3


```

### Steps to reproduce
```bash
vue create my-project

# select `Manually select features`
# select `Babel and Linter / Formatter`
# select `ESLint   Prettier`
# select `Lint on save`
# select `In dedicated config files`

cd my-project

less package-lock.json
```

### What is expected?
Version of Prettier at `my-project/node_modules/`  should be greater than 1.15.(The 1.15 version is inside `my-project/node_modules/@vue/eslint-config-prettier/node_modules`.

`eslint-plugin-prettier` turns off all rules about vue template, this means we should format vue template using Prettier?

So I wrote an npm script:

```bash
prettier --write src/**/*.{js,json,css,vue}
```

However, Prettier 1.13 does not support format vue template.

### What is actually happening?
Version of Prettier at `my-project/node_modules/` is 1.13

**Comment by LinusBorg** [comment]
the eslint plugin add @vue/eslit-config-prettier when you choose the prettier option, and that config has `prettier@^1.15.3` as a dependency, os without looking your actual project I don'T see any reason for this.

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/eslint-config-prettier/package.json#L26

**Comment by zhuscat** [comment]
`@vue/component-compiler-utils@2.4.0` requires `prettier@1.13.7`

I used `npm` to install packages so `yarn why`didn't work.(npm version is 6.5.0)

Then I tried installing packages using `yarn`. But this time `prettier@1.15.3` was in `my-project/node_modules`，and `prettier@1.13.7` was in `my-project/node_modules/@vue/component-compiler-utils/node_modules`.

And here is the repo:

https://github.com/zhuscat/vue-cli-prettier-minimum-reproduction/tree/master

```bash
git clone git@github.com:zhuscat/vue-cli-prettier-minimum-reproduction.git
```

**Comment by sodatea** [comment]
If you want to use `prettier` in your npm scripts, you need to add it to the project's direct (dev)dependencies.

**Comment by sodatea** [comment]
For now we added `prettier` to `@vue/eslint-config-prettier` to avoid `eslint-plugin-prettier`'s peer dep warning and it now seems misleading.
Maybe we should make it a peer dep and add it to the root `package.json` during project generation.

**Comment by dflock** [comment]
```console
$ prettier --version

1.13.7

$ yarn why prettier

yarn why v1.12.3
[1/4] Why do we have the module "prettier"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "prettier@1.15.3"
info Reasons this module exists
   - "@vue#eslint-config-prettier" depends on it
   - Hoisted from "@vue#eslint-config-prettier#prettier"
info Disk size without dependencies: "8.65MB"
info Disk size with unique dependencies: "8.65MB"
info Disk size with transitive dependencies: "8.65MB"
info Number of shared dependencies: 0
=> Found "@vue/component-compiler-utils#prettier@1.13.7"
info This module exists because "@vue#cli-service#vue-loader#@vue#component-compiler-utils" depends on it.
info Disk size without dependencies: "7.89MB"
info Disk size with unique dependencies: "7.89MB"
info Disk size with transitive dependencies: "7.89MB"
info Number of shared dependencies: 0
Done in 0.55s.

$ yarn add prettier --dev

...

$ prettier --version
1.15.3
```

**Comment by sodatea** [comment]
Already fixed in recent versions of `@vue/component-compiler-utils`
