### ISSUE TITLE
How to change output filename for the extracted CSS?

### ISSUE THREAD

**Issue by tadejstanic** [vuejs/vue-cli#325]
I found that current `vue-build` in production mode offers fixed filename for the extracted CSS which is taken from the entry path:

In [https://github.com/vuejs/vue-cli/blob/master/bin/vue-build](https://github.com/vuejs/vue-cli/blob/master/bin/vue-build)
```
new ExtractTextPlugin(options.lib ? `${replaceExtension(options.entry, '.css')}` : '[name].[contenthash:8].css')

```
I have a different project folder structure and I need to define a custom filename for the extracted CSS. How this can be achieved? 

My temporary solution is presented below, but I think there must be a better way.

```
module.exports = {

  webpack(defaults, options) {
    defaults.output.filename = './index.js'
    defaults.plugins.find(el => {
      if (el.constructor.name === 'ExtractTextPlugin') {
        el.filename = './style.css'
      }
    })
    return defaults;
  }

};
```

**Comment by egoist** [comment]
You can also use `.map` to replace that plugin.

maybe add option for this:

```js
module.exports = {
  filename: {
    js: 'index.js',
    css: 'style.css',
    assets: 'static/[name].[ext]'
  }
}
```

**Comment by tadejstanic** [comment]
Ok great!

**Comment by casio** [comment]
hey there

hm, I'm using `v.2.8.1` and for me `filename` in the (non-webpack) config seems to be just ignored.
```js
filename: {
    js: 'index.js',
    css: 'style.css',
    assets: 'static/[name].[ext]'
}
````
..will still output eg `client.35a7fe68.js` when built with `prod`

**Comment by stevensanborn** [comment]
yeah 3.0 you can map filename , it expects a string no?

**Comment by rafegoldberg** [comment]
I tried adding the `filename` entry to my Vue config file thusly:

```js
module.exports = {
  filename: {
    css: 'style.css',
    assets: 'static/[name].[ext]'
  },
  // ...
}
```

But when I run the `build` task I get an error:
 
```
 ERROR  Invalid options in vue.config.js: "filename" is not allowed
```

Am I missing something? (If it helps, am using the `v3.0.0-beta.10` of the `@vue/cli`.)
