### ISSUE TITLE
Cannot create or import project from C: with vue ui

### ISSUE THREAD

**Issue by loicGR** [vuejs/vue-cli#3253]
### Version
3.2.3

### Reproduction link
[http://no.github.for.this.issue.fr](http://no.github.for.this.issue.fr)

### Environment info
```
Windows 10
Firefox or IE or Brave
```

### Steps to reproduce
install vue cli on a window 10 desktop. 
Run vue ui. 
Go to  http://localhost:8000/project/select with Firefox or IE or Brave. 
Go to Create or goto Import. 
Clic on C: in the path input

### What is expected?
The directories under C: should be listed.

### What is actually happening?
Nothing appear and it is impossible to select a project in a directory under C:

**Comment by loicGR** [comment]
![image](https://user-images.githubusercontent.com/8182967/50716952-6e135900-1084-11e9-9fe0-47f742b286ff.png)

**Comment by sodatea** [comment]
Fixed in #3331
