### ISSUE TITLE
[mini-css-extract-plugin] warning

### ISSUE THREAD

**Issue by libbGit** [vuejs/vue-cli#3259]
### Version
3.2.3

### Reproduction link
[http://www.baidu.com(无连接，但又是必需，所以随便填写)](http://www.baidu.com(无连接，但又是必需，所以随便填写))

### Environment info
```
win10 x64,
vue-cli@3
```

### Steps to reproduce
运行yarn build命令

### What is expected?
无此警告

### What is actually happening?
warning

chunk chunk-common [mini-css-extract-plugin]
Conflicting order between:

。。。。。。。。。。。非常多

而且会重复好多遍

---
有什么办法可以消除这个chunk chunk-common [mini-css-extract-plugin]警告吗？在vue.config.js中如何配置，才会消除？

**Comment by sodatea** [comment]
「重现链接」必须填写就是因为我们需要有个重现才能定位问题，随便填的话恕我们帮不上忙。你说的这个 warning 我自己从来没碰上过。

**Comment by wuyuweixin** [comment]
使用cli默认配置是不会出现这种问题的，把你的vue.config.js贴出来。

**Comment by libbGit** [comment]
我刚删除了vue.confing.js试了下没问题，我发现产生的条件是 因为我采用 vue的多入口的方式，即配置了vue.config.js中的pages，然后再两个 入口处，调用了一个公共的组件，然后才报的这个警告

**Comment by sodatea** [comment]
Closing as there's no reproduction provided and likey to be an upstream issue.
