### ISSUE TITLE
最新@vue/cli版本问题

### ISSUE THREAD

**Issue by ayiaq1** [vuejs/vue-cli#3261]
### Version
3.2.3

### Reproduction link
[ https://www.npmjs.com/package/@vue/cli]( https://www.npmjs.com/package/@vue/cli)

### Environment info
```
版本问题
```

### Steps to reproduce
https://www.npmjs.com/package/@vue/cli-plugin-babel
npm最新版本为3.2.2
@vue/cli安装版本为 ：
https://www.npmjs.com/package/@vue/cli
3.2.3 自动构建安装失败

### What is expected?
希望升级@vue/cli-内置包，或者@vue/cli内置包调整为 3.2.2

### What is actually happening?

需要手动修改package.json里面配置版本为 ：3.2.2

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/releases/tag/v3.2.0 https://github.com/vuejs/vue-cli/pull/3020

现在默认创建出来的项目里依赖版本号都是形如 `^3.2.0` 这样的，如果你创建的项目有问题，请升级全局的 @vue/cli 到最新版。

**Comment by ayiaq1** [comment]
我是删除之后，用的最新版本@vue/cli 然后 vue create项目的时候提示找不到@vue/cli-plugin-babel 3.2.3

**Comment by sodatea** [comment]
请运行一下 `vue --version` 和 `vue info` 然后在这里贴一下运行结果。我们整个项目都没有依赖 @vue/cli-plugin-babel 3.2.3 并且我本地测试没有问题，所以应该是你全局安装的问题。

**Comment by anihCevol** [comment]
@sodatea   yarn global add @vue/cli  是安装最新版本（3.3.0）的吧 我是3.2.3 的 ，执行完之后，版本还是3.2.3的。

**Comment by ayiaq1** [comment]
我的是nvm问题 直接删除文件夹之后 重新更新@vue/cli 再创建项目就好了

**Comment by anihCevol** [comment]
好的。
