### ISSUE TITLE
控制台显示的IP地址有点问题

### ISSUE THREAD

**Issue by liaowentuan** [vuejs/vue-cli#3266]
### Version
3.2.0

### Environment info
```
 System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
  Binaries:
    Node: Not Found
    Yarn: Not Found
    npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.785.0
  npmPackages:
    @vue/babel-preset-app:  3.2.0
    @vue/cli-overlay:  3.2.0
    @vue/cli-plugin-babel: ^3.2.0 => 3.2.0
    @vue/cli-plugin-typescript: ^3.2.0 => 3.2.0
    @vue/cli-service: ^3.2.0 => 3.2.0
    @vue/cli-shared-utils:  3.2.0
    @vue/component-compiler-utils:  2.3.1
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    vue: ^2.5.17 => 2.5.21
    vue-class-component: ^6.0.0 => 6.3.2
    vue-hot-reload-api:  2.3.1
    vue-lazyload:  1.2.3
    vue-loader:  15.4.2
    vue-property-decorator: ^7.0.0 => 7.2.0
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.17 => 2.5.21
    vue-template-es2015-compiler:  1.6.0
    vuex: ^3.0.1 => 3.0.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
vue.config.js 
devServer: {
		// host: 'localhost',
		host: "0.0.0.0",
		port: 8000, 
 npm run serve 后，别的小伙伴使用 Network地址 无法打开

### What is expected?
npm run serve 后上面的Network地址显示的是别人都能访问的地址

### What is actually happening?
我的电脑有3个IPv4的地址，使用的是最下面的那个无线局域网适配器的IP地址；而控制台显示的是最上面那个地址，故无法使用别的电脑通过命令行上显示的 ‘Network‘地址打开

---
npm run serve 后上面的Network地址要么不显示；要么就全显示吧

**Comment by liaowentuan** [comment]
![image](https://user-images.githubusercontent.com/27112774/53380140-4adf9880-39a7-11e9-82ca-3235e5dca046.png)

**Comment by shenliangv** [comment]
I had the same problem [(#2534)](https://github.com/vuejs/vue-cli/issues/2534#issue-360729349).
It seems that when there are multiple network adapters, the program did not get the correct IP address.
When I disabled the network adapter until there was only one left, the expected results were achieved.

**Comment by shenliangv** [comment]
This problem seems to be solved by modifying the file [packages/@vue/cli-service/lib/util/prepareURLs.js](https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/util/prepareURLs.js).
Need to install [default-gateway](https://www.npmjs.com/package/default-gateway) dependencies first

line ~ 12
```js
const defaultGateway = require('default-gateway')
```

line ~ 36
```js
// lanUrlForConfig = address.ip()
const result = defaultGateway.v4.sync()
lanUrlForConfig = address.ip(result && result.interface)
```
@sodatea

**Comment by WONDERlust91** [comment]
> This problem seems to be solved by modifying the file [packages/@vue/cli-service/lib/util/prepareURLs.js](https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/util/prepareURLs.js).
> Need to install [default-gateway](https://www.npmjs.com/package/default-gateway) dependencies first
> 
> line ~ 12
> 
> ```js
> const defaultGateway = require('default-gateway')
> ```
> 
> line ~ 36
> 
> ```js
> // lanUrlForConfig = address.ip()
> const result = defaultGateway.v4.sync()
> lanUrlForConfig = address.ip(result && result.interface)
> ```
> 
> @sodatea

My vue-cli version is 3.8.3

**There is also something wrong when the Interface name is in Chinese words.**

![image](https://user-images.githubusercontent.com/23548132/59478023-728d3a80-8e8a-11e9-8de2-7955afcc4cb1.png)

![image](https://user-images.githubusercontent.com/23548132/59477925-08749580-8e8a-11e9-8db1-d0330b0915fe.png)

**I changed the Interface name to English. The problem solved.**

![image](https://user-images.githubusercontent.com/23548132/59478154-e29bc080-8e8a-11e9-80d8-0cd19944c641.png)

![image](https://user-images.githubusercontent.com/23548132/59478179-f810ea80-8e8a-11e9-9ce8-76d3494dcd5c.png)

@sodatea

**Comment by sodatea** [comment]
@WONDERlust91 Thanks for the hint. I don't have a Windows computer at the moment so I can't debug it until later. Could you raise an issue to https://github.com/silverwind/default-gateway? Seems they failed to parse Unicode interface names.

**Comment by WONDERlust91** [comment]
> @WONDERlust91 Thanks for the hint. I don't have a Windows computer at the moment so I can't debug it until later. Could you raise an issue to https://github.com/silverwind/default-gateway? Seems they failed to parse Unicode interface names.

I've already raise an issue to default-gateway.

**Comment by athrunsun** [comment]
Be aware that the IP of your router also matters - it has to match `^10[.]|^172[.](1[6-9]|2[0-9]|3[0-1])[.]|^192[.]168[.]` to be a "private IP".

I changed the IP of my router from `192.168.1.1` to `172.168.1.1` recently and `Network: unavailable` suddenly shows up. `172.16.1.1` will do the trick.

**Comment by zhoufanglu** [comment]
> ### Version
> 3.2.0
> 
> ### Environment info
> ```
>  System:
>     OS: Windows 10
>     CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
>   Binaries:
>     Node: Not Found
>     Yarn: Not Found
>     npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
>   Browsers:
>     Edge: 41.16299.785.0
>   npmPackages:
>     @vue/babel-preset-app:  3.2.0
>     @vue/cli-overlay:  3.2.0
>     @vue/cli-plugin-babel: ^3.2.0 => 3.2.0
>     @vue/cli-plugin-typescript: ^3.2.0 => 3.2.0
>     @vue/cli-service: ^3.2.0 => 3.2.0
>     @vue/cli-shared-utils:  3.2.0
>     @vue/component-compiler-utils:  2.3.1
>     @vue/preload-webpack-plugin:  1.1.0
>     @vue/web-component-wrapper:  1.2.0
>     babel-helper-vue-jsx-merge-props:  2.0.3
>     babel-plugin-transform-vue-jsx:  4.0.1
>     vue: ^2.5.17 => 2.5.21
>     vue-class-component: ^6.0.0 => 6.3.2
>     vue-hot-reload-api:  2.3.1
>     vue-lazyload:  1.2.3
>     vue-loader:  15.4.2
>     vue-property-decorator: ^7.0.0 => 7.2.0
>     vue-router: ^3.0.1 => 3.0.2
>     vue-style-loader:  4.1.2
>     vue-template-compiler: ^2.5.17 => 2.5.21
>     vue-template-es2015-compiler:  1.6.0
>     vuex: ^3.0.1 => 3.0.1
>   npmGlobalPackages:
>     @vue/cli: Not Found
> ```
> 
> ### Steps to reproduce
> vue.config.js
> devServer: {
> // host: 'localhost',
> host: "0.0.0.0",
> port: 8000,
> npm run serve 后，别的小伙伴使用 Network地址 无法打开
> 
> ### What is expected?
> npm run serve 后上面的Network地址显示的是别人都能访问的地址
> 
> ### What is actually happening?
> 我的电脑有3个IPv4的地址，使用的是最下面的那个无线局域网适配器的IP地址；而控制台显示的是最上面那个地址，故无法使用别的电脑通过命令行上显示的 ‘Network‘地址打开
> 
> npm run serve 后上面的Network地址要么不显示；要么就全显示吧

请问 你这个问题解决了吗？

**Comment by liaowentuan** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vuejs/vue-cli"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月4日(星期五) 上午10:47
收件人:&nbsp;"vuejs/vue-cli"<vue-cli@noreply.github.com&gt;;
抄送:&nbsp;"獬豸一族"<996002654@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vuejs/vue-cli] 控制台显示的IP地址有点问题 (#3266)





  
Version
 
3.2.0
 
Environment info
  System:     OS: Windows 10     CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz   Binaries:     Node: Not Found     Yarn: Not Found     npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD   Browsers:     Edge: 41.16299.785.0   npmPackages:     @vue/babel-preset-app:  3.2.0     @vue/cli-overlay:  3.2.0     @vue/cli-plugin-babel: ^3.2.0 =&gt; 3.2.0     @vue/cli-plugin-typescript: ^3.2.0 =&gt; 3.2.0     @vue/cli-service: ^3.2.0 =&gt; 3.2.0     @vue/cli-shared-utils:  3.2.0     @vue/component-compiler-utils:  2.3.1     @vue/preload-webpack-plugin:  1.1.0     @vue/web-component-wrapper:  1.2.0     babel-helper-vue-jsx-merge-props:  2.0.3     babel-plugin-transform-vue-jsx:  4.0.1     vue: ^2.5.17 =&gt; 2.5.21     vue-class-component: ^6.0.0 =&gt; 6.3.2     vue-hot-reload-api:  2.3.1     vue-lazyload:  1.2.3     vue-loader:  15.4.2     vue-property-decorator: ^7.0.0 =&gt; 7.2.0     vue-router: ^3.0.1 =&gt; 3.0.2     vue-style-loader:  4.1.2     vue-template-compiler: ^2.5.17 =&gt; 2.5.21     vue-template-es2015-compiler:  1.6.0     vuex: ^3.0.1 =&gt; 3.0.1   npmGlobalPackages:     @vue/cli: Not Found  
Steps to reproduce
 
vue.config.js
 devServer: {
 // host: 'localhost',
 host: "0.0.0.0",
 port: 8000,
 npm run serve 后，别的小伙伴使用 Network地址 无法打开
 
What is expected?
 
npm run serve 后上面的Network地址显示的是别人都能访问的地址
 
What is actually happening?
 
我的电脑有3个IPv4的地址，使用的是最下面的那个无线局域网适配器的IP地址；而控制台显示的是最上面那个地址，故无法使用别的电脑通过命令行上显示的 ‘Network‘地址打开
 
npm run serve 后上面的Network地址要么不显示；要么就全显示吧
  
请问 你这个问题解决了吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.







----------

不好意思，由于离开了上家公司了。所以没有当时的复杂环境。我也没法验证这个问题

**Comment by zhoufanglu** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "vuejs/vue-cli" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月4日(星期五) 上午10:47 收件人:&nbsp;"vuejs/vue-cli"<vue-cli@noreply.github.com&gt;; 抄送:&nbsp;"獬豸一族"<996002654@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [vuejs/vue-cli] 控制台显示的IP地址有点问题 (#3266) Version 3.2.0 Environment info System: OS: Windows 10 CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz Binaries: Node: Not Found Yarn: Not Found npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD Browsers: Edge: 41.16299.785.0 npmPackages: @vue/babel-preset-app: 3.2.0 @vue/cli-overlay: 3.2.0 @vue/cli-plugin-babel: ^3.2.0 =&gt; 3.2.0 @vue/cli-plugin-typescript: ^3.2.0 =&gt; 3.2.0 @vue/cli-service: ^3.2.0 =&gt; 3.2.0 @vue/cli-shared-utils: 3.2.0 @vue/component-compiler-utils: 2.3.1 @vue/preload-webpack-plugin: 1.1.0 @vue/web-component-wrapper: 1.2.0 babel-helper-vue-jsx-merge-props: 2.0.3 babel-plugin-transform-vue-jsx: 4.0.1 vue: ^2.5.17 =&gt; 2.5.21 vue-class-component: ^6.0.0 =&gt; 6.3.2 vue-hot-reload-api: 2.3.1 vue-lazyload: 1.2.3 vue-loader: 15.4.2 vue-property-decorator: ^7.0.0 =&gt; 7.2.0 vue-router: ^3.0.1 =&gt; 3.0.2 vue-style-loader: 4.1.2 vue-template-compiler: ^2.5.17 =&gt; 2.5.21 vue-template-es2015-compiler: 1.6.0 vuex: ^3.0.1 =&gt; 3.0.1 npmGlobalPackages: @vue/cli: Not Found Steps to reproduce vue.config.js devServer: { // host: 'localhost', host: "0.0.0.0", port: 8000, npm run serve 后，别的小伙伴使用 Network地址 无法打开 What is expected? npm run serve 后上面的Network地址显示的是别人都能访问的地址 What is actually happening? 我的电脑有3个IPv4的地址，使用的是最下面的那个无线局域网适配器的IP地址；而控制台显示的是最上面那个地址，故无法使用别的电脑通过命令行上显示的 ‘Network‘地址打开 npm run serve 后上面的Network地址要么不显示；要么就全显示吧 请问 你这个问题解决了吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> […](#)
> ---------- 不好意思，由于离开了上家公司了。所以没有当时的复杂环境。我也没法验证这个问题

好吧，我这是个人电脑出这个问题了。。不知道是不是环境变量的问题

**Comment by zoudingyi** [comment]
> 好吧，我这是个人电脑出这个问题了。。不知道是不是环境变量的问题

请问你解决了吗？我也怀疑是环境变量问题。
