### ISSUE TITLE
Too many templates generate confusion

### ISSUE THREAD

**Issue by bluesurfer** [vuejs/vue-cli#327]
I am relatively new to Vue and the npm world. I have played with Vue for a while and fell in love with it. Now, I want to make the **next step**:  starting a medium-to-large scale project (meaning that I have to communicate with an API backend).

 I read the [docs section](https://vuejs.org/v2/guide/single-file-components.html#For-Users-New-to-Module-Build-Systems-in-JavaScript) about starting a new project and I reach this repository. I begin looking at the four template and choose the `webpack`one, then I discover that it is not very maintained (packages outdated) and got disappointed. After that I take a look at other templates on Github: 
- [Vuepack](https://vuejs.org/v2/guide/single-file-components.html#For-Users-New-to-Module-Build-Systems-in-JavaScript)
- [vue.js-starter-template](https://github.com/villeristi/vue.js-starter-template)

Now I discover `vuex` and found this other [project structure](https://vuex.vuejs.org/en/structure.html) which is said to be best suited for large project (wasn't it also the `webpack` one best suited?). It becomes all quite confusing. There are too many ways to start a project and each one claims to be the best.

It would be great if there exists **one**, **well maintained** and **officially recognized** project structure.

**Comment by egoist** [comment]
What else disappointed you besides the outdated webpack dependencies in the [webpack](https://github.com/vuejs-templates/webpack) template? (technically webpack 1 is not outdated)

> Now I discover vuex and found this other project structure which is said to be best suited for large project (wasn't it also the webpack one best suited?). It becomes all quite confusing. There are too many ways to start a project and each one claims to be the best. ... There are too many ways to start a project and each one claims to be the best.

After a little research, I found none of these templates and examples are said to be the best one by themselves, can you point it out?

**Comment by yyx990803** [comment]
What makes you think the official webpack template is not well maintained? If there are specific problem you ran into, please open issue there. It is intended to be the **one, well maintained and officially recognized** template. However, the templates are focused on **build toolchains**, not project structure - i.e. it doesn't mandate how you structure your source code. We intentionally stayed away from an overly opinionated source code structure before best practices are consolidated in the community.

**Comment by bluesurfer** [comment]
@egoist 

"best" is not the correct term let's say suggested.

@yyx990803 
 
> What makes you think the official webpack template is not well maintained?

No problem at all. Mostly because `webpack`template uses webpack 1, `webpack-simple` uses webpack 2 and in the webpack site I read: 

> webpack v1 is deprecated. We encourage all developers to upgrade to webpack 2.

I tend to follow best practices (from my Python experience) but **unfortunately**, as you said, the best practices here are not yet consolidated. And I am struggling to find the best way to start whereas in Python the path is more clear. I need a guide to move around this new messy Javascript world :D and if you say:

>  It is intended to be the one, well maintained and officially recognized template. However, the templates are focused on build toolchains, not project structure

I will start right from there and begin installing the stuff I need (bootstrap, vue-routers and axios for the API communication).

**Comment by yyx990803** [comment]
v1 to v2 upgrade is planned for the webpack template and will happen soon (webpack 2 was officially out only two weeks a go).

**Comment by LinusBorg** [comment]
update: the template is now using webpack2 since a week ago or so.
