### ISSUE TITLE
2 missing images on homepage

### ISSUE THREAD

**Issue by StephenOrJames** [vuejs/vue-cli#3273]
### Steps to reproduce
Visit https://cli.vuejs.org/ and you'll see that there are two images missing on the homepage:
- The favicon (used as a logo), which was removed in 016d474
- The Bit logo, which was removed in vuejs/vuejs.org@a835017

### What is expected?
Images should load.

### What is actually happening?
Images fail to load, because they have been deleted.

![image](https://user-images.githubusercontent.com/8732346/50941959-e8f9bc80-1454-11e9-90ed-6836bde3a974.png)

**Comment by sodatea** [comment]
Oops, deleted the favicon by accident. Thank you so much for pointing out!
