### ISSUE TITLE
Deep selector in scss.

### ISSUE THREAD

**Issue by ruojianll** [vuejs/vue-cli#3276]
### What problem does this feature solve?
A deep selector like `>>>` in scoped scss.

### What does the proposed API look like?
Sth like
```
.a{
&>>>.b{
}
}
```

**Comment by sodatea** [comment]
1. This issue should be reported to vue-loader
2. As stated in the [documentaton](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors), sass is not able to parse `>>>`, but `/deep/` works, you can use it instead.
