### ISSUE TITLE
在vue.config.js的configureWebpack配置DefinePlugin，不起作用

### ISSUE THREAD

**Issue by libbGit** [vuejs/vue-cli#3279]
### Version
3.3.0

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Environment info
```
npm  version  6.5.0
node version  10.13.0
vue-cli versioin  3.0.4
```

### Steps to reproduce
我再vue.config.js中添加了DefinePlugin插件，用于扩展 process.env变量，但是结果在控制台打出来，还是定义的这个没有，好像被覆盖了。不知道我哪里写错了
configureWebpack: {
    plugins: [
      new webpack.DefinePlugin({
         'process.env.my_name': '123456789'
       }),
    ]
  },

### What is expected?
在vue的任何组件中调用
process.env.my_name都为123456789

### What is actually happening?
process.env.my_name值为undefined

**Comment by sodatea** [comment]
https://github.com/vuejs/vue-cli/issues/1671
因为默认配置里已经有一个 DefinePlugin 的实例了，请参考链接中提供的代码进行配置。

**Comment by s33you** [comment]
调用方式错了，直接用my_name 宝贝。。
