### ISSUE TITLE
Respect size unit case sensitive in build result

### ISSUE THREAD

**Issue by eneim** [vuejs/vue-cli#3283]
### Version
3.3.0

### Environment info
```
System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  Binaries:
    Node: 10.15.0 - ~/.nodebrew/current/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nodebrew/current/bin/npm
```

### Steps to reproduce
Create new project by ``vue create``, run ``yarn build``

### What is expected?
In build result output, built file whose size is 136 kB (read: kilobyte) are shown in 'kb' (read: kilobit) unit.

### What is actually happening?
In build result output, built file size in proper unit.

> 115,549 bytes (119 KB on disk)

<img width="580" alt="screen shot 2019-01-11 at 12 59 32" src="https://user-images.githubusercontent.com/1776230/51012772-3899ce80-15a2-11e9-8413-a9f0836a573e.png">

---
These days, many developers misuse the size unit (kb for kilobyte, gb for gigabyte, etc, and their argue are always "in the context, we understand".

Here where I work, we have both software engineers (most of the time, their 'context' is at byte level) and network engineers (most of the time, their 'context' is at bit level), so the communication involving data size, transfer bandwidth, etc needs to be exact.

This issue is minor, but I always feel uncomfortable. It is 8 times of different.

**Comment by LinusBorg** [comment]
is't that an upstream issue with webpack?

**Comment by eneim** [comment]
> is't that an upstream issue with webpack?

I'm not really sure. Kinda new to vue eco system and webpack so ...

**Comment by eneim** [comment]
https://en.wikipedia.org/wiki/Units_of_information per this (Wikipedia, I know), I think it should be KiB.
