### ISSUE TITLE
Configure pwa with vue-cli3，throw error: Cannot read property '__expression' of undefined

### ISSUE THREAD

**Issue by MrOldK** [vuejs/vue-cli#3284]
### Version
3.2.3

### Environment info
```
 System:
    OS: macOS High Sierra 10.13.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.14.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 63.0.3
    Safari: 11.1
  npmPackages:
    @vue/babel-preset-app:  3.2.0
    @vue/cli-overlay:  3.2.0
    @vue/cli-plugin-babel: ^3.2.0 => 3.2.0
    @vue/cli-plugin-eslint: ^3.2.1 => 3.2.1
    @vue/cli-plugin-pwa: ^3.3.0 => 3.3.0
    @vue/cli-service: ^3.2.0 => 3.2.0
    @vue/cli-shared-utils:  3.2.0
    @vue/component-compiler-utils:  2.3.1
    @vue/eslint-config-prettier: ^4.0.0 => 4.0.1
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    eslint-plugin-vue: ^5.0.0 => 5.0.0
    vue: ^2.5.17 => 2.5.21
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.1
    vue-loader: ^15.4.2 => 15.4.2
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader: ^4.1.2 => 4.1.2
    vue-template-compiler: ^2.5.21 => 2.5.21
    vue-template-es2015-compiler:  1.6.0
    vuex: ^3.0.1 => 3.0.1
  npmGlobalPackages:
    @vue/cli: 3.2.1
```

### Steps to reproduce
this is my pwa.config.js for the pwa item of vue.config.js:

module.exports = {
  name: "vuecli-pwa-demo",
  themeColor: "#4DBA87",
  msTileColor: "#000000",
  appleMobileWebAppCapable: "yes",
  appleMobileWebAppStatusBarStyle: "black",
  // configure the workbox plugin
  workboxPluginMode: "InjectManifest",
  workboxOptions: {
    // swSrc is required in InjectManifest mode.
    swSrc: "../sw.js"
    // ...other Workbox options...
  }
}

this is  registerServiceWorker.js:

import { register } from 'register-service-worker'

if (process.env.NODE_ENV === 'production') {
  register(`${process.env.BASE_URL}service-worker.js`, {
    ready () {
      console.log(
        'App is being served from cache by a service worker.\n'  
        'For more details, visit https://goo.gl/AFskqB'
      )
    },
    registered () {
      console.log('Service worker has been registered.')
    },
    cached () {
      console.log('Content has been cached for offline use.')
    },
    updatefound () {
      console.log('New content is downloading.')
    },
    updated () {
      console.log('New content is available; please refresh.')
    },
    offline () {
      console.log('No internet connection found. App is running in offline mode.')
    },
    error (error) {
      console.error('Error during service worker registration:', error)
    }
  })
} else if(process.env.NODE_ENV === 'development') {
  register('../sw.js',{
    ready () {
      console.log(
        'App is being served from cache by a service worker.')
    },
    registered () {
      console.log('Service worker has been registered.')
    },
    cached () {
      console.log('Content has been cached for offline use.')
    },
    updatefound () {
      console.log('New content is downloading.')
    },
    updated () {
      console.log('New content is available; please refresh.')
    },
    offline () {
      console.log('No internet connection found. App is running in offline mode.')
    },
    error (error) {
      console.error('Error during service worker registration:', error)
    }
  })
}

### What is expected?
Running pwa success

### What is actually happening?
Cannot read property '__expression' of undefined

---
After running the project with vue-cli3, I just added the configuration based on the original configuration and completely followed the steps described in this link, but it was disappointing that this error was reported.

**Comment by MrOldK** [comment]
oh,sorry,i forgot it .This link refers to: https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-pwa

**Comment by sodatea** [comment]
Please provide a reproduction repo.
