### ISSUE TITLE
chunk自动添加的hash如何去掉？

### ISSUE THREAD

**Issue by orchie** [vuejs/vue-cli#3289]
### Version
3.3.0

### Reproduction link
[https://gitee.com/staroom/temporary_reference/tree/master/vuecli3_howToRemoveChunkHash](https://gitee.com/staroom/temporary_reference/tree/master/vuecli3_howToRemoveChunkHash)

### Environment info
```
win64,npm6.4.1,
```

### Steps to reproduce
配置文件如下
```
// vue.config.js
module.exports = {
    lintOnSave: false,
    filenameHashing: false,
    productionSourceMap: false,
    indexPath: 'backend.html',
    assetsDir: 'dist',
    configureWebpack: config => {
        output: {
            chunkFilename: 'chunk[id].js',
            config.devtool = 'source-map'
        }
    },
    chainWebpack: config => {
        if (process.env.NODE_ENV === 'development') {
            config.output.filename('[name].js').end()
        }
    }
}
```

### What is expected?
期望生成的js及css中不含hash

### What is actually happening?
实际是有hash的 
如 chunk-2d213ee6.js

---
各种尝试  npm run build (指向是     "build": "vue-cli-service build",)
都没有办法去除chunk的hash 我怀疑是哪个插件改的 但网上搜不到是哪个插件改 以及如何改成去除hash
能搜到的方法都尝试了如 vue.config.js中
有三处是为去除hash做的尝试

**Comment by sodatea** [comment]
请提供完整的复现仓库

**Comment by orchie** [comment]
> 请提供完整的复现仓库

项目代码没法提交，我提交了一个构建结果的输出信息 请参考
[控制台输出](https://gitee.com/staroom/temporary_reference/blob/master/vuecli3_howToRemoveChunkHash/npmRunBuildResult)
我又尝试使用vuecli3新建了一个空项目 然后把src文件放进去 补充缺少的package后 build
构建出的js 还是 chunk-hash.js 这种形式  
所以这个应该是个默认的模式  只要是大一点的项目 就会出现这个情况

**Comment by sodatea** [comment]
这是 chunkId 不是 hash，是因为你用了 dynamic import，所以拆出来的异步加载的 JS 文件没有名字的话就会默认生成一个 ID 给它。要自定义这种 JS 文件的名字请使用形如 `/* webpackChunkName: "lodash" */` 的注释。
参考 https://webpack.js.org/guides/code-splitting/#dynamic-imports 和 https://webpack.js.org/api/module-methods/#magic-comments

**Comment by zming619** [comment]
你怎么解决的？show me your code! 哈哈 @orchie
