### ISSUE TITLE
Where can I set transformToRequire?

### ISSUE THREAD

**Issue by sowinski** [vuejs/vue-cli#3301]
Hi,

where can I set the transformToRequire option in a vue-cli 3 based project? (I just used vue create myapp with default settings)

I would like to use bootstrap-vue <b-image> with images from my assets folder.
https://bootstrap-vue.js.org/docs/reference/images/

Thank you

**Comment by LinusBorg** [comment]
```javascript
// vue.config.js
module.exports = {
  chainWebpack: config => {
    config.module.rule('vue').use('vue-loader').tap(options => {
      options.transformToRequire = { ... }
    }
  }
}
```
