### ISSUE TITLE
希望在生成js/css引用时可以添加后缀参数(防缓存)

### ISSUE THREAD

**Issue by orchie** [vuejs/vue-cli#3302]
### What problem does this feature solve?
首先不使用文件名hash解决缓存是因为不喜欢文件名比较乱
(因为是直接丢到git里更新 所以每次名字里hash不一致 git会有一堆增删信息)
但现在名字每次一致 浏览器又会做缓存
还有一个方案就是如 **js?v=123** 这样为js/css资源添加一个后缀
(当然这个后缀可以是hash 可以是变量 函数返回值 等 不是写死的)
这样就完美解决这个问题了
现在 生成的 dist/index.html 入口文件
```
<link as="script" href="/dist/chunk-vendors.js" rel="preload">
    <link as="style" href="/dist/css/app.css" rel="preload">
        <link as="style" href="/dist/css/chunk-vendors.css" rel="preload">
            <link as="script" href="/dist/js/app.js" rel="preload">
                <link href="/dist/css/chunk-vendors.css" rel="stylesheet">
                    <link href="/dist/css/app.css" rel="stylesheet"/>
                </link>
            </link>
        </link>
    </link>
</link>
```

### What does the proposed API look like?
在vue.config.js 中
一行配置 
```
static_asses_name_suffix:value
```
value的类型可以是 [hash] [time] 等cli3提供的变量 
也可以是
```
static_asses_name_suffix:function(){
   return Math.random()
}
```
这样的自定义函数返回值
然后npm run build  
创建的index.html 中 就会生成js/css 带后缀的引用
望采纳，感谢！

**Comment by sodatea** [comment]
只要文件内容不一致，Git 就会有增删信息，保持文件名一致并不能解决这个问题。
暂不考虑支持这类需求，具体讨论可以参见 https://github.com/vuejs/vue-cli/issues/2413
