### ISSUE TITLE
Static method Class B extends A: "Type 'typeof B' is not assignable to type 'typeof A'" in .vue files

### ISSUE THREAD

**Issue by baseprime** [vuejs/vue-cli#3304]
### Version
3.2.3

### Reproduction link
[Here](http://www.typescriptlang.org/play/#src=class%20Food%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%0D%0A%20%20%20%20constructor(name%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.name%20%3D%20name%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20eat()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('Ate'%2C%20this.name)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20static%20create%3CT%20extends%20Food%20%3D%20T%3E(name%3A%20string)%3A%20Promise%3CT%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20let%20instance%20%3D%20%3CT%3Enew%20this(name)%0D%0A%20%20%20%20%20%20%20%20return%20new%20Promise(resolve%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20setTimeout(()%20%3D%3E%20resolve(instance)%2C%205000)%0D%0A%20%20%20%20%20%20%20%20%7D)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20MexicanFood%20extends%20Food%20%7B%0D%0A%20%20%20%20addHotSauce()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('Added%20hot%20sauce%20to'%2C%20this.name)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A(async%20function%20main()%20%7B%0D%0A%20%20%20%20let%20taco%3A%20MexicanFood%20%3D%20await%20MexicanFood.create('Taco')%0D%0A%20%20%20%20taco.addHotSauce()%0D%0A%20%20%20%20taco.eat()%0D%0A%7D)()%0D%0A)

### Environment info
```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
    Yarn: Not Found
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: Not Found
    Safari: 12.0.2
  npmPackages:
    @vue/babel-preset-app:  3.2.2 
    @vue/cli-overlay:  3.2.0 
    @vue/cli-plugin-babel: ^3.2.0 => 3.2.2 
    @vue/cli-plugin-eslint: ^3.2.0 => 3.2.2 
    @vue/cli-plugin-typescript: ^3.2.0 => 3.2.2 
    @vue/cli-plugin-unit-mocha: ^3.2.0 => 3.2.2 
    @vue/cli-service: ^3.2.0 => 3.2.3 
    @vue/cli-shared-utils:  3.2.2 
    @vue/component-compiler-utils:  2.4.0 
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1 
    @vue/eslint-config-typescript: ^3.2.0 => 3.2.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/test-utils: ^1.0.0-beta.20 => 1.0.0-beta.28 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    babel-plugin-transform-vue-jsx:  4.0.1 
    bootstrap-vue: ^2.0.0-rc.11 => 2.0.0-rc.11 
    eslint-plugin-vue: ^5.0.0 => 5.1.0 
    vue: ^2.5.21 => 2.5.21 
    vue-class-component: ^6.0.0 => 6.3.2 
    vue-eslint-parser:  2.0.3 
    vue-functional-data-merge:  2.0.7 
    vue-hot-reload-api:  2.3.1 
    vue-loader:  15.5.0 
    vue-localstorage: ^0.6.2 => 0.6.2 
    vue-property-decorator: ^7.0.0 => 7.2.0 
    vue-router: ^3.0.1 => 3.0.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.5.21 
    vue-template-es2015-compiler:  1.6.0 
    vuex: ^3.0.1 => 3.0.1 
  npmGlobalPackages:
    @vue/cli: 3.2.3
```

### Steps to reproduce
Take this `FoodComponent.vue` example:
```typescript
<script lang="ts">
class Food {
    name: string;

    constructor(name: string) {
        this.name = name
    }

    eat() {
        console.log('Ate', this.name);
    }

    static create<T extends Food = T>(name: string): Promise<T> {
        let instance = <T>new this(name)
        return new Promise(resolve => {
            setTimeout(() => resolve(instance), 5000)
        })
    }
}

class MexicanFood extends Food {
    addHotSauce() {
        console.log('Added hot sauce to', this.name)
    }
}

MexicanFood.create('Taco').then((taco: MexicanFood) => {
    //                           ^
    // In ALL .vue files, receiving this error:
    //   Type 'Food' is not assignable to type 'MexicanFood'.
    //    Property 'addHotSauce' is missing in type 'Food'.
})
</script>
```

### What is expected?
I shouldn't receive any errors

### What is actually happening?
Moving the above code to its own file does not show any errors. However, using this code in the exact same way in a `.vue` file shows a Type check error, which shouldn't happen:
```
Type 'Food' is not assignable to type 'MexicanFood'.
  Property 'addHotSauce' is missing in type 'Food'.
```

**Comment by LinusBorg** [comment]
I just [copied your code into the typescript playground](https://www.typescriptlang.org/play/index.html#src=class%20Food%20%7B%0D%0A%20%20%20%20name%3A%20string%3B%0D%0A%0D%0A%20%20%20%20constructor(name%3A%20string)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.name%20%3D%20name%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20eat()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('Ate'%2C%20this.name)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20static%20create%3CT%20extends%20Food%20%3D%20T%3E(name%3A%20string)%3A%20Promise%3CT%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20let%20instance%20%3D%20%3CT%3Enew%20this(name)%0D%0A%20%20%20%20%20%20%20%20return%20new%20Promise(resolve%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20setTimeout(()%20%3D%3E%20resolve(instance)%2C%205000)%0D%0A%20%20%20%20%20%20%20%20%7D)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20MexicanFood%20extends%20Food%20%7B%0D%0A%20%20%20%20addHotSauce()%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log('Added%20hot%20sauce%20to'%2C%20this.name)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0AMexicanFood.create('Taco').then((taco%3A%20MexicanFood)%20%3D%3E%20%7B%0D%0A%20%20%20%20%2F%2F%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%0D%0A%20%20%20%20%2F%2F%20In%20ALL%20.vue%20files%2C%20receiving%20this%20error%3A%0D%0A%20%20%20%20%2F%2F%20%20%20Type%20'Food'%20is%20not%20assignable%20to%20type%20'MexicanFood'.%0D%0A%20%20%20%20%2F%2F%20%20%20%20Property%20'addHotSauce'%20is%20missing%20in%20type%20'Food'.%0D%0A%20%20%20%20taco%0D%0A%7D)), and I get the same error.

And it's not really suprising, since `create()` is generically Typed, falling back on type `Food` if none was provided (if I'm not mistaken).

If you provide an actual type for the generic, it works:
```
MexicanFood.create<MexicanFood>('Taco').then((taco: MexicanFood) => {
  // ...
})
```

So the question is rather why you don't you get that error in normal files?

**Comment by LinusBorg** [comment]
Edit: If you change this code in your Playground:
```typescript
let taco: MexicanFood = await MexicanFood.create('Taco')
```

To this:
```typescript
let taco = await MexicanFood.create('Taco')
```

Then you also ge the error. In other words: your TS Playground example works because of that annotation, which is missing from the you code you pasted into this issue above.

**Comment by baseprime** [comment]
@LinusBorg The issue is that the type errors are not consistent across standalone `.ts` files and `.vue` files. 

In a Vue project using single `.vue` files, I can take the example code and put it into a `.vue` file wrapped with `<script lang="ts">` and I see these type errors. But when I take that exact same code and move it into a standalone `.ts` file, I don't receive any errors at all. Both using the same `tsconfig.json` and therefore the same rules.

**Comment by baseprime** [comment]
> Then you also ge the error. In other words: your TS Playground example works because of that annotation, which is missing from the you code you pasted into this issue above.

And by changing 
```typescript
let taco: MexicanFood = await MexicanFood.create('Taco')
``` 
to 
```typescript
let taco = await MexicanFood.create('Taco')
```
then you're unassigning `taco` as an instance of `MexicanFood` so you get another error if you try to
```typescript
taco.addHotSauce()
// Property 'addHotSauce' does not exist on type 'Food'
```

The above result is very peculiar because it's typed to be given the context `T extends Food` so your example *should* work, and you *shouldn't have to* explicitly type `taco: MexicanFood`, and it should know that it's an instance of `MexicanFood` and not `Food`, but it doesn't in this case.

**Comment by baseprime** [comment]
In the TS Playground, hovering over `create()` method also shows a preview of the correct output, which is the same for standalone `.ts` files, but not the case for `.vue` files.

<img width="772" alt="screen shot 2019-01-15 at 5 55 09 pm" src="https://user-images.githubusercontent.com/1062622/51221777-b5ed7800-18ef-11e9-9006-737b31a28b6b.png">



Here's what I get in a `.vue` file with the same exact code:

<img width="856" alt="screen shot 2019-01-15 at 6 02 53 pm" src="https://user-images.githubusercontent.com/1062622/51221801-d9182780-18ef-11e9-9e54-6637cacd954e.png">


This type in the latter screenshot is not correct:
```typescript
(method) Food.create<Food>(name: string): Promise<Food>
```

**Comment by LinusBorg** [comment]
Please provide a reproduction repository.

**Comment by baseprime** [comment]
Example app is here: 🗄 [issue-3304-demo.zip](https://github.com/vuejs/vue-cli/files/2767259/issue-3304-demo.zip)

I just simply used Vue CLI with TypeScript+Prettier preset and added two files:

- `src/TSFileExample.ts`
- `src/VueFileExample/vue`

The `.vue` file has type errors and the `.ts` file doesn't.

@LinusBorg

**Comment by sodatea** [comment]
Can't reproduce.

**Comment by baseprime** [comment]
@sodatea Did you download the example app?

**Comment by baseprime** [comment]
@sodatea @LinusBorg Still having this issue. I'm wondering if you had a chance to download the example source I attached above.
