### ISSUE TITLE
when using Nested Routes,  hot-reload is not working,  child page can not  be rerendered

### ISSUE THREAD

**Issue by liuhao1991** [vuejs/vue-cli#3314]
### Version
3.2.3

### Environment info
```
windows 10
```

### Steps to reproduce
none

### What is expected?
rerender the page

### What is actually happening?
rerender the page is not happening

this happens when a router has multi-children, and you change path in the browser between these path, then you change you code in any of  multi-children components, page can not be rerendered

**Comment by jkzing** [comment]
Please provide a reproduction repo.

**Comment by LinusBorg** [comment]
Also sounds like an issue for vue-loader or vue-router, not the CLI. We don't do anything special for HMR besides activating it through webpack.

**Comment by liuhao1991** [comment]
> Please provide a reproduction repo.

it's my vue.config.js's problem, I find it.

**Comment by sshanzel** [comment]
> > Please provide a reproduction repo.
> 
> it's my vue.config.js's problem, I find it.

Can you please mention what should be placed in the config specifically? I'm actually having the same issue

**Comment by nehalshah50** [comment]
I have same issue as well. How to fix this?

**Comment by nehalshah50** [comment]
> > Please provide a reproduction repo.
> 
> it's my vue.config.js's problem, I find it.

Please provide solution

**Comment by nehalshah50** [comment]
I found the solution.

You need to add the following in your index.html under <head>

<base href="/" />

**Comment by kamasuPaul** [comment]
> I found the solution.
> 
> You need to add the following in your index.html under
> 
> `<base href="/" />`

Thank you @nehalshah50 . Adding `<base href="/" />` under the `<head></head>` section of the `index.html` page solved the issue

**Comment by Khaled-Alaa** [comment]
I am facing the same issue in nested routes and after adding `<base href="/" />` still not working.

Here is my vite config,
``` js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import eslintPlugin from "vite-plugin-eslint";
import path from "path";

export default defineConfig({
  plugins: [
    react(),
    eslintPlugin({
      cache: false,
      emitError: true,
      failOnError: true,
    }),
  ],
});
```
