### ISSUE TITLE
新建的vue-cli3项目Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by x3852** [vuejs/vue-cli#3317]
新建的vue-cli 3项目启动后浏览器控制台直接会出现这个异常
![image](https://user-images.githubusercontent.com/26081477/51306525-7dc57100-1a78-11e9-98e9-8b52b8728f60.png)
这是我的配置
![image](https://user-images.githubusercontent.com/26081477/51306572-9df53000-1a78-11e9-84cc-b82542d8b99a.png)

**Comment by sodatea** [comment]
injectScripts.min.js 很明显不是 Vue CLI 提供的文件，请检查你自己的代码或者浏览器扩展。根据 Google 到的信息可能是 Egret 扩展引起的报错。

**Comment by x3852** [comment]
这的是Egret扩展引起的异常，关闭Egret异常就消失了

**Comment by x3852** [comment]
> injectScripts.min.js很明显不是Vue CLI提供的文件，请检查你自己的代码或者浏览器扩展。根据Google到的信息可能是Egret扩展引起的报错。

真的是Egret扩展引起的报错，关闭Egret扩展后异常就消失了
