### ISSUE TITLE
静态资源引用路径错误

### ISSUE THREAD

**Issue by xbigcat** [vuejs/vue-cli#3319]
### Version
3.3.0

### Environment info
```
  System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Node: 8.9.4 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.1
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.1
    @vue/babel-preset-app:  3.3.0
    @vue/babel-preset-jsx:  1.0.0-beta.1
    @vue/babel-sugar-functional-vue:  1.0.0-beta.1
    @vue/babel-sugar-inject-h:  1.0.0-beta.1
    @vue/babel-sugar-v-model:  1.0.0-beta.1
    @vue/babel-sugar-v-on:  1.0.0-beta.1
    @vue/cli-overlay:  3.3.0
    @vue/cli-plugin-babel: ^3.3.0 => 3.3.0
    @vue/cli-plugin-eslint: ^3.3.0 => 3.3.0
    @vue/cli-service: ^3.3.0 => 3.3.0
    @vue/cli-shared-utils:  3.3.0
    @vue/component-compiler-utils:  2.5.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    eslint-plugin-vue: ^5.0.0 => 5.1.0
    vue: ^2.5.21 => 2.5.21
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.1
    vue-lazyload:  1.2.6
    vue-loader:  15.5.1
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.5.21
    vue-template-es2015-compiler:  1.8.1
    vuex: ^3.0.1 => 3.0.1
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
1. 将 publicPath 设置为相对路径 './'
2. pages 多页面配置 filename 为多层级路径，例如 page.filename = './activity/sale.html' 
3. 最终生成的 sale.html 里引用的静态资源路径为 static/js/chunk-vendors.320144e8.js

### What is expected?
../static/js/chunk-vendors.320144e8.js

### What is actually happening?
static/js/chunk-vendors.320144e8.js

**Comment by LinusBorg** [comment]
@sodatea Can we close this? It's still lacking a reproduction but since I can't read any of this maybe I'm missing a clue?

**Comment by sodatea** [comment]
See: https://cli.vuejs.org/zh/config/#publicpath
> 相对路径的 `publicPath` 有一些使用上的限制。在以下情况下，应当避免使用相对 `publicPath`:
>  - 当使用基于 HTML5 `history.pushState` 的路由时；
>  - 当使用 `pages` 选项构建多页面应用时。

**Comment by foreverwang** [comment]
> See: https://cli.vuejs.org/zh/config/#publicpath
> 
> > 相对路径的 `publicPath` 有一些使用上的限制。在以下情况下，应当避免使用相对 `publicPath`:
> > 
> > * 当使用基于 HTML5 `history.pushState` 的路由时；
> > * 当使用 `pages` 选项构建多页面应用时。

publicPath: '' 这样？
