### ISSUE TITLE
Minor Bug: router/index.js needs repositioning of import

### ISSUE THREAD

**Issue by codeofsumit** [vuejs/vue-cli#333]
Reproduce like this:

vue init webpack project
Choose eslint with airbnb preset
choose vue-router

after `npm install && npm run dev`, `router/index.js` will look like this:

```
import Vue from 'vue';
import Router from 'vue-router';

Vue.use(Router);

import Hello from 'components/Hello'; // <-- eslint error

export default new Router({
  routes: [
    {
      path: '/',
      name: 'Hello',
      component: Hello,
    },
  ],
});

```

ESLint will throw an error as `import Hello from 'components/Hello';` needs to be above `Vue.use(Router);`.

I would've created a PR (guess the fix is simple) but to be honest: I have not the slightest clue how vue-cli works 😊. Sorry.

**Comment by posva** [comment]
This should be open on the relevant template repository. But there's already a fix for it at https://github.com/vuejs-templates/webpack/pull/478
