### ISSUE TITLE
Vue SFC typescript prettier lint reports <template> block as invalid white space

### ISSUE THREAD

**Issue by danielwaltz** [vuejs/vue-cli#3330]
### Version
3.3.0

### Reproduction link
[https://github.com/danielwaltz/vue-typescript-prettier](https://github.com/danielwaltz/vue-typescript-prettier)

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.4 Ubuntu 16.04.5 LTS (Xenial Xerus)
    CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor

  Binaries:
    Node: 10.15.0 - /usr/bin/node
    Yarn: 1.13.0 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vue/cli-overlay:  3.3.0
    @vue/cli-plugin-typescript: ^3.3.0 => 3.3.0
    @vue/cli-service: ^3.3.0 => 3.3.0
    @vue/cli-shared-utils:  3.3.0
    @vue/component-compiler-utils:  2.5.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    vue: ^2.5.21 => 2.5.22
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.5.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.5.22
    vue-template-es2015-compiler:  1.8.1
  npmGlobalPackages:
    @vue/cli: 3.3.0
```

### Steps to reproduce
Run `yarn && yarn lint`.

### What is expected?
The output of the lint script should be successful.

### What is actually happening?
The output of the lint script fails.

---
Related issue: https://github.com/prettier/tslint-config-prettier/issues/259

**Comment by LinusBorg** [comment]
There really is a big block of whitespace added where the template was - without it, sourcemaps would always point for totally wrong line numbers for the JS if your script blocks are below the template blocks. 

A similar problem exists with eslint, which is why we disable this rule it eslint config preset for vue files i think.

**Comment by LinusBorg** [comment]
I'll close this as there's no real solution to this. the rule is simply incompatible with the setup we currently have for tslint.

Fortunately, eslint just announced that they will soon support all tslint rules with their typescript preset & parser, so we might be able to ditch tslint rather soon.
