### ISSUE TITLE
IOS 9.3.3 vue3 blank screen

### ISSUE THREAD

**Issue by postalangel** [vuejs/vue-cli#3333]
I am developing web app vue3/npm and have node babel package installed.
I had an object.values undefined on Vue app render error in IOS 9,10 so I have included following script inside babel.config.js
presets: [
'@vue/app',
["@babel/preset-env", {
"useBuiltIns": "entry"
}]
]

and then included in main.js entry point import '@babel/polyfill';

Current Behavior
Now I have no errors when tracking app running on IOS 10, but still I see that vue app has not been rendered (blank screen)

Environment

@babel/polyfill 7.2.5
node 11.7.0
vue3
OS: IOS 9.3.2.

**Comment by walleevaysh** [comment]
so am i !!!!,  ios8.3 also can not start up nomal,  blank screen
