### ISSUE TITLE
最新的cli无法使用路由懒加载

### ISSUE THREAD

**Issue by artiely** [vuejs/vue-cli#3337]
### Version
3.3.0

### Environment info
```
win7
```

### Steps to reproduce
今日更新cli后， 

vue create my-project

cd my-project

npm run serve

报错

### What is expected?
顺利启动

### What is actually happening?
Module parse failed: Unexpected token (19:13)
You may need an appropriate loader to handle this file type.
|     name: 'about',
|     component: function component() {
>       return import('./views/About.vue');
|     }
|   }]

---
我什么都还没有做，示例跑不起来

**Comment by windy330** [comment]
我也遇到同样的问题

**Comment by kobezhu** [comment]
```sh
 error  in ./src/script/router.js

Module parse failed: Unexpected token (12:11)
You may need an appropriate loader to handle this file type.
|   },
|   component: function component() {
>     return import(
|     /* webpackChunkName: "index" */
|     '@v/index');

 @ ./src/main.js 11:0-31 20:10-16
 @ multi (webpack)-dev-server/client?http://172.22.16.209:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```
I have also experienced this problem.

**Comment by TpWILovePanda** [comment]
與 #3335 依樣問題

**Comment by ZhexuanCao** [comment]
有没有解决这个问题

**Comment by CaiPeng1989** [comment]
刚才新建了一个项目，用yarn安装的依赖，没有返现这个问题，你们能提供代码吗

**Comment by LinusBorg** [comment]
Duplicate

**Comment by IEfucker** [comment]
查了半天才找到是cli的问题。。。

**Comment by CarryKiana** [comment]
win10, 同样的问题

**Comment by TY-LIU** [comment]
npm i webpack@4.28.4
done

**Comment by dyyliao123** [comment]
> 查了半天才找到是cli的问题。。。

解决了吗  大哥  能不能分享一下

**Comment by CaiPeng1989** [comment]
@dyyliao123 现在升级一下 `@vue/cli-service` 就行了
