### ISSUE TITLE
Why use ensureSlash to force slash in front?

### ISSUE THREAD

**Issue by csvwolf** [vuejs/vue-cli#3338]
### What problem does this feature solve?
We set `publicPath` in the `vue.config.js`. But it will add a slash in the front when there is no `https?:`. In our usage, we will use a publishing tools to handle some STRING LIKE `__CDN__`. In webpack we only need to set publicPath to `__CDN__/`, but now we should set as `./__CDN__/`.

 I don't think the cli should check and auto change personal publicPath settings.

### What does the proposed API look like?
For compatibility, maybe add an option like `forceSlash` to switch the feature is better.

**Comment by LinusBorg** [comment]
> Really ugly

Uglyness is an expression of personal taste, so not really a criteria by which to judge this.

Do you have any real, tangible, technical problem resulting from this?

**Comment by jkzing** [comment]
Because webpack `publicPath` do that, https://webpack.js.org/configuration/output/#output-publicpath.
