### ISSUE TITLE
Lock toolchain dependencies' version

### ISSUE THREAD

**Issue by 634750802** [vuejs/vue-cli#3340]
### What problem does this feature solve?
CI always reinstall packages, and it's difficult to find the problem from toolchains like `webpack` or `babel`. Locking the dependencies' version helps.

See issue https://github.com/webpack/webpack/issues/8656. 

### What does the proposed API look like?
None

**Comment by LinusBorg** [comment]
That problem wouldn't really have been avoided by us locking dependencies. 

Plus, this means that we would have to update our own packages daily, practically speaking. Because otherwise we would risk missing patch releases. 

Your project has a lock file which locks your dependencies anyway, so i don't see any worthwhile advantage in your proposal

**Comment by 634750802** [comment]
Thanks for reply. The fact is, I didn't know when webpack updates from v4.28.* to v4.29.0, I have to track all `@vue/cli-service` dependencies to find if I was wrong (My bad for not checking github issues first :)).

The cli-service is really a complicated program, how about locking the minor version to reduce the risk from other dependencies?

**Comment by Akryum** [comment]
You should either have a `package-lock.json` or a `yarn.lock` file in your project if you use npm or yarn. This files already contains all the versions of all the installed packages in `node_modules` no matter if they are direct or transitive (dependencies of other packages). Your CI will either run `npm install` or `yarn`, which will install the exact same versions.

**Comment by 634750802** [comment]
What if I upgrade some packages like `@vue/cli-service`? It always requires the latest version of webpack 4.

**Comment by 634750802** [comment]
It’s Wired, I haven’t deleted my lock file, but the webpack version just changed.
