### ISSUE TITLE
Hot Reload does not work. WebSocket frame shows up a type:invalid payload

### ISSUE THREAD

**Issue by daniele-orlando** [vuejs/vue-cli#3345]
### Version
3.3.0

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (2) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Download the attached archive [Bug.zip](https://github.com/vuejs/vue-cli/files/2780760/Bug.zip) and extract it
2. `npm install`
3. `./node_modules/.bin/vue-cli-service serve`
4. Edit the file `src/ui/boot-view.vue` and see HMR failing

### What is expected?
Changing a Vue component source code, modifications should be reflected on the client without the need of reloading the page.

### What is actually happening?
Changes are processed by the vue-cli resulting in a valid build output,
but they are not correctly notified to the client.

---
Hot Reloading was working fine with version 3.1 of vue-cli.

Looking inside the Chrome Network Panel these are the WebSocket frames:

```
o
a["{\"type\":\"hot\"}"]
a["{\"type\":\"overlay\",\"data\":{\"warnings\":false,\"errors\":true}}"]
a["{\"type\":\"log-level\",\"data\":\"none\"}"]
a["{\"type\":\"hash\",\"data\":\"4817374291a2ba483ed7\"}"]
a["{\"type\":\"ok\"}"]
```

At this point I change the source code and when the vue-cli ends compilation this is what is notified to the client:

```
a["{\"type\":\"invalid\"}"]
a["{\"type\":\"invalid\"}"]
a["{\"type\":\"hash\",\"data\":\"5b48de2c0f5894247e83\"}"]
a["{\"type\":\"ok\"}"]
```

It doesn't matter what I change (style/js/template) in which component, I end up always with the same result.
The only way to fix it is manually reloading the page.

package.json
```
        "@babel/core": "7.2.2",
        "@babel/plugin-proposal-export-default-from": "7.2.0",
        "@babel/plugin-proposal-nullish-coalescing-operator": "7.2.0",
        "@babel/plugin-proposal-object-rest-spread": "7.2.0",
        "@babel/plugin-proposal-optional-chaining": "7.2.0",
        "@babel/plugin-proposal-pipeline-operator": "7.2.0",
        "@babel/plugin-syntax-jsx": "7.2.0",
        "@babel/preset-env": "7.2.3",
        "@vue/babel-helper-vue-jsx-merge-props": "1.0.0-beta.2",
        "@vue/babel-preset-jsx": "1.0.0-beta.2",
        "@vue/cli": "3.3.0",
        "@vue/cli-plugin-babel": "3.3.0",
        "@vue/cli-service": "3.3.1",
        "babel-loader": "8.0.5",
        "babel-plugin-transform-imports": "1.5.1",
        "vue": "2.5.22",
        "vue-cli-plugin-quasar": "0.17.1",
        "vue-router": "3.0.2",
        "vue-template-compiler": "2.5.22",
        "webpack": "4.29.0",
        "webpack-cli": "3.2.1"
```

**Comment by daniele-orlando** [comment]
@LinusBorg Given the `a["{\"type\":\"invalid\"}"]` payload inside the WebSocket frame, is there anything I can do to output the cause of the error. I mean enabling some vue-cli/webpack debug options. At least for trying to understand who is emitting that invalid message and why.

**Comment by jkzing** [comment]
@daniele-orlando You have `"webpack": "4.29.0"` in you package.json, which doesn't match the one we are using (`"4.28.4"`). Remove it or just change it to "4.28.4" solves your problem.

**Comment by daniele-orlando** [comment]
@jkzing I had `webpack@4.28.4` but Hot Reloading was not working. I updated it to `4.29.0` as an attempt to fix the problem but it didn't. I just downgraded it to `4.28.4` and it still doesn't work.

**Comment by daniele-orlando** [comment]
Thanks @LinusBorg. I'll update the issue with my further investigation, because the fix proposed by @jkzing does work with the "Bug.zip" project I attached, but does not work with my real project. So I'm going to update the ticked with a new way to reproduce the bug still using WebPack `4.28.4`.

**Comment by daniele-orlando** [comment]
Ok, thanks to the @jkzing suggestion, I've been able to identify the problem.

I had to downgrade both `webpack` and `webpack-cli` to their previous minor versions: `4.28.4` and `4.1.2` respectively.

Guys, do you think is it the case to open an issue on the webpack/webpack-cli project or is it something between vue-cli and the newest version of webpack/webpack-cli that collides?

Thank you very much for the help.

**Comment by hsablonniere** [comment]
@daniele-orlando Do you mean `webpack-cli@3.2.1`? `4.1.2` does not exist.

FYI, I may have the same pb.

**Comment by daniele-orlando** [comment]
@hsablonniere Yes that one :sweat_smile:

**Comment by hsablonniere** [comment]
I'm struggling to make it work...

**Comment by daniele-orlando** [comment]
Oh my god, it's a never ending nightmare really. It doesn't work again:
```
webpack@4.28.4
webpack-cli@3.2.1
```

**Comment by LinusBorg** [comment]
Out of interest: what do you need the webpack-cli for in combination with vue-cli?

**Comment by daniele-orlando** [comment]
I use webpack-cli for this
```
webpack --config "$WebpackFile" --profile --json
```
and I use webpack inside `vue.config.js` for the `webpack.ContextReplacementPlugin`.

**Comment by daniele-orlando** [comment]
Things seam to have improved after I deleted the `node_modules/.cache/{babel-loader,vue-loader}` directories.

**Comment by DMXL** [comment]
> You have `"webpack": "4.29.0"` in you package.json, which doesn't match the one we are using (`"4.28.4"`). Remove it or just change it to "4.28.4" solves your problem.

@jkzing Thank you that does it for me. Care to elaborate on why it's causing the HMR malfunctioning?

**Comment by mecampbellsoup** [comment]
> Given the `a["{\"type\":\"invalid\"}"]` payload inside the WebSocket frame, is there anything I can do to output the cause of the error. I mean enabling some vue-cli/webpack debug options. At least for trying to understand who is emitting that invalid message and why.

Does anyone know the answer to this? I was thinking of using something like `devServer.proxy` or `devServer.after` to ... check the response message content from the websocket server I suppose?

cc @daniele-orlando

**Comment by Anubarak** [comment]
I deleted and reinstalled everything several times but it still does not work
My package json is
```JSON
{
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@babel/plugin-proposal-class-properties": "^7.13.0",
    "axios": "^0.21.1",
    "core-js": "^3.6.5",
    "lodash": "^4.17.21",
    "mitt": "^2.1.0",
    "moment": "^2.29.1",
    "object-hash": "^2.1.1",
    "primeicons": "^4.1.0",
    "primevue": "^3.2.1",
    "socket.io-client": "^2.2.0",
    "vue": "^3.0.0",
    "vue-router": "^4.0.4",
    "vuex": "^4.0.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0-0"
  }
}
```
And I always receive `{"type":"invalid"}`
![image](https://user-images.githubusercontent.com/6122122/112849976-e1f90c00-90a9-11eb-89a0-5c4e23abdad6.png)

Any way to solve that or at least search for an solution?

**Comment by mxvsh** [comment]
any fix @Anubarak ?

**Comment by Anubarak** [comment]
> any fix @Anubarak ?

My fix was not using primevue. It's great from js perspective but really poorly written in terms of vue. Not using it fixed many problems I had.

**Comment by mxvsh** [comment]
> > any fix @Anubarak ?
> 
> My fix was not using primevue. It's great from js perspective but really poorly written in terms of vue. Not using it fixed many problems I had.

i am getting type invalid error in the websocket message, i am using webpack with react
