### ISSUE TITLE
无法定制打包过程中是否删除dist目录

### ISSUE THREAD

**Issue by Richard-Choooou** [vuejs/vue-cli#3347]
### What problem does this feature solve?
目前有需要将其他文件打包到dist目录的需求，但是一旦运行打包命令，会将整个dist目录删除，webpack config里也没看见cleanWebpackplugin的配置，无法手动更改。

**Comment by sodatea** [comment]
https://cli.vuejs.org/zh/config/#outputdir

> 注意目标目录在构建之前会被清除 (构建时传入 `--no-clean` 可关闭该行为)。
