### ISSUE TITLE
VUE CLI3的构建库构建 CommonJS 包没有提供压缩功能

### ISSUE THREAD

**Issue by ziyi2** [vuejs/vue-cli#3348]
### Version
3.3.0

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue-cli](https://new-issue.vuejs.org/?repo=vuejs/vue-cli)

### Environment info
```
vue-cli 3.3.0
```

### Steps to reproduce
package.json:

"lib:common": "cross-env LIB_TYPE=common vue-cli-service build --no-clean --target lib --formats commonjs

vue.config.js

// commonjs2打包处理
    webpackConfig.when(process.env.LIB_TYPE === 'common', config => {
      config.optimization.minimize(true)
    })

### What is expected?
希望能得到压缩版本

### What is actually happening?
无法产生压缩版本

---
用户的vue.config.js被resolveLibConfig.js中的genConfig配置覆盖，希望可以增加一个 --formats commonjs-min。

**Comment by sodatea** [comment]
为什么 CommonJS 需要压缩版本？CommonJS 包又不可能直接拿到浏览器中使用。

**Comment by ziyi2** [comment]
> 为什么 CommonJS 需要压缩版本？CommonJS 包又不可能直接拿到浏览器中使用。

我也是这么想的，但是我看了element组件库是产生压缩版本的，我不知道是基于什么考虑的，如果不产生压缩版本，那么有办法去掉注释么，这个要怎么配置，我们公司对于信息比较敏感。

**Comment by ziyi2** [comment]
> 为什么 CommonJS 需要压缩版本？CommonJS 包又不可能直接拿到浏览器中使用。

我之前也是这么想的，主要是看到element打包CommonJS用了压缩，所以才有疑问。
