### ISSUE TITLE
如何在VUE CLI3中配置webpack-node-externals

### ISSUE THREAD

**Issue by ziyi2** [vuejs/vue-cli#3352]
### What problem does this feature solve?
在VUE CLI3构建库中，我想请问在VUE CLI3中我要对externals配置webpack-node-externals，要怎么处理，我不清楚这个是webpack-chain的限制还是vue-cli3的限制，还是说有其他方法例如webpack-merge，我对webpack不是很熟悉，VUE-CLI3中默认加入了对象类型的vue打包忽略，但是如果要使用webpack-node-externals，根据webpack的官方文档，externals需要使用数组类型，于是乎我不知道该怎么设置了，另外我是不是可以换个思路，如果不采用webpack-node-externals，那就去读取package.json里的dependencies依赖列表，然后加入externals。在这里求助。。、。、。、。

### What does the proposed API look like?
无

**Comment by ziyi2** [comment]
通过configureWebpack可以生效，具体进行如下配置

``` javascript
configureWebpack () {
    return {
      externals: [
        {
          vue: 'vue'
        },
        nodeExternals(),
        nodeExternals({
          modulesDir: path.resolve(__dirname, 'node_modules')
        })
      ]
    }
  }
```

但是如果想换成webpack-chain，仍然不知道如何配置。

**Comment by sodatea** [comment]
```js
module.exports = {
  chainWebpack: config =>
    config.externals([
      { vue: 'Vue' },
      nodeExternals(),
      nodeExternals({
        modulesDir: path.resolve(__dirname, 'node_modules')
      })
    ])
}
```
