### ISSUE TITLE
typescript-eslint-parser is deprecated

### ISSUE THREAD

**Issue by kuoruan** [vuejs/vue-cli#3355]
### What problem does this feature solve?
typescript-eslint-parser has moved to https://github.com/typescript-eslint/typescript-eslint , the new package is ```@typescript-eslint/parser```.

new package supports typescript 3.2 and the commit da6bd75e2cf11033f3c761158bbb2e652c421db1 should be revert.

### What does the proposed API look like?
Support eslint typescript 3.2

**Comment by kjleitz** [comment]
For context, here is the deprecation notice: https://github.com/bradzacher/eslint-plugin-typescript/issues/290

**Comment by kuoruan** [comment]
Close this issue -> 189ea5440208735549b9d5c4df28280fb7a5bced
