### ISSUE TITLE
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. 

### ISSUE THREAD

**Issue by 410919244** [vuejs/vue-cli#3356]
### Version
3.3.0

### Reproduction link
[https://github.com/410919244/mp-web.git](https://github.com/410919244/mp-web.git)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Node: 11.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\word\yarn\bin\yarn.CMD
    npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 38.14393.2068.0
  npmPackages:
    vue: ^2.5.2 => 2.5.16
    vue-hot-reload-api: ^2.2.4 => 2.3.0
    vue-html-loader: ^1.2.3 => 1.2.4
    vue-loader: ^13.5.0 => 13.7.1
    vue-router: ^3.0.1 => 3.0.1
    vue-style-loader: ^3.0.3 => 3.1.2
    vue-template-compiler: ^2.2.1 => 2.5.16
    vue-template-es2015-compiler:  1.6.0
    vuex: ^2.2.1 => 2.5.0
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
yarn install
yarn run serve

### What is expected?
100%

### What is actually happening?
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.                       65% building 866/940 modules 74 active ...les\vux\src\components\sticky\index.vue
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.                       65% building 869/940 modules 71 active ...les\vux\src\components\sticky\index.vue

---
The error message should be that there is a problem in the configuration. There is no solution on the internet. My technical ability can not solve this problem.

**Comment by 410919244** [comment]
删除这一行会报其他错误。
https://segmentfault.com/a/1190000014586699
原因是因为使用了vux

**Comment by sodatea** [comment]
那就是 vux 的问题，请给他们报 bug

**Comment by luojinghui** [comment]
如果使用了prettier组件，请尝试：
yarn add prettier@1.12.1 --save-dev

**Comment by kasaiee** [comment]
What?!?! Dears please write English. I have this issue too :))

**Comment by JohnZengshi** [comment]
> 如果使用了prettier组件，请尝试：
> yarn add prettier@1.12.1 --save-dev

这个可以解决

**Comment by snakeUni** [comment]
> 如果使用了prettier组件，请尝试：
> yarn add prettier@1.12.1 --save-dev

酷

**Comment by sebsastianek** [comment]
please english guys :)

**Comment by Kreeg** [comment]
add 
```parser: 'babel'```
to `.prettierrc` file
