### ISSUE TITLE
开发模式下，vue.config.js 的配置中有没有提供接口获取到 webpack-dev-server 在内存中创建的文件

### ISSUE THREAD

**Issue by DarkoPeng** [vuejs/vue-cli#3364]
### Version
3.3.0

### Environment info
```
略
```

### Steps to reproduce
略

### What is expected?
略

### What is actually happening?
略

---
在vue-cli@2 中，有一种用法是，自定义开发模式下文件的路由（常用于多页面应用）。
```
app.use('*', (req, res, next) => {
    const filename = path.join(compiler.outputPath, 'index.html')
    // webapck提供的outputFileSystem 
    compiler.outputFileSystem.readFile(filename, (err, result) => {
        if (err) {
            return next(err)
        }
        res.set('content-type', 'text/html')
        res.send(result)
        res.end()
    })
})
```
不知道在 vue.config.js 中有没有提供相对应的接口，可以自定义路由访问到内存中存储的文件。

现在想到的是可以在 devServer 的 before 中自定义中间件来自定义路由，但是怎么才能访问到 webapck-dev-server 创建在内存中的文件呢？？？

**Comment by DarkoPeng** [comment]
thank you very much ! My problem has been solved

**Comment by JoyZ1122** [comment]
请问你是怎么解决的呀 我现在也是有个需求需要获取内存中的文件
