### ISSUE TITLE
自定义一个webpack,使用webpack-chain导入的时候，报Cannot find module

### ISSUE THREAD

**Issue by zheNeng** [vuejs/vue-cli#3367]
### What problem does this feature solve?
使用chainWebpack导入一个插件

### What does the proposed API look like?
 chainWebpack: config => {
    if (process.env.NODE_ENV == "production") {
      config.plugin("qiniu").use(qiniuPlugin);    //qiniuPlugin是实例化返回的一个对象
    }
  },
报以下错误
 ERROR  Error loading vue.config.js:
 ERROR  Error: Cannot find module 'qiniu'

<
![image](https://user-images.githubusercontent.com/28520144/51730379-3a8b8380-20b2-11e9-9c88-4a2a6ab3e983.png)
!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by Gong-Elory** [comment]
same with you
