### ISSUE TITLE
使用tsx文件时，Chrome Debugger 似乎无法正常识别生成的map文件

### ISSUE THREAD

**Issue by kissYou** [vuejs/vue-cli#3369]
### Version
3.3.0

### Reproduction link
[https://github.com/kissYou/vue-cli-bug-repro1](https://github.com/kissYou/vue-cli-bug-repro1)

### Environment info
```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  Binaries:
    Node: 8.11.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1、下载重现，并在Chrome浏览器中打开index.html文件
2、打开开发者工具，找到webpack:///./src/App.tsx

### What is expected?
其他文件如ts的map在Chrome的开发工具里显示为彩色，并且打断点时，鼠标悬停在变量上会有智能提示。。。

### What is actually happening?
tsx文件的map无法实现期望结果

---
Chrome 版本 71.0.3578.98（正式版本） （64 位）
先提前感谢你们提供的帮助。

**Comment by sodatea** [comment]
![image](https://user-images.githubusercontent.com/3277634/51753623-2ddc4f00-20f5-11e9-8373-0c9288d1bd48.png)
在 macOS 10.14.2, Chrome 71.0.3578.98 下无法复现

**Comment by kissYou** [comment]
> ![image](https://user-images.githubusercontent.com/3277634/51753623-2ddc4f00-20f5-11e9-8373-0c9288d1bd48.png)
> 在 macOS 10.14.2, Chrome 71.0.3578.98 下无法复现

嗯,可能是window的问题(window 10 下的情况)
![image](https://user-images.githubusercontent.com/7747700/51779327-9cdf9500-2141-11e9-93f6-96d683fd7569.png)

**Comment by kissYou** [comment]
发现QQ浏览器没这个问题,所以应该不是vue-cli的问题，关闭该问题
