### ISSUE TITLE
Extraneous instruction when generating in the current directory

### ISSUE THREAD

**Issue by stephaner** [vuejs/vue-cli#337]
Hello,
I just noticed that when generating a project in the current directory (see highlighting in the shell log below), the "To get started" instruction still instruct to cd in the current directory, which is not needed and doesn't work. See log here for reproducing the issue:

```shell
0> vue-init webpack

? Generate project in current directory? Yes
  This will install Vue 2.x version of the template.

  For Vue 1.x use: vue init webpack#1.0 

? Project name vue-init-dir
? Project description A Vue.js project
? Author Stephane Rodet
? Vue build standalone
? Install vue-router? No
? Use ESLint to lint your code? No
? Setup unit tests with Karma + Mocha? No
? Setup e2e tests with Nightwatch? No

   vue-cli · Generated "vue-init-dir".

   To get started:
   
     cd vue-init-dir
     npm install
     npm run dev
   
   Documentation can be found at https://vuejs-templates.github.io/webpack

0> ls
README.md	config		package.json	static
build		index.html	src
0> cd vue-init-dir
bash: cd: vue-init-dir: No such file or directory
```

I use currently node 6.8.0 and vue-cli 2.8.1.

**Comment by posva** [comment]
Thanks for pointing it out.
The completeMessage was simply not tweaked for it. I created a PR to fix that.
Next time, please open the issue on the relevant template repository

**Comment by stephaner** [comment]
@posva thanks for the quick response - I had missed that this is part of the template, sorry for that.
