### ISSUE TITLE
cli-plugin-unit-mocha overwrites webpack mode in NODE_ENV=test

### ISSUE THREAD

**Issue by jdoubleu** [vuejs/vue-cli#3370]
### Version
3.3.0

### Reproduction link
[https://github.com/jdoubleu/vue-cli-plugin-unit-mocha-bug](https://github.com/jdoubleu/vue-cli-plugin-unit-mocha-bug)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14.x
    CPU: n/a
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Firefox: 64.0.2
    Safari: 12.0.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2 
    @vue/babel-preset-app:  3.3.0 
    @vue/babel-preset-jsx:  1.0.0-beta.2 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2 
    @vue/babel-sugar-inject-h:  1.0.0-beta.2 
    @vue/babel-sugar-v-model:  1.0.0-beta.2 
    @vue/babel-sugar-v-on:  1.0.0-beta.2 
    @vue/cli-overlay:  3.3.0 
    @vue/cli-plugin-babel: ^3.0.5 => 3.3.0 
    @vue/cli-plugin-eslint: ^3.0.5 => 3.3.0 
    @vue/cli-plugin-unit-mocha: ^3.3.0 => 3.3.0 
    @vue/cli-service: ^3.0.5 => 3.3.1 
    @vue/cli-shared-utils:  3.3.0 
    @vue/component-compiler-utils:  2.5.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/test-utils: ^1.0.0-beta.20 => 1.0.0-beta.28 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    babel-plugin-transform-vue-jsx:  4.0.1 
    eslint-plugin-vue: ^5.0.0 => 5.1.0 
    vue: ^2.5.21 => 2.5.22 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.1 
    vue-loader:  15.6.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.5.22 
    vue-template-es2015-compiler:  1.8.2 
  npmGlobalPackages:
    @vue/cli: 3.3.0
```

### Steps to reproduce
1. Set NODE_ENV to test (e.g. `export NODE_ENV=test`)
2. Run `npm run serve`

### What is expected?
The served app is built under the testing environment. No errors are shown.

### What is actually happening?
A blank page is shown.

The developer console logs:
```
ReferenceError: require is not defined
	url
external "url":1
__webpack_require__
bootstrap:19
./node_modules/webpack-dev-server/client/index.js?http://192.168.2.107:8080/sockjs-node/<
client:6
./node_modules/webpack-dev-server/client/index.js?http://192.168.2.107:8080/sockjs-node
client:1
__webpack_require__
bootstrap:19
0
http://localhost:8080/app.js:18470:1
__webpack_require__
bootstrap:19
<anonymous>
bootstrap:83
<anonymous>
http://localhost:8080/app.js:1:11
```

---
Whenever the `NODE_ENV` is set to `test` the `cli-plugin-unit-mocha` [sets webpack's target to `node`](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-unit-mocha/index.js#L3-L7).

This might be required for unit tests but it conflicts with all other commands.

It is not uncommon to have the `NODE_ENV` set to `test` in any CI. Although running the `serve` command in a testing environment is uncommon, running [`cli-plugin-e2e-cypress`](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-e2e-cypress) in CI isn't.

### Workaround
In [`vue.config.js`](https://github.com/jdoubleu/vue-cli-plugin-unit-mocha-bug/blob/master/vue.config.js) you can utilize the `chainWebpack` option:
```javascript
module.exports = {
    chainWebpack: webpackConfig => {
        // When FIX_BUG is set in env, apply this workaround.
        // Alternatively one could check the process.env.npm_lifecycle_event (e.g. process.env.npm_lifecycle_event !== 'test:unit').
        // However this only works when run via `npm run test:unit`
        if (process.env.NODE_ENV === 'test' && process.env.FIX_BUG) {
            // Revert changes made by vue-cli-plugin-unit-mocha
            // @see https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-unit-mocha/index.js#L3-L18
            webpackConfig.target(undefined)

            webpackConfig.module
                .rule('vue')
                .use('vue-loader')
                .tap(options => {
                    options.optimizeSSR = true
                    return options
                })
        }
    }
}
```

**Comment by LinusBorg** [comment]
> It is not uncommon to have the NODE_ENV set to test in any CI. 

It may not be uncommon, but I'd argue it's not a good idea. E.g.: How would you build&deploy for production with `NODE_ENV` set to `test`? Mot setups, Vue CLI 3 included, rely on `NODE_ENV=production` to build for production. Your config makes that impossible.

`NODE_ENV` should be set per command, in my opinion. not for the CI environment as a whole.

**Comment by jdoubleu** [comment]
Okay, I agree, `NODE_ENV=test` is not a good option for most tasks.

In my build jobs I overwrote `NODE_ENV` with `production`.

However when running `vue-cli-service test:unit` it [sets `process.env.NODE_ENV` to `test`](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-unit-mocha/index.js#L82) so that I can use this inside my application. But when running [`cli-plugin-e2e-cypress`](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-e2e-cypress) I cannot detect a testing environment.

Normally an integration/e2e test should only test a production build.
In my case I need to extend the `vue-router` so that I can access certain "hidden" components with cypress.

One option would be to set a `VUE_APP_IS_E2E_TESTING` variable, so that I can implement a switch inside my router, but it would not be consistent with the unit tests.

**Comment by LinusBorg** [comment]
You can use a customer mode for running e2e with additional env vars (see the docs i already linked

**Comment by n1ywb** [comment]
This behavior is harmful. Serving node targeted JS to the browser should _never_ happen. At least bail out with an error. I just wasted days trying to figure out why it was serving me broken javascript.
