### ISSUE TITLE
npm run build occur deprecated message

### ISSUE THREAD

**Issue by radicalviva** [vuejs/vue-cli#338]
when I run `npm run build`, it occurs 
### fallbackLoader option has been deprecated - replace with "fallback" loader option has been deprecated - replace with "use"
many lines
any suggestions?

**Comment by egoist** [comment]
https://github.com/vuejs-templates/webpack/pull/490

**Comment by radicalviva** [comment]
I have upgrade `extract-text-webpack-plugin` to `^2.0.0-rc.3`, but this message still occurs

**Comment by posva** [comment]
You have to upgrade the config as in the PR.
Next time, please, open the issue in the relevant template repro instead
