### ISSUE TITLE
vue-cli3 打包后生成的chunk-vendors还包含有es6语法 如箭头函数等

### ISSUE THREAD

**Issue by lianghw** [vuejs/vue-cli#3385]
### Version
3.3.0

### Reproduction link
[https://github.com/lianghw/vue-cli3-test.git](https://github.com/lianghw/vue-cli3-test.git)

### Environment info
```
npm run build
```

### Steps to reproduce
npm run build

### What is expected?
具体打包配置文档细节  太多黑盒，文档描述太多简单

### What is actually happening?
能够在打包文件中排除es6 代码

---
https://bcommuat.aghcdn.com/static/js/chunk-vendors.682d6d30.js 这是线上发布的一个工程打包出来的实际代码 里面包含=> 等...

重新链接里 一个测试仓库 build后可以查看到问题

**Comment by sodatea** [comment]
```bash
npm i -D @vue/cli-plugin-babel
```
或者
```bash
vue add @vue/cli-plugin-babel
```

**Comment by lianghw** [comment]
并没什么软用啊 ....... ！！！！！

**Comment by anrananran** [comment]
为啥就不能默认编译全部依赖呢？不是说开箱即用吗
