### ISSUE TITLE
lighthouse causes vue-template-compiler dependency error

### ISSUE THREAD

**Issue by steveworkman** [vuejs/vue-cli#3394]
### Version
3.3.0

### Reproduction link
[https://github.com/steveworkman/vue-cli-bug-repo](https://github.com/steveworkman/vue-cli-bug-repo)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 11.8.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: Not Found
    Safari: 12.0.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.3.0
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.3.0
    @vue/cli-plugin-babel: ^3.3.0 => 3.3.0
    @vue/cli-plugin-eslint: ^3.3.0 => 3.3.0
    @vue/cli-service: ^3.3.0 => 3.3.1
    @vue/cli-shared-utils:  3.3.0
    @vue/component-compiler-utils:  2.5.1
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    babel-plugin-transform-vue-jsx:  4.0.1
    eslint-plugin-vue: ^5.0.0 => 5.1.0
    vue: ^2.5.21 => 2.5.22
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.6.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.5.22
    vue-template-es2015-compiler:  1.8.2
  npmGlobalPackages:
    @vue/cli: 3.3.0
```

### Steps to reproduce
- Create a new app using the Vue CLI, choose custom preset. Pick the defaults, but choose to put config in dedicated config files.
- Test it with `npm run serve` and it works
- Add a webpack plugin, for example, webpack-lighthouse-plugin
- `npm i -D webpack-lighthouse-plugin`
- `touch vue.config.js`
- Add the following basic configuration
```js
const WebpackLighthousePlugin = require("webpack-lighthouse-plugin");
module.exports = {
  configureWebpack: {
    plugins: [
      new WebpackLighthousePlugin({
        url: "http://localhost:8080"
      })
    ]
  }
};
```
- run `npm run serve`

### What is expected?
The app starts as normal, Lighthouse also starts up and runs an audit

### What is actually happening?
```
 vue-cli-service serve

 INFO  Starting development server...
 10% building 1/1 modules 0 active(node:50717) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 98% after emitting unnamed compat plugin

 ERROR  Failed to compile with 2 errors                                                                                                                                             15:48:17

Module Error (from ./node_modules/vue-loader/lib/index.js):
[vue-loader] vue-template-compiler must be installed as a peer dependency, or a compatible compiler implementation must be passed via options.

Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/steveworkman/code/preset-test/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/Users/steveworkman/code/preset-test/node_modules/vue-loader/lib/index.js:67:22)
```

---
This can also happen when no additional plugins are passed in with the configureWebpack option, it seems to be the webpack-merge process that is changing the config into a state that causes `vue-template-compiler` to be a dependency issue

**Comment by sodatea** [comment]
It's caused by `lighthouse` in the dependency chain - it mocked the `window` object globally but failed to do it correctly, thus breaking `vue-template-compiler` https://github.com/vuejs/vue/blob/v2.5.22/src/core/util/env.js#L10
which in turn triggered this warning https://github.com/vuejs/vue-loader/blob/fdd033801fa0512ebf9673f5809768cf97213f71/lib/index.js#L18-L30

**Comment by steveworkman** [comment]
Closed in https://github.com/addyosmani/webpack-lighthouse-plugin/issues/15

**Comment by Juljan** [comment]
I had this issue and the only solution I found was to force the version of vue and vue-template-compiler to be the same in my package.json, without the leading `^` :
```
        "vue": "2.5.16",
        "vue-template-compiler": "2.5.16",
 ```
Hope it can help someone :-)

**Comment by gersonm91** [comment]
> I had this issue and the only solution I found was to force the version of vue and vue-template-compiler to be the same in my package.json, without the leading `^` :
> 
> ```
>         "vue": "2.5.16",
>         "vue-template-compiler": "2.5.16",
> ```
> 
> Hope it can help someone :-)

thank you so much. Had to update vue and vue-template-compiler to 2.6.10.
