### ISSUE TITLE
[3.4.0] eslint error in project creation

### ISSUE THREAD

**Issue by DRoet** [vuejs/vue-cli#3395]
### Version
3.4.0

### Reproduction link
[http://seebelow](http://seebelow)

### Environment info
```
 System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 11.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmGlobalPackages:
    @vue/cli: Not Found

vue --version gives 3.4.0 so im not sure why it says Not Found above^^
```

### Steps to reproduce
? Please pick a preset: Manually select features
? Check the features needed for your project: **Babel, Router, Vuex, CSS Pre-processors, Linter**
? Use history mode for router? (Requires proper server setup for index fallback in production) **Yes**
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): **Sass/SCSS (with dart-sass)**
? Pick a linter / formatter config: **Standard**
? Pick additional lint features: (Press <space> to select, <a> to toggle all, <i> to invert selection)**Lint on save**
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? **In dedicated config files**

### What is expected?
New project is created

### What is actually happening?
Project creation fails and throws an error about @vue/cli-plugin-eslint

---
⚙  Installing CLI plugins. This might take a while...

npm ERR! code ETARGET
npm ERR! notarget **No matching version found for @vue/cli-plugin-eslint@^3.4.0**
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'testproject'

**Comment by sodatea** [comment]
It is present on npm: https://www.npmjs.com/package/@vue/cli-plugin-eslint
So it might be caused by your npm cli / registry cache
