### ISSUE TITLE
vue create project fails

### ISSUE THREAD

**Issue by elmer120** [vuejs/vue-cli#3396]
### Version
3.4.0

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 AMD FX(tm)-8150 Eight-Core Processor
  Binaries:
    Node: 11.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 40.15063.674.0
  npmPackages:
    @vue/cli:  3.4.0
    @vue/cli-shared-utils:  3.4.0
    @vue/cli-ui:  3.4.0
    @vue/cli-ui-addon-webpack:  3.4.0
    @vue/cli-ui-addon-widgets:  3.4.0
    vue:  2.5.22
    vue-cli-plugin-apollo:  0.19.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
windows 10 1709
install node.js 11.09 - same error with LTS
- run cmd  
- npm install vue
- npm install -g @vue/cli
- vue create project

### What is expected?
create a new project

### What is actually happening?
✨  Creating project in D:\xammp7.2\htdocs\t\t.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://registry.npmjs.org/@vue%2fcli-service failed, reason: connect ETIMEDOUT 104.16.20.35:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Elmer\AppData\Roaming\npm-cache\_logs\2019-01-31T21_11_50_076Z-debug.log
 ERROR  command failed: npm install --loglevel error

---
I not have a proxy,

https://registry.npmjs.org/@vue%2fcli-service run in browser
http://registry.npmjs.org/@vue%2fcli-service run in browser

 I have win 10 version 1709.

I have remove and purge node.js some times = same result.

**Comment by LinusBorg** [comment]
I'm sorry this is not working for you, but according to the error message, this is an error directly in npm. so as far as we can tell, it can#t really be caused by Vue CLI calling npm or anything.

**Comment by elmer120** [comment]
But if i can install another packages, like npm install uikit then npm work correcty.
Cannot help me?

**Comment by dousybox** [comment]
I try to link your report IP adress `104.16.20.35`, found out it belongs to [`Cloudflare`](https://www.cloudflare.com/).

few years ago someone has the same problem with you in https://github.com/yarnpkg/yarn/issues/944.

Your situation most probably because of this https://github.com/yarnpkg/yarn/issues/944#issuecomment-272776984

**Comment by dousybox** [comment]
> But if i can install another packages, like npm install uikit then npm work correcty.
> Cannot help me?

I try to link your report IP adress `104.16.20.35`, found out it belongs to [`Cloudflare`](https://www.cloudflare.com/).

few years ago someone has the same problem with you in https://github.com/yarnpkg/yarn/issues/944.

Your situation most probably because of this https://github.com/yarnpkg/yarn/issues/944#issuecomment-272776984

**Comment by dousybox** [comment]
I find some mistake of your ***Environment info*** 

```
npmPackages:
    @vue/cli:  3.4.0
    @vue/cli-shared-utils:  3.4.0
    @vue/cli-ui:  3.4.0
    @vue/cli-ui-addon-webpack:  3.4.0
    @vue/cli-ui-addon-widgets:  3.4.0
    vue:  2.5.22
    vue-cli-plugin-apollo:  0.19.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

Your cli is install as a local packge, not a global package.
