### ISSUE TITLE
Add a way to contain non-js files inside outputDir

### ISSUE THREAD

**Issue by Danon** [vuejs/vue-cli#3413]
### What problem does this feature solve?
I want my folder `public` to contain some unrelated files (`index.php`, `.htaccess`, `favicon.ico`, `robots.txt`) and my `vue-cli-service` built files (`/js/app.13314234.js` and `/css/app.13314234.css`).

My vue.config.js looks like this
```js
module.exports = {
    outputDir: '../../public/build',
    indexPath: 'some.index.html'
};
```
And js and css are built into `/public/build/js/app.13314234.js` and `/public/build/css/app.13314234.css` but, into the generated some.index.html, only paths `/js/app.13314234.js` and `/css/app.13314234.css` are injected (without the build) file.

I could specify
```js
    outputDir: '../../public', 
```
but then `/public` folder will be cleared of my files I want to keep.
I could use flag `--no-clean`, but then the `/js` and `/css` folders will contain older versions of built js and css, which I don't want.

Is there a way to add a prefix, to the webpack injecting js/css to inject it with a prepended path?

### What does the proposed API look like?
Add an entry to the vue.config.js to add a prefixed path, which will be used to generate paths injected into indexPath

**Comment by LinusBorg** [comment]
Unless I missunderstand you, all you have to do is to set the `publicPath` to `/build` when building for production in `vue.config.js`:
```javascript
publicpath: process.env.NODE_ENV === 'production' ? '/build' : undefined
```

That would prefix paths in your built files to go to `/build/css/app.13314234.css` etc.

If that's not what you want, please clarify

**Comment by Danon** [comment]
I'll try it when I'm home.

Thank you for your answer :)

niedz., 3 lut 2019, 14:05: Thorsten Lünborg <notifications@github.com>
napisał(a):

**Comment by Danon** [comment]
Yes, that was exactly it! :)

Sorry for bothering you :/
