### ISSUE TITLE
vue upgrade does not work

### ISSUE THREAD

**Issue by ffxsam** [vuejs/vue-cli#3417]
### Version
3.4.0

### Environment info
```

Environment Info:

  System:
    OS: macOS 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: Not Found
    Safari: 12.0.3
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2 
    @vue/babel-preset-app:  3.4.0 
    @vue/babel-preset-jsx:  1.0.0-beta.2 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2 
    @vue/babel-sugar-inject-h:  1.0.0-beta.2 
    @vue/babel-sugar-v-model:  1.0.0-beta.2 
    @vue/babel-sugar-v-on:  1.0.0-beta.2 
    @vue/cli-overlay:  3.4.0 
    @vue/cli-plugin-babel: ^3.4.0 => 3.4.0 
    @vue/cli-plugin-eslint: ^3.4.0 => 3.4.0 
    @vue/cli-service: ^3.4.0 => 3.4.0 
    @vue/cli-shared-utils:  3.4.0 
    @vue/component-compiler-utils:  2.5.2 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.1.0 
    vue: ^2.5.22 => 2.6.0 
    vue-eslint-parser:  4.0.3 
    vue-hot-reload-api:  2.3.1 
    vue-loader:  15.6.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.0 
    vue-template-es2015-compiler:  1.8.2 
  npmGlobalPackages:
    @vue/cli: 3.4.0


```

### Steps to reproduce
1. vue create myproj
2. cd myproj
3. vue upgrade

### What is expected?
Upgrade should work.

### What is actually happening?
Even after following the instructions and globally installing `@vue/cli-upgrade`, I get the same message instructing me to install the package.

**Comment by krave1986** [comment]
I have the same problem. No matter how you try, it will always told you to install @vue/cli-upgrade instead of upgrading.

**Comment by douglasg14b** [comment]
And news on this? This is pretty frustrating....

**Comment by LinusBorg** [comment]
The upgrde functionality was added unofficially to test it out. It's not a documented feature yet.

We will revamp it a bit, hopefully within March.

**Comment by iuliuscaesar92** [comment]
The same story. Nothing changed in that time?

**Comment by lpj145** [comment]
not a solution ?

**Comment by brikoleur** [comment]
This still does not work. Vue-cli version 3.11.0, OS X. I get 

```
Command vue upgrade requires a global addon to be installed.  
Please run npm install -g @vue/cli-upgrade and try again.
```

@vue/cli-upgrade is installed and also at 3.11.0.

**Comment by grufelous** [comment]
I have the same issue. I am using vue-cli v3.11.0 on Windows 10 (1903).  Vue **has** been installed globally with `vue install -g @vue/cli`.

`Environment Info:                                                                                                                                                                                                                                 
System:                                                                                                                   OS: Windows 10                                                                                                          CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz                                                                 Binaries:                                                                                                                 Node: 12.9.1 - C:\nodejs\node.EXE                                                                                       Yarn: Not Found                                                                                                         npm: 6.10.2 - C:\nodejs\npm.CMD                                                                                       Browsers:                                                                                                                 Edge: 44.18362.329.0                                                                                                  npmGlobalPackages:                                                                                                        @vue/cli: Not Found`

**Comment by sodatea** [comment]
I still don't know what stops `vue upgrade` from working properly in v3.
But anyway, in Vue CLI v3, it does nothing more than invoking `npm update` or `yarn upgrade` underlyingly for `@vue/cli-service` & `@vue/cli-plugin-*` packages. So I recommend you to use these commands instead.
BTW, `yarn upgrade-interactive` has a nice user interface.
