### ISSUE TITLE
`vue create`d app does not work in IE11

### ISSUE THREAD

**Issue by mismith** [vuejs/vue-cli#3419]
### Version
3.4.0

### Environment info
```
 System:
    OS: macOS 10.14.2
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 8.14.0 - ~/.nvm/versions/node/v8.14.0/bin/node
    Yarn: 1.13.0 - ~/.yarn/bin/yarn
    npm: 6.6.0 - ~/.nvm/versions/node/v8.14.0/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 64.0
    Safari: 12.0.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2 
    @vue/babel-preset-app:  3.4.0 
    @vue/babel-preset-jsx:  1.0.0-beta.2 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2 
    @vue/babel-sugar-inject-h:  1.0.0-beta.2 
    @vue/babel-sugar-v-model:  1.0.0-beta.2 
    @vue/babel-sugar-v-on:  1.0.0-beta.2 
    @vue/cli-overlay:  3.4.0 
    @vue/cli-plugin-babel: ^3.4.0 => 3.4.0 
    @vue/cli-plugin-typescript: ^3.4.0 => 3.4.0 
    @vue/cli-service: ^3.4.0 => 3.4.0 
    @vue/cli-shared-utils:  3.4.0 
    @vue/component-compiler-utils:  2.5.2 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    typescript: ^3.0.0 => 3.3.1 
    vue: ^2.5.22 => 2.6.0 
    vue-hot-reload-api:  2.3.1 
    vue-loader:  15.6.2 
    vue-router: ^3.0.1 => 3.0.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.0 
    vue-template-es2015-compiler:  1.8.2 
    vuex: ^3.0.1 => 3.1.0 
  npmGlobalPackages:
    @vue/cli: 3.4.0

```

### Steps to reproduce
1. Run `vue create test`, and select the following options:
```
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, TS, Router, Vuex, Linter
? Use class-style component syntax? No
? Use Babel alongside TypeScript for auto-detected polyfills? Yes
? Use history mode for router? (Requires proper server setup for index fallback in production)
 No
? Pick a linter / formatter config: TSLint
? Pick additional lint features: 
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In package.json
? Save this as a preset for future projects? No
```

2. `cd test`
3. `npm i -g http-server`
4. `yarn build`
5. `http-server ./dist/`
6. In IE11, open `localhost:8080` (or whatever port it launches on)

### What is expected?
App should load in IE11

### What is actually happening?
Blank white page, with console errors resulting from transpilation 'issues'/stuff that IE11 doesn't understand, e.g. "Object doesn't support this property or method" and
"Expected identifier, string or number"

---
I have no provided a minimal reproduction since I have made zero edits to the output from @vue/cli.

That said, I have tried configuring a number of polyfills, babel plugins, various flags/options, etc to get the transpilation to output code that will work in shitty IE11, but have come up unsuccessful in all my attempts.

**Comment by LinusBorg** [comment]
You really should provide a reproduction, because vue CLI does work in IE11 by default, so it's likely that something went wrong when you created the project.

**Comment by mismith** [comment]
Fair enough, here is one: https://github.com/mismith/vue-cli-babel-test

I really hope it's something on my end, because I would have for you guys to have to dig around in IE11 too.

**Comment by mismith** [comment]
And here's a screenshot of how IE11 (failingly) loads the page:
<img width="1031" alt="screen shot 2019-02-04 at 2 53 53 pm" src="https://user-images.githubusercontent.com/638816/52239917-cc527800-288c-11e9-8253-202872f31c03.png">

**Comment by mismith** [comment]
I've now included the `dist/` output in that repo, which includes at least one instance of transpiled code that IE11 can't handle, e.g. https://github.com/mismith/vue-cli-babel-test/blob/master/dist/js/chunk-vendors.a8633657.js -- search file for `default:`

**Comment by LinusBorg** [comment]
Your screenshot days that IE is running in `Browser mode: IE8`.

Vue only supports IE>=9

**Comment by mismith** [comment]
Wow, was using the wrong VM/browser entirely.

So sorry to bother you! https://i.giphy.com/media/UPHDrXTD2tNni/200w.webp
