### ISSUE TITLE
Single dependency like create-react-app does it

### ISSUE THREAD

**Issue by Hurtak** [vuejs/vue-cli#342]
Hi,

are there any plans/discussion to move to single dependency structure, like create-react-app does it?

**Comment by posva** [comment]
I suppose you wanted to open the issue in the https://github.com/vuejs-templates/webpack repository instead, you should open an issue **in the relevant template repo**. I don't think there're plans for that but feel free to share your thoughts (on the new issue) about why it should be done

**Comment by kincaidoneil** [comment]
@Hurtak If you have `vue-cli` as a single dependency, the [`vue build` command](https://github.com/vuejs/vue-cli/blob/master/docs/build.md) replicates the functionality of create-react-app (and even goes beyond it with CSS preprocessor support!)
