### ISSUE TITLE
Template caching

### ISSUE THREAD

**Issue by iatsiuk** [vuejs/vue-cli#343]
I would like to introduce more *standard-friendly* folder for storing template files and make PR with the necessary changes. Are you guys interested in it?

```js
var os = require('os');
var path = require('path');

function cacheDir() {
  var platforms = {
    'win32': function() {
      return process.env.APPDATA ?
             path.join(process.env.APPDATA, 'Local') :
             os.tmpdir();
    },
    'linux': function() {
      return process.env.XDG_CACHE_HOME || path.join(os.homedir(), '.cache');
    },
    'darwin': function() {
      return path.join(os.homedir(), 'Library/Caches');
    },
    'default': function() {
      return os.tmpdir();
    }
  }

  return (platforms[os.platform()] || platforms['default'])();
}
```

**Comment by yyx990803** [comment]
tmpdirs are cleaned up on system reboot, no? I think the offline feature needs the cached templates to be persisted?

**Comment by posva** [comment]
I think it's much easier to have the same dir across all OS even if it's not standard. If you ever have a cache issue you can use the same command to clean it

**Comment by iatsiuk** [comment]
> tmpdirs are cleaned up on system reboot, no?

@yyx990803 Well, my example uses os.tmpdir() method only for uncommon platforms like 'freebsd'. All other folders are widely used for persistent storage of application's cache. Just have a look how ugly cache folder are on Windows:

![screen](https://cloud.githubusercontent.com/assets/24681814/23093096/1c8cd258-f5f3-11e6-90e7-75b4f9585987.png)

> If you ever have a cache issue you can use the same command to clean it

@posva I can't use the same command because commands are different for windows and linux platforms. All platforms has own rules for storage of this data type and cli utils should respect that.

**Comment by egoist** [comment]
Maybe change it to `process.env.LOCALAPPDATA` on windows if needed

**Comment by iatsiuk** [comment]
I'll be very grateful if you move cache folder to `~/.cache` on linux as well.

**Comment by posva** [comment]
@iatsiuk Who cares about an _ugly_ directory tree... You can hide them if you want.

> @posva I can't use the same command because commands are different for windows and linux platforms. All platforms has own rules for storage of this data type and cli utils should respect that.

Actually, yes you can, it depends on the command. The point was that the folder being the same across different OS makes it easy to deal with any cache-related issue Because it doesn't matter where you are, you know what folder to deal with.

Therefore, having different cache dirs is a downside.

What are the benefits of such rules?
