### ISSUE TITLE
Handlebars-loader is not working

### ISSUE THREAD

**Issue by ekvilon** [vuejs/vue-cli#3430]
### Version
3.4.0

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.4.0
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.4.0
    @vue/cli-plugin-babel: ^3.4.0 => 3.4.0
    @vue/cli-plugin-eslint: ^3.4.0 => 3.4.0
    @vue/cli-service: ^3.4.0 => 3.4.0
    @vue/cli-shared-utils:  3.4.0
    @vue/component-compiler-utils:  2.5.2
    @vue/eslint-config-airbnb: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.1.0
    vue: ^2.5.22 => 2.6.2
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.6.2
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.2
    vue-template-es2015-compiler:  1.8.2
    vuex: ^3.0 => 3.1.0
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
- Install raw and handlebars loaders
- Write vue.config.js
- Write any single file component
- Try

### What is expected?
`<template lang="hbs">` in .vue file is handled correctly

### What is actually happening?
I got error on running vue-cli-service serve :
 ERROR  Failed to compile with 1 errors                                               23:40:43

 error  in ./src/views/Home.vue?vue&type=template&id=fae5bece&lang=hbs&

Module Error (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error)

  Errors compiling template:

  text "module.exports = "var Handlebars...

---
vue.config.js content:
```
module.exports = {
  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.hbs$/,
          loader: ["raw-loader", "handlebars-loader"]
        }
      ]
    }
  }
};
```

**Comment by LinusBorg** [comment]
The handlebars loader returns a function that has to be called (with the context for the template), it doesn't return html. 

So it's not really compatible with vue-loader like that. This won't be solvable in vue-cli.

For further help please use forum.vuejs.org or chat.vuejs.org
