### ISSUE TITLE
build fails with NODE_ENV=development

### ISSUE THREAD

**Issue by diego81b** [vuejs/vue-cli#3436]
### Version
3.4.0

### Reproduction link
[https://github.com/diego81b/vue-hello-world](https://github.com/diego81b/vue-hello-world)

### Environment info
```
System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Node: 10.15.1 - C:\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.7.0 - C:\nodejs\npm.CMD
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.4.0
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.4.0
    @vue/cli-plugin-babel: ^3.4.0 => 3.4.0
    @vue/cli-plugin-eslint: ^3.4.0 => 3.4.0
    @vue/cli-plugin-pwa: ^3.4.0 => 3.4.0
    @vue/cli-service: ^3.4.0 => 3.4.0
    @vue/cli-shared-utils:  3.4.0
    @vue/component-compiler-utils:  2.5.2
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.1.0
    vue: 2.6.3 => 2.6.3
    vue-eslint-parser:  4.0.3
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.6.2
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: 2.6.3 => 2.6.3
    vue-template-es2015-compiler:  1.8.2
    vuex: ^3.0.1 => 3.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
 - yarn install
 - yarn build:dev
 - cd dist
 - run a web server ( i use http-server)

### What is expected?
the same dist structure as NODE_ENV=production and running

### What is actually happening?
with --modern: it give me Cannot read property 'webpackHotUpdate' of undefined
without --modern: fails to load service-worker

---
i use 2 custom env
 - .env.production
 - .env.developement

the difference between them is only NODE_ENV
when i run mode --production all works fine

**Comment by LinusBorg** [comment]
1. The result will have a different directory structure in development 
2. Service worker is mocked in development. 
3. I would suspect that the hmr code that is injected in development mode doesn't work well with `<script type=module>`?

So this is mostly expected. Why do you want to build in development mode?

**Comment by diego81b** [comment]
HI @LinusBorg 
1. why the need to have a different structure ? for example 'map' files will looks to js folder that doesn't exists. Seems that index.html is not build / compiled accordlying to env
2. So why the need to copy on dist ?
3. Yes, in developement type module raise that error

The need to build in development is to apply some code condition based on NODE_ENV.
What i really expect is that i shouldn't care about build in each environment if i want standard build
I didn't find any doc that tell me how build process works in different env
how i have learned is that NODE_ENV = development is pretty much useless IMHO

I'm not criticizing i'm trying to understand better what happens behind the scene on build process

thank you very much
best regards

**Comment by LinusBorg** [comment]
> 1. why the need to have a different structure ?

Well, in development, things work differently. As one example, we don't extract CSS in order to be able to hot reload it for individual components. Hence, no *.css files.

> for example 'map' files will looks to js folder that doesn't exists. Seems that index.html is not build / compiled accordlying to env

Not sure what you refer to here.

> So why the need to copy on dist ?

Also not sure what you mean, but when you build, the resulting files are output into `/dist`. What's strange about that?

> The need to build in development is to apply some code condition based on NODE_ENV.

Again, I'm not sure what specific problem you are trying to solve. But it *sounds* like you actually want to do a build that behaves like a production build for the most part, but does a few things differently?

Maybe you just want to do a variation of the `staging` example in [our docs](https://cli.vuejs.org/guide/mode-and-env.html#modes)? You could add another env variable for that new mode and use that to conditionally switch things between "staging" and real production builds

If that doesn't solve your problem, please give a real example of the thing you want to accomplish.

**Comment by diego81b** [comment]
I understand that i'm not focusin on the behavior
What i mean is that if i have NODE_ENV= development i can't serve it from a web server beacuse this is the result:

[with --modern]

![web development](https://user-images.githubusercontent.com/9203744/52537091-ebf11100-2d62-11e9-9f61-f2feffa306e7.PNG)

![dev_service_worker](https://user-images.githubusercontent.com/9203744/52537151-88b3ae80-2d63-11e9-8f54-dcccd69ebac0.PNG)

[without --modern]
i got only the second error

so the questions are:
1. does hmr has problem with type=module ?
2. The script tag for service-worker is created in dist index.html but service-worker is not created in dist so what is the right behavior ?

sorry for my bad english
bye

**Comment by LinusBorg** [comment]
And I'll ask for a third time: why would you want to build a development version and serve it? It's not meant to be done, and I don't see a reason why anyone would want to do that.What is your use case?

You said you want to use `NODE_ENV` to do some behaviour switching or something. I said you should use a different, custom mode for that if you want something like a "staging" mode.

So, asking again: if that's not what you want to do, what is the problem that you are trying to solve by running `build --mode development`?

**Comment by diego81b** [comment]
ok i see,
for the moment i don't have any reason to do that, was just a wrong use of the cli i made

i close the issue
thanks
