### ISSUE TITLE
npm run test Error

### ISSUE THREAD

**Issue by zhangxinxinWTB** [vuejs/vue-cli#344]
vue-cli init webpack testing; cd testing; cnpm install; npm run test;

npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/herely/.nvm/versions/node/v6.9.2/bin/node" "/Users/herely/.nvm/versions/node/v6.9.2/bin/npm" "run" "unit"
npm ERR! node v6.9.2
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testing@1.0.0 unit: `cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testing@1.0.0 unit script 'cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the testing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs testing
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls testing
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/herely/.npm/_logs/2017-02-10T05_51_51_672Z-debug.log

OS: mac osx 10.12.2
node:  6.9.2
npm: 4.2.0
vue-cli: 2.8.1

**Comment by zigomir** [comment]
Seems like you're having an issue with [webpack template](https://github.com/vuejs-templates/webpack). Please report it there.
