### ISSUE TITLE
Cannot navigate in the vue create menus

### ISSUE THREAD

**Issue by kawazoe** [vuejs/vue-cli#3446]
### Version
3.4.0

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 11.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
`npm install -g @vue/cli`

`vue create foobar`

Use the up/down arrow key to navigate.

### What is expected?
I am able to select any options from the menu.

### What is actually happening?
Each time a key is pressed, the selection jumps twice. While it is possible to actually navigate through every selection with quick key presses (there is a slight delay between the selection changes) this is far from usable.

---
I have reproduced this issue on two computers with similar configurations. Same node version, same npm version, both with a clean @vue/cli installation. This happens in PowerShell, the standard command line and the WebStorm terminal window.

**Comment by kieranhoney** [comment]
I'm having the exact same problem. In Powershell it doesn't appear to move. In the regular windows command line it moves down then rubber bands back to option 1. I've found that if I hold the down arrow for a while it will eventually end up on manual options and then continue. I can see when there are more options pressing down actually moves the selection 2 items instead of 1.

**Comment by defunkydrummer** [comment]
I'm having the exact same problem, either in Powershell command line, or in CMD command line.

node --version
v11.9.0

npm -v
6.5.0

Windows 10 [Version 10.0.16299.904]

CLI for VUE was downloaded today through NPM.

**Comment by sodatea** [comment]
https://github.com/SBoudrias/Inquirer.js/issues/778

**Comment by BenHayat** [comment]
Just uninstalled Node V11.x and installed V10.x and everything works.

**Comment by kawazoe** [comment]
Node 11.10.0 fixes this issue.
