### ISSUE TITLE
Support different environment configuration file formats

### ISSUE THREAD

**Issue by adamreisnz** [vuejs/vue-cli#3447]
### What problem does this feature solve?
When you have many environment variables that you need to manage, being restricted to a flat data structure can be cumbersome. It results in overly long variable names (especially since you're forced to use the `VUE_APP_` prefix, makes it hard to find the variable you're looking for when you want to make changes, and can make your code harder to read. Moreover, being restricted to the flat format make it impossible to include any kind of dynamic values, like a git commit revision hash.

### What does the proposed API look like?
In other projects I've worked on, where I've built the build process using Gulp, we were able to specify environment configuration as javascript, and it was loaded as such in the Node environment of the build process.

This allowed you to nest configuration as you saw fit, allowed inclusion of dynamic variables/values, allowed grouping of related configuration, and was much cleaner and easier to read:

```js
const git = import 'git-rev-sync';

export default config = {
  
  //App config
  app: {
    title: 'My app',
    baseUrl: 'https://example.com',
    revision: git.short(),
  },

  //Google analytics
  googleAnalytics: {
    isEnabled: true,
    trackingId: 'UA-XXXXXXX',
    options: {
      //Some nested options
    },
  },

  //Sentry
  sentry: {
    apiKey: 'Some key',
    ignoreErrors: [
      'array',
      'of',
      'values',
    ],
  },

  //Etc
};
```

This can be made accessible as a nested data structure in a convenient, short variable on `process.env`, like `process.env.CFG` (or if you must, `process.env.VUE_APP`).

Some advantages are:

### 1. The app can get a subset of the configuration easily and use it in easy to read chunks:

```
const {isEnabled, trackingId, options} = process.env.CFG.googleAnalytics;

if (isEnabled) {
  GoogleAnalytics.setupTracking(trackingId, options);
}
```

Instead of:

```
if (process.env.VUE_APP_GOOGLE_ANALYTICS_IS_ENABLED) {
  GoogleAnalytics.setupTracking(process.env.VUE_APP_GOOGLE_ANALYTICS_TRACKING_ID, process.env.VUE_APP_GOOGLE_ANALYTICS_OPTIONS);
}
```

This is really hard to read and creates overly long code lines.
So perhaps:

```
const {
  VUE_APP_GOOGLE_ANALYTICS_IS_ENABLED: isEnabled,
  VUE_APP_GOOGLE_ANALYTICS_TRACKING_ID: trackingId,
  VUE_APP_GOOGLE_ANALYTICS_OPTIONS: options,
} = process.env;

if (isEnabled) {
  GoogleAnalytics.setupTracking(trackingId, options);
}
```

But that just seems like a waste of code and unnecessary boilerplate.

### 2. You can embed dynamic values in your config as illustrated above with a git revision example:

```js
  //App config
  app: {
    title: 'My app',
    baseUrl: 'https://example.com',
    revision: git.short(),
  },
```

### 3. The config file is much easier to read and can contain comments
Not sure if Vue's env files can contain comments as well, but regardless, in the english language and most programming languages, you are used to reading from left to right. So when you're looking for something, your eyes automatically go to the first part of a word. This makes trying to find something in the config file a pain in the butt, as you constantly have to fight against the mess of ALL_UNDERSCORED_CAPS which all are prefixed with VUE_APP_.

E.g. to find the "options" config for Google Analytics, your eyes have to scan each line first and get through the `VUE_APP_GOOGLE_ANALYTICS_` part, before it reaches the relevant part `OPTIONS`.

In a javascript config file you can neatly group your configuration, add comments, and avoid unnecessary prefixes for easy visual grepping and categorisation. 

### 4. Allows nested data and arrays
The javascript format is more flexible and allows for nested data and even arrays, rather than just flat, simple values. We often use array values in our environment configuration.

---

Alternatively it would be nice if other formats can also be supported, like YAML. Other software like ESLint allows you to specify your configuration in many different formats, whatever the developer is most comfortable with. 

Working with Vue and the flat, hard to read config files after being used to the dynamic and easy to read structures I used to have in my Angular apps really feels like a step back.

So I would propose perhaps not to replace the current API, but to add support for other formats of env config files.

**Comment by LinusBorg** [comment]
The .env format  is meant for environment variables, really - stuff that you might want to define as real environment variables in a CI / CD system, for example.

It's useful for api paths or apiu keys etc, small but important pieces of info that differ between different environments.

What you want is a config file with a load of stuff to properly config a lot of aspects of your project. environment vairables are indeed not a good place for that, but I would personally just do something like this:

```
let config
if (process.ev.NODE_ENV === 'production') {
  config = require('./config.prod')
} else {
  config = require('./config.dev')
}
```
Done. Can be done in the app itself and/or in the build env, depending on your needs.

Just keep sensitive info (api keys) out of there and use env variables for them for production.

**Comment by adamreisnz** [comment]
I understand where you're coming from, but from our perspective, these things go hand in hand. I want to be able to specify *everything* about our Google Analytics, or Sendgrid, or Mailchimp or Sentry, or whatever integration in one place, because all of it can potentially be environment specific, and I don't want to go hunting for it in two different places.

So it's ideal to have not only API keys in there, but also connection strings and configuration parameters for those same services.

I guess what I could do is use a configuration system like you suggest, and simply read only the sensitive data from `process.env` and mix it in with the config, so that the app doesn't have to access `process.env` vars directly.

I might write a vue package for that then, thanks.

**Comment by adamreisnz** [comment]
By the way another problem this would tackle is that you could define arbitrary config files for arbitrary environments. So spinning up a new environment would be easy. Problem of defining it in runtime in the app is that you can't do dynamic imports with ES6 (e.g. something like you can do with Node: 

```js
const env = process.env.NODE_ENVIRONMENT;
require(`./config/${env}`);
```

**Comment by adamreisnz** [comment]
Another issue that I recalled was that Vue doesn't differentiate between the application environment and the node environment.

For example, some PaaS services do things differently depending on Node environment. But when I have a staging environment that I want to behave exactly as production, except some different API keys/config vars, I won't be able to do it in Vue, because I'd need to specify my NODE_ENVIRONMENT as `staging`, and this would break/not work on some PaaS service providers.

That's why we split up the two concepts and have a separate APP_ENVIRONMENT parameter, which can be used in conjunction with NODE_ENVIRONMENT.

So you NODE_ENVIRONMENT could still be `production` (for build processes etc), but your APP_ENVIRONMENT would be `staging`. 

I don't believe it's possible to distinguish the two in Vue at the moment?

**Comment by LinusBorg** [comment]
> I don't believe it's possible to distinguish the two in Vue at the moment

```
# .env.staging
NODE_ENV=production
VUE_APP_ENV=staging


```

**Comment by adamreisnz** [comment]
Is there a way to access the mode in the Vue app as well, or only the NODE_ENVIRONMENT? The two can be different, but the docs don't specify how to access the mode. Something like process.env.VUE_MODE would be useful.

**Comment by adamreisnz** [comment]
> Edit: did you delete your last comment? I'm confused

Sorry, yes I realised it is possible when I looked at my staging config file, I realised what I needed was the mode, but couldn't find how to access that in the app.

**Comment by adamreisnz** [comment]
It appears `NODE_ENV` reports the **mode**, not the actual NODE_ENV value, so I'll use that to identify the mode.

**Comment by adamreisnz** [comment]
Contrary to what I wrote above, actually it doesn't use the mode in the `process.env.NODE_ENV` var. It will report **production** as the NODE_ENV while running in the **staging** mode. So the documentation on that is definitely incorrect.

**Comment by LinusBorg** [comment]
Please re-read the chapter about modes and show me where it says to use NODE_ENV=staging.

That part doesn't exist. It says to use an env file like i showed you, with NODE_ENV set to one of the main modes: development, production, test

**Comment by adamreisnz** [comment]
Ok, I can understand your point of view, but to me:

> NODE_ENV - this will be one of "development", "production" or "test" depending on the **mode** the app is running in.

Re-reading it, I can see how this can be interpreted in different ways. I interpreted it as `NODE_ENV` will be set to the mode that the app is running in. I imagine quite a few people would interpret it this way.

I would clarify this to emphasize that it will not be set to the actual mode.

Can you tell me how we can access the actual mode in the app itself?
