### ISSUE TITLE
Out-of-the-box build error in registerServiceWorker.ts

### ISSUE THREAD

**Issue by spaasis** [vuejs/vue-cli#3448]
### Version
3.4.0

### Reproduction link
[https://github.com/spaasis/vuecli-test](https://github.com/spaasis/vuecli-test)

### Environment info
```
No output? I just get "Environment Info:" and then nothing.
This is on Windows
```

### Steps to reproduce
Create a new project with everything except E2E testing.
Select TypeScript class notation (and Babel   TS if that matters)

After the setup run `npm run serve`

### What is expected?
The solution builds without errors out of the box

### What is actually happening?
There is a TypeScript error in registerServiceWorker.ts:

```Argument of type '{ ready(): void; registered(): void; cached(): void; updatefound(): void; updated(): void; offline(): void; error(error: Error): void; }' is not assignable to parameter of type 'Hooks'.
  Property 'registrationOptions' is missing in type '{ ready(): void; registered(): void; cached(): void; updatefound(): void; updated(): void; offline(): void; error(error: Error): void; }' but required in type 'Hooks'.```

<!-- generated by vue-issues. DO NOT REMOVE -->

**Comment by LinusBorg** [comment]
Seems to be a bug in the `register-service-worker` package's types.

I'll open an issue there.
 
As a workaround, add this to `registerServiceWorker.js`:
```diff
if (process.env.NODE_ENV === 'production') {
  register(`${process.env.BASE_URL}service-worker.js`, {
+   registerOptions: { scope: './'}
    ready () {
```

**Comment by LinusBorg** [comment]
Did a PR: https://github.com/yyx990803/register-service-worker/pull/24

**Comment by LinusBorg** [comment]
FYI: PR is merged, we're awaiting the release. Once that's out you can get it by deleting your lockfile and running install again.

**Comment by LinusBorg** [comment]
1.6.1 is out with the fixed type definitions.
