### ISSUE TITLE
Feature Request: Custom Configs

### ISSUE THREAD

**Issue by Austio** [vuejs/vue-cli#345]
Hello, I am wanting to create a PR for a small addition and wanted to make sure that it is something that is needed.

Currently the config/index.js only has a configurable ENV variable.  This isn't ideal for running tests while having a dev server running b/c the ports collide.

Proposal:  I would like to create a PR to update the cli to generate a config that merges the entire test/dev in config/index.js for the dev key.  Also webpack will need to be updated to use the exports  correctly.

Please let me know if this is wanted and i'll knock it out.

Thanks!

**Comment by posva** [comment]
Hey, thanks for your interest in vue-cli!
If I understood well, you should open this in the relevant template repository. I suppose it's the webpack one (https://github.com/vuejs-templates/webpack).
The port thing could be useful 🙂
