### ISSUE TITLE
npm ERR! missing script: dev

### ISSUE THREAD

**Issue by tfak** [vuejs/vue-cli#3452]
$ npm run dev
npm ERR! missing script: dev

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\akash\AppData\Roaming\npm-cache\_logs\2019-02-14T08_02_31_477Z-debug.log

**Comment by pcanwar** [comment]
> $ npm run dev
> npm ERR! missing script: dev
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\akash\AppData\Roaming\npm-cache_logs\2019-02-14T08_02_31_477Z-debug.log

you should've take a look on this file Users\akash\AppData\Roaming\npm-cache_logs\2019-02-14T08_02_31_477Z-debug.log
