### ISSUE TITLE
多页和单页混合开发这种方式目前的vue-cli3.0好像还不支持

### ISSUE THREAD

**Issue by 948911908** [vuejs/vue-cli#3465]
### Version
3.4.0

### Reproduction link
[System:     OS: Windows 10     CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   Binaries:     Node: 10.15.1 - C:\Program Files\nodejs\node.EXE     Yarn: Not Found     npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD   Browsers:     Edge: 41.16299.15.0   npmPackages:     @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2     @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2     @vue/babel-preset-app:  3.4.0     @vue/babel-preset-jsx:  1.0.0-beta.2     @vue/babel-sugar-functional-vue:  1.0.0-beta.2     @vue/babel-sugar-inject-h:  1.0.0-beta.2     @vue/babel-sugar-v-model:  1.0.0-beta.2     @vue/babel-sugar-v-on:  1.0.0-beta.2     @vue/cli-overlay:  3.4.0     @vue/cli-plugin-babel: ^3.4.0 => 3.4.0     @vue/cli-plugin-eslint: ^3.4.0 => 3.4.0     @vue/cli-service: ^3.4.0 => 3.4.0     @vue/cli-shared-utils:  3.4.0     @vue/component-compiler-utils:  2.5.2     @vue/preload-webpack-plugin:  1.1.0     @vue/web-component-wrapper:  1.2.0     babel-helper-vue-jsx-merge-props:  2.0.3     eslint-plugin-vue: ^5.0.0 => 5.2.1 (5.2.1)     vue: ^2.5.22 => 2.6.6     vue-awesome-swiper: ^3.1.3 => 3.1.3     vue-eslint-parser:  5.0.0 (5.0.0)     vue-hot-reload-api:  2.3.2     vue-loader:  15.6.2     vue-router: ^3.0.1 => 3.0.2     vue-style-loader:  4.1.2     vue-template-compiler: ^2.5.21 => 2.6.6     vue-template-es2015-compiler:  1.8.2     vue-video-player: ^5.0.2 => 5.0.2     vuex: ^3.0.1 => 3.1.0   npmGlobalPackages:     @vue/cli: Not Found](System:     OS: Windows 10     CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   Binaries:     Node: 10.15.1 - C:\Program Files\nodejs\node.EXE     Yarn: Not Found     npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD   Browsers:     Edge: 41.16299.15.0   npmPackages:     @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2     @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2     @vue/babel-preset-app:  3.4.0     @vue/babel-preset-jsx:  1.0.0-beta.2     @vue/babel-sugar-functional-vue:  1.0.0-beta.2     @vue/babel-sugar-inject-h:  1.0.0-beta.2     @vue/babel-sugar-v-model:  1.0.0-beta.2     @vue/babel-sugar-v-on:  1.0.0-beta.2     @vue/cli-overlay:  3.4.0     @vue/cli-plugin-babel: ^3.4.0 => 3.4.0     @vue/cli-plugin-eslint: ^3.4.0 => 3.4.0     @vue/cli-service: ^3.4.0 => 3.4.0     @vue/cli-shared-utils:  3.4.0     @vue/component-compiler-utils:  2.5.2     @vue/preload-webpack-plugin:  1.1.0     @vue/web-component-wrapper:  1.2.0     babel-helper-vue-jsx-merge-props:  2.0.3     eslint-plugin-vue: ^5.0.0 => 5.2.1 (5.2.1)     vue: ^2.5.22 => 2.6.6     vue-awesome-swiper: ^3.1.3 => 3.1.3     vue-eslint-parser:  5.0.0 (5.0.0)     vue-hot-reload-api:  2.3.2     vue-loader:  15.6.2     vue-router: ^3.0.1 => 3.0.2     vue-style-loader:  4.1.2     vue-template-compiler: ^2.5.21 => 2.6.6     vue-template-es2015-compiler:  1.8.2     vue-video-player: ^5.0.2 => 5.0.2     vuex: ^3.0.1 => 3.1.0   npmGlobalPackages:     @vue/cli: Not Found)

### Environment info
```
node 10.15.1
npm 6.4.1
vue-cli 3.4.0
```

### Steps to reproduce
无

### What is expected?
希望可以通过vue-cli3.0配置多页和单页混合

### What is actually happening?
最近想要开发一个大型项目，想法是多页混合单页，用vue-cli3.0试了多页配置之后发现路由不生效了

**Comment by sodatea** [comment]
Will be fixed once https://github.com/vuejs/vue-cli/pull/3181 is done.

**Comment by sodatea** [comment]
Landed in v3.4.1
