### ISSUE TITLE
indexPath doesn't work with `vue-cli-service build --mode='development'`

### ISSUE THREAD

**Issue by masquevil** [vuejs/vue-cli#3468]
### Version
3.4.0

### Reproduction link
[https://github.com/masquevil/demo-issue](https://github.com/masquevil/demo-issue)

### Environment info
```
  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: Not Found
    Safari: 12.0.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2 
    @vue/babel-preset-app:  3.4.0 
    @vue/babel-preset-jsx:  1.0.0-beta.2 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2 
    @vue/babel-sugar-inject-h:  1.0.0-beta.2 
    @vue/babel-sugar-v-model:  1.0.0-beta.2 
    @vue/babel-sugar-v-on:  1.0.0-beta.2 
    @vue/cli-overlay:  3.4.0 
    @vue/cli-plugin-babel: ^3.4.0 => 3.4.0 
    @vue/cli-plugin-eslint: ^3.4.0 => 3.4.0 
    @vue/cli-service: ^3.4.0 => 3.4.0 
    @vue/cli-shared-utils:  3.4.0 
    @vue/component-compiler-utils:  2.5.2 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue:  4.7.1 
    vue: ^2.6.6 => 2.6.6 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.2 
    vue-loader:  15.6.2 
    vue-router: ^3.0.2 => 3.0.2 
    vue-state-router: ^3.0.9 => 3.0.9 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.6 => 2.6.6 
    vue-template-es2015-compiler:  1.8.2 
  npmGlobalPackages:
    @vue/cli: 3.4.0

```

### Steps to reproduce
```bash
git clone git@github.com:masquevil/demo-issue.git
npm i
npm run build_dev
```

### What is expected?
A `index.html` file be created at directory: `dist/html/`

### What is actually happening?
A `index.html` file be created at directory: `dist/`

**Comment by masquevil** [comment]
sorry there is sth wrong with the demo. wait me for a moment and I will reopen

**Comment by sodatea** [comment]
We've recently added the following guide in the documentation to make this clearer:
> When you are running `vue-cli-service build`, your NODE_ENV should always be set to "production" to obtain an app ready for deployment, regardless of the environment you're deploying to.

As the `dist` directory structure is different between dev build and prod build, we only expect `indexPath` to work when `NODE_ENV` equals `production`.

https://github.com/vuejs/vue-cli/blob/fccb1143e5cf05823a19364159920e9d8c4266ac/packages/%40vue/cli-service/lib/config/app.js#L95-L107

**Comment by taai** [comment]
@sodatea Then, please, write that in documentation! https://cli.vuejs.org/config/#indexpath
