### ISSUE TITLE
vue init throwing error while running on windows

### ISSUE THREAD

**Issue by aankittcoolest** [vuejs/vue-cli#347]
1. Node version : v6.9.5
2. npm version: 3.10.10
3. vue version: vue@2.1.10
4. vue-cli version: vue-cli@2.8.1

Commands fired

<pre>npm install -g vue-cli</pre>
<pre>npm install -g vue</pre>
<pre>vue install wepack test</pre>

Following error is thrown

<pre>'vue' is not recognized as an internal or external command,
operable program or batch file.</pre>

Tried workouts (but same failure result)

1. npm unistall -g vue-cli ➡npm install -g vue-cli
2. npm cache clean

**Comment by posva** [comment]
> npm install -g vue

That's not necessary 🙂 It installs the vue packages

You're probably missing the the bin path. You can find some help here: http://stackoverflow.com/questions/27864040/fixing-npm-path-in-windows-8

**Comment by aankittcoolest** [comment]
@posva Thanks for the spontaneous reply :+1: 

This thread solved the issue from the same page :arrow_down: 
http://stackoverflow.com/a/32159233/5133699 

Thanks a lot!

**Comment by posva** [comment]
Thanks for sharing it! It may help other people

**Comment by fernandoSalome** [comment]
It's just add in your variable path of windows the path of Vue.js 
![variable_path](https://cloud.githubusercontent.com/assets/15473716/25756318/b4013522-319c-11e7-9773-43a203643874.png)

**Comment by frequency-design** [comment]
Hi,

I'm having the same issue, I've set up: System > Enviroment Variables > System Variables > Path > 

C:\Users\Admin\AppData\Roaming\npm\node_modules\vue-cli\bin

npm install -g vue-cli, looks to have installed the files in the AppData folder.

I'm running the following:

node -v 
v8.1.2

npm --version
5.0.4

Windows 10.

I'm getting the following error: 'vue' is not recognized as an internal or external command,
operable program or batch file.

I followed the same idea and got the zf cli working by adding the bin to the path in Enviroment Variables, not sure why this isn't working.

Can someone advise on what I'm missing.

**Comment by frequency-design** [comment]
A fix for the issue, that worked for me.

On the Vue JS website the following is used to install vue-cli

# install vue-cli
$ npm install --global vue-cli
# create a new project using the "webpack" template
$ vue init webpack my-project
# install dependencies and go!
$ cd my-project
$ npm install
$ npm run dev

Instead of installing: npm install --global vue-cli
I used: yarn global add vue-cli 

Before I did the above, I uninstalled node js version v8.1.2 and installed the recommended version v6.11.0 (not sure this really made a difference, but it was part of what I did). Then I reinstalled Git from the Git website using the downloadable installer.

**Comment by Hujjat** [comment]
I had the same issue. 
Here the quick fix. 

after running the following command
`npm install --global vue-cli`

It will place the vue.cmd in the following directory
`C:\Users\YourUserName\AppData\Roaming\npm`

at least for me it's there. 

To use vue as command in cmd. Open the cmd as admin and the the following command.
`setx /M path "%path%;%appdata%\npm"`

Now restart the cmd and run the vue again. It should work just fine.

**Comment by Daltimore** [comment]
thanks hujjat. you saved a life.

**Comment by gohance** [comment]
hi @Hujjat i have no vue.cmd inside by /AppData/Roaming/npm after installing vue-cli. How to fix this?
I already follow all the instruction above, nothing works for me

**Comment by Hujjat** [comment]
@gohance Do you have npm ? you must face any error if it's not working for you ???

**Comment by suvrodattamitu** [comment]
@Hujjat is awesome.. in my case command: setx /M path "%path%;%appdata%\npm" first did not work for me.. then i gave path to Path then it works properly.. my final command was. etx /M Path "%path%;%appdata%\npm" . it is just for your environment variables.. it may be Path or path just see what it is in your pc.. and if not create one . using Path or path. and use 1)setx /M path "%path%;%appdata%\npm" or 2)setx /M Path "%path%;%appdata%\npm"

**Comment by web-developer1** [comment]
@suvrodattamitu thanks for posting that. I was trying everything from the start and saw your comment when nothing actually worked for me. Then I went back and changed the variable path from 'PATH' to 'path' which worked like a charm. Didn't realize that case sensitive would be such a big deal. Glad I saw your comment, cheers!

**Comment by colinlancasterodoe** [comment]
Thanks @Hujjat !

**Comment by amulyachennaboyena** [comment]
I've read and found that running npm config set prefix /usr/local then re-running npm install -g vue-cli has fixed my issue? Not sure whether this was necessary though?

**Comment by mockingloris** [comment]
I am running a windows 8.1 64bit architecture.
This problem seems to be cos I used a combo of nvm-windows and Yarn.
I installed nvm-windows
Then Installed node version 8
Then Yarn
Then used Yarn to install Vue-cli
Then when I do 'vue --version' it throws an error : vue is not recognized as an internal ...

My current fix is installing vue-cli via npm instead of Yarn.

**Comment by zahafyou** [comment]
thanks @Hujjat

**Comment by CelticParser** [comment]
Keep in mind that the package is no longer `vue-cli`.

Use:
`npm install -g @vue/cli`

**Comment by alfiesalano001** [comment]
1. delete "node_modules" folder 
2. run - npm install 
![2019-03-06_9-41-42](https://user-images.githubusercontent.com/48016132/53849865-6163a080-3ff4-11e9-9ba2-035d163c53f9.png)

**Comment by palakvasani** [comment]
> I had the same issue.
> Here the quick fix.
> 
> after running the following command (as Admin)
> `npm install --global vue-cli`
> 
> It will place the vue.cmd in the following directory
> `C:\Users\YourUserName\AppData\Roaming\npm`
> 
> at least for me it's there.
> 
> To use vue as command in cmd. Open the cmd as admin and run the the following command.
> `setx /M path "%path%;%appdata%\npm"`
> 
> Now restart the cmd and run the vue again. It should work just fine.

Thank you so much! I debugged this for 2 hrs and this was very very helpful. Thanks again.

**Comment by suvrodattamitu** [comment]
thanks too

**Comment by alanlcardoso** [comment]
> > I had the same issue.
> > Here the quick fix.
> > after running the following command (as Admin)
> > `npm install --global vue-cli`
> > It will place the vue.cmd in the following directory
> > `C:\Users\YourUserName\AppData\Roaming\npm`
> > at least for me it's there.
> > To use vue as command in cmd. Open the cmd as admin and run the the following command.
> > `setx /M path "%path%;%appdata%\npm"`
> > Now restart the cmd and run the vue again. It should work just fine.
> 
> Thank you so much! I debugged this for 2 hrs and this was very very helpful. Thanks again.

Works very well!!! TKS

**Comment by xzyaoi** [comment]
If you are using yarn, ```C:\Users\{username}\AppData\Local\Yarn\bin``` also needs to be in PATH.

**Comment by rodolfoberlezi** [comment]
That is what I was missing @xzyaoi

**Comment by SimeonVSimeonov** [comment]
> To use vue as command in cmd. Open the cmd as admin and run the the following command.
> `setx /M path "%path%;%appdata%\npm"`
> 
> Now restart the cmd and run the vue again. It should work just fine.

You need to make it clear that this command will completely replace everything in PATH

**Comment by yinca7** [comment]
> I had the same issue.
> Here the quick fix.
> 
> after running the following command (as Admin)
> `npm install --global vue-cli`
> 
> It will place the vue.cmd in the following directory
> `C:\Users\YourUserName\AppData\Roaming\npm`
> 
> at least for me it's there.
> 
> To use vue as command in cmd. Open the cmd as admin and run the the following command.
> `setx /M path "%path%;%appdata%\npm"`
> 
> Now restart the cmd and run the vue again. It should work just fine.

Thank you very much!!

**Comment by swapmeet25** [comment]
Been reading through all these comments. Seems this one solution is a fix. 
setx /M path "%path%;%appdata%\npm" .. THIS DOES NOT WORK. 
Anyone else try anything else with success?

**Comment by Alphapluse** [comment]
Thanks Hujjat and yinka7 ...I had this problem but with your help fix.

**Comment by Lazy-poet** [comment]
> Just for information, If you are using yarn, ```C:\Users\{username}\AppData\Local\Yarn\bin``` also needs to be in PATH.

how then do I set this path please? I've been struggling with it but no help. I installed vue with yarn

**Comment by AntonShumin** [comment]
Hujjat's answer is from 2017,
´npm install --global vue-cli´ will install vue cli 2, for cli 3 use ´npm install -g @vue/cli´

**Comment by xzyaoi** [comment]
@Lazy-poet If you are still struggling with this, take a look at https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/

A quick google search on how to set path on windows should help.

**Comment by ialirezaei** [comment]
> I had the same issue. Here the quick fix.
> 
> after running the following command (as Admin) `npm install --global vue-cli`
> 
> It will place the vue.cmd in the following directory `C:\Users\YourUserName\AppData\Roaming\npm`
> 
> at least for me it's there.
> 
> To use vue as command in cmd. Open the cmd as admin and run the the following command. `setx /M path "%path%;%appdata%\npm"`
> 
> Now restart the cmd and run the vue again. It should work just fine.

Dude what the ...!please test and then answer!!!! dont run the last command its erase all your paths in environment variables windows 10!

**Comment by fede-2110** [comment]
> Just for information, If you are using yarn, `C:\Users\{username}\AppData\Local\Yarn\bin` also needs to be in PATH.

Thank you soy much!

**Comment by TimonDev0220** [comment]
Thank you.
I found very happy line of code by you.

**Comment by Adxell** [comment]
thank u <3
