### ISSUE TITLE
Images and assets omitted during production build

### ISSUE THREAD

**Issue by WhiteBookmark** [vuejs/vue-cli#3473]
### Version
3.4.0

### Environment info
```
Environment Info:

  System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (1) x64 QEMU Virtual CPU version (cpu64-rhel6)
  Binaries:
    Node: 10.15.1 - /usr/bin/node
    Yarn: Not Found
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: 3.4.0

```

### Steps to reproduce
Include any image in assets folder under src (/src/assets)
Run "npm run build" which is equivalent to "vue-cli-service build"

### What is expected?
Build including all images and assets

### What is actually happening?
Following message is displayed when running "npm run build":

"Images and other types of images are omitted"

---
I need to include my logo in the application, which I included in assets folder.
However running a production build is not including those images/logo.

Secondly, I have tried using NODE_ENV = Production while running the production build, result was same and problem was not fixed.

**Comment by LinusBorg** [comment]
> "Images and other types of images are omitted"

This just means that they are omitted from the display in the console. 

All assets that you *import into your application code* are processed by webpack.

If however you need to have an asset copied into /dist that is *not* imported in you appliucation code, webpack will *not* process it. For these types of static assets, we have the `/public` directory - its contents will be copied into dist regardless of wether your app uses them.

Please eread the documentation: https://cli.vuejs.org/guide/html-and-static-assets.html#static-assets-handling

**Comment by WhiteBookmark** [comment]
Well thats the thing, to check whether or not this is just in the console, I tried ti open those images in browser and download from the server in my PC but it appears to be those are just blank images and not the actual ones I placed in assets directory.

This could really mean that hose images and assets are indeed omitted.

**Comment by LinusBorg** [comment]
I can't follow. 

Please provide a reproduction as is required, then i can reconsider reopening this.

**Comment by lslvxy** [comment]
No spaces in the path
