### ISSUE TITLE
Can update webpack-chain to 5.x ?I need some new feature

### ISSUE THREAD

**Issue by mkanako** [vuejs/vue-cli#3478]
### What problem does this feature solve?
use the new feature of  webpack-chain 5.x

### What does the proposed API look like?
same as before

**Comment by LinusBorg** [comment]
We can't right now as it's a major version with breaking changes. 

You could however use the `resolutions` field in package.json (requires yarn) to overwrite the dependency for vue-cli-service  and see if it works for your usecase.

**Comment by mkanako** [comment]
Thank you,but unfortunately I use npm.
Now I avoid use the new feature of webpack-chain 5.x in other ways.

> v5.1.0
> Allow use of before() and after() with oneOf rules #133

I need this

**Comment by AlbertBrand** [comment]
I can confirm that upgrading to the current version of `webpack-chain` doesn't break the current cli-service. However it could be that projects in the community use specific 4.x functionality that breaks by upgrading this dep. But is that a blocker?

**Comment by AlbertBrand** [comment]
This seems to be the only breaking change: https://github.com/neutrinojs/webpack-chain/pull/84

**Comment by LinusBorg** [comment]
Yes it is. We expose webpack-chain's aPI as part of *our* public API. And as updating webpack-chain could break configs that users of Vue CLI have implemented, it's a breaking change.

**Comment by AlbertBrand** [comment]
OK, so to follow that train of thought, you could update the dependency but cli-service would then need to be bumped major as well, right?

**Comment by LinusBorg** [comment]
Right
