### ISSUE TITLE
vue.config.js 文件的pages配置里template配置为ejs文件，不能正确构建输出对应的ejs文件

### ISSUE THREAD

**Issue by imust98** [vuejs/vue-cli#3481]
### Version
3.2.1

### Environment info
```
production
```

### Steps to reproduce
 pages: {
     index: {
       // page 的入口
       entry: 'src/main.js',
       // 模板来源
       template: '!raw-loader!public/index.ejs',
       // 在 dist/index.html 的输出
       filename: 'index.ejs',
       title: 'Index Page',
       // 在这个页面中包含的块，默认情况下会包含
       // 提取出来的通用 chunk 和 vendor chunk。
       chunks: ['chunk-vendors', 'chunk-common', 'index']
     },

### What is expected?
构建输出对应的ejs文件

### What is actually happening?
构建输出的还是index.html的内容

**Comment by sodatea** [comment]
https://github.com/jantimon/html-webpack-plugin/blob/master/docs/template-option.md#2-setting-a-loader-directly-for-the-template

1. 是 `!!` 而不是 `!`
2. 需要自行安装 ejs-loader 并配置对应规则
3. 下次提交 bug 报告还烦请提供复现仓库……这个问题描述实在有点太不清晰了
4. 即使存在 bug，由于这部分配置我们内部是直接转给 html-webpack-plugin 作为参数的，所以应当向该插件反馈

**Comment by funkyLover** [comment]
@sodatea  可以麻烦看下这个issue https://github.com/vuejs/vue-cli/issues/3976 吗？

`pages`在处理过程中会判断了文件模板是否存在，如果不存在会替换成默认模板

但是没有考虑到指定loader的情况导致误判

这里的处理的方式直接透传参数给`html-webpack-plugin`会不会更好，如果开发者传错了也可以直接把错误抛出来，直接替换模板的话会有点困惑

如果还是按目前的一个方式处理的话，除了处理指定loader的情况，是不是也可以文档增加说明如果模板不存在会替换默认模板

**Comment by funkyLover** [comment]
之前定位到问题所在之后就想等这个bug解决之更新版本来修复

都忘记了`chainWebpack`可以再次修改webpack插件配置...

```js
const pages = {
    app: {
        entry: 'src/app.js',
        template: 'public/index.shtml'
    },
    about: {
        entry: 'src/about.js',
        template: 'public/about.shtml'
    }
};

module.exports = {
    pages: pages,
    chainWebpack: config => {
        Object.keys(pages).forEach(key => {
               config.plugin(`html-${key}`).tap(args => {
                    if (!args || args.length === 0) return args;
                    args[0].template = `!!/path/to/loader!${args[0].template}`;
                    return args;
                });
        });
    }
}
```

虽然有解决方案, 但还是希望可以处理下这个`pages`的传参问题
