### ISSUE TITLE
"Open in Editor" functionality should be accessible from within the Project view as well.

### ISSUE THREAD

**Issue by jgwill** [vuejs/vue-cli#3484]
### What problem does this feature solve?

:) It does not solve any problem, rather it gives us the result of resolving in opening the project into the Editor (like VSCode) right from the Project Dashboard :)  
Also openning the files folder structure might be great
___
<details>
<summary>Some unrelated thoughts</summary>
### Cross-Related insights  I Hope will dynamize your work 
I love that quote: "You can solve all your problems and still not have what you want" -Fritz
You guys with Vue.js dont solve problem, rather, I picture you as oriented toward innovating, which is a way different orientation that getting rid of something. (the problem)
If you want to know more about it, dont hesitate to contact me, I am always happy to give insights into the structural approach of the innovative orientation.  
in the meantime, that might kick you off on structural thinking to understand that, in my opinion, vue.js is far from a Problem Oriented product rather it is an advancing one : http://guillaumeisabelle.com/r/fritz/structural-thinking
:)
Best Regards :)
</details>

### What does the proposed API look like?
Quick and instinctive access to our Editing environment from one location (Project Dashboard).

**Comment by LinusBorg** [comment]
I don't think you understand what you are asking or suggesting...

**Comment by jgwill** [comment]
> And the bulk of your post reads like an ad.
Sorry about that, I sincerely want to share that orientation with you, I find it so important...

**Comment by jgwill** [comment]
> I don't think you understand what you are asking or suggesting.
We have access to "Open in Editor" only from the Top level or dashboard for a project (which in my case opens VSCode).  I am requesting that this "action" be accessible also when we are in the Project itself (as opening the project is really a common action I want to do from the Vue UI).
regards

**Comment by Akryum** [comment]
It already exists, but maybe not discoverable enough.

![Screenshot from 2019-04-08 21-28-38](https://user-images.githubusercontent.com/2798204/55751188-5feb2500-5a45-11e9-9ab4-01d09b3f46f9.png)
