### ISSUE TITLE
spread operator not transpiling

### ISSUE THREAD

**Issue by gigioSouza** [vuejs/vue-cli#3486]
### Version
3.0.3

### Node and OS info
9.9.0, npm(5.6.0), macOS Mojave

### Steps to reproduce
I need to test/run my project in an older version of Chrome: 54.0.2840.87 (64-bit)
When testing I realized that project wasn't transpiling spread operators. And as this old version of chrome don't support spread operator I need to configure it.

### What is expected?
Transpile spread operator:
```js
function foo(options = {}) {
  const bar = {
    ...options
  }
}
```

### What is actually happening?
Not transpiling the `...options`

---
My `babel.config.js`
```js
module.exports = {
  presets: [
    '@vue/app'
  ]
};
```

My `package.json`:
```json
  "dependencies": {
    "@oito/v-boot": "2.9.2",
    "axios": "0.18.0",
    "bootstrap-vue": "2.0.0-rc.11",
    "d3": "5.7.0",
    "lodash-es": "4.17.10",
    "moment": "2.22.2",
    "rxjs": "6.3.2",
    "v-stylish": "2.0.0",
    "vue": "2.5.17",
    "vue-router": "3.0.1",
    "vue-rx": "6.0.1",
    "vuelidate": "0.7.4",
    "vuex": "3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "3.0.3",
    "@vue/cli-plugin-eslint": "3.0.3",
    "@vue/cli-plugin-unit-jest": "3.0.3",
    "@vue/cli-service": "3.0.3",
    "@vue/test-utils": "1.0.0-beta.25",
    "json-server": "^0.14.0",
    "lint-staged": "^7.2.0",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.0.1",
    "vue-template-compiler": "2.5.17"
  }
```

**Comment by LinusBorg** [comment]
He default setup *does* transpile those. 

If its not working for you, please provide a repository with s reproduction as required in the issue template. 

It likely isn't vue-cli but some dependency of your project that is not transpiled. 

Thanks.

**Comment by gigioSouza** [comment]
@LinusBorg that's it! I simply forgot it, I need to add an internal package to the `transpileDependencies` prop in the `vue.config.js`. I can´t test it right now but I'm sure that's the issue.

**Comment by gigioSouza** [comment]
@LinusBorg Yeah, that was my mistake. Thanks for your time and sorry for bothering with this little mistake.

**Comment by browndemon** [comment]
@gigioSouza 
error: Invalid attempt to spread non-iterable instance
Was it the same mistake?
