### ISSUE TITLE
cant create test-app in test folder

### ISSUE THREAD

**Issue by xxholly32** [vuejs/vue-cli#3489]
### Version
3.4.1

### Reproduction link
[https://github.com/vuejs/vue-cli/blob/dev/.github/CONTRIBUTING.md#development-setup](https://github.com/vuejs/vue-cli/blob/dev/.github/CONTRIBUTING.md#development-setup)

### Environment info
```
System:
    OS: macOS 10.14
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: Not Found
    Safari: 12.0
  npmGlobalPackages:
    @vue/cli: 3.3.0
```

### Steps to reproduce
follow step :

[https://github.com/vuejs/vue-cli/blob/dev/.github/CONTRIBUTING.md#development-setup](https://github.com/vuejs/vue-cli/blob/dev/.github/CONTRIBUTING.md#development-setup)

### What is expected?
create vue project 

error at vue create test-app

### What is actually happening?
```
Vue CLI v3.3.0 DEBUG
? Please pick a preset: default (babel, eslint)

Vue CLI v3.3.0 DEBUG
✨  Creating project in /Users/xiangxiao/Documents/work/workspace/vue-cli/packages/test/test-app.
⚙  Installing CLI plugins. This might take a while...

 ERROR  Error: Cannot find module '@vue/cli-service/bin/vue-cli-service'
Error: Cannot find module '@vue/cli-service/bin/vue-cli-service'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at setupDevProject (/usr/local/lib/node_modules/@vue/cli/lib/util/setupDevProject.js:8:13)
    at Creator.create (/usr/local/lib/node_modules/@vue/cli/lib/Creator.js:152:46)
    at process._tickCallback (internal/process/next_tick.js:68:7)
xiangxiaodeMacBook-Pro:test xiangxiao$ vue info
```

---
根据[https://github.com/vuejs/vue-cli/blob/dev/.github/CONTRIBUTING.md#development-setup](https://github.com/vuejs/vue-cli/blob/dev/.github/CONTRIBUTING.md#development-setup)
在vue create test-app这行报错；不过我在其他文件夹可以创建，包括@vue

follow step ：[https://github.com/vuejs/vue-cli/blob/dev/.github/CONTRIBUTING.md#development-setup](https://github.com/vuejs/vue-cli/blob/dev/.github/CONTRIBUTING.md#development-setup)
,error at vue create test-app.but i can create any other folder include @vue

**Comment by sodatea** [comment]
Try `npm uninstall @vue/cli -g`.
It looks like that you are still using the globally installed `vue` binary rather than the `yarn link`ed one.

**Comment by xxholly32** [comment]
@sodatea 
it seemed yarn had a bug with globally install at 1.13+ . it only can use npm link.

https://github.com/yarnpkg/yarn/issues/891
