### ISSUE TITLE
Prettier errors when running npm run serve

### ISSUE THREAD

**Issue by vielhuber** [vuejs/vue-cli#3493]
### Version
3.4.1

### Environment info
```
Ubuntu 18 LTS
```

### Steps to reproduce
Create a vue file, put inside ```<template>next</template>``` and save. The code is now formatted in vscode to:

```
<template
   >next</template
>
```

### What is expected?
No error when comiling with npm run serve.

### What is actually happening?
```
error: Insert `</template` (prettier/prettier) at src\components\test.vue:1135:33:
  1133 |                                 <template
  1134 |                                     >next</template
> 1135 |                                 >
```

**Comment by sodatea** [comment]
Is it formatted by VSCode or by `vue-cli-service lint`?
Also, please provide a reproduction repo. We can't debug without real code to run.

**Comment by vielhuber** [comment]
The problem were different configs for vscode and eslint. Thanks for your time and work!
