### ISSUE TITLE
Disabling the index.html generation does not work

### ISSUE THREAD

**Issue by smtxdev** [vuejs/vue-cli#3498]
### Version
3.4.1

### Environment info
```
  System:
    OS: macOS Sierra 10.12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5575R CPU @ 2.80GHz
  Binaries:
    Node: 11.4.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2 
    @vue/babel-preset-app:  3.4.1 
    @vue/babel-preset-jsx:  1.0.0-beta.2 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2 
    @vue/babel-sugar-inject-h:  1.0.0-beta.2 
    @vue/babel-sugar-v-model:  1.0.0-beta.2 
    @vue/babel-sugar-v-on:  1.0.0-beta.2 
    @vue/cli-overlay:  3.4.1 
    @vue/cli-plugin-babel: ^3.4.0 => 3.4.1 
    @vue/cli-plugin-eslint: ^3.4.0 => 3.4.1 
    @vue/cli-service: ^3.4.0 => 3.4.1 
    @vue/cli-shared-utils:  3.4.1 
    @vue/component-compiler-utils:  2.6.0 
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.2 
    vue: ^2.6.6 => 2.6.7 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.6.4 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.7 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 3.4.1
```

### Steps to reproduce
- `vue create test`
- create a `vue.config.js` file
- copy and paste the content of this section: https://cli.vuejs.org/guide/html-and-static-assets.html#disable-index-generation into the `vue.config.js` file
- npm run build

### What is expected?
No `index.html` file under `dist/index.html`

### What is actually happening?
There is an `index.html` file under `dist/index.html`

**Comment by smtxdev** [comment]
Of course directly after I submitted this issue I found the problem. It was a side effect because the `vue-cli` generates in the `public` folder an `index.html` file. The copy Plugin moves the `index.html` file then to `dist/index.html`.

Just delete the `index.html` file from `public/index.html` then everything works as expected.

**Comment by fxxjdedd** [comment]
I have encountered the same problem. 
Is this not a bug?

**Comment by ricky11** [comment]
even when index.html file is deleted from public folder one is still built...

**Comment by boutell** [comment]
I also see that it is still built in ui/dist/index.html when it's gone from public/index.html. I resorted to removing it after it is copied to my server's public folder.
