### ISSUE TITLE
babel-plugin-transform-runtime和babel-polyfill能同时使用么？

### ISSUE THREAD

**Issue by agileago** [vuejs/vue-cli#35]
使用vue的过程中，发现官方的配置是使用transform-runtime，但这个有一些es6的东西不能使用，比如Object.assign,然后我就添加了一个babel-polyfill,但发现polyfill和transform-runtime同时使用的话，会有重复代码，比如polyfill里面已经有Promise和regenerator,但transform-runtime也会自己添加这些东西，所以我就一直很疑惑这个东西到底该怎么配置？

**Comment by yyx990803** [comment]
transform-runtime 支持 `Object.assign` 啊。transfrom-runtime 不支持的只有原生类型 prototype 上的新方法，比如 `String.prototype.repeat`。通常来说用了 transform-runtime 就不需要 babel-polyfill 了。

http://www.2ality.com/2015/12/babel6-helpersstandard-library.html
