### ISSUE TITLE
autoprefixer Didn't work ？

### ISSUE THREAD

**Issue by cench** [vuejs/vue-cli#350]
In file webpack.base.conf.js has code

```  vue: {
    loaders: utils.cssLoaders({ sourceMap: useCssSourceMap }),
    postcss: [
      require('autoprefixer')({
        browsers: ['last 2 versions']
      })
    ]
  }
```

But in Vue component when i use css3 it really not add a prefix ?

```
<template>
    <div class="taskLog">
        <div class="test">TaskLog</div>
    </div>
</template>
<style scoped>
    .test{
        transform: scale(1.2);
    }
</style>
```

**Comment by posva** [comment]
transform doesn't need a prefix in any of 2 last version of browsers: http://caniuse.com/#search=transform
Next time, please, open the issue in the relevant template repo. Thanks 🙂

**Comment by tfsimondouglas** [comment]
```
   loaders: utils.cssLoaders({ sourceMap: useCssSourceMap }),
    postcss: [
      require('autoprefixer')({
        browsers: ['ie >=9']
      })
    ]
  }
```
Doesn't work. Doesn't generate any prefixes.
Related backlink: https://stackoverflow.com/questions/45208186/vue-webpack-2-autoprefixer-for-ie9
