### ISSUE TITLE
vue ui 运行后页面样式出错

### ISSUE THREAD

**Issue by akai007** [vuejs/vue-cli#3501]
### Version
3.4.1

### Environment info
```
mac / chrome 56.0.2924.87 (64-bit)
```

### Steps to reproduce
运行 vue ui 打开已有项目 发现样式存在问题

### What is expected?
运行tasks run server 出现 open app 按钮

### What is actually happening?
不出现，切布局不一致

**Comment by iTaster** [comment]
vue ui 打开空白页面路过地说

**Comment by sodatea** [comment]
为什么要用 Chrome 56……现在最新版 Chrome 已经是 72 了……你落后了 16 个大版本……先升级 Chrome 再看看有没有问题吧。

@iTaster 请清除浏览器缓存再试一下

**Comment by akai007** [comment]
@sodatea  _哈哈。掏出家里很久没用的mac才遇到的，升级了就行了~
