### ISSUE TITLE
yarn build never finishes

### ISSUE THREAD

**Issue by layanto** [vuejs/vue-cli#3504]
### Version
3.4.0

### Environment info
```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.4.1
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.4.1
    @vue/cli-plugin-babel: ^3.4.0 => 3.4.1
    @vue/cli-plugin-eslint: ^3.4.0 => 3.4.1
    @vue/cli-service: ^3.4.0 => 3.4.1
    @vue/cli-shared-utils:  3.4.1
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.2
    vue: ^2.6.6 => 2.6.7
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.6.4
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.7
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. vue create test-project
2. Enter to accept default option
3. yarn build
Build never finishes, dist folder not created.

### What is expected?
Production build of project created

### What is actually happening?
Build for production never finishes. Console showing "Building for production..."

---
Dev build working no problem.

**Comment by sodatea** [comment]
Can't reproduce. Could you please provide a reproduction repo?
According to the environment info, the project that encountered this problem is certainly not created with default preset - there's `vuex` in its dependencies.

**Comment by layanto** [comment]
![vue-cli](https://user-images.githubusercontent.com/245078/53525495-07676480-3b36-11e9-94e2-8bb2dcba1c53.gif)

**Comment by layanto** [comment]
![2019-02-28 08_53_41-1 consolez](https://user-images.githubusercontent.com/245078/53525711-80ff5280-3b36-11e9-9552-a47e1afbfeb5.png)

**Comment by layanto** [comment]
Project files excluding node-modules: 
[test.zip](https://github.com/vuejs/vue-cli/files/2912497/test.zip)

**Comment by layanto** [comment]
Tested on another Windows 10 machine which never had vue-cli installed before and same behaviour observed - yarn build never finishes. Is there log file where I can find out what "vue-cli-service build" is doing?

**Comment by layanto** [comment]
Issue not with vue-cli-service. I am using ansicon terminal (https://github.com/adoxa/ansicon) and it appears that when I run yarn build with ansicon, it fails to create node_modules/.cache folder. If I use Windows cmd.exe and run yarn build, Vue builds correctly and I noticed node_modules/.cache folder appears. After that if I run yarn build with ansicon terminal, Vue builds correctly.
