### ISSUE TITLE
devServer.writeToDisk

### ISSUE THREAD

**Issue by shinehs** [vuejs/vue-cli#3514]
### Version
3.3.0

### Reproduction link
[https://github.com/shinehs/catcher](https://github.com/shinehs/catcher)

### Environment info
```
npm run dev
```

### Steps to reproduce
when I config devServer.writeToDisk, I get an error!
code:
devServer : {
writeToDisk: true
}
error:
ValidationError: webpack Dev Server Invalid Options options should NOT have additional properties!
I found the problem was caused by this file:
in *node_modules\webpack-dev-server\node_modules\schema-utils\src\validateOptions.js!!!
help me please!!!

### What is expected?
file is output to the dist directory

### What is actually happening?
error

---
when I config devServer.writeToDisk, I get an error!
code:
devServer : {
writeToDisk: true
}
error:
ValidationError: webpack Dev Server Invalid Options options should NOT have additional properties!
I found the problem was caused by this file:
in *node_modules\webpack-dev-server\node_modules\schema-utils\src\validateOptions.js!!!
help me please!!!

**Comment by Akryum** [comment]
I don't think it has anything to do with vue-cli. You should open an issue on webpack-dev-server instead.
