### ISSUE TITLE
vue/no-unused-components detect error when component used in render function

### ISSUE THREAD

**Issue by marszoolong** [vuejs/vue-cli#3515]
**Version**
3.3.0

**Environment info**
System:                                                                                                                     
  OS: Windows 7                                                                                                             
  CPU: (4) x64 Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz                                                                     
Binaries:                                                                                                                   
  Node: 8.11.1 - d:\devenv\nodejs\node.EXE                                                                                  
  Yarn: 1.5.1 - d:\devenv\nodejs\node_global\yarn.CMD                                                                       
  npm: 5.6.0 - d:\devenv\nodejs\npm.CMD                                                                                     
npmPackages:                                                                                                                
  @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2                                                                      
  @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2                                                                        
  @vue/babel-preset-app:  3.4.0                                                                                             
  @vue/babel-preset-jsx:  1.0.0-beta.2                                                                                      
  @vue/babel-sugar-functional-vue:  1.0.0-beta.2                                                                            
  @vue/babel-sugar-inject-h:  1.0.0-beta.2                                                                                  
  @vue/babel-sugar-v-model:  1.0.0-beta.2                                                                                   
  @vue/babel-sugar-v-on:  1.0.0-beta.2                                                                                      
  @vue/cli-overlay:  3.4.0                                                                                                  
  @vue/cli-plugin-babel: ^3.4.0 => 3.4.0                                                                                    
  @vue/cli-plugin-e2e-cypress: ^3.4.0 => 3.4.0                                                                              
  @vue/cli-plugin-eslint: ^3.4.0 => 3.4.0                                                                                   
  @vue/cli-plugin-pwa: ^3.4.0 => 3.4.0                                                                                      
  @vue/cli-plugin-unit-mocha: ^3.4.0 => 3.4.0                                                                               
  @vue/cli-service: ^3.4.0 => 3.4.0                                                                                         
  @vue/cli-shared-utils:  3.4.0                                                                                             
  @vue/component-compiler-utils:  2.5.2                                                                                     
  @vue/eslint-config-standard: ^4.0.0 => 4.0.0                                                                              
  @vue/preload-webpack-plugin:  1.1.0                                                                                       
  @vue/test-utils: ^1.0.0-beta.20 => 1.0.0-beta.29                                                                          
  @vue/web-component-wrapper:  1.2.0                                                                                        
  eslint-plugin-vue: ^5.0.0 => 5.2.2                                                                                        
  vue: ^2.5.22 => 2.6.6                                                                                                     
  vue-content-placeholders: ^0.2.1 => 0.2.1                                                                                 
  vue-echarts: ^4.0.1 => 4.0.1                                                                                              
  vue-eslint-parser:  2.0.3                                                                                                 
  vue-genid-loader: http://139.224.22.150:4873/vue-genid-loader/-/vue-genid-loader-1.0.1.tgz => 1.0.1                       
  vue-hot-reload-api:  2.3.2                                                                                                
  vue-i18n: ^8.8.2 => 8.8.2                                                                                                 
  vue-image-editor: http://139.224.22.150:4873/vue-image-editor/-/vue-image-editor-0.4.8.tgz => 0.4.8                       
  vue-loader:  15.6.3                                                                                                       
  vue-router: ^3.0.1 => 3.0.2                                                                                               
  vue-style-loader:  4.1.2                                                                                                  
  vue-template-compiler: ^2.5.21 => 2.6.6                                                                                   
  vue-template-es2015-compiler:  1.8.2                                                                                      
  vue-text-mask: ^6.1.2 => 6.1.2                                                                                            
  vuex: ^3.0.1 => 3.1.0                                                                                                     
npmGlobalPackages:                                                                                                          
  @vue/cli: Not Found     
                                                                                                  
**Steps to reproduce**
// A single file component
<template>
 <div>
  ...
 // no CompoentA tag
  </div>
</template>
<script>
import ComponentA from './ComponentA.vue'

export default {
  components: { ComponentA },
  render: (h, params) => {
            return h('ComponentA ', {
              props: {
                params: params
              }
            })
          }
}
</script>

**What is expected?**
no eslint error

**What is actually happening?**
error The "ComponentA" component has been registered but not used vue/no-unused-components

**Comment by XinHuaLuFang** [comment]
https://github.com/vuejs/vue-cli/issues/3515
只是在render、createElement、JSX中使用的话，只用import进来就可以了，不用在components里注册，components里注册是给template中用的，画蛇添足导致的报错😄
