### ISSUE TITLE
debug info is confusing in chrome  在chrome浏览器下调试信息错乱但在火狐下正常

### ISSUE THREAD

**Issue by jumplee** [vuejs/vue-cli#352]
hi,I'm using the vue-cli to create the project ,and find the chrome dev tool can not work well with the
webpack dev server(just npm run dev)

1.  breakpoint may not work or did in the wrong line
2. error catch is terrible !no stack info 

by the way ,**firefox** is working fine

anybody know why 

system :  mac os

browser: chrome 56

vue: lastest version

**Comment by egoist** [comment]
请在 template repo 里发 issue
