### ISSUE TITLE
打包相对路径问题，设置publicPath: '' 或者publicPath: './'都无作用

### ISSUE THREAD

**Issue by PolanZ** [vuejs/vue-cli#3520]
### Version
3.4.1

### Reproduction link
无

### Environment info
```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 8.11.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Users\Zent\AppData\Roaming\npm\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.4.1
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.4.1
    @vue/cli-plugin-babel: ^3.4.0 => 3.4.1
    @vue/cli-plugin-e2e-cypress: ^3.4.0 => 3.4.1
    @vue/cli-plugin-eslint: ^3.4.0 => 3.4.1
    @vue/cli-plugin-unit-mocha: ^3.4.0 => 3.4.1
    @vue/cli-service: ^3.4.1 => 3.4.1
    @vue/cli-shared-utils:  3.4.1
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/test-utils: ^1.0.0-beta.20 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    eslint-plugin-vue: ^5.0.0 => 5.2.2
    vue: ^2.6.6 => 2.6.7
    vue-awesome: ^3.4.0 => 3.4.0
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.6.4
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.7
    vue-template-es2015-compiler:  1.9.1
    vuedraggable: ^2.18.1 => 2.18.1
    vuex: ^3.0.1 => 3.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
vue-cli-service build 想打包出现文件的相对路径，但是按文档设置了publicPath([https://cli.vuejs.org/zh/config/#publicpath)无作用。](https://cli.vuejs.org/zh/config/#publicpath)%E6%97%A0%E4%BD%9C%E7%94%A8%E3%80%82)
打包出现的index.html里面引用的`` js``css ``都是以`/`开头。

```
// vue.config.js
module.exports = {
   publicPath: './',
   assetsDir: '',
   runtimeCompiler: true,
   devServer: {
      host: '0.0.0.0',
      port: '8083'
   },
}
```

打包出来的`dist/index.html`片断：
```
<script src=js/chunk-vendors.d9159855.js></script><script src=js/app.b6247eab.js></script>
```

### What is expected?
<script src=./js/chunk-vendors.d9159855.js></script><script src=./js/app.b6247eab.js></script>

### What is actually happening?
<script src=js/chunk-vendors.d9159855.js></script><script src=js/app.b6247eab.js></script>

---
自行去调试打印`node_modules/@vue/cli-service/lib/config/base.js`里的 `options`参数打印出来里面的`publicPath`都转换成``空字符串，但是生成路径并不是预期的`./`开头

**Comment by jkzing** [comment]
`<script src=js/chunk-vendors.d9159855.js></script><script src=js/app.b6247eab.js></script>`

这个不就是相对路径吗...

**Comment by PolanZ** [comment]
```
<script src=./js/chunk-vendors.d9159855.js></script><script src=./js/app.b6247eab.js></script>
```
这样才是相对路径呀，随便放到哪个目录下发布都可以相对引用到资源，
没有`./`开头的话，只能是根目录

**Comment by sodatea** [comment]
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#Examples_of_relative_URLs

`./` 在 URL 解析中是会被消去的，非以协议头或者 `/` 开始的字符串就是相对路径。
至于回复里说的，那是 serve 的问题，`/dist/index.html` 被重定向到了 `/dist`，以 `/dist` 作为基准计算相对路径，结果肯定是错误的。不信的话你可以自己试试把 `dist/index.html` 的内容改成你认为正确的样子，结果还是会一样的。

**Comment by laiyonghao** [comment]
> https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#Examples_of_relative_URLs
> 
> `./` 在 URL 解析中是会被消去的，非以协议头或者 `/` 开始的字符串就是相对路径。
> 至于回复里说的，那是 serve 的问题，`/dist/index.html` 被重定向到了 `/dist`，以 `/dist` 作为基准计算相对路径，结果肯定是错误的。不信的话你可以自己试试把 `dist/index.html` 的内容改成你认为正确的样子，结果还是会一样的。

`./` 在URL解析中是有意义的，和 ` ` 肯定不一样。可以从 http://webreference.com/html/tutorial2/3.html 的 table 2 例子中看出来。

退一步来说，根据用户设定的 `publicPath` 出现路径错误那就由用户自己去修改 `publicPath` 就好了，库擅作“正确决定”也是“手伸得太长”，还是要把这个权利还给用户为宜。

另外，手动把生成的 `js/chunk-vendors.d9159855.js` 改为 `./js/chunk-vendors.d9159855.js` 确实可以解决部署到 `/dist/` 导致404的问题，这里确实有 bug。

**Comment by sodatea** [comment]
@laiyonghao 

1. 哪里不一样了？请仔细看 table 2 第一行和最后一行

Relative URI | Absolute URI
-- | --
about.html | http://WebReference.com/html/about.html
./about.html | http://WebReference.com/html/about.html

2. 这里没有路径错误不错误的问题，我们进行的是一个等价转换，没有把错的改成对的

3. 这个 bug 不是 Vue CLI 打包结果的，是你们用的静态服务器 `serve` 的

**Comment by sodatea** [comment]
`serve` 的问题在于它把 `dist/` 和 `dist` 等价了。这是错误的处理。
URL 路径**中**的 `./` 是完全没有意义可以消掉的，但是**结尾**的 `/` 表示这个路径是一个目录，不带 `/` 表示是一个文件。

习惯是静态服务器用 `dist/index.html` 响应目录请求 `dist/`，但是 `serve` 直接把这个请求重定向到了 `dist`，这肯定是错的，目录层级都不对了。

要是有兴趣可以去给 `serve` 提 bug，但这不是 Vue CLI 的问题。

**Comment by laiyonghao** [comment]
仔细看了我们问题，发现和这个还是稍不一样的，应该是我们的问题。Sorry。

**Comment by PLQin** [comment]
最后如何？ 我也期待打包后保留 `./js/`  ， 而不是变为 `js/`

**Comment by laiyonghao** [comment]
> 最后如何？ 我也期待打包后保留 `./js/` ， 而不是变为 `js/`

库没错。
我们之前的用法不对，所以还是我们自己改吧。

**Comment by 826327700** [comment]
> > 最后如何？ 我也期待打包后保留 `./js/` ， 而不是变为 `js/`
> 
> 库没错。
> 我们之前的用法不对，所以还是我们自己改吧。

我也遇到这个问题了 所以到底应该怎么改？我就想要我写publicPath:"./"，打包出来就是./开头，库没错？前几个版本还是写什么就是什么，现在就替我省略掉了，难道不是手太长？

**Comment by 546200350** [comment]
https://github.com/vuejs/vue-cli/blob/v4/packages/@vue/cli-service/lib/Service.js
第398行的正则可以看一下
