### ISSUE TITLE
Proxy settings do not accept an array but array passes validations and fails silently

### ISSUE THREAD

**Issue by aldencolerain** [vuejs/vue-cli#3524]
### Version
3.4.1

### Steps to reproduce
in vue config set proxy config to:
```
devServer: {
  overlay: {
    warnings: true,
    errors: true
  },
  host: '0.0.0.0',
  disableHostCheck: true,
  index: '',
  proxy:[{
    context: ['/**', '!/app.js', '!/sockjs-node/**'],
    target: 'http://localhost:8000'
  }]
}
```

### What is expected?
The http-proxy-middleware package accepts an array as a config option (https://github.com/chimurai/http-proxy-middleware#context-matching) but this is not supported by vue-cli.  Vue cli should warn the user that the array syntax is unsupported.

### What is actually happening?
No error is raised because in the prepareProxy function in prepareProxy.js typeof proxy !== 'object' is used to check that the proxy config is an object, but an array passes this test.  The typeof an Array is 'object'.

**Comment by BennyAlex** [comment]
@LinusBorg 
The error message is not concrete enough, see https://github.com/vuejs/vue-cli/issues/5740.

It gives no information that array is not supported in vue, even its valid in the middleware.

**Comment by BennyAlex** [comment]
In my opinion its kinda dumb to pass down the config instead of using the webpack dev server (and middleware) directly.

If all options arent fully supported, you shouldnt mention the http-proxy-middleware documentation inside vue's docs.

**Comment by LukeusMaximus** [comment]
I got caught by this as well. If the proxy is capable of interpreting an array, surely it can just be passed through.
