### ISSUE TITLE
建议创建项目时能够先将模板生成，依赖包的安装可以交给用户

### ISSUE THREAD

**Issue by yft** [vuejs/vue-cli#3528]
### What problem does this feature solve?
新创建项目时，依赖包安装步骤发生错误的概率太大，导致项目生成失败，如果先生成模板，后续包安装步骤失败影响不会很大，体验更好

### What does the proposed API look like?
无

**Comment by cooper1x** [comment]
我也这样觉得，另外我自己想用yarn安装依赖，npm还是太慢了

**Comment by yft** [comment]
@cooper1x 在创建时的第一个步骤里面可以选择是使用yarn还是npm的

**Comment by cooper1x** [comment]
我输入`vue init webpack demo`回车，结果第一个是创建名字，并没有找到选择yarn还是npm的提示。
```
? Project name demo
? Project description A Vue.js project
? Author cooperx <cooperx@foxmail.com>
? Vue build standalone
? Install vue-router? Yes
? Use ESLint to lint your code? Yes
? Pick an ESLint preset (Use arrow keys)
> Standard (https://github.com/standard/standard)
  Airbnb (https://github.com/airbnb/javascript)
  none (configure it yourself)
```

**Comment by cooper1x** [comment]
@yft 找到了，在后面，谢谢！
```
? Should we run `npm install` for you after the project has been created? (recommended)
  Yes, use NPM
> Yes, use Yarn
  No, I will handle that myself
```

**Comment by gauseen** [comment]
```
vue create hello-world -m yarn # -m, --packageManager <command>  在安装依赖时使用指定的 npm 客户端
```

**Comment by KuangPF** [comment]
`vue-cli3.0` 是基于插件构建的，在初始化项目时需要安装一些核心的插件以及依赖包，比如 `cli-plugin-babel`，`cli-plugin-eslint` 等插件以及核心的 `cli-service` 依赖包。在安装完这些依赖后，`cli` 会调用每个插件的 `PluginAPI` 来对项目进行增强，比如修改初始化项目文件，注册 `vue-cli-service` 命令等。那么如果不先安装依赖的话插件这一部分就不能很好的使用，就和 `vue-cli 2.x` 直接拉取远程模板没有太大的区别。用户可以通过命令或者直接修改` ～/.vuerc` 文件来设置包管理器，如果选用 npm 包管理器，`vue-cli 3.0` 会自动判断是 `npm` 官方源快还是淘宝源快，并使用较快的源进行依赖的安装。

**Comment by yft** [comment]
@KuangPF 那增强的这部分处理可以由cli完成吗  将这些作为全局安装的插件  提供用户一个选择是不是要全局安装

**Comment by KuangPF** [comment]
@yft 插件都是安装在局部的，增强那部分是 `cli` 中 `Generator` 类实现的，项目初始化模板是在`cli-service/generator/template` 中，如果你不装安装插件依赖这些，怎么利用插件去增强项目呢，比如写了一个 `cli-plugin-edit-app` 的插件用于替换项目中的 `App.vue` 文件中的一部分，如果不装这个插件，那就不能利用 vue-cli 3.0 提供的 `PluginAPI` 去进行操作了噻。

**Comment by yft** [comment]
@KuangPF 所以是不是可以将那些插件做成全局包 变动的只有配置 让配置跟随项目即可

**Comment by KuangPF** [comment]
@yft 你考虑的情况可能只有固定的 `vue-cli` 官方的插件包，但还有种情况就是 vue create 可以拉去远程的 `preset`，里面也可以包含第三方的插件包，当你不知道这些第三`vue-cli`插件包的时候就不好安装在全局，因此在初始化项目将插件包和相关依赖安装在本地是比较科学的。

**Comment by yft** [comment]
@KuangPF 可以将按照常用步骤创建项目的流程优化一下，毕竟这种步骤使用的人也是很多的

**Comment by sodatea** [comment]
> 将那些插件做成全局包 变动的只有配置 让配置跟随项目即可

这个工作应该是包管理器操心的，比如 yarn pnp 和 pnpm 在实践的全局包缓存。Vue CLI 暂时不会考虑引入你说的这些设计。

**Comment by MissZhang-oo** [comment]
新创建项目时，有什么命令可以只安装模板，不安装依赖吗?
