### ISSUE TITLE
建议vue init加入可选参数实现默认配置

### ISSUE THREAD

**Issue by cooper1x** [vuejs/vue-cli#3531]
### What problem does this feature solve?
希望可以vue init后面可以添加-y这个参数，就不用一个个确认回车了，参照npm init -y。

### What does the proposed API look like?
[npm-init | npm Documentation](https://docs.npmjs.com/cli/init)

**Comment by sodatea** [comment]
谢谢建议。不过 `vue init` 只用于兼容 vue-cli 2.x，并不推荐使用，目前不再接受新的特性请求。
如果使用 Vue CLI 3.x 的 `vue create` 命令的话，可以用 `vue create -d my-project` 采用默认配置生成项目，也可以提供 `--preset` 参数，使用事先定义的项目预设，这两种方式都可以避免手动确认回车。

**Comment by lijing666** [comment]
@sodatea vue create 支持和vue init一样指定远程模板吗？vue create 的远程preset好像不是这个功能，它仅仅只是一些插件预置配置而已？是不是只有旧的vue init才支持指定模板仓库的功能呀？这么好的功能废掉了有些可惜了。很多情况vue模板工程需要根据不同的终端，不同的行业，添加各自不同的基础功能，从而产生多个不同的应用初始化模板，vue cli2的vue init 的自定义git仓库模板，就很好解决了这个问题，vue cli 3.0却废掉这个功能好可惜呀。

**Comment by sodatea** [comment]
@lijing666 preset 可以带一个 Generator https://cli.vuejs.org/guide/plugins-and-presets.html#remote-presets 用它来生成模板就好了
