### ISSUE TITLE
Can you pass JS functions into the package as configuration?

### ISSUE THREAD

**Issue by steveworkman** [vuejs/vue-cli#3535]
### What problem does this feature solve?
I'm creating a standardised babel config in a preset. This config requires that different configuration is used depending on the `process.env` options, in particular when Jest is running in `test` mode.

```js
  api.extendPackage({
    babel: {
      ignore:  process.env === "test" ? ["core-js/*"] : []
    }
  });
```
This results in
```js
module.exports = {
  presets: [
    '@vue/app'
  ],
  ignore: []
}
```

### What does the proposed API look like?
I'm not sure. The generator script is evaluating the code when it is running, so I guess it would need to be a method similar to that but that takes a string to be evaluated.

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-eslint/eslintOptions.js

**Comment by steveworkman** [comment]
That's a lovely bit of black magic right there. It works, and it'd be great to see that as utility as part of the API. Would you be open to a PR for this?

**Comment by sodatea** [comment]
Yeah, PR is welcome 😀
