### ISSUE TITLE
Please update workbox-webpack-plugin to 4.0.0 in the PWA plugin

### ISSUE THREAD

**Issue by mikejamesli** [vuejs/vue-cli#3540]
### What problem does this feature solve?
The official workbox 4.0.0 has been released along with the updated the workbox-webpack-plugin library.

https://www.npmjs.com/package/workbox-webpack-plugin

### What does the proposed API look like?
Update @vue/cli-plugin-pwa workbox-webpack-plugin from "3.6.3" to "4.0.0"

**Comment by Amareis** [comment]
++, without this I cannot skip waiting for workbox service worker (https://github.com/GoogleChrome/workbox/pull/1929)

**Comment by sodatea** [comment]
Landed in v4.0.0-alpha.0

**Comment by bilouw** [comment]
Hey,

I'm still with the 3.6.3 version, how can i update this ?

**Comment by sodatea** [comment]
Just update the `@vue/cli-plugin-pwa` dependency in your project.

**Comment by bilouw** [comment]
Oh yes, i thought i had the latest version of @vue/cli-plugin-pwa. It seems that vue-cli doesn't install the last @vue/cli-plugin-pwa or i don't know.
