### ISSUE TITLE
not support template in self-builded gitlab

### ISSUE THREAD

**Issue by echopi** [vuejs/vue-cli#355]
command I used is like below:
```sh
vue init -c gitlab:gitlab-host.com:username/my-template-repo project-name
```
the vue-cli seems to treat the above template local

```js
if (/^[./]|(\w:)/.test(template)) {}
```

**Comment by zigomir** [comment]
@echopi please check if this is fixed on master and maybe then we should publish a new version. I was working on this some days ago: https://github.com/vuejs/vue-cli/pull/341

**Comment by echopi** [comment]
@zigomir the master solved the problem, thanks.

Another problem comes to me is when I do the following cmd again with the `-c` options, git clone failed due to the path git clone to existed already.

```sh
vue init -c gitlab:gitlab-host.com:username/my-template-repo another-project-name
```

Can vue-cli provide a option to disable the template to be cached？

**Comment by posva** [comment]
Closing since this was fixed long time ago. Caching should also be working correctly now, but if it doesn't, please, open a new issue with some details 🙂
