### ISSUE TITLE
how to disable AMD loader using vue.config.js

### ISSUE THREAD

**Issue by muraliwise** [vuejs/vue-cli#3550]
module: {
rules: [
{
parser: {
amd: false
}
}
]
}
 In webpack server we are configuring like this but vue.config.js how to do this one.

and i tried chainWebpack in vue.config.js file but it is reflecting.

give me the solutions for this

**Comment by d9k** [comment]
```
// . . . .
configureWebpack: webpackConfig => {
      webpackConfig.module.rules.push({
        parser: {
          amd: false,
        },
      });
```
