### ISSUE TITLE
How to set the typescript settings file?

### ISSUE THREAD

**Issue by NightCatSama** [vuejs/vue-cli#3551]
### What problem does this feature solve?
Support for other typescript configuration files.

For example, I want to use `tsconfig.prod.json` again when `mode = production`.

### What does the proposed API look like?
Can be configured in vue.config.js or babel.config.js

**Comment by LinusBorg** [comment]
you can change the ts-loader settings through the webpack APIs.

https://cli.vuejs.org/guide/webpack.html#simple-configuration

You can visit us on forum.vuejs.org if you need help with the config.
