### ISSUE TITLE
yarn run serve卡住不动了，没有报错信息

### ISSUE THREAD

**Issue by cooper1x** [vuejs/vue-cli#3554]
### Version
3.4.1

### Environment info
```
Windows 10 1809 x64
 Binaries:
    Node: 11.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
```

### Steps to reproduce
yarn run serve，输入这个命令后，卡在23%这个位置，没有报错，yarn lint也没有报错。

### What is expected?
顺利运行，返回一个ip地址，可以打开项目

### What is actually happening?
卡在中途没有反应。

**Comment by sodatea** [comment]
请提供复现代码。

**Comment by cooper1x** [comment]
@sodatea 找到问题了，vue的template的末尾少了一个div。

**Comment by elainema** [comment]
> @sodatea 找到问题了，vue的template的末尾少了一个div。

你是怎么找到了？如果有很多个template的话？我也遇到了这种问题
