### ISSUE TITLE
开发环境 safari 页面 缓存  

### ISSUE THREAD

**Issue by dmkwld** [vuejs/vue-cli#3559]
### Version
3.4.1

### Environment info
```
 System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 11.4.0 - /usr/local/bin/node
    Yarn: 1.6.0 - /usr/local/bin/yarn
    npm: 6.8.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.119
    Firefox: Not Found
    Safari: 12.0.3
  npmPackages:
    vuex-router-sync:  5.0.0 
  npmGlobalPackages:
    @vue/cli: 3.4.1
```

### Steps to reproduce
1、开发环境中 可以 进行热更新，但是safari页面 有缓存，刷新页面，刷新出的是老的缓存数据
2、但是在chrome 中一切正常

### What is expected?
1、开发环境中 safari 不缓存 app.js

### What is actually happening?
1、开发环境中 可以 进行热更新，但是safari页面 有缓存，刷新页面，刷新出的是老的缓存数据
2、但是在chrome 中一切正常

**Comment by dmkwld** [comment]
利用vue-cli3.4.1 创建的新项目

**Comment by sodatea** [comment]
Duplicate of https://github.com/vuejs/vue-cli/issues/2509
这应该是 Safari 的 bug……

**Comment by JackyChan** [comment]
貌似跟预加载插件有关，把preload插件删除即可，在vue.config.js加上以下配置
```
// vue.config.js
module.exports = { 
  chainWebpack: (config) => {
    config.plugins.delete('preload')
  }
}
```
