### ISSUE TITLE
Add an optional ESLint config

### ISSUE THREAD

**Issue by wishinghand** [vuejs/vue-cli#356]
While I'm ok with modifying my .eslintrc, I think it'd be cool for an option with the ESLint opt-in to configure it yourself, similar to this image:

![Configuring ESLint in CLI](http://devnull.guru/content/images/2015/07/eslint-init.png "EsLint options")

**Comment by LinusBorg** [comment]
vue-cli is agnostic to the stuff that templates decide to ask and generate, so you should probbably request this in the repository fo the template you want this for, maybe https://github.com/vuejs-templates/webpack
