### ISSUE TITLE
如何通过git链接下载preset？

### ISSUE THREAD

**Issue by ruimax** [vuejs/vue-cli#3564]
### What problem does this feature solve?
cli项目使用的是download-git-repo 1.0.2版本，这个库在1.1.0的时候才支持使用git链接下载。由于目前项目使用gerrit管理，只能通过git链接下载

### What does the proposed API look like?
vue create --preset direct:https://github.com/ruimax/vue-preset.git --clone  my-project

**Comment by sodatea** [comment]
这个在我们英文文档里有提及，中文版尚未更新：
```bash
vue create --preset direct:ssh://git@my-gitlab-server.com/group/projectname.git --clone my-project
```

我们用的是 download-git-repo@^1.0.2，实际安装时 ^1.0.2 会被 resolve 到 1.1.0，不过感谢建议，下个版本里会更新最低版本号要求。

---

下次如果有使用上的问题建议到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问，我们的 GitHub issues 只用于 Bug 反馈和特性请求
