### ISSUE TITLE
compression styles, update depending, webpack 2 can es2015 import, add rules UglifyJs

### ISSUE THREAD

**Issue by slavikse** [vuejs/vue-cli#357]
Hello!

* Please add compression styles and use plug-ins only on production
```javascript
var postcssOptions = production? {
   plugins: [
     require ( 'postcss-will-change'), // fallback will-change
     require ( 'autoprefixer') (Object.assign ({
       browsers: [ 'ie> 8', 'last 5 versions']
     }, Options.autoprefixer)),
     require ( 'postcss-csso'),
     require ( 'postcss-flexbugs-fixes')
   ]
} {}
```

* Please update depending :)

* Webpack 2 can es2015 import, may be necessary to specify in .babelrc: [ "es2015", { "modules": false}] a babel advises himself to a preset page?

* It is possible as well to add a couple of rules to compress js:
new webpack.optimize.UglifyJsPlugin ({
       minimize: true,
       beautify: false,
})

Thank you! :)

**Comment by egoist** [comment]
Hmm, seems you posted something in the wrong repo?

**Comment by slavikse** [comment]
oh, is not true bearings :(
I hope the author of this wonderful framework still add compression to styles like as noticed :)

**Comment by yyx990803** [comment]
CSS compression is already enabled out of the box when running `npm run build`.
