### ISSUE TITLE
没有自动导入 postcss.config.js

### ISSUE THREAD

**Issue by cleverboy32** [vuejs/vue-cli#3575]
### Version
3.4.1

### Reproduction link
[no](no)

### Environment info
```
mac
```

### Steps to reproduce
我在项目中添加了 postcss.config.js  文件 并写了配置

### What is expected?
css 文件能够成功编译

### What is actually happening?
编译时没有用到我写的 postcss.config......

---
我的配置没有问题，因为当我 css.loaderOptions.postcss 使用时是可以的。但是不是说可以自动引入配置么。。。

**Comment by LinusBorg** [comment]
请查看文件“package.json”

```json
{
  "postcss": {
    "autoprefixer":  {}
  }
}
```

**Comment by cleverboy32** [comment]
是有这个没错 ？ 昂我还是不太明白 ？ 难道哪里还有需要配置的吗？

**Comment by sodatea** [comment]
是因为 package.json 里也有 postcss 字段，优先用了 package.json 里的配置。

**Comment by sodatea** [comment]
如果删掉 package.json 里的相关字段后还不行的话，请提供复现代码。

**Comment by cleverboy32** [comment]
昂 成功了。 谢谢

**Comment by zhouweiccc** [comment]
夫人
