### ISSUE TITLE
Docs: Support to pt-br lang (Re-Open)

### ISSUE THREAD

**Issue by hericlesme** [vuejs/vue-cli#3576]
### What problem does this feature solve?
Add support to pt-br language in the documentation.

### What does the proposed API look like?
The current documentation on https://cli.vuejs.org/guide/ is only available in English, Russian and Chinese. After this change, this will also be available in Portuguese.

_Note: I am willing to keep observing changes in the documentation and keep it updated._

**Comment by yyx990803** [comment]
Thanks for the interest to contribute - please open a pull request, and ideally find another user speaking your language as a reviewer.

**Comment by hericlesme** [comment]
@yyx990803 Would you rather I work on my fork, and then request the merge with everything? Or that I send in parts?

**Comment by yyx990803** [comment]
Preferably when it's all done. Otherwise we'd get notifications every time you push.

**Comment by hericlesme** [comment]
Ok! Already in progress. Coming soon with the changes completed. I will be watching changes in the documentation and updating if necessary.

**Comment by hericlesme** [comment]
@yyx990803 Already finished, just reviewing the files
