### ISSUE TITLE
why production css is not uglify???

### ISSUE THREAD

**Issue by ChangeZhang** [vuejs/vue-cli#358]
npm run build  ..... 

![image](https://cloud.githubusercontent.com/assets/6948367/23052167/1b70c45e-f50a-11e6-8ee3-91e77b905df7.png)

why production css is not uglify???

thanks for all help

**Comment by ChangeZhang** [comment]
optimize-css-assets-webpack-plugin

**Comment by yyx990803** [comment]
Thanks, I've added this plugin into the template itself.
