### ISSUE TITLE
prod build:  global styles after scoped styles in index.html

### ISSUE THREAD

**Issue by bernerha** [vuejs/vue-cli#3586]
### Environment info
```
Environment Info:

  System:
    OS: Linux 4.20 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: Not Found
    npm: 6.8.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
  npmGlobalPackages:
    @vue/cli: 3.4.1
```

### Steps to reproduce
```npm run build```

with global and scoped scss style

### What is expected?
The scoped style get loaded after the global style

### What is actually happening?
The global style get loaded after the scoped style

---
The scoped style is in front of the global style. The problem which I encouter is when the global and the scoped style have the same  specificity. Sometimes it happens and the local style get overwritten by a global style from a framework.

See https://www.w3.org/TR/selectors-3/#specificity

**Comment by LinusBorg** [comment]
Hi  

Thanks for filing this issue! Could you please provide a small reporduction on jsfiddle.net so we can debug this without trying to replicate this ourselves?`

That would be very helpful, thanks!

**Comment by bernerha** [comment]
Okay, I found the reason.
We used following for optimization:

```
optimization: {
    splitChunks: {
        maxAsyncRequests: 2,
        maxInitialRequests: 5,
        maxSize: 900000
    }
}
```

After using the `maxSize` only on the `.js` the `.css` get in one file and in the correct order.
 
```
optimization: {
            splitChunks: {
                maxAsyncRequests: 2,
                maxInitialRequests: 5,
                chunks: 'all',
                cacheGroups: {
                    js: {
                        maxSize: 900000,
                        test: /\.js$/,
                    }
                }
            }
        }
```

Maybe a Problem with Webpack or not. Idk the whole code :)
