### ISSUE TITLE
Can I build a node server with vue ui

### ISSUE THREAD

**Issue by zangxx66** [vuejs/vue-cli#3592]
### What problem does this feature solve?
I want to build a node server with vue ui.It will be more convenient to use.Otherwise I need to enter the command every time

### What does the proposed API look like?
I hope I can build it on my PC

**Comment by LinusBorg** [comment]
If by "node server" you mean a web server / Api server:

no. There's not special feature for this and we won't support it.

**Comment by sodatea** [comment]
Did you mean . https://github.com/egoist/vue-cli-gui ?

**Comment by zangxx66** [comment]
> Did you mean . https://github.com/egoist/vue-cli-gui ?

yes but I need rebuild a win32 program.

**Comment by sodatea** [comment]
Well, just clone that repo and build it yourself.
