### ISSUE TITLE
@vue/cli-plugin-unit-jest fails with error EBADF: bad file descriptor, close

### ISSUE THREAD

**Issue by phil-scott-78** [vuejs/vue-cli#3605]
### Version
3.5.0

### Reproduction link
[https://github.com/phil-scott-78/jest-EBADF](https://github.com/phil-scott-78/jest-EBADF)

### Environment info
```
Windows 10
```

### Steps to reproduce
`npm run unit:test`

### What is expected?
Tests to run

### What is actually happening?
Sporadic failure with an error `EBADF: bad file descriptor`

---
This is due to `write-file-atomic@2.4.2`. Newer versions of jest have been updated to force the version to `2.4.1`. 

See:
* https://github.com/facebook/jest/issues/7709
* https://github.com/npm/write-file-atomic/issues/39

**Comment by sodatea** [comment]
Actually I can't reproduce this issue locally. But according to the discussions in the above link, it may be related to race conditions across multiple processes, so you can try to enable `--runInBand` flag to see if the error disappears:
```
npm run test:unit -- --runInBand
```

**Comment by phil-scott-78** [comment]
Thanks for your quick reply. Ran it with `--runInBand` a few times and it does seem to resolve it. Also seemed to have success with a specific resolution when using yarn. But I don't really want to update build scripts and the such with this work around. Fortunately I can hold off on the upgrade on `vue-cli` for a while until a new version of `@vue/cli-plugin-unit-jest`  is pushed with the latest version of jest.
