### ISSUE TITLE
please, enhance the cli commands parameters!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [vuejs/vue-cli#361]
# please, enhance the cli commands parameters!

```
vue  -v
vue -V
vue --version
vue
```
![vue-v](https://cloud.githubusercontent.com/assets/18028768/23098148/1c300322-f682-11e6-8d95-5c4f2be3179b.png)

**Comment by egoist** [comment]
-v traditionally means verbose I guess. You might check out some disscusions [here](https://news.ycombinator.com/item?id=12687711#up_12688427)
