### ISSUE TITLE
我在一个项目中使用vue-cli3.5又创建了一个新的项目后，内部项目的postcss.config.js 路径读取到

### ISSUE THREAD

**Issue by FAKER-A** [vuejs/vue-cli#3612]
### Version
3.5.0

### Reproduction link
[https://github.com/FAKER-A/vue-table.git](https://github.com/FAKER-A/vue-table.git)

### Environment info
```
  System:
    OS: macOS 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: Not Found
    Safari: 12.0.3
  npmPackages:
    @vue/component-compiler:  3.6.0 
    @vue/component-compiler-utils:  2.6.0 
    babel-helper-vue-jsx-merge-props: ^2.0.3 => 2.0.3 
    babel-plugin-transform-vue-jsx: ^3.7.0 => 3.7.0 
    eslint-plugin-vue: ^5.2.2 => 5.2.2 
    rollup-plugin-vue: ^4.7.2 => 4.7.2 
    vue: ^2.6.8 => 2.6.8 
    vue-eslint-parser: ^6.0.3 => 6.0.3 
    vue-runtime-helpers:  1.0.0 
    vue-template-compiler: ^2.6.8 => 2.6.8 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 3.5.0
```

### Steps to reproduce
1.克隆仓库 
2.进入example文件夹
3.开启项目
4.看到错误信息

### What is expected?
可以正确读取到example文件夹下的postcss.config.js文件

### What is actually happening?
读取不到example下的配置文件，在项目根目录下查找

**Comment by FAKER-A** [comment]
![image](https://user-images.githubusercontent.com/25676164/54120959-20c0b880-4434-11e9-97cf-44e53d00eaee.png)

**Comment by LinusBorg** [comment]
Note: zhe repro link is to the library that seems to cause OP's issue. It's not actually a reproductio. Was confused for a second.

**Comment by FAKER-A** [comment]
@LinusBorg 
Thank you for your reply, I know the reason for the problem.
