### ISSUE TITLE
不兼容ie11

### ISSUE THREAD

**Issue by xie3480469** [vuejs/vue-cli#3616]
### Version
3.5.0

### Environment info
```
 System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Binaries:
    Node: 10.15.3 - D:\Application\Nodejs\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - D:\Application\Nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
使用npm安装最新版的@vue/cli
安装完成之后使用vue ui 工具创建新项目，使用插件为vuex,vue-router,babel，安装完成之后能够在chrome中运行
所有配置项都是默认的vue/cli配置项，没有更改过
在chrome 72中测试没有错误，但是在ie11中测试白屏，并且报错为：[vuex] vuex requires a Promise polyfill in this browser.

### What is expected?
希望官网可以给我答复

### What is actually happening?
修复这个问题，或者有解决的办法

**Comment by ivanov-wai** [comment]
I can confirm, I have the same issue with 3.5.0. The issue disappears if I downgrade to 3.4.1

**Comment by sodatea** [comment]
Should have been fixed in 3.5.1
