### ISSUE TITLE
deprecate tslint

### ISSUE THREAD

**Issue by troy351** [vuejs/vue-cli#3617]
### What problem does this feature solve?
see https://github.com/palantir/tslint/issues/4534

**Comment by LinusBorg** [comment]
> This will not be an immediate deprecation; on the contrary, there is a lot of work to do to ensure a smooth transition to the new tooling without any regressions.

We will not deprecate tslint before they do. Deprecating it would require us to tell people what to use instead, and directing them to use eslint-typescript *now* would leave them with a lot of missing functionality that they relied on from tslint.

We are tracking this situation and will deprecate tslint when the main project does, asuming they/we can ensure a decent alterntive path by then.
