### ISSUE TITLE
图形化界面

### ISSUE THREAD

**Issue by pingmouren** [vuejs/vue-cli#3619]
### Version
3.5.1

### Reproduction link
[https://cli.vuejs.org/zh/guide/creating-a-project.html#vue-create](https://cli.vuejs.org/zh/guide/creating-a-project.html#vue-create)

### Environment info
```
安装3.5.1 不能使用图形化页面
```

### Steps to reproduce
vue ui

### What is expected?
图形化界面正常打开

### What is actually happening?
图形化页面不能打开

**Comment by sodatea** [comment]
请问具体报了什么错？清空缓存再重试或者在隐身窗口打开呢？

**Comment by pingmouren** [comment]
清一下缓存可以了  不好意思  谢谢啦

**Comment by sodatea** [comment]
嗯，这是我们 UI 需要改进的地方，具体进展会在这个 issue 里更新：https://github.com/vuejs/vue-cli/issues/3240
