### ISSUE TITLE
set development browserslist to modern browsers in package.json to simplify debug

### ISSUE THREAD

**Issue by jarek102** [vuejs/vue-cli#3625]
### What problem does this feature solve?
I'm beginner javascript / vue developer.

Out of box debug experience with default vue cli project is not perfect.
When trying to debug application, it was really hard to use console / inspect application state.

After setup it is much easier to debug.

### What does the proposed API look like?
in default `package.json`:

```javascript
"browserslist": [
      "> 1%",
      "last 2 versions",
      "not ie <= 8"
    ]
  }
```
change to:
```javascript
"browserslist": {
    "production": [
      "> 1%",
      "last 2 versions",
      "not ie <= 8"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version"
    ]
  }
```

**Comment by sodatea** [comment]
Thanks for the advice. But for debugging, we've already had source map enabled. So I don't think it's necessary, and it may confuse some people if they want to visit the dev server on IE.
