### ISSUE TITLE
My application does not switch to production mode.

### ISSUE THREAD

**Issue by xereda** [vuejs/vue-cli#363]
I have an application based on vue-cli and webpack. When you run the `npm run build`, the application does not go into **production mode**.

I already checked the documentation and apparently it is correct.

Thank you for your help.

```
vue --version = 2.2.0
vue@2.1.10
webpack@1.14.0
```

![captura de tela 2017-02-20 as 09 35 31](https://cloud.githubusercontent.com/assets/14337850/23125334/fbf0d504-f74f-11e6-903f-b4b15ccd31ce.png)
_with npm run build_

![captura de tela 2017-02-20 as 09 35 15](https://cloud.githubusercontent.com/assets/14337850/23125362/168f1006-f750-11e6-995a-1625c141d578.png)
_with npm run dev_

**Comment by egoist** [comment]
Please open issue in template repo.
