### ISSUE TITLE
Web Component Slot Not Working Properly

### ISSUE THREAD

**Issue by Adam-RapidRTC** [vuejs/vue-cli#3640]
### Version
3.5.1

### Reproduction link
[https://github.com/Adam-RapidRTC/vue-web-component-issue](https://github.com/Adam-RapidRTC/vue-web-component-issue)

### Environment info
```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.820.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.5.1
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.5.1
    @vue/cli-plugin-babel: ^3.5.0 => 3.5.1
    @vue/cli-plugin-typescript: ^3.5.0 => 3.5.1
    @vue/cli-service: ^3.5.0 => 3.5.1
    @vue/cli-shared-utils:  3.5.1
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    typescript: ^3.2.1 => 3.3.3333
    vue: ^2.6.6 => 2.6.9
    vue-class-component: ^6.0.0 => 6.3.2
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-property-decorator: ^7.0.0 => 7.3.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.9
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Build shared-ui and host the js file locally. 
Update shared-ui-consumer index.html line 16 to point to the hosted js file from shared-ui;
`<script defer src="http://[hosted-shared-ui]/shared-ui.js"></script>`

### What is expected?
I would expect the content inside the container to have red text

### What is actually happening?
Vue is cloning the element into the Shadow DOM the .testClass style is being ignored and the text is rendered with a black fill

**Comment by Adam-RapidRTC** [comment]
Here is a link to my forum post on vuejs.org which explains the issue in more detail. 
https://forum.vuejs.org/t/web-component-slot-not-working-properly/58972

**Comment by LinusBorg** [comment]
This is an issue that we would have to solve here:

https://github.com/vuejs/vue-web-component-wrapper/issues

This issue has already been adressed in that repo, but we haven't really been able to take care of this repository in the last months as we concentracted on other things.

I'll try and make time for it next though.

**Comment by A00079** [comment]
> ### Version
> 3.5.1
> 
> ### Reproduction link
> https://github.com/Adam-RapidRTC/vue-web-component-issue
> 
> ### Environment info
> ```
>   System:
>     OS: Windows 10
>     CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
>   Binaries:
>     Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
>     Yarn: Not Found
>     npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
>   Browsers:
>     Edge: 41.16299.820.0
>   npmPackages:
>     @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
>     @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
>     @vue/babel-preset-app:  3.5.1
>     @vue/babel-preset-jsx:  1.0.0-beta.2
>     @vue/babel-sugar-functional-vue:  1.0.0-beta.2
>     @vue/babel-sugar-inject-h:  1.0.0-beta.2
>     @vue/babel-sugar-v-model:  1.0.0-beta.2
>     @vue/babel-sugar-v-on:  1.0.0-beta.2
>     @vue/cli-overlay:  3.5.1
>     @vue/cli-plugin-babel: ^3.5.0 => 3.5.1
>     @vue/cli-plugin-typescript: ^3.5.0 => 3.5.1
>     @vue/cli-service: ^3.5.0 => 3.5.1
>     @vue/cli-shared-utils:  3.5.1
>     @vue/component-compiler-utils:  2.6.0
>     @vue/preload-webpack-plugin:  1.1.0
>     @vue/web-component-wrapper:  1.2.0
>     typescript: ^3.2.1 => 3.3.3333
>     vue: ^2.6.6 => 2.6.9
>     vue-class-component: ^6.0.0 => 6.3.2
>     vue-hot-reload-api:  2.3.3
>     vue-loader:  15.7.0
>     vue-property-decorator: ^7.0.0 => 7.3.0
>     vue-style-loader:  4.1.2
>     vue-template-compiler: ^2.5.21 => 2.6.9
>     vue-template-es2015-compiler:  1.9.1
>   npmGlobalPackages:
>     @vue/cli: Not Found
> ```
> 
> ### Steps to reproduce
> Build shared-ui and host the js file locally.
> Update shared-ui-consumer index.html line 16 to point to the hosted js file from shared-ui;
> `<script defer src="http://[hosted-shared-ui]/shared-ui.js"></script>`
> 
> ### What is expected?
> I would expect the content inside the container to have red text
> 
> ### What is actually happening?
> Vue is cloning the element into the Shadow DOM the .testClass style is being ignored and the text is rendered with a black fill
