### ISSUE TITLE
eslint-prettier warn

### ISSUE THREAD

**Issue by halfmoonvic** [vuejs/vue-cli#3641]
### Version
3.5.1

### Reproduction link
[https://github.com/halfmoonvic/test-esint-warn](https://github.com/halfmoonvic/test-esint-warn)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: Not Found
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.5.1
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.5.1
    @vue/cli-plugin-babel: ^3.5.0 => 3.5.1
    @vue/cli-plugin-eslint: ^3.5.0 => 3.5.1
    @vue/cli-plugin-typescript: ^3.5.0 => 3.5.1
    @vue/cli-service: ^3.5.0 => 3.5.1
    @vue/cli-shared-utils:  3.5.1
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1
    @vue/eslint-config-typescript: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.2
    typescript: ^3.2.1 => 3.3.3333
    vue: ^2.6.6 => 2.6.9
    vue-class-component: ^6.0.0 => 6.3.2
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-property-decorator: ^7.0.0 => 7.3.0
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.9
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.0
  npmGlobalPackages:
    @vue/cli: 3.5.1
```

### Steps to reproduce
1. vue create project
2. select options as below
3. npm run serve
4. there will be warn info on the termail

select options:
i have select `Babel` `TypeScript` `Router` `Vuex` `CSS Pre-processors` `Linter / Formatter` `Eslint   Prettier`

after i create the project, i have do nothing, there will be some warn info on the terminal

### What is expected?
there is no warn on terminal 

### What is actually happening?
1. there are some warns on terminal
2. there are some warn at `<script lang="ts">` or `<style lang="scss">`, the warn info is `Parsing error: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>?`
3. the terminal warn info link https://github.com/halfmoonvic/test-esint-warn/blob/master/eslint-warn.png

**Comment by LinusBorg** [comment]
Can#t reproduce this with the provided repository. please delete  your lockfile and reinstall your dependencies

**Comment by halfmoonvic** [comment]
I clone my repo `https://github.com/halfmoonvic/test-esint-warn`, and npm install, same warn info on the terminal

**Comment by LinusBorg** [comment]
Did you delete package-lock.json before?

**Comment by halfmoonvic** [comment]
yeah... I clone repo again and delete the package-lock.json file, after npm run serve, same warn info on the terminal

**Comment by LinusBorg** [comment]
can you try yarn?

**Comment by halfmoonvic** [comment]
there will be warn info on the terminal after i `npm run serve` at the first time.
if i close the terminal and run `npm run serve` again, the warn info disappear.
i don't why, and i dont't want to watch this issue, so i close it
