### ISSUE TITLE
Allow a vue.config.js to dynamically accept scss files.

### ISSUE THREAD

**Issue by Secular12** [vuejs/vue-cli#3648]
### What problem does this feature solve?
I am trying to create a Vue.js component library, which will later be released on npm for future projects of mine to use it. However, I would like the components to have default scss variables, AKA variables marked with the !default flag. Then, whenever I use the component library in a new project I would like to have the ability for the component library to use a unique scss file which may contain overwrites to the scss variables.

I know to add scss file to the libraries vue.config.js file for each component to pull in that file. However, I cannot figure out how to have vue's configuration to use both the default variables file and a project's variables file to "merge" the scss variables.

### What does the proposed API look like?
Perhaps when the vue component library is initiated something that can *merge* with the current config file? So that a project using a component library can add-to its own config file.

```javascript
Vue.config({
  css: {
    loaderOptions: {
      sass: {
        data: `@import "~@/variables.scss"`
      }
    }
  }
})
```

**Comment by LinusBorg** [comment]
>  However, I cannot figure out how to have vue's configuration to use both the default variables file and a project's variables file to "merge" the scss variables.

Document for the user where to import the original variables file from. Then they can do:
```
Vue.config({
  css: {
    loaderOptions: {
      sass: {
        data: `@import "your-package/default-vars.scss"; @import "~@/variables.scss"`
      }
    }
  }
})
```
