### ISSUE TITLE
why import css autoprefixer is not work

### ISSUE THREAD

**Issue by ChangeZhang** [vuejs/vue-cli#365]
![image](https://cloud.githubusercontent.com/assets/6948367/23196210/368ed5e0-f8f3-11e6-9037-88649020a669.png)
![image](https://cloud.githubusercontent.com/assets/6948367/23196236/53370bae-f8f3-11e6-9c5e-4048241d0041.png)

import css autoprefixer is not work. but .vue file css autoprefixer is work!

thanks for all help

**Comment by egoist** [comment]
Please open issue in relevant template repo.

**Comment by li9269391** [comment]
@ChangeZhang 在utils.js，webpack.base.conf.js中加入postcss-loader对样式的处理。[https://segmentfault.com/q/1010000007688548](url)
