### ISSUE TITLE
The environment created by vue-cli cannot determine the type of async function

### ISSUE THREAD

**Issue by leafydream** [vuejs/vue-cli#3654]
### Version
3.5.0

### Reproduction link
[https://github.com/vuejs/vue-cli/issues/3653](https://github.com/vuejs/vue-cli/issues/3653)

### Environment info
```
 System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.13.0 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 73.0.3683.75
    Firefox: 65.0.1
    Safari: 12.0.3
  npmGlobalPackages:
    @vue/cli: 3.5.0
```

### Steps to reproduce
 mounted() {
    let str = Object.getPrototypeOf(this.test1).constructor;
    console.log(str);  // ƒ Function() { [native code] }
},
methods: {
    async test1() {

    }
}

### What is expected?
Solve this problem

### What is actually happening?
Unable to determine type

**Comment by LinusBorg** [comment]
Still no reproduction.

**Comment by sodatea** [comment]
https://github.com/babel/babel/issues/4691
https://github.com/babel/babel/issues/7767
https://github.com/babel/babel/issues/8642

Unless you turn off babel transpiling, there's no way to distinguish a async function from normal functions.
