### ISSUE TITLE
如何按语言分别打包成一个语言文件？

### ISSUE THREAD

**Issue by ristona** [vuejs/vue-cli#3658]
### What problem does this feature solve?
如何配置才能按语言分别打包成一个独立的文件，类似 于ELEMENTUI

### What does the proposed API look like?
每种 语言一个独立的JS文件，并能自动根据所选语言加载匹配的语言JS文件。

**Comment by sodatea** [comment]
感谢关注，但是我们的 GitHub issues 只用于 Bug 反馈和特性请求，如果有使用上的问题建议到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问。
