### ISSUE TITLE
New projects created with the UI not created properly

### ISSUE THREAD

**Issue by everttrollip** [vuejs/vue-cli#3664]
### Version
3.5.1

### Environment info
```
System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.12.0/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: Not Found
    Safari: 12.0.2
  npmGlobalPackages:
    @vue/cli: 3.5.1
```

### Steps to reproduce
Create a starter app (I selected the following plugins: vue-router, vuex, node-sass, babel, eslint, unit-jest, e2e-nightwatch) 

### What is expected?
I expect that the UI will create the project folders (src, public ...) and also install the project dependencies. 

### What is actually happening?
Only the node_modules folder is visible, and no project dependencies are installed. 

---
Create the starter app two times: 1) with vue create in a terminal 2) with vue ui. When you compare the projects, the app installed with the UI is incomplete. Running npm run serve results in an (obvious) error: missing serve script.

**Comment by JohnNiang** [comment]
Same error.

**Comment by pymike00** [comment]
I am facing the same issue with on Manjaro 18.0.4 Illyria, with:

Node 11.11.0 
npm 6.9.0
Vue 3.5.1.

I also know this to be a problem on Ubuntu 18.04, with:
Node 11.12
npm 6.7
Vue 3.5.1

**Comment by l-gothberg** [comment]
Same issue.  Project creation runs as expected from CLI, but using UI fails.

```
System:
    OS: macOS 10.14.3
    CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 11.12.0 - /usr/local/bin/node
    npm: 6.9.0 -  /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 66.0.1
    Safari: 12.0.3
  npmGlobalPackages:
    @vue/cli: 3.5.1
```

**Comment by bulletmark** [comment]
Same problem on up to date Arch Linux with

- node 11.12.0
- npm 6.9.0
- vue 3.5.3

I am trying to setup https://www.sitepoint.com/creating-beautiful-charts-vue-chart-js/ and that very trivial initial setup project runs fine if I run `vue create` manually as per those instructions. I thought I would delete the project and try the new fangled UI using *exactly* the same creation options but it fails as per the description here. I can create the project manually and then run UI to use it but just can not create the project using UI. Repeated all this many times.

Here is the "good" output using `vue create`:

````
ue CLI v3.5.3
? Please pick a preset: Manually select features
? Check the features needed for your project: Babel, Router, Linter
? Use history mode for router? (Requires proper server setup for index fallback in production) Yes
? Pick a linter / formatter config: Basic
? Pick additional lint features: (Press <space> to select, <a> to toggle all, <i> to invert selection)L
int on save
? Where do you prefer placing config for Babel, PostCSS, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No


Vue CLI v3.5.3
✨  Creating project in /home/mark/Data/src/chart-js-demo.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...


> yorkie@2.0.0 install /home/mark/Data/src/chart-js-demo/node_modules/yorkie
> node bin/install.js

setting up Git hooks
done

added 1119 packages from 642 contributors and audited 23495 packages in 17.817s
found 0 vulnerabilities

🚀  Invoking generators...
📦  Installing additional dependencies...

added 38 packages from 28 contributors, updated 2 packages, moved 9 packages and audited 23784 packages in 7.005s
found 0 vulnerabilities

⚓  Running completion hooks...

📄  Generating README.md...

🎉  Successfully created project chart-js-demo.
👉  Get started with the following commands:

 $ cd chart-js-demo
 $ npm run serve

$ ls -l chart-js-demo
total 468
-rw-r--r--   1 mark mark     53 Mar 29 11:37 babel.config.js
drwxr-xr-x 800 mark mark  32768 Mar 29 11:37 node_modules
-rw-r--r--   1 mark mark    545 Mar 29 11:37 package.json
-rw-r--r--   1 mark mark 414110 Mar 29 11:37 package-lock.json
-rw-r--r--   1 mark mark     59 Mar 29 11:37 postcss.config.js
drwxr-xr-x   2 mark mark   4096 Mar 29 11:37 public
-rw-r--r--   1 mark mark    366 Mar 29 11:37 README.md
drwxr-xr-x   5 mark mark   4096 Mar 29 11:37 src

````

Here is the "bad" output using UI:

````
ue CLI v3.5.3
✨  Creating project in /home/mark/Data/src/chart-js-demo.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...


> yorkie@2.0.0 install /home/mark/Data/src/chart-js-demo/node_modules/yorkie
> node bin/install.js

setting up Git hooks
done

added 1119 packages from 642 contributors and audited 23495 packages in 15.535s
found 0 vulnerabilities

🚀  Invoking generators...
📦  Installing additional dependencies...

audited 23495 packages in 5.836s
found 0 vulnerabilities

⚓  Running completion hooks...

📄  Generating README.md...

🎉  Successfully created project chart-js-demo.
👉  Get started with the following commands:

 $ cd chart-js-demo
 $ npm run serve

$ ls -l chart-js-demo
total 428
drwxr-xr-x 790 mark mark  28672 Mar 29 11:22 node_modules/
-rw-r--r--   1 mark mark    211 Mar 29 11:22 package.json
-rw-r--r--   1 mark mark 399654 Mar 29 11:22 package-lock.json
-rw-r--r--   1 mark mark    145 Mar 29 11:22 README.md
````

**Comment by skillnull** [comment]
Same error.

**Comment by bulletmark** [comment]
@hito read the words here. Clearly this bug has been fixed so it is likely you are running an older version of vue-cli.

**Comment by daamsie** [comment]
Hmm, just updated to v3.11.0 after reading this issue report. Tried creating another project and still have the same issue. The created package.json looks like this:

`{
  "name": "myproject",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.11.0",
    "@vue/cli-plugin-e2e-cypress": "^3.11.0",
    "@vue/cli-plugin-eslint": "^3.11.0",
    "@vue/cli-plugin-pwa": "^3.11.0",
    "@vue/cli-plugin-unit-mocha": "^3.11.0",
    "@vue/cli-service": "^3.11.0"
  }
}`

Trying to run npm run serve results in 
`npm ERR! missing script: serve`

There are only three files in the project folder: 
package.json, package-lock.json and README.md
