### ISSUE TITLE
With `useBuiltIns` option, required direct setting of `corejs` option

### ISSUE THREAD

**Issue by DemoHu** [vuejs/vue-cli#3675]
With `useBuiltIns` option, required direct setting of `corejs` option
                                                                                   98% after emitting CopyPlugin
 ERROR  Failed to compile with 36 errors                                                                                                                 10:20:25
These dependencies were not found:

* core-js/modules/es6.array.iterator in ./src/main.js, ./src/webapp/main.js
* core-js/modules/es6.function.name in ./src/main.js
* core-js/modules/es6.number.constructor in ./src/assets/js/utils.js
* core-js/modules/es6.object.assign in ./src/main.js, ./src/webapp/main.js
* core-js/modules/es6.object.to-string in ./src/main.js, ./src/assets/js/utils.js and 2 others
* core-js/modules/es6.promise in ./src/main.js, ./src/webapp/main.js
* core-js/modules/es6.regexp.match in ./src/assets/js/utils.js
* core-js/modules/es6.regexp.replace in ./src/main.js, ./src/assets/js/gt.js and 3 others
* core-js/modules/es6.regexp.split in ./src/assets/js/utils.js
* core-js/modules/es6.regexp.to-string in ./src/main.js, ./src/assets/js/utils.js and 1 other
* core-js/modules/es6.string.includes in ./src/store.js, ./src/main.js and 2 others
* core-js/modules/es6.string.iterator in ./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--12-0!./node_modules/_babel-loader@8.0.5@babel-loader/lib!./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.7.0@vue-loader/lib??vue-loader-options!./src/views/assets/Index.vue?vue&type=script&lang=js&
* core-js/modules/es6.typed.uint8-array in ./src/assets/js/utils.js
* core-js/modules/es7.array.includes in ./src/store.js, ./src/main.js and 3 others
* core-js/modules/es7.promise.finally in ./src/main.js, ./src/webapp/main.js
* core-js/modules/web.dom.iterable in ./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--12-0!./node_modules/_babel-loader@8.0.5@babel-loader/lib!./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.7.0@vue-loader/lib??vue-loader-options!./src/views/assets/Index.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save core-js/modules/es6.array.iterator core-js/modules/es6.function.name core-js/modules/es6.number.constructor core-js/modules/es6.object.assign core-js/modules/es6.object.to-string core-js/modules/es6.promise core-js/modules/es6.regexp.match core-js/modules/es6.regexp.replace core-js/modules/es6.regexp.split core-js/modules/es6.regexp.to-string core-js/modules/es6.string.includes core-js/modules/es6.string.iterator core-js/modules/es6.typed.uint8-array core-js/modules/es7.array.includes core-js/modules/es7.promise.finally core-js/modules/web.dom.iterable

**Comment by Jabbar2010** [comment]
The same issue

**Comment by agrass-GitHub** [comment]
同样

**Comment by SGrondin** [comment]
It seems to be due to https://github.com/babel/babel/pull/9616

I fixed it by adding `"@babel/parser": "<7.4.0",` to my dependencies. That forces `parcel-bundler` to resolve to @babel/parser 7.3. And with that the problem is fixed. I'll revisit this in a month or two once the Babel people fix the problem.

```
npm ls @babel/parser
├─┬ @babel/core@7.3.4
│ ├── @babel/parser@7.3.4  deduped
│ ├─┬ @babel/template@7.4.0
│ │ └── @babel/parser@7.4.0
│ └─┬ @babel/traverse@7.4.0
│   └── @babel/parser@7.4.0
├── @babel/parser@7.3.4
└─┬ parcel-bundler@1.11.0
  └── @babel/parser@7.3.4  deduped
```

Other links discussing this problem:
https://stackoverflow.com/questions/55251983/what-does-this-error-mean-with-usebuiltins-option-required-direct-setting-of
https://github.com/parcel-bundler/parcel/issues/2820
https://github.com/vuejs/vue-cli/issues/3678
https://github.com/apollographql/react-apollo/issues/2886

**Comment by aa-ziyi** [comment]
https://github.com/vuejs/vue-cli/issues/3678

babel.config.js
 presets: [['@vue/app', { useBuiltIns: 'entry' }]]

**Comment by ajayugq** [comment]
> [# 3678](https://github.com/vuejs/vue-cli/issues/3678)
> 
> cambiar los 
> presets de babel.config.js : [['' @ vue / app ', {useBuiltIns:' entrada '}]]

si funciona ,  yo pensando que era por problema de core-js o babel, aunque creo que lo corrigieron en la ultima versión de babel.
