### ISSUE TITLE
event-stream-3.3.6.tgz 404

### ISSUE THREAD

**Issue by suconghou** [vuejs/vue-cli#3679]
### Version
3.5.1

### Environment info
```
yarn 1.13.0 
node v11.12.0
```

### Steps to reproduce
yarn global add @vue/cli-service-global got 404 error

### What is expected?
install @vue/cli-service-global success

### What is actually happening?
error An unexpected error occurred: "https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/Users/admin/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Comment by sodatea** [comment]
Please run `yarn cache clean` and try again.
`event-stream@3.3.6` is a malicious package and was unpublished from npm months ago. Now none of our dependencies depends on it. So there must be a cache issue in your environment that causes such incorrect resolution.
