### ISSUE TITLE
‘vue list’Command execution（使用vue list出现问题？）

### ISSUE THREAD

**Issue by piaohan** [vuejs/vue-cli#368]
API rate limit exceeded for 116.216.128.235. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

The solution?
-----------------
这是我翻译的

API速率限制为116.216.128.235超过。(但这是一个好消息:经过身份验证的请求得到更高的速率限制。查看更多细节的文档)。

请问 有解决方案吗？O(∩_∩)O谢谢

**Comment by piaohan** [comment]
@znck I use MAC ，use command install   'sudo npm install -g vue-cli',‘evn’ configuration ‘token’？
 -----
     我是在mac环境下，在终端使用 命令‘sudo npm install -g vue-cli’，‘evn’还需要配置token吗？

**Comment by znck** [comment]
With the PR #369 merged, You can do `GITHUB_PERSONAL_ACCESS_TOKEN=yourTokenHere vue list` or export GITHUB_PERSONAL_ACCESS_TOKEN in you `.bashrc`.

**Comment by piaohan** [comment]
@znck Thanks。I try。。But I don't understand why this design? If you can, can you tell me?
-----
O(∩_∩)O谢谢 我尝试下。可是我不理解为何要这么设计？如果可以，能讲讲吗？

**Comment by znck** [comment]
There could be better implementation. 😝
