### ISSUE TITLE
How to use commands to package by module, unnecessary files are not packaged

### ISSUE THREAD

**Issue by WilliamALiang** [vuejs/vue-cli#3689]
### What problem does this feature solve?
There are many modules in my current project, but sometimes some modules do not need to be produced, so it is necessary to exclude the modules that can not be produced, how to use commands to do this?

### What does the proposed API look like?
There are many modules in my current project, but sometimes some modules do not need to be produced, so it is necessary to exclude the modules that can not be produced, how to use commands to do this?

**Comment by LinusBorg** [comment]
Please use forum.vuejs.org for usage questions
