### ISSUE TITLE
vue-cli-service build 路径输出错误 wrong output path

### ISSUE THREAD

**Issue by jimhia** [vuejs/vue-cli#3697]
### Version
3.5.1

### Reproduction link

 请见 Steps to reproduce

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 10.14.2 - C:\Users\jim han\scoop\apps\nodejs-lts\current\node.EXE
    Yarn: 1.13.0 - C:\Users\jim han\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Users\jim han\scoop\apps\nodejs-lts\current\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
vue ui新建项目后编译

use ```vue ui``` to create a new project and compile it.

### What is expected?
``` <script src=js/chunk-vendors.ecd76ec1.js> ```

### What is actually happening?
``` <script src=/js/chunk-vendors.ecd76ec1.js> ```

**Comment by LinusBorg** [comment]
https://cli.vuejs.org/zh/config/#publicpath
