### ISSUE TITLE
Electron isn't launching while start vue-cli-service serve

### ISSUE THREAD

**Issue by LL-LAILAI** [vuejs/vue-cli#3698]
### Version
3.5.1

### Environment info
```
 System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
  Binaries:
    Node: 10.15.1
    Yarn: 1.13.0
    npm: 6.4.1
  Browsers:
    Google Chrome:72.0.3626.121
  npmGlobalPackages:
    @vue/cli: 3.5.1
```

### Steps to reproduce
cross-env NODE_ENV=development vue-cli-service serve && cross-env NODE_ENV=development electron .

### What is expected?
Start the  vue-cli-service serve  and then start the electron .

### What is actually happening?
Only start  vue-cli-service serve and did not start electron .

**Comment by LinusBorg** [comment]
The second command would only be run after the dev server has exited. 

I recommend to run bitch commands with a utility like the "concurrently" package, but that's outside of the scope of this repository.
