### ISSUE TITLE
Where to load CSS for v-cloak?

### ISSUE THREAD

**Issue by sszigeti** [vuejs/vue-cli#37]
After `vue init webpack my-project` and `npm run dev` I couldn't figure out where to put the usual `[v-cloak] { display: none }`, because even if I used something like `require('./assets/cloak.css')` I still saw my vue placeholders for a second.

Currently I have a `<style>` tag in my index.html which fixes this cloaking issue, but if there's a way to load static content like 3rd party stylesheets with the dev server, I'd really appreciate if someone could show an example code.

**Comment by yyx990803** [comment]
You can add it to the style section of your main `App.vue`. Or if you prefer having a separate file for global css you will need to configure appropriate loader for requiring css files.
