### ISSUE TITLE
`vue add typescript` fails with `applyTS is not a function`

### ISSUE THREAD

**Issue by Evil-Me** [vuejs/vue-cli#3705]
### Version
3.5.1

### Environment info
```
 System:
    OS: macOS 10.14.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 72.0.3626.121
    Firefox: 66.0
    Safari: 12.0.3
  npmPackages:
    @storybook/vue:  4.1.14 
    @vue/babel-preset-app:  3.0.0-rc.3 
    @vue/cli-overlay:  3.0.0-rc.3 
    @vue/cli-plugin-babel: ^3.0.0-rc.3 => 3.0.0-rc.3 
    @vue/cli-plugin-eslint: ^3.0.0-beta.15 => 3.0.0-rc.3 
    @vue/cli-plugin-typescript: ^3.5.1 => 3.5.1 
    @vue/cli-plugin-unit-jest: ^3.0.0-beta.15 => 3.0.0-rc.3 
    @vue/cli-service: ^3.0.0-beta.15 => 3.0.0-rc.3 
    @vue/cli-shared-utils:  3.0.0-rc.3 
    @vue/component-compiler-utils:  1.3.1 
    @vue/eslint-config-standard: ^3.0.0-rc.3 => 3.0.0-rc.3 
    @vue/preload-webpack-plugin:  1.0.0 
    @vue/test-utils: ^1.0.0-beta.16 => 1.0.0-beta.19 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    babel-plugin-transform-vue-jsx:  4.0.1 
    eslint-plugin-vue:  4.5.0 
    jest-serializer-vue:  1.0.0 
    typescript: ^3.3.4000 => 3.3.4000 
    vue: ^2.5.16 => 2.5.16 
    vue-chartjs: ^3.4.0 => 3.4.0 
    vue-cli-plugin-storybook: ^0.5.2 => 0.5.2 
    vue-eslint-parser:  2.0.3 
    vue-head: ^2.1.1 => 2.1.1 
    vue-hot-reload-api:  2.3.0 
    vue-jest:  2.6.0 
    vue-loader:  15.2.4 
    vue-router: ^3.0.1 => 3.0.1 
    vue-style-loader:  4.1.0 
    vue-template-compiler: ^2.5.16 => 2.5.16 
    vue-template-es2015-compiler:  1.6.0 
    vuetify: ^1.0.19 => 1.0.19 
    vuex: ^3.0.1 => 3.0.1 
  npmGlobalPackages:
    @vue/cli: 3.5.1

```

### Steps to reproduce
I have a vue cli 3 project in javascript. We did try to install @vue/cli-plugin-typescript. After the installation the initial configuration wizzards starts. I can select the class component style and use bable alongside. 

### What is expected?
Install and config the plugin correctly

### What is actually happening?
 Use class-style component syntax? Yes
 Use Babel alongside TypeScript for auto-detected polyfills? Yes

 ERROR  TypeError: require(...).applyTS is not a function
TypeError: require(...).applyTS is not a function
    at module.exports (~/path/to/project/node_modules/@vue/cli-plugin-typescript/generator/index.js:70:54)
    at Generator.plugins.forEach (~/.nvm/versions/node/v10.15.3/lib/node_modules/@vue/cli/lib/Generator.js:103:7)
    at Array.forEach (<anonymous>)
    at new Generator (~/.nvm/versions/node/v10.15.3/lib/node_modules/@vue/cli/lib/Generator.js:101:13)
    at runGenerator (~/.nvm/versions/node/v10.15.3/lib/node_modules/@vue/cli/lib/invoke.js:116:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by LinusBorg** [comment]
You are using *very* outdated packages (beta versions) of the core plugins.

Your outdated version of `@vue/cli-plugin-eslint` doensn't have a function which the current `@vue/cli-plugin-typescript` plugin expects.

Solution: update your dependencies.
