### ISSUE TITLE
vue init webpack project_name

### ISSUE THREAD

**Issue by w3cteching** [vuejs/vue-cli#371]
`sudo vue init webpack vue_webpack_pro

  This will install Vue 2.x version of the template.

  For Vue 1.x use: vue init webpack#1.0 vue_webpack_pro

**⠴ downloading template**`

Installation has been stopped in the "downloading template" this position, I do not know why, thank the gods of the instructions

end:Finally reported a mistake "vue-cli · Failed to download repo vuejs-templates / webpack: connect ETIMEDOUT 192.30.252.122:443"

note:I use the system environment is: mac, node environment: 6.9.1

**Comment by posva** [comment]
Hi!, Unfortunately, the timeout is unrelated to vue-cli 
It may be an issue with your network connection
