### ISSUE TITLE
Vue not being externalized despite using `--target lib` with `vue-cli-service build`

### ISSUE THREAD

**Issue by eldilibra** [vuejs/vue-cli#3718]
### Version
3.5.1

### Environment info
```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: Not Found
    Safari: 12.0.3
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Build with `vue-cli-service build --target lib index.js`

### What is expected?
After another project imports my library, that project's `node_modules/my-library/node_modules` does not contain `vue`.

### What is actually happening?
`node_modules/my-library/node_modules/vue` exists.

Note that this library also depends on `vuex`.

**Comment by sodatea** [comment]
"externalized" only indicates that the bundle file does not contain the Vue source code, while contents of `node_modules` are only determined by your `package.json`. These are two different concepts.

**Comment by eldilibra** [comment]
Thanks, and sorry for the uninformed question here. I solved this issue by adding `vue` to my `peerDependencies` in `package.json`.
