### ISSUE TITLE
使用vue-cli脚手架工具构建时，一直卡在download template问题

### ISSUE THREAD

**Issue by w3cteching** [vuejs/vue-cli#372]
`我用npm install vue-cli -g p 安装完，但用vue init webpack pro_name时，一直卡在了那个download template那里，最终报了一个vue-cli · Failed to download repo vuejs-templates/webpack: connect ETIMEDOUT 192.30.252.122:443这个错误`
我的系统环境：mac,node:6.9.1,npm使用的是淘宝镜像，希望大神们能指点一二，不知道尤大有人给您反馈过这个问题没有，刚才看了issues，好像没有这个问题

**Comment by xCss** [comment]
同遇到这个问题:
```bash
$ vue init webpack project_name

  This will install Vue 2.x version of the template.

  For Vue 1.x use: vue init webpack#1.0 project_name

   vue-cli · Failed to download repo vuejs-templates/webpack: connect ETIMEDOUT 192.30.253.112:443

```

**Comment by PeakTai** [comment]
我也遇到了，为什么要做成即时下载的呢，可以将模板集成在vue-cli里面吗？

**Comment by posva** [comment]
Duplicate of #371

**Comment by w3cteching** [comment]
解决了，我好像以前改过hosts,把改过的hosts删除了，即好了
