### ISSUE TITLE
no-unsafe-inline for styles

### ISSUE THREAD

**Issue by vanhumbeecka** [vuejs/vue-cli#3720]
### What problem does this feature solve?
There is already an --no-unsafe-inline attribute for building with Vue Cli so no unsafe-inline SCRIPTS are there.
However, I'm facing the problem of having unsafe-inline STYLES now in my production-build output from vendor-dependencies (not my fault).

This could help in building CSP-compatible output builds.

### What does the proposed API look like?
vue-cli-script build --no-unsafe-inline (where "no-unsafe-inline" is for BOTH scripts AND styles. Not only scripts)

**Comment by LinusBorg** [comment]
`--nounsafe-lines` only refers to inline scripts that vue-cli itself injects during build (I think mainly for Safari workarounds in some place).

We can't detect and block adding inline scripts during runtime of your app from vendor depenencies.

**Comment by vanhumbeecka** [comment]
Ok, thanks for the clarification. I thought the setting was also able to 'convert' some the inline scripts...
