### ISSUE TITLE
Set "@/" relative to package in monorepo

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vue-cli#3723]
### What problem does this feature solve?
Right now, if you have a monorepo, the "@/" shortcut is always relative to the package that currently runs the command, i.e. `vue-cli-service serve`. This prevents all other packages from using "@/". 

For example, assuming the following project structure `@/module1` inside `some_other_package`'s `main.js` would resolve to `main_package/src/` instead of `some_other_package/src/`.

```
- root
  - packages
    - main_package
      - src/
      - package.json
    - some_other_package
      - src/
        - main.js
        - module1.js
      - package.json
```

### What does the proposed API look like?
The vue-cli could check for the existance of `package.json`, and if found use that directory for the root for the alias.

**Comment by LinusBorg** [comment]
> the "@/" shortcut is always relative to the package that currently runs the command,

Not quite, it's relative to the current working directory. So if you run the command in a page subfolder of your monorepo, the alias woll resolve correctly. 

And if that's lacking conveniences for you, you can always replace the alias with your own implementation with `chainWebpack` or `xonfigureWebpack`

**Comment by johannes-z** [comment]
> Not quite, it's relative to the current working directory. So if you run the command in a page subfolder of your monorepo, the alias woll resolve correctly.

I know, that's what I meant. The package I run is the current working directory, so the alias in all the other packages won't work anymore, as it resolves to the current working directory, rather than it's own package root.

> And if that's lacking conveniences for you, you can always replace the alias with your own implementation with `chainWebpack` or `xonfigureWebpack`

While it's true that I could override the aliases, could you consider adding it as a default to the vue-cli? The alias could resolve to the package root (i.e. the folder where the package.json resides), and fall back to the cwd if there is no package.json?

**Comment by LinusBorg** [comment]
I think that's simply not possible, since webpack aliases can't be dynamic hey only accept a string, so can't respect any requirements that are only known at runtime.

**Comment by LinusBorg** [comment]
As a step back: Why is this behaviour a problem in a monorepo? Typically, you wouldn't  import raw source from other packages, instead you would link packages with `npm link` and consume built versions, where alias paths are no longer included, no?

**Comment by johannes-z** [comment]
> I think that's simply not possible, since webpack aliases can't be dynamic, they only accept a string.

Hm I see what you mean, this is why I wasn't able to provide an alias via e.g. `chainWebpack` that's dynamic.

> As a step back: Why is this behaviour a problem in a monorepo?

Here is why it's a problem: I'm using `lerna` to manage my monorepo. So in my example I have two packages in my monorepo, one of which acts as the main package. This allows me to finish `package A`, and then work on `package B` that has a dependency on `package A`. While I develop `package B` I usually use `vue-cli-service serve` in `package B`. This, of course, breaks the webpack aliases in `package A` (because the cwd is different).

Even if I would run a main script from the monorepo's root directory, the cwd would still resolve to that directory, so the aliases in the packages wouldn't work either, right?

> Typically, you wouldn't import raw source from other packages, instead you would link packages with `npm link` and consume built versions, where alias paths have already been preprocessed by webpack, no?

Yes, that's what I was thinking too. I build `package A` and add the following to the package's `package.json` `"main": "dist/property-pane.common.js"`, right? `package A` can be built like this without a problem, but building `package B` results in an error:

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript
heap out of memory
```

This might be a completely unrelated error, but it just made aware that dynamic aliases could be useful!

**Comment by LinusBorg** [comment]
This error is pretty surely unrelated to webpack aliases, yes, at most is tangenially related only. 

Did you link package A into package B with `link`?


Either way this seems to drift off into a support question, so feel free to ping me about it on forum.vuejs.org

This issue can be closed i think.

**Comment by brijesh-k-bharattechlabs-com** [comment]
@johannes-z have you find any solution of the problem as i am facing the same?

**Comment by Nikkolast88** [comment]
me too!

**Comment by Nikkolast88** [comment]
@brijesh-k-bharattechlabs-com 
[https://github.com/vercel/turborepo/discussions/620](url)
