### ISSUE TITLE
yarn serve failed after adding resolve option in vue.config.js vue cli 3

### ISSUE THREAD

**Issue by lotfikamel** [vuejs/vue-cli#3724]
i'm triying to create an alias in vue.config.js : 
var path = require('path');

module.exports = {

	resolve : {

		alias : {
			'core' : path.resolve(__dirname, '../core')
		}
	}
}

then i run : yarn serve

and this is the result : 

 ERROR  Invalid options in vue.config.js: "resolve" is not allowed

please help !

**Comment by sodatea** [comment]
You need to wrap that into the `configureWebpack` field.
https://cli.vuejs.org/guide/webpack.html#simple-configuration
