### ISSUE TITLE
service-worker.js error

### ISSUE THREAD

**Issue by BusyHe** [vuejs/vue-cli#373]
vue-cli 2.0 

npm run dev 

![image](https://cloud.githubusercontent.com/assets/17348825/23240571/25807e46-f9a9-11e6-9efa-87a84e497a56.png)

how it happened?

**Comment by egoist** [comment]
Support questions are better asked on StackOverflow or Forums.

**Comment by BusyHe** [comment]
@egoist I don't understand what you say

**Comment by egoist** [comment]
The issue tracker is reserved for vue-cli related bug report or feature request, but your issue is a general webpack question, if you think it's a bug you can re-open it in webpack template repo (with minimal repro of course).

**Comment by BusyHe** [comment]
ok，thanks
