### ISSUE TITLE
vue-cli-service build --watch runs in development and ignores publicPath

### ISSUE THREAD

**Issue by ZaidBarghouthi** [vuejs/vue-cli#3731]
### Version
3.5.3

### Reproduction link
[https://github.com/ZaidBarghouthi/vue-cli-index-path-issue](https://github.com/ZaidBarghouthi/vue-cli-index-path-issue)

### Environment info
```
vue info doesn't work! 

Usage: vue <command> [options]

Options:

  -V, --version                         output the version number
  -h, --help                            output usage information

```

### Steps to reproduce
see README in repo.

### What is expected?
```vue-cli-service build --watch``` runs in development mode and **indexPath** is not ignored! 

```build --watch``` should either run in development mode and not ignore **indexPath**, or it should run in production by default!

### What is actually happening?
```vue-cli-service build --watch```  runs in development mode and **indexPath** is ignored

**Comment by fnick851** [comment]
Were you able to resolve this? I also need it to NOT ignore indexPath when running in development mode.

**Comment by ZaidBarghouthi** [comment]
no!

**Comment by fnick851** [comment]
It is likely a Vue CLI issue. There are work arounds.
You can find details here: https://github.com/vuejs/vue-cli/issues/2327
