### ISSUE TITLE
npm run serve stops building development server when it gets to node_modules\vue-hot-reload-api\dist\index.js

### ISSUE THREAD

**Issue by adamcole123** [vuejs/vue-cli#3733]
### Version
3.5.3

### Reproduction link
[https://github.com/adamcole123/pharaoh-web-app](https://github.com/adamcole123/pharaoh-web-app)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 AMD A8-7410 APU with AMD Radeon R5 Graphics
  Binaries:
    Node: 11.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3
    @vue/babel-preset-app:  3.5.3
    @vue/babel-preset-jsx:  1.0.0-beta.3
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3
    @vue/babel-sugar-inject-h:  1.0.0-beta.3
    @vue/babel-sugar-v-model:  1.0.0-beta.3
    @vue/babel-sugar-v-on:  1.0.0-beta.3
    @vue/cli: ^3.5.3 => 3.5.3
    @vue/cli-overlay:  3.5.1
    @vue/cli-plugin-babel: ^3.5.0 => 3.5.3
    @vue/cli-plugin-eslint: ^3.5.0 => 3.5.1
    @vue/cli-service: ^3.5.3 => 3.5.3
    @vue/cli-shared-utils:  3.5.1
    @vue/cli-ui:  3.5.3
    @vue/cli-ui-addon-webpack:  3.5.3
    @vue/cli-ui-addon-widgets:  3.5.3
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    bootstrap-vue: ^2.0.0-rc.15 => 2.0.0-rc.16
    eslint-plugin-vue: ^5.0.0 => 5.2.2
    express-vue: ^5.8.2 => 5.8.2
    vue: ^2.6.9 => 2.6.10
    vue-axios: ^2.1.4 => 2.1.4
    vue-cal: ^1.40.4 => 1.44.0
    vue-cli-plugin-apollo:  0.19.2
    vue-eslint-parser:  2.0.3
    vue-functional-data-merge:  2.0.7
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-pronto:  1.8.2
    vue-router: ^3.0.2 => 3.0.2
    vue-server-renderer:  2.6.10
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vueify:  9.4.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Download code from github, run npm install in directory to install packages, run npm run serve to attempt to start the dev server with vue/cli. That's how i recreated it.

### What is expected?
The vue/cli dev environment should build fully then allow me to access a dev build of my app on localhost.

### What is actually happening?
The dev environment starts building then stops around 20-30%. My tests have stopped on node_modules\vue-hot-reload-api\dist\index.js twice but not every time, the other directories i can not remember.

**Comment by adamcole123** [comment]
Any suggestions guys? I can't work on my project without this being fixed.

**Comment by sodatea** [comment]
I'm sorry but I can't reproduce this issue on my local environment. Any error messages?

**Comment by adamcole123** [comment]
@sodatea I can't reproduce it on my other PC either. There aren't any error messages, it just stops building but says that it is still building so im stumped. I have ran `npm uninstall -g @vue/cli`, then reinstalled it globally, i have deleted all of my node modules from that package and then reinstalled and it didnt fix it. Does vue stop building if there are errors in the code? or does it just build the entire thing and then tell you if there are errors?

**Comment by adamcole123** [comment]
@sodatea try it now. I managed to reproduce it on my second PC using the project that is currently up on the repo in the reproduction link.

**Comment by sodatea** [comment]
@adamcole123 Anything I can refer to? The reproduction repository seems not quite right. There're several errors in https://github.com/adamcole123/pharaoh-web-app/blob/master/src/components/DashboardComponent.vue (multi-root element in template, syntax error in `data` function)

**Comment by adamcole123** [comment]
Wow VSCode didn't tell me about the syntax error. Must be the extensions i use for Vue. That fixed it thanks. I'd still consider this a bug as the command line didn't tell me anything was wrong when it stopped building.

Adam Cole

________________________________

**Comment by LinusBorg** [comment]
> I'd still consider this a bug as the command line didn't tell me anything was wrong when it stopped building.

There's little for _us_ do to in this repo if webpack doesn't display the error though.
