### ISSUE TITLE
执行yarn serve期间，一直在building

### ISSUE THREAD

**Issue by ristona** [vuejs/vue-cli#3734]
### Version
3.5.3

### Environment info
```
WIN10
VSCODE
```

### Steps to reproduce
1、创建了一个MPA，3个page，具体配置附后
2、执行yarn build正常且没有任何警告或错误
3、执行yarn serve，一直在building，界面情况如下：
yarn run v1.13.0
$ vue-cli-service serve --port 10002
 INFO  Starting development server...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
 35% building 215/293 modules 78 active ...\src\ui\src\infrastructure\Authorize.ts
4、每次执行yarn serve停止的比例不同。
具体cue-config.js代码如下：
const path = require('path')

module.exports = {
  pages: {
    index: {
      entry: 'src/pages/Index/main.js',
      template: 'src/pages/Index/template.html',
      filename: 'index.html',
      title: 'SMES',
      chunks: ['index-vendors', 'index-common', 'index']
    },
    // 当使用只有入口的字符串格式时，
    // 模板会被推导为 `public/subpage.html`
    // 并且如果找不到的话，就回退到 `public/index.html`。
    // 输出文件名会被推导为 `subpage.html`。
    signin: {
      entry: 'src/pages/signin/main.js',
      template: 'src/pages/signin/template.html',
      filename: 'signin/index.html',
      title: 'AuthorizationSErver',
      chunks: ['signin-vendors', 'signin-common', 'signin']
    },
    models: {
      entry: 'src/pages/models/main.js',
      template: 'src/pages/models/template.html',
      filename: 'models/index.html',
      title: 'Models',
      chunks: ['models-vendors', 'models-common', 'models']
    },
  },

  configureWebpack: config => {
    // https://www.jianshu.com/p/741d9c98c395
    optimization: {
      runtimeChunk: {
        name: 'manifest'
      }
      splitChunks: {
        cacheGroups: {
          // default: false
          vendors: false
          vendor: {
            test: /[\\/]node_modules[\\/]/
            chunks: 'initial'
            enforce: true
            priority: 10
            name: 'vendor'
          }
          common: {
            chunks: "all"
            minChunks: 2
            name: 'common'
            enforce: true
            priority: 5
          }
        }
      }
    }

  },
  chainWebpack: config => {
    // Deleting default entry
    delete config.entry.app

    const svgRule = config.module.rule('svg')
    // 清除已有的所有 loader。
    // 如果你不这样做，接下来的 loader 会附加在该规则现有的 loader 之后。
    svgRule.uses.clear()

    // 添加要替换的 loader
    svgRule
      .exclude
      .add(path.resolve(__dirname, 'src/icons'))
      .end()
      .use('vue-svg-loader')
      .loader('vue-svg-loader')

    config.module.rule('svg-icon')
      .test(/\.(svg)(\?.*)?$/)
      .include
      .add(path.resolve(__dirname, 'src/icons'))
      .end()
      .use('svg-sprite-loader')
      .loader('svg-sprite-loader')
      .tap(options => {
        options = {
          symbolId: 'icon-[name]',
          extract: true,
          spriteFilename: svgPath => `sprite${svgPath.substr(-4)}`

        }
        return options
      })

    config.externals({
      'vue': 'Vue',
      'vue-router': 'VueRouter',
      'element-ui': 'ELEMENT',
      'lodash': '_'
    })

  },

}

### What is expected?
yarn serve执行成功。

### What is actually happening?
一直在building.
希望有错误日志可以查看原因。

**Comment by ristona** [comment]
原因找到了，是因为其中一个vue的templete的HTML没有成对出现，少了一个</div>。
但仍然建议能提供一些提示帮助。最起码不能一直building。

**Comment by sodatea** [comment]
请提供一个可以运行的复现。

**Comment by ristona** [comment]
抱歉，重现不了。
另外有可能跟死循环有关。我先关掉，以后重现，我再上传代码。

**Comment by ristona** [comment]
暂时无法重现
