### ISSUE TITLE
在MPA下，pages配置节点下的chunks无效

### ISSUE THREAD

**Issue by ristona** [vuejs/vue-cli#3735]
### Version
3.5.3

### Environment info
```
WIN10
VSCODE
```

### Steps to reproduce
1、配置MPA
2、希望各个页面独立生成common和vendor
具体配置如下：
pages: {
    index: {
      entry: 'src/pages/Index/main.js',
      template: 'src/pages/Index/template.html',
      filename: 'index.html',
      title: 'SMES',
      chunks: ['index-vendors', 'index-common', 'index']
    },
    // 当使用只有入口的字符串格式时，
    // 模板会被推导为 `public/subpage.html`
    // 并且如果找不到的话，就回退到 `public/index.html`。
    // 输出文件名会被推导为 `subpage.html`。
    signin: {
      entry: 'src/pages/signin/main.js',
      template: 'src/pages/signin/template.html',
      filename: 'signin/index.html',
      title: 'AuthorizationSErver',
      chunks: ['signin-vendors', 'signin-common', 'signin']
    },
    models: {
      entry: 'src/pages/models/main.js',
      template: 'src/pages/models/template.html',
      filename: 'models/index.html',
      title: 'Models',
      chunks: ['models-vendors', 'models-common', 'models']
    },
  },

### What is expected?
配置了3个page，希望生成11个文件，分别为：
index-common.js
index-vendor.js
index.js
signin-common.js
signin-vendor.js
signin.js
models-common.js
models-vendor.js
models.js
chunk-common.js
chunk-vendor.js

### What is actually happening?
只生成了5个，分别为：
index.js
signin.js
models.js
chunk-common.js
chunk-vendor.js

**Comment by sodatea** [comment]
首先……你得配置 webpack 的 splitChunks 让 webpack 生成对应的 chunk 文件，才能往页面上加。

这是使用上的问题，下次请先考虑到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问。

另外如果报 bug 的话我们是需要一个可以运行的复现的。

**Comment by libin1991** [comment]
try
```
configureWebpack: config => {
		
    config.optimization.splitChunks.cacheGroups.common={ 
            name: 'chunk-common',
              priority: -20,
              chunks: 'initial',
              minChunks: 200, //   Pages. length still generates chunk-common files. Use a big number, or it 
                                          //     generates chunk-common files.
              reuseExistingChunk: true,
              enforce: true
        }
       ...
```
or

Webpack will default to chunk-vendors for commonChunk. So you need to delete the webpack configuration.
```
chainWebpack: config => {
  config.optimization.delete('splitChunks')
}
```

**Comment by yutent** [comment]
> ### Version
> 3.5.3
> 
> ### Environment info
> ```
> WIN10
> VSCODE
> ```
> ### Steps to reproduce
> 1、配置MPA
> 2、希望各个页面独立生成common和vendor
> 具体配置如下：
> pages: {
> index: {
> entry: 'src/pages/Index/main.js',
> template: 'src/pages/Index/template.html',
> filename: 'index.html',
> title: 'SMES',
> chunks: ['index-vendors', 'index-common', 'index']
> },
> // 当使用只有入口的字符串格式时，
> // 模板会被推导为 `public/subpage.html`
> // 并且如果找不到的话，就回退到 `public/index.html`。
> // 输出文件名会被推导为 `subpage.html`。
> signin: {
> entry: 'src/pages/signin/main.js',
> template: 'src/pages/signin/template.html',
> filename: 'signin/index.html',
> title: 'AuthorizationSErver',
> chunks: ['signin-vendors', 'signin-common', 'signin']
> },
> models: {
> entry: 'src/pages/models/main.js',
> template: 'src/pages/models/template.html',
> filename: 'models/index.html',
> title: 'Models',
> chunks: ['models-vendors', 'models-common', 'models']
> },
> },
> 
> ### What is expected?
> 配置了3个page，希望生成11个文件，分别为：
> index-common.js
> index-vendor.js
> index.js
> signin-common.js
> signin-vendor.js
> signin.js
> models-common.js
> models-vendor.js
> models.js
> chunk-common.js
> chunk-vendor.js
> 
> ### What is actually happening?
> 只生成了5个，分别为：
> index.js
> signin.js
> models.js
> chunk-common.js
> chunk-vendor.js



你好, 我的是  3.5.5版。 可是我在mpa下, 配置了chunks, 根本没生效, 根本没生成 独立的 chunk-common.js 和 chunk-vendor.js。  现在搞的每个js都 1M多, 太可怕了。
