### ISSUE TITLE
@vue/babel-preset-app got error

### ISSUE THREAD

**Issue by GodofHope** [vuejs/vue-cli#3740]
### Version
3.5.4

### Reproduction link
doesn't need

### My solution

I add the @babel/runtime-corejs2 in my devDependencies and everything work fine

### Environment info
```
npmPackages:
    @ant-design/icons-vue:  1.0.1
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3
    @vue/babel-preset-app:  3.5.4
    @vue/babel-preset-jsx:  1.0.0-beta.3
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3
    @vue/babel-sugar-inject-h:  1.0.0-beta.3
    @vue/babel-sugar-v-model:  1.0.0-beta.3
    @vue/babel-sugar-v-on:  1.0.0-beta.3
    @vue/cli-overlay:  3.5.1
    @vue/cli-plugin-babel: ^3.5.4 => 3.5.4
    @vue/cli-plugin-eslint: ^3.5.1 => 3.5.1
    @vue/cli-plugin-pwa: ^3.5.1 => 3.5.1
    @vue/cli-plugin-typescript: ^3.5.3 => 3.5.3
    @vue/cli-service: ^3.5.3 => 3.5.3
    @vue/cli-shared-utils:  3.5.1
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-airbnb: ^4.0.0 => 4.0.0
    @vue/eslint-config-typescript: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    ant-design-vue: ^1.3.7 => 1.3.7
    babel-helper-vue-jsx-merge-props:  2.0.3
    eslint-plugin-vue: ^5.2.2 => 5.2.2
    typescript: ^3.4.1 => 3.4.1
    vue: ^2.6.10 => 2.6.10
    vue-class-component: ^7.0.2 => 7.0.2
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-property-decorator: ^8.1.0 => 8.1.0
    vue-ref:  1.0.6
    vue-router: ^3.0.2 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vue-wechat-title: ^2.0.5 => 2.0.5
    vuex: ^3.1.0 => 3.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
In 3.5.4, @babel/runtime-corejs2 devDependencies was moved, and it cause `npm run serve` failure.

### What is expected?
Build success

### What is actually happening?
a error hint that some files of @babel/runtime-corejs2 not found

**Comment by sodatea** [comment]
1. We need a runnable reproduction
2. How did you get this error? After this commit: https://github.com/vuejs/vue-cli/pull/3730/ I don't think there will be any `@babel/runtime-corejs2` imports injected anymore so it is no longer a necessary dependency.

**Comment by GodofHope** [comment]
I deleted the node_modules folder and run `npm install`, and everything works just fine. Maybe it's my problem..... THX

**Comment by GodofHope** [comment]
SO you guys add it back in 3.5.5? why?

**Comment by sodatea** [comment]
😂because of https://github.com/vuejs/vue-cli/issues/3741
I need some time to figure out the correct fix so have to temporarily revert that commit for now...

**Comment by GodofHope** [comment]
hahaha😂I see, waiting for your 3.5.6(❤ ω ❤)
