### ISSUE TITLE
Throw error when use create --preset [local dir]

### ISSUE THREAD

**Issue by soouup** [vuejs/vue-cli#3744]
### Version
3.5.5

### Environment info
```
System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 10.3.0 - ~/.nvm/versions/node/v10.3.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.1.0 - ~/.nvm/versions/node/v10.3.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 65.0
    Safari: 12.0.2
  npmPackages:
    sd-vue-cli:  0.0.41
  npmGlobalPackages:
    @vue/cli: 3.5.5
```

### Steps to reproduce
vue create --preset ~/Desktop/somePreset.json my-project

### What is expected?
Create a project use the preset which i declare

### What is actually happening?
 ERROR  TypeError: Cannot set property '@vue/cli-service' of undefined
TypeError: Cannot set property '@vue/cli-service' of undefined
    at Creator.create (/Users/tangruijia/.nvm/versions/node/v10.3.0/lib/node_modules/@vue/cli/lib/Creator.js:91:40)

**Comment by soouup** [comment]
somePreset.json:
{
  "useTaobaoRegistry": true,
  "packageManager": "yarn",
  "presets": {
    "spa": {
      "useConfigFiles": false,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-eslint": {
          "config": "standard",
          "lintOn": [
            "save"
          ]
        }
      },
      "router": true,
      "routerHistoryMode": true,
      "vuex": true
    }
  }
}

**Comment by sodatea** [comment]
The preset.json content should be:
```json
{
  "useConfigFiles": false,
  "plugins": {
    "@vue/cli-plugin-babel": {},
    "@vue/cli-plugin-eslint": {
      "config": "standard",
      "lintOn": [
        "save"
      ]
    }
  },
  "router": true,
  "routerHistoryMode": true,
  "vuex": true
}
```

**Comment by soouup** [comment]
Thanks
