### ISSUE TITLE
Error on global install: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by parion** [vuejs/vue-cli#3749]
### Version
3.5.5

### Environment info
```
Can't run since vue-cli is unable to be installed. Here's release info, though.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Node version: v11.13.0
NPM version: v6.7.0
```

### Steps to reproduce
1. Ensure no version of vue/cli is installed.
2. Run `sudo npm i -g @vue/cli` inside Ubuntu's terminal.
3. Observe the `Maximum call stack size exceeded` error.

### What is expected?
`vue-cli` v3.5.5 should be installed globally, giving global access to the `vue` command

### What is actually happening?
The following error message is received:
```
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/usr/local/bin/vue -> /usr/local/lib/node_modules/@vue/cli/bin/vue.js
npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/1872/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> protobufjs@6.8.8 postinstall /usr/local/lib/node_modules/@vue/cli/node_modules/protobufjs
> node scripts/postinstall

2019/04/03 08:55:34.121225 cmd_run.go:876: WARNING: cannot create user data directory: cannot create "/nonexistent/snap/node/1872": mkdir /nonexistent: permission denied
cannot create user data directory: /nonexistent/snap/node/1872: Permission denied
npm WARN ts-node@8.0.3 requires a peer of typescript@>=2.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-tracing@0.5.2 requires a peer of graphql@0.10.x - 14.1.x but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/@vue/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! Maximum call stack size exceeded
```

---
I am currently running into this issue on a clean install of Ubuntu 18.04. I have attempted to clean the cache(`npm cache clean --force`) and rebuild npm (`npm rebuild`). I also attempted to install other npm packages globally, such as `nodemon`, with success.

**Comment by parion** [comment]
After a complete re-install of Ubuntu and node/npm, installing the vue-cli now works. Hate I can't give any more helpful advice for future readers looking to fix this issue, but I'm closing this issue.

**Comment by robschaap242** [comment]
Hi there, I had the identical problem today, with a fresh Ubuntu 18 install. I installed Typescript globally, it didn't work. However, reinstalling NPM, did.

`sudo apt install npm`

**Comment by heikkiket** [comment]
Hello everyone!

I had node installed from snap package. I removed that and installed Node from Nodesource's repository: After that (and running `npm install npm@latest -g`) vue-cli installed correctly. I think snap version was so sandboxed it couldn't actually install stuff to system.

Another option would have been to use Node Version Manager.
