### ISSUE TITLE
有将后端Node框架结合起来的vue脚手架吗？

### ISSUE THREAD

**Issue by ycjcl868** [vuejs/vue-cli#375]
有将后端Node框架结合起来的vue脚手架吗？

**Comment by posva** [comment]
No, but you can probably find out one or start from any existing template.
Next time, please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!
