### ISSUE TITLE
使用cli3 报core-js warning

### ISSUE THREAD

**Issue by elainema** [vuejs/vue-cli#3756]
### Version
3.0.5

### Node and OS info
nodejs:v10.15.1, yarn:1.9.4

### Steps to reproduce
yarn install
yarn serve

### What is expected?
正常运行

### What is actually happening?
报warning：You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you n
eed to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

在择一操作之后依旧warning……………………

---
最早开始使用cli3版本应该是3.0.5，运行正常。最近发现dev和打包都会报core-js的warning，视图升级和卸载cli3，均失败

**Comment by elainema** [comment]
创建全新的hello-wolrd，yarn serve却是正常的！

**Comment by sodatea** [comment]
最新版已经是 3.5.5 了，请更新一下项目依赖（删除 yarn.lock 或者 package-lock.json 并重新安装依赖）。如果仍然有报错请运行 `npm install --save core-js@2` / `yarn add --save core-js@2` 再试试。

**Comment by elainema** [comment]
> 最新版已经是 3.5.5 了，请更新一下项目依赖（删除 yarn.lock 或者 package-lock.json 并重新安装依赖）。如果仍然有报错请运行 `npm install --save core-js@2` / `yarn add --save core-js@2` 再试试。

删除yarn.lock和 package-lock.json，重新安装依赖，解决~~~非常感谢

**Comment by xxholly32** [comment]
@sodatea 

现在corejs已经升级到3了，后面有计划开放配置么？

now，corejs version is update to 3， Do you have any plan to support it.

**Comment by sodatea** [comment]
Will be upgraded in CLI v4, considering it's a breaking change.
