### ISSUE TITLE
unable to install in vue-cli 

### ISSUE THREAD

**Issue by sudhirpandey** [vuejs/vue-cli#3758]
### Version
3.5.5

### Environment info
```
Os:
Linux rhel7.localdomain 3.10.0-862.14.4.el7.x86_64 #1 SMP Fri Sep 21 09:07:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linu

node --version
v10.15.3

npm --version
6.9.0
```

### Steps to reproduce
try to install vue-cli results in error

npm ls -g --depth=0
/root/.nvm/versions/node/v10.15.3/lib
└── npm@6.9.0

npm install -g @vue/cl

### What is expected?
installed vue-cli 

### What is actually happening?
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/root/.nvm/versions/node/v10.15.3/bin/vue -> /root/.nvm/versions/node/v10.15.3/lib/node_modules/@vue/cli/bin/vue.js

> protobufjs@6.8.8 postinstall /root/.nvm/versions/node/v10.15.3/lib/node_modules/@vue/cli/node_modules/protobufjs
> node scripts/postinstall

module.js:550
    throw err;
    ^

Error: Cannot find module '/root/.nvm/versions/node/v10.15.3/lib/node_modules/@vue/cli/node_modules/protobufjs/scripts/postinstall'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm WARN ts-node@8.0.3 requires a peer of typescript@>=2.0 but none is installed. You must install peer dependencies yourself.
npm WARN apollo-tracing@0.5.2 requires a peer of graphql@0.10.x - 14.1.x but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/@vue/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-04T20_12_20_710Z-debug.log

---
Using nvm to fro using different node versions

**Comment by sodatea** [comment]
https://cli.vuejs.org/guide/troubleshooting.html#running-installation-with-sudo-or-as-root
