### ISSUE TITLE
Error with npm run dev

### ISSUE THREAD

**Issue by Joudee** [vuejs/vue-cli#376]
It's tell 'Module build failed: Error: No ESLint configuration found' .
When open 'localhost:8080',the browser shows 'Cannot GET /'.

**Comment by znck** [comment]
Please ask such questions on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue). The issue list is reserved exclusively for bug reports and feature requests.

Thanks.
