### ISSUE TITLE
Environment Variable page does not disclose the requirement of dotenv-webpack

### ISSUE THREAD

**Issue by wisteso** [vuejs/vue-cli#3762]
### Version
3.4.0

### Reproduction link
[https://cli.vuejs.org/guide/mode-and-env.html#using-env-variables-in-client-side-code](https://cli.vuejs.org/guide/mode-and-env.html#using-env-variables-in-client-side-code)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 38.14393.1066.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.4.0
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.4.0
    @vue/cli-plugin-babel: ^3.4.0 => 3.4.0
    @vue/cli-plugin-eslint: ^3.4.0 => 3.4.0
    @vue/cli-service: ^3.4.0 => 3.4.0
    @vue/cli-shared-utils:  3.4.0
    @vue/component-compiler-utils:  2.5.2
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.1.0
    vue: ^2.5.22 => 2.6.3
    vue-axios: ^2.1.4 => 2.1.4
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.1
    vue-loader:  15.6.2
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.3
    vue-template-es2015-compiler:  1.8.2
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Documentation issue

### What is expected?
Disclosure that the .env feature of Vue requires the NPM module dotenv-webpack to be installed into the project

### What is actually happening?
Documentation implies that this feature is built-in to Vue CLI 3 and includes no mention to dotenv-webpack aside from a single line about how to get more details on dotenv parsing rules.

---
Ran into this bug after being unable to debug a problem with my .env files not being loaded, despite following all disclosed requirements (prefix with VUE_APP_ and naming file .env within root dir, etc).

Seems other users have encountered this issue as well https://stackoverflow.com/a/55521419/1060650

**Comment by wisteso** [comment]
Seems this is actually a real bug with Vue CLI.     Not running into this issue with a newly created project on the same machine.

**Comment by sodatea** [comment]
FYI, we didn't use dotenv-webpack.
