### ISSUE TITLE
[Enhancement] Please support "productionTip" in vue.config.js too

### ISSUE THREAD

**Issue by fancydev18** [vuejs/vue-cli#3764]
### What problem does this feature solve?
 Please support "productionTip" in vue.config.js too. Now it gives:

 ERROR  Invalid options in vue.config.js: "productionTip" is not allowed

Related issue: https://github.com/vuejs/vue/issues/7562

### What does the proposed API look like?
vue.config.js new property

**Comment by sodatea** [comment]
Why? It's a runtime configuration.

**Comment by fancydev18** [comment]
I didn't know that makes a difference. Please close if you don't see it useful.

Thanks
