### ISSUE TITLE
vuex2..0   mapActions  

### ISSUE THREAD

**Issue by lijiancheng** [vuejs/vue-cli#377]
when i use vuex2.0   -- mapActions 

the code like this https://vuex.vuejs.org/zh-cn/actions.html 

...mapActions([
      'increment' // 映射 this.increment() 为 this.$store.dispatch('increment')
    ]),

vue-cli  return a error 

-----------------------------------------------------------------------------------------------------------
> node build/dev-server.js

(node:5264) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

 ERROR  Failed to compile with 1 errors                                                                                                                                                             17:21:56

This dependency was not found in node_modules:

* babel-runtime/helpers/extends in ./~/.npminstall/babel-loader/6.3.2/babel-loader/lib!./~/.npminstall/vue-loader/11.1.0/vue-loader/lib/selector.js?type=script&index=0!./src/components/Hello.vue

Did you forget to run npm install --save for it?
> Listening at http://localhost:8080

----------------------------------------------------------------------------------------------------------------

**Comment by posva** [comment]
Update vue-loader
