### ISSUE TITLE
[mini-css-extract-plugin]  warning Conflicting order

### ISSUE THREAD

**Issue by elainema** [vuejs/vue-cli#3771]
### Version
3.0.5

### Reproduction link
[https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order)

### Node and OS info
node: v10.15.3, yarn 1.9.4

### Steps to reproduce
yarn install
yarn run build

### What is expected?
正常打包

### What is actually happening?
打包报warning: chunk offer_create~offer_detail [mini-css-extract-plugin]
Conflicting order between: xxxxxx

---
查看并不影响结果，只是报wanring

另外vue最新cli已升级到3.5.5，当时安装时是3.0.5，本地升级后显示：success Installed "@vue/cli@3.5.5" with binaries，
查看版本依然是3.0.5，想卸载后重新也无法卸载，求助

**Comment by sodatea** [comment]
1. The warnings are from mini-css-extract-plugin, see more detail explanations here: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-415345126 Generally it's due to some import ordering issues in your code base.

------

## The Problem

In your case, there're three such warnings:
```
 warning

chunk offer_create~offer_detail [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Offer/components/application-questions/application-questions.vue?vue&type=style&index=0&id=69b13b08&scoped=true&lang=css&
 * css ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/MutipleEvents.vue?vue&type=style&index=0&id=fe6da6ea&scoped=true&lang=css&

 warning

chunk offer_create~offer_detail [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Editable_Chosen_Offer_Onfocus.vue?vue&type=style&index=0&id=6c9a7e11&scoped=true&lang=css&
 * css ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/MutipleEvents.vue?vue&type=style&index=0&id=fe6da6ea&scoped=true&lang=css&

 warning

chunk offer_create~offer_detail [mini-css-extract-plugin]
Conflicting order between:
 * css ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/OfferWhiteIPModal.vue?vue&type=style&index=0&lang=css&
 * css ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/MutipleEvents.vue?vue&type=style&index=0&id=fe6da6ea&scoped=true&lang=css&
```

Basically they are all complaining that the file `MutipleEvents.vue`'s ordering in the `offer_detail` chunk and `offer_create` chunk are conflicting.

The ordering is very clear in [Create.vue](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Create.vue#L579):
1. `application-questions.vue` before `MutipleEvents.vue`
2. `Editable_Chosen_Offer_Onfocus.vue` before `MutipleEvents.vue`
3. `OfferWhiteIPModal` (imported by `OfferConversionWhiteList`) before `MutipleEvents.vue`

However, the situation is different in [`Detail.vue`](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L199):
1. There're 2 imports of `Payment.vue`([L209](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L209) and [L212](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L212)), which transitively imports `MultipleEvents.vue`
2. `Editable_Chosen_Offer_Onfocus.vue` is transitively imported by [`Targeting.vue`](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L211) and it's between the 2 imports of `Payment.vue`
3. `application-questions.vue` imported by [`Basic.vue`](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L210), also between them.
4. `OfferConversionWhiteList`, imported by [`Tracking.vue`](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L214), is **after** `Payment.vue`, this is conflicting with the ordering in `Create.vue`.

## The Solution

1. Delete [the first occurrence of `./Detail/Payment.vue`](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L209)
2. Correct the name of [the second import of `./Detail/Payment.vue`](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L212) (`submodule_pyament` -> `submodule_payment`)
3. Move [this line](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L214) up above `./Detail/Payment.vue`

------

2. Maybe it's due to you've used different package managers to install Vue CLI. Run `ls -l $(which vue)` in the terminal to see which folder the binary actually links to.

------

**Next time please consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂**

**Comment by elainema** [comment]
> 1. The warnings are from mini-css-extract-plugin, see more detail explanations here: [webpack-contrib/mini-css-extract-plugin#250 (comment)](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250#issuecomment-415345126) Generally it's due to some import ordering issues in your code base.
> 
> ## The Problem
> In your case, there're three such warnings:
> 
> ```
>  warning
> 
> chunk offer_create~offer_detail [mini-css-extract-plugin]
> Conflicting order between:
>  * css ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Offer/components/application-questions/application-questions.vue?vue&type=style&index=0&id=69b13b08&scoped=true&lang=css&
>  * css ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/MutipleEvents.vue?vue&type=style&index=0&id=fe6da6ea&scoped=true&lang=css&
> 
>  warning
> 
> chunk offer_create~offer_detail [mini-css-extract-plugin]
> Conflicting order between:
>  * css ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Editable_Chosen_Offer_Onfocus.vue?vue&type=style&index=0&id=6c9a7e11&scoped=true&lang=css&
>  * css ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/MutipleEvents.vue?vue&type=style&index=0&id=fe6da6ea&scoped=true&lang=css&
> 
>  warning
> 
> chunk offer_create~offer_detail [mini-css-extract-plugin]
> Conflicting order between:
>  * css ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/OfferWhiteIPModal.vue?vue&type=style&index=0&lang=css&
>  * css ./node_modules/css-loader??ref--6-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??postcss!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/MutipleEvents.vue?vue&type=style&index=0&id=fe6da6ea&scoped=true&lang=css&
> ```
> Basically they are all complaining that the file `MutipleEvents.vue`'s ordering in the `offer_detail` chunk and `offer_create` chunk are conflicting.
> 
> The ordering is very clear in [Create.vue](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Create.vue#L579):
> 
> 1. `application-questions.vue` before `MutipleEvents.vue`
> 2. `Editable_Chosen_Offer_Onfocus.vue` before `MutipleEvents.vue`
> 3. `OfferWhiteIPModal` (imported by `OfferConversionWhiteList`) before `MutipleEvents.vue`
> 
> However, the situation is different in [`Detail.vue`](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L199):
> 
> 1. There're 2 imports of `Payment.vue`([L209](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L209) and [L212](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L212)), which transitively imports `MultipleEvents.vue`
> 2. `Editable_Chosen_Offer_Onfocus.vue` is transitively imported by [`Targeting.vue`](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L211) and it's between the 2 imports of `Payment.vue`
> 3. `application-questions.vue` imported by [`Basic.vue`](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L210), also between them.
> 4. `OfferConversionWhiteList`, imported by [`Tracking.vue`](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L214), is **after** `Payment.vue`, this is conflicting with the ordering in `Create.vue`.
> 
> ## The Solution
> 1. Delete [the first occurrence of `./Detail/Payment.vue`](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L209)
> 2. Correct the name of [the second import of `./Detail/Payment.vue`](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L212) (`submodule_pyament` -> `submodule_payment`)
> 3. Move [this line](https://github.com/elainema/-mini-css-extract-plugin-Conflicting-order/blob/d5aea457750891137cc051022b0bf083a861bbc9/src/views/Offer/pages/Detail.vue#L214) up above `./Detail/Payment.vue`
> 
> 1. Maybe it's due to you've used different package managers to install Vue CLI. Run `ls -l $(which vue)` in the terminal to see which folder the binary actually links to.
> 
> **Next time please consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug slightly_smiling_face**

Thanks very much, your method solved my question, and i will try using the forum, the Discord server or StackOverflow for questions first.

**Comment by qnp** [comment]
Regarding 
https://github.com/webpack-contrib/mini-css-extract-plugin/issues/250
https://forum.vuejs.org/t/sppress-warnings-in-vue-cli-3/45905/5

If you wonder how to remove only these warnings in vue-cli-3, I have done the following in `vue.config.js`:
```
  chainWebpack: config => {
    config.plugin('friendly-errors').tap(args => {
      const vueCli3Transformer = args[0].additionalTransformers[0];
      args[0].additionalTransformers = [
        vueCli3Transformer,
        error => {
          const regexp = /\[mini-css-extract-plugin\]\nConflicting order between:/;
          if (regexp.test(error.message)) return {};
          return error;
        },
      ];
      return args;
    });
  }
```

**Comment by Zacaria** [comment]
An answer that worked perfectly for me found here :
https://github.com/vuetifyjs/vuetify/issues/5271#issuecomment-542624461

If you are using Vue CLI v3, add the code below to vue.config.js can ignore this error.

// vue.config.js
module.exports = {
    css: {
        extract: { ignoreOrder: true },
    },
}
Make sure that you have install the latest mini-css-extract-plugin, which is a dependency of @vue/cli-service.

Check links below for more information:

webpack-contrib/mini-css-extract-plugin#250
webpack-contrib/mini-css-extract-plugin#422
https://cli.vuejs.org/config/#css-extract

**Comment by the-owl** [comment]
Simply setting `css.extract.ignoreOrder` leads to CSS extraction in dev mode and for me it breaks CSS hot reloading. Replace with this:
```js
css: {
  extract: process.env.NODE_ENV === 'production' ? {
     ignoreOrder: true,
  } : false,
}
```

**Comment by PLQin** [comment]
关于 [mini-css-extract-plugin] Conflicting order. Following module has been added: 异常的参考资料 ：  
- https://laysent.com/til/2019-11-28_conflicting-order-in-mini-css-extract-plugin
- https://github.com/webpack-contrib/mini-css-extract-plugin/pull/468
- https://github.com/webpack-contrib/mini-css-extract-plugin/pull/465

解决方案(2个) ： 

- 设置 ignoreOrder
```
// vue.config.js
plugins: [
  new MiniCssExtractPlugin({
    // ......
    ignoreOrder: true
  }),
],
```

- 处理css顺序问题
```
WARNING in chunk styles [mini-css-extract-plugin]
Following module has been added:
 * css xxx/css-loader/dist/cjs.js!./e1.css
 * css xxx/css-loader/dist/cjs.js!./a1.vue
while this module as dependencies that haven't been added before:
 * css xxx/css-loader/dist/cjs.js!./e2.css (used previous to added module in chunk entry2)
 * css xxx/css-loader/dist/cjs.js!./a2.vue (used previous to added module in chunk entry2)
```
将 e2.css 放置在 e1.css之前, a2.vue 放置在 a1.vue, 即可。

**Comment by PLQin** [comment]
关于 [mini-css-extract-plugin] Conflicting order. Following module has been added: 异常的参考资料 ：  
- https://laysent.com/til/2019-11-28_conflicting-order-in-mini-css-extract-plugin
- https://github.com/webpack-contrib/mini-css-extract-plugin/pull/468
- https://github.com/webpack-contrib/mini-css-extract-plugin/pull/465

解决方案(2个) ： 

- 设置 ignoreOrder
  ```
  // vue.config.js
  plugins: [
    new MiniCssExtractPlugin({
      // ......
      ignoreOrder: true
    }),
  ],
  ```

- 处理css顺序问题
  ```
  WARNING in chunk styles [mini-css-extract-plugin]
  Following module has been added:
  * css xxx/css-loader/dist/cjs.js!./e1.css
  * css xxx/css-loader/dist/cjs.js!./a1.vue
  while this module as dependencies that haven't been added before:
  * css xxx/css-loader/dist/cjs.js!./e2.css (used previous to added module in chunk entry2)
  * css xxx/css-loader/dist/cjs.js!./a2.vue (used previous to added module in chunk entry2)
  ```
  将 e2.css 放置在 e1.css之前, a2.vue 放置在 a1.vue, 即可。

**Comment by rustyx** [comment]
Another solution - configure MiniCssExtractPlugin only when it's enabled:

```
// vue.config.js
module.exports = {
  configureWebpack: config => {
    const miniCssExtractPlugin = config.plugins.find(
      plugin => plugin.constructor.name === 'MiniCssExtractPlugin'
    );
    if (miniCssExtractPlugin) {
      miniCssExtractPlugin.options.ignoreOrder = true;
    }
  }
}
```

**Comment by tmcdos** [comment]
To prevent breaking HMR in development mode when using the `extract` option, we can patch **mini-css-extract-plugin**
```
Index: \mini-css-extract-plugin\dist\hmr\hotModuleReplacement.js
===================================================================
--- \mini-css-extract-plugin\dist\hmr\hotModuleReplacement.js
+++ \mini-css-extract-plugin\dist\hmr\hotModuleReplacement.js
@@ -57,13 +57,13 @@
     var splitResult = src.split(/([^\\/]+)\.js$/);
     var filename = splitResult && splitResult[1];
 
     if (!filename) {
-      return [src.replace('.js', '.css')];
+      return [src.replace('.js', '.css').replace('/js/', '/css/')]; // TMCDOS
     }
 
     if (!fileMap) {
-      return [src.replace('.js', '.css')];
+      return [src.replace('.js', '.css').replace('/js/', '/css/')]; // TMCDOS
     }
 
     return fileMap.split(',').map(function (mapRule) {
       var reg = new RegExp("".concat(filename, "\\.js$"), 'g');
@@ -126,9 +126,9 @@
     stripWWW: false
   }); // eslint-disable-next-line array-callback-return
 
   src.some(function (url) {
-    if (href.indexOf(src) > -1) {
+    if (href.indexOf(url) > -1) { // TMCDOS
       ret = url;
     }
   });
   return ret; 
```

**Comment by davidyuk** [comment]
One more way to ignore order using chainWebpack
```js
// add to vue.config.js
module.exports = {
  chainWebpack(config) {
    if (config.plugins.has('extract-css')) {
      config.plugin('extract-css').tap(([definitions]) => [{
        ...definitions,
        ignoreOrder: true,
      }]);
    }
  },
};
```
