### ISSUE TITLE
What's manifest.js handle in aid of? 

### ISSUE THREAD

**Issue by ytudt** [vuejs/vue-cli#378]
In vue-cli webpack.prod.conf.js  there are some code like this
```
 new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest',
      chunks: ['vendor']
    })

```
and generate a manifest.js file  what js  should i put in this file?
中国人用汉语回答更好。。。。

**Comment by LinusBorg** [comment]
https://webpack.js.org/guides/code-splitting-libraries/#manifest-file

**Comment by yyyuuu777** [comment]
manifest 文件定义了 vendor.js 内部模块的管理， 尽可能使vendor.js 保持不变(vendor js通常比较大变动不利于缓存) , 需要在vendor.js 引入前，引入到html中
