### ISSUE TITLE
新建项目没有.vuerc文件  ？？windows环境

### ISSUE THREAD

**Issue by zhoufanglu** [vuejs/vue-cli#3780]
### Version
3.5.5

### Reproduction link
[https://github.com/vuejs/vue-cli/issues/new](https://github.com/vuejs/vue-cli/issues/new)

### Environment info
```
windows环境
```

### Steps to reproduce
新建项目没有.vuerc文件  ？？windows环境

### What is expected?
新建项目没有.vuerc文件  ？？windows环境

### What is actually happening?
新建项目没有.vuerc文件  ？？windows环境

**Comment by sodatea** [comment]
`.vuerc` 文件是在 `~` 目录下的，这个文件是用来存放 Vue CLI 本身的全局配置，跟单个项目无关。

**Comment by ShisiJu** [comment]
windows 在 C:\Users\ 下你的用户名的文件夹中
