### ISSUE TITLE
Infinite loop / cycle when running "vue-cli-service build" with --watch and --dest options together

### ISSUE THREAD

**Issue by aberonni** [vuejs/vue-cli#3785]
### Version
3.5.5

### Reproduction link
[https://github.com/aberonni/vue-cli-reproduce-infinite-loop](https://github.com/aberonni/vue-cli-reproduce-infinite-loop)

### Environment info
```
➜ vue info

Environment Info:

  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  Binaries:
    Node: 11.6.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 59.0.2
    Safari: 12.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3 
    @vue/babel-preset-app:  3.5.5 
    @vue/babel-preset-jsx:  1.0.0-beta.3 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3 
    @vue/babel-sugar-inject-h:  1.0.0-beta.3 
    @vue/babel-sugar-v-model:  1.0.0-beta.3 
    @vue/babel-sugar-v-on:  1.0.0-beta.3 
    @vue/cli-overlay:  3.5.1 
    @vue/cli-plugin-babel: ^3.5.0 => 3.5.5 
    @vue/cli-plugin-eslint: ^3.5.0 => 3.5.1 
    @vue/cli-service: ^3.5.0 => 3.5.3 
    @vue/cli-shared-utils:  3.5.1 
    @vue/component-compiler-utils:  2.6.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.2 
    vue: ^2.6.6 => 2.6.10 
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
- create new project with defaults
- change the serve command to the following: `vue-cli-service build --watch --dest public/build`
- run `yarn serve`

### What is expected?
rebuild when file changes

### What is actually happening?
it rebuilds in an infinite loop and creates infinite build folders inside public/build

**Comment by aberonni** [comment]
Example of output:
![image](https://user-images.githubusercontent.com/1260402/55818704-86699880-5af7-11e9-8d4b-56f84db68cb8.png)

**Comment by LinusBorg** [comment]
you can't build into the public folder, as it's the source folder for static files

**Comment by aberonni** [comment]
Is there a way for me to use `public/build` for output and maybe use a different folder as the source folder for static files? I can't seem to find a way to configure that in the configuration reference.

**Comment by LinusBorg** [comment]
No, there isnt.

**Comment by LinusBorg** [comment]
You can reconfigure or rempvd the copy plugin that needs this as a source folder. 

Join us on forum.vuejs.org if you need help with details.

**Comment by aberonni** [comment]
Would you be interested in a PR that adds this as a configuration option? I'm not sure if I can pull it off but I won't bother looking into it if you prefer this to not be configurable out of the box.

**Comment by aberonni** [comment]
Managed to solve it with the following, big thanks to @LinusBorg for the advice:

```js
// vue.config.js
module.exports = {
    chainWebpack: config => {
        if (config.plugins.has('copy')) {
            config.plugins.delete('copy')
        }
    }
}
```
This assumes (as in my specific case) that you don't need the statics in the `public` folder

**Comment by LinusBorg** [comment]
> Would you be interested in a PR that adds this as a configuration option? 

Sorry but no. We aim to provide consistent project layouts with Vue ClI, so static assets should always go into /public. Users are free to change it on their own if they must.
