### ISSUE TITLE
vue-cli-e2e-cypress allow modify default port

### ISSUE THREAD

**Issue by plehnen** [vuejs/vue-cli#3786]
### What problem does this feature solve?
My api does listen on port 8888.
When I run `yarn test:e2e` it starts the server in production mode with the next free port starting from 8080. 
So all my api calls won't work, since it detects it is not development-mode and doesn't apply my proxy rule in vue.config.js.

### What does the proposed API look like?
It would be nice to add `--port` to overwrite the default port, similar to the serve command.

**Comment by LinusBorg** [comment]
I don't understand the scenario completely.

> It would be nice to add --port to overwrite the default port, similar to the serve command.

Then the server would run on the specified port, but still not prox to your API, and your api would run on localhost:8888

So I think what you are *asking for* will not *solve your problem*

I think you should rather run e2e tests with a custom [mode](https://cli.vuejs.org/guide/mode-and-env.html#example-staging-mode) and provide the alternative AI url as an environment variable ....

**Comment by plehnen** [comment]
@LinusBorg If it would start with `--port 8888` and my api runs on port 8888, the relative path to /api/ should work. At least that's how I understand it. May be I am missing something. Don't you agree?

**Comment by LinusBorg** [comment]
>  If it would start with --port 8888 and my api runs on port 8888 [...]

...it would result in an ugly error because two applications (vue-cli's devServer and your API server) can't use the same port.

**Comment by plehnen** [comment]
Ah! You are right. My app was acting as a server in production mode. That's why I was assuming setting the port would fix my issue. But working with --mode is apparently the better way. Closing.
