### ISSUE TITLE
（vue-cli proxyTable request  code 200,but data = null）vue-cli 中的proxyTable 请求成功了(200，我请求的是thinkphp那边的接口)，但是数据为空，怎么回事的啊

### ISSUE THREAD

**Issue by zhangli790847400** [vuejs/vue-cli#379]
我发布的问题 ：https://segmentfault.com/q/1010000008566981

我请求thinkphp那边的接口，tp中的接口post到node那边的接口（tp请求的是node）。我请假tp这边200，但是数据为null，我直接请求node那边的接口，是可以拿出数据的。请求的接口是一样的（我觉得是tp那边的问题吧，但是我这个项目不能请求node那边的）

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!

**Comment by zhangli790847400** [comment]
Sorry
