### ISSUE TITLE
Option to nickname projects in the vue-ui Dashboard

### ISSUE THREAD

**Issue by PeterDKC** [vuejs/vue-cli#3793]
### What problem does this feature solve?
I have a whole list of SPA's within parent applications that are all called "frontend", so I have no idea what I'm looking at when I pull up the ui dashboard. I just accidentally made a bunch of changes to one that I wasn't even intending to work on.

It would be great if Vue UI projects could be "nicknamed" by something besides the last dir in path.

### What does the proposed API look like?
// shrug

I'm just an end user, I have no idea what the API looks like currently.

**Comment by Akryum** [comment]
Note: when created, the project name is set using the `name` field in `package.json`
