### ISSUE TITLE
views bug

### ISSUE THREAD

**Issue by xumoyan** [vuejs/vue-cli#3794]
### Version
3.5.5

### Reproduction link
[https://github.com/xumoyan/vue-cli-bug.git](https://github.com/xumoyan/vue-cli-bug.git)

### Environment info
```
app.vue 
<app-header></app-header>
<router-view />

home.vue
<template>
  <div class="home">
    <p>Home</p>
  </div>
</template>

<script lang="ts">
import { Vue } from "vue-property-decorator";
export default class Home extends Vue {}
</script>

header.vue
<template>
  <div>
    <h1>Header</h1>
  </div>
</template>

<script lang="ts">
import { Vue } from "vue-property-decorator";
export default class Header extends Vue {}
</script>

display:
Home
Home

header.vue delete export default  class Header extends Vue {}
display:
Header
Home
```

### Steps to reproduce
yarn install 
yarn serve
header.vue delete export default  class Header extends Vue {}
yarn serve

### What is expected?
Header 
Home

### What is actually happening?
Home
Home

**Comment by sodatea** [comment]
You forgot to add the `@Component` decorators.
