### ISSUE TITLE
Error when run UI in DEV mode

### ISSUE THREAD

**Issue by orblazer** [vuejs/vue-cli#3802]
### Version
3.6.0

### Environment info
```
System:
    OS: Linux 5.0 Antergos Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 11.14.0 - /usr/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.9.0 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 66.0.3
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Install Vue CLI with `yarn global add @vue/cli`
2. Run Vue CLI UI with `vue ui -D`
3. Import an project
4. Restart Vue CLI UI

### What is expected?
The widget loaded and the project keeped

### What is actually happening?
The widget is not loaded (error : `Component load timeout`) and the project is absent (need re import the project and re configure the widget)

**Comment by sodatea** [comment]
Just released v3.6.1. Does this bug still exist (without the `-D` flag)?
