### ISSUE TITLE
生成的package.json中文件版本错误

### ISSUE THREAD

**Issue by magicstf** [vuejs/vue-cli#3803]
### Version
3.0.0-rc.3

### Reproduction link
[https://github.com/vuejs/vue-cli/issues](https://github.com/vuejs/vue-cli/issues)

### Node and OS info
v8.11.3,5.6.0 macos

### Steps to reproduce
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/cli-plugin-eslint@^3.6.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'webpack-demo'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sutengfei/.npm/_logs/2019-04-14T02_52_51_915Z-debug.log
 ERROR  command failed: npm install --loglevel error

### What is expected?
正常创建项目

### What is actually happening?
{
  "name": "webpack-demo",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.6.1",
    "@vue/cli-plugin-eslint": "^3.6.1",
    "@vue/cli-service": "^3.6.1"
  }
}

---
在npm 官网查看，发现@vue/cli-plugin-babel、@vue/cli-plugin-eslint 最新版本才3.6.0 ，为什么会打出3.6.1呢？

**Comment by sodatea** [comment]
你的全局 cli 版本太老了，3.0.0-rc.3，建议升级到 3.6.1

**Comment by magicstf** [comment]
> 你的全局 cli 版本太老了，3.0.0-rc.3，建议升级到 3.6.1

好的，谢谢啦
