### ISSUE TITLE
Received "TypeError: Path must be a string. Received undefined" when using "vue add"

### ISSUE THREAD

**Issue by ivanreyne** [vuejs/vue-cli#3804]
### Version
3.6.1

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    Yarn: Not Found
    npm: 3.5.2 - /usr/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 66.0.2
  npmGlobalPackages:
    @vue/cli: 3.6.1

```

### Steps to reproduce
Create a new vue project:
```bash
vue create testapp1
cd vue testapp1
vue add vuetify
```
FAILS

### What is expected?

📦  Installing vue-cli-plugin-vuetify...

✔  Successfully installed plugin: vue-cli-plugin-vuetify

? Choose a preset: Default (recommended)

🚀  Invoking generator for vue-cli-plugin-vuetify...
⚓  Running completion hooks...

✔  Successfully invoked generator for plugin: vue-cli-plugin-vuetify
   The following files have been updated / added:

     src/assets/logo.svg
     src/plugins/vuetify.js
     package.json
     public/index.html
     src/App.vue
     src/components/HelloWorld.vue
     src/main.js
     src/views/Home.vue

   You should review these changes with git diff and commit them.

### What is actually happening?

📦  Installing vue-cli-plugin-vuetify...

 ERROR  TypeError: Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1236:7)
    at exports.hasProjectPnpm (/usr/local/lib/node_modules/@vue/cli/node_modules/@vue/cli-shared-utils/lib/env.js:113:25)
    at add (/usr/local/lib/node_modules/@vue/cli/lib/add.js:30:94)
    at module.exports.args (/usr/local/lib/node_modules/@vue/cli/lib/add.js:66:10)
    at Command.program.command.description.option.allowUnknownOption.action (/usr/local/lib/node_modules/@vue/cli/bin/vue.js:86:26)
    at Command.listener (/usr/local/lib/node_modules/@vue/cli/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/local/lib/node_modules/@vue/cli/node_modules/commander/index.js:651:12)

---
I did a bit of debug and the problem is caused because no "cwd" argument is passed to the calls of the function "hasProjectPnpm" from @vue/cli-shared-utils/lib/env.js:113

In this simple "add" case there are two places where this happen:

at add (/usr/local/lib/node_modules/@vue/cli/lib/add.js:30:94)

and later at:

at runGenerator (/usr/local/lib/node_modules/@vue/cli/lib/invoke.js:148:75)

You will see something similar to this (from invoke.js):

loadOptions().packageManager || (hasProjectYarn(context) ? 'yarn' : hasProjectPnpm() ? 'pnpm' : 'npm')

where the "hasProjectPnpm" function is called without arguments but it needs the cwd (context) as the other "hasProjectYarn" function, it should be like this:

loadOptions().packageManager || (hasProjectYarn(context) ? 'yarn' : hasProjectPnpm(context) ? 'pnpm' : 'npm')

I report it here because rather than submitting a patch because I am not familiar with the vue-cli code and it might affect other commands and other places as well.

Regards,

Ivan.

**Comment by LinusBorg** [comment]
Hi, 

please verify that you are actually using `@vue/cli-service@ >=3.6.0` or higher, as that version already *does* pass the CWD, for example:

https://github.com/vuejs/vue-cli/pull/3790/files#diff-b5b228d4b419ff0f6a9d3e77a291f3c0L238

Your issue states you are on 3.6.1 of the CLI, but that doesn't mean you're on 3.6.1 of the @vue/* packages in your project, which are likely locked to some lower version...

**Comment by ivanreyne** [comment]
Hi,

The new project is using @vue/cli-service@3.6.0 (it is a brand new project, just by creating and adding you already get the error)

If you look closely at the pull request you just send you will see that the calls to "hasProjectPnpm" from "serve.js" (line 238) look correct as it is getting the cwd passed into but the calls to "hasProjectPnpm" from "command.js" (line 13), "add.js" (line 30), "invoke.js" (line 148) are missing the cwd argument to the call. I guess that this is (at least part of) the problem.

Regards,

Ivan.

**Comment by LinusBorg** [comment]
Right, thanks

**Comment by thousandsofraccoons** [comment]
@LinusBorg Hello. I getting some similar error with `vue add` command: 
Version of "@vue/cli-service": "^3.6.0",

`C:\open_server\OSPanel\domains\logoflix\packages\parser>vue add electron-builder

�  Installing vue-cli-plugin-electron-builder...

 ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:427:7)
    at exports.hasProjectPnpm (C:\Users\T\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\@vue\cli-shared-utils\lib\env.js:113:25)
    at add (C:\Users\T\AppData\Roaming\npm\node_modules\@vue\cli\lib\add.js:30:94)
    at module.exports.args (C:\Users\T\AppData\Roaming\npm\node_modules\@vue\cli\lib\add.js:66:10)
    at Command.program.command.description.option.allowUnknownOption.action (C:\Users\T\AppData\Roaming\npm\node_modules\@vue\cli\bin\vue.js:86:26)
    at Command.listener (C:\Users\T\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:189:13)
    at Command.parseArgs (C:\Users\T\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\commander\index.js:651:12)
    at Command.parse (C:\Users\T\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\commander\index.js:474:21)`

Could you please help me?

**Comment by LinusBorg** [comment]
Well it's a bug. We will shortly release a fix. Until then you can downgrade to 3.5.* or install yarn (which results in skipping the problematic code).

**Comment by thousandsofraccoons** [comment]
@LinusBorg thank you

**Comment by cosminroger** [comment]
I am having exactly the same issue when I try to add Vuetify to a new project. Also, I have searched and it seems that I can't downgrade from version 3.6.1 as every time I try to run npm install -g @vue/cli@3.5.5 for example, the 3.6.1 gets installed anyway. Am I doing something wrong here?

**Comment by LinusBorg** [comment]
Have you tried ~turning it on and off again~ uninstalling and re-installing it?

There's lots of intricacies with global packages that could cause trouble, like having installed it with another package manager than the one you're using to install now etc. pp.

Check `which vue` in your terminal to see where the version is installed, then check where that symlink points to with `readlink <path returned by ''which vue>`

**Comment by cosminroger** [comment]
Yes, I have tried to uninstall and re-install it and it doesn't work. Every time I get the 3.6.1 installed regardless of what I have tried. I have been just setting up everything from scratch as I just reinstalled windows a couple of days ago. I have installed Node.js and when I installed the vue/cli package I used the `npm` command to do so.

Any other suggestions?

**Comment by LinusBorg** [comment]
No, unfortunately not. Seems to be a problem with npm as we can't influence what version gets installed at your machine...

**Comment by cheng-github** [comment]
oh guys, I got the same problem but I was running on windows 10.

And after I modify the source code followed by @sodatea who committed a few hour age, now the problem solved. Thanks, :).

**Comment by sodatea** [comment]
Sorry folks but I’m currently on a train and the cellular network is not stable enough for me to publish a new version on npm. I’ll release the patch as soon as I arrived home.

**Comment by cosminroger** [comment]
For those having this problem, I managed to solve it!

It depends how did you installed `@vue/cli`. If you did it through:

`npm install -g @vue/cli`

then you'll have to uninstall it through:

`npm uninstall -g @vue/cli`

That `-g` is very important, otherwise you'll still have the global files saved and it would conflict.
After you perform the uninstall, you can simply reinstall it as `npm install -g @vue/cli@3.5.0` and it would install the 3.5.0 version. Change the 3.5.0 so something else if you wanna get another version.

I hope this helps!

**Comment by kat15** [comment]
Hi, I have the same problem:
vue --version
@vue/cli 4.4.1

when run  yarn run test:unit
yarn run v1.22.4
```
$ vue-cli-service test:unit
 ERROR  Error loading /var/www/html/vue.config.js:
 ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1085:7)
    at Object.<anonymous> (/var/www/html//vue.config.js:9:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
vue.config.js:
```
const path = require('path');

module.exports = {
    runtimeCompiler: true,

    devServer: {
        proxy: 'http://localhost:80/'
    },
    outputDir: path.resolve(__dirname, process.env.VUE_APP_DIRECTORY),
    assetsDir: process.env.VUE_APP_DIRECTORY_STATIC,

    pluginOptions: {
        i18n: {
            locale: 'pl',
            fallbackLocale: 'pl',
            localeDir: 'locales',
            enableInSFC: true
        }
    }
}

```

**Comment by sodatea** [comment]
@kat15 Maybe `VUE_APP_DIRECTORY` or `VUE_APP_DIRECTORY_STATIC` is empty in the test environment.

**Comment by kat15** [comment]
@sodatea  Ok, maybe, but why then 'yarn run serve' is working?

**Comment by sodatea** [comment]
Maybe you've only set these environment variables in the development env? Like, they are in `.env.development` but not `.env.test`

**Comment by kat15** [comment]
Yep, true. I forgot about .env.test ;/ sorry and thanks for that:)
