### ISSUE TITLE
Progressive Web App template

### ISSUE THREAD

**Issue by addyosmani** [vuejs/vue-cli#381]
@yyx990803 and I have talked about working on an official PWA template for Vue 📱 

There are a few different options for what this could include:

- Web Application Manifest
- Default favicons (minimalist setup from realfavicongenerator.net)
- Service Worker precaching + runtime caching via `sw-precache-webpack-plugin` 
- Application Shell architecture 
- Code-splitting by default with vue-router

If we wanted to go even more ambitious we could cover:

- PRPL pattern support (using something like `preload-webpack-plugin`)
- Simple server-side rendering + pre-fetching
- CSS extraction for production

**Requirements** 

- Aim to score as close to 100/100 on [Lighthouse](https://github.com/GoogleChrome/lighthouse)
- Must be straight-forward to use. If we make it inherently complex, it will lose value to end users.

**Prior-art - PWA templates and boilerplates** 🎨 

- https://github.com/Narkoleptika/webpack-everything
- https://github.com/electricjesus/vue-pwa-template
- https://github.com/BosNaufal/vue-simple-pwa

**Vue.js PWAs (open-source)** 👐 

- https://github.com/vuejs/vue-hackernews-2.0
- https://github.com/GoogleChrome/jscost.org (not yet fully released)
- https://github.com/mrgodhani/feedbox
- https://github.com/bstavroulakis/vue-wordpress-pwa

**Other references** 📚 

- [PRPL pattern with Webpack and React](https://github.com/GoogleChrome/preload-webpack-plugin/tree/master/demo)

Initially, I would love to get a feel for what would considered palatable for an MVP. There's technically nothing stopping us baking in everything in the above list, but let's talk and figure out a path forward 🚀

**Comment by yyx990803** [comment]
Thanks Addy! The list looks good and totally feasible. The only thing I'd consider is whether we want to include SSR for now, since SSR comes with some tradeoffs in increased dev and deployment complexity which may not be a net win for all apps.

**Comment by addyosmani** [comment]
> The only thing I'd consider is whether we want to include SSR for now, since SSR comes with some tradeoffs in increased dev and deployment complexity which may not be a net win for all apps. We can start with a version without SSR and then work on a separate one that uses SSR.

This plan of action sgtm 👍 

What's the best way to get started? Worth us creating a new empty repo on the vuejs org to start on a PR?

**Comment by yyx990803** [comment]
I've created https://github.com/vuejs/pwa and sent an invite for collaboration. We'll move it to `vuejs-templates` once it's ready.

**Comment by addyosmani** [comment]
Awesome. Thanks, @yyx990803!

**Comment by rwatts3** [comment]
This is great news.  Thank you for taking the lead on this topic.  Frankly it's the only reason I even consider opening polymer in my computer.  Then I very quickly miss the Vue workflow.  If Vue had pwa.  There would be no reason to use another framework.  So nice work !

**Comment by rwatts3** [comment]
This is great news. Just curious if there is a posted timeline and roadmap for this ? 
I'd be interested in assisting if possible.

**Comment by posva** [comment]
Closing this now that the template exists at https://github.com/vuejs-templates/pwa and it's ready
👏 @addyosmani
