### ISSUE TITLE
CLI 更新到3.6.2版本后，创建项目失败。

### ISSUE THREAD

**Issue by yrfandrew** [vuejs/vue-cli#3812]
### Version
3.6.2

### Environment info
```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 11.13.0 - E:\Program Files\nodejs\node.EXE
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.7.0 - E:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/cli:  3.6.2
    typescript:  3.4.3
    vue:  2.6.10
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. 选择 `yarn` 作为包管理器；
2. 在“功能”中选择：Babel，Progressive Web App (PWA) Support，Router，Vuex，CSS Pre-processors，Linter / Formatter，使用配置文件；
3. 在“配置”中分别选择：Sass/SCSS (with node-sass)，ESLint   Airbnb config，Lint on save；

### What is expected?
能正常创建项目。

### What is actually happening?
![cmd](https://user-images.githubusercontent.com/4082323/56103621-64906b80-5f66-11e9-816a-278850230ac1.png)

**Comment by sodatea** [comment]
请确认下是否分别使用 npm 和 yarn 安装过全局的 @vue/cli，并且其中一个还是旧版？
3.6 以后，vue ui 创建项目时是在单独的进程中调用 `vue create` 的 https://github.com/vuejs/vue-cli/commit/8c3ff1165384bf4bafca39a267e3da3d9821abdb
比较怀疑是因为在新的进程中取到的 vue 命令跟你调用 vue ui 时的不是同一个

**Comment by yrfandrew** [comment]
@sodatea 在移除使用全局包，并重新安装`@vue/cli` `3.6.2`版本后，重试创建项目，依然失败。
我尝试了将包管理器选择为 `npm`、`yarn`，但无一成功。

![image](https://user-images.githubusercontent.com/4082323/56115829-ef895a00-5f96-11e9-9c93-f28366cf29a1.png)

**Comment by YangGoldDragon** [comment]
> @sodatea 在移除使用全局包，并重新安装`@vue/cli` `3.6.2`版本后，重试创建项目，依然失败。
> 我尝试了将包管理器选择为 `npm`、`yarn`，但无一成功。
> 
> ![image](https://user-images.githubusercontent.com/4082323/56115829-ef895a00-5f96-11e9-9c93-f28366cf29a1.png)

请问问题解决了吗？如何解决的，我现在也遇到了同样的问题。

**Comment by yrfandrew** [comment]
> > @sodatea 在移除使用全局包，并重新安装`@vue/cli` `3.6.2`版本后，重试创建项目，依然失败。
> > 我尝试了将包管理器选择为 `npm`、`yarn`，但无一成功。
> > ![image](https://user-images.githubusercontent.com/4082323/56115829-ef895a00-5f96-11e9-9c93-f28366cf29a1.png)
> 
> 请问问题解决了吗？如何解决的，我现在也遇到了同样的问题。

你把全局安装的 `@vue/cli` 的移除掉，然后再重新安装 `3.7.0` 版本的。

**Comment by YangGoldDragon** [comment]
> > > @sodatea 在移除使用全局包，并重新安装`@vue/cli` `3.6.2`版本后，重试创建项目，依然失败。
> > > 我尝试了将包管理器选择为 `npm`、`yarn`，但无一成功。
> > > ![image](https://user-images.githubusercontent.com/4082323/56115829-ef895a00-5f96-11e9-9c93-f28366cf29a1.png)
> > 
> > 
> > 请问问题解决了吗？如何解决的，我现在也遇到了同样的问题。
> 
> 你把全局安装的 `@vue/cli` 的移除掉，然后再重新安装 `3.7.0` 版本的。

还是不行哦，还是报同样的错误

**Comment by yrfandrew** [comment]
> > > > @sodatea 在移除使用全局包，并重新安装`@vue/cli` `3.6.2`版本后，重试创建项目，依然失败。
> > > > 我尝试了将包管理器选择为 `npm`、`yarn`，但无一成功。
> > > > ![image](https://user-images.githubusercontent.com/4082323/56115829-ef895a00-5f96-11e9-9c93-f28366cf29a1.png)
> > > 
> > > 
> > > 请问问题解决了吗？如何解决的，我现在也遇到了同样的问题。
> > 
> > 
> > 你把全局安装的 `@vue/cli` 的移除掉，然后再重新安装 `3.7.0` 版本的。
> 
> 还是不行哦，还是报同样的错误

你在电脑上搜索一下，有哪几个地方用`npm`或`yarn`安装了`@vue/cli`，找到后，用命令行移除。
