### ISSUE TITLE
Consistent versions when using `vue create`

### ISSUE THREAD

**Issue by cexbrayat** [vuejs/vue-cli#3816]
### Version
3.5.5

### Reproduction link
[https://github.com/cexbrayat/vue-cli-355](https://github.com/cexbrayat/vue-cli-355)

### Environment info
```
System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 66.0.2
    Safari: 12.0.3
  npmPackages:
    @vue/cli-overlay:  3.6.0
    @vue/cli-plugin-e2e-cypress: ^3.6.0 => 3.6.0
    @vue/cli-plugin-typescript: ^3.6.0 => 3.6.0
    @vue/cli-plugin-unit-jest: ^3.6.0 => 3.6.0
    @vue/cli-service: ^3.6.0 => 3.6.0
    @vue/cli-shared-utils:  3.6.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    jest-serializer-vue:  2.0.2
    typescript: ^3.4.3 => 3.4.3
    vue: ^2.6.10 => 2.6.10
    vue-class-component: ^7.0.2 => 7.0.2
    vue-hot-reload-api:  2.3.3
    vue-jest:  3.0.4
    vue-loader:  15.7.0
    vue-property-decorator: ^8.1.0 => 8.1.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: 3.5.5
```

### Steps to reproduce
npm uninstall -g @vue/cli && npm i -g @vue/cli@3.5.5

vue create 355 -m npm --inlinePreset '{"useConfigFiles": true,"plugins": {"@vue/cli-plugin-typescript": {"classComponent": true,"tsLint": true,"lintOn": ["save"]},"@vue/cli-plugin-unit-jest": {},"@vue/cli-plugin-e2e-cypress": {}}}'

### What is expected?
When using a specific version of `@vue/cli`, we would expect to have the same consistent behavior when creating a new application.

### What is actually happening?
It appears that if you have a version of the CLI installed, the generated app will not have the same version of the `@vue/cli` packages.

Note that whereas the global NPM package is `3.5.5` in the Environment info, the CLI overlay and plugins are in `3.6.0`.
It leads to inconstencies when you run `vue create` if between two runs a new release of the CLI was published.

---
We stumbled on #3814 while using CLI 3.5.5, which should not happen (as #3814 was introduced by `3.6.x`). This is perhaps the desired behavior, but I found it rather surprising. Maybe it's just that it should only use the latest patch and not minor (as the Angular CLI does for example)?

**Comment by LinusBorg** [comment]
It's desired behaviour. 

Otherwise you would always have to upgrade the cli in order to generate a project with the latest versions, which is kind of counter-intuitive at best and risky at worst, i.e. you miss out on important security patches (the latter could be fixed by your suggestion to restrict to minors, in theory).

> It leads to inconstencies when you run vue create if between two runs a new release of the CLI was published.

Yes., but to me, that's no different than installing a package. If in between two installs in different project a new version was released, you end up with the same inconsistency.

I understand angluar CLI does it differently but fail to see the advantage as the problem you describe is rather a seldom occurence while being on the latest stable release should be a general desire, no?

**Comment by cexbrayat** [comment]
Thank you for your answer @LinusBorg 

I think it is suprising to bring the latest minor instead of patch, but I get your point. The problem you can face by always bringing the latest stable is that if you have a regression in the last release, everybody is going to be hit, with no possibility to downgrade right? 

But anyway, if this is the desired behavior, that's fine by me, I'll close 👍  Thanks for your time.

**Comment by LinusBorg** [comment]
> everybody is going to be hit, with no possibility to downgrade right?

Yes, everyone is hit. But you can downgrade by adjusting versions in package.json, of course.
