### ISSUE TITLE
Filename hash when building as "commonjs" format

### ISSUE THREAD

**Issue by epartipilo** [vuejs/vue-cli#3817]
I'm not sure if this is a Bug or a Feature or just a misunderstood use of the builder
 
### Version
3.6.0

### Reproduction link
[https://github.com/epartipilo/webpack-vue-lib](https://github.com/epartipilo/webpack-vue-lib)

### Environment info
```
 System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.14.2 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 65.0.2
    Safari: 12.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3 
    @vue/babel-preset-app:  3.5.5 
    @vue/babel-preset-jsx:  1.0.0-beta.3 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3 
    @vue/babel-sugar-inject-h:  1.0.0-beta.3 
    @vue/babel-sugar-v-model:  1.0.0-beta.3 
    @vue/babel-sugar-v-on:  1.0.0-beta.3 
    @vue/cli-overlay:  3.5.1 
    @vue/cli-plugin-babel: ^3.5.0 => 3.5.5 
    @vue/cli-plugin-eslint: ^3.5.0 => 3.5.1 
    @vue/cli-service: ^3.5.0 => 3.5.3 
    @vue/cli-shared-utils:  3.5.1 
    @vue/component-compiler-utils:  2.6.0 
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.2 
    vue: ^2.6.6 => 2.6.10 
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
yarn install && yarn build

### What is expected?
The files:
webpack-vue-lib.common.js
webpack-vue-lib.css

Should be generated with [contenthash] added to the file name to avoid browser caché

### What is actually happening?
There is no hash added to filenames as they are when building as target "app"

---
The intention behind this result is to use a Vue application as a library imported into another framework so the hash on filenames will avoid the browser cache when using this library.

**Comment by LinusBorg** [comment]
these files are not hashed as you woill import them into another application anyway, where they will be processed (i.e. end up in a `vendor` bundle which gets hashed)

It would be highly impractical to have these files hashed as imports would break all the time.

**Comment by epartipilo** [comment]
Thanks for the quick response!
So in my particular case I'll manage to edit the _vue.config.js_ file.

Cheers!

**Comment by AMerkuri** [comment]
> Thanks for the quick response!
> So in my particular case I'll manage to edit the _vue.config.js_ file.
> 
> Cheers!

Did you get it working in `vue.config.js`?

I have similar issue.
Using async components where I need to generate hash for each component when targeting lib.
