### ISSUE TITLE
Using varibles for filename and template in chainWebpack html plugin lead to unexpected result

### ISSUE THREAD

**Issue by xiangnanscu** [vuejs/vue-cli#3818]
### Version
3.6.1

### Environment info
```
ubuntu 14.04
```

### Steps to reproduce
say in the standard vue cli project I've two html files in `public` folder: foo.html bar.html.

##  vue.config.js
```
var NAME = process.env.NAME 
var filename = `${NAME}.html`
var template = `./public/${NAME}.html`
module.exports = {
  // https://github.com/neutrinojs/webpack-chain#getting-started
  chainWebpack: config => {
    config
      .plugin('html')
      .tap(args => {
        const opts = args[0]
        opts.filename = filename
        opts.template = template
        return args
      })
  },
}
```
## run command

`NAME=foo vue-cli-service build`

### What is expected?
the `dist` folder should contain only one html file: `foo.html`

### What is actually happening?
the `dist` folder contains two html files: `foo.html` and `bar.html`

**Comment by LinusBorg** [comment]
Everything from /public will be copied to /dist. That's what that folder is for. 

For more info visit the docs
