### ISSUE TITLE
Escaping for package.json

### ISSUE THREAD

**Issue by Arial7** [vuejs/vue-cli#382]
I am certain if this is a issue with vue-cli or the template, however I think the "setup questions" are asked by the cli?

My problem: I just setup a new project and followed the standard procedure:
![See this](https://cloud.githubusercontent.com/assets/6919894/23676002/75c93b28-037b-11e7-9566-08803ab3abde.png)

As you can see, I used double quotes inside of the Author field (for my nickname). This resulted in the following error:
![image](https://cloud.githubusercontent.com/assets/6919894/23676142/01273918-037c-11e7-8f5a-b46df14a7f6e.png)

When looking into my generated package.json, you can see that the double quotes just got copied into the `author` field:

```json
....
"author": "Pascal "Arial7" Riesinger <riesinger.pascal@gmail.com>",
  "private": true,
  "scripts": {
....
```

So my suggestion is to escape the user input before writing it to the `package.json` file.

**Comment by posva** [comment]
Hey, thanks for reporting this. It's indeed not expected. It's a fairly easy PR. Tests may be a bit complicated because of the cli nature, though

**Comment by Arial7** [comment]
I just pushed a PR (#388) that fixes this.
