### ISSUE TITLE
Code linting using TSLint is ignored with config in YAML format

### ISSUE THREAD

**Issue by Ky6uk** [vuejs/vue-cli#3820]
### Version
3.6.2

### Environment info
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
  Binaries:
    Node: 11.13.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
    Safari: Not Found
  npmPackages:
    @vue/cli-overlay:  3.6.0
    @vue/cli-plugin-typescript: ^3.6.0 => 3.6.0
    @vue/cli-service: ^3.6.0 => 3.6.0
    @vue/cli-shared-utils:  3.6.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    typescript: ^3.4.3 => 3.4.3
    vue: ^2.6.10 => 2.6.10
    vue-class-component: ^7.0.2 => 7.0.2
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-property-decorator: ^8.1.0 => 8.1.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
* `$ vue create woof`
* `$ cd woof`
* `$ rm tslint.json`
* `$ vim tslint.yml`
* `$ npm run serve`

### What is expected?
`npm run serve` will use `tslint.yml` config file for linting.

### What is actually happening?
`npm run serve` uses only `tslint.json` config file.

**Comment by sodatea** [comment]
https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/6bdf63264b6188668f475258e4c8081c0aaf9918/src/linterConfigHelpers.ts#L36

https://github.com/vuejs/vue-cli/blob/57151bef32c9b4c456171be47010fbdfd5f1169f/packages/%40vue/cli-plugin-typescript/index.js#L73


[fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin) does not support other config formats except `tslint.json` so we did a check for it as well.
To fix it, please open an issue or pr in the [upstream repository](https://github.com/Realytics/fork-ts-checker-webpack-plugin).

**Comment by Ky6uk** [comment]
Unfortunately, the maintainer [rejects it](https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/247). 😞

**Comment by sodatea** [comment]
😞Then we are not likely to support it, either.
