### ISSUE TITLE
@vue/cli3.6.2 create project error via vue ui

### ISSUE THREAD

**Issue by yrfandrew** [vuejs/vue-cli#3821]
### Version
3.6.2

### Environment info
```
System:
   OS: Windows 10
   CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
 Binaries:
   Node: 11.13.0 - E:\Program Files\nodejs\node.EXE
   Yarn: 1.15.2 - E:\Program Files\nodejs\node_global\yarn.CMD
   npm: 6.7.0 - E:\Program Files\nodejs\npm.CMD
 Browsers:
   Edge: 42.17134.1.0
 npmPackages:
   @vue/cli:  3.6.2
   typescript:  3.4.3
 npmGlobalPackages:
   @vue/cli: Not Found
```

### Steps to reproduce
1. Select Package Manager: yarn.
2. Select in “Features”: Babel, Progressive Web App (PWA) Support, Router, Vuex, CSS Pre-processors, Linter / Formatter, User Config Files.
3. Select in “Configuration”: Sass/SCSS (with node-sass), ESLint Airbnb config, Lint on save.

### What is expected?
Can create a project successfully.

### What is actually happening?
![image](https://user-images.githubusercontent.com/4082323/56175834-8273d400-602b-11e9-9a59-f2d1d01233d8.png)

**Comment by sodatea** [comment]
1. Is it 3.5.5 or 3.6.2? I'm confused.
2. Why is there a local `@vue/cli` package installed? You are expected to install it globally.
3. Please run `yarn global remove @vue/cli` and try again. Apparently the ui invokes a global `vue` binary installed by yarn it is of an older version.

**Comment by yrfandrew** [comment]
OK, I can create a project successfully.
