### ISSUE TITLE
Running init unattended (i.e. for Docker)

### ISSUE THREAD

**Issue by Joshfindit** [vuejs/vue-cli#383]
I understand that this at first glance may seem in the template scope, but I'm looking for a way to answer any template's questions without having to interact with the console.

How could something like this be done:

```
RUN vue init webpack-simple /tmp/hello --author="Author" --project-name="Hello" --project-description="A Vue.js project" --use-sass="No"
RUN bash -c "(cd /tmp/hello && npm install)"
```

*Apologies if there is already a solution to this that's obvious if you have a background in Node. I did search through the documentation and did not see anything that I understood as solving this.*

**Comment by OmgImAlexis** [comment]
This should be in scope for this issue so I'd be great to also see a `-y` option for just allowing all defaults.

**Comment by posva** [comment]
dup of #291
