### ISSUE TITLE
Option to turn off PWA generation

### ISSUE THREAD

**Issue by holtwick** [vuejs/vue-cli#3830]
### What problem does this feature solve?
If building for multiple targets, some of them might not support PWA. It would be great to have an option to turn off the functionality

### What does the proposed API look like?
Currently the only way is to use a env var `VUE_CLI_BUILD_TARGET` different to `app`: https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-pwa/index.js#L4

This line could e.g. be changed to:

```js
if (target && target !== 'app' || options.pwa.off === true) {
      return
}
```

**Comment by holtwick** [comment]
I am currently developing the following app for multiple targets: https://collect-app.com/

Especially for iOS and macOS I distribute the built HTML/CSS/JS inside of the app package I put on the respective app stores. `WKWebView` (the OS's native web view) is used and it supports PWA. But in this scenario it doesn't make much sense, since the access is instant and always "online" (at least as seen from the app itself). Therefore a service-worker is contra productive, because this extra step is not required.

For Windows and web browsers instead PWA makes sense. See http://desktop.collect-app.com/ and https://mobile.collect-app.com/ as examples (work in progress).

**Comment by holtwick** [comment]
After looking closer at it, I have to agree, that by just not registering the `service-worker` the whole PWA functionality can be avoided. I would still like to avoid this step via config instead of post processing and deleting the superfluous files. But indeed this feature is not very urgent.

**Comment by sbyps** [comment]
when npm add @vue/cli-plugin-pwa into dependencies, but dont configure it in vue.config.js( or config like `pwa: {}`)
finally, the build bubdle would build serviceWorker.js/robots.txt/manifest.json, these files should avoid building
@LinusBorg

**Comment by etktnse** [comment]
I need the same functionality for same reason.  some of my build targets do not need a service worker(because they are in a local server anyway), I'm afraid it can cause buggy behaviour. I dont want to have it, i dont want to think about it. This is not just me : https://stackoverflow.com/questions/52800904/disable-pwa-plugin-in-vue-cli-3

**Comment by LinusBorg** [comment]
I think this makes sense. I'll do make a PR.

**Comment by camiant** [comment]
temporary workaround

[https://stackoverflow.com/a/48188540](https://stackoverflow.com/a/48188540)

**Comment by zzx0106** [comment]
config.plugins.delete('pwa');
config.plugins.delete('workbox');
