### ISSUE TITLE
I made a mistake when creating a new vue/cli demo

### ISSUE THREAD

**Issue by qq229338869** [vuejs/vue-cli#3849]
### Version
3.6.3

### Reproduction link
[https://github.com/qq229338869/my-question/blob/master/vue/vue-cli/question-one](https://github.com/qq229338869/my-question/blob/master/vue/vue-cli/question-one)

### Environment info
```
  System:
    OS: macOS Mojave 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 66.0.3
    Safari: 12.0.3
  npmGlobalPackages:
    @vue/cli: 3.6.3
```

### Steps to reproduce
after install @vue/cli , webpack ,run  vue create my-project

### What is expected?
create the vue/cle demo

### What is actually happening?
fail
ERROR  command failed: pnpm install --loglevel error --shamefully-flatten

---
on windows ,i was success but macos.
i want to know "ERROR  command failed: pnpm install --loglevel error --shamefully-flatten"
when install pnpm ,run 'vue create', still fail,

**Comment by sodatea** [comment]
If you are in China, it's very likely the error is caused by the taobao npm registry.
I haven't figured out why but changing the registry from `https://registry.npm.taobao.org/` to `https://r.cnpmjs.org/` fixed this issue on my machine.

**Comment by qq229338869** [comment]
> If you are in China, it's very likely the error is caused by the taobao npm registry.
> I haven't figured out why but changing the registry from `https://registry.npm.taobao.org/` to `https://r.cnpmjs.org/` fixed this issue on my machine.

thank you for your answer.
i changed registry,it still doesn`t work.
now ,i create the demo on windows ,then copy it in macos ，it work.
forgive my Chinglish.
![image](https://user-images.githubusercontent.com/30120123/56423171-7e6edd00-62dd-11e9-98e4-2f7f94f61ae7.png)

**Comment by sodatea** [comment]
@qq229338869 
Try edit `~/.vuerc` and change the `useTaobaoRegistry` option to `false`.
Also, are you sure you have `pnpm` installed?

**Comment by sodatea** [comment]
Fixed. See https://github.com/cnpm/cnpmjs.org/issues/1458
