### ISSUE TITLE
Shell error creating new application

### ISSUE THREAD

**Issue by jtsom** [vuejs/vue-cli#3854]
### Version
3.6.3

### Environment info
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.1-next.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3766.2
    Firefox: Not Found
    Safari: 12.1
  npmGlobalPackages:
    @vue/cli: 3.6.3
```

### Steps to reproduce
When creating a new Vue application, an error is displayed before going through the new application steps.

### What is expected?
vue create new-application starts the new app wizard without errors.

### What is actually happening?
% vue create vue-ts-test
/bin/sh: pnpm: command not found

Vue CLI v3.6.3
? Please pick a preset: (Use arrow keys)
❯ VueDotNet (vue-router, stylus, babel, typescript)
  default (babel, eslint)
  Manually select features

**Comment by sodatea** [comment]
Fixed in https://github.com/vuejs/vue-cli/pull/3826 and will be included in the next release.
