### ISSUE TITLE
why the file in  static directory haven't  copy to dist directory while  execute   " npm run build "

### ISSUE THREAD

**Issue by xiaochen1** [vuejs/vue-cli#3856]
### Version
2.9.3

### Reproduction link
[https://github.com/xiaochen1/testbuild](https://github.com/xiaochen1/testbuild)

### Node and OS info
node:   v10.14.1

### Environment info
```
 npm run build
```

### Steps to reproduce
(1) vue  init webpack   testbuild
(2) cd  testbuild
(3)add  some  picture  into static
(3) npm run build 

### What is expected?
I expected the file  like  css、image、js  and so on  in static  directory should  copy  into dist directory  after execute  "npm run build "

### What is actually happening?
there  is no  picture in dist directory 

---
I want to know what  kind of reasons  can  lead to this issue  that   the files  in  static  directory  haven't  copy to  the dist directory  after  execute  "npm run build ";    how to resolve this problem?

**Comment by LinusBorg** [comment]
Static files go into /public, not /static.

See: https://cli.vuejs.org/zh/guide/html-and-static-assets.html

**Comment by LinusBorg** [comment]
Oh, I just see that this is using vue-cli 2. Why???
