### ISSUE TITLE
Not updating version when adding features

### ISSUE THREAD

**Issue by OmgImAlexis** [vuejs/vue-cli#386]
When features get added to this repo the minor version should be bumped and the latest version should be pushed to npm. Right now I have version 2.8.1 installed from npm which is the latest yet the version I have installed is different to what's in this repo with the exact same version number without even a minor version bump.

From what I can see about 25 commits have been added since the npm update. Maybe you should move to using a dev and master branch and only update npm when dev is merged into master like most projects?

**Comment by OmgImAlexis** [comment]
Closes: https://github.com/vuejs/vue-cli/issues/384

**Comment by posva** [comment]
Yes, we can do that but I really don't understand what's the matter here. It's normal for the repository code to be more advanced than the released version after all. If you want the latests version you don't rely on the master branch, you use a dist-tag like `latest`, and if you want the dev version you usually use the dev branch, which in this case is master.

**Comment by OmgImAlexis** [comment]
It's actually normal to use a dev branch as master should be the MASTER copy which is the latest public version. This is exactly what I've seen on every other large project even ones I work on.

**Comment by posva** [comment]
It's not about being normal or not, it's about what problem are you facing that can be solved by changing the branches names. The reason I'm asking this is to understand how important the task is to prioritise it

**Comment by OmgImAlexis** [comment]
Well going to the repo and new things being added that don't work will just end up causing issues like mine where I expected the complete field to work yet it doesn't as it's not up to date on npm as master is for some reason out of sync with it.

**Comment by posva** [comment]
If you are using the dev version, you're doing it at your own risk. I still don't see the matter

**Comment by OmgImAlexis** [comment]
If there's something added to the master then the MASTER on npm which is the latest version should also have the thing added hence the issue.

If you don't understand it maybe leave this issue for someone else on the development team to deal with.

**Comment by posva** [comment]
You're still not answering my question about the issue you had. I know what is a git flow, lol... Whatever...
I'll create a new proper issue but just so you know, you don't ned a dev/master flow for every project (large or not)

> If you don't understand it maybe leave this issue for someone else on the development team to deal with.

lol. Next time, keep that for yourself 😉

**Comment by OmgImAlexis** [comment]
The issue is you've got up to date code on your repo which is leading people to think they're implemented in the version that can be downloaded from npm.

This is not the case.

**Comment by OmgImAlexis** [comment]
The other issue is the versions isn't getting bumped when it should. 2.8.1 for example is listed on both the version of this repo with and without a complete field. That's an issue.

**Comment by posva** [comment]
Finally! Thanks

**Comment by luxueyan** [comment]
Yes! I agree with the @OmgImAlexis  .For example, the complete callback function is not supported in the version that can be downloaded from npm !
