### ISSUE TITLE
Night Watch Critical Issue https://www.npmjs.com/advisories/146

### ISSUE THREAD

**Issue by g5insider** [vuejs/vue-cli#3868]
### Version
3.4.0

### Reproduction link
[https://www.npmjs.com/advisories/146](https://www.npmjs.com/advisories/146)

### Environment info
```
https://www.npmjs.com/advisories/146
```

### Steps to reproduce
https://www.npmjs.com/advisories/146

### What is expected?
https://www.npmjs.com/advisories/146

### What is actually happening?
https://www.npmjs.com/advisories/146

---
https://www.npmjs.com/advisories/146

**Comment by LinusBorg** [comment]
#3257
