### ISSUE TITLE
babel-preset-env@7.4.0 and core-js@3 support?

### ISSUE THREAD

**Issue by ztyzbb** [vuejs/vue-cli#3869]
### What problem does this feature solve?
For future
https://babeljs.io/blog/2019/03/19/7.4.0
https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md

### What does the proposed API look like?
```
plugins: [
  ["@babel/transform-runtime", {
    corejs: 3,
  }]
  ["@babel/preset-env", {
    useBuiltIns: "usage",
    corejs: 3,
  }]
]
```

**Comment by sodatea** [comment]
Will be upgraded in v4, as addressed in the roadmap https://github.com/vuejs/vue-cli/issues/3649
