### ISSUE TITLE
Browser plugin in ui with windows

### ISSUE THREAD

**Issue by brunokunace** [vuejs/vue-cli#3872]
### Version
3.5.5

### Reproduction link
[https://github.com/brunokunace/vuesaxplugin](https://github.com/brunokunace/vuesaxplugin)

### Environment info
```
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Users\Brun00\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3
    @vue/babel-preset-app:  3.5.5
    @vue/babel-preset-jsx:  1.0.0-beta.3
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3
    @vue/babel-sugar-inject-h:  1.0.0-beta.3
    @vue/babel-sugar-v-model:  1.0.0-beta.3
    @vue/babel-sugar-v-on:  1.0.0-beta.3
    @vue/cli-overlay:  3.5.1
    @vue/cli-plugin-babel: ^3.5.0 => 3.5.5
    @vue/cli-plugin-eslint: ^3.5.0 => 3.5.1
    @vue/cli-service: ^3.5.0 => 3.5.3
    @vue/cli-shared-utils:  3.5.1
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.2
    vue: ^2.6.6 => 2.6.10
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuesaxplugin: file:F:\docker\vuesaxplugin => 1.0.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
I try to create a new vue-cli-plugin (example in github link),  but when i use vue ui --dev and select a plugin, he copy all files to node_modules, set package.json dependency and alert with error. This error is not found the dependency installed before.

### What is expected?
found dependency and install it

### What is actually happening?
don't know why, but not found

## More details (screens)

![image](https://user-images.githubusercontent.com/16597320/56586450-23c3d280-65b6-11e9-9f3d-f7fd783e69cf.png)

![image](https://user-images.githubusercontent.com/16597320/56586514-3b9b5680-65b6-11e9-96eb-aee130532811.png)

---
It's my test to make a plugin, maybe 90% chance this error is my code, 9% windows and 1% vue-cli/webpack

**Comment by Akryum** [comment]
First thing I noticed is that the plugin doesn't follow naming convention, which can lead to problems:

https://cli.vuejs.org/dev-guide/plugin-dev.html#discoverability
https://slides.com/akryum/create-a-vue-cli-plugin#/12

**Comment by brunokunace** [comment]
it's it @Akryum , i thought is only on npm, but now works!
