### ISSUE TITLE
Serialport module Uncaught TypeError:

### ISSUE THREAD

**Issue by wstefan20** [vuejs/vue-cli#3876]
### Version
3.6.3

### Reproduction link
[https://github.com/wstefan20/vue-cli3-serialport-error](https://github.com/wstefan20/vue-cli3-serialport-error)

### Environment info
```
 System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3
    @vue/babel-preset-app:  3.6.0
    @vue/babel-preset-jsx:  1.0.0-beta.3
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3
    @vue/babel-sugar-inject-h:  1.0.0-beta.3
    @vue/babel-sugar-v-model:  1.0.0-beta.3
    @vue/babel-sugar-v-on:  1.0.0-beta.3
    @vue/cli-overlay:  3.6.0
    @vue/cli-plugin-babel: ^3.6.0 => 3.6.0
    @vue/cli-plugin-eslint: ^3.6.0 => 3.6.0
    @vue/cli-service: ^3.6.0 => 3.6.0
    @vue/cli-shared-utils:  3.6.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.2
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Build generic vue-cli and add import SerialPort from 'serialport' in script section

### What is expected?
No errors

### What is actually happening?
Uncaught TypeError: Cannot read property 'modules' of undefined

---
This module works in SimulatedGREG boilerplate and older versions of vue, but vue cli3 keeps throwing an error. I have tried moving this code to the main.js and other places but same error. I have also tried using the webpack externals in the config file with no success. Not sure what is causing the error on this version and not the latter.

**Comment by sodatea** [comment]
See https://github.com/node-serialport/node-serialport/issues/1733
SerialPort cannot be webpacked. Even though you may have been able to hack it to work somehow, it is not officially supported.
