### ISSUE TITLE
 make fork-ts-checker-webpack-plugin async=false in default

### ISSUE THREAD

**Issue by TerenceZ** [vuejs/vue-cli#3877]
### What problem does this feature solve?
In default, the plugin `fork-ts-checker-webpack-plugin`'s option `async` is `true`, which means it make webpack dev server cannot print typescript errors on the error overlay, should we make it default to false, or use a custom hot dev entry and some plugins to make it work for async errors, just like what `react-dev-utils` does?

### What does the proposed API look like?
Make `async=false` in default for `fork-ts-checker-webpack-plugin`, or implement custom hot dev entry with plugins to report async errors.

**Comment by sodatea** [comment]
We're not likely to make `async` `false` by default, for performance concerns.
As for the custom error overlay feature, tracked at this issue: https://github.com/vuejs/vue-cli/issues/926
