### ISSUE TITLE
Fatal error in , line 0 # Check failed: U_SUCCESS(status).

### ISSUE THREAD

**Issue by armandsalle** [vuejs/vue-cli#3879]
### Version
3.6.3

### Environment info
```
System:
    OS: macOS Mojave 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.0.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
    Safari: 12.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3 
    @vue/babel-preset-app:  3.6.0 
    @vue/babel-preset-jsx:  1.0.0-beta.3 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3 
    @vue/babel-sugar-inject-h:  1.0.0-beta.3 
    @vue/babel-sugar-v-model:  1.0.0-beta.3 
    @vue/babel-sugar-v-on:  1.0.0-beta.3 
    @vue/cli-overlay:  3.6.0 
    @vue/cli-plugin-babel: ^3.6.0 => 3.6.0 
    @vue/cli-plugin-eslint: ^3.6.0 => 3.6.0 
    @vue/cli-service: ^3.6.0 => 3.6.0 
    @vue/cli-shared-utils:  3.6.0 
    @vue/component-compiler-utils:  2.6.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.2 
    vue: ^2.6.10 => 2.6.10 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 3.6.3
```

### Steps to reproduce
I got a new Macbook pro, and I haven't installed anything other than Nodejs.
I run sudo npm install @vue/cli -g

then sudo vue create coolkids
then cd coolkids
then sudo npm run serve

I try with sudo and without sudo, but it's always the same, the error : 

     INFO  Starting development server...
     98% after emitting CopyPlugin
    
    
    #
    # Fatal error in , line 0
    # Check failed: U_SUCCESS(status).
    #
    #
    #
    #FailureMessage Object: 0x7ffeefbfc0c0Illegal instruction: 4

### What is expected?
run the basic vue serve

### What is actually happening?

     INFO  Starting development server...
     98% after emitting CopyPlugin
    
    
    #
    # Fatal error in , line 0
    # Check failed: U_SUCCESS(status).
    #
    #
    #
    #FailureMessage Object: 0x7ffeefbfc0c0Illegal instruction: 4

---
I don't understand, I do nothing else on my Mac. I format and install the last version of Mojave. Then, I only install NodeJs, then @vue/cli and it's not working...

**Comment by sodatea** [comment]
Can't reproduce on my machine but I suspect this is somehow related to the freshly released Node.js v12.
Try to downgrade it to v10 LTS?

**Comment by armandsalle** [comment]
I install nvm and install the 10.15.3 version of nodejs and now it's working ! Th'x a lot 😎

**Comment by watership** [comment]
I have the same problem. if run with Node: 12.0.0, the error must appear.

**Comment by borodadada** [comment]
I have same problem too. It fix in future? What to do now?

**Comment by armandsalle** [comment]
Just install nvm and install node 10.15.3 and restart your computer and that's it !

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/issues/3883 and https://github.com/nodejs/node/issues/27379

It's a bug in Node.js v12, may get fixed in the next release of Node.js.
For now just revert back to Node.js v10.

**Comment by r692802421** [comment]
i have the same wrong many times!Now i try to download the  node 10.15.3 version!I hope it work!

**Comment by r692802421** [comment]
now install v10.15.3 it worked! thanks a lot!

**Comment by likeyouli** [comment]
The problem has been solved, thank you very much!

**Comment by cristiaan3003** [comment]
Thanks a lot!

**Comment by bruceeewong** [comment]
Thanks a lot. Switch back to v10 works.
