### ISSUE TITLE
error: Parsing error: Unexpected character '�' 

### ISSUE THREAD

**Issue by heshamelmasry77** [vuejs/vue-cli#3882]
![Screenshot 2019-04-24 at 17 35 20](https://user-images.githubusercontent.com/15607302/56668518-4d652280-66b8-11e9-9fcb-18b55b34250f.png)

### Steps to reproduce
run : vue-cli-service lint src/*/** --fix

### What is expected?
to lint the code and works normally 

### What is actually happening?
i get this issue :
error: Parsing error: Unexpected character '�'

> 1 | �PNG
    | ^
  2 | 
  3 | 
  4 | IHDR��X��tEXtSoftwareAdobe ImageReadyq�e<#iTXtXML:com.adobe.xmp<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?> <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.6-c014 79.156797, 2014/08/20-09:53:02        "> <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"> <rdf:Description rdf:about="" xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/" xmlns:stRef="http://ns.adobe.com/xap/1.0/sType/ResourceRef#" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmpMM:DocumentID="xmp.did:996BB8FA761611E5A84E8FB1649162D8" xmpMM:InstanceID="xmp.iid:996BB8F9761611E5A84E8FB1649162D8" xmp:CreatorTool="Adobe Photoshop CC (Macintosh)"> <xmpMM:DerivedFrom stRef:instanceID="xmp.iid:656A1279769211E391898D90BF8CE476" stRef:documentID="xmp.did:656A127A769211E391898D90BF8CE476"/> </rdf:Description> </rdf:RDF> </x:xmpmeta> <?xpacket end="r"?>V�*4IDATx��]k�]�u^�u�=��] at src/assets/logo.png:1:1:
> 1 | �PNG
    | ^
  2 | 
  3 | 
  4 | IHDR��X��tEXtSoftwareAdobe ImageReadyq�e<#iTXtXML:com.adobe.xmp<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?> <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.6-c014 79.156797, 2014/08/20-09:53:02        "> <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"> <rdf:Description rdf:about="" xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/" xmlns:stRef="http://ns.adobe.com/xap/1.0/sType/ResourceRef#" xmlns:xmp="http://ns.adobe.com/xap/1.0/" xmpMM:DocumentID="xmp.did:996BB8FA761611E5A84E8FB1649162D8" xmpMM:InstanceID="xmp.iid:996BB8F9761611E5A84E8FB1649162D8" xmp:CreatorTool="Adobe Photoshop CC (Macintosh)"> <xmpMM:DerivedFrom stRef:instanceID="xmp.iid:656A1279769211E391898D90BF8CE476" stRef:documentID="xmp.did:656A127A769211E391898D90BF8CE476"/> </rdf:Description> </rdf:RDF> </x:xmpmeta> <?xpacket end="r"?>V�*4IDATx��]k�]�u^�u�=��]

**Comment by LinusBorg** [comment]
You should restrict linting to `.{vue|js|ts}`

Right now you are linting *all types of files, and the error you are seeing is eslint trying to lint a *.png file.

**Comment by heshamelmasry77** [comment]
okay my solution after i search how to do it on the package.json is like that :
 i changed my lint script from : 
```
"lint": "vue-cli-service lint src/*/** --fix"
```
to
```
    "lint": "vue-cli-service lint src/*/*.{js,vue} --fix"
```

now i a only specifying which files exactly i want to lint as it used to lint the images before!
