### ISSUE TITLE
Best practice to compress css selector names?

### ISSUE THREAD

**Issue by georgyfarniev** [vuejs/vue-cli#3884]
### What problem does this feature solve?
Hello. First, thank you for working on this useful tool.

My story: I tried to find information how to implement css selector name compression to reduce size of bundle, but I found only this article, which seems bit outdated:  https://medium.com/@my_own_grave/reducing-css-generated-by-vue-loader-by-using-classnames-shorten-trick-aa1d25d77473

Is there a good solution for this task nowadays, or maybe someone solved it without monkey-patching css-loader? If it is solved somehow, I would like to see any example. I think, it would be great if vue-cli can provide such functionality. 

Thanks in advance.

### What does the proposed API look like?
I suggest to add some option to vue.config.js that will enable css class name compresion, such as: ```compressCssClassNames: true```

**Comment by LinusBorg** [comment]
The vue-loader specific restriction mentioned in the article no longer applies.

You can simply add your own getLocalIdent function to the css loader options like this:
```javascript
module.exports = {
  css: {
    loaderOptions: {
      css: {
        getLocalIdentName() => ...
      }
    }
  }
}
```

**Comment by georgyfarniev** [comment]
@LinusBorg thank you, I will definitely try it as soon as I get to my computer and let you know it it solved.

**Comment by georgyfarniev** [comment]
@LinusBorg so this will work only if I import css file, not in vue sfc or .sass file? There’s no way or plans to implement this?

**Comment by LinusBorg** [comment]
It works everywhere, provided you are using css modules of course.

**Comment by georgyfarniev** [comment]
@LinusBorg I apologize for stupid question, but what does it mean to use css modules in context of the topic? How can I enable it for vue-cli? Does it mean simply importing css file in root of my vue project?

**Comment by LinusBorg** [comment]
Oh, I assumed you knew what css modules  where since the article you linked to talks about it, basically.

**Comment by georgyfarniev** [comment]
@LinusBorg thank you. Closing this issue.
