### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by shutong037** [vuejs/vue-cli#3892]
### Version
3.6.0

### Environment info
```
本地环境
```

### Steps to reproduce
执行完 “npm run build”后，页面开始报错。

### What is expected?
关闭相关的错误信息

### What is actually happening?
Uncaught SyntaxError: Unexpected token <

Error: Loading chunk about failed.

---
请修改相关的官方文档，感觉整个流程下来，还是不明白说的是什么。

**Comment by sodatea** [comment]
请遵守 Issue Helper 的说明，**请提供`vue info` 的完整输出结果和可以运行的复现**，否则我们也无法明白你问的是什么
