### ISSUE TITLE
Uncaught TypeError: __webpack_require__(...).context is not a function

### ISSUE THREAD

**Issue by itlangzi** [vuejs/vue-cli#3893]
### Version
3.6.0

### Environment info
```
vue 2.6.0  @vue/cli-service   3.6.0
```

### Steps to reproduce
js文件中使用 require.context （webpack提供）浏览器 出现__webpack_require__(...).context is not a function （require.context is not function ） 同样 require.ensure 也不可用

### What is expected?
require.context 可用

### What is actually happening?
require.context 不可用

**Comment by sodatea** [comment]
请遵守 Issue Helper 的说明，**请提供可以运行的复现**

**Comment by itlangzi** [comment]
这个问题已解决 [require-context](https://webpack.docschina.org/guides/dependency-management/)
**传递给 require.context 的参数必须是字面量(literal)！**

**Comment by mkknx** [comment]
Seriously you are on an english-based community, you cannot speak in english, please? It may be useful for other devs reading you.

**Comment by papa-zulu** [comment]
What @itlangzi tried to say there is that the path parameter has to be a literal regex and can't be passed via variable.
You can read more about this in another issue here: https://github.com/webpack/webpack/issues/9300#issuecomment-524744609

**Comment by MAN-chen-bug** [comment]
![image](https://user-images.githubusercontent.com/68693997/106995180-4b028880-67b9-11eb-99a6-1fdeb0736159.png)

**Comment by MAN-chen-bug** [comment]
![image](https://user-images.githubusercontent.com/68693997/106995214-62417600-67b9-11eb-8684-942ef0d42fcd.png)
this is a item of vue. why is that ?
