### ISSUE TITLE
Change directory for static assets

### ISSUE THREAD

**Issue by redcomethk** [vuejs/vue-cli#3895]
### What problem does this feature solve?
Currently, from the official website, any static assets placed in the public folder will simply be copied and not go through webpack. I need to change the directory as I do not need to copy those static assets again in the output directory. It is an existing project and the public directory is already being used by other parts of the project, so it is not a good idea to change the directory name to cater for using with vue cli which is added afterwards. 

I have tried to find out the corresponding solution but I cannot find it. So I would like to request the following feature. In case existing config can solve the problem please let me know. Thanks!

### What does the proposed API look like?
// If user just wants to skip this behaviour, one can set an empty dir in this property to override the original default 'public' and everythings would be fine.
// vue.config.js
module.exports = {
  staticAssetsDir: 'otherAssetsDir'
}

**Comment by Akryum** [comment]
Is it required for you to mix the vue-cli project with the other one? Maybe you can move it to it's own sibling folder or sub-folder?

**Comment by redcomethk** [comment]
I now try to set another project for the frontend and do the consolidation in the backend. However, I think there may also be some others who want the same feature.

**Comment by LinusBorg** [comment]
This has been requested before and we have declined. 

We want to provide a consistent baseline for projects, Making folders like /public and /src configurable goes against that goal and complicates our internals. 

It's still possible to adjust webpack for this manually, though.
