### ISSUE TITLE
The project created has only three files.

### ISSUE THREAD

**Issue by skillnull** [vuejs/vue-cli#3900]
### Version
3.6.3

### Environment info
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
  Binaries:
    Node: 11.10.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.108
    Firefox: 65.0.1
    Safari: 12.0.3
  npmGlobalPackages:
    @vue/cli: 3.6.3
```

### Steps to reproduce
Vue CLI v3.6.3
✨  Creating project in /Users/liyafei/Work/skillnull/vue-power-popup.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

audited 23519 packages in 25.38s
found 0 vulnerabilities

🚀  Invoking generators...
📦  Installing additional dependencies...

audited 23519 packages in 6.8s
found 0 vulnerabilities

⚓  Running completion hooks...

📄  Generating README.md...

🎉  Successfully created project vue-power-popup.
👉  Get started with the following commands:

 $ cd vue-power-popup
 $ npm run serve

➜  skillnull cd vue-power-popup
➜  vue-power-popup git:(master) ✗ ll
total 752
-rw-r--r--  1 liyafei  staff   147B  4 27 15:44 README.md
-rw-r--r--  1 liyafei  staff   367K  4 27 15:44 package-lock.json
-rw-r--r--  1 liyafei  staff   213B  4 27 15:44 package.json

➜  vue-power-popup git:(master) ✗ npm run serve
npm ERR! missing script: serve

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liyafei/.npm/_logs/2019-04-27T07_49_43_174Z-debug.log

### What is expected?
Complete project structure.

### What is actually happening?
There are only three files:

README.md    
package-lock.json     
package.json

**Comment by LinusBorg** [comment]
Those reproduction steps are not steps describing how to reproduce. You just copied the output of the console *after* the steps. 

This is likely permissions-related.

**Comment by skillnull** [comment]
I operate step by step according to the official document, how do I solve the problem of permissions-related?

**Comment by bulletmark** [comment]
@skillnull, this issue is a symptom of issue #3664 which you also commented on to say you have that problem as well. That issue #3664 was fixed and closed about a month ago so update your version of Vue CLI and all should be ok.

This bug can be closed.
