### ISSUE TITLE
在使用webpack4的optimization情况下，生成的静态页面中，不会自动注入js文件

### ISSUE THREAD

**Issue by qingdengyue** [vuejs/vue-cli#3901]
### Version
3.6.3

### Reproduction link
[https://github.com/qingdengyue/vue-cli-repos](https://github.com/qingdengyue/vue-cli-repos)

### Environment info
```
Node v8.11.4
Win10：10.0.17134

```

### Steps to reproduce
直接 npm run build即可

### What is expected?
js文件可以被注入

### What is actually happening?
js文件没有被注入

**Comment by qingdengyue** [comment]
如果不配置vue.config.js 中的配置节configureWebpack，则js文件可以被注入。

**Comment by sodatea** [comment]
原因应该是配置了 `splitChunks.maxSize` 导致 webpack 生成的 chunk 名字产生变化，而 html-webpack-plugin 用的仍然是旧的 chunk 名字，所以没有注入进去。

我一时也想不到怎么解决这个问题，不过这不是 Vue CLI 的 bug，建议去其他相关项目的论坛或者问答网站上提问。

**Comment by sodatea** [comment]
最直接的办法是直接注释掉 maxSize 那一行配置

**Comment by qingdengyue** [comment]
@sodatea 奇怪的 是preload插件确可以获取到chunks，然后成功注入preload的css和js文件，reload插件还在html-webpack-plugin的后面。

**Comment by sodatea** [comment]
因为 preload 插件配置了 `include: 'initial'`，而你在 html-webpack-plugin 里指定了只有 `[entryChunk]` 会被包含进来，但是又因为 `maxSize` 导致真正的入口 chunk 和你指定的名字不同，所以就没了。

**Comment by soneway** [comment]
持续关注, 解决了请告诉我

**Comment by heshimang** [comment]
> 
这个帮我解决了问题，希望也能帮到你
https://github.com/vuejs/vue-cli/issues/3454#issuecomment-821034908
