### ISSUE TITLE
Change a Vue script URL in demo.html depending on NODE_ENV

### ISSUE THREAD

**Issue by naoki-kishi** [vuejs/vue-cli#3906]
### What problem does this feature solve?
When we execute  `vue-cli-service build` with `--target` option: `wc`, `wc-async`, or `lib`, we get a `demo.html` at `/dist`.
In `demo.html`, we can see the below code,
```
<script src="https://unpkg.com/vue"></script>
```

However, `https://unpkg.com/vue` is a script for development. So, when you open a `demo.html` in browser, console shows you the below message even if `NODE_ENV` is `production`,
```
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
``` 

### What does the proposed API look like?
We solve this problem by changing a script url  depending on `NODE_ENV`.
In detail, using `htmlWebpackPlugin.options`, we inject appropriate url from `resolveLibConfig.js` and `resolveWcConfig.js` .

Do you mind if I send a Pull Request?

**Comment by LinusBorg** [comment]
I think we inlcuded the dev build so devtools work etc. I don't think that it makes sense to include a minified production build in this demo page.

**Comment by sodatea** [comment]
I don't think this feature makes sense. It's a demo page after all.

**Comment by Makio64** [comment]
Hi, I run in similar issue and it does make sense when you run with the command --inline-vue to not have 
<script src="https://unpkg.com/vue"></script>
in the demo page
