### ISSUE TITLE
Parse DotENV (.env) file with standard syntax

### ISSUE THREAD

**Issue by Aysnine** [vuejs/vue-cli#3907]
### Version
3.7.0

### Environment info
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.108
    Firefox: Not Found
    Safari: 12.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3 
    @vue/babel-preset-app:  3.7.0 
    @vue/babel-preset-jsx:  1.0.0-beta.3 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3 
    @vue/babel-sugar-inject-h:  1.0.0-beta.3 
    @vue/babel-sugar-v-model:  1.0.0-beta.3 
    @vue/babel-sugar-v-on:  1.0.0-beta.3 
    @vue/cli-overlay:  3.7.0 
    @vue/cli-plugin-babel: ^3.7.0 => 3.7.0 
    @vue/cli-plugin-eslint: ^3.7.0 => 3.7.0 
    @vue/cli-service: ^3.7.0 => 3.7.0 
    @vue/cli-shared-utils:  3.7.0 
    @vue/component-compiler-utils:  2.6.0 
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    eslint-plugin-vue: ^5.0.0 => 5.2.2 
    vue: ^2.6.10 => 2.6.10 
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.3 
    vue-router: ^3.0.3 => 3.0.6 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vue2-transitions: ^0.3.0 => 0.3.0 
    vuex: ^3.0.1 => 3.1.0 
  npmGlobalPackages:
    @vue/cli: 3.6.3
```

### Steps to reproduce
`.env`:
```
VUE_APP_FOO='BAR' # comment here, but get WTF value
```

### What is expected?
``` js
process.env.VUE_APP_FOO === 'BAR'
```

### What is actually happening?
``` js
process.env.VUE_APP_FOO === "'BAR'"
```

---
vue-cli3 current way for parse: https://github.com/vuejs/vue-cli/blob/9c1e797ac6/packages/%40vue/cli-service/lib/util/loadEnv.js#L13

maybe use https://github.com/motdotla/dotenv ?

syntax demo:

![EC65871690577AAF53C675B4B517EEE2](https://user-images.githubusercontent.com/10137653/56867492-67846500-6a18-11e9-9ca5-8ac7f568c9f7.jpg)

![image](https://user-images.githubusercontent.com/10137653/56867513-8aaf1480-6a18-11e9-9e59-2c7f86573202.png)

**Comment by sodatea** [comment]
FYI we do use dotenv since v3.4.1 https://github.com/vuejs/vue-cli/commit/225b55893590ef74c419f692dacc37b28b028578
And I don't think it supports inline comments

**Comment by Akryum** [comment]
> maybe use https://github.com/motdotla/dotenv ?

We already use the `dotenv` package to parse the `.env` files.

> vue-cli3 current way for parse: https://github.com/vuejs/vue-cli/blob/9c1e797ac6/packages/%40vue/cli-service/lib/util/loadEnv.js#L13

[Here is the real current source code](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/Service.js#L99) (since [@vue/cli-service 3.4.1](https://github.com/vuejs/vue-cli/commit/225b55893590ef74c419f692dacc37b28b028578)).

**Comment by Akryum** [comment]
Beaten by few milliseconds 😹

**Comment by LinusBorg** [comment]
it's also worth noting that the double strings are on purpose so we end up with valid code when webpack replaces the `process.env.*` string with the content.

**Comment by Akryum** [comment]
@LinusBorg The issue was the inline comment. We use `JSON.stringify` [internally](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/util/resolveClientEnv.js#L17) to add the quotes, to if they were not removed by `dotenv`, you would end up with quotes inside the string.
