### ISSUE TITLE
Disable autoprefixer plugin

### ISSUE THREAD

**Issue by tadejstanic** [vuejs/vue-cli#391]
Is there any way to disable autoprefixer plugin in vue-build when post-cssnext plugin is added?

I think the problem lays in this part of code from [vue-build](https://github.com/vuejs/vue-cli/blob/master/bin/vue-build#L96):

```
var postcssOptions = {
  plugins: [
    require('autoprefixer')(Object.assign({
      browsers: ['ie > 8', 'last 5 versions']
    }, options.autoprefixer))
  ]
}
```

which includes autoprefixer regardless the situation where other plugin (in my situation postcss-cssnext) may also include autoprefixer plugin. At the end, CSS code is autoprefixed twice which unnecessary extend re/build process.

**Comment by posva** [comment]
You can overwrite the postcss config: http://vue-loader.vuejs.org/en/features/postcss.html

Next time, open the issue on the template repo please

**Comment by tadejstanic** [comment]
What template repo? This issue is linked to vue build which is part of this repo...

**Comment by posva** [comment]
Oh right, sorry for that. Had a hard day
ping @egoist

**Comment by egoist** [comment]
you can disable autoprefixer in your cssnext plugin instead

**Comment by tadejstanic** [comment]
Ok. It seems that cssnext plugin doesn't provide an option for disabling autoprefixer. I'll try with postcss option. Thx @egoist
