### ISSUE TITLE
Some missing workbox configuration options 

### ISSUE THREAD

**Issue by leolux** [vuejs/vue-cli#3911]
### What problem does this feature solve?
There seems to be no possibility to configure workbox options like the debug flag or the cache name prefix regarding https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-pwa. Having the ability to configure these options would improve the developer experience.

### What does the proposed API look like?
I suggest to add these options to vue.config.js:
```
module.exports = {
    pwa: {
        [...]
        workboxOptions: {
            debug: true,
            cacheNamePrefix: 'customCacheName'
        }
    },
```

**Comment by LinusBorg** [comment]
We are using workbox's webpack plugin, and pass all options through to that plugin.

Please see their docs here: https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin#full_generatesw_config

If you find an option to be missing, you would have to open an issue in their repo. We can't to anything about it.
