### ISSUE TITLE
IOS 8.3 vue3 blank screen

### ISSUE THREAD

**Issue by walleevaysh** [vuejs/vue-cli#3917]
### Version
3.2.3

### Environment info
```
IOS  8.3
```

### Steps to reproduce
1,  install vue-cli3.2.3
2,  vue create vue-office     choose  default config
3, npm run build 
4, ios 8.3   open it    blank screen   

it seem like ios 9.3.3 will blank screen 

### What is expected?
page can show in ios 8.3

### What is actually happening?
may be es6 can not change to es5 correct

**Comment by sodatea** [comment]
Is it iOS 8.3 or iOS 9.3.3? I don't understand.
See the documentation for how to configure targeted browsers: https://cli.vuejs.org/guide/browser-compatibility.html#browserslist

Both iOS 8 & iOS 9's market shares are too small to include by default: https://browserl.ist/?q=ios+%3E%3D+8 (The default target is `["> 1%", "last 2 versions"]`)
