### ISSUE TITLE
npm install -g @vue/cli npm WARN

### ISSUE THREAD

**Issue by jquery2005** [vuejs/vue-cli#3925]
### Version
3.7.0

### Reproduction link
[https://github.com/vuejs/vue-cli/issues/516](https://github.com/vuejs/vue-cli/issues/516)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
  Binaries:
    Node: 10.15.3 - E:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Users\msdn1\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - E:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
PS E:\VueLearning> node -v
v10.15.3
PS E:\VueLearning> npm -v
6.4.1
PS E:\VueLearning> vue info

Environment Info:

System:
OS: Windows 10
CPU: (8) x64 Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Binaries:
Node: 10.15.3 - E:\Program Files\nodejs\node.EXE
Yarn: 1.15.2 - C:\Users\msdn1\AppData\Roaming\npm\yarn.CMD
npm: 6.4.1 - E:\Program Files\nodejs\npm.CMD
Browsers:
Edge: 42.17134.1.0
npmGlobalPackages:
@vue/cli: Not Found

PS E:\CSharp\VueLearning> npm uninstall -g @vue/cli
removed 685 packages in 16.855s
PS E:\VueLearning> npm install -g @vue/cli
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
PS E:\VueLearning>

### What is expected?
no npm WARN deprecated

### What is actually happening?
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead

**Comment by LinusBorg** [comment]
Those are warnings, not errors. And they come from transitive dependencies that we can't influence.

Vue CLI works just fine. Ignore the warnings.

**Comment by DavyGuedes** [comment]
Hi.
> This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

Do we need to worry about this message? Or is there no security issue about this and also should we just ignore the warning, since it comes from transitive dependencies? 

Thanks.
