### ISSUE TITLE
3.7.0 breaks codesandbox template

### ISSUE THREAD

**Issue by tkrugg** [vuejs/vue-cli#3928]
### Version
3.7.0

### Reproduction link
[https://codesandbox.io/s/r4p8l2m1kn](https://codesandbox.io/s/r4p8l2m1kn)

### Environment info
```
Codesandbox on chrome
```

### Steps to reproduce
1. open the vue template for codesandbox: https://codesandbox.io/s/vue
2. update cli dependencies from 3.6.0 to 3.7.0

### What is expected?
it should continue working 

### What is actually happening?
Seeing compilation errors

Error: [BABEL] /src/main.js: Error: ENOENT: No such file or directory., '/events' (While processing: "base$0")

---
N/A

**Comment by sodatea** [comment]
The only commit shipped in `@vue/babel-preset-app` is this one https://github.com/vuejs/vue-cli/commit/bc1a345fe1c3c42674c3548610088365f55bc7c3#diff-d8e341482c7dd4a7872d0eea73aa34d9R176
We've added a new plugin and seems codesandbox can't properly handle it.

@CompuIves is working on a fix as he said [on twitter](https://twitter.com/CompuIves/status/1122482256348635139)
