### ISSUE TITLE
use Newest vue-cli build project can't loader the css style from the .vue file

### ISSUE THREAD

**Issue by HelTi** [vuejs/vue-cli#393]
the App.vue <style></style> can loader .but I write components and import the component into App.vue.
Visit the website the <style type="text/css"></style> is blank . But the App.vue <style>.....</style> have style content !
why?

**Comment by posva** [comment]
Hello!
Please, open the issue on the relevant template repo (I think you're using the [webpack one](https://github.com/vuejs-templates/webpack)) and provide some steps to reproduce the problem.
Thanks!
