### ISSUE TITLE
Bug report tool broken

### ISSUE THREAD

**Issue by wellcaffeinated** [vuejs/vue-cli#3931]
Reproduce steps:
* Visit bug report tool
* attempt to fill out version field
* open developer console

you will see the following error:
```
Failed to load resource: api.github.com/repos/vuejs/vue-cli/releases?page=1&per_page=100:1
the server responded with a status of 403 (Forbidden)
```

Here's what the github api is returning
```
{
  "message": "API rate limit exceeded for 132.163.141.72. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by wellcaffeinated** [comment]
@LinusBorg 
Sorry i had to ping someone. The bug report tool itself is broken so I can't report bugs...

**Comment by Akryum** [comment]
You got rate limited by the GitHub API on your IP.
