### ISSUE TITLE
Webpack 4.28.4 dependency breaks wasm loading

### ISSUE THREAD

**Issue by wellcaffeinated** [vuejs/vue-cli#3932]
*Aside: Sorry i can't use your bug report tool. see #3931*

Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i7-3667U CPU @ 2.00GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 57.0.4
    Safari: 12.0.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3
    @vue/babel-preset-app:  3.7.0
    @vue/babel-preset-jsx:  1.0.0-beta.3
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3
    @vue/babel-sugar-inject-h:  1.0.0-beta.3
    @vue/babel-sugar-v-model:  1.0.0-beta.3
    @vue/babel-sugar-v-on:  1.0.0-beta.3
    @vue/cli-overlay:  3.7.0
    @vue/cli-plugin-babel: ^3.7.0 => 3.7.0
    @vue/cli-plugin-eslint: ^3.7.0 => 3.7.0
    @vue/cli-plugin-pwa: ^3.7.0 => 3.7.0
    @vue/cli-service: ^3.7.0 => 3.7.0
    @vue/cli-shared-utils:  3.7.0
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.2
    vue: ^2.6.10 => 2.6.10
    vue-cli-plugin-pug: ^1.0.7 => 1.0.7
    vue-cli-plugin-vuetify: ^0.5.0 => 0.5.0
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router: ^3.0.3 => 3.0.6
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuetify: ^1.5.5 => 1.5.14
    vuetify-loader: ^1.0.5 => 1.2.2
    vuex: ^3.0.1 => 3.1.0
  npmGlobalPackages:
    @vue/cli: Not Found

Attempting to load .wasm modules with the webpack 4.28.x won't work. It results in...

> Module parse failed: Unexpected section: 0xfe
> You may need an appropriate loader to handle this file type.
> Error: Unexpected section: 0xfe
>     at new CompileError (/Users/wellcaffeinated/Documents/github/nist/spdcalc-ui/node_modules/@webassemblyjs/helper-api-error/lib/index.js:40:109)
>     at parseSection (/Users/wellcaffeinated/Documents/github/nist/spdcalc-ui/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1542:11)
>     at Object.decode (/Users/wellcaffeinated/Documents/github/nist/spdcalc-ui/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1559:25)
>     at decode (/Users/wellcaffeinated/Documents/github/nist/spdcalc-ui/node_modules/@webassemblyjs/wasm-parser/lib/index.js:240:21)
>     at WebAssemblyParser.parse (/Users/wellcaffeinated/Documents/github/nist/spdcalc-ui/node_modules/@vue/cli-service/node_modules/webpack/lib/wasm/WebAssemblyParser.js:74:19)
>     at doBuild.err (/Users/wellcaffeinated/Documents/github/nist/spdcalc-ui/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:460:32)
>     at runLoaders (/Users/wellcaffeinated/Documents/github/nist/spdcalc-ui/node_modules/@vue/cli-service/node_modules/webpack/lib/NormalModule.js:342:12)
>     at /Users/wellcaffeinated/Documents/github/nist/spdcalc-ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
>     at iterateNormalLoaders (/Users/wellcaffeinated/Documents/github/nist/spdcalc-ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
>     at Array.<anonymous> (/Users/wellcaffeinated/Documents/github/nist/spdcalc-ui/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
>     at Storage.finished (/Users/wellcaffeinated/Documents/github/nist/spdcalc-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
>     at provider (/Users/wellcaffeinated/Documents/github/nist/spdcalc-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
>     at /Users/wellcaffeinated/Documents/github/nist/spdcalc-ui/node_modules/graceful-fs/graceful-fs.js:90:16
>     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
> 
>  @ ./src/plugins/vue-wasm.js 8:0-46 107:9-41
>  @ ./src/main.js
>  @ multi (webpack)-dev-server/client?http://localhost:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

This is a reported and solved issue in webpack. It was fixed in webpack version 4.29.5
https://github.com/webpack/webpack/issues/8781#issuecomment-471855144

I'd love to use WASM. Pretty please update to use webpack >=4.29.5

**Comment by sodatea** [comment]
Well, this is a tradeoff for us.
There's a bug in npm and it might be triggered by webpack >= 4.29, see https://github.com/webpack/webpack/issues/8656
This bug is no easy to identify and fix for npm users. So we decided to pin our version for now.

For yarn users, however, the webpack version can be easily upgraded by adding a `resoultions` field in `package.json`, see https://yarnpkg.com/en/docs/selective-version-resolutions/
