### ISSUE TITLE
[@vue/pwa] add option to configure crossorigin tag in manifest link in generated index.html

### ISSUE THREAD

**Issue by BigsonLvrocha** [vuejs/vue-cli#3933]
### What problem does this feature solve?
I work with an apache server with sspi auth, so I've been having problems with the manifest.json include returning 401, with the text:

    This server could not verify that you are authorized to access the URL "[...]/manifest.json". You either supplied the wrong credentials (e.g. bad password), or you browser doesn't understand how to supply the credentials required.

Adding `crossorigin=use-credentials` to the manifest link tag fixes it, but there is no automatic generation, it's something I have to do every time I build a new version. This is something that could be a plugin setting

### What does the proposed API look like?
add `pwa.crossorigin` seeting option to vue.config.js file to specify if crossorigin tag should be added and if so, it's value

**Comment by drewjosh** [comment]
@BigsonLvrocha From the MR and the docs I suppose this should work, but in my app it doesn't. Setting the property crossorigin: "use-credentials" in pwa or manifestOptions property doesn't have any effect on the generated manifest tag. 
I'm using @vue/cli-service version 5.0.8. Can you help please?
