### ISSUE TITLE
在centOs中发现当安装 @vue/cli-plugin-unit-mocha 这个插件时出现错误问题 window未发现此类问题

### ISSUE THREAD

**Issue by hddGithub02** [vuejs/vue-cli#3949]
### Version
3.7.0

### Environment info
```
node:14094) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at /project/node-v8.11.3-linux-x64/lib/node_modules/@vue/cli/node_modules/envinfo/dist/envinfo.js:1:55150
    at <anonymous>
(node:14094) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14094) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Steps to reproduce
ue CLI v3.7.0
✨  Creating project in /root/platform-web.
⚙  Installing CLI plugins. This might take a while...

> nodent-runtime@3.2.1 install /root/platform-web/node_modules/nodent-runtime
> node build.js

fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/root/platform-web/node_modules/nodent-runtime/dist/index.js'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Object.<anonymous> (/root/platform-web/node_modules/nodent-runtime/build.js:5:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)

### What is expected?
问题解决

### What is actually happening?
单个安装还是vue-cli安装涉及到 @vue/cli-plugin-unit-mocha

**Comment by sodatea** [comment]
https://cli.vuejs.org/guide/troubleshooting.html#running-installation-with-sudo-or-as-root
不要用 root 用户身份安装项目的依赖。如果非要这么做请加上 `npm_config_unsafe_perm=true` 的前缀
