### ISSUE TITLE
使用vue 过滤器，用switch-case报错

### ISSUE THREAD

**Issue by xuxiaoxiao312** [vuejs/vue-cli#395]
`    filters: {
      iPhoneModel: function (value) {
        switch (value) {
          case 'iPhone1,1':
            return 'iPhone 2G'
            break
          default:
            return value
        }
      }
    }`
![image](https://cloud.githubusercontent.com/assets/24541297/23840712/8169ba28-07e2-11e7-9dd0-25ebab39718e.png)
该怎么正确使用switch case 它才不会报错呢

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

That is just an eslint rule failing in your code
