### ISSUE TITLE
Builder pre-appends slash '/' to font-faces paths

### ISSUE THREAD

**Issue by mateuszs** [vuejs/vue-cli#3953]
### Version
3.5.2

### Environment info
```
vue.config.js

const path = require('path');

module.exports = {
    assetsDir: './static',
    publicPath: '',
    transpileDependencies: [
        /\bvue-awesome\b/,
        /node_modules[/\\\\]vuetify[/\\\\]/
    ],
    css: {
        extract: {
            filename: '[name].css',
            chunkFilename: '[name].css'
        }
    },
    configureWebpack: () => {
        return {
            output: {
                filename: '[name].js',
                chunkFilename: '[name].js'
            },
            resolve: {
                alias: {
                   styles: path.join(__dirname, 'src/assets/css'),
                   images: path.join(__dirname, 'src/assets/images')
               }
            }
        }
    }
}
```

### Steps to reproduce
1. Install vuetify material icons
2. Install vue-cli 3.5.2
3. Build with provided config
4. Open dist/chunk-vendors.css and find paths to font-faces (builder pre-appends / to paths)

### What is expected?
@font-face{
font-family:Material Icons;
font-style:normal;
font-weight:400;
src:url(static/fonts/MaterialIcons-Regular.016c14ad.eot);
}

### What is actually happening?
@font-face{
font-family:Material Icons;
font-style:normal;
font-weight:400;
src:url(/static/fonts/MaterialIcons-Regular.016c14ad.eot);
}

---
Works fine on 3.3.0. Bugged on 3.5.2

**Comment by LinusBorg** [comment]
Please provide an actual run able production as requested in our issue guidelines.
