### ISSUE TITLE
vue-cli@3.0 component <keep-alive> something the matter 

### ISSUE THREAD

**Issue by 630133368** [vuejs/vue-cli#3958]
### Version
3.0.5

### Node and OS info
node v10.9.0      windows 10

### Steps to reproduce
Build projects with vue-cli@3.0 and Typescript。
Use es6  class syntax to create and export components in a .vue file。

export default class Home extends Vue {}

I need to use <keep-alive> component to cache <view-route>. I use the include of <keep-alive> to store the component name Home.

But this only applies to development environments.After compiling to the generation environment, vue-cli@3.0 will parse and compress the source file to generate the build file, and compress and rewrite the local variable names in the process.So local variable names are different from mine.Therefore, <keep-alive> cannot properly cache the Home component.

export default class PersonalCenter extends Vue {
    constructor() {
        super();
        const _this: any = this;
        _this.$options.__proto__.name = 'PersonalCenter';
  }
I need this for now to solve the problem temporarily。
But it's not elegant。
I need the class syntax to create a component that has a normal method of assigning the name attribute to a vue instance

### What is expected?
I need the class syntax to create a component that has a normal method of assigning the name attribute to a vue instance

### What is actually happening?
vue-cli@3.0 component <keep-alive> something the matter

**Comment by sodatea** [comment]
Just use the `name` option in `@Component` decorator:

```ts
@Component({
  name: 'Home'
})
export default class Home extends Vue {
  private created() {
    console.log(this.$options.name);
  }
}
```
