### ISSUE TITLE
Update dependencies: joi, topo, hoek

### ISSUE THREAD

**Issue by Krabi** [vuejs/vue-cli#3959]
### What problem does this feature solve?
# npm install -g @vue/cli
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @hapi/topo. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
/opt/node-v10.15.3-linux-x64/bin/vue -> /opt/node-v10.15.3-linux-x64/lib/node_modules/@vue/cli/bin/vue.js
npm WARN ts-node@8.1.0 requires a peer of typescript@>=2.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@vue/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

  @vue/cli@3.7.0
updated 1 package in 7.919s

### What does the proposed API look like?
-

**Comment by LinusBorg** [comment]
Those are transitive dependencies from other packages that we can't update.

**Comment by jsshapiro** [comment]
Then you need to reach out to the package maintainers and insist they deal with this. Vue cannot be responsible for knowingly installing insecure modules.

**Comment by sodatea** [comment]
There're only 2 occurrences of `joi` in the dependency chain:
1. `@vue/cli-shared-utils`, updated and will be included in the next release https://github.com/vuejs/vue-cli/commit/f99645cfcd47269eeb1fff4284d0c2a0996ec07d
2. `workbox-build`, already updated in v4.3.1 https://github.com/GoogleChrome/workbox/pull/2047 and will be automatically included if you are using @vue/cli v4.0.0-alpha.0. v3 won't get this update, though.

**Comment by jsshapiro** [comment]
If v4 is still in alpha, v3 workbox-build needs to get the update. It isn’t
even a code change - just a package relocation. There’s really excuse for
leaving downstream users exposed in this fashion.

**Comment by sodatea** [comment]
There's no actual security vulnerability in this case.

**Comment by jsshapiro** [comment]
The package at the current location is publicly identified as unmaintained.
Given that it is unmaintained, how can you be sure? I'd bet a substantial
sum of money that there *is* a security vulnerability. Statistically, there
is one for every seven to ten lines of code in the joi code base. That's
actually the point.

Right now, existing Vue users are being cut off from the update patches
when they become available. Deciding not to patch is a pretty irresponsible
and arrogant position to take, and given your response I'm considering
whether to file a CVE on Vue. Even if Vue4 comes along soon, many existing
deployments will remain on Vue3 for a long time to come. Those users and
customers shouldn't have to be vulnerable this way.

Especially when all it takes is a patch release with a dependency path
change.

Jonathan

**Comment by sodatea** [comment]
It's over-exaggerating and irresponsible sensationalism.

I will explain it in detail later but it takes some time (I'm a non-native English speaker).
For now, if you insist, please file an issue in the workbox repository and tell them to backport this commit to their v3 branch and cut a new release.

**Comment by sodatea** [comment]
And, it's Vue CLI 4, not Vue 4. Users who cares security issues **should** upgrade to v4 once it's stable. There are breaking changes but I wrote in the roadmap, they **are necessary updates**.

> There's no actual security vulnerability in this case.

When I say there's no actual security vulnerability, I mean it. Because `joi` in `workbox` is only used for validating option schemas. By option schema I mean the user-specified webpack plugin options. It's not like the user input sending to web servers. It's under your (the developer's) control. There is not likely to have any vulnerabilities even if it's of an old version. There's a better chance that you've already upgraded to v4 before a real security breach happens. I'd rather have my time and energy spent on v4 release than bikeshedding anywhere.

Of course a patch update is still welcome. So now I have proposed in the comment https://github.com/GoogleChrome/workbox/pull/2047#issuecomment-491735687
But it's still a workbox issue, not Vue CLI's. You are being unreasonable to blame it on us for not caring Vue users.

**Comment by LinusBorg** [comment]
> Especially when all it takes is a patch release with a dependency path change.

A patch release can only upgrade our own depedency on joi in `@vue/cli-shared-utils`

For Workbox, we would have to upgrade workbox to a new major (unless they backport their dependency update to workbox v3 as proposed by @sodatea) , which means breaking changes for existing projects. 

So this is not a patch update fo Vue CLI.

Furthermore, people can update workbox themselves and deal with breaking changes that are introducted by workbox v4. When using yarn, the could use the `resolutions` field to overwrite the dependency in `@vue/cli-pugin-pwa` if they wanted to.

If there was an concrete security risk (i.e. a reported vulnerability) with these dependencies, that would be another story, and we would have to take necessary steps, of course. 

But these are just no longer maintained, and only used on code the developer has under control.

**Comment by Ne4to777** [comment]
Same problem. Installation freezes after these warnings. Nodejs version 6. On another PC with version 10 everything is fine.

**Comment by sodatea** [comment]
@Ne4to777 https://github.com/nodejs/Release#end-of-life-releases Node.js v6 has already reached end-of-life and I don't think we've ever claimed official support for it (https://github.com/vuejs/vue-cli/issues/1316#issuecomment-390001834). Please consider upgrading your node version.

**Comment by Ne4to777** [comment]
sodatea, Problem is solved. Package-lock.json was missed. It is not version issue.

**Comment by marsanaemi** [comment]
i still dont understand if this warning is a problem and if it is how can i fix that

**Comment by Krabi** [comment]
Strange. If dependencies can't be updated and for now 3 of them are critical, why tu use vulnerable dependencies as direct/first level dependencies?

**Comment by sesam** [comment]
If anyone has the time and cares, how about adding a "resolutions" property in packages.json and setting a minimal version to skip over the the sub-dependency there? I've used it to avoid a conflict with a specific breaking patch version in the past, i.e.
```
"resolutions": {
  "sub-dependendency-package-name": ">=wanted <broken patch version"
}
```

and then of course you add a issue/ticket on your app to remove this hack once the subdependency is fixed.

In this case for vue-cli I guess you can try with just a ">=version" resolution to force-upgrade the subdependency, or someone please point out why this won't work :)
