### ISSUE TITLE
How can i cancel compile when modify a static style in public folder?

### ISSUE THREAD

**Issue by burkgames** [vuejs/vue-cli#3964]
### Version
3.7.0

### Reproduction link
[https://github.com/burkgames/vue-cli-test](https://github.com/burkgames/vue-cli-test)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Node: 10.13.0 - D:\Software\Node\node.EXE
    Yarn: 1.12.3 - D:\Software\Yarn\bin\yarn.CMD
    npm: 6.4.1 - D:\Software\Node\npm.CMD
  Browsers:
    Edge: 41.16299.967.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1  npm run serve
2  modify "public/assets/css/style.css"
3  the page will be recompiled...

### What is expected?
the page don't compile...

### What is actually happening?
the page compiled....

---
because i have many multi-pages in project,  it must cost too many time to compile when i modify static resource.....

**Comment by LinusBorg** [comment]
Well, you obviously use these styles as dependencies in webpack, so the changes won't show up in the browser if the page doesn'r recompile.

I don't think you want that?

**Comment by burkgames** [comment]
> Well, you obviously use these styles as dependencies in webpack, so the changes won't show up in the browser if the page doesn't recompile.
> 
> I don't think you want that?

thank you very much~

emmm....
I link the styles in index.html，it is a static resource....i don't want recompile when i change it.......

**Comment by sodatea** [comment]
It's recompiled because it's depended on by the `copy-webpack-plugin`.
Could be fixed by disabling the `copy` plugin during the `serve` command.

While it could be an improvement, I don't think it worth the extra maintenance burden.
So please work it around in your own configuration.
