### ISSUE TITLE
Deployment on Heroku

### ISSUE THREAD

**Issue by pjotrsavitski** [vuejs/vue-cli#3967]
### What problem does this feature solve?
Documentation about deployment on Heroku

### What does the proposed API look like?
This script should work, though it does require heroku cli utility to be present, account being logged in and an app already existing.

This was used as a source of information on how to deploy static web: https://gist.github.com/wh1tney/2ad13aa5fbdd83f6a489

```
#!/usr/bin/env sh

# abort on errors
set -e

# build
npm run build

# navigate into the build output directory
cd dist

# Create  Heroku specific files for deployment
# Could also use Procfile to clearly define what should be used
echo '{}' > composer.json
echo '<?php include_once("home.html"); ?>' > index.php

git init
git add -A
git commit -m 'Deploy'

heroku git:remote --app {APP-NAME}

git push -f heroku master

cd -
```

**Comment by zigomir** [comment]
Dunno why you included php related stuff here...anyhow, I proposed Heroku docs some time ago and it's still hanging in https://github.com/vuejs/vue-cli/pull/3777

**Comment by pjotrsavitski** [comment]
The PHP is there to serve the main page content, mainly because there were
a couple of resources that pointed out this approach to be working. Judging
by the name of the service used it boils down to plain apache + PHP setup.
It almost does perform the job of just serving static files. If there is a
better approach, then this issue should be closed.

It might be that Heroku as such is not a suitable match for hosting just
some static files and there certainly are alternatives for just that
purpose.

**Comment by pjotrsavitski** [comment]
I have looked at all of the proposed solutions (linked within the pull request description) and all of them look like they are using node.js to serve the static file in one way or the other. This gets the job done, yet Node is not really meant for serving static files as such. In this regard Apache httpd or hginx are clearly on the winning side with superior reliability and speed. Having PHP added into the mix does not seem like a huge downside. This `include_once()` is there to get the file served without the need of navigating to `index.html` directly. That step would not be needed if the server instance would have been preconfigured to serve the `index.html `along with `index.php` as the directory index file (that is the default behaviour for apache, if I do remember it correctly).

This guide would also be a lot like the one for GitHub pages, though requires a bit more steps and effort.

**Comment by zigomir** [comment]
I don’t understand - my PR doesn’t require (other listed do, that’s why I don’t prefer them) you to run and configure node server, nor php.

**Comment by pjotrsavitski** [comment]
To be honest, i did not check your solution in details (probably missing some of the basic knowledge for that matter), but it looked like a configuration for something (not sure what that something is). if it is just a standard service meant for serving static content, the all is well and sunny. If that is a configuration for some node.js based solution, then it still is alright as it is shorter, simpler and easier to get up and running. In my case, the solution was needed fast and having apache or any similar alternative seemed like a win-win situation. Do excuse my ignorance as I did not really invest much into understanding what was that configuration for. Please do share the link to docs page if that is not a huge effort. Thank you for your responses.

**Comment by sodatea** [comment]
Closing as the corresponding PR has been merged.
See documentation at https://cli.vuejs.org/guide/deployment.html#heroku
