### ISSUE TITLE
run vue create got network error

### ISSUE THREAD

**Issue by tolerious** [vuejs/vue-cli#3968]
### Version
3.7.0

### Environment info
```
  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 66.0.5
    Safari: 12.0.3
  npmGlobalPackages:
    @vue/cli: 3.7.0


```

### Steps to reproduce
vue create test-hello

### What is expected?
create test-hello project successfully.

### What is actually happening?
Vue CLI v3.7.0
✨  Creating project in /Users/tolerious/test-hello.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

yarn install v1.10.1
info No lockfile found.
info There appears to be trouble with your network connection. Retrying...
[1/4] 🔍  Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info If you think this is a bug, please open a bug report with the information provided in "/Users/tolerious/test-hello/yarn-error.log".
error An unexpected error occurred: "https://registry.npm.taobao.org/@vue%2fcli-plugin-babel: tunneling socket could not be established, cause=connect EHOSTUNREACH 0.0.4.63:80 - Local (192.168.1.102:50753)".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 ERROR  command failed: yarn --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist
 ✘ dervish@toleriousdeMacBook-Pro-2  ~ 

**Comment by LinusBorg** [comment]
This seems to be a (liekly temporary) problem with the taobao npm registry. Does the problem still persist?

You can change the registry that vue-cli uses either in the command with `--registry` or globally in the `~/.vuerc` file
