### ISSUE TITLE
template will not clean without --offline mode

### ISSUE THREAD

**Issue by ausir0726** [vuejs/vue-cli#397]
I am writing template for my team.
but when I modify asset a.css to b.css 

when my team member vue init my template for new project
they will get a.css and b.css both.

I guess that vue init without --offline will use git clone repo but no delete outdate version.
so , that will be get old version file and new version file both .

I manually delete .vue-templates will fixed.

but If we don't watch template repo will not know template need delete .
and when use vue init template .. it show [ downloading template ... ] 
unfortunately we got a mixed template . ( cache mixed online repo )
maybe I think it need force delete old version template without --offline  , or have a prompt ?

thanks.

**Comment by posva** [comment]
That's by design, it allows you to update an existing project without deleting your project files. If you need to clean the dir and start from scratch, the best option for you is to delete the existing directory
