### ISSUE TITLE
vue-cli3.7.0 项目vue.config.js不起作用

### ISSUE THREAD

**Issue by Pancho2wang** [vuejs/vue-cli#3974]
### Version
3.7.0

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
  Binaries:
    Node: 8.15.0 - D:\ProgramEnv\NodeJs\node.EXE
    Yarn: 1.10.1 - C:\Users\lenovo\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - D:\ProgramEnv\NodeJs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
vue create demo
在根目录下新建vue.config.js
module.exports = {
  devServer: {
    port: 9000,
  },
}
yarn serve

### What is expected?
以端口9000启动

### What is actually happening?
还是以默认端口8080启动

![图片](https://user-images.githubusercontent.com/6365417/57507904-a5478e80-7332-11e9-93f0-a87625cc217f.png)

**Comment by erwer8363** [comment]
我也遇到了这个问题,楼主怎么解决的?
