### ISSUE TITLE
config `pages` do not support to specify template loader

### ISSUE THREAD

**Issue by funkyLover** [vuejs/vue-cli#3976]
### Version
3.5.0

### Environment info
```
  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: Not Found
    Safari: 12.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3 
    @vue/babel-preset-app:  3.5.3 
    @vue/babel-preset-jsx:  1.0.0-beta.3 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3 
    @vue/babel-sugar-inject-h:  1.0.0-beta.3 
    @vue/babel-sugar-v-model:  1.0.0-beta.3 
    @vue/babel-sugar-v-on:  1.0.0-beta.3 
    @vue/cli-overlay:  3.5.1 
    @vue/cli-plugin-babel: ^3.5.0 => 3.5.3 
    @vue/cli-plugin-e2e-nightwatch: ^3.5.0 => 3.5.1 
    @vue/cli-plugin-eslint: ^3.5.0 => 3.5.1 
    @vue/cli-plugin-unit-jest: ^3.5.3 => 3.5.3 
    @vue/cli-service: ^3.5.0 => 3.5.3 
    @vue/cli-shared-utils:  3.5.1 
    @vue/component-compiler-utils:  2.6.0 
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.2 
    jest-serializer-vue:  2.0.2 
    vue: ^2.6.6 => 2.6.10 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.3 
    vue-jest:  3.0.4 
    vue-loader:  15.7.0 
    vue-router: ^3.0.1 => 3.0.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 3.5.1
```

### Steps to reproduce
- config with `pages` option

```js
pages: {
    index: {
        entry: 'src/pages/home/index.js',
        template: 'public/index.html',
        filename: 'index.shtml',
        chunks: ['chunk-vendors', 'chunk-common', 'index'],
        minify: false
    },
    about: {
        entry: 'src/pages/about/index.js',
        template: `!!${path.resolve(__dirname, './lib/loader/html.js')}!${'about.shtml'}`,
        filename: 'about.shtml',
        chunks: ['chunk-vendors', 'chunk-common', 'about'],
        minify: false
    }
}
```

- run `vue inspect > ./webpack.config.js`
- check webpack.config.js

### What is expected?
should get config like below

```js
    /* config.plugin('html-about') */
    new HtmlWebpackPlugin(
      {
        templateParameters: function () { /* omitted long function */ },
        chunks: [
          'chunk-vendors',
          'chunk-common',
          'about'
        ],
        template: '!!/path/to/loader/html.js!/path/to/about.html',
        filename: 'about.shtml',
        minify: false
      }
    ),
```

### What is actually happening?
```js
new HtmlWebpackPlugin(
      {
        templateParameters: function () { /* omitted long function */ },
        chunks: [
          'chunk-vendors',
          'chunk-common',
          'about'
        ],
        template: '/path/to/node_modules/@vue/cli-service/lib/config/index-default.html',
        filename: 'about.shtml',
        minify: false
      }
    )
```

**Comment by funkyLover** [comment]
BTW, I want to create a minimal reproduction, but the installation is stuck with the process to `extract @webassemblyjs/floating-point-hex-parser@1.7.11`

![屏幕快照 2019-05-11 00 47 47](https://user-images.githubusercontent.com/5418228/57543444-000ad580-7387-11e9-8789-40edadaad2a8.png)

however, the message provided above is enough to reproduce the bug

following is more debugger information

![屏幕快照 2019-05-10 23 49 52](https://user-images.githubusercontent.com/5418228/57543681-a3f48100-7387-11e9-862b-b105aeec4d90.png)

![屏幕快照 2019-05-10 23 50 19](https://user-images.githubusercontent.com/5418228/57543740-ca1a2100-7387-11e9-8ed2-f121bf804c76.png)

I think is totally a bug in `vue-cli`, not `html-webpack-plugin`(https://github.com/vuejs/vue-cli/issues/3481)

it mentioned in the [document](https://cli.vuejs.org/config/#pages)

> An object that specifies its entry, template, filename, title and chunks (all optional except entry). Any other properties added beside those will also be passed directly to html-webpack-plugin, allowing user to customize said plugin;

but actually, `vue-cli-service` will check and change the config value with no warning throw out.

**Comment by funkyLover** [comment]
I think it will be better to pass template to html-webpack-plugin directly, if getting an error just throw it out, and developers will check their config and make it right.

**Comment by funkyLover** [comment]
find a way to avoid this situation.

```js
const pages = {
    app: {
        entry: 'src/app.js',
        template: 'public/index.shtml'
    },
    about: {
        entry: 'src/about.js',
        template: 'public/about.shtml'
    }
};

module.exports = {
    pages: pages,
    chainWebpack: config => {
        Object.keys(pages).forEach(key => {
               config.plugin(`html-${key}`).tap(args => {
                    if (!args || args.length === 0) return args;
                    args[0].template = `!!/path/to/loader!${args[0].template}`;
                    return args;
                });
        });
    }
}
```

**Comment by sodatea** [comment]
Just thought about this and I think it would be a breaking change (removing the fallback logic). May fix it in v4.

**Comment by lisiyizu** [comment]
> find a way to avoid this situation.
> 
> ```js
> const pages = {
>     app: {
>         entry: 'src/app.js',
>         template: 'public/index.shtml'
>     },
>     about: {
>         entry: 'src/about.js',
>         template: 'public/about.shtml'
>     }
> };
> 
> module.exports = {
>     pages: pages,
>     chainWebpack: config => {
>         Object.keys(pages).forEach(key => {
>                config.plugin(`html-${key}`).tap(args => {
>                     if (!args || args.length === 0) return args;
>                     args[0].template = `!!/path/to/loader!${args[0].template}`;
>                     return args;
>                 });
>         });
>     }
> }
> ```

感谢，我也遇到了这个问题，🙏
