### ISSUE TITLE
./del

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [vuejs/vue-cli#3977]
Just ./del

**Comment by LinusBorg** [comment]
1. What's "this error"? The bug issue that you linked to is still open.
2. "As you can see" - All I see is that you show me a screenshot of `acorn-dynamic-import`. How does this relate to the still-open issue that you linked to ?

It would be very helpful if you could describe the situation in more than one sentence so we don't have to read a whole wall of text from that linked issue to find out what you are referring to.

**Comment by afwn90cj93201nixr2e1re** [comment]
Issue that described at 'wall' was fixed at latest webpack build, so, maybe we should update vue-cli-service webpack dependencies too?
```
"requires": {
        "webpack": ">=4 < 4.29",
      },
```
as you can see now it's locked at last 'stable' build.
But at 4.30.0 we doesn't have any bug's(depend's on acorn-dynamic-import bugged version in 3.x.x branches) with dynamic import's, so we should update webpack version requirement's.

![image](https://user-images.githubusercontent.com/9306996/57561038-a1e7ed80-739a-11e9-950e-cf2c143fca35.png)
