### ISSUE TITLE
Adding `libraryTarget` and `library` output options to one of the pages

### ISSUE THREAD

**Issue by MansoorBashaBellary** [vuejs/vue-cli#3981]
### Version
3.7.0

### Reproduction link
[https://github.com/vuejs/vue-cli/issues/3980](https://github.com/vuejs/vue-cli/issues/3980)

### Environment info
```
pages
```

### Steps to reproduce
For example i have pages in my vue.config.js as:

```
pages: {
  app: {
    entry: 'src/app/index.js'
  },
  main: {
    entry: 'src/main/index.js'
  }
}
```

I have 2 pages(app and main). For page app i have to have my output options differently which shouldn't apply to main. For example output options should be:

```
output: {
  filename: '[name].js',
  library: 'ABC',
  libraryTarget: 'umd'
}
```

How can i achieve that in Vue CLI ?

### What is expected?
There should be an option to provide different output options to different pages

### What is actually happening?
output options are generic to all pages

**Comment by LinusBorg** [comment]
Pages mode is for building multi-page apps, no for building a library.

Mixing the two options would create a lot of challanges and complexity internally for use, while you can solve this by simply running the ``build commmand two times with different options.

So I would argue this can be solved in userland elegantly enough to not add anything to vue-cli.

**Comment by MansoorBashaBellary** [comment]
Thanks @LinusBorg for your quick reply. One quick question on the above comment. How do i run build command two times. Can i have 2 `vue.config.js` files for different options. Pasting some code sample would be great.

**Comment by LinusBorg** [comment]
>  How do i run build command two times.

Well, create two scripts in package.json, one building the app, one building the library. then run both either manually or from a 3rd script

> Can i have 2 vue.config.js files for different options. 

You can use environment variables if you need your config to change depending on certain external factors.

For the question you initially asked: when building as a library (`--target lib`), the pages option is simply skipped so there's little to adjust.

But maybe the babel config should be adjusted to skip polyfills for the lib, which could be done with an environment variable.

We can egt into the details on forum.vuejs.org - the issue tracker is for bugs.

**Comment by MansoorBashaBellary** [comment]
Thanks @LinusBorg. I have created a 3rd script `build:components` like:

```
"build:pages": "NODE_ENV=production vue-cli-service build",
"build:umd": "vue-cli-service build --target lib --name abc src/index.js",
"build:components": "yarn build:umd && yarn build:pages",
```

When run `yarn build:components`, both are running fine in terminal, but my `dist` folder has got files which ran at last. As i ran `build:pages` at last. My `dist` folder has got only files related to `build:pages`. `build:umd` files are not present.

How could i solve this issue. So, that i can have both script files in `dist`. ?

And one more issue is: on passing `NODE_ENV=production` to `build:umd` like:

```
"build:umd": "NODE_ENV=production vue-cli-service build --target lib --name abc src/index.js"
```

I am getting the error:

```
This dependency was not found:

* ~entry in ./node_modules/@vue/cli-service/lib/commands/build/entry-lib.js

To install it, you can run: npm install --save ~entry
```

Could you please provide your inputs on these issues

**Comment by LinusBorg** [comment]
I already told you to continue on the forums, not on the bug tracker.
