### ISSUE TITLE
Vue Cli 3 Build not minifying css

### ISSUE THREAD

**Issue by Alik2015** [vuejs/vue-cli#3982]
I have been looking into Vue and have got it working with what I need.

* Typescript
* SSR

My sample project can be found at https://github.com/Alik2015/VueDemo. To run

      npm install
      npm run ssr:serve //development
      npm run ssr:build //production build
      npm run ssr:start

View source of page and see css has not been minified.

When building this project I observe the following:

1) My css is in the head section of the page and not extracted (read somewhere this is default behaviour but not 100% sure)

2) My comments still  still exists in the css for example /*comment\*/

3) My html losing all spacing

I did try  and set css:{extract:true} and various other options in vue.config.js but them just left it blank as none worked.

Appreciate if someone could point me in the right direction.

I am not a front-end developer so might have missed something simple.

**Comment by LinusBorg** [comment]
I'll reopen since OP followed the rules content-wise even though he didn't use the issue helper.

**Comment by LinusBorg** [comment]
Sidenote: since you are using the SSR Plugin, you will likely have more success opening an issue there.

**Comment by Alik2015** [comment]
@LinusBorg  I will do that but it seems even if I remove plugin the issue still exists.

**Comment by sodatea** [comment]
It's a plugin issue: https://github.com/Akryum/vue-cli-plugin-ssr/issues/37

**Comment by Alik2015** [comment]
Although you mentioned its plugin issue the spacing in the html index file are still removed when building regardless of plugin or not.

**Comment by sodatea** [comment]
HTML spacing are dealt with by https://github.com/jantimon/html-webpack-plugin#options

**Comment by Alik2015** [comment]
Checked the above and from my knowledge you attempt something like this in vue.config.js but does not work to resolve spacing.

```
chainWebpack: (config) => {
    config.plugin('html').tap((args) => {
      args[0].template = 'public/index.html';
      args[0].collapseWhitespace = false;
      args[0].removeComments = true;
      return args;
    });
  }
```

**Comment by sodatea** [comment]
```diff
- args[0].collapseWhitespace = false;
- args[0].removeComments = true;
+ args[0].minify.collapseWhitespace = false;
+ args[0].minify.removeComments = true;
```
