### ISSUE TITLE
yarn serve卡住不动，无任何错误提示

### ISSUE THREAD

**Issue by elainema** [vuejs/vue-cli#3985]
### Version
3.7.0

### Reproduction link
[https://github.com/elainema/reproduction-vue-serve](https://github.com/elainema/reproduction-vue-serve)

### Environment info
```
node  :v10.15.3
npm: 6.4.1 
yarn: 1.15.2
```

### Steps to reproduce
git clone https://github.com/elainema/reproduction-vue-serve.git
yarn install
yarn serve

### What is expected?
正常构建

### What is actually happening?
构建至68%左右卡住不动，无任何提示

---
这个代码有删除几个组件，新增几个组件，并改动部分代码，未改动前运行正常

**Comment by sodatea** [comment]
我这里有报错啊，你删掉 yarn.lock 和 package-lock.json、node_modules 然后重新装一遍依赖试试。
报的错是
```
* @/components/Alert_pop.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Tool/Settings.vue?vue&type=script&lang=js&
* @/components/DailyWarningModal.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Publisher/pages/P_Daily_Warning.vue?vue&type=script&lang=js&
* @/components/Editable_Text_Offer.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Employees/Detail/PersonalInfo.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Offer/components/offer-group-filter-form/offer-group-filter-form.vue?vue&type=script&lang=js& and 6 others
```

`@/components/Alert_pop.vue`, `@/components/DailyWarningModal.vue`, `@/components/Editable_Text_Offer.vue` 这几个文件不存在

**Comment by elainema** [comment]
> node_modules



> 我这里有报错啊，你删掉 yarn.lock 和 package-lock.json、node_modules 然后重新装一遍依赖试试。
> 报的错是
> 
> ```
> * @/components/Alert_pop.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Tool/Settings.vue?vue&type=script&lang=js&
> * @/components/DailyWarningModal.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Publisher/pages/P_Daily_Warning.vue?vue&type=script&lang=js&
> * @/components/Editable_Text_Offer.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Employees/Detail/PersonalInfo.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Offer/components/offer-group-filter-form/offer-group-filter-form.vue?vue&type=script&lang=js& and 6 others
> ```
> 
> `@/components/Alert_pop.vue`, `@/components/DailyWarningModal.vue`, `@/components/Editable_Text_Offer.vue` 这几个文件不存在


> 我这里有报错啊，你删掉 yarn.lock 和 package-lock.json、node_modules 然后重新装一遍依赖试试。
> 报的错是
> 
> ```
> * @/components/Alert_pop.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Tool/Settings.vue?vue&type=script&lang=js&
> * @/components/DailyWarningModal.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Publisher/pages/P_Daily_Warning.vue?vue&type=script&lang=js&
> * @/components/Editable_Text_Offer.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Employees/Detail/PersonalInfo.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Offer/components/offer-group-filter-form/offer-group-filter-form.vue?vue&type=script&lang=js& and 6 others
> ```
> 
> `@/components/Alert_pop.vue`, `@/components/DailyWarningModal.vue`, `@/components/Editable_Text_Offer.vue` 这几个文件不存在


之前有尝试过删除node_modules，然后重装依赖，但是没有删除 yarn.lock 和 package-lock.json，没有解决；
按照提供方法删除了 yarn.lock 和 package-lock.json、node_modules ， 重装依赖，参照你的报错提示改动对应的错误，执行yarn serve还是会卡住，构建大约在68%左右卡住，无提示。

**Comment by sodatea** [comment]
`yarn build` 会不会卡住？操作系统是？`vue info` 的完整输出呢？

**Comment by elainema** [comment]
> `yarn build` 会不会卡住？操作系统是？`vue info` 的完整输出呢？

 vue --version
3.7.0


错误：https://github.com/elainema/reproduction-vue-serve/blob/master/doc/error2.png

操作系统：win7     https://github.com/elainema/reproduction-vue-serve/blob/master/doc/%E8%AE%A1%E7%AE%97%E6%9C%BA%E4%BF%A1%E6%81%AF.png

vue info：https://github.com/elainema/reproduction-vue-serve/blob/master/doc/vueinfo.png

yarn build：有报错， error  in ./src/views/Tool/Offer_Audit_Log.vue?vue&type=template&id=4b51d1b4&
Syntax Error: SyntaxError: Unexpected token (1:2322)，修改错误后yarn build正常， yarn serve 构建OK

yarn serve是这个分支出的异常(改动部分文件后)，之前版本找不到文件，路径错误等都会提示，尴尬。。。

**Comment by sodatea** [comment]
目前有两个怀疑方向：

1. 操作系统/文件系统的问题，可能是 watch 相关的功能有问题
2. friendly-errors-webpack-plugin 可能没有正确输出错误信息，导致控制台卡住

也有可能两个问题同时存在……

不过目前没办法复现了，等有新的类似 bug 反馈时我再详查一下。

**Comment by elainema** [comment]
> 目前有两个怀疑方向：
> 
> 1. 操作系统/文件系统的问题，可能是 watch 相关的功能有问题
> 2. friendly-errors-webpack-plugin 可能没有正确输出错误信息，导致控制台卡住
> 
> 也有可能两个问题同时存在……
> 
> 不过目前没办法复现了，等有新的类似 bug 反馈时我再详查一下。

OK~~问题先暂时解决了，非常感谢及时回复~
