### ISSUE TITLE
@vue/cli-plugin-e2e-cypress headless not exiting on success

### ISSUE THREAD

**Issue by MatthiasGrandl** [vuejs/vue-cli#3987]
### Version
3.7.0

### Environment info
```
  System:
    OS: Linux 5.0 Solus 4.0
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
  Binaries:
    Node: 10.15.3 - /usr/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 66.0.5
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3 
    @vue/babel-preset-app: ^3.6.0 => 3.6.0 
    @vue/babel-preset-jsx:  1.0.0-beta.3 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3 
    @vue/babel-sugar-inject-h:  1.0.0-beta.3 
    @vue/babel-sugar-v-model:  1.0.0-beta.3 
    @vue/babel-sugar-v-on:  1.0.0-beta.3 
    @vue/cli-overlay:  3.6.0 
    @vue/cli-plugin-babel: ^3.6.0 => 3.6.0 
    @vue/cli-plugin-e2e-cypress: ^3.7.0 => 3.7.0 
    @vue/cli-plugin-eslint: ^3.6.0 => 3.6.0 
    @vue/cli-service: ^3.6.0 => 3.6.0 
    @vue/cli-shared-utils:  3.6.0 
    @vue/component-compiler-utils:  2.6.0 
    @vue/eslint-config-prettier: ^3.0.0-beta.6 => 3.0.0-rc.3 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/test-utils: ^1.0.0-beta.10 => 1.0.0-beta.19 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue:  4.7.1 
    vue: ^2.5.13 => 2.5.16 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-router: ^3.0.1 => 3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.13 => 2.5.16 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.0.1 
    vuex-router-sync: ^5.0.0 => 5.0.0 
```

### Steps to reproduce
vue-cli-service test:e2e --headless

### What is expected?
After running all specs successfully it should exit. It exits properly if one spec fails.

### What is actually happening?
The process is stuck with "All specs passed!" and I have to "ctrl c" to exit it manually.

**Comment by LinusBorg** [comment]
Does that happen with a fresh out-of-the box project? Which settings did you pick? Can you share a repository so we can ensure we are talking about the same exact thing?

**Comment by MatthiasGrandl** [comment]
@LinusBorg ok seems like something is wrong in my project, since I can't reproduce it with a fresh setup... Guess I'll have to dig deeper. Sadly I can't share the repo since it's not yet open sourced.

**Comment by MatthiasGrandl** [comment]
Quick update. Something seems to be wrong with one of my spec files. Even though the tests run as expected it doesn't exit. If I specify another spec file with the `--spec` parameter it exits as expected. Now I'll investigate what exactly the culprit is, but yeah probably has nothing to do with vue-cli-service

**Comment by LinusBorg** [comment]
Thanks for the feedback!
