### ISSUE TITLE
HTML not reloading automatically

### ISSUE THREAD

**Issue by PrimozRome** [vuejs/vue-cli#40]
I installed the full webpack scaffolding package. It's running fine, but if I change the main index.html file it's not automatically reloaded. Do I need to add something to Webpack config in order to enable this?

**Comment by yyx990803** [comment]
Somehow the hot middleware is not recognizing `index.html` changing because the js bundle has the same hash. I've updated the scaffold template and it should now reload the page when you edit `index.html`.

**Comment by PrimozRome** [comment]
Thanks a lot. Can you help me on how can I update this scaffolding template to the latest version on my existing project?

**Comment by yyx990803** [comment]
You can init a new project and copy over the src files.

**Comment by PrimozRome** [comment]
src files? I don't want to do that as my project already has my own src files.

What was exactly the change that you did to the scaffolding template to make HTML reload? I thought there was some change in webbpack configuration file or something similar?
