### ISSUE TITLE
npm run build not work

### ISSUE THREAD

**Issue by edolfuchs** [vuejs/vue-cli#400]
The npm run build does not work. No errors appear, but when you access the project (http://localhost/project) the screen is blank.

Example:

npm command:

![npm](https://cloud.githubusercontent.com/assets/12100777/23973604/9a23935c-09b5-11e7-80b3-147335dd9f38.png)

http:://localhost/web (no html)

![html](https://cloud.githubusercontent.com/assets/12100777/23973635/b726bfd8-09b5-11e7-8c35-638587ba250f.png)

http:://localhost/web (no console error)

![console](https://cloud.githubusercontent.com/assets/12100777/23973640/c0c8704a-09b5-11e7-9df0-e5b3945a5e28.png)

Can anybody help?

PS.: npm run dev everything works

**Comment by edolfuchs** [comment]
package.json

**{
  "name": "web",
  "version": "1.0.0",
  "description": "web test production",
  "author": "Edson Fuchs",
  "private": true,
  "scripts": {
    "dev": "node build/dev-server.js",
    "build": "node build/build.js"
  },
  "dependencies": {
    "vue": "^2.2.2",
    "vue-router": "^2.2.0"
  },
  "devDependencies": {
    "autoprefixer": "^6.7.2",
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.2.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^1.1.3",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.1",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.10.0",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "function-bind": "^1.1.0",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "webpack-bundle-analyzer": "^2.2.1",
    "semver": "^5.3.0",
    "opn": "^4.0.2",
    "optimize-css-assets-webpack-plugin": "^1.3.0",
    "ora": "^1.1.0",
    "rimraf": "^2.6.0",
    "url-loader": "^0.5.7",
    "vue-loader": "^11.1.4",
    "vue-style-loader": "^2.0.0",
    "vue-template-compiler": "^2.2.4",
    "webpack": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.16.1",
    "webpack-merge": "^2.6.1"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}**

**Comment by znck** [comment]
Provide minimal reproduction repository to demonstrate your issue.

**Comment by posva** [comment]
Hello!
Please, open the issue on the relevant template repo (I think you're using the [webpack one](https://github.com/vuejs-templates/webpack)) and provide some steps to reproduce the problem.
Thanks!
