### ISSUE TITLE
How to compile one of the multi pages ?

### ISSUE THREAD

**Issue by burkgames** [vuejs/vue-cli#4001]
### Version
3.7.0

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Node: 10.13.0 - D:\Software\Node\node.EXE
    Yarn: 1.12.3 - D:\Software\Yarn\bin\yarn.CMD
    npm: 6.4.1 - D:\Software\Node\npm.CMD
  Browsers:
    Edge: 41.16299.967.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1  Configuring many multi pages in vue.config.js
2  I want to compile one of them...
3  I use "npm run serve src/pages/index.js", the page is blank...

### What is expected?
'npm run serve entry' does't work 

### What is actually happening?
compile any one of page i want

Thx

**Comment by LinusBorg** [comment]
Use an environment variable to dynamically create the pages option however you like.
