### ISSUE TITLE
sh: 1: vue-cli-service: Permission denied

### ISSUE THREAD

**Issue by janlueders** [vuejs/vue-cli#4004]
### Version
3.7.0

### Reproduction link
[https://github.com/janlueders/vue-cms](https://github.com/janlueders/vue-cms)

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.19 Parrot GNU/Linux 4.6 4.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.2.0 - /usr/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 66.0.5
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.7.0 
    @vue/babel-preset-jsx:  1.0.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.0.0 
    @vue/cli-overlay:  3.7.0 
    @vue/cli-plugin-babel: ^3.7.0 => 3.7.0 
    @vue/cli-plugin-eslint: ^3.7.0 => 3.7.0 
    @vue/cli-service: ^3.7.0 => 3.7.0 
    @vue/cli-shared-utils:  3.7.0 
    @vue/component-compiler-utils:  2.6.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.2 (4.7.1)
    vue: ^2.6.10 => 2.6.10 
    vue-eslint-parser:  5.0.0 (2.0.3)
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 3.7.0

```

### Steps to reproduce
vue create vue-cms

    $ cd vue-cms
    $ yarn serve

    $cd vue-cms/

    $yarn serve
    yarn run v1.16.0
    $ vue-cli-service serve
    /bin/sh: 1: vue-cli-service: Permission denied
    error Command failed with exit code 126.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### What is expected?
That the application would be compiled and served as runable version on port 8080 on localhost.

### What is actually happening?
after default installation it breaks up with the following Error

    $ vue-cli-service serve
    /bin/sh: 1: vue-cli-service: Permission denied
    verbose 0.17122726 Error: Command failed with exit code 
    126.
    at ProcessTermError.ExtendableBuiltin (/usr/share/yarn/lib
    /cli.js:721:66)
    at ProcessTermError.MessageError (/usr/share/yarn/lib  
    /cli.js:750:123)
    at new ProcessTermError (/usr/share/yarn/lib
    /cli.js:790:113)
    at /usr/share/yarn/lib/cli.js:34066:30
    at Generator.throw (<anonymous>)
    at step (/usr/share/yarn/lib/cli.js:304:30)
    at /usr/share/yarn/lib/cli.js:317:13
    at processTicksAndRejections (internal/process  
    /task_queues.js:89:5)
    error Command failed with exit code 126.
    info Visit https://yarnpkg.com/en/docs/cli/run for         
    documentation about this command.

---
the same error occurs if i try it with npm 

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'serve' ]
    2 info using npm@6.9.0
    3 info using node@v12.2.0
    4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
    5 info lifecycle vue-cms@0.1.0~preserve: vue-cms@0.1.0
    6 info lifecycle vue-cms@0.1.0~serve: vue-cms@0.1.0
    7 verbose lifecycle vue-cms@0.1.0~serve: unsafe-perm in lifecycle true
    8 verbose lifecycle vue-cms@0.1.0~serve: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/storage/web/cleancodestudio/vue-cms/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/home/jl/.local/bin:/snap/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
    9 verbose lifecycle vue-cms@0.1.0~serve: CWD: /storage/web/cleancodestudio/vue-cms
    10 silly lifecycle vue-cms@0.1.0~serve: Args: [ '-c', 'vue-cli-service serve' ]
    11 silly lifecycle vue-cms@0.1.0~serve: Returned: code: 126  signal: null
    12 info lifecycle vue-cms@0.1.0~serve: Failed to exec serve script
    13 verbose stack Error: vue-cms@0.1.0 serve: `vue-cli-service serve`
    13 verbose stack Exit status 126
    13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
    13 verbose stack     at EventEmitter.emit (events.js:196:13)
    13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
    13 verbose stack     at ChildProcess.emit (events.js:196:13)
    13 verbose stack     at maybeClose (internal/child_process.js:1011:16)
    13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
    14 verbose pkgid vue-cms@0.1.0
    15 verbose cwd /storage/web/cleancodestudio/vue-cms
    16 verbose Linux 4.19.0-parrot4-28t-amd64
    17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "serve"
    18 verbose node v12.2.0
    19 verbose npm  v6.9.0
    20 error code ELIFECYCLE
    21 error errno 126
    22 error vue-cms@0.1.0 serve: `vue-cli-service serve`
    22 error Exit status 126
    23 error Failed at the vue-cms@0.1.0 serve script.
    23 error This is probably not a problem with npm. There is likely additional logging output above.
    24 verbose exit [ 126, true ]

**Comment by sodatea** [comment]
Are you running any of these commands with `sudo` / `root` privilege?

**Comment by janlueders** [comment]
I can do it both.

Yesterday it was a Debian today it is a ubuntu and same story.

**Comment by Ausqa21** [comment]
@janlueders , I'm having the same issue and the directory is on my pc and not mounted from another device. Can you help out please?

**Comment by BenjaminWinks** [comment]
I'm having this issue too on a gitlab runner but only when copying the `node_modules` over for offline use.

**Comment by HaoXiangL** [comment]
Your can remove `node_modules` and `sudo npm install` to fix this question

**Comment by MohMehrnia** [comment]
I create github actions for build vue projects:
```
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true

```

but failed in npm run build and show errors:
```
Run npm run build --if-present
  npm run build --if-present
  shell: /bin/bash -e {0}

> aiki-helpdesk@0.1.0 build /home/runner/work/Aiki-HelpDesk/Aiki-HelpDesk
> vue-cli-service build

sh: 1: vue-cli-service: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! aiki-helpdesk@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 126
npm ERR! 
```

**Comment by smilevietnam** [comment]
First: 
+) rm -rf node_modules
Second:
+) npm install
