### ISSUE TITLE
stylus-loader unit tests fail

### ISSUE THREAD

**Issue by peteringram0** [vuejs/vue-cli#4005]
### Version
3.7.0

### Environment info
```


  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 11.13.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: Not Found
    Safari: 12.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.7.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.7.0
    @vue/cli-plugin-babel: ^3.7.0 => 3.7.0
    @vue/cli-plugin-e2e-cypress: ^3.7.0 => 3.7.0
    @vue/cli-plugin-typescript: ^3.7.0 => 3.7.0
    @vue/cli-plugin-unit-mocha: ^3.7.0 => 3.7.0
    @vue/cli-service: ^3.7.0 => 3.7.0
    @vue/cli-shared-utils:  3.7.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    typescript: ^3.4.3 => 3.4.5
    vue: ^2.6.10 => 2.6.10
    vue-class-component: ^7.0.2 => 7.1.0
    vue-clickaway:  2.2.2
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-property-decorator: ^8.1.0 => 8.1.1
    vue-router: ^3.0.3 => 3.0.6
    vue-style-loader:  4.1.2
    vue-sweetalert:  0.1.18
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vue-toasted:  1.1.26
    vuex: ^3.0.1 => 3.1.1
    vuex-typescript: ^3.0.2 => 3.0.2
  npmGlobalPackages:
    @vue/cli: 3.7.0
```

### Steps to reproduce
use stylus-loader and give a .vue file lang="stylus" with stylus markup.

### What is expected?
Tests to ignore CSS and pass

### What is actually happening?
tests error

The only change between the following is stylus markup was removed.

#### With Stylus
<img width="1312" alt="Screenshot 2019-05-15 at 22 54 36" src="https://user-images.githubusercontent.com/6588942/57812336-a7f81880-7764-11e9-8a2b-2a6a3daf5154.png">
<img width="578" alt="Screenshot 2019-05-15 at 22 54 52" src="https://user-images.githubusercontent.com/6588942/57812339-ab8b9f80-7764-11e9-8fac-7f4d5726701b.png">

#### Without Stylus
<img width="1312" alt="Screenshot 2019-05-15 at 22 55 11" src="https://user-images.githubusercontent.com/6588942/57812359-b6463480-7764-11e9-83df-89789380104a.png">
<img width="506" alt="Screenshot 2019-05-15 at 22 54 59" src="https://user-images.githubusercontent.com/6588942/57812364-bc3c1580-7764-11e9-967a-6871d15c1285.png">

**Comment by sodatea** [comment]
Can't reproduce. Could you provide a reproduction repository please?

**Comment by peteringram0** [comment]
Please don't close this issue. I'll get around to this soon.

**Comment by peteringram0** [comment]
Please close this issue. For some reason i had --mode production flag against the unit tests.
