### ISSUE TITLE
How to cache const elements in JSX

### ISSUE THREAD

**Issue by TerenceZ** [vuejs/vue-cli#4006]
### Description
I wrote vue in TSX (not with single  vue component file), e.g., a modified [HelloWorld](https://github.com/TerenceZ/vue-cli-plugin-tsx/blob/master/samples/HelloWorld/src/components/HelloWorld.tsx) component. In this file, lots of elements are constant and won't be changed. In React, they can be extracted by babel plugin. But with vue's jsx babel plugin, they won't be extracted. So can I just simplely create some constant vnodes (just like what react's plugin does), and reuse them across different component instances?

**Comment by LinusBorg** [comment]
Please open your issue in the vuejs/jsx repo
