### ISSUE TITLE
SyntaxError: Unexpected token ... when using cypress with webpack-preprocessor

### ISSUE THREAD

**Issue by Bastczuak** [vuejs/vue-cli#4008]
### Version
3.7.0

### Reproduction link
[https://github.com/Bastczuak/vue-cli-issue](https://github.com/Bastczuak/vue-cli-issue)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 66.0.5
    Safari: 12.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.7.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.7.0
    @vue/cli-plugin-babel: ^3.7.0 => 3.7.0
    @vue/cli-plugin-e2e-cypress: ^3.7.0 => 3.7.0
    @vue/cli-plugin-eslint: ^3.7.0 => 3.7.0
    @vue/cli-plugin-unit-jest: ^3.7.0 => 3.7.0
    @vue/cli-service: ^3.7.0 => 3.7.0
    @vue/cli-shared-utils:  3.7.0
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.2 (4.7.1)
    jest-serializer-vue:  2.0.2
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0 (2.0.3)
    vue-hot-reload-api:  2.3.3
    vue-jest:  3.0.4
    vue-loader:  15.7.0
    vue-router: ^3.0.3 => 3.0.6
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: 3.7.0
```

### Steps to reproduce
Install node modules with yarn and try to run the e2e tests with yarn test:e2e and see the error message. 

### What is expected?
The e2e will run with no errors.

### What is actually happening?
Cypress throws an exception when trying to run e2e tests.

---
I'm using https://github.com/cypress-io/cypress-webpack-preprocessor for bundling my tests with webpack. It works when using @vue/cl-service in version 3.5.0.

**Comment by LinusBorg** [comment]
I think Cypress uses an putdated node version internally, and we use Node >8.11 features in Vue CLI, like Object rest spread. That probably breaks it.

**Comment by Bastczuak** [comment]
@LinusBorg Do you want me to open a issue on their repo then?

**Comment by cars10** [comment]
Are there any updates to this? Running cypress worked with 3.5.0 but is broken in the current version of vue-cli.

**Comment by LinusBorg** [comment]
Cypress updated their internal node version from node 8.2.1 to node 8.9.3 in Cypress `3.3.0` ([see CHANGELOG](https://docs.cypress.io/guides/references/changelog.html#3-3-0))

> Upgraded node from `8.2.1` to `8.9.3`. Addressed in #4001

That version was released a day after this issue was opened (on 5/17/2019), so I assume that updateing your Cypress dependency should make it work.

**Comment by LinusBorg** [comment]
I'll close this assuming the new version fixed this problem.

@Bastczuak Please ping me if my assumption turns out to be incorrect.

**Comment by cars10** [comment]
@LinusBorg upgrading cypress to `3.3.0` worked, thanks.

**Comment by Bastczuak** [comment]
@LinusBorg thanks mate! All good now.
