### ISSUE TITLE
[WDS] Hot Module Replacement enabled when clientLogLevel set to 'info'

### ISSUE THREAD

**Issue by matrunchyk** [vuejs/vue-cli#4009]
### Version
3.7.0

### Reproduction link
[https://github.com/matrunchyk/vue-cli-hmr-duplication-issue](https://github.com/matrunchyk/vue-cli-hmr-duplication-issue)

### Environment info
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: Not Found
    Safari: 12.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.7.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.7.0
    @vue/cli-plugin-babel: ^3.7.0 => 3.7.0
    @vue/cli-plugin-eslint: ^3.7.0 => 3.7.0
    @vue/cli-plugin-pwa: ^3.7.0 => 3.7.0
    @vue/cli-service: ^3.7.0 => 3.7.0
    @vue/cli-shared-utils:  3.7.0
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-airbnb: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.2
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router: ^3.0.3 => 3.0.6
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: 3.7.0
```

### Steps to reproduce
1. Clone the repo
2. Run npm i
3. Run npm run serve
4. Open Chrome and Chrome dev tools

### What is expected?
It's expected to see the `"[WDS] Hot Module Replacement enabled."` message only once.

### What is actually happening?
After creating a vue.config.js file and turning clientLogLevel: info, it starts showing `"[WDS] Hot Module Replacement enabled."` twice (probably one message per host). 

---
I'm not sure whether it's a real bug or not, but I suspect that the real bug might be discovered behind the scenes.
If it's OK to show the message twice, my question is why it does not show _the same_ twice when clientLogLevel:info is turned off?

**Comment by LinusBorg** [comment]
This sounds like an issue with webpack-dev-server ...

**Comment by matrunchyk** [comment]
I see, that's what I suspected. In that case I will rather open the issue over there. Thanks for your confirmation @LinusBorg!
