### ISSUE TITLE
Environment variables compiled incorrectly in a production build when used in combination with a compare.

### ISSUE THREAD

**Issue by gilian1993** [vuejs/vue-cli#4015]
### Version
3.7.0

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 10.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Add an environment variable for example `VUE_APP_IS_PUBLIC=true` in `.env.production` (or development)
2. Add somewhere in your code `const isPublic = process.env.VUE_APP_IS_PUBLIC === "true";`
3. Do a production build.

### What is expected?
The compiled output should be something like: `var s = "true" === "true";`

### What is actually happening?
What you actually see is: `var s = !1;` (Which is false)

---
A workaround is to change the variable to something like `const isPublic = process.env.VUE_APP_IS_PUBLIC` and then check it afterward. It will then compile to: `var s = "true";` which is expected.

Could not find any documentation of this so it's probably a bug. This took me a while to find and happened to gave us some unpredicted behavior since we expected the value to be true.

Environment Info is less relevant because we host it in different environments like Azure and IIS.

**Comment by LinusBorg** [comment]
Can't reproduce this locally, please provide a runnable reproduction in a git repo.

**Comment by gilian1993** [comment]
I tried to replicate the problem in a newly created Vue project, however, I also had different results. I forgot to mention the project is made in with the Typescript + Babel template. However, I found some interesting differences in the builds between javascript and typescript. Here's an example:

I added the following method in 'App.vue':

```
isPublic() {
    // Assume that VUE_APP_SECRET is true.
    var test = process.env.VUE_APP_SECRET === "true";
    console.log("SEARCH_THIS");
}
```

The typescript result is:
`var e=!0;console.log("SEARCH_THIS");`

The javascript result is:
`var e = "true" === Object({ NODE_ENV: "production", VUE_APP_SECRET: "true", BASE_URL: "/" }).VUE_APP_SECRET;console.log("SEARCH_THIS");`

So the Typescript result is intended I think, however, the problem is that I face is that I replace the environment variables after a build. Which is possible in the javascript build but not in the typescript result. My suggestion is to keep both behaviours the same, but I don't know if this it's possible due the typescript dependency.

Also, here is a link of the repo: https://github.com/gilian1993/vue-issue-4015

**Comment by sodatea** [comment]
@gilian1993 Could you also provide a JavaScript example? I can't reproduce this locally.

**Comment by gilian1993** [comment]
I'm sorry I think I made a mistake. There is no typescript difference 😅.

However, there is still a significant difference between the following:

- `var test1 = process.env.VUE_APP_IS_PUBLIC === "true";`
    - Compiles to: `var e=!1`
- `var test2 = process.env.VUE_APP_IS_PUBLIC;`
    - Compiles to: `var t="true"`

Because in the second example, someone could replace the original string value after a build since the original value is used. This is not possible in the first example since the original value is replaced.

Here's a repo of the above: https://github.com/gilian1993/vue-issue-4015-2

**Comment by sodatea** [comment]
I'm not sure if I follow, but that's not a bug:

Webpack DefinePlugin only does simple string replacement and the outcome of this step will be `var test1 = "true" === "true"`.
Since the right-hand side expression is a comparison between two string literals, a JavaScript compressor will certainly pre-evaluate it and turn it into `!0`.

**Comment by gilian1993** [comment]
It might not be a bug, but it can be confusing if you replace environment variables after a release. Let's say that my `.env` contains `VUE_APP_TEST=#{CHANGING_REALEASE_VARIABLE}#`. The `#{CHANGING_REALEASE_VARIABLE}#` is a token variable that will be replaced after a build is done. I want to do this post build because my app is used by different environments while using the same build. In this case, I'm checking for `var test1 = process.env.VUE_APP_TEST === "true";`. And when building the output will always be false. The workaround would be:
```
var test1 = process.env.VUE_APP_TEST;
if (test1 === "true") {
....more code
```
Which is in my opinion kinda confusing, because I expected that `process.env.VUE_APP_TEST === "true"` would be replaced by `"#{CHANGING_REALEASE_VARIABLE}#" === "true"` after reading https://cli.vuejs.org/guide/mode-and-env.html#using-env-variables-in-client-side-code. Which tells me that `During build, process.env.VUE_APP_SECRET will be replaced by the corresponding value. In the case of VUE_APP_SECRET=secret, it will be replaced by "secret".` Which is not the case in this scenario.

I'm not saying that this is a bug, but it could be really confusing in this scenario. Maybe add a little note in https://cli.vuejs.org/guide/mode-and-env.html about this.

**Comment by LinusBorg** [comment]
> Which is not the case in this scenario.

It totally is the case. it works exactly as described.

Your issue is that you try to replace a bit of code that the minifier (not the env variable mechanism) replaced with something smaller (to do its job - minifying your code).

You have to do *your* replacement before the code is minified, or configure Terser (the minifier) to skip this placeholder (if that's possible).
