### ISSUE TITLE
Unable to start dev server after deleting some unused components

### ISSUE THREAD

**Issue by pSnehanshu** [vuejs/vue-cli#4019]
### Version
3.7.0

### Reproduction link
[https://github.com/pSnehanshu/vuetify-frontend](https://github.com/pSnehanshu/vuetify-frontend)

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i3-4005U CPU @ 1.70GHz
  Binaries:
    Node: 11.10.0 - ~/.nvm/versions/node/v11.10.0/bin/node
    Yarn: Not Found
    npm: 6.7.0 - ~/.nvm/versions/node/v11.10.0/bin/npm
  Browsers:
    Chrome: 73.0.3683.75
    Firefox: 66.0.5
  npmGlobalPackages:
    @vue/cli: 3.7.0
```

### Steps to reproduce
Get inside the project directory, and then
1. `$ npm install`
2. `$ npm run serve`

### What is expected?
The dev server should have started

### What is actually happening?
 ERROR  Failed to compile with 2 errors                                                                                                                                   9:56:40 PM

This dependency was not found:

* @/components/HelloWorld.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/vuetify-loader/lib/loader.js!./node_modules/cache
-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save @/components/HelloWorld.vue

This relative module was not found:

* ../assets/logo.png in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"6f0cf991-vue-loader-template"}!./node_modules/
vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vuetify-loader/lib/loader.js!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader
/lib??vue-loader-options!./src/views/Home.vue?vue&type=template&id=fae5bece&

---
I have deleted all existing files in Assets folder and Components folder. I don't know who is trying to import those files.

**Comment by LinusBorg** [comment]
likely a caching issue. Delete `node_modules/.cache` and run again.

**Comment by sodatea** [comment]
It is not "unused": https://github.com/pSnehanshu/vuetify-frontend/blob/7c998c275ec8e17ec95fc8b204b38c0495d5239c/src/views/Home.vue#L10

**Comment by pSnehanshu** [comment]
@sodatea Thanks, it helped. This file was automatically created when I installed vue-router.

**Comment by sloughin** [comment]
@sodatea - I have this issue too, I renamed the HelloWorld.vue component to Main.vue and changed every occurrence of "HelloWorld" to "Main".  According to my editor there are now no occurrences of HelloWorld anywhere in my file hierarchy which includes the node_modules.  I have deleted the .cache folder as you suggested and still I get 
`npm run serve

> arc-onix@0.1.0 serve /Users/stephenloughin/dev/arc/onix/arc-onix
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                                            1:03:45 PM

This relative module was not found:

* ./components/HelloWorld.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-load
er/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&`
