### ISSUE TITLE
@vue/cli ui 界面在执行命令行时，会去掉参数的等号

### ISSUE THREAD

**Issue by QingshanLuoyue** [vuejs/vue-cli#4027]
### Version
3.7.0

### Environment info
```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.0.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: 66.0.3
    Safari: 11.0.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.7.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.7.0
    @vue/cli-plugin-babel: ^3.7.0 => 3.7.0
    @vue/cli-plugin-eslint: ^3.7.0 => 3.7.0
    @vue/cli-plugin-pwa: ^3.7.0 => 3.7.0
    @vue/cli-plugin-unit-jest: ^3.7.0 => 3.7.0
    @vue/cli-service: ^3.7.0 => 3.7.0
    @vue/cli-shared-utils:  3.7.0
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1
    @vue/preload-webpack-plugin:  1.1.0
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    eslint-plugin-vue: ^5.0.0 => 5.2.2 (4.7.1)
    jest-serializer-vue:  2.0.2
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  2.0.3 (5.0.0)
    vue-hot-reload-api:  2.3.3
    vue-i18n: ^8.11.2 => 8.11.2
    vue-jest:  3.0.4
    vue-loader:  15.7.0
    vue-router: ^3.0.3 => 3.0.6
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: 3.7.0
```

### Steps to reproduce
1. install @vue/cli@3.7.0
2. vue ui
3. import your project
4. click tasks
5. execute the script in  package.scripts， the script like this "node build/build.config.js -scene=test && npm run start"
6. finally the script would be changed like this "node build/build.config.js -scene test && npm run start"
7. why "="  gone?

### What is expected?
node build/build.config.js -scene=test && npm run start

### What is actually happening?
node build/build.config.js -scene=test && npm run start

---
1.it is available in @vue/cli@3.5.5,
but when i update the version to @vue/cli@3.7,
it  behaves like above.
2.i uninstall @vue/cli@3.7,
and re install @vue/cli3.5.5,
you guest what happen?
@vue/cli@3.5.5 does not work too~~~

**Comment by QingshanLuoyue** [comment]
"What is actually happening?
node build/build.config.js -scene=test && npm run start"

I made a mistake and made some changes.

"What is actually happening?
node build/build.config.js -scene test && npm run start"

**Comment by sodatea** [comment]
Fixed in https://github.com/vuejs/vue-cli/commit/3eabfad234071dd1fb4730211db49dbfb579101e
Will be included in the next release (in this week)
