### ISSUE TITLE
add option to disable cli-highlight when inspecting webpack config

### ISSUE THREAD

**Issue by lkho** [vuejs/vue-cli#4037]
### What problem does this feature solve?
when running `vue-cli-service inspect > output.js` through `npm run`/`yarn run`,  the output.js file is full of unreadable escape characters

### What does the proposed API look like?
`--nocolor` sth like that

**Comment by sodatea** [comment]
I've never seen such escape characters… Which OS and shell are you using?

**Comment by sodatea** [comment]
As far as I know, the highlight utility (`chalk`) uses https://github.com/chalk/supports-color to detect if the stdout stream supports color. It will return false if you are using I/O redirection.

**Comment by lkho** [comment]
I am using windows 10

Maybe it is a shell/terminal problem? I am using PhpStorm, and the behaviors differ from typing the command in the Terminal directly to running a npm configuration. The terminal command runs without problem while the "Run Configuration" output a gibberish file.

**Comment by lkho** [comment]
`package.json`
```json
{
  "scripts": {
    "inspect": "vue-cli-service inspect > inspect.js"
  }
}
```
so my situation is:
Typing directly in terminal `$ vue-cli-service inspect > inspect.js` works.
Typing directly in terminal `$ npm run inspect` works.
Setting up a npm Run Configuration don't work.

**Comment by lkho** [comment]
For anyone encountering this, my solution is to setup a Node.js Run Configuration which points to the real script `node_modules\@vue\cli-service\bin\vue-cli-service.js`, set the application parameters manually, and enable the "Save console output to file" option via the "Logs" tab.

**Comment by sodatea** [comment]
As a workaround, you can run the command with `FORCE_COLOR=0 vue-cli-service inspect`

**Comment by lkho** [comment]
thanks

**Comment by basaran** [comment]
I have the same issue, running inspect via WSL, and opening on windows through VS Code.

This is how it looks like
:
![image](https://user-images.githubusercontent.com/30809170/100292529-bffe4a00-2f4e-11eb-86e7-493619db27b3.png)

Meanwhile, opening the file through console via vi, it's fine.

`FORCE_COLOR=0 ./node_modules/.bin/vue-cli-service inspect  > output.js` did not help.
