### ISSUE TITLE
huge webpack build size

### ISSUE THREAD

**Issue by oivinds** [vuejs/vue-cli#4039]
### Version
4.0.0-alpha.0 

Also tested versions of vue-cli in 3.* range.

### Reproduction link
[https://github.com/oivinds/vue-cli-phaser-bug](https://github.com/oivinds/vue-cli-phaser-bug)

### Environment info
```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
  Binaries:
    Node: 8.9.4 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.5
    Safari: 12.1.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.7.0 
    @vue/babel-preset-jsx:  1.0.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.0.0 
    @vue/cli-overlay:  3.7.0 
    @vue/cli-plugin-babel: ^3.7.0 => 3.7.0 
    @vue/cli-plugin-eslint: ^3.7.0 => 3.7.0 
    @vue/cli-service: ^3.7.0 => 3.7.0 
    @vue/cli-shared-utils:  3.7.0 
    @vue/component-compiler-utils:  2.6.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.2 (4.7.1)
    typescript:  3.4.5 
    vue: ^2.6.10 => 2.6.10 
    vue-eslint-parser:  5.0.0 (2.0.3)
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Run build.

### What is expected?
That the filesize should be far less. 17 mb less!

### What is actually happening?
Import of the phaser npm module in a vue-cli project results in a approx 18 mb app.js file in dist folder on build.
Import of the phaser npm module a plain webpack build: approx 1 mb. 

---
In a separeate test project: Just running webpack on a directory results in: 
 bundle.js  930 bytes       0  [emitted]  main
After adding an import statement importing phaser module : 
bundle.js  1.07 MiB       0  [emitted]  [big]  main

**Comment by LinusBorg** [comment]
I can't run this right now but:

1. Could you run the build command with the `--report` flag to get a bundle report.html producded? It should be able to tell you where the size is coming from.
2. Do you by any change have `NODE_ENV=develomnent` hardcoded in your system environment? That would make the build command to build a development build, inlcuding Webpack code for Hot Module replacement etc.pp.

**Comment by sodatea** [comment]
Here's what I've got:
```
  File                                 Size               Gzipped

  dist/js/chunk-vendors.2a516fac.js    1263.80 KiB        318.83 KiB
  dist/js/app.20d71f44.js              4.61 KiB           1.66 KiB
  dist/css/app.e2713bb0.css            0.33 KiB           0.23 KiB
```

With `NODE_ENV=development`:
```
  File           Size                          Gzipped

  dist/app.js    17866.83 KiB                  3279.39 KiB
```

So I think it might be the culprit.

**Comment by oivinds** [comment]
Yes, your both right. I had exported the NODE_ENV variable. 
Thanks!
