### ISSUE TITLE
Generate .tern-project with vue init

### ISSUE THREAD

**Issue by Yamakaky** [vuejs/vue-cli#404]
See http://ternjs.net/. The file itself is easy to generate http://ternjs.net/doc/manual.html#configuration

**Comment by LiuSuY** [comment]
vue init webpack demo

After the initialization is always the problem in the node version cannot solve this problem
In the following error

· Failed to download repo vuejs-templates/webpack: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80

Do you have friend have a good way to solve my share

**Comment by Yamakaky** [comment]
Wat
Anyway, I use the following config:
```json
{
    "libs": [
        "browser",
        "ecmascript"
    ],
    "plugins": {
        "es_modules": {},
        "webpack": {}
    }
}
```

**Comment by unr** [comment]
Dropped in @Yamakaky's example file, tern started working instantly in my vue components. Cheers!

**Comment by egoist** [comment]
In which template you want to generate `.tern-project`? You should post the feature request there. :P

**Comment by Yamakaky** [comment]
Right ^^
