### ISSUE TITLE
vue create --preset  package install change vue version

### ISSUE THREAD

**Issue by mimimile** [vuejs/vue-cli#4041]
### Version
3.7.0

### Environment info
```
vue 创建预设的时候 vue的包 安装了不是配置文件的版本 安装了最新版。
```

### Steps to reproduce
vue create --preset

### What is expected?
generator
"vue": "^2.5.21",

### What is actually happening?
generator
"vue": "^2.6.10",

**Comment by sodatea** [comment]
请提供复现

**Comment by mimimile** [comment]
@sodatea 这是 执行vue create的时候遇到的 预设的vue版本 被修改了

**Comment by sodatea** [comment]
怎么预设的？

**Comment by mimimile** [comment]
@sodatea 
```
// 项目依赖
  api.extendPackage({
    dependencies: {
      '@fortawesome/fontawesome-free-webfonts': '^1.0.9',
      '@fortawesome/fontawesome-svg-core': '^1.2.10',
      '@fortawesome/free-brands-svg-icons': '^5.6.1',
      '@fortawesome/free-solid-svg-icons': '^5.6.1',
      '@fortawesome/vue-fontawesome': '^0.1.3',
      '@sentry/browser': '^4.6.5',
      'async-validator': '^1.10.1',
      'axios': '^0.18.0',
      'cookiejar': '^2.1.2',
      'decimal.js': '^10.0.2',
      'element-ui': '^2.4.11',
      'js-cookie': '^2.2.0',
      'js-model': '^1.6.1',
      'lodash': '^4.17.11',
      'mockjs': '^1.0.1-beta3',
      'moment': '^2.23.0',
      'normalize.css': '^8.0.1',
      'nprogress': '^0.2.0',
      'numeral': '^2.0.6',
      'path-to-regexp': '^3.0.0',
      'vue': '^2.5.21',
      'vue-qr': '^1.5.2',
      'vue-router': '^3.0.2',
      'vuex': '^3.0.1'
    }
  })
```
实际 vue 的版本 被覆盖成了 
```
'vue': '^2.6.10',
```

**Comment by sodatea** [comment]
这个是因为被默认模板里的版本覆盖了
https://github.com/vuejs/vue-cli/blob/197fd92c735f4c5d9a5dace69698565bd8bf3e4b/packages/%40vue/cli-service/generator/index.js#L12

对于不同 generator 中注入同名依赖的情况，我们合并后的结果会是兼容其版本范围并选择最低版本要求较高的那一个：https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli/lib/util/mergeDeps.js

这不是 bug。

另外有什么特别的原因一定要用 `^2.5.21` 而不是 `^2.6.10` 吗？正常来讲这两个版本区间最后安装的都会是 2.6.10。

如果确有需求可以在 `onCreateComplete` 回调里改 `package.json`。

**Comment by mimimile** [comment]
@sodatea 因为在不知情的情况下 vue-template-compiler  会出现版本不兼容报错，我在使用第三方预设的时候会出问题，所以是不是要把 vue 相关依赖都升级到最新版本呢。

**Comment by sodatea** [comment]
是的，建议都升级都最新版本
