### ISSUE TITLE
Vue CLI creates project directories that are readonly

### ISSUE THREAD

**Issue by AmeerTaweel** [vuejs/vue-cli#4042]
### Version
3.7.0

### Environment info
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
  Binaries:
    Node: 10.15.3 - /usr/bin/node
    Yarn: Not Found
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 67.0
  npmGlobalPackages:
    @vue/cli: 3.7.0
```

### Steps to reproduce
  Create a new project with Vue CLI using `sudo vue create project-name`.

### What is expected?
  Create a project directory that is editable.

### What is actually happening?
  It creates the project directory as **readonly**.

**Comment by sodatea** [comment]
Can't reproduce.
What does "readonly" exactly mean? Could you please paste the result of running `ls -al .` in the project directory here?

**Comment by AmeerTaweel** [comment]
Readonly means that I can't edit anything inside that directory (I can't perform deletions, cutting, or pasting). And a lock icon is shown on the directory in the file explorer of the system. I ran the command `ls -al .` in the project directory and here is the output:

```total 488
drwxr-xr-x   6 root         root           4096 May 23 18:48 .
drwxrwxr-x   6 ameer_taweel ameer_taweel   4096 May 23 18:45 ..
-rw-r--r--   1 root         root             53 May 23 18:47 babel.config.js
drwxr-xr-x   8 root         root           4096 May 23 18:48 .git
-rw-r--r--   1 root         root            214 May 23 18:47 .gitignore
drwxr-xr-x 817 root         root          32768 May 23 18:48 node_modules
-rw-r--r--   1 root         root            910 May 23 18:47 package.json
-rw-r--r--   1 root         root         427007 May 23 18:48 package-lock.json
drwxr-xr-x   2 root         root           4096 May 23 18:47 public
-rw-r--r--   1 root         root            365 May 23 18:48 README.md
drwxr-xr-x   4 root         root           4096 May 23 18:47 src
```

I will edit the issue as I discovered what is happening: If I create the project with `sudo vue create project-name` the directory will be readonly. If I use `vue create project-name` it will work fine and as expected. This means that I just can run `vue create project-name`. But I think it is still a bug that if I use `sudo` it will be readonly.

**Comment by Akryum** [comment]
`sudo` will run it with the Admin super user privileges, which means you as a regular user won't get the rights on the generated content (only the Admin super user). This is unrelated to vue-cli.
