### ISSUE TITLE
创建项目失败

### ISSUE THREAD

**Issue by DaikonX** [vuejs/vue-cli#4043]
### Version
3.6.2

### Environment info
```
vue create fenggege
```

### Steps to reproduce
PS D:\code> vue create fenggege

Vue CLI v3.6.2
┌───────────────────────────┐
│  Update available: 3.7.0  │
└───────────────────────────┘
? Please pick a preset: default (babel, eslint)

Vue CLI v3.6.2
✨  Creating project in D:\code\fenggege.
�  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

yarn install v1.15.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "D:\\code\\fenggege\\yarn-error.log".
error An unexpected error occurred: "https://registry.npm.taobao.org/electron-to-chromium/download/electron-to-chromium-1.3.137.tgz: Request failed \"404 Not Found\"".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 ERROR  command failed: yarn --registry=https://registry.npm.taobao.org --disturl=https://npm.taobao.org/dist

### What is expected?
创建项目成功

### What is actually happening?
实际报淘宝源找不到文件

**Comment by lcexc** [comment]
`verbose stack Error: 404 Not Found: electron-to-chromium@^1.3.133`

刚才也遇到了, 创建个web项目怎么还需要安装 electron呢?

**Comment by CubePoint** [comment]
npm ERR! 404 Not Found: node-releases@^1.1.19

**Comment by demong89** [comment]
都是这样了。等修复

**Comment by lebronxie** [comment]
都这样了

**Comment by Tsingwu** [comment]
+1，一早上都在失败，各种资源找不到

**Comment by lavandulor** [comment]
也遇到了，求解决

**Comment by lcexc** [comment]
换成官方源就好了(注释掉npmrc里面的配置)

**Comment by nongshuqiner** [comment]
+1，也遇到这个问题，创建失败并且npm run serve无法运行起项目

**Comment by sodatea** [comment]
CNPM / 淘宝源现在不稳定，请暂时使用官方源。修改 `~/.vuerc` 中 useTaobaoRegistry 字段为 false

**Comment by Jhaidi** [comment]
修改 .vuerc文件中useTaobaoRegistry: false, packageManager: yarn

**Comment by sodatea** [comment]
已恢复
