### ISSUE TITLE
crate project failed

### ISSUE THREAD

**Issue by demong89** [vuejs/vue-cli#4045]
### Version
3.7.0

### Reproduction link
[https://github.com/](https://github.com/)

### Environment info
```
node version 10.15.3.

```

### Steps to reproduce
failed reason is node-releases is not found

### What is expected?
create success

### What is actually happening?
not found  node-releases

**Comment by nongshuqiner** [comment]
I have the same problem.And the project created cannot `npm run serve` run.

**Comment by sodatea** [comment]
cnpm & taobao registry are unstable right now.

**Comment by sodatea** [comment]
As a workaround:
`vue config -s useTaobaoRegistry false`

**Comment by sodatea** [comment]
已修复
