### ISSUE TITLE
How do I configure the 'vue.config.js' file after dev or build can make index.html link extracted less file not extracted css file?

### ISSUE THREAD

**Issue by AeoRu5** [vuejs/vue-cli#4049]
### What problem does this feature solve?
This is a question about VUE-CLI3.
When run 'npm run serve' or 'npm run build', webpack will extract all less files and make them become one css file, then in index.html will appear a link `link rel='sheetstyle' href='app.css'>`.
But I wanna the result like `<link rel='sheetstyle/less' href='app.less'>` without `<link rel='sheetstyle' href='app.css'>`.

How to configure?

### What does the proposed API look like?
css.enable()
less.extract()
less.loaderOptions()

**Comment by AeoRu5** [comment]
在编译的时候，mini-css-extract-plugin会把所有的style里面的less编译成css，然后link进index.html。
我在vue.config.js里面new MiniCssExtractPlugin()生成了一个less文件，但是他还是会生成一个css文件，并且在我这个less下面。怎么做才能不让生成这个css文件呢？

**Comment by sodatea** [comment]
感谢关注，但是我们的 GitHub issues 只用于 Bug 反馈和特性请求，如果有使用上的问题建议到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问。
