### ISSUE TITLE
Include Vue instance when Build Target is Lib mode

### ISSUE THREAD

**Issue by seteam1** [vuejs/vue-cli#4055]
### What problem does this feature solve?
We are building multiple micro frontend applications that are then stitched together into singular spa experience at run-time. As such, building these applications in using a build target "--target app" is not a viable approach. We need a single file that contains the application source code to load up as we are stitching applications together. For this reason, using a build target "--target lib" seemed like a ideal solution for us. However, we've noticed the build tool contains logic when it is building the application that it excludes Vue instances automatically, which you folks have clearly indicated in your documentation. We weren't able to override this behavior using either the configureWebpack object nor the chainWebpack() callback function. 

### What does the proposed API look like?
As simple fix would be to move the process of externalizing Vue up prior to applying configureWebpack config object or executing chainWebpack() callback. That way, you are giving programmers the flexibility to include it if it suits their architectural scenario without it being a breaking change.

**Comment by trickstival** [comment]
I've seen that config is defined based on user webpack chain:
https://github.com/vuejs/vue-cli/blob/500dc5020517f8d5780ce1ef85f9c74abc0c184c/packages/%40vue/cli-service/lib/commands/build/resolveLibConfig.js#L29

and then used to remove Vue instances:
https://github.com/vuejs/vue-cli/blob/500dc5020517f8d5780ce1ef85f9c74abc0c184c/packages/%40vue/cli-service/lib/commands/build/resolveLibConfig.js#L57

Is it possible to create the config another way, apply externals and then apply the chain?

If it's not, maybe a flag on vue.config can do that, so we add an "if" before applying externals

**Comment by seteam1** [comment]
Personally, not having reviewed the source code in depth, @trickstival approach seems like a simple, backwards compatible solution to the problem. We would be happy with a change like that!

**Comment by trickstival** [comment]
I'm still trying to understand the project structure as a whole, but I imagine something like that might work:
```js
    if (!api.service.projectOptions.keepVueInstance) {
      // externalize Vue in case user imports it
      config
        .externals({
          ...config.get('externals'),
          vue: {
            commonjs: 'vue',
            commonjs2: 'vue',
            root: 'Vue'
          }
        })
    }
```
Here in the original file:
https://github.com/vuejs/vue-cli/blob/500dc5020517f8d5780ce1ef85f9c74abc0c184c/packages/%40vue/cli-service/lib/commands/build/resolveLibConfig.js#L57

But I'm not sure how to test it right now, still searching some examples in the project

**Comment by seteam1** [comment]
Looking at the code snippet you provided, I might suggest a slightly different incarnation of it. That approach has a limitation in that if your "keepVueInstance" is false, then externals that the developer wanted to configure will not be applied either.

Maybe something like the following:
` 
      // externalize Vue in case user imports it
      config
        .externals({
          ...config.get('externals'),
          ...(!api.service.projectOptions.keepVueInstance ? { 
               vue: {
                    commonjs: 'vue',
                    commonjs2: 'vue',
                    root: 'Vue'
               }
          } : {})
        })
`

**Comment by trickstival** [comment]
That's actually much better!

**Comment by seteam1** [comment]
Apologies for the formatting, just fixed it. I am still learning my way around GitHub's formatting features.

**Comment by trickstival** [comment]
## [OFFTOPIC]
If you add js after your backticks you get some code highlighting. Like that:
` ``js 
let a = 'hey'

`` `
Without spaces:
```js
let a = 'hey'
```

**Comment by mithom** [comment]
i am trying to do something very similar (a core app with modules the user can install, but i don't want to update the app when new modules become available). I justed wanted to start looking into the lib or wc option when i tumbled upon this. If you want to load them at runtime, won't the webcomponent build be an option? or does the webcomponent solution not offer the following capabilities:
```html 
<component :is="moduleA">slot content</component>
```

**Comment by romansp** [comment]
I'm trying to do this exact thing. Is there any workaround? Also, I wonder if this issue is up for grabs, I would like to work on it.

**Comment by sodatea** [comment]
I'm skeptical about the actual use case.
But if we have to support it, I think `vue.config.js` is not the best place to put this option, as it only applies the lib or web component target. This name also leads to confusion (Vue **instance** typically refers to the result of `new Vue`).	

What about adding a flag to the `build` command? Like:
```
--inline-vue         include the Vue module in the final bundle of library or web component target
```

**Comment by mithom** [comment]
I got my plan to work by globally registering the components i wanted to share to the subcomponents. This way i don't have to call anything special. For data transfer between both i use either props or vuex. I build with target lib and include them using dynamic imports with the native require instead of webpack require.

So far no issues for me

**Comment by agileago** [comment]
@sodatea When will it be released？ i strongly need this feature

**Comment by agileago** [comment]
@mithom how do you resolve this question? is there some code to see ?

**Comment by romansp** [comment]
@sodatea, I really like flag for `build` command more than `vue.config.js` option.

Worth updating #4261 PR?

**Comment by sodatea** [comment]
@romansp Yeah go ahead please.

**Comment by romansp** [comment]
@sodatea I updated #4261 PR. I think we can continue discussion over there.

**Comment by agileago** [comment]
@sodatea 
Is it possible to merge and publish as soon as possible?

**Comment by sodatea** [comment]
This feature is now shipped in both v3.11.0 & v4.0.0-rc.0

**Comment by agileago** [comment]
@sodatea  thanks. perfect!

**Comment by dika-pro** [comment]
When inline flag is true, is Vue attached to global variable?

What if two components bundle different versions of Vue?

**Comment by agileago** [comment]
@dika-pro no. Vue is module
