### ISSUE TITLE
Adding HtmlWebpackPlugin break --modern

### ISSUE THREAD

**Issue by ziaxdk** [vuejs/vue-cli#4062]
### Version
3.8.0

### Reproduction link
[https://github.com/ziaxdk/vue-build-modern-bug](https://github.com/ziaxdk/vue-build-modern-bug)

### Environment info
```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: ^3.8.0 => 3.8.0
    @vue/cli-plugin-eslint: ^3.8.0 => 3.8.0
    @vue/cli-service: ^3.8.0 => 3.8.0
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.2
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
When adding a HtmlWebpackPlugin entry in vue.config.js and using the --moden switch, the injected output is only modern and not legacy

### What is expected?
To inject both legacy and modern scripts

### What is actually happening?
Only modern scripts are injected

---
Comment out the vue.config.js

**Comment by sodatea** [comment]
There's already an html-webpack-plugin instance in the default config:
https://github.com/vuejs/vue-cli/blob/500dc5020517f8d5780ce1ef85f9c74abc0c184c/packages/%40vue/cli-service/lib/config/app.js#L138-L231
Why add it again?

**Comment by trickstival** [comment]
I just got curious about this "modern" switch. Searched a little bit and couldn't find a thing about it.
Where does it come from? Are there any docs for that?

**Comment by trickstival** [comment]
Nevermind, just found that: https://cli.vuejs.org/guide/cli-service.html

**Comment by ziaxdk** [comment]
It's when adding an extra HtmlPlugin "entry" to webpacks config, and not when importing again

**Comment by sodatea** [comment]
Sorry for forgetting to reply this issue ealier.
Actually, you can (and should) use `pages` to config additional html-webpack-plugin entries, because there are many underlying configs to do so as to make it work with modern mode and other features.

An example adapted from the config in your reproduction repo:
```js
const HtmlWebpackExcludeAssetsPlugin = require('html-webpack-exclude-assets-plugin')

module.exports = {
   pages: {
      index2: {
         filename: 'index2.html',
         template: 'public/index2.html',
         entry: 'src/main.js',
         excludeAssets: /.css$/
      }
   },
   configureWebpack: {
      plugins: [
         new HtmlWebpackExcludeAssetsPlugin(),
      ]
   },
}
```
