### ISSUE TITLE
cli3默认设置了publicpath，这使得我无法使用__webpack_public_path__，怎么办

### ISSUE THREAD

**Issue by jiong0208** [vuejs/vue-cli#4072]
### Version
3.8.0

### Environment info
```
nodejs 8.12.0
```

### Steps to reproduce
![image](https://user-images.githubusercontent.com/21174896/58522776-6b143300-81f4-11e9-8f46-756b5be7b3e2.png)

### What is expected?
项目入口文件中设置了__webpack_public_path__，vue.config.js里没有设置publicPath，这样子做并不能运行时设置publicPath

### What is actually happening?
希望vue-cli3能增加配置项开关，让用户能够设置__webpack_public_path__，来实现动态publicPath的功能！

**Comment by sodatea** [comment]
请提供代码并详细描述期望行为。

**Comment by Rplus** [comment]
I have some problem with vue/cli v3.8.4

I cannot let the path become 'relative path' when following [doc](https://cli.vuejs.org/config/#publicpath). 
```js
module.exports = {
  publicPath: './',
}
```

But it successes with that code: (´･ω･`)a
```js
module.exports = {
  publicPath: './.',
}
```
