### ISSUE TITLE
非default导出组件导致无法引入和打包高阶异步组件

### ISSUE THREAD

**Issue by yangdan8** [vuejs/vue-cli#4077]
### Version
4.0.0-alpha.1

### Reproduction link
[https://codepen.io/anon/pen/pmxRVB](https://codepen.io/anon/pen/pmxRVB)

### Environment info
```
vue last
```

### Steps to reproduce
见代码
修改官方cli默认demo部分代码,即将default去掉后导致无法打包

### What is expected?
打包正常,组件异步加载

### What is actually happening?
无法正常打包,或者组件无法正确加载

**Comment by sodatea** [comment]
https://vue-loader.vuejs.org/zh/spec.html#%E8%84%9A%E6%9C%AC
单文件组件规范要求必须有默认导出，如果你不用默认导出、在一个文件里定义多个组件的话，我们无法确认对应的 template 应该关联到哪个组件。所以有这种需求的请放在单独的文件里。
