### ISSUE TITLE
能否自定义node_modules/.cache这个目录的位置

### ISSUE THREAD

**Issue by mkanako** [vuejs/vue-cli#4078]
### What problem does this feature solve?
因为这个缓存目录写了大量大量小文件，我心疼硬盘

我希望能自定义，然后我把目录指向一个内存盘（ramdisk），这样既不伤硬盘，也能提高性能

### What does the proposed API look like?
提供选项自定义.cache目录

**Comment by sodatea** [comment]
建议自行 mount，考虑到实现可能带来的维护成本，暂时不准备支持此类需求。

**Comment by mkanako** [comment]
了解，费了一番功夫才搞定，mac下不能用mount，要装osxfuse和bindfs才行
