### ISSUE TITLE
eslint: import/no-cycle definition not found.

### ISSUE THREAD

**Issue by vpiskunov** [vuejs/vue-cli#4082]
### Version
3.8.0

### Reproduction link
[https://github.com/vpiskunov/canwego-test-eslint](https://github.com/vpiskunov/canwego-test-eslint)

### Environment info
```

Environment Info:

  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
  Binaries:
    Node: 12.3.1 - ~/.nvm/versions/node/v12.3.1/bin/node
    Yarn: Not Found
    npm: 6.9.0 - ~/.nvm/versions/node/v12.3.1/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 61.0.1
    Safari: 12.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: ^3.8.0 => 3.8.0
    @vue/cli-plugin-eslint: ^3.8.0 => 3.8.0
    @vue/cli-service: ^3.8.0 => 3.8.0
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-airbnb: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.2 (4.7.1)
    nativescript-vue: ^2.2.2 => 2.2.2
    nativescript-vue-navigator: ^0.0.3 => 0.0.3
    nativescript-vue-template-compiler: ^2.2.2 => 2.2.2
    nativescript-vue-web: ^0.9.4 => 0.9.4
    vue: ^2.6.10 => 2.6.10
    vue-cli-plugin-nativescript-vue: git https://github.com/nativescript-vue/vue-cli-plugin-nativescript-vue.git#dev => 0.0.15
    vue-eslint-parser:  2.0.3 (5.0.0)
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router: ^3.0.3 => 3.0.6
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: 3.7.0
```

### Steps to reproduce
Clone repository - or:

Create a new project in Vue CLI / UI
Use:
Package manager: npm
Preset: vue-router, vuex, node-sass, babel, eslint
Linter config: ESLint   Airbnb config

### What is expected?
No errors should occur.

### What is actually happening?
Error given in any file:

Definition for rule 'import/no-cycle' was not found

Using atom & eslint. 

---
This is all on a clean, new project, created fresh from Vue CLI / UI

Workaround to resolve this could be to extend `airbnb-base` instead of `@vue/airbnb`. That works, but results in another issue, such as import resolver not willing to take aliases when resolving paths. 

Although node/npm version in environment is v12.3.1, this has been tested and happens on versions 9 through 11.

**Comment by sodatea** [comment]
Can't reproduce when running `npm run lint`.
Does it only occur in the atom editor?

**Comment by vpiskunov** [comment]
Yes, it only happens in atom. However there doesn't seem to be a way to force the two, to use same configuration.

To my understanding, atom uses the `.eslintrc.js` in the project root. So it either should have same errors as `npm run lint`, or `npm run lint` doesn't use `.eslintrc.js`.

I'm lead to believe its the last option, so need to find how to fix this.

**Comment by sodatea** [comment]
`npx eslint src/` does not output any errors, either.
I believe it's a bug in atom's linter-eslint.

**Comment by vpiskunov** [comment]
Actually was happening due to editor using a global ESLint, and that package (along with plugins e.g. airbnb etc.) were outdated. 

For anyone encountering this issue, try unchecking the box in `Settings > Packages > linter-eslint > Settings > Use global ESLint installation`. 

If that works, check it again, ensure the correct `Global Node Installation Path`(for same version, if using NVM) is set on the same page, and run:
`npm outdated -g`
`npm i -g [package_name]` for each package with eslint in the name. 

Also ensure you have `eslint-plugin-vue` package installed.

**Comment by huan0118** [comment]
我在Visual Studio Code中也出现这个问题。我卸载了全局ESLint，但还是有错误出现，我在项目的.eslintrc.js中加入了 'import/no-cycle': ['error', { maxDepth: 1 }]。我的场景是在vuex的store.js中引用了aaa.js。aaa.js又引入了bbb.js，最后在bbb.js中我引入了store.js。我担心会出现问题，但是不知如何解决

**Comment by chaojiangcn** [comment]
> 我在Visual Studio Code中也出现这个问题。我卸载了全局ESLint，但还是有错误出现，我在项目的.eslintrc.js中加入了 'import/no-cycle': ['error', { maxDepth: 1 }]。我的场景是在vuex的store.js中引用了aaa.js。aaa.js又引入了bbb.js，最后在bbb.js中我引入了store.js。我担心会出现问题，但是不知如何解决

老哥  最后怎么解决的 ？ 一直提示错误，看着难受
