### ISSUE TITLE
 Multi-page HTML Files can not been Hot Update when html file changed

### ISSUE THREAD

**Issue by jerryniepan** [vuejs/vue-cli#4085]
### Version
3.8.0

### Reproduction link
[http://any.com](http://any.com)

### Environment info
```
v10.11.0
```

### Steps to reproduce
v10.11.0

### What is expected?
v10.11.0

### What is actually happening?
can not Hot Update of Multi-page HTML Files when html file changed

---
can not Hot Update of Multi-page HTML Files when html file changed

**Comment by LinusBorg** [comment]
This is not a valid bug report. Please follow the issue guidelines.
