### ISSUE TITLE
Change default value of TypeScript class-style prompt to false

### ISSUE THREAD

**Issue by k-miyake** [vuejs/vue-cli#4086]
### What problem does this feature solve?
According to the policy of [[Abandoned] Class API proposal: Update: the Class API proposal is being dropped.](Https://github.com/vuejs/rfcs/pull/17#issuecomment-494242121) , we should to set the default value to false in the TypeScript prompt `Use class-style component syntax?`.

### What does the proposed API look like?
Change `vue-cli/packages/@vue/cli-plugin-typescript/prompts.js` as follows:

```
{
    name: `classComponent`,
    type: `confirm`,
    message: `Use class-style component syntax?`,
    default: false
},
```

**Comment by LinusBorg** [comment]
`vue-class-component` will continue to be supported / exist in Vue 3, with decorators just like it works now.

We just don't intend to make a class API *without decorators* part of Core.

So as vue-class-component still provides the best TS exerience as fas as complete type safety is concerned, it makes sense to keep it as a default.

When Vue 3 arrives, people who want to use the "new way" of using TS  would have to migrate their code with either style (class or options object)

**Comment by k-miyake** [comment]
Thank you. I understood very well.
Many people around me are wondering that `vue-class-component` will not be supported in Vue 3. So I hope your team announce that policy widely.

**Comment by LinusBorg** [comment]
We mentioned it many times in the RFC discussions both before and after it was abandoned.

It's a separate library and was never affected by the RFC.

**Comment by k-miyake** [comment]
Thank you!
