### ISSUE TITLE
Uncaught SyntaxError: Use of const in strict mode since v3.8.0

### ISSUE THREAD

**Issue by mistabiggx** [vuejs/vue-cli#4089]
### Version
3.8.0

### Environment info
```
  System:
    OS: macOS Sierra 10.12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 11.10.1 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: Not Found
    Safari: 12.1.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.8.0 
    @vue/babel-preset-jsx:  1.0.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.0.0 
    @vue/cli-overlay:  3.8.0 
    @vue/cli-plugin-babel: ^3.0.3 => 3.8.0 
    @vue/cli-plugin-eslint: ^3.0.3 => 3.8.0 
    @vue/cli-service: 3.8.0 => 3.8.0 
    @vue/cli-shared-utils:  3.8.0 
    @vue/component-compiler-utils:  2.6.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue:  4.7.1 
    vue: ^2.5.17 => 2.6.10 
    vue-cli-plugin-cordova: ^2.0.3 => 2.1.3 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.3 
    vue-lazyload:  1.2.3 
    vue-loader:  15.7.0 
    vue-router: ^3.0.1 => 3.0.6 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.7 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 3.8.2
```

### Steps to reproduce
with the plugin "vue-cli-plugin-cordova" installed/set up, run "npm run cordova-serve-android"

### What is expected?
N/A

### What is actually happening?
N/A

---
When running "npm run serve" for mobile/cordova, it throws the exception "Uncaught SyntaxError: Use of const in strict mode" causing the app to hang. I understand this is a babel-related issue but since vue-cli is handling babel, I thought I should report this here. The issue on started from v3.8.0. Prior versions since v3.0.3 all work and so I'm using v3.7.0 for now. I must also mention that the issue does not apply when building, only for when serving/dev

**Comment by LinusBorg** [comment]
Hi  

Thanks for filing this issue! Could you please provide a small reproduction on jsfiddle.net so we can debug this without trying to replicate this ourselves?`

That would be very helpful, thanks!

Also: As this only happens with the cordova setup, did you open an issue there as well?

**Comment by riki137** [comment]
We receive this error a lot:
https://sentry.io/share/issue/1cbe4aae4a3d40d28be7038b78f8f181/
