### ISSUE TITLE
Linux下npm run build构建成功后node进程扔需要很长时间才能结束

### ISSUE THREAD

**Issue by xiaoming0827** [vuejs/vue-cli#4102]
### Reproduction link
[http:/vuejs.org](http:/vuejs.org)

### Environment info
```
Linux   jekins
```

### Steps to reproduce
1、因为项目是借助jekins在Linux下进行打包构建的
2、但是在Linux下执行npm run build 命令，都已经提示 ”DONE  Build complete. The dist directory is ready to be deployed.“ 但是node进程一直还不结束，光标仍然还在闪
3、一般会几分钟才会结束，这会影响jekins的执行效率，因为构建成功后下面还有一些部署的脚本去执行，而jekins会等待node进结束才会执行 下面的脚本

### What is expected?
提示”DONE  Build complete. The dist directory is ready to be deployed.“
node进程会立刻结束活退出

### What is actually happening?
需要几分钟进程才能结束或者退出，导致时间的浪费

**Comment by sodatea** [comment]
任何项目都这样吗？所有环境都是这样还是特定的 Linux 系统下是这样？能提供一下 `vue info` 命令的输出方便我们看一下系统和环境相关的信息吗？不然的话无法排查问题，因为我这边从来没碰到过，也没有其他人报告过类似问题。

**Comment by xiaoming0827** [comment]
> 任何项目都这样吗？所有环境都是这样还是特定的 Linux 系统下是这样？能提供一下 `vue info` 命令的输出方便我们看一下系统和环境相关的信息吗？不然的话无法排查问题，因为我这边从来没碰到过，也没有其他人报告过类似问题。

以下为本地vue info输出相关的信息，因Linux服务器环境没有全局安装vuecli所以无法查新info，经过测试再Linux 服务器上去build都会有这样的问题，构建成功后都会过几分钟进程才会自动结束，很容易复现此问题，十分感谢！
System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.80
    Firefox: 66.0.5
    Safari: 12.1.1
  npmPackages:
    @ant-design/icons-vue:  1.0.1 
    ant-design-vue:  1.3.8 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    vue-ref:  1.0.6 
  npmGlobalPackages:
    @vue/cli: 3.7.0

**Comment by sodatea** [comment]
服务器的系统以及 node 版本是……？

**Comment by xiaoming0827** [comment]
> 服务器的系统以及 node 版本是……？

nodejs版本 v10.16.0 服务器系统是redhat 具体版本不太清楚

**Comment by vanppo** [comment]
在 node 12.2.0 遇到同样的问题，构建库文件后进程不退出，CPU 占用飙高，导致 CI 失败，node 8.12.0 没问题。
```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v12.2.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
    Safari: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2 
    @vue/babel-preset-app:  3.3.0 
    @vue/babel-preset-jsx:  1.0.0-beta.2 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2 
    @vue/babel-sugar-inject-h:  1.0.0-beta.2 
    @vue/babel-sugar-v-model:  1.0.0-beta.2 
    @vue/babel-sugar-v-on:  1.0.0-beta.2 
    @vue/cli-overlay:  3.3.0 
    @vue/cli-plugin-babel: ^3.3.0 => 3.3.0 
    @vue/cli-plugin-eslint: ^3.3.0 => 3.3.0 
    @vue/cli-plugin-typescript: ^3.3.0 => 3.3.0 
    @vue/cli-plugin-unit-mocha: ^3.3.0 => 3.3.0 
    @vue/cli-service: ^3.3.0 => 3.3.0 
    @vue/cli-shared-utils:  3.3.0 
    @vue/component-compiler-utils:  2.5.0 
    @vue/eslint-config-airbnb: ^4.0.0 => 4.0.0 
    @vue/eslint-config-typescript: ^3.2.0 => 3.2.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/test-utils: ^1.0.0-beta.20 => 1.0.0-beta.28 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    babel-plugin-transform-vue-jsx:  4.0.1 
    eslint-plugin-vue: ^5.0.0 => 5.1.0 (4.7.1)
    typescript: ~3.1.1 => 3.1.6 
    vue: ^2.5.21 => 2.5.22 
    vue-class-component:  6.3.2 
    vue-eslint-parser:  4.0.3 (2.0.3)
    vue-hot-reload-api:  2.3.1 
    vue-loader:  15.5.1 
    vue-property-decorator: ^7.0.0 => 7.3.0 
    vue-router: ^3.0.1 => 3.0.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.5.22 
    vue-template-es2015-compiler:  1.8.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Comment by sodatea** [comment]
请问是你们的特定项目才会出现此问题还是说新建一个 Hello World 项目也这样？我暂时没办法在本地复现出来……

**Comment by xiaoming0827** [comment]
> 请问是你们的特定项目才会出现此问题还是说新建一个 Hello World 项目也这样？我暂时没办法在本地复现出来……

建议本地使用Linux虚拟机试一下，一般会结束进程需要1-3分钟才结束，在windows和mac上构建成功会立即结束，没有这样的问题

**Comment by vanppo** [comment]
> 请问是你们的特定项目才会出现此问题还是说新建一个 Hello World 项目也这样？我暂时没办法在本地复现出来……

是几个月之前建的项目，构建的目标是 lib，在 nodejs v8.12.0 下面一切正常。
当我想要升级 nodejs 版本到 v12.2.0 时才发现这个问题的，同样的 nodejs 版本构建 app 又不会这样。
尝试过升级 **@vue/cli-service** 问题还是存在。
在 CircleCI 的 nodejs 镜像和我自己的 Mac 必定能重现。

**Comment by sodatea** [comment]
我用 node:12 的 docker 镜像新建了一个默认应用，无法复现。

@xiaoming0827 你的 `vue info` 输出肯定不是你碰到问题的这个项目。请再次确认是否任何一个用 Vue CLI 创建的项目都会出现此问题，还是说只有你的这个特定项目出问题了。如果是后者，请提供代码。

@vanppo 你的 `vue info` 结果显示你很多依赖版本都过劳，请先重新安装依赖。如果仍然有问题的话请提供代码。

**Comment by panio123** [comment]
我也有这个问题，打包完之后需要使用gulp做一些后续操作，实现不了。

**Comment by panio123** [comment]
突然找到了我的问题，是我用了一个插件（自己写的） ```vue-auto-routes-webpack-plugin```的问题，有一个监听文件变化自动生成路由配置的功能，打包时也进行了监听，然后进程就一直无法结束了。

**Comment by EthanHannn** [comment]
我这里发现webpack-bundle-analyzer会导致打包进程无法终止，移除这个插件功能恢复正常

**Comment by blazeplore** [comment]
今天也遇到了这个问题，把node换了一个版本解决了
