### ISSUE TITLE
使用环境变量VUE_APP_***的一些问题

### ISSUE THREAD

**Issue by lvjiaxuan** [vuejs/vue-cli#4106]
### Version
3.8.2

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  Binaries:
    Node: 11.3.0 - D:\devtools\dev_nvm\nodejs\node.EXE
    Yarn: 1.16.0 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - D:\devtools\dev_nvm\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.8.0 
    @vue/babel-preset-jsx:  1.0.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.0.0 
    @vue/cli-overlay:  3.8.0 
    @vue/cli-plugin-babel: ^3.8.0 => 3.8.0 
    @vue/cli-service: ^3.8.0 => 3.8.0 
    @vue/cli-shared-utils:  3.8.0 
    @vue/component-compiler-utils:  2.6.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    vue: ^2.6.10 => 2.6.10 
    vue-cli-plugin-ljx-test: ^1.0.68 => 1.0.68 
    vue-cli-plugin-style-resources-loader: ^0.1.3 => 0.1.3 
    vue-hot-reload-api:  2.3.3 
    vue-infinite-scroll: ^2.0.2 => 2.0.2 
    vue-lazyload:  1.2.3 
    vue-loader:  15.7.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. **.env.production:** set `VUE_APP_VCONSOLE = 0`.

2. **main.js:** code `+process.env.VUE_APP_VCONSOLE === 1 && import('vconsole').then(module => new module.default());`.

3. run build in production env.

4. In the dependency graph, the vconsole module still exists.

***

1. **main.js:** code `process.env.VUE_APP_VCONSOLE === '1' && import('vconsole').then(module => new module.default());`.

2. In the dependency graph, the vconsole is nonexistent.That's what I expected.

### What is expected?
When " process.env.VUE_APP_VCONSOLE === 1 && import('vconsole').then(module => new module.default());", the vconsole should not exist in the dependency graph.

### What is actually happening?
In the dependency graph, the vconsole module still exists.

---

![image](https://user-images.githubusercontent.com/11309921/58940579-5d3e4f00-87ac-11e9-8849-56d3095a69d6.png)

这看起来是webpack的问题，但我觉得这里容易被回复得到答案

**Comment by sodatea** [comment]
.env 文件里定义的变量都是字符串，`'1' !== 1`

**Comment by lvjiaxuan** [comment]
> .env 文件里定义的变量都是字符串，`'1' !== 1`

我用的是，`+process.env.VUE_APP_VCONSOLE === 1`，即`+'1' !== 1`？？

**Comment by sodatea** [comment]
哦哦，之前没理解对，抱歉。

那这样的话这是 webpack 的 bug，请给他们提 issue。
如果我没搞错的话，这是因为 webpack 在处理依赖树之前，用于 dead code elimination 的解析器解析能力有限，只能处理等号两边表达式结果类型相同的情况，所以实际仍然会生成对应 chunk（但并不会使用，因为后面用于压缩代码的 terser 会把这部分加载依赖的代码消除掉）。
