### ISSUE TITLE
After built the z-index changed

### ISSUE THREAD

**Issue by RoamIn** [vuejs/vue-cli#411]
### Version
not just v2.8.1

### Reproduction link
Just init any project.

### Steps to reproduce
- Just make a vue component，write z-index in style
- Run command: `npm  run dev`，everything fine
- Run command: 'npm run build`，what a mess...my z-index value changed

I think the z-index value shouldn't be changed，because we may use the third party plugin like jQuery plugin which could use z-index. In this condition, the z-index calculation is unnecessary, and make mistakes.

### What is expected?
keep my z-index value

### What is actually happening?
my z-index changed

**Comment by egoist** [comment]
Please report issue in relevant template repo.

**Comment by RoamIn** [comment]
Oh, it's webpack template.
