### ISSUE TITLE
Any way to escape $ in the ENV file?

### ISSUE THREAD

**Issue by tomko80** [vuejs/vue-cli#4110]
I have my endpoint URLs listed in the .env files. One of the URLs point to an OData source so we address includes /items?$top=999. When I build I notice the value from the variable becomes /items?=999. 

How can I escape the $ character to avoid this? I guess the webpack assumes I like to point to an other variable in the value?

Found nothing in the docs about this.

**Comment by LinusBorg** [comment]
`\$`

**Comment by dalezak** [comment]
@LinusBorg I don't believe that `\$` works. In my `.env` file, I tried both:

```
VUE_APP_GOOGLE_DISCOVERY_DOCS=https://sheets.googleapis.com/$discovery/rest?version=v4
```
and
```
VUE_APP_GOOGLE_DISCOVERY_DOCS=https://sheets.googleapis.com/\$discovery/rest?version=v4
```
However at runtime the `process.env.VUE_APP_GOOGLE_DISCOVERY_DOCS` value is always `https://sheets.googleapis.com//rest?version=v4`.

**Comment by Davut-Atajanov** [comment]
don't know if anyone needs this, but put $ in front of every $. 
essentially a double $$ everywhere

**Comment by naveedpash** [comment]
use `"VARIABLE=foo\$bar" ` or `VARIABLE=foo$$bar`
