### ISSUE TITLE
No way to escape $ in the ENV variables?

### ISSUE THREAD

**Issue by tomko80** [vuejs/vue-cli#4111]
### Version
3.5.1

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.1004.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.3
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.3
    @vue/babel-preset-app:  3.5.1
    @vue/babel-preset-jsx:  1.0.0-beta.3
    @vue/babel-sugar-functional-vue:  1.0.0-beta.3
    @vue/babel-sugar-inject-h:  1.0.0-beta.3
    @vue/babel-sugar-v-model:  1.0.0-beta.3
    @vue/babel-sugar-v-on:  1.0.0-beta.3
    @vue/cli-overlay:  3.5.1
    @vue/cli-plugin-babel: ^3.5.0 => 3.5.1
    @vue/cli-plugin-eslint: ^3.5.0 => 3.5.1
    @vue/cli-service: ^3.5.0 => 3.5.1
    @vue/cli-shared-utils:  3.5.1
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.2
    vue: ^2.6.6 => 2.6.10
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router: ^3.0.1 => 3.0.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
I have my endpoint URLs listed as variables in the .env files. One of the URLs point to an OData source like /items?$top=999. When I build the project I notice at runtime that the value from the variable becomes /items?=999 without $top.

### What is expected?
I need a way to escape the $ character to avoid this. Using $$ or \ $ did not help.

### What is actually happening?
$ and preceding strings get removed/replaced.

---
There is nothing about this in the documentation.

**Comment by LinusBorg** [comment]
Accoding to the ["docs" / tests](https://github.com/motdotla/dotenv-expand/blob/master/test/.env) of the `dotenv-expand` package that we use (and that we [link to from the cli docs](https://cli.vuejs.org/guide/mode-and-env.html#environment-variables)), a backslash `is` the appropriate escape character:

```env
ESCAPED_EXPAND=\$ESCAPED
```

**Comment by eelokets** [comment]
Sometimes `\\$variable` is working
