### ISSUE TITLE
Strip console and debug calls in production code

### ISSUE THREAD

**Issue by holtwick** [vuejs/vue-cli#4115]
### What problem does this feature solve?
Usually logging in production code should be limited in difference to development mode. In production mode debug calls should be stripped to allow smaller code and faster execution.

### What does the proposed API look like?
Code optimizers offer settings like `drop_comments` to strip calls to console for production code. 

But it would be great to have more complex settings like leaving `console.error` calls and the like in place.

Also stripping calls to custom loggers like https://www.npmjs.com/package/debug would be great.

**Comment by LinusBorg** [comment]
We minimize code with Terser, so if Terser doesn't support this, we won't be able to provide it - we won't write our own minifier.

If you really need this as a feature in Terser, open a feature request in their repository.

If Terser options offer what you need, you can adjust the minifier options through the [webpack config API in `vue.config.js`](https://cli.vuejs.org/guide/webpack.html)
