### ISSUE TITLE
vue init webpack projectname 创建项目时，一直在downloading templates

### ISSUE THREAD

**Issue by luoxianchao** [vuejs/vue-cli#412]
Failed to download repo vuejs-templates/webapck: tunneling socket could not be established, cause=connect ETIMEDOUT 172.16.10.7:80
最后报的这个错误，npm的镜像也切换了，还是不能成功

**Comment by posva** [comment]
Look for closed similar issues. The problem is with your network not vue-cli

**Comment by rakaalrian** [comment]
i got same issue, could you please explain what kind of problem that might be in my network? cause i think my network is working fine to do other things, except for installing vue @posva

**Comment by sevencai** [comment]
Maybe you are behind a proxy, try "npm config set proxy=http://your-company-proxy.com:port"
