### ISSUE TITLE
Does vue css modules support the ::v-deep function like scoped?

### ISSUE THREAD

**Issue by fengyun2** [vuejs/vue-cli#4123]
### What problem does this feature solve?
Customize the style of a subcomponent in a local style in the parent component.

### What does the proposed API look like?
```html
<style module>
.search-form-box {
  ::v-deep {
    .el-form {
      .el-input {
        line-height: 40px;
      }
    }
  }
}
</style>
```

**Comment by LinusBorg** [comment]
1. Your feature request should explain a bit more what you want. I don't understand it at all.
2. It seems this is more of a request for vue-loader than vue-cli

**Comment by Viney29** [comment]
Any update on this?
