### ISSUE TITLE
devServer 下可否生成 html 文件，其它样式热更新？

### ISSUE THREAD

**Issue by mzTeamMeatMan** [vuejs/vue-cli#4128]
### What problem does this feature solve?
因为我们项目是 java 端渲染模板且运行的，独立端口运行前端将无法访问 api

我们的是旧项目，webpack 3.0,自己配置的，升级插件带来太多麻烦·想要改用 vue-cli

### What does the proposed API look like?
是否可以只是生成 html,其它的样式脚本热更新。

**Comment by sodatea** [comment]
不是很确定你说的只生成 HTML 文件是什么意思。但是 `devServer.proxy` 选项应该能满足你的需求
https://cli.vuejs.org/config/#devserver-proxy

**Comment by mzTeamMeatMan** [comment]
> 不是很确定你说的只生成 HTML 文件是什么意思。但是 `devServer.proxy` 选项应该能满足你的需求
> https://cli.vuejs.org/config/#devserver-proxy

@sodatea 
我并不是需要代理的意思，而是 html 模板是需要放在 java 端后端渲染，这个我没办法改变的
那么我需要 devServer 开发模式下，生成 html 模板在 java 端运行

**Comment by sodatea** [comment]
哦这个直接在 Java 端的模板里引入 app.js 就行了。你可以在开发模式查看一下源码，其实这个页面没做什么，就是放了一个 `<div id="app">` 和一个 `<script src="/app.js">`，自行在后端模板里引入也可以。

**Comment by mzTeamMeatMan** [comment]
> 哦这个直接在 Java 端的模板里引入 app.js 就行了。你可以在开发模式查看一下源码，其实这个页面没做什么，就是放了一个 `<div id="app">` 和一个 `<script src="/app.js">`，自行在后端模板里引入也可以。

噢好，我试试，谢谢
