### ISSUE TITLE
What's the Roadmap to version 2.8.1

### ISSUE THREAD

**Issue by neves** [vuejs/vue-cli#413]
It has been 2 months since the last version, 2.8.0.
Why it's taking so long? 41 commits so far.

**Comment by Toilal** [comment]
@posva any ETA ? I need to use complete callback, but it's still unreleased.

**Comment by posva** [comment]
We'll release it when we can...
If you need the latest version, you can always clone the repo and use it locally

**Comment by neves** [comment]
Maybe we can help. What's holding you?

**Comment by dflourusso** [comment]
I'm waiting for this release too.

**Comment by paliari** [comment]
How can I help? If the repo is usable, why not publish a 2.8.1 version with the current changes?

**Comment by Toilal** [comment]
holly ****, it's been released :) thanks !
