### ISSUE TITLE
web components problems

### ISSUE THREAD

**Issue by HappyColour** [vuejs/vue-cli#4134]
### Version
3.8.2

### Reproduction link
[none](none)

### Environment info
```
[11:21:00] danny :: localhost  ➜  ~/Danny/Niu_Home ‹feature-danny-WebComponents*› » yarn fuck
yarn run v1.15.2
warning package.json: "dependencies" has dependency "vue-template-compiler" with range "^2.5.22" that collides with a dependency in "devDependencies" of the same nam
e with version "^2.5.13"
$ vue-cli-service build --target wc --name Danny-Header ./components/common/header.vue
⠦  Building for production as web component...Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
⠧  Building for production as web component...
 ERROR  Failed to compile with 10 errors                                                                                                                  11:21:04 AM
These dependencies were not found:
* @/components/common/country.vue in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./no
de_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./components/common/header.vue?vue&type=script&lang=js&shadow
* assets/images/public/header/niuaero.svg in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"01ba1360-v
ue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue
-loader/lib??vue-loader-options!./components/common/header.vue?vue&type=template&id=06c2766c&scoped=true&shadow
* assets/images/public/header/store-m.svg in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"01ba1360-v
ue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue
-loader/lib??vue-loader-options!./components/common/header.vue?vue&type=template&id=06c2766c&scoped=true&shadow
* assets/images/public/header/store.svg in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"01ba1360-vue
-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-l
oader/lib??vue-loader-options!./components/common/header.vue?vue&type=template&id=06c2766c&scoped=true&shadow
* assets/images/public/header_remind.svg in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"01ba1360-vu
e-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-
loader/lib??vue-loader-options!./components/common/header.vue?vue&type=template&id=06c2766c&scoped=true&shadow
* assets/images/public/icon-close-b.svg in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"01ba1360-vue
-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-l
oader/lib??vue-loader-options!./components/common/header.vue?vue&type=template&id=06c2766c&scoped=true&shadow
* assets/images/public/icon-menu.svg in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"01ba1360-vue-lo
ader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-load
er/lib??vue-loader-options!./components/common/header.vue?vue&type=template&id=06c2766c&scoped=true&shadow
* assets/images/public/icon_menu_close.svg in ./node_modules/cache-loader/dist/cjs.js?{"cacheDirectory":"node_modules/.cache/vue-loader","cacheIdentifier":"01ba1360-
vue-loader-template"}!./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vu
e-loader/lib??vue-loader-options!./components/common/header.vue?vue&type=template&id=06c2766c&scoped=true&shadow
⠇  Building for production as web component...
 ERROR  Failed to compile with 10 errors 
```

### Steps to reproduce
Env: nuxtjs vue vue-cli
When i use the vue-cli make a Web Components, the ternimal will show the images not found & the other depend components not found , I don't know how to solve this problem, please help me to solve, beacause i want to make the components header.vue to share with other projects thx.

### What is expected?
componets header.vue could share with other projects

### What is actually happening?
images not found & other depend components not found

**Comment by HappyColour** [comment]
框架：Nuxtjs ssr
应用场景：想将header.vue打包成Web Components(header.vue里面引入了一个country.vue的组件)
在执行(yarn fuck)vue-cli-service build --target wc --name Danny-Header ./components/common/header.vue的时候报错(如上文所示)。希望得到大神的帮助~


**Comment by sodatea** [comment]
请按照 Issue Helper 的指示给出正确的重现（代码）和相关环境信息（请运行 `vue info`）。否则我们无法提供帮助。

**Comment by HappyColour** [comment]
> 请按照 Issue Helper 的指示给出正确的重现（代码）和相关环境信息（请运行 `vue info`）。否则我们无法提供帮助。

[16:03:47] danny :: localhost  ➜  ~/Danny/Niu_Home ‹feature-danny-WebComponents*› » vue info                                                                   130 ↵

Environment Info:


  System:
    OS: macOS High Sierra 10.13.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: Not Found
    Safari: 12.1.1
  npmPackages:
    @nuxt/vue-app:  2.3.4 
    @nuxt/vue-renderer:  2.3.4 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.8.0 
    @vue/babel-preset-jsx:  1.0.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.0.0 
    @vue/cli-overlay:  3.8.0 
    @vue/cli-plugin-babel: ^3.0.0-beta.10 => 3.8.0 
    @vue/cli-plugin-eslint: ^3.0.0-beta.10 => 3.8.0 
    @vue/cli-service: ^3.8.0 => 3.8.0 
    @vue/cli-shared-utils:  3.8.0 
    @vue/component-compiler-utils:  2.6.0 (2.5.0)
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    babel-plugin-transform-vue-jsx:  4.0.1 
    eslint-plugin-vue: ^4.0.0 => 4.7.1 
    vue:  2.5.22 
    vue-awesome-swiper: ^3.1.3 => 3.1.3 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.1 
    vue-lazyload: ^1.2.6 => 1.2.6 
    vue-loader:  15.7.0 (15.6.0)
    vue-meta:  1.5.8 
    vue-no-ssr:  1.1.1 
    vue-router:  3.0.2 
    vue-server-renderer: ^2.5.22 => 2.5.22 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.22 => 2.5.22 
    vue-template-es2015-compiler:  1.9.1 (1.8.2)
    vuex:  3.1.0 
  npmGlobalPackages:
    @vue/cli: 3.8.2

**Comment by sodatea** [comment]
抱歉，没有代码我们仍然无法判断你碰到了什么问题

**Comment by HappyColour** [comment]
NuxtJs引入图片的语法糖为('~assets/xxx.png')，@vue-cli不能找到图片。

**Comment by HappyColour** [comment]
> 抱歉，没有代码我们仍然无法判断你碰到了什么问题

NuxtJs引入图片的语法糖为('~assets/xxx.png')，@vue-cli不能找到图片。

**Comment by sodatea** [comment]
**请提供可以运行的代码**

**Comment by HappyColour** [comment]
> **请提供可以运行的代码**

[demo-nuxt-WebComponents.zip](https://github.com/vuejs/vue-cli/files/3284103/demo-nuxt-WebComponents.zip)

**Comment by HappyColour** [comment]
When i run yarn components , the images is not found.
repo : https://github.com/HappyColour/Monster or zip which is on this top of message

**Comment by sodatea** [comment]
`~` is for importing from `node_modules`. https://github.com/webpack-contrib/css-loader#url
You should use `../assets/logo.png`

**Comment by HappyColour** [comment]
It's very kind of you. Thx , Like this, I can fix it , but this is Nuxtjs rules(https://nuxtjs.org/guide/assets),I must use ~assets (without a slash) or the @ alias in url CSS references, i.e. background: url("~assets/banner.svg").So I think this is not the best way for nuxtjs framework.

**Comment by sodatea** [comment]
Then you may need to configure the alias yourself. After all, it's not a bug in Vue CLI.
