### ISSUE TITLE
Use VUE_APP_ to replace code fragment

### ISSUE THREAD

**Issue by mattwmj** [vuejs/vue-cli#4137]
### What problem does this feature solve?
I am using vue cli 3 to packing vue library and want to keep process.env.NODE_ENV code fragment in compiled common.js so that Apps depend on my library can replace the code fragment when building.
I put 

`VUE_APP_NODE_ENV=process.env.NODE_ENV `

in .env.production

I expect code in js like

`if (process.env.VUE_APP_NODE_ENV !== 'production')`

to be compiled to

`if (process.env.NODE_ENV !== 'production')`

so that Apps can replace it.

However it is compiled to

`if(true)`

I understand this is the current expected behavior, but can I use some escape string in .env value so as to replace variable as code fragment instead of string? Also disable compiler from evaluate the expression?

Or, is there any workaround or Am I doing anything wrong?

### What does the proposed API look like?
Use some escape string in .env value like

VUE_APP_NODE_ENV=\process.env.NODE_ENV

**Comment by LinusBorg** [comment]
Can you provide an example repository so we can be sure to reproduce exactly  what you try to do?

**Comment by mattwmj** [comment]
Let me try to explain here:

https://github.com/mattwmj/vue-cli-issues-4137/commit/1231b2818a48c937ae295d89517225f40d293461

I am trying to build a vue library with vue cli 3

`vue-cli-service build --target lib --name vue-cli-issue-4137 src/main.js`

Developers will use this library in their application. 

What I want to achieve is: when a developer's application runs in development mode, my library should output detail log and in production mode, not.

So in App.vue:

```
  mounted() {
    if (process.env.NODE_ENV !== 'production') {
      console.log('Development mode. Log some debug information.')
    } else {
      console.log('Production mode. Do nothing.')
    }
  }
```

With default configuration, above lines are compiled to:

```
  mounted: function mounted() {
    if (false) {} else {
      console.log('Production mode. Do nothing.');
    }
  }
```

I try to turn off webpack minimize in vue.config.js but not working: 

```
module.exports = {
  configureWebpack: {
    optimization: {
      minimize: false
    }
  }
}
```

**Comment by sodatea** [comment]
It's webpack `ConstPlugin` that did this.
https://github.com/webpack/webpack/blob/master/lib/ConstPlugin.js

Next time please try to isolate the issue, like, try in a simple webpack project first.
