### ISSUE TITLE
Vue-cli 3, when building the lib mode, how can I divide the package by component and load it on demand when using it?

### ISSUE THREAD

**Issue by minteliuwm** [vuejs/vue-cli#4145]
### What problem does this feature solve?
Vue-cli 3, when building the lib mode, how can I divide the package by component and load it on demand when using it?like element-ui.

### What does the proposed API look like?
None

**Comment by sodatea** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You may want to checkout https://github.com/chrisvfritz/hello-vue-components
