### ISSUE TITLE
项目无法创建和导入

### ISSUE THREAD

**Issue by zhaipeihua** [vuejs/vue-cli#4155]
### Version
3.8.4

### Environment info
```
mac OS
```

### Steps to reproduce
通过命令行vue ui进入导入项目页面，但是三个选项卡（项目，创建，导入）下面没有对应操作项

### What is expected?
能够正常创建项目，导入项目

### What is actually happening?
无法导入项目

**Comment by sodatea** [comment]
抱歉，没有理解你的意思……能提供一下截图或者录屏吗？（浏览器以及命令行的）控制台是否有报错？

**Comment by zhaipeihua** [comment]
/Users/zhaipeihua/Desktop/9C3C23F8-613D-434C-8613-136E14CC446D.png/Users/zhaipeihua/Desktop/0CB85101-BB06-442D-A3AB-6EAA8D19FC95.png/Users/zhaipeihua/Desktop/6BFCBCF4-F9FB-4AB8-846E-21D45280C21C.png

控制台没有报错，不管是新建项目还是导入项目下面都没有对应的操作项

**Comment by zhaipeihua** [comment]
新建跟导入下面都没有对应的操作项，都是一片空白，控制台并没有报错的内容
