### ISSUE TITLE
vue-cli3初始化一个工程，必须在dependencies中依赖core-js吗？为什么

### ISSUE THREAD

**Issue by cuivip** [vuejs/vue-cli#4156]
IMPORTANT: Please use the following link to create a new issue:

https://new-issue.vuejs.org/?repo=vuejs/vue-cli

If your issue was not created using the app above, it will be closed immediately.

中文用户请注意：
请使用上面的链接来创建新的 issue。如果不是用上述工具创建的 issue 会被自动关闭。

**Comment by sodatea** [comment]
如果用 Babel 的话，core-js 就必须被依赖。
https://babeljs.io/docs/en/babel-preset-env#usebuiltins
可以看到实际被编译出来的代码里都有对 core-js 的依赖。
