### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by LiuSuY** [vuejs/vue-cli#417]
vue init webpack demo

After the initialization is always the problem in the node version cannot solve this problem
In the following error

· Failed to download repo vuejs-templates/webpack: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80

Do you have friend have a good way to solve my share

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

----

You shouldn't use the port 80 for local development, it requires admin rights on Unix systems. Use the default 8080
