### ISSUE TITLE
linux vue-cli-service build 命令 segmentation fault

### ISSUE THREAD

**Issue by stephen7729** [vuejs/vue-cli#4170]
### Version
3.0.3

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Node and OS info
Node 10.13.0 / centos 7.2

### Steps to reproduce
不知道有没有大佬遇见过这样的问题：
jenkin构建报错，进入jenkins工作区的项目目录执行build命令报一样的错

![错误](https://user-images.githubusercontent.com/25659117/59815414-14a99880-934b-11e9-8e28-2b0b36d19771.png)

**Comment by stephen7729** [comment]
网上搜索出来的都是npm相关命令出现 `segmentation fault`，这里npm、node相关命令没有任何问题

**Comment by sodatea** [comment]
请提供一下复现代码（尽量提供**最小可复现**代码）。
我们没有办法靠截图和猜测来解决问题。

**Comment by stephen7729** [comment]
我也是想问一下有没有人使用vue-cli-service 命令在linux系统出现过`Segmentation fault`这样的异常，无关代码

**Comment by sodatea** [comment]
但是我们的 GitHub issues 只用于 Bug 反馈和特性请求，如果有使用上的问题建议到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问。

**Comment by stephen7729** [comment]
行的打扰了！
