### ISSUE TITLE
如何根据自定义环境变量获取完整的 webpack config 文件？ How to get webpack config by custom ENV value?

### ISSUE THREAD

**Issue by PyMonar** [vuejs/vue-cli#4173]
### What problem does this feature solve?
为了实现服务器端渲染，我在 vue.config.js 中针对不同 target 使用了自定义环境变量 process.env.WEBPACK_TARGET === 'node' 。为了实现 HMR，在 server.js 中需要获取到 webpack config 文件。但是通过官方文档只能通过 const webpackConfig = require('@vue/cli-service/webpack.config') 的方式进行获取，无法传入自定义环境变量，返回的永远是客户端入口的 webpack config。如何能够根据不同的环境变量来获取 resolved webpack config 呢？

### What does the proposed API look like?
暂无 API

**Comment by PyMonar** [comment]
const webpackConfig = require('@vue/cli-service/webpack.config') 
How to get webpack config by custom ENV value?

**Comment by sodatea** [comment]
```js
process.env.NODE_ENV = 'production'
const config = require('@vue/cli-service/webpack.config')
```

**Comment by PyMonar** [comment]
> ```js
> process.env.NODE_ENV = 'production'
> const config = require('@vue/cli-service/webpack.config')
> ```

process.env.WEBPACK_TARGET = 'node'
let config = require('@vue/cli-service/webpack.config')
console.log(config)
process.env.WEBPACK_TARGET = 'web'
let config2 = require('@vue/cli-service/webpack.config')
console.log(config2)

config and config2 are same.

**Comment by PyMonar** [comment]
@sodatea

**Comment by sodatea** [comment]
请设置 `NODE_ENV` 变量。
