### ISSUE TITLE
After start vue-cli-3 tutorial  project 98% after emitting CopyPlugin

### ISSUE THREAD

**Issue by skortabeast** [vuejs/vue-cli#4174]
### Version
3.8.4

### Environment info
```
 System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: ^3.8.0 => 3.8.0
    @vue/cli-plugin-eslint: ^3.8.0 => 3.8.0
    @vue/cli-service: ^3.8.0 => 3.8.4
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.2 (4.7.1)
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0 (2.0.3)
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Download Nodejs version 10.16.0 , install, npm install -g @vue/cli ,  vue create hello-world ,  npm run serve

### What is expected?
project is compiled

### What is actually happening?
INFO  Starting development server...
 98% after emitting CopyPlugin

**Comment by sodatea** [comment]
Please provide an actual reproduction repo.

**Comment by skortabeast** [comment]
@sodatea https://github.com/skortabeast/vue-cli-3-rep

**Comment by sodatea** [comment]
I'm sorry but I can't reproduce this issue on my machine.
I guess this may be related to your filesystem, file permissions, network environment, terminal, etc… But not likely Vue CLI itself.

**Comment by skortabeast** [comment]
@sodatea yes man,  I try run on virtual machine and everything is ok, sorry for for request

**Comment by sam-araiza** [comment]
I'm getting the same ```98% after emitting CopyPlugin                                                       
 ERROR  Failed to compile with 976 errors                                                 6:00:26 PM```

**Comment by eduardosada** [comment]
Me too:

```98% after emitting CopyPlugin```

and that's it. No response.

**Comment by DrMarkEy** [comment]
I experienced the same issue when I tried to use

`import {someFunction} from '';`

, i.e. I forgot to specify the package to import from.

**Comment by BartusZak** [comment]
Any ideas?

![error](https://user-images.githubusercontent.com/16143176/66468151-feecea00-ea85-11e9-951d-4d0b3d648741.jpg)

**Comment by tapriandi** [comment]
I have the same problem, but after debugging I found a mistake from my router file.
the problem is: "forget to submit path and component"
hope this can help you

**Comment by ssabalak** [comment]
I had such a problem. Somewhere in the code I left an empty import and forgot. Code: 

> import {} from ''

Hope this can help you

**Comment by vuchan** [comment]
i got the same problem like @ssabalak and @DrMarkEy , search those codes in your project folder:
```
import ''
```
or
```
import {} from ''
```

Hope this can help you

**Comment by Edwing123** [comment]
I was getting this problem too, but for me it was defining a route in the routes (vue-router) but without creating the view component, it just hung out.

**Comment by walter-la** [comment]
I got the same error message, but I resolved it.
In my case, I just change different branch. after that, I change back the original branch, then it doesn't work when I run "npm run serve".

**The problem is all import paths are case sensitive!**
So when I change to the old branch, it changes my directory name to uppercase letters( before I use uppercase directory name). But the latest branch I already changed to lowercase letters for directory  name. 

For example, if your import like below:
`component: () => import('@/views/test/Test'),`
then you should check the directory's name and file's name must be the same uppercase letters and lowercase letters.

**Comment by Abhishek325** [comment]
I had this problem because of an empty import (`component: () => import("")`)  in my router.js as I was importing it with `import router from "./router/index";` in main.js

**Comment by rodrigoaraujolima92** [comment]
> Tive o mesmo problema quando tentei usar
> 
> `import {someFunction} from '';`
> 
> , ou seja, eu esqueci de especificar o pacote para importar.

Very Very Tnks !

**Comment by edsel77** [comment]
> I experienced the same issue when I tried to use
> 
> `import {someFunction} from '';`
> 
> , i.e. I forgot to specify the package to import from.

thanks man haha

**Comment by alidadaashi** [comment]
I think you forget to copy the files that starts with '.' like: .env or .eslint 
press the cmnd + shift + . to show this hidden files and copy them.

**Comment by Nvhub** [comment]
I have same problem stuck in 98%.

98% after emitting CopyPlugin

In my case, I recheck again my code, and I found my import path is invalid, something like :

`import { myComponent } from ```

**After fix the code, It works again.**

**Comment by arrowing** [comment]
There was same error for me, the problem is that I lost my vue.config.js file.

**Comment by YoungHearts** [comment]
我也遇到了同样的问题，已经排除了`import`、`require`或者`from`引用为空的状况，我已经没有办法了

**Comment by arrowing** [comment]
@YoungHearts  看看是不是vue.config.js丢失了，我是误删了。

**Comment by rodrigoaraujolima92trulogic** [comment]
@Nvhub 

> I have same problem stuck in 98%.
> 
> 98% after emitting CopyPlugin
> 
> In my case, I recheck again my code, and I found my import path is invalid, something like :
> 
> `import { myComponent } from ''`
> 
> **After fix the code, It works again.**

**very good!** 

- [ ]

**Comment by hhm-lxb** [comment]
maybe your import path is invalid like:
```js
import { getPDF } from ''
```

**Comment by joobei** [comment]
I had the same problem. Turns out one of my imports was
`import { packageName} from ''`

**Comment by xieerduos** [comment]
> ### Version
> 3.8.4
> 
> ### Environment info
> ```
>  System:
>     OS: Windows 10
>     CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
>   Binaries:
>     Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
>     npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
>   Browsers:
>     Edge: 42.17134.1.0
>   npmPackages:
>     @vue/babel-helper-vue-jsx-merge-props:  1.0.0
>     @vue/babel-plugin-transform-vue-jsx:  1.0.0
>     @vue/babel-preset-app:  3.8.0
>     @vue/babel-preset-jsx:  1.0.0
>     @vue/babel-sugar-functional-vue:  1.0.0
>     @vue/babel-sugar-inject-h:  1.0.0
>     @vue/babel-sugar-v-model:  1.0.0
>     @vue/babel-sugar-v-on:  1.0.0
>     @vue/cli-overlay:  3.8.0
>     @vue/cli-plugin-babel: ^3.8.0 => 3.8.0
>     @vue/cli-plugin-eslint: ^3.8.0 => 3.8.0
>     @vue/cli-service: ^3.8.0 => 3.8.4
>     @vue/cli-shared-utils:  3.8.0
>     @vue/component-compiler-utils:  2.6.0
>     @vue/preload-webpack-plugin:  1.1.0
>     @vue/web-component-wrapper:  1.2.0
>     eslint-plugin-vue: ^5.0.0 => 5.2.2 (4.7.1)
>     vue: ^2.6.10 => 2.6.10
>     vue-eslint-parser:  5.0.0 (2.0.3)
>     vue-hot-reload-api:  2.3.3
>     vue-loader:  15.7.0
>     vue-style-loader:  4.1.2
>     vue-template-compiler: ^2.6.10 => 2.6.10
>     vue-template-es2015-compiler:  1.9.1
>   npmGlobalPackages:
>     @vue/cli: Not Found
> ```
> 
> ### Steps to reproduce
> Download Nodejs version 10.16.0 , install, npm install -g @vue/cli , vue create hello-world , npm run serve
> 
> ### What is expected?
> project is compiled
> 
> ### What is actually happening?
> INFO Starting development server...
> 98% after emitting CopyPlugin

```js

require(‘’)
```

**Comment by hzh-test** [comment]
I also encountered this problem.
Maybe the problem is "vue.config.js" file setting.
You can see this article 
[[entry] in the CLI command is defined as the entry file (default: src/main.js or src/main.ts in TypeScript project), not an additional entry file. If you overwrite the entry in the CLI, then the entries from config.pages are no longer considered, which may cause an error.](https://cli.vuejs.org/guide/cli-service.html#vue-cli-service-serve)
So remove ***module.exports***, it maybe work, and I was successed.
After that, you can remove less code to find the district error place.

**Comment by justfeizai** [comment]
This problem will occur as long as the path of import is written wrong. I don't know what happened, it was fine before

**Comment by justfeizai** [comment]
> This problem will occur as long as the path of import is written wrong. I don't know what happened, it was fine before

Delete the code, re-pull the code, reinstall vscode, problem solved
