### ISSUE TITLE
vue init stuck at project description when running vue init webpack <name>

### ISSUE THREAD

**Issue by mboekhold** [vuejs/vue-cli#4177]
### Version
3.8.4

### Environment info
```
System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: Not Found
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 67.0.3
  npmGlobalPackages:
    @vue/cli: 3.8.4
```

### Steps to reproduce
run vue init webpack <name>

### What is expected?
Vue scaffold is created

### What is actually happening?
Vue hangs on project description

---
I am aware that this was an issue with node v8, but I am getting this issue with the latest node version

Stuck here: 
`? Project name `
`? Project description (A Vue.js project) `

**Comment by sodatea** [comment]
https://github.com/SBoudrias/Inquirer.js/issues/811
Upstream bug in inquirer.

**Comment by mboekhold** [comment]
I'd like to add that I  discovered that the webpack is deprecated introducing vue cli-3, not sure if this causes the problem though.

**Comment by slhck** [comment]
Same issue here.

Could someone propose a PR that locks `inquirer` at a lower version until this is resolved?
Apparently the same was done here to temporarily fix it: https://github.com/umijs/create-umi/pull/70

**Comment by asdico** [comment]
Same issue.

I'm working in Mac OSX. 🤷🏻‍♂️

**Comment by eryueweiyu** [comment]
Same issue.
working in win10.

**Comment by slhck** [comment]
Please don't post "same issue" comments, as the actual upstream issue has been identified already. Just click the +1 button if you want to express support.

**Comment by aa1143** [comment]
> Same issue.
> 
> I'm working in Mac OSX. 🤷🏻‍♂️

the same question!

**Comment by xLivan** [comment]
For those, who is looking for temporary fix of `vue init` command.
PowerShell (Windows):
```powershell
cd "$(Split-Path $(whereis vue)[0] -Parent)\node_modules\@vue\cli-init"
npm i inquirer@~6.3.1
```
bash:
```bash
cd "$(dirname $(which vue))/node_modules/@vue/cli-init"
npm i inquirer@~6.3.1
```

**Comment by AdenSTL** [comment]
LInux user :Ubuntu 18.04LTS
@xLivan 
I ran command: 

> cd "$(vuetest $(2.9.6))/node_modules/@vue/cli-init"

vuestest is the name of my directory and vue version is 2.9.6 ,node version 8.0.0.

Output is:

> 2.9.6: command not found
> vuetest: command not found
> bash: cd: /node_modules/@vue/cli-init: No such file or directory

Before this I have ran 

> sudo npm install 
>sudo npm install -g @vue/cli

Link to my package.json
[https://github.com/AdenSTL/stackoverflow-errors/blob/master/package.json]()

Please help.
Thanks.

**Comment by sodatea** [comment]
Fixed in inquirer@6.4.1
Now please try to clean your npm/yarn cache and reinstall `@vue/cli` `@vue/cli-init`

**Comment by xLivan** [comment]
@AdenSTL, sorry, didn't saw your question earlier. But problem already fixed, so just do `npm i -g @vue/cli @vue/cli-init`.
Regarding question, you should run commands exactly as I provided in previous message. And, I think, you are getting error
> No such file or directory

because you're using yarn and it has different path for global node_modules.

**Comment by NazarLesyuk** [comment]
Hi @xLivan I put in PowerShell this command
`cd "$(Split-Path $(whereis vue)[0] -Parent)\node_modules\@vue\cli-init"`
and receive error http://prntscr.com/o4ywht . 

Short text about error:

> whereis : The term 'whereis' is not recognized as the name of a cmdlet,

Also when I replace **whereis** to **which** error is not disappear

Can you provide more informative instruction to resolve this issue?
thank you a lot!

**Comment by NazarLesyuk** [comment]
@xLivan I resolve it by making update npm(to 6.9.0) and node (10.16.0).
Thank you a lot!

**Comment by trd-renato** [comment]
Im still stuck at project description

**Comment by NazarLesyuk** [comment]
> Im still stuck at project description

What I did:
1) update npm , nodejs
2)  installed `npm install -g @vue/cli @vue/cli-init` - it is latest version instaled
3) try again `vue webpack-simple vue-project`

it works for me

**Comment by trd-renato** [comment]
> > Im still stuck at project description
> 
> What I did:
> 
> 1. update npm , nodejs
> 2. installed `npm install -g @vue/cli @vue/cli-init` - it is latest version instaled
> 3. try again `vue webpack-simple vue-project`
> 
> it works for me

Does this also work with nativescript-vue?

BTW thank you for your reply

**Comment by NazarLesyuk** [comment]
> > > Im still stuck at project description
> > 
> > 
> > What I did:
> > 
> > 1. update npm , nodejs
> > 2. installed `npm install -g @vue/cli @vue/cli-init` - it is latest version instaled
> > 3. try again `vue webpack-simple vue-project`
> > 
> > it works for me
> 
> Does this also work with nativescript-vue?
> 
> BTW thank you for your reply

I don't know about `nativescript-vue`, because I develop on vue.js (web only)

**Comment by geekhybrid** [comment]
Update vue 

Run with npm install npm@latest -g
