### ISSUE TITLE
Pug Files not in the Dev server watch list？

### ISSUE THREAD

**Issue by evolutionjay** [vuejs/vue-cli#418]
# CLI version:  2.8.0

# 操作步骤

```
vue init webpack demo
cd demo
npm i 
npm i -D pug pug-loader less less-loader
```
# Add files:

App.js
App.pug
App.less
App.vue

# in `App.vue`
```html

<template lang="pug">
  include ./App.pug
</template>
<script src="./App.js"></script>
<style lang="less" src="./App.less">

```

# ⚠️问题

```bash
npm run dev
```

and then in `localhost:8080/`

when i change  or save the  `App.pug` file ， the webpack server hot reload not work

`pug` file not in watch file list？ 

***

Sorry, My English is poor , I am try my best to let you know what I say.....

**Comment by LinusBorg** [comment]
pug file not in watch file list？

```pug
  include ./App.pug
```

This include is done by pug, not webpack, so webpack isn't aware of it. That'S why hot reloading can't work like that.

Try this:
```html
<template lang="pug" src="./App.pug">
</template>
```
