### ISSUE TITLE
Doc inhance of how to config Multipage mode on server

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vue-cli#4182]
### What problem does this feature solve?
The official doc only mentions how to config a single page website. But users like me don't know how to write httpd.conf on Apache and can't find help information on both Apache/NGINX and Vue docs, so on the forum of both sides.

I wonder whether an example configuartion can be put on the vue-cli(or vue-router) docs.
Thanks!

### What does the proposed API look like?
Doc inhancement

**Comment by GodofHope** [comment]
Could you tell me when can the docs been update?

**Comment by GodofHope** [comment]
I had a discussion with my friends, and I figued out how to config today. How can I help? Make a comment in this issue?

**Comment by sodatea** [comment]
Send a pull request for this file https://github.com/vuejs/vue-cli/blob/dev/docs/guide/deployment.md#docker-nginx, adding guides on multipage configurations.

**Comment by GodofHope** [comment]
OK👌 I'll try, since I am a Chinese, I may make grammar mistakes.🤣
