### ISSUE TITLE
Can't change preset when creating into existing folder

### ISSUE THREAD

**Issue by softwareguy74** [vuejs/vue-cli#4186]
It seems that when using `vue create .` or `vue create <existing folder>` when you get the prompt to "Please pick a preset: (Use arrow keys)", you are unable to change the selection with the arrow keys.  I have confirmed I AM able to do this when creating into a new folder.

**Comment by sodatea** [comment]
Duplicate of https://github.com/vuejs/vue-cli/issues/4179
Please clean your npm/yarn cache and reinstall @vue/cli
