### ISSUE TITLE
Hot Reload doesn't work in linux

### ISSUE THREAD

**Issue by lesinlor** [vuejs/vue-cli#419]
I run `init` `npm i` and `npm run dev` ,the hot reload doesn't work even i reload the website.Only i reload the server that will reload what i change in the code.
After i changed some codes in  build/dev-server.js,hot reload run(line 26):

```javascript
var devMiddleware = require('webpack-dev-middleware')(compiler, {
  publicPath: webpackConfig.output.publicPath,
  quiet: false,
  stats: {
    colors: true,
    chunks: false
  },
  watchOptions: { //Add Polling
    aggregateTimeout: 300,
    poll: 1000
  }
})
```
thanks

env:
system:  ubuntu-14.04-amd64
node: v7.2.1/v.6.9.1
vue-cli: 2.5.1/2.8.1

**Comment by Toilal** [comment]
I think you should post this on the webpack template issue tracker => https://github.com/vuejs-templates/webpack/issues
