### ISSUE TITLE
 Error loading saved preferences: ~/.vuerc may be corrupted or have syntax errors. Please fix/delete it and re-run vue-cli in manual mode. (Unexpected token   in JSON at position 0)

### ISSUE THREAD

**Issue by az73** [vuejs/vue-cli#4191]
### Version
3.8.4

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue-cli](https://new-issue.vuejs.org/?repo=vuejs/vue-cli)

### Environment info
```
win 10
```

### Steps to reproduce
https://new-issue.vuejs.org/?repo=vuejs/vue-cli

### What is expected?
i want only create new project 

### What is actually happening?
 Error loading saved preferences: ~/.vuerc may be corrupted or have syntax errors. Please fix/delete it and re-run vue-cli in manual mode.
(Unexpected token   in JSON at position 0)

**Comment by NataliaTepluhina** [comment]
@az73 as a workaround, have you tried to delete `.vuerc`?  Happened to me on MacOS, removing the file helped.

**Comment by az73** [comment]
Hi Natalia,
thank you for helping me, where I find this .vuerc?


beste,
ahmed

**Comment by NataliaTepluhina** [comment]
@az73 usually it's located in your user folder (i.e. `C:/Users/<username>`).
