### ISSUE TITLE
【环境变量和模式】导致按需加载失效

### ISSUE THREAD

**Issue by FourLeafClover** [vuejs/vue-cli#4195]
vue-cli里面使用了环境变量配置。
![image](https://user-images.githubusercontent.com/8449788/60064173-28ca0d00-9732-11e9-84a8-2c3de035f993.png)
1.router配置使用的是 ()=>import('xxxx.vue')引入页面组件。最后打包的时候只有一个app.js。页面对JS拆分。
2.如果替换成resolve=>require(['xxxx.vue'],resolve),打包后是会拆分成多个js的。
3.如果不使用.env.xxxx 来区分不同环境配置。使用()=>import('xxx.vue')最后打包后js也是会被拆分的。

PS:  ()=>import 和  require 不都是按需加载的两种方式吗？ 而且平时都更倾向于使用()=>import。 是因为vue-cli内部做了什么特殊处理吗。

**Comment by inewjean** [comment]
> vue-cli里面使用了环境变量配置。 ![image](https://user-images.githubusercontent.com/8449788/60064173-28ca0d00-9732-11e9-84a8-2c3de035f993.png) 1.router配置使用的是 ()=>import('xxxx.vue')引入页面组件。最后打包的时候只有一个app.js。页面对JS拆分。 2.如果替换成resolve=>require(['xxxx.vue'],resolve),打包后是会拆分成多个js的。 3.如果不使用.env.xxxx 来区分不同环境配置。使用()=>import('xxx.vue')最后打包后js也是会被拆分的。
> 
> PS: ()=>import 和 require 不都是按需加载的两种方式吗？ 而且平时都更倾向于使用()=>import。 是因为vue-cli内部做了什么特殊处理吗。

webpack打包有两种模式，production 代码被压缩，development 代码未做压缩。
使用 `vue-cli-service build --mode testing` 命令进行构建时，
若环境变量配置文件 `env.testing` 中未定义 NODE_ENV 的值。会认为 NODE_ENV 值为 `testing` 。webpack会以 development 模式进行打包，代码文件不会被压缩和分割。
若在环境变量配置文件 `env.testing` 中定义 NODE_ENV 的值为 production，webpack会以 production 模式进行打包，代码文件会被压缩和分割。
