### ISSUE TITLE
not work on windows?

### ISSUE THREAD

**Issue by fishenal** [vuejs/vue-cli#42]
when npm install ,there are some errors! seems from
`npm ERR! git clone --template=C:\Users\yudonghan\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror http://githu
b.com/ianstormtaylor/to-camel-case C:\Users\yudonghan\AppData\Roaming\npm-cache\_git-remotes\git-http-github-com-ianstor
mtaylor-to-camel-case-0-2-1-075cfbaf204dae5d923dd8439e3cfb10: fatal: unable to access 'http://github.com/ianstormtaylor/
to-camel-case/': Empty reply from server`

what ever, no vue command:
![image](https://cloud.githubusercontent.com/assets/1457884/13134586/0f7a8518-d643-11e5-9de4-755a6251338b.png)

windows powerShell
npm 3.3.12
node v5.1.0
git version 2.7.0.windows.1

**Comment by JasinYip** [comment]
Try `git bash` in Windows

**Comment by yyx990803** [comment]
The github dependency has been removed in the latest deps, try re-install.

**Comment by fishenal** [comment]
working now, thank you!

**Comment by siempay** [comment]
I just installed vue-cli on bash on windows, after it completed everything. I tried vue init webpack myproject  but I got nothing , no errors no folder created!! 


`/usr/local/bin/vue -> /usr/local/lib/node_modules/vue-cli/bin/vue
/usr/local/bin/vue-init -> /usr/local/lib/node_modules/vue-cli/bin/vue-init
/usr/local/bin/vue-build -> /usr/local/lib/node_modules/vue-cli/bin/vue-build
/usr/local/bin/vue-list -> /usr/local/lib/node_modules/vue-cli/bin/vue-list`

after npm installed it I got this; this means that the command is there but why it is not firing?
