### ISSUE TITLE
SASS module doesn't work 

### ISSUE THREAD

**Issue by grafikri** [vuejs/vue-cli#4200]
### Version
3.8.4

### Reproduction link
[https://github.com/grafikri/Vue-Instragram](https://github.com/grafikri/Vue-Instragram)

### Environment info
```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.4
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
  Binaries:
    Node: 8.11.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: Not Found
    Safari: 11.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.8.0 
    @vue/babel-preset-jsx:  1.0.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.0.0 
    @vue/cli-overlay:  3.8.0 
    @vue/cli-plugin-babel: ^3.8.0 => 3.8.0 
    @vue/cli-plugin-unit-jest: ^3.8.0 => 3.8.0 
    @vue/cli-service: ^3.8.0 => 3.8.4 
    @vue/cli-shared-utils:  3.8.0 
    @vue/component-compiler-utils:  2.6.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29 
    @vue/web-component-wrapper:  1.2.0 
    jest-serializer-vue:  2.0.2 
    vue: ^2.6.10 => 2.6.10 
    vue-hot-reload-api:  2.3.3 
    vue-jest:  3.0.4 
    vue-loader:  15.7.0 
    vue-router: ^3.0.3 => 3.0.6 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.1.1 
  npmGlobalPackages:
    @vue/cli: 3.8.4

```

### Steps to reproduce
npm install
npm run serve

### What is expected?
I want to use SASS variables in Vue components as JS variables . That as known CSS modules. Also, I used vue-cli service and added  pre-processors feature, When I created Vue App.

### What is actually happening?
I added this code (I shared link below) to vue.config.js webpackConfigure section,  but It doesn't work. I'm getting this error: Invalid CSS after "...load the styles": expected 1 selector or at-rule, was "var content = requi"

https://vue-loader.vuejs.org/guide/css-modules.html#using-with-pre-processors

Also I want to import my 'src/assets/style/_colors.sass' file into any .vue component file. When I imported sass file for module I'm getting empty json file

import style from 'src/assets/style/_colors.sass'

console.log(style) -> style is empty json

---
/featureSassModule is my branch where occured error on project

Thank you for your support

**Comment by sodatea** [comment]
1. In Vue CLI you don't need to manually configure webpack for CSS Modules support. Just add `{ css: { modules: true }` in `vue.config.js`. See https://cli.vuejs.org/guide/css.html#css-modules

2. CSS modules won't automatically export all variables from the stylesheet (IIRC, it only exports selectors by default). You need to explicitly export them. See https://github.com/css-modules/css-modules/blob/master/docs/values-variables.md
  
    And it seems not able to export variables starting with `$`, you'll need to declare a new name for the sass variable, i.e:

    ```scss
    $primary-color: blue // this is a sass variable
    @value primaryColor: #{$primary-color}	// this is the exported css module variable
    ```

**Comment by grafikri** [comment]
It's working, thank you so much.
