### ISSUE TITLE
如何向 html-webpack-plugin 插件添加新属性？

### ISSUE THREAD

**Issue by jiankafei** [vuejs/vue-cli#4213]
### What problem does this feature solve?
根据vue-cli 的介绍，cli 会自动把环境变量插入到模板里，但是现在有个需求，我需要向 index.html 插入新的值，就需要添加 html-webpack-plugin ，但这样一来，cli 所提供的 环境变量差值就失效了，报错：无法找到 BASE_URL 。有没有办法实现添加的 html-webpack-plugin 不是替换原有的插件，而是merge两个插件。

### What does the proposed API look like?
新增 configureHtmlWebpackPlugin 用于向该插件添加新的属性

**Comment by jiankafei** [comment]
vue-cli 坑好多啊

**Comment by sodatea** [comment]
```js
module.exports = {
  chainWebpack: (config) => {
    config.plugin('html').tap((args) => {
      // modify args
      return args;
    });
  }
}
```
