### ISSUE TITLE
Components transition `enter` function not called when using Vue version 2.6.10 

### ISSUE THREAD

**Issue by katerlouis** [vuejs/vue-cli#4214]
### Version
3.8.4

### Reproduction link
[https://github.com/katerlouis/vue-2610-bug](https://github.com/katerlouis/vue-2610-bug)

### Environment info
```
 System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    Yarn: Not Found
    npm: 6.9.2 - ~/.nvm/versions/node/v11.15.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.4
    Safari: 12.1.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: ^3.8.0 => 3.8.0
    @vue/cli-plugin-eslint: ^3.8.0 => 3.8.0
    @vue/cli-service: ^3.8.4 => 3.8.4
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue:  undefined (4.7.1)
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: 3.8.4
```

### Steps to reproduce
serve or build the app
and press the toggle button

### What is expected?
HelloWorld component should call `enter` function

### What is actually happening?
HelloWorld component doesn't call `enter` function

---
`enter` of the transition directly inside `App.vue` (the logo img) gets called though, which is odd.
With vue v2.5.17 it works as expected (haven't used any other vue version since)

**Comment by LinusBorg** [comment]
Hi @katerlouis 

If it's dependent on the Vue version it seems it's an issue with Vue itself, not Vue CLI.

Can you please reopen the issue in that repo? Thanks.

**Comment by zrh122** [comment]
mybe [this](https://github.com/vuejs/vue/pull/9668#issuecomment-472085917) can help you. @katerlouis

**Comment by katerlouis** [comment]
Reopened the issue here:
https://github.com/vuejs/vue/issues/10227

@zrh122 I decided to keep using 2.5.17 until this is fixed.
