### ISSUE TITLE
vue build src/main.js --prod cant resolve @/components/Hello

### ISSUE THREAD

**Issue by steffanhalv** [vuejs/vue-cli#422]
vue build src/main.js --prod doesnt build because it cant resolve the include path '@/component/Hello'

Using npm 4, latest vue-cli and it happens on fresh install of vue init webpack my-project

npm run dev works just fine

**Comment by Sghazzawi** [comment]
I am experiencing the same issue, any update on this?

**Comment by mcescalante** [comment]
I am running the latest `vue-cli`and vue-loader and am seeing this issue when I run the command `vue build src/main.js --prod`:

```
ERROR in ./src/router/index.js
Module not found: Error: Can't resolve '@/components/User' in 'path/to/file/here'
 @ ./src/router/index.js 4:0-37
 @ ./src/main.js
 @ multi src/main.js

ERROR in ./src/router/index.js
Module not found: Error: Can't resolve '@/components/Hello' in 'path/to/file/here'
 @ ./src/router/index.js 3:0-39
 @ ./src/main.js
 @ multi src/main.js
```
