### ISSUE TITLE
打包命令后代码没有压缩

### ISSUE THREAD

**Issue by MBearo** [vuejs/vue-cli#4226]
### Version
3.8.0

### Environment info
```
node 10.14.2
os centos 7
```

### Steps to reproduce
docker环境内
起了一个node服务，用户通过调用api，node用exec运行npm run build

### What is expected?
DONE  Compiled successfully in 4337ms3:50:15 AM

  File                 Size                       Gzipped

  fe2d80f43/main.js    4028.38 KiB                877.17 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The fe2d80f43 directory is ready to be deployed.

### What is actually happening?

  File                                      Size             Gzipped

  fe2d80f43/js/chunk-vendors.9e75aeb4.js    281.50 KiB       85.23 KiB
  fe2d80f43/js/main.8485403b.js             27.78 KiB        8.67 KiB
  fe2d80f43/css/main.afe7245d.css           3.86 KiB         1.59 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The fe2d80f43 directory is ready to be deployed.

---
没有定位问题，希望可以给点思路

**Comment by sodatea** [comment]
从输出的消息来看不是已经压缩了吗？

另外，请提供复现代码。

**Comment by MBearo** [comment]
感谢，是因为子进程环境变量的问题
