### ISSUE TITLE
vue cli3 打包后有什么办法不生成index.html文件

### ISSUE THREAD

**Issue by ChinaMars** [vuejs/vue-cli#4228]
### What problem does this feature solve?
我的index.html文件不需要架手框架生成的，我只需要js文件，绑定在某个模块上面

### What does the proposed API look like?
      config.plugins.delete('html-index')
      config.plugins.delete('preload-index')
      config.plugins.delete('prefetch-index')

使用了这个方法，还是没有删除打包后的index.html

**Comment by sodatea** [comment]
再加一句 `config.plugins.delete('copy')`

**Comment by yandeqiang** [comment]
hi， 咨询下。 如果我是多页应用， 我不希望我打包出所有的 html 。 如果做到。
