### ISSUE TITLE
Vue Cli 更新3.9.1 后,启动异常

### ISSUE THREAD

**Issue by crper** [vuejs/vue-cli#4236]
### Version
3.9.1

### Environment info
```
 System:
      OS: macOS 10.14.5
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.5.0 - /usr/local/bin/node
      Yarn: 1.17.0 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
```

### Steps to reproduce
用yarn全局安装的，3.9及以前都是正常的（包括更新）

今天更新后就报异常了，也尝试过卸载重装

### What is expected?
修正问题

### What is actually happening?
必现

![image](https://user-images.githubusercontent.com/8272877/60644595-2c177400-9e69-11e9-958f-5e49c374125c.png)

**Comment by sodatea** [comment]
`yarn global add vue` 试试。
我这边无法复现，应该是你某个全局安装的包引入了旧版本的依赖，破坏了整个依赖树（可能是 yarn 的去重机制出了问题）。全局再安装一个新版本的 vue 就好了。

**Comment by crper** [comment]
@sodatea  全局装了vue后修正了这个问题，那有可能是你说的其他依赖了。
