### ISSUE TITLE
Vue CLI should use parcel instead of webpack

### ISSUE THREAD

**Issue by turbobuilt** [vuejs/vue-cli#4240]
### What problem does this feature solve?
Webpack is complex and slow, Parcel is simple and fast.  Parcel seems much more aligned with the Vue.js philosophy.  I'm using it right now without Vue cli.  But for the sake of newcomers, I suggest we give them the best in official tooling.

### What does the proposed API look like?
It would be the same as the current api.

**Comment by Akryum** [comment]
I think Webpack is the most mature bundler available, and it's getting faster and simpler to use every release.

**Comment by LinusBorg** [comment]
If you can come up with a prototype that supports all the things vue-cli-service does, go ahead and publish it as vue-cli-service-parcel or something for us to test out 

If it's not possible to do all of these things with parcel (which I would assume), we stick with webpack for now.

**Comment by Akryum** [comment]
I also see on the Internet some benchmarks showing webpack as being faster than parcel 🤷‍♂️

**Comment by turbobuilt** [comment]
Hm, looks like they are actually working on this already:
https://github.com/parcel-bundler/parcel/issues/2574
