### ISSUE TITLE
Give hint when the value in 'dev.env.js' does not be enclosed by a double quotes and  a single quotes

### ISSUE THREAD

**Issue by weiziyoung** [vuejs/vue-cli#4243]
### What problem does this feature solve?
The config file of 'dev.env.js' is so weird!!!!
I enclosed a double quotes on my value,  like that:
```
'use strict'
const merge = require('webpack-merge')
const prodEnv = require('./prod.env')

module.exports = merge(prodEnv, {
  NODE_ENV: '"development"',
  SERVER: "http://localhost:8000"
})
```

and want to access the 'process.env'. But it told me my syntax is error. 
I spent one day on finding the error but still in vain.
Finally, I found I missed a single quotes which should be enclosed outside the double quotes.
I know it's my mistake.
But that is so weird!!Why I need to put an extra quote outside an exsiting quote????
And it even can't give me any clues to fix it.
Please add some hints to inform developers it should be enclosed by an extra quotes please!!!

### What does the proposed API look like?
I have mentioned it above.

**Comment by sodatea** [comment]
It's a webpack caveat anyway. https://webpack.js.org/plugins/define-plugin/#root

And that's why we recommend using a `.env` file https://cli.vuejs.org/guide/mode-and-env.html#environment-variables

**Comment by Akryum** [comment]
@weiziyoung Webpack will replace the content of the string value as code. So in your code, you want `const url = "http://localhost:8000"`, not `const url = http://localhost:8000`.
