### ISSUE TITLE
 runtimeCompiler causes rewriting of some dependencies in chunk-vendors to use ES6 syntax

### ISSUE THREAD

**Issue by kevteljeur** [vuejs/vue-cli#4249]
### Version
3.9.0

### Environment info
```
System:
    OS: macOS 10.14
  Binaries:
    Node: 10.15.2 - /opt/local/bin/node
    Yarn: 1.16.0 - /opt/local/bin/yarn
    npm: 6.9.2 - /opt/local/bin/npm
  Browsers:
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.9.0 
    @vue/babel-preset-jsx:  1.0.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.0.0 
    @vue/cli-overlay:  3.9.0 
    @vue/cli-plugin-babel: ^3.9.0 => 3.9.0 
    @vue/cli-plugin-eslint: ^3.9.0 => 3.9.1 
    @vue/cli-plugin-unit-mocha: ^3.9.0 => 3.9.0 
    @vue/cli-service: ^3.9.0 => 3.9.0 
    @vue/cli-shared-utils:  3.9.0 
    @vue/component-compiler-utils:  2.6.0 
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.3 (4.7.1)
    vue: ^2.6.10 => 2.6.10 
    vue-eslint-parser:  2.0.3 (5.0.0)
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-router: ^3.0.3 => 3.0.7 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.1.1 
  npmGlobalPackages:
    @vue/cli: 3.8.4
```

### Steps to reproduce
Create a 'hello-world' app with vue-cli (all defaults).
Add a vue.config.js file.
Build.
Observe that the 'chunk-vendors' file contains no arrow functions.
Set ' runtimeCompiler: true' in the vue.config.js file.
Build.
Observe that one of the dependencies in the 'chunk-vendors' file contains arrow functions.

### What is expected?
The 'chunk-vendors' file contains no arrow functions.

### What is actually happening?
The 'chunk-vendors' file contains arrow functions.

---
Initially, I saw this because the project wouldn't run in IE. I thought that this was because of the Babel/node_modules defaults, so I set about trying to work with 'transpileDependencies' settings, which didn't work. I tried eliminating dependencies, to explicitly set the dependency file path, all with no success, until I went back to testing with the 'hello-world' app.

The effect in a 'real-world' project is unpredictable but consistent in that it does happen every time. If I remove a dependency, then which dependency is rewritten changes - generally between one and two, although it does seem to like rewriting Bootstrap when available. After a couple of days at this I realised that it was the runtimeCompiler setting that was triggering it.

I don't explicitly need the runtimeCompiler, I'm not sure why I enabled this, but it seems to me that this is a bug and I have seen that others have encountered this also.

**Comment by sodatea** [comment]
Do you have an actual reproduction repo? Because I can't find any arrow functions after following your steps to reproduce.

**Comment by kevteljeur** [comment]
I don't have a public repo, unfortunately. I'm still debugging - it's an infuriatingly hard bug to pin down. I cleared the cache, everything, but I'm still getting it. Maybe park this bug until I can come back with more. I'm definitely getting it but I can imagine that you'll need more info.

**Comment by kevteljeur** [comment]
No, I can definitely reproduce it, by setting `runtimeCompiler: true`. My actual persistent problem seems to be triggered by one of my own files (which is a separate issue for me to resolve), but this is without that file:
- a raw skeleton application produced by running `vue create hello-world`
- adding a vue.config.js file with `runtimeCompiler: true`.

**Comment by sodatea** [comment]
But the only thing we do with the `runtimeCompiler` option is to set a different alias for `vue`:
https://github.com/vuejs/vue-cli/blob/8f0673a93f87c1724d26dd405d3b1278ab179ae3/packages/%40vue/cli-service/lib/config/base.js#L50-L57

I don't understand why it makes a difference. I still need an actual project to investigate the problem.

**Comment by kevteljeur** [comment]
I'll try and check one in today, @sodatea - hopefully then we'll be able to find if there is an issue. Thanks again for investigating (I'm getting closer to isolating the issue in my own project too - it has the same effect but with a different cause).
