### ISSUE TITLE
mode:mordern safari 12 still load legacy modules

### ISSUE THREAD

**Issue by mylhei** [vuejs/vue-cli#4255]
### Version
3.8.3

### Reproduction link
[https://www.ipalfish.com/klian/web/dist/m/reading/read-share.html?productid=228335010523147&bookid=239838670192654&official=1&uid=1031309](https://www.ipalfish.com/klian/web/dist/m/reading/read-share.html?productid=228335010523147&bookid=239838670192654&official=1&uid=1031309)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 67.0.2
    Safari: 12.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.8.0 
    @vue/babel-preset-jsx:  1.0.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.0.0 
    @vue/cli-overlay:  3.8.0 
    @vue/cli-plugin-babel: ^3.4.0 => 3.8.0 
    @vue/cli-plugin-eslint: ^3.4.0 => 3.8.0 
    @vue/cli-plugin-typescript: ^3.4.0 => 3.8.1 
    @vue/cli-service: ^3.4.0 => 3.8.3 
    @vue/cli-shared-utils:  3.8.0 
    @vue/component-compiler-utils:  2.6.0 
    @vue/eslint-config-airbnb: ^4.0.0 => 4.0.0 
    @vue/eslint-config-typescript: ^4.0.0 => 4.0.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.2 
    typescript: ~3.2.2 => 3.2.4 
    vue: ^2.6.10 => 2.6.10 
    vue-awesome-swiper: ^3.1.3 => 3.1.3 
    vue-cli-plugin-dll: https://gitlab.pri.ibanyu.com/yaolei/vue-cli-plugin-dll.git => 1.1.8 
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.3 
    vue-lazyload:  1.2.6 
    vue-loader:  15.7.0 
    vue-router: ^3.0.1 => 3.0.6 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
open this url in safari(PC or iPhone), the notice at the networks

### What is expected?
only load type="module" 

### What is actually happening?
load both module and nomodule

---
it seems has inline script above module , when remove inline scripts , it seems ok . or add "type = "module" in inline script"

**Comment by sodatea** [comment]
Because the web page is not valid HTML.
Your inline script is neither inside `head` nor `body` and this seems to trigger some bug in Safari.

**Comment by mylhei** [comment]
@sodatea Sorry， 我修正后问题依然没有解决。 现在发现只要module上有inline script 就会出现多次加载的情况。 去掉，或者挪到最下方就可以了。

**Comment by sodatea** [comment]
我试了一下只有第一次会出现，后续刷新都没有问题。不过，这肯定是 Safari 的 bug…… 我们之前是用了这个方案绕开 https://gist.github.com/samthor/64b114e4a4f539915a95b91ffd340acc 现在看来在最新版里还需要找其他方法了。

**Comment by mylhei** [comment]
> 我试了一下只有第一次会出现，后续刷新都没有问题。不过，这肯定是 Safari 的 bug…… 我们之前是用了这个方案绕开 https://gist.github.com/samthor/64b114e4a4f539915a95b91ffd340acc 现在看来在最新版里还需要找其他方法了。

多谢了 ， 我想其他办法
