### ISSUE TITLE
Option to disable vue-cli plugins through vue.config.js

### ISSUE THREAD

**Issue by franciscolourenco** [vuejs/vue-cli#4262]
### What problem does this feature solve?
I have a project with multiple entry files and multiple vue.config.js, or a dynamic vue.config.js. Depending on the entry or target I would like to enable/disable certain vue-cli plugins.

### What does the proposed API look like?
config.disablePlugins = []

**Comment by LinusBorg** [comment]
I pushed a PR for this. However I chose to solve this through a command line flag rather than an option in the config file as that is much more flexible, solving use cases like #3830 as well.
