### ISSUE TITLE
Modify the final webpack config

### ISSUE THREAD

**Issue by Allenice** [vuejs/vue-cli#4272]
### What problem does this feature solve?
The vue-cli needs to provide a configuration that modifies the final webpack config before the webpack runs. For example, I need to customize the output file name when building the web component.

### What does the proposed API look like?
```js
// vue.config.js
module.exports = {
    finalWebpack: (config) => {
        return config
    }
}
```

**Comment by sodatea** [comment]
We do have a `--filename` option for lib target. See https://github.com/vuejs/vue-cli/pull/3703/

**Comment by sodatea** [comment]
I don't feel like adding this feature. It increases the cognitive burden for users and the maintenance burden for us maintainers, but brings little benefit.

- For common use cases, if there's any scenario that can't be supported with the current API interface, we should fix them case by case.
- For rare edge cases, users can opt-out Vue CLI and use webpack directly, using the resolved config object https://cli.vuejs.org/guide/webpack.html#using-resolved-config-as-a-file
