### ISSUE TITLE
Update lodash.defaultsdeep

### ISSUE THREAD

**Issue by kolaente** [vuejs/vue-cli#4280]
### Version
3.9.2

---

There was a security vulnerability in `lodash.defaultsdeep` which is a direct dependency of `vue/cli-service`. It would be nice if you could upgrade the dependency.

More Info: https://github.com/lodash/lodash/pull/4336

I got this alert from github for my project:

![image](https://user-images.githubusercontent.com/13721712/61116719-48349a00-a495-11e9-8b1b-b3cc13418bf9.png)

**Comment by sodatea** [comment]
This specific warning is targeting at your lockfile, and can be easily fixed by removing the `yarn.lock` and reinstall dependencies.

As for the dependency version in vue cli, we'll do it in the next patch release (in a day or two, need some time to do cherry-picking and testing before publishing)
