### ISSUE TITLE
how to extract SCSS in components into a single CSS file

### ISSUE THREAD

**Issue by SoldierAb** [vuejs/vue-cli#4281]
### Version
3.8.0

### Reproduction link
[none](none)

### Environment info
```
 "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
 "dependencies": {
    "vue": "^2.6.10",
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.8.0",
    "@vue/cli-plugin-eslint": "^3.8.0",
    "@vue/cli-service": "^3.8.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "node-sass": "^4.12.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "webpack-dev-server": "^2.9.7"
  },
```

### Steps to reproduce
npm run build

### What is expected?
extract SCSS in components into a single CSS file

### What is actually happening?
... ...

**Comment by LinusBorg** [comment]
That already works.

If it doesn't work for you l, provide a reproduction as is required for bug reports.

**Comment by Mighty683** [comment]
I have the same problem css files fromchunks are extrqcted into multiple files instead of one.

**Comment by LinusBorg** [comment]
See my previous reply

**Comment by Mighty683** [comment]
https://github.com/vuejs/vue-cli/issues/4409

Created issue
