### ISSUE TITLE
error: The "header" component has been registered but not used (vue/no-unused-components) at

### ISSUE THREAD

**Issue by ajeethhacki** [vuejs/vue-cli#4285]
### Version
3.9.2

### Reproduction link
[https://github.com/ajeethhacki](https://github.com/ajeethhacki)

### Environment info
```
npm -v  6.10.1,  node -v  v10.14.2, vue --version  3.9.2
```

### Steps to reproduce
create new project  in the hellow world page add two component and then run it the above i told error will occur

### What is expected?
<header />
<content />
<footer />

### What is actually happening?
The "header" component has been registered but not used (vue/no-unused-components)

**Comment by LinusBorg** [comment]
As *required*, please add a reproduction.

Your explanation is not allowing us to understand your problem.
