### ISSUE TITLE
vue-cli (2.x) should display deprecation warning

### ISSUE THREAD

**Issue by jbuhacoff** [vuejs/vue-cli#4290]
### What problem does this feature solve?
There are tutorials out there telling users to `npm install -g vue-cli` and this feature would give users a hint that there's a newer version at `@vue/cli` that they should be looking at.

Currently:
* https://www.npmjs.com/package/vue-cli  is version 2.9.6 
* https://www.npmjs.com/package/@vue/cli is version 3.9.2

### What does the proposed API look like?
`npm install -g vue-cli` should give a deprecation warning with a hint to use `@vue/cli` instead. For example:

```
npm WARN deprecated vue-cli@2.9.7: use @vue/cli instead (try "npm install -g @vue/cli")
```

**Comment by jbuhacoff** [comment]
@linusborg thanks for the quick response even when you're on the road!

**Comment by sodatea** [comment]
Done. Thanks for your suggestion!
