### ISSUE TITLE
E2E Cypress Plugin - Lodash prototype polution

### ISSUE THREAD

**Issue by maxtomczyk** [vuejs/vue-cli#4296]
### Version
3.9.2

### Environment info
```
Environment Info:
```

### Steps to reproduce
Install cli-plugin-e2e-cypress plugin
Run npm audit

### What is expected?
Cypress plugin using version of lodash higher than 4.17.12

### What is actually happening?
cli-plugin-e2e-cypress plugin uses lodash package vulernable to Prototype Pollution: https://www.npmjs.com/advisories/1065

**Comment by sodatea** [comment]
It's a direct dependency of cypress. Please wait for their update.

**Comment by jclaudan** [comment]
> It's a direct dependency of cypress. Please wait for their update.

cypress is now update in RP #4303
