### ISSUE TITLE
Proxy dev proxy server not working 504 connection refused

### ISSUE THREAD

**Issue by SephVelut** [vuejs/vue-cli#4297]
### Version
3.9.2

### Environment info
```
No info given by cmd
```

### Steps to reproduce
```
//config/index.js
      proxyTable: {
          '/api': {
              target: 'http://127.0.0.1:9000',
              logLevel: 'debug',
              changeOrigin: true,
              secure: false,
              pathRewrite: {
                  '^/api': ''
              }
          }
      },
```
Have http server listening on 127.0.0.1:9000
Make ajax request using axios
```
this.$http({
        method: 'post',
        url: '/api/login',
        data: {
          username: this.login.username,
          password: this.login.password
        }
      })
      .then(function (response) {
        this.$store
        console.log(response)
      }.bind(this))
      .catch(function (_) {
        this.$router.replace({ name: 'Login' })
      }.bind(this))
    }
```
### What is expected?
Proxy post request to backend http server

### What is actually happening?
504 Gateway Timeout response

---
My http server receives the post request and responds with 
```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 0
Server: MyServer
Date: 2019-07-16 Tue
Content-Type: text/html
```

Have also tried returning
```
HTTP/1.1 202 Accepted
Content-Length: 0
Date: Tue, 16 Jul 2019 02:55:17 GMT
Server: MyServer
```

Tried running backend server on http://localhost:8000. Tried many different configurations. 
Don't understand the why the 504 from the proxy server. Meanwhile `npm run dev` reports this log `[HPM] Error occurred while trying to proxy request /login from localhost:8080 to http://localhost:8000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`
My server works just fine. Responds to curl, in the browser, etc.

Removed node and npm and ~/.npm and node_modules and reinstalled everything. Ran npm docotor, everything is clean. So next, tried using vue/cli version 3 has the exact same issue with
```
//$rootDir/vue.config.js
module.exports = {
    devServer: {
        proxy: {
            "/login": {
                target: "https://localhost:8000",
                secure: false,
                changeOrigin: true
            }
        }
    }
};
```

`npm run serve`

This time I get `Proxy error: Could not proxy request /login from localhost:8080 to https://localhost:8000.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).`

Digging into the backend server I went and logged the bytes coming in from the proxy server. Decoding them to utf8 produces garbage of valid utf8 up to 11 characters `\u{16}\u{3}\u{1}\u{1}f\u{1}\u{0}\u{1}b\u{3}\u{3}`. When any other application sends an http request, for example curl, its a well formed http message `POST /login HTTP/1.1`.

**Comment by qzmer1104** [comment]
same question 
why? 
how to fix

**Comment by nhiguchi-stb** [comment]
I have same question.
