### ISSUE TITLE
how to enable the css  autoprefix function in webpack.dev.config and webpack.prod.config

### ISSUE THREAD

**Issue by dannyliou** [vuejs/vue-cli#431]
how to enable the css  autoprefix function in webpack.dev.config and webpack.prod.config?

I try to add the following to the vue-loader.conf.js file

```
module.exports = {
  loaders: utils.cssLoaders({
    sourceMap: isProduction
      ? config.build.productionSourceMap
      : config.dev.cssSourceMap,
    extract: isProduction
  }),
  postcss: [
     require('postcss-cssnext')({
       browsers: ['last 20 versions']
     })
   ]
}
```
my pakage.json file : 
```
   "webpack": "^2.2.1",
   "postcss-cssnext": "^2.10.0",
   "postcss-loader": "^1.3.3",
```
when I exec the npm run dev ,no autoprefix in the flex and transform css attrs

thank you very much if anyone can help me

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

Maybe _last 20 versions_ is not valid (it's quite unrealistic too). Try something like last 2 versions ie >= 9. You should look up css-next doc for that
