### ISSUE TITLE
Can't create new projects that uses prettier

### ISSUE THREAD

**Issue by filimon-danopoulos-stratsys** [vuejs/vue-cli#4310]
### Version
3.9.2

### Environment info
```
  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
* Run `vue create sample-app`
* Pick "Manually select features"
* Check "Linter"
* Select "Prettier"
* Pick "Lint on Save"

### What is expected?
A new project is created. 

### What is actually happening?
The following error is thrown `Error: Failed to load plugin prettier: Cannot find module 'eslint-plugin-prettier'`

**Comment by gabemule** [comment]
The same occurs on old project when deleting yarn.lock/package-lock.json and reinstalling dependencies.

**Comment by max8hine** [comment]
Same here.
![image](https://user-images.githubusercontent.com/15165714/61501056-b4794580-aa21-11e9-94db-a8281cd4550b.png)

**Comment by staticfire** [comment]
Same issue.

`yarn install eslint-plugin-prettier` solved the problem.

**Comment by filimon-danopoulos-stratsys** [comment]
@gabemule You are probably correct.
