### ISSUE TITLE
Creating a new projects on ubuntu 18.04 takes about 10 hours

### ISSUE THREAD

**Issue by dimaty26** [vuejs/vue-cli#4312]
### Version
3.9.2

### Environment info
```
vue create some-project
```

### Steps to reproduce
vue create some-project

### What is expected?
project creates

### What is actually happening?
the project creates in 10 hours

**Comment by sodatea** [comment]
Could you please provide more context on this issue?
Which options did you choose? At what phase was the command stuck? Any console outputs?

**Comment by dimaty26** [comment]
I found out that the reason of this issue was in npm. When I tried to use yarn everything became good. Thank you
