### ISSUE TITLE
vue-cli关于打包后接口请求跨域应该如何设置？

### ISSUE THREAD

**Issue by frontHu** [vuejs/vue-cli#432]
![image](https://cloud.githubusercontent.com/assets/19454392/24828685/0c13d62e-1c95-11e7-9226-889e14ee3e78.png)
首先，在本地开发的时候设置接口代理能够正常的请求到数据，然然后build后，我把dist文件里面的内容放到服务器上，在服务器上运行的时候，接口请求前面的地址是我服务器域名的地址，所以会报404找不到的错误。
那么我该如何设置，打包后的文件放到服务器环境下请求的接口地址是正确的呢？

**Comment by egoist** [comment]
Read the docs before creating a issue: https://github.com/vuejs-templates/webpack/blob/master/docs/proxy.md (Proxy is only for development)

Next time please open issues in relevant repo.

**Comment by MaYuning** [comment]
解决了吗？

**Comment by zhaoyunyi** [comment]
如何解决

**Comment by cethink** [comment]
解决了吗？
