### ISSUE TITLE
hot reload  in build watch mode

### ISSUE THREAD

**Issue by lastlink** [vuejs/vue-cli#4322]
### What problem does this feature solve?
For vuejs applications running on the same port as a service e.g. php and to avoid cors watch build is very effective, just that hot reload doesn't work.

Example of package.json
```json
"scripts": {
    "watch": "vue-cli-service build --watch"
  }
```

### What does the proposed API look like?
An additional option to the vuejs config to support hot reload if it's not desired by default. Could be something similar to this.
```js
// vue.config.js
module.exports = {
    outputDir: "../wwwroot/client-app/",
    filenameHashing: true,
    publicPath: "/client-app/",
    chainWebpack: config => {
        config.module
            .rule('vue')
            .use('vue-loader')
            .loader('vue-loader')
            .tap(options => {
                options.hotReload = true
                // modify the options...
                return options
            })
    }
}
```

**Comment by sodatea** [comment]
Hot module replacement is not that easy. a dev server is **required**.

For your use case, you can have a look at [the proxy option](https://cli.vuejs.org/config/#devserver-proxy)

**Comment by pradsdev** [comment]
I'm using firebase to handle my backend stuffs including hosting. Firebase emulators are actually good for development. Running those emulators i'm connecting multiple projects into one to run as a whole product. So i'm insisted to specify `dist` folder on firebase config. So what i'm running the `vue-cli-service build --watch`. In this hot-reload is not working. Is there any way to make it working on build watch mode? Is that something not available in vue-cli?

**Comment by sodatea** [comment]
It's just not possible to do hot-reload without a dedicated dev server. Because you'd need an additional WebSocket connection to pass the information about the changed modules to the client.

So please use the proxy option if you have any other backend servers and still want to have hot module replacement.
