### ISSUE TITLE
babel.config.js not loaded if cli-plugin-babel is installed from a package's dependencies

### ISSUE THREAD

**Issue by pzjzeason** [vuejs/vue-cli#4324]
### Version
3.9.0

### Environment info
```
  System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: Not Found
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: Not Found
    Safari: 13.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.9.2 
    @vue/babel-preset-jsx:  1.0.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.0.0 
    @vue/cli-overlay:  3.9.0 
    @vue/cli-plugin-babel: ^3.9.0 => 3.9.2 
    @vue/cli-plugin-eslint:  3.9.2 
    @vue/cli-service:  3.9.3 
    @vue/cli-shared-utils:  3.9.0 
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    eslint-plugin-vue:  5.2.3 (4.7.1)
    vue:  2.6.10 
    vue-eslint-parser:  2.0.3 (5.0.0)
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.1 
    vue-router:  3.0.7 
    vue-rx: ^6.1.0 => 6.2.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler:  2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuex:  3.1.1 
    vuex-router-sync:  5.0.0 
  npmGlobalPackages:
    @vue/cli: 3.8.4
```

### Steps to reproduce
In my team, all dependencies are placed in a separate package's dependencies (eg. packageA). When I install this packageA in a project, all dependencies like vue and vue-cli will be installed too. Here is the problem. The babel.config.js is not loaded. I put a console.log at the first line in this file, but it doesn't print anything when i start the project or run vue inspect.

However, when I place "@vue/cli-plugin-babel": "^3.9.0" in project's package.json's dependencies field instead of in packageA's. Console.log works which means babel.config.js is loaded.

What happed here? If I want the babel.config.js to be loaded in the first case, what can I do?

### What is expected?
babel.config.js is loaded 

### What is actually happening?
babel.config.js not loaded

**Comment by pzjzeason** [comment]
Look at this......
<img width="759" alt="vuePlugin" src="https://user-images.githubusercontent.com/36041376/61601563-a23d1880-ac68-11e9-9239-17773611976c.png">

**Comment by wQueryLoveMm** [comment]
@pzjzeason 
thx 
in  monorepos
if someone input ` vue inspect --rules ` in terminal,  can not find `js eslint`

add

package.json
the real path plugins listed
```json
 "vuePlugins": {
    "resolveFrom": "../../" 
  }
```
