### ISSUE TITLE
Static assets relative path

### ISSUE THREAD

**Issue by maxflex** [vuejs/vue-cli#433]
Let's say I put an image in `/static/img.png` and then reference it somewhere in css like so 

    .wrapper {
      background: url('/static/img.png')
    }

It works fine. But when deployed to non-first-level url the app is referencing assets from `root`.

Thus, if I were to deploy to https://example.com/app-name/, the app would be referencing `https://example.com/static/img.png` instead of `https://example.com/app-name/static/img.png` (*with `/app-name`*).

If I don't go from `root` in CSS `background: url('static/img.png')` (*fronting slash removed*) [webpack will interpret it as a module dependency][1].

**How do I solve this?**

*\*vue-cli webpack 2 template*

  [1]: http://vuejs-templates.github.io/webpack/static.html

**Comment by zhaotoday** [comment]
I meet the same problem.
You can try to import your style file like:
```html
<style lang="scss" scoped src="./theme/styles/index.scss">
</style>
```
I solve the problem by importing style file like this.
https://github.com/zhaotoday/vue.js/blob/master/src/app/Articles/components/ChildComp/index.vue#L19

**Comment by posva** [comment]
You can play with the option [here](https://github.com/vuejs-templates/webpack/blob/master/template/config/index.js#L9-L10) to get the desired behaviour. Closing because it's not related to vue-cli

**Comment by jbayona89** [comment]
I'm having this issue also. I changed all my static routes from /static to /app-name/static and that worked for my production server but now my npm run dev server cannot locate the files.

Is there any way to keep the routes as /static in my code and then just process them in webpack to show like /app-name/static?

**Comment by DoubleMarv** [comment]
Same issue here. Very annoying
