### ISSUE TITLE
node_env

### ISSUE THREAD

**Issue by thelongmarch** [vuejs/vue-cli#4334]
### What problem does this feature solve?
'use strict'
const merge = require('webpack-merge')
const prodEnv = require('./prod.env')
module.exports = merge(prodEnv, {
NODE_ENV: '"development"'
})

为什么要merge上之前的prod.env，
prod.env里面就一行内容
意义大吗

https://segmentfault.com/q/1010000012918070

### What does the proposed API look like?
抱歉，没有cli2入口，大佬，能解释下为啥这么写？难道就是为了防止覆盖么

**Comment by sodatea** [comment]
https://github.com/vuejs-templates/webpack/blob/master/docs/env.md
实际使用时里面一般会有其他字段

**Comment by thelongmarch** [comment]
感谢！！！
As we can see, test.env inherits the dev.env and the dev.env inherits the prod.env.

这个继承关系一定要这么写么？是因为prod字段肯定全，所以继承prod么？还有如果这样可以 test.env inherits the prod.env么

**Comment by sodatea** [comment]
当然可以，文档里只是举了个例子，完全可以根据实际情况自己修改。

**Comment by thelongmarch** [comment]
好的，感谢！大佬休息的也好晚
