### ISSUE TITLE
vue-cli build lib's Bug

### ISSUE THREAD

**Issue by kazehaiya** [vuejs/vue-cli#4338]
### Version
2.6.0

### Reproduction link
[https://github.com/kazehaiya/vue-cli-project-demo](https://github.com/kazehaiya/vue-cli-project-demo)

### Node and OS info
node:  v10.15.3、yarn: 1.17.3、System: MacOS 10.14.5

### Steps to reproduce
First run 'yarn build'.Then run devEnv and chage the '@lib/vue-cli-project-demo.umd' with '@lib/vue-cli-project-demo.umd.min' in src/main.ts

### What is expected?
The component's name of MyButton is "Mybutton"

### What is actually happening?
When use minimize js file, the name of MyButton is 'e'

---
If the Mybutton component doesn't use TS, the result of minimize file run well.

I think that it should be fixed beacause many package use minimize output file.

**Comment by sodatea** [comment]
Don't rely on class names, use the component name property:
```ts
@Component({ name: 'MyButton' })
class MyButton extends Vue {
  // ...
}
```

More detailed explanation: https://medium.com/haiiro-io/element-component-name-with-vue-class-component-f3b435656561

**Comment by kazehaiya** [comment]
I've tried this method, It's doesn't work. May be I should try the solution 1.

**Comment by sodatea** [comment]
Oh sorry I didn't look into your repository carefully.
Then your problem is the same as this one: https://github.com/vuejs/vue-cli/issues/4065#issuecomment-496267589 and you need to use `MyButton.options.name` to register it.

**Comment by kazehaiya** [comment]
Thank you so much @sodatea
