### ISSUE TITLE
The packaged CSS file does not contain non-routing components

### ISSUE THREAD

**Issue by SoldierAb** [vuejs/vue-cli#4341]
### Version
3.9.2

### Environment info
```
//--- vue.config.js
const path = require('path')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

module.exports = {

  publicPath: '/',

  configureWebpack: {
    module: {
      rules: [
        {
          test: /\.scss$/,
          use: ExtractTextPlugin.extract({
            fallback: "style-loader",
            use: [
              "css-loader",
              "sass-loader",
              {
                loader: 'sass-resources-loader',
                options: {
                  resources: path.resolve(__dirname, `./src/theme/${process.env.VUE_APP_THEME}.scss`)  //主题皮肤文件全局注入
                }
              }
            ]
          })
        },
      ]
    },
    plugins: [
      new ExtractTextPlugin({
        filename: `theme/${process.env.VUE_APP_THEME}.css`,
        allChunks: true      
      }),
    ],
   }
}



//App.vue  
<template>
  <div>
      <top-nav></top-nav>
      <router-view></router-view>
  </div>
</template>

<style lang="scss">

</style>


// ---------------------
```

### Steps to reproduce
npm run build

### What is expected?
The packaged CSS file contain non-routing components

### What is actually happening?
The packaged CSS file does not contain non-routing components(App， TopNav) 

---

**Comment by sodatea** [comment]
What do you mean by "non-routing components"?
Please provide a runnable reproduction.

**Comment by SoldierAb** [comment]
The App.vue and TopNav.vue




| |
陈贵坚
邮箱：ab140140@163.com
|

签名由 网易邮箱大师 定制

On 07/23/2019 20:15, Haoqun Jiang wrote:

What do you mean by "non-routing components"?
Please provide a runnable reproduction.

**Comment by sodatea** [comment]
Please do provide a **runnable reproduction**. I've no idea how you use the `App.vue` so I can't give any suggestions.

**Comment by Mighty683** [comment]
If you lazy load component CSS files are splited with JS files I think there should be option to extract single CSS file.

**Comment by LinusBorg** [comment]
This has been without a reproduction long enough. I'll close it.
