### ISSUE TITLE
How to print total time of building with vue cli3?

### ISSUE THREAD

**Issue by superevanzhu** [vuejs/vue-cli#4343]
### What problem does this feature solve?
When using webpack2.0,i can see building total time in terminal. But with  vue cli 3 ,there is't time printed, Do i need config something?

### What does the proposed API look like?
I want to optimize my build process.

**Comment by sodatea** [comment]
![image](https://user-images.githubusercontent.com/3277634/61714383-43bd8a80-ad8d-11e9-8335-6f26fec2dd7b.png)
But we do print the time…
