### ISSUE TITLE
Hot reloading always doing a full page reload

### ISSUE THREAD

**Issue by BaptisteLemarcis** [vuejs/vue-cli#4344]
### Version
3.9.3

### Environment info
```
Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE      
    Yarn: Not Found
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.9.2
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.9.0
    @vue/cli-plugin-babel: ^3.9.2 => 3.9.2
    @vue/cli-plugin-eslint: ^3.9.2 => 3.9.2
    @vue/cli-plugin-unit-jest: ^3.8.0 => 3.9.0
    @vue/cli-service: ^3.8.4 => 3.9.3
    @vue/cli-shared-utils:  3.9.0
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    bootstrap-vue: 2.0.0-rc.21 => 2.0.0-rc.21
    eslint-plugin-vue:  4.7.1
    jest-serializer-vue:  2.0.2
    portal-vue:  2.1.5
    vue: ^2.6.8 => 2.6.10 (1.0.28)
    vue-axios: ^2.1.4 => 2.1.4
    vue-chartjs: ^3.3.2 => 3.4.2
    vue-clickaway: ^2.2.2 => 2.2.2
    vue-cropperjs: ^2.2.2 => 2.2.2
    vue-eslint-parser: ^6.0.4 => 6.0.4 (2.0.3)
    vue-functional-data-merge:  2.0.7
    vue-hot-reload-api:  2.3.3
    vue-i18n: ^7.8.1 => 7.8.1
    vue-jest:  3.0.4
    vue-js-toggle-button: ^1.3.2 => 1.3.2
    vue-loader: ^15.7.0 => 15.7.1
    vue-loading: ^0.1.4 => 0.1.4
    vue-lodash: ^2.0.0 => 2.0.2
    vue-multiselect: ^2.1.6 => 2.1.6
    vue-observe-visibility: ^0.4.3 => 0.4.4
    vue-router: ^3.0.1 => 3.0.7
    vue-session: ^1.0.0 => 1.0.0
    vue-style-loader: ^4.1.2 => 4.1.2
    vue-swatches: ^1.0.3 => 1.0.3
    vue-template-compiler: ^2.6.8 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vue-tippy: ^2.1.0 => 2.1.3
    vue2-dropzone: 3.5.2 => 3.5.2
    vuedraggable: ^2.16.0 => 2.23.0
    vuejs-datepicker: git https://github.com/brurubio/vuejs-datepicker.git#build => 1.3.3
    vuejs-jwt: ^1.1.0 => 1.1.0
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
I just need to update style, html or JS code

### What is expected?
That my application don't full reload each little update of style

### What is actually happening?
Each time a change is detected the application rebuild (~3s) and the page reload.

---
When I was on webpack 2.7 everythings worked fined, now it takes longer to compile and detecting change recompile in ~3s instead of ~500ms.

My VueCLI config

```
module.exports = {
  devServer: {
    host: 'localhost',
    overlay: {
      warnings: true,
      errors: true
    }
  },
  transpileDependencies: ['vuex'],
  runtimeCompiler: true,
  productionSourceMap: false,
  chainWebpack: config => {
      config.module
        .rule('vue')
        .use('vue-loader')
          .loader('vue-loader')
          .options({
            prettify : false
          })
    }
}
```

**Comment by sodatea** [comment]
Can't reproduce. Please provide a runnable reproduction as is required by the issue helper.

**Comment by BaptisteLemarcis** [comment]
I can't share my project as it's a work project but I will try to provide an example

**Comment by xzdm** [comment]
I had the same problem, bro

**Comment by CuongStf** [comment]
how to resolve it? I have same problem. It's really make my performance slowly so much. Can help?

**Comment by xzdm** [comment]
> how to resolve it? I have same problem. It's really make my performance slowly so much. Can help?

you can create a new project, and migrate your original business logic to this new project. I solved in this way

**Comment by CuongStf** [comment]
> > how to resolve it? I have same problem. It's really make my performance slowly so much. Can help?
> 
> you can create a new project, and migrate your original business logic to this new project. I solved in this way

so it's really hard to make, project so big and complicate now

**Comment by BaptisteLemarcis** [comment]
We discovered the problem, it was the webpack package in the package.json. It was a webpack problem!
So we removed webpack from our package.json, delete node_module and an npm i.

**Comment by CuongStf** [comment]
> We discovered the problem, it was the webpack package in the package.json. It was a webpack problem!
> So we removed webpack from our package.json, delete node_module and an npm i.

really in webpack version. i tried remove node_modules and reinstall but it's till not working in your solution.

**Comment by CuongStf** [comment]
> We discovered the problem, it was the webpack package in the package.json. It was a webpack problem!
> 
> ```
>     "webpack": "^4.35.3",
>     "webpack-bundle-analyzer": "^3.3.2",
>     "webpack-cli": "^3.3.5",
>     "webpack-dev-server": "^3.7.2",
>     "webpack-merge": "^4.2.1"
> ```
> 
> Theses lines were remove as VueCLI include the right version.
> Then delete package-lock.json and node_modules to reinstall all package with npm i.
> 
> That fix my problem

If i delete package-lock, have affect to my project, because it's on production?
