### ISSUE TITLE
[FR] Hot Reload Delay / Throttle

### ISSUE THREAD

**Issue by rayfoss** [vuejs/vue-cli#4353]
### What problem does this feature solve?
`hotReload: false` is too blunt. I have auto save on and I can't disable it on Glitch.com. 

### What does the proposed API look like?
`hotReloadDelay: 6000`

SEO: Watchdog auto save autosave glitch.com

**Comment by sodatea** [comment]
```js
// vue.config.js
module.exports = {
  devServer: {
    watchOptions: {
      aggregateTimeout: 5000
    }
  }
}
```

References:
https://webpack.js.org/configuration/dev-server/#devserverwatchoptions-
https://webpack.js.org/configuration/watch/#watchoptionsaggregatetimeout
