### ISSUE TITLE
使用vue build App.vue 进行原型开发打包后，直接打开dist里面的index.html浏览器显示空白

### ISSUE THREAD

**Issue by svnfox** [vuejs/vue-cli#4355]
### Version
3.9.3

### Reproduction link
[http://abc.com](http://abc.com)

### Environment info
```
mac mojave
```

### Steps to reproduce
普通的App.vue的hello word文件

### What is expected?
vue serve 进行原型开发后， vue build能打包原型文件

### What is actually happening?
猜是路径问题，默认配置打包后的引用路径是/根目录的js文件夹，

---
打包后的路径引用能改成相对路径吗

**Comment by sodatea** [comment]
不要直接打开文件访问，请使用静态文件服务器

**Comment by svnfox** [comment]
> 不要直接打开文件访问，请使用静态文件服务器
这个回答不是很满意。不过我找到方法了，就是在App.vue下，可以新建vue.config.js 更改里面的publicPath: './',  打包后就可以用浏览器看到页面了

**Comment by svnfox** [comment]
> 不要直接打开文件访问，请使用静态文件服务器

我觉得更好的解决方案是能在命令 vue build 后面加个参数 类似 --publicPath="./" 就更好了

**Comment by sodatea** [comment]
网页本来就不应该用 `file://` 协议访问，就算没有 `publicPath` 的问题也会有其他问题，支持这种使用场景完全是费力不讨好。

**Comment by svnfox** [comment]
> 网页本来就不应该用 `file://` 协议访问，就算没有 `publicPath` 的问题也会有其他问题，支持这种使用场景完全是费力不讨好。

虽然不知道你说的其他问题是什么，但既然vue 支持了原型开发，那这些问题就需要考虑斟酌，而原型开发的特点就是快速便捷，很多情况下是不需要像正式开发那样部署到服务器的，只要将dist文件传给其他同事，他打开看没问题就算完成。个人见解，这问题就到这吧。谢谢你的回答！
