### ISSUE TITLE
css-loader options error

### ISSUE THREAD

**Issue by Maorey** [vuejs/vue-cli#4357]
### Version
4.0.0-beta.1

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Environment info
```
css-loader 3.0.1
```

### Steps to reproduce
1. set css.loaderOptions.css.localIdentName get css-loader ValidationError
2. set css.loaderOptions.css.modules.localIdentName get css-loader ValidationError too

### What is expected?
correct css-loader option

### What is actually happening?
wrong

---
https://github.com/vuejs/vue-cli/blob/76eb7146caea9b51b13e5459ca511ca17667cc27/packages/%40vue/cli-service/lib/config/css.js#L126

**Comment by LinusBorg** [comment]
Hi  

Thanks for filing this issue! Could you please provide a small reproduction on jsfiddle.net or as a github reporsitory so we can debug this without trying to replicate this ourselves?`

That would be very helpful, thanks!

**Comment by Maorey** [comment]
It‘s quite simple，in css-loader 3.1.0, it's options like this:
``` JavaScript
{
  modules: {
    localIdentName: '[folder]-[name]-[local][emoji]',
  },
  localsConvention: 'camelCaseOnly,
}
```
but in [this line](https://github.com/vuejs/vue-cli/blob/76eb7146caea9b51b13e5459ca511ca17667cc27/packages/%40vue/cli-service/lib/config/css.js#L126):
``` JavaScript
const { localIdentName = '[name]_[local]_[hash:base64:5]' } = loaderOptions.css || {}
Object.assign(cssLoaderOptions, {
  modules: {
    localIdentName,
  },
})
```

so, when pass:
``` JavaScript
{
  modules: {
    localIdentName: '[folder]-[name]-[local][emoji]',
  },
  localsConvention: 'camelCaseOnly,
}
```
get:
``` JavaScript
{
  modules: {
    localIdentName: '[name]_[local]_[hash:base64:5]',
  },
  localsConvention: 'camelCaseOnly,
}
```
That's not i wanted

pass:
``` JavaScript
{
  localIdentName: '[folder]-[name]-[local][emoji]',
  localsConvention: 'camelCaseOnly,
}
```
get:
``` JavaScript
{
  modules: {
    localIdentName: '[folder]-[name]-[local][emoji]',
  },
  localIdentName: '[folder]-[name]-[local][emoji]',
  localsConvention: 'camelCaseOnly,
}
```
That's will get a ValidationError

**Comment by Maorey** [comment]
And, how about this option: [css.modules](https://cli.vuejs.org/config/#css-modules)?
> By default, only files that ends in *.module.[ext] are treated as CSS modules. Setting this to true will allow you to drop .module in the filenames and treat all *.(css|scss|sass|less|styl(us)?) files as CSS modules.
