### ISSUE TITLE
Project creation failed when using Yarn

### ISSUE THREAD

**Issue by BlueskyFR** [vuejs/vue-cli#4369]
### Version
3.9.3

### Environment info
```
Environment Info:

  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 10.16.0 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.10.0 - /usr/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: 68.0.1
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
1. Run `vue create test-project`
2. Select `Manually select features`
3. Select `Babel`, `Router`, `Vuex` and `Linter / Formatter`
4. Use history mode for Router
5. Select `ESLint + Prettier`
6. Select `Lint on save`
7. Select `In dedicated config files`
8. Don't save as a new preset.

### What is expected?
Project should then be created without errors.

### What is actually happening?
When using Yarn as the package manager, after the installation of additional dependencies, this error is displayed:
```
ERROR  Error: Failed to load plugin prettier: Cannot find module 'eslint-plugin-prettier'
Referenced from: /home/XXXX/code/vue/test-project/.eslintrc.js
```

---
Please note that I installed vue-cli using Yarn global.
There is no error when using npm as the package manager in vue-cli, only when using Yarn, and I really want to use it.
Can you help me?

Thanks in advance!

**Comment by sodatea** [comment]
Workarounds:
1. Use v4 beta
2. Bear with the error message, manually update the dependency after project creation (`@vue/eslint-plugin-prettier` v4 -> v5, add `eslint-plugin-prettier` as `devDependencies`)
3. Wait for the next release of v3. (I need time to do the cherry-picking and testing, likely to do it next week unless critical bugs encountered)

**Comment by BlueskyFR** [comment]
@sodatea I can't get to update the dependencies :-/
What should I exactly change?

**Comment by sodatea** [comment]
Even if there's an error thrown, the project folder should have been successfully created. The only missing part is linting and automatic git commit.

So:
```
cd test-project
yarn add -D @vue/eslint-config-prettier eslint-plugin-prettier
yarn lint
git add -A .
git commit -m 'init'
```

(sorry for the typo in the previous comment)

**Comment by BlueskyFR** [comment]
Thanks, it works!
Thanks for your time and good patching :D
