### ISSUE TITLE
vue-cli 使用css modules，global类无效

### ISSUE THREAD

**Issue by linlinyang** [vuejs/vue-cli#4371]
### Version
3.9.3

### Reproduction link
[https://github.com/linlinyang/vue_note](https://github.com/linlinyang/vue_note)

### Environment info
```
Environment Info:

  System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 10.4.1 - F:\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.9.0 - F:\nodejs\npm.CMD
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.9.2
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.9.0
    @vue/cli-plugin-babel: ^3.9.0 => 3.9.2
    @vue/cli-service: ^3.9.0 => 3.9.3
    @vue/cli-shared-utils:  3.9.0
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.1
    vue-router: ^3.0.3 => 3.0.7
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### 我的vue.config.js如下：
    const path = require('path');
	const resolve = dirname => path.resolve(__dirname,dirname);
	
	
	module.exports = {
	    css: {
	      modules: true
	    },
	    chainWebpack: config => {
	        const types = ['vue-modules', 'vue', 'normal-modules', 'normal']
	        types.forEach(type => addStyleResource(config.module.rule('less').oneOf(type)))
	      },
	};
	  
	function addStyleResource (rule) {
	    rule.use('style-resource')
	      .loader('style-resources-loader')
	      .options({
	        patterns: [
	            resolve('./src/assets/styles/global.less')
	        ],
	      })
	  }

###我的组件如下：
    <template>
	    <div :class="[styles.button,styles.global_button]">
	        <span>按钮</span>
	    </div>
	</template>
	
	<script>
	import styles from './index.less';
	console.log(styles);
	export default {
	    name: 'Login',
	    data(){
	        return {
	            styles
	        };
	    }
	}

###我的样式表如下（style.less）：

    .button{
	    width: 300px;
	    height: 40px;
	    margin: 30px auto;
	    color: @color;
	
	    span{
	        font-size: 20px;
	    }
	}
	 
	:global{
	    .globalButton{
	        color: aqua;
	    }
	}
	
	:local(.localButton){
	    border-radius: 10px;
	}

###但是结果打印只出现local类，并未出现global类，相应的样式也并未出现在按钮样式表上

### What is expected?
button和localButton类被处理，
globalButton类不做处理，但应该返回在样式结果中

### What is actually happening?
button和localButton类被处理，
globalButton类并未返回

---
就是一个简单地vue-cli例子

**Comment by sodatea** [comment]
https://github.com/webpack-contrib/css-loader#scope

global 类不作处理，所以也不需要导出。这是 `css-loader` 的默认行为。
