### ISSUE TITLE
vue-cli generated project (with typescript) builds with type error when there is props.

### ISSUE THREAD

**Issue by foresightyj** [vuejs/vue-cli#4381]
### Version
3.9.3

### Reproduction link
[https://github.com/foresightyj/vue_ts_minimal](https://github.com/foresightyj/vue_ts_minimal)

### Environment info
```
Environment Info:

  System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.9.2
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.9.0
    @vue/cli-plugin-babel: ^3.9.0 => 3.9.2
    @vue/cli-plugin-typescript: ^3.9.0 => 3.9.0
    @vue/cli-service: ^3.9.0 => 3.9.3
    @vue/cli-shared-utils:  3.9.0
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    typescript: ^3.4.3 => 3.5.3
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.1
    vue-router: ^3.0.3 => 3.0.7
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce

`vue create` a new project with `typescript` and copy `test.vue` in the minimal project in the question to `components` folder, and then:

run `npm run build`。

**I had been happily working with vue & typescript for quite a few months until today**, I removed node_modules and ran `cnpm install`. I upgraded `@vue/cli` and reproduced the problem using the minimal test case in this question.

### What is expected?
runs without ts error

### What is actually happening?
```
 ERROR  Failed to compile with 1 errors                                                                                                                                   18:37:14


 error  in C:/Users/Administrator/Desktop/testvue3/src/components/test.vue

ERROR in C:/Users/Administrator/Desktop/testvue3/src/components/test.vue
22:24 Property 'showDialog' does not exist on type 'Vue'.
    20 |   methods: {
    21 |     handleSelectionChange(): void {
  > 22 |       console.log(this.showDialog);
       |                        ^
    23 |     }
    24 |   }
    25 | });

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testvue3@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1

```

**Comment by foresightyj** [comment]
Do note that if `props` are removed`, the everything compiles.

The weirdest part is that the program looks OK in vscode.

![image](https://user-images.githubusercontent.com/1296736/62123086-ba143c80-b2f9-11e9-8e1f-8f1ec57e69d5.png)

Note that the type `this.showDialog` is showing correctly.

**Comment by foresightyj** [comment]
This does not work either:

```
 props: {
    TestId: {
      require: true,
      type: Number
    }
  },
```

And magically this works:

 ```
props: {
    TestId: {
      type: Number
    }
  },
```

**Comment by LinusBorg** [comment]
"required", not "require"

**Comment by foresightyj** [comment]
Thank you very much! It works (magically) after fixing the typo. Typescript gives me a false sense of security so I never suspected that line.

But IMHO, the error message is completely irrelevant to the actual fix. The `required` property is optional so it should mess up the type inference in spite of the typo. You are free to close the issue if you do not think that is a problem though.
