### ISSUE TITLE
different contentHash with the same repo on different path

### ISSUE THREAD

**Issue by xiao555** [vuejs/vue-cli#4390]
### Version
3.9.3

### Reproduction link
[https://github.com/xiao555/vue-cli-different-contentHash-demo](https://github.com/xiao555/vue-cli-different-contentHash-demo)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 68.0.1
    Safari: 12.1.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.9.2
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.9.0
    @vue/cli-plugin-babel: ^3.9.0 => 3.9.2
    @vue/cli-plugin-eslint: ^3.9.0 => 3.9.2
    @vue/cli-service: ^3.9.0 => 3.9.3
    @vue/cli-shared-utils:  3.9.0
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3 (4.7.1)
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0 (2.0.3)
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.1
    vue-router: ^3.0.7 => 3.0.7
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: 3.9.3
```

### Steps to reproduce
Clone twice in different path:
``` javascript
git clone https://github.com/xiao555/vue-cli-different-contentHash-demo.git repo1
git clone https://github.com/xiao555/vue-cli-different-contentHash-demo.git repo2
```
Then run in each repo:
``` javascript
yarn install && yarn run build
```

### What is expected?
The contentHash of app.js need to be same.

### What is actually happening?
It's different in two repo's build result.

repo1:

dist/js/chunk-vendors.2ce01813.js    82.78 KiB          29.90 KiB

dist/js/app.0a4bb3ac.js              4.56 KiB           1.61 KiB

dist/css/app.e2713bb0.css            0.33 KiB           0.23 KiB

repo2: 

dist/js/chunk-vendors.2ce01813.js    82.78 KiB          29.90 KiB

dist/js/app.d7be3b8a.js              4.56 KiB           1.61 KiB

dist/css/app.e2713bb0.css            0.33 KiB           0.23 KiB

MD5 (dist/js/app.0a4bb3ac.js) = 6e3c442893421e0803d507bcf81e9163

MD5 (../vue-cli-different-contentHash-demo/dist/js/app.d7be3b8a.js) = 6e3c442893421e0803d507bcf81e9163

---
I think it should only be related to the content.

**Comment by sodatea** [comment]
There's an undocumented option in `@vue/babel-preset-app` called `absoluteRuntime`.
See https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/babel-preset-app/index.js#L60-L67
https://babeljs.io/docs/en/babel-plugin-transform-runtime#absoluteruntime
