### ISSUE TITLE
Vue packages version mismatch

### ISSUE THREAD

**Issue by vdcrea** [vuejs/vue-cli#4394]
### Version
3.9.3

### Environment info
```
Mac OSX
node 8.9.0
npm 6.1.0
```

### Steps to reproduce
Type in terminal:

npm install -g @vue/cli

vue create project

### What is expected?
Usual perfect bootstrap of a new vue project

### What is actually happening?
Error:

Vue packages version mismatch:

- vue@2.5.17 (/Users/vincentdupont/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/Users/vincentdupont/.nvm/versions/node/v8.9.0/lib/node_modules/@vue/cli/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

**Comment by sodatea** [comment]
Why do you have a `node_modules` in your home directory?
I think it's interfering with the global `@vue/cli` installation somehow, though I can't reproduce this issue.

**Comment by vdcrea** [comment]
Thank you very very much, that was the issue. Removing the home/node_modules folder make the vue cli works correctly now.

**Comment by seifip** [comment]
On Windows the solution is to remove `node_modules` from your user directory.

**Comment by Jesonhu** [comment]
On Windows remove `node_modules` is a solution. but if i had install some other global package by npm. that solution is costly. 
so my soltion is remove `node_modules/vue` folder if it exist then `npm install -g @vue/cli` again.

environment(has error):
os: windows
vue: 2.5.6

**Comment by evansxper** [comment]
i deleted the node_module and it worked perfectly !!!...awsome try that

**Comment by silvio-e** [comment]
On a Mac using Yarn I had a `node_modules` folder in `/Users/myuser/.config/yarn/global/` . Deleting that and the `yarn.lock` and then do a `yarn global add @vue/cli` solved the problem for me.

**Comment by Versus2017** [comment]
remove `node_modules ` and  `yarn.lock` in `/Users/myuser/.config/yarn/global/ ` solved my issue. thanks very much~

**Comment by thedamon** [comment]
but... where are globally installed packages supposed to live? it makes sense that folder should exist

**Comment by eddjimlab** [comment]
Thanks
node_modules in home directory
