### ISSUE TITLE
Option of choosing semicolons in template files?

### ISSUE THREAD

**Issue by sohamkamani** [vuejs/vue-cli#44]
I understand that the creators of vue do not use semi colons as a convention, and that is completely fine. However, some teams, including mine, have adopted the use of semicolons as a convention as well. 
It would be great if we could have the option of choosing which convention we want to use, because I really love the official template, but have to manually add semicolons everywhere in the code to catch up.

Perhaps something like a `--semicolons` flag, or we could also include it in #5 . I would love to contribute towards this effort. Thoughts?

**Comment by yyx990803** [comment]
You can replace the eslint config with anything you like (and fork the
official templates if you want to)

**Comment by sohamkamani** [comment]
Alright, sounds good. Thanks :)

**Comment by martynchamberlin** [comment]
Here's the syntax to add to `.eslintrc` to do what @sohamkamani is asking:

```
"rules": {
  "semi": 0,
}
```

**Comment by ryanouyang** [comment]
Here's the config for someone prefer use semi add to `package.json`. 
```JSON
"eslintConfig": {
  "rules": {
    "semi": ["warn", "always"]
  }
}
```
