### ISSUE TITLE
request: vue init without subfolder

### ISSUE THREAD

**Issue by karlpokus** [vuejs/vue-cli#440]
Hi!

Is there a way to do `vue init webpack .` and have the project initialize in the `pwd` without creating a subfolder? I often have a repo already created and it's a drag to move all files one level up. This makes using an api-server (at top level) serving from `/dist` much simpler.

**Comment by LinusBorg** [comment]
Yes, that command works just like you want it to. Haver you actually tried it?

**Comment by karlpokus** [comment]
OMG! I'm an idiot. Sorry.
