### ISSUE TITLE
Add documentation for `css.extract` object configuration

### ISSUE THREAD

**Issue by Etheryte** [vuejs/vue-cli#4401]
### What problem does this feature solve?
Currently, [the docs for `css.extract`](https://cli.vuejs.org/config/#css-extract) state that it's of type `boolean | Object`.  
However, valid values for the object-based configuration are not explained nor are there any details on where to look for further info.  

I'd assume the library used is [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin), but right now it isn't clear from the documentation.

### What does the proposed change look like?
Please either add a link to external documentation or add a brief description inline.

**Comment by NataliaTepluhina** [comment]
Closing this as related PR was merged.
