### ISSUE TITLE
ValidationError: "templatedURLs" is not a supported parameter.

### ISSUE THREAD

**Issue by Janne252** [vuejs/vue-cli#4406]
### Version
3.10.0

### Reproduction link
[https://github.com/Janne252/vue-cli-pwa-workbox-options-templated-urls-issue](https://github.com/Janne252/vue-cli-pwa-workbox-options-templated-urls-issue)

### Environment info
```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 10.16.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.267.0
  npmPackages:
    @vue/cli-overlay:  3.10.0
    @vue/cli-plugin-pwa: ^3.10.0 => 3.10.0
    @vue/cli-service: ^3.10.0 => 3.10.0
    @vue/cli-shared-utils:  3.10.0
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
First-time setup:
```bash
npm install
```
Issue reproduction:
```bash
npm run build
```

### What is expected?
`npm run build` is expected to finish without errors.

### What is actually happening?
`npm run build` results in an error:

> ValidationError: "templatedURLs" is not a supported parameter.

---
The vue project was created using `vue create`. When prompted with feature selection, manual features was selected and only `pwa` was enabled in the feature list.

**Comment by sodatea** [comment]
`@vue/cli-plugin-pwa` v3 uses workbox v3 underlying and `templatedURLs` is only available for workbox v4. Please either use the legacy `templatedUrls` option in v3 or update to `@vue/cli-plugin-pwa` v4 beta.
