### ISSUE TITLE
插件 generator.js 方法支持异步方法

### ISSUE THREAD

**Issue by F-happy** [vuejs/vue-cli#4408]
### What problem does this feature solve?
现在我开发的插件执行Generator的时候如果exports的是一个async函数的话，里面的api.extendPackage 方法就无法正常使用了，

// generator.js
module.exports = async (api, options, rootOptions) => {
   await downloadTemplate();

   api.extendPackage({ dependencies: dependenciesMap }); // not work
}

// generator.js
module.exports = async (api, options, rootOptions) => {
 
   api.extendPackage({ dependencies: dependenciesMap }); // work ok
}

### What does the proposed API look like?
支持async函数

**Comment by sodatea** [comment]
谢谢建议，这个功能 4.0 beta 里已经支持了，backport 到 3.0 分支稍微有点麻烦，即使要支持的话我们也会在本月 4.0 正式版发布后再做，还请耐心等待。

**Comment by frontHu** [comment]
我也遇到了这个需求，有木有什么插件可以解决。是4.0发布后支持，那么3.x的是否还支持。
