### ISSUE TITLE
stylus global import not work!

### ISSUE THREAD

**Issue by BusyHe** [vuejs/vue-cli#441]
i use stylus ,

```
min.styl
$main-color = #000000
```

```
App.vue
  @import "../assets/min.styl"
```

```
Holle.vue
  .button
      $main-color
```

holle.vue can't find $main-color
what can i do

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

--- 

I think you have to import the stylus file in the style section

**Comment by BusyHe** [comment]
@posva I don't want to do in every vue file,Is any other way to do

**Comment by posva** [comment]
Not that I know. You should search about how to do it in plain stylus
files, but it's not related to Vue

**Comment by syntacticsolutions** [comment]
but it is related to the vue-cli. Importing fonts doesn't work either.

**Comment by sky790312** [comment]
In cli2 webpack's setting like following: 

plugins: [
    new webpack.LoaderOptionsPlugin({
      options: {
        stylus: {
          import: [path.resolve(__dirname, '../src/stylus/variables.styl'), path.resolve(__dirname, '../src/stylus/extends.styl')]
        }
      }
    })
  ]

In cli3 you can add file 'vue.config.js' and handle your webpack's setting like:

// vue.config.js
var path = require('path')
var webpack = require('webpack')

module.exports = {
  configureWebpack: {
    plugins: [
      new webpack.LoaderOptionsPlugin({
        options: {
          stylus: {
            import: [path.resolve(__dirname, './src/stylus/variables.styl'), path.resolve(__dirname, './src/stylus/extends.styl')]
          }
        }
      })
    ]
  }
}

It works for me.

**Comment by tamm** [comment]
I just wanted to leave a note to say @sky790312 's comment above helped me figure this out. 

My `vue.config.js` which works
```
// vue.config.js
var path = require('path');
module.exports = {
  css: {
    loaderOptions: {
      stylus: {
        import: [path.resolve(__dirname, "src/stylus/variables")]
      }
    }
  }
};
```

**Comment by tomderudder** [comment]
![image](https://user-images.githubusercontent.com/48674816/64892718-8016b400-d675-11e9-9dd1-9ffadfbc6f9d.png)
