### ISSUE TITLE
Vue config Externals Array Syntax does not work

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vue-cli#4413]
### Version
4.0.0-alpha.5

### Environment info
```
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 11.13.0
    Yarn: 1.16.0
    npm: 6.7.0
  Browsers:
    Edge: 44.18362.1.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Using a `vue.config.js` like this: 

```js
module.exports = {
  chainWebpack: config => {
    config.externals([
      /@namespace/,
      {
        'jquery': 'jquery',
        'test': 'test',
      },
    ])
  },
}
```

### What is expected?
All the `config.externals` should be externalized.

### What is actually happening?
None of the libraries are externalized, because vue-cli (?) changes the `externals` to:

```js
{ '0': /@namespace/,
  '1': { jquery: 'jquery', test: 'test' },
  vue: { commonjs: 'vue', commonjs2: 'vue', root: 'Vue' } }
```

This causes the `node_modules\webpack\lib\ExternalModuleFactoryPlugin.js`to *ignore*  the `externals`.

---
I'm not sure if this is caused by the cli or by webpack-chain, but since vue-cli is adding the `vue` property to the object, I'm guessing that it's vue-cli's doing.

**Comment by sodatea** [comment]
Thanks for submitting this issue! Due to our limited time, we ask you to include a reproduction link to a minimal full reproduction of your problem (for example in a GitHub repository) so we can find what is causing the issue. Thank you for your understanding!

**Comment by johannes-z** [comment]
@sodatea Sure, here's the repro: https://github.com/johannes-z/vue-cli-externals
Just `npm install` and `npm run build`. The `test.umd-report.html` shows that the external dependencies are still added to the bundle.

**Comment by johannes-z** [comment]
@sodatea Hi, are you sure this is resolved? I just updated the RC0 and it has wrong externals:

```
λ vue -V
4.0.0-rc.0
```
