### ISSUE TITLE
A simple question about how things were done

### ISSUE THREAD

**Issue by BRKsDeadPool** [vuejs/vue-cli#442]
## First of all, thanks for the incredible tool available to us.

I recently had an idea about creating projects based on environment variables, which could be easy to set up even if you're not a developer, and then I remembered *vue-cli* doing just that with meta.js (or meta.json), and would like to know how this tool works, if I needed a simple project that used only html, css and a bit of js, what would it take ?

I'm asking because after analyzing your source code for a few hours, I realized that there are several dependencies that I will not really need, since I just need to create templates based on customizable variables (like in meta.js)

**Comment by posva** [comment]
you can use vue-cli for that but there're other alternatives like yeoman that are agnostic
