### ISSUE TITLE
vue2 + vue router2  lazyload not work   ios7

### ISSUE THREAD

**Issue by docikaci** [vuejs/vue-cli#443]
ios 7 下  

两种方式都不加载，在ios 7.0  7.1下

1：System.import方式
![image](https://cloud.githubusercontent.com/assets/7788102/25304271/9c4f83e4-2796-11e7-8eae-af4493825ccd.png)
export default new Router({
  routes: [
    {
        path: '/new',
        name: 'New',
        component: resolve => System.import('../views/new.vue')
    }
  ]
})

2：require.ensure方式
![image](https://cloud.githubusercontent.com/assets/7788102/25304280/d46d4180-2796-11e7-9183-c7ec2cfe0b9b.png)

**Comment by docikaci** [comment]
add：  
同步方式可以加载 打包之后就是一个  app.md5.js

**Comment by egoist** [comment]
Please ask support questions on stackoverflow or forums.
