### ISSUE TITLE
Adding an extra options object to sass-loader

### ISSUE THREAD

**Issue by profyt** [vuejs/vue-cli#4434]
### Version
3.9.3

### Environment info
```
System:
OS: Linux 4.20 Linux Mint 19.1 (Tessa)
CPU: (4) x64 AMD Athlon 200GE with Radeon Vega Graphics
Binaries:
Node: 11.13.0 - ~/.nvm/versions/node/v11.13.0/bin/node
Yarn: Not Found
npm: 6.7.0 - ~/.nvm/versions/node/v11.13.0/bin/npm
Browsers:
Chrome: 75.0.3770.80
Firefox: 67.0
npmGlobalPackages:
@vue/cli: 3.9.3
```

### Steps to reproduce
Add in vue.config.js options for sass-loader.
![image](https://user-images.githubusercontent.com/39933434/63005413-ad214c80-bea6-11e9-8727-4ec5d65fb9f3.png)

### What is expected?
An option with data will be added to the loader options:
`{ loader: 'sass-loader', options: { sourceMap: false, ......, data: '@import "~@/variables.scss";' }, }`

### What is actually happening?
A second options object is created, to which changes are added from vue.config:

`{ loader: 'sass-loader', options: { sourceMap: false, ...... }, options: { data: '@import "~@/variables.scss";' }, }`

**Comment by LinusBorg** [comment]
Please provide a reproduction as is required.

How did you check for the duplicate object?

**Comment by profyt** [comment]
> How did you check for the duplicate object?


After changing the configuration, I used vue-cli-service inspect. I found a rule in it for which I made changes and saw a duplication of the options object there.


Here is the repository with the configuration; during inspection, see the sass section, there will be double options everywhere.
https://github.com/profyt/Vue-cli-duplicate-options

**Comment by LinusBorg** [comment]
Thanks, we'll check it out

**Comment by sodatea** [comment]
```diff
  css: {
    loaderOptions: {
      sass: {
-        options: {
          data: `@import "~@/variables.scss";`
-        }
      },
    }
  }
```

The example in our documentation does not have the extra `options`.
See https://cli.vuejs.org/guide/css.html#passing-options-to-pre-processor-loaders

**Comment by profyt** [comment]
> ```diff
>   css: {
>     loaderOptions: {
>       sass: {
> -        options: {
>           data: `@import "~@/variables.scss";`
> -        }
>       },
>     }
>   }
> ```


But this option will not be added to the settings. It will be added after the options object, therefore the configuration will not be working!
https://github.com/webpack-contrib/sass-loader

**Comment by sodatea** [comment]
I mean, if you do this, the options will be merged correctly:

```
  css: {
    loaderOptions: {
      sass: {
        data: `@import "~@/variables.scss";`
      },
    }
  }
```

**Comment by profyt** [comment]
I tried to do as you showed. But as a result, Data is not added to the options, but after them.

**Comment by sodatea** [comment]
It works on my machine after modifying your reproduction repository.
![image](https://user-images.githubusercontent.com/3277634/63413709-d3a63100-c42c-11e9-9ebd-39792607335b.png)

**Comment by sodatea** [comment]
The modification I suggested was that this line in your config is extraneous:
https://github.com/profyt/Vue-cli-duplicate-options/blob/7965fceee9d477fd5c304c8fab0395f2457aeb66/vue.config.js#L17
