### ISSUE TITLE
Mac环境问题

### ISSUE THREAD

**Issue by mrerhuo** [vuejs/vue-cli#4435]
### Version
3.10.0

### Reproduction link
[htttp://localhost:9090](htttp://localhost:9090)

### Environment info
```
Mac 最新版本 vscode最新版本
```

### Steps to reproduce
安装了全局的vuecli然后呢，mac终端正常能vue --version,但是使用vscode就无法运行该命令。

### What is expected?
安装了全局的vuecli然后呢，mac终端正常能vue --version,但是使用vscode就无法运行该命令。

### What is actually happening?
安装了全局的vuecli然后呢，mac终端正常能vue --version,但是使用vscode就无法运行该命令。

---
安装了全局的vuecli然后呢，mac终端正常能vue --version,但是使用vscode就无法运行该命令。

**Comment by mrerhuo** [comment]
bash: vue: command not found

**Comment by Chenthy** [comment]
我寻思你这环境变量问题和vue-cli也没关系吧

**Comment by sodatea** [comment]
跟 Vue CLI 无关，我能给的建议只有重启 VSCode 试试。
