### ISSUE TITLE
Can not disable hotReload

### ISSUE THREAD

**Issue by doncatnip** [vuejs/vue-cli#4444]
Hello. I have been looking through the web for something that should be really simple: how to disable hotReload in a standard project that has been initialized with vue-cli.
The only official piece of documentation is here:
https://vue-loader.vuejs.org/guide/hot-reload.html#usage
However, it does not say anywhere where exactly hotReload goes. If I put it into my vue config 
in package.json like so:

    "vue": {
        "publicPath": "/app/",
        "hotReload": false,

It just tells me that the option hotReload is not allowed. 

Another one trying to find a solution:
https://stackoverflow.com/questions/51844289/turn-off-hot-reload-on-project-started-with-vue-cli-3-webpack-4-15-1

This is way too obfuscated.

**Comment by sodatea** [comment]
https://github.com/vuejs/vue-cli/issues/4368#issuecomment-515532738
