### ISSUE TITLE
plugin-unit-jest "todo is not a function" error

### ISSUE THREAD

**Issue by ShaunaGordon** [vuejs/vue-cli#4446]
### Version
3.10.0

### Reproduction link
[https://github.com/ShaunaGordon/vue-cli-jest-bug](https://github.com/ShaunaGordon/vue-cli-jest-bug)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 66.0.5
    Safari: 12.1.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.10.0
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.10.0
    @vue/cli-plugin-babel: ^3.10.0 => 3.10.0
    @vue/cli-plugin-eslint: ^3.10.0 => 3.10.0
    @vue/cli-plugin-unit-jest: ^3.10.0 => 3.10.0
    @vue/cli-service: ^3.10.0 => 3.10.0
    @vue/cli-shared-utils:  3.10.0
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3 (4.7.1)
    jest-serializer-vue:  2.0.2
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0 (2.0.3)
    vue-hot-reload-api:  2.3.3
    vue-jest:  3.0.4
    vue-loader:  15.7.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Use vue-cli to create a project with default plugins

vue add unit-jest

Write test with a test.todo (or it.todo) format (https://jestjs.io/docs/en/api#testtodoname)

Run test

### What is expected?
Test should properly read todo functions and report them accordingly

### What is actually happening?
Tests fail on both test.todo() and it.todo() with "test/it.todo is not a function"

---
I use the it.todo construct all of the time in my projects (which have historically not used vue-cli to set up) and ran into this when I tried my tried-and-true test scaffold with the Vue-CLI setup.

**Comment by sodatea** [comment]
It was introduced in Jest 24 and Vue CLI 3 uses Jest 23 underlyingly.
You can use v4 beta for this feature for now.
