### ISSUE TITLE
vue-cli3创建less工程，npm run serve 无法运行

### ISSUE THREAD

**Issue by lulinglm** [vuejs/vue-cli#4449]
### Version
3.10.0

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Environment info
```
 System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 66.0.5
    Safari: 12.1.2
  npmGlobalPackages:
    @vue/cli: 3.10.0
```

### Steps to reproduce
vue create xx
选择css 选择less
npm run serve 无法运行报错
具体错误日志贴在下文;
使用旧工程的package-lock.json安装则可以正常使用，
怀疑是库更新，造成npm包之间不兼容
文件对比库不同：
"@babel": "7.0.0" 升级到  "7.5.5",

### What is expected?
能够正常运行

### What is actually happening?

 ERROR  Failed to compile with 2 errors                               1:27:52 PM

 error  in ./src/App.vue?vue&type=style&index=0&lang=less&

Module build failed (from ./node_modules/less-loader/dist/cjs.js):

Class constructor FileManager cannot be invoked without 'new'
      in undefined (line undefined, column undefined)

 @ ./node_modules/vue-style-loader??ref--10-oneOf-1-0!./node_modules/css-loader??ref--10-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--10-oneOf-1-2!./node_modules/less-loader/dist/cjs.js??ref--10-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=less& 4:14-416 14:3-18:5 15:22-424
 @ ./src/App.vue?vue&type=style&index=0&lang=less&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.242.65.184:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/components/HelloWorld.vue?vue&type=style&index=0&id=469af010&scoped=true&lang=less&

Module build failed (from ./node_modules/less-loader/dist/cjs.js):

Class constructor FileManager cannot be invoked without 'new'
      in undefined (line undefined, column undefined)

 @ ./node_modules/vue-style-loader??ref--10-oneOf-1-0!./node_modules/css-loader??ref--10-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--10-oneOf-1-2!./node_modules/less-loader/dist/cjs.js??ref--10-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=style&index=0&id=469af010&scoped=true&lang=less& 4:14-465 14:3-18:5 15:22-473
 @ ./src/components/HelloWorld.vue?vue&type=style&index=0&id=469af010&scoped=true&lang=less&
 @ ./src/components/HelloWorld.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.242.65.184:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by social4hyq** [comment]
less 的问题，具体参看 https://github.com/less/less.js/issues/3414

**Comment by finishergithub2** [comment]
解决方法：
1. 把node_modules目录删除
2. 修改package.json文件，具体为 "less": "3.9.0",  (之前是  "less": "^3.0.4",)
3. 重新全部依赖包  yarn  （或  npm install）
即可解决

原因：
less依赖包升级到3.10.0有bug导致的

**Comment by lulinglm** [comment]
tanks
