### ISSUE TITLE
async returns and Promises have different prototypes in initial template

### ISSUE THREAD

**Issue by abbradar** [vuejs/vue-cli#4456]
### Version
3.10.0

### Reproduction link
[https://github.com/abbradar/promise-example/](https://github.com/abbradar/promise-example/)

### Environment info
```
Environment Info:

  System:
    OS: Linux 5.2 NixOS 19.09.git.6bd7279 (Loris) 19.09.git.6bd7279 (Loris)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 10.16.0 - /usr/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 68.0.1
  npmPackages:
    @vue/cli: ^3.10.0 => 3.10.0 
    @vue/cli-shared-utils:  3.10.0 
    @vue/cli-ui:  3.10.0 
    @vue/cli-ui-addon-webpack:  3.10.0 
    @vue/cli-ui-addon-widgets:  3.10.0 
    typescript:  3.5.3 
    vue-cli-plugin-apollo:  0.20.0 
    vue-jscodeshift-adapter:  2.0.2 
    vue-sfc-descriptor-to-string:  1.0.0 
    vue-template-compiler:  2.6.10 
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
1. Run `npm run serve`;
2. Open website in a browser;
3. Check console log; observe `false` in a sanity check.

### What is expected?
Only one Promise implementation is used for Promise and for transpiling `async` functions.

### What is actually happening?
Two different Promise implementations can be seen - native one and a polyfilled one.

---
The project is freshly generated with `vue create`. I fixed this by moving to `fast-async` with this `babel.config.js`:

```
module.exports = {
  presets: [
    ['@vue/app', {
      "exclude": ["babel-plugin-transform-async-to-generator", "babel-plugin-transform-regenerator"]
    }]
  ],
  "plugins": [
    ["module:fast-async", {
      "spec": true,
      "useRuntimeModule": false
    }]
  ]
}
```

**Comment by LinusBorg** [comment]
Given that this is the default behaviour of the polyfills / tranforms done by babel's preset-env, what's the drawback?

Specifically because that other plugin that you want to use isn't "official", and hasn't seen any commits since Oct 2018, which of course may simply be an indicator that it's stable - or that it's kind of unmaintained.

**Comment by abbradar** [comment]
I didn't try it with raw preset-env, should I report this issue to them instead?

To be clear my idea isn't to use fast-async by default, that's just my way out of the problem. I'm not sure how to fix this problem in a better way but having two different Promise implementations silently used in a project feels very wrong. 

On August 21, 2019 9:53:25 AM GMT+02:00, "Thorsten Lünborg" <notifications@github.com> wrote:
>Given that this is the default behaviour of the polyfills / tranforms
>done by babel's preset-env, what's the drawback?
>
>Specifically because that other plugin that you want to use isn't
>"official", and hasn't seen any commits since Oct 2018, which of course
>may simply be an indicator that it's stable - or that it's kind of
>unmaintained.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vuejs/vue-cli/issues/4456#issuecomment-523341624

-- 
Nikolay.

**Comment by sodatea** [comment]
Seems no longer reproducible?
