### ISSUE TITLE
portfinder1.0.22版本导致vue-cli-service servey启动后，服务端口变成了随机端口的问题

### ISSUE THREAD

**Issue by qyvip** [vuejs/vue-cli#4460]
### Version
3.10.0

### Environment info
```
mac 
```

### Steps to reproduce
无

### What is expected?
The configuration file specifies port 8000, which should start at 8000, or 8001, or something like that

### What is actually happening?
The port is random, like 37301, and it's different every time it starts

---
Portfinder1.0.22, temporarily limited to 1.0.21

**Comment by Amiedon** [comment]
i ran into this problem ,too. This problem is caused by portfinder 1.0.22, which updated in Oct 19th.

**Comment by tuhe32** [comment]
I also encountered this problem, how to solve it？

**Comment by alanwhy** [comment]
如何解决这个问题呢？

**Comment by iamobj** [comment]
Just now, I also met, I don’t know what to do.

**Comment by bullBeer** [comment]
我也遇到这个问题~

**Comment by 383366204** [comment]
how to fix it ?

**Comment by hlbj105** [comment]
我的也是，随机端口，设置的无效了

**Comment by 383366204** [comment]
是新版本的portfinder有bug，安装旧版的就可以了
 npm install portfinder@1.0.21

**Comment by hlbj105** [comment]
@383366204 好像也不行

**Comment by ArcherGu** [comment]
> @383366204 好像也不行

先`npm install portfinder@1.0.21`，再正常`[c]npm i`

**Comment by kinoshitaringo** [comment]
到node_modules/@vue/cli-service/package.json 修改依赖 "portfinder": "1.0.21"，去掉^号，选择版本为1.0.21，然后在该目录下install。

**Comment by feixiang-aa** [comment]
> 是新版本的portfinder有bug，安装旧版的就可以了
> npm install portfinder@1.0.21

npm install portfinder@1.0.21之后，当前文件夹是8080端口了，但是重新创建脚手架文件夹 还是随机端口，请问该怎么办？

**Comment by 383366204** [comment]
> > 是新版本的portfinder有bug，安装旧版的就可以了
> > npm install portfinder@1.0.21
> 
> npm install portfinder@1.0.21之后，当前文件夹是8080端口了，但是重新创建脚手架文件夹 还是随机端口，请问该怎么办？

可能还是引用了新版的portfinder吧

**Comment by reducm** [comment]
+1 端口变化导致websocket请求的地址端口一直出错

**Comment by purestart** [comment]
npm install portfinder@1.0.21自己本地 可以解决但是别人拉了代码install后还是有问题，坐等官方解决

**Comment by GZWZC** [comment]
> > @383366204 好像也不行
> 
> 先`npm install portfinder@1.0.21`，再正常`[c]npm i`


刚clone vue-element-admin，devServer配好了port，但是也是随机端口。
这种方法可以解决

**Comment by whq920729** [comment]
> > > @383366204 好像也不行
> > 
> > 
> > 先`npm install portfinder@1.0.21`，再正常`[c]npm i`
> 
> 刚clone vue-element-admin，devServer配好了port，但是也是随机端口。
> 这种方法可以解决

确定可以？我这不行啊，依然还是有两个版本的portfinder

**Comment by sodatea** [comment]
portfinder 1.0.23 修复了这个问题，请删除项目里的 package-lock.json 或者 yarn.lock 然后重新安装依赖
