### ISSUE TITLE
npm run serve 下 css.extract 设置为 true 后 IE11 运行错误

### ISSUE THREAD

**Issue by smalike** [vuejs/vue-cli#4461]
### Version
3.10.0

### Environment info
```
mac
nodejs：8
vue：2
```

### Steps to reproduce
1. css.extract 设置为 true 

2. 运行 npm run serve

3. IE11 运行

### What is expected?
没有问题

### What is actually happening?
貌似没有转换尖头函数

**Comment by sodatea** [comment]
请提供复现代码。

**Comment by yj-ang** [comment]
我也遇到相同的问题，我找到了root cause，是mini-css-extract-plugin的[dependency问题](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/385)，目前已降级处理。

**Comment by smalike** [comment]
我的处理方式是增加 webpack plugin `"mini-css-extract-plugin": "^0.8.0",` 就可以了
