### ISSUE TITLE
今天用vue create demo创建一个项目，启动demo报错（2019年8月19日12:45:21）

### ISSUE THREAD

**Issue by y-e-y-u** [vuejs/vue-cli#4462]
上面是报错，下面是版本
![image](https://user-images.githubusercontent.com/26995987/63239739-5093a800-c27f-11e9-99f0-c06e9dea01ed.png)

![image](https://user-images.githubusercontent.com/26995987/63239759-5ee1c400-c27f-11e9-9fe8-e4aa0ed80cd6.png)

**Comment by sodatea** [comment]
```
npm install -D less-loader@5
```

**Comment by y-e-y-u** [comment]
> ```
> npm install -D less-loader@5
> ```

谢谢
