### ISSUE TITLE
vue-cli3 set port  is invalid

### ISSUE THREAD

**Issue by fchangjun** [vuejs/vue-cli#4464]
After creating the project today through ue-cli3.0, we found that we could not set the port property either on the command line or in the vue.config.js file，A port is a value in a range, not a set port。
It turns out that the plugin that searched for valid ports was updated two days ago and returned valid ports that were not set as default ports but in other ranges
![port](https://user-images.githubusercontent.com/9472901/63276752-96c82600-c2d6-11e9-9ce1-8f39b81125f4.jpg)
![portfinder](https://user-images.githubusercontent.com/9472901/63276756-9760bc80-c2d6-11e9-8ce5-c81fc6dae766.png)

**Comment by LinusBorg** [comment]
duplicate of #4460 #4452
