### ISSUE TITLE
multi-page模式下开启服务无法列出dist目录下的文件夹及文件，显示Cannot Get /，该如何解决

### ISSUE THREAD

**Issue by tjHong** [vuejs/vue-cli#4475]
### Version
3.10.0

### Reproduction link
[https://github.com/tjHong/vue_multipage](https://github.com/tjHong/vue_multipage)

### Environment info
```
node v10.16.0
npm v6.10.2
```

### Steps to reproduce
执行npm run serve，
访问localhost:8080

### What is expected?
开启服务后希望在浏览器中看到dist文件下的文件目录列表

### What is actually happening?
显示Cannot Get /

---
vue-cli-service内部具体对webpack-dev-server做了哪些重置？

**Comment by sodatea** [comment]
webpack-dev-server 也没这个功能吧？

**Comment by tjHong** [comment]
> webpack-dev-server 也没这个功能吧？

contentBase: 'dist'时是可以列出dist下所有文件夹的，类似gulp开启的服务那种

**Comment by sodatea** [comment]
想了一下，这个功能暂不考虑支持。
功能设计上意义不大、边界情况复杂（比如多页应用使用了 vue-router 等……），目前没有精力维护。

**Comment by tjHong** [comment]
> 想了一下，这个功能暂不考虑支持。
> 功能设计上意义不大、边界情况复杂（比如多页应用使用了 vue-router 等……），目前没有精力维护。

谢谢解答和建议
