### ISSUE TITLE
Vue cli serve does not import SFC files with capital letters in extension (.vue is fine whereas .Vue is not)

### ISSUE THREAD

**Issue by aledujke** [vuejs/vue-cli#4476]
### Version
3.10.0

### Reproduction link
[https://github.com/aledujke/vue_cli_test](https://github.com/aledujke/vue_cli_test)

### Environment info
```
PS C:\Users\dusan.aleksic\projects\test_vue> vue info     
                                                          
Environment Info:                                         
                                                          
  System:                                                 
    OS: Windows 10                                        
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:                                               
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE      
    Yarn: Not Found                                       
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD          
  Browsers:                                               
    Edge: 42.17134.1.0                                    
  npmPackages:                                            
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0         
    @vue/babel-plugin-transform-vue-jsx:  1.0.0           
    @vue/babel-preset-app:  3.10.0                        
    @vue/babel-preset-jsx:  1.1.0                         
    @vue/babel-sugar-functional-vue:  1.0.0               
    @vue/babel-sugar-inject-h:  1.0.0                     
    @vue/babel-sugar-v-model:  1.0.0                      
    @vue/babel-sugar-v-on:  1.1.0                         
    @vue/cli-overlay:  3.10.0                             
    @vue/cli-plugin-babel: ^3.10.0 => 3.10.0              
    @vue/cli-plugin-eslint: ^3.10.0 => 3.10.0             
    @vue/cli-service: ^3.10.0 => 3.10.0                   
    @vue/cli-shared-utils:  3.10.0                        
    @vue/component-compiler-utils:  2.6.0 (3.0.0)         
    @vue/eslint-config-prettier: ^5.0.0 => 5.0.0          
    @vue/preload-webpack-plugin:  1.1.1                   
    @vue/web-component-wrapper:  1.2.0                    
    eslint-plugin-vue: ^5.0.0 => 5.2.3 (4.7.1)            
    vue: ^2.6.10 => 2.6.10                                
    vue-eslint-parser:  2.0.3 (5.0.0)                     
    vue-hot-reload-api:  2.3.3                            
    vue-loader:  15.7.1                                   
    vue-router: ^3.0.3 => 3.1.2                           
    vue-style-loader:  4.1.2                              
    vue-template-compiler: ^2.6.10 => 2.6.10              
    vue-template-es2015-compiler:  1.9.1                  
    vuex: ^3.0.1 => 3.1.1                                 
  npmGlobalPackages:                                      
    @vue/cli: Not Found
```

### Steps to reproduce
Create a new vue app with `vue create`, rename one of the SFC files to `something.Vue` instead `someting.vue` (capitilize one of the letters in extension)

run `npm run serve`

### What is expected?
That SFC files with capital letters in extension are included in build

### What is actually happening?
Files that have capital letter in their file extension are not being imported in build

**Comment by aledujke** [comment]
In the repo that I linked this file is causing the problem:
https://github.com/aledujke/vue_cli_test/blob/master/src/components/HelloWorld.Vue

If i change it's name to `HelloWorld.vue` both `npm run serve` and `npm run build` will work.

**Comment by LinusBorg** [comment]
Some file systems are cases sensitive, so import names/paths are case-sensitive as well. That's just how it works for imports, nothing vue-cli specific about that.

**Comment by aledujke** [comment]
Ah dang I did not explain properly what I mean... and the repo is wrong too. I'll update it.

When I try and import SFC without specifying it's extension like this:
`import HelloWorld from "@/components/HelloWorld"` it will not work unless the extension is in lower case

**Comment by aledujke** [comment]
I realize now that this might be desired behavior? It seems that plugin `CaseSensitivePathsPlugin` is blocking these includes... in which case it would be nice if this is mentioned somewhere.

![image](https://user-images.githubusercontent.com/235002/63438009-ed934400-c42b-11e9-85fc-dd108b46448a.png)

**Comment by LinusBorg** [comment]
Well yeah, I think you could call it desired behaviour. On some file systems, these would be two different files:
* `HelloWorld.vue`
* `HelloWorld.Vue`

oh, we could also have:
`* HelloWorld.vUe`

and countless permutations. Which is why this plugin is used - it makes sure all paths match in case all the time.

Combined with how webpack resolves file extensions (it tacks the ones it is aware of  - .js, .vue ... to the path's end), you get a lowercase extension, which triggers the plugin.
