### ISSUE TITLE
vue.config.js esm support

### ISSUE THREAD

**Issue by patarapolw** [vuejs/vue-cli#4477]
### What problem does this feature solve?
Instead of

```javascript
require = require("esm")(module);
const { pugFilters } = require("./src/plugins/render");
```

I can do  `import { .pugFilter } from "./src/plugins/render"` directly.

Note that I have to do ES6 import from source to enable import in other places in TypeScript.

This is to be on par with [Webpack Node API](https://webpack.js.org/api/node/#installation)

### What does the proposed API look like?
```javascript
// vue.config.js
import { .pugFilter } from "./src/plugins/render";
```

**Comment by sodatea** [comment]
There are two possible outcomes for this issue:
1. For support of a custom module format without changing the file extension, we'd preload a module loader before requiring the config file. We may implement a CLI option for this feature, like [the `config-register` option in `webpack-cli`](https://github.com/webpack/webpack-cli/commit/ab9421136887b7e9e10f25a39b59fb32f07b5037).
2. For support of a custom module format with a custom file extension, we can use [the `node-interpret` package](https://github.com/gulpjs/interpret).

**Comment by corydorning53** [comment]
is there plans to allow this now that node v14+ allows esm?

**Comment by gmichaeljaison** [comment]
Is this released yet? Which version of `vue-cli` supports this?

**Comment by kid1412621** [comment]
> Is this released yet? Which version of `vue-cli` supports this?

I managed to change filename to `vue.config.mjs` to use esm. It could work. But somehow the settings about css in the file doesn't take effect.

**Comment by JinPengGeng** [comment]
is there any update for esm support ??
