### ISSUE TITLE
启动项目的时候出现These dependencies were not found:

### ISSUE THREAD

**Issue by waterwong** [vuejs/vue-cli#448]
![image](https://cloud.githubusercontent.com/assets/17227858/25513425/8d361402-2c07-11e7-9054-df013c63216e.png)

**Comment by posva** [comment]
Hi!
Please make sure to follow the [Issue Reporting Guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md#issue-reporting-guidelines) before opening an issue.
Thanks!
