### ISSUE TITLE
Support custom packageManager other than npm/yarn/pnpm.

### ISSUE THREAD

**Issue by zyy7259** [vuejs/vue-cli#4483]
### What problem does this feature solve?
Currently the --packageManager only supports npm/yarn/pnpm.

This feature will let the end user specify a custom node package manager.

The company I worked at uses a private packageManager. Right now I cannot find a way to use it with vue-cli to create my project.

### What does the proposed API look like?
--packageManager xxx

**Comment by zyy7259** [comment]
happy to send a PR

**Comment by Alex-Sokolov** [comment]
It would also be nice to be able to configure the package manager you are using via vue.config.js. For example, you usually use yarn everywhere, but sometimes you support projects where npm is used. And you don't want to delete yarn.lock and reinstall node_modules to avoid side-effects

**Comment by LinusBorg** [comment]
@zyy7259 how would you tackle the possibly different commands that some custom package manager might have? These would have to be mapped somehow, i.e. what command is the qeuivalent of "npm install"?

**Comment by sodatea** [comment]
@Alex-Sokolov in v4 we've refactored the package manager related stuff and it now infers the project manager from project lockfiles
https://github.com/vuejs/vue-cli/blob/91024a7843c28a82074152c57672d533c6a8ed5b/packages/%40vue/cli/lib/util/ProjectPackageManager.js#L70-L76

**Comment by sodatea** [comment]
If the subcommands are identical to npm, just use command-line alias (like, `alias npm="tnpm"`.

If not, it will surely increase our maintenance burden. We are not going to support custom package managers without a clear plan of future maintenance.

**Comment by zyy7259** [comment]
alias won't work with execa https://github.com/sindresorhus/execa/issues/100

**Comment by sodatea** [comment]
Okay…
Then we can make it a warning rather than an error for unknown package manager.

**Comment by zyy7259** [comment]
How about [use an env variable to specify the bin used by PackageManager](https://github.com/vuejs/vue-cli/pull/4620)

**Comment by sodatea** [comment]
Not necessary.
See the above snippets. We have 3 ways to determine the package manager to use, in the following order:
1. the command line `--packageManager` option
2. infer the command from the lockfile name in the project
3. the `packageManager` field in `~/.vuerc`

The problem of custom package manager is not how to specify it, but how to map the subcommands:
https://github.com/vuejs/vue-cli/blob/a42f83854388fe3cab4e471402c43e8e60b21989/packages/%40vue/cli/lib/util/ProjectPackageManager.js#L33-L52

So if we want to support such a feature, we need to turn this error into a warning and then use the `npm` subcommands as fallbacks. https://github.com/vuejs/vue-cli/blob/a42f83854388fe3cab4e471402c43e8e60b21989/packages/%40vue/cli/lib/util/ProjectPackageManager.js#L78-L81

**Comment by zyy7259** [comment]
How about this https://github.com/vuejs/vue-cli/pull/4621
