### ISSUE TITLE
Document default serve entry

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vuejs/vue-cli#4485]
### Version
3.11.0

### Reproduction link
[https://github.com/vuejs/vue-cli/blob/dev/docs/guide/cli-service.md#vue-cli-service-serve](https://github.com/vuejs/vue-cli/blob/dev/docs/guide/cli-service.md#vue-cli-service-serve)

### Environment info
```
docs
```

### Steps to reproduce
https://github.com/vuejs/vue-cli/blob/dev/docs/guide/cli-service.md#vue-cli-service-serve

The Vue-CLI-Service Serve does not document what the default entry point is.

### What is expected?
document entry

### What is actually happening?
not

---
no

**Comment by pavan-kalyan** [comment]
What is the default entry point ?

**Comment by jeneser** [comment]
Default: [`src/main.js`](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/base.js#L32) or [`src/main.ts`](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-typescript/index.js#L13) in TypeScript project. PR  #5558 . I document a clear hint, any suggestions?
