### ISSUE TITLE
optional-chaining syntax default support

### ISSUE THREAD

**Issue by ikarosu** [vuejs/vue-cli#4487]
### What problem does this feature solve?
这是一个常用的下一代ES语法，目前已经在stage-3阶段，现社区已有`@babel/plugin-proposal-optional-chaining`插件支持，每次新的Vue项目都需要手动安装并使用这个插件，我希望能够在该项目中默认支持。

主要是因为我今天安装了这个插件但却报缺少loader，可能和我使用了`vue-function-api`有关，这样一来我久暂时无法使用这个新的语法了

**The following is an English translation**

This is a commonly used next-generation ES syntax. It is currently in the stage-3 stage. The community now has the @babel/plugin-proposal-optional-chaining` plugin support. Every new Vue project needs to be manually installed and used. Plugin, I hope to be supported by default in this project.

Mainly because I installed this plugin today but I reported missing the loader, which may be related to my use of `vue-function-api`, so I can't use this new syntax for a long time.

### What does the proposed API look like?
最好v4的cli能默认支持现有的所有stage-3阶段的提案

The best v4 cli can support all existing stage-3 proposals by default.

**Comment by sodatea** [comment]
Sorry but we decide to only support standard ECMAScript, except for the class-properties & decorators proposals that are so widely used by Vue users.
optional-chaining will be supported once it makes its way into ES2020. Before that, you can manually add this plugin into your projects or create a preset for it.
