### ISSUE TITLE
跪求 cli3怎么配置才能写jsx  cli2.0配置个transform-vue-jsx  就好了，请问怎么配置，很急

### ISSUE THREAD

**Issue by livelyPeng** [vuejs/vue-cli#4496]
### What problem does this feature solve?
跪求 cli3怎么配置才能写jsx  cli2.0配置个transform-vue-jsx  就好了，请问怎么配置，很急

### What does the proposed API look like?
跪求 cli3怎么配置才能写jsx  cli2.0配置个transform-vue-jsx  就好了，请问怎么配置，很急

**Comment by sodatea** [comment]
我们的 GitHub issues 只用于 Bug 反馈和特性请求，如果有使用上的问题建议到[官方论坛](https://forum.vuejs.org/)、[Discord](https://chat.vuejs.org/)、[StackOverflow](http://stackoverflow.com/tags/vue.js) 或其他问答网站上提问。

---

直接写。默认生成的项目中，`@vue/babel-preset-app` 里已经帮你配置好 `@vue/babel-preset-jsx` 了。语法参考 https://github.com/vuejs/jsx

**Comment by livelyPeng** [comment]
不行啊




------------------ 原始邮件 ------------------
发件人: "Haoqun Jiang"<notifications@github.com>;
发送时间: 2019年8月24日(星期六) 晚上8:17
收件人: "vuejs/vue-cli"<vue-cli@noreply.github.com>;
抄送: "Simple love"<403802162@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vuejs/vue-cli] 跪求 cli3怎么配置才能写jsx  cli2.0配置个transform-vue-jsx  就好了，请问怎么配置，很急 (#4496)




我们的 GitHub issues 只用于 Bug 反馈和特性请求，如果有使用上的问题建议到官方论坛、Discord、StackOverflow 或其他问答网站上提问。
 
 
直接写。默认生成的项目中，@vue/babel-preset-app 里已经帮你配置好 @vue/babel-preset-jsx 了。语法参考 https://github.com/vuejs/jsx
