### ISSUE TITLE
This dependency was not found:  * ~entry in ./node_modules/@vue/cli-service/lib/commands/build/entry-lib.js

### ISSUE THREAD

**Issue by huashaoxu** [vuejs/vue-cli#4498]
This dependency was not found:  * ~entry in ./node_modules/@vue/cli-service/lib/commands/build/entry-lib.js

when i run “npm install --save ~entry”，npm tips “no ~entry” exit！

how should i solve this problem？

**Comment by tomieric** [comment]
#5583

**Comment by javaLuo** [comment]
我也遇到了这个问题，之前还可以，我也没改什么啊
后来就不可以了，为啥啊？
楼主解决了吗

**Comment by AzeShinja** [comment]
经过排查， 我是configureWebpack配置问题导致的 换成对象模式且注销掉其他配置后是好用的。 我一会看看如何修改

**Comment by AzeShinja** [comment]
https://blog.csdn.net/AzeShinja/article/details/121510302 我的解决方法
