### ISSUE TITLE
have 2 warning when npm install vue-cli

### ISSUE THREAD

**Issue by mcdongWang** [vuejs/vue-cli#45]
node -v:  v5.2.0

npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.

**Comment by skyronic** [comment]
Thanks for letting us know. This looks like outdated packages in some dependencies. `vue-cli` should continue work fine despite these warnings.

Closing this issue. Please re-open if you experience any problem because of these dependency.
