### ISSUE TITLE
`vue-cli-service build` and `vue-cli-service build --watch` creates two different file structures in `dist`

### ISSUE THREAD

**Issue by Znegl** [vuejs/vue-cli#4506]
### Version
3.11.0

### Reproduction link
[https://github.com/Znegl/vue-pages-watch-bug](https://github.com/Znegl/vue-pages-watch-bug)

### Environment info
```
  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  Binaries:
    Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
    Yarn: Not Found
    npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 67.0.4
    Safari: 12.1.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.11.0 
    @vue/babel-preset-jsx:  1.1.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.1.0 
    @vue/cli-overlay:  3.11.0 
    @vue/cli-plugin-babel: ^3.11.0 => 3.11.0 
    @vue/cli-plugin-eslint: ^3.11.0 => 3.11.0 
    @vue/cli-service: ^3.11.0 => 3.11.0 
    @vue/cli-shared-utils:  3.11.0 
    @vue/component-compiler-utils:  3.0.0 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.3 
    vue: ^2.6.10 => 2.6.10 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
1. Install the project with `npm ci`
2. Build with `npx vue-cli-service build`
3. Observe that the `dist` folder contains a `js` folder with all the JS files in it
4. Build with `npx vue-cli-service build --watch`
5. Observe that the `dist` folder doesn't contain a `js` folder and that all JS files are located directly in the `dist` folder instead

### What is expected?
I expect the build command to result in the same output in both cases, since `--watch` should just be a live-building version of build.

### What is actually happening?
I get two different file structures, making it a lot harder to integrate into an existing project, since I suddenly need different file operations depending on how the build was started.

---
I would either expect the two builds to result in the same file structure or expect  the documentation to explain the differences between `--watch` and no `--watch`.
We discovered the bug when merging our new Vue code into our legacy application and saw our nightly builds and staging servers fail on operations that works flawlessly on our development setup. The only difference is the `--watch` flag.

**Comment by sodatea** [comment]
It has been fixed in 4.0.0-rc.0, didn't backport to v3 because we think changing directory structure may be a breaking change for some users (`--watch` is run in development mode, so the fix affects all code built in development mode).
