### ISSUE TITLE
Vue UI compiles Typescript project, shows no errors despite listing type errors in output

### ISSUE THREAD

**Issue by agdsat134** [vuejs/vue-cli#4508]
### Version
3.11.0

### Environment info
```
 System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz
  Binaries:
    Node: 11.8.0 - /usr/bin/node
    Yarn: 1.15.2 - /usr/bin/yarn
    npm: 6.5.0 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 68.0.2
  npmGlobalPackages:
    @vue/cli: 3.11.0
```

### Steps to reproduce
* Create new project in Vue UI with Typescript and TSLint, Component Classes
* Serve project
* Add a variable to the component class with obvious type error (such as 'variable: number = 'test';)
* Check project in Vue UI interface

### What is expected?
Project should:
* Show errors on the Serve tab of project if there are errors in the Output section
* Not compile if there are Errors
* Either show compile errors on the App page or log them to the console

### What is actually happening?

* Compiles with no issues
* Shows that there are no errors under 'Serve' section despite having errors in the Output section
* Does not log any errors to the live app page console

**Comment by LinusBorg** [comment]
Hi @agdsat134 

Thanks for filing this issue! Could you please provide a small reproduction on jsfiddle.net or as a Github repository so we can debug this without trying to replicate this ourselves?

That would be very helpful, thanks!

**Comment by agdsat134** [comment]
Here is a repo:

https://github.com/agdsat134/ts-vue-problem

And here is the file where I've put a type error.

https://github.com/agdsat134/ts-vue-problem/blob/master/src/App.vue

**Comment by LinusBorg** [comment]
Thanks!

**Comment by sinbino** [comment]
I experience almost the same problem.

I chose "ESLint with error prevention only" or "ESLint + Standard config" instead of "TSLint" in lue / formatter config settings in vue create, but I have the same problem.

npm run serve outputs type error, but nothing is displayed in the page overlay.
In case of a grammatical error, it will be displayed correctly on the page overlay.

**Comment by sodatea** [comment]
See the documentation of fork-ts-checker-webpack-plugin: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#options

You can manually turn off the `async` option to see the type errors in the overlay, but this may affect build performance.
