### ISSUE TITLE
@vue/cli-service-global 如何支持typescript？

### ISSUE THREAD

**Issue by F-happy** [vuejs/vue-cli#4509]
### What problem does this feature solve?
我看到文档上说可以使用这个库来进行快速原型开发，但是我的.vue 文件是通过 @Component 导出的，该需要配置什么嘛？

### What does the proposed API look like?
希望在文档里介绍如何支持 lang="ts"

**Comment by sodatea** [comment]
不支持。快速原型开发不是给生产环境用的，不会支持所有场景，只会支持最基础的功能。
