### ISSUE TITLE
Windows 10.1 "vue init webpack vuejs" command error

### ISSUE THREAD

**Issue by darryldecode** [vuejs/vue-cli#451]
Hi guys, good day! I am struggling on my vue-cli isntallation to get to work on my windows 10.
Whenever I run this command: 
```vue init webpack vuejs```
An error always occurs, please see the screenshot below:
![image](https://cloud.githubusercontent.com/assets/5498919/25768917/aaf5a1c2-31c2-11e7-8b69-6b230eda2f1e.png)

Do anyone encounter this same problem? Did I do something wrong? Please lead me to right direction. Thanks in advance!

**Comment by darryldecode** [comment]
Turns out my nodejs installation was out of date. I updated my nodejs installation and its working fine now.

**Comment by iampinheirosamuel** [comment]
I have some trouble with vue webpack on my Window 10 Pro see image below
![issue](https://user-images.githubusercontent.com/22229935/36096992-1f3cb0c4-0ff9-11e8-84e1-f7ed15b4c897.PNG)





Any help?
