### ISSUE TITLE
如何正确的从npm插件中引入插件公共样式

### ISSUE THREAD

**Issue by a523926245** [vuejs/vue-cli#4511]
### Version
3.5.5

### Reproduction link
[https://github.com/a523926245/yaxhtest.git](https://github.com/a523926245/yaxhtest.git)

### Environment info
```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 10.15.3 - D:\node\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - D:\node\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.11.0
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.11.0
    @vue/cli-plugin-babel: ^3.11.0 => 3.11.0
    @vue/cli-plugin-eslint: ^3.11.0 => 3.11.0
    @vue/cli-service: ^3.11.0 => 3.11.0
    @vue/cli-shared-utils:  3.11.0
    @vue/component-compiler-utils:  3.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3
    vue:  2.6.10
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.1
    vue-router:  3.1.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex:  3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1.npm install yaxh 
引入自定义插件包后
2.在main.js中引入插件
import yaxh from "yaxh"
import "yaxh/lib/yaxh.css"

 

### What is expected?
组件及样式都表现正常

### What is actually happening?
组件可以使用，但是样式出现了问题
样式被编译的与正常样式不一样

列子：
正确:.y-cell{position:relative;display:-webkit-box;display:-ms-flexbox;display:flex;width:100%;padding:10px 16px;overflow:hidden;color:#323233;font-size:14px;line-height:24px;background-color:#fff}

引入后:.yaxh_y-cell_2ZNvx{position:relative;display:-webkit-box;display:-ms-flexbox;display:flex;width:100%;padding:10px 16px;overflow:hidden;color:#323233;font-size:14px;line-height:24px;background-color:#fff}

样式的名字变得奇怪，导致组件的样式失效

---
关于复现的仓库，npm包已经发布了，可以直接用一个新的cli脚手架引入npm包即可

**Comment by sodatea** [comment]
因为你设置了 `css: { modules: true }`
https://cli.vuejs.org/zh/guide/css.html#css-modules
