### ISSUE TITLE
HappyPack config

### ISSUE THREAD

**Issue by Luooooooo** [vuejs/vue-cli#4515]
### What problem does this feature solve?
HappyPack config should be supports,i not see it's description at https://cli.vuejs.org/zh/config/

### What does the proposed API look like?
threadPool:{ size: 5 }

**Comment by LinusBorg** [comment]
This project does not use/include HappyPack and we dont' intend to do so out of the box.

You can config happypack yourself with https://cli.vuejs.org/zh/guide/webpack.html
