### ISSUE TITLE
Single Spa Supported Template -- micro frontend

### ISSUE THREAD

**Issue by zero7u** [vuejs/vue-cli#4517]
### What problem does this feature solve?
Because of the popularity of ```micro-frontend```, we also need to do the transformation of micro-frontend. VueCli has built-in the best configuration of webpack, but it is difficult to modify it to the ```webpack.config.js``` needed by micro-frontend. So I hope the official team can make a template for Single Spa. Thank you so!

### What does the proposed API look like?
vue create project -c http://path-to-template

**Comment by LinusBorg** [comment]
I think this is something the community can provide. That's why we have a plugin&preset system.
