### ISSUE TITLE
automate prompts

### ISSUE THREAD

**Issue by nkovacs** [vuejs/vue-cli#452]
I'd like to automate the generation of templates, e.g. I'd like to be able to do something like this:

```
vue init webpack my-project --name "Foo" --description "A vue.js project" --author "Me" --build runtime --no-router --lint --lint-config airbnb --unit --e2e
```

This would make it possible to automatically test templates, e.g. generate with `--lintConfig airbnb`, then run eslint on the generated template, then do the same with `--lintConfig standard` etc.

**Comment by posva** [comment]
dup of #291

**Comment by ihattab** [comment]
still ask the same questions, where I need to enter answers manually !!

**Comment by ihattab** [comment]
![image](https://user-images.githubusercontent.com/52972810/65058584-6672b680-d96c-11e9-8b39-6cb18960964d.png)
