### ISSUE TITLE
打包后background问题

### ISSUE THREAD

**Issue by zhangchao828** [vuejs/vue-cli#4521]
### Version
3.10.0

### Environment info
```
window
```

### Steps to reproduce
css 背景图片地址query中带有/的比如：
background: url('https://ss0.bdstatic.com/70cFuHSh_Q1YnxGkpoWK1HF6hhy/it/u=508387608,2848974022&fm=26&gp=0.jpg?imageView2/1/w/750/h/1334');
最后/会被转译为%2F 

### What is expected?
url原模原样输出

### What is actually happening?
/被转译成了%2F

---
这样导致有些图片服务器无法解析%2F

**Comment by sodatea** [comment]
这应该是在 [css-loader](https://github.com/webpack-contrib/css-loader) 中处理的，请给他们提 bug。
