### ISSUE TITLE
vue-xeditable 

### ISSUE THREAD

**Issue by AngieNavarro** [vuejs/vue-cli#4524]
### Version
3.11.0

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
  Binaries:
    Node: 11.14.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.7.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: Not Found
    Safari: 12.1.2
  npmPackages:
    @nuxt/vue-app:  2.9.1 
    @nuxt/vue-renderer:  2.9.1 
    @onekiloparsec/vue-xeditable: ^1.2.2 => 1.2.2 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-jsx:  1.1.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.1.0 
    @vue/component-compiler-utils:  3.0.0 
    bootstrap-vue: ^2.0.0-rc.28 => 2.0.0-rc.28 
    eslint-plugin-vue: ^4.0.0 => 4.7.1 
    portal-vue:  2.1.6 
    vue: ^2.6.10 => 2.6.10 
    vue-client-only:  2.0.0 
    vue-eslint-parser:  2.0.3 
    vue-form-wizard: ^0.8.4 => 0.8.4 
    vue-functional-data-merge:  3.1.0 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.1 
    vue-meta:  2.2.1 
    vue-no-ssr:  1.1.1 
    vue-router:  3.0.7 
    vue-server-renderer:  2.6.10 
    vue-style-loader:  4.1.2 
    vue-template-compiler:  2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vue-xeditable: ^1.1.2 => 1.1.2 
    vuejs-datepicker:  1.6.2 
    vuex:  3.1.1 
  npmGlobalPackages:
    @vue/cli: 3.11.0
```

### Steps to reproduce
1 npm install vue-xeditable --save
    import Editable from './Editable.vue'
or 
2 npm install @onekiloparsec/vue-xeditable --save
   import vue-xeditable from './vue-xeditable.vue'

3 npm run dev 

### What is expected?
I was hoping to use the Vue Editable Component, base on X-Editable

### What is actually happening?
This relative module was not found:
./vue-xeditable in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=script&lang=js&`` how can I solve that ?

---
although it says that it is already installed in the package.json that I remain after executing steps 1 or 2 "vue-xeditable: ^ 1.1.2 => 1.1.2", when performing step 3 I throw the error mentioned

**Comment by LinusBorg** [comment]
``` javascript
import vue-xeditable from 'vue-xeditable.vue'
```

It seems You have to learn how to import node modules properly. They don't take relative paths, just the package name.
