### ISSUE TITLE
Cannot read property 'getDisplayMedia' of undefined

### ISSUE THREAD

**Issue by xusJs** [vuejs/vue-cli#4529]
### Version
3.9.3

### Reproduction link
[https://github.com/xusJs/test](https://github.com/xusJs/test)

### Environment info
```
System:
    OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
    CPU: (2) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
    Yarn: Not Found
    npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 68.0.2
  npmPackages:
    @vue/test-utils: ^1.0.0-beta.29 => 1.0.0-beta.29 
    babel-helper-vue-jsx-merge-props: ^2.0.3 => 2.0.3 
    babel-plugin-transform-vue-jsx: ^3.5.0 => 3.7.0 
    vue: ^2.6.10 => 2.6.10 
    vue-awesome-swiper: ^3.1.3 => 3.1.3 
    vue-freemde: ^0.1.0 => 0.1.0 
    vue-fullpage: ^2.0.5 => 2.0.5 
    vue-hot-reload-api:  2.3.3 
    vue-jest: ^3.0.4 => 3.0.4 
    vue-loader: ^13.3.0 => 13.7.3 
    vue-router: ^3.0.1 => 3.0.6 
    vue-style-loader: ^3.0.1 => 3.1.2 
    vue-template-compiler: ^2.5.2 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 3.9.3

```

### Steps to reproduce
 click start button

### What is expected?

Screen sharing will occur if browser support is provided

### What is actually happening?
“TypeError: navigator.getDisplayMedia is not a function"

**Comment by LinusBorg** [comment]
There's no getDisplayMedia() method on navigator, only a (deprecated) getUserMedia() method.

If you think I'm wrong please send a link to docs.

Anyway, not vue-cli related

**Comment by xusJs** [comment]
https://github.com/muaz-khan/RecordRTC/blob/master/simple-demos/screen-recording.html

**Comment by xusJs** [comment]
the question is   If I don't use vuecli, That's right；
