### ISSUE TITLE
请问如何布局字体文件和引用路径？（本地预览情况下静态资源路径设置）

### ISSUE THREAD

**Issue by HoldSkill** [vuejs/vue-cli#454]
![image](https://cloud.githubusercontent.com/assets/25190239/25778442/3df63234-3330-11e7-89c6-10fd98b014e5.png)
感谢大大的无私奉献！
我想使用vue-cli来做一个Hybrid App，所以需要：本地打开`dist`文件夹下的`index.html`文件进行预览。
但是出现了字体引用路径错误的问题，已经修改了`config/index.js`文件下的`assetsPublicPath: '/'`为`assetsPublicPath: './'`，但是还是无效，出现以下错误。
请问我该如何设置？谢谢指导~
![image](https://cloud.githubusercontent.com/assets/25190239/25778463/a3115360-3330-11e7-8183-edd74149dffc.png)

**Comment by egoist** [comment]
请阅读运行 `npm run build` 之后的提示，下次请将类似问题提到 stackoverflow 或者相应的 repo 里。
