### ISSUE TITLE
PucPath cannot be set to./

### ISSUE THREAD

**Issue by bosens-China** [vuejs/vue-cli#4547]
### Version
3.5.1

### Reproduction link
[https://github.com/bosens-China/error-demo](https://github.com/bosens-China/error-demo)

### Environment info
```
node: v10.15.0
webpack: 4.29.6
```

### Steps to reproduce
npm run build

### What is expected?
According to the document description, it can be set to./

### What is actually happening?
It will be filtered out. ./

---
I want to preview it locally. Please give me the appropriate solution.

**Comment by sodatea** [comment]
See discussions at https://github.com/vuejs/vue-cli/issues/3520#issuecomment-467329995

`'./'` is equivalent to `''`

**Comment by swhmonster** [comment]
这个问题解决了吗？解决方式是什么？

**Comment by swhmonster** [comment]
What is the final solution？
