### ISSUE TITLE
Allow specifying files to lint during vue-cli-service serve

### ISSUE THREAD

**Issue by ChristophWalter** [vuejs/vue-cli#4556]
### What problem does this feature solve?
`vue-cli-service lint` accepts target files or folders to lint, but `vue-cli-service serve` will only lint the default ones (src and tests) during development

### What does the proposed API look like?
`vue-cli-service serve --lint src tests mocks`

or in vue.config.js

```
lintOnSave: "warning"
lintFiles: "src tests mocks"
```

**Comment by LinusBorg** [comment]
`vue-cli-service serve` uses eslint-loader to lint files hat your app actually consumes.  That means it can only lint files that are handled by webpack when serving your app.

So there's no way - within justifiable effort limits - to make this work.

**Comment by ChristophWalter** [comment]
Okay, thank you anyway. Now I know that I need to start eslint myself for those files. 👍
