### ISSUE TITLE
Externals from CDN - Terser Unexpected token

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vue-cli#4559]
### Version
4.0.0-rc.3

### Reproduction link
[https://github.com/johannes-z/vue-terser-repro](https://github.com/johannes-z/vue-terser-repro)

### Environment info
```
  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 11.13.0 - ...\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.17.3 - ...\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.7.0 - ...\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.267.0
Browsers:
    Edge: 44.18362.267.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  4.0.0-rc.3
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  4.0.0-rc.3
    @vue/cli-plugin-babel: ^4.0.0-rc.3 => 4.0.0-rc.3
    @vue/cli-plugin-eslint: ^4.0.0-rc.3 => 4.0.0-rc.3
    @vue/cli-service: ^4.0.0-rc.3 => 4.0.0-rc.3
    @vue/cli-shared-utils:  4.0.0-rc.3
    @vue/component-compiler-utils:  3.0.0
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. git clone
2. npm install
3. npm run build
4. error is thrown

### What is expected?
Successful building

### What is actually happening?
An error is thrown:
```
js/app.0b6a2318.js from Terser
Unexpected token: punc (:) [external "https:/cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.min.js":1,0][js/app.0b6a2318.js:359,22]
```

---
I'm not sure if this is related to vue-cli, webpack or terser or the webpack-terser-plugin. I also tried the latest stable of vue-cli, same error though.

**Comment by LinusBorg** [comment]
you can't use URLs in webpack's externals config

https://webpack.js.org/configuration/externals/

it expects the name of a global variable from which to get the dependency (i.e.: `Vue`)

**Comment by johannes-z** [comment]
@LinusBorg Ah yes you are right, sorry my bad. I however also tried using regex for package names that have their scope in the name, e.g. `@pnp/sp`. It's the same error, but with `@` instead of `:`. Is this a terser bug?

**Comment by LinusBorg** [comment]
I have no real idea, tbh. Never used re RegExp option and don't really understand its usecase / intended outcome.

Seems not related to Vue CLI though.
