### ISSUE TITLE
cli-plugin-e2e-nightwatch@4.0.0-rc.3 SyntaxError

### ISSUE THREAD

**Issue by ManfredHu** [vuejs/vue-cli#4564]
### Version
4.0.0-rc.3

### Reproduction link
[https://github.com/ManfredHu/vue-jest-nightwatch](https://github.com/ManfredHu/vue-jest-nightwatch)

### Environment info
```
Chrome Version: 版本 76.0.3809.132（正式版本） （64 位）
System: macOS Mojave 10.14.5
```

### Steps to reproduce
The project created by vue-cli3 executes npm run test: e2e cannot run.
npm i cli-plugin-e2e-nightwatch@4.0.0-rc.3 --save-dev
npm i chromedriver geckodriver selenium-server@^3.141.59 --save-dev
use cli-plugin-e2e-nightwatch@4.0.0-rc.3 to replace vue-cli3 created project e2e folder by template.

### What is expected?
no error 

### What is actually happening?
[Test With Pageobjects] Test Suite
==================================
Running:  e2e tests using page objects

✔ Element <#app> was visible after 22 milliseconds.
✔ Testing if element <img> has count: 1  - 7 ms.
✔ Expected element <Section [name=app],Element [name=@welcome]> to be visible - condition was met in 27ms
✔ Expected element <Section [name=app],Element [name=@headline]> text to match: "/^Welcome to Your Vue\.js (.*)App$/" - condition was met in 29ms

OK. 4 assertions passed. (425ms)
Running:  verify if string "e2e-nightwatch" is within the cli plugin links

✔ Expected element <Section [name=app],Section [name=welcome],Element [name=@cliPluginLinks[0]]> text to contain: "e2e-nightwatch" - condition was met in 42ms

OK. 1 assertions passed. (1.109s)
_________________________________________________

TEST FAILURE: 1 error during execution 0 assertions failed, 5 passed. 2.57s

  SyntaxError: missing ) after argument list
         .assert.containsText('h1', 'Welcome to Your Vue.js <%- hasTS ? '  TypeScript ' : '' %>App')
                                                                           ^^^^^^^^^^

   SyntaxError: missing ) after argument list
       at createScript (vm.js:80:10)
       at Object.runInThisContext (vm.js:139:10)
       at Module._compile (module.js:617:28)
       at Object.Module._extensions..js (module.js:664:10)
       at Module.load (module.js:566:32)
       at tryModuleLoad (module.js:506:12)
       at Function.Module._load (module.js:498:3)
       at Module.require (module.js:597:17)
       at require (internal/module.js:11:18)

 ERROR  Error: Command failed: /Users/pphu/Documents/vue-jest-nightwatch/node_modules/nightwatch/bin/nightwatch --config /Users/pphu/Documents/vue-jest-nightwatch/node_modules/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js --env chrome
Error: Command failed: /Users/pphu/Documents/vue-jest-nightwatch/node_modules/nightwatch/bin/nightwatch --config /Users/pphu/Documents/vue-jest-nightwatch/node_modules/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js --env chrome
    at makeError (/Users/pphu/Documents/vue-jest-nightwatch/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/pphu/Documents/vue-jest-nightwatch/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-jest-nightwatch@0.1.0 test:e2e: `vue-cli-service test:e2e`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-jest-nightwatch@0.1.0 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pphu/.npm/_logs/2019-09-11T06_45_42_392Z-debug.log

**Comment by sodatea** [comment]
> use cli-plugin-e2e-nightwatch@4.0.0-rc.3 to replace vue-cli3 created project e2e folder by template.

Users are not supposed to directly copy template folders to the project.
Run `vue invoke e2e-nightwatch` instead.
