### ISSUE TITLE
false positive "new content popup" on docs site

### ISSUE THREAD

**Issue by atilkan** [vuejs/vue-cli#4566]
### Reproduction link
[https://cli.vuejs.org/config/](https://cli.vuejs.org/config/)

### Environment info
```
Win 10, Chrome
```

### Steps to reproduce
I always see the popup but i've just entered the site. I think there is an issue with service worker.
https://cli.vuejs.org/config/

### What is expected?
Should not pop

### What is actually happening?
pops

**Comment by LinusBorg** [comment]
That works as expected. When you visit the site, the content buffered by the SW is served. After that, the newer files are downloaded, so now there's new content, and the message is shown.

**Comment by atilkan** [comment]
@LinusBorg Thanks for explainig. Even though i feel some things doesn't feel right i can't explain further. Closing now.

**Comment by atilkan** [comment]
@LinusBorg Can this be prevented if used network first strategy?

**Comment by LinusBorg** [comment]
I'm not particularly versed in that, no.
