### ISSUE TITLE
vue.config.js中的outputDir的Type可改为String || Object，这样是否在build打包时可以配合pages输出多个project目录

### ISSUE THREAD

**Issue by maxiaoqu** [vuejs/vue-cli#4568]
### What problem does this feature solve?
由于目前使用的微服务的思想，前端开发工程师也必须出对应的微应用（或者叫：微前端的思想）相对应；
参考链接：
1、https://mp.weixin.qq.com/s/DpFXTrQ3_kBX4EB6or4Q8Q
2、https://segmentfault.com/a/1190000016206160

1、假如我的pages配置了projectA、projectB、projectC、projectD......；
2、我想在npm run build后打包的dist中出现projectA、projectB、projectC、projectD......这些对应的目录；
3、由于outputDir的Type为String，我现在只能配置成：npm run build projectA、npm run build projectB、npm run build projectC、npm run build projectD......分别去打包才行；
4、是否可将outputDir的Type改为String || Object，这样是否在build打包时可以配合pages输出多个project目录
5、虽然npm run build修改一些配置和增加一些额外的插件后，就可以实现第2步中的打包效果，outputDir的Type同时支持String || Object，这样就减少了很多配置；

### What does the proposed API look like?
outputDir的Type同时支持String || Object

**Comment by sodatea** [comment]
不考虑。`outputDir` 和其他选项的联动太过复杂，不适合用于实现你的需求。
