### ISSUE TITLE
Polyfills still included in modern build

### ISSUE THREAD

**Issue by tobyzerner** [vuejs/vue-cli#4574]
### Version
4.0.0-rc.3

### Environment info
```
  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.npm-global/bin/yarn
    npm: 6.11.3 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 69.0
    Safari: 12.1.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  4.0.0-rc.3
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  4.0.0-rc.3
    @vue/cli-plugin-babel: ^4.0.0-rc.3 => 4.0.0-rc.3
    @vue/cli-plugin-eslint: ^4.0.0-rc.3 => 4.0.0-rc.3
    @vue/cli-service: ^4.0.0-rc.3 => 4.0.0-rc.3
    @vue/cli-shared-utils:  4.0.0-rc.3
    @vue/component-compiler-utils:  3.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: 4.0.0-rc.3
```

### Steps to reproduce
1. `vue create test` with default babel preset
2. In `src/main.js`, insert the following code anywhere in the file:

  ```
  Symbol();
  new Promise();
  ```

3. `node_modules/.bin/vue-cli-service build --modern --report`
4. Open `dist/report.html` and note that a large amount of core-js code is included in the bundle

### What is expected?
Since `Symbol` and `Promise` are supported by modern browsers, the modern bundle should not contain polyfills for these features.

### What is actually happening?
The modern bundle does contain polyfills for these features.

**Comment by tobyzerner** [comment]
Just tried with 4.0.5 and still an issue.

I had a look at the output in the compiled JS files (with `--mode=development`). As far as I can tell, the actual calling code (`Symbol(); new Promise();`) correctly remains untouched... but the core JS modules are still imported at the start of main.js and never used.

**Comment by sodatea** [comment]
Not a bug.

https://github.com/babel/babel/blob/c7d8b8a37752f42163128cf4d5e8b54c2637cec4/packages/babel-preset-env/data/built-in-modules.json#L2-L10

https://github.com/zloirock/core-js/blob/306ba2ccfba32350f596ef80292ae56592145f06/packages/core-js-compat/src/data.js#L700-L704

Module support: Chrome >= 61
Full Promise support: Chrome >= 67

So the polyfill must be included.

**Comment by tobyzerner** [comment]
@sodatea Ah I see. So right now "modern" means "browsers that support modules" (I guess because that makes it easy to implement legacy fallback loading). Surely at some point in the future this meaning will need to change though... is it possible to configure vue-cli to generate a modern build which targets an even more modern subset of browsers?

**Comment by sodatea** [comment]
Not possible at the moment. You can file a separate feature request for this.

**Comment by tobyzerner** [comment]
On second thoughts, I think it would defeat the purpose. The whole point of "modern" mode is that it can automatically load the legacy vs. modern bundle depending on the browser's support for modules. If the modern build was retargeted to more modern browsers, then all browsers with module support would still load it anyway, and those that don't support the newer features would break. If the intention is to not support older browsers at all, one can simply [configure the normal build via browserslist](https://cli.vuejs.org/guide/browser-compatibility.html#browserslist).

Thanks for your help!
