### ISSUE TITLE
Vue JS not running in Safari or mobile

### ISSUE THREAD

**Issue by Miltage** [vuejs/vue-cli#4576]
### Version
3.11.0

### Environment info
```
Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 45.0.1
    Safari: 12.1.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.11.0 
    @vue/babel-preset-jsx:  1.1.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.1.0 
    @vue/cli-overlay:  3.11.0 
    @vue/cli-plugin-babel: ^3.11.0 => 3.11.0 
    @vue/cli-plugin-eslint: ^3.11.0 => 3.11.0 
    @vue/cli-service: ^3.11.0 => 3.11.0 
    @vue/cli-shared-utils:  3.11.0 
    @vue/component-compiler-utils:  3.0.0 
    @vue/eslint-config-prettier: ^5.0.0 => 5.0.0 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.3 (4.7.1)
    vue: ^2.6.10 => 2.6.10 
    vue-async-computed: ^3.7.0 => 3.7.0 
    vue-eslint-parser:  2.0.3 (5.0.0)
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.1 
    vue-moment: ^4.0.0 => 4.0.0 
    vue-multiselect: ^2.1.6 => 2.1.6 
    vue-router: ^3.0.3 => 3.1.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 3.11.0
```

### Steps to reproduce
Create project

`vue create hello-world`

Serve project

`cd hello-world`

`npm run serve`

Open Safari and navigate to `localhost:8080`

### What is expected?
Get Vue hello world welcome screen

### What is actually happening?
Get white screen. Console logs 'SyntaxError: Invalid regular expression: invalid group specifier name'

---
I searched extensively for this issue but couldn't find other reports of it, so it may just be my system, but I am unable to get any Vue project running in Safari or on mobile browsers.

**Comment by sodatea** [comment]
Could you please provide a runnable reproduction?
I don't think this could be reproduced in a default hello-world app.

**Comment by Miltage** [comment]
If it can't be reproduced in the default hello-world app, then it confirms that it is an issue with just my system.

**Comment by sodatea** [comment]
Make sure to check the [`transpileDependencies` option](https://cli.vuejs.org/config/#transpiledependencies) if you have any third-party dependency.

**Comment by 702pjc** [comment]
I'm having the same issue. Just a blank white page after running the hello world app.

**Comment by Miltage** [comment]
In my case it was because I had regex that worked fine on Chrome but was
breaking the site  on every other browser.

**Comment by ruralcoder** [comment]
Same here.  Worked on chrome on my mac while developing.  But did not load on mobile Safari or Mobile Chrome.  Then i checked Safari on the iMac and nothing.  On Chrome on the iMac ALL GOOD! and fast.

**Comment by linrongbin16** [comment]
Same issue with vue-cli 4.
The default app works correctly, but I modified the app with using CDN instead of third-party package dependencies, remove babel plugins (because I don't want any old browser compatibility). Then there're `Invalid regular expression: invalid group specifier name` error in macbook safari browser.
