### ISSUE TITLE
Use typescript configuration  vue.config file

### ISSUE THREAD

**Issue by huanent** [vuejs/vue-cli#4581]
### What problem does this feature solve?
Use typescript configration vue.config file

### What does the proposed API look like?
import { ProjectOptions } from "@vue/cli-service";

export default function() {
  return {
    outputDir: "build"
  } as ProjectOptions;
}

**Comment by sodatea** [comment]
Currently, you can use the following snippet for type hints:
```js
/** @type {import('@vue/cli-service').ProjectOptions */
module.exports = {
  
}
```

**Comment by huanent** [comment]
Thanks , it would be great if you could support using .ts in the future like webpack .
https://webpack.js.org/configuration/configuration-languages/

**Comment by sodatea** [comment]
https://github.com/vuejs/vue-cli/issues/2138
https://github.com/vuejs/vue-cli/issues/4477
