### ISSUE TITLE
Can't create issue via Vue issue helper

### ISSUE THREAD

**Issue by JeremieANACHE** [vuejs/vue-cli#4588]
github API call fails :
`api.github.com/repos/vuejs/vue-cli/releases?page=1&per_page=100` returns :

`documentation_url: "https://developer.github.com/v3/#rate-limiting"
message: "API rate limit exceeded for XXX.X.XXX.XXX. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)" `

**Comment by LinusBorg** [comment]
Sorry to hear that. You can either re-use this existing issiu and describe your bug here - 'll keep it open.

or you wait an hour and try again, when the rate limit from github has reset.

We'll see if we can find a solution to the rate-limit problem in the helper.

**Comment by JeremieANACHE** [comment]
It should have resetted at 1pm (gmt+1) I was just able to create it a few minutes ago, sorry for the inconvenience. You can close this one

**Comment by LinusBorg** [comment]
Thanks, good to hear.

Nonethelesse, I opened an issue to track this in the issue-helper rep: https://github.com/vuejs/vue-issue-helper/issues/40
