### ISSUE TITLE
ES6 syntax is not transpiled from import in Vue file

### ISSUE THREAD

**Issue by Zysce** [vuejs/vue-cli#459]
Here is my project structure : 
 - ClientApp
   | - build
   | - config
   | - src
       ...
       | - App.Vue
   ...
- Lib
  ...
  | -src
     | - components
         | - SharedComponent.Vue
     | - tools
         | - index.js

I have 2 Vue-Cli projects (ClientApp and Lib).
ClientApp is my SPA project and Lib is my components library (shared with other projects)

In my webpack.base.conf.js of ClientApp, I added an alias to Lib : 
```
resolve: {
    extensions: ['.js', '.vue', '.json'],
    alias: {
      '@': resolve('src'),
      '~lib': path.join(__dirname, '../../lib/src'),
    }
  },
```

In my file App.Vue : 
```
<!-- Script -->
<script>
import SharedComponent from '~lib/components/SharedComponent';
...
```

In my file SharedComponent.Vue : 
```
<!-- Script -->
<script>
import Tools from '~lib/tools';
...
```

And in my module Tools, I am using an arrow function.

When I build my project ClientApp, the arrow function in module Tools from the library project is not transpiled, so UglifyJS module fail.

Is it a webpack problem ? babel-loader is not called ? 
Is it a vue-loader problem ?

**Comment by posva** [comment]
Please ask questions on the [forum](http://forum.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js). It'll be easier if you share your project code too
