### ISSUE TITLE
[ESLINT-Typescript] Missing semicolon stays unnoticed

### ISSUE THREAD

**Issue by NicoAiko** [vuejs/vue-cli#4590]
### Version
3.11.0

### Environment info
```
  System:
    OS: macOS 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: Not Found
    npm: 6.11.3 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 68.0.1
    Safari: 12.1.2
  npmPackages:
    @vue/cli-overlay:  3.11.0
    @vue/cli-plugin-e2e-cypress: ^3.11.0 => 3.11.0
    @vue/cli-plugin-eslint: ^3.11.0 => 3.11.0
    @vue/cli-plugin-pwa: ^3.11.0 => 3.11.0
    @vue/cli-plugin-typescript: ^3.11.0 => 3.11.0
    @vue/cli-plugin-unit-jest: ^3.11.0 => 3.11.0
    @vue/cli-service: ^3.11.0 => 3.11.0
    @vue/cli-shared-utils:  3.11.0
    @vue/component-compiler-utils:  3.0.0
    @vue/eslint-config-prettier: ^5.0.0 => 5.0.0
    @vue/eslint-config-typescript: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.2.3 => 5.2.3 (4.7.1)
    jest-serializer-vue:  2.0.2
    typescript: ~3.5.3 => 3.5.3
    vue: ^2.6.10 => 2.6.10
    vue-class-component: ^7.1.0 => 7.1.0
    vue-cli-plugin-vuetify: ^0.6.3 => 0.6.3
    vue-eslint-parser:  2.0.3 (5.0.0)
    vue-hot-reload-api:  2.3.4
    vue-jest:  3.0.5
    vue-loader:  15.7.1
    vue-property-decorator: ^8.2.2 => 8.2.2
    vue-router: ^3.1.3 => 3.1.3
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuetify: ^2.0.18 => 2.0.18
    vuex: ^3.1.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: 3.11.0
```

### Steps to reproduce
When using a callback in an existing function like this:

```js
class Foobar {
  public testFunction() {
    ['Foo', 'bar'].map((item: string) => {
      return {} // <-- missing semicolon stays unnoticed
    });
  }
}
```

The Semicolon in the `map` callback stays unnoticed by eslint.
I don't know if this issue is actually produced by the plugin implementation of vue-cli or if it is a problem of the typescript-eslint package itself, but maybe you experienced the same?

### What is expected?
Missing Semicolon should be noticed and an error should occur

### What is actually happening?
Missing semicolon isn't noticed and no error occurs.

**Comment by sodatea** [comment]
What ESLint config did you use? The default "Error prevention only" config does not care about semicolons at all.

Please follow the issue helper guide and do provide full environment info and reproduction.

**Comment by NicoAiko** [comment]
Environment info added.
ESLint Config is ESLint + Prettier

Reproduction repo following...

**Comment by NicoAiko** [comment]
OK so.
I actually had to add `semi: ['error', 'always']` to the `.eslintrc` to let `npm run lint` notice the missing semicolon.

What does not happen is VSCode noticing.

Does that have anything to do with this repo?

**Comment by sodatea** [comment]
I still need a reproduction for the first issue (has to add the `semi` rule manually, which, does not happen on my machine).
For the VSCode part, see https://github.com/microsoft/vscode-eslint#enable-typescript-file-validation

**Comment by NicoAiko** [comment]
OK. Issue can be closed. The mistake was on my side. The VSCode Typescript validation part was missing in my settings.

Thanks and have a nice day.
