### ISSUE TITLE
Unable to dynamically generate .env file in Spring Boot java application

### ISSUE THREAD

**Issue by macfisher** [vuejs/vue-cli#4591]
### What problem does this feature solve?
Say you are wrapping Vuejs in a Spring Boot application and deploying it as a Jar file within a docker container and being served as a microservice. By restricting developers to place their .env file within the project root you are preventing the ability to modify that or dynamically generate env vars post deployment due to the fact that the .env file is now trapped inside of a read-only jar file. I cannot generate the .env file during CI/CD build pipelines due to pipelines not having access to protected configuration server apps. I need to be able to modify .env post deployment and that isn't possible under these constraints.

I understand the philosophy of wanting all project file structures to be uniform, but in this scenario it breaks functionality. If you deploy the app as a jar file you would need to be able to access and modify the .env file from outside the jar file, but you can't because Vuejs doesn't allow it. I've read and done lots of research but I cannot figure out how to override the .env path and it sounds like it's a design feature. Am I missing something?

### What does the proposed API look like?
Allow developers to override the default .env file path like webpack-dotenv allows:

```
webpackConfig: {
    plugins: [
      new dotenvWebpack({
        path: path.resolve(__dirname, '/root/.env')
      })
    ]
  }
```

**Comment by LinusBorg** [comment]
Hi there, @macfisher 

I kind of see your point, but want to clarify something with you first, before talking about adding some feature for this.

Question: Why do you want  or need to add a dynamic .env file instead of using actual environment variables?

The reason I am asking is that generally, in my understanding, it's recommended to *not* use .env files in production, especially for sensitive content like API keys and stuff like that, which I think about when hearing the need for a *"dynamic"* env file.

But I may be missing the use case, so can you clarify?

**Comment by macfisher** [comment]
I need to be able to deploy a generic image that can retrieve its authentication variables when it is deployed. I do not want to have separate images for each environment that we have, i.e. Test, Production, Development etc.

To your point that I should not be doing this... why then is there a concept of the .env.local file that is git ignored? I may be missing something but I do not see an issue with having a dynamically generated .env file that only lives within the lifecycle of that image and is not committed to any source repository.

Again, if I have an external configuration server that allows the application to talk to it and get its env variables based on its environment that it is deployed to, I am currently not able to do that if I cannot move the .env file outside of the project root directory.

**Comment by LinusBorg** [comment]
Not sure if we are talking past each other.

Are you aware that Vue cli also accepts wnv variables from the system itself, not just from the env files?

I was referring to setting the env variables on the system (I think for docker one uses the `-e` flag to set an environment variable in the container process, right?

That way, the no sensitive data is being saved in an file and the app can access them just the same, the same rules apply (VUE_APP_* variables are passed into the webpack bundle etc.)

**Comment by macfisher** [comment]
Thank you @LinusBorg for taking the time. I had tried to do that via a Java library but it must have set the environment variable for the Java environment and Vuejs didn't know about it but I was getting a false positive because Java could read it and Vue couldn't so I apologize for making the incorrect assumption. You've been a huge help. I can close this request as this was 100% user error.
