### ISSUE TITLE
normal application support

### ISSUE THREAD

**Issue by yuicer** [vuejs/vue-cli#4593]
### What problem does this feature solve?
sometimes we just want the normal application with any framework  vue and react.

just want run ts or modern js feature quickly, and pay no attention to annoying project configuration like webpack and so on.

### What does the proposed API look like?
vue create project-name --type normal

**Comment by LinusBorg** [comment]
I understand that english is not your first language, but a feature request needs a bit more information.

I don't understand what you want.

**Comment by yuicer** [comment]
sorry for my poor English 😂

"normal" maybe means only run js or ts?
we do have babel or webpack config. but do not need vue-loader and vue-template

**Comment by LinusBorg** [comment]
Then why use vue-cli if you don't want to use Vue?

There are other tools for these situations

**Comment by sodatea** [comment]
Vue CLI does support any kind of front end framework as you can freely extend it with plugins. For example, here's a plugin that mimics create-react-app: https://github.com/miccycn/vue-cli-plugin-react

But, we are not going to remove the Vue specific configurations inside it; it would violate the fundamental purpose of Vue CLI.
