### ISSUE TITLE
Do not evaluate expressions added to `configs` in `preset.json`

### ISSUE THREAD

**Issue by amitnavindgi** [vuejs/vue-cli#4603]
### Version
3.11.0

### Environment info
```
Mac/Ubuntu
Node  10.16.0
```

### Steps to reproduce
Add the following to `preset.json`.

```
"configs": {
   "vue": {
       "lintOnSave": process.env.NODE_ENV === 'production' ? 'error' : true,
    }
}
```

### What is expected?
The config mentioned to go in `vue.config.js` as it is.
```
lintOnSave: process.env.NODE_ENV === 'production' ? 'error' : true,
```

### What is actually happening?
The above config evaluates the expression and adds
```
lintOnSave: true,
```
to the `vue.config.js`...as one can expect.

But I want the config to go in as it is mentioned in `preset.json`. How do I make sure that the expression doesn't evaluate?

**Comment by LinusBorg** [comment]
I can't follow your description. the content for preset.json that you show is not valid JSON, parsing will fail.


Please provide a runnable reproduction in a github repository.
