### ISSUE TITLE
npm ERR! Unexpected end of JSON input while parsing near '...,"dist":{"shasum":"b4' when running `npm install @vue/cli`

### ISSUE THREAD

**Issue by Drac5079** [vuejs/vue-cli#4614]
When I run `npm install @vue/cli` in cmd, I get this error:

`npm ERR! Unexpected end of JSON input while parsing near '...,"dist":{"shasum":"b4'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tripathy\AppData\Roaming\npm-cache\_logs\2019-09-24T13_39_42_908Z-debug.log`

Here's the debug log file from above:

[2019-09-24T13_39_42_908Z-debug.log](https://github.com/vuejs/vue-cli/files/3647451/2019-09-24T13_39_42_908Z-debug.log)

**Comment by etghanibahman** [comment]
I had the same problem. By the way I used 'yarn global add @vue/cli' and it did the job.
