### ISSUE TITLE
postcss version < 6.0

### ISSUE THREAD

**Issue by evanyangg** [vuejs/vue-cli#462]
Your current PostCSS version is 5.2.17, but postcss-nested uses 6.0.1. Perhaps this is the source of the error below.

**Comment by posva** [comment]
Hello!
Please, open the issue on the relevant template or loader repo. Thanks!

**Comment by QuantumInformation** [comment]
Why don't we get a postcss option in the cli chooser?

```
 Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): (Use arrow keys)
❯ SCSS/SASS
  LESS
  Stylus```

**Comment by QuantumInformation** [comment]
best tip I read all day

**Comment by Akryum** [comment]
😸
