### ISSUE TITLE
how to ignore self tags in SFC build

### ISSUE THREAD

**Issue by MrGaoGang** [vuejs/vue-cli#4623]
### What problem does this feature solve?
hello, i have i structure in my SFC, such as:

```html
<template>
  <button :style="styles" @click="handleClick">
  </button>
</template>

<script>

</script>

<docs>
   This button is amazing, use it responsibly.
</docs>
```

### What does the proposed API look like?
i have a self define `docs` tags, but i find when i use `vue cli` to build project; the `docs` tag also build to js files, so how should i ignore the tag when i build project!

thank!

**Comment by tychenjiajun** [comment]
@MrGaoGang So how? Did you figure out?
