### ISSUE TITLE
Toggle template pre compilation

### ISSUE THREAD

**Issue by angelul** [vuejs/vue-cli#4624]
### What problem does this feature solve?
Its needed the option of not pre compile templates, instead of, compile at runtime (despite of cost of consumption of resources in execution).

Because on the distribution of the site to clients, some request a text change, and that shouldn't envolve a full site recompile

### What does the proposed API look like?
In vue.config.js:

```js
module.exports = {
  ...
  precompileTemplates: false, // default: true
}
```

In CLI:

`vue-cli-service ... --precompileTemplates=false`

**Comment by sodatea** [comment]
Enable `runtimeCompiler` https://cli.vuejs.org/config/#runtimecompiler
And then use the `template` option https://vuejs.org/v2/api/#template rather than a `.vue` file.
