### ISSUE TITLE
Current version of sass-loader doesn't support Vue

### ISSUE THREAD

**Issue by dundunn** [vuejs/vue-cli#4625]
### Version
3.11.0

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.19 Manjaro Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.9.1 - /usr/bin/node
    Yarn: Not Found
    npm: 6.11.2 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 69.0.1
  npmGlobalPackages:
    @vue/cli: 3.11.0
```

### Steps to reproduce
sass-loader 8.0.0 doesn't work with the current version of Vue.js and leads to a compiler error. 7.3.1 works fine. I thought it should be mentioned as the [documentation](https://cli.vuejs.org/guide/css.html#pre-processors) refers the latest version. 

### What is expected?
Vue should run fine

### What is actually happening?
Module build failed: TypeError: this.getResolve is not a function
    at Object.loader (/PROJECT/node_modules/sass-loader/dist/index.js:52:26)

**Comment by DRoet** [comment]
This has already been fixed in the `4.0.0-rc3`, not sure if it can be backported without breaking changes.
