### ISSUE TITLE
Include update command when vue-cli can be updated

### ISSUE THREAD

**Issue by pacific202** [vuejs/vue-cli#4626]
### What problem does this feature solve?
There are so many different update syntaxes around these days it's hard to keep up with all of them.  It would be great if vue-cli follows the example of node and npm and when an update is available also provide the exact command needed to update.

### What does the proposed API look like?
-- An update is available.  Use this to update:
npm install -g @vue/cli

**Comment by sodatea** [comment]
Working on that: https://github.com/vuejs/vue-cli/pull/3926

**Comment by sodatea** [comment]
Landed in v4.
