### ISSUE TITLE
Yarn as default?

### ISSUE THREAD

**Issue by phoet** [vuejs/vue-cli#464]
First of all, thank you for this tool. It has helped me getting into building client-side apps with vue much faster than I could have wished. I even gave [a talk about that on our local ruby on rails usergroup](http://hamburg.onruby.de/topics/vue-js-javascript-the-good-parts).

I hope that it is ok to ask a question here rather than reporting a bug.

I've seen some comments in this repo like #245 for [YARN support](https://yarnpkg.com/en/) in the vue-cli.

My question would be if it is reasonable to push YARN to be the default in vue-cli, ie. generated code, installation, examples etc?

For me as a backend developer, the whole JS tooling is kinda confusing, especially coming from the very opinionated RoR.
As far as i understand, using YARN is beeing adopted as a best practice for client side dependency management, and I would love to see that reflected in this project.

I'd also be willing to help getting this done wherever I can.

**Comment by posva** [comment]
It's up to the user. People who use yarn will use it anyway but npm is the default/standard package manager and what most people is used to 🙂

**Comment by phoet** [comment]
great to see that yarn is now the default!

**Comment by serak** [comment]
how can i change it back to npm?. npm has proven to work on very slow network. while yarn keeps failing multiple times.

**Comment by posva** [comment]
edit `~/.vuerc`

**Comment by serak** [comment]
yes i finally found it under user home directory , thanks.

**Comment by ShuvoHabib** [comment]
Change yarn to npm
`vi ~/.vuerc`

**Comment by rishabhrastogi31** [comment]
> edit `~/.vuerc`

where pls specify

**Comment by booluw** [comment]
> > edit `~/.vuerc`
> 
> where pls specify

https://github.com/vuejs/vue-cli/issues/1300#issuecomment-389379048
This could help.

**Comment by jonas-weimar** [comment]
> edit `~/.vuerc`

The best help i found on this problem!
