### ISSUE TITLE
Shared node_modules folders

### ISSUE THREAD

**Issue by simon-rc** [vuejs/vue-cli#4642]
### What problem does this feature solve?
The CLI lets you create multiple projects in the same folder. As a result each new project created has its own unique **node_modules** folder. This works well, when each projected created is unique and has a unique set of dependencies.
```
root folder
  - project a
    - node_modules
  - project b
    - node_modules
```
However, if by design you're creating a set of projects within the same root folder, it would be nice if each project created could share the same node_modules folder to reduce bloat and keep things consistent across each project. When requiring/importing a module, node/npm will search up the folder tree to find a node_modules folder to import from (depending on your version of node), so there is no reason why the node_modules folder couldn't (optionally) be located at a **higher level**:
```
root folder
  - node_modules
  - project a
  - project b
```

One solution would be to install things globally (-g), but doing so is a danger because of the impact on unrelated projects (package versions etc).

So i'm hoping this feature can solve the unnecessary need for multiple node_modules folders when the developer wants to share the exact same packages across multiple projects, without resorting to a global install.

### What does the proposed API look like?
Given the initial "npm install" procedure happens during the "vue create" phase, it would make sense to include another question:

```bash
? Where does your node_modules folder live
|
```

If left blank we can use the root of the new project as the location i.e proceed as normal. Otherwise, under the hood we can use the npm "--prefix" option to install the package in the right location (if no answer given don't use the --prefix flag). So:

If location given:

```bash
npm install package --prefix ../../provided/location
```

If no location given:

```bash
npm install package (or however the cli does the install)
```

After vue create has finished, all subsequent install commands by the developer can also include the --prefix call. This should be left up to the developer to either implement with a script or remember to add it manually.

Another quick solution would be to not install the packages. Create the package.json file,  but let the developer run the npm install command.

I would love to know if there is another way this can be achieved. I've searched (probably not well enough) and haven't found a solution. And apologies if i've missed anything obvious.

**Comment by KyeRussell** [comment]
I don't know enough to know if the proposed implementation is sufficient, but I am also in a position where I want my `node_modules` served from a different location (a side-effect of my Dockerized setup). Right now I am attempting to accomplish this by configuring the underlying Webpack, but a more blessed API would be preferred.

**Comment by sodatea** [comment]
That's not how we typically optimize npm installs, and [`--prefix` is not for such use cases](https://github.com/npm/npm/issues/11007#issuecomment-168989576).

To share `node_modules` across projects, the recommended way is to set up a "workspace", with tools designed for managing workspaces - either [lerna](https://github.com/lerna/lerna) or [yarn](https://yarnpkg.com/en/docs/workspaces). Workspace management is so complicated that we don't want to reinvent the wheel in Vue CLI. So just use the existing tools.

To avoid bloat and speed up installations, I'd say it's the job of package managers. Yarn Plug'n'Play and PNPM are meant to solve this problem. PNPM is (well but not fully) supported by Vue CLI, and Yarn PnP support is on the way, full support of PNPM may arrive by then too. They are tracked in other separate issues.
