### ISSUE TITLE
devServe inline:false is invalid

### ISSUE THREAD

**Issue by HuangZhaoPing** [vuejs/vue-cli#4647]
### Version
3.11.0

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue-cli](https://new-issue.vuejs.org/?repo=vuejs/vue-cli)

### Environment info
```
win10
```

### Steps to reproduce
vue.config.js

```js
module.export = {
  devServer: {
    inline: false,
    hot: false
  }
}
```

or 

```js
module.export = {
  chainWebpack: config => {
    config.devServer.set('inline', false)
    config.devServer.set('hot', false)
  }
}
```

When files are modified, browsers refresh, I hope browsers don't refresh automatically 

### What is expected?
browsers refresh

### What is actually happening?
browsers don't refresh automatically

**Comment by sodatea** [comment]
Wrong config. See https://github.com/vuejs/vue-cli/issues/4368#issuecomment-515532738
