### ISSUE TITLE
 i cant npm run dev successful after vue-cli init

### ISSUE THREAD

**Issue by chenhm123** [vuejs/vue-cli#466]
when i  npm run dev
the console show 
> Listening at http://localhost:8080
(node:15732) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
(node:15732) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by posva** [comment]
You should report the issue to the template repo that showed this warning. Even better, you could submit a PR to add the missing `.catch` 😄

**Comment by DimitrisNL** [comment]
Any progress on this? Did you find any solution?
