### ISSUE TITLE
cli-plugin-e2e-nightwatch does on version 3.11 

### ISSUE THREAD

**Issue by rlagoue** [vuejs/vue-cli#4668]
### Version
3.11.0

### Environment info
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  Binaries:
    Node: 10.16.3 - /usr/bin/node
    Yarn: Not Found
    npm: 6.11.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.2
  npmGlobalPackages:
    @vue/cli: 3.11.0

```

### Steps to reproduce

1. vue create <any-project-name>
2. npm i -D chromedriver (because chrome is the newest on my pc)
3. create the file nightwatch.config.js to set the path to chromedriver explicitely like here: (#4522)
4. start the e2e test

### What is expected?
 Test is executed correctly

### What is actually happening?
`Error: Command failed: /node_modules/nightwatch/bin/nightwatch --config /node_modules/@vue/cli-plugin-e2e-nightwatch/nightwatch.config.js --env chrome
at makeError (cm.bao.fret.web/node_modules/execa/index.js:174:9)
at Promise.all.then.arr (cm.bao.fret.web/node_modules/execa/index.js:278:16)
at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR!@0.1.0 test:e2e: "vue-cli-service test:e2e"
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the@0.1.0 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! .../.npm/_logs/2019-10-09T02_56_15_620Z-debug.log

**Comment by sodatea** [comment]
Fixed in v4.
