### ISSUE TITLE
vue-cli · Failed to download repo

### ISSUE THREAD

**Issue by yangdaidi** [vuejs/vue-cli#467]
command: vue init https://github.com/yang*****/test.git test
error:     vue-cli · Failed to download repo https://github.com/yang*****/test.git: Response code 404 (Not Found)

**Comment by posva** [comment]
from the readme:

> If you would like to download from a private repository use the --clone flag and the cli will use git clone so your SSH keys are used.

**Comment by yangdaidi** [comment]
I have tried the following command, but still failed.
command: vue init --clone https://github.com/yang*****/test.git test1
error: Failed to download repo vuejs-templates/test1: 'git clone' failed with status 128
Can you show me the correct usage of this command？

**Comment by posva** [comment]
It's on the readme
