### ISSUE TITLE
vue command not found

### ISSUE THREAD

**Issue by TeAmP0is0N** [vuejs/vue-cli#4671]
### Version
4.0.0-rc.7

### Reproduction link
[https://github.com/vuejs/vue-cli/issues/4670](https://github.com/vuejs/vue-cli/issues/4670)

### Environment info
```
command prompt - ubuntu subsystem
I am using ubuntu terminal in windows
os - window10
Browser - chrome,mozilla
```

### Steps to reproduce
https://github.com/vuejs/vue-cli/issues/4670

### What is expected?
It should show vue version.

### What is actually happening?
vue --version

Command 'vue' not found, did you mean:

  command 'vpe' from deb texlive-latex-extra

Try: sudo apt install <deb name>

---
Please check the below link:
https://github.com/vuejs/vue-cli/issues/4670

**Comment by sodatea** [comment]
Please make sure that `/home/clay/.npm-global/bin` is in your `$PATH` environment variable

**Comment by sodatea** [comment]
Also, it is recommended to use `@vue/cli` rather than `vue-cli`.

**Comment by TeAmP0is0N** [comment]
Solved, thank you!
