### ISSUE TITLE
'npm install -g vue-cli' error

### ISSUE THREAD

**Issue by ahmedfouzan** [vuejs/vue-cli#468]
My env
os :windows 8
node : v7.10.0
npm: 4.2.0

I executed the following command
`npm install -g vue-cli`
and the errors :
![err](https://cloud.githubusercontent.com/assets/14348478/26198598/3cf85d1e-3be4-11e7-882c-2881cf739bc5.png)

**Comment by posva** [comment]
I looked up a bit on google about that npm error and windows and it seems to happen to a lot of people with different packages. This thread may help you: https://github.com/npm/npm/issues/10826
Closing as it's not related to vue-cli
