### ISSUE TITLE
eslint-config-typescript depends on old version of @typescript-eslint/eslint-plugin and @typescript-eslint/parser

### ISSUE THREAD

**Issue by GauthierPLM** [vuejs/vue-cli#4680]
### Version
4.0.0-rc.8

### Reproduction link
[https://github.com/GauthierPLM/vue-cli-typescript-warning](https://github.com/GauthierPLM/vue-cli-typescript-warning)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 70.0
    Safari: 13.0.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  4.0.0-rc.8 
    @vue/babel-preset-jsx:  1.1.1 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.1.1 
    @vue/babel-sugar-v-on:  1.1.0 
    @vue/cli-overlay:  4.0.0-rc.8 
    @vue/cli-plugin-babel: ^4.0.0-rc.8 => 4.0.0-rc.8 
    @vue/cli-plugin-eslint: ^4.0.0-rc.8 => 4.0.0-rc.8 
    @vue/cli-plugin-router: ^4.0.0-rc.8 => 4.0.0-rc.8 
    @vue/cli-plugin-typescript: ^4.0.0-rc.8 => 4.0.0-rc.8 
    @vue/cli-service: ^4.0.0-rc.8 => 4.0.0-rc.8 
    @vue/cli-shared-utils:  4.0.0-rc.8 
    @vue/component-compiler-utils:  3.0.0 
    @vue/eslint-config-prettier: ^5.0.0 => 5.0.0 
    @vue/eslint-config-typescript: ^4.0.0 => 4.0.0 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.3 
    typescript: ^3.4.5 => 3.6.4 
    vue: ^2.6.10 => 2.6.10 
    vue-class-component: ^7.0.2 => 7.1.0 
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.7.1 
    vue-property-decorator: ^8.1.0 => 8.2.2 
    vue-router: ^3.0.6 => 3.1.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Create a new project using vue-cli@next.
In the preset, select TypeScript and Eslint Prettier.
Start a lint: the warning appears every time.

### What is expected?
Eslint should be the latest version to support the most up-to-date version of typescript. The warning about typescript version should not be displayed

### What is actually happening?
The following message is displayed:

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.2.1 <3.6.0

YOUR TYPESCRIPT VERSION: 3.6.4

Please only submit bug reports when using the officially supported version.

=============

---
This bug occurs with both vue-cli 3 and 4 (rc 8) on every new projects I created (giving that TypeScript and Eslint are enabled).

**Comment by doits** [comment]
:+1: just released v4 still has this old dependency

**Comment by sodatea** [comment]
Working on that. https://github.com/typescript-eslint/typescript-eslint/issues/883
We've temporarily pinned the typescript version in the default generator to `~3.5.3` until that issue has been resolved.

**Comment by Mister-Hope** [comment]
Update a new discovery here, if you don't have a vue.config.js or an empty one, no errors when hot load triigered by file save.

But it you add `chainWebapck` options (even an empty one):

```js
module.exports = {
  chainWebpack(config) { }
};
```

Errors like [Here](https://github.com/typescript-eslint/typescript-eslint/issues/883) will disappear

**Comment by doits** [comment]
typescript-eslint/typescript-eslint#883 was closed/fixed in the meantime - does it mean this one could be fixed now, too?

**Comment by GauthierPLM** [comment]
@doits the error is still here and no update has been released yet. So I guess it's a bit early to close the issue without confirmation from the dev team that it's indeed fixed.

**Comment by doits** [comment]
@GauthierPLM What I meant to say is: Now that typescript-eslint/typescript-eslint#883 issue is fixed - which was a blocker for *this* issue here - can *this* issue be worked on and get fixed? Maybe by simply updating the deps?

**Comment by c-bandy** [comment]
Made a PR for this vuejs/eslint-config-typescript#4

Hopefully we can line up a release for this soon so we can close this!

**Comment by c-bandy** [comment]
eslint-config-typescript was updated to 5.0.0 so I think this issues can be closed
