### ISSUE TITLE
vue.config.js在二级目录，怎么指定?

### ISSUE THREAD

**Issue by PandaTsui** [vuejs/vue-cli#4682]
### Version
3.8.1

### Environment info
```
win10, node10.16.0, npm 6.9.0
```

### Steps to reproduce
npx vue-cli-service serve 但是当前目录不存在vue.config.js，vue.config.js在二级目录./client里面.

### What is expected?
希望能够通过配置，指定vue.config.js的位置

### What is actually happening?
官网没有提供具体的配法，只是提了一下，说是在package.json里添加vue字段，尝试配置“vue”:"client" ， “vue”:"client/vue.config.js" ， “vue”:"./client/vue.config.js"  均不能生效 

---
我按照官网说的，在package.json里添加vue字段，但是没有成功？请问如何配置，或者发给vue field的用法链接？

**Comment by sodatea** [comment]
设置 `VUE_CLI_SERVICE_CONFIG_PATH` 环境变量
注意：虽然现在可以这样绕开，但我们不鼓励、也并没有官方支持这种用法，不保证这个用法未来会一直有效。
