### ISSUE TITLE
filenameHashing:false; 在pages的页面中使用了vue-router页面，打包生成的含很多chunk的js文件

### ISSUE THREAD

**Issue by jason65** [vuejs/vue-cli#4684]
在vue.config.js设置了filenameHashing:false;
pages:配置如下：
{ index:
   { entry: './src/pages/sd_user/index.ts',
     template: './src/pages/sd_user/index.html',
     filename: 'index.html' } }
打包生成js含很多chunk,如下；
chunk-7a70dd02.js；
期望：
生成的js去除这些随机的chuk改为index.js或者index_bundle.js

**Comment by sodatea** [comment]
https://webpack.js.org/guides/code-splitting/#dynamic-imports
