### ISSUE TITLE
4.0 not yet available on npmjs.com

### ISSUE THREAD

**Issue by vesper8** [vuejs/vue-cli#4687]
Just got a release alert for 4.0.. wtg on the long awaited launch!

Tried following the migration guide and `npm install -g @vue/cli` still installed 3.12 

I guess that's because 4.0 is not yet published on https://www.npmjs.com/package/@vue/cli

**Comment by sodatea** [comment]
Thanks for the report!
There was a bug in the release script that incorrectly set the `dist-tag` to `next`. I've manually added the packages to the `latest` dist-tag now.

**Comment by vesper8** [comment]
no problem! I guess it takes a while before it propagates? It's still not updated on npmjs.com

**Comment by sodatea** [comment]
Isn't it? On my side, it's all updated.

**Comment by vesper8** [comment]
hrmm.. it is? I just checked again on https://www.npmjs.com/package/@vue/cli.. using incognito to make sure it isn't cached

<img width="807" alt="Screen Shot 2019-10-16 at 3 50 57 PM" src="https://user-images.githubusercontent.com/816028/66920891-d8522480-f02c-11e9-985c-e158417a584a.png">

**Comment by sodatea** [comment]
Weird…
Here's what I saw:
![image](https://user-images.githubusercontent.com/3277634/66921018-fd5b8d00-f056-11e9-920b-af778e410790.png)

**Comment by vesper8** [comment]
hrmm. very weird indeed

I just tried running `npm install -g @vue/cli` again and unlike before where it just installed 3.12, this time I got this error:

```
npm install -g @vue/cli
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/cli-ui-addon-widgets@^4.0.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@vue/cli'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/redacted/.npm/_logs/2019-10-16T13_05_09_432Z-debug.log
```

**Comment by shaqq** [comment]
I have the exact same error, fwiw

**Comment by vesper8** [comment]
after running `npm remove -g @vue/cli` and then again `npm install -g @vue/cli` I am now on `@vue/cli@4.0.1`

**Comment by shaqq** [comment]
Maybe NPM needs the new package to propagate through some caching layer to make it to different people in different parts of the globe. It looks like @vue/cli-ui-addon-widgets@4.0.1 got published just 40 minutes ago.
