### ISSUE TITLE
Do you have multi-page cli?

### ISSUE THREAD

**Issue by zhangwei900808** [vuejs/vue-cli#469]
I have to new multi-page but the cli not found it and it SPA project!!!

**Comment by posva** [comment]
I guess, you mean a template. No, we don't

**Comment by zhangwei900808** [comment]
you dont understand my issue and close it. Do not the vue-cli only run the SPA project?

**Comment by egoist** [comment]
@zhangwei900808 I think you don't understand how vue-cli works, `vue init` is just a scaffolding tool. All you need is a template that is designed for multi-page project. btw, @posva understands you pretty well 😅

**Comment by posva** [comment]
You asked a question and I answered... Sorry if I didn't understand you, I
really tried

**Comment by LinusBorg** [comment]
The repository for the webpack template can be found here:

https://github.com/vuejs-templates/webpack

But I don't understand the specific problem.
