### ISSUE TITLE
Building with custom mode will lose all built-in config.

### ISSUE THREAD

**Issue by krave1986** [vuejs/vue-cli#4699]
### Version
3.4.1

### Environment info
```
System:
  OS: Windows 7
  CPU: (6) x64 Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Binaries:
  Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
npmGlobalPackages:
  @vue/cli: Not Found

```

### Steps to reproduce
1. add npm script to package.json
"buildtest": "vue-cli-service build --mode test"
2. create file .env.test
3. npm run buildtest

### What is expected?
Compressed output bundle with checksum in file name.

### What is actually happening?
Output bundle without compression nor checksum in file name.

**Comment by krave1986** [comment]
I can't see why it is not explicit in .env file.
What are the main features of CLI 4.0.3 by the way?

**Comment by sodatea** [comment]
A lot of bug fixes compared to 3.4.

https://cli.vuejs.org/guide/mode-and-env.html#modes
Takeaways:
1. 
> When running `vue-cli-service`, environment variables are loaded from all [corresponding files](https://cli.vuejs.org/guide/mode-and-env.html#environment-variables). If they don't contain a `NODE_ENV` variable, it will be set accordingly. For example, `NODE_ENV` will be set to `"production"` in production mode, `"test"` in test mode, and defaults to `"development"` otherwise.

2.
> `test` is used by `vue-cli-service test:unit`


3. 
> When you are running `vue-cli-service build`, your `NODE_ENV` should always be set to "production" to obtain an app ready for deployment, regardless of the environment you're deploying to.

The last one is because of the conventions in the Node.js ecosystem. Most tools won't enable those production-only features like minimization or dead code elimination or file name hashing under non-`production` env. For more background reading, see https://overreacted.io/how-does-the-development-mode-work/

**Comment by BryanAdamss** [comment]
> A lot of bug fixes compared to 3.4.
> 
> https://cli.vuejs.org/guide/mode-and-env.html#modes
> Takeaways:
> 1.
> 
> > When running `vue-cli-service`, environment variables are loaded from all [corresponding files](https://cli.vuejs.org/guide/mode-and-env.html#environment-variables). If they don't contain a `NODE_ENV` variable, it will be set accordingly. For example, `NODE_ENV` will be set to `"production"` in production mode, `"test"` in test mode, and defaults to `"development"` otherwise.
> 
> 
> > `test` is used by `vue-cli-service test:unit`
> 
> 
> > When you are running `vue-cli-service build`, your `NODE_ENV` should always be set to "production" to obtain an app ready for deployment, regardless of the environment you're deploying to.
> 
> The last one is because of the conventions in the Node.js ecosystem. Most tools won't enable those production-only features like minimization or dead code elimination or file name hashing under non-`production` env. For more background reading, see https://overreacted.io/how-does-the-development-mode-work/


---

What is the relationship between  `vue-cli mode(production、development、test)` and ` webpack mode(production、development)` and `NODE_ENV`?

If I use `vue-cli-service build --mode customMode`，and I do not create `.env.customMode` , In this case,`webpack mode`、`NODE_ENV`get what value?

**Comment by sodatea** [comment]
> If I use `vue-cli-service build --mode customMode`，and I do not create `.env.customMode` , In this case,`webpack mode`、`NODE_ENV` get what value?

- webpack mode: `development`
- `NODE_ENV`: `development`

> If I set `NODE_ENV=custom` in `.env.customMode`,what `webpack mode` get?

- webpack mode: `development`
- `NODE_ENV`: `custom`

But we do not recommend to set `NODE_ENV` to other values than the commonly used `production`, `development` and `test`.

**Comment by BryanAdamss** [comment]
> > If I use `vue-cli-service build --mode customMode`，and I do not create `.env.customMode` , In this case,`webpack mode`、`NODE_ENV` get what value?
> 
> * webpack mode: `development`
> * `NODE_ENV`: `development`
> 
> > If I set `NODE_ENV=custom` in `.env.customMode`,what `webpack mode` get?
> 
> * webpack mode: `development`
> * `NODE_ENV`: `custom`
> 
> But we do not recommend to set `NODE_ENV` to other values than the commonly used `production`, `development` and `test`.


Thank you for your reply😊! 

Is the following conclusion correct?
- Only the `NODE_ENV` get `production` value , the `webpack mode` could be `production`(enable compress). In other case ,`webpack mode` is always set as `development`

- ps:ignore my chingish😂

**Comment by sodatea** [comment]
Yeah that's correct.
