### ISSUE TITLE
How to get base64 img source after webpack?

### ISSUE THREAD

**Issue by fishenal** [vuejs/vue-cli#47]
i write something like this:

```<img :src='rtrImg(ava)'/>```
```
rtrImg (sex) {
      if (sex === '女') {
        return '../img/girl.jpg'
      } else {
        return '../img/boy.jpg'
      }
    }
```
i cant get the img resource because img has turn to base64 code.
how can i get these source in method inside ?
or any other way to write?

**Comment by azamat-sharapov** [comment]
Maybe pass one more attribute? Like `data-src`. Or you can just disable webpack's url-loader for images.

**Comment by yyx990803** [comment]
``` js
return require('../img/girl.jpg')
```

The require will be handled by file-loader and return the after-build file location.

**Comment by LorenzoSun** [comment]
1.<img :src="icon_src" />
2.import the image at the top level
import icon from 'icon.png';
3. data () { return { icon_src:icon } }
or computed instead

**Comment by rrki** [comment]
What if I got a base64 bytes array from a restful service?
Can I do <img src=“BASE64STR”> ?

**Comment by websmallrabbit** [comment]
> ```js
> return require('../img/girl.jpg')
> ```
> 
> The require will be handled by file-loader and return the after-build file location.

尤大， vue-cli3项目集成electron-vue 桌面系统, svg 怎么显示不出来，

```
import Vue from 'vue'
import SvgIcon from '@/components/SvgIcon'// svg component

// register globally
Vue.component('svg-icon', SvgIcon)

const req = require.context('./svg', false, /\.svg$/)
// const requireAll = requireContext => requireContext.keys().map(requireContext)

const requireAll = requireContext => requireContext.keys().map((key) => {
  console.log(key, req(key))
})
requireAll(req)

```
j转成了base64位图片
![image](https://user-images.githubusercontent.com/34472552/66709621-e8eb6c00-ed9a-11e9-94ce-100074bf827b.png)

正常的情况是
![image](https://user-images.githubusercontent.com/34472552/66709638-13d5c000-ed9b-11e9-904f-02d630b19be0.png)
