### ISSUE TITLE
[V3][V4] Plugin not installing correctly when adding version number

### ISSUE THREAD

**Issue by DRoet** [vuejs/vue-cli#4700]
### Version
4.0.3 and 3.12.0

### Reproduction link
[https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/119#issuecomment-543071642](https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/119#issuecomment-543071642)

### Environment info
```
 Binaries:
    Node: 12.11.1 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
```

### Steps to reproduce
```sh
npm install -g @vue/cli@3.12.0
vue create testapp
cd testapp
vue add vuetify@1.0.2
```

### What is expected?
Plugin gets installed and invoked just like when not specifying a version number: `vue add vuetify` works

### What is actually happening?
When using 3.12.0:

```sh
Successfully installed plugin: vue-cli-plugin-vuetify@1.0.2

Plugin vue-cli-plugin-vuetify@1.0.2 does not have a generator to invoke
```

When using 4.0.2:
```sh
Successfully installed plugin: vue-cli-plugin-vuetify@1.0.2

 ERROR  Error: Cannot resolve plugin vuetify@1.0.2 from package.json. Did you forget to install it?
```

**Comment by willemavjc** [comment]
For info: Still occurs with 4.0.5 (and vuetify 1.1.1)
