### ISSUE TITLE
Depenedency not found when running with --mode 

### ISSUE THREAD

**Issue by NickJoyce-IO** [vuejs/vue-cli#4704]
### Version
4.0.0

### Reproduction link
[https://github.com/NickJoyce-IO/testvuecli](https://github.com/NickJoyce-IO/testvuecli)

### Environment info
```
Environment Info:

  System:
    OS: Windows 8.1
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2665 0 @ 2.40GHz
  Binaries:
    Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  4.0.3
    @vue/babel-preset-jsx:  1.1.1
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.1.1
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  4.0.3
    @vue/cli-plugin-babel: ^4.0.0 => 4.0.3
    @vue/cli-plugin-eslint: ^4.0.0 => 4.0.3
    @vue/cli-plugin-router:  4.0.3
    @vue/cli-plugin-vuex:  4.0.3
    @vue/cli-service: ^4.0.0 => 4.0.3
    @vue/cli-shared-utils:  4.0.3
    @vue/component-compiler-utils:  3.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
npm run serve --mode staging or
npm run build --mode staging

### What is expected?
It either to serve or build the files with the .env.staging file I have created

### What is actually happening?
I get the below error message, it appears to be looking in a dir with the name of the argument I defined

 ERROR  Failed to compile with 2 errors                                        12:25:15 PM

This dependency was not found:

* C:\Users\njoy\Documents\projects\testvuecli\staging in multi (webpack)-dev-server/client?http://10.202.31.100:8081/sockjs-node (webpack)/hot/dev-server.js ./staging, multi (webpack)-dev-server/client?http://localhost (webpack)/hot/dev-server.js (webpack)-dev-server/client?http://10.202.31.100:8081/sockjs-node ./staging

To install it, you can run: npm install --save C:\Users\njoy\Documents\projects\testvuecli\staging

---
npm run serve and npm run build run fine

I am porting across some code that was built outside vue-cli into vue-cli.

**Comment by sodatea** [comment]
If you want to pass arguments to npm scripts, a `--` is required:
`npm run serve -- --mode staging`
