### ISSUE TITLE
Upgrade jest version

### ISSUE THREAD

**Issue by AriLFrankel** [vuejs/vue-cli#4707]
### What problem does this feature solve?
Vue-Cli is two minor versions back in Jest. This is a proposal to upgrade to the latest version

https://new-issue.vuejs.org/?repo=vuejs/vue-cli

### What does the proposed API look like?
N/A

**Comment by sodatea** [comment]
Thanks for the reminder. But as we use the caret version range `^24.8.0`, package managers will automatically resolve to the latest minor version that satisfies this range. We also do a periodical dependency maintenance, so there's no need to do this urgently.
