### ISSUE TITLE
when run vue-cli-service server with  --port xxxx, not inject .env.development

### ISSUE THREAD

**Issue by elevenkey** [vuejs/vue-cli#4713]
### Version
3.9.3

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /mnt/c/Users/Administrator/AppData/Roaming/npm/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: 3.9.3
```

### Steps to reproduce
1、add .env.development 
2、vue-cli-service serve --port 9090

### What is expected?
in .env.development

NODE_ENV = development
VUE_APP_FLAG = pro00
VUE_APP_URL = http://192.168.8.88

when vue-cli-services --port 9090 can load .evn.development

### What is actually happening?
console.log(process.evn)
{
BASE_URL: ""
NODE_ENV: "development"
}

**Comment by sodatea** [comment]
Please provide a runnable reproduction.

Are these envs logged from `vue.config.js` or from the web app?
