### ISSUE TITLE
Error using vue upgrade

### ISSUE THREAD

**Issue by wrtisans** [vuejs/vue-cli#4717]
### Version
3.12.0

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.12.0 - ~/.nvm/versions/node/v12.12.0/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v12.12.0/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.12.0/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: Not Found
    Safari: 13.0.2
  npmGlobalPackages:
    @vue/cli: 3.12.0
```

### Steps to reproduce
just type 

vue upgrade 

### What is expected?
upgrade vue-cli to latest version (4.0.4)

### What is actually happening?
➜ vue upgrade

  Command vue upgrade requires a global addon to be installed.
  Please run yarn global add @vue/cli-upgrade and try again.

when i run that command i got 

warning "@vue/cli-upgrade@3.12.1" has no binaries

---
➜ vue upgrade

  Command vue upgrade requires a global addon to be installed.
  Please run yarn global add @vue/cli-upgrade and try again.

when i run that command i got 

warning "@vue/cli-upgrade@3.12.1" has no binaries

**Comment by sodatea** [comment]
`vue upgrade` is not for upgrading the CLI itself. It's meant to be used in projects. You need to run `npm i -g @vue/cli` or `yarn global add @vue/cli` to install the latest CLI, and then run `vue upgrade` in projects that scaffolded by 3.x CLI.
