### ISSUE TITLE
`vue create .` hangs 

### ISSUE THREAD

**Issue by bruceauyeung** [vuejs/vue-cli#4718]
### Version
vue-cli: 4.0.4

### Reproduction link
[http://no-link-needed-for-this-issue.github.com](http://no-link-needed-for-this-issue.github.com)

### Environment info
```
$ vue info

Environment Info:

  System:
    OS: Linux 4.19 Manjaro Linux undefined
    CPU: (4) x64 AMD Athlon(tm) X4 870K Quad Core Processor
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v12.4.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: Not Found

[bruce@bruce-manjaro ~]$ which vue
/home/bruce/.yarn/bin/vue
[bruce@bruce-manjaro ~]$ which firefox-beta
/usr/bin/firefox-beta


```

### Steps to reproduce
1. install `nvm`
2. install nodejs 12.4.0 using nvm:   `nvm install 12.4.0`
3. install yarn using node:  `node i yarn -g`
4. install vue-cli using yarn: `yarn global add @vue/cli`
5. add `/home/bruce/.yarn/bin/` into env variable `$PATH`
6. use `vue` command to create a vue+typescript project with features: less, babel, typescript, router, vuex, eslint, unit-jest, e2e-cypress
7. vue command hangs at here,  no matter how long i wait for:
~~~
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/5] ⠄ waiting...
[-/5] ⠄ waiting...
[-/5] ⠄ waiting...
[-/5] ⠄ waiting...
^C/5] ⠄ cypress
~~~

### What is expected?
`vue create .`  creates this project successfully.

### What is actually happening?
`vue create .` hangs

**Comment by sodatea** [comment]
Likely a network issue.
Considering you are in China, please set this environment variable and try again:
```bash
export CYPRESS_INSTALL_BINARY=https://npm.taobao.org/mirrors/cypress/3.4.1/linux-x64/cypress.zip
```

**Comment by bruceauyeung** [comment]
@sodatea i will try this evening.
when this situation happened, i'd like to enable `vue-cli`'s debug mode / verbose mode to figure out what's happening, but `vue-cli` seems lack of it.

**Comment by bruceauyeung** [comment]
@sodatea  i tried just now in my windows 7 64bit environment.
1. set env variable: `set CYPRESS_INSTALL_BINARY=https://npm.taobao.org/mirrors/cypress/3.4.1/win32-x64/cypress.zip`
2. run `vue create helloworld` 2 times. at the first time,  it hangs as described,  but at the second time,  `vue create helloworld`  finished  its job very soon. I think it's indeed related to network lag.

about the `verbose mode` i mentioned, should i fire a feature request ?

**Comment by LinusBorg** [comment]
@bruceauyeung you can certainly open a separate feature request for this.

I'll close this issue here since it seems to be related to the network, not Vue CLI
