### ISSUE TITLE
How to use the "setup"

### ISSUE THREAD

**Issue by wengcd** [vuejs/vue-cli#472]
https://github.com/vuejs/vue-cli/blob/master/docs/build.md#setup

witch file could be written?

```
module.exports = {
  setup(app) {
    app.get('/api', (req, res) => {
      res.end('This is the API')
    })
  }
}
```

**Comment by LinusBorg** [comment]
Are you asking into what file you should add this code? Thius is explained here:

https://github.com/vuejs/vue-cli/blob/master/docs/build.md#configuration-files

**Comment by wengcd** [comment]
I mean how to mock api

**Comment by LinusBorg** [comment]
Then you might rather look at the `proxy` option:

https://github.com/vuejs/vue-cli/blob/master/docs/build.md#proxy
