### ISSUE TITLE
4.0.4的"vue ui"没有最新的预设“installui”，并且“默认预设”安装路由时仍然需要确认！

### ISSUE THREAD

**Issue by playfulhd** [vuejs/vue-cli#4725]
### Version
4.0.4

### Environment info
```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz
  Binaries:
    Node: 12.12.0 - D:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.11.3 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. node官网安装12.12.0版本
2. npm i -g @vue/cli
3. vue ui

### What is expected?
创建并运行项目

### What is actually happening?
安装异常

---
- 使用“vue ui”创建项目，没有最新的“installui”预设
- 使用“默认预设”，选择“vue-router”按钮，仍然需要在dos里确认
- 使用“vue info”打印信息，显示“ @vue/cli: Not Found”
- 已安装插件列表，最新版本号都是0.1.0

Dos：
vue ui
🚀  Starting GUI...
🌠  Ready on http://localhost:8000
✨  Creating project in E:\Code\Test\vue\vue-test-4.0.4.
🗃  Initializing git repository...
⚓  Running completion hooks...
📄  Generating README.md...

📦  Installing @vue/cli-plugin-router...

  @vue/cli-plugin-router@4.0.4
updated 1 package in 14.508s
✔  Successfully installed plugin: @vue/cli-plugin-router

? Use history mode for router? (Requires proper server setup for index fallback in production) (Y/n)

**Comment by sodatea** [comment]
installui 预设是什么？
另一个问题是已知 bug，我们会尽快修复。

**Comment by sodatea** [comment]
预设的问题，你看一下你的 ~/.vuerc 文件。
所有用户定义预设都是存到这里的，可能是你不同电脑上存的预设不一样。

**Comment by playfulhd** [comment]
> installui 预设是什么？
> 另一个问题是已知 bug，我们会尽快修复。

好的，明白了
