### ISSUE TITLE
vue upgrade does not check vue.config.js for deprecated sass-loader options

### ISSUE THREAD

**Issue by nstuyvesant** [vuejs/vue-cli#4726]
### Version
4.0.4

### Reproduction link
[https://github.com/nstuyvesant/shy3/commit/05e52316539b0c63db8c340c518c2334769de60e#diff-0e893b3578ae3d5c8b98bac1c80756a7](https://github.com/nstuyvesant/shy3/commit/05e52316539b0c63db8c340c518c2334769de60e#diff-0e893b3578ae3d5c8b98bac1c80756a7)

### Environment info
```
  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.12.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: Not Found
    Safari: 13.0.2
  npmPackages:
    @fortawesome/vue-fontawesome: ^0.1.7 => 0.1.7 
    @types/vuelidate: ^0.7.7 => 0.7.7 
    @vue/cli-overlay:  4.0.4 
    @vue/cli-plugin-e2e-cypress: ^4.0.4 => 4.0.4 
    @vue/cli-plugin-pwa: ^4.0.4 => 4.0.4 
    @vue/cli-plugin-router:  4.0.4 
    @vue/cli-plugin-typescript: ^4.0.4 => 4.0.4 
    @vue/cli-plugin-unit-jest: ^4.0.4 => 4.0.4 
    @vue/cli-plugin-vuex:  4.0.4 
    @vue/cli-service: ^4.0.4 => 4.0.4 
    @vue/cli-shared-utils:  4.0.4 
    @vue/component-compiler-utils:  3.0.0 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29 
    @vue/web-component-wrapper:  1.2.0 
    bootstrap-vue: ^2.0.4 => 2.0.4 
    jest-serializer-vue:  2.0.2 
    portal-vue:  2.1.6 
    typescript: ^3.6.4 => 3.6.4 
    vue: ^2.6.10 => 2.6.10 
    vue-class-component: ^7.1.0 => 7.1.0 
    vue-cli-plugin-pug: ^1.0.7 => 1.0.7 
    vue-cli-webpack:  1.0.0 
    vue-functional-data-merge:  3.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-jest:  3.0.5 
    vue-loader:  15.7.1 
    vue-property-decorator: ^8.3.0 => 8.3.0 
    vue-router: ^3.1.3 => 3.1.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuelidate: ^0.7.4 => 0.7.4 
  npmGlobalPackages:
    @vue/cli: 4.0.4
```

### Steps to reproduce
If upgrading from an older version of vue-cli and you have an export for configureWebpack.css.loaderOptions.scss.data, using sass-loader 8 will fail. 

### What is expected?
Running "vue upgrade" should check for this deprecated option and suggest replacing it with configureWebpack.css.loaderOptions.scss.prependData.

### What is actually happening?
vue upgrade outputs:
✔  Gathering package information...
 DONE  Seems all plugins are up to date. Good work!

**Comment by sodatea** [comment]
The sass-loader v8 update is more than just renaming the options.

For example:
> The `functions` option can't be used as `Function`, you should use `sassOption` as `Function` to achieve this.

This is not something that we can automate without breaking any existing use cases. Plus, sass-loader v7 is still supported so it's not a mandatory update.

So I think it's better to leave the version warning as a reminder at runtime.
