### ISSUE TITLE
vue-cli3创建sass工程，npm run serve 

### ISSUE THREAD

**Issue by objcxiaobai** [vuejs/vue-cli#4729]
### Version
3.12.0

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Environment info
```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: Not Found
    Safari: 12.1.2
  npmGlobalPackages:
    @vue/cli: 3.12.0
```

### Steps to reproduce
选择 node-sass

在home.vue文件下引入其他.vue文件

npm run serve 无法运行报错

### What is expected?
能够正常运行

### What is actually happening?
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Home.vue?vue&type=script&lang=js& 15:0-46 20:10-14
 @ ./src/views/Home.vue?vue&type=script&lang=js&
 @ ./src/views/Home.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.0.106:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by sodatea** [comment]
请提供复现代码。

**Comment by objcxiaobai** [comment]
```
<template>
  <div class="container">
    <nav-bar></nav-bar>
    <div class="content-box">
      <tags></tags>
      <div class="content">
        <router-view></router-view>
      </div>
    </div>
  </div>
</template>
<script>
// @ is an alias to /src
import NavBar from "@/components/NavBar/NavBar.vue";
import Tags from "@/components/Tags/Tags.vue"
export default {
  name: "home",
  components: {
    NavBar,
    Tags
  }
};
</script>

```

**Comment by objcxiaobai** [comment]
@sodatea  当引入第二个tags.vue文件的时候,完全启动不了。

**Comment by sodatea** [comment]
麻烦提供一下完整的可以运行的代码……目前这样看不出问题

**Comment by objcxiaobai** [comment]
@sodatea  前辈，请教一下...是通过codepen形式还是上传github再发链接..

**Comment by sodatea** [comment]
GitHub 吧

**Comment by objcxiaobai** [comment]
@sodatea https://github.com/objcxiaobai/example

**Comment by sodatea** [comment]
控制台提示是 ESLint 报错。
先跑一遍 `npm run lint` 修掉可以自动修复的问题，再删掉 https://github.com/objcxiaobai/example/blob/4310c6c2dadc1fdadebdbe39fc4dd63c08543244/src/components/Tags/Tags.vue#L21-L23 这里没用到的 `oldValue` 解决掉那个 `no-unused-vars` 报错。就可以运行了。

**Comment by objcxiaobai** [comment]
@sodatea  非常感谢前辈
