### ISSUE TITLE
vue-cli-service build --name some-component --entry ./packages/index.js --target lib

### ISSUE THREAD

**Issue by firekcc** [vuejs/vue-cli#4735]
### What problem does this feature solve?
this command not let vue.config.js work,i add some setting to drop_console

configureWebpack(config) {
    if (process.env.NODE_ENV === 'production') {
      const terserWebpackPlugin = config.optimization.minimizer[0];
      const terserOptions = terserWebpackPlugin.options.terserOptions;
      terserOptions.compress["warnings"] = false;
      terserOptions.compress["drop_console"] = true;
      terserOptions.compress["drop_debugger"] = true;
      terserOptions.compress["pure_funcs"] = ['console.log']
    }
  }

### What does the proposed API look like?
vue-cli-service build

**Comment by firekcc** [comment]
but i use the command:vue-cli-service serve --mode=production has work,did the --target lib no use the vue.config.js,if i require use webpack plugin in the env of  --target lib,can i take what method to slove the problem.

**Comment by LinusBorg** [comment]
I can't really follow your description. What's not working? terser is not picking up your changed options when building as a library?

We would need a reproduction to understand what's going on, so please provide one.

**Comment by firekcc** [comment]
I know the seeting is work in the umd 
https://cli.vuejs.org/guide/build-targets.html#library
office say ： dist/myLib.common.js: A CommonJS bundle for consuming via bundlers (unfortunately, webpack currently does not support ES modules output format for bundles yet)
only the umd.min.js is work

**Comment by firekcc** [comment]
package.json    is "main": "dist/vuedraggable.umd.min.js", not "main": "dist/vuedraggable.umd.js"
