### ISSUE TITLE
Typescript support enhance

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vue-cli#4738]
### What problem does this feature solve?

I suggest the official  make these changes to enhance typescript support.

Now developeres still have a bad experience using typescript

-  let `@vue/cli-plugin-typescript` Support Typescript 3.6
    > Now Typescript3.6 stiill marked as unsupport version
-  update `@vue/eslint-config-typescript`  dependecies as `@typescript-eslint V2` now fullly support vue.
  
    > See [#1083](https://github.com/typescript-eslint/typescript-eslint/pull/1083)
    > `@vue/eslint-config-typescript` still use V1 version and it contain bugs and conflicts with prettier and other eslint plugins

**Comment by zerefwayne** [comment]
Hey @sodatea, can I work on this issue?

**Comment by sodatea** [comment]
Yeah go ahead, please

**Comment by qidaneix** [comment]
Hey @zerefwayne @sodatea, could you please update `eslint` to `eslint^6.x`? I want to use `extends` property in `overrides`, but it seems donot support on `eslint^5.x`, which is used in `vue-cli^4`

**Comment by doits** [comment]
I tried to find the source for `@vue/eslint-config-typescript` to see if I could update the versions, but it is not in https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue anymore - where can I find it? Or how can it be updated?

**Comment by sodatea** [comment]
https://github.com/vuejs/eslint-config-typescript

Note: it's not as simple as upgrading the dependency versions - there are breaking changes in config options too, per https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.0.0

**Comment by doits** [comment]
thanks @sodatea, I see there is already a PR https://github.com/vuejs/eslint-config-typescript/pull/3 for updating things.

**Comment by zakjan** [comment]
New version of `@vue/eslint-config-typescript` with TS 3.7 support just got released

**Comment by zakjan** [comment]
@Mister-Hope I can't find what's missing to implement in `@vue/cli-plugin-typescript`?

**Comment by doits** [comment]
It should be working now after an update to `"@vue/eslint-config-typescript": "^5.0.0"`. I can lint my typescript 3.7.2-codebase without any problems now.

**Comment by Mister-Hope** [comment]
Since no one is getting problems any more, I am closing this issue.

**Comment by GerryWilko** [comment]
Could someone explain how to enable support for TS 3.7+? I have upgraded all my dependencies, cli plugins and eslint to latest and my code is linting fine and vscode is not showing any ts errors.

However when actually being compiled Babel is complaining that it doesnt understand ``??`` and asking to install an experimental plugin. The CLI is showing ts 3.7.3 when compiling but it seems that typescript is not replacing its new coalese syntax at compile time any ideas?

Thanks guys!

Here are all my dev dependencies incase it helps:

"devDependencies": {
    "@types/chai": "^4.1.0",
    "@types/mocha": "^5.2.7",
    "@types/vue-markdown": "^2.2.1",
    "@typescript-eslint/eslint-plugin": "^2.7.0",
    "@typescript-eslint/parser": "^2.7.0",
    "@vue/cli-plugin-babel": "^4.1.1",
    "@vue/cli-plugin-eslint": "^4.1.1",
    "@vue/cli-plugin-typescript": "^4.1.1",
    "@vue/cli-plugin-unit-mocha": "^4.1.1",
    "@vue/cli-service": "^4.1.1",
    "@vue/eslint-config-airbnb": "^5.0.0",
    "@vue/eslint-config-typescript": "^5.0.1",
    "@vue/test-utils": "1.0.0-beta.29",
    "babel-eslint": "^10.0.3",
    "chai": "^4.1.2",
    "copy-webpack-plugin": "^5.0.4",
    "cross-env": "^6.0.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.0.1",
    "mocha-junit-reporter": "^1.23.1",
    "mocha-teamcity-reporter": "^3.0.0",
    "npm-run-all": "^4.1.5",
    "sass": "^1.19.0",
    "sass-loader": "^8.0.0",
    "typescript": "~3.7.3",
    "vue-template-compiler": "^2.6.10"
  }

**Comment by Mister-Hope** [comment]
@GerryWilko I wound lilke to help you if you can create a minial example on github for me to clone

**Comment by sodatea** [comment]
@GerryWilko It's because TypeScript won't transform this syntax for the `esnext` target.

Workarounds:
1. Change the `target` field in `tsconfig.json` to `es2019` (don't use `es2020` because although it still does the transformation at the moment, it might soon stop transforming as the proposal will soon land in the official `es2020` standard);
2. Configure babel to add the corresponding plugins for this syntax.

Or, you can wait until https://github.com/babel/babel/pull/10811 is landed in babel

**Comment by GerryWilko** [comment]
@Mister-Hope @sodatea Thank you both. @sodatea I noticed this too yesterday. I have updated my ES to 2019 for now. That solves the problem.

Presumably we are going to have to wait for [babel/babel#10811](https://github.com/babel/babel/pull/10811)  before Vue CLI can fully go to TS 3.7!
