### ISSUE TITLE
Vue Build Stylus and Pug Missing Module

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue-cli#474]
i'm using the new vue-build command which reduces alot of config but when using pug and stylus it gives errors where it can't find the module so i tried to hack a way to it and install the pug and pug-loader same to stylus inside the vue-cli in the npm globally

any way that i can do this right without doing the global way?

**Comment by egoist** [comment]
Install all of them including vue-cli locally in your project.

**Comment by ralphchristianeclipse** [comment]
@egoist can the collaborators provide a property in the config.js stylus: true or pug: true so the global vue-cli will install there i think the vue-cli is very convenient globally reducing download times and repetetive node_modules

**Comment by LinusBorg** [comment]
I don't see how that does save any noticable time compared to typing `yar add pug pug-loader stylus-loader`

**Comment by posva** [comment]
You can also head to `~/.vue` and install any dependency you need as well as using your own webpack config 😉
