### ISSUE TITLE
default --mode option to NODE_ENV

### ISSUE THREAD

**Issue by cdekok** [vuejs/vue-cli#4743]
### What problem does this feature solve?
Simplify build environments

### What does the proposed API look like?
Currently if I want to run a test build I have to do `vue-cli-service build --mode=test` if It would respect the NODE_ENV I could run it as `NODE_ENV=development vue-cli-service build` or `NODE_ENV=development yarn build`

**Comment by LinusBorg** [comment]
But you can do that... Granted I may be missing something from your one sentence of information and lack of example, but ... you can set NODE_ENV like that today and it will be respected.

**Comment by cdekok** [comment]
No it doesn't seem to work like that for example see this: https://github.com/cdekok/vue-env
When you run `./node_modules/.bin/vue-cli-service serve --mode=test` You will get a console statement with the output of `test` but if you would run `NODE_ENV=test yarn serve` the output is undefined.

**Comment by LinusBorg** [comment]
where in that repo did you add the console log? there's only one big init commit.

**Comment by cdekok** [comment]
Sorry I forgot to push the commit it's now on:
https://github.com/cdekok/vue-env/blob/master/src/main.ts#L8
https://github.com/cdekok/vue-env/blob/master/.env.test#L1

**Comment by LinusBorg** [comment]
Oh, now I gt it. you want to set the actual `mode` depending on th NODE_ENV value. I didn't understand that, the example made it clear for me.

That's not how this is intended to work. As explained in the documentation, we have three main modes, that map to a NODE_ENV of the same name:

* `development`: for the development server (i.e. with hot module reloading)
* `production`: for a production-style build (i.e. with minification)
* `test`: webpack config for unit tests with mocha-webpack

We however allow for users to define their own modes that implement variants of the above. For that, you have to define an env file with that mode's name, and *each custom mode has to define one of the three main `NODE_ENV` values* so Vue CLI knows in which main mode this custom mode is intended to run.

So from that i think it becomes clear that we can't have the NODE_ENV define the mode as 

1. the mode is more than just NODE_ENV
2. You can't have NODE_ENV values like `staging` or `acceptance`
