### ISSUE TITLE
Build failed with errors - Returned: code: 1  signal: null

### ISSUE THREAD

**Issue by dukedhx** [vuejs/vue-cli#4745]
### Version
4.0.5

### Reproduction link
[https://github.com/Autodesk-Forge/forge-digital-catalog](https://github.com/Autodesk-Forge/forge-digital-catalog)

### Environment info
```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 10.9.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 77.0.3865.120
    Firefox: 62.0
    Safari: 12.1.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  4.0.5 
    @vue/babel-preset-jsx:  1.1.1 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.1.1 
    @vue/babel-sugar-v-on:  1.1.0 
    @vue/cli-overlay:  4.0.5 
    @vue/cli-plugin-babel: ^4.0.5 => 4.0.5 
    @vue/cli-plugin-eslint: ^4.0.5 => 4.0.5 
    @vue/cli-plugin-pwa: ^4.0.5 => 4.0.5 
    @vue/cli-plugin-router:  4.0.5 
    @vue/cli-plugin-typescript: ^4.0.5 => 4.0.5 
    @vue/cli-plugin-vuex:  4.0.5 
    @vue/cli-service: ^4.0.5 => 4.0.5 
    @vue/cli-shared-utils:  4.0.5 
    @vue/component-compiler-utils:  3.0.0 
    @vue/eslint-config-typescript: ^4.0.0 => 4.0.0 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: 5.2.3 => 5.2.3 
    eslint-plugin-vuetify: 1.0.0-beta.3 => 1.0.0-beta.3 
    typescript: ^3.4.3 => 3.6.4 
    vue: 2.6.10 => 2.6.10 
    vue-class-component: ^7.0.2 => 7.1.0 
    vue-cli-plugin-axios: 0.0.4 => 0.0.4 
    vue-cli-plugin-vuetify: ^1.1.1 => 1.1.1 
    vue-eslint-parser:  undefined (5.0.0)
    vue-hot-reload-api:  2.3.4 
    vue-i18n: 8.14.1 => 8.14.1 
    vue-jest: 3.0.5 => 3.0.5 
    vue-loader:  15.7.1 
    vue-mq: 1.0.1 => 1.0.1 
    vue-property-decorator: ^8.1.0 => 8.2.2 
    vue-router: 3.1.3 => 3.1.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: 2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuejs-logger: 1.5.3 => 1.5.3 
    vuetify: 2.0.17 => 2.0.17 
    vuetify-loader: 1.3.0 => 1.3.0 
    vuex: 3.1.1 => 3.1.1 
  npmGlobalPackages:
    @vue/cli: 4.0.5
```

### Steps to reproduce
vue upgrade
vue-cli-service build

### What is expected?
the project was building before upgrading to v4

### What is actually happening?
build is failing with below as the only info in the log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/10.9.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.2.0
3 info using node@v10.9.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle forge-digital-catalog-app@0.1.0~prebuild: forge-digital-catalog-app@0.1.0
6 info lifecycle forge-digital-catalog-app@0.1.0~build: forge-digital-catalog-app@0.1.0
7 verbose lifecycle forge-digital-catalog-app@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle forge-digital-catalog-app@0.1.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/huangbr/Projects/Digital Catalog/node_modules/.bin:/Users/huangbr/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/huangbr/Go/bin:/usr/local/opt/go/libexec/bin
9 verbose lifecycle forge-digital-catalog-app@0.1.0~build: CWD: /Users/huangbr/Projects/Digital Catalog
10 silly lifecycle forge-digital-catalog-app@0.1.0~build: Args: [ '-c', 'vue-cli-service build --mode development' ]
11 silly lifecycle forge-digital-catalog-app@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle forge-digital-catalog-app@0.1.0~build: Failed to exec build script
13 verbose stack Error: forge-digital-catalog-app@0.1.0 build: `vue-cli-service build --mode development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
14 verbose pkgid forge-digital-catalog-app@0.1.0
15 verbose cwd /Users/huangbr/Projects/Digital Catalog
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/10.9.0/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.9.0
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error forge-digital-catalog-app@0.1.0 build: `vue-cli-service build --mode development`
22 error Exit status 1
23 error Failed at the forge-digital-catalog-app@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

---
vue ui shows there were "76" errors but there appears to be no way to see the actual errors...

**Comment by sodatea** [comment]
If you don't delete the `friendly-errors` plugin then the errors are shown.
These errors are related to `core-js`.

Solution: either upgrade the `core-js` version in `babel.config.js` to `2`, or downgrade the `core-js` version in the dependencies to `3`.

Sorry for not being able to cover this use case in the migrator.
But I really don't know how to programmatically detect such cases at the moment.

**Comment by mazerab** [comment]
Hello @sodatea , thank you for prompt reply. Our babel.config.js file is already using version 2 of core-js.

`module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        'corejs': 'core-js@2',
        'useBuiltIns': 'usage'
      }
    ]
  ]
}`

**Comment by sodatea** [comment]
I mean, in the migrator, we’ve upgrade the one in `package.json` to 3 after you running `vue upgrade`

**Comment by dukedhx** [comment]
Thanks @sodatea I was able to build after upgrading to core3

**Comment by mazerab** [comment]
@sodatea after updating my package.json to use the cli plugins at version 4.0.5 and core-js at version 3.3.3, and updating babel.config.js to use core-js version 3, I am still seeing an error on the first run of npm run build. Without changing anything, re-running the npm run build command succeeds. 

Here is the error on first build run:
`13 verbose stack Error: forge-digital-catalog-app@0.1.0 build: `vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid forge-digital-catalog-app@0.1.0
15 verbose cwd /Users/mazerab/Repos/digital-catalog
16 verbose Darwin 19.0.0
17 verbose argv "/usr/local/Cellar/node/12.12.0/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v12.12.0`

Why does the build command fails on first run but not on second run?

**Comment by dukedhx** [comment]
Like Haoqun suggested install friendly-errors to see the error details......

**Comment by mazerab** [comment]
I solved the issue after installing friendly-error and commenting out a console statement. Here is the error that was exposed:

`Module Error (from ./node_modules/thread-loader/dist/cjs.js):

/Users/mazerab/Repos/digital-catalog/src/client/plugins/axios.js
  45:7  error  Unexpected console statement  no-console`
