### ISSUE TITLE
Execute vue ui error

### ISSUE THREAD

**Issue by LiuCaiHe** [vuejs/vue-cli#4747]
### Version
4.0.5

### Environment info
```
$ vue info

Environment Info:

  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
  Binaries:
    Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.5.0/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: Not Found
    Safari: 13.0.2
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
$ vue ui 
🚀  Starting GUI...
 ERROR  Error: 
               
Vue packages version mismatch:
               
- vue@2.5.17 (/Users/xxxxx/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/Users/xxxxx/.config/yarn/global/node_modules/vue-jscodeshift-adapter/node_modules/vue-template-compiler/package.json)
               
This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
               
/Users/xxxxx/.config/yarn/global/node_modules/vue-jscodeshift-adapter/node_modules/vue-template-compiler/index.js:1
Error: 

Vue packages version mismatch:

- vue@2.5.17 (/Users/xxxxx/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.10 (/Users/xxxxx/.config/yarn/global/node_modules/vue-jscodeshift-adapter/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/xxxxx/.config/yarn/global/node_modules/vue-jscodeshift-adapter/node_modules/vue-template-compiler/index.js:10:9)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)

### What is expected?
Start the vue ui interface

### What is actually happening?
Unable to start vue ui

Uninstall @vue/cli (yarn global remove @vue/cli)
Reinstall @vue/cli (yarn blobal add @vue/cli)
Still the same

**Comment by Noor600** [comment]
i have problem too 
 i got this message throw er; // Unhandled 'error' event
