### ISSUE TITLE
Vue CLI 4 doesn't work correct with SCSS sourcemaps

### ISSUE THREAD

**Issue by VasiliyRusin** [vuejs/vue-cli#4761]
### Version
4.0.5

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (6) x64 Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
  Binaries:
    Node: 12.13.0 - /usr/bin/node
    Yarn: Not Found
    npm: 6.12.0 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 70.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  4.0.5 
    @vue/babel-preset-jsx:  1.1.1 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.1.1 
    @vue/babel-sugar-v-on:  1.1.0 
    @vue/cli-overlay:  4.0.5 
    @vue/cli-plugin-babel: ^4.0.0 => 4.0.5 
    @vue/cli-plugin-eslint: ^4.0.0 => 4.0.5 
    @vue/cli-plugin-pwa: ^4.0.0 => 4.0.5 
    @vue/cli-plugin-router: ^4.0.0 => 4.0.5 
    @vue/cli-plugin-vuex: ^4.0.0 => 4.0.5 
    @vue/cli-service: ^4.0.0 => 4.0.5 
    @vue/cli-shared-utils:  4.0.5 
    @vue/component-compiler-utils:  3.0.0 
    @vue/eslint-config-prettier: ^5.0.0 => 5.0.0 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.3 
    vue: ^2.6.10 => 2.6.10 
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.7.1 
    vue-router: ^3.1.3 => 3.1.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.1.1 
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
1. Create a new project (I create it with npx), or open existed. 
2. Run: `npm run serve`
2. Try to get the source of CSS code in dev tools (Chrome/Firefox/Edge).

### What is expected?
See source file and link on it. (App.vue, for example)

### What is actually happening?
See <style> (in Chrome) or inline:1 (in Firefox).

### Screenshots
![image](https://user-images.githubusercontent.com/3685852/67635059-200e6100-f8f5-11e9-8785-b660d5904322.png)

---
I'm not sure that it's vue-cli problem, and I will be glad to get any response for my searches.

**Comment by LinusBorg** [comment]
Hi @VasiliyRusin 

Your description leaves out many details (e.g.: "open a project" - do you mean run a built project, or run `serve`? There's a difference in how CSS is handled), and your post is missing a reproduction, which is a requirement for bug reports.

Please provide the necessary information so we can properly analyse the issue you are reporting.

**Comment by VasiliyRusin** [comment]
@LinusBorg, sorry, of course, I should mention about "serve". Description updated.

**Comment by LinusBorg** [comment]
Are you aware that CSS sourcemaps are deactivated by default?

https://cli.vuejs.org/config/#css-sourcemap

**Comment by VasiliyRusin** [comment]
@LinusBorg, oh sorry. Has it been changed recently? Maybe I'm mistaken, but I think that my older projects generated sourcemaps without this flag.

**Comment by LinusBorg** [comment]
No it has always been this way

**Comment by VasiliyRusin** [comment]
@LinusBorg, thank you for your help.

**Comment by kirkbross** [comment]
Closed issue, but related to this... any thoughts on why sourcemaps for nested scss shows you the line number for the top parent of your nested rules, versus giving you the exact line number? Is there something I need add to vue.config.js?
