### ISSUE TITLE
Can you differentiate mode and command when loading .env files?

### ISSUE THREAD

**Issue by krave1986** [vuejs/vue-cli#4762]
### What problem does this feature solve?
Suppose that we can load diffentent .env files for `vue-cli-service build` and `vue-cli-service serve`, we can put same options for build or serve together. Which is very common in many cases.
And leave per-mode options to each .env for specific mode.

### What does the proposed API look like?
For example, I have specific env settings for projectA. I also have specific env settings for both serve and build command.
When I run `vue-cli-service build --mode projectA`, .env loaded would be:
.env
.env.build
.env.projectA
.env.projectA.local

When I run `vue-cli-service serve --mode projectA`, .env loaded would be:
.env
.env.serve
.env.projectA
.env.projectA.local

**Comment by LinusBorg** [comment]
What do you mean when referring to "projectA"? Do you have multiple projects inside one Vue CLI project folder?

It would be helpful to understand the challenge you want to solve, can you please explain a bit more detailed?
