### ISSUE TITLE
This is bug?

### ISSUE THREAD

**Issue by TDcloud** [vuejs/vue-cli#4763]
### Version
4.0.5

### Reproduction link

- [https://raw.githubusercontent.com/TDcloud/es6/master/vue-cli4.png](url)

### Environment info
```
win7,64
```

### Steps to reproduce
 System:
   OS: Windows 7
   CPU: (4) x64 Intel(R) Core(TM) i5-2450M CPU
 Binaries:
   Node: 10.16.3 - D:\nodejs\node.EXE
   Yarn: Not Found
   npm: 6.12.0 - D:\nodejs\npm.CMD
 npmPackages:
   @vue/babel-helper-vue-jsx-merge-props:  1.0
   @vue/babel-plugin-transform-vue-jsx:  1.0.0
   @vue/babel-preset-app:  4.0.5
   @vue/babel-preset-jsx:  1.1.1
   @vue/babel-sugar-functional-vue:  1.0.0
   @vue/babel-sugar-inject-h:  1.0.0
   @vue/babel-sugar-v-model:  1.1.1
   @vue/babel-sugar-v-on:  1.1.0
   @vue/cli-overlay:  4.0.5
   @vue/cli-plugin-babel: ^4.0.0 => 4.0.5
   @vue/cli-plugin-router: ^4.0.0 => 4.0.5
   @vue/cli-plugin-vuex:  4.0.5
   @vue/cli-service: ^4.0.0 => 4.0.5
   @vue/cli-shared-utils:  4.0.5
   @vue/component-compiler-utils:  3.0.0
   @vue/preload-webpack-plugin:  1.1.1
   @vue/web-component-wrapper:  1.2.0
   vue: ^2.6.10 => 2.6.10
   vue-hot-reload-api:  2.3.4
   vue-loader:  15.7.1
   vue-router: ^3.1.3 => 3.1.3
   vue-style-loader:  4.1.2
   vue-template-compiler: ^2.6.10 => 2.6.10
   vue-template-es2015-compiler:  1.9.1
 npmGlobalPackages:
   @vue/cli: Not Found

### What is expected?
No real-time trace trigger required check box

### What is actually happening?
Click the check box once to trigger it, which is easy to be misunderstood as a bug.

**Comment by LinusBorg** [comment]
Hello @TDcloud 

thank you for your filing this issue.

Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on www.jsfiddle.net (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted. ([Why is this necessary?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff))


Thank you.

**Comment by sodatea** [comment]
Can't reproduce. Which terminal emulator did you use?

**Comment by TDcloud** [comment]
> 你好@TDcloud
> 
> （我无法打开指向图像的链接-403）
> 
> 感谢您提出此问题。
> 
> 请遵循有关如何报告问题的[准则](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md)。特别是，在[www.jsfiddle.net](http://www.jsfiddle.net)（或类似服务）上提供一个重现该问题的示例。如有必要，请创建一个存储库，以便我们以最少的复制量进行克隆。通常不会接受实际项目的资料库。（[这为什么有必要？](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)）
> 
> 谢谢。
The picture has been updated and can be opened normally now?
https://raw.githubusercontent.com/TDcloud/es6/master/vue-cli4.png

**Comment by TDcloud** [comment]
> Hello @TDcloud
> 
> (I can't open that link to the image - 403)
> 
> thank you for your filing this issue.
> 
> Please follow the [guidelines](https://github.com/vuejs/vue/blob/dev/.github/CONTRIBUTING.md) on how to report an issue. In particular, provide an example on [www.jsfiddle.net](http://www.jsfiddle.net) (or a similar service) that reproduces the problem. If necessary, create a repository for us to clone with a minimal reproduction. repositories of actual projects will generally not be accepted. ([Why is this necessary?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff))
> 
> Thank you.

https://raw.githubusercontent.com/TDcloud/es6/master/vue-cli4.png

**Comment by TDcloud** [comment]
> Can't reproduce. Which terminal emulator did you use?

https://raw.githubusercontent.com/TDcloud/es6/master/vue-cli4.png

**Comment by sodatea** [comment]
Not a bug in Vue CLI. See https://github.com/SBoudrias/Inquirer.js/issues/793

**Comment by TDcloud** [comment]
> Not a bug in **Vue CLI**. See [SBoudrias/Inquirer.js#793](https://github.com/SBoudrias/Inquirer.js/issues/793)

So if my check box changes, will my operations always be echoed synchronously in CMD?
