### ISSUE TITLE
No npm scripts are added after vue create command

### ISSUE THREAD

**Issue by Loskir** [vuejs/vue-cli#4772]
### Version
3.12.1

### Reproduction link
[https://github.com/loskir/hello-world](https://github.com/loskir/hello-world)

### Environment info
```
System: 
OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
CPU: (2) x64 AMD EPYC 7281 16-Core Processor
Binaries:
Node: 12.10.0 - /usr/bin/node
Yarn: Not Found
npm: 6.10.3 - /usr/bin/npm
Browsers:
Chrome: Not Found
Firefox: Not Found
npmGlobalPackages:
@vue/cli: 3.12.1
```

### Steps to reproduce
`vue create hello-world`

### What is expected?
scripts like "serve" and "build" in package.json

### What is actually happening?
no scripts in package.json

**Comment by sodatea** [comment]
Likely a network or permission issue.
Any error messages?

**Comment by Loskir** [comment]
Solved this already. The reason was the wrong directory rights.

Let you are going to create the project in directory `/my`
If this directory is owned by `root` group (or mb by any group that this user doesn't belong to), so
`ls -al /my` outputs something like
`drwxr-xr-x 4 user root 4096 date time .`
And you run `vue create hello-world`
The result is as described in the first message
But if you chown your directory like `chown user:user /my` the issue resolves.

Maybe that's npm issue.
