### ISSUE TITLE
use loader make hot replace slow

### ISSUE THREAD

**Issue by ermu592275254** [vuejs/vue-cli#4776]
### Version
3.12.0

### Reproduction link
[https://cli.vuejs.org/zh/config/#pluginoptions](https://cli.vuejs.org/zh/config/#pluginoptions)

### Environment info
```
windows10
```

### Steps to reproduce
// vue.config.js
pluginOptions: {
        'style-resources-loader': {
            preProcessor: 'scss',
            patterns: [
                path.resolve(__dirname, 'src/style/_variables.scss')
            ]
        }
    }

### What is expected?
hot replace no affected

### What is actually happening?
is work.but, make hot replace too slow.

**Comment by LinusBorg** [comment]
Well, then that's an issue for that loader, not Vue CLI
