### ISSUE TITLE
How to use "merge: false" in api.extendPackage

### ISSUE THREAD

**Issue by deraw** [vuejs/vue-cli#4779]
### Version
4.0.5

### Environment info
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 70.0
  npmGlobalPackages:
    @vue/cli: 4.0.3
```

### Steps to reproduce
Create a plugin and try to override a field in package.json in a generator.

### What is expected?
In [the documentation of `api.extendPackage()`,](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli/lib/GeneratorAPI.js#L180) it is stated that "Nested fields are deep-merged unless `{ merge: false }` is passed."

### What is actually happening?
I don't see any part that handles this case in the code, I don't known how to override a field :slightly_frowning_face:

**Comment by tobyzerner** [comment]
Building a preset and was just wondering this exact thing.

**Comment by sodatea** [comment]
That comment was outdated documentation referring to an option that was removed long before @vue/cli 3 stable release. It will be added back in the next version.
