### ISSUE TITLE
how does the HMR work?

### ISSUE THREAD

**Issue by rainke** [vuejs/vue-cli#478]
for the` webpack template`, I can't find `module.hot.accept` in `src` folder, I do wonder how the HMR works?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
