### ISSUE TITLE
 'is-gzip' is not in the npm registry.

### ISSUE THREAD

**Issue by zhangchier** [vuejs/vue-cli#480]
npm install -g vue-cli
     Registry returned 404 for GET on http://registry.npmjs.org/is-gzip
     'is-gzip' is not in the npm registry.

**Comment by LinusBorg** [comment]
It is:

![image](https://user-images.githubusercontent.com/1444526/26871144-7618df7c-4b72-11e7-8e9f-d707253bdf72.png)
