### ISSUE TITLE
Allow presets to create README.md

### ISSUE THREAD

**Issue by tobyzerner** [vuejs/vue-cli#4802]
### What problem does this feature solve?
When creating a project, the README.md file is generated after the preset/plugins have been invoked. So even if a preset or a plugin renders a README.md file in its generator, it gets overwritten by the one generated by `vue create`.

### What does the proposed API look like?
The simplest solution would probably be just to check if a README.md file already exists before generating a new one.

**Comment by nickbreen** [comment]
As a workaround, [onCreateComplete](https://cli.vuejs.org/dev-guide/generator-api.html#oncreatecomplete) fires after `README.md` is written to disk. E.g.

```javascript
api.onCreateComplete(() => fs.unlink('README.md))
```
