### ISSUE TITLE
Feature request - utilize CSS Purify in webpack templates

### ISSUE THREAD

**Issue by focussing** [vuejs/vue-cli#481]
This would be very helpful when using Bootstrap or Bulma. Significant reduction of final dist CSS file.
[https://github.com/purifycss/purifycss](https://github.com/purifycss/purifycss)

**Comment by LinusBorg** [comment]
This seems like a suggestion for a feature for one of the templates? I assume you mean the main webpoack template, found [here](https://github.com/vuejs-templates/webpack).

IF so, please close this issue and open a new one in the template's repository.

Thanks.

**Comment by focussing** [comment]
I mean all webpack templates.
(And maybe this would be benificial for browserify templates as well?)

**Comment by LinusBorg** [comment]
Then add issues in those repsective templates. This repository is concernred with the commmand line tool, not the templates themselves.
