### ISSUE TITLE
What are the main differences between vue-cli3 and vue-cli4?

### ISSUE THREAD

**Issue by chenguzhen87** [vuejs/vue-cli#4817]
IMPORTANT: Please use the following link to create a new issue:

https://new-issue.vuejs.org/?repo=vuejs/vue-cli

If your issue was not created using the app above, it will be closed immediately.

中文用户请注意：
请使用上面的链接来创建新的 issue。如果不是用上述工具创建的 issue 会被自动关闭。

**Comment by sodatea** [comment]
https://github.com/vuejs/vue-cli/releases/tag/v4.0.0
https://cli.vuejs.org/migrating-from-v3/#vue-cli-plugin-unit-jest

In short:
- bump versions of underlying tools;
- improved support for PWA and testing experience;
- new API for plugins;
- support for more package managers besides npm & yarn.
