### ISSUE TITLE
Eslint 6 support

### ISSUE THREAD

**Issue by DRoet** [vuejs/vue-cli#4824]
### What problem does this feature solve?
Ability to use eslint 6 instead of 5. I know this is already on its way, but just wondering if it is close now that the `eslint-plugin-vue` and `vue-eslint-parser` both got updated to support eslint 6.

Feel free to close this, but I couldn't find a tracking issue for this

**Comment by ThomasKientz** [comment]
@sodatea Any news about this?

**Comment by falcon03** [comment]
Are there any blockers for this issue? Eslint-plugin-vue seems to have been already updated to support eslint 6...

**Comment by sodatea** [comment]
I've just implemented this feature. Will release a new version in days.
