### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by logyoo** [vuejs/vue-cli#483]
run `vue init webpack projectName`

vue-cli · Failed to download repo vuejs-templates/webpack: unable to verify the first certificate

**Comment by posva** [comment]
This is because you're behind a VPN. This may help: https://github.com/typings/typings/issues/564

**Comment by artzub** [comment]
It's helped me
```
npm_config_strict_ssl=false vue init webpack my-project
```

**Comment by zuekegreen** [comment]
I have the same problem and tried your solution and still got an error

**Comment by crocodilered** [comment]
My way on Windows 10:

1. Run "Node.js command prompt".
2. Type `SET npm_config_strict_ssl=false` there.
3. Type `vue init vuetifyjs/webpack-simple my-project`

It's a kind of magic you know but it works for me. Good luck!

**Comment by yejingrong** [comment]
> My way on Windows 10:
> 
> 1. Run "Node.js command prompt".
> 2. Type `SET npm_config_strict_ssl=false` there.
> 3. Type `vue init vuetifyjs/webpack-simple my-project`
> 
> It's a kind of magic you know but it works for me. Good luck!

thanks, It works! but seems not so secure. I wonder how to add self-signed certificated in npm;

**Comment by ssying** [comment]
> It helped me
> 
> ```
> npm_config_strict_ssl=false vue init webpack my-project
> ```

could it be more detail please? i just copy and enter it at my cmd but it failed.

**Comment by zulrang** [comment]
None of these solutions work for me.  I'm going through a proxy, which works fine with npm, but will not work with vue-cli.  What is vue doing differently than npm?
