### ISSUE TITLE
entry pattern "'./src/components/*.vue'" did not match any files.

### ISSUE THREAD

**Issue by kelclen13** [vuejs/vue-cli#4834]
### Version
4.0.5

### Reproduction link
[https://github.com/vuejs/vue-cli/issues/4833](https://github.com/vuejs/vue-cli/issues/4833)

### Environment info
```
Building Web components  VUEJS 
```

### Steps to reproduce
RUN 
npm run build:target will create wc vue to js 

### What is expected?
 "build:target": "vue-cli-service build --target wc --name my-compo './src/components/*.vue'  "

### What is actually happening?
 "build:target": "vue-cli-service build --target wc --name my-compo ./src/components/*.vue "

---
Why i follow instructions in documents Build Target in vue js , try to use npm run build:target , that not work like docs said , but when i try to remove ' ' and it run fine  , can some one explain tks 
Sorry for my bad english.

**Comment by LinusBorg** [comment]
This still needs a reproduction from @kelclen13

**Comment by m-mohr** [comment]
I'm facing the same issue on Windows 10.

**Comment by LinusBorg** [comment]
> This still needs a reproduction

**Comment by m-mohr** [comment]
You can reproduce it using the official Vue Readme on Multiple Web Components: https://cli.vuejs.org/guide/build-targets.html#bundle-that-registers-multiple-web-components
Follow the description on Windows in PowerShell and it fails. As @kelclen13 said, removing the `'` helps, so I'm happy with it for now and won't investigate any further. It may actually just need a fix in the docs...
