### ISSUE TITLE
Vue-CLI文档访问太慢了，能不能部署在国内的服务器。

### ISSUE THREAD

**Issue by sl1673495** [vuejs/vue-cli#4838]
### What problem does this feature solve?
访问速度太慢。

### What does the proposed API look like?
访问速度太慢。

**Comment by sodatea** [comment]
Duplicate of #3998

**Comment by sodatea** [comment]
部署到国内服务器到问题参见这里：
https://github.com/vuejs/cn.vuejs.org/issues/89#issuecomment-310995133

目前大部分 vuejs.org 的子域名都部署在 Netlify 上，cn.vuejs.org 是部署在 GitHub Pages 的，
似乎现在国内访问 GitHub Pages 会比 Netlify 好一点，这个迁移我们会考虑一下的。

**Comment by sl1673495** [comment]
好的 谢谢 Vue现在是国内最受欢迎的框架 搭建一个工程少不了Vue-CLI的配置定制 期待访问速度的提升！
