### ISSUE TITLE
vue init webpack hangs

### ISSUE THREAD

**Issue by Pasch1000** [vuejs/vue-cli#484]
When I execute command vue init webpack my-project it hangs on project name question. I cannot enter anything, ENTER does not work as well. I try to execute it on Win 10 in command line as well as in git bash, the same effect in both.

**Comment by ilearnio** [comment]
Just wanted to write about this too. I have the same issue:

```
$ vue init webpack vue

? Project name vue
? Project description (A Vue.js project)
```

At this step it hangs and it doesn't even allows to exit with Ctrl+C/Ctrl+D

**Comment by TimsManter** [comment]
Same issue with my custom template I made from scratch. Hangs every time on second question. Have to force close the terminal to exit. I bet it worked a few days ago as I remember. It may be related with recent `npm` update.

**Comment by ilearnio** [comment]
I tried to downgrade it up to v2.0.0 and there is the same issue. Very strange. Maybe that is because I'm installing it with yarn... npm just throws an error when trying to install vue-cli, but it is probably has something to do with my setups

**Comment by ilearnio** [comment]
Downgrading Node from 8.1.0 to 8.0.0 solves the issue

**Comment by johnwebbcole** [comment]
Same issue with Win10 and Node 8.1.0 and NPM 5.0.3.

**Comment by Pasch1000** [comment]
Thanks ilearnio. Downgradinig node to 8 / 6 fixes the problem.

**Comment by prashant332** [comment]
downgrading to 8.0.0 works

**Comment by posva** [comment]
dup of #482 
It looks like a patch was released with node 8.1.1 but I'm haven't tried myself

**Comment by Sobient** [comment]
Tested with NodeJS 9.0 and 8.1.1 nightly. Yields "You must upgrade node to >=>=4.0.0.x to use vue-cli".
lol.

**Comment by dougajmcdonald** [comment]
I have this same problem but also with NPM init as referenced here: https://github.com/nodejs/node/issues/13557

**Comment by AshrafBasry** [comment]
same problem here
? Project name (name)
? Project description (A Vue.js project) _
Ubuntu 17.04
Node v8.1.0
npm 5.0.3
vue 2.8.2

**Comment by ssfdust** [comment]
Same here
Archlinux
Node v8.1.0
npm 5.0.3
vue 2.8.2

**Comment by learnmove** [comment]
me too cant work in node 8.1.0

**Comment by posva** [comment]
You only need to upgrade node
