### ISSUE TITLE
vue create error if without yarn

### ISSUE THREAD

**Issue by nepaul** [vuejs/vue-cli#4845]

**Comment by sodatea** [comment]
1. Make sure you are on the latest version of `@vue/cli`

2. Try
```
vue config --set packageManager npm
``` 

You might have chosen yarn as the default package manager before and then uninstalled yarn.

**Comment by nepaul** [comment]
> 1. Make sure you are on the latest version of `@vue/cli`
> 2. Try
> 
> ```
> vue config --set packageManager npm
> ```
> 
> You might have chosen yarn as the default package manager before and then uninstalled yarn.

Actually, It should have to set npm as default. Not yarn...

**Comment by marcinwasilewski** [comment]
> 1. Make sure you are on the latest version of `@vue/cli`
> 2. Try
> 
> ```
> vue config --set packageManager npm
> ```
> 
> You might have chosen yarn as the default package manager before and then uninstalled yarn.

Any tips on how I could do that with npx?

**Comment by sodatea** [comment]
You can edit the `~/.vuerc` file manually.
