### ISSUE TITLE
如何从 vue-cli4.0 降级到3.0+

### ISSUE THREAD

**Issue by zbldsg** [vuejs/vue-cli#4846]
现在使用 vue-cli4.0 在IE浏览器上存在兼容性，希望恢复到3.0+ 的版本，但是目前找不到卸载或恢复到3.0版本的方法

**Comment by ddzy** [comment]
> 现在使用 vue-cli4.0 在IE浏览器上存在兼容性，希望恢复到3.0+ 的版本，但是目前找不到卸载或恢复到3.0版本的方法

同样的问题... IE9、IE10 显示空白
