### ISSUE TITLE
Add experimental preset "@babel/preset-modules" for modern build

### ISSUE THREAD

**Issue by academici** [vuejs/vue-cli#4848]
### What problem does this feature solve?
The result is improved bundle size and performance, while supporting the same browsers.

[Babel preset link](https://github.com/babel/preset-modules)
### What does the proposed API look like?
```json
{
    "presets": [
        ["@vue/babel-preset-app", {
           "presetModules": true
        }]
    ]
}
```

**Comment by Djaler** [comment]
Hey, so what about it?
