### ISSUE TITLE
ESLint --output-file option not supported in @vue/cli-plugin-eslint

### ISSUE THREAD

**Issue by ataylorme** [vuejs/vue-cli#4849]
### Version
4.0.5

### Reproduction link
[https://github.com/ataylorme/vue-cli-lint-output-file-issue](https://github.com/ataylorme/vue-cli-lint-output-file-issue)

### Environment info
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: Not Found
    Safari: 13.0.3
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.0.5
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.0.5
    @vue/cli-plugin-babel: ^4.0.0 => 4.0.5
    @vue/cli-plugin-eslint: ^4.0.0 => 4.0.5
    @vue/cli-plugin-router:  4.0.5
    @vue/cli-plugin-vuex:  4.0.5
    @vue/cli-service: ^4.0.0 => 4.0.5
    @vue/cli-shared-utils:  4.0.5
    @vue/component-compiler-utils:  3.0.2
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3
    vue: ^2.6.10 => 2.6.10
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: 4.0.5
```

### Steps to reproduce
Clone the [`ataylorme/vue-cli-lint-output-file-issue`](https://github.com/ataylorme/vue-cli-lint-output-file-issue) repository
Run `npm install` to download dependencies
Run `npm run lint`, which is an [npm script](https://docs.npmjs.com/misc/scripts) alias for `vue-cli-service lint --format json --output-file lint_results.json`

### What is expected?
The results of `vue-cli-service lint` are saved to the file `lint_results.json` in JSON format

### What is actually happening?
The results of `vue-cli-service lint` are displayed as terminal output and the `lint_results.json` is not created

---
[The Vue CLI ESLint plugin documentation](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-eslint#injected-commands) says "Other ESLint CLI options are also supported."

`--output-file` is a valid [ESLint CLI option](https://eslint.org/docs/user-guide/command-line-interface#options).

My end goal is to save the Vue lint results in JSON format to a file, which can then be analyzed.

**Comment by LinusBorg** [comment]
We shouldake clear in the docs that CLI-only options are not supported since we don't run the eslint CLI, we import and run the `CLIEngine` in our node process which doesn't support CLI-only flags.

**Comment by ataylorme** [comment]
@LinusBorg I opened #4850 which adds the `output-file` option. It also changes the documentation to say:

> Other [ESLint CLI options](https://eslint.org/docs/user-guide/command-line-interface#options) are not supported.

so that it is clear options not listed in the `README` aren't supported

**Comment by mttmccb** [comment]
Also ran into this problem and have a bit of a hacky method of piping the output to a file, however when it's successful then the format is invalid (in my case XML)

**Comment by ataylorme** [comment]
@mttmccb can you test my work in #4850? It should work with XML if you specify `--format`
