### ISSUE TITLE
Certificate issue when running vue init

### ISSUE THREAD

**Issue by TisteDup** [vuejs/vue-cli#485]
Hi,

My environment:
- Centos7 on VirtualBox (true OS : Windows 7)
- Node version: 6.11.0
- Npm version : 3.10.10
- **I'm behind a corporate proxy**

I installed vue-cli, like this:
`sudo npm install -g vue-cli`

But now, when I try to init a new project with "vue init", like this:
`vue init webpack-simple myproject`

I get an error:
`vue-cli · Failed to download repo vuejs-templates/webpack-simple: unable to get local issuer certificate`

Does anyone know how to fix it please?

**Comment by TisteDup** [comment]
I fixed it by uninstall then reinstall nodejs on my centos.

**Comment by Nordes** [comment]
I have the same issue, on windows. I will try to re-install, but maybe it's because I am also behind a corporate proxy. (Node version 8.5.0 / npm 5.3.0)

**Comment by douggass** [comment]
+1
