### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by marnjo** [vuejs/vue-cli#4853]
### Version
4.0.5

### Environment info
```
  System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
  Binaries:
    Node: 13.1.0 - ~/.nvm/versions/node/v13.1.0/bin/node
    Yarn: 1.19.1 - /usr/bin/yarn
    npm: 6.12.1 - ~/.nvm/versions/node/v13.1.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 70.0.1
  npmPackages:
    vue:  2.6.10 
  npmGlobalPackages:
    @vue/cli: 4.0.5

```

### What is expected?
The vue ui or the create command should create a project

### What is actually happening?
an error message
Cannot read property 'indexOf' of undefined

---
My issue is not really occuring in a project. The vue UI or the vue create command does not create a project all i get is     "Cannot read property 'indexOf' of undefined"   that error message.
I have tried installing and reinstalling, updating npm, nvm and node clearing npm cache but still it won't work

**Comment by sodatea** [comment]
I'm sorry but I can't reproduce it locally.
Do you have a more detailed error log? What options did you choose when creating a project?

**Comment by jasonbunnell** [comment]
I got this same issue.  I am also running Ubuntu 18.04 and Firefox 72.  Tried to create new project using Vue UI using options:
- Preset = manual
- Babel = true
- Router = true
- VueX = true
- Linter/Formatter = true
- Lint on save = ESLint + Prettier

**Comment by jasonbunnell** [comment]
I think I may have the solution.  I think this is not a Vue issue, but rather a Linux permissions issue.  I tried creating a Vue project from the command line and got an issue with the suggestion to permanently fix by running:
`sudo chown -R 1001:1001 "/home/jason/.npm`
I tried creating a new Vue project from the command line a second time with no issue.  Hope this helps.

**Comment by Jackyjk** [comment]
my solution:File path can only consist of English, no special characters or other languages
