### ISSUE TITLE
自动创建有错误

### ISSUE THREAD

**Issue by Scandinavian0** [vuejs/vue-cli#4862]
### Version
4.0.5

### Environment info
```
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 13.1.0 - D:\node\node.EXE
    Yarn: Not Found
    npm: 6.12.1 - D:\node\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vue/cli-overlay:  4.0.5
    @vue/cli-plugin-router: ^4.0.0 => 4.0.5
    @vue/cli-plugin-unit-mocha: ^4.0.0 => 4.0.5
    @vue/cli-plugin-vuex: ^4.0.0 => 4.0.5
    @vue/cli-service: ^4.0.0 => 4.0.5
    @vue/cli-shared-utils:  4.0.5
    @vue/component-compiler-utils:  3.0.2
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    vue: 2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.2
    vue-router: ^3.1.3 => 3.1.3
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.2
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
vue create <name>

### What is expected?
能创建项目并运行

### What is actually happening?
Module build failed (from ./node_modules/postcss-loader/src/index.js):
BrowserslistError: E:\JAVA_WebStorm\vueproject\newagain contains both .browserslistrc and browserslist

---
Module build failed (from ./node_modules/postcss-loader/src/index.js):
BrowserslistError: E:\JAVA_WebStorm\vueproject\newagain contains both .browserslistrc and browserslist，就简单的创建项目并运行

**Comment by sodatea** [comment]
你是新建了一个全新项目？还是和已有目录合并？创建的时候都选了些什么选项？

我们需要可以复现这个错误的项目代码才能够排查问题，还烦请提供一下。
