### ISSUE TITLE
command: [ vue create appName ] keeps failing at downloading geckodirver

### ISSUE THREAD

**Issue by Lysander686** [vuejs/vue-cli#4867]
### Version
4.0.5

### Reproduction link
[https://privnote.com/AKHt7S9N#a92hdXusf](https://privnote.com/AKHt7S9N#a92hdXusf)

### Environment info
```
windows 10, surface pro 4 
location: China mainland.
```

### Steps to reproduce
input command in cmd:
vue create appName

And then it stuck at downloading geckodriver.

### What is expected?
successfully create appName.

### What is actually happening?
stuck at downloading geckodriver

**Comment by sodatea** [comment]
It's because China blocks the CDN. In v4.1.0, Vue CLI will automatically switch to a mirror CDN if you've set `useTaobaoRegistry`.
