### ISSUE TITLE
wizard hang on project description [windows 10]

### ISSUE THREAD

**Issue by nueko** [vuejs/vue-cli#488]
nothing error shown but just hang

**Comment by pikpok** [comment]
Same happens on Linux (Arch Linux, Gnome, tested in `gnome-terminal`, `alacritty`, `xterm`; both `bash` and `zsh`). Node v8.1.0, npm v4.6.1, vue-cli v2.8.2 (just installed globally from npm). Strange that Ctrl+C/Ctrl+Z doesn't work, I can only close terminal window. Can reproduce when running `vue init` with any template.

**Comment by LinusBorg** [comment]
What node version are you on? There's a regression with node 8.1 that's going to be fixed in node 8.1.1

**Comment by posva** [comment]
It's probably the node 8.1.0 bug fixed in 8.1.1. Please, next time you need to give more information about your env like @pikpok did
Tell me if the error persists with 8.1.1 and more info so I can reopen
