### ISSUE TITLE
Nyelvi gondok

### ISSUE THREAD

**Issue by bertaandor** [vuejs/vue-cli#4888]
### What problem does this feature solve?
Kifejezetten utálom, hogy a nyelv automatikusan detektálva van amikor a grafikus projekt kezelőt használom. Soha semmilyen kifejezést nem tanultam sem használtam magyarul, ezért engem nagyon zavar. Ezt is csak azért írom magyarul, hogy nektek se legyen olyan egyszerű kibogózni, hogy mi is a probléma :P 

### What does the proposed API look like?
Az első használatkor jó lenne ha rákérdezne, hogy a detektált nyelvet, vagy az angolt preferálom.
Elöre is köszönöm.

**Comment by sodatea** [comment]
Duplicate of https://github.com/vuejs/vue-cli/issues/2688 and https://github.com/vuejs/vue-cli/issues/2151
