### ISSUE TITLE
Project dependencies route spawns dozens of slow cmd.exe processes

### ISSUE THREAD

**Issue by richardtallent** [vuejs/vue-cli#4895]
### Version
4.0.5

### Environment info
```
 System:
   OS: Windows 7
   CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
 Binaries:
   Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
   Yarn: Not Found
   npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
 npmGlobalPackages:
   @vue/cli: Not Found
```

### Steps to reproduce
Open any project in Vue UI. Go to the dependencies tab. Look at Windows Task Manager and note how many cmd.exe processes are spawned and how slowly they resolve with version information.

### What is expected?
If shelling out is needed to get versions, batching the requests somehow might improve performance significantly

### What is actually happening?
It appears a new cmd process is created for each dependency and plugin

---
I don't recall this being slow in v3, but now it's slow enough that I try to avoid that tab and just use npm outdated from the command line.

**Comment by LinusBorg** [comment]
I'd apprechiate you editing your issue removing the unnecessary snark. :)

**Comment by richardtallent** [comment]
Updated! Apologies, the mild humor was with the intention of keeping it light rather than just filing another boring complaint. :)

The same spawning of lots of node processes to check dependency versions happens on my Mac too, but it's done in a second or two, not 2-5 minutes. The Mac is newer and faster than my day-job-corporate-Dell, but not orders of magnitude faster. They're on the same network (I work remotely), so it doesn't appear to be a network issue.

**Comment by sodatea** [comment]
Got it. It's because in v4 package metadata are achieved calling the `npm info` command.

https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli/lib/util/ProjectPackageManager.js#L177-L198

Could be fixed by replacing it with a normal HTTP request.
