### ISSUE TITLE
reloading not working

### ISSUE THREAD

**Issue by TarikAmine** [vuejs/vue-cli#49]
Hello, i tried tree of the default templates (webpack, webpack-simple, browserify-simple) and non of had hot reloading working, the last one (browserify) didnt even render the  index.html and was stuck with ```Cannot GET /```, trying to get it to work the entire day with no avail.

**Comment by yyx990803** [comment]
Are you on windows?

**Comment by TarikAmine** [comment]
Sorry forgot about that, yes i'm
windows 8.1
npm 3.5.3
node 4.2.3

**Comment by yyx990803** [comment]
The browserify template is currently broken on template because the build script is using a unix-only `&` operator. However I just tested on Windows 8.1 with Node 5.3.0 and the webpack based ones are working fine. What browser are you using?

**Comment by TarikAmine** [comment]
I tested it with Chrome and Firefox,  both browser have socket open with a pending status, I think its that webpack doesn't pick up changes on files, tried looking for similar issues in its repo, but vue-cli configuration derive from standard one.

**Comment by yyx990803** [comment]
Also check your `npm install` log to see if there are any native module build related issues, e.g. `fs-events`.

**Comment by TarikAmine** [comment]
Yeah, i have some warnings about fs-events, which i tried to install before but always fallen into 'npm WARN install Couldn't install optional dependency: Unsupported'. Which version of npm do you have? since it was stated that it is optional i didnt give it any thougths. 

with npm 3.6.3
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm 3.3.12
npm WARN install Couldn't install optional dependency: Unsupported

**Comment by yyx990803** [comment]
Hmm that is interesting. Did you try upgrading your Node to 5.x? 5.3.0 worked fine for me on Windows 8.1.

**Comment by samgreenwood** [comment]
Getting this issue with NPM 3.7.3 and Node 5.8 on Fedora 23 also.

**Comment by zigomir** [comment]
@samgreenwood and @TarikAmine still issues with official templates? I suggest you open more specific issues on a template that doesn't work: https://github.com/vuejs-templates

**Comment by chrisvfritz** [comment]
I'm closing this, because some the specific issues discussed here have been solved by now. If people continue experiencing problems with reloading, definitely do as @zigomir suggested and open up an issue with the specific template you're using. :smiley:
