### ISSUE TITLE
vue init can not work

### ISSUE THREAD

**Issue by fayewong25** [vuejs/vue-cli#491]
{
$ vue init webpack-simple gggg

? Project name (gggg)
? Project name gggg
? Project description (A Vue.js project)
}
Stop here，someone knows what's happening?

**Comment by wrtlbrmpft** [comment]
Same behavior here.
I was unable to enter the project description. Ignores any keyboard inputs..

**Comment by cardiojim** [comment]
I've met the same problem with you!

**Comment by cardiojim** [comment]
See #482

**Comment by egoist** [comment]
Try searching existing issues.
