### ISSUE TITLE
Can vue-cli detect the syntax error when import an empty string?

### ISSUE THREAD

**Issue by givingwu** [vuejs/vue-cli#4914]
### What problem does this feature solve?
when user import an empty string like `import ''` in SFC, the webpack build will stuck at `98% after emitting CopyPlugin`.

  [issue#4174](https://github.com/vuejs/vue-cli/issues/4174)
  [issue#4252](https://github.com/vuejs/vue-cli/issues/4252)

### What does the proposed API look like?
Hope the `vue-template-compiler` could check the `path` string  is an available string for `require(path)`, and if not use the error-overlay to indicates what and where error happened.

Thanks.

**Comment by sodatea** [comment]
> the webpack build will stuck

This is due to the same bug as https://github.com/vuejs/vue-cli/issues/4891

---

After that bug to be fixed, we'll need to correctly detect the error and show the right error message in https://github.com/geowarin/friendly-errors-webpack-plugin/

Contributions are welcome.

**Comment by vuchan** [comment]
> Nevertheless, there's a bug in Vue CLI that we forgot to process the webpack failed hook in the serve command.

ok, i knew that, thanks.

**Comment by jdz321** [comment]
> > the webpack build will stuck
> 
> This is due to the same bug as #4891
> 
> After that bug to be fixed, we'll need to correctly detect the error and show the right error message in https://github.com/geowarin/friendly-errors-webpack-plugin/
> 
> Contributions are welcome.

#4891 已经修掉了  这个问题有进展吗
