### ISSUE TITLE
node.js 8.* vue init webpack test.

### ISSUE THREAD

**Issue by darksc** [vuejs/vue-cli#493]
![](https://ws1.sinaimg.cn/mw690/6a39992dly1fgloz36ab3j20s20ounbx.jpg)

To perform to this step, there is no any response

**Comment by Binaryify** [comment]
+1

**Comment by clementdelebecque** [comment]
updating to node 8.1.1 worked for me

**Comment by Binaryify** [comment]
@clementdelebecque 
It worked for me too, thx ~

**Comment by darksc** [comment]
@clementdelebecque is true
