### ISSUE TITLE
vue init webpack 卡在Project Description步骤

### ISSUE THREAD

**Issue by qiutuleng** [vuejs/vue-cli#494]
问题：用vue init webpack创建新项目的时候会卡在第二部 Project Description ，光标一直闪，没法输入也没法ctrl+c结束程序。

环境：
    Ubuntu 16.04
    Node.js v8.1.0

在降级为V7.10.0之后正常运行。

**Comment by Binaryify** [comment]
+1

**Comment by Binaryify** [comment]
升级到8.1.1可解决问题

**Comment by egoist** [comment]
Duplicate of https://github.com/vuejs/vue-cli/issues/482
