### ISSUE TITLE
creator不创建readme选项

### ISSUE THREAD

**Issue by zero7u** [vuejs/vue-cli#4942]
### Version
4.1.1

### What is expected?
vue create -p remote-preset my-project --no-readme

---
希望添加```--no-readme```选项，因为从远程组件、项目preset创建项目，通常需要有自己的使用说明，不希望被默认的readme强制替换掉，谢谢！
或者在```generateReadme```时，先判断是否已经存在readme，存在则不创建。

---
还有一种情况请一起考虑，如果是组件的preset，是不需要```src/```的，建议拉取远程github的preset项目时，将控制权交给用户，而不要强制把src和readme安利过来。

**Comment by whq731** [comment]
vue-cli3也有相同问题
