### ISSUE TITLE
发现一个bug，在nodeJS8+中,（find a bug in ‘nodeJS 8+’）

### ISSUE THREAD

**Issue by ranchoopenwrt** [vuejs/vue-cli#495]
如果使用node8+，会到导致vue init webpack myProjec 时候 从输入项目描述开始就无法，在控制台中输入东西了。

when use node.JS8+ and input "vue init webpack myProjec"，you can`t input anything to windows`cmd.exex.
环境：nodeJS 8+版本
系统：win10

**Comment by egoist** [comment]
Duplicated of https://github.com/vuejs/vue-cli/issues/482
