### ISSUE TITLE
`npm install -g vue-cli` throw an error

### ISSUE THREAD

**Issue by HADB** [vuejs/vue-cli#496]
npm install -g vue-cli
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hadb/.npm/_logs/2017-06-16T02_27_54_896Z-debug.log

log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'vue-cli' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose npm-session 4a495c3f3731d46a
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/vue-cli 372ms (from cache)
8 silly pacote tag manifest for vue-cli@latest fetched in 420ms
9 verbose stack RangeError: Maximum call stack size exceeded
9 verbose stack     at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
9 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/node.js:36:14
9 verbose stack     at Array.forEach (native)
9 verbose stack     at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
9 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/node.js:36:14
9 verbose stack     at Array.forEach (native)
9 verbose stack     at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:377:5)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
10 verbose cwd /Users/hadb
11 verbose Darwin 16.6.0
12 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "vue-cli"
13 verbose node v8.1.2
14 verbose npm  v5.0.3
15 error Maximum call stack size exceeded
16 verbose exit [ 1, true ]

**Comment by anuxs** [comment]
+1

on my macOS High Sierra and  node v8.1.2 and npm 5.0.3 , this error:
npm install -g vue-cli
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/langge/.npm/_logs/2017-06-17T00_07_44_979Z-debug.log


0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.2/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'vue-cli' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose npm-session 0e2a958d086d9f1f
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/vue-cli 496ms (from cache)
8 silly pacote tag manifest for vue-cli@latest fetched in 531ms
9 verbose stack RangeError: Maximum call stack size exceeded
9 verbose stack     at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
9 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/node.js:36:14
9 verbose stack     at Array.forEach (native)
9 verbose stack     at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
9 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/node.js:36:14
9 verbose stack     at Array.forEach (native)
9 verbose stack     at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:377:5)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
10 verbose cwd /Users/langge/dev/test/h5js/webtest/vue-Meizi
11 verbose Darwin 17.0.0
12 verbose argv "/usr/local/Cellar/node/8.1.2/bin/node" "/usr/local/bin/npm" "install" "-g" "vue-cli"
13 verbose node v8.1.2
14 verbose npm  v5.0.3
15 error Maximum call stack size exceeded
16 verbose exit [ 1, true ]

**Comment by daliborgogic** [comment]
+1

```bash
dlbr@lnx:~/dev$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
NAME="Ubuntu"
VERSION="17.04 (Zesty Zapus)"
...

dlbr@lnx:~/dev$ npm install -g vue-cli
/home/dlbr/.npm-global/bin/vue -> /home/dlbr/.npm-global/lib/node_modules/vue-cli/bin/vue
/home/dlbr/.npm-global/bin/vue-init -> /home/dlbr/.npm-global/lib/node_modules/vue-cli/bin/vue-init
/home/dlbr/.npm-global/bin/vue-list -> /home/dlbr/.npm-global/lib/node_modules/vue-cli/bin/vue-list
/home/dlbr/.npm-global/bin/vue-build -> /home/dlbr/.npm-global/lib/node_modules/vue-cli/bin/vue-build
+ vue-cli@2.8.2
updated 1 package in 31.034s
dlbr@lnx:~/dev$ vue init pwa foo
No command 'vue' found, did you mean:
 Command 'vpe' from package 'texlive-latex-extra' (universe)
vue: command not found

```

**Comment by daliborgogic** [comment]
Workaround:
```bash
dlbr@lnx:~/dev$ node ~/.npm-global/bin/vue-init pwa foo
? Project name (foo)
...
```

**Comment by xp6530** [comment]
+1

**Comment by posva** [comment]
Cannot reproduce with same versions

**Comment by openks** [comment]
+1 
```
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zyx/.npm/_logs/2017-07-18T12_31_53_059Z-debug.log
```
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.2/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'vue-cli' ]
2 info using npm@5.0.4
3 info using node@v8.1.2
4 verbose npm-session 8cc4c68874eadce1
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/vue-cli 25ms (from cache)
8 silly pacote tag manifest for vue-cli@latest fetched in 53ms
9 verbose stack RangeError: Maximum call stack size exceeded
9 verbose stack     at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:31:40)
9 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/node.js:36:14
9 verbose stack     at Array.forEach (native)
9 verbose stack     at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
9 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/node.js:36:14
9 verbose stack     at Array.forEach (native)
9 verbose stack     at exports.create (/usr/local/lib/node_modules/npm/lib/install/node.js:33:25)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:377:5)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
9 verbose stack     at Array.forEach (native)
9 verbose stack     at normalizeTree (/usr/local/lib/node_modules/npm/lib/install.js:379:19)
10 verbose cwd /Users/zyx
11 verbose Darwin 16.6.0
12 verbose argv "/usr/local/Cellar/node/8.1.2/bin/node" "/usr/local/bin/npm" "i" "-g" "vue-cli"
13 verbose node v8.1.2
14 verbose npm  v5.0.4
15 error Maximum call stack size exceeded
16 verbose exit [ 1, true ]
```

**Comment by openks** [comment]
After I update node to V8.1.4 it works. maybe it is a bug in v8.1.2
