### ISSUE TITLE
Parcel Bundler

### ISSUE THREAD

**Issue by 0x77dev** [vuejs/vue-cli#4965]
### What problem does this feature solve?
Faster then webpack.
make a template with parcel support.

### What does the proposed API look like?
# [Parcel](https://parceljs.org/)

**Comment by sodatea** [comment]
Parcel doesn't have the extensibility like webpack so it's currently impossible to cover all the use cases of Vue CLI with Parcel. It's a tradeoff.

And if you'd like to use Parcel for Vue, you don't need a template - it's zero-configuration anyway.
