### ISSUE TITLE
vue build doesn't use config host or --host HOST

### ISSUE THREAD

**Issue by ralphchristianeclipse** [vuejs/vue-cli#497]
I'm using this config file

```javascript
module.exports = {
    port: 8080,
    host: "0.0.0.0",
    title: "Test",
    html: {
        title: "Test",
        template: './index.html',
    },
    filename: {
        js: "js/[name].js",
        css: "css/[name].css",
        static: "assets/[name].[chunkhash].[ext]",
    },
};
```

But it seems it doesnt change the host location to my desired host

it's still localhost

removing the third parameter "localhost" at vue-build inside vue-cli bin

```javascript
  .option('--host [host]', 'Server host','localhost')

//to this

  .option('--host [host]', 'Server host')
```
removing the local host fixes it.

Any idea why the default value is still used?

**Comment by egoist** [comment]
Hmm because cli options take higher priority over config file, now fixed in master branch.
