### ISSUE TITLE
执行过程中报错

### ISSUE THREAD

**Issue by Zhang-Yida** [vuejs/vue-cli#4978]
### Version
4.1.1

### Environment info
```
  System:
    OS: Windows 10 10.0.16299
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 12.14.0 - C:\Software\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Software\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.1419.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
vue create project

### What is expected?
Right install dependence

### What is actually happening?
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path C:\ProjectCode\pwc-frontend-framework\node_modules\array.prototype.flat
npm ERR! dest C:\ProjectCode\pwc-frontend-framework\node_modules\.array.prototype.flat.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\ProjectCode\pwc-frontend-framework\node_modules\array.prototype.flat' -> 'C:\ProjectCode\pwc-frontend-framework\node_modules\.array.prototype.flat.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by sodatea** [comment]
`vue create` 的时候选了哪些选项？完整的错误日志是怎么样的？

**Comment by Zhang-Yida** [comment]
默认选项，并没特殊制定参数，array.prototype.flat是eslint的依赖，怀疑是eslint的版本问题，开发工具vscode

**Comment by Zhang-Yida** [comment]
![image](https://user-images.githubusercontent.com/17022452/71222768-c92d7280-230c-11ea-8966-46e1ebaf5170.png)

**Comment by sodatea** [comment]
你这个项目还加了很多自己的依赖吧……这样不提供实际复现代码，没办法排查的。

**Comment by Zhang-Yida** [comment]
并没有加脚手架外的依赖，只是执行了 vue create projectname。。。

**Comment by sodatea** [comment]
可你的依赖里怎么会有react-favicon

**Comment by Zhang-Yida** [comment]
最终报错的包是 array.prototype.flat 而依赖这个包的 eslint-plugin-import 正是脚手架中的 eslint 所依赖的，请您确认

**Comment by sodatea** [comment]
> 最终报错的包是 array.prototype.flat 而依赖这个包的 eslint-plugin-import 正是脚手架中的 eslint 所依赖的

这并不能提供什么有效信息。
单从日志里就能看出你这个项目环境很复杂，绝对不是默认选项生成的。
难以排查的 bug 一般都来自于项目错综复杂的依赖关系和环境，要是默认配置就能出错的话也不会到现在就只有这一个 issue 提出来，所以我们的 Issue Helper 里写了，**复现是必须的**。

刚刚猜想到一个另外的可能原因：NODE_ENV 设置了 production 或者 `~/.npmrc` 里改了什么设置导致 devDependencies 安装出问题。

在不提供代码的情况下我们只能帮到这里了。
