### ISSUE TITLE
在自定义 node 脚本中调用类似 vue-cli-service build 来打包 vue 项目

### ISSUE THREAD

**Issue by zoux** [vuejs/vue-cli#4980]
### What problem does this feature solve?
在一个 node 脚本流程中，实现打包多个 vue 项目，并完成其他 node fs 的操作。

目前是利用循环调用 node child_process.execSync(`vue-cli-service build ${packageName}`) 来打包 vue 项目。
但下游工具似乎存在不支持 child_process.execSync 的构建方式。

因此想了解下目前是否存在类似的功能调用；抑或没有的话，是否考虑加上该功能？

### What does the proposed API look like?
满足上述场景即可，感谢～

**Comment by sodatea** [comment]
> 但下游工具似乎存在不支持 child_process.execSync 的构建方式。

这个具体指的是……？

**Comment by zoux** [comment]
> > 但下游工具似乎存在不支持 child_process.execSync 的构建方式。
> 
> 这个具体指的是……？

这个下游工具指的是公司内部自研的打包提测工具～ 😅

在该工具中使用 child_process.execSync(vue-cli-service build ${packageName}) 无效，从现象上来看似乎直接结束了构建流程。

所以才想请教下有没有方法可以在 node 中使用非 child_process.execSync 的方式完成 vue 项目的打包～

**Comment by sodatea** [comment]
这个现象我比较怀疑是 cwd 的问题。
建议：换用 `execa`、再次确认 `cwd` 传对了。

因为 CLI 内部打包 modern mode 时也用了 `execa` 调用子进程，以及其他一些检测环境的地方也用了子进程。
所以如果是环境存在问题的话可能不止这一个调用会出问题，解决了目前这个问题可能还会碰到其他坑。

---

目前没有这样的公开 API。不过要 hack 的话也简单，参考 https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/bin/vue-cli-service.js，引入 `@vue/cli-service/lib/Service`，`new` 一个 `service` 实例，`service.run('build', args, rawArgv)` 就好了。
