### ISSUE TITLE
Template properties are not working in my vue-cli application

### ISSUE THREAD

**Issue by kumaresan-subramani** [vuejs/vue-cli#4983]
### Version
3.12.0

### Reproduction link
[https://github.com/kumaresan-subramani/ej2-vue-samples/blob/master/src/auto-complete/template.vue](https://github.com/kumaresan-subramani/ej2-vue-samples/blob/master/src/auto-complete/template.vue)

### Environment info
```
     "vue": "^2.5.2",
    "vue-class-component": "4.3.1",
    "vue-property-decorator": "^6.0.0",
    "vue-router": "^3.0.1",
     "@vue/cli-plugin-babel": "^3.7.0",
    "@vue/cli-plugin-typescript": "^3.7.0",
    "@vue/cli-service": "^3.7.0",
   "vue-template-compiler": "^2.5.21",
```

### Steps to reproduce
1.  clone this sample
     https://github.com/kumaresan-subramani/ej2-vue-samples
2. give `npm i`
3. run the application using `npm run serve`
4. Then goto `http://localhost:8080/#/material/auto-complete/template.html` sample and enter value in that sample you will see `template` properties are not working

### What is expected?
need to work like below

https://ej2.syncfusion.com/vue/demos/#/material/auto-complete/template.html

### What is actually happening?
values not getting displayed

**Comment by kumaresan-subramani** [comment]
Hi @sodatea ,

In here, i got sollution but how can i use this in my application ?

https://stackoverflow.com/questions/57012338/vue-cli-service-build-does-not-generate-templates-code

**Comment by LinusBorg** [comment]
https://cli.vuejs.org/config/#runtimecompiler

**Comment by sodatea** [comment]
Create a new file called `vue.config.js`

**Comment by kumaresan-subramani** [comment]
@sodatea , thanks Bro...
