### ISSUE TITLE
Cannot Create Project

### ISSUE THREAD

**Issue by danielbrooks4p** [vuejs/vue-cli#4984]
### Version
4.1.1

### Environment info
```
  System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  Binaries:
    Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 71.0
    Safari: 13.0.3
  npmGlobalPackages:
    @vue/cli: 4.1.1
```

### Steps to reproduce
Using the `vue ui` command and the environment settings above, follow along with the project setup detailed in Vue School's Vue Router course (https://vueschool.io/lessons/create-a-new-project-with-vue-router-using-the-vue-cli-ui). 

### What is expected?
A project is set up correctly.

### What is actually happening?
The CLI cannot install many dependencies and crashes. Projects get "created" but are never recognized as projects in the UI.

**Comment by sodatea** [comment]
> The CLI cannot install many dependencies and crashes. Projects get "created" but are never recognized as projects in the UI.

What's the created project like?

Might be caused by pre-existing `NODE_ENV` environment variable in your environment. Make sure it's unset. (If it was set to `production`, devDependencies will fail to install.)
