### ISSUE TITLE
The "Vue init" command does not work correctly on windows 10

### ISSUE THREAD

**Issue by juliandavidmr** [vuejs/vue-cli#499]
Hi,

I'm using windows 10. When trying to generate a project __webpack__ does not work.

What happens is this:
1. I execute the command `vue init webpack .`
2. Then it shows `Generate project in current directory?`, I type `Y`.
3. Next, it displays the message `Project name (WinJS_Vue):`, Here is the problem because I can not write anything, and I can not even exit the program using Ctrl + C, Ctrl + Z, exit ... Because the CMD terminal is suspended and stops working.

__Package Versions:__
- Node - 8.1.0
- NPM - 5.0.3
- Vue CLI - 2.8.2

**Comment by posva** [comment]
dup of #484
