### ISSUE TITLE
如何实现公共模块发生变动而不需要全部引用模块都重新打包

### ISSUE THREAD

**Issue by taozhangxian** [vuejs/vue-cli#4994]
### Version
4.1.1
### Environment info
```
 System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Users\taozx\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
```

### Steps to reproduce
假如我有30个模块分30个组30改独立项目，其中依赖了一个公共模块，当公共模块有变更时，我如何避免所有项目重新打包

### What is expected?
当公共模块变更，只有重新打包公共模块，所有模块引用的是打包后的公共模块的文件的路径，

### What is actually happening?
必须把公共模块复制到各个模块 然后分模块打包。

### Environment info
```
 System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Users\taozx\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
```

### Steps to reproduce
假如我有30个模块分30个组30改独立项目，其中依赖了一个公共模块，当公共模块有变更时，我如何避免所有项目重新打包

### What is expected?
当公共模块变更，只有重新打包公共模块，所有模块引用的是打包后的公共模块的文件的路径，

### What is actually happening?
必须把公共模块复制到各个模块 然后分模块打包。

**Comment by sodatea** [comment]
https://webpack.js.org/configuration/externals/
