### ISSUE TITLE
vue create or vue info doesn't output anything

### ISSUE THREAD

**Issue by webcoderkz** [vuejs/vue-cli#4995]
### Version
4.1.1

### Reproduction link
[https://forum.vuejs.org/t/vue-cli-doesnt-work-on-catalina-10-15-2/83224](https://forum.vuejs.org/t/vue-cli-doesnt-work-on-catalina-10-15-2/83224)

### Environment info
```
MacOS Catalina 10.15.2
Node 12.10.0
NPM 6.13.3
```

### Steps to reproduce
Install globally `npm i -g @vue/cli` on MacOS Catalina 10.15.2, then try to create a new project `vue create appname` - outputs nothing, no errors, nothing. Same with `vue info`

### What is expected?
It just works, creates an app, shows the info

### What is actually happening?
Nothing, no output

**Comment by AdelineDs** [comment]
Hello,

I encountered the same problem.
To solve it I have to uninstall @ vue / cli (which was in version 4.xx) and reinstall it by specifying a version: npm install -g @ vue / cli @ 3.0.1

Hoping it will help someone.
Have a good day
