### ISSUE TITLE
Can you use ES6 modules in vue config yet?

### ISSUE THREAD

**Issue by martixy** [vuejs/vue-cli#4996]
### What problem does this feature solve?
It's the new decade (almost) and config still relies on ancient CommonJS module syntax.

Is it possible to use the new(ish) ES6 modules in the config instead?  
In webpack you can use `webpack --config-register esm`.

Is a similar feature in vue-clie yet?

(Related: https://github.com/vuejs/vue-cli/issues/4477)

### What does the proposed API look like?
Same as webpack? I don't know, just pipe `config-register` back to webpack?

**Comment by Akryum** [comment]
ES6 modules are still experimental in the most recent versions of Node.js.

**Comment by martixy** [comment]
Dang. I got confused by this page:
https://nodejs.org/api/modules.html

Turns out I should be looking here:
https://nodejs.org/api/esm.html
