### ISSUE TITLE
node 8.1.2 install vue-cli and to meet the wrong

### ISSUE THREAD

**Issue by naihe138** [vuejs/vue-cli#500]
<img width="890" alt="123" src="https://user-images.githubusercontent.com/12893716/27259757-cddf7f94-544c-11e7-9e5d-ec04c1449fe2.png">

node v8.1.2

npm v5.0.3

Have enclosed the debug.log
Please help to resolve this issue.thx

**Comment by posva** [comment]
use `sudo` it's telling you

**Comment by naihe138** [comment]
@posva yes  at last i use ‘sudo’   but  it didn't work~~~~can·t  closed this issue

**Comment by posva** [comment]
The problem you're facing is related to npm. Googling it will probably give
you the answer
