### ISSUE TITLE
vue-cli 中路由用 keep-alive 缓存且 <router-view> 加了 key 之后修改 js 热更新白屏

### ISSUE THREAD

**Issue by hellomrbigshot** [vuejs/vue-cli#5008]
### Version
4.1.2

### Reproduction link
[https://github.com/hellomrbigshot/router-test](https://github.com/hellomrbigshot/router-test)

### Environment info
```
macOS 10.15.2
Chrome 79.0.3945.88
```

### Steps to reproduce
将界面切换到Page1，然后修改page1的js代码，page1界面消失了。
但是将 <router-view/> 的 key 去掉就能正常热更新。

### What is expected?
修改代码后界面正常更新

### What is actually happening?
修改js代码后界面显然出错

**Comment by sodatea** [comment]
Duplicate of https://github.com/vuejs/vue-loader/issues/1332
