### ISSUE TITLE
Dedicated config file .browserslistrc never read

### ISSUE THREAD

**Issue by ThomasKientz** [vuejs/vue-cli#5010]
### Version
4.1.2

### Reproduction link
[https://github.com/ThomasKientz/vue-cli-issue-repro-browserlist](https://github.com/ThomasKientz/vue-cli-issue-repro-browserlist)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  Binaries:
    Node: 12.1.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 69.0.3
    Safari: 13.0.3
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.1.2 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.1.2 
    @vue/cli-plugin-babel: ^4.1.0 => 4.1.2 
    @vue/cli-plugin-eslint: ^4.1.0 => 4.1.2 
    @vue/cli-plugin-router:  4.1.2 
    @vue/cli-plugin-vuex:  4.1.2 
    @vue/cli-service: ^4.1.0 => 4.1.2 
    @vue/cli-shared-utils:  4.1.2 
    @vue/component-compiler-utils:  3.1.0 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.3 
    vue: ^2.6.10 => 2.6.11 
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.8.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.1.2
```

### Steps to reproduce
`npm run build`

### What is expected?
Babel to read `.browserslistrc` file to determine targets for transpilation. So bundled js files in `/dist` to not contain any object spread syntax (ES6).

### What is actually happening?
For the demonstration of the issue, I have used object spread syntax in `App.vue`. Babel is configured with the default vue preset that uses browserslist. I have modified the dedicated `.browserslistrc` file to include only : `ie 10`. Somehow, after building the output still contains object' spread syntax. 

But, if you configure browserslist in the `package.json` file it works as expected, no more spread syntaxt in bundled files. See the branch "solution" .

---
Project created with vue cli 4.1.2 with the `dedicated config files` option.

**Comment by sodatea** [comment]
Sorry, but I can't reproduce this issue with the given project…

**Comment by LinusBorg** [comment]
would it be possible that this is some permission problem on your system?

**Comment by linglongmi** [comment]
Has it been resolved? I also have the same problem. Vue CLI defaults to configuring the browserslist field using packageion.json. If I introduce the preset @ vue/cli plugin babel/reset in babel.cnfig.js and use targets.browsers to configure browser compatibility, it will take effect. However, adding the. browserslistrc file configuration will not take effect.

**Comment by linglongmi** [comment]
> ### Version
> 4.1.2
> 
> ### Reproduction link
> https://github.com/ThomasKientz/vue-cli-issue-repro-browserlist
> 
> ### Environment info
> ```
> Environment Info:
> 
>   System:
>     OS: macOS 10.15.1
>     CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
>   Binaries:
>     Node: 12.1.0 - /usr/local/bin/node
>     Yarn: 1.15.2 - /usr/local/bin/yarn
>     npm: 6.13.4 - /usr/local/bin/npm
>   Browsers:
>     Chrome: 79.0.3945.88
>     Firefox: 69.0.3
>     Safari: 13.0.3
>   npmPackages:
>     @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
>     @vue/babel-plugin-transform-vue-jsx:  1.1.2 
>     @vue/babel-preset-app:  4.1.2 
>     @vue/babel-preset-jsx:  1.1.2 
>     @vue/babel-sugar-functional-vue:  1.1.2 
>     @vue/babel-sugar-inject-h:  1.1.2 
>     @vue/babel-sugar-v-model:  1.1.2 
>     @vue/babel-sugar-v-on:  1.1.2 
>     @vue/cli-overlay:  4.1.2 
>     @vue/cli-plugin-babel: ^4.1.0 => 4.1.2 
>     @vue/cli-plugin-eslint: ^4.1.0 => 4.1.2 
>     @vue/cli-plugin-router:  4.1.2 
>     @vue/cli-plugin-vuex:  4.1.2 
>     @vue/cli-service: ^4.1.0 => 4.1.2 
>     @vue/cli-shared-utils:  4.1.2 
>     @vue/component-compiler-utils:  3.1.0 
>     @vue/preload-webpack-plugin:  1.1.1 
>     @vue/web-component-wrapper:  1.2.0 
>     eslint-plugin-vue: ^5.0.0 => 5.2.3 
>     vue: ^2.6.10 => 2.6.11 
>     vue-eslint-parser:  5.0.0 
>     vue-hot-reload-api:  2.3.4 
>     vue-loader:  15.8.3 
>     vue-style-loader:  4.1.2 
>     vue-template-compiler: ^2.6.10 => 2.6.11 
>     vue-template-es2015-compiler:  1.9.1 
>   npmGlobalPackages:
>     @vue/cli: 4.1.2
> ```
> 
> ### Steps to reproduce
> `npm run build`
> 
> ### What is expected?
> Babel to read `.browserslistrc` file to determine targets for transpilation. So bundled js files in `/dist` to not contain any object spread syntax (ES6).
> 
> ### What is actually happening?
> For the demonstration of the issue, I have used object spread syntax in `App.vue`. Babel is configured with the default vue preset that uses browserslist. I have modified the dedicated `.browserslistrc` file to include only : `ie 10`. Somehow, after building the output still contains object' spread syntax.
> 
> But, if you configure browserslist in the `package.json` file it works as expected, no more spread syntaxt in bundled files. See the branch "solution" .
> 
> Project created with vue cli 4.1.2 with the `dedicated config files` option.

Has it been resolved? I also have the same problem. Vue CLI defaults to configuring the `browserslist` field using `package.json`. If I introduce the preset `@vue/cli-plugin-babel/reset` in `babel.cnfig.js` and use `targets.browsers` to configure browser compatibility, it will take effect. However, adding the `.browserslistrc` file configuration will not take effect.
