### ISSUE TITLE
吐槽一下 vue.config.js

### ISSUE THREAD

**Issue by DeanDrake** [vuejs/vue-cli#5011]
算是初学者吧，刚开始看了几个参差不齐的博文教程，说是要用到 vue.config.js 这个配置文件，但是我创建的项目目录下根本就没有这个文件，又查了些说是这个文件需要手动创建，手动填写，真是醉了。。。

说到底，这个文件还是可能会用到的，而且会有很大的用处。我如果不用这个文件的话我可以**自行删除**，但是你这一个用来创建项目的工具怎么能不创建它呢，需要用到但是有没有，让人很懵。。。

**Comment by sodatea** [comment]
对于项目配置，我的想法是：

- 「足够好的默认配置」是 Vue CLI 这个项目的核心目标之一。如果我们有效地达成了这个目标，vue.config.js 的存在感就肯定是非常低的，那我们没必要默认生成，只有实际有需要的高级用户才用得着它，而这些用户肯定得懂得去找文档，知道要自己创建。
- 对于使用场景略少但足够通用的配置，我觉得 plugin 和 preset 应该可以覆盖大部分场景。这样子的话，要么自定义配置被封装在插件中，用户不再需要自己去理解和修改，要么 vue.config.js 会从 preset 里生成，那 Vue CLI 本身也没必要默认生成这个文件。

所以对于你吐槽的这个点，我觉得 Vue CLI 可以改进的地方有这些：
1. 针对「初学者」但是又需要用 vue.config.js 自定义配置这一点，我觉得可能是我们的默认配置或者初始化引导做得不够好，如果你可以具体描述一下有什么场景需要自己去改这个文件的话，我们可以在这方面改进；
2. 针对「几个参差不齐的博文教程」，这方面我们可能需要注意加强一下社区教程的引导，避免出现误导人的情况……

**Comment by DeanDrake** [comment]
（前端新人，我来描述下我遇到情况）

- 之前稍稍用过 vue-cli 2.x 的 `vue init webpack xxx` 命令来创建项目，最近用最新版的 `vue create` 来创建项目，发现目录结构有不小的出入，找了几篇博文（非社区的）想了解一下差异目录的功用，发现有的介绍里面有 vue.config.js 这个文件，有的则没有。
- 刚开始以为是我创建的方式不对，用另一种方式创建项目后也还是没有这个文件。之后看的某篇文章说 原 build 目录下的 config.js 被换成了 vue.config.js 且需要手动创建，好吧。。。
- 当今天遇到跨域问题需要在 vue.config.js 文件中进行配置时，想到前几天经历，有些不堪，遂来吐槽。

PS：官网上的指南我貌似也没有发现有提到 vue.config.js 的内容（可能我看的不仔细吧，而指南后面的配置参考也就心大跳过没看，否则也应该早发现了）。

PPS：我觉得 vue.config.js 这种参数众多的配置文件还是蛮重要的，最起码要让人知道有这么个东西🤦‍♀️。

**Comment by jo0ger** [comment]
我觉得文档加一句话就可以了

**Comment by Sirlanri** [comment]
我遇到了跨域的问题，Google到的解决方案几乎是清一色的编辑 vue.config.js
请问您解决问题的方式，就是手动新建vue.config.js，然后进行编辑？

**Comment by DeanDrake** [comment]
@Sirlanri 是要手动创建编辑。
附上我的渣配置：
```
module.exports = {
    chainWebpack: config = >{
        config.plugin("define").tap(args = >{
            args[0]["process.env"].BASE_API_URL = JSON.stringify("/api");
            return args;
        });
    },
    lintOnSave: false,
    devServer: {
        open: true,
        host: "localhost",
        port: "8080",
        https: false,
        // hotOnly: false, // 是否开启热更新 
        proxy: {
            "/api": {
                target: "http://localhost:8082",
                changeOrigin: true,
                pathRewrite: {
                    "^/api": ""
                }
            }
        }
    }
}
```

**Comment by Sirlanri** [comment]
@DeanDrake 
感谢您的回复！
我们没有创建vue.config.js，而是采用新的方式，绕过了跨域。
不过今后肯定会遇到跨域问题，感谢您提供了切实可行的解决方案！
