### ISSUE TITLE
vue cli plugin typescript generate project throw error

### ISSUE THREAD

**Issue by Phinome** [vuejs/vue-cli#5018]
### Version
4.1.2

### Environment info
```
System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  Binaries:
    Node: 10.16.3 - /usr/local/opt/node@10/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/opt/node@10/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: Not Found
    Safari: 13.0
  npmPackages:
    @bytedesign/web-vue: ^1.5.5 => 1.5.6
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  3.12.1
    @vue/cli-plugin-babel: ^3.8.0 => 3.12.1
    @vue/cli-plugin-eslint: ^3.8.0 => 3.12.1
    @vue/cli-plugin-typescript: ^4.1.2 => 4.1.2
    @vue/cli-plugin-unit-jest: ^3.10.0 => 3.12.1
    @vue/cli-service: ^3.8.0 => 3.12.1
    @vue/cli-shared-utils:  3.12.1 (4.1.2)
    @vue/component-compiler-utils:  3.0.2
    @vue/composition-api: ^0.3.4 => 0.3.4
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    ag-grid-vue: ^21.1.0 => 21.2.2
    eslint-plugin-vue: ^5.2.2 => 5.2.3 (4.7.1)
    jest-serializer-vue:  2.0.2
    vue: ^2.6.10 => 2.6.10
    vue-chat-scroll: ^1.3.5 => 1.3.6
    vue-class-component:  6.3.2
    vue-cli-plugin-svg-sprite: ^1.0.0 => 1.0.0
    vue-clickaway:  2.2.2
    vue-clipboard2: ^0.3.0 => 0.3.1
    vue-context: ^5.0.0 => 5.0.0
    vue-echarts: ^4.0.3 => 4.0.4
    vue-eslint-parser:  5.0.0 (2.0.3)
    vue-fixed-header: ^3.2.2 => 3.2.11
    vue-hot-reload-api:  2.3.4
    vue-jest:  3.0.5
    vue-loader:  15.7.2
    vue-property-decorator: ^7.2.0 => 7.3.0
    vue-router: ^3.1.2 => 3.1.3
    vue-scroll: ^2.1.12 => 2.1.13
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.1 => 3.1.2
    vuex-router-sync: ^5.0.0 => 5.0.0
  npmGlobalPackages:
    @vue/cli: 4.1.2
```

### Steps to reproduce
vue add typescript 
 WARN  There are uncommited changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? Yes

📦  Installing @vue/cli-plugin-typescript...

yarn add v1.21.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ @vue/cli-plugin-typescript@4.1.2
info All dependencies
└─ @vue/cli-plugin-typescript@4.1.2
✨  Done in 9.68s.
✔  Successfully installed plugin: @vue/cli-plugin-typescript

? Use class-style component syntax? No
? Use Babel alongside TypeScript (required for modern mode, auto-detected polyfills, transpiling JSX)
? Yes
? Convert all .js files to .ts? No
? Allow .js files to be compiled? Yes

🚀  Invoking generator for @vue/cli-plugin-typescript...
 ERROR  Error: Line 20: Unexpected token ...
Error: Line 20: Unexpected token ...
    at ErrorHandler.constructError (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.parseObjectPropertyKey (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2499:33)
    at Parser.parseObjectProperty (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2534:25)
    at Parser.parseObjectInitializer (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2602:35)
    at Parser.inheritCoverGrammar (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parsePrimaryExpression (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2354:38)
    at Parser.inheritCoverGrammar (/usr/local/lib/node_modules/@vue/cli/node_modules/esprima/dist/esprima.js:2285:37)

### What is expected?
success or throw helpful error stack

### What is actually happening?
failed and throw nouse error stack

**Comment by sodatea** [comment]
Looks like something went wrong when parsing some js files.
Would you provide a reproduction repo, please? Without real code, it's hard to tell which syntax caused it to fail.

**Comment by Phinome** [comment]
sorry, the code is private.

now, i create new project with cli, everything is okay.

thanks~

**Comment by baruchiro** [comment]
This issue should be open until we get a better error message.

Maybe we can print the "unexpected token"?

**Comment by baruchiro** [comment]
I removed the Spread Operator from **line 20** in my `.eslintrc.js` file, and it works! What the chance?

Do we work on the same project? ;-) (no)

**Comment by ma-jahn** [comment]
Thanks @baruchiro 
Removing Spread Operators in my .eslintrc.js did the trick 🎉
