### ISSUE TITLE
npm run build 

### ISSUE THREAD

**Issue by nieyulin112** [vuejs/vue-cli#502]
打包的时候报这个问题
ERROR in static/js/vendor.6cb8570731583c9b326b.js from UglifyJs
Unexpected token: operator (>) [./~/iview/src/mixins/emitter.js:2,0][static/js/vendor.6cb8570731583c9b326b.js:44067,34]

**Comment by nieyulin112** [comment]
iview是2.0.0-rc.17

**Comment by egoist** [comment]
Please refer to the iview docs.
