### ISSUE TITLE
more vue.config.js,  How to write

### ISSUE THREAD

**Issue by wuchuguang** [vuejs/vue-cli#5025]
### Version
4.1.2

### Reproduction link
[https://www.github.com](https://www.github.com)

### Environment info
```
all
```

### Steps to reproduce
i want define more vue.config.js ,

but, i cant do it.

### What is expected?
load use config, can i load other config?

### What is actually happening?
vue.config.js
vue.test.js
vue.dev.js

**Comment by sodatea** [comment]
Why not just conditionally load these files in `vue.config.js`?
It's a JS file anyway. You can do whatever you want in that file.
