### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kumaresan-subramani** [vuejs/vue-cli#5027]
### Version
3.12.1

### Reproduction link
[https://github.com/kumaresan-subramani/sample-ref](https://github.com/kumaresan-subramani/sample-ref)

### Environment info
```
"@vue/cli-plugin-babel": "^3.7.0",
"@vue/cli-plugin-typescript": "^3.7.0",
"@vue/cli-service": "^3.7.0",
"vue": "^2.5.2",
		"vue-class-component": "4.3.1",
		"vue-property-decorator": "^6.0.0",
		"vue-router": "^3.0.1"
```

### Steps to reproduce
1. clone my sample - https://github.com/kumaresan-subramani/sample-ref/tree/master

2. give `npm i`

3. then run `npm run serve`

4. you will see my issue and my search also not get working

### What is expected?
no console error and search works fine

### What is actually happening?
Console error and search not working fine

```
vue.esm.js?a026:628 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'length' of undefined"

found in

---> <App> at src/App.vue
       <Root>
warn @ vue.esm.js?a026:628
logError @ vue.esm.js?a026:1893
globalHandleError @ vue.esm.js?a026:1888
handleError @ vue.esm.js?a026:1848
invokeWithErrorHandling @ vue.esm.js?a026:1871
callHook @ vue.esm.js?a026:4228
insert @ vue.esm.js?a026:3148
invokeInsertHook @ vue.esm.js?a026:6357
patch @ vue.esm.js?a026:6576
Vue._update @ vue.esm.js?a026:3954
updateComponent @ vue.esm.js?a026:4075
get @ vue.esm.js?a026:4488
Watcher @ vue.esm.js?a026:4477
mountComponent @ vue.esm.js?a026:4082
Vue.$mount @ vue.esm.js?a026:9063
Vue.$mount @ vue.esm.js?a026:11974
eval @ main.ts?cd49:6
./src/main.ts @ app.js:12656
__webpack_require__ @ app.js:727
fn @ app.js:101
1 @ app.js:12682
__webpack_require__ @ app.js:727
(anonymous) @ app.js:794
(anonymous) @ app.js:797
vue.esm.js?a026:1897 TypeError: Cannot read property 'length' of undefined
    at Function.t.DocumentStore.load (elasticlunr.min.js:10)
    at Function.t.Index.load (elasticlunr.min.js:10)
    at VueComponent.loadTheme (App.vue?ec60:1202)
    at VueComponent.loadJSON (App.vue?ec60:1631)
    at VueComponent.mounted (App.vue?ec60:543)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at callHook (vue.esm.js?a026:4228)
    at Object.insert (vue.esm.js?a026:3148)
    at invokeInsertHook (vue.esm.js?a026:6357)
    at Vue.patch [as __patch__] (vue.esm.js?a026:6576)
```

### Reference image - 

![Screenshot (17)](https://user-images.githubusercontent.com/36756050/71708856-053afa00-2e1a-11ea-9676-3342a621daec.png)

---
I am using `"elasticlunr": "0.9.5",` for my search process

**Comment by kumaresan-subramani** [comment]
HI @sodatea ,  I am expecting your suggestions brother...!

**Comment by sodatea** [comment]
From the error message, I think it's not a bug in Vue CLI.

Our Github issues are for bug reports and feature requests only.
I'd recommend you to ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
