### ISSUE TITLE
vue create . does not allow upper case letters.  Causes headaches when integrating into existing project

### ISSUE THREAD

**Issue by MarkBMtz** [vuejs/vue-cli#5032]
### What problem does this feature solve?
When integrating vue into existing web frameworks like Aspnet you cannot install into the root web project unless your aspnet web projects folder is all lower case.

Most guidelines on the web say to make a sub folder called app that you stuff everything into.  That seems like a hack.  I assume the casing restriction is due to npm package.json restrictions.

### What does the proposed API look like?
Allow users to create a package.json file ahead of time and take the name from that instead.  

So steps to add vue to existing project could be

npm init --yes

vue create .

If the naming restriction goes beyond package.json, just add a --lower-name flag or something.

**Comment by sodatea** [comment]
Makes sense.
Though `npm` does not support upper case letters, it automatically turns them into lower case and goes on.
Also, most use cases of upper case letters are for folder names, not for the `name` property in `package.json`. I'll submit a PR for it.

**Comment by sodatea** [comment]
After a second thought, I'm now hesitant about adding this feature. See the notes at https://github.com/vuejs/vue-cli/pull/5096

**Comment by Kuufo** [comment]
Any more considerations on this? My current solution is to simply rename the directory Vue gives me after I run `vue create some-app` to `SomeApp`. Works, of course, however this is just my personal project directory for a standalone app so the restriction on naming seems a little out of place here.
