### ISSUE TITLE
vuecli 插件 如何本地测试

### ISSUE THREAD

**Issue by bhabgs** [vuejs/vue-cli#5037]
### Version
4.0.2

### Reproduction link
[https://github.com/aepe/vue-cli-plugin-aepe-lint](https://github.com/aepe/vue-cli-plugin-aepe-lint)

### Environment info
```
mac v10.15.2 
node v12.11.1
vue 2.6
vuecli 4.0.2

```

### Steps to reproduce
cli插件本地开发测试，在官网没有具体测试方案

### What is expected?
期望一个较好开发方案

### What is actually happening?
本地测试较为困难

---
我希望能够在官网提供一个插件开发 测试的方案

**Comment by fangbinwei** [comment]
可以先参考官方插件的单元测试, 用`@vue/cli-test-utils`

**Comment by bhabgs** [comment]
非常感谢，目前已经知道该如何去做了。
