### ISSUE TITLE
I can't enter description

### ISSUE THREAD

**Issue by Chooin** [vuejs/vue-cli#504]
### I can't enter description
vue-cli：v2.8.2
node version：node v8.1.0
iTerm2：Build 3.0.15 or Build 3.1.beta.5
system environment：macOS Sierra
``` bash
vue init webpack sp-dashboard
? Project name sp-dashboard
# I can't enter description
? Project description (A Vue.js project) 
```
After using `vue init`， `control + c` is not working 😓😓😓😓

**Comment by posva** [comment]
update node to a more recent version 🙂

**Comment by safevirus** [comment]
node v8.0.0 can resolve it
