### ISSUE TITLE
require('electron') in jest test case returns a string(module absolute path) instead of module object

### ISSUE THREAD

**Issue by bruceauyeung** [vuejs/vue-cli#5054]
### Version
3.12.1

### Reproduction link
[http://no.repo](http://no.repo)

### Environment info
```
Environment Info:

  System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (8) x64 Embedded AMD Opteron(tm) Processor 23KS EE
  Binaries:
    Node: 12.13.1 - /bin/node
    Yarn: 1.19.0 - /bin/yarn
    npm: 6.12.1 - /bin/npm
  Browsers:
    Chrome: dev
    Firefox: 69.0.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.0.5
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.0.5
    @vue/cli-plugin-babel: ^4.0.0 => 4.0.5
    @vue/cli-plugin-e2e-cypress: ^4.0.0 => 4.0.5
    @vue/cli-plugin-eslint: ^4.0.0 => 4.0.5
    @vue/cli-plugin-router:  4.0.5
    @vue/cli-plugin-typescript: ^4.0.0 => 4.0.5
    @vue/cli-plugin-unit-jest: ^4.0.0 => 4.0.5
    @vue/cli-plugin-vuex:  4.0.5
    @vue/cli-service: ^4.0.0 => 4.0.5
    @vue/cli-shared-utils:  4.0.5
    @vue/component-compiler-utils:  3.0.2
    @vue/eslint-config-prettier: ^5.0.0 => 5.1.0
    @vue/eslint-config-typescript: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    eslint-plugin-vue: ^5.0.0 => 5.2.3
    jest-serializer-vue:  2.0.2
    typescript: ~3.5.3 => 3.5.3
    vue: ^2.6.10 => 2.6.10
    vue-class-component: ^7.0.2 => 7.1.0
    vue-cli-plugin-electron-builder: ^1.4.3 => 1.4.3
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.4
    vue-jest:  3.0.5
    vue-loader:  15.7.2
    vue-property-decorator: ^8.3.0 => 8.3.0
    vue-router: ^3.1.3 => 3.1.3
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.2
  npmGlobalPackages:
    @vue/cli: 3.3.0
```

### Steps to reproduce
my electron app was created via `vue create xxx` and `vue add electron-builder`.
when creating the app, what i  chose for the app:
~~~
Use class-style component syntax: choose y
Use Babel alongside TypeScript: choose y
Use history mode for router: choose n
Pick a CSS pre-processor: choose less              
Pick a linter / formatter config choose: eslint + prettier    
Pick additional lint features: choose Lint on save
Pick a unit testing solution: choose jest             
Pick a E2E testing solution: choose cypress            
Where do you prefer placing config: choose In dedicated config files
~~~

i use [jest-electron](https://github.com/hustcc/jest-electron) as jest's runner and testEnvironment because some modules(electron-util, native modules) can only run on an electron process

the failing jest test case :
~~~js
// file : test.spec.js
jest.setTimeout(100000);

test('Window Loads Properly',  () => {

  expect(process.type).toBe('renderer'); // true
  try{
    const electron = require('electron');
    console.log(`${typeof electron}`)  // got a string, expecting module object
                                //value is '/root/icenter-next/node_modules/electron/dist/electron'
  }catch(e){
    console.log(e)
  }
  try{
    const {ipcRenderer} = require('electron');
    console.log(`${typeof ipcRenderer}`)  // got undefined, expecting object
  }catch(e){
    console.log(e)
  }
  try{
    const exit = require('exit');
    console.log(`${typeof exit}`)  // function, expected
  }catch(e){
    console.log(e)
  }
  try {
    const { is } = require('electron-util');
  } catch (e) {
    console.log(e)
  }
});
~~~

but i can workaround this by replace all `require` keyword	to `globalThis.require`, inspired by https://github.com/electron/electron/issues/7300#issuecomment-248773783

the working `test.spec.js`
~~~js
jest.setTimeout(100000);
test('Window Loads Properly',  () => {
  expect(process.type).toBe('renderer');  // true
  try{
    const electron = window.require('electron');  // use window.require instead of require
    console.log(`${typeof electron}`)  // object
    console.log(`${electron}`)  // object, not  module absolute path
  }catch(e){
    console.log(e)
  }
  try {
    const { is } = globalThis.require('electron-util'); // use globalThis.require instead of require
    console.log(`${is.renderer}`) // true
  } catch (e) {
    console.log(e)
  }
});

~~~

it looks like babel's `require` conflicts normal `require`

but my module are almost written with TypeScript, so here is the failing test.spec.ts
~~~js
import electron from 'electron';
import { is } from 'electron-util';

jest.setTimeout(100000);
test('Window Loads Properly',  () => {
  expect(process.type).toBe('renderer');
  try{
    console.log(`${typeof electron}`)
    console.log(`${electron}`)
  }catch(e){
    console.log(e)
  }
  try {
    console.log(`${is.renderer}`) 
  } catch (e) {
    console.log(e)
  }
});

~~~
this test case will fail when Node.js try to resolve modules,  because `electron-util` try to require `electron` but got a string instead of a module object. error:
>\# yarn test:unit
>yarn run v1.19.0
>$ vue-cli-service test:unit
> FAIL  tests/unit/refUtils.spec.ts
>  ● Test suite failed to run
>
>    TypeError: Cannot create proxy with a non-object as target or handler
>
>      1 | import WorkbenchTab from '@/components/Workbench/workbenchTab';
>      2 | import { remote } from 'electron';
>    > 3 | import { is } from 'electron-util';
>        | ^
>      4 |
>      5 | import { SharedObjectKey } from '@/sharedObjects/sharedObjectKey';
>      6 |
>
>      at Object.<anonymous> (node_modules/electron-util/source/api.js:4:18)
>      at Object.<anonymous> (node_modules/electron-util/index.js:8:13)
>      at Object.<anonymous> (src/sharedObjects/sharedObjects.ts:3:1)
>      at Object.<anonymous> (src/logger/index.ts:3:1)
>      at Object.<anonymous> (src/commons/lang/array.ts:1:1)
>      at Object.<anonymous> (src/bindings/types.ts:3:1)
>      at Object.<anonymous> (tests/unit/refUtils.spec.ts:1:1)

`electron-util/source/api.js` source code quoted from github repo:
~~~js
'use strict';
const electron = require('electron');

module.exports = new Proxy(electron, {
	get: (target, property) => target[property] || (target.remote ? target.remote[property] : undefined)
});
~~~

### What is expected?
`require('electron')` and `import electron from 'electron'` can work correctly in jest test case with `jest-electron`

### What is actually happening?
`require('electron')` and `import electron from 'electron'` failed to work in jest test case because it returns a string (module absolute path ) instead of module object itself.

**Comment by LinusBorg** [comment]
1. I don't see how the Vue CLI base configuration has anything to do with this or could be changed to support this. 
2. your setup is ery ucstom

* using a 3rd party Vue CLI plugin that heavily messes with onfigs and project setup
* using a different jest runner than the one we support.
* you already found a workaround.

3. Given that you didn't povide a reproduction of the issue, there's nothing to further look into.

**Comment by bruceauyeung** [comment]
@LinusBorg i found a workaround that works only for `xxx.spec.js`, not `xxx.spec.ts`, would you please to give some hints about how to tell babel transpiling `import('electron')` to  `globalThis.require('electorn')` ?

**Comment by LinusBorg** [comment]
No, unfortunately I have no idea how to do that.

**Comment by bruceauyeung** [comment]
@LinusBorg ok then, i will give a reproduction repo later, thanks

**Comment by bruceauyeung** [comment]
the root cause of the problem:
`jest` has its own `require` function implementation and it replaces node/electron's `require` before running each test cases. you can restore `require` function to node/electron's version via `jest`'s `setupFiles` scripts

thank you again @LinusBorg

**Comment by richirich999** [comment]
Now Can you please share the final solution.How to import remote and Menu from electron in jest in a correct way?
