### ISSUE TITLE
QUESTION: How do I use the vue-cli-service to create a Vue 3 app?

### ISSUE THREAD

**Issue by dannysmc95** [vuejs/vue-cli#5058]
### What problem does this feature solve?
Hello all,

I know that Vue 3 is in pre-alpha, but my company is looking at a 8 month process of rebuilding our platform and we can see that Vue 3 will be coming out soon, so we would quite like to start using it and trialling it out and testing some prototypes, so was wondering if there is a way I can get some kind of base setup (like Vue CLI for Vue 2)?

If this is something that already exists, can you let me know how to? and if not can someone point me in the right direction of creating a new setup for it?

Thanks,

### What does the proposed API look like?
N/A

**Comment by sodatea** [comment]
I've written a simple plugin: https://github.com/vuejs/vue-cli-plugin-vue-next#readme

**Comment by dannysmc95** [comment]
That's great, thank you! Will have a little look!
