### ISSUE TITLE
Error: Failed to load plugin 'vue' declared in 'BaseConfig':  Cannot find module 'eslint-plugin-vue'

### ISSUE THREAD

**Issue by Brolly0204** [vuejs/vue-cli#5067]
### Version
4.1.2

### Environment info
```
macOS 10.15
node v10.16.0 
npm v6.11.3

```

### Steps to reproduce
vue serve

### What is expected?
normal

### What is actually happening?
Unable to start Vue serve normally

**Comment by npearson72** [comment]
Why was this closed?

**Comment by Xuezenghuigithub** [comment]
Why was this closed?
