### ISSUE TITLE
command line freeze after "vue init webpack my-project" on description question

### ISSUE THREAD

**Issue by darkylmnx** [vuejs/vue-cli#507]
After installing the last version of the vue-cli (2.8.2 with **yarn**,
i tried to create a simple project with the webpack template and after entering the name, the commande line freezed or should i say vue-cli freezed and i can't even do "ctrl+c" to stop the commande, though the cursor still blinks

![image](https://user-images.githubusercontent.com/1426357/27516733-fc56bdb0-59bf-11e7-93b8-a61b9e9819f4.png)

same with **git bash**

![image](https://user-images.githubusercontent.com/1426357/27516743-248deed4-59c0-11e7-848b-aaf20ce93cec.png)

Environment:
Windows 10
Vue-cli 2.8.2
Node v8.1.0
Yarn 0.24.6

**Comment by posva** [comment]
upgrade node

**Comment by TomFrajer** [comment]
Same problem after Node upgraded to latest stable.

**Comment by rkg0612** [comment]
Node upgraded to latest stable but I have the same problem. Any fixes yet?

**Comment by dedyjuliana** [comment]
Try to downgrade Node.js to 8.11.3 LTS version, it works here. I used 10.7.0 before but the terminal frozen after Description line.
