### ISSUE TITLE
Vue-cli proxy is not working

### ISSUE THREAD

**Issue by wnghdcjfe** [vuejs/vue-cli#5075]
### Version
@4.1.2

### Reproduction link
https://github.com/wnghdcjfe/vue-cli-proxy-test/tree/master/testing

### Environment info
```
@vue/cli 4.0.1
window 10
```

### Steps to reproduce
I tried all things about same issue https://github.com/vuejs/vue-cli/issues/3588

List of my challenges
## 1. Change cli-service > lib > util > prepareProxy.js
```js
  function mayProxy (pathname) {
    const maybePublicPath = path.resolve(appPublicFolder, pathname.slice(1))
    const isPublicFileRequest = fs.existsSync(maybePublicPath)
    const isWdsEndpointRequest = pathname.startsWith('/sockjs-node') // used by webpackHotDevClient
    // return !(isPublicFileRequest || isWdsEndpointRequest)
    return !(isWdsEndpointRequest)
  }
```
## 2. vue.config.js & ProxyMiddleWare
```js
const proxyMiddleware = require('http-proxy-middleware')
const PROXY = 'http://localhost:12010'
module.exports = {
  devServer: { 
    proxy: {
      '^/api': {
        target: PROXY, 
        ws: false,
        changeOrigin: true
      }
    }, 
    after: app => app.use('/api', proxyMiddleware({ target: PROXY, changeOrigin: true }))
  },
} 
```
## 3. vue-cli-plugin-proxy
```js
module.exports = {
    pluginOptions: {
        proxy: {
            enabled: true,
            context: '/api',
            options: {
                target: 'http://127.0.0.1:12010',
                changeOrigin: true
            }
        }
    }
}
```

But all I tried to do is not working
`Access to XMLHttpRequest at 'http://127.0.0.1:12010/api/auth/token' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

is there solution to solve this things? please give me advice

## My environment
@vue/cli 4.0.1
window 10

### What is expected?
it is worked get data from http://127.0.0.1:12010/api/auth/token

### What is actually happening?
'http://127.0.0.1:12010/api/auth/token' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by cheqianxiao** [comment]
@wnghdcjfe  maybe your axios baseUrl shoud set to be `/` instead of  the target url `'http://127.0.0.1:12345'` (hope this can help

**Comment by wnghdcjfe** [comment]
You are... genius. Thanks a lot.

**Comment by MCYouks** [comment]
Hello @wnghdcjfe I al currently struggling with the exact same issue. Your reproduction link is no longer accessible. Could it be possible to make it available again please ? Thanks

**Comment by wnghdcjfe** [comment]
@MCYouks  Hi I solved this issue by `maybe your axios baseUrl shoud set to be / instead of the target url 'http://127.0.0.1:12345' (hope this can help` go a head!

**Comment by MCYouks** [comment]
Hello @wnghdcjfe  thanks for your reply. Trust me I did, but it didn't work.

I have two main questions for you:

• Which of the 3 solutions you expose did you finally opt for?
• Does it also solve your problem in production mode?

Thanks
