### ISSUE TITLE
快速原型开发无法配置eslint

### ISSUE THREAD

**Issue by loqhcn** [vuejs/vue-cli#5084]
### Version
4.1.2

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Environment info
```
快速原型开发无法配置eslint, 尝试了在根目录创建package.josn和.eslintrc都无效
```

### Steps to reproduce
快速原型开发无法配置eslint, 尝试了在根目录创建package.josn和.eslintrc都无效

### What is expected?
能正常配置,或者说我希望快速原型开发默认不打开eslint

### What is actually happening?
快速原型开发无法配置eslint, 尝试了在根目录创建package.josn和.eslintrc都无效

**Comment by sodatea** [comment]
可以配置的……

注意：快速原型开发针对的是单个文件，所以没有「根目录」的概念，它只会在**当前运行目录**下找配置。

**Comment by loqhcn** [comment]
我是在当前目录配置的 但是无效  您能发个demo么------------------ 原始邮件 ------------------
发件人: "Haoqun Jiang"<notifications@github.com>
发送时间: 2020年1月15日(星期三) 下午5:39
收件人: "vuejs/vue-cli"<vue-cli@noreply.github.com>;
抄送: "mulo"<474693310@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vuejs/vue-cli] 快速原型开发无法配置eslint (#5084)



可以配置的……
 
注意：快速原型开发针对的是单个文&#x4EF6;，所以没有「根目录」的概念，它只会在当前运行目录下找配置。
 
&mdash;

**Comment by sodatea** [comment]
你能发个复现么？我的任何一个项目都能正常处理啊。

**Comment by loqhcn** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Haoqun Jiang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月15日(星期三) 晚上6:34
收件人:&nbsp;"vuejs/vue-cli"<vue-cli@noreply.github.com&gt;;
抄送:&nbsp;"叶落归#庚Ж"<474693310@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vuejs/vue-cli] 快速原型开发无法配置eslint (#5084)




你能发个复现么？我的任何一个项目都能正常处理啊。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.




在vue文件内似乎没有问题, 但是外部引入的js, 使用console.log 和&nbsp;localStorage的时候就有问题, 配置了关闭eslint但是没有效果,
