### ISSUE TITLE
VUE_CLI_BABEL_TRANSPILE_MODULES 设置为true 无法生效

### ISSUE THREAD

**Issue by yangyiming** [vuejs/vue-cli#5088]
### Version
4.1.1

### Environment info
```
 System:
    OS: macOS Mojave 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  Binaries:
    Node: 10.10.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 70.0.1
    Safari: 12.0.3
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.12.1 
    @vue/babel-preset-jsx:  1.1.1 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.1.1 
    @vue/babel-sugar-v-on:  1.1.0 
    @vue/cli-overlay:  3.12.1 
    @vue/cli-plugin-babel: 3.6.0 => 3.6.0 
    @vue/cli-plugin-eslint: 3.6.0 => 3.6.0 
    @vue/cli-plugin-unit-jest: ^3.8.0 => 3.12.1 
    @vue/cli-service: 3.6.0 => 3.6.0 
    @vue/cli-shared-utils:  3.12.1 
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    eslint-plugin-vue: 5.2.2 => 5.2.2 (4.7.1)
    jest-serializer-vue:  2.0.2 
    vue: 2.6.10 => 2.6.10 
    vue-eslint-parser:  2.0.3 (5.0.0)
    vue-hot-reload-api:  2.3.4 
    vue-jest:  3.0.5 
    vue-loader:  15.7.1 
    vue-router: 3.0.6 => 3.0.6 
    vue-style-loader:  4.1.2 
    vue-template-compiler: 2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuedraggable: ^2.23.0 => 2.23.2 
    vuex: 3.1.0 => 3.1.0 
    vuex-persistedstate: ^2.5.4 => 2.6.0 
  npmGlobalPackages:
    @vue/cli: 4.1.1

```

### Steps to reproduce
npm run dev

### What is expected?
实现开发环境路由懒加载

### What is actually happening?
全部打包成了APP.js 无法实现分包加载

**Comment by sodatea** [comment]
懒加载应该跟 VUE_CLI_BABEL_TRANSPILE_MODULES 没有关系。你需要的是使用 `import()` 语句……

**Comment by yangyiming** [comment]
项目使用就是import 导入的方式
`{
    path: '/',
    name: 'teacher',
    redirect: '/courseIndex',
    component: () => import('@/layout/index'),
    meta: { title: '教师平台',role: [super_teacher, teacher, teacher_noclass]  },
    children: [
      {
        path: 'courseIndex',
        name: 'courseIndex',
        component: () => import('@/views/teacher/course/index'),
        meta: { title: '课程管理',role: [super_teacher, teacher, teacher_noclass]}
      },
      {
        path: 'gameManagement',
        name: 'gameManagement',
        redirect: {name: 'tGame'},
        component: () => import('@/views/teacher/gameManagement/index'),
        meta: { title: '赛事管理',role: [super_teacher, teacher, teacher_noclass] },
        children: [
          {
            path: 'tGame',
            name: 'tGame',
            component: () => import('@/views/teacher/gameManagement/gameList'),
            meta: { title: '比赛列表',role: [super_teacher, teacher, teacher_noclass] },
            hidden: true
          },
          {
            path: 'tGame/result/:id',
            name: 'gameResult',
            component: () => import('@/views/teacher/gameManagement/gameResult'),
            meta: { title: '比赛成绩',role: [super_teacher, teacher, teacher_noclass] },
            hidden: true
          },
          {
            path: 'tGame/group/:id',
            name: 'groupList',
            component: () => import('@/views/teacher/gameManagement/groupList'),
            meta: { title: '比赛小组',role: [super_teacher, teacher, teacher_noclass] },
            hidden: true
          },
          {
            path: 'tTest',
            name: 'tTest',
            component: () => import('@/views/teacher/gameManagement/testPaper'),
            meta: { title: '试卷列表',role: [super_teacher, teacher, teacher_noclass] },
            hidden: true
          },
          {
            path: 'tTest/assignTopic/:id',
            name: 'assignTopic',
            component: () => import('@/views/teacher/gameManagement/assignTopic'),
            meta: { title: '案例出题',role: [super_teacher, teacher, teacher_noclass] },
            hidden: true
          }

        ]
      },
      {
        path: 'analysisTool',
        name: 'analysisTool',
        component: () => import('@/views/teacher/analysisTool/index'),
        meta: { title: '分析工具',role: [super_teacher, teacher, teacher_noclass] }
      },
      {
        path: 'analysisChart',
        name: 'analysisChart',
        component: () => import('@/views/teacher/analysisTool/analysisChart'),
        meta: { title: '工具图表',role: [super_teacher, teacher, teacher_noclass] },
        hidden: true
      },
      {
        path: 'enterpriseData',
        name: 'enterpriseData',
        component: () => import('@/views/teacher/enterpriseData/index'),
        meta: { title: '企业数据',role: [super_teacher, teacher, teacher_noclass] }
      },
      {
        path: 'schoolInformation',
        name: 'schoolInformation',
        component: () => import('@/views/teacher/schoolInformation/index'),
        meta: { title: '学校信息',role: [super_teacher] }
      },
      {
        path: 'organizationalManagement',
        name: 'organizationalManagement',
        component: () => import('@/views/teacher/organizationalManagement/index'),
        meta: { title: '组织管理',role: [super_teacher, teacher] }
      },
      {
        path: 'teacherManagement',
        name: 'teacherManagement',
        component: () => import('@/views/teacher/teacherManagement'),
        meta: { title: '教师管理',role: [super_teacher] }
      },
      {
        path: 'studentManagement',
        name: 'studentManagement',
        component: () => import('@/views/teacher/studentManagement'),
        meta: { title: '学生管理',role: [super_teacher, teacher] }
      },
      {
        path: 'systemMessages',
        name: 'systemMessages',
        component: () => import('@/views/teacher/systemMessages'),
        meta: { title: '系统消息',role: [super_teacher]}
      },
    ]
  },`

**Comment by sodatea** [comment]
那理论上不会有问题啊……
我刚在 Vue CLI 3 默认生成的带 vue-router 的项目里试验了一下，即使是在开发环境下也是有懒加载的
（注意看这里 about.js 前面的图标，它不是作为一个要被执行的 JS 文件加载的，而是因为页面里的 preload 标签所导致的资源预加载，直到切换到 about 页面才是真正加载执行了）。

![image](https://user-images.githubusercontent.com/3277634/72591443-19631900-393b-11ea-8e15-c6266a675ee9.png)


麻烦提供一下最小复现吧

**Comment by whatlife** [comment]
+1

**Comment by sodatea** [comment]
这个环境变量和分包加载没有关系。更大可能是 webpack 配置出了问题。
