### ISSUE TITLE
How can i use computed‘s 'set' and 'get' in '.vue' file?

### ISSUE THREAD

**Issue by zhuxiao2004** [vuejs/vue-cli#509]
How can i use computed‘s 'set' and 'get' in '.vue' file like:
// ...
computed: {
  fullName: {
    // getter
    get: function () {
      return // ...;
    },
    // setter
    set: function (newValue) {
      // ...
    }
  }
}
// ...

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
