### ISSUE TITLE
Vue not inherited from .env (.env.*) file when running in a different mode

### ISSUE THREAD

**Issue by hamza-makraz** [vuejs/vue-cli#5093]
Vue-cli Version: 3.7.0
Environment info
  System:
    OS: macOS Catalina 10.15.2
  Binaries:
    Node: v12.14.0
    Yarn: 1.21.1
    npm: 6.13.4
  Browsers:
    Chrome: Version 78.0.3904.108 (Official Build) (64-bit)

I have the same issue NODE_ENV not inherited from .env file when running in a different mode 
but when i restart system and again the command take the env config 

**Scenario**

I run build with : **npm run build -- --mode development**
the build done successfully after that i run the build with **npm run build**  (also i tried **npm run build -- --mode production**)
the build done successfully but all config is inherited from **.env.development** and not from **.env. production**
but if i restart the system again and run **npm run build**  (or **npm run build -- --mode production**) the build done successfully and it's work fine 

so what i think is that the config is loaded on the RAM and when the mode is change vue-cli done update config in RAM

_Originally posted by @hamza-makraz in https://github.com/vuejs/vue-cli/issues/3983#issuecomment-575928382_

**Comment by sodatea** [comment]
Can't reproduce and not likely a Vue CLI issue because it's not possible for Vue CLI to affect its parent process's environment variables.

Please check other configurations in your system.

**Comment by hamza-makraz** [comment]
Hi thank you for reply 
I found that this issue is linked to ohmyz and zsh

when I close the terminal and open a new one the build work normal
