### ISSUE TITLE
同一项目，是否可以通过修改配置来实现打出不同的发布包？

### ISSUE THREAD

**Issue by jackytsu** [vuejs/vue-cli#5095]
### What problem does this feature solve?
我有一个公用的后台管理类的前端项目，针对不同的后端应用会有一些不同的配置，比如不同的登录页面样式和LOGO，不同整体页面的布局等等。目前都是通过运行时的代码来进行动态的加载组件或路由，但是最终的发布包会包含多余的静态资源、无用的路由或组件。是否可以通过配置来实现打出来的包只包含需要的资源和组件呢？

### What does the proposed API look like?
增加配置项目，根据不同的值选择对应的资源进行打包操作。

**Comment by sodatea** [comment]
vue.config.js 是一个 JS 文件，所以里面可以写各种逻辑，根据传进来的不同环境变量或者其他什么参数来动态调整返回的配置，这个是一直都可以的。
