### ISSUE TITLE
inquirer@0.12.0 inquirer.prompt is not work in node v8.1.0

### ISSUE THREAD

**Issue by hodor-cn** [vuejs/vue-cli#510]
inquirer@0.12.0 inquirer.prompt is not work in node v8.1.0;
With node v8.1.0 run vue init pwa pwa, enter the name after the stuck, and then no response
when i change the inquirer to 3.1.1, it works but can't pass the unit test, so i close the pull requests, There may be a better solution

**Comment by posva** [comment]
upgrade node
