### ISSUE TITLE
Is the vue ui easily extracted from this project?

### ISSUE THREAD

**Issue by bschlenk** [vuejs/vue-cli#5101]
### What problem does this feature solve?
Extending other cli's with a feature rich gui, with just a few config files.

### What does the proposed API look like?
Not sure yet, but I'd like to start a discussion!

**Comment by LinusBorg** [comment]
Hi. :)

Currently, the UI is likely not that easy to extract as it's using a couple of shared dependencies from this monorepo and it's not designed as a framework that can be put on arbitrary CLIs - it's pretty closely attached to the design of the CLI API and the way our plugin system works.

@Akryum can say more to this though, and also about where he wants to take this in the future.

**Comment by bschlenk** [comment]
I wonder how much effort it would be to pull it out and make it config driven. I thought it was one of the coolest experiences starting a new project, if it was really easy to add to a project then I could see it being a new defacto requirement for project starters.

**Comment by sodatea** [comment]
Well, now there's https://github.com/Akryum/guijs, please check it out.
