### ISSUE TITLE
Support for node 8.10.0

### ISSUE THREAD

**Issue by gribanov2la** [vuejs/vue-cli#5104]
### Version
4.1.2

### Environment info
```
Environment Info:

  System:
    OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 72.0.1
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
1. Install vue-cli "yarn global add @vue/cli"
2. Create project "vue create project-name"
3. Select "babel/eslint" preset
....
4. Error

### What is expected?
Successful installation of application template

### What is actually happening?
Error:
```
yarn install v1.21.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
error default-gateway@5.0.5: The engine "node" is incompatible with this module. Expected version "^8.12.0 || >=9.7.0". Got "8.10.0"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Found incompatible module.
 ERROR  command failed: yarn --registry=https://registry.yarnpkg.com

```

---
On the PC on which the project is being developed on vue, node 8.10.0 is strictly installed without the possibility of updating. The vue-cli documentation says `Vue CLI requires Node.js version 8.9 or above (8.11.0  recommended) .`

**Comment by sodatea** [comment]
Workaround:
```
vue config --set packageManager npm
```

It's due to the `default-gateway` and its `execa` dependency requires Node >= 8.12.
Though, even with this requirement, it should only be a warning in older version.

So another cause of this issue is that Yarn and NPM [handles the `engines` field differently](https://github.com/yarnpkg/yarn/issues/6627).

As [the npm documentation](https://docs.npmjs.com/files/package.json#engines) said:

> Unless the user has set the `engine-strict` config flag, this field is advisory only and will only produce warnings when your package is installed as a dependency.

But Yarn makes it a hard fail.

So the workaround is to switch to NPM for now.

**Comment by LinusBorg** [comment]
Node 8 isn't supported anymore since end of 2019, so I don't think we should invest any effort for it in Vue CLI.

**Comment by NumesSanguis** [comment]
How to upgrade Node to 9 (or higher)?
I'm also on Ubuntu 18.04 and following the official instructions here (today): https://classic.yarnpkg.com/en/docs/install/#debian-stable
I also end up with version `Node: 8.10.0`.
Tried to `yarn install` some Vue project, but encountered the same error as OP.

Googling for something like "ubuntu 18.04 yarn update node to 9", doesn't give me any answers.

**Comment by NumesSanguis** [comment]
@sodatea @LinusBorg Any idea about my question above? I just updated my Yarn version to 1.22.5, but still the same issue.

**Comment by LinusBorg** [comment]
yarn is. just a package manager like npm, and npm != node

You have to upgrade NodeJS itself. never done trhat on ubuntu but a quick look at the node website leads here:

https://github.com/nodesource/distributions/blob/master/README.md#debinstall

**Comment by NumesSanguis** [comment]
I see, thank you @LinusBorg . The following code did the trick for me:

```bash
# Using Ubuntu
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs
```

I didn't know that 'node' here referred to NodeJS.
