### ISSUE TITLE
`vue init webpack my-project` stuck at the `Project description` step with Node v8.1.0

### ISSUE THREAD

**Issue by CaptainYouz** [vuejs/vue-cli#511]
Hi,

when trying to run the example command to init a new webpack project, my terminal get stuck at the `Project description` step. See screenshot:

<img width="307" alt="screen shot 2017-06-28 at 5 39 50 pm" src="https://user-images.githubusercontent.com/2973285/27646524-20a1454e-5c29-11e7-8c10-18be27ff5f20.png">

`node -v: v8.1.0`
`npm -v: 5.0.4`
`vue -V: 2.8.2`

on macOs Sierra version 10.12.5

Edit:
after switching to node v6, it is working fine. The vue-cli operate as it should.

**Comment by mashpie** [comment]
ran into same issue 10mins ago. Updating node to v8.1.2 resolved it.

**Comment by egoist** [comment]
There're many existing/duplicated issues like this, upgrading node would fix it :)
