### ISSUE TITLE
npx serve does not work

### ISSUE THREAD

**Issue by geekox86** [vuejs/vue-cli#5111]
### Version
`4.1.2`

### Environment info
```
Windows 10 x64 (1909), NodeJS 10.15.3 x64, NPM 6.4.1 x64
```

### Steps to reproduce
```
md vuecli
npm install @vue/cli
npx vue create test
> Select manual
> Select babel   typescript   router   css pre-processor   linting/formatting   unit testing
> No class style
> Yes for babel along typescript
> Yes for history routing mode
> Yes for dart-sass
> Select ESLint with Standard config
> Select lint on save
> Select Jest
> Select dedicated config files
> No for saving as preset
cd test
npx serve
> Browse to http://localhost:5000
> You will see Index of test with a directory listing of the test directory instead of the Welcome to vue page
```

### What is expected?
Showing the Welcome to vue page

### What is actually happening?
Showing a directory listing of the test directory

---
I am not installing @vue/cli globally.
I tested the same setup on my macOS with Yarn and it works perfectly.

**Comment by sodatea** [comment]
But the command is `npm run serve` rather than `npx serve`. By executing the latter command you are actually running the [`serve` package](https://www.npmjs.com/package/serve)
