### ISSUE TITLE
When I use "npm run build" to build the program, the background-image path is not correct

### ISSUE THREAD

**Issue by laden666666** [vuejs/vue-cli#512]
Thanks vue-cli tool, I do not need to personally configure webpack, but I encountered a problem.

My static files and html flies are in the same directory, so I used a relative path.Look at my `config.js` file's assetsPublicPath property.
```
// see http://vuejs-templates.github.io/webpack for documentation.
var path = require('path')

module.exports = {
  build: {
    env: require('./prod.env'),
    index: path.resolve(__dirname, '../dist/index.html'),
    assetsRoot: path.resolve(__dirname, '../dist'),
    assetsSubDirectory: 'static',
    assetsPublicPath: './',
```

In my program, I used the **background-url** css attribute：
```
<style>
    .my-style{
        background-image: url('./assets/logo.jpg');
    }
</style>
```
This image and the vue file are in the same directory.In the development process, the program is not wrong.

But when I ran "npm run build", I found that my program was having problems.My picture is placed in the `static / img` directory,my css file is placed in the `static / css` directory.The value of background-image is as follows
```
background-image:url(static/img/logo.1680760.jpg)}
```
Obviously it`s wrong.

Because vue-cli uses `extract-text-webpack-plugin`, if vue-cli does not use this plugin, the background-image url is correct. I know that this plugin has the `ExtractTextPlugin.extract` function, which allows me to tell the webpack css file relative to the asset directory location. But I do not know how to use it in vue-cli.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
Also, please note this is a webpack question and is actually related to a specific template

**Comment by sumitridhal** [comment]
@posva I've the same issue.
@laden666666 Did you find any solution for this one?
