### ISSUE TITLE
Unable to install @vue/cli

### ISSUE THREAD

**Issue by vkbamania** [vuejs/vue-cli#5127]
### Version
4.1.2

### Reproduction link
[https://codepen.io/vkbamania/pen/abzgezJ](https://codepen.io/vkbamania/pen/abzgezJ)

### Environment info
```
Windows 10, Node v12.14.1, NPM 6.13.4
```

### Steps to reproduce
Just ran "npm install -g @vue/cli" and got the error.

### What is expected?
Install Vue CLI

### What is actually happening?
 npm install -g @vue/cli
npm ERR! Unexpected end of JSON input while parsing near '...","dependencies":{"cr'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2020-02-01T09_25_45_976Z-debug.log

---
I tried every possible combination to install Vue CLI but still unable to do so.

**Comment by vkbamania** [comment]
You guys should improve this, as I'm surfing through your Github page and found the same issue with previous versions.

**Comment by sodatea** [comment]
It's an npm / network issue.
Please check your network connection, verify the npm cache, and try again.

> You guys should improve this

I'm not sure what we can do regarding such issues. As it comes from npm, not from `@vue/cli`.
