### ISSUE TITLE
Instant Prototyping with Typescript

### ISSUE THREAD

**Issue by pleek91** [vuejs/vue-cli#5138]
### Version
4.1.2

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 4.6.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.1.2
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.1.2
    @vue/cli-plugin-babel: ^4.1.0 => 4.1.2
    @vue/cli-plugin-eslint: ^4.1.0 => 4.1.2
    @vue/cli-plugin-router:  4.1.2
    @vue/cli-plugin-typescript: ^4.1.0 => 4.1.2
    @vue/cli-plugin-unit-mocha: ^4.1.0 => 4.1.2
    @vue/cli-plugin-vuex:  4.1.2
    @vue/cli-service: ^4.1.0 => 4.1.2
    @vue/cli-shared-utils:  4.1.2
    @vue/component-compiler-utils:  3.1.1
    @vue/eslint-config-typescript: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0 => 5.2.3
    typescript: ~3.5.3 => 3.5.3
    vue: ^2.6.10 => 2.6.11
    vue-class-component: ^7.0.2 => 7.2.2
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.8.3
    vue-property-decorator: ^8.3.0 => 8.3.0
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. `vue create my-app`
2. Choose default
4. `vue serve ./my-app/src/components/HelloWorld.vue`

**Note that the `HelloWorld` vue component is served in the browser as expected**

1. `vue create my-typescript-app`
2. Choose `Manually select features`
3. Select `TypeScript`
4. Enter `n` for Use class-style component syntax
5. Enter `n` for Use Babel alongside TypeScript
6. `vue serve ./my-typescript-app/src/components/HelloWorld.vue`

**Note how the browser tab is now empty rather than displaying the component.**

1. Repeat the previous steps but answer `Y` for Use class-style component syntax

**Note Error**
```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                            5:01:25 PM
 error  in ./src/components/HelloWorld.vue?vue&type=script&lang=ts&

Module parse failed: Unexpected character '@' (35:0)
You may need an appropriate loader to handle this file type.
| import { Component, Prop, Vue } from 'vue-property-decorator';
|
> @Component
| export default class HelloWorld extends Vue {
|   @Prop() private msg!: string;

 @ ./src/components/HelloWorld.vue?vue&type=script&lang=ts& 1:0-179 1:195-198 1:200-376 1:200-376
 @ ./src/components/HelloWorld.vue
```

### What is expected?
I would expect the HelloWorld.vue component to be served no matter what settings I select while running vue create

### What is actually happening?
Typescript components are either not displayed or error when attempting to serve. 

---
All three vue apps can be served by serving the `./src/main.js` or `./src/main.ts` file. But when attempting to serve the HelloWorld.vue component directly, it only works if TypeScript wasn't selected when creating the app. 

I ran across this because I'm creating a library of components. And rather than having a playground page/app it seemed like using `vue serve MyComponent.vue` would be the perfect way to develop each individual component. 

I didn't create a minimal reproduction repo because I'm literally not writing any code. Seems the cli serve doesn't work as I'm expecting it to out of the box.

**Comment by LinusBorg** [comment]
When you create a project with `vue create`, you're no longer prototyping in the sense that we use this term in the docs.

Consequently, you should be using `vue-cli-service serve` to serve your project, not `vue serve` - which is meant to serve a quick prototype, not a project.

Prototyping doesn't currently support TS. Yoiu can open a feature request for this, but it's not a bug.

**Comment by pleek91** [comment]
ah okay thanks for your reply. That distinction is definitely not clear in the docs in my opinion. 

https://cli.vuejs.org/guide/prototyping.html says

> vue serve uses the same default setup (webpack, babel, postcss & eslint) as projects created by vue create. It automatically infers the entry file in the current directory - the entry can be one of main.js, index.js, App.vue or app.vue. You can also explicitly specify the entry file:

And the entry file example says `vue serve MyComponent.vue`

In reading that I understood that vue create and vue serve worked together (which I know know is incorrect). So it seemed logical to me that if my project was typescript then `serve` would use the projects webpack and serve the typescript component. But `serve` has its own webpack and will not support any customizations made by the project. 

Thanks for clearing that up for me though!
