### ISSUE TITLE
Installing CLI plugins. taking too much time get download.

### ISSUE THREAD

**Issue by vikashRG** [vuejs/vue-cli#5144]
### Version
4.1.2

### Environment info
```
  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 8.10.0 - /usr/bin/node
    Yarn: Not Found
    npm: 3.5.2 - /usr/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.2
  npmGlobalPackages:
    @vue/cli: 4.1.2


```

### Steps to reproduce
sudo npm install -g vue

sudo npm install -g @vue/cli

sudo vue create mpproj

### What is expected?
The project "mpproj" was created.

### What is actually happening?
After choosing parameters this text was showing in console for endless time :

Vue CLI v4.1.2
sparkles Creating project in /home/vikash/mpproj.
⚙ Installing CLI plugins. This might take a while...

loadDep:jsesc -> network - |##########################################################---------------------------------------------------------------------------------------------------------------------|

{
"name": "mpproj",
"version": "0.1.0",
"private": true,
"devDependencies": {
"@vue/cli-plugin-babel": "^4.1.0",
"@vue/cli-plugin-eslint": "^4.1.0",
"@vue/cli-service": "^4.1.0"
}
}

**Comment by sodatea** [comment]
Don't use `sudo` to create projects.

And your npm version seems quite old, there might be known bugs in it.

**Comment by vikashRG** [comment]
I have updated my npm and also tried to create project without sudo. still facing the same issue.

**Comment by sodatea** [comment]
If you successfully updated npm, I think there should be a different error message. What's the output now?

**Comment by vikashRG** [comment]
![Screenshot from 2020-02-05 15-57-10](https://user-images.githubusercontent.com/54055697/73833586-37cc7e00-4830-11ea-8255-2ddf193e6b9f.png)

no, it's not giving any error message. please find the screenshot.

**Comment by sodatea** [comment]
Looks like an npm (or network) issue.

What about running the `npm install --verbose` command in the target folder (`/home/vikash/myprok`)? If it's an npm issue, then this command will produce the same result but with more verbose output. And then we can try to diagnose the problem from the output.

**Comment by vikashRG** [comment]
I have run '''npm run --verbose" . now it's still doing the same. Please find the screenshot.
It keeps loading other plugins.

![Screenshot from 2020-02-05 16-30-25](https://user-images.githubusercontent.com/54055697/73836430-3a7da200-4835-11ea-89fc-1dee91c5922e.png)
![Screenshot from 2020-02-05 16-32-55](https://user-images.githubusercontent.com/54055697/73836432-3baecf00-4835-11ea-91bd-5696669f2ca0.png)

**Comment by sodatea** [comment]
I mean:
1. `Ctrl` + `C` to stop the command
2. `cd myprok` (There's a `package.json` in the project but the plugins haven't been successfully installed yet.)
3. `npm install --verbose` (We are now trying to install the plugins by using npm directly and see if there's any helpful error messages)

**Comment by sodatea** [comment]
Another command to try is `vue config --set useTaobaoRegistry false`, in case it's caused by the network connectivity to taobao registry.

**Comment by vikashRG** [comment]
> I mean:
> 
> 1. `Ctrl` + `C` to stop the command
> 2. `cd myprok` (There's a `package.json` in the project but the plugins haven't been successfully installed yet.)
> 3. `npm install --verbose` (We are now trying to install the plugins by using npm directly and see if there's any helpful error messages)

Yes I did the same. its still not working.

**Comment by sodatea** [comment]
> Yes I did the same. its still not working.

What's the output of `npm install --verbose`?

**Comment by sodatea** [comment]
Your screenshots were the outputs of `vue create`

**Comment by vikashRG** [comment]
> > Yes I did the same. its still not working.
> 
> What's the output of `npm install --verbose`?

It simply installed all node modules.

**Comment by sodatea** [comment]
So npm works but `vue create` doesn't? Then it might be caused by `useTaobaoRegistry`. Please run `vue config --set useTaobaoRegistry false` and try again.

**Comment by vikashRG** [comment]
`vue config --set useTaobaoRegistry false ` this worked for me. Thanks.
