### ISSUE TITLE
Vue Cli created project doesn't show up in Vue UI

### ISSUE THREAD

**Issue by ProffeComics01** [vuejs/vue-cli#5152]
### Version
4.1.2

### Environment info
```
Node 12.13.0
```

### Steps to reproduce
Create a Vue project from the console with vue create projectname on a folder which was previously filled with a "git clone remoteurl" command.
Start Vue UI from project folder, no projects is available.

### What is expected?
See the project created with CLI in the web UI

### What is actually happening?
The project doesn't show up

---
I had to create the project with command line VS VueUI because on the UI, if you choose an exhisting (git initialized) folder, choose Overwrite destination and choose Don't init GIT fails and overwrite my git settings because a new subfolder with same name is created.

**Comment by LinusBorg** [comment]
I can't start the UI right now (and our docs are lacking in describing its features), but you should be able to *add* a project from an existing folder, there's a button for that.

**Comment by ProffeComics01** [comment]
Yes, you are right!
After writing the issue I realized there was an Import Button which did the
trick.
Sorry for false flag.

Il Ven 7 Feb 2020, 09:39 Thorsten Lünborg <notifications@github.com> ha
scritto:
