### ISSUE TITLE
Error: No module factory available for dependency type: CssDependency

### ISSUE THREAD

**Issue by FranciscoMendes10866** [vuejs/vue-cli#5154]
### Version
4.1.0

### Reproduction link
[https://github.com/FranciscoMendes10866/Juliana-Project.git](https://github.com/FranciscoMendes10866/Juliana-Project.git)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
npm install
npm run build

### What is expected?
No errors

### What is actually happening?
Error: No module factory available for dependency type: CssDependency

---
This week I started to learn Vue CLI and when I try to Build my Web App the following error appears in the Output of the vue ui:

Error: No module factory available for dependency type: CssDependency

I'm quite new to this and I don't quite understand why this happens, even because when I do the "run serve", the Web App works on localhost.

I spoke with a friend of mine at college and he told me to install a few dependencies, such as mini-css-extract-plugin, vue-style-loader and css-loader. But it did not work.

**Comment by sodatea** [comment]
I'm sorry but the link is broken.
According to feedbacks from [other similar issues](https://github.com/vuejs/vue-cli/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+No+module+factory+available+for+dependency+type%3A+CssDependency), it's likely [due to the path casing](https://github.com/vuejs/vue-cli/issues/5022#issuecomment-570770950). Please check your project path in the terminal.

**Comment by FranciscoMendes10866** [comment]
> I'm sorry but the link is broken.
> According to feedbacks from [other similar issues](https://github.com/vuejs/vue-cli/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+No+module+factory+available+for+dependency+type%3A+CssDependency), it's likely [due to the path casing](https://github.com/vuejs/vue-cli/issues/5022#issuecomment-570770950). Please check your project path in the terminal.

Thank you! It worked but now the problem is that when I run build cmd and I upload it on netlify, some text elements just disappeared.
