### ISSUE TITLE
Document how to upgrade vue-cli

### ISSUE THREAD

**Issue by Uninen** [vuejs/vue-cli#5155]
### What problem does this feature solve?
There's currently no documented way to upgrade vue-cli, however there is `vue upgrade --all`. If you search current documentation for 'upgrade', you find only one mention for the word and even that is just marketing speak. 

We should have a documented way to do upgrades to `vue-cli` inside the repo so when for example user sees a security issue in Vue UI dashboard in vue-cli packages, there would be a documented way to do the upgrade.

### What does the proposed API look like?
Start with minimal and easiest documentation, expand later (when we for example have non-experimental command available). I'm happy to start a PR if it helps.

**Comment by NataliaTepluhina** [comment]
@Uninen thank you for creating the issue! Starting a PR would be really nice if you're fine with working on it 👍

**Comment by Uninen** [comment]
Added a short PR. I'm not familiar how tightly these changes are screened, but there's definitely room for improvements by at least checking by someone English-native that the language is not bad :)

**Comment by NataliaTepluhina** [comment]
Closing the issue because related PR was merged
