### ISSUE TITLE
Show old version after update

### ISSUE THREAD

**Issue by NoLimitsStudio** [vuejs/vue-cli#5159]
### Version
4.2.2

### Environment info
```
  System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 13.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
vue --version

### What is expected?
@vue/cli 4.2.2

### What is actually happening?
@vue/cli 4.1.1

and warning while I create new project

---
After update with npm I saw text below

C:\Users\Adv.DESKTOP>npm list -g --depth=0
C:\Users\Adv.DESKTOP\AppData\Roaming\npm
 -- @quasar/cli@1.0.5
 -- @vue/cli@4.2.2
 -- node-sass@4.13.1
`-- yarn@2.0.0-rc.27

C:\Users\Adv.DESKTOP>vue --version
@vue/cli 4.1.1

**Comment by NoLimitsStudio** [comment]
C:\Users\Adv.DESKTOP>npm -g install @vue/cli
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
C:\Users\Adv.DESKTOP\AppData\Roaming\npm\vue -> C:\Users\Adv.DESKTOP\AppData\Roaming\npm\node_modules\@vue\cli\bin\vue.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\@vue\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @vue/cli@4.2.2
updated 1 package in 55.67s

C:\Users\Adv.DESKTOP>vue info

Environment Info:

  System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 13.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0
  npmGlobalPackages:
    @vue/cli: Not Found


C:\Users\Adv.DESKTOP>

**Comment by sodatea** [comment]
Would you please run `yarn global list` to see if there's another instance of `@vue/cli`?

**Comment by NoLimitsStudio** [comment]
C:\Users\Advart.DESKTOP>yarn global list
yarn global v1.22.0
info "@quasar/cli@1.0.5" has binaries:
   - quasar
info "@vue/cli@4.2.2" has binaries:
   - vue
info "eslint@5.16.0" has binaries:
   - eslint
info "gulp-cli@2.2.0" has binaries:
   - gulp
info "parcel-bundler@1.12.4" has binaries:
   - parcel
info "prettier@1.19.1" has binaries:
   - prettier
info "yarn-upgrade-all@0.5.2" has binaries:
   - yarn-upgrade-all
Done in 2.25s.

**Comment by sodatea** [comment]
That doesn't make sense. There must be an old version of `@vue/cli` installed somewhere in the system.

Please run `where vue` (or `Get-Command vue` if you're using PowerShell) to see where it's installed.

**Comment by NoLimitsStudio** [comment]
C:\Users\Adv.DESKTOP>where vue
C:\Program Files\nodejs\vue
C:\Program Files\nodejs\vue.cmd
C:\Users\Adv.DESKTOP\AppData\Local\Yarn\bin\vue
C:\Users\Adv.DESKTOP\AppData\Local\Yarn\bin\vue.cmd
C:\Users\Adv.DESKTOP\AppData\Roaming\npm\vue
C:\Users\Adv.DESKTOP\AppData\Roaming\npm\vue.cmd

**Comment by sodatea** [comment]
The first two don't seem right to me. I don't have such files on my system. Maybe you can remove them and see if the new version works.

**Comment by NoLimitsStudio** [comment]
@sodatea Thank you! Now it's all right
