### ISSUE TITLE
windows npm version error

### ISSUE THREAD

**Issue by ittce** [vuejs/vue-cli#516]
hi, 在check-version.js中，如果我更新了npm的版本，在node 4.4.x版本下，npm包版本为2.14.x，我将版本更新后， child_process获取到的 npm --version 还是2.14.x，造成报错

in check-version.js, if I update npm version, "child_process.execSync()" get the npm version is 2.14.x。 I exec in cmd by myself, the answer is 5.14.x

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by jquery2005** [comment]
Environment Info:
System:
OS: Windows 10
CPU: (8) x64 Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Binaries:
Node: 10.15.3 - E:\Program Files\nodejs\node.EXE
Yarn: 1.15.2 - C:\Users\msdn1\AppData\Roaming\npm\yarn.CMD
npm: 6.4.1 - E:\Program Files\nodejs\npm.CMD
Browsers:
Edge: 42.17134.1.0
PS C:\WINDOWS\system32> npm install -g @vue/cli
npm WARN deprecated joi@14.3.1: This module has moved and is now available at @hapi/joi. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
PS C:\WINDOWS\system32>
how to update dependencies?
