### ISSUE TITLE
Couldn't find package "@vue/cli-plugin-babel" on the "npm" registry

### ISSUE THREAD

**Issue by assisgui** [vuejs/vue-cli#5160]
### Version
4.2.2

### Environment info
```
System:
    OS: Windows 10 10.0.16299
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  Binaries:
    Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.1480.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
npm install -g @vue/cli
vue create my-project

### What is expected?
New Vue app created

### What is actually happening?
When I try create a new app, the error appears: error Couldn't find package "@vue/cli-plugin-babel" on the "npm" registry.

**Comment by sodatea** [comment]
But it does exist: https://www.npmjs.com/package/@vue/cli-plugin-babel
Maybe it's a network/cache problem of npm. Please run `npm cache clean -f` and try again.

**Comment by asssc** [comment]
Same problem on Mac OS X 10.15

**Comment by MostGG** [comment]
same news??
