### ISSUE TITLE
Vue packages version mismatch:

### ISSUE THREAD

**Issue by panayotoff** [vuejs/vue-cli#5161]
### Version
4.2.2

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.17.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.87
    Firefox: 72.0.1
    Safari: 13.0.5
  npmGlobalPackages:
    @vue/cli: 4.2.2
```

### Steps to reproduce
Install @vue/cli using ```sudo npm install -g @vue/cli`` Try to create new project with vue create myproject

### What is expected?
Scaffold new Vue project

### What is actually happening?
Throws new error

Error: 

Vue packages version mismatch:

- vue@2.6.10 (/usr/local/lib/node_modules/vue/dist/vue.runtime.common.js)
- vue-template-compiler@2.6.11 (/usr/local/lib/node_modules/@vue/cli/node_modules/vue-template-compiler/package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

**Comment by sodatea** [comment]
Please run `sudo npm install -g vue`.

Seems due to wrong hoisting or because you 've previously installed an old version of vue globally.

**Comment by Akryum** [comment]
Seems to not be fixed.

**Comment by Akryum** [comment]
Workaround:

```sh
akryum@akryum-XPS-13-9370:~$ cd .config/yarn/global/
akryum@akryum-XPS-13-9370:~/.config/yarn/global$ ls
node_modules  package.json  yarn-error.log  yarn.lock
akryum@akryum-XPS-13-9370:~/.config/yarn/global$ rm -rf node_modules/
akryum@akryum-XPS-13-9370:~/.config/yarn/global$ rm yarn.lock 
akryum@akryum-XPS-13-9370:~/.config/yarn/global$ yarn

```
