### ISSUE TITLE
Switch over to leven for command suggestion

### ISSUE THREAD

**Issue by jamesgeorge007** [vuejs/vue-cli#5164]
### What problem does this feature solve?
As of now [didyoumean.js](https://github.com/dcporter/didyoumean.js/) matching engine is used to suggest matching commands if the user mistypes. But it is not longer actively maintained. Instead I would suggest switching over to [leven](https://github.com/sindresorhus/leven) which is the fastest JS implementation of the Levenshtein distance algorithm. 

### What does the proposed API look like?
`leven` returns the distance between 2 strings which can be made use of to find the exact match.

**Comment by jamesgeorge007** [comment]
@sodatea I would love to shoot a PR :+1:

**Comment by sodatea** [comment]
Good point. Go ahead please.
