### ISSUE TITLE
cli-plugin-e2e-cypress: Upgrade to Cypress v5

### ISSUE THREAD

**Issue by lassesteffen** [vuejs/vue-cli#5177]
### What problem does this feature solve?
Users can use all the new features of cypress v5 like cross browser testing

### What does the proposed API look like?
Update the package.json

**Comment by loter** [comment]
Hi @sodatea , what is the PR number?

**Comment by sodatea** [comment]
https://github.com/vuejs/vue-cli/pull/5139

**Comment by morgant** [comment]
This would also improve BSD support [as noted in a comment](https://github.com/vuejs/vue-cli/pull/5139#issuecomment-636056597) to the aforementioned PR.

**Comment by lassesteffen** [comment]
v5 was release 5 days ago: https://github.com/cypress-io/cypress/releases

**Comment by pocketcolin** [comment]
I'm pretty sure updating our Cypress version would also give us the ability to integrate Typescript following the Cypress TS docs. At the moment, it doesn't look like those docs work running the bundled Cypress version.

**Comment by manuelmazzuola** [comment]
any update?
just installed 4.5.9 version and cypress version is 3.x.x

**Comment by sodatea** [comment]
@manuelmazzuola 
See https://github.com/vuejs/vue-cli/releases/tag/v4.5.9

**Comment by sodatea** [comment]
Updated in [v5.0.0-alpha.0](https://github.com/vuejs/vue-cli/releases/tag/v5.0.0-alpha.0)
