### ISSUE TITLE
npm run sever 如何停止热更新？热更新是否会导致上传文件的页面必然刷新？

### ISSUE THREAD

**Issue by XSun771** [vuejs/vue-cli#5179]
### What problem does this feature solve?
通过 ` <input type="file"> ` 获取文件，调用fetch或axios时将文件组织入一个 FormData 对象交给 data （从头到尾一个 Form 元素都没用，type=submit 的按钮从来没出现过）提交，若成功提交必然引发页面刷新（我在处理请求成功后要求router.push("/")，然后会被这个页面刷新强行刷新回来。），但如果 FormData 中不带文件则不会刷新。同时将build好的网站发布到有 nginx 的服务器上，也不会出现这样的问题。

我实在想不到我这里还能有什么问题了。由于每次刷新后必然出现大两个 大概这样的 socket.js 的请求

http://localhost:8080/sockjs-node/info?t=1581408558968

{"websocket":true,"origins":["*:*"],"cookie_needed":false,"entropy":2165565923}

我看着像是热更新服务相关的东西？

所以想关掉 热更新 这一功能，看看问题会不会复现。

### What does the proposed API look like?
最好能在 vue.config.js 中配置。

**Comment by sodatea** [comment]
关闭热更新：
```js
module.exports = {
  devServer: {
    hot: false,
    liveReload: false
  }
}
```

至于第二个问题，我认为跟热更新关系不大，由于没有复现代码，恕无法进一步解答。
