### ISSUE TITLE
vue create npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex

### ISSUE THREAD

**Issue by danywalls** [vuejs/vue-cli#5182]
Below error comes when creating new project
`Vue CLI v4.1.2
✨  Creating project in C:\Users\dany\Desktop\hello2.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex
npm ERR! 404
npm ERR! 404  'error-ex@^1.3.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'parse-json'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dany\AppData\Roaming\npm-cache\_logs\2020-02-12T12_57_45_506Z-debug.log
 ERROR  command failed: npm install --loglevel error --registry=https://registry.npmjs.org/
`

**Comment by Fowindev** [comment]
See https://github.com/request/request/issues/3142

**Comment by poode** [comment]
try this ;)
npm config set registry https://skimdb.npmjs.com/registry
