### ISSUE TITLE
Build as lib failed

### ISSUE THREAD

**Issue by AlekseyPn** [vuejs/vue-cli#5193]
### Version
4.1.2

### Environment info
```
Environment Info:

  System:
    OS: Linux 5.4 Fedora 31 (Workstation Edition) 31 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: Not Found
    npm: 6.13.7 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.106
    Firefox: 73.0
  npmPackages:
    @storybook/vue: ^5.2.8 => 5.2.8 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.1.2 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.1.2 
    @vue/cli-plugin-babel: ^4.1.2 => 4.1.2 
    @vue/cli-plugin-e2e-cypress: ^4.1.2 => 4.1.2 
    @vue/cli-plugin-eslint: ^4.1.2 => 4.1.2 
    @vue/cli-plugin-router: ^4.1.2 => 4.1.2 
    @vue/cli-plugin-unit-jest: ^4.1.2 => 4.1.2 
    @vue/cli-plugin-vuex: ^4.1.2 => 4.1.2 
    @vue/cli-service: ^4.1.2 => 4.1.2 
    @vue/cli-shared-utils:  4.1.2 
    @vue/component-compiler-utils:  3.1.1 
    @vue/eslint-config-airbnb: ^4.0.0 => 4.0.1 
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/test-utils: ^1.0.0-beta.29 => 1.0.0-beta.29 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    babel-plugin-transform-vue-jsx:  3.7.0 
    babel-preset-vue: ^2.0.2 => 2.0.2 
    eslint-plugin-vue: ^5.0.0 => 5.2.3 
    jest-serializer-vue:  2.0.2 
    vue: ^2.6.10 => 2.6.10 
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-jest:  3.0.5 
    vue-line-clamp: ^1.3.2 => 1.3.2 
    vue-loader:  15.8.3 
    vue-mq: ^1.0.1 => 1.0.1 
    vue-router: ^3.1.3 => 3.1.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.1.2 => 3.1.2 
  npmGlobalPackages:
    @vue/cli: 4.1.2

```

### Steps to reproduce
Create js file with class with static field, try build as lib

### What is expected?
my package build is success

### What is actually happening?
Error:
Module parse failed: Unexpected token (4:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| export default class Token extends Model {
>   static entity = "tokens";
| 
|   static fields() {

 @ ./index.js 3:0-43 11:26-32
 @ /home/fargustian/workspace/whenspeak-core/node_modules/@vue/cli-service/lib/commands/build/entry-lib-no-default.js

---
When I remove static field from class my build is success

**Comment by AlekseyPn** [comment]
And i export class with static fields from index.js file which i build as lib.

**Comment by sodatea** [comment]
Thanks for submitting this issue! Due to our limited time, we ask you to include a reproduction link to a minimal full reproduction of your problem (for example in a GitHub repository) so we can find what is causing the issue. Thank you for your understanding!

**Comment by AlekseyPn** [comment]
https://github.com/AlekseyPn/vue-cli-reproduction - you need install lerna globally and run "lerna run build", if i comment static someStaticField = "field"; build success :)

**Comment by AlekseyPn** [comment]
> Thanks for submitting this issue! Due to our limited time, we ask you to include a reproduction link to a minimal full reproduction of your problem (for example in a GitHub repository) so we can find what is causing the issue. Thank you for your understanding!

https://github.com/AlekseyPn/vue-cli-reproduction - you need install lerna globally and run "lerna run build", if i comment static someStaticField = "field"; build success :)

**Comment by jaireina** [comment]
Hi all, I used the repo provided by @AlekseyPn and I was able to run the build command  without getting errors.

If I run `npx vue-cli-service build --target lib ./packages/reproduction/index.js` everything works fine.

If I import the ReproductionStaticClass in src/main.js and run `npx vue-cli-service build --target lib --inline-vue ./src/main.js` it works. I'm also able to see the app running:
![image](https://user-images.githubusercontent.com/1864623/75125779-807f9600-567c-11ea-9dbb-0ad859b3c36f.png)

However, if I run  `lerna run build` I do get the error you reported. That makes me think that there's a problem with some of the configurations in your project and not with the vue-cli-service.

**Comment by AlekseyPn** [comment]
> Hi all, I used the repo provided by @AlekseyPn and I was able to run the build command without getting errors.
> 
> If I run `npx vue-cli-service build --target lib ./packages/reproduction/index.js` everything works fine.
> 
> If I import the ReproductionStaticClass in src/main.js and run `npx vue-cli-service build --target lib --inline-vue ./src/main.js` it works. I'm also able to see the app running:
> ![image](https://user-images.githubusercontent.com/1864623/75125779-807f9600-567c-11ea-9dbb-0ad859b3c36f.png)
> 
> However, if I run `lerna run build` I do get the error you reported. That makes me think that there's a problem with some of the configurations in your project and not with the vue-cli-service.

You tried comment static field in class, and not comment static method? If comment static field, build works correct.

And i get error when i try build project with optional chaining babel plugin. 

Unfortunately I can not find the error in the configurations. The error is either with you or in lerna :(((

**Comment by AlekseyPn** [comment]
I solved the problem, by install @babel/plugin-proposal-class-properties @vue/babel-preset-app @vue/babel-preset-app in package locally and copy babel.config in folder. Thank, issue closed. :heavy_check_mark:

**Comment by xiaogaofudao** [comment]
@sodatea 遇到了同样问题，打包库文件。4.5.x 版本的 都报错。降级 4.4.x 可以打包成功。
报错信息：
> vue-cli-service build --target lib --name index src/index.js


-  Building for production as library (commonjs,umd,umd-min)...

 ERROR  Failed to compile with 1 error                                                                                                                                                          下午8:11:10
 error  in ./src/components/Dialog/index.vue

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|   <el-dialog
|     class="v-dialog"

 @ ./src/index.js 1:0-41 4:18-24 4:31-37
 @ ./node_modules/@vue/cli-service/lib/commands/build/entry-lib.js
