### ISSUE TITLE
vue serve fails with compile error in eslint-loader/index.js

### ISSUE THREAD

**Issue by paddelboot** [vuejs/vue-cli#5194]
### Version
4.2.2

### Environment info
```
System:
    OS: Linux 4.15 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: Not Found
    npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 72.0.2
  npmGlobalPackages:
    @vue/cli: 4.2.2

```

### Steps to reproduce
`vue create my_project`

*choose defaults*

`cd my_project/src`

`vue serve`

### What is expected?
Starting of development server

### What is actually happening?
INFO  Starting development server...
98% after emitting

 ERROR  Failed to compile with 1 errors                                                                                                                            20:38:46

Module build failed (from /home/hans/.nvm/versions/node/v12.13.1/lib/node_modules/@vue/cli-service-global/node_modules/eslint-loader/index.js):
Error: BaseConfig:
	Configuration for rule "no-debugger" is invalid:
	Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"process.env.NODE_ENV === "production" ? "error" : "off""').

    at validateRuleOptions (/media/Entwicklung/Entwicklung/CodeAcademy/Vue-Router/vue-router/node_modules/eslint/lib/shared/config-validator.js:138:19)
    at /media/Entwicklung/Entwicklung/CodeAcademy/Vue-Router/vue-router/node_modules/eslint/lib/shared/config-validator.js:193:9
    at Array.forEach (<anonymous>)
    at validateRules (/media/Entwicklung/Entwicklung/CodeAcademy/Vue-Router/vue-router/node_modules/eslint/lib/shared/config-validator.js:190:30)
    at validateConfigArray (/media/Entwicklung/Entwicklung/CodeAcademy/Vue-Router/vue-router/node_modules/eslint/lib/shared/config-validator.js:337:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/media/Entwicklung/Entwicklung/CodeAcademy/Vue-Router/vue-router/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/media/Entwicklung/Entwicklung/CodeAcademy/Vue-Router/vue-router/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at CLIEngine.isPathIgnored (/media/Entwicklung/Entwicklung/CodeAcademy/Vue-Router/vue-router/node_modules/eslint/lib/cli-engine/cli-engine.js:951:18)
    at CLIEngine.executeOnText (/media/Entwicklung/Entwicklung/CodeAcademy/Vue-Router/vue-router/node_modules/eslint/lib/cli-engine/cli-engine.js:868:38)
    at lint (/home/hans/.nvm/versions/node/v12.13.1/lib/node_modules/@vue/cli-service-global/node_modules/eslint-loader/index.js:278:17)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.

---
This is a clean install, no custom configuration etc.

    $ npm list -g --depth 0
    /home/hans/.nvm/versions/node/v12.13.1/lib
    ├── @vue/cli@4.2.2
    ├── @vue/cli-service-global@4.2.2
    ├── grunt@1.0.4
    ├── gulp-cli@2.2.0
    ├── http-server@0.12.0
    ├── node-sass@4.13.0
    ├── npm@6.12.1
    └── sfdx-cli@7.36.0

After creating a new project without eslint, `vue serve` is starting the dev server as expected.

**Comment by pberberich** [comment]
Same issue here. Applied the but fix manually but any ETA on when someone might review  Sodatea's PR?

**Comment by Osokavictor** [comment]
pls help me out 
{Failed to compile.

./src/views/Home.vue
Module Error (from ./node_modules/eslint-loader/index.js):

C:\Users\OSOKA\Desktop\VUE\vue-shop\src\views\Home.vue
   2:21  warning  Delete `⏎···⏎··`                                             prettier/prettier
  14:5   error    The "HelloWorld" component has been registered but not used  vue/no-unused-components

✖ 2 problems (1 error, 1 warning)
  0 errors and 1 warning potentially fixable with the `--fix` option.}

**Comment by pberberich** [comment]
> pls help me out
> {Failed to compile.
> 
> ./src/views/Home.vue
> Module Error (from ./node_modules/eslint-loader/index.js):
> 
> C:\Users\OSOKA\Desktop\VUE\vue-shop\src\views\Home.vue
> 2:21 warning Delete `⏎···⏎··` prettier/prettier
> 14:5 error The "HelloWorld" component has been registered but not used vue/no-unused-components
> 
> ✖ 2 problems (1 error, 1 warning)
> 0 errors and 1 warning potentially fixable with the `--fix` option.}

Looks like your Home.vue is expecting a HelloWorld component in your template. It is being registered but you aren't using it. you may have deleted it which is fine you just need to make sure to remove reference to it. 
```
It will look something like this. Just get rid of the `HelloWorld` part and you should be fine. If you are importing it in the doc remove that too. ALSO make sure if you have testing set up that you remove corresponding tests.
component: { HelloWorld }
```

**Comment by pberberich** [comment]
Osokavictor 
It is a linting error. You are registering a hello world component
```
component: { HelloWorld }
```
but you have removed `<HelloWorld />` from your template. 

my guess is that you started with a hello world example and deleted it from `./src/views/Home.vue`

remove HelloWorld from here
`component: { HelloWorld }`
and make it 
`component: { }`
or 
If you aren't registering any more components in the file, remove `component: { }` all together in the spirit of tidiness.
