### ISSUE TITLE
Choosing to save as a preset should also tell you where it was saved

### ISSUE THREAD

**Issue by revolter** [vuejs/vue-cli#5197]
### What problem does this feature solve?
- Run `vue create my-app`
- Choose to save it as a preset

The output that comes after this last question looks identical to the one where you choose not to save it as a preset.

### What does the proposed API look like?
I expected for a "The preset was saved to ~/.vuerc" log to be present.

**Comment by imrishabh18** [comment]
Hey, I am a beginner can i work on this issue ?

**Comment by jaireina** [comment]
@sodatea  I created a pull request for you to check when you have time.
