### ISSUE TITLE
App template includes a package that is not used anymore

### ISSUE THREAD

**Issue by revolter** [vuejs/vue-cli#5198]
### Version
4.2.2

### Environment info
```

Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: Not Found
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.116
    Firefox: 67.0.4
    Safari: 13.0.4
  npmGlobalPackages:
    @vue/cli: 4.2.2

```

### Steps to reproduce
Create a new app using this preset:

```
{
  "useTaobaoRegistry": false,
  "presets": {
    "website-template": {
      "useConfigFiles": true,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-typescript": {
          "classComponent": true,
          "useTsWithBabel": true
        },
        "@vue/cli-plugin-router": {
          "historyMode": false
        },
        "@vue/cli-plugin-eslint": {
          "config": "base",
          "lintOn": [
            "save"
          ]
        }
      },
      "cssPreprocessor": "node-sass"
    }
  }
}
```

### What is expected?
An year ago, when I used this preset with the version that was available then, it created the project with the same npm package, but with `parserOptions: { parser: '@typescript-eslint/parser' }` instead, so it looks to me like `@typescript-eslint/parser` is not used anymore, meaning it shouldn't be declared as a dependency.

### What is actually happening?
It is created with a `package.json` file containing the `@typescript-eslint/parser` package, and with an `.eslintrc.js` file containing `parserOptions: { ecmaVersion: 2020 }`.

**Comment by sodatea** [comment]
It's because the option is moved into the `@vue/eslint-config-typescript` package: https://github.com/vuejs/eslint-config-typescript/blob/166bc0de599f03435dca7fa4af8589d9b259bed5/index.js#L8

`@typescript-eslint/parser` is still required as a peer dependency of that config. https://github.com/vuejs/eslint-config-typescript/blob/166bc0de599f03435dca7fa4af8589d9b259bed5/package.json#L43
