### ISSUE TITLE
It's not clear how to change the page title from the default template

### ISSUE THREAD

**Issue by revolter** [vuejs/vue-cli#5199]
### Version
4.2.2

### Environment info
```

Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: Not Found
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.116
    Firefox: 67.0.4
    Safari: 13.0.4
  npmGlobalPackages:
    @vue/cli: 4.2.2

```

### Steps to reproduce
Use this preset:

```
{
  "useTaobaoRegistry": false,
  "presets": {
    "website-template": {
      "useConfigFiles": true,
      "plugins": {
        "@vue/cli-plugin-babel": {},
        "@vue/cli-plugin-typescript": {
          "classComponent": true,
          "useTsWithBabel": true
        },
        "@vue/cli-plugin-router": {
          "historyMode": false
        },
        "@vue/cli-plugin-eslint": {
          "config": "base",
          "lintOn": [
            "save"
          ]
        }
      },
      "cssPreprocessor": "node-sass"
    }
  }
}
```

### What is expected?
Maybe find a `*webpack*` file with a `title` key for which to change the value?

### What is actually happening?
The project is created with an `index.html` file containing `<title><%= htmlWebpackPlugin.options.title %></title>`, but with no indication of where is that `title` property defined.

**Comment by sodatea** [comment]
It's calculated from the `name` field in `package.json`. For multi-page apps, it's the `title` field in the page options (inside the `pages` field).

**Comment by revolter** [comment]
`pages` field of what object? Or, in what file? `router/index.ts`?

**Comment by sodatea** [comment]
It's explained here: https://cli.vuejs.org/config/#pages

**Comment by igbominadeveloper** [comment]
If you use the vue-pwa plugin, then the `name` is set within your `site.webmanifest` file

**Comment by weiliang903** [comment]
Holy shit, two years have passed, and now you still can't change the title.

**Comment by revolter** [comment]
@weiliang903, see if [this](https://github.com/revolter/iulianonofrei.com/commit/f483f717ac524b076b5294963420b1151bcb4fa6) helps you.

**Comment by majestiq** [comment]
did we ever figure out how to change the title?  Especially for a page that has route params like /product/:id where depending on the id, each page might have a different title?

**Comment by vtonu** [comment]
All I want is to change my localhost300 title in my browser. Why is this so hard? Seriously vue?

**Comment by igbominadeveloper** [comment]
While you are figuring this out, can you check vueuse npm package, there should be a hook to change your title.

**Comment by alejandroyunes** [comment]
how the hell we remove the name key in package.json from the title
