### ISSUE TITLE
@vue/babel-preset-app option exclude conflict

### ISSUE THREAD

**Issue by ac88** [vuejs/vue-cli#5208]
### Version
3.12.1

### Reproduction link
[https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/babel-preset-app/index.js#L8](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/babel-preset-app/index.js#L8)

### Environment info
```
Chrome: 82
```

### Steps to reproduce
at babel.config.js config `exclude:['es6.promise']`

### What is expected?
build dist code exclude core-js es6.promise

### What is actually happening?

only set exclude:['es6.promise'] then build dist code still include core-js es6.promise

---
require config polyfills:['es6.array.iterator','es6.object.assign'] rewrite defaultPolyfills 

but node_modules/@babel/preset-env/lib/built-in-definitions.js has Promise definitions

```js
const definitions = {
  builtins: {
    //...
    Map: ["es6.map"].concat(CommonIterators),
    Number: "es6.number.constructor",
    Promise: ["es6.object.to-string", "es6.promise"]
    //...
  }
}

```

may be defaultPolyfills can remove es6.promise

**Comment by lovetingyuan** [comment]
`es6.promise` is **always** included, see https://cli.vuejs.org/guide/browser-compatibility.html#polyfills
> Note that es6.promise is included by default because it's very common for libs to depend on Promises.

**Comment by lucaswerkmeister** [comment]
[We](https://phabricator.wikimedia.org/project/profile/4074/) also have a use case for this feature request. We don’t mind Promise being polyfilled, whether other libs require it or not; however, Promise is already polyfilled on the page where our app is used, and so it’s unnecessary to include a Promise polyfill in our app bundle, and we would like to remove it to save some bytes (core-js’ Promise polyfill is rather weighty). I’ll send a pull request.

**Comment by lovetingyuan** [comment]
Most modern browsers already support `Promise` for a long time, so the polyfill for `Promise` should not be compulsory any more.
