### ISSUE TITLE
Merge conflict marker encountered

### ISSUE THREAD

**Issue by Patrick-Spiegel** [vuejs/vue-cli#5213]
### Version
4.2.2

### Environment info
```

  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  3.12.1
    @vue/cli-plugin-babel: 3.11.0 => 3.11.0
    @vue/cli-plugin-eslint: 4.2.2 => 4.2.2
    @vue/cli-plugin-typescript: 3.11.0 => 3.11.0
    @vue/cli-plugin-unit-jest: 3.11.0 => 3.11.0
    @vue/cli-service: 3.11.0 => 3.11.0
    @vue/cli-shared-utils:  3.12.1 (4.2.2)
    @vue/component-compiler-utils:  3.1.1
    @vue/eslint-config-airbnb: 5.0.2 => 5.0.2
    @vue/eslint-config-typescript: 5.0.1 => 5.0.1
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.29 => 1.0.0-beta.29
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: 6.1.2 => 6.1.2
    typescript: 3.7.5 => 3.7.5
    vue: 2.6.11 => 2.6.11
    vue-cli-webpack:  1.0.0
    vue-eslint-parser:  7.0.0
    vue-functional-data-merge:  3.1.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.8.3
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Swap branches in git while vue serve is running
2. You have to restart the application due to the error "12:8 error Parse errors in imported module '@/data/graphql/schema': Merge conflict marker encountered. (482:0) import/named"

### What is expected?
Hot-Reload should not view any merge conflict markers. There are none

### What is actually happening?
12:8 error Parse errors in imported module '@/data/graphql/schema': Merge conflict marker encountered. (482:0) import/named

**Comment by LinusBorg** [comment]
We will need a runnable reproduction to understand what you are talking about.

**Comment by Patrick-Spiegel** [comment]
I will attach a project soon, I have currently not really time for this ticket.

**Comment by alexravenna** [comment]
I have the same problem too:
![merge_conflict_marker](https://user-images.githubusercontent.com/29532881/76512585-36a4f700-6455-11ea-84d9-7f22fafd6730.png)

Restarting `npm run serve` "fixes" the problem, but it would still be nice to be able to switch branches (which I have to do not infrequently) without having to restart the HMR server.

Hopefully @Patrick-Spiegel can reproduce this for you guys.

**Comment by Patrick-Spiegel** [comment]
It only occurrs on larger projects. No chance to get this error on smaller samples.

**Comment by alexravenna** [comment]
> It only occurrs on larger projects. No chance to get this error on smaller samples.

What a coincidence, our project is very large 😆.

**Comment by sodatea** [comment]
1. As I just searched, the error message came from typescript codebase.
2. Restarting `npm run serve` does not fix the problem, it just skipped the lint process due to this bug https://github.com/vuejs/vue-cli/issues/3065#issuecomment-454373989

**Comment by Patrick-Spiegel** [comment]
I can confirm that deleting the cache is a sufficient workaround.

**Comment by isaacalves** [comment]
Just solved this by simply commenting and then uncommenting the line of code of a file where the import statement was for the file that allegedly had the merge conflict marker although it had already been resolved and re-saved a few times (React project)

**Comment by matt-s-lee** [comment]
@Popeye4242 Wondering which cache you are referring to? Is it the cache in VSCode (Library > Application Support > Code > Cache)? 

Facing the same error, and commenting/uncommenting did not work. Also received an "Unexpected token" message instead of "Merge conflict marker encountered"

**Comment by HakuTheWolfSpirit** [comment]
@matt-s-lee There should be some directories at the top of the node_modules directory.

**Comment by deadlyw1re** [comment]
I've just encountered this when I was resolving a conflict on my branch in WebStorm and then without finishing switching to another branch.

Clearing cache in the node_module directory resolved it.
