### ISSUE TITLE
UMD build can't be used in Node Env

### ISSUE THREAD

**Issue by rockmandash** [vuejs/vue-cli#5216]
### Version
4.2.2

### Reproduction link
[https://runkit.com/rockmandash/5e554e8282df830013cbf6c0](https://runkit.com/rockmandash/5e554e8282df830013cbf6c0)

### Environment info
```
All Node version
```

### Steps to reproduce
1. Put a random UMD bundle generated from vue-cli-service at top of your node.js file
2. console.log your global UMD name
3. node yells your global name is undefined

### What is expected?
UMD should be usable on the window or Node env.

### What is actually happening?
Node env is not working with UMD build

---
I know it's a WebPack config thing, but can we fix it as vue-cli-service default?

**Comment by jaireina** [comment]
@rockmandash it works, but you need to put it in it your own file and them require it in other, like this (assuming you put the code in a utils.js file):

const {sum} = require('./utils.js');
console.log(sum); // this is a function
