### ISSUE TITLE
Migrate away from request package

### ISSUE THREAD

**Issue by DRoet** [vuejs/vue-cli#5220]
### Version
4.2.2

### Steps to reproduce
warning @vue/cli-plugin-babel > @vue/cli-shared-utils > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

### What is expected?
No deprecation notices in the cli

### What is actually happening?
request is being used in @vue/cli-shared-utils but is now deprecated

**Comment by sodatea** [comment]
Aha! I was thinking about this just now.
Would you like to work on a PR for it?

There may be some drop-in replacements for this package. And we can replace `request-promise-native` with `util.promisify`.

**Comment by corbinu** [comment]
I would recommend we switch to got as it is under very active development. It does have a nice comparison of alternatives if somebody else wants to propose a different option: https://github.com/sindresorhus/got#faq

**Comment by sodatea** [comment]
We can switch to it in the next major version. But for now, we need a drop-in replacement. Because there are many CLI plugins depending on `@vue/cli-shared-utils` and I'm not sure how many of them use the `request` functionality in a non-trivial way.

**Comment by corbinu** [comment]
@sodatea No worries I didn't know there was a need to do it before the next major. I don't know of any drop in options however.

**Comment by muhammednagy** [comment]
Hey.
I will work on this one if that's alright.
It'd be my first.

**Comment by nainardev** [comment]
https://github.com/request/request/issues/3143

**Comment by jeneser** [comment]
> We can switch to it in the next major version. But for now, we need a drop-in replacement.

@sodatea  Yes! `got` is a great choice. however, if we replace it directly, not sure what side effects. PR #5572 just replace `request-promise-native` with `util.promisify`. 

I noticed a plan in project [v5](https://github.com/vuejs/vue-cli/projects/11), i'm happy to work for it. any suggestions?
