### ISSUE TITLE
cli-plugin-e2e-cypress - Wrong Base URL

### ISSUE THREAD

**Issue by fschirinzi** [vuejs/vue-cli#5221]
### Version
4.2.2

### Environment info
```
 System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Users\Francesco\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    @fortawesome/vue-fontawesome: ^0.1.6 => 0.1.6
    @panter/vue-i18next: 0.13.0 => 0.13.0
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: 3.4.0 => 3.4.0
    @vue/cli-plugin-e2e-cypress: ^4.2.2 => 4.2.2
    @vue/cli-plugin-eslint: 3.4.0 => 3.4.0
    @vue/cli-service: ^3.6.0 => 3.8.4
    @vue/cli-shared-utils:  3.8.0 (4.2.2)
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    bootstrap-vue: ^2.0.0-rc.19 => 2.0.0-rc.24
    eslint-plugin-vue:  4.7.1
    portal-vue:  2.1.5
    vue: 2.5.17 => 2.5.17
    vue-cli-webpack:  1.0.0
    vue-color: 2.7.0 => 2.7.0
    vue-eslint-parser:  2.0.3
    vue-functional-data-merge:  3.1.0
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-pagination-2:  1.6.2
    vue-resource:  0.9.3
    vue-router: 3.0.1 => 3.0.1
    vue-style-loader:  4.1.2
    vue-sweetalert2: ^2.0.5 => 2.1.0
    vue-tables-2: 1.4.70 => 1.4.70
    vue-template-compiler: 2.5.17 => 2.5.17
    vue-template-es2015-compiler:  1.9.1
    vue-text-mask: 6.1.2 => 6.1.2
    vue-toasted: 1.1.25 => 1.1.25
    vuex: 3.0.1 => 3.0.1 (2.5.0)
    vuex-persistedstate: 2.5.4 => 2.5.4
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. set in `vue.config.js` ->  { devServer:  {  public: 'http://custom-domain.local' } }
2. run `vue-cli-service test:e2e` 

### What is expected?
Cypress baseUrl is set to the public URL defined in vue.config.js OR to the baseUrl defined in `cypress.json` or `cypress.env.json`

### What is actually happening?
If plugin parameter --URL is given, the app isn't served (as expected).

Therefore I omit the URL parameter so that the app is also served. But because the URL parameter is omitted, the plugin forcefully sets the baseUrl by passing it to Cypress over the CLI command. Because the CLI has the highest priority, the  baseURL in the cypress-Env-Files is overridden.

One solution would be to serve the app normally and then start test:e2e with the url paremeter. But since hot reloading is not working for this case, I'ts not a solution either.

From Dev Server:

App running at:
  - Local:   http://localhost:8890/ 
  - Network: http://custom-domain.local/

---
2 Possible Solution from my side:

File: https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-e2e-cypress/index.js

Replace line 23-25 with:

        let url, server;

        if (args.url){
          url = args.url;
        } else {
          service = await api.service.run('serve');
          server = service.server;
          url = service.server.options.public ? service.server.options.public : service.url;
        }

OR

Add CLI parameter to forcefully server app even though the 'URL' parameter is set.

__

WORKAROUND TILL FIX (Workaround because it's hard coded):

*First why it's a workaround and not a solution:*
the `const cyArgs` equals to ...
```
[ 'open',
  '--config',
  'baseUrl=http://localhost:8890/,baseUrl=http://custom-domain.local' ]
```
... which could cause further problems in new releases.

In package.json change:

        "test:e2e": "vue-cli-service test:e2e"

TO:

        "test:e2e": "vue-cli-service test:e2e --config baseUrl=http://custom-domain.local"

**Comment by LinusBorg** [comment]
I can't really follow the "What happens instead" part as you don't describe the *effect* of the problem: what kind of error happens?

>  Because the CLI has the highest priority, the baseURL in the cypress-Env-Files is overridden.

What cypress env files? 

Which URL should it use if not the `public` one that you specified? 

Also, as per our guidelines, please provide an actual githu reporsitory with a runnable reproduction.

**Comment by fschirinzi** [comment]
Sorry for the inconvenience.

I was using different version of the CLI...which caused the behavior.

Solved.
