### ISSUE TITLE
Exclude dead browsers from browserlist

### ISSUE THREAD

**Issue by petterw03** [vuejs/vue-cli#5232]
### What problem does this feature solve?
With the current browserlist configuration (> 1%, last 2 versions), the apps are [supporting dead browsers like IE 10](https://browserl.ist/?q=%3E+1%25%2C+last+2+versions) and will keep doing that for ever after, since IE10 and IE11 will always be the last two versions of Internet Explorer.

### What does the proposed API look like?
By adding the line `not dead` to the .browserlistrc, we can rule out IE 10, and in the future when IE 11 usage drops below 0.5%, it will be gone as well.

**Comment by sodatea** [comment]
Good catch 👍
