### ISSUE TITLE
Question: is it possible to specify vue version to use at the time of installation?

### ISSUE THREAD

**Issue by franklingu** [vuejs/vue-cli#524]
I bring up this issue because of the latest vue 2.4.0 built error found [here](https://github.com/vuejs/vue/issues/6086). this is quickly fixed. However, if I know that vue 2.3.4 works, can I install vue 2.3.4 via cli?

Or can I do it with

```
npm install -g vue@2.3.4
npm instlal -g vue-cli
```

Thanks

**Comment by egoist** [comment]
sure. but it's `npm install -D vue@2.3.4` not `npm install -g vue@2.3.4`

**Comment by franklingu** [comment]
so vue-cli will use locally install vue?

**Comment by egoist** [comment]
sure
