### ISSUE TITLE
After project has created the spinner continue to rotate on header and terminal stack on "Generating README.md..."

### ISSUE THREAD

**Issue by DQvsRA** [vuejs/vue-cli#5240]
### Version
4.2.2

### Reproduction link
[https://mega.nz/#!lksyHAYB!b2t7D9X_b7dpjWLQg3Bdy6A38j0CfR2TQmrSwBqpjjk](https://mega.nz/#!lksyHAYB!b2t7D9X_b7dpjWLQg3Bdy6A38j0CfR2TQmrSwBqpjjk)

### Environment info
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 11.0.0 - ~/.nvm/versions/node/v11.0.0/bin/node
    Yarn: Not Found
    npm: 6.9.0 - ~/.nvm/versions/node/v11.0.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.122
    Firefox: Not Found
    Safari: 13.0.5
  npmPackages:
    @storybook/vue: ^5.0.3 => 5.0.3 
    vue-vimeo-player: 0.0.9 => 0.0.9 
  npmGlobalPackages:
    @vue/cli: 4.2.2
```

### Steps to reproduce
Start new project with custom settings

### What is expected?
Project setup complete

### What is actually happening?
Looks like it is not

---
Link with screenshot: https://mega.nz/#!lksyHAYB!b2t7D9X_b7dpjWLQg3Bdy6A38j0CfR2TQmrSwBqpjjk

**Comment by sodatea** [comment]
Project setup does have completed. There's a bug that we mistakenly output the log to the console, it should be shown in the UI and cleared after project creation.
