### ISSUE TITLE
Upgrade dependencies to core-js@3

### ISSUE THREAD

**Issue by DarkLite1** [vuejs/vue-cli#5257]
### Version
4.2.3

### Environment info
```
  System:
    OS: Windows Server 2016 10.0.14393
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
  Binaries:
    Node: 13.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Not Found
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
C:\> npm i -g @vue/cli

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

### What is expected?
Installation of the vue/cli without error messages or deprecation warnings.

### What is actually happening?
Deprecation warnings pop up about packages that are no longer safe to use.

**Comment by lovetingyuan** [comment]
I think these are just internal dependencies and have no negative effect on your application code. Vue cli will upgrade it's own dependencies as it's own version is updated.

**Comment by sodatea** [comment]
The `core-js` one should have been fixed with the latest release of `apollo`.
The `request` one is tracked at https://github.com/vuejs/vue-cli/issues/5220
