### ISSUE TITLE
Hot update does not work out of box

### ISSUE THREAD

**Issue by nskforward** [vuejs/vue-cli#5258]
### Version
4.2.3

### Reproduction link
[http://localhost](http://localhost)

### Environment info
```
MacOS 10.14.6
Safari 13.0.5
npm 6.13.4
```

### Steps to reproduce
1) Install Vue project:
$ vue create hello-world
$ cd hello-world
$ npm run serve

Browser window opened and I am able to see default Vue page
Added some test text to App.vue template area.
Typed Ctrl S hot key and I see message "DONE  Compiled successfully in 104ms" in the console
But browser window shows old version of app. I tried to remove browser cache, refresh page but it did not help.
This is my first Vue project, I don't have any more Vue projects. So conflicts are not possible.

### What is expected?
Changed web page

### What is actually happening?
Old web page

---
I read documentation but nothing found about force cache cleanup

**Comment by sodatea** [comment]
I've seen an odd browser bug that manually refreshing the page in Safari would result in a cached page, but even in that case, hot module replacement still works, saving the file again would trigger an update. Could you try that and see if it works?

**Comment by nskforward** [comment]
@sodatea, no it does not work. I use manual browser cache cleanup + manual page refresh = I see my update on the web page. Any other options don not work.
