### ISSUE TITLE
[Dependencies] How to remove lodash-es from final build

### ISSUE THREAD

**Issue by DQvsRA** [vuejs/vue-cli#5262]
### Version
4.2.3

### Environment info
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 11.0.0 - ~/.nvm/versions/node/v11.0.0/bin/node
    Yarn: Not Found
    npm: 6.9.0 - ~/.nvm/versions/node/v11.0.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: Not Found
    Safari: 13.0.5
  npmPackages:
    @storybook/vue: ^5.0.3 => 5.0.3 
    vue-vimeo-player: 0.0.9 => 0.0.9 
  npmGlobalPackages:
    @vue/cli: 4.2.3
```

### Steps to reproduce
1. Start new project
2. Run build task
3. Observe lodash-es in the dependencies - 493Kb

### What is expected?
No dependencies of lodash-es

### What is actually happening?
lodash-es included in the final build and takes 493Kb

---
I can't find any use of lodash-es in the app.

**Comment by sodatea** [comment]
Thanks for submitting this issue! Due to our limited time, we ask you to include a reproduction link to a minimal full reproduction of your problem (for example in a GitHub repository) so we can find what is causing the issue. Thank you for your understanding!

**Comment by DQvsRA** [comment]
Thanks for your response @sodatea, I'm not allowed to publish the private project event if it's a discovery project. But i will try to prepare separate. 
And here is a how problem is looks like (look at lodash-es, it's in dependencies):
<img width="359" alt="Screenshot 2020-03-11 at 15 40 00" src="https://user-images.githubusercontent.com/442111/76428912-97c5bf80-63ae-11ea-8c40-53bf067bb454.png">

**Comment by sodatea** [comment]
It's depended on by `vuex-orm-localforage` https://github.com/eldomagan/vuex-orm-localforage/blob/bc93d0e7a33c1d5c9ef153241137875e80b5e6da/package.json#L36

**Comment by DQvsRA** [comment]
Thanks a lot @sodatea!
