### ISSUE TITLE
Module not found: Error: Can't resolve '@vue/cli-plugin-typescript/generator/convert'

### ISSUE THREAD

**Issue by hamzaehsan95** [vuejs/vue-cli#5263]
### Version
4.2.3

### Reproduction link
[https://github.com/hamzaehsan95/testing-project.git](https://github.com/hamzaehsan95/testing-project.git)

### Environment info
```
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: Not Found
    Safari: 13.0.4
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.2.3 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.2.3 
    @vue/cli-plugin-babel: ~4.2.0 => 4.2.3 
    @vue/cli-plugin-eslint: ~4.2.0 => 4.2.3 
    @vue/cli-plugin-router:  4.2.3 
    @vue/cli-plugin-vuex:  4.2.3 
    @vue/cli-service: ~4.2.0 => 4.2.3 
    @vue/cli-shared-utils:  4.2.3 
    @vue/component-compiler-utils:  3.1.1 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.1.2 => 6.2.2 
    nativescript-vue: ^2.5.0-alpha.3 => 2.5.0 
    nativescript-vue-template-compiler: ^2.5.0-alpha.3 => 2.5.0 
    vue: ^2.6.11 => 2.6.11 
    vue-cli-plugin-nativescript-vue: ~0.3.1 => 0.3.1 
    vue-eslint-parser:  7.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.2.3
```

### Steps to reproduce
1. Please do yarn install.
2. Then tns run android 
OR 
tns run ios --emulator

### What is expected?
The app should run

### What is actually happening?
Throwing following errors.

ERROR in ../node_modules/@vue/cli-plugin-router/generator/index.js
Module not found: Error: Can't resolve '@vue/cli-plugin-typescript/generator/convert' in '/Users/hamza/VueProjects/testing-project/node_modules/@vue/cli-plugin-router/generator'
 @ ../node_modules/@vue/cli-plugin-router/generator/index.js 18:25-80
 @ ./router.js
 @ . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|kt|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$
 @ ./main.native.js

ERROR in ./App.vue?vue&type=style&index=0&web=true&lang=css& (../node_modules/nativescript-dev-webpack/style-hot-loader.js!../node_modules/nativescript-dev-webpack/apply-css-loader.js!../node_modules/css-loader/dist/cjs.js??ref--3-2!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/vue-loader/lib??vue-loader-options!./App.vue?vue&type=style&index=0&web=true&lang=css&)
Module not found: Error: Can't resolve 'styles/style-one' in '/Users/hamza/VueProjects/testing-project/src'
 @ ./App.vue?vue&type=style&index=0&web=true&lang=css& (../node_modules/nativescript-dev-webpack/style-hot-loader.js!../node_modules/nativescript-dev-webpack/apply-css-loader.js!../node_modules/css-loader/dist/cjs.js??ref--3-2!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/vue-loader/lib??vue-loader-options!./App.vue?vue&type=style&index=0&web=true&lang=css&) 3:40-118
 @ ./App.vue?vue&type=style&index=0&web=true&lang=css&
 @ ./App.vue
 @ ./main.native.js

ERROR in ./App.vue?vue&type=style&index=1&native=true&lang=css& (../node_modules/nativescript-dev-webpack/style-hot-loader.js!../node_modules/nativescript-dev-webpack/apply-css-loader.js!../node_modules/css-loader/dist/cjs.js??ref--3-2!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/vue-loader/lib??vue-loader-options!./App.vue?vue&type=style&index=1&native=true&lang=css&)
Module not found: Error: Can't resolve 'styles/style-one' in '/Users/hamza/VueProjects/testing-project/src'
 @ ./App.vue?vue&type=style&index=1&native=true&lang=css& (../node_modules/nativescript-dev-webpack/style-hot-loader.js!../node_modules/nativescript-dev-webpack/apply-css-loader.js!../node_modules/css-loader/dist/cjs.js??ref--3-2!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/vue-loader/lib??vue-loader-options!./App.vue?vue&type=style&index=1&native=true&lang=css&) 3:40-118
 @ ./App.vue?vue&type=style&index=1&native=true&lang=css&
 @ ./App.vue
 @ ./main.native.js

**Comment by LinusBorg** [comment]
This is very likely related to vue-cli-plugin-nativescript-vue, which somehow overrode the router.js file with some code that's means to be part of the cli plugin, not the app.

https://github.com/hamzaehsan95/testing-project/blob/master/src/router.js

Please open an issue in their repo.
