### ISSUE TITLE
Does vue-cli have a special optimization for sourceMap generation?

### ISSUE THREAD

**Issue by shen-zhao** [vuejs/vue-cli#5276]
### Version
4.2.3
### Environment info
```
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
    Yarn: Not Found
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.2/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 72.0.2
    Safari: 13.0.4
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx: ^1.1.2 => 1.1.2
    @vue/component-compiler:  4.2.0
    @vue/component-compiler-utils:  3.1.0
    babel-helper-vue-jsx-merge-props:  2.0.3
    eslint-plugin-vue: ^6.0.1 => 6.0.1
    rollup-plugin-vue: ^5.1.4 => 5.1.4
    rollup-plugin-vue-inline-svg: ^1.0.1 => 1.0.1
    typescript:  2.9.2
    vue: ^2.6.11 => 2.6.11
    vue-eslint-parser:  6.0.5
    vue-runtime-helpers:  1.1.2
    vue-template-compiler:  2.6.11
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: 4.2.3
```

### Steps to reproduce
I have a npm private package with the file name esm.vue.js. My build time is 200s. When I change the file name to esm.v.js (there is no .vue in front of the extension), the build time is about 50s. When I modify the cli internal code to print out the log log, I see the build process stick at when generate a SourceMap of vendors chunk, you may think that my vendors file is big, it is, but the speed of building after I modify the file name is normal, I am very confused now

### What is expected?
Does vue-cli have a special optimization for sourceMap generation? And is it matched by file name(like `/\.vue/`)?

### What is actually happening?
when the name of my npm private package is esm.vue.js. the build process stick at when generate a SourceMap of vendors chunk, Causes build time is too long

**Comment by sodatea** [comment]
See: https://github.com/vuejs/vue-cli/issues/1889#issuecomment-406078216
