### ISSUE TITLE
How about use @babel/preset-typescript to replace ts-loader?

### ISSUE THREAD

**Issue by lovetingyuan** [vuejs/vue-cli#5278]
### What problem does this feature solve?
I think it should be a little faster than using both babel-loader and ts-loader.

### What does the proposed API look like?
Just remove ts-loader and add @babel/preset-typescript to @vue/babel-preset-app when the project is using typescript. That is what CRA did.

**Comment by sodatea** [comment]
See https://babeljs.io/docs/en/babel-plugin-transform-typescript#caveats

The babel preset lacks many features compared to the official typescript compiler. So we won't do this by default. But feel free to implement a third-party Vue CLI plugin for it.
