### ISSUE TITLE
npm install for production

### ISSUE THREAD

**Issue by luguosheng1314** [vuejs/vue-cli#528]
How to ignore the contents of the installation devDependencies while publishing the production package, and I try to use NPM install --production, but it will be reported wrong。

**Comment by luguosheng1314** [comment]
npm install --production  and then  npm run build,  it will be reported wrong

**Comment by posva** [comment]
that command is more useful with node programs than with front end apps because front end usually need a build step.
Closing because this is unrelated to vue-cli
