### ISSUE TITLE
vue-cli-service build 执行时卡住

### ISSUE THREAD

**Issue by blueskink** [vuejs/vue-cli#5286]
### Version
4.2.3

### Environment info
```
vue info 同样无法执行
环境： docker 容器
```
Linux 3c44b9dfd301 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 GNU/Linux

google-chrome --version
Chromium 64.0.3282.119 built on Debian 9.3, running on Debian 9.4
```
```

### Steps to reproduce
执行“npm run build”

### What is expected?
正常执行

### What is actually happening?
```
root@3c44b9dfd301:/source# npm run build

> sample@0.1.0 build /source
> vue-cli-service build
卡在此处
```

---
###问题定位：
因为在问题环境下“google-chrome --version”命令卡住（原因未知），导致“browsers.chrome = getLinuxAppVersion('google-chrome')”代码执行永久性阻塞。最终表现为所述问题。
```
root@3c44b9dfd301:/source# google-chrome --version                                                 
Chromium 64.0.3282.119 built on Debian 9.3, running on Debian 9.4
卡在此处，不退出
```

**Comment by sodatea** [comment]
但是这个为什么会影响 build？
`installedBrowsers` 只在运行 `test:e2e` 或者创建项目时才用到啊……

**Comment by blueskink** [comment]
导出时就检测了，不是用的时候才检测的。

**Comment by sodatea** [comment]
明白了，是这行代码触发了 getter https://github.com/vuejs/vue-cli/blob/5b1709abf010413b2f0b3d1a94ebb9577218c051/packages/%40vue/cli-shared-utils/index.js#L16
