### ISSUE TITLE
installing vue cli i got this type of error ?

### ISSUE THREAD

**Issue by jagasan** [vuejs/vue-cli#529]
`~$ npm install -g vue-cli
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bn.js@^4.1.1 (node_modules/vue-cli/node_modules/browserify-sign/node_modules/bn.js):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Failed to parse json
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No data, empty input at 1:1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ^
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: File: /home/jack/.npm/bn.js/4.11.7/package/package.json
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: parse-asn1@^5.0.0 (node_modules/vue-cli/node_modules/browserify-sign/node_modules/parse-asn1):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Failed to parse json
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No data, empty input at 1:1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ^
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: File: /home/jack/.npm/parse-asn1/5.1.0/package/package.json
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: elliptic@^6.0.0 (node_modules/vue-cli/node_modules/browserify-sign/node_modules/elliptic):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Failed to parse json
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No data, empty input at 1:1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ^
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: File: /home/jack/.npm/elliptic/6.4.0/package/package.json
npm ERR! Linux 4.8.0-58-generic
npm ERR! argv "/home/jack/node-v6.11.1-linux-x64/bin/node" "/home/jack/node-v6.11.1-linux-x64/bin/npm" "install" "-g" "vue-cli"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! file /home/jack/.npm/browserify-rsa/4.0.1/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /home/jack/.npm/browserify-rsa/4.0.1/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jack/npm-debug.log`

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
