### ISSUE TITLE
vue-cli3 使用lib模式打包公共代码vue.js 被自动external

### ISSUE THREAD

**Issue by cqupt-yifanwu** [vuejs/vue-cli#5298]
### Version
4.2.2

### Reproduction link
null

### Environment info
```
macos
```

### Steps to reproduce
vue-cli-service build --target lib --name zyThirdVendors common/index.js --no-clean

### What is expected?
使用lib默认打包公共部分代码时可以将vue.js打包进去

### What is actually happening?
其他依赖可以正常打包，vue.js输出undefined

---
主动将vue.config.js 中external配置制空不起作用

**Comment by sodatea** [comment]
https://cli.vuejs.org/zh/guide/build-targets.html#%E5%BA%93
有个 `--inline-vue` 选项可以用

**Comment by seafronthu** [comment]
为什么我用lib模式会把 vue打包进去

**Comment by cqupt-yifanwu** [comment]
> 为什么我用lib模式会把 vue打包进去

--inline-vue
