### ISSUE TITLE
npm run build hangs around 50%

### ISSUE THREAD

**Issue by TheDutchCoder** [vuejs/vue-cli#53]
Not sure what's going on, but whenever I build my code, it hangs at around 50%.
Is there a way to make the build process output anything, so I can see where it halts?

**Comment by chrisvfritz** [comment]
@TheDutchCoder You can configure Webpack's output in the `build` script in `package.json` to show more details. In particular, you may find these options helpful:

```
--display-exclude
--display-modules
--display-chunks
--display-error-details
--display-origins
--display-cached
--display-cached-assets
--display-reasons, --verbose, -v
```

See [Webpack's _Display options_ docs](https://webpack.github.io/docs/cli.html#display-options) for more info.

**Comment by chrisvfritz** [comment]
Closing pending more information from @TheDutchCoder or someone else that can reproduce this with more information.
