### ISSUE TITLE
npm install -g vue-cli failed

### ISSUE THREAD

**Issue by oppee** [vuejs/vue-cli#530]
install vue-cli fialed, error msg:  
"
npm ERR! Unexpected end of input at 1:19108
npm ERR! 85ee90a76dbf346","tarball":"https://registry.npmjs.org/ajv/-/ajv-0.4.
npm ERR!  
"  
what to do to solve this ?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

I really don't know where that's coming from, I mean apparently the ajv package messed up something but it doesn't look related to vue-cli
