### ISSUE TITLE
npm-run-script  doesn`t working properly

### ISSUE THREAD

**Issue by cench** [vuejs/vue-cli#5302]
### Version
4.0.0

### Environment info
```
mac os && Linux
```

### Steps to reproduce
Dynamic parameter passing to packaging script is needed in the project。

npm run script -- version=xxx

https://docs.npmjs.com/cli-commands/run-script.html

1、package.json script, "build": "vue-cli-service build"

2、npm run build -- version=xxx.xx

3、Entry module not found: Error: Can't resolve  /../path/version=xxx.xx

### What is expected?
want to use `process.argv` to get the parameter through parameter passing

### What is actually happening?
build failure.

**Comment by sodatea** [comment]
The script does work properly.
You ran `npm run build -- version=xxx.xx` so the build command was `vue-cli-service build version=xxx.xx`. That command runs this script underlyingly https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/build/index.js It takes `version=xxx.xx` as the `entry` argument. Of course it failed.
