### ISSUE TITLE
How to set proxy for `vue add` command?

### ISSUE THREAD

**Issue by krave1986** [vuejs/vue-cli#5313]
### What problem does this feature solve?
My development environment requires to install everything via proxy.
If I need to add a new plugin, I have to run `vue add unit-jest`.
But it seems that add command also needs to go through a proxy.
How can I set a proxy for vue add command?

### What does the proposed API look like?
vue add unit-jest --proxy=1.2.3.4:5678

**Comment by sodatea** [comment]
`vue add` runs `npm install` or `yarn add` underlyingly. According to the npm documentation:

> If the HTTPS_PROXY or https_proxy or HTTP_PROXY or http_proxy environment variables are set, proxy settings will be honored by the underlying request library.

**Comment by krave1986** [comment]
In fact, I've tried setting environment variables in PowerShell like:
`$env:HTTPS_PROXY="http://1.2.3.4:5678"`
But no luck, it doesn't work for me either.

On the other side, with npm proxy set, vue create work smoothly without a problem.
