### ISSUE TITLE
vue-cli使用less出错：This relative module was not found

### ISSUE THREAD

**Issue by ytftianwen** [vuejs/vue-cli#532]
项目结构是：
### - components
        -index.js
        -style.less
        -template.html
  ### -router
  ### -App.vue
  ### -main.js

使用vue-cli脚手架，想把.vue单文件改成html+js+less形式进行架构的组建，webpack.base.conf.js中less-loader的配置是：
`**{
        test: /\.less$/,
        loader: 'style-loader!css-loader!less-loader'
      },**`
js引入.less文件是：
`**import './style.less'**
`
在使用less时出现了如下问题：
`$ npm run dev

> music@1.0.0 dev D:\work\project\demo\music
> node build/dev-server.js

> Starting dev server...
 ERROR  Failed to compile with 1 errors16:39:26

This relative module was not found:

* ./style.less in ./src/components/index.js
> Listening at http://localhost:8080
`
请问如何解决

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

It's telling you the file `./style.less` is not there. You may need a different path
