### ISSUE TITLE
 how to vue-cli in Multiple pages application?

### ISSUE THREAD

**Issue by baixiyang** [vuejs/vue-cli#533]

**Comment by baixiyang** [comment]
how to vue-cli in Multiple pages application

**Comment by egoist** [comment]
This is actually a webpack topic. 🙂 Ask it on stackoverflow or forums.

**Comment by baixiyang** [comment]
i just wish vue-cli support Multiple pages

**Comment by egoist** [comment]
@baixiyang I guess you mean the webpack template not vue-cli
