### ISSUE TITLE
vue ui project creation failed

### ISSUE THREAD

**Issue by surapuramakhil** [vuejs/vue-cli#5333]
Version
4.2.3

Environment info

Environment Info:

  System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.2.3 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.2.3 
    @vue/cli-plugin-babel: ~4.2.0 => 4.2.3 
    @vue/cli-plugin-e2e-cypress: ~4.2.0 => 4.2.3 
    @vue/cli-plugin-eslint: ~4.2.0 => 4.2.3 
    @vue/cli-plugin-pwa: ~4.2.0 => 4.2.3 
    @vue/cli-plugin-router: ~4.2.0 => 4.2.3 
    @vue/cli-plugin-typescript: ~4.2.0 => 4.2.3 
    @vue/cli-plugin-unit-mocha: ~4.2.0 => 4.2.3 
    @vue/cli-plugin-vuex:  4.2.3 
    @vue/cli-service: ~4.2.0 => 4.2.3 
    @vue/cli-shared-utils:  4.2.3 
    @vue/component-compiler-utils:  3.1.1 
    @vue/eslint-config-typescript: ^5.0.1 => 5.0.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/test-utils: 1.0.0-beta.31 => 1.0.0-beta.31 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.1.2 => 6.2.2 
    typescript: ~3.7.5 => 3.7.5 
    vue: ^2.6.11 => 2.6.11 
    vue-class-component: ^7.2.2 => 7.2.3 
    vue-eslint-parser:  7.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.1 
    vue-property-decorator: ^8.3.0 => 8.4.1 
    vue-router: ^3.1.5 => 3.1.6 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.2.3
Steps to reproduce
Use Vui Ui. create Project -> presets [Manual] -> features [babel , typescript , pwa , router , link formatter , test , e2e -> configs -> createProject

What is expected?
without error, Not to get stuck in project creation UI

What is actually happening?
Got Error for vue ui server 📄 Generating README.md... Error: NO_MODULES at importProject (/usr/local/lib/nodemodules/@vue/cli/nodemodules/@vue/cli-ui/apollo-server/connectors/projects.js: 363:11) at progress.wrap (/usr/local/lib/nodemodules/@vue/cli/nodemodules/@vue/cli-ui/apollo-server/connectors/projects.js: 355:12) at at process.tickCallback (internal/process/nexttick.js:188:7)

In UI pop came as a project created successfully, by a still project created/installation window. a bit confused is project creation happened fully for broke abrupt in middle

**Comment by sodatea** [comment]
Check your environment variables. If `NODE_ENV` is set to `production`, please unset it.
