### ISSUE TITLE
build --target lib fails on newly created project

### ISSUE THREAD

**Issue by jonasfh** [vuejs/vue-cli#5336]
### Version
4.2.3

### Reproduction link
[https://github.com/jonasfh/vueissue](https://github.com/jonasfh/vueissue)

### Environment info
```
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 74.0
    Safari: 13.0.5
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.2.3
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.2.3
    @vue/cli-plugin-babel: ~4.2.0 => 4.2.3
    @vue/cli-plugin-eslint: ~4.2.0 => 4.2.3
    @vue/cli-plugin-router:  4.2.3
    @vue/cli-plugin-vuex:  4.2.3
    @vue/cli-service: ~4.2.0 => 4.2.3
    @vue/cli-shared-utils:  4.2.3
    @vue/component-compiler-utils:  3.1.1
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.1.2 => 6.2.2
    vue: ^2.6.11 => 2.6.11
    vue-eslint-parser:  7.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: 4.2.3
```

### Steps to reproduce
Create a pristine vue project: 

```
vue create vuetest
cd vuetest
npm run build --target lib
```

Also tried different options: 

```
npm run build --target lib --inline-vue # inlining the vue library
npm run build --target lib --name myLib src/main.js # Specifying entrypoint
```

All fails with the same result. 

Default builds works as expected: 

`npm run build # This works as expected` 

### What is expected?
Expected the project to be built as a library, as specified in the docs: https://cli.vuejs.org/guide/build-targets.html#library

### What is actually happening?
Build fails with the following output: 

> vuetest@0.1.0 build /Users/jhe052/dev/vuetest
> vue-cli-service build "lib"

> ⠸  Building for production...

> ERROR  Failed to compile with 1 errors                                                                                     > 12:46:59 AM

> error

> Entry module not found: Error: Can't resolve '/Users/jhe052/dev/vuetest/lib' in '/Users/jhe052/dev/vuetest'

> ERROR  Build failed with errors.

> npm ERR! code ELIFECYCLE

> npm ERR! errno 1

> npm ERR! vuetest@0.1.0 build: `vue-cli-service build "lib"`

> npm ERR! Exit status 1

> npm ERR!

> npm ERR! Failed at the vuetest@0.1.0 build script.

> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> npm ERR! A complete log of this run can be found in:

> npm ERR!     /Users/jhe052/.npm/_logs/2020-03-29T22_46_59_854Z-debug.log

---
Tried building a really simple project. As that did not work, I tried building the project as created by default by vue create. Seems to me this should, but unfortunately not, and the only place I found someone asked on so, no-one has answered.

**Comment by sodatea** [comment]
> npm ERR! vuetest@0.1.0 build: vue-cli-service build "lib"

This line means the `--target` argument failed to be passed to the `vue-cli-service` command.

It is because to pass arguments to an npm script, there must be a `--` separator between the script name and the argument list. See the npm documentation: https://docs.npmjs.com/cli/run-script
