### ISSUE TITLE
How to open the webpack  --progress --profile in vue-cli-service scripts?

### ISSUE THREAD

**Issue by gottayan** [vuejs/vue-cli#5337]
"build": "vue-cli-service build ",
    "build-dll": "webpack --config build/webpack.dll.config.js --mode production --progress --profile",
can I set the script of build with  --progress --profile like webpack?

**Comment by jinceon** [comment]
npx webpack --mode production --config ./node_modules/@vue/cli-service/webpack.config.js  --profile --json > stats.json

有了./node_modules/@vue/cli-service/webpack.config.js，就可以直接使用webpack了
