### ISSUE TITLE
How to add less plugin for single vue component file

### ISSUE THREAD

**Issue by bq-hentai** [vuejs/vue-cli#534]
I use `vue-cli` to generate my project. And I use `less`. I need to use a less plugin. But error occurred.
`Plugin.install is not a function`. 

I noticed that `less-loader` use `loader-utils` to get `options`. And in `loader-utils`, the query is a string like this ` ?{"plugins":[{}],"sourceMap":false}`. So the loader can't get the correct plugin instance (the install function is in the prototype object).

I found that if I use `use` option, the query is an object. I am not familiar to webpack. So how can I fix this.

[similar ref](https://github.com/webpack-contrib/less-loader/issues/200)

P.S. less-loader v4.0.1 not [this bug](https://github.com/webpack-contrib/less-loader/issues/181)

**Comment by posva** [comment]
I suggest you to ask your question on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

I think this is more related to vue-loader
