### ISSUE TITLE
error while installing vue-cli globally

### ISSUE THREAD

**Issue by surajrathod** [vuejs/vue-cli#535]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: postcss@6.0.8 (node_modules\vue-cli\node_modules\postcss-modules-scope\node_modules\postcss):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\suraj\AppData\Roaming\npm\node_modules\.staging\postcss-00ec8050\lib\parser.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: browserify-rsa@4.0.1 (node_modules\vue-cli\node_modules\browserify-rsa):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\suraj\AppData\Roaming\npm\node_modules\.staging\browserify-rsa-f26350c4\test.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: postcss@6.0.8 (node_modules\vue-cli\node_modules\postcss-modules-values\node_modules\postcss):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\suraj\AppData\Roaming\npm\node_modules\.staging\postcss-921aa32a\docs\source-maps.md'

npm ERR! code EINTEGRITY
npm ERR! sha1-0+MQtA72ZKNmIiAAl8bUQCmPK/4= integrity checksum failed when using sha1: wanted sha1-0+MQtA72ZKNmIiAAl8bUQCmPK/4= but got sha1-d8JMvIyTzHBntAjegyCCQhh/J1I=. (2238 bytes)

**Comment by posva** [comment]
You seem to have an integrity error but this is unrelated to vue-cli
