### ISSUE TITLE
Error during vue init in _stream_transform.js

### ISSUE THREAD

**Issue by Eilie** [vuejs/vue-cli#536]
Hello,

Trying to initialize new Vuejs project but I'm getting following result:
```
$ vue init webpack my-project
                     
⠼ downloading template
/.../node_modules/readable-stream/lib/_stream_transform.js:159
  throw new Error('not implemented');
```

**Comment by Eilie** [comment]
Vue cli version is 2.8.2.

**Comment by Eilie** [comment]
Also for some reason installing vue-cli wasn't enough and I had to additionally install process-nextick-args and buffer-shims because vue-cli complained about those packages as missing.

**Comment by posva** [comment]
This is not enough information...
Are you using at least node 6?

**Comment by Eilie** [comment]
@posva Using node v8.2.1.

**Comment by posva** [comment]
I tried with that version and it works nicely
Make sure your installation is right and that you're also using the last version of npm

Searching for the error on google says that you need to clean your node_modules (in this case, that would be the [global node_modules](https://stackoverflow.com/questions/5926672/where-does-npm-install-packages)
