### ISSUE TITLE
create so slowly in china? can i replace 'yarn' with cnpm?

### ISSUE THREAD

**Issue by skykingit** [vuejs/vue-cli#5364]
### What problem does this feature solve?
when i create new project in china ,it is very slowly when "Installing CLI plugins. This might take a while..." with yarn
i think you  can make a feature which let user use cnpm ,so the speed will faster

### What does the proposed API look like?
vue create newProjectName  --cnpm

**Comment by sodatea** [comment]
`vue config --set useTaobaoRegistry true`
