### ISSUE TITLE
cli生成的public目录不正确

### ISSUE THREAD

**Issue by tansuo1989** [vuejs/vue-cli#5365]
### Version
4.3.0

### Environment info
```
Environment Info:

  System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 10.14.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.7.0 - E:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - D:\Program Files\nodejs\npm.CMD
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
@vue/cli 4.3 运行：
vue create test
后，生成的目录中的 public在项目根目录下，但实测应该放到 src 目录下才是正确的

### What is expected?
111

### What is actually happening?
111

**Comment by sodatea** [comment]
public 目录里是静态资源文件，除了 HTML 外都不会过编译，放在根目录下是正确的。

**Comment by sodatea** [comment]
https://cli.vuejs.org/zh/guide/html-and-static-assets.html#public-%E6%96%87%E4%BB%B6%E5%A4%B9
