### ISSUE TITLE
New project built by vue - cli, which can be started after npm run dev, but the hot update can go wrong, please?

### ISSUE THREAD

**Issue by Fridolph** [vuejs/vue-cli#537]
When I save, the console will report the error ,  
`
F:\WSKP\edr3_dev\node_modules/enhanced-resolve\lib\CacheInputFilesSystem.js:145  
if (key.startsWith(what))

**TypeError: cannot read property 'startsWith' of undefined**
`

---

I guess it might be the package version of the problem. 
When I installed the `enhanced-resolve@3.2.0` package, the hot update problem was solved

---

I hope you can see and fix the `enhanced-resolve@3.4.0` problem,  Good luck with your work

**Comment by palmerye** [comment]
This problem has been resolved in the latest version of enhanced-resolve@3.4.1,
you can do this:
`npm install enhanced-resolve@latest`

**Comment by Fridolph** [comment]
@palmerye  Thank you for your reply. The problem has been solved
---

vue官方的效率真不是盖的。。…… 

ps博客很漂亮 已star~ 以后多多指教

**Comment by palmerye** [comment]
@Fridolph Thanks! :)
