### ISSUE TITLE
sockPath, sockPort, sockHost are ignored (regression from #5069)

### ISSUE THREAD

**Issue by nemoneph** [vuejs/vue-cli#5372]
### Version
4.3.1

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.19 Alpine Linux
    CPU: (4) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.3.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.3.1 
    @vue/cli-plugin-babel: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-eslint: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-router:  4.3.1 
    @vue/cli-plugin-vuex:  4.3.1 
    @vue/cli-service: ~4.3.0 => 4.3.1 
    @vue/cli-shared-utils:  4.3.1 
    @vue/component-compiler-utils:  3.1.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.1.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.11 
    vue-eslint-parser:  7.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
Hello,
In my application I have a subpath:
http://my-app/my-path/

So I use sockPath   sockHost in my vue.config.js.

```
module.exports = {
	publicPath: '/my-path/',
	devServer: {
		sockPath: '/my-path/sockjs-node',
		disableHostCheck: true,
		sockPort: '443',
		port: 80,
		host: '0.0.0.0',
		watchOptions: {
			aggregateTimeout: 300,
			poll: true,
			ignored: /node_modules/
		}
	}
}
```

### What is expected?
sockPath, sockHost and sockPort are ignored 

### What is actually happening?
With vue/cli-service 4.1.2 it's working 
With 4.2.0 it's not working anymore.

It's due to this change:  https://github.com/vuejs/vue-cli/pull/5069

Maybe by default, the sockPath can be the publicPath ?

**Comment by sraillard** [comment]
When working with subPath, I think the `devServer.sockPath` can be ajusted automatically based on the `publicPath` value already configured. And if needed, the `devServer.sockPath` can still be ovlerloaded.

**Comment by bompus** [comment]
Possibly related to #4400

**Comment by sraillard** [comment]
Seems to be fixed in 4.4.1

**Comment by McPo** [comment]
Still appears to be an issue for me.

This is my current config
```
module.exports = {
  publicPath: '/ui/',
  devServer: {
    publicPath: '/',
    /*
      Currently broken due to a regession
      https://github.com/vuejs/vue-cli/issues/5372
    */
    // sockPath: '/ui/sockjs-node',
    disableHostCheck: true,
    headers: {
      'Vary': '*' // Required to prevent caching on safari
    }
  }
}
```

In the previous version it was attempting to reach `/sockjs-node` instead of `/ui/sockjs-node, even with sockPath defined. In the latest version there has been no change.

Gonna continue to play around with it to see if I can get a fix

**Comment by sraillard** [comment]
This is working for me:
```
module.exports = {
  publicPath: '/SUBPATH',
  devServer: {
    public: 'MY_HOSTNAME',
    sockPath: '/SUBPATH/sockjs-node',
    port: 80,
    watchOptions: {
      poll: true,
      ignored: '/node_modules/'
    }
  }
}
```
Don't forget the `vue upgrade` to upgrade all the project libraries.

**Comment by nemoneph** [comment]
I confirm that  #4800 fixed my issue. (release 4.4.0)
Thx

**Comment by daneren2005** [comment]
To add another weird part of it is if you add a port to the `public` config it won't work.  You HAVE to put `127.0.0.1` and not `127.0.0.1:8000`.  This is weird because in https://webpack.js.org/configuration/dev-server/#devserverpublic it seems like it supposed to include the port and not just be the host.

**Comment by tomklino** [comment]
sockHost is still being ignored

**Comment by gdevdeiv** [comment]
Hi there, I ran into this issue today. What's the current issue status?

I'm running:
- "@vue/cli": "^4.5.11"
- "@vue/cli-plugin-babel": "~4.5.11"
- "@vue/cli-plugin-eslint": "~4.5.11"
- "@vue/cli-service": "~4.5.11"
