### ISSUE TITLE
Can't install vue-cli (Ubuntu 18.04 running in a Docker container)

### ISSUE THREAD

**Issue by luistm** [vuejs/vue-cli#5377]
### Version
4.3.1

### Reproduction link
[https://gist.github.com/luistm/13f01e5cddab501f4ac76c69b19a948f](https://gist.github.com/luistm/13f01e5cddab501f4ac76c69b19a948f)

### Environment info
```
root@635321fddea8:~# vue info
bash: vue: command not found
```

### Steps to reproduce
```bash
docker run -it ubuntu:18.04 /bin/bash
```
Next, inside the container
```bash
apt update
apt install curl
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
source ~/.bashrc
# Installs node v12.16.2
nvm install --lts 
npm install -g @vue/cli
```

### What is expected?
I expect vue-cli to be installed

### What is actually happening?
Installation finishes with an error:

npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! core-js@2.6.11 postinstall: `node -e "try{require('./postinstall')}catch(e){}"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the core-js@2.6.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-11T09_51_22_986Z-debug.log

---
This form does not allow me to submit a bug without choosing a Version. I choose 4.3.1, but only because the form required it. I don't know if that is correct.

**Comment by sodatea** [comment]
I'm not sure if it's the actual problem, but it's a bad practice to use `root` user in such docker containers.

- The official documentation of docker-node recommends using a non-root user: https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#non-root-user
- The official `nvm` docker image uses a non-root user https://github.com/nvm-sh/nvm/blob/master/Dockerfile
- There are various comments from the maintainers of `nvm` in the issue threads that discourage usage with root privileges.

**Comment by luistm** [comment]
Hi,

I'm not producing a system intended to be used in a production environment, therefore, I don't care much about it is using root or not. I was just doing an experiment and ended up finding this problem. But I can work around this issue. It's not really a blocker for me. 

Thanks

**Comment by sodatea** [comment]
Even for development usage, it's not recommended to use the root user.
`postinstall` scripts often fail when executed as `root` in `npm`.

See https://cli.vuejs.org/guide/troubleshooting.html#running-installation-with-sudo-or-as-root
