### ISSUE TITLE
无法定位外部引入.js 文件里面的对象undefined错误；

### ISSUE THREAD

**Issue by pangxieju** [vuejs/vue-cli#538]
.vue文件里面引入.js文件；.js文件里面对象undefined，浏览区控制台不提示错误信息，用try catch 错误正常；
把.js文件代码拷贝到.vue文件里面错误正常。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is also unrelated to vue-cli
