### ISSUE TITLE
webpck-cdn-plugin@3.3.1 can't use

### ISSUE THREAD

**Issue by pillarBoy** [vuejs/vue-cli#5385]
### Version
4.3.1

### Reproduction link
[https://github.com/pillarBoy/vue-cdn-error](https://github.com/pillarBoy/vue-cdn-error)

### Environment info
```
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 74.0
    Safari: 13.0.5
  npmGlobalPackages:
    @vue/cli: 4.3.1
```

### Steps to reproduce
step1: yarn

step2: yarn serve

### What is expected?
I hope this service can start normally.

### What is actually happening?
vue-cli-service service can not work.
It stopped at [ Starting development server ]

---
if I remove webpck-cdn-plugin in vue.config.js [configureWebpack]. It works normally.

And I use webpck-cdn-plugin in webpack.config.js project，it works without any problem.

if this bug can be fixed, thank you very much. 谢谢

**Comment by pillarBoy** [comment]
我写错配置了，修改之后，就可以执行了

**Comment by LinusBorg** [comment]
Vue CLI's webpack config already uses HTMLWebpackPlugin. You should not add another instance of that plugin.

Rather, alter the existing plugin's options

https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-plugin
