### ISSUE TITLE
Build failed Travis (Cannot find babel module)

### ISSUE THREAD

**Issue by nleborgne** [vuejs/vue-cli#5398]
### Version
4.3.1

### Reproduction link
[https://github.com/nleborgne/nCov](https://github.com/nleborgne/nCov)

### Environment info
```
  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 12.16.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: Not Found
    Safari: 13.0.4
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.2.3 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.2.3 
    @vue/cli-plugin-babel: ~4.2.0 => 4.2.3 
    @vue/cli-plugin-eslint: ~4.2.0 => 4.2.3 
    @vue/cli-plugin-router:  4.2.3 
    @vue/cli-plugin-vuex:  4.2.3 
    @vue/cli-service: ~4.2.0 => 4.2.3 
    @vue/cli-shared-utils:  4.2.3 
    @vue/component-compiler-utils:  3.1.1 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    bootstrap-vue: ^2.11.0 => 2.11.0 
    eslint-plugin-vue: ^6.1.2 => 6.2.2 
    portal-vue:  2.1.7 
    vue: ^2.6.11 => 2.6.11 
    vue-axios: ^2.1.5 => 2.1.5 
    vue-chartjs: ^3.5.0 => 3.5.0 
    vue-class-component:  7.2.3 
    vue-data-tables: ^3.4.5 => 3.4.5 
    vue-eslint-parser:  7.0.0 
    vue-functional-data-merge:  3.1.0 
    vue-graph: ^0.8.7 => 0.8.7 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.0 
    vue-loading-overlay: ^3.3.2 => 3.3.2 
    vue-property-decorator:  8.4.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuejs-datatable: ^2.0.0-alpha.7 => 2.0.0-alpha.7 
  npmGlobalPackages:
    @vue/cli: 4.3.1
```

### Steps to reproduce
- Clone Repo
- Change travis.yml configuration
- Go to travis-ci.org
- Select repo

### What is expected?
We expect the build to be completed without any error.

### What is actually happening?
The following error and the build fails :

> vue-cli-service build
-  Building for production...
 ERROR  Failed to compile with 1 errors10:22:12 AM
 error  in ./src/main.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
[BABEL] /home/travis/build/nleborgne/nCov/src/main.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/travis/build/nleborgne/nCov/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/travis/build/nleborgne/nCov/node_modules/@babel/preset-env/lib/index.js
- /home/travis/build/nleborgne/nCov/node_modules/@vue/babel-preset-app/index.js
- /home/travis/build/nleborgne/nCov/node_modules/@vue/cli-plugin-babel/preset.js
- /home/travis/build/nleborgne/nCov/node_modules/@babel/core/lib/config/files/plugins.js
- /home/travis/build/nleborgne/nCov/node_modules/@babel/core/lib/config/files/index.js
- /home/travis/build/nleborgne/nCov/node_modules/@babel/core/lib/index.js
- /home/travis/build/nleborgne/nCov/node_modules/babel-loader/lib/index.js
- /home/travis/build/nleborgne/nCov/node_modules/loader-runner/lib/loadLoader.js
- /home/travis/build/nleborgne/nCov/node_modules/loader-runner/lib/LoaderRunner.js
- /home/travis/build/nleborgne/nCov/node_modules/thread-loader/dist/worker.js (While processing: "/home/travis/build/nleborgne/nCov/node_modules/@vue/cli-plugin-babel/preset.js")
    at PoolWorker.fromErrorObj (/home/travis/build/nleborgne/nCov/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /home/travis/build/nleborgne/nCov/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Module.require (internal/modules/cjs/loader.js:1012:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/travis/build/nleborgne/nCov/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Module.require (internal/modules/cjs/loader.js:1012:19)

**Comment by sodatea** [comment]
The babel folks have already answered the question: https://github.com/babel/babel/issues/11439

Please upgrade your dependencies. You can do it by running `vue upgrade` in the project.
