### ISSUE TITLE
support building src/components/*.vue as standalone umd modules?

### ISSUE THREAD

**Issue by airyland** [vuejs/vue-cli#54]
I tried to add some component to `entry`, but got the output file including `Vue` source code.

````javascript
entry: {
    app: './src/main.js',
    input: ['./src/components/Input.vue']
  }
````

![image](https://cloud.githubusercontent.com/assets/559179/13628038/d7c58ac4-e609-11e5-9163-5bb3b886b686.png)

So I wonder if I did it the wrong way?

**Comment by azamat-sharapov** [comment]
Well, you are probably importing Vue too?

**Comment by airyland** [comment]
@azamat-sharapov No. I found if the vue component does not use directives config then it works fine, otherwise vue's source code is included. I wonder why.

````
 directives: {
    someDirective: someDirective
  },
````

**Comment by chrisvfritz** [comment]
@airyland I don't think this is to do with vue-cli. Perhaps it's an issue with [vue-loader](https://github.com/vuejs/vue-loader)?

**Comment by airyland** [comment]
Close it as I found out I may made a mistake.
