### ISSUE TITLE
The logic of isLocalPath

### ISSUE THREAD

**Issue by blackmiaool** [vuejs/vue-cli#540]
https://github.com/vuejs/vue-cli/blob/f46774b45dc8d7cb9ce2dbc1f7330f0f54a1ce68/lib/local-path.js

`/^[./]|(^[a-zA-Z]:)/.test('/home')`   => true

The logic of the function seems wrong, I think it should be 
`/^\.\/|(^[a-zA-Z]:)/.test('/home')`

**Comment by posva** [comment]
no, because we can pass an absolute path to test a local template
