### ISSUE TITLE
Macos install failed: No matching version found for apollo-codegen-core@^0.36.7

### ISSUE THREAD

**Issue by atyshka** [vuejs/vue-cli#5402]
### Version
4.3.1

### Environment info
```
Not applicable, not yet installed
```

### Steps to reproduce
Install node 13.13.0 on macos with homebrew
npm install -g @vue/cli 

### What is expected?
Successful Installation

### What is actually happening?
npm ERR! notarget No matching version found for @apollographql/apollo-tools@^0.4.6.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'apollo'
npm ERR! notarget

**Comment by Phoscur** [comment]
Issue is not limited to macos!

Older versions of `@vue/cli` are not installable either:
```
> npm i -g @vue/cli@4.2.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for apollo-env@^0.6.3
```
```
> npm i -g @vue/cli@4.1/0.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @apollographql/apollo-tools@^0.4.6
```

**Comment by gabrielstuff** [comment]
was banging my head.
just tried with yarn which allow to select an other version of `"apollo-language-server"` which seems to be the package that generated the issue.

using `yarn global add @vue/cli` makes it possible.

**Comment by atyshka** [comment]
How long has this been an issue and why can't I find it mentioned anywhere else? ANy success in getting it working with npm rather than yarn?

**Comment by jagj77** [comment]
I have same issue but with another apollo package.


npm ERR! notarget No matching version found for apollo-env@^0.6.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'apollo'
npm ERR! notarget

**Comment by atyshka** [comment]
Fixed as of now
