### ISSUE TITLE
Not working on IE11 when choosing TypeScript

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue-cli#5406]
### Version
4.3.1

### Environment info
```
OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz  
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vue/cli-overlay:  4.3.1 
    @vue/cli-plugin-eslint: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-router: ~4.3.0 => 4.3.1
    @vue/cli-plugin-typescript: ~4.3.0 => 4.3.1
    @vue/cli-plugin-vuex: ~4.3.0 => 4.3.1
    @vue/cli-service: ~4.3.0 => 4.3.1
    @vue/cli-shared-utils:  4.3.1
    @vue/component-compiler-utils:  3.1.2
    @vue/eslint-config-typescript: ^5.0.2 => 5.0.2
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    typescript: ~3.8.3 => 3.8.3
    vue: ^2.6.11 => 2.6.11
    vue-eslint-parser:  7.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.1
    vue-router: ^3.1.6 => 3.1.6
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.3 => 3.2.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Create a project and select "TypeScript" without class-based syntax.
2. Run the project.
3. Open it on IE11.
4. As you can see, it is not working. There is blank page.

### Repro project
You can reproduce the issue using this project.

[ie-typescript-test.zip](https://github.com/vuejs/vue-cli/files/4498871/ie-typescript-test.zip)

### What is expected?
The project should work on IE11.

### What is actually happening?
The project does not work on IE11.

**Comment by LinusBorg** [comment]
Without Babel, polyfills are missing. This is explained in the questionnaire when you are asked if You want to use Babel alongside Typescript.

**Comment by Mikilll94** [comment]
@LinusBorg 
But I have set TypeScript to transpile code to ES5. Thus, I don't understand why this is not working on IE11.

**Comment by LinusBorg** [comment]
Typescript transpires syntax. It doesn't polyfill missing *language features*, like `Promise`
