### ISSUE TITLE
this package has 2 low vulnerabilities when you run yarn audi / npm audit

### ISSUE THREAD

**Issue by bdllhdrss3** [vuejs/vue-cli#5412]
IMPORTANT: Please use the following link to create a new issue:

https://new-issue.vuejs.org/?repo=vuejs/vue-cli

If your issue was not created using the app above, it will be closed immediately.
this package has 2 low vulnerabilities. how can we fix them
![Screenshot (13)](https://user-images.githubusercontent.com/46565520/79887004-dfc50280-83ae-11ea-9704-65df8038f189.png)

**Comment by LinusBorg** [comment]
Duplicate of #5413
