### ISSUE TITLE
yarn  serve  进度69%卡住，无任何错误输出

### ISSUE THREAD

**Issue by xyfy** [vuejs/vue-cli#5414]
### Version
4.3.1

### Reproduction link
[https://github.com/xyfy/vue-cli-stop-err](https://github.com/xyfy/vue-cli-stop-err)

### Environment info
```

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
yarn
yarn serve

### What is expected?
go to run the app

### What is actually happening?
stop and no error show

---
 yarn --version
1.22.4

**Comment by xyfy** [comment]
when use npm ,I got the same status
```
npm install 
npm run serve
```

**Comment by xyfy** [comment]
I fixed some lint errs ,it works on my PC,I will try on other pcs

**Comment by sodatea** [comment]
kindeditor 的代码太大了，卡住了。建议放进 public 文件夹，这样不用经过 webpack 打包。
https://cli.vuejs.org/zh/guide/html-and-static-assets.html#public-%E6%96%87%E4%BB%B6%E5%A4%B9
