### ISSUE TITLE
use gitlab repo throw a error: Basic authentication must be done with auth option

### ISSUE THREAD

**Issue by hacke2** [vuejs/vue-cli#542]
I use `vue-init` command, like:

```bash
vue-init git@gitlab.alibaba-inc.com:xinglong.wangwxl/sm-weex-template.git test          
```
it will throw a error      

```bash
⠋ downloading template
/usr/local/lib/node_modules/.vue-cli_npminstall/node_modules/.5.7.1@got/index.js:221
			throw new Error('Basic authentication must be done with auth option');
			^

Error: Basic authentication must be done with auth option

```

I use other commands,like `vue init --clone git@gitlab.xxx.com:aaa/bbb.git test `, it will throw 128 error

```
  vue-cli · Failed to download repo vuejs-templates/test-sm-weex: 'git clone' failed with status 128
```

**Comment by daqSam** [comment]
Hi @yyx990803, I see this issue has been closed. Was there a resolution to @hacke2 's issue?
Thanks.

**Comment by yyx990803** [comment]
No, but we are deprecating vue-cli 2.x and will not be making new releases for 2.x unless for critical vulnerabilities.

**Comment by daqSam** [comment]
Thanks, I appreciate your response.
