### ISSUE TITLE
使用vue-cli新建项目，启动时报错：Error: Cannot find module 'E:\@vue\cli-service\bin\vue-cli-service.js'

### ISSUE THREAD

**Issue by wanghuan19961020** [vuejs/vue-cli#5420]
### Version
4.3.1

### Environment info
```
win10
```

### 问题复现
1. 使用`vue create test-demo`创建项目test-demo，自定义配置如下：
![image](https://user-images.githubusercontent.com/49217992/80186138-19f90300-8640-11ea-8172-76926a4fac75.png)
2. 进入test-demo目录，启动项目`npm run serve`，出现以下报错：
![image](https://user-images.githubusercontent.com/49217992/80186374-76f4b900-8640-11ea-8aea-d392ec3747f8.png)
### 错误原因分析
- 仔细看报错提示`Error: Cannot find module 'E:\@vue\cli-service\bin\vue-cli-service.js'`
- 发现事实上在E盘下的确没有这个模块
- 这个模块正确的路径应该是在
```
E:\[项目文件]\node_models\.bin\@vue\cli-service\bin\vue-cli-service.js'
```
- 思考是不是在启动服务的时候，配置文件出错导致没有正确的找到模块路径
- 然后将node_modules/.bin/vue-cli-service.cmd文件的内容修改为：
```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\@vue\cli-service\bin\vue-cli-service.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\@vue\cli-service\bin\vue-cli-service.js" %*
)
```
- 项目可以正常运行了
- node_modules/.bin/vue-cli-service.cmd文件的原本内容：
```
@ECHO off
SETLOCAL
CALL :find_dp0

IF EXIST "%dp0%\node.exe" (
  SET "_prog=%dp0%\node.exe"
) ELSE (
  SET "_prog=node"
  SET PATHEXT=%PATHEXT:;.JS;=;%
)

"%_prog%"  "%dp0%\..\@vue\cli-service\bin\vue-cli-service.js" %*
ENDLOCAL
EXIT /b %errorlevel%
:find_dp0
SET dp0=%~dp0
EXIT /b
```
### What is expected?
npm run serve可以正常启动项目，不会报错

### What is actually happening?
npm run serve无法正常启动项目，报错Error: Cannot find module 'E:\@vue\cli-service\bin\vue-cli-service.js'

**Comment by vyrru5** [comment]
the same, on win10 & macOS  
node -v 14
npm 6.14.4
@vue/cli 4.3.1

**Comment by fangbinwei** [comment]
It seems the error caused by the `&` of  path `webpack&vuecli&vue-router&vuex`

**Comment by wanghuan19961020** [comment]
> The error caused by the `&` of path `E:\webpack&vuecli&vue-router&vuex`
> 
> and `node_modules/.bin/vue-cli-service.cmd` is generated by npm

Is it because of the environment or configuration?How to deal with this situation?

**Comment by fangbinwei** [comment]
@wanghuan19961020  I am not familiar with the syntax of `.cmd`. I can only suggest don't use `&` in your directory. Maybe someone else can help you.

**Comment by wanghuan19961020** [comment]
@fangbinwei Thank you

**Comment by sodatea** [comment]
Seems related to this bug https://github.com/npm/cmd-shim/issues/45
