### ISSUE TITLE
Custom Template Issue with Private Bitbucket Repo

### ISSUE THREAD

**Issue by bajras** [vuejs/vue-cli#543]
Im having a issue with the custom template and its hosted at my work's private bitbucket repo and get the following error:

`vue-cli · Failed to download repo ssh://git@bitbucket.moo.com:7999/mac/vue-moo-webpack-boilerplate.git: 'git clone' failed with status 128
`
I tried all the mentioned steps:
`vue init -c ssh://git@bitbucket.moo.com:7999/mac/vue-moo-webpack-boilerplate.git yay`
`vue init ssh://git@bitbucket.moo.com:7999/mac/vue-moo-webpack-boilerplate.git --clone yay`

When I put in on a public Github repo it works fine but not sure why its not working with the private bitbucket repo?

When I do git clone bitbucket of the exact repo it works fine as so I can tell its not the connection issue with SSH.

`git clone ssh://git@bitbucket.moo.com:7999/mac/vue-moo-webpack-boilerplate.git`

Any help would be highly appreciated. Thanks.

**Comment by kospot** [comment]
do the two step, can fix it
1、in the window system, the symbol ':' is can not be in a file name
2、update the module download-git-repo must to the lastest

**Comment by bajras** [comment]
@kospot That doesnt work.

**Comment by kospot** [comment]
first, you may edit vue-cli/bin/vue-init at line 68, change to this:
`var tmp = path.join(home, '.vue-templates', template.replace(/[\/|:]/g, '-'))`
then the module download-git-repo must to the lastest @1.0.1

my gitlab url is 'http://192.168.44.125/minghua/vue-template-test.git'
so i use
` vue-init -c http://192.168.44.125:minghua/vue-template-test  test2`
