### ISSUE TITLE
Build unwantedly changes css colour from string to hex

### ISSUE THREAD

**Issue by chrissyast** [vuejs/vue-cli#5431]
### Version
4.3.1

### Reproduction link
[https://github.com/chrissyast/example/](https://github.com/chrissyast/example/)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
    Safari: 13.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.1.2 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.3.1 
    @vue/cli-plugin-babel: ^4.1.0 => 4.1.2 
    @vue/cli-plugin-eslint: ^4.1.0 => 4.1.2 
    @vue/cli-plugin-router:  4.3.1 
    @vue/cli-plugin-vuex:  4.3.1 
    @vue/cli-service: ^4.3.1 => 4.3.1 
    @vue/cli-shared-utils:  4.1.2 (4.3.1)
    @vue/component-compiler-utils:  3.1.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.0.0 => 5.2.3 
    vue: ^2.6.10 => 2.6.11 
    vue-cli-plugin-vuetify: ^2.0.3 => 2.0.3 
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuetify: ^2.1.0 => 2.2.8 
    vuetify-loader: ^1.3.0 => 1.4.3 
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Observe colours in style section of `example.vue`

Run `vue-cli-service build`

Observe colours in `dist/css/app.xxxx.css`

### What is expected?
Colours are preserved as strings in css in "dist" folder

Alternate system bars have class:

`v-system-bar theme--light orange`

`v-system-bar theme--light blue`

### What is actually happening?
`blue` is converted to `#00f` in css in "dist" folder

Alternate system bars have class:

`v-system-bar theme--light orange`

`v-system-bar theme--light`

**Comment by sodatea** [comment]
`blue` and `#00f` are equivalent when used as a color. Why do you think it's a bug?

**Comment by chrissyast** [comment]
> `blue` and `#00f` are equivalent when used as a color. Why do you think it's a bug?

I don't think it's a bug necessarily, but it's unwanted behaviour. 

`blue` and `#00f` are equivalent but not interchangeable, i.e. you can have a component

<div class="v-system-bar theme--light blue">
but you can't have
<div class="v-system-bar theme--light #00f">

**Comment by sodatea** [comment]
Class and color are not the same. CSS compression tool only compresses colors, not class names.

**Comment by sodatea** [comment]
If you'd like to fix this issue, we use @intervolga/optimize-cssnano-plugin underlyingly https://github.com/vuejs/vue-cli/blob/320e3919c9000c5c00be21b30445393b7d4765cc/packages/%40vue/cli-service/lib/config/css.js#L246 which uses [postcss-colormin](https://github.com/cssnano/cssnano/tree/master/packages/postcss-colormin) for color minification.

Here are the code snippets that are relevant https://github.com/cssnano/cssnano/blob/8dd5c4498533c4a62385856c94d1aa7f89deb9d2/packages/postcss-colormin/src/colours.js#L5
https://github.com/cssnano/cssnano/blob/8dd5c4498533c4a62385856c94d1aa7f89deb9d2/packages/postcss-colormin/src/colours.js#L20

It compares the color keyword string with its hex form, chooses the shorter one, and prefers the latter when the two strings are of the same length. Feel free to submit a PR to it.

**Comment by chrissyast** [comment]
> Class and color are not the same. CSS compression tool only compresses colors, not class names.
In the example repository, you can see the class name depends on the `--main-colour` and `--secondary-colour` variables which are defined in the css. That is why the CSS compression is an issue.

**Comment by sodatea** [comment]
Or you can tap into the cssnano config and disable the `postcss-colormin` plugin.

**Comment by chrissyast** [comment]
Thanks for the info @sodatea , I will take a look at the cssnano repo. Within vue-cli, would there potentially be some way to skip using within vue-cli based on a parameter? 

i.e. `vue-cli-service build --skip-colormin`

**Comment by sodatea** [comment]
Use [`chainWebpack`](https://cli.vuejs.org/guide/webpack.html#chaining-advanced), tap into [the `optimize-css` rule](https://github.com/vuejs/vue-cli/blob/320e3919c9000c5c00be21b30445393b7d4765cc/packages/%40vue/cli-service/lib/config/css.js#L244-L249), change the `cssnanoOptions` to [exclude the `colormin` transform](https://cssnano.co/guides/presets/#excluding-transforms).

It's very cumbersome because such default settings are only expected to be modified under rare circumstances. This issue certainly is workaround-able, but I do strongly recommend you to find another way to implement the feature instead of relying on a runtime property value.

**Comment by chrissyast** [comment]
@sodatea Yes, you're right, there is probably a better way of implementing what I want.

**Comment by kontur** [comment]
For future reference, I've been debugging an issue where colors were off in a production build because of this. In my case I was defining an rgb color `$text: #FFFFFF` and an rgba css variable `--dimmed-text: #{text}66` — the resulting `#FFF66` gets rendered as "rgbaa" by Firefox (transparent white), and as "rgb" (with missing 6th digit) by Webkit (full white).

Also I have no clue how to actually do the config @sodatea suggested.
