### ISSUE TITLE
Cannot use contenthash in filename or chunk file name for web component build

### ISSUE THREAD

**Issue by princesspoopan** [vuejs/vue-cli#5434]
### Version
4.1.1

### Environment info
```
@vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.11.0
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  4.1.1
    @vue/cli-plugin-babel: ^3.11.0 => 3.11.0
    @vue/cli-plugin-e2e-cypress: ^3.11.0 => 3.11.0
    @vue/cli-plugin-eslint: ^4.1.1 => 4.1.1
    @vue/cli-plugin-router:  4.1.1
    @vue/cli-plugin-typescript: ^4.1.1 => 4.1.1
    @vue/cli-plugin-unit-jest: ^4.1.1 => 4.1.1
    @vue/cli-plugin-vuex:  4.1.1
    @vue/cli-service: 4.1.1 => 4.1.1
    @vue/cli-shared-utils:  4.1.1 (3.11.0)
    @vue/component-compiler-utils:  3.1.0
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/eslint-config-typescript: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/test-utils: 1.0.0-beta.30 => 1.0.0-beta.30
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.0.1 => 6.2.2
    jest-serializer-vue:  2.0.2
    typescript: ^3.7.3 => 3.7.3 (3.7.2)
    vue: ^2.6.11 => 2.6.11
    vue-class-component: ^7.0.2 => 7.1.0
    vue-eslint-parser:  7.0.0
    vue-hot-reload-api:  2.3.4
    vue-i18n: 8.17.0 => 8.17.0
    vue-jest:  3.0.5
    vue-loader:  undefined (15.8.3)
    vue-property-decorator: ^8.3.0 => 8.3.0
    vue-router: ^3.0.3 => 3.1.3
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vue-test-utils: 1.0.0-beta.11 => 1.0.0-beta.11
    vuex: ^3.1.2 => 3.1.2
```

### Steps to reproduce
in vue.config.js
```
configureWebpack: {
    mode: 'production',
    plugins: [new CompressionPlugin(), new webpack.EnvironmentPlugin(['NODE_ENV', 'DEBUG', 'API_TOKEN'])],
    output: {
      filename: '[name].[contenthash].js',
      chunkFilename: '[name].[contenthash].js'
    }
  }
```

command: `vue-cli-service build --target wc-async --name foo ./src/foo.vue`

### What is expected?
The chunk filename generate by the build should contain chunkhash for example:

- dist/foo.c0b14a2b59b6a2991383.min.js
- dist/foo.1.c0b14a2b59b6a2991383.min.js

### What is actually happening?
Chunkhash is not appear in the chunk file name

---
The above setup works with normal vue-cli build but it doesn't work with --target wc-async

**Comment by LinusBorg** [comment]
The current implementation for (async) web components doesn't allow to use hashes.

We manually create the JavaScript code for the entry file, which means we can't write import statements for files whose hash we don't know yet.

See:

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/build/resolveWcEntry.js

Unless someone comes up with a clever different way, this can't be supported

**Comment by princesspoopan** [comment]
@LinusBorg Thank you for your answer. 
Is it okay if I change this to Feature Request instead ?
It could help solving browser cache issue.

**Comment by LinusBorg** [comment]
Feel free to open a Feature request issue and add a link to this issue as part of the description.

**Comment by aryaroudi** [comment]
> The current implementation for (async) web components doesn't allow to use hashes.
> 
> We manually create the JavaScript code for the entry file, which means we can't write import statements for files whose hash we don't know yet.
> 
> See:
> 
> https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/build/resolveWcEntry.js
> 
> Unless someone comes up with a clever different way, this can't be supported

it doesn't even change the filename FYI, using something like 
```javascript
config
  // Interact with entry points
  .entry('index')
    .add('src/index.js')
    .end()
  // Modify output settings
  .output
    .path('dist')
    .filename('[name].bundle.js');
```
won't work in chain config
