### ISSUE TITLE
update issue: vue-cli base config on vuetify-loader

### ISSUE THREAD

**Issue by LaKing** [vuejs/vue-cli#5435]
### Version
4.3.1

### Environment info
```
System:
    OS: Linux 5.4 Fedora 30 (Thirty) 30 (Thirty)
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: Not Found
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: Not Found

```
My linux environment uses lots of symlinks - this is a design to allow multilingual builds, and project instantiation based on the same code, and a language plugin.

### Steps to reproduce
The problem is os-specific and probably related to in environmental behavior, thus not simply reproducible by a repo.

### The problem and the workaround
After upgrading vue to the latest version I had the following error:
`Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.`
Indeed `vuetify-loader/lib/plugin.js` didn't get the argument as it did in previous versions.
Investigating further took me to `@vue/cli-service/lib/config/base.js` line 57.
`.loader('vue-loader')` has been changed to `.loader(require.resolve('vue-loader'))`
That broke my existing installation(s). Removing require.resolve works, and I can get my instances to work with the latest version.

### What is expected?
Upgrade not breaking the working code. (or indicate configuration problems)

### What is actually happening?
```
ERROR  Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (/srv/codepad-project/var/vue/node_modules/vuetify-loader/lib/plugin.js:18:13)
    at webpack (/srv/codepad-project/var/vue/node_modules/webpack/lib/webpack.js:51:13)
    at Promise (/srv/codepad-project/var/vue/node_modules/@vue/cli-service/lib/commands/build/index.js:192:5)
```

---
This might have no effect on other people, however, it enforces me to apply a patch - so I just wanted to drop a notice if others encounter this issue as well. After all, it was not easy to hunt that problem down, after the unclear error log.

**Comment by sodatea** [comment]
This issue has been fixed long ago.
https://github.com/vuetifyjs/vuetify-loader/pull/97
You might just need to update your vuetify-loader version.
