### ISSUE TITLE
Basic project still contains unsupported javascript after setting browserslist to chromium 38

### ISSUE THREAD

**Issue by Peter-Barrett** [vuejs/vue-cli#5437]
### Version
4.3.1

### Reproduction link
[https://github.com/Peter-Barrett/vue-transpile-reproduction](https://github.com/Peter-Barrett/vue-transpile-reproduction)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 71.0
    Safari: 13.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.3.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.3.1
    @vue/cli-plugin-babel: ~4.3.0 => 4.3.1
    @vue/cli-plugin-eslint: ~4.3.0 => 4.3.1
    @vue/cli-plugin-router:  4.3.1
    @vue/cli-plugin-vuex:  4.3.1
    @vue/cli-service: ~4.3.0 => 4.3.1
    @vue/cli-shared-utils:  4.3.1
    @vue/component-compiler-utils:  3.1.2
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    vue: ^2.6.11 => 2.6.11
    vue-eslint-parser:  7.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: 4.3.1
```

### Steps to reproduce
npm run build-component

### What is expected?
The web component built in dist should not have javascript unsupported by chromium 38.

### What is actually happening?
I have the browserslist set to support chromium 38 (I need it to be this version to support LG tvs). You can see in the dist folder that there is still unsupported javascript such as use strict, => and spread operators. From what I have read on the Vue docs this shouldn't be the case.

**Comment by LinusBorg** [comment]
As explicitly noted in the documentation, the web component wrapper implementation that Vue CLI currently uses does *not* support IE11.

more specifically, it requires ES2015 support.

You can attempt to transpile `vue-web-component-wrapper` with the `transpileDependencies` option, but there's no warranty it's going to work.
