### ISSUE TITLE
Uglify-es support

### ISSUE THREAD

**Issue by ryatziv** [vuejs/vue-cli#544]
vue-cli currently only supports uglify-js.  Unfortunately, the current version of vue-markdown only supports uglify-es.  It would be nice to get support for uglify-es as well.

https://github.com/miaolz123/vue-markdown/issues/37#issuecomment-318563899

**Comment by sylvainpolletvillard** [comment]
This is not the solution, uglify-es does not transpile down to ES5 so you won't get a good browser support. We just need this issue to be solved: valeriangalliat/markdown-it-highlightjs#3

**Comment by ryatziv** [comment]
@sylvainpolletvillard Thank you for following up.

**Comment by ivanyv** [comment]
What if one actually wants ES6? Any way to plug uglify-es in?

**Comment by sylvainpolletvillard** [comment]
@ivanyv you can always make your own template and plug uglify-es in the webpack config, but that seems to be a lot of effort for almost no gain (~10% less bundle size but broken support for ~10% browsers out there, probably much more on mobile)

**Comment by ivanyv** [comment]
@sylvainpolletvillard could you point me in the right direction on how to go about that? I know JS but webpack and its ecosystem is completely new to me so I'm learning as I go along with vue. Alternatively, could you help me set up vue to transpile from CoffeeScript to ES6 and then to ES5? I already have CS->ES6 working but that's obviously tripping Uglify.

**Comment by sylvainpolletvillard** [comment]
@ivanyv I'm afraid I don't have the time and knowledge to help you about that, but you should ask on https://discordapp.com/channels/325477692906536972/325479107012067328, lots of talented people there.

**Comment by ivanyv** [comment]
Thanks!
