### ISSUE TITLE
vue-cli install

### ISSUE THREAD

**Issue by bimalmagar10** [vuejs/vue-cli#5440]
### Version
4.3.1

### Environment info
```
vue info
```

### Steps to reproduce
this is all about installation so no need to have a compulsion of git repo

### What is expected?
i want to install an older version of vue cli i.e. v2.9.6
can you help me?

### What is actually happening?
i am trying to install an older version of vue cli but the command line is saying that theis version is depreciated in favour of @vye/cli.

**Comment by sodatea** [comment]
Yeah, it's deprecated but usable. You have it installed right.
