### ISSUE TITLE
Stuck at Generating README.md... for over 40 minutes

### ISSUE THREAD

**Issue by monstablog** [vuejs/vue-cli#5445]
![vue probs](https://user-images.githubusercontent.com/62035135/80870628-94103400-8c9f-11ea-86ea-cab5709e076d.JPG)
### Version
4.3.1

### Environment info
```
System:
    OS: Windows 7 6.1.7601
    CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
  Binaries:
    Node: 8.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.3.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.3.1
    @vue/cli-plugin-babel: ~4.3.0 => 4.3.1
    @vue/cli-plugin-eslint: ~4.3.0 => 4.3.1
    @vue/cli-plugin-router: ~4.3.0 => 4.3.1
    @vue/cli-plugin-vuex: ~4.3.0 => 4.3.1
    @vue/cli-service: ~4.3.0 => 4.3.1
    @vue/cli-shared-utils:  4.3.1
    @vue/component-compiler-utils:  3.1.2
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    vue: ^2.6.11 => 2.6.11
    vue-eslint-parser:  7.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.2
    vue-router: ^3.1.6 => 3.1.6
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.3 => 3.3.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
$ vue ui
??  Starting GUI...
??  Ready on http://localhost:8001
Auto cleaned 1 projects (folder not found).
 ERROR  Failed to get response from https://registry.npmjs.org/vue-cli-versioarker
 ERROR  Failed to get response from https://registry.npmjs.org/vue-cli-versioarker
-  Creating project in C:\Users\MyLaptop\Desktop\Main Api\client.
?  Creating project in C:\Users\MyLaptop\Desktop\Main Api\client.
-  Initializing git repository...
??  Initializing git repository...
-  Running completion hooks...
?  Running completion hooks...
-  Generating README.md...
??  Generating README.md...

### What is expected?
Create new project

### What is actually happening?
Stuck at Generating README.md... for over 40 minutes

**Comment by sodatea** [comment]
I can't tell what the problem is from the screenshot. Possibly a network issue.

Could you run the UI with `vue ui -D` and share the error logs here?

**Comment by sodatea** [comment]
I just took another look at this issue.
Maybe the project has been successfully created, it's just that Vue CLI failed to correctly stop the spinner.
