### ISSUE TITLE
   "@vue/cli-service": "3.5.3", 

### ISSUE THREAD

**Issue by yanstars** [vuejs/vue-cli#5447]
### Version
4.3.1

### Reproduction link
[https://e.coding.net/allstars/serve.git](https://e.coding.net/allstars/serve.git)

### Environment info
```
  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 12.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
 npm run dev  后 通过外网 ip   port 无法访问本地服务  。 局域网 ip   port 则可以成功访问

### What is expected?
外网 ip   port 能访问本地 dev serve 服务  

### What is actually happening?
 无法访问

**Comment by sodatea** [comment]
1. 链接的项目无法访问
2. 不像是 Vue CLI 的问题。Vue CLI 默认绑定到 `0.0.0.0`，应该不会有问题。请确认是否是防火墙设置问题，或者是电信运营商禁止了外网端口访问。
