### ISSUE TITLE
build fails as part of a CI/CD pipeline with NODE_ENV=production

### ISSUE THREAD

**Issue by amlisirev** [vuejs/vue-cli#5452]
### Version
4.3.1

### Environment info
```
  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
  Binaries:
    Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v14.0.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.3.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.3.1
    @vue/cli-plugin-babel: ~4.3.0 => 4.3.1
    @vue/cli-plugin-eslint: ~4.3.0 => 4.3.1
    @vue/cli-plugin-router:  4.3.1
    @vue/cli-plugin-vuex:  4.3.1
    @vue/cli-service: ~4.3.0 => 4.3.1
    @vue/cli-shared-utils:  4.3.1
    @vue/component-compiler-utils:  3.1.2
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    vue: ^2.6.11 => 2.6.11
    vue-eslint-parser:  7.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.2
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
```bash 
npx @vue/cli create test
cd test
export NODE_ENV=production
npm install
npm run build
```

### What is expected?
Should be able to run `npm run build` as part of CI/CD with `NODE_ENV=production`

### What is actually happening?
build fails due to `sh: 1: vue-cli-service: not found`

---
Is this intended behavior that the tools required to build are not part of 'production' dependencies. I would assume that a project should be able to be built inside a production environment as part of a pipeline.

Ran into the bug when trying to setup a Lerna monorepo deploy pipeline on Heroku. Standalone Vue projects build fine with the nodejs buildpack, as it installs devDependencies by default, but this does not extend to nested packages in a project. So when `lerna bootstrap` gets run, it calls `npm install` on the sub-packages with `NODE_ENV=production`, causing issues with Vue deployment.

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/issues/5107#issuecomment-605556617
