### ISSUE TITLE
图形界面：创建项目失败

### ISSUE THREAD

**Issue by playfulhd** [vuejs/vue-cli#5461]
### Version
4.3.1

### Reproduction link
[https://github.com/playfulhd/ISSUE/tree/master](https://github.com/playfulhd/ISSUE/tree/master)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 12.16.3 - D:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.4 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
- `vue ui`
- `babel`   `router `  `vuex `  `Linter/Formater`   使用配置文件
- `Eslint with error`   `node sass   Lint on save`
执行一会儿后，失败

### What is expected?
创建项目

### What is actually happening?
创建失败

---
看的我头皮发麻，请问这个问题怎么解决？

**Comment by playfulhd** [comment]
一天前，更新后就变成这样了

**Comment by sodatea** [comment]
> 一天前，更新后就变成这样了

变成怎样了？请详细描述你碰到的问题

**Comment by playfulhd** [comment]
> > 一天前，更新后就变成这样了
> 
> 变成怎样了？请详细描述你碰到的问题

变成，创建项目失败，cmd中的结果放在下面：
https://github.com/playfulhd/ISSUE/tree/master

**Comment by sodatea** [comment]
网络问题，导致 node-sass 下载失败。
请运行一遍 `vue config --set useTaobaoRegistry true` 或者翻墙。

**Comment by playfulhd** [comment]
> vue config --set useTaobaoRegistry true

网速没问题，是淘宝的镜像地址，可能是dns的原因？我再试试吧
感谢回复，周末愉快！
