### ISSUE TITLE
$var from .env.local and .env.production are escaped differently

### ISSUE THREAD

**Issue by euchen** [vuejs/vue-cli#5465]
### Version
4.3.1

### Reproduction link
[https://github.com/euchen/vue-cli-env-variables-bug](https://github.com/euchen/vue-cli-env-variables-bug)

### Environment info
```
Environment Info:

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.3.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.3.1 
    @vue/cli-plugin-babel: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-eslint: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-router:  4.3.1 
    @vue/cli-plugin-vuex:  4.3.1 
    @vue/cli-service: ~4.3.0 => 4.3.1 
    @vue/cli-shared-utils:  4.3.1 
    @vue/component-compiler-utils:  3.1.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.11 
    vue-eslint-parser:  7.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.3.1

```

### Steps to reproduce
1. run `npm run serve`
1. compare the variables in .env (VUE_APP_A_ENV) and .env.local (VUE_APP_A_LOCAL) (they both have as value `$bla`

### What is expected?
`window.__ENV_VARS__.VUE_APP_A_LOCAL` should have the value `"$Bla"`

### What is actually happening?
`window.__ENV_VARS__.VUE_APP_A_LOCAL` has the value `""`

---
The project contains an environment variable in each file: .env, .env.local, .env.production. The three variables contain the same value. 

When the value is read from process.env inside the Vue app it behaves normally. 

When the values are injected into the index.html using lodash templates, only the value from .env is inserted correctly. The char `$` seems to trigger some additional escaping in .local and .production, so that you can't use these values in index.html through `<%= process.env.VUE_APP_VAR %>`.

**Comment by sodatea** [comment]
It's `VUE_APP_A_ENV_LOCAL` not `VUE_APP_A_LOCAL`.
There's a typo in the HTML file.
