### ISSUE TITLE
Improve --skip-plugins

### ISSUE THREAD

**Issue by Fl0pZz** [vuejs/vue-cli#5477]
### What problem does this feature solve?
I try use vue-cli ecosystem with [yarn install --production](https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install-production-true-false).

For this i separate `@vue/cli-plugins-*`:
**dependencies**

* @vue/cli-service
* @vue/cli-plugin-babel

**devDependencies**
* @vue/cli-plugin-eslint

Then i try to build my app:
```sh
vue-cli-service build --skip-plugins @vue/cli-plugin-eslint
```
And got an error:
`Error: Cannot find module '@vue/cli-plugin-eslint'`

That's because the [Service.js](https://github.com/vuejs/vue-cli/blob/a91649e8c04a47b527515d2768809901a2f81c2f/packages/%40vue/cli-service/lib/Service.js#L47)  tries to find all the plugins first and skips some of them just to run them.

### What does the proposed API look like?
I'll think, skipPlugins must use before resolvePlugin.

**Comment by sodatea** [comment]
Why do you use `yarn install --production`? What's the specific use case?

**Comment by Fl0pZz** [comment]
It is not a specific use case:
https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file
> **"devDependencies"**: Packages that are only needed for local development and testing.

**Comment by sodatea** [comment]
Vue CLI plugins are meant to be development dependencies. More detailed explanations here: https://github.com/vuejs/vue-cli/issues/5107#issuecomment-605556617

**Comment by Fl0pZz** [comment]
@sodatea production deps is corejs, babel and build tools: vue cli (i need start build via vue-cli-service build), typescript (ts -> js)

**Comment by Fl0pZz** [comment]
and the issue (#5107) explain dependecies for node (node has own module resolution), however browsers does not support module resilution, so we need build app (for resolve deps)

So, build tooling must be dependecies

**Comment by sodatea** [comment]
"Build" is a development task. The production app only needs the built bundle.

**Comment by Zulcom** [comment]
>"Build" is a development task. The production app only needs the built bundle.

So how to optimize build project on CI/CD? By moving unnecessary for `build` task dependencies to devDeps as recommended by package manager.

Why this issue can't be resolved? It's would be useful for me too. As I can see you don't use specific install keys so it's not a blocker for you or for project

**Comment by sodatea** [comment]
For whatever it's worth, you misunderstood the concept of "production dependencies".

**Comment by sodatea** [comment]
If it's skippable, then it should be inside "optionalDependencies" rather than "devDependencies"

**Comment by sodatea** [comment]
And, I think it's very wrong to "optimize" CI in this way.
You can speed up the CI build by utilizing caches of the package manager. You should not pass essential workflows like linting or testing. That defeats the purpose of linting and testing. They are meant to ensure the integrity of your CI builds.

**Comment by Fl0pZz** [comment]
@sodatea ok, imagine i builded my SPA app.

I can install core-js as a dependency and as devDependesies and my application will still be built without errors because the dependencies are resolved by webpack.

I agree with you that vue-cli is a development dependency, but only if we were making a node js application, because there dependencies can be resolved in runtime. But the frontend application is built into bundles with all its dependencies, and no matter what the dependecies of the package.json section say.

**Comment by sodatea** [comment]
@Fl0pZz 
For front end projects:
- If it's a web app, then all dependencies are dev dependencies.
- If it's meant to be published as a library, then these are dependencies, and they should be "externalized" on building, the users of the library will need to install them.

As "dependencies" will be installed regardless of the environment, we chose the put those modules in the "dependencies" field for maximum compatibility across all use cases.

**Comment by Fl0pZz** [comment]
@sodatea  Okay, that sounds convincing. However, the original question remains: why `--scip-plugins` does not work at the [initialization](https://github.com/vuejs/vue-cli/blob/a91649e8c04a47b527515d2768809901a2f81c2f/packages/%40vue/cli-service/lib/Service.js#L47) stage?

**Comment by sodatea** [comment]
Sorry for the late reply.

It's because it's not the design goal of this flag - if you take a look at the [original PR](https://github.com/vuejs/vue-cli/pull/4448/files), it says this option is to "skip (plugins) for this run", meaning it's a one-off command that doesn't affect the original plugin loading logic.

Anyway, I feel it's okay to skip the plugin loading at all. Though, it's a low-priority for us to implement, given the abovementioned alternative workarounds.
You are welcome to open a PR to address this issue and we'll be glad to accept it, but we are not likely to implement it on our own in the foreseeable future.
