### ISSUE TITLE
VUE Cli build hangs and no debug information

### ISSUE THREAD

**Issue by bitquality** [vuejs/vue-cli#5485]
### Version
4.3.1

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue-cli](https://new-issue.vuejs.org/?repo=vuejs/vue-cli)

### Environment info
```
Local Dev Environment
```

### Steps to reproduce
I have a node js project based on vue framework. While building the project using vue-cli-service , the typechecker hangs or stuck at below line..

    Starting type checking service...
    Using 1 worker with 2048MB memory limit
    40% building 220/229 modules 9 active usr\abc\node_modules\querystring-   es3\encode.js

    40% building 152/164 modules 12 active ..\node_modules\@vue\babel-preset-app\node_modules\core-js\internals\call-with-safe-iteration-closing.js

The above line doesn't help me to figure out whats the issue with type checking..

with little bit of research i found out vue-cli uses `fork-ts-checker-webpack-plugin`

Is there a way to disable it or print more debug info ?

update: I used below config to not to load it but it still stops there.

          // in vue.config.js
      const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

      module.exports = {
        configureWebpack: config => {
          // remove the existing ForkTsCheckerWebpackPlugin
          config.plugins = config.plugins.filter(
            p => !(p instanceof ForkTsCheckerWebpackPlugin),
          );
        },
      };

Update:

 Below are plugins part of vue inspect:

    		[
			  'vue-loader',
			  'define',
			  'case-sensitive-paths',
			  'friendly-errors',
			  'html',
			  'pwa',
			  'preload',
			  'prefetch',
			  'copy',
			  'fork-ts-checker'
			]

### What is expected?
Display at least why  the build cannot proceed and display errors

### What is actually happening?
Build doesnt fail or pass and never completes

**Comment by sodatea** [comment]
Please do provide a reproduction repo here.

**Comment by williamreetz** [comment]
I have the same problem on Ubuntu 18.04.3. When I run ``vue-cli-service build``` my server freezes after a few seconds and I have to reboot the machine.

The issue was that I had to little RAM. What helped me was creating a swapfile and then it worked.

**Comment by bitquality** [comment]
I have added more debugging info and figured out it was stuck at loading one of my npm link library .
 I tried to set symlinks to false lin vue.config.js like shown below but it didnt work.As a temporary fix i copied entire plugin project to my main vue project and tested . it works this way for now.

Not sure what is wrong with `config.resolve['symlinks'] = false;`

`			const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
			const webpack = require('webpack');

			module.exports = {
			  lintOnSave: true,

			  configureWebpack: (config) => {

				config.resolve['symlinks'] = false;
			  }
			}`

**Comment by gonzalo-piffaretti-tfs** [comment]
you just saved my week, been blocked for a couple of days trying to fix this dependency to a local package.
