### ISSUE TITLE
Vue init not working before and after installing vue-init

### ISSUE THREAD

**Issue by informathemusic** [vuejs/vue-cli#5494]
When i ran vue init it says ```Command vue init requires a global addon to be installed.
Please run pnpm install -g @vue/vli-init and try again.```
So I ran pnpm i -g @vue/cli-init as required but still got the same error after running vue init again.
I also tried to install it with npm but it didn't work either.

Any ideas on how to get rid of this error?

**Comment by RyanIPO** [comment]
> When i ran vue init it says `Command vue init requires a global addon to be installed. Please run pnpm install -g @vue/vli-init and try again.`
> So I ran pnpm i -g @vue/cli-init as required but still got the same error after running vue init again.
> I also tried to install it with npm but it didn't work either.
> 
> Any ideas on how to get rid of this error?

Have you found a solution

**Comment by informathemusic** [comment]
No I didn't. Sorry.

**Comment by Giamme** [comment]
Same here.
I'm trying to use "vue-web-extension" that requires vue init, but installing vue/cli-init doesn't solve it.
Keeps telling me to install cli-init globally, and that's what I'm doing...

**Comment by lovanya** [comment]
Same here.

**Comment by LazyTechwork** [comment]
Yes, what about solution? Anyone found it?

**Comment by beamsies** [comment]
Having same issue
