### ISSUE TITLE
vue-cli upgrading not working

### ISSUE THREAD

**Issue by it-sha** [vuejs/vue-cli#5501]
### Version
4.4.0

### Reproduction link
[https://cli.vuejs.org/ru/guide/creating-a-project.html](https://cli.vuejs.org/ru/guide/creating-a-project.html)

### Environment info
```
vue info not working (screen http://prntscr.com/sk5we9)

node 13.7.0
npm 6.13.6
vue --version 2.9.6

```

### Steps to reproduce
1. vue --version  # returns 2.9.6
2. npm uninstall -g vue-cli
3. npm install -g @vue/cli
4. vue --version  # still returns 2.9.6

http://prntscr.com/sk5x53

### What is expected?
it is possible to create a new project with
vue create project-name

### What is actually happening?
vue create project-name returns 

 vue create is a Vue CLI 3 only command and you are using Vue CLI 2.9.6.

  You may want to run the following to upgrade to Vue CLI 3:

  npm uninstall -g vue-cli

  npm install -g @vue/cli

http://prntscr.com/sk5y9e

---
I can't give a link to minimal reproduction because it's not possible to create any project

**Comment by sodatea** [comment]
Maybe you have it installed with yarn. What about `yarn global remove vue-cli`?

**Comment by it-sha** [comment]
Yes it seems like yarn problem. I have tryed to `yarn global remove vue-cli` but it doesn't work.
So I deleted yarn, global packages forder and install yarn from scratch

cli works now
