### ISSUE TITLE
vue3中style的scoped不生效

### ISSUE THREAD

**Issue by a644994** [vuejs/vue-cli#5503]
### Version
4.4.0

### Environment info
```
 System:
   OS: Windows 10 10.0.18363
   CPU: (4) x64 Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
 Binaries:
   Node: 12.16.1 - D:\environment\nodejs\node.EXE
   Yarn: 1.22.4 - D:\environment\yarn\bin\yarn.CMD
   npm: 6.13.4 - D:\environment\nodejs\npm.CMD
 Browsers:
   Edge: 44.18362.449.0
 npmGlobalPackages:
   @vue/cli: Not Found

```

### Steps to reproduce
创建项目
添加vue3支持： vue add vue-next
运行项目
打开浏览器审查元素，发现在添加了style标签scoped的，还是全局样式

### What is expected?
h3[data-v-469af010] {
    margin: 40px 0 0;
}

### What is actually happening?
h3 {
    margin: 40px 0 0;
}

**Comment by CaiPeng1989** [comment]
`scoped` -> `slotted`

**Comment by a644994** [comment]
> ```
> <style lang="scss" scoped>
> ::v-slotted(h3) {
>   margin: 40px 0 0;
> }
> ::v-slotted(ul) {
>   list-style-type: none;
>   padding: 0;
> }
> ::v-slotted(li) {
>   display: inline-block;
>   margin: 0 10px;
> }
> ::v-slotted(a) {
>   color: #42b983;
> }
> </style>
> ```

试了一下，没有用呀，样式直接没了，而且编辑器里不识别这个选择器。

**Comment by CaiPeng1989** [comment]
![image](https://user-images.githubusercontent.com/29009081/82525332-aaedcc00-9b63-11ea-831c-770ac4ef5245.png)

**Comment by a644994** [comment]
![批注 2020-05-21 134100](https://user-images.githubusercontent.com/17060692/82527386-e76ff680-9b68-11ea-950c-29a5c959dac3.png)
![批注 2020-05-21 134155](https://user-images.githubusercontent.com/17060692/82527411-f5257c00-9b68-11ea-83cb-3f609166849c.png)

**Comment by CaiPeng1989** [comment]
`vue` 和 `@vue/compiler-sfc` 用 `^3.0.0-beta.14` 试试

**Comment by a644994** [comment]
试过了，不行，我觉得跟vue没关系吧，应该是vue-loader的问题。

**Comment by CaiPeng1989** [comment]
现在不是 `vue-loader` 处理代码了，都是 `@vue/compiler-sfc` 在处理代码。

**Comment by a644994** [comment]
那是bug呢，还是我的问题呢，我直接创建的项目，什么都没改。

**Comment by CaiPeng1989** [comment]
改完目标版本后重新安装依赖重启项目了吗？

**Comment by a644994** [comment]
是的，执行yarn，然后重新启动的。

**Comment by sodatea** [comment]
Fixed in vue-loader v16.0.0-beta.3

**Comment by haihuo0910** [comment]
那现在怎么解决呢？
