### ISSUE TITLE
env variables not taken

### ISSUE THREAD

**Issue by myleshk** [vuejs/vue-cli#5506]
### Version
4.3.1

### Reproduction link
[https://github.com/myleshk/vue-cli-issue-minimal-reproduction](https://github.com/myleshk/vue-cli-issue-minimal-reproduction)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Edge: Not Found
    Firefox: 72.0.2
    Safari: 13.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.3.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.3.1 
    @vue/cli-plugin-babel: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-eslint: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-router: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-typescript: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-vuex: ~4.3.0 => 4.3.1 
    @vue/cli-service: ~4.3.0 => 4.3.1 
    @vue/cli-shared-utils:  4.3.1 
    @vue/component-compiler-utils:  3.1.2 
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0 
    @vue/eslint-config-typescript: ^5.0.2 => 5.0.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    typescript: ~3.8.3 => 3.8.3 
    vue: ^2.6.11 => 2.6.11 
    vue-class-component: ^7.2.3 => 7.2.3 
    vue-eslint-parser:  7.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.2 
    vue-property-decorator: ^8.4.1 => 8.4.2 
    vue-router: ^3.1.6 => 3.2.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.1.3 => 3.4.0 
  npmGlobalPackages:
    @vue/cli: 4.3.1
```

### Steps to reproduce
1. Install dependencies. `npm ci` or `yarn install`.
2. `yarn build` or `npm run build`.

### What is expected?
`BASE_URL` in `public/index.html` template should be replaced by values in `.env.production`. Like 
```
    <link rel="icon" href="/production/favicon.ico">
```

### What is actually happening?
Environment variable `BASE_URL` not loaded from neither `.env` nor `.env.production`. The build results in `/` as one can see in `dist/index.html`. Like
```
    <link rel=icon href=/favicon.ico>
```

---
If I change the variable name to `VUE_APP_xxx`, it will work. But isn't that syntax for client side access only? BTW this whole project is generated by `vue create` directly, except for the 2 `.env` files. If the variable name is wrong, it is also your bug I guess.

**Comment by CaiPeng1989** [comment]
https://cli.vuejs.org/guide/html-and-static-assets.html#interpolation

`BASE_URL` will not be overwritten by` .env`, your modification is invalid.

**Comment by myleshk** [comment]
ok so `BASE_URL` cannot be overwritten directly.
[https://cli.vuejs.org/config/#publicpath](https://cli.vuejs.org/config/#publicpath)
To change it, one must set it in `vue.config.js` like this for different environment:
```
module.exports = {
  publicPath: process.env.NODE_ENV === 'production'
    ? '/production-sub-path/'
      : process.env.NODE_ENV === 'staging'
        ? '/staging-sub-path/'
          : '/'
};
```
