### ISSUE TITLE
edge modern Promise.allSettled polyfill

### ISSUE THREAD

**Issue by CaiPeng1989** [vuejs/vue-cli#5507]
### Version
4.4.0

### Reproduction link
[https://github.com/CaiPeng1989/edge-modern-promise-all-settled-polyfill](https://github.com/CaiPeng1989/edge-modern-promise-all-settled-polyfill)

### Environment info
```
  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz      
  Binaries:
    Node: 14.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Users\CaiPeng\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.1.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.3.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.3.1 
    @vue/cli-plugin-babel: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-eslint: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-router:  4.3.1 
    @vue/cli-plugin-vuex:  4.3.1 
    @vue/cli-service: ~4.3.0 => 4.3.1 
    @vue/cli-shared-utils:  4.3.1 
    @vue/component-compiler-utils:  3.1.2 
    @vue/eslint-config-standard: ^5.1.2 => 5.1.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.11 
    vue-eslint-parser:  7.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.4.0
```

### Steps to reproduce
yarn build  
Use the `edge` browser to open the compiled project.

### What is expected?
console.log(Promise.allSettled) -> ƒ allSettled() { [native code] }

### What is actually happening?
console.log(Promise.allSettled) -> undefined

**Comment by CaiPeng1989** [comment]
@sodatea look here!
In modern mode, the `edge` browser cannot correctly fill` Promise.allSettled`.

**Comment by CaiPeng1989** [comment]
Using the hack method

```js
function init () {
  console.log(Promise.allSettled)

  new Vue({
    render: h => h(App)
  }).$mount('#app')
}

const isEdge = window.navigator.userAgent.includes('Edge')

if (isEdge) {
  import('core-js/es/promise/all-settled')
    .then(() => {
      init()
    })
} else {
  init()
}
```

**Comment by sodatea** [comment]
The problem is two-fold:
1. The core-js version set in the babel preset was 3, but `allSettled` wasn't moved into stable ES until core-js 3.2, so it's not injected by default
2. Modern mode didn't take custom polyfills into account.

**Comment by igadmile** [comment]
Hi! I'm having this issue also with browsers that do not support `Promise.allSettled` (IE, Safari < 13, Firefox Android). Is this a bug or config issue?

I'm also using modern build flag.

My babel.config.js:
```javascript
module.exports = {
    presets: [
        ['@vue/cli-plugin-babel/preset', {
            polyfills: [
                'es.promise.all-settled'
            ]
        }],
    ],
};
```

**Comment by igadmile** [comment]
I assume that the issue is [here](https://github.com/vuejs/vue-cli/blob/55d33754f47465a77b8c961eaafe25cfb8fbf191/packages/%40vue/babel-preset-app/index.js#L142).

Is there a possibility to pass `proposals: true` to corejs or change version to >= 3.2?
