### ISSUE TITLE
vue-cli-service build bug

### ISSUE THREAD

**Issue by dtcz** [vuejs/vue-cli#5508]
### Version
4.4.0

### Reproduction link
[https://github.com/dtcz/vue-cli-bug-report](https://github.com/dtcz/vue-cli-bug-report)

### Environment info
```
System:
  OS: Windows 7 6.1.7601
  CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
Binaries:
  Node: 10.15.1 - C:\ThsSoftware\nodejs\node.EXE
  Yarn: 1.19.1 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 6.4.1 - C:\ThsSoftware\nodejs\npm.CMD
npmPackages:
  @vue/babel-helper-vue-jsx-merge-props:  1.0.0
  @vue/babel-plugin-transform-vue-jsx:  1.1.2
  @vue/babel-preset-app:  4.4.0
  @vue/babel-preset-jsx:  1.1.2
  @vue/babel-sugar-functional-vue:  1.1.2
  @vue/babel-sugar-inject-h:  1.1.2
  @vue/babel-sugar-v-model:  1.1.2
  @vue/babel-sugar-v-on:  1.1.2
  @vue/cli-overlay:  4.4.0
  @vue/cli-plugin-babel: ~4.4.0 => 4.4.0
  @vue/cli-plugin-router:  4.4.0
  @vue/cli-plugin-vuex:  4.4.0
  @vue/cli-service: ~4.4.0 => 4.4.0
  @vue/cli-shared-utils:  4.4.0
  @vue/component-compiler-utils:  3.1.2
  @vue/preload-webpack-plugin:  1.1.1
  @vue/web-component-wrapper:  1.2.0
  vue: ^2.6.11 => 2.6.11
  vue-hot-reload-api:  2.3.4
  vue-loader:  15.9.2
  vue-style-loader:  4.1.2
  vue-template-compiler: ^2.6.11 => 2.6.11
  vue-template-es2015-compiler:  1.9.1
npmGlobalPackages:
  @vue/cli: Not Found

```

### Steps to reproduce
```
git clone https://github.com/dtcz/vue-cli-bug-report.git
cd vue-cli-bug-report
npm install
npm run build:1
npm run build:2
```

### What is expected?
build products in dist1and dist2 both include es.promise.finally

### What is actually happening?
there is no es.promise.finally in dist2's report.html
not compatible with chrome 49 

---
some debug help
in @vue/babel-preset-app/index.js line 90  add
```
console.log(entryFiles)
```
npm run build:2
will see entryFiles is
```
 [ 'D:\\demo\\vue-cli-template\\src\\main.js' ]
```
but it should be
```
[ 'D:\\demo\\vue-cli-template\\src\\pages\\main.js' ]
```

**Comment by dtcz** [comment]
I find the reason
https://github.com/vuejs/vue-cli/blob/fa871b05b319783934522e267da7e665186a66a7/packages/%40vue/cli-service/lib/Service.js#L282-L296

https://github.com/vuejs/vue-cli/blob/fa871b05b319783934522e267da7e665186a66a7/packages/%40vue/cli-service/lib/commands/build/resolveAppConfig.js#L39-L44

forgot to update process.env.VUE_CLI_ENTRY_FILES

**Comment by sodatea** [comment]
Yeah, I think that's the problem.
Thanks! PR's welcome
