### ISSUE TITLE
Can i use environment variables in vue template?

### ISSUE THREAD

**Issue by BiosSun** [vuejs/vue-cli#5511]
### What problem does this feature solve?
I'm in a project, the project have some user for different type, i need build and publish different feature on the project.

### What does the proposed API look like?
```html
<AppProductActions v-if="process.env.VUE_APP_TARGET === 'merchant'" />
```

**Comment by LinusBorg** [comment]
You should rather do that in component data.
```
data() {
  return {
    isMerchant: process.env.VUE_APP_TARGET === 'merchant'
  }
}
```
