### ISSUE TITLE
PeerDependencies are also bundled in lib mode which results in redundant output size

### ISSUE THREAD

**Issue by cloydlau** [vuejs/vue-cli#5512]
### Version
4.3.1

### Environment info
```
System:
  OS: Windows 10
Binaries:
  Node: 12.16.3
  Yarn: 1.22.4
  npm: 6.14.4
npmPackages:
  @vue/babel-helper-vue-jsx-merge-props:  1.0.0
  @vue/babel-plugin-transform-vue-jsx:  1.1.2
  @vue/babel-preset-app:  4.3.1
  @vue/babel-preset-jsx:  1.1.2
  @vue/babel-sugar-functional-vue:  1.1.2
  @vue/babel-sugar-inject-h:  1.1.2
  @vue/babel-sugar-v-model:  1.1.2
  @vue/babel-sugar-v-on:  1.1.2
  @vue/cli-overlay:  4.3.1
  @vue/cli-plugin-babel: ~4.3.0 => 4.3.1
  @vue/cli-plugin-router:  4.3.1
  @vue/cli-plugin-vuex:  4.3.1
  @vue/cli-service: ~4.3.0 => 4.3.1
  @vue/cli-shared-utils:  4.3.1
  @vue/component-compiler-utils:  3.1.1
  @vue/preload-webpack-plugin:  1.1.1
  @vue/web-component-wrapper:  1.2.0
  babel-helper-vue-jsx-merge-props:  2.0.3
  vue: ^2.6.11 => 2.6.11
  vue-hot-reload-api:  2.3.4
  vue-loader:  15.9.1
  vue-style-loader:  4.1.2
  vue-template-compiler: ^2.6.11 => 2.6.11
  vue-template-es2015-compiler:  1.9.1
  vuex:  3.3.0
npmGlobalPackages:
  @vue/cli: Not Found
```

### Steps to reproduce
1. Add a peerDependency and use it as devDependency as well for development only.
2. Import this dependency.
3. Run "vue-cli-service build --target lib --name xxx src/main.js"

### What is expected?
"In lib mode, Vue is externalized. This means the bundle will not bundle Vue even if your code imports Vue."

PeerDependencies should be externalized as well.
Or is there a way to do so?

### What is actually happening?
PeerDependencies will be bundled into the output files

**Comment by LinusBorg** [comment]
It seems that you are under the impression that Vue does externalize dependencies for you.

That's. It the case. You will have to tell webpack what to externalize yourself.
