### ISSUE TITLE
Getting error(Uncaught SyntaxError: Unexpected token '<') after "npm run serve"

### ISSUE THREAD

**Issue by Somnus007** [vuejs/vue-cli#5519]
### Version
4.3.1

### Reproduction link
[https://github.com/Somnus007/vue-demo](https://github.com/Somnus007/vue-demo)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Edge: 80.0.361.111
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.3.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.3.1 
    @vue/cli-plugin-babel: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-eslint: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-router:  4.3.1 
    @vue/cli-plugin-vuex:  4.3.1 
    @vue/cli-service: ~4.3.0 => 4.3.1 
    @vue/cli-shared-utils:  4.3.1 
    @vue/component-compiler-utils:  3.1.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.11 
    vue-eslint-parser:  7.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.3.1
```

### Steps to reproduce
- vue create vue-demo
- cd vue-demo
- npm run serve

### What is expected?
I can access to the home page with a hello world content

### What is actually happening?
I got a blank page, and there is a error (Uncaught SyntaxError: Unexpected token '<') on broswer console

---
I created a demo by using @vue-cli 4.3.1 and have not changed any code yet. But I got a blank page after run "npm run serve"

**Comment by sodatea** [comment]
I'm sorry but I can't reproduce the error. Do you have a more detailed error log? What's the exact error stack and from which file did it throw?

**Comment by Somnus007** [comment]
<img width="449" alt="截屏2020-05-25 下午5 33 18" src="https://user-images.githubusercontent.com/31230649/82800255-fa0e6680-9ead-11ea-898e-97b3147d51cf.png">

**Comment by sodatea** [comment]
`npm run serve` won't serve a production service worker, neither does it come with hashed assets files.
It must be due to the incorrect service worker caches brought by other projects that were previously served at `localhost:8080`.

So, please clear your browser service worker cache (Chrome Dev Tools -> Application -> Clear Storage -> Clear site data)

**Comment by Somnus007** [comment]
@sodatea Yes, that's it. Everything is ok now, thanks

**Comment by Pryme8** [comment]
I am getting the same error, I have followed all the steps with clearing the cache.  Making sure you have the correct version of cli installed etc.  Have gone through every stackoverflow suggestion and all the stuff I can find on git about it still to no avail.

My app runs correctly on the first ```npm run serve``` but fails on the first refresh or even a hard reload with the
```Uncaught SyntaxError: Unexpected token '<'``` Error

I am running Windows 10 and here are all my dependencys
```
"dependencies": {
    "@babylonjs/core": "^4.2.0",
    "@babylonjs/materials": "^4.2.0",
    "@babylonjs/gui": "^4.2.0",
    "core-js": "^3.9.0",
    "vee-validate": "^3.4.5",
    "vue": "^2.6.12",
    "vue-router": "^3.5.1",
    "vuetify": "^2.4.4",
    "vuex": "^3.6.2"
  },
  "devDependencies": {
    "@mdi/font": "^5.9.55",
    "@vue/cli-plugin-babel": "~4.5.11",
    "@vue/cli-plugin-eslint": "~4.5.11",
    "@vue/cli-plugin-router": "^4.5.11",
    "@vue/cli-plugin-vuex": "^4.5.11",
    "@vue/cli-service": "~4.5.11",
    "babel-eslint": "^10.0.3",
    "eslint": "^7.20.0",
    "eslint-plugin-vue": "^7.6.0",
    "eslint-plugin-vuetify": "^1.0.0-beta.8",
    "sass": "^1.32.8",
    "sass-loader": "^10.1.1",
    "vue-cli-plugin-vuetify": "~2.1.0",
    "vue-loader": "^15.9.6",
    "vue-template-compiler": "^2.6.12",
    "vuetify-loader": "^1.7.2"
  }```
  
  Is there maybe a conflict in my versions?  What would be another route to try?
