### ISSUE TITLE
List Deno as a package manager

### ISSUE THREAD

**Issue by javatlacati** [vuejs/vue-cli#5523]
### What problem does this feature solve?
Deno is a new package manager that seems to be very hyped, It would be nice to try how well it behaves with vue-cli

### What does the proposed API look like?
Add the deno executable to the dropdoen in [ProjectPackageManager.js](https://github.com/vuejs/vue-cli/blob/master/packages/@vue/cli/lib/util/ProjectPackageManager.js)

**Comment by geopic** [comment]
@javatlacati Deno isn't a package manager, it's a runtime.

**Comment by sodatea** [comment]
**Deno is not a package manager.**
