### ISSUE TITLE
反向代理的地址可以在打包后修改吗?方便运维管理

### ISSUE THREAD

**Issue by sunshuaizhong** [vuejs/vue-cli#5524]
### What problem does this feature solve?
反向代理的地址可以在打包后修改吗?方便运维管理

### What does the proposed API look like?
target的地址可以放在public下面,不参与打包,打包之后可以修改

**Comment by sodatea** [comment]
「反向代理的地址」指的是？

如果是指 devServer 的 proxy，这个跟打包是无关的；
如果是指 `publicPath`，参见文档 https://cli.vuejs.org/zh/config/#publicpath
> 这个值也可以被设置为空字符串 (`''`) 或是相对路径 (`'./'`)，这样所有的资源都会被链接为相对路径，这样打出来的包可以被部署在任意路径，也可以用在类似 Cordova hybrid 应用的文件系统中。

**Comment by sunshuaizhong** [comment]
> 「反向代理的地址」指的是？
> 
> 如果是指devServer的代理，这个跟打包是无关的；
> 如果是指`publicPath`，参见文档https://cli.vuejs.org/zh/config/#publicpath
> 
> > 这个值也可以被设置为空字符串（`''`）或相对路径（`'./'`），这样所有的资源都会被链接为相对路径，这样打出来的包可以被部署在任意路径，也可以用在类似的Cordova hybrid应用的文件系统中。

我的意思是方向代理写的是http://127.0.0.1:8888,这个地址可以打包后修改吗

**Comment by sodatea** [comment]
这个写在哪里？
