### ISSUE TITLE
Error deploy vue with router to Heroku : This relative module was not found: * ./router in ./src/main.js

### ISSUE THREAD

**Issue by FabriceSALAH** [vuejs/vue-cli#5526]
When I create a Vue project with CLI with router : "vue create myProject"

The project works in local.

But I cannot deploy this project on Heroku

### Version
4.3.1

### Reproduction link
[https://github.com/FabriceSALAH/20200526_issuesForVueCliService](https://github.com/FabriceSALAH/20200526_issuesForVueCliService)

### Environment info
```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 81.0.4044.138
    Edge: Not Found
    Firefox: 69.0
    Safari: 13.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.3.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.3.1 
    @vue/cli-plugin-babel: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-eslint: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-router: ~4.3.0 => 4.3.1 
    @vue/cli-plugin-vuex:  4.3.1 
    @vue/cli-service: ~4.3.0 => 4.3.1 
    @vue/cli-shared-utils:  4.3.1 
    @vue/component-compiler-utils:  3.1.2 
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.11 
    vue-eslint-parser:  7.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.2 
    vue-router: ^3.1.6 => 3.2.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Create vue project with CLI with router and add this configuration : https://cli.vuejs.org/guide/deployment.html#heroku

### What is expected?
to build and deploye with succes on heroku

### What is actually happening?
remote: -----> Build
remote:        Running build
remote:        
remote:        > test_vue_router_to_heroku@0.1.0 build /tmp/build_ba6426395db88aaa98be1e0cd8e8e70b
remote:        > vue-cli-service build
remote:        
remote:        
remote: -  Building for production...
remote:         ERROR  Failed to compile with 1 errors4:10:21 PM
remote:        
remote:        This relative module was not found:
remote:        
remote:        * ./router in ./src/main.js
remote:  ERROR  Build failed with errors.
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! errno 1
remote: npm ERR! test_vue_router_to_heroku@0.1.0 build: `vue-cli-service build`
remote: npm ERR! Exit status 1
remote: npm ERR! 
remote: npm ERR! Failed at the test_vue_router_to_heroku@0.1.0 build script.
remote: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote: 
remote: npm ERR! A complete log of this run can be found in:
remote: npm ERR!     /tmp/npmcache.vPL77/_logs/2020-05-26T16_10_21_473Z-debug.log
remote: 
remote: -----> Build failed

**Comment by FabriceSALAH** [comment]
I found the problem.

When you create a project AND BY DEFAULT this file "src/router/index.js" is IGNORED in git.

1) Please, can you update the CLI and add this file "src/router/index.js" on git tracking by default ?

2) Please, can you fix the same problem for vuex when you create a project with CLI : "vue create myProject" and add VueX : this file src/store/index.js is also ignored by git by default ?

Thank you

**Comment by sodatea** [comment]
But it's not ignored by default - just have a look at the `.gitignore` file https://github.com/FabriceSALAH/20200526_issuesForVueCliService/blob/master/.gitignore

Maybe it's in your `~/.gitignore_global`?

**Comment by FabriceSALAH** [comment]
@sodatea  Thanks for you answer.

I'm agree with you, the .gitignore file is good but, please, create a project with Vue CLI and Router and check this git command : 

git ls-files . --ignored --exclude-standard --others

I spend 6 hours cause of this bug, please, look these screenshots : 

<img width="553" alt="Capture d’écran 2020-05-27 à 19 46 40" src="https://user-images.githubusercontent.com/8639345/83054545-dcc6cd00-a052-11ea-83d7-b553ae1a5026.png">

<img width="316" alt="Capture d’écran 2020-05-27 à 19 45 55" src="https://user-images.githubusercontent.com/8639345/83054549-de909080-a052-11ea-83ba-a48e8d22d184.png">

**Comment by sodatea** [comment]
I have. But it works fine on my side.
As the git documentation said, patterns in `.gitignore` files of any parent directory will also be respected (https://git-scm.com/docs/gitignore), could you also try to look at some of your upper-level directories for some clue?

**Comment by sodatea** [comment]
Oops, misunderstood the documentaion. Please ignore my previous advice.

Please check the `core.excludesFile` option in `~/.gitconfig`

**Comment by FabriceSALAH** [comment]
humm @sodatea you're right, thank you.
I didn't know these files ~/.gitconfig and ~/gitignore_global

In ~/.gitconfig, there is `excludesfile = /Users/me/.gitignore_global`

In ~/gitignore_global, there is :
```
*~
.DS_Store
index.js
Sign_in.class

```

I'm looking for why my .gitignore_global has index.js ... any idea ?
