### ISSUE TITLE
No response in the browser after the first running

### ISSUE THREAD

**Issue by sebhochuli** [vuejs/vue-cli#554]
### Issue

I am running my app with `npm run dev` command and I go on **http://localhost:8080**. But I can load the page once time only.

After the server still running but I have no respond in the browser.

### Translate in french

Je démarre mon application avec la commande  `npm run dev`  et je me rend sur **http://localhost:8080**. Mais je peux charger la page qu'une seule fois.

Après le serveur continue de tourner mais je n'ai aucune réponse dans le navigateur.

### Environment

node v6.11.2
npm v3.9.6
vue v2.3.3

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js). This is also related to a specific template, make sure to say which template you're using
