### ISSUE TITLE
自动生成 vue.config.js

### ISSUE THREAD

**Issue by wangtong321** [vuejs/vue-cli#5546]
### What problem does this feature solve?
可否在使用vue create生成项目时自动生成带有注释的vue.config.js？每次都要去另外的地方找，很不方便。
或者已经提供了这个功能，我没有发现？

### What does the proposed API look like?
vue create app

**Comment by sodatea** [comment]
可是为什么需要？

Vue CLI 最核心的使用场景是开箱即用的 Vue 项目生成工具，默认配置即覆盖常规使用场景，所以默认不会带上 vue.config.js，只有真正有需要的场景才会由用户手动创建。

如果你真的需要给每个项目都加上带注释的 vue.config.js，那请自行写一个 preset 然后用它来生成项目。
