### ISSUE TITLE
'npm install -g vue-cli' error

### ISSUE THREAD

**Issue by mubassirhayat** [vuejs/vue-cli#555]
When I am installing vue-cli on my system I get a few warnings and errors in the installation fails. here is the screenshot of my cmd
![image](https://user-images.githubusercontent.com/6506964/29117837-2d380692-7d19-11e7-9822-379087fa4ec1.png)

**Comment by posva** [comment]
You seem to be retrieving a different version of the vue-cli, careful, you may be the victim of a man in the middle attack. Closing because this is a generic npm error
