### ISSUE TITLE
Styling terminal output while in development

### ISSUE THREAD

**Issue by sat-sat** [vuejs/vue-cli#556]
This is not a bug issue but rather an inquiry regarding what is being used to output information in the terminal while in development mode. This is specific to when you save a file in a vue-cli project with no errors and it simply outputs information like 'WAIT: Compiling...' and 'DONE: Compiled successfully in ...'. I noticed that whenever this happens the last outputted message gets pushed to to the top of the terminal window, and I was wondering if there is a particular package that is responsible for styling and outputting these message and if there is a way to style it so it doesn't push the messages to the top and stay at the bottom of the window. I apologize if this is a super newb question, but I wasn't able to find anything that would lead me to an answer to this question.

**Comment by posva** [comment]
I imagine you're talking about the webpack template. I think it's this one: https://github.com/vuejs-templates/webpack/blob/master/template/package.json#L56

**Comment by sat-sat** [comment]
Thanks @posva! That did the trick.
