### ISSUE TITLE
紧急！！！ Cannot find module 'typescript' 的奇怪问题

### ISSUE THREAD

**Issue by lisiyizu** [vuejs/vue-cli#5561]
npm run build 报错如下，好像所有的vue项目都受到影响了：

![image](https://user-images.githubusercontent.com/12014252/83991008-069ac080-a97e-11ea-98a0-2baf4fab22db.png)

**Comment by wuxiaobin1995** [comment]
这个是eslint的问题，目前已修复了，升级版本为2.21.1即可！
