### ISSUE TITLE
How to disable prefetch in vue-cli v4

### ISSUE THREAD

**Issue by FrancescoMussi** [vuejs/vue-cli#5562]
### Version
4.3.1

### Environment info
```
vue info doesn't seem to work in vue-cli v4
```

### Steps to reproduce
I am trying to disable prefetch for webpack.
I am following the docs here:

https://cli.vuejs.org/guide/html-and-static-assets.html#prefetch

Deleting the prefetch plugin, in vue.config.js
```
chainWebpack: config => {
  config.plugins.delete('prefetch')
}
```

Or disabling it for each view in the router:
```
function loadView (view) {
  return () => import(
    /* webpackChunkName: "view-[request]" */
    /* webpackPrefetch: false */
    `@/views/${view}.vue`)
}
```

### What is expected?
I expect not to load the views at startup

### What is actually happening?
all views are actually loaded

**Comment by sodatea** [comment]
There's also a `preload` plugin, too.

**Comment by cwtgogo** [comment]
> I mean, you need to disable both `prefetch` and `preload` plugins.

i do this,but this problem is also exists.

**Comment by tcstory** [comment]
```bash
    config.plugins.delete('prefetch')
    config.plugins.delete('preload')
```

the above code does not work

**Comment by ux-engineer** [comment]
Same here using version 4.5.7 and Vue 3.0 core.

**Comment by ux-engineer** [comment]
It seems [vuejs/preload-webpack-plugin](https://github.com/vuejs/preload-webpack-plugin) is forked from GoogleChromeLabs/preload-webpack-plugin and **is 23 commits ahead, 62 commits behind GoogleChromeLabs:master**.

Those unmerged commits are since September 2017.

**Comment by czl032405** [comment]
const PreloadPlugin = require("@vue/preload-webpack-plugin");

// in option configureWebpack
config.plugins = config.plugins.filter(p => !(p instanceof PreloadPlugin));

**Comment by ux-engineer** [comment]
> const PreloadPlugin = require("@vue/preload-webpack-plugin");
> 
> // in option configureWebpack
> config.plugins = config.plugins.filter(p => !(p instanceof PreloadPlugin));

This doesn't work as `plugins` property is not an array.

However, this worked for me when using multipage setup:

```js
chainWebpack: (config) => {
    config.plugins.store.delete('prefetch-app');
    config.plugins.store.delete('preload-app');
},
```

**Comment by bsnman** [comment]
Currently on **vue-cli 0.5.8**
But neither of this works.

Everything are still prefetched.

Any update on this one?

`
chainWebpack: config => {
    config.plugins.delete("prefetch");
    config.plugins.delete("preload");
    // or
    config.plugins.store.delete("prefetch");
    config.plugins.store.delete("preload");
}
`

**Comment by mrzdevcore** [comment]
Hello, 

this issue is closed but using this solution is not working for me
` config.plugins.delete('prefetch')
    config.plugins.delete('preload')`
    
is there any update ?

**Comment by RezaErfani67** [comment]
@mrzdevcore  update vue-router package

**Comment by mdaffan01** [comment]
The issue is closed and I don't know why @sodatea even thought of closing this, as this issue hasn't been resolved. I've tried everything above and nothing worked

**Comment by LinusBorg** [comment]
open a new issue and provide a reproduction, please. this issue didn't include one (even though one it required), and from what was available to deduct from the short example code given, sodatea provided the likely solution.

**Comment by czl032405** [comment]
my config keep working well and the generated html did not contain any prefetch..
"@vue/cli-service": "^4.5.7",



```
const PreloadPlugin = require("@vue/preload-webpack-plugin");

// in option **configureWebpack**  not **chainWebpack**
config.plugins = config.plugins.filter(p => !(p instanceof PreloadPlugin));
```

**Comment by w1301625107** [comment]
i have same problem,but i found some interesting.maybe use the wrong dash?
```js
prefetch-app
"-".charCodeAt()// copy from console.log(config.plugins).it's work for me
45
prefetch—app
"—".charCodeAt() // copy from network ,failed
8212
```

**Comment by ricky11** [comment]
have the same issue, rather then fix it the vue.config.js method, can i do anything in the webpack magic comments to disable prefetching?
