### ISSUE TITLE
Vue-cli4.x 版本 运行npm run serve 只能通过localhost访问 不能通过ip地址访问，请问需要怎么配置？

### ISSUE THREAD

**Issue by Gittboy** [vuejs/vue-cli#5564]
IMPORTANT: Please use the following link to create a new issue:

https://new-issue.vuejs.org/?repo=vuejs/vue-cli

If your issue was not created using the app above, it will be closed immediately.

中文用户请注意：
请使用上面的链接来创建新的 issue。如果不是用上述工具创建的 issue 会被自动关闭。

**Comment by Gittboy** [comment]
控制台显示的network地址也是localhost，这样就无法通过手机访问页面调试，请问该如何配置？

**Comment by XdYangXiaoRong** [comment]
我也是一样的问题
