### ISSUE TITLE
vue/cli库模式打包成组件库添加版本号

### ISSUE THREAD

**Issue by qisi007** [vuejs/vue-cli#5566]
### What problem does this feature solve?
打包成组件库后支持多版本共存，用户可以根据自己的需求使用对应版本号的组件

### What does the proposed API look like?
"lib": "vue-cli-service build --target lib --name 库名称 --dest dist/lib[版本号] 入口文件"

**Comment by sodatea** [comment]
这个完全可以基于 Vue CLI 已有的能力自己扩展实现，我看不出 CLI 核心模块有什么需要改动的地方。
