### ISSUE TITLE
Unexpected top-level property "lintOnSave".

### ISSUE THREAD

**Issue by davidmoseler** [vuejs/vue-cli#5568]
### Version
4.4.1

### Reproduction link
[https://github.com/davidmoseler/vue-dynamic-table](https://github.com/davidmoseler/vue-dynamic-table)

### Environment info
```
Environment Info:
Killed
```

### Steps to reproduce
Clone following repository and run

npm run lint

### What is expected?
No error

### What is actually happening?
An error happens although the docs are being followed. According to the docs:

`ESLint can be configured via .eslintrc or the eslintConfig field in package.json.`

And then it gives the configuration structure only for .eslintrc:

```
module.exports = {
  lintOnSave: false
}
```

So I used

```
"eslintConfig": {
    "lintOnSave": false
}
```

in package.json, and the output is:

```
 ERROR  Error: ESLint configuration in package.json is invalid:
        - Unexpected top-level property "lintOnSave".
```

So, either there is a bug, or the docs could probably have an example of where the lintOnSave property is expected in package.json.

**Comment by sodatea** [comment]
https://cli.vuejs.org/config/#lintonsave

It's under the section of `vue.config.js`.

**Comment by jeneser** [comment]
@sodatea ping
