### ISSUE TITLE
alter publicPath would occurr wrong

### ISSUE THREAD

**Issue by flowke** [vuejs/vue-cli#557]
if I alter publicPath in output, such as "/" to "/ac/", when project run wuould occurr wrong， and if I alter "/" to "/ac",  js file will load correct (/ac/static/js/**.js)， but img file not.  it would be "/acstatic/img/**.png", but i want it to be "/ac/static/img/**.png".

so I alter the filename in output, make it became "static/js/**.js", and every thing works in the right way;

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js). Also this seems to be related to a specific template
