### ISSUE TITLE
Prototype Pollution via ts-jest > yargs-parser

### ISSUE THREAD

**Issue by msklvsk** [vuejs/vue-cli#5573]
### Version
4.4.1

### Environment info
```
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 77.0.1
    Safari: 13.1
  npmPackages:
    @vue/cli-plugin-unit-jest: ^4.4.1 => 4.4.1 
    @vue/cli-shared-utils:  4.4.1 
    jest-serializer-vue:  2.0.2 
    vue-jest:  3.0.5 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.2.3
```

### Steps to reproduce
`npm i @vue/cli-plugin-unit-jest`

### What is expected?
“Found 0 vulnerabilities.”

### What is actually happening?
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ yargs-parser                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @vue/cli-plugin-unit-jest [dev]                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @vue/cli-plugin-unit-jest > ts-jest > yargs-parser           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1500                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Comment by Chadys** [comment]
More recent version of `ts-jest` don't have that problem, the dependency version of `ts-jest` should therefore be updated to `v25.3.0` minimum (first version with a non-vulnerable dependency to `yargs-parser`).
See [corresponding commit](https://github.com/kulshekhar/ts-jest/commit/07901d553d569eeb59f283c3ece79d639be97e9b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

**Comment by sodatea** [comment]
Not possible in this major because that's a breaking change for Vue CLI.

And there is no actual vulnerability exposed to the end-users, because in `ts-jest`, `yargs-parser` is only used for parsing command-line arguments for the command `ts-jest`, such as `ts-jest config:init`, which, an end-user would never have the chance to call.

If you do need to circumvent the warning, you can use the [`resolutions` field](https://yarnpkg.com/en/docs/selective-version-resolutions) in `package.json` and [`npm-force-resolutions`](https://www.npmjs.com/package/npm-force-resolutions).

**Comment by Aaronm14** [comment]
Also having this issue (from this library and also [laravel-mix](https://github.com/JeffreyWay/laravel-mix/issues/2389)).

I did as @sodatea suggested, which removed the warnings, not yet clear what kind of impact it might have to the libraries that depend on the problem versions. Seems okay so far.

In package.json:
```

**Comment by MakiOtaku** [comment]
<img width="571" alt="Screen Shot 2020-06-19 at 12 17 48 AM" src="https://user-images.githubusercontent.com/67115632/85045964-4fdee180-b1c2-11ea-8ace-cfb1791ed80b.png">
Same with @Aaronm14, originally my problem was just Laravel-mix but then I tried to just input what @msklvsk shared which is **`npm i @vue/cli-plugin-unit-jest`** and then a new error was added which is the **@vue/cli-plugin-unit-jest > ts-jest > yargs-parser**. So I tried to do what @sodatea suggested, and same thing happened with Aaron, it removed the warnings but I'm really not sure what happened but it worked.

**In package.json just copy what Aaronm14 inputed.**

**Comment by fabri01** [comment]
I wonder what impact this vulnerability can have..for me the dependency is related to laravel-mix(4.1.4).
@sodatea , do you know if there are vulnerability exposed to the end-users in the laravel-mix scenario?

**Comment by lartheon** [comment]
Updated yargs-parser to 18.1.3 but I'm still seeing this vulnerability warning.

**Comment by lartheon** [comment]
> Also having this issue (from this library and also [laravel-mix](https://github.com/JeffreyWay/laravel-mix/issues/2389)).
> 
> I did as @sodatea suggested, which removed the warnings, not yet clear what kind of impact it might have to the libraries that depend on the problem versions. Seems okay so far.
> 
> In package.json:
> 
> ```
> ...
> "scripts": {
>       "preinstall": "npx npm-force-resolutions",
> },
> "resolutions": {
>     "yargs-parser": "15.0.1"
>   },
> ...
> ```

This worked for me, this looks like the best work around for the time being
