### ISSUE TITLE
自定义配置文件路径问题

### ISSUE THREAD

**Issue by Huahua-Chen** [vuejs/vue-cli#5584]
### Version
4.4.4

### Environment info
```
  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 11.11.0 - ~/.nvm/versions/node/v11.11.0/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v11.11.0/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.11.0/bin/npm
```

### Steps to reproduce
```
VUE_CLI_SERVICE_CONFIG_PATH=$PWD/vue.lib-config.js vue-cli-service lib --sourceMap
```

### What is expected?
读取项目文件夹下的vue.lib-config.js配置文件

### What is actually happening?
实际上读取的是同级文件夹下的vue.config.js配置文件

https://github.com/vuejs/vue-cli/blob/a41cac220a5bc5e5305807f5249178cbcbf642f4/packages/%40vue/cli-service/lib/Service.js#L306-L318

之前是通过VUE_CLI_SERVICE_CONFIG_PATH环境变量自定义配置文件路径，请问现在是会被 `./vue.config.js` `./vue.config.cjs`替换么

**Comment by sodatea** [comment]
这个 for 循环漏了个 break 的逻辑。

不过，为什么要用这么 hacky 的方式加载配置文件？`VUE_CLI_SERVICE_CONFIG_PATH` 不是公开的 API。你的需求更适合在 `vue.config.js` 里根据其他环境变量进行条件判断，然后返回不同的配置。

**Comment by Huahua-Chen** [comment]
是的 开始是放在vue.config.js中判断，后面发现有这个环境变量就拿来试试了 省了判断的逻辑。这么用确实不好
