### ISSUE TITLE
ENOENT: no such file or directory, open "...@soda/friendly-errors-webpack-plugin..."

### ISSUE THREAD

**Issue by andriihorpenko** [vuejs/vue-cli#5587]
### Version
4.4.4

### Environment info
```
System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
  Binaries:
    Node: 14.4.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: 4.4.4
```

### Steps to reproduce
*Create a new project with the following options:*

Check the features needed for your project: Babel, Router, Vuex, CSS Pre-processors, Linter

? Use history mode for router? (Requires proper server setup for index fallback in production) Yes

? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Sass/SCSS (with node-sass)

? Pick a linter / formatter config: Prettier

? Pick additional lint features: Lint on save, Lint and fix on commit

? Where do you prefer placing config for Babel, ESLint, etc.? In dedicated config files

? Save this as a preset for future projects? No

After that I get the following error: 

npm ERR! enoent ENOENT: no such file or directory, open '/home/vagrant/code/vuecli-project/node_modules/@soda/friendly-errors-webpack-plugin/node_modules/string-width/node_modules/ansi-regex/package.json.4204358107'
npm ERR! enoent This is related to npm not being able to find a file.

### What is expected?
Successful project generation

### What is actually happening?
Project generation fails

---
Tried installing with and without sudo, in different folders (existing and merging).

**Comment by sodatea** [comment]
> Tried installing with and without sudo, in different folders (existing and merging).

Could you elaborate on this? I don't quite get what you mean here. Did you create the project on an existing folder and choose "Merge"? Was the project created with `sudo`? What do you mean by "different folders"?

Also, I think it is very likely to be an npm issue rather than Vue CLI issue.

**Comment by andriihorpenko** [comment]
Let me clarify this for you. 
- First of all, I can’t create a project even with default options(Babel+ESLint). 
- I also tried to create a project with `sudo` command, but this has no effect. 
- I tried to create a project on the existing folder by choosing “Merge” and “Overwrite” options during installation.

The problem is that there’s some dependency missing, but I can’t find it neither via npm.js website, nor in package.json. Here’s what I mean: the package `string-width` doesn’t have `ansi-reflex` dependency, but as you see from the error it is trying to find it there.

Because of that I can’t generate a project with latest NPM and Vue CLI package. What should I do?

**Comment by sodatea** [comment]
`ansi-reflex` is a transitive dependency of `string-width`.

I still have no idea why this happens. Maybe an npm or vagrant issue.

You can try `npm cache clean -f` and then rerun the `vue create` command to see if it works. Or switch to yarn by executing `vue config --set packageManager yarn`

**Comment by andriihorpenko** [comment]
So here are the results:
- `npm cache clean -f` has no effect and the issue persists.
- using yarn instead of npm works like a charm.

What shall I do next? This is clearly not a Vue CLI issue.

**Comment by sodatea** [comment]
I guess it's the same issue as https://github.com/npm/cli/issues/1148
Keep an eye on it or post the problem you're facing to npm too.
