### ISSUE TITLE
ajax get request to data.json which in src folder

### ISSUE THREAD

**Issue by andrew-basilioos** [vuejs/vue-cli#559]
ajax get request to data.json which in src folder within webpack full template ... it gives 404 all the time do i need loader for that or just server config ?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
