### ISSUE TITLE
how to make terserWebpackPlugin eliminate dead code in vue file after built when using environment variables

### ISSUE THREAD

**Issue by aeonlu** [vuejs/vue-cli#5597]
in .env.production i have 
```
VUE_APP_MY_VAR = active
```
if i use 
```
if (process.env.NODE_ENV !== 'production') {console.log('i m dead code')}
```
and build.
the code will be eliminated as expected because we can touch the NODE_ENV at compiling  time
but if i use 
```
if (process.env.VUE_APP_MY_VAR !== 'active') {console.log('i m dead code')}
```
and build   
the process.env will hard coded into the built file which looks like
```
 {a lot of envs}.VUE_APP_MY_VAR !== 'active'
```
it only works when the app is running, and the dead code wont be removed by terserWebpackPlugin
so how can i remove the dead code with using environment variables?

**Comment by sodatea** [comment]
Terser does eliminated such code.

**Comment by sodatea** [comment]
It's that terser plugin is only enabled when `NODE_ENV` equals `production`, so you won't see it eliminated under any other environment. In those circumstance, webpack does the dead code elimination, and its ability is quite limited.

**Comment by aeonlu** [comment]
> It's that terser plugin is only enabled when `NODE_ENV` equals `production`, so you won't see it eliminated under any other environment. In those circumstance, webpack does the dead code elimination, and its ability is quite limited.

do you notice that i m using the .env.production  so the environment must be production

**Comment by sodatea** [comment]
Then please follow the issue helper and provide a proper reproduction repo & env info. Because I have tried the code in a newly created project and the elimination worked.

**Comment by aeonlu** [comment]
> Then please follow the issue helper and provide a proper reproduction repo & env info. Because I have tried the code in a newly created project and the elimination worked.

i test with my newly created project and it works.that's my project bug.Thank you for taking the time.:)

**Comment by wuyuweixin** [comment]
@sodatea not worked in template.

**Comment by wuyuweixin** [comment]
![image](https://user-images.githubusercontent.com/16173597/92195529-d04adf80-ee9f-11ea-9b82-f8f12027d8f8.png)

**Comment by wuyuweixin** [comment]
Why "process.env.NODE_ENV" can not be used in template ?

**Comment by sodatea** [comment]
https://cn.vuejs.org/v2/guide/syntax.html#:~:text=%E6%A8%A1%E6%9D%BF%E8%A1%A8%E8%BE%BE%E5%BC%8F%E9%83%BD%E8%A2%AB%E6%94%BE%E5%9C%A8%E6%B2%99%E7%9B%92%E4%B8%AD,%E5%85%A8%E5%B1%80%E5%8F%98%E9%87%8F%E3%80%82

> 模板表达式都被放在沙盒中，只能访问[全局变量的一个白名单](https://github.com/vuejs/vue/blob/v2.6.10/src/core/instance/proxy.js#L9)，如 `Math` 和 `Date` 。你不应该在模板表达式中试图访问用户定义的全局变量。

**Comment by wuyuweixin** [comment]
这个目前只能用 jsx 来解决了
