### ISSUE TITLE
Installation problem, catch 22 on node versions

### ISSUE THREAD

**Issue by robverhoef** [vuejs/vue-cli#5599]
### Version
4.4.4

### Environment info
```
Mac OS 10.15.5, nvm (Node v9.11.2 or v12.18.1)
```

### Steps to reproduce
yarn global add @vue/cli

### What is expected?
A proper installation

### What is actually happening?
using node v12.18.1  
yarn global add @vue/cli  
upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "12.18.1"

using node v9.11.2  
yarn global add @vue/cli  
object-treeify@1.1.25: The engine "node" is incompatible with this module. Expected version ">= 10". Got "9.11.2"

**Comment by sodatea** [comment]
I don't find any hard (direct or indirect) dependency on `upath@1.0.4` in the dependencies of Vue CLI. `object-treeify` doesn't even appear in the dependency tree.

So these errors must have come from some other global packages.

**Comment by silversonicaxel** [comment]
temporary solution might be this @robverhoef 
```
yarn config set ignore-engines true
```

**Comment by robverhoef** [comment]
> temporary solution might be this @robverhoef
> 
> ```
> yarn config set ignore-engines true
> ```

Thank you. 
I replaced my computer in the mean time and didn't see the issue anymore. 
But I will keep your suggestion in mind.

**Comment by silversonicaxel** [comment]
well to me it fixes the node issue, but still other issues occur, I will create a ticket
