### ISSUE TITLE
Webfonts are not loaded

### ISSUE THREAD

**Issue by PrimozRome** [vuejs/vue-cli#56]
Looks like url-loader does not solve out web fonts in my CSS files ok... My main CSS file is included in main.js like this:

`import './assets/scss/main.scss'`

in the css I reference some web fonts

```
@font-face {
	font-family: 'pages-icon';
	src:url('../fonts/pages-icon/icons.eot?-u69vo5');
	src:url('../fonts/pages-icon/icons.eot?#iefix-u69vo5') format('embedded-opentype'),
		url('../fonts/pages-icon/icons.woff?-u69vo5') format('woff'),
		url('../fonts/pages-icon/icons.ttf?-u69vo5') format('truetype'),
		url('../fonts/pages-icon/icons.svg?-u69vo5#Pages-icon') format('svg');
	font-weight: normal;
	font-style: normal;
}
```

The icons aren't loaded by the browser. I then tested `npm run build` and investigated the build and the fonts files are included in the static folder but not sure why are not loaded when I run app in the browser. 

My font loaders in the webpack config are:

      {
        test: /\.woff/,
        loader: 'url?prefix=font/&limit=10000&mimetype=application/font-woff'
      }, {
        test: /\.ttf/,
        loader: 'file?prefix=font/'
      },
      {
        test: /\.eot/,
        loader: 'file?prefix=font/'
      },
      {
        test: /\.svg/,
        loader: 'file?prefix=font/'
      },

Any idea?

**Comment by PrimozRome** [comment]
With some trail-and-error with my webpack configuration I have somehow find the loader configuration for the web fonts... This one works, don't ask my why. Tried at list 10 different setups and this one finally worked

```
      {
        test: /\.(woff|woff2|eot|ttf|svg)(\?.*$|$)/,
        loader: 'url-loader?importLoaders=1&limit=100000'
      },

```

**Comment by chrisvfritz** [comment]
@PrimozRome Can you check if [this PR](https://github.com/chrisvfritz/webpack/commit/3dac744238bd6711cdbd22acdf87ec27bd9d9c94) fixes your issue?

**Comment by PrimozRome** [comment]
@chrisvfritz for my case it does not work... I get errors, see bellow. I think the problem in this part (\?v=[0-9\.]+)... 

```
ERROR in ./src/assets/fonts/pages-icon/Pages-icon.eot?-u69vo5
Module parse failed: /Users/primozrome/Documents/Web/webshop-frontend/src/assets/fonts/pages-icon/Pages-icon.eot?-u69vo5 Line 1: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader?sourceMap!./src/assets/css/pages-icons.css 6:238-291

```

I am loading my web-fonts like this:

```
@font-face {
	font-family: 'pages-icon';
	src:url('../fonts/pages-icon/Pages-icon.eot?-u69vo5');
	src:url('../fonts/pages-icon/Pages-icon.eot?#iefix-u69vo5') format('embedded-opentype'),
		url('../fonts/pages-icon/Pages-icon.woff?-u69vo5') format('woff'),
		url('../fonts/pages-icon/Pages-icon.ttf?-u69vo5') format('truetype'),
		url('../fonts/pages-icon/Pages-icon.svg?-u69vo5#Pages-icon') format('svg');
	font-weight: normal;
	font-style: normal;
}

```

**Comment by chrisvfritz** [comment]
@PrimozRome Thanks for the example! [This PR](https://github.com/vuejs-templates/webpack/pull/45) should do the trick.

**Comment by PrimozRome** [comment]
@chrisvfritz for me it somehow does not work. Now I don't get any error but the icon files are not loaded by the browser and the icons are not visible...

This setup that I commented above does work for me: 

```
      {
        test: /\.(woff|woff2|eot|ttf|svg)(\?.*$|$)/,
        loader: 'url-loader?importLoaders=1&limit=100000'
      },

```

**Comment by chrisvfritz** [comment]
@PrimozRome This is very strange. :confused: I have a few more questions, because I want to make sure we have a correct understanding of what the real issue is.

1. The regex you provided should behave _exactly_ like the one in the PR, so that shouldn't be the issue. (I even just did a sanity check with the specific filepaths you provided.)
2. `importLoaders` does not appear to be an option for `url-loader` - I think it's just a `css-loader` option. But - it sounds like you're saying removing `importLoaders=1&` breaks it for you? Can you confirm this?
3. Your limit of 100,000 is much higher than the 10,000 currently in the template and I don't think it necessarily makes sense to arbitrarily raise that. Can you confirm whether lowering the limit to `10000` breaks it for you? If it does, then it sounds like files _not_ passed on to `file-loader` may be breaking for you. (This is now my current theory.)

**Comment by PrimozRome** [comment]
@chrisvfritz you were right the importLoaders=1 had no effect in my case. I have removed it now...

The limit is the real reason. I tried changing the limit down to 10.000 in my setup and the icons were not loaded. Then I tried your setup from [this PR](https://github.com/vuejs-templates/webpack/pull/45) with limit of 100.000 and if worked.

So if I understand it right. Url-loader will pass it to the file-loader if the file is larger then the limit option? My font files are 15-38k so this is the real reason.

**Comment by chrisvfritz** [comment]
Excellent! And yes, your understanding is exactly correct. Now we just have to figure out why `file-loader` isn't working for you. Are you getting the exact same error (the `Module parse failed`) when the only difference is the `limit`? And what kind of system are you running this on?

**Comment by PrimozRome** [comment]
I am running OS X as for node and npm

```
primozrome$ npm version
^[[A{ npm: '3.6.0',
  ares: '1.10.1-DEV',
  http_parser: '2.6.1',
  icu: '56.1',
  modules: '47',
  node: '5.6.0',
  openssl: '1.0.2f',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }
node -v
v5.6.0
```

**Comment by chrisvfritz** [comment]
@PrimozRome With the new configuration, is it the the same error as before (`Module parse failed`) or a different one?

**Comment by PrimozRome** [comment]
@chrisvfritz I don't get "Module parse failed", no error actually just icons are not loaded in the browser... If I increase limit to higher then actual size of icon files then they are loaded by the browser.

**Comment by chrisvfritz** [comment]
@PrimozRome I've done a little more investigating. Is it possible [this is your problem](https://github.com/webpack/url-loader/issues/19)?

**Comment by brickgale** [comment]
@PrimozRome what version for url-loader do you put on package.json?

**Comment by zjhken** [comment]
I also got the same problem when using vue cli 3. 
I import the png image file like "../assets/logo.png"
but when run "vue serve" , it reports
error in ./assets/logo.png
Module build failed ( from ../node_modules/url-loader/dist/cjs.js)
