### ISSUE TITLE
npm ERR! peer dep missing: @babel/preset-env@^7.1.6, required by jscodeshift@0.9.0

### ISSUE THREAD

**Issue by CQBoyBrand** [vuejs/vue-cli#5612]
### Version
4.4.5

### Environment info
```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.0.0 - ~/.nvm/versions/node/v14.0.0/bin/node
    Yarn: Not Found
    npm: 6.14.4 - ~/.nvm/versions/node/v14.0.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.106
    Edge: Not Found
    Firefox: Not Found
    Safari: 13.1.1
  npmGlobalPackages:
    @vue/cli: 4.4.5
```

### Steps to reproduce
$ npm list -g --depth 0  
/Users/brand/.nvm/versions/node/v14.0.0/lib
├── @vue/cli@4.4.5
└── npm@6.14.4

npm ERR! peer dep missing: @babel/preset-env@^7.1.6, required by jscodeshift@0.9.0

### What is expected?
No error for peer deps

### What is actually happening?
npm ERR! peer dep missing: @babel/preset-env@^7.1.6, required by jscodeshift@0.9.0

**Comment by sodatea** [comment]
Fixed in 4.4.6 but seems to introduce more warnings for yarn 😂
Should've tested it more thoroughly.

Anyway, it will be fully fixed in the next minor as we'll get rid of jscodeshift as a direct dependency.
