### ISSUE TITLE
max-header-size

### ISSUE THREAD

**Issue by mathianasj** [vuejs/vue-cli#5618]
### Version
4.4.6

### Environment info
```

Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 72.0.1
    Safari: 13.1.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  3.12.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  3.12.1 
    @vue/cli-plugin-babel: ^3.4.0 => 3.12.1 
    @vue/cli-plugin-eslint: ^3.4.0 => 3.12.1 
    @vue/cli-plugin-pwa: ^3.4.0 => 3.12.1 
    @vue/cli-service: ^3.4.0 => 3.12.1 
    @vue/cli-shared-utils:  3.12.1 
    @vue/component-compiler-utils:  3.1.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue:  4.7.1 
    vue: ^2.6.6 => 2.6.11 
    vue-chartjs: ^3.4.0 => 3.5.0 
    vue-cli-plugin-i18n: ^0.5.1 => 0.5.2 
    vue-eslint-parser:  2.0.3 
    vue-hot-reload-api:  2.3.4 
    vue-i18n: ^8.8.1 => 8.18.2 
    vue-i18n-ts:  0.1.0 
    vue-loader:  15.9.2 
    vue-router: ^3.0.2 => 3.3.4 
    vue-router-prefetch: ^1.4.0 => 1.6.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.6 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vue2-transitions: ^0.2.3 => 0.2.3 
  npmGlobalPackages:
    @vue/cli: 4.0.5
```

### Steps to reproduce
vue-cli-service serve
Make a request with a large header over 8kb

### What is expected?
Web page is displayed

### What is actually happening?
receive http status 431

---
Would like to be able to pass nodejs arguments to alter the --max-http-header-size or any arguments in general

**Comment by sodatea** [comment]
Most of Node.js specific command line options can be set through the `NODE_OPTIONS` environment variable https://nodejs.org/api/cli.html#cli_node_options_options

So just replace the script with `NODE_OPTIONS='--max-http-header-size=100000' vue-cli-service serve`

**Comment by mathianasj** [comment]
@sodatea thank you for the response, I did find it when looking into the webpack documentation.  Do you know if this is documented somewhere on the vue docs?

**Comment by sodatea** [comment]
Not documented yet.
We are open to PRs though 🙂

**Comment by quanru** [comment]
> Most of Node.js specific command line options can be set through the `NODE_OPTIONS` environment variable https://nodejs.org/api/cli.html#cli_node_options_options
> 
> So just replace the script with `NODE_OPTIONS='--max-http-header-size=100000' vue-cli-service serve`

still not ok

**Comment by ccfish86** [comment]
> still not ok
install cross-env use `npm i cross-env -g`
and change the start script to `"dev": "cross-env NODE_OPTIONS='--max-http-header-size=8192' vue-cli-service serve  ",`
hope it will use
