### ISSUE TITLE
ChromeDriver installation failed Error with http request: Error

### ISSUE THREAD

**Issue by zhangchier** [vuejs/vue-cli#562]
D:\projects\vue-demo>npm i --registry=https://registry.npm.taobao.org

> chromedriver@2.31.0 install D:\projects\vue-demo\node_modules\chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.31/chromedriver_win32.zip
Saving to C:\Users\ZHANGC~1\AppData\Local\Temp\chromedriver\chromedriver_win32.zip
ChromeDriver installation failed Error with http request: Error: connect ETIMEDOUT 172.217.27.144:443
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chromedriver@2.31.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromedriver@2.31.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zhang Chier\AppData\Roaming\npm-cache\_logs\2017-08-16T05_01_30_379Z-debug.log

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

This has nothing to deal with vue-cli or any of its templates. Tthe problem is probably with your connection

**Comment by wenJanus** [comment]
@zhangchier Try several times will resolve it

**Comment by liaozd** [comment]
it is not his connection, it GFW of China, maybe vue-cli should not put files in the Google or other servers which could be accessed in China. That will make more chinese users easy to use.

**Comment by GongchuangSu** [comment]
@wenJanus It works. Thanks.

**Comment by kairok** [comment]
Try another link
npm install chromedriver --chromedriver_cdnurl=https://npm.taobao.org/mirrors/chromedriver

**Comment by SivasubramanianV** [comment]
@GongchuangSu How did you get it work? I am facing the same issue.

**Comment by Cat1987** [comment]
> Try another link npm install chromedriver --chromedriver_cdnurl=https://npm.taobao.org/mirrors/chromedriver

works! thanks!
