### ISSUE TITLE
Environment variables cannot use Boolean or numeric values

### ISSUE THREAD

**Issue by developer-qi** [vuejs/vue-cli#5626]
### Version
4.4.6

### Environment info
```
node: v10.8.0 npm: v6.2.0  @vue/cli: 4.1.2 
```

### Steps to reproduce
.env文件里配置环境变量  例如APP_VUE_TEST =  ture

### What is expected?
在页面可以正确获取环境变量类型

### What is actually happening?
现在赋值ture或者0 1页面获取都是string类型

**Comment by sodatea** [comment]
It's by design. Environment variables are strings by definition. Here's the POSIX specification: https://pubs.opengroup.org/onlinepubs/9699919799/
