### ISSUE TITLE
collapse  .env.* files into one folder 

### ISSUE THREAD

**Issue by Vincent1993** [vuejs/vue-cli#5630]
### What problem does this feature solve?
Because there are too many env files in the project will cause the project structure to be confusing

### What does the proposed API look like?
custom env file root

``` js
// vue.config.js
module.exports = {
   envRoot: 'configs'
}
```

**Comment by wenfangdu** [comment]
Possible duplicate to https://github.com/vuejs/vue-cli/issues/4878
