### ISSUE TITLE
Upgrade html-webpack-plugin to v4

### ISSUE THREAD

**Issue by dlindenkreuz** [vuejs/vue-cli#5634]
### What problem does this feature solve?
html-webpack-plugin v4 provides new features, and adding html-webpack-plugin to vue-cli projects will currently result in v3 and v4 being installed simultaneously. This can lead to some conflicts with plugins that modify HTML output (e.g. html-webpack-harddisk-plugin).

### What does the proposed API look like?
n/a

**Comment by fech-dev** [comment]
There are any news about this?

**Comment by sodatea** [comment]
Updated in [v5.0.0-alpha.0](https://github.com/vuejs/vue-cli/releases/tag/v5.0.0-alpha.0)

**Comment by huhm** [comment]
@vue/cli-service@^4.5.13 is still using html-webpack-plugin@^3.2.0,  which is outdated 
My Project is still using webpack4(there're some plugins only support webpack4)

**Comment by huhm** [comment]
> Updated in [v5.0.0-alpha.0](https://github.com/vuejs/vue-cli/releases/tag/v5.0.0-alpha.0)

@vue/cli-service@^4.5.13 is still using html-webpack-plugin@^3.2.0, which is outdated
