### ISSUE TITLE
Sourcemap should be closed by default in production mode

### ISSUE THREAD

**Issue by 2239559319** [vuejs/vue-cli#5638]
### What problem does this feature solve?
By default, the map file will be produced after packaging with @vue/cli in production mode, but in my opinion, the devtool sourcemap should be closed by default for safety reasons. If sourcemap is opened other people can also see the source code of my webpage.  It is troublesome to manually configure configureWebpack option every time.

### What does the proposed API look like?
Sourcemap is closed by default in production mode and no need to manually configure

**Comment by sodatea** [comment]
No. The better practice is to disable or restrict access to `.map` files in your server config.
