### ISSUE TITLE
是否, 在开发环境中, 有可选择性动态编译文件的配置?

### ISSUE THREAD

**Issue by lanseria** [vuejs/vue-cli#5646]
### What problem does this feature solve?
当项目变得庞大或者需要不断添加功能的项目群时, 我可以选择性的编译指定项目的文件夹或者文件夹群, 是利用 vue-router 动态路由功能 `import()`

### What does the proposed API look like?

在vue.config.js 暴露还是可以在webpack查看

#### cli

```
$ yarn serve --exclude-dir=[./src/views/admin/*]
```

#### vue.config.js

```js
{
  ...
  excludeDir:[./src/views/admin/*]
  ...
}
```

**Comment by IndexXuan** [comment]
for MPA，you can write mpa plugin for `yarn dev --file=index,subpage1,subpage2`
for SPA, you can use auto-routing for `yarn  dev --route=index,spa1,spa2`

**Comment by Lanseria** [comment]
> for MPA，you can write mpa plugin for `yarn dev --file=index,subpage1,subpage2` or `VUE_CLI_MPA=index yarn dev`
> for SPA, you can use auto-routing for `yarn dev --route=index,spa1,spa2`
> 
> link:
> https://github.com/ktsn/vue-route-generator

好像静态生成路由并不是我的需求, 我的菜单或者说路由都是从后端控制权限获取得到的

like this project:

http://boot.jeecg.org/isystem/newPermissionList

项目在开发时,` webpack` 会找到所有可能的 `vue` 文件进行编译, 但当项目十分庞大时, 我只需要编译src下, 某些文件夹下或者正则的文件夹就行, 虽然编译不完全, 访问这些路由会import err 等等, 但编译时间缩短了
