### ISSUE TITLE
vue create command creates a project which doesn't run

### ISSUE THREAD

**Issue by tdallagnol** [vuejs/vue-cli#5651]
### Version
4.4.6

### Reproduction link
[https://github.com/tdallagnol/vue-cli-default-error](https://github.com/tdallagnol/vue-cli-default-error)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.97
    Edge: Not Found
    Firefox: Not Found
    Safari: 13.1.1
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.4.6 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.4.6 
    @vue/cli-plugin-babel: ~4.4.0 => 4.4.6 
    @vue/cli-plugin-eslint: ~4.4.0 => 4.4.6 
    @vue/cli-plugin-router:  4.4.6 
    @vue/cli-plugin-vuex:  4.4.6 
    @vue/cli-service: ~4.4.0 => 4.4.6 
    @vue/cli-shared-utils:  4.4.6 
    @vue/component-compiler-utils:  3.1.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.11 
    vue-eslint-parser:  7.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.3 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.4.6

```

### Steps to reproduce
npm install
npm run serve

### What is expected?
It is expected that the project runs

### What is actually happening?
MacBook-Air-de-Tiago:will-not-run dallagnol$ npm run serve

> will-not-run@0.1.0 serve /Users/dallagnol/Documents/personal/will-not-run
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  Error: No valid exports main found for '/Users/dallagnol/Documents/personal/will-not-run/node_modules/colorette'
Error: No valid exports main found for '/Users/dallagnol/Documents/personal/will-not-run/node_modules/colorette'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/dallagnol/Documents/personal/will-not-run/node_modules/autoprefixer/lib/autoprefixer.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! will-not-run@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the will-not-run@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dallagnol/.npm/_logs/2020-07-06T01_42_14_129Z-debug.log

---
It looks like that there is a problem in colorette package, recently updated (now version 1.2.1). Manually installing the version 1.2.0 appears to fix the problem.

**Comment by gtsiolis** [comment]
Hi @tdallagnol! I could reproduce this using `node` `13.3.0`. This seems to be related to the `node` version you're using since using the LTS version (`12.18.2`) seems to be working ok for creating a project as well as running the project from the reproduction link you mentioned above.

**Suggetion:** Either update to the latest version (`14.5.0`) or more preferably use the LTS version.
