### ISSUE TITLE
Merge plugin-related navigation items

### ISSUE THREAD

**Issue by gtsiolis** [vuejs/vue-cli#5652]
### What problem does this feature solve?
The plugin development documentation sections are linked from a separate menu item at the top navigation, see _Plugin Dev Guide_. This makes it a) harder to use the top navigation on medium viewports and b) slower to locate the most relevant information regarding plugins or plugin development.

### What does the proposed change look like?
It could be worth considering merging the _Plugin Dev Guide_ with the _Plugins_ top navigation menu to provide more clear navigation and make the top navigation more accessible on small viewports. WDYT?

| Before (1)        | Before (2)           | After |
| ------------- |-------------|-----|
| ![nav-before-1](https://user-images.githubusercontent.com/120486/86595513-8332b600-bfa1-11ea-8de9-397faf4f53c4.png) | ![nav-before-2](https://user-images.githubusercontent.com/120486/86595516-8463e300-bfa1-11ea-8a63-667eab5303d3.png) | ![nav-after](https://user-images.githubusercontent.com/120486/86595521-85951000-bfa1-11ea-92c5-c4c45b99e02a.png) |

**Comment by sodatea** [comment]
Yeah, the last one looks much cleaner to me. Looks good!

**Comment by gtsiolis** [comment]
Thanks @sodatea! I've added https://github.com/vuejs/vue-cli/pull/5655 to resolve this, feel free to review or forward this to someone. 🏀 

/cc @NataliaTepluhina because https://github.com/vuejs/vue-cli/pull/2973

/cc @Akryum because https://github.com/vuejs/vue-cli/pull/1535
