### ISSUE TITLE
Impossible to create a build with a single js file with recent vue-cli

### ISSUE THREAD

**Issue by ericledonge** [vuejs/vue-cli#5659]
### Version
4.4.6

### Reproduction link
[https://github.com/ericledonge/vue-create-issue](https://github.com/ericledonge/vue-create-issue)

### Environment info
```
Mac OS 1.15.5
Node 14.5.0
@vue/cli 4.4.6
```

### Steps to reproduce
1) Generate an app with vue create

2) Create a vue.config.js with:

```
module.exports = {
  configureWebpack: {
    optimization: {
      splitChunks: false
    }
  },
  css: {
    extract: false
  }
};
```

3) Build the app

### What is expected?
A single app.js file

### What is actually happening?
A app.js  and an about.js file

Note: It is working fine with older apps generated by previous vue-cli versions.

**Comment by sodatea** [comment]
Add this to `babel.config.js`:

```
"plugins": ["dynamic-import-node"]
```
