### ISSUE TITLE
构建优化问题

### ISSUE THREAD

**Issue by Free-share** [vuejs/vue-cli#566]
#1 当vue-cli项目足够大的时候，整个项目全量构建的速度比较慢，我想通过增量构建的方式来发布部署，有比较好的解决方案吗
<!--

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
