### ISSUE TITLE
Can not install vue CLI on corporate environments due to inconsistent GraphQL license links

### ISSUE THREAD

**Issue by antonioaguilar** [vuejs/vue-cli#5663]
### Version
4.4.6

### Environment info
```
Environment Info:

  System:
    OS: Windows 7 6.1.7601
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1585L v5 @ 3.00GHz
  Binaries:
    Node: 12.1.0 - C:\nodejs\12.1.0\node.EXE
    Yarn: Not Found
    npm: 6.9.0 - C:\nodejs\12.1.0\npm.CMD
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
We have a corporate "tool" that allows us to request and import any NPM packages from the main public NPM registry so we could use in our internal web projects. 
When trying to pull the latest @vue/cli@4.4.6 our tool rejects importing the vue CLI because it can not determine the `graphql` or `flowtype` licenses from the provided URLs. See sample output below:

```
Artifact:                    NPM - @vue/cli@4.4.6
  Dependencies (1042)
    Dependency: NPM - @akryum/winattr@3.0.0
    Dependency: NPM - @apollo/federation@0.16.2
    Dependency: NPM - @apollo/protobufjs@1.0.4
    Dependency: NPM - @types/node@10.17.26
    Dependency: NPM - @apollographql/apollo-tools@0.4.8
    Dependency: NPM - @apollographql/graphql-language-service-interface@2.0.2
      RejectReasons (2)
        RejectReason:   97df2859-a2fc-409c-b8de-3400e49de908
          Type:      UNAPPROVED_LICENSE
          License:   Custom: https://github.com/graphql/graphql-language-service
        RejectReason:   b4dfef5d-6b4f-443d-92da-f213a12b145e
          Type:      UNKNOWN_LICENSE_FOUND
          License:   Custom: https://github.com/graphql/graphql-language-service
    Dependency: NPM - @apollographql/graphql-language-service-parser@2.0.2
      RejectReasons (2)
        RejectReason:   a159453b-5bea-4e30-a29f-2479b5d0009e
          Type:      UNAPPROVED_LICENSE
          License:   Custom: http://graphql.org/
        RejectReason:   afee07f0-c5ab-4c61-995f-c4d8747f43f1
          Type:      UNKNOWN_LICENSE_FOUND
          License:   Custom: http://graphql.org/
    Dependency: NPM - @apollographql/graphql-language-service-types@2.0.2
      RejectReasons (2)
        RejectReason:   89e14d6a-5374-4c7c-9b2a-4d3271943ade
          Type:      UNAPPROVED_LICENSE
          License:   Custom: https://flowtype.org/
        RejectReason:   81e44cf0-e487-4055-a3e2-c9a7b5420fba
          Type:      UNKNOWN_LICENSE_FOUND
          License:   Custom: https://flowtype.org/
    Dependency: NPM - @apollographql/graphql-language-service-utils@2.0.2
      RejectReasons (2)
        RejectReason:   c92d082f-f762-48f3-8775-2bce989e85e4
          Type:      UNAPPROVED_LICENSE
          License:   Custom: https://github.com/graphql/graphql-language-service
        RejectReason:   6dc5f6bf-1519-49cf-ba03-5884b3f15a5f
          Type:      UNKNOWN_LICENSE_FOUND
          License:   Custom: https://github.com/graphql/graphql-language-service
    Dependency: NPM - @apollographql/graphql-playground-html@1.6.26
    Dependency: NPM - @babel/code-frame@7.10.4
    Dependency: NPM - @babel/compat-data@7.10.4
    Dependency: NPM - @babel/core@7.10.4
    Dependency: NPM - @babel/generator@7.10.4
    Dependency: NPM - @babel/helper-annotate-as-pure@7.10.4
    Dependency: NPM - @babel/helper-builder-binary-assignment-operator-visitor@7.10.4
    Dependency: NPM - @babel/helper-compilation-targets@7.10.4
    Dependency: NPM - @babel/helper-create-class-features-plugin@7.10.4
```

If we check the URL for the `https://github.com/graphql/graphql-language-service` you can see the github repo is archived and this could be the reason why our tool is not able to fetch the license. If we check the NPM registry for the https://www.npmjs.com/package/graphql-language-service, we can see the `graphql-language-service` is now hosted in the github repo: https://github.com/graphql/graphiql

So, the inconsistency could be in the NPM dependency links provided by @vue/cli or by graphql. Could you please provide some feedback - this is currently preventing us from using the @vue/cli in our corporate enviroment. 

### What is expected?
To be able to install @vue/cli in our corporate enviroment

### What is actually happening?
Our internal tool is not able to detect and fetch the licenses for the graphql dependency in the @vue/cli and is therefore preventing us from pulling the latest version of the @vue/cli. 

---
Let me know if you think this is an issue that could be fixed on the @vue/cli side or if I need to contact the graphql team.

**Comment by sodatea** [comment]
It's this package using an outdated version of `@apollographql/graphql-language-service-interface`
https://github.com/apollographql/apollo-tooling/blob/cbf732fdcabed3ff4b962756695f8b0f6d21e98c/packages/apollo-language-server/package.json#L22

**Comment by antonioaguilar** [comment]
@sodatea is this something that needs to be fixed in graphql? Let me know and I can raise an issue on their package. Thanks.

**Comment by sodatea** [comment]
They need to update that line to `graphql-language-service-interface`
