### ISSUE TITLE
这个cli2如果多这个 是这样写，webpack.common.js webpack.dev.js webpack.demo.js等等然后package配置 webpack --config build/webpack.common.js && webpack --config build/webpack.component.js 那么cli3怎么写呢？

### ISSUE THREAD

**Issue by livelyPeng** [vuejs/vue-cli#5670]
### What problem does this feature solve?
这个cli2如果多这个 是这样写，webpack.common.js webpack.dev.js webpack.demo.js等等然后package配置 webpack --config build/webpack.common.js && webpack --config build/webpack.component.js 那么cli3怎么写呢？

### What does the proposed API look like?
这个cli2如果多这个 是这样写，webpack.common.js webpack.dev.js webpack.demo.js等等然后package配置 webpack --config build/webpack.common.js && webpack --config build/webpack.component.js 那么cli3怎么写呢？

**Comment by sodatea** [comment]
1. 请遵守 issue 模板
2. > 其次，Vue 的 issue 列表只接受 bug 报告或是新功能请求 (feature requests)。这意味着**我们不接受用法问题**。如果你开的 issue 不符合规定，它将会被**立刻关闭**。
