### ISSUE TITLE
怎么知道vue-cli生成项目脚手架 包含哪些功能

### ISSUE THREAD

**Issue by oridark** [vuejs/vue-cli#5677]
### What problem does this feature solve?
需要知道生成的vue create 生成的项目脚手架里集成了哪些脚手架功能，目前的文档里好像查不到，比如像html-webpack-plugin之类的插件，亦或者是webpack.DllReferencePlugin之类的功能

### What does the proposed API look like?
一份文档介绍

**Comment by sodatea** [comment]
https://cli.vuejs.org/zh/guide/webpack.html#%E5%AE%A1%E6%9F%A5%E9%A1%B9%E7%9B%AE%E7%9A%84-webpack-%E9%85%8D%E7%BD%AE
