### ISSUE TITLE
url path in css files to load static fonts is not correct after build with vue-cli.

### ISSUE THREAD

**Issue by wisetc** [vuejs/vue-cli#568]
I import font-awesome.css into main.js. It works well in dev mode. But when I build it using script `npm run build`, the fonts folder and css folder are separated in static folder and css can not load fonts correctly cause css use a path like url(static/fonts/xxxxx), which means fonts folder should be in the css folder or maybe root slash forgot in the path.
I can't reveal it cause I'm using a iPad right now, and I don't have a computer in my room. Sorry for that.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js). This is also unrelated to vue-cli

**Comment by wisetc** [comment]
I solved it by changing `assetsPublicPath` option of the configuration file from `'./'` to `'../'`. You are right, it's not bug. Thank you.
