### ISSUE TITLE
Update to Jest 26

### ISSUE THREAD

**Issue by jfbrennan** [vuejs/vue-cli#5680]
### What problem does this feature solve?
Right now Vue tests can't handle/verify anything that relates to Custom Elements (my app uses Custom Elements for UI bits and Vue for the overall application structure and state mgmt., this approach is becoming much more popular btw) because Vue CLI is using an outdated version of Jest. The newest version of Jest, version 26, now has support for Custom Elements.

### What does the proposed API look like?
Nothing, just update to Jest 26.

**Comment by krissrex** [comment]
Relevant: #5114
