### ISSUE TITLE
sass-loader update prependData is removed

### ISSUE THREAD

**Issue by ImJustAMan** [vuejs/vue-cli#5684]
### Version
4.4.6

### Environment info
```
sass-loader 9.0.2
```

### Steps to reproduce
sass-loader is updated. prependData is removed in favor the additionalData.

### What is expected?
I use prependData.

### What is actually happening?
it throw me an Error like options has an unknown property 'prependData'.

---
I just want doc will be update that I can use scss better

**Comment by sodatea** [comment]
But it's been updated. Have you refreshed the website?

https://cli.vuejs.org/zh/guide/css.html#%E5%90%91%E9%A2%84%E5%A4%84%E7%90%86%E5%99%A8-loader-%E4%BC%A0%E9%80%92%E9%80%89%E9%A1%B9
https://cli.vuejs.org/guide/css.html#passing-options-to-pre-processor-loaders

**Comment by ImJustAMan** [comment]
sorry about that. its because my browser cache.
