### ISSUE TITLE
How to import less modules with JSX?

### ISSUE THREAD

**Issue by wangbagang** [vuejs/vue-cli#569]
Hi, I am using Vue2 with JSX template, when I want to load the less as modules, but there got a little errors, such as 
```
import styles from './ListItem.less'
```
got the errors
```
 This relative module was not found:
* ./ListItem.less in ./src/pages/treatment/ListItem.js
```

my webpack loaders is 
```
     {
        test: /\.less$/,
        loader: 'style!css-loader?modules&importLoaders=2&localIdentName=[name]__[local]___[hash:base64:5]',
        include: [resolve('src'), resolve('test')]
      },
```

How to config can be make it to be worked?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

I'm not sure about what you're trying to do but webpack is telling you the file doesn't exist. Maybe it's in another folder
