### ISSUE TITLE
Invalid tag name "@vue-cli"

### ISSUE THREAD

**Issue by Vaintti** [vuejs/vue-cli#5691]
### Version
4.4.6

### Environment info
```
fish: Unknown command: vue
```

### Steps to reproduce
Install nvm
Install node 8, 12 or 14 with nvm
Try to run npm i -g @vue-cli

### What is expected?
Vue cli installs succesfully

### What is actually happening?
Npm throws error at you:
npm ERR! Invalid tag name "@vue-cli": Tags may not have any characters that encodeURIComponent encodes.

**Comment by sodatea** [comment]
It's `@vue/cli`

**Comment by Vaintti** [comment]
Ah thanks a lot and my bad 😂
