### ISSUE TITLE
Webpack5 Support

### ISSUE THREAD

**Issue by fxxjdedd** [vuejs/vue-cli#5692]
### What problem does this feature solve?
Is there any plan to support webpack5?

### What does the proposed API look like?
webpack5

**Comment by xiaolee55** [comment]
什么时候支持webpack5

**Comment by thefoxie** [comment]
@sodatea  This should get priority as the webpack 5 is stable now.

**Comment by sodatea** [comment]
Yeah I'm looking into it. It will take some time, because the changeset is huge.

**Comment by sodatea** [comment]
Supported in 5.0.0-alpha.0
