### ISSUE TITLE
Update version of eslint-loader used in cli-plugin-eslint

### ISSUE THREAD

**Issue by Amndeep7** [vuejs/vue-cli#5698]
### What problem does this feature solve?
vue cli (cli-plugin-eslint) 4.4.6 uses eslint-loader 2.2.1.  eslint-loader 2.2.1 does not support the 7.x release of eslint, which is the most recent version of eslint.  The latest version of eslint-loader is 4.0.2 which does support the 7.x release of eslint.  Can the version of eslint-loader used by cli-plugin-eslint be updated to the most recent version?  Word of caution that doing so will drop support for versions of eslint less than 6.x.  

### What does the proposed API look like?
No api change, just version change in package.json for cli-plugin-eslint.

**Comment by zhangzhao666** [comment]
good

**Comment by lianzhao** [comment]
Well, seems that `eslint-loader` [has been deprecated](https://github.com/webpack-contrib/eslint-loader/issues/337).

Maybe vue-cli v5 should migrate to [eslint-webpack-plugin](https://github.com/webpack-contrib/eslint-webpack-plugin)?

**Comment by Amndeep7** [comment]
I'm for it, but it seems like eslint-webpack-plugin only supports eslint v7 so it will be even more of a breaking change.  It's also not a drop-in replacement so some changes to configuration will need to be made but the docs have a little bit of advice on how to migrate between them at least.

**Comment by Amndeep7** [comment]
Should probably tag @sodatea as well to hear from them about when they think this should occur.

**Comment by sodatea** [comment]
Done in [v5.0.0-alpha.0](https://github.com/vuejs/vue-cli/releases/tag/v5.0.0-alpha.0)
