### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by SallyOne** [vuejs/vue-cli#57]
.vue file 

this is code

`<style>
    .regist {
        margin-top: 86px;
        border: 1px solid lightgray;
        border-radius: 4px;
        padding: 20px;
    }
    .regist-login-link {
        display: block;
        margin-top: 10px;
    }
    .login-icon {
        width: 100%;
        background: url('https://dn-coding-net-production-static.qbox.me/5aad72f4-a78e-433a-815b-3a991794f4ba.jpg') no-repeat;
        background-position: center center;
        overflow: hidden;
        overflow-y: hidden;
        height: 100vh;
    }
</style>
<template>
    <div class="login-icon">
    
    <div class="regist col-sm-4 col-sm-offset-4">
        <p class="regist-title">用户登陆</p>
         <validator name="validationLogin">
        <form role="form" novalidate>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="用户名"  v-validate:username="{minlength:5,maxlength:12,required: true}" autocomplete="off" v-on:focus="scope.setFormaaa($event)">
            </div>
            <div v-if="$validationLogin.username.dirty && $validationLogin.username.invalid">
                <p style="color: #ffffff">用户名不符合要求</p>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="密码"  v-validate:password="{minlength:5,maxlength:12,required:true}" autocomplete="off" v-on:focus="setFormaaa($event)">
            </div>
            <div v-if="$validationLogin.password.dirty && $validationLogin.password.invalid">
                <p style="color: #ffffff">密码不符合要求</p>
            </div>
            <div class="form-group">
                <input type="checkbox"><span>记住我</span>
                <a href="#" class="pull-right">找回密码</a>
            </div>
            <button type="button" class="btn btn-primary center-block" v-bind:disabled="$validationLogin.invalid" v-on:click="login()">登陆</button>
        </form>
        </validator>
        <a href="/regist" class="regist-login-link pull-right">没有账户？马上注册</a>
    </div>
    </div>
<template>
<script>
    export default {
        data() {
            retrn {
                username: '',
                password: ''
            }
        },
        methods: {
            setFormaaa(event) {
                console.log(1);
            }
            login() {
                console.log(1);
            }
        }
        
    }
</script>`

have problem `Uncaught TypeError: Cannot read property 'setFormaaa' of undefined(anonymous function) @ VM5242:3handler @ vue.common.js?e881:8108
VM5244:3 Uncaught TypeError: scope.setFormaaa is not a function(anonymous function) @ VM5244:3handler @ vue.common.js?e881:8108
7VM5249:3 Uncaught TypeError: scope.login is not a function`

**Comment by SallyOne** [comment]
`<script>
    export default {
        data() {
            retrn {
                username: '',
                password: ''
            }
        },
        methods: {
            setFormaaa(event) {
                console.log(1);
            }
            login() {
                console.log(1);
            }
        }
        
    }
</script>`

**Comment by SallyOne** [comment]
<script>
    export default {
        data() {
            retrn {
                username: '',
                password: ''
            }
        },
        methods: {
            setFormaaa(event) {
                console.log(1);
            }
            login() {
                console.log(1);
            }
        }
        
    }
</script>

**Comment by SallyOne** [comment]
export default {
        data() {
            return {
                username: '',
                password: ''
            }
        },
        methods: {
            setFormaaa(event) {
                console.log(1);
            }
            login() {
                console.log(1);
            }
        }
        
    }

**Comment by yyx990803** [comment]
You should at least isolate the issue and format the code properly. I don't debug your code for free.
