### ISSUE TITLE
Error in creating new project

### ISSUE THREAD

**Issue by nikhilbhavsar5895** [vuejs/vue-cli#5701]
Hi, I am facing this issue when I try to create the new project using the command vue create projectname
 command failed: npm install --loglevel error

![Screenshot from 2020-07-20 20-45-54](https://user-images.githubusercontent.com/61405192/87954462-0851bb00-caca-11ea-995c-52f536cb7dcf.png)

**Comment by sodatea** [comment]
Same issue as https://github.com/vuejs/vue-cli/issues/5669#issuecomment-656457179
