### ISSUE TITLE
verson 4.5.0 dosen't suport npm5.6.0

### ISSUE THREAD

**Issue by jerry000lin** [vuejs/vue-cli#5715]
### Version
4.5.0

### Environment info
```
npm 5.6.0
node 8.11.3
```

### Steps to reproduce
in npm 5.6.0

execute `npm install` with @vue/cli-service v4.5.0 

get error:

error in npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "npm:": npm:vue-loader@^16.0.0-beta.3

### What is expected?
npm install can be executed in npm5.6.0

### What is actually happening?
@vue/cli-service v4.5.0 dosen't support npm 5.6.0

---
Notice that package aliasing is support since npm 6.9.0

Will npm5.6.0 be supported again?

**Comment by sodatea** [comment]
Yeah, we can make it an optional dependency. Thanks for reporting this!

**Comment by Memeyan** [comment]
My personal solution it's just updated npm to version 6 and then it's just work
also, I suspect that when you install npm and node you use apt-get method directly on ubuntu, which causes that it's only installed you node 8 and npm 5, the resent version of a node is already 14
