### ISSUE TITLE
Building a vue library is including the @vue/cli-service build command in the output bundle

### ISSUE THREAD

**Issue by Robin-Hoodie** [vuejs/vue-cli#5717]
### Version
2.6.11

### Reproduction link
[https://github.com/Robin-Hoodie/vue-test-project](https://github.com/Robin-Hoodie/vue-test-project)

### Steps to reproduce
- `vue create test-project` (choose default preset with babel/eslint)
- Add `src/index.js` file which exports generated HelloWorld component `export * from ./components/HelloWorld.vue`
- Create `vue.config.js` file and add `webpack-bundle-analyzer` plugin to webpack config (this is just to inspect the bundle size)
- Change `build` command to `vue-cli-service build --target lib --name test-project src/index.js`
- Run `yarn build`
- Inspect generated `dist/report.html` file
- Notice `@vue/cli-service/lib/commands/build` is included in bundle

### What is expected?
Since `@vue/cli-service` is a `devDependency` I do not expect anything of this dependency to be included in the output bundle

### What is actually happening?
`@vue/cli-service/lib/commands/build` is included in the output bundle

---
I am developing a component library for internal use. I noticed the bundle was quite big and upon inspecting the output I noticed the `@vue/cli-service/lib/commands/build` was being included. 

I had already added quite a lot of components, which may be the cause for that dependency taking in a lot more space than in the test project I created (34.63 KB gzipped vs 1.25 KB gzipped)

I used `@vue/cli-service@4.3.1` to generate the above project.

**Comment by sodatea** [comment]
It's used as an entry so you'll see it in the stats.

Meanwhile, all the contents of those files are bundled into the final dist files. So it still makes sense to declare them as `devDependencies` because in production you only use the files under `dist/` and none of them would actually `require` `@vue/cli-service/*`.

FYI, here's what's included in the bundle:
https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/build/entry-lib-no-default.js
https://github.com/vuejs/vue-cli/blob/v4.3.1/packages/%40vue/cli-service/lib/commands/build/entry-lib-no-default.js (`~entry` is the alias for the command line argument `src/index.js`)
So it's actually very tiny. The size stats in the report are mostly due to the entry file but the analyzer failed to show them in detail.

**Comment by Robin-Hoodie** [comment]
@sodatea I am not completely following, let me give you some more background:

`webpack-bundle-analyzer` reports `@vue/cli-service/lib/commands/build` to be included in the main library bundle. 

In my original problem I saw the following (gzipped) size:
Main bundle size: 68.49 KB of which `@vue/cli-service/lib/commands/build` took in 34.63 KB

When requiring this library bundle in another application, and then inspecting that bundle with `webpack-bundle-analyzer`, the total size of the library bundle is almost the same size (68.35KB, 0.14 KB less)

If `webpack-bundle-analyzer` fails to report this correctly for the library bundle itself, would it then also report this wrongly when actually requiring this as a dependency? 

When included in another bundle, I would expect its size to be reported as 33.86 KB (68.49 KB - 34.63 KB)

**Comment by sodatea** [comment]
With your test project, I don't see such big chunks:

```
Webpack Bundle Analyzer saved report to /Users/soda/Test/vue-test-project/dist/report.html
  File                            Size                  Gzipped

  dist/test-project.umd.min.js    5.64 KiB              2.04 KiB
  dist/test-project.umd.js        17.55 KiB             4.70 KiB
  dist/test-project.common.js     17.16 KiB             4.61 KiB
  dist/test-project.css           0.17 KiB              0.13 KiB
```

**Comment by sodatea** [comment]
> If `webpack-bundle-analyzer` fails to report this correctly for the library bundle itself, would it then also report this wrongly when actually requiring this as a dependency?

It might. Because they're both inferred from the same source map.

**Comment by sodatea** [comment]
So, as I just found out, there's a "Show content of concatenated modules" option in the webpack bundle analyzer UI, check it and you'll see a more detailed chunk graph.

![image](https://user-images.githubusercontent.com/3277634/88786521-35d2ee80-d1c5-11ea-9ff6-7e050190605b.png)

**Comment by Robin-Hoodie** [comment]
Aha perfect, that indeed shows me that the actual code in there is my own sourcecode that I wrote myself. Hence why it's so much bigger than in the test project.

Thanks for digging into this @sodatea , much appreciated!
