### ISSUE TITLE
hot module replacement seems to get stuck on css optimization

### ISSUE THREAD

**Issue by keithn** [vuejs/vue-cli#572]
Steps to reproduce

vue init webpack blah
all the defaults except nightwatch
npm install
npm run dev

running on windows 10

detects the change, but doesn't update the webpage, the console just says

Starting to optimize CSS...

every time it detects a change

if I hit f5, then the change is visible, but just won't auto update.

**Comment by loveshullf** [comment]
我也碰到类似的问题
我使用element-ui，引入了css文件，
运行之后，浏览器没有错误，
界面就是不能显示，一片空白：
![image](https://user-images.githubusercontent.com/15190244/29770843-71edd8e8-8c23-11e7-9743-87fc5d99f095.png)

命令行显示：
![image](https://user-images.githubusercontent.com/15190244/29770540-39727164-8c22-11e7-9a5e-e29a08d68c96.png)

**Comment by joustava** [comment]
@keithn had the same issue, seems the configuration in `build/dev-server.js` loads production configuration when running  `npm run dev`

**Comment by keithn** [comment]
thanks @joustava ,  this was exactly my problem!
