### ISSUE TITLE
Style imports with web components as build target

### ISSUE THREAD

**Issue by sebastiandittrich** [vuejs/vue-cli#5726]
### Version
4.5.0

### Reproduction link
[https://github.com/sebastiandittrich/vue-cli-issue-reproduction](https://github.com/sebastiandittrich/vue-cli-issue-reproduction)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  Binaries:
    Node: 12.5.0 - ~\laragon\bin\nodejs\node-v12\node.EXE
    Yarn: Not Found
    npm: 6.9.0 - ~\laragon\bin\nodejs\node-v12\npm.CMD   
  Browsers:
    Chrome: 84.0.4147.89
    Edge: Spartan (44.19041.1.0)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.4.6
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.4.6
    @vue/cli-plugin-babel: ~4.4.0 => 4.4.6
    @vue/cli-plugin-router:  4.4.6
    @vue/cli-plugin-vuex:  4.4.6
    @vue/cli-service: ~4.4.0 => 4.4.6
    @vue/cli-shared-utils:  4.4.6
    @vue/component-compiler-utils:  3.2.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.2.0
    vue: ^2.6.11 => 2.6.11
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.3
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Run `npm install`
2. Run `npm run serve`
    - Notice That the app background is RED
3. Run `npm run build`
    -  Open `dist/demo.html` in your browser
    - Notice that the background is WHITE

### What is expected?
The `dist/demo.html` file opened in your browser should include the `assets/main.css` in some way, in order for the app being shown with a red background, just like it was in development.

### What is actually happening?
The background is white, and the contents of `assets/main.css` aren't anywhere in the dom tree.

---
Please note that the contents of `assets/main.css` are actually included in the built `dist/wc-test.js` file. If you are searching for `#app`, you will find this line in the file: 

```js
exports.push([module.i, "#app{background:red}", ""]);
```

But for some reason, this line has absolutely no effect.

**Comment by rumblefrog** [comment]
My scenario is similar but not sure if related to this, or vue-loader.

I'm loading in an SCSS file via import and making it available globally through a property in mixins. During development mode, the content in the style tag in the head has barely any of the stylings in the SCSS file. Yet, when building for production, the dist CSS contains all of the styles.

**Comment by sodatea** [comment]
Use `<style src="./assets/main.css"></style>` instead of import css files in the script block.

Because the styles need to be processed by `vue-loader` to be web-component-compatible. When you import it in the script block, it's merely processed by the `css-loader` and not aware of the web-component context.

**Comment by sebastiandittrich** [comment]
@sodatea Thank you for your reply! I have simplified the issue for others to better understand what is happening. In this simple case this is a perfectly valid fix, but it is not applicable if you are relying on stylesheets that are getting imported by modules loaded through `node_modules`. You will have to manually go through each `import` in the module and add a `<style>` tag for each of them, repeating the process on each update. Is there an easier way to do this?
