### ISSUE TITLE
vue-cli · Failed to download repo vuejs-templates/webpack: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by ashwin9801** [vuejs/vue-cli#5727]
### Version
4.5.0

### Environment info
```
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.89
    Edge: Spartan (44.17763.831.0)
  npmPackages:
    vue:  2.6.11
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
I honestly have no idea how to since I am completely new to this.

### What is expected?
To create a folder and to initialize the webpack template in the project folder.

### What is actually happening?
vue-cli · Failed to download repo vuejs-templates/webpack: Client network socket disconnected before secure TLS connection was established

is returned

---
When I try to run the command vue init webpack clientfolder, the line "vue-cli · Failed to download repo vuejs-templates/webpack: Client network socket disconnected before secure TLS connection was established" is shown.

The same happens when I try  to install msnodesqlv8 via npm.

Since I am new to VueJS or the JavaScript world for that matter, I am not sure how to navigate this problem. Please help me.

Thanks in advance

**Comment by sodatea** [comment]
Please check your network settings. It's a network issue rather than Vue CLI issue.

Meanwhile, we recommend you to use `@vue/cli` and `vue create` rather than `vue init` to initialize projects. `vue init` is considered legacy, though it still works, it won't receive active support from us.
