### ISSUE TITLE
when I do the command 'npm run dev'  ，i find the error.  I dont  know if the version of node

### ISSUE THREAD

**Issue by zhhshen** [vuejs/vue-cli#573]
shendeMacBook-Pro:koa-learn shen$ npm run dev

> koa-learn@1.0.0 dev /Users/shen/myWorks/koa-learn
> node build/dev-server.js

fs.js:1646
      binding.lstat(baseLong);
              ^

Error: ENOENT: no such file or directory, lstat '/Users/shen/myWorks/koa-learn/test'

0 info it worked if it ends with ok
    at Object.realpathSync (fs.js:1646:15)
    at resolve (/Users/shen/myWorks/koa-learn/build/webpack.base.conf.js:8:13)
    at Object.<anonymous> (/Users/shen/myWorks/koa-learn/build/webpack.base.conf.js:40:35)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! koa-learn@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the koa-learn@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shen/.npm/_logs/2017-08-29T02_43_29_680Z-debug.log
shendeMacBook-Pro:koa-learn shen$ vi /Users/shen/.npm/_logs/2017-08-29T02_43_29_680Z-debug.log
shendeMacBook-Pro:koa-learn shen$ node -v
v8.0.0
shendeMacBook-Pro:koa-learn shen$ vue-cli -v
-bash: vue-cli: command not found
shendeMacBook-Pro:koa-learn shen$ npm view vue-cli version
2.8.2
shendeMacBook-Pro:koa-learn shen$ npm -v
5.0.4
shendeMacBook-Pro:koa-learn shen$

**Comment by posva** [comment]
This is not related to vue-cli... You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

BTW, you should update your node version
