### ISSUE TITLE
Supporting RFC <script setup>

### ISSUE THREAD

**Issue by boonyasukd** [vuejs/vue-cli#5730]
### What problem does this feature solve?
Evan recently implemented several features into `vue-next/compiler-sfc`, among them is `<script setup>`, which has already been introduced to `vite`, but doesn't seem to be supported by `vue-cli` just yet. Introducing this feature to `vue-cli` will help with the adoption of such feature to a wider audience.

### What does the proposed API look like?
All possible variants (in JS, or TS) have already been described [here](https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-script-setup.md) as part of the RFC.

**Comment by sodatea** [comment]
Supported in the latest version.

If you encounter any bug, please raise an issue [in the vue-loader repository](https://new-issue.vuejs.org/?repo=vuejs/vue-loader).
