### ISSUE TITLE
use location.search report core-js error

### ISSUE THREAD

**Issue by FeiBam** [vuejs/vue-cli#5732]
### Version
4.4.6

### Reproduction link
[https://github.com/FeiBam/Picture-Gallery/blob/master/main.js](https://github.com/FeiBam/Picture-Gallery/blob/master/main.js)

### Environment info
```
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.4.6
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.4.6
    @vue/cli-plugin-babel: ~4.4.0 => 4.4.6
    @vue/cli-plugin-eslint: ~4.4.0 => 4.4.6
    @vue/cli-plugin-router:  4.4.6
    @vue/cli-plugin-vuex:  4.4.6
    @vue/cli-service: ~4.4.0 => 4.4.6
    @vue/cli-shared-utils:  4.4.6
    @vue/component-compiler-utils:  3.2.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    vue: ^2.6.11 => 2.6.11
    vue-axios: ^2.1.5 => 2.1.5
    vue-eslint-parser:  7.1.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.3
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
in main.js try to found QueryString
 
console.log(location.seacrh)

### What is expected?
search = '?token=eyJuYW1lIjoiZmx5Ym9vbSJ9:1k1Jz6:iX06zwMBBV464ECYhhg1M_8l0Lw'

### What is actually happening?
These dependencies were not found:

* core-js/modules/es.regexp.exec in ./src/main.js
* core-js/modules/es.string.search in ./src/main.js

To install them, you can run: npm install --save core-js/modules/es.regexp.exec core-js/modules/es.string.search

**Comment by FeiBam** [comment]
my browser url 
http://127.0.0.1:8080/?token=eyJuYW1lIjoiZmx5Ym9vbSJ9:1k1Jz6:iX06zwMBBV464ECYhhg1M_8l0Lw

**Comment by sodatea** [comment]
It's because babel detected the usage of `.search` and inferred that that might be a reference to the  `String.prototype.search` function, so it automatically injects the corresponding polyfills.

Solution:
Either install `core-js` as your project dependency or disable the auto polyfill injection feature via the `usage` option as described at https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/babel-preset-app#usebuiltins
