### ISSUE TITLE
Use @babel/eslint-parser instead of babel-eslint

### ISSUE THREAD

**Issue by DRoet** [vuejs/vue-cli#5734]
### What problem does this feature solve?
`babel-eslint` has been deprecated into a new module `@babel/eslint-parser`, see [more info](https://github.com/babel/babel-eslint#note-babel-eslint-is-now-babeleslint-parser-and-has-moved-into-the-babel-monorepo)

### What does the proposed API look like?
Now that the new parser has finally been released (7.11.0) it might be time to migrate over

**Comment by sodatea** [comment]
Cool. I'll check it out.

**Comment by danger89** [comment]
I just create a new project from scratch. For some reason I still have the old "babel-eslint" put into in my package.json, when I created a nice VueJS v3 app.
