### ISSUE TITLE
eslintrc.js parserOptions has no parser key after creating the project with eslint and typescript

### ISSUE THREAD

**Issue by zhouxinyong** [vuejs/vue-cli#5745]
### Version
4.5.0

### Reproduction link
[https://github.com/zhouxinyong/vue-cli-issue/blob/master/.eslintrc.js](https://github.com/zhouxinyong/vue-cli-issue/blob/master/.eslintrc.js)

### Environment info
```
System:
    OS: macOS 10.15.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Not Found
    Firefox: Not Found
    Safari: 13.1.2
  npmPackages:
    @ant-design-vue/babel-helper-vue-transform-on:  1.0.1 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.5.0 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.5.0 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.0 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.0 
    @vue/cli-plugin-router: ~4.5.0 => 4.5.0 
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.0 
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.0 
    @vue/cli-service: ~4.5.0 => 4.5.0 
    @vue/cli-shared-utils:  4.5.0 
    @vue/compiler-core:  3.0.0-rc.5 
    @vue/compiler-dom:  3.0.0-rc.5 
    @vue/compiler-sfc: ^3.0.0-0 => 3.0.0-rc.5 
    @vue/compiler-ssr:  3.0.0-rc.5 
    @vue/component-compiler-utils:  3.2.0 
    @vue/eslint-config-standard: ^5.1.2 => 5.1.2 
    @vue/eslint-config-typescript: ^5.0.2 => 5.0.2 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/reactivity:  3.0.0-rc.5 
    @vue/runtime-core:  3.0.0-rc.5 
    @vue/runtime-dom:  3.0.0-rc.5 
    @vue/shared:  3.0.0-rc.5 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^7.0.0-0 => 7.0.0-beta.0 
    typescript: ~3.9.7 => 3.9.7 
    vue: ^3.0.0-0 => 3.0.0-rc.5 
    vue-eslint-parser:  7.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.3 (16.0.0-beta.4)
    vue-router: ^4.0.0-0 => 4.0.0-beta.4 
    vue-style-loader:  4.1.2 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^4.0.0-0 => 4.0.0-beta.4 
  npmGlobalPackages:
    @vue/cli: 4.5.0
```

### Steps to reproduce
1. yarn add @vue/cli@next
2. vue ui
3. choose vue version 3 (version 2 is the same)
4. choose typescript,  eslint with standard
5. create

### What is expected?
.eslintrc.js parserOptions has key parser
which value is @typescript-eslint/parser

### What is actually happening?
.eslintrc.js parserOptions has no key parser

**Comment by sodatea** [comment]
It's set here https://github.com/vuejs/eslint-config-typescript/blob/9b3245240f3c97b46c3e0435b6ac1ed6041b732d/index.js#L8

**Comment by zhouxinyong** [comment]
You can look at here [https://github.com/zhouxinyong/vue-cli-issue/blob/master/.eslintrc.js](https://github.com/zhouxinyong/vue-cli-issue/blob/master/.eslintrc.js) .
The generated file has no ` parser: '@typescript-eslint/parser'`, is this a bug?
@sodatea

**Comment by sodatea** [comment]
The generated config extends from `@vue/eslint-config-typescript/recommended`, so the `parserOptions`  from that package is merged into the final configuration. You don't have to explicitly set it.

**Comment by zhouxinyong** [comment]
> so the parserOptions from that package is merged into the final configuration. You don't have to explicitly set it.

but in the created repo above,when you clone and open in vscode
1. yarn install
2. edit a ts file like main.ts, add some blank lines at the end
then you can see yarn serve can show error：

![image](https://user-images.githubusercontent.com/15569753/89482987-9ec1f400-d7cd-11ea-807c-df46d0db99d1.png)

vscode has no error message:
![image](https://user-images.githubusercontent.com/15569753/89483253-2c9ddf00-d7ce-11ea-9cf2-3073dbbb3ebb.png)

after I edit .eslintrc.js, add `parser: '@typescript-eslint/parser'`, then it work well as expected:
![image](https://user-images.githubusercontent.com/15569753/89483366-7a1a4c00-d7ce-11ea-9a2f-cf47b6f15f8d.png)
![image](https://user-images.githubusercontent.com/15569753/89483578-ff9dfc00-d7ce-11ea-8d24-b7a7e71b8088.png)


@sodatea something may be wrong in `@vue/eslint-config-typescript/recommended`?

**Comment by sodatea** [comment]
The error has nothing to do with the parser option. It disappears only because of this bug https://github.com/vuejs/vue-cli/issues/3065#issuecomment-454373989
