### ISSUE TITLE
Assertion Failed error on server stop

### ISSUE THREAD

**Issue by wonbyte** [vuejs/vue-cli#5748]
### Version
4.4.6

### Environment info
```
Platform: macOS 10.15.6
VS Code version: 1.47.3
```

### Steps to reproduce
1. start a vue app via the vscode terminal.
2. use ctrl   c to stop the server.

### What is expected?
App should exit and not crash. 

### What is actually happening?
 DONE  Compiled successfully in 270ms                                                                                                                                       4:59:49 PM

  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.86.57:8080/

^CAssertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 174.
[1]    15803 abort      npm run serve

---
I first noticed this bug today and originally thought it was a Vetur plugin issue. Here is the link to the issue I opened https://github.com/vuejs/vetur/issues/2114 which they told me was a vue-cli issue.

**Comment by sodatea** [comment]
I'm sorry but we do need the full output of `vue info`. Because as I've investigated, this may be related to https://github.com/webpack/webpack/issues/10037, which is a webpack/chokidar issue that only happens in certain Node versions.

**Comment by wonbyte** [comment]
@sodatea that dawned on me last night too that I may have used an older version of node via `nvm` by accident. I just tried again with the latest Node 14 and there was no error. I don't recall what version I used, so if this is a known issue in webpack it can probably be closed out. Unless it would be helpful for you to have me try to reproduce and provide that info?
