### ISSUE TITLE
vue-cli-server is not HMR

### ISSUE THREAD

**Issue by zxltjl** [vuejs/vue-cli#5752]
### Version
4.4.4

### Reproduction link
[ https://github.com/zxltjl/project.git]( https://github.com/zxltjl/project.git)

### Environment info
```
"dependencies": {
        "ant-design-vue": "^1.6.2",
        "axios": "^0.19.2",
        "core-js": "^3.6.5",
        "light-storage": "^0.2.2",
        "moment": "^2.26.0",
        "nprogress": "^0.2.0",
        "register-service-worker": "^1.7.1",
        "tinymce": "^5.3.2",
        "vue": "^2.6.11",
        "vue-router": "^3.3.4",
        "vuex": "^3.4.0",
        "webpack-dev-server": "^3.11.0",
        "xlsx": "^0.16.2"
    },
    "devDependencies": {
        "@vue/cli-plugin-babel": "^4.4.4",
        "@vue/cli-plugin-eslint": "^4.4.4",
        "@vue/cli-plugin-pwa": "^4.4.4",
        "@vue/cli-plugin-unit-jest": "^4.4.4",
        "@vue/cli-service": "^4.4.4",
        "@vue/test-utils": "^1.0.3",
        "antd-theme-webpack-plugin": "^1.3.6",
        "babel-core": "^7.0.0-bridge.0",
        "babel-eslint": "^10.1.0",
        "babel-jest": "^26.0.1",
        "eslint": "^7.2.0",
        "eslint-plugin-vue": "^6.2.2",
        "less": "^3.11.3",
        "less-loader": "^6.1.1",
        "lint-staged": "^10.2.10",
        "mockjs": "^1.1.0",
        "qs": "^6.9.4",
        "vue-svg-loader": "^0.16.0",
        "vue-template-compiler": "^2.6.11"
    },
```

### Steps to reproduce
vue create project->npm install -> npm run serve

### What is expected?
when i change the code in anywhere,the page can auto update  

### What is actually happening?
but when i change the code ,the page is not change

**Comment by sodatea** [comment]
I'm sorry but I don't think the repo matches your environment info, and I can't reproduce the issue with that repo.

**Comment by zxltjl** [comment]
follow is projet‘s package.json:

{
  "name": "project",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "core-js": "^3.6.5",
    "vue": "^2.6.11"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.4.0",
    "@vue/cli-plugin-eslint": "~4.4.0",
    "@vue/cli-service": "~4.4.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^6.2.2",
    "vue-template-compiler": "^2.6.11"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

**Comment by zxltjl** [comment]
it's package.json for me to use  "vue create project" create project ,but it not HMR

**Comment by sodatea** [comment]
But I can't reproduce the issue. Did you use `cnpm` to install the dependencies or have symlinks in `node_modules`? Did you install the dependencies on a network drive? Both may cause problems for HMR.

**Comment by andrewmnlv** [comment]
I've had the same issue. After removing node_modules folder and clearing npm cache it works fine.

**Comment by sodatea** [comment]
Closing due to lack of response.
