### ISSUE TITLE
Cannot install from NPM

### ISSUE THREAD

**Issue by vkozelka** [vuejs/vue-cli#5756]
### Version
4.4.6

### Environment info
```
Docker image: node:12.15
```

### Steps to reproduce
1. Run docker image node:12.15
2. Run npm install -g @vue/cli (or i tried @vue//cli because it was transformed to %2f if one slash used)

### What is expected?
Installed CLI service

### What is actually happening?
Got error
1 slash used - E404, 
2 slashes used - There is no package.json file

**Comment by sodatea** [comment]
https://status.npmjs.org/
The NPM registry is down.

**Comment by sertaco** [comment]
I am also getting `404 Not Found - GET https://registry.npmjs.org/@vue%2fcli-plugin-eslint - Not found` when I do `npm npm i @vue/cli`

**Comment by sertaco** [comment]
oh thanks, just saw down announcement

**Comment by bugbounty69** [comment]
thank u so much was getting the same error

**Comment by felix2015GitHub** [comment]
Getting the same issue, too

**Comment by anfield343** [comment]
Getting the same issue, too
<img width="654" alt="Screen Shot 2020-08-06 at 13 43 00" src="https://user-images.githubusercontent.com/15375857/89522979-ca070c00-d7ea-11ea-813c-fb825afab532.png">

**Comment by Karloski** [comment]
I'm also seeing this error in Yarn, so this might be a more general issue.

![image](https://user-images.githubusercontent.com/1800877/89524335-48a87d00-d7dc-11ea-938b-3099b69f73cc.png)

**Comment by hello-chenchen** [comment]
+ 1, and we are build release package, and today is the final deadline. 
it's really hard to me.

**Comment by logicelf** [comment]
I had this issue as well. It's back up now (for me at least) and `npm install -g @vue/cli` works as expected.

**Comment by sodatea** [comment]
Seems it's been resolved now.
