### ISSUE TITLE
初始化项目失败

### ISSUE THREAD

**Issue by l-moondream** [vuejs/vue-cli#5758]
版本：4.4.6
说明：重新卸载安装多次，一直这样，不知道有没有遇见过得大佬
报错信息：
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'C:\Users\admin\AppData\Roaming\npm\node_modules\@vue\cli\bin\vue.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:840:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
![Snipaste_2020-08-06_18-15-59](https://user-images.githubusercontent.com/53330236/89520745-eb7aee80-d810-11ea-95b7-98714a797702.png)

**Comment by amzrk2** [comment]
Same as #5756 
https://status.npmjs.org/ - Issues accessing npmjs.com and installing scoped packages
npm registry is down

**Comment by sodatea** [comment]
NPM 已恢复。

**Comment by shinchanZ** [comment]
> 版本：4.4.6
> 说明：重新卸载安装多次，一直这样，不知道有没有遇见过得大佬
> 报错信息：
> internal / modules / cjs / loader.js：960
> throw err;
> ^
> 
> 错误：找不到模块'C：\ Users \ admin \ AppData \ Roaming \ npm \ node_modules @ vue \ cli \ bin \ vue.js'
> -[90m at Function.Module._resolveFilename（internal / modules / cjs / loader.js ：957：15）。[39m
> ... [90m at Function.Module._load（internal / modules / cjs / loader.js：840：27）。[39m
> ... [90m at Function.executeUserEntryPoint [as runMain]（内部/模块/run_main.js:74:12).[39m...[90m
> at internal / main / run_main_module.js：18：47。[39m {
> code： [32m'MODULE_NOT_FOUND'。[39m，
> requireStack：[]
> }
> ![Snipaste_2020-08-06_18-15-59](https://user-images.githubusercontent.com/53330236/89520745-eb7aee80-d810-11ea-95b7-98714a797702.png)

你好，请问一下这个问题你是怎么解决的
