### ISSUE TITLE
Please add an option to select available code editors to use using the vuecli

### ISSUE THREAD

**Issue by LokotamaTheMastermind** [vuejs/vue-cli#5767]
## What problem does this feature solve?
This is because when I open the project in code editor it opens in `PyCharm IDE`, which I use for python not javascript and I don't know how to configure it to say otherwise. It also doesn't use `VSCode` which is on my user `%PATH%` variable. Also some people don't install apps to their `C:` drive so it has to be a bit dynamic. Thanks!

### Kinda something like this

```js

options = [
'Path to Application',
]

var code_editor = options.current()

if code_editor === options {
// Pls let this be in a dynamic way not fixed.
// Open the particular application then save the configuration.
}

// Also add the option to add new applications using their physical path
```

**Comment by sodatea** [comment]
We use [launch-editor](https://github.com/yyx990803/launch-editor/) to open editors from the UI, so you can customize your preferred editor by setting the `EDITOR` or `VISUAL` environment variable.
