### ISSUE TITLE
vue-cli Initialization of project errors

### ISSUE THREAD

**Issue by xugyc** [vuejs/vue-cli#577]
Use vue-cli new projects, the use of npm run start / npm run dev should be into the development mode? But in fact the use of the production model, so as the primary user I do not know why the use of hot overload can not be resolved, I do not know whether it is specialized This design, or mistakes?
---var webpackConfig = process.env.NODE_ENV === 'testing' || 'production'
  ? require('./webpack.prod.conf')
  : require('./webpack.dev.conf')

**Comment by LinusBorg** [comment]
This was a  bug we had for a day in the webpack template, it has been fixed already.

Sorry for any inconvenience this may have caused :(
