### ISSUE TITLE
vue create fails with TypeError

### ISSUE THREAD

**Issue by bpasson** [vuejs/vue-cli#5775]
Using the vue cli to create a vue 2/3 project fails to complete.

### Version
4.5.3

### Environment info
```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 12.15.0 - ~/.sdkman/candidates/java/current/languages/js/bin/node
    Yarn: Not Found
    npm: 6.13.4 - ~/.sdkman/candidates/java/current/languages/js/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Not Found
    Firefox: Not Found
    Safari: 12.1.2
  npmGlobalPackages:
    @vue/cli: 4.5.3
```
### Steps to reproduce
Make sure you have GraalVM 20.1.0 installed and afterwards ran npm install -g @vue/cli after that.

Next run 'vue create .'

### What is expected?
A bootstrapped project.

### What is actually happening?
You get a TypeError: Cannot read property '1' of null on line 455 of GeneratorAPI.js

---
The issue seems to be with the following method:

```
function extractCallDir () {
  // extract api.render() callsite file location using error stack
  const obj = {}
  Error.captureStackTrace(obj)
  const callSite = obj.stack.split('\n')[3]
  const fileName = callSite.match(/\s\((.*):\d :\d \)$/)[1]
  return path.dirname(fileName)
}
```

**Comment by sodatea** [comment]
This function uses the non-standard V8 API `Error.captureStackTrace` and relies on V8's internal stack trace format, so it's very likely to break when executed by GraalVM.

I haven't used GraalVM so I don't know how to fix it. Any help would be appreciated.

**Comment by jrnewton** [comment]
I was not able to reproduce this problem on Linux (using [this docker image](https://hub.docker.com/r/raonigabriel/graalvm-playground) as a starting point).  Could it be a macOs + GraalVM issue? 

Vue Environment Info:
```
  System:
    OS: Linux 5.4 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
  Binaries:
    Node: 12.15.0 - /opt/graalvm-ce-java11-20.1.0/bin/node
    Yarn: Not Found
    npm: 6.13.4 - /opt/graalvm-ce-java11-20.1.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: 4.5.9
```

node --version:graalvm
```
GraalVM CE Native Polyglot Engine Version 20.1.0
Java Version 11.0.7
Java VM Version GraalVM 20.1.0 Java 11 CE
GraalVM Home /opt/graalvm-ce-java11-20.1.0
  Installed Languages:
    JavaScript version 20.1.0
    LLVM       version 20.1.0
  Installed Tools:
    Agent Script            version 0.6
    Code Coverage           version 0.1.0
    CPU Sampler             version 0.4.0
    CPU Tracer              version 0.3.0
    Heap Allocation Monitor version 0.1.0
    Insight                 version 0.6
    Chrome Inspector        version 0.1
    Language Server         version 0.1
    Memory Tracer           version 0.2
```

I also tried GraalVM with Java 8 but same result.

**Comment by bpasson** [comment]
Issue doesn't occur any more in newest version. Closing the issue.
