### ISSUE TITLE
Unexpected end of JSON input while parsing near '...C8NRdIrPMRwyANLmrGM4P'

### ISSUE THREAD

**Issue by cosmicGenesis** [vuejs/vue-cli#5781]
### Version
4.5.3

### Environment info
```
npm ver. 6.14.4
node ver.  12.18.4
```

### Steps to reproduce
npm install -g @vue/cli

### What is expected?
@vue/cli installing

### What is actually happening?
Unexpected end of JSON input while parsing near '...C8NRdIrPMRwyANLmrGM4P'

---
@vue/cli simply won't download, keeps failing with "Unexpected end of JSON input while parsing near '...C8NRdIrPMRwyANLmrGM4P' ".

does anyone know why?

heres the log:

120 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...C8NRdIrPMRwyANLmrGM4P'
120 verbose stack     at JSON.parse (<anonymous>)
120 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
120 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
120 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
121 verbose cwd C:\Users\liad2\Desktop
122 verbose Windows_NT 10.0.18363
123 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@vue/cli"
124 verbose node v12.18.3
125 verbose npm  v6.14.6
126 error Unexpected end of JSON input while parsing near '...C8NRdIrPMRwyANLmrGM4P'
127 verbose exit [ 1, true ]

**Comment by sodatea** [comment]
It's just bad network or bad npm cache. Try `npm cache clean -f` and install again.
