### ISSUE TITLE
initDev() Not being called in the browser

### ISSUE THREAD

**Issue by d-pollard** [vuejs/vue-cli#5785]
### Version
3.0.0-rc.5

### Reproduction link
[https://github.com/d-pollard/testing-vue3](https://github.com/d-pollard/testing-vue3)

### Steps to reproduce
Vue CLI generate a new app;
npm run serve

open dev tools; see that `window.__VUE__` isn't set

### What is expected?
[initDev()](https://github.com/vuejs/vue-next/blob/master/packages/vue/src/dev.ts#L4) should run (setting `__VUE__` and  running `setDevtoolsHook` with `__VUE_DEVTOOLS_GLOBAL_HOOK__`)

### What is actually happening?
These fields aren't being set; `initDev` is being called when we build instead

---
I can add `import 'vue/dist/vue.esm-bundler';` in main.js and it'll set properly

**Comment by d-pollard** [comment]
@sodatea - would love to contribute a PR for this; as it stands a fix from the users perspective would be something like this:

### vue.config.js

```javascript
module.exports = {
  runtimeCompiler: process.env.NODE_ENV === 'development'
};
```

The alternative would be to check the environent we're running in here: https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/base.js#L118

```javascript
webpackConfig.resolve
        .alias
          .set(
            'vue$',
            options.runtimeCompiler || process.env.NODE_ENV === 'development'
              ? 'vue/dist/vue.esm-bundler.js'
              : '@vue/runtime-dom'
          )
```

Please advise which approach you'd prefer; alternatively, suggest a fix and I'll implement it

**Comment by sodatea** [comment]
@d-pollard See https://github.com/vuejs/vue-cli/pull/5788
