### ISSUE TITLE
[vue build] `filename.js` in config file does not work.

### ISSUE THREAD

**Issue by gluons** [vuejs/vue-cli#580]
I've used `vue build ./src/index.js --dist ./dist` with `--lib` and config file.

```javascript
module.exports = {
	filename: {
		js:  '<my new file name>.js'
	}
};
```

I always get `index.js` in `./dist` folder.

Seems that output file name is replaced by entry file name?  
https://github.com/vuejs/vue-cli/blob/c5b2ea3a13e32b331b65991421d6755002820a6b/bin/vue-build#L235-L236

**Comment by LinusBorg** [comment]
Seems to be a bug, thanks for the report!
