### ISSUE TITLE
vue info execute error, UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by StringKe** [vuejs/vue-cli#5809]
### Version
4.5.4

### Environment info
```
can't execute

macOS: 10.15.6 (19G2021
node: v12.17.0
npm: 6.14.4
yarn: 1.22.4
```

### Steps to reproduce
execute `vue info`

### What is expected?
execution succeed

### What is actually happening?
execution failed

---
[![asciicast](https://asciinema.org/a/St6JL8xAo2W2QZP9B3m6rHikP.svg)](https://asciinema.org/a/St6JL8xAo2W2QZP9B3m6rHikP)

**Comment by sodatea** [comment]
See https://github.com/tabrindle/envinfo/issues/184
