### ISSUE TITLE
babel-preset-env

### ISSUE THREAD

**Issue by herzinger** [vuejs/vue-cli#581]
It's about the deprecated warnings in npm install. I think they are self-explanatory, straight forward and simple enough to solve, so here's a copy:

> npm WARN deprecated babel-preset-latest@6.24.1: 💥  preset-latest accomplishes the same task as babel-preset-env. 🙏  Please install it with 'npm install babel-preset-env --save-dev'. '{ "presets": ["latest"] }' to '{ "presets": ["env"] }'. For more info, please check the docs: http://babeljs.io/docs/plugins/preset-env 👌. And let us know how you're liking Babel at @babeljs on 🐦                              
> npm WARN deprecated babel-preset-es2017@6.24.1: We're really excited that you're trying to use ES2017 syntax, but instead of making more yearly presets, Babel has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. Give us a follow @babeljs to get more updates         
> npm WARN deprecated babel-preset-es2016@6.24.1: We're really excited that you're trying to use ES2016 syntax, but instead of making more yearly presets, Babel has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. Give us a follow @babeljs to get more updates         

It's something minor and provably not urgent, but I searched the issues and there was nothing about it, so I decided to post it.

**Comment by posva** [comment]
Can you open this on the template repository showing this warning, please?

**Comment by herzinger** [comment]
It's not a template, this shows when installing the CLI with 'npm install -g vue-cli' on bash on Windows.

**Comment by posva** [comment]
Ah, I see. It seems to be happening in one of the dependencies. I don't see which one though 🙁

**Comment by herzinger** [comment]
Oh, that makes sense. Well, I don't think it's very critical, and I suppose most packages will make the change soon enough. Thanks for the replies.
