### ISSUE TITLE
Duplicate root app (id="app") when creating vue3 project

### ISSUE THREAD

**Issue by kirianguiller** [vuejs/vue-cli#5813]
### Version
4.5.4

### Reproduction link
[https://github.com/kirianguiller/vue3-issue](https://github.com/kirianguiller/vue3-issue)

### Environment info
```
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: Not Found
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 79.0
  npmGlobalPackages:
    @vue/cli: 4.5.4

```

### Steps to reproduce
- Create a vue3 app with vue CLI 4.5.4
- Run 'npm run serve'

### What is expected?
Only one "id='app'" html element

### What is actually happening?
Two "id='app'" html element

---
These duplicates are an issue i if we add some CSS styling for padding (for instance) as they will be duplicated and the padding will be summed. 

I don't know if the problem come from the vue@cli default setup or from the vuejs3 mounting method.

PS : This duplication is not occuring for vue2 app.

**Comment by 9mm** [comment]
I also have this... what is this originating from?

**Comment by Manidos** [comment]
**vue**: version 3.0.0-rc.10
**@vue/cli**: version 4.5.4

The same issue when creating default templates from `vue ui`.

![1](https://user-images.githubusercontent.com/16019131/92302995-d4a3f500-ef92-11ea-986f-12d7fef8adeb.png)
