### ISSUE TITLE
when time support to upgrade webpack 3

### ISSUE THREAD

**Issue by kinanson** [vuejs/vue-cli#583]
I saw webpack 3 release for a while.I think that can imporve some feature for develope stage.I have some question for when time upgrade to webpack 3

**Comment by posva** [comment]
We're working on it for the templates, but you should be able to easily upgrade your existing project if you have one. The upgrade path of webpack is easy

**Comment by kinanson** [comment]
Why official not default offer webpack 3?If that is so easy?I can't understand for this.
