### ISSUE TITLE
error  in  ie11

### ISSUE THREAD

**Issue by 1o1w1** [vuejs/vue-cli#5839]
### Version
4.5.4

### Reproduction link
[https://github.com/1o1w1/temp_vue-cli4](https://github.com/1o1w1/temp_vue-cli4)

### Environment info
```
os: win 10  
broswer: ie 11
```

### Steps to reproduce
yarn  
npm run serve 
open it in ie 11 

### What is expected?
no error

### What is actually happening?
error in ie 11

---

**Comment by 1o1w1** [comment]
reproduction demo created  using vue-cli with vue3.

something wrong when i open it with  ie11.
![image](https://user-images.githubusercontent.com/22697045/91791180-0d676580-ec45-11ea-8c51-dad4ec06d94a.png)

**Comment by sodatea** [comment]
Vue 3 hasn't shipped an IE11 compatible build yet.
