### ISSUE TITLE
can not install vue-cli

### ISSUE THREAD

**Issue by choudewh** [vuejs/vue-cli#584]
When i install vue-cli, i get a error "Unexpected end of input at 1:46728" like this:
![tim 20170908121624](https://user-images.githubusercontent.com/3983407/30195968-bb35d2b6-948f-11e7-996f-b19412264dce.png)

**Comment by egoist** [comment]
Just install it again and it should be fine 😄

**Comment by allybi-design** [comment]
i got the same problem....

`npm ERR! path C:\Users\dj ally bi\AppData\Roaming\npm\node_modules\vue-cli\node_modules\fsevents\node_modules\abbrev\package.json

npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\dj ally bi\AppData\Roaming\npm\node_modules\vue-cli\node_modules
\fsevents\node_modules\abbrev\package.json'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\dj ally bi\AppData\Roaming\npm\node_modules\vue-cli\node_modu
les\fsevents\node_modules\abbrev\package.json'
npm ERR!     at Error (native)
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\dj ally bi\\AppData\\Roaming\\npm\\node_modules\\vu
e-cli\\node_modules\\fsevents\\node_modules\\abbrev\\package.json\'\n    at Error (native)',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\dj ally bi\\AppData\\Roaming\\npm\\node_modules\\vue-cli\\node_modules\\fsevents\\node_modules\\abbr
ev\\package.json' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dj ally bi\AppData\Roaming\npm-cache\_logs\2017-09-08T10_19_55_113Z-debug.log

**Comment by rufusl** [comment]
This might be related to this npm bug: **https://github.com/npm/npm/issues/18380**
Try downgrading to npm 5.3 until it is fixed.
