### ISSUE TITLE
Using 1 worker with 2048MB memory limit

### ISSUE THREAD

**Issue by rajanb03** [vuejs/vue-cli#5841]
### Version
4.5.4

### Reproduction link
[https://github.com/vuejs/vue-cli/issues/](https://github.com/vuejs/vue-cli/issues/)

### Environment info
```
Vue
```

### Steps to reproduce
npm run serve

### What is expected?
npm run serve command run successfully

### What is actually happening?
Starting type checking service...
Using 1 worker with 2048MB memory limit
40% building 50/53 modules 3 active C:\xampp\htdocs\vueapp\node_modules

**Comment by sodatea** [comment]
Please follow the instructions on the issue helper page and fill in the necessary information for reproduction.
I can't help with such vague descriptions.

**Comment by miromarchi** [comment]
I think this might be related to this https://stackoverflow.com/questions/55258355/vue-clis-type-checking-service-ignores-memory-limits
