### ISSUE TITLE
Library build target causes the `install` method to be missing 

### ISSUE THREAD

**Issue by Namchee** [vuejs/vue-cli#5846]
### Version
4.5.4

### Reproduction link
[https://github.com/Namchee/tetikus](https://github.com/Namchee/tetikus)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 AMD Ryzen 3 1200 Quad-Core Processor
  Binaries:
    Node: 12.18.2 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.83
    Edge: Spartan (44.19041.423.0)
  npmPackages:
    @ant-design-vue/babel-helper-vue-transform-on:  1.0.1
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.5.4
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.5.4
    @vue/cli-plugin-babel: ^4.5.4 => 4.5.4
    @vue/cli-plugin-eslint: ^4.5.4 => 4.5.4
    @vue/cli-plugin-router:  4.5.4
    @vue/cli-plugin-typescript: ^4.5.4 => 4.5.4
    @vue/cli-plugin-vuex:  4.5.4
    @vue/cli-service: ^4.5.4 => 4.5.4
    @vue/cli-shared-utils:  4.5.4
    @vue/compiler-core:  3.0.0-rc.5
    @vue/compiler-dom:  3.0.0-rc.5
    @vue/compiler-sfc: ^3.0.0-beta.1 => 3.0.0-rc.5
    @vue/compiler-ssr:  3.0.0-rc.5
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-typescript: ^5.0.2 => 5.0.2
    @vue/preload-webpack-plugin:  1.1.2
    @vue/reactivity:  3.0.0-rc.5
    @vue/runtime-core:  3.0.0-rc.5
    @vue/runtime-dom:  3.0.0-rc.5
    @vue/shared:  3.0.0-rc.5
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^7.0.0-alpha.0 => 7.0.0-beta.0
    typescript: ~3.9.3 => 3.9.7
    vue: ^3.0.0-beta.1 => 3.0.0-rc.5
    vue-eslint-parser:  7.1.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.3 (16.0.0-beta.5)
    vue-style-loader:  4.1.2
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Clone the repository
2. Execute the build command `npm run build`
3. Install the library in other Vue 3 project (or clone [this](https://github.com/Namchee/tetikus-playground/settings) vite app, install deps, and execute `npm run dev`)

### What is expected?
The plugin is installed successfully 

### What is actually happening?
The browser logs that a plugin must be a function or an object with `install` method.

It works fine when the default object is installed and executed in the same repo, pretty sure this is a build issue.

**Comment by sodatea** [comment]
It's expected when you import a CommonJS module from an ES module with **Vite**.

`import Tetikus from 'tetikus'` gets the module record of the `tetikus` module, which is the same as `require('tetikus')`. So you need to `app.use(Tetikus.default)`.

Strictly speaking, a CommonJS module with the `__esModule: true` flag is still a CommonJS module.
So you can't expect the transpiled CommonJS module to work in the same way as a native ES module.

**Comment by sodatea** [comment]
After a second thought, I think rollup's failing to optimize such a CommonJS module in a more intuitive way is the root cause.

**Comment by sodatea** [comment]
https://github.com/rollup/plugins/pull/501

It's fixed in @rollup/plugin-commonjs v15. But vite currently depends on v14.
CC @antfu @underfin, I think it needs to be updated.

It's a breaking change though.

**Comment by underfin** [comment]
Yeah.The deps is already updated.
