### ISSUE TITLE
npm run dev Error for Null projects

### ISSUE THREAD

**Issue by shuaiZend** [vuejs/vue-cli#585]
1. npm install vue-cli -g
2. vue init wepack index
3. cd index
4. npm install
5. npm run dev
notie error:
'''
 DONE  Compiled successfully in 2570ms                                                                         21:43:59

> Listening at http://localhost:8080

(node:22397) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
(node:22397) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
'''
i used node v8.4.0
#476

**Comment by posva** [comment]
This belongs to the template. Please make sure there isn't already an open issue for that there before opening it though

**Comment by shuaiZend** [comment]
fiexd.
1.reinstall nodejs to v6.11
2.npm install webpack
:)
