### ISSUE TITLE
vue.config.js compliation issues

### ISSUE THREAD

**Issue by faithfulojebiyi** [vuejs/vue-cli#5850]
### Version
4.5.4

### Reproduction link
[https://github.com/faithfulojebiyi/vueconfigjs/blob/master/vue.config.js](https://github.com/faithfulojebiyi/vueconfigjs/blob/master/vue.config.js)

### Environment info
```

  System:
    OS: Windows 10 10.0.18362
    CPU: (2) x64 AMD E-300 APU with Radeon(tm) HD Graphics
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.83
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @ant-design-vue/babel-helper-vue-transform-on:  1.0.1
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.5.4
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.5.4
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.4
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.4
    @vue/cli-plugin-router: ~4.5.0 => 4.5.4
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.4
    @vue/cli-service: ^4.5.4 => 4.5.4
    @vue/cli-shared-utils:  4.5.4
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-standard: ^5.1.2 => 5.1.2
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.2.0
    bootstrap-vue: ^2.16.0 => 2.16.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    portal-vue:  2.1.7
    vue: ^2.6.12 => 2.6.12
    vue-eslint-parser:  7.1.0
    vue-functional-data-merge:  3.1.0
    vue-hot-reload-api:  2.3.4
    vue-loader: ^15.9.3 => 15.9.3 (16.0.0-beta.5)
    vue-router: ^3.2.0 => 3.4.3
    vue-style-loader: ^4.1.2 => 4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.4.0 => 3.5.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce

Run: npm run serve
Observe failure / error

### What is expected?
Successful build 

### What is actually happening?
CLIserve fails

 ERROR  Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
Error: [VueLoaderPlugin Error] No matching use for vue-loader is found.
Make sure the rule matching .vue files include vue-loader in its use.
    at VueLoaderPlugin.apply (C:\Users\MRS OJEBIYI\Desktop\apps\Dev\oyfims-app\node_modules\vue-loader\lib\plugin-webpack4.js:59:13)
    at webpack (C:\Users\MRS OJEBIYI\Desktop\apps\Dev\oyfims-app\node_modules\webpack\lib\webpack.js:51:13)
    at serve (C:\Users\MRS OJEBIYI\Desktop\apps\Dev\oyfims-app\node_modules\@vue\cli-service\lib\commands\serve.js:163:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oyfims-app@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oyfims-app@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MRS OJEBIYI\AppData\Roaming\npm-cache\_logs\2020-09-07T03_34_14_771Z-debug.log

**Comment by sodatea** [comment]
I don't understand why you are adding all these rules. Except for the `lintOnSave`, `productionSourceMap` and `alias` part, all other configurations in your `vue.config.js` are set by default in Vue CLI.

So you are basically adding a second instance of VueLoaderPlugin to webpack, and that causes the error.

**Comment by faithfulojebiyi** [comment]
why would you close and issue without getting a response from the person that opened it. its bullshit. you asked a question why did i add all this configurations you did not allow me to respond to that and you just closed my issue.

**Comment by sodatea** [comment]
I've provided the answer.

> So you are basically adding a second instance of VueLoaderPlugin to webpack, and that causes the error.

Delete that part and the error disappears.

**Comment by sodatea** [comment]
And, this part:
> Except for the `lintOnSave`, `productionSourceMap` and `alias` part, all other configurations in your `vue.config.js` are set by default in Vue CLI.

What I was saying is, besides the problematic `new VueLoaderPlugin()` expression, those other configurations are also safe to be removed, and I would recommend you to do so.

**Comment by faithfulojebiyi** [comment]
i was having this issues before i added the vue. config file

vue?vue&type=style&index=0&lang=scss&%20(./node_modules/@vue/cli-service/node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=style&index=0&lang=scss&)%20Module%20build%20failed%20(from%20./node_modules/sass-loader/dist/cjs.js):%20SassError:%20Undefined%20variable:%20"$gray-600".

**Comment by sodatea** [comment]
I apologize for my tone in the previous comment.
But I close the issue only because it's resolved.

**Comment by sodatea** [comment]
Then it's a new issue. I can't debug it by merely looking at the config file, please provide a full reproduction.

**Comment by faithfulojebiyi** [comment]
it's all cool once i npm run serve again and i still run into issues after deleting the rules ill let you know
