### ISSUE TITLE
Propose a 'back to last step' when setting up project with vue-cli

### ISSUE THREAD

**Issue by hyaocuk** [vuejs/vue-cli#5853]
### What problem does this feature solve?
When we are using vue-cli to create a project from scratch, we are looking for a feature which would enable us to step back to the last step when we made some incorrect or unsatisfied options without terminating the whole process.

### What does the proposed API look like?
I think features are to be added:
1. key maps to the 'step back' action, like `q`
2. while the user hit step back, current recorded options are to be removed, and the previous questions and options show up.

**Comment by sodatea** [comment]
But there *is* a `Previous` button when setting up projects.

![image](https://user-images.githubusercontent.com/3277634/92423612-4f982600-f1b4-11ea-8c58-fedc4a478f7c.png)

**Comment by timstats91** [comment]
I don't know why you closed this. The question referred to vue cli, no the ui
