### ISSUE TITLE
Vue dev tools not working

### ISSUE THREAD

**Issue by tylik1** [vuejs/vue-cli#5854]
### Version
4.5.4

### Environment info
```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.83
    Edge: Not Found
    Firefox: 78.0.1
    Safari: 13.1.2
  npmGlobalPackages:
    @vue/cli: 4.5.4

```

### Steps to reproduce
Create project with vue-cli

### What is expected?
Vue dev tools should discover veiw app and allow to debug it

### What is actually happening?
Vue dev tools is inactive

**Comment by sodatea** [comment]
What's the created project like? We need a reproduction.

**Comment by tylik1** [comment]
Oops. It was vue 3, which was causing this issue. Closing...
