### ISSUE TITLE
ValidationError: "swSrc" is not a supported parameter.

### ISSUE THREAD

**Issue by aronsuarez** [vuejs/vue-cli#5856]
### Version
4.5.4

### Environment info
```
Mac OS 10.15.6
Node 12.16.2
```

### Steps to reproduce
Add vue cli pwa plugin and use this config:

pwa: {
    workBoxPluginMode: 'InjectManifest',
    workboxOptions: {
      swSrc: './src/service-worker.js',
      swDest: 'service-worker.js',
    },
  },

### What is expected?
When build the project in production a running sevice worker.

### What is actually happening?
Got this error: ValidationError: "swSrc" is not a supported parameter.

**Comment by sodatea** [comment]
It's `workboxPluginMode` not `workBoxPluginMode`
