### ISSUE TITLE
Lazy Loading is kinda not working.

### ISSUE THREAD

**Issue by MisterJ936** [vuejs/vue-cli#5857]
### Version
4.5.4

### Reproduction link
[https://github.com/MisterJ936/MyPortFolio/tree/master/jenuelganawed_home](https://github.com/MisterJ936/MyPortFolio/tree/master/jenuelganawed_home)

### Environment info
```
 System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 14.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - D:\Program Files\yarn\bin\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.83
    Edge: Spartan (44.19041.423.0), Chromium (85.0.564.44)
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
npm install

npm run serve

and try goind to different pages

### What is expected?
I created a route with importing components to be lazy loaded. Im expecting that when I go to other route. It will download the data or chunks. 

### What is actually happening?
It is prefetching the chunk. this means that when the site is opened. All chunks are downloaded.

**Comment by sodatea** [comment]
Prefetching happens at browser idle time, rather than on the initial load. https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ
So it can still be considered a lazy-loaded chunk.

**Comment by MisterJ936** [comment]
thanks a lot 👍🏻
