### ISSUE TITLE
When is this file used，‘dev-client.js’

### ISSUE THREAD

**Issue by zhump** [vuejs/vue-cli#586]
Is this file used for hot loading? When to use it ？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

It's used internally by the scripts, so you don't need to worry 🙂
