### ISSUE TITLE
vue 3 + ts + router - new project - Component not loading.. inconsistent hot reload, throwing error when making changes to Home component

### ISSUE THREAD

**Issue by pranay-91** [vuejs/vue-cli#5863]
### Version
4.5.4

### Environment info
```
mac os: 10.15.4
node: 14.5.0
```

### Steps to reproduce
- create a new project
- npm run serve
- initially threw error to enable plugins form decorators and decorators-legacy in babel
- second time np run serve, successfully compiles
- HelloWorld Component is missing.
- developer console throwing warning: Failed to resolve component.
- making changes to Home Component throws same decorators error.

### What is expected?
build successfully
load components succesfully

### What is actually happening?
build is sometime successful sometime fails
some components are not loading

---
- could be issue with Decorators?
- could be issue with Router Component?

# warning in dev console
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Failed to resolve component: HelloWorld 
  at <Home onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
warn @ runtime-core.esm-bundler.js?5c40:38

# warning when compile fails

 ERROR  Failed to compile with 1 errors                               8:28:12 pm

 error  in ./src/views/Home.vue

Module Error (from ./node_modules/vue-loader-v16/dist/index.js):
This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (7:0)

 @ ./src/router/index.ts 3:0-37 7:13-17
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.0.149:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

**Comment by pranay-91** [comment]
It seems to be the issue with Decorators. Using without Decorators , `defineComponent` is working fine.
Other candidates are`vue-class-component` or the `vue-router`?

**Comment by sodatea** [comment]
It's caused by the recent releases of vue-loader. I'm looking into it.

**Comment by emiyalee1005** [comment]
Having the same problem here

**Comment by shijunti19** [comment]
me too

**Comment by yimzk** [comment]
+1
