### ISSUE TITLE
Getting EUNSUPPORTEDPROTOCOL error when creating a project (node v10)

### ISSUE THREAD

**Issue by HuubVerbeek** [vuejs/vue-cli#5864]
### Version
4.5.4

### Environment info
```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (2) x64 AMD EPYC 7232P 8-Core Processor
  Binaries:
    Node: 10.21.0 - /usr/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 68.12.0esr
  npmGlobalPackages:
    @vue/cli: 4.5.4


```

### Steps to reproduce
vue create project

these are the settings ->

Vue CLI v4.5.4
? Please pick a preset: Manually select features
? Check the features needed for your project: Choose Vue version, Babel, Router,
 Vuex, Linter
? Choose a version of Vue.js that you want to start the project with 3.x
? Use history mode for router? (Requires proper server setup for index fallback
in production) Yes
? Pick a linter / formatter config: Prettier
? Pick additional lint features: Lint on save
? Where do you prefer placing config for Babel, ESLint, etc.? In package.json
? Save this as a preset for future projects? (y/N)

### What is expected?
Should create a new project. 

### What is actually happening?
Vue CLI v4.5.4

✨  Creating project in /var/www/html/vueproject/project.
🗃  Initializing git repository...
⚙️  Installing CLI plugins. This might take a while...

npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "npm:": npm:vue-loader@^16.0.0-beta.3
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-09T12_52_41_782Z-debug.log

 ERROR  command failed: npm install --loglevel error

---
This is the log --> 

Note: the npm version at line 7 is not concurrent with the version of npm (6.14.8) in my environment. 

0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v10.21.0
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, $
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [ '/usr/bin/node',
6 verbose cli   '/usr/bin/npm'
6 verbose cli   'install',
6 verbose cli   '--loglevel',
6 verbose cli   'error' ]
7 info using npm@5.8.0
8 info using node@v10.21.0
9 verbose npm-session a38ef51317bccdb1
10 silly install runPreinstallTopLevelLifecycles
11 silly preinstall project@0.1.0
12 info lifecycle project@0.1.0~preinstall: project@0.1.0
13 silly install loadCurrentTree
14 silly install readLocalPackageData
15 silly install loadIdealTree
16 silly install cloneCurrentTreeToIdealTree
17 silly install loadShrinkwrap
18 silly install loadAllDepsIntoIdealTree
19 http fetch GET 304 https://registry.npmjs.org/@vue%2fcli-plugin-babel 188ms $
20 silly pacote range manifest for @vue/cli-plugin-babel@~4.5.0 fetched in 207ms
21 http fetch GET 304 https://registry.npmjs.org/@vue%2fcli-plugin-router 235ms$
22 http fetch GET 304 https://registry.npmjs.org/@vue%2fcli-plugin-vuex 235ms ($
23 silly pacote range manifest for @vue/cli-plugin-router@~4.5.0 fetched in 238$
24 silly pacote range manifest for @vue/cli-plugin-vuex@~4.5.0 fetched in 240ms
25 http fetch GET 304 https://registry.npmjs.org/@vue%2fcli-plugin-eslint 241ms$
26 silly pacote range manifest for @vue/cli-plugin-eslint@~4.5.0 fetched in 244$
27 http fetch GET 304 https://registry.npmjs.org/@vue%2fcli-service 258ms (from$
28 silly pacote range manifest for @vue/cli-service@~4.5.0 fetched in 266ms
29 silly saveTree project@0.1.0
30 verbose stack Error: Unsupported URL Type "npm:": npm:vue-loader@^16.0.0-bet$
30 verbose stack     at unsupportedURLType (/usr/lib/nodejs/npm-package-arg/npa$
30 verbose stack     at fromURL (/usr/lib/nodejs/npm-package-arg/npa.js:250:13)
30 verbose stack     at Function.resolve (/usr/lib/nodejs/npm-package-arg/npa.j$
30 verbose stack     at Object.keys.map (/usr/share/npm/lib/install/deps.js:445$
30 verbose stack     at Array.map (<anonymous>)
30 verbose stack     at BB.resolve.then (/usr/share/npm/lib/install/deps.js:444$
30 verbose stack     at tryCatcher (/usr/lib/nodejs/bluebird/js/release/util.js$
30 verbose stack     at Promise._settlePromiseFromHandler (/usr/lib/nodejs/blue$
30 verbose stack     at Promise._settlePromise (/usr/lib/nodejs/bluebird/js/rel$
30 verbose stack     at Promise._settlePromiseCtx (/usr/lib/nodejs/bluebird/js/$
30 verbose stack     at Async._drainQueue (/usr/lib/nodejs/bluebird/js/release/$
30 verbose stack     at Async._drainQueues (/usr/lib/nodejs/bluebird/js/release$
30 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib$
30 verbose stack     at runCallback (timers.js:705:18)
30 verbose stack     at tryOnImmediate (timers.js:676:5)
30 verbose stack     at processImmediate (timers.js:658:5)
31 verbose cwd /var/www/html/vueproject/project
32 verbose Linux 4.19.0-10-amd64
33 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--loglevel" "error"
34 verbose node v10.21.0
35 verbose npm  v5.8.0
36 error code EUNSUPPORTEDPROTOCOL

**Comment by HuubVerbeek** [comment]
Thanks in advance!

**Comment by sodatea** [comment]
It's like this one: https://github.com/vuejs/vue-cli/issues/5669#issuecomment-656526082

You have multiple node/npm installations and the old one somehow takes higher precedence.
