### ISSUE TITLE
transpileDependencies field does not work with package intalled by cnpm

### ISSUE THREAD

**Issue by littlee** [vuejs/vue-cli#5875]
### Version
4.5.6

### Environment info
```
System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Edge: Not Found
    Firefox: Not Found
    Safari: 13.1.2
```

### Steps to reproduce
create a vue/cli project
```
vue create my-app
```
install some esm module with cnpm, like swiper
```
cnpm i -S swiper
```
update vue.config.js
```
module.exports = {
  transpileDependencies: ['swiper', 'dom7']
}
```
build the app
```
npm run build
```
check the dist folder, there are still some `const` keywords

### What is expected?
package installed by cnpm should work with transpileDependencies

### What is actually happening?
package installed by cnpm do not work with transpileDependencies

**Comment by sodatea** [comment]
https://cli.vuejs.org/guide/troubleshooting.html#symbolic-links-in-node-modules
