### ISSUE TITLE
Inline project creation works differently on Windows and MacOS

### ISSUE THREAD

**Issue by de-soul** [vuejs/vue-cli#5878]
### Version
4.5.6

### Reproduction link
[https://gist.github.com/de-soul/c886ced22396ffa448f57978554d5960#file-vue-cli_create-full-project_bug-js](https://gist.github.com/de-soul/c886ced22396ffa448f57978554d5960#file-vue-cli_create-full-project_bug-js)

### Environment info
```
WINDOWS

C:\Develop>vue info

Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.102
    Edge: Spartan (44.19041.423.0), Chromium (85.0.564.51)
  npmGlobalPackages:
    @vue/cli: Not Found

C:\Develop>vue -V
@vue/cli 4.5.6

MACOS

~/Develop $ vue info

Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 70.0.1
    Safari: 13.1.2
  npmGlobalPackages:
    @vue/cli: 4.5.6
```

### Steps to reproduce
Try to run this command on Windows and macOS with npm and vue-cli

vue create test-app --inlinePreset '{"useConfigFiles":true,"plugins":{"@vue\/cli-plugin-babel":{},"@vue\/cli-plugin-pwa":{},"@vue\/cli-plugin-router":{"historyMode":true},"@vue\/cli-plugin-vuex":{},"@vue\/cli-plugin-eslint":{"config":"prettier","lintOn":["save","commit"]}},"vueVersion":"2","cssPreprocessor":"stylus"}'

### What is expected?
Successful project creation

### What is actually happening?
The project is successfully created in macOS.
In Windows it gives an error:  
ERROR  CLI inline preset is not valid JSON: '{useConfigFiles:true,plugins:{@vue\/cli-plugin-babel:{},@vue\/cli-plugin-pwa:{},@vue\/cli-plugin-router:{historyMode:true},@vue\/cli-plugin-vuex:{},@vue\/cli-plugin-eslint:{config:prettier,lintOn:[save,commit]}},vueVersion:2,cssPreprocessor:stylus}'

---
Inline project creation works differently on Windows and MacOS
P.S. Github not displayed backslashes correctly, so correct command and error output in my gist available by the link on the top

**Comment by sodatea** [comment]
On Windows, you need to escape double quotes in command line arguments, while the slash doesn't need to be escaped.

**Comment by sodatea** [comment]
The command-line arguments are processed by the shell first, so technically it's a caveat of PowerShell, not Vue CLI.
