### ISSUE TITLE
import css 文件不会通过 postcss

### ISSUE THREAD

**Issue by liujunchina** [vuejs/vue-cli#588]
js文件:
`import './test.scss'`

test.scss:
`body{
  display: flex;
}`

![image](https://user-images.githubusercontent.com/6283929/30318997-3ab01728-97e1-11e7-8302-519359b48cdd.png)
不会通过 autoprefixer 

vue文件内的style 标签是正常的

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
