### ISSUE TITLE
 @vue/cli-service was packed into my output lib

### ISSUE THREAD

**Issue by GoldSubmarine** [vuejs/vue-cli#5882]
### Version
4.5.6

### Environment info
```
win 10
node v12.16.1
yarn v1.22.4

```

### Steps to reproduce
I ran the `vue ui` command, and import my project by the ui page, then choose the task compile,it's actual command is `vue-cli-service build --target lib --inline-vue --entry package/index.js`

### What is expected?
exclude the package `@vue/cli-service` from output file

### What is actually happening?
I found the `@vue/cli-service` was packed into my output lib, but it's too big, is this normal?

**Comment by GoldSubmarine** [comment]
![image](https://user-images.githubusercontent.com/22909744/93248357-503b4880-f7c2-11ea-9c51-ced4fd4b296e.png)

**Comment by sodatea** [comment]
Not really. See explanation here: https://github.com/vuejs/vue-cli/issues/5717#issuecomment-665567802
