### ISSUE TITLE
Please update the CLI for V3 support

### ISSUE THREAD

**Issue by swaggyolafson** [vuejs/vue-cli#5886]
### What problem does this feature solve?
Currently the CLI version 4.5.6 shows up with the preview version of V3.

It should get a proper update to install the released V3 version per default.

![image](https://user-images.githubusercontent.com/69816887/93705437-97f10580-fb1d-11ea-80d3-ff40509ba7aa.png)

### What does the proposed API look like?
The CLI should not come up with a "preview" anymore. Further V3 should be picked by default.

**Comment by swaggyolafson** [comment]
With that said, TS should be the default now too :)

**Comment by painbfb** [comment]
Could not agree more, also if ts is the default, Could this error be fixed in vscode? 

`Cannot find module '@/components/Hello.vue' or its corresponding type declarations.ts(2307)`

I am searching everywhere for a solution on this error.

All I want to is have a `hello vue3+ ts` project running in vs code. 

What a hard  experience.

**Comment by DRoet** [comment]
I don't agree with changing these defaults. vue 3 still uses the `@next` tag on npm untill the end of the year so I don't think it's ready to be the new default. 

Vue 3 is also still a javascript-first framework. I like typescript, but I think it should remain opt-in for the foreseeable future.

**Comment by sodatea** [comment]
I'd go with the `preview` word until all the major dependencies used to scaffold the project reach stable. At the moment many are still in Beta or RC.

**Comment by thomassittig** [comment]
It's nearly a week after the official release of  the v3 of vuejs, and the cli is still in the preview mode. Is there any update what the update roadmap says? 
Without a useful cli, i can directly switch back to react for upcoming projects ;)

**Comment by sodatea** [comment]
Choice of words should not affect the usefulness of the CLI.

**Comment by TiredFalcon** [comment]
> It's nearly a week after the official release of the v3 of vuejs

It's now apparently more than 5 months later, and I haven't used Vue in more than a year so I had no idea about any of this.
When creating a project with vue-cli, I wasn't sure whethe Vue 3 was released or not, or if I could use it reliably for a project.

So, if v3 is out, why does `vue-cli` still say "(Preview)" for Vue 3.x?

**Comment by CodingItWrong** [comment]
I wrote a free online book that includes a Vue tutorial, and I'm hesitant to update it to Vue 3 while the CLI still says "Vue 3 preview". I'd like to hear some clarity from the Vue core team on the stability of using Vue CLI with Vue 3 before I update it.

**Comment by sodatea** [comment]
It's quite stable. I'll update it soon after I come back from my holiday.

**Comment by sodatea** [comment]
Released as v4.5.13.
