### ISSUE TITLE
vue-cli构建Library时能否减小生成的文件体积

### ISSUE THREAD

**Issue by summer0101** [vuejs/vue-cli#5888]
### What problem does this feature solve?
通过vue-cli构建Library时有没有什么方式能够减小生成的.umd.min.js的体积，或者是否支持esm格式的压缩方式

### What does the proposed API look like?
-

**Comment by sodatea** [comment]
1. 请详细描述需求，目前的体积已经尽可能小了
2. ESM 格式需要等 webpack 支持
