### ISSUE TITLE
Vue add apollo is failing

### ISSUE THREAD

**Issue by Patrick-Spiegel** [vuejs/vue-cli#5893]
### Version
4.5.6

### Reproduction link
[https://google.com](https://google.com)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.19041
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - node_modules\.bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.121
    Edge: Spartan (44.19041.423.0)
  npmPackages:
    @fortawesome/vue-fontawesome: 3.0.0-1 => 3.0.0-1
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2
    @vue/babel-plugin-jsx:  1.0.0-rc.3
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.5.6
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.5.6
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.6
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.6
    @vue/cli-plugin-router: ~4.5.0 => 4.5.6
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.6
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.6
    @vue/cli-service: ~4.5.0 => 4.5.6
    @vue/cli-shared-utils:  4.5.6
    @vue/compiler-core:  3.0.0
    @vue/compiler-dom:  3.0.0
    @vue/compiler-sfc: ^3.0.0-0 => 3.0.0
    @vue/compiler-ssr:  3.0.0
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-standard: ^5.1.2 => 5.1.2
    @vue/eslint-config-typescript: ^5.0.2 => 5.1.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/reactivity:  3.0.0
    @vue/runtime-core:  3.0.0
    @vue/runtime-dom:  3.0.0
    @vue/shared:  3.0.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^7.0.0-0 => 7.0.0-beta.3
    typescript: ~3.9.3 => 3.9.7
    vue: ^3.0.0-0 => 3.0.0
    vue-awesome-example:  2.0.0
    vue-cli-plugin-apollo: ~0.22.2 => 0.22.2
    vue-eslint-parser:  7.1.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.3 (16.0.0-beta.7)
    vue-router: ^4.0.0-0 => 4.0.0-beta.10
    vue-style-loader:  4.1.2
    vue-template-compiler:  2.6.12
    vue-template-es2015-compiler:  1.9.1
    vuex: ^4.0.0-0 => 4.0.0-beta.4
    vuex-module-decorators: ^1.0.1 => 1.0.1
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
(using webstorm)
Vue 3 project
- vuex
- router
- dart-scss
- eslint with standard config
- typescript (no class)

$ vue add apollo

### What is expected?
installs

### What is actually happening?
vue add apollo

�  Installing vue-cli-plugin-apollo...

> bufferutil@4.0.1 install E:\node_modules\bufferutil
> node-gyp-build

> utf-8-validate@5.0.2 install E:\node_modules\utf-8-validate
> node-gyp-build

> core-js@2.6.11 postinstall E:\node_modules\fbjs\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

> @apollo/protobufjs@1.0.5 postinstall E:\node_modules\@apollo\protobufjs
> node scripts/postinstall

> nodemon@2.0.4 postinstall E:\node_modules\nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

  vue-cli-plugin-apollo@0.22.2
added 612 packages from 413 contributors and audited 2130 packages in 61.376s

87 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
✔  Successfully installed plugin: vue-cli-plugin-apollo

? Add example code Yes
? Add a GraphQL API Server? No
? Configure Apollo Engine? No

�  Invoking generator for vue-cli-plugin-apollo...
 ERROR  Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
    at Collection.get (\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\jscodeshift\src\Collection.js:213:13)
    at injectOptions (\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\codemods\injectOptions.js:15:6)
    at runTransformation (\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\vue-codemod\dist\src\run-transformation.js:61:17)
    at \AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:290:23
    at Array.forEach (<anonymous>)
    at Generator.resolveFiles (\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:276:24)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Generator.generate (\AppData\Roaming\npm\node_modules\@vue\cli\lib\Generator.js:175:5)
    at async runGenerator (\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:111:3)
    at async invoke (\AppData\Roaming\npm\node_modules\@vue\cli\lib\invoke.js:92:3)

**Comment by sodatea** [comment]
vue-cli-plugin-apollo hasn't added support for Vue 3 yet. The error is expected.
