### ISSUE TITLE
vue-cli build: asking to install core node module after setup sass-loader

### ISSUE THREAD

**Issue by lvfxbr** [vuejs/vue-cli#5894]
### Version
4.5.6

### Environment info
```
  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.102
    Edge: Spartan (44.18362.449.0)
  npmGlobalPackages:
    @vue/cli: Not Found

*@vue/cli is not being recognized by "vue info", but if I run "vue --version", it shows: "@vue/cli 4.5.6".
```

### Steps to reproduce
1-Create a basic project via "vue create hello-world" or through "vue ui"(my preference is choose only babel as feature).

2-Add sass using vue-cli configuration described in documentation: "yarn add -D sass sass-loader".

3-Create some style tags with lang="scss" and do some scss style in hello world component.

4-Build the project using "yarn build", "npm run build" or "vue ui tasks".

### What is expected?
Is expected to have a clear build without errors.

### What is actually happening?
```

This dependency was not found:

* readline in ./node_modules/sass/sass.dart.js

To install it, you can run: npm install --save readline
 ERROR  Build failed with errors.
```

---
Excuse me if it is not a problem of vue or vue-cli, but I can't find the root of this problem. 
I updated my node and yarn to latest version until today but without success.
I removed my node_modules folder and installed again many times.

**Comment by sodatea** [comment]
Do you have a reproduction repo for this issue? I can't reproduce it.

**Comment by lvfxbr** [comment]
@sodatea, I tried to reproduce the problem in a test repository: https://github.com/lvfxbr/vue-cli-test/commit/95af99f2d32d93165cee00f75c0713db4406ebe2. 
But i didn't achieve the same result in my application that I don't want to exposed the code, but the dependencies is the same and the vue.config.js are the same. I did some extra components in the original app, but nothing more.

**Comment by sodatea** [comment]
Maybe it's because of your sass version being too old. Because I can no longer find a reference to require readline in the latest dart-sass source code.

**Comment by lvfxbr** [comment]
Well, reading from node_modules/sass/package.json:
```
{"name":"sass","description":"A pure JavaScript implementation of Sass.","license":"MIT","bugs":"https://github.com/sass/dart-sass/issues","homepage":"https://github.com/sass/dart-sass","repository":{"type":"git","url":"https://github.com/sass/dart-sass"},"author":{"name":"Natalie Weizenbaum","email":"nweiz@google.com","url":"https://github.com/nex3"},"engines":{"node":">=8.9.0"},"dependencies":{"chokidar":">=2.0.0 <4.0.0"},"keywords":["style","scss","sass","preprocessor","css"],"version":"1.26.11","bin":{"sass":"sass.js"},"main":"sass.dart.js"}
```

Checking with the npm repository "sass" is pointing to this github repository, here is a list of its latest releases:
https://github.com/sass/dart-sass/tags

The code that builder is pointing: node_modules/sass/sass.dart.js: https://gist.github.com/lvfxbr/662de79674ffc8fb50267040ace31c07 (TL;DR but use CTRL+F and you will find that require('readline') is there).

Well, the main point is: which tool is requiring readline module? it's a native module,  I don't understand why the builder didn't recognize as a core node module.

**Comment by sodatea** [comment]
Another guess: there might be some other dependencies in your project that modifies the `require` functionality underlyingly.

**Comment by lvfxbr** [comment]
Thanks again, @sodatea! Well, I tracked require using VSCode debug and looks like the require is pointing for one of internal files of node.js, helpers.js to be precise:

![image](https://user-images.githubusercontent.com/71705790/93955479-3f408900-fd26-11ea-92a9-0d60726864bd.png)
