### ISSUE TITLE
Should a simplest possible template be added for beginners?

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-cli#59]
I'm using Vue with relatively new JavaScript developers in some of my curricula and I wondered whether a `simple` template might be useful for beginners who just want to dive into a simple, single-file, single-component app. No Webpack, Browserify, Babel, etc - just plain HTML and JavaScript.

Possibly something like this?

``` html
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Vue</title>
  <script src="https://cdn.jsdelivr.net/vue/latest/vue.js"></script>
</head>
<body>
  <div id="app">
    <img src="https://vuejs.org/images/logo.png" alt="Vue logo">
    <h1>{{ greeting }}</h1>
    <ul>
      <li>
        To learn more about Vue, visit
        <a href="{{ docsURL }}" target="_blank">
          {{ humanizeURL(docsURL) }}
        </a>
      </li>
      <li>
        For live help with simple questions, check out
        <a href="{{ gitterURL }}" target="_blank">
          the Gitter chat
        </a>
      </li>
      <li>
        For more complex questions, post to
        <a href="{{ forumURL }}" target="_blank">
          the forum
        </a>
      </li>
    </ul>
  </div>

  <script>
    new Vue({
      el: '#app',
      data: {
        greeting: 'Welcome to your Vue.js app!',
        docsURL: 'http://vuejs.org/guide/',
        gitterURL: 'https://gitter.im/vuejs/vue',
        forumURL: 'http://forum.vuejs.org/'
      },
      methods: {
        humanizeURL: function (url) {
          return url
            .replace(/^https?:\/\//, '')
            .replace(/\/$/, '')
        }
      }
    })
  </script>
</body>
</html>
```

**Comment by yyx990803** [comment]
I could see this useful, although the docs already suggests starting with a jsfiddle: https://jsfiddle.net/yyx990803/okv0rgrk/

I personally think the CLI's purpose is doing the "heavy lifting" for scenarios with at least medium complexity.

On the other hand I feel there could be a simpler way to let people try out single file components (`*.vue` files). http://www.webpackbin.com/ is soon going to support that, which is great. There could also be an in-browser transform for `*.vue` files - which would be ideal for quick prototyping and could potentially serve as the "simplest boilerplate" - once you are happy with the idea you can simply port the `*.vue` files into a more complete boilerplate.

**Comment by chrisvfritz** [comment]
I like the jsfiddle, but for some students, I've found the extra layer of abstraction can make it difficult to transfer what they learn to a real file in a text editor. As a result, I try to have people coding real, complete projects as soon as possible (and ideally from the very beginning). 

_Some_ kind of dead simple template would help in this regard. I do like the idea of an in-browser transform for `*.vue` files, but I worry that even introducing the (albeit core) idea of components is too much complexity to start with. Unlike the other templates, the purpose wouldn't be to facilitate prototyping, boost productivity, or consolidate community knowledge. It would actually _never_ be used by more experienced devs, but rather would act as an entry point for _less_ experienced devs. 

It'd give them a small taste of (and introduction to) the tooling in the Vue ecosystem, as well as a demonstration of how truly _simple_ adding Vue to a project is - even for those who are just now looking to move beyond jQuery. My hope would be that over time, it would help those less experienced developers see that _they don't actually need a template_ for apps this simple. Until they get to that point though, they'd have some training wheels.

And in terms of bringing new people into the ecosystem, I think it could do a lot to make Vue's simplicity even more apparent to newcomers. And I think this is vital, because it stands in stark contrast to what's probably the most popular, direct competitor: React. I'm also an enthusiastic member of the React ecosystem, but despite the _possibly_ smaller API, using it in even simple projects is [far from trivial](https://github.com/chrisvfritz/view-framework-demos/blob/master/react/index.html).

So that's sort of what I'm thinking. Sorry for not being able to better communicate that earlier! What are your thoughts?

**Comment by yyx990803** [comment]
Sure! I can add you to the `vuejs-templates` organization to work on that - that would also give you privilege to manage issues in other templates. Are you interested in that?

**Comment by chrisvfritz** [comment]
Sounds great! :smiley: Do you have any policies I should stick to? (For example, when issues should be closed or what's definitely out-of-scope for a template.)

**Comment by yyx990803** [comment]
Not at this moment, I guess just use your best judgement. If not sure just mention me :)

**Comment by chrisvfritz** [comment]
:+1: Will do.

**Comment by chrisvfritz** [comment]
@yyx990803 It looks like I can add new repositories, but don't yet have access to moderate / write to current repos.

**Comment by yyx990803** [comment]
Should be good now.

**Comment by chrisvfritz** [comment]
Confirmed. :smiley: Thanks again!

**Comment by chrisvfritz** [comment]
Done: [vuejs-templates/simple](https://github.com/vuejs-templates/simple)
