### ISSUE TITLE
Unable to remove the project directory on Windows machine. Getting "The process cannot access the file because it is being used by another process." message in cmd

### ISSUE THREAD

**Issue by kumarklc** [vuejs/vue-cli#590]
I'm new to Vue. Learned the basics and started experimenting with Vue-CLI. So, i created a test project with webpack-simple template and understood how to create new component and link with core one.

Next, i closed the "npm run dev" with "ctrl + c  + Enter". I thought of deleting the test project created and typed "rmdir test-project /s /q" on my Windows machine. But the below message is being updated on cmd.

> The process cannot access the file because it is being used by another process.

I think this is a bug which is running even after closing the local server. Please, let me know what's the issue. I want to learn more.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You probably just left one of the files open on an editor, or the console on the directory

**Comment by kumarklc** [comment]
I'm clear on what I said. I have closed the editor and respective tab on my browser. After that I noticed the issue on CMD. So, I posted the issue.
