### ISSUE TITLE
env配置文件中不支持js语法

### ISSUE THREAD

**Issue by gitbu** [vuejs/vue-cli#5900]
### Version
4.5.6

### Reproduction link
[https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/util/resolveClientEnv.js](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/util/resolveClientEnv.js)

### Environment info
```
module.exports = function resolveClientEnv (options, raw) {
  const env = {}
  Object.keys(process.env).forEach(key => {
    if (prefixRE.test(key) || key === 'NODE_ENV') {
      env[key] = process.env[key]
    }
  })
  env.BASE_URL = options.publicPath

  if (raw) {
    return env
  }

  for (const key in env) {
    env[key] = JSON.stringify(env[key])     // 这里处理引起的
  }
  return {
    'process.env': env
  }
}
```

### Steps to reproduce
![图片](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/9c26f312992a4d869c0238a9ba8392e9~tplv-k3u1fbpfcp-zoom-1.image)

### What is expected?
env文件中支持写js代码

### What is actually happening?
env文件中想写入js代码，发现不生效

**Comment by sodatea** [comment]
env 是语言无关的，本来就不支持 JS 语法。

**Comment by gitbu** [comment]
但是有的场景是需要的，那这个怎么解决了

**Comment by sodatea** [comment]
那就直接写 JS 处理，不要在 env 文件里写。
