### ISSUE TITLE
High Vuln with lodash in cli-service

### ISSUE THREAD

**Issue by mgallion** [vuejs/vue-cli#5911]
### Version
4.5.6

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 80.0.1
    Safari: 14.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Need to bump versions of lodash methods defaultsdeep, mapvalues & transform to ^4.17.11

https://snyk.io/vuln/SNYK-JS-LODASH-73638

### What is expected?
No High Vulns in dependencies. 

### What is actually happening?
High Vulns in dependencies.

**Comment by sodatea** [comment]
I don't there are any vulnerabilities in these dependencies. You are referring to a vulnerability in the `lodash` package, while Vue CLI uses the *latest* version of these standalone packages, which is not affected by the issue.
