### ISSUE TITLE
Path alias randomly stops working.

### ISSUE THREAD

**Issue by aok-dev** [vuejs/vue-cli#5924]
### Version
4.5.6

### Environment info
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
  Browsers:
    Chrome: 85.0.4183.121
    Edge: Not Found
    Firefox: Not Found
    Safari: 12.1.2
  npmPackages:
    @fortawesome/vue-fontawesome: ^0.1.10 => 0.1.10 
    @vue/cli-overlay:  4.5.4 
    @vue/cli-plugin-router: ^4.5.0 => 4.5.4 
    @vue/cli-plugin-typescript: ^4.5.0 => 4.5.4 
    @vue/cli-plugin-vuex:  4.5.4 
    @vue/cli-service: ^4.5.0 => 4.5.4 
    @vue/cli-shared-utils:  4.5.4 
    @vue/component-compiler-utils:  3.2.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.2.0 
    typescript: ~3.9.3 => 3.9.7 
    vue: ^2.6.11 => 2.6.12 
    vue-class-component: ^7.2.5 => 7.2.5 
    vue-cli-plugin-i18n: ~1.0.1 => 1.0.1 
    vue-cli-plugin-tailwind: ~1.4.2 => 1.4.2 
    vue-cli-webpack:  1.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-i18n: ^8.21.0 => 8.21.0 
    vue-i18n-extract:  1.0.2 
    vue-loader:  15.9.3 (16.0.0-beta.5)
    vue-property-decorator: ^9.0.0 => 9.0.0 
    vue-router: ^3.2.0 => 3.4.3 
    vue-scrollto: ^2.18.2 => 2.18.2 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found


```

### Steps to reproduce
I have no idea.  But 3-4 times as I have been working on this project, on compile I will get:

 ERROR  Failed to compile with 1 errors                                                                                                                                                  9:14:45 AM

This dependency was not found:

* @/types in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/ts-loader??ref--12-1!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/admin/ViewReports.vue?vue&type=script&lang=ts&

To install it, you can run: npm install --save @/types

I haven't changed path aliases from the defaults EVER.  It will randomly stop working, and I just have to mess around until it suddenly starts again.  Things which have sometimes worked (but not always):  rm -rf node_modules; yarn; yarn serve;  Commenting out types 1 by 1 until I find one it's somehow offended at.  Sometimes moving it to a different file helps.  Sometimes, just taking it out is the only thing that will work, leaving me with <any> as the only option, which sort of defeats the purpose of working with typescript in the first place.

Even creating a new vue project via the CLI doesn't solve it.

### What is expected?
@ as a path alias for src/* to work all the time. And by extension, @/types to work as an alias for src/types

### What is actually happening?
sometimes it does, other times it just randomly stops working

---
At the very least - a better error report would be helpful, since if '@/types' works just fine as an import path in all the other files in the project (.ts, .vue) then I'm guessing the problem is something other than the error being reported:  "can't find dependency"

**Comment by sodatea** [comment]
Hi, thanks for your report.
Would you please reduce your issue to [a small reproducible example](https://stackoverflow.com/help/mcve) (e.g. a GitHub repository together with instructions on how to get to the problem)? Without a runnable example it would be difficult for us to find out what is going wrong.

**Comment by aok-dev** [comment]
As I said - I can't.  It's completely at random.  So...nevermind I guess?
