### ISSUE TITLE
With cnpm installed vue-cli being given, I use the company's other computer is being given, the error is as follows

### ISSUE THREAD

**Issue by Jon-Millent** [vuejs/vue-cli#593]
`[40/43] request@^2.67.0 installed at node_modules\_request@2.81.0@request
Install fail! Error: ENOENT: no such file or directory, chmod 'C:\Users\HP\AppData\Roaming\npm\node_modules\vue-cli\node_modules\_js-beautify@1.7.0@js-beautify\js\bin\css-beautify.js'
Error: ENOENT: no such file or directory, chmod 'C:\Users\HP\AppData\Roaming\npm\node_modules\vue-cli\node_modules\_js-beautify@1.7.0@js-beautify\js\bin\css-beautify.js'
    at Error (native)`

**Comment by posva** [comment]
dup of #591
