### ISSUE TITLE
npm config package 3.3.2 used with @vue/cli 4.5.6 Vuex plugin failed compiling

### ISSUE THREAD

**Issue by kotiel** [vuejs/vue-cli#5930]
### Version
4.5.6

### Reproduction link
[http://none](http://none)

### Environment info
```
https://www.npmjs.com/package/config
vuex installed with "vue create" @vue/cli 4.5.6
Linux a02kte 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35  0000 x86_64 GNU/Linux
Environment Info:

  System:
    OS: Linux 5.8 Arch Linux
    CPU: (4) x64 AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
  Binaries:
    Node: 14.13.0 - /usr/bin/node
    Yarn: Not Found
    npm: 6.14.7 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: 4.5.6 
```

### Steps to reproduce
store uses a plugin - soket.io-client - connected to Vuex state variables.
in the plugin file 
import config from 'config';

### What is expected?
npm run serve 
We expect the npm package config compiling in the Vuex plugin file - 
import config from 'config';

Error with npm run serve
Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/config/parser.js

require.extensions is not supported by webpack. Use a loader instead.

 @ ./node_modules/config/lib/config.js 10:13-33
 @ ./src/store/plugins/skupi.js
 @ ./src/store/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.2.121:8090&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

### What is actually happening?
File: err.log  
   1   │ critical dependency: the request of a dependency is an expression
   2   │
   3   │  warning  in ./node_modules/config/parser.js
   4   │
   5   │ require.extensions is not supported by webpack. Use a loader instead.
   6   │
   7   │  @ ./node_modules/config/lib/config.js 10:13-33
   8   │  @ ./src/store/plugins/skupi.js
   9   │  @ ./src/store/index.js
  10  │  @ ./src/main.js
  11  │  @ multi (webpack)-dev-server/client?http://192.168.2.121:8090&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

---
error message from @vue/cli 4.5.6
npm config package 3.3.2

Critical dependency: the request of a dependency is an expression

warning  in ./node_modules/config/parser.js

require.extensions is not supported by webpack. Use a loader instead.

**Comment by sodatea** [comment]
The [`config`](https://www.npmjs.com/package/config) package is for Node.js environment, it can't be used in a frontend project.

**Comment by seSze** [comment]
the fact that this was designed for node.js app does not change the fact that this is used in many frontend projects. e.g. https://docs.vuestorefront.io/

But this requires additional work not only importing package

**Comment by sodatea** [comment]
@seSze There's no meaningful way to use the `config` package in the browsers. *It relies on file system functionalities*! https://github.com/lorenwest/node-config/blob/ff64ba79e17adf6d0c49acacfa64c9c909378809/lib/config.js#L13

As for `vue-storefront`, they use the `config` package only in the server-side rendering code.
In client-side code, that's merely an alias https://github.com/DivanteLtd/vue-storefront/blob/09ef606e134a51a24279f0f7334e06023f698e1f/core/build/webpack.base.config.ts#L101

**Comment by sodatea** [comment]
Sorry for the previous misleading comment. I found the documentation on how to use `config` with webpack. https://github.com/lorenwest/node-config/wiki/Webpack-Usage 
The way `vue-storefront` uses it is in option 3.
