### ISSUE TITLE
Peer Dependency Warning When Installing @vue/cli

### ISSUE THREAD

**Issue by plewsible** [vuejs/vue-cli#5937]
### Version
4.5.7

### Reproduction link
[https://github.com/plewsible/country-selection](https://github.com/plewsible/country-selection)

### Environment info
```
vue@3.0.0
```

### Steps to reproduce
npm install -g @vue/cli

### What is expected?
Install Successful

### What is actually happening?
Last login: Fri Oct  9 00:22:29 on ttys000
xxxxxxxx@328327 ~ % npm install -g @vue/cli

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14 . Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14  and could be using insecure binaries. Upgrade to fsevents 2.

> yarn@1.22.10 preinstall /usr/local/lib/node_modules/@vue/cli/node_modules/yarn
> :; (node ./preinstall.js > /dev/null 2>&1 || true)

npm WARN @vue/compiler-sfc@3.0.0 requires a peer of vue@3.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code EACCES
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/@vue/cli/bin/vue.js
npm ERR! dest /usr/local/bin/vue
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, symlink '../lib/node_modules/@vue/cli/bin/vue.js' -> '/usr/local/bin/vue'
npm ERR!  [OperationalError: EACCES: permission denied, symlink '../lib/node_modules/@vue/cli/bin/vue.js' -> '/usr/local/bin/vue'] {
npm ERR!   cause: [Error: EACCES: permission denied, symlink '../lib/node_modules/@vue/cli/bin/vue.js' -> '/usr/local/bin/vue'] {
npm ERR!     errno: -13,
npm ERR!     code: 'EACCES',
npm ERR!     syscall: 'symlink',
npm ERR!     path: '../lib/node_modules/@vue/cli/bin/vue.js',
npm ERR!     dest: '/usr/local/bin/vue'
npm ERR!   },
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'symlink',
npm ERR!   path: '../lib/node_modules/@vue/cli/bin/vue.js',
npm ERR!   dest: '/usr/local/bin/vue'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxxxxxx/.npm/_logs/2020-10-08T16_28_10_276Z-debug.log
putrinuralisha@328327 ~ %

**Comment by Emsawy** [comment]
same problem

**Comment by Emsawy** [comment]
solved by this steps
`sudo npm install -g npm`
`sudo npm install -g @vue/cli`

**Comment by sodatea** [comment]
Warnings are just warnings. Will be fixed in the next major.
The error that blocked the installation process is the `EACCES` error and can be fixed by `sudo`.

**Comment by plewsible** [comment]
thank you for your help! it works!

**Comment by marshallepie** [comment]
It worked for me too except i had to use full path to get it to work like so.

sudo /usr/local/bin/yarn install

result:

yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
warning Pattern ["ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v6/npm-ethereumjs-abi-0.6.8-1ce6a1d64235fabe2aaf827fd606def55693508f/node_modules/ethereumjs-abi" as pattern ["ethereumjs-abi@^0.6.8"]. This could result in non-deterministic behavior, skipping.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/hardhat > eslint-config-airbnb@18.2.0" has unmet peer dependency "eslint-plugin-import@^2.21.2".
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/hardhat > eslint-config-airbnb@18.2.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.3.0".
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/hardhat > eslint-config-airbnb@18.2.0" has unmet peer dependency "eslint-plugin-react@^7.20.0".
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/hardhat > eslint-config-airbnb@18.2.0" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/hardhat > eslint-plugin-prettier@3.1.4" has unmet peer dependency "prettier@>=1.13.0".
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/react-app > @testing-library/user-event@12.1.8" has incorrect peer dependency "@testing-library/dom@>=7.21.4".
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/react-app > @uniswap/sdk@3.0.3" has unmet peer dependency "@ethersproject/networks@^5.0.0-beta".
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/react-app > @uniswap/sdk@3.0.3" has unmet peer dependency "@ethersproject/solidity@^5.0.0-beta".
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/react-app > eth-hooks@1.1.2" has unmet peer dependency "@ethersproject/constants@^5.0.1".
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/react-app > graphiql@1.0.5" has unmet peer dependency "prop-types@>=15.5.0".
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/hardhat > eslint-config-airbnb > eslint-config-airbnb-base@14.2.0" has unmet peer dependency "eslint-plugin-import@^2.21.2".
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/react-app > web3modal > styled-components@5.2.0" has unmet peer dependency "react-is@>= 16.8.0".
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/react-app > react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "workspace-aggregator-05403e98-4391-4c85-9f0f-8103e175ce9c > @scaffold-eth/react-app > @walletconnect/web3-provider > web3-provider-engine > eth-block-tracker > @babel/plugin-transform-runtime@7.12.0" has unmet peer dependency "@babel/core@^7.0.0-0".
**[4/4] Building fresh packages...
success Saved lockfile.
Done in 138.17s.**

I believe the last three lines men its worked?
