### ISSUE TITLE
Install fail!

### ISSUE THREAD

**Issue by linghuam** [vuejs/vue-cli#594]
I run <b>npm install -g vue-cli</b> in my computer(win10),but install fail.The terminal print the message:
```
Install fail! Error: ENOENT: no such file or directory, chmod 'C:\Users\linghuam\AppData\Roaming\npm\node_modules\vue-cli\node_modules\_js-beautify@1.7.0@js-beautify\js\bin\css-beautify.js'
Error: ENOENT: no such file or directory, chmod 'C:\Users\linghuam\AppData\Roaming\npm\node_modules\vue-cli\node_modules\_js-beautify@1.7.0@js-beautify\js\bin\css-beautify.js'
    at Error (native)
```
can you help me with this problem,thank you very much!

**Comment by standardspace** [comment]
See https://github.com/beautify-web/js-beautify/issues/1247

**Comment by posva** [comment]
dup of #591

**Comment by valiner** [comment]
same problem

**Comment by qm3ster** [comment]
**Emergency fix for `vue-loader` is incoming:** https://github.com/vuejs/vue-loader/commit/97bd432bba4350988bfd0db6d7a1a514b66a9826
