### ISSUE TITLE
Peer Dep Missing Error When use "npm list -g"

### ISSUE THREAD

**Issue by CNMathon** [vuejs/vue-cli#5940]
### Version
4.5.7

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.20221
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.18.1 - D:\Installation\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - D:\Installation\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.75
    Edge: Spartan (44.20221.1000.0), Chromium (85.0.564.70)
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
When I use "npm list -g --depth 0", @vue/cli throws a peer dep missing error just like this. 

![](https://i.loli.net/2020/10/10/fEyqsV873ZHkuQj.png)

And I find that when I install @vue/cli, cli also returns a "@vue/compiler-sfc@3.0.0 requires a peer of vue@3.0.0 but none is installed" warning.

![](https://i.loli.net/2020/10/10/KMOpxRAQuX6yoic.png)

I don't think this is a coincidence, as I have found that quite a few members of our team have the phenomenon.

### What is expected?
Run Successful

### What is actually happening?
Throw Error

**Comment by shouzia** [comment]
I also encountered this situation

**Comment by sodatea** [comment]
NPM incorrectly hoisted the dependencies from `vue-codemod`, putting `vue@3` & `@vue/compiler-sfc` at different levels of the dependency tree, thus the warning. We'll try to find a workaround.

**Comment by CNMathon** [comment]
> NPM incorrectly hoisted the dependencies from `vue-codemod`, putting `vue@3` & `@vue/compiler-sfc` at different levels of the dependency tree, thus the warning. We'll try to find a workaround.

So all we need to do is wait for a subsequent version update to fix the issue, right?

**Comment by JosephMing** [comment]
![image](https://user-images.githubusercontent.com/31059354/97152643-27887480-17ac-11eb-84fb-4b534cd13912.png)

**Comment by jcvw75** [comment]
Same problem on windows 10 here.

+-- @vue/cli@4.5.8
+-- http-server@0.12.3
`-- parcel-bundler@1.12.4

npm ERR! peer dep missing: vue@3.0.2, required by @vue/compiler-sfc@3.0.2

**Comment by shba007** [comment]
Same Here
![image](https://user-images.githubusercontent.com/48382105/98269069-52947480-1fb3-11eb-9301-65b3f15119ce.png)

**Comment by jcvw75** [comment]
I found the issue. You need to use latest nodejs (15.0.1) and npm.  (7.0.3)

Don't use the LTS or stable version.

**Comment by jcvw75** [comment]
Damn it now another problem... was working fine yesterday until I updated.

npm ERR! code ECONNRESET
npm ERR! network aborted
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by SergioEanX** [comment]
I have the same issue but I don't want to use the latest node version but latest LTS. Until now I was unable to fix the issue. I also tried to clear npm cache with `npm cache clean -f ` but with no results.

> NPM incorrectly hoisted the dependencies from `vue-codemod`, putting `vue@3` & `@vue/compiler-sfc` at different levels of the dependency tree, thus the warning. We'll try to find a workaround.

**Comment by enmotion** [comment]
C:\npm list -g --depth 0
C:\Users\Administrator\AppData\Roaming\npm
+-- @vue/cli@4.5.9
`-- cnpm@6.1.1

npm ERR! peer dep missing: vue@3.0.4, required by @vue/compiler-sfc@3.0.4
