### ISSUE TITLE
ValidationError: Invalid options object. Stylus Loader has been initialized using an options object that does not match the API schema.

### ISSUE THREAD

**Issue by VinceFanZ** [vuejs/vue-cli#5947]
### Version
4.5.7

### Environment info
```
"stylus-loader": "^4.1.1",
```

### Steps to reproduce
install stylus-loader@4.x

npm run serve

### What is expected?
stylus compile successfully

### What is actually happening?
```
 ERROR  Failed to compile with 1 errors                                                                                                                                10:42:34 PM

 error  in ./src/App.vue?vue&type=style&index=0&id=7ba5bd90&lang=stylus&scoped=true

Module build failed (from ./node_modules/stylus-loader/dist/cjs.js):
ValidationError: Invalid options object. Stylus Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'preferPathResolver'. These properties are valid:
   object { stylusOptions?, sourceMap?, webpackImporter?, additionalData? }
```
---
![image](https://user-images.githubusercontent.com/7631809/95761123-73ccb280-0cde-11eb-8ebb-bfe1c97e41b4.png)

**Comment by sodatea** [comment]
Please use stylus-loader@3 at the moment.

**Comment by zf1998** [comment]
I also encountered this problem, using stylus-loader v3 can solve it

**Comment by buyijiuyang** [comment]
> I also encountered this problem, using stylus-loader v3 can solve it

确实有效，将stylus-loader的版本降低到3.0.2 能够成功编译

**Comment by songchunfan** [comment]
对，我也试过了，用3.0.2版本的stylus-loader就能编译通过。

**Comment by vinayakkulkarni** [comment]
```diff
- "stylus-loader": "^4.2.0",
+ "stylus-loader": "^3.0.2",
```

This solves it, but I believe we should ensure that v4.x is supported while bundling the app

**Comment by xiaofulzm** [comment]
nice

**Comment by michaelalhilly** [comment]
Thanks for posting the fix!

**Comment by thisVioletHydra** [comment]
Thanks for posting the fix!
