### ISSUE TITLE
macOS cannot install using npm

### ISSUE THREAD

**Issue by henryhe1993** [vuejs/vue-cli#595]
My environment: MacOS version 10.12.6

I am quite new to Nodejs and npm, so it might be a silly question to ask. 

Basically, I cannot install vue-cli using npm (sudo npm install -g vue-cli). Initially, I tried the latest version of npm(5.4.2) and nodejs(8.5.0), which reported:  ENOENT: no such file or directory, access '/usr/local/lib/node_modules/vue-cli/node_modules/js-beautify/js/bin/css-beautify.js.

Then I downgraded my npm to 3.10.10 and nodejs to 6.10.3. A similar(or same?) problem still exists, which says: ENOENT: no such file or directory, access '/usr/local/lib/node_modules/vue-cli/node_modules/abbrev'.

For a test, I could successfully install jslint using npm command.  

I heard that there is an issue with js-beautify, which might be the answer to my first problem. But I cannot figure out the second one (abbrev one). 

Any help will be appreciated. Btw, I am in china using shadowsocks to perform the installation. Is it likely to be the issue(though i don't think so).

**Comment by posva** [comment]
dup of #591 
It will be fixed very soon
