### ISSUE TITLE
npm v7 incompatibility

### ISSUE THREAD

**Issue by rajeshjaga** [vuejs/vue-cli#5958]
### Version
4.5.7

### Reproduction link
[https://github.com/rajeshjaga/vue-cli-report](https://github.com/rajeshjaga/vue-cli-report)

### Environment info
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
  Binaries:
    Node: 14.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.0.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 85.0.4183.121
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.38)
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
clone the linked repo 
npm install
&& 
to resolve this prob:
change eslint version in package.json 7.11.0

### What is expected?
vue create app
created successfully

### What is actually happening?
 code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: eslint@7.11.0
npm ERR! node_modules/eslint
npm ERR! dev eslint@"^6.7.2" from the root project

---
Please bump up eslint version to 7.11.0 
I resolve it by changing the version on package.json

**Comment by sodatea** [comment]
Workaround: `npm config set legacy-peer-deps true`

**Comment by rajeshjaga** [comment]
$ npm config set legacy-peer-deps true
validBefore? true
"this was the response" and vue creates the project perfectly.
Should I close this issue
