### ISSUE TITLE
The official 2.x installation and project creation guide says use `vue serve` but this doesn't work

### ISSUE THREAD

**Issue by geoidesic** [vuejs/vue-cli#5959]
### Version
4.5.7

### Environment info
```
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.6.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.80
    Edge: Not Found
    Firefox: 81.0.1
    Safari: 14.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2
    @vue/babel-plugin-jsx:  1.0.0-rc.3
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.5.7
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.5.7
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.7
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.7
    @vue/cli-plugin-router:  4.5.7
    @vue/cli-plugin-vuex:  4.5.7
    @vue/cli-service: ~4.5.0 => 4.5.7
    @vue/cli-shared-utils:  4.5.7
    @vue/component-compiler-utils:  3.2.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    vue: ^2.6.11 => 2.6.12
    vue-eslint-parser:  7.1.1
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.3 (16.0.0-beta.8)
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: 4.5.7
```

### Steps to reproduce
As per the docs:
`npm install -g @vue/cli`
`npm i -g @vue/cli-init` <-- this bit is required but isn't documented
`vue create vuetest` <-- select all defaults
`cd vuetest`
`npm install`
`vue serve` <-- as per the documentation

### What is expected?
Should serve the app as documented.

### What is actually happening?
Get error: `Failed to locate entry file in /Users/me/repo/vuetest/vuetest.
Valid entry file should be one of: main.js, index.js, App.vue or app.vue.`

---
The cli tells us to use `yarn serve`. If that's the preferred way then the documentation should be updated. Most people are going to be looking at the docs as their entry point into learning.

**Comment by sodatea** [comment]
Which part of the documentation refers to `vue serve`?

**Comment by geoidesic** [comment]
This bit:
https://cli.vuejs.org/guide/prototyping.html

**Comment by sodatea** [comment]
I'm sorry if the documentation is a little bit misleading here. It is meant for "rapidly prototype with just a single `*.vue` file". For project usage, please follow the README of the generated project, which recommends `yarn serve`.

We'll alias `vue serve` to `yarn serve` in the next major version.
