### ISSUE TITLE
An error occurred while installing vue-cli

### ISSUE THREAD

**Issue by Shruan** [vuejs/vue-cli#596]
Error 1 ：
![image](https://user-images.githubusercontent.com/28869029/30702992-0f440e3a-9eb4-11e7-8146-4793658d0673.png)
Error 2 ：
![image](https://user-images.githubusercontent.com/28869029/30703083-51d1332c-9eb4-11e7-8bc6-b5010cafbcc4.png)

安装突然遇到这两个问题  要捉急

**Comment by posva** [comment]
Are you using the last version of npm and node?

**Comment by Shruan** [comment]
npm version 5.3.0
node version 8.4.0

**Comment by posva** [comment]
It looks like the problem is with the template (or a package used by it) you installed being badly formatted
