### ISSUE TITLE
#Disconnected from UI server

### ISSUE THREAD

**Issue by amanu-nur** [vuejs/vue-cli#5982]
### Version
4.5.7

### Environment info
```
 System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
  Binaries:
    Node: 14.11.0 - E:\Node\node.EXE
    Yarn: 1.22.5 - E:\Yarn\bin\yarn.CMD
    npm: 6.14.8 - E:\Node\npm.CMD
  Browsers:
    Chrome: 86.0.4240.75
    Edge: Spartan (44.19041.423.0), Chromium (86.0.622.43)
  npmPackages:
    vue:  2.6.12
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
-

### What is expected?
-

### What is actually happening?
-

---
I found a bug on Vue UI, the bug occurs when I open the link http: // localhost: 8000 / project / select and it will display the message #Disconnected from UI server #

**Comment by sodatea** [comment]
Please run `rm -rf ~/.vue-cli-ui` and try again.
