### ISSUE TITLE
@vue/cli@4.5.7 Configuration vue.config.js does not take effect   in vue3

### ISSUE THREAD

**Issue by wuyanwen** [vuejs/vue-cli#5985]
### Version
4.5.7

### Environment info
```
@vue/cli@4.5.7 Configuration vue.config.js in vue3. For example, outputDir, productionSourceMap does not take effect, but @vue/cli@4.5.6 does, and multiple machines have verified this problem, and hope to fix it soon
```

### Steps to reproduce
@vue/cli@4.5.7 Configuration config.vue.js For example, outputDir, productionSourceMap does not take effect, but @vue/cli@4.5.6 does, and multiple machines have verified this problem, and hope to fix it soon

### What is expected?
take effect

### What is actually happening?
does not take effect

---
@vue/cli@4.5.7 Configuration vue.config.js in vue3 For example, outputDir, productionSourceMap does not take effect, but @vue/cli@4.5.6 does, and multiple machines have verified this problem, and hope to fix it soon

**Comment by sodatea** [comment]
Thanks for submitting this issue! Due to our limited time, we ask you to include a reproduction link to a minimal full reproduction of your problem (for example in a GitHub repository) so we can find what is causing the issue. Thank you for your understanding!

**Comment by sodatea** [comment]
BTW the config file is `vue.config.js` not `config.vue.js`.

**Comment by wuyanwen** [comment]
> BTW the config file is `vue.config.js` not `config.vue.js`.

It is vue.config.js, the file name was typed wrong just now, as long as it is vue3, the vue.config.js setting will not take effect

**Comment by wuyanwen** [comment]
> Thanks for submitting this issue! Due to our limited time, we ask you to include a reproduction link to a minimal full reproduction of your problem (for example in a GitHub repository) so we can find what is causing the issue. Thank you for your understanding!

https://github.com/wuyanwen/vue-cli-vue3

**Comment by sodatea** [comment]
There's a typo. `module.exports` is not `module.export`.
