### ISSUE TITLE
Newly-Created App does not load in the Browser

### ISSUE THREAD

**Issue by reillybrown** [vuejs/vue-cli#5987]
### Version
4.5.8

### Reproduction link
[https://github.com/reillybrown/hello-world](https://github.com/reillybrown/hello-world)

### Environment info
```
Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Edge: Not Found
    Firefox: 81.0.2
    Safari: 13.0.5
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2 
    @vue/babel-plugin-jsx:  1.0.0-rc.3 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.8 
    @vue/babel-preset-jsx:  1.2.3 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.1 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.8 
    @vue/cli-plugin-babel: ~4.5.8 => 4.5.8 
    @vue/cli-plugin-eslint: ~4.5.8 => 4.5.8 
    @vue/cli-plugin-router: ~4.5.8 => 4.5.8 
    @vue/cli-plugin-vuex: ~4.5.8 => 4.5.8 
    @vue/cli-service: ~4.5.8 => 4.5.8 
    @vue/cli-shared-utils:  4.5.8 
    @vue/component-compiler-utils:  3.2.0 
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.12 
    vue-eslint-parser:  7.1.1 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.3 (16.0.0-beta.8)
    vue-router: ^3.2.0 => 3.4.7 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.4.0 => 3.5.1 
  npmGlobalPackages:
    @vue/cli: 4.5.8
```

### Steps to reproduce
1. Run `npm i` and `npm run build` in a terminal
2. In a browser, open `<your-path>/hello-world/dist/index.html`

### What is expected?
The template greeting page appears.

### What is actually happening?
The page is blank, checking in the console I receive errors that the files could not be found.

Firefox:
Loading failed for the <script> with source “file:///js/chunk-vendors.4cc7896c.js”.
Loading failed for the <script> with source “file:///js/app.0422b194.js”.

Chrome:
Failed to load resource: net::ERR_FILE_NOT_FOUND
app.0422b194.js:1
Failed to load resource: net::ERR_FILE_NOT_FOUND
chunk-vendors.4cc7896c.js:1
Failed to load resource: net::ERR_FILE_NOT_FOUND
about.668be4a2.js:1
Failed to load resource: net::ERR_FILE_NOT_FOUND
/favicon.ico:1 

---
All of the resources seem to load just fine when using the development server instead (npm run serve).  I noticed that, in the built version, the index.html uses prepended slashes in front of all of the file references.  Removing these slashes from dist/index.html seems to solve the issue.  However, this is not a sustainable answer.

It seems to me that a freshly-generated project using the @vue-cli should run without any errors.  Is this a potential bug?

**Comment by sodatea** [comment]
A web app is not expected to be viewed via the `file://` protocol. Please do not open the HTML file directly. Use a static web server like [http-server](https://www.npmjs.com/package/http-server).
