### ISSUE TITLE
You can customize it dynamically when you execute the packing command package.json Is the package output name under scripts in

### ISSUE THREAD

**Issue by xiaoxian521** [vuejs/vue-cli#5988]
### Version
4.5.8

### Environment info
```
You can customize it dynamically when you execute the packing command package.json Is the package output name under scripts in
```

### Steps to reproduce
You can customize it dynamically when you execute the packing command package.json Is the package output name under scripts in

### What is expected?
You can customize it dynamically when you execute the packing command package.json Is the package output name under scripts in

### What is actually happening?
You can customize it dynamically when you execute the packing command package.json Is the package output name under scripts in

**Comment by sodatea** [comment]
PLEASE DON'T SPAM.
