### ISSUE TITLE
Disable filenameHashing, but add hash as query parameter in index.html

### ISSUE THREAD

**Issue by herrernst** [vuejs/vue-cli#5989]
### What problem does this feature solve?
Hi,
I want to disable `filenameHashing`, but instead want to add the hash as query param to the injected resources in index.html, like `<script src="/js/chunk-vendors.js?_hash=0d01e0b2c53c417bdcfd"></script>`. Thus, the resources loaded via index.html will still be fetched if changed even if they got a long cache expiry. Is this possible somehow?
Thanks!

### What does the proposed API look like?
`<script src="/js/chunk-vendors.js?_hash=0d01e0b2c53c417bdcfd"></script>`

or

`<script src="/js/chunk-vendors.js?_version=0d01e0b2c53c417bdcfd"></script>`

maybe via a setting in vue.config.js like `addFilenameHashAsQueryParam`

**Comment by fangbinwei** [comment]
You can overwrite the webpack config

**vue.config.js**
```js
/** @type {import('@vue/cli-service').ProjectOptions} */
module.exports = {
  chainWebpack: (config) => {
    config
      .output
      .filename('js/[name].js?_hash=[contenthash:8]')
      .chunkFilename('js/[name].js?_hash=[contenthash:8]')

    config.plugin('extract-css').tap(args => {
      args[0].filename = 'css/[name].css?_hash=[contenthash:8]'
      args[0].chunkFilename = 'css/[name].css?_hash=[contenthash:8]'
      return args
    })
  },
}
```

**Comment by herrernst** [comment]
Thank you very much!

**Comment by herrernst** [comment]
Sorry to bother again, but found a small issue: both configs now CSS and JS source maps as link preload hints:

...```<link href="/css/app.css.map?_hash=0a4d67eb" rel="preload" as="script"><link href="/css/app.css?_hash=0a4d67eb" rel="preload" as="style"><link href="/js/app.js.map?_hash=8e0a5265" rel="preload" as="script">```...

**Comment by fangbinwei** [comment]
@herrernst @botic Sorry I didn't notice that. You can check [this demo repo](https://github.com/fangbinwei/webpack-bundle-hash-query)

**Comment by herrernst** [comment]
Thanks again! Perfect!

**Comment by mtskf** [comment]
@fangbinwei @herrernst
With the solution above, app-legacy.js isn't generated.
Here's my solution:
```
config.output.filename((process.env.VUE_CLI_MODERN_MODE && process.env.VUE_CLI_MODERN_BUILD) ? 'js/[name].js?_hash=[hash:8]' : 'js/[name]-legacy.js?_hash=[hash:8]')
```
