### ISSUE TITLE
vue.config.js     config    image-webpack-loader    and  also  use  css.extract   but  will  let   image  not   show  in  safari

### ISSUE THREAD

**Issue by yehoan** [vuejs/vue-cli#5996]
### Version
4.4.0

### Reproduction link
[http://www.xxx.com](http://www.xxx.com)

### Environment info
```
later  show  pic
```

### Steps to reproduce
when    i   use   npm  run  build   and   in   safari    not   show  image      i  not  know  why    but  in google   firefox  is okay   not  show  error

### What is expected?
can  show  in  safari

### What is actually happening?
not show  in  safari

**Comment by yehoan** [comment]
this   is  my    vue.config.js   config  
![Uploading 8V[N7(O]2%}0`OTTVYL}R1X.png…]()

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/96964409-f8200080-153c-11eb-8738-71c4e620294d.png)

**Comment by yehoan** [comment]
here  is  my   environment info    
![Uploading image.png…]()

**Comment by yehoan** [comment]
my  question  is   why   my  images  not  show  in  safari     i   just  follow  api  to config  and  finally   i  have  solve  my  question  but  use   delete  code     i  not  think  this  is   a  good  methods  so  i   want  to know  why

**Comment by sodatea** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by yehoan** [comment]
hello   this  is  really   a  bug  sir

**Comment by yehoan** [comment]
my  image   not  show  in   safari

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/96967753-8ea2f080-1542-11eb-93cd-929e796fa439.png)
when  i   use   a  image  as  a  background   not   show  in  safari

**Comment by sodatea** [comment]
Then please open a new issue with a valid reproduction.

**Comment by sodatea** [comment]
Screenshots aren't valid reproductions.

**Comment by yehoan** [comment]
beacause  have  this  problem   so   not  allow  in  production  environment   okay  。。
