### ISSUE TITLE
vue-build docs page not working

### ISSUE THREAD

**Issue by abdullah** [vuejs/vue-cli#600]

**Comment by posva** [comment]
do you mean the [readme](/vuejs/vue-cli/blob/master/README.md)?
Can you give more details?

**Comment by abdullah** [comment]
My apologies, This [link](https://github.com/vuejs/vue-cli/blob/master/docs/build.md)  on the vue-cli readme

**Comment by fuxic** [comment]
> **vue build**
> 
> Use vue-cli as a zero-configuration development tool for your Vue apps and component, check out the [docs](https://github.com/vuejs/vue-cli/blob/master/docs/build.md).
> 

Where are the docs now? The page not working
