### ISSUE TITLE
vue-config.js   backgroundImage not show  in   safari

### ISSUE THREAD

**Issue by yehoan** [vuejs/vue-cli#6002]
### Version
4.5.0

### Reproduction link
[https://codesandbox.io/s/zealous-shtern-gl4th?file=/src/App.vue](https://codesandbox.io/s/zealous-shtern-gl4th?file=/src/App.vue)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.111
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2
    @vue/babel-plugin-jsx:  1.0.0-rc.3
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.8
    @vue/babel-preset-jsx:  1.2.3
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.1
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.8
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.8
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.8
    @vue/cli-plugin-router:  4.5.8
    @vue/cli-plugin-vuex:  4.5.8
    @vue/cli-service: ~4.5.0 => 4.5.8
    @vue/cli-shared-utils:  4.5.8
    @vue/compiler-core:  3.0.2
    @vue/compiler-dom:  3.0.2
    @vue/compiler-sfc: ^3.0.0 => 3.0.2
    @vue/compiler-ssr:  3.0.2
    @vue/component-compiler-utils:  3.2.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/reactivity:  3.0.2
    @vue/runtime-core:  3.0.2
    @vue/runtime-dom:  3.0.2
    @vue/shared:  3.0.2
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^7.0.0-0 => 7.1.0
    vue: ^3.0.0 => 3.0.2
    vue-eslint-parser:  7.1.1
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.3 (16.0.0-beta.8)
    vue-style-loader:  4.1.2
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
when  i   put   my code  in  codesandbox  not find   background-image  plz  help  us  why  not  show

### What is expected?
show  backgroundImage

### What is actually happening?
not  show

**Comment by yehoan** [comment]
i  search  url  not   have  problem

**Comment by sodatea** [comment]
Remove the `webp` option of `image-webpack-loader`

**Comment by yehoan** [comment]
First  you  not  try   you  just  repsonse   not  think   can you try ?   
second   i really  want  to  know  the   reason   and   i     put  my  code in  codesandbox   is  so  easy  to  check  
Finally  can  you  give  me   a   correct  response   okay?
https://codesandbox.io/s/zealous-shtern-gl4th?file=/vue.config.js  
i have  remove  the  webp option  but  not  use

**Comment by sodatea** [comment]
I have downloaded the repo and tried. It works perfectly fine on my Mac after removing the `webp` option.

**Comment by sodatea** [comment]
As for codesandbox, it's a totally different environment. It's out of the scope of this repo.

**Comment by sodatea** [comment]
Here's the explanation, which, you should have figured it out by yourself instead of blaming others for not being specific enough:
1. It's caused by `image-webpack-loader`, which, has nothing to do with Vue CLI.
2. Safari does not support `webp` until iOS 14 and macOS Big Sur, so that's the reason why it didn't work on your Safari.
3. Codesandbox does not work exactly as a normal Node.js environment. It has its own hacks to run Vue CLI in that environment. So the result you get from there may differ from what's on a real machine.

**Comment by sodatea** [comment]
It's 00:18 a.m. on Sunday and I can't believe I'm actually sitting in front of a computer answering such a rude question.

**Comment by yehoan** [comment]
yes  when  i   use  npm  run  serve   it   is  use   but  just  in   development   environment   but  in   production  environment   will  show  this  problem

**Comment by yehoan** [comment]
i  just  really  want  to know  the  reason  because  it  is  really   influence   my   work

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/97097078-3f2a0500-16a7-11eb-8803-0de489d052bb.png)
this  is  my  phone  show  not  see  backgroundimage

**Comment by yehoan** [comment]
in production  environment

**Comment by sodatea** [comment]
This is a codesandbox page. It is not in the production environment.
