### ISSUE TITLE
Support Webpack 5

### ISSUE THREAD

**Issue by daniluk4000** [vuejs/vue-cli#6008]
### What problem does this feature solve?
I didn't find any existing issues for Webpack 5. I'm a little wondered if Vue CLI will support it (as it doesn't as I can see). It has released like 16 days ago, but I want to ask about any deadline for this feature.

Thanks!

### What does the proposed API look like?
Webpack 5 is supported

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/pull/5611#issuecomment-707113628

**Comment by daniluk4000** [comment]
> 
> 
> See [#5611 (comment)](https://github.com/vuejs/vue-cli/pull/5611#issuecomment-707113628)

Thanks!
