### ISSUE TITLE
node-sass is deprecated

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue-cli#6012]
### What problem does this feature solve?
node-sass is officially deprecated.
https://github.com/sass/node-sass

vue-cli should inform the user about that fact. Dart Sass should be the suggested SASS implementation.

### What does the proposed API look like?
When selecting a CSS preprocessor the prompt should inform the user that node-sass is deprecated.
```
Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported 
by default): (Use arrow keys)
❯ Sass/SCSS (with dart-sass) 
  Sass/SCSS (with node-sass) <!-- THIS IS DEPRECATED NOW -->
  Less 
  Stylus 
```

**Comment by fangbinwei** [comment]
Close via #6090
