### ISSUE TITLE
vue create project-name 创建后只有：readme.md 和 package.json , 参考现有解决方案： 改变.npmrc中：production: false 未能解决

### ISSUE THREAD

**Issue by wmo123** [vuejs/vue-cli#6014]
### Version
4.5.8

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Environment info
```
System:
    OS: macOS Mojave 10.14.6
    CPU: 2.3 GHz Intel Core i5
  Binaries:
    Node: v12.18.4 
    Yarn: v1.22.10   
    npm: 6.14.6
  Browsers:
    chrome 86.0.4240.111
 
  npmGlobalPackages:
    @vue/cli: 4.5.8
```

### Steps to reproduce
1、vue create hello-world
--------------------------------------
? Please pick a preset:
Default ([Vue 2] babel, eslint) 
Vue CLI v4.5.8
✨  Creating project in /Users/wangmin/project/demo.
🗃  Initializing git repository...
⚙️  Installing CLI plugins. This might take a while...

  demo@0.1.0
added 1 package in 0.056s
🚀  Invoking generators...
📦  Installing additional dependencies...

  demo@0.1.0
updated 1 package in 0.053s
⚓  Running completion hooks...

📄  Generating README.md...

🎉  Successfully created project demo.
👉  Get started with the following commands:

 $ cd demo
 $ npm run serve
-----------------------------------------
3、过程中无报错和异常
4、cd demo

### What is expected?
项目目录正常，文件齐全，npm run serve 启动服务

### What is actually happening?
demo文件下只有README.md  和 package.json，
package.json 文件内容：
{
  "name": "demo",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0"
  }
}

---
参考issue#4926,更改.npmrc文件，.npmrc 文件内容为： 
-----------------
registry=https://registry.npm.taobao.org/
global=true
production=false
package-lock =false
----------------------------
问题没有被解决，希望能帮忙解决一下，非常感谢！

**Comment by sodatea** [comment]
请在命令行运行 `echo $NODE_ENV`，确认输出为空。

**Comment by wmo123** [comment]
运行`echo $NODE_ENV`，确定输出为空

**Comment by sodatea** [comment]
把 npmrc 里 global=true 这行删掉。这个配置会导致你没法给项目装任何本地依赖。https://docs.npmjs.com/cli/v6/using-npm/config#global

**Comment by wmo123** [comment]
删掉global=true 后，可以成功创建项目了，非常感谢。
