### ISSUE TITLE
Pep jQuery plugin importing issue

### ISSUE THREAD

**Issue by hafizjee36** [vuejs/vue-cli#6016]
### Version
4.5.8

### Reproduction link
[https://github.com/briangonzalez/jquery.pep.js](https://github.com/briangonzalez/jquery.pep.js)

### Environment info
```
./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Dragger.vue
Module not found: Error: Can't resolve 'jquery.pep' in 'C:\Users\Muhammad Hassan\Desktop\vue-map-dragger\src\components'
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Dragger.vue 7:0-29
```

### Steps to reproduce
https://github.com/briangonzalez/jquery.pep.js

### What is expected?
I need to resolve this issue

### What is actually happening?
I have to need import another file but getting issue pep library not importing with:
"import pep from 'jquery.pep';" 
webpack file:
resolve:{
    modules: [__dirname, 'node_modules'],
    alias: {
      "jquery" : "jquery/src/jquery",
      "jquery.pep" : path.join(__dirname,"bower_components/pep/src/jquery.pep.js")
    }
  },

**Comment by sodatea** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
