### ISSUE TITLE
Unable to produce large library bundle that can be consumed by other projects

### ISSUE THREAD

**Issue by triforcely** [vuejs/vue-cli#6019]
### Version
2.6.0

### Node and OS info
Node 10.13.0 / latest npm / Windows 10

### Environment info
```
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  Binaries:
    Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.111
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @ionic/vue: 0.0.9 => 0.0.9
    @ionic/vue-router: ^5.4.0 => 5.4.1
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2
    @vue/babel-plugin-jsx:  1.0.0-rc.3
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.8
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.8
    @vue/cli-plugin-babel: ^4.5.6 => 4.5.8
    @vue/cli-plugin-e2e-cypress: ~4.5.0 => 4.5.8
    @vue/cli-plugin-e2e-nightwatch: ^4.5.6 => 4.5.8
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.8
    @vue/cli-plugin-router: ~4.5.0 => 4.5.8
    @vue/cli-plugin-typescript: ^4.5.6 => 4.5.8
    @vue/cli-plugin-unit-jest: ~4.5.0 => 4.5.8
    @vue/cli-plugin-unit-mocha: ^4.5.6 => 4.5.8
    @vue/cli-plugin-vuex:  4.5.8
    @vue/cli-service: ^4.5.6 => 4.5.8
    @vue/cli-shared-utils:  4.5.8
    @vue/compiler-core:  3.0.2
    @vue/compiler-dom:  3.0.2
    @vue/compiler-sfc: ^3.0.0-0 => 3.0.2
    @vue/compiler-ssr:  3.0.2
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-typescript: ^5.0.2 => 5.1.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared:  3.0.2
    @vue/test-utils: 1.1.0 => 1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^7.0.0-0 => 7.1.0
    jest-serializer-vue:  2.0.2
    typescript: ~3.9.3 => 3.9.7
    vue: ^2.6.12 => 2.6.12
    vue-eslint-parser:  7.1.1
    vue-hot-reload-api:  2.3.4
    vue-jest: ^3.0.7 => 3.0.7
    vue-loader:  15.9.4
    vue-router: ^3.4.3 => 3.4.8
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.12 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Build large repository with library target.
2. Import library in different vue-cli created project.
3. Start the build.

This happens with large projects, my "library bundle" is around ~7mbs which is build for SPA application with multiple Vue components.

### What is expected?
I expect that large library create with vue-cli should be imported and bundled with another vue-cli project.

### What is actually happening?
Webpack is unable to consume library that was created from other webpack project and is built for commonjs target. It fails with "FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out
of memory"

---
This was initially reported in webpack project: https://github.com/webpack/webpack/issues/11859

**Comment by fangbinwei** [comment]
Is your `large library bundle` published on public/private npm ?  Just import it to your project without extra config?

**Comment by triforcely** [comment]
@fangbinwei  It is a separate, private npm library build according to https://cli.vuejs.org/guide/build-targets.html#library

**Comment by fangbinwei** [comment]
>2. Import library in different vue-cli created project.

Can you provide more information about this step ? I assume you publish your library and npm install it by private registry in a new project. If your library is processed by some loader in your new project? @triforcely

**Comment by triforcely** [comment]
@fangbinwei You are correct, it is npm installedin the second project. This "second project" imports this library, and it is also created with vue-cli and uses vue-cli-service for building.

**Comment by fangbinwei** [comment]
@triforcely have you ever tried increasing the memory limit or updating node version?

**Comment by triforcely** [comment]
Updating nodejs to latest LTS version solved the issue. Thanks @fangbinwei !
