### ISSUE TITLE
Babel config file not being used in the root of a monorepo

### ISSUE THREAD

**Issue by cameron-martin** [vuejs/vue-cli#6034]
### Version
4.5.8

### Reproduction link
[https://github.com/cameron-martin/vue-transpile-node-modules-repro](https://github.com/cameron-martin/vue-transpile-node-modules-repro)

### Environment info
```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
  Binaries:
    Node: 15.0.1 - /tmp/yarn--1604497994926-0.13951107835497734/node
    Yarn: 1.22.5 - /tmp/yarn--1604497994926-0.13951107835497734/yarn
    npm: 7.0.3 - ~/.nvm/versions/node/v15.0.1/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 82.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
* Compile the app using `yarn workspace my-app run build`
* Inspect the files in `packages/my-app/dist/js/`

### What is expected?
I expect the config file in the root of the monorepo to take effect, causing the arrow function in the app to be compiled, including the ones in the appauthhelper node module due to the `transpileDependencies` option in the vue config.

### What is actually happening?
The arrow functions are not being compiled.

---
I think this is because of babel's `rootMode` not being set to `'upward'` in babel-loader's config in [`@vue/cli-plugin-babel`](https://github.com/vuejs/vue-cli/blob/0b86e70f86aebea2286617625dac1daa77247883/packages/%40vue/cli-plugin-babel/index.js#L88-L90). It would be good to have an option to set this, or even have it set by default. Alternatively, an option to set the `root` would be sufficient.

**Comment by fangbinwei** [comment]
current workaround
**vue.config.js**
```js
/** @type {import('@vue/cli-service').ProjectOptions} */
module.exports = {
  transpileDependencies: [
    'appauthhelper',
  ],
  chainWebpack(config) {
    config.module
      .rule('js')
        .use('babel-loader')
          .tap(options => {
            return {
              rootMode: "upward"
            }
          })
  }
};

```

**Comment by cameron-martin** [comment]
Oh neat, didn't know this was possible. This seems to work in the sense that it is now using the `babel.config.js` file in the root.

However, I now run into a different issue. Running `vue-cli-service build` succeeds fine, but `vue-cli-service serve` has an error:

> Cannot find module 'babel-preset-minify' from '/repo/node_modules/appauthhelper'

What seems to be happening here is the `.babelrc` file in `node_modules/appauthhelper` is being used to compile that package. However, this shouldn't be the default behaviour since babel 7, since [`babelrcRoots`](https://babeljs.io/docs/en/options#babelrcroots) must be specified to enable this behaviour.

**Comment by cameron-martin** [comment]
Oh neat, didn't know you could do this.

However it uncovered a bug in babel: https://github.com/babel/babel/issues/12314
