### ISSUE TITLE
Pages section in vue.config.js results in returning index.html file for other files in public directory

### ISSUE THREAD

**Issue by zwik** [vuejs/vue-cli#6039]
### Version
4.5.8

### Reproduction link
[https://github.com/zwik/vue-config-external](https://github.com/zwik/vue-config-external)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.16299
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 86.0.4240.183
    Edge: Spartan (41.16299.1480.0)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2
    @vue/babel-plugin-jsx:  1.0.0-rc.3
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.8
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.8
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.8
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.8
    @vue/cli-plugin-router:  4.5.8
    @vue/cli-plugin-vuex:  4.5.8
    @vue/cli-service: ~4.5.0 => 4.5.8
    @vue/cli-shared-utils:  4.5.8
    @vue/component-compiler-utils:  3.2.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    vue: ^2.6.11 => 2.6.12
    vue-eslint-parser:  7.1.1
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.5 (16.0.0-beta.10)
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
npm install
npm run serve

open the browser and watch the output in the console. The test.js file should be ran and give the output `this is now being executed` but it doesn't. Because HTML is returned an `Uncaught SyntaxError: Unexpected token '<'` is being thrown because of unexpected HTML.

### What is expected?
Console should output: `this is now being executed`. Important here is that the code is actually living in another directory, which is also configured is the vue.config.js file. When a default configuration is used, so no vue.config.js file and the code in the default location, it works.

### What is actually happening?
Console outputs: Uncaught SyntaxError: Unexpected token '<'

**Comment by fangbinwei** [comment]
CLI can only handle the `public` folder in the root directory. Maybe It's better import `test.js` in `main.js`? 
```
├── public
│   ├── favicon.ico
│   └── test.js
└── vue.config.js
```

Or you can use `yarn workspace`/monorepo

```
├── package.json
├── packages
│   └── my-app
│       ├── package.json
│       ├── public
│       ├── src
│       └── vue.config.js
└── yarn.lock
```

**Comment by zwik** [comment]
That indeed does solve the issue. Why is that actually? Would it be nice to configure this as well?

**Comment by fangbinwei** [comment]
Any static assets placed in the public folder will simply be copied to outputDir.  If you want to put some assets to  `packages/someapp/`, these assets look more like "private".  Public assets can be used by `packages/app1`, `packages/app2`, etc.  So, personally I think it is reasonable that the public folder is located in the root of the project.

For monorepo, you can organize the structure like this

```
├── package.json
├── packages
│   ├── app1
│   │   ├── package.json
│   │   ├── public
│   │   ├── src
│   │   └── vue.config.js
│   └── app2
│       ├── package.json
│       ├── public
│       ├── src
│       └── vue.config.js
└── yarn.lock
```

**Comment by zwik** [comment]
Issue resolved with the help of @fangbinwei .
