### ISSUE TITLE
vue-perf-devtool  not work 

### ISSUE THREAD

**Issue by hqzh** [vuejs/vue-cli#6045]
### Version
4.5.8

### Reproduction link
[https://github.com/vue-perf-devtool/vue-perf-devtool/issues/15](https://github.com/vue-perf-devtool/vue-perf-devtool/issues/15)

### Environment info

[性能优化](https://github.com/vue-perf-devtool/vue-perf-devtool)

### What is expected?
worked

### What is actually happening?
no working

**Comment by sodatea** [comment]
Please follow the issue template and fill in meaningful content. Otherwise, there's not much we can help with.
