### ISSUE TITLE
Need equivalent vue build

### ISSUE THREAD

**Issue by koekaverna** [vuejs/vue-cli#605]
Hello, i need equivalent of these command
`vue build .\src\components\Component.vue --prod --lib`

**Comment by LinusBorg** [comment]
If that question is about poi, why do you ask here?

**Comment by koekaverna** [comment]
because that command removed from vue, is there any way to do this?

**Comment by LinusBorg** [comment]
https://poi.js.org/#/recipes/cjs-and-umd-format
