### ISSUE TITLE
npm ERR! peer dep missing while installing vue/cli

### ISSUE THREAD

**Issue by HQCuong** [vuejs/vue-cli#6061]
### Version
4.5.8

### Environment info
```
windows 10x64
```

### Steps to reproduce
First I run the command "npm i -g @ vue/cli" to install vue cli. The installation is fine, no errors occur.

But when I run the command "npm list --depth=0 -g" I get the following error: "npm ERR! peer dep missing: vue@3.0.2, required by @vue/compiler-sfc@3.0.2"

I installed vue@3.0.2 but the error message still appears.
I also tried clearing the cache, reinstalling it but it still didn't work.

The only way that works is I delete vue/cli on npm and install it with yarn, now there will be no error message. But I don't really want to switch to yarn I just want to install vue/cli with npm

### What is expected?
OK

### What is actually happening?
npm ERR! peer dep missing: vue@3.0.2, required by @vue/compiler-sfc@3.0.2

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/issues/5940#issuecomment-706528527
