### ISSUE TITLE
tsx: css module not working in production build

### ISSUE THREAD

**Issue by Innei** [vuejs/vue-cli#6069]
### Version
4.5.9

### Reproduction link
[https://github.com/mx-space/notebook/tree/29f705b18f380f072e588bdfa7238d1037a2cbaf)

### Environment info
```
[System Information]
OS Version     : macOS Big Sur
NodeJS Version : v14.15.0
YARN Version    : 1.22.10 

Vue: 3.0.0
ts: 4.0.5
```

### Steps to reproduce

1. use css module in `.tsx` file. In development mode, tt working, not working in production build. and every class which is css module lost.

![image](https://user-images.githubusercontent.com/41265413/99548432-9d6ead00-29f3-11eb-9acc-b95e6b81ceb7.png)

and this is my vue conifg: 

```js
module.exports = {
  publicPath:
    process.env.NODE_ENV === 'production'
      ? !process.env.VUE_APP_PUBLIC_URL
        ? 'https://cdn.jsdelivr.net/gh/mx-space/notebook@gh-pages'
        : ''
      : '/',
}

```

### What is expected?
css module working in production

### What is actually happening?
css module not working in production

**Comment by fangbinwei** [comment]
`vue-cli-plugin-tailwind/purgecss` purge your css-module codes. I think you should open a new  issue in `vue-cli-plugin-tailwind`. maybe it's not smart enough and can't judge if your css-module codes is used.
