### ISSUE TITLE
npm run build fails when using git-based dependency

### ISSUE THREAD

**Issue by VictorioBerra** [vuejs/vue-cli#6070]
### Version
4.5.8

### Reproduction link
[https://github.com/VictorioBerra/vue-cli-build-git-issue](https://github.com/VictorioBerra/vue-cli-build-git-issue)

### Environment info
```
windows 10
@vue/cli 4.5.8
npm 6.14.8
node v14.15.0
```

### Steps to reproduce

1. `vue create helloworld`
2. `cd helloworld`
3. `npm i https://github.com/qrohlf/trianglify.git --save`
4. `npm run build`
5. Edit HelloWorld.vue and import trianglify and then "use" it. IE: `console.log(trianglify)`

### What is expected?
npm run build does not fail

### What is actually happening?
npm run build fails

```
 ERROR  Failed to compile with 1 errors                                                                       4:41:29 PM

This dependency was not found:

* trianglify in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/HelloWorld.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save trianglify
 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project-git-issue@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-project-git-issue@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2020-11-18T22_41_29_689Z-debug.log
PS C:\Users\me\Desktop\my-project-git-issue>
```

**Comment by sodatea** [comment]
The main entry of `trianglify` is `dist/trianglify.js` but it does not exist in the Github repository.

https://github.com/qrohlf/trianglify/blob/0d469f288fa72b7dce91ea36a58a1261487953ff/package.json#L5
