### ISSUE TITLE
vue 使用 psd.js 库出现问题

### ISSUE THREAD

**Issue by tgy3300** [vuejs/vue-cli#6077]
### Version
4.5.9

### Reproduction link
[http://localhost:8080/](http://localhost:8080/)

### Environment info
```
vue/cli 4.5.9
```

### Steps to reproduce
1、npm install -g @vue/cli
2、vue create my-project
3、? Please pick a preset:
                Default ([Vue 2] babel, eslint)
             > Default (Vue 3 Preview) ([Vue 3] babel, eslint) 
                Manually select features
4、安装完成后
5、cd my-project
6、npm install psd
7、修改 src\components\HelloWorld.vue 文件如下：
      
     <script>
     var PSD = require('psd');
     export default {
         name: 'HelloWorld',
         ...
         mounted(){
             var file = "path/a.psd";
             var psd = PSD.fromFile(file);
             psd.parse();
             console.log(psd.tree().export());
         }
     }
     </script>

       
8、npm run serve

### What is expected?
运行不通过

### What is actually happening?
 ./node_modules/coffee-script/lib/coffee-script/register.js
Module not found: Error: Can't resolve 'module' in 'path\my-project\node_modules\coffee-script\lib\coffee-script'

**Comment by fangbinwei** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only.

You can use [CDN](https://cdnjs.cloudflare.com/ajax/libs/psd.js/2.0.0/psd.min.js).I hope it can help you
> https://github.com/meltingice/psd.js/issues/138#issuecomment-547810701
