### ISSUE TITLE
Cannot strip comments using Vue cli / Terser

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuejs/vue-cli#6082]
### Version
4.5.9

### Reproduction link
[https://github.com/webpack-contrib/terser-webpack-plugin/issues/360](https://github.com/webpack-contrib/terser-webpack-plugin/issues/360)

### Environment info
```
N/A
```

### Steps to reproduce
According to this link, this is how to correctly set terser within vue:
https://cli.vuejs.org/migrating-from-v3/#vue-cli-service

If I modify that code by adding a console.output, I can see format and output are both missing:
```
module.exports = {
  chainWebpack: (config) => {
    config.optimization.minimizer('terser').tap((args) => {
      console.log(JSON.stringify(args, null, 2); //<--Added this line
      args[0].terserOptions.compress.drop_console = true
      return args
    })
  }
}
```
When I do an npm run build The output shows something like
```
{
  "terserOptions": {"compress":{someStuffInHere}, "mangle":{someStuffInHere}},
  "sourceMap":true
  "cache":true,
  "parallel":true,
  "extractComments": false,
}
```
If I manually add in a format.comments=false or output.comments=false to the terserOptions, there are no errors, but the commands do nothing (don't work)

This page seems to indicate they 'might' be deprecated, but show no equivalents.
https://webpack.js.org/plugins/terser-webpack-plugin/#terseroptions

### What is expected?
Comments get stripped

### What is actually happening?
No comments are getting stripped

**Comment by fangbinwei** [comment]
This [v4 doc](https://v4.webpack.js.org/plugins/terser-webpack-plugin/#remove-comments) can help you ?

**Comment by UglyHobbitFeet** [comment]
Unfortunately, I've tried that and it didn't work either

**Comment by fangbinwei** [comment]
It works for me. Or please provide a reproducible repo @UglyHobbitFeet

**Comment by UglyHobbitFeet** [comment]
Ahh I think I see. The js files in question are in the 'public' folder which are static assets. Is there a way to minify those using vue/terser?

**Comment by fangbinwei** [comment]
you need [transform of copy-webpack-plugin](https://v4.webpack.js.org/plugins/copy-webpack-plugin/#transform). using terser by yourself.

**Comment by UglyHobbitFeet** [comment]
Got it, thanks!

**Comment by UglyHobbitFeet** [comment]
Unfortunately that gives me an "optimize is not defined" error message when I try to use it :(

**Comment by fangbinwei** [comment]
`optimize` means anything, you should define your own 'optimize', like 

```js
 transform(content, path) {
   const { minify } = require("terser");
  minify(...)
 return ...
},
```

you need to optimize by yourself.

**Comment by guohuihot** [comment]
5.0的配置
```        // 去除js中的打印信息
        configure.optimization.minimizer[0].options.minimizer.options.compress.drop_console = true
```
