### ISSUE TITLE
Fail when 'npm run dev' on Linux CentOS server

### ISSUE THREAD

**Issue by jakub-wisniewski** [vuejs/vue-cli#609]
I develop Vue.js project on Windows 10. It works fine when I run 'npm run dev' command inside init folder.

When I copied this same folder on Linux CentOS server I got an error after running this command:

17 error Linux 3.10.0-327.22.2.el7.x86_64
18 error argv "/data/myproject/application/node/bin/node" "/data/myproject/application/node/bin/npm" "run" "dev"
19 error node v6.11.4
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error vue-mdl-login-component@1.0.0 dev: `node build/dev-server.js`
22 error Exit status 1
23 error Failed at the vue-mdl-login-component@1.0.0 dev script 'node build/dev-server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vue-mdl-login-component package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node build/dev-server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vue-mdl-login-component
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vue-mdl-login-component
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

I have all installed: node.js, npm, vue-cli (globally)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is  not related to vue-cli. It seems to be related to vue-mdl-login-component
