### ISSUE TITLE
update webpack-bundle-analyzer to ^4.1.0

### ISSUE THREAD

**Issue by genie-youn** [vuejs/vue-cli#6091]
### What problem does this feature solve?
Hi teams 😄 
Thanks for making awesome tool.

Into the subject..

webpack-bundle-analyzer 4.1.0 was released a few days ago: https://github.com/webpack-contrib/webpack-bundle-analyzer/compare/v3.8.0...v4.1.0

In this update, the `bfj` module was replaced by a custom json writer, which resulted in many performance improvements.
(ref [PR](https://github.com/webpack-contrib/webpack-bundle-analyzer/pull/390))

In my case, I use a large scale Vue Application in vue-cli, and when I changed the version, the performance was greatly improved as follows.

#### before
<img width="418" alt="before" src="https://user-images.githubusercontent.com/16642635/100498861-7d37ae80-31a8-11eb-9f24-39bc4c2e6c56.png">

#### after
<img width="427" alt="after" src="https://user-images.githubusercontent.com/16642635/100498864-8163cc00-31a8-11eb-8a49-52f2be2acecd.png">

I've seen that there is no break change between versions, so what do you think of upgrading the version of webpack-bundle-analyzer to 4.1.0?

I prepared a pull request.

Thanks you 😄 

### What does the proposed API look like?
Update webpack-bundle-analyzer to ^4.1.0

**Comment by IndexXuan** [comment]
@genie-youn Hi Bro，how to use smp(speed-measure-plugin) with vue-cli ?

**Comment by genie-youn** [comment]
@IndexXuan 
Hi, I tried these things.

### 1. in configureWebpack
vue.config.js
```javascript
const SpeedMeasurePlugin = require("speed-measure-webpack-plugin");
const smp = new SpeedMeasurePlugin();

module.exports = {
  configureWebpack: smp.wrap({
    plugins: [
      new MyAwesomeWebpackPlugin()
    ]
  }),
  //...
}
```

### 2. in chainWebpack
You must delete `preload` plugin. `speed-measure-webpack-plugin` crash with `PreloadPlugin`. It seems bug in `speed-measure-webpack-plugin`

vue.config.js
```javascript
\module.exports = {
  //...
  chainWebpack: config => {
    // *Must delete these plugins*
    config.plugins.delete('preload');
    config.plugins.delete('prefetch');
    // GraphQL Loader
    config.module
      .rule('graphql')
      .test(/\.graphql$/)
      .use('graphql-tag/loader')
        .loader('graphql-tag/loader')
        .end()
      // Add another loader
      .use('other-loader')
        .loader('other-loader')
        .end()

    config
      .plugin('html')
      .tap(args => {
          return [/* new args to pass to html-webpack-plugin's constructor */]
      })

    const wrappedConfig = smp.wrap(config.toConfig());
    config.toConfig = () => wrappedConfig;
  }
}
```

## 3. Modify vue-cli source in your project's node_modules
Some plugins that appended by vue-cli, (e.g. webpack-bundle-analyzer) `speed-measure-webpack-plugin` can't collect metric. becuase these plugins append after adopt `speed-measure-webpack-plugin`. 

So to measure the speed of these plugins, we directly modify code of vue-cli.

Similarly, should delete `preload` plugin.

[this point at node_modules/@vue/cli-service/libs/commands/build/index.js](https://github.com/vuejs/vue-cli/blob/c64afc3c2a8854aae30fbfb85e92c0bb8b07bad7/packages/%40vue/cli-service/lib/commands/build/index.js#L198)
```javascript
if (args.clean) {
  await fs.remove(targetDir)
}

const SpeedMeasurePlugin = require("speed-measure-webpack-plugin");
const smp = new SpeedMeasurePlugin();

webpackConfig = smp.wrap(webpackConfig);

return new Promise((resolve, reject) => {
  webpack(webpackConfig, (err, stats) => {
```

It would be great if `vue-cli` support option. (like `vue-cli-service build --measure-speed`).
But the first thing to do is fix the `speed-measure-webpack-plugin` bug, so I'm looking at that part.

**Comment by IndexXuan** [comment]
@genie-youn Thanks a lot. long time to find the solution.

so  @sodatea , will smp be the built in function in Vue CLI, like https://umijs.org/zh-CN/docs/env-variables#speed_measure
e.g. SPEED_MEASURE=1 yarn build or yarn build --speed-measure

**Comment by ShuBuShao** [comment]
`const SpeedMeasurePlugin = require('speed-measure-webpack-plugin')
module.exports = {
  chainWebpack: config => {
    config
      .plugin('speed-measure-webpack-plugin')
      .use(SpeedMeasurePlugin)
      .end()
  }
}
`
不用删除 preload plugin,
用上面的方式可以直接使用

**Comment by BuugMakerr** [comment]
> ```
> module.exports = {
>   chainWebpack: config => {
>     config
>       .plugin('speed-measure-webpack-plugin')
>       .use(SpeedMeasurePlugin)
>       .end()
>   }
> }
> ```
> 
> 不用删除 preload plugin, 用上面的方式可以直接使用

但是这样好像不能测量插件的时间
