### ISSUE TITLE
html-webpack-plugin is outdated

### ISSUE THREAD

**Issue by jantimon** [vuejs/vue-cli#6109]
### Version
4.5.9

The current used version of the html-webpack-plugin can be seen here: https://unpkg.com/@vue/cli-service/package.json

### What is expected?
`@vue/cli-service` is using `html-webpack-plugin` 3.2.0 which is slower than `html-webpack-plugin` 4.5.0 and quite outdated (3 years since the release)

See all information about the html-webpack-plugin 4.x release here: https://dev.to/jantimon/html-webpack-plugin-4-has-been-released-125d

Furthermore for webpack 5.x there will be a `html-webpack-plugin` 5.x which is in alpha right now

---
I am the author of the html-webpack-plugin - please let me know if I can be of any help to migrate to a supported version

**Comment by sodatea** [comment]
Hi, I've recently updated to `html-webpack-plugin` 4 in the dev branch, and an alpha version would be released very soon. It will use webpack 5 by default.

But for now, as the plugin ecosystem hasn't fully caught up with webpack 5, I would like the next version of Vue CLI to also support opting out to webpack 4 compilation.

So I'm wondering if `html-webpack-plugin` can still keep support for webpack 4?

**Comment by jantimon** [comment]
hey @sodatea

wow cool that sounds great :)
if you need any help e.g. with the template option or anything else just ping me.

Unfortunately webpack 5 is very different from webpack 4 and therefore it is very hard to maintain webpack 4 & 5 with the same html-webpack-plugin - the support plan is the following:

- html-webpack-plugin 3.x - out of support - fully compatible to webpack <= 4
- html-webpack-plugin 4.x - only bug fixes - fully compatible to webpack 4 & partialy compatible to webpack 5
- html-webpack-plugin 5.x - active branch - fully compatible to webpack 5

Please note that html-webpack-plugin 5 is still wip - the current progress can be seen here:  
https://github.com/jantimon/html-webpack-plugin/issues/1527

**Comment by sodatea** [comment]
Besides dropping webpack 4 support, will there be any user-facing breaking changes in configuration options? If no, I think I can still find a way to support both versions 🤔

**Comment by jantimon** [comment]
that should be possible there are only 3 breaking changes for html-webpack-plugin 5:

* Drop support for appcache-webpack-plugin
* scripts are now loaded deferred in the <head> tag to improve page load performance by default - This can be turned off by setting `scriptLoading: ‘blocking’`
* drop webpack 4 and node <= 10 support

**Comment by jantimon** [comment]
@sodatea html-webpack-plugin 5.x was officially released this week (it is the same code which was released as beta 1 month ago)

did you had any success upgrading vue-cli to a current html-webpack-plugin?

**Comment by jantimon** [comment]
wow so cool thanks a lot @sodatea

**Comment by thefoxie** [comment]
@sodatea do you think you could release another alpha with this dependency updated? It stopped working this morning because of this dependency.

**Comment by sodatea** [comment]
Yeah tomorrow.
Today is the last day of my Lunar New Year vacation and I haven't got the time to reach for my computer yet.

**Comment by thefoxie** [comment]
Oh cool, thank you. Enjoy your free time 😊

**Comment by zhangchenna** [comment]
麻烦尽快更新吧，现在项目跑不起来了

 ```
ERROR  Failed to compile with 1 error                                                                                           下午3:11:04

  Error: The loader "/Volumes/Work/vue3-demo/node_modules/html-webpack-plugin/lib/loader.js!/Volumes/Work/vue3-demo/public/index.html" didn'  t return html.
  
  - index.js:336 HtmlWebpackPlugin.evaluateCompilationResult
    [vue3-demo]/[html-webpack-plugin]/index.js:336:24
  
  - index.js:243 
    [vue3-demo]/[html-webpack-plugin]/index.js:243:22
  
  - runMicrotasks
  
  - task_queues.js:93 processTicksAndRejections
    internal/process/task_queues.js:93:5
  
  - async Promise.all
  
  - async Promise.all
```

**Comment by jantimon** [comment]
@zhangchenna https://github.com/jantimon/html-webpack-plugin/issues/1603

**Comment by zhangchenna** [comment]
> @zhangchenna [jantimon/html-webpack-plugin#1603](https://github.com/jantimon/html-webpack-plugin/issues/1603)

thank you

**Comment by sodatea** [comment]
Fixed in alpha.4
