### ISSUE TITLE
What does lib/eval.js do

### ISSUE THREAD

**Issue by clemtrek** [vuejs/vue-cli#611]
I am a beginner and a student of class 9. I am trying to build a scaffolding tool and I was going through how you wonderfully manage to work it all.

I could not figure out what the evaluate function does ?

Any explaination would be really helpful

**Comment by qm3ster** [comment]
It's using [the Function() constructor](http://2ality.com/2014/01/eval.html) to evaluate an expression, providing the properties of the 'data' parameter with [the `with` operator](http://2ality.com/2011/06/with-statement.html)

So, if you provide the following expression and data:
```js
const exp = "list[0]"
const data = {
  list: [1]
}
const fn = new Function('data', 'with (data) { return ' + exp + '}')
// equivalent to
const fn = function (data) {
  with (data){
    return list[0]
  }
}

// so,
return fn(data)
// will return

with ({list: [1]}){
  return list[0]
}

// which behaves like destructuring:
list = [1]
return list[0]
```

**Comment by clemtrek** [comment]
Thanks.....

**Comment by qm3ster** [comment]
It's used to evaluate user-supplied expressions. Eval (and obviously function) evaluate the code in the context of a statement, that's why a return is added.

**Comment by clemtrek** [comment]
Actually, I am a student of class 9. I wanted to learn by collaborating.  

Would you be kind enough to help
