### ISSUE TITLE
vue3全局注入scss的方法和类失效

### ISSUE THREAD

**Issue by HUAzd** [vuejs/vue-cli#6110]
**问题**
![image](https://user-images.githubusercontent.com/44830285/101272147-8afebc80-37c4-11eb-87f6-5a7c7daf59f8.png)
首先，按照官方文档，在vue.config.js中进行配置，注入样式入口文件，@css是别名
![image](https://user-images.githubusercontent.com/44830285/101272180-c9947700-37c4-11eb-8f9d-b986db5fe4ac.png)
该入口文件注入若干样式
然后全局样式和scss变量均生效，只有使用@extend的scss类和@include的scss函数无效

**描述**
上面的做法我在vue2项目是正常的，在迁移至vue3时才出现问题，两边代码和配置都是一样的。
新老项目都是用vue-cli的命令窗口搭建的，都是选择dart-scss。

**出问题的版本**
"vue": "^3.0.0",
"@vue/cli-plugin-babel": "~4.5.0",
"@vue/cli-service": "~4.5.0",
"@vue/compiler-sfc": "^3.0.0",
"sass": "^1.26.5",
"sass-loader": "^8.0.2",

**没问题的版本**
"vue": "^2.6.11",
"@vue/cli-plugin-babel": "~4.4.0",
"@vue/cli-service": "~4.4.0",
"vue-template-compiler": "^2.6.11",
"sass": "^1.26.5",
"sass-loader": "^8.0.2",

**Comment by wangfpp** [comment]
@HUAzd 你解决了这个问题了吗
