### ISSUE TITLE
Env Configuration cannot be overridden

### ISSUE THREAD

**Issue by 19Qingfeng** [vuejs/vue-cli#6111]
### Version
4.5.0

### Reproduction link
[https://github.com/19Qingfeng/nx-aloha](https://github.com/19Qingfeng/nx-aloha)

### Environment info
```
1. yarn
2. yarn build
```

### Steps to reproduce
1. yarn build
2. open dist/index.html
3. Check the console

### What is expected?
{
NODE_ENV: "production", 
BASE_URL: "",
VUE_APP_HTTP="http://aloha.admin.boochat.cn/api"
__proto__: Object
}

### What is actually happening?
{
NODE_ENV: "production", BASE_URL: ""}
BASE_URL: ""
NODE_ENV: "production"
__proto__: Object

---
how can i  give environment  variable files any name?

**Comment by fangbinwei** [comment]
Why not use `.env` file directly?  The project you provided is too complicated for me, it's better to provide a minimal reproduction.

**Comment by 19Qingfeng** [comment]
> 为什么不`.env`直接使用文件？您提供的项目对我来说太复杂了，最好提供最小的复制。

I don't use `.env` for some special reasons

`https://github.com/19Qingfeng/nx-aloha/tree/test/src`This is a small demo.

step 1 : yarn
step 2 : yarn build
step 3 : open dist/index.html

**Comment by 19Qingfeng** [comment]
> Why not use `.env` file directly? The project you provided is too complicated for me, it's better to provide a minimal reproduction.

I don't use `.env` for some special reasons.
`https://github.com/19Qingfeng/nx-aloha/tree/test` This is a small Demo.

step 1 : npm install /yarn
step 2 : npm run build/yarn build
step 3 : open dist/index.html
step 4 : check console

**Comment by fangbinwei** [comment]
I think it's not a big deal, since you can get `process.env.VUE_APP_HTTP` correctly.  Try below code to validate
```js
   console.log(process.env.VUE_APP_HTTP)
```

---

If you must want to get `process.env` like you define, there are two way

- **vue.config.js**
```js
/** @type {import('@vue/cli-service').ProjectOptions} */
module.exports = {
    chainWebpack: config => {
        config.plugins.delete('define')
    }
}
```

- **vue.config.js**
```js
/** @type {import('@vue/cli-service').ProjectOptions} */
module.exports = {
    chainWebpack: config => {
        config.plugin('define')
            .tap(args => {
                args[0] = {
                    'process.env': {
                        ...args[0]['process.env'],
                        ...envParams
                    }
                }
                return args
            })
    }
}
```
