### ISSUE TITLE
The clli don't know the js code

### ISSUE THREAD

**Issue by 19Qingfeng** [vuejs/vue-cli#6112]
### Version
4.5.0

### Reproduction link
[https://github.com/19Qingfeng/issues.git](https://github.com/19Qingfeng/issues.git)

### Environment info
```
npm install nx-website-component
```

### Steps to reproduce
yarn
yarn serve

### What is expected?
Identification code and Start project

### What is actually happening?
Cli don't know the js code

**Comment by fangbinwei** [comment]
sorry, I don't know your problem.

**Comment by 19Qingfeng** [comment]
> sorry, I don't know your problem.

I'm not sure why I reported js wrong by cli

**Comment by 19Qingfeng** [comment]
I understand the question,thanks.
