### ISSUE TITLE
初始化vue项目后，npm install 一直停留在extract:core-js: sill extract big.js@3.2.0

### ISSUE THREAD

**Issue by YangZhenFang** [vuejs/vue-cli#612]
vue-cli · Generated "road".

   To get started:
   
     cd road
     npm install
     npm run dev
   
   Documentation can be found at https://vuejs-templates.github.io/webpack

yangzhenfangdeMacBook-Pro:Koa yangzhenfang$ cd road
yangzhenfangdeMacBook-Pro:road yangzhenfang$ npm install
⸨            ░░░░░░⸩ ⠇ extract:core-js: sill extract big.js@3.2.0

**Comment by posva** [comment]
It may be something with your network or proxy because it works well on my side

**Comment by YangZhenFang** [comment]
ok,thank you

**Comment by YangZhenFang** [comment]
ok,thank you

**Comment by caowenkai** [comment]
we need VPN

**Comment by zhangzhangxinmiao** [comment]
Now I have encountered this problem. How did you solve it？
