### ISSUE TITLE
websocket handshake error crash vue-cli 

### ISSUE THREAD

**Issue by yandixuan** [vuejs/vue-cli#6122]
### Version
4.5.9

### Reproduction link
[https://github.com/yandixuan/cli-crash](https://github.com/yandixuan/cli-crash)

### Environment info
```
 Node: 14.15.1 - C:\node-v14.15.1-win-x64\node.EXE
 Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 npm: 6.14.8 - C:\node-v14.15.1-win-x64\npm.CMD
```

### Steps to reproduce
clone the demo which is just created by official cli (i only added code in App.vue and also i added proxy config in vue.config.js)   
the cli crashed when websocket handshake error return 200 or 301
### What is expected?
cli service does't crash

### What is actually happening?
exit when it occurs error
![image](https://user-images.githubusercontent.com/23276822/101466665-5cc3dd00-397c-11eb-907d-46c1ff69d98e.png)
![image](https://user-images.githubusercontent.com/23276822/101466598-4b7ad080-397c-11eb-9e09-16abb1d4bd15.png)

---
then i changed node version to v8.9.4 it's ok,the cli service never crash when connection failed

**Comment by oxiran** [comment]
hi, i got the same error, how did you solved？@[yandixuan](https://github.com/yandixuan)
