### ISSUE TITLE
How to use `htmlWebpackPlugin.options.title` inside SFC template?

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/vue-cli#6124]
### What problem does this feature solve?
Reuse `htmlWebpackPlugin.options.title` outside `index.html`.

### What does the proposed API look like?
none

**Comment by fangbinwei** [comment]
I am not very clear about your problem, maybe what you want is `document.title`, or you can use something like webpack `DefinePlugin`

**Comment by wenfangdu** [comment]
@fangbinwei Yes, `document.title` will do the job, didn't thought it could be so simple 🤣. I'm curious about the "webpack `DefinePlugin`" you mentioned though, can you please elaborate?

**Comment by fangbinwei** [comment]
Raw webpack config like below
```js
{
  entry: 'index.js',
  output: {
    path: __dirname + '/dist',
    filename: 'index_bundle.js'
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: 'My App'
    }),
    new webpack.DefinePlugin({
      TITLE: JSON.stringify('My App'),
    });
  ]
}
```

then you can use `TITLE` in your code @wenfangdu
