### ISSUE TITLE
IE11 memory detection tool found that the page has memory leaks, only increase until the browser crashes

### ISSUE THREAD

**Issue by sunshineYe** [vuejs/vue-cli#613]
### Issues: after Vue packaging, the browser routing switch page causes IE memory overflow
Environment: win 10 (x64) IE 11
Vue version: vue-cli 2.3.3
Plugins: swiper  echarts

![image](https://user-images.githubusercontent.com/10955849/31645419-8862edc0-b32e-11e7-9f04-fcb172057a6f.png)

@ vue-team Help to see the problem, thanks!

**Comment by egoist** [comment]
This is not related to vue-cli, you may use StackOverflow or Forums for support questions.

**Comment by sunshineYe** [comment]
ok, thanks~
