### ISSUE TITLE
node-sass 问题

### ISSUE THREAD

**Issue by flynetgao1** [vuejs/vue-cli#614]
vue-cli 2.9.1 新建的项目无法在4.7 版本的node下 运行，会报错，如果升级到6.x 没问题，但是node-sass就会报错 这个如何处理？

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by flynetgao1** [comment]
thanks resolved
