### ISSUE TITLE
Can not run the command "test:unit" 

### ISSUE THREAD

**Issue by HomyeeKing** [vuejs/vue-cli#6141]
### Reproduction link
[https://github.com/HomyeeKing/learn-test](https://github.com/HomyeeKing/learn-test)

### Environment info
```
vue: 3.0.4
vite app
```

### Steps to reproduce
0. yarn create vite-app xxx
1.  run ` vue add unit-jest `   to add jest, vue-jest  something and  also inject the npm script 'test:unit' automatically
2.   then run 'yarn test:unit'  , it failed
3.  console "shows command not found "

### What is expected?
run the test file automatically

### What is actually happening?
command not found

---
this is a new vite app ,the url is the repo

**Comment by HomyeeKing** [comment]
by the way, is the  test:unit default config same with the Jest?

**Comment by sodatea** [comment]
Vue CLI and Vite are two different tools.

`vue add unit-jest` can only be run in projects that are created by `vue create`
