### ISSUE TITLE
eslint not working for ts file by default config.

### ISSUE THREAD

**Issue by l619534951** [vuejs/vue-cli#6143]
### Version
4.5.9

### Environment info
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.9 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.57)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2
    @vue/babel-plugin-jsx:  1.0.0-rc.4
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.9
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.9
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.9
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.9
    @vue/cli-plugin-router:  4.5.9
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.9
    @vue/cli-plugin-vuex:  4.5.9
    @vue/cli-service: ~4.5.0 => 4.5.9
    @vue/cli-shared-utils:  4.5.9
    @vue/compiler-core:  3.0.4
    @vue/compiler-dom:  3.0.4
    @vue/compiler-sfc: ^3.0.0 => 3.0.4
    @vue/compiler-ssr:  3.0.4
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/eslint-config-typescript: ^5.0.2 => 5.1.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/reactivity:  3.0.4
    @vue/runtime-core:  3.0.4
    @vue/runtime-dom:  3.0.4
    @vue/shared:  3.0.4
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^7.0.0-0 => 7.2.0
    typescript: ~3.9.3 => 3.9.7
    vue: ^3.0.0 => 3.0.4
    vue-eslint-parser:  7.2.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.5 (16.1.1)
    vue-style-loader:  4.1.2
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1、vue create tsdemo

2、choose Babel、TypeScript、Linter

3、choose Vue 3.x

4、choose ESLint   Prettier, and choose default config for other options

5、waitting for finnish

### What is expected?
eslint and prettier working in ts file default.

### What is actually happening?
eslint and prettier not working in ts file default.

---
I think the default eslint config should support ts file. 
英语可能讲不明白，就是默认生成的配置文件，eslint 和 prettier是不是该支持.ts的才对，我默认生成的是不支持的。

eslint default config

  parserOptions: {
       ecmaVersion: 2020
  }

eslint config which working in ts file

  parserOptions: {
    ecmaVersion: 2020,
    parser: '@typescript-eslint/parser'
  }

**Comment by fangbinwei** [comment]
目前生成的是支持.ts的, 你那不支持么? 
![image](https://user-images.githubusercontent.com/13298807/101981464-028e8900-3ca8-11eb-89ef-1a664fad96ad.png)

**Comment by l619534951** [comment]
> 目前生成的是支持.ts的, 你那不支持么?
> ![image](https://user-images.githubusercontent.com/13298807/101981464-028e8900-3ca8-11eb-89ef-1a664fad96ad.png)

在IDEA（2020.2）内不行，默认配置只对.vue、.js文件生效，.ts的不生效，要加这个配置才可以，parser: '@typescript-eslint/parser'

**Comment by fangbinwei** [comment]
应该是IDEA的问题，vscode配合eslint插件没有问题

**Comment by l619534951** [comment]
> 应该是IDEA的问题，vscode配合eslint插件没有问题

那我就关了，我也不清楚是哪里的问题，设置里面的eslint设置也包含了.ts文件，但是就是ts文件不生效

**Comment by tangshuaibo** [comment]
> > 应该是IDEA的问题，vscode配合eslint插件没有问题
> 
> 那我就关了，我也不清楚是哪里的问题，设置里面的eslint设置也包含了.ts文件，但是就是ts文件不生效

请问是如何解决的？遇到了同样的问题

**Comment by l619534951** [comment]
> > > 应该是IDEA的问题，vscode配合eslint插件没有问题
> > 
> > 
> > 那我就关了，我也不清楚是哪里的问题，设置里面的eslint设置也包含了.ts文件，但是就是ts文件不生效
> 
> 请问是如何解决的？遇到了同样的问题
eslint配置文件加这行，parser: '@typescript-eslint/parser'

parserOptions: {
ecmaVersion: 2020,
parser: '@typescript-eslint/parser'
}

**Comment by tangshuaibo** [comment]
> > > > 应该是IDEA的问题，vscode配合eslint插件没有问题
> > > 
> > > 
> > > 那我就关了，我也不清楚是哪里的问题，设置里面的eslint设置也包含了.ts文件，但是就是ts文件不生效
> > 
> > 
> > 请问是如何解决的？遇到了同样的问题
> 
> eslint配置文件加这行，parser: '@typescript-eslint/parser'
> 
> parserOptions: {
> ecmaVersion: 2020,
> parser: '@typescript-eslint/parser'
> }
多谢！
