### ISSUE TITLE
About typescript

### ISSUE THREAD

**Issue by returnGirl** [vuejs/vue-cli#615]
I want to know when will vue-cli support typescript init. 
The vue official said they will soon support this, but when?

**Comment by ckdlbc** [comment]
I also want to know XD
I got inspiration from here [ElemeFE/webpack-typescript](https://github.com/ElemeFE/webpack-typescript)

**Comment by octref** [comment]
I can start working on one, but I have a feeling @egoist has made it somewhere.

**Comment by egoist** [comment]
@octref nope I haven't got a working boilerplate but [this](https://github.com/egoist/poi/tree/master/packages/poi-preset-typescript), it would be awesome to have a boilerplate from you. 😄

**Comment by sthomp** [comment]
This is already being discussed here: https://github.com/vuejs/vue-cli/issues/263

**Comment by posva** [comment]
Duplicate of #263
