### ISSUE TITLE
vue ui 启动后，浏览器打开http://localhost:8000/project/select后一直loading卡死

### ISSUE THREAD

**Issue by xujbOvO** [vuejs/vue-cli#6164]
### Version
4.5.9

### Environment info
```
  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz 
  Binaries:
    Node: 12.16.1 - D:\nodejs\node.EXE
    Yarn: 1.5.1 - D:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - D:\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
```

### Steps to reproduce
安装：npm install -g @vue/cli
创建：vue create test
启动可视化管理：vue ui 

### What is expected?
正常导入新创建的test项目

### What is actually happening?
1、打开了http://localhost:8000/project/select页面；
2、默认加载了以前的项目，无法导入新建的test项目，
3、页面一直loading，界面操作无响应；
4、命令行没有信息输出。
5、电脑会巨卡，cpu飘升，最后编辑器无响应

---
能够正常运行

**Comment by xujbOvO** [comment]
![image](https://user-images.githubusercontent.com/4187351/102995062-38125c80-455b-11eb-8ca9-b8b486f3b5f5.png)
![image](https://user-images.githubusercontent.com/4187351/102995312-bec73980-455b-11eb-8a16-8caf1289647e.png)
![image](https://user-images.githubusercontent.com/4187351/102995535-38f7be00-455c-11eb-87c5-bb1ccfdcfd08.png)

**Comment by sodatea** [comment]
删除 `~/.vue-cli-ui` 目录后再试试？

**Comment by xujbOvO** [comment]
> .vue-cli-ui

正常了。不过导入要好久才结束
