### ISSUE TITLE
vue-cli 创建的项目，在选择TypeScript、Eslint Prettier选项时，创建的项目执行yarn lint命令会报错。这个错误有什么优美的解决方式吗？

### ISSUE THREAD

**Issue by rainydaycode** [vuejs/vue-cli#6165]
### Version
5.0.0-alpha.0

### Reproduction link
复现错误请查看下面的快照~谢谢

### Environment info
```

Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 15.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.0.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2
    @vue/babel-plugin-jsx:  1.0.0-rc.5
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.9
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.9
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.9
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.9
    @vue/cli-plugin-router: ~4.5.0 => 4.5.9
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.9
    @vue/cli-plugin-vuex:  4.5.9
    @vue/cli-service: ~4.5.0 => 4.5.9
    @vue/cli-shared-utils:  4.5.9
    @vue/compiler-core:  3.0.4
    @vue/compiler-dom:  3.0.4
    @vue/compiler-sfc: ^3.0.0 => 3.0.4
    @vue/compiler-ssr:  3.0.4
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/eslint-config-typescript: ^5.0.2 => 5.1.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/reactivity:  3.0.4
    @vue/runtime-core:  3.0.4
    @vue/runtime-dom:  3.0.4
    @vue/shared:  3.0.4
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^7.0.0-0 => 7.3.0
    typescript: ~3.9.3 => 3.9.7
    vue: ^3.0.0 => 3.0.4
    vue-class-component: ^8.0.0-0 => 8.0.0-rc.1
    vue-eslint-parser:  7.3.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.6 (16.1.2)
    vue-router: ^4.0.0-0 => 4.0.1
    vue-style-loader:  4.1.2
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
![Z6 O8285U~K0S B6B8B K$2](https://user-images.githubusercontent.com/39460470/103010161-ca722a80-4572-11eb-81a3-997090da5cc0.png)

### What is expected?
vue-cli创建的项目，即使执行yarn lint命令，应该也不能会出现错误。

### What is actually happening?
执行yarn lint，发生了错误！

C:\git-projects\vue-test>yarn lint
yarn run v1.22.10
$ vue-cli-service lint
warning: Parsing error: '=' expected (prettier/prettier) at src\shims-vue.d.ts:2:16:
  1 | declare module '*.vue' {
> 2 |   import type { DefineComponent } from 'vue'
    |                ^
  3 |   const component: DefineComponent<{}, {}, any>
  4 |   export default component
  5 | }

warning: Unexpected any. Specify a different type (@typescript-eslint/no-explicit-any) at src\shims-vue.d.ts:3:44:
  1 | declare module '*.vue' {
  2 |   import type { DefineComponent } from 'vue'
> 3 |   const component: DefineComponent<{}, {}, any>
    |                                            ^
  4 |   export default component
  5 | }
  6 |

2 warnings found.
Done in 2.91s.

**Comment by sodatea** [comment]
暂时请先手动在文件开头加上 `/* eslint-disable */`
https://github.com/vuejs/vue-cli/blob/451f3d2f5fae5d153d337f00e35be9571638101c/packages/%40vue/cli-plugin-typescript/generator/template-vue3/src/shims-vue.d.ts#L1

我们会在下个版本的默认模板里加上这个注释。

**Comment by rainydaycode** [comment]
嗯嗯好吧，可这样感觉不是很好看。我会试着去接受。

**Comment by sodatea** [comment]
5.0.0-alpha.1 的默认模板加上了注释。

未来会想办法把这些 shim 放到第三方包里，这样就能避免和项目的代码风格冲突了。
或者如果能用上 https://github.com/znck/vue-developer-experience/tree/master/packages/typescript-plugin-vue，这些 shim 文件也是可以不用的。
