### ISSUE TITLE
vue.config.js 引入 postcss-preset-env 导致打包时 publicPath 失效

### ISSUE THREAD

**Issue by chaizhize** [vuejs/vue-cli#6166]
### Version
5.0.0-alpha.0

### Environment info
```
vue: *2.6.11 => 2.6.11     
@vue/cli: 4.5.3
```

### Steps to reproduce
在vue.config.js中加入css/loaderOptions/postcss/plugins/require('postcss-preset-env')，publicPath打包时
publicPath: process.env.ENV === 'production' ? '/project' : '/'。导致打包打不上‘project’

### What is expected?
资源路径正常

### What is actually happening?
缺少project

**Comment by chaizhize** [comment]
这种情况加上 require('postcss-preset-env')后，打包出来的资源路径是不带/project/的，去掉了可以。
```
module.exports = {
    publicPath: '/project/',
    css: {
        loaderOptions: {
            postcss: {
                plugins: [
                       require('postcss-preset-env')
                ]
            }
        }
    }
};
<script src=/js/chunk-vendors.e9a7b99b.js>
<script src=/project/static/js/chunk-vendors.f5cf48cd.js>
```

**Comment by fangbinwei** [comment]
@chaizhize  可以提供复现的repo么

**Comment by chaizhize** [comment]
@fangbinwei 
https://github.com/chaizhize/vue-cli3
branch：test
build：npm run build:prod

**Comment by fangbinwei** [comment]
@chaizhize 在项目中执行 `npm i postcss-preset-env -D` . CLI 在加载vue.config.js的时候忽略了`MODULE_NOT_FOUND`错误, 需要看下这个问题

**Comment by chaizhize** [comment]
@fangbinwei  感谢大佬！

**Comment by fangbinwei** [comment]
Close because this problem has been solved in 5.0.0-alpha.0
