### ISSUE TITLE
vue3   ts 模版下，import 引入文件时，文件地址是否可以省略 .vue 后缀

### ISSUE THREAD

**Issue by zoux** [vuejs/vue-cli#6171]
### What problem does this feature solve?
记得 vue2   js 模版内是可以省略 .vue 后缀的。不知道 vue3   ts 是否可以实现？

### What does the proposed API look like?
可以省略 .vue 后缀。

**Comment by sodatea** [comment]
非常不建议省略 .vue 后缀

参见：
- https://github.com/vitejs/vite/issues/178#issuecomment-630138450
- https://github.com/vuejs/vue-cli/issues/5307
