### ISSUE TITLE
vue3官网通过vite方法构建的项目，无法导入webpack通过umd模式打包出来的静态资源(vue2能导入)

### ISSUE THREAD

**Issue by Ka-Houl** [vuejs/vue-cli#6179]
### Version
5.0.0-alpha.0

### Environment info
```
$ vue info

Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
  Binaries:
    Node: 12.18.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.18362.1.0)
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
未打包的资源：
https://github.com/Ka-Houl/webpack_build_file/blob/master/index.ts
打包生成的资源：
https://github.com/Ka-Houl/webpack_build_file/blob/master/index.js
结果展示情况：
vue3无法导入的结果：
http://sourse.kahoul.top/vue3.png
vue2成功导入的结果：
http://sourse.kahoul.top/vue2.png
webpack打包配置：
http://sourse.kahoul.top/webpack%E6%89%93%E5%8C%85.png

引入写法均为 
import * as utils from './../../index'
console.log('u1tils', utils)

### What is expected?
vue3初始化的项目也能导入webpack打包出来的资源

### What is actually happening?
vue3官网通过vite方法构建的项目，无法导入webpack通过umd模式打包出来的静态资源(但vue2能导入)

**Comment by sodatea** [comment]
你这是 Vite 项目还是 Vue CLI 项目？Vite 项目请到 https://github.com/vitejs/vite/ 提 issue
