### ISSUE TITLE
vue cli not create webpack-simple 

### ISSUE THREAD

**Issue by mehrdadphp** [vuejs/vue-cli#618]
hi 

I upgraded node js and vue cli . but I can not create new template .

>  vue init webpack-simple

```

/usr/local/lib/node_modules/vue-cli/bin/vue-init:60
let template = program.args[0]
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

```

**node : v4.2.6
npm : 3.5.2
vue-cli : 2.9.1**

**Thank you for helping me**

**Comment by posva** [comment]
Use at least node 6
I think that now we should start dropping support for node 4 as node 8 is soon entering LTS

**Comment by mjosborne1** [comment]
Hi I have the same version issue on the  Windows Linux subsystem.
nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.1).
Is there a way to install a newer version other than apt-get or do I need to go running back to powershell?

**Comment by jiujiuwen** [comment]
Perhaps node verison is too low.
update your node version using
```
npm install -g n 
sudo n stable  
sudo npm install npm -g
```
when you *node -v* find there is no change, but try to init vue project again.

**Comment by herOwOw** [comment]
thx

**Comment by herOwOw** [comment]
thx jiujiuwen

**Comment by Musbell** [comment]
Thanks @jiujiuwen

**Comment by tangxininjava** [comment]
Thanks @jiujiuwen

**Comment by dbarjs** [comment]
Thanks @jiujiuwen 
(i'm using Ubuntu 17.04)

**Comment by elinardo10** [comment]
Obrigado @jiujiuwen resolveu meu priblema tbm. Usando ubuntu 16.4 via vagrant

**Comment by Broadroad** [comment]
Thanks @jiujiuwen

**Comment by drRoX-DevCodez** [comment]
Thanks @jiujiuwen
