### ISSUE TITLE
cannot update highlight.js to a non-vulnerable version

### ISSUE THREAD

**Issue by KnowsCount** [vuejs/vue-cli#6180]
### Version
4.5.9

### Environment info
```
Environment Info:

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.0
  npmGlobalPackages:
    @vue/cli: 4.5.9
```

### Steps to reproduce
use `dependabot` in your GitHub repository whilst using `highlight.js` and `vue-cli (versioned 4.5.9)`. 

### What is expected?
I was expecting to use the highest version of `highlight.js` and thus fix a moderate security vulnerability.

### What is actually happening?
It soon warns me of a [moderate security vulnerability](https://github.com/advisories/GHSA-7wwv-vh3v-89cq) which has the impact of Potential ReDOS vulnerabilities (exponential and polynomial RegEx backtracking). I, as a perfectionist, wants to change this situation. 

However, it tells me: 

```
Dependabot cannot update highlight.js to a non-vulnerable version
The latest possible version that can be installed is 9.18.5 because of the following conflicting dependency:

@vue/cli-service@4.5.9 requires highlight.js@^9.6.0 via cli-highlight@2.1.4
The earliest fixed version is 10.4.1.
```

It is a private repo, so I am sorry you cannot see the complete log.

---
I realised just now when choosing my version – is there a 5.0.0 alpha?

That might be the very key.

**Comment by fangbinwei** [comment]
Maybe you should bump the version of `cli-highlight` to `2.1.9` which depends on `highlight.js@10` by yourself. It seems `dependabot` can't handle this case.

**Comment by KnowsCount** [comment]
this should solve the issue as it does for me. Thanks!
