### ISSUE TITLE
After Comand “vue-cli-service build --mode test‘’  finished executing without exiting the process

### ISSUE THREAD

**Issue by sufengyong** [vuejs/vue-cli#6181]
### Version
4.5.9

### Environment info
```
Vue 3.0.5
```

### Steps to reproduce
First init a Vue3.0.5 project by using vue-cli, and then execute command "vue-cli-service build --mode test"

### What is expected?
After building project,the process exit normally.

### What is actually happening?
After building project,the process does not exit，the console stays and do nothing with the log which show 'Build Complete.the app directory is ready to be depoyed. INFO check out deployment in instructions at https://cli.vuejs.org/guide/deployment.html'

---
when i use "vue-cli-service", all is normal

**Comment by sodatea** [comment]
> when i use "vue-cli-service", all is normal

Sorry, I'm not sure I fully understand your question. Does or does everything works fine when you execute `vue-cli-service build --mode test`? Do you have a reproduction repo?
