### ISSUE TITLE
Update vue-property-decorator to v9 in vue 2 projects

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue-cli#6183]
### What problem does this feature solve?
Right now when scaffolding new Vue 2 project with TypeScript and class components, vue-cli installs:
```
    "vue-class-component": "^7.2.3",
    "vue-property-decorator": "^8.4.2"
```

The latest version of `vue-property-decorator` is v9.1.2 and this version should be installed.

### What does the proposed API look like?
For Vue 2 project with TypeScript and class components, install the latest versions of `vue-class-component` and `vue-property-decorator`.

**Comment by sodatea** [comment]
Fixed in 4.5.10
