### ISSUE TITLE
vue cli return error Cannot find module 'is-obj'

### ISSUE THREAD

**Issue by zengAlex** [vuejs/vue-cli#619]
node 6.11.1
npm 3.10.10
system: window7

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
