### ISSUE TITLE
Support .vuerc.js in alternative to vue.config.js

### ISSUE THREAD

**Issue by namnm** [vuejs/vue-cli#6190]
### What problem does this feature solve?
To normalize all config using dotfile

### What does the proposed API look like?
Support .vuerc.js in alternative to vue.config.js

**Comment by sodatea** [comment]
No.

Babel use `babel.config.js` for project-wide configuration https://babeljs.io/docs/en/config-files
PostCSS recommend `postcss.config.js` over other configuration formats https://github.com/webpack-contrib/postcss-loader#config
ESLint is going to support `eslint.config.js` and deprecate `.eslintrc.*` https://github.com/eslint/eslint/issues/13481

I don't see any reason why we should support `.vuerc.js` against the trend.
