### ISSUE TITLE
@babel/plugin-proposal-optional-chaining is not working with @vue/cli-plugin-babel/preset

### ISSUE THREAD

**Issue by wpitallo** [vuejs/vue-cli#6193]
### Version
4.5.10

### Environment info
```
System:
    OS: Linux 4.14 Amazon Linux AMI 2018.03
    CPU: (1) x64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: Not Found
    npm: 6.14.8 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.0 
    @vue/babel-plugin-jsx:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.10 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.10 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.10 
    @vue/cli-plugin-e2e-cypress: ~4.5.0 => 4.5.10 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.10 
    @vue/cli-plugin-pwa: ~4.5.0 => 4.5.10 
    @vue/cli-plugin-router: ~4.5.0 => 4.5.10 
    @vue/cli-plugin-unit-jest: ~4.5.0 => 4.5.10 
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.10 
    @vue/cli-service: ~4.5.0 => 4.5.10 
    @vue/cli-shared-utils:  4.5.10 
    @vue/compiler-core:  3.0.5 
    @vue/compiler-dom:  3.0.5 
    @vue/compiler-sfc: ^3.0.0 => 3.0.5 
    @vue/compiler-ssr:  3.0.5 
    @vue/component-compiler-utils:  3.2.0 
    @vue/eslint-config-standard: ^5.1.2 => 5.1.2 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/reactivity:  3.0.5 
    @vue/runtime-core:  3.0.5 
    @vue/runtime-dom:  3.0.5 
    @vue/shared:  3.0.5 
    @vue/test-utils: ^2.0.0-0 => 2.0.0-beta.13 
    @vue/web-component-wrapper:  1.2.0 
    devextreme-vue: 20.2.4 => 20.2.4 
    eslint-plugin-vue: ^7.0.0-0 => 7.4.1 
    jest-serializer-vue:  2.0.2 
    typescript: ~3.9.3 => 3.9.7 
    vue: ^3.0.0 => 3.0.5 
    vue-eslint-parser:  7.3.0 
    vue-hot-reload-api:  2.3.4 
    vue-jest: ^5.0.0-0 => 5.0.0-alpha.7 (3.0.7)
    vue-loader:  15.9.6 (16.1.2)
    vue-router: ^4.0.0-0 => 4.0.2 
    vue-style-loader:  4.1.2 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^4.0.0-0 => 4.0.0-rc.2 
  npmGlobalPackages:
    @vue/cli: 4.5.10
```

### Steps to reproduce
export const navigation = {test: data?.layouts_mobile?.navigation}

### What is expected?
Expecting compile

### What is actually happening?
Error

---
Module parse failed: Unexpected token (19:38)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| //const test = data?.layouts_mobile?.navigation
| 
> export const navigation = {test: data?.layouts_mobile?.navigation}
| 

 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./node_modules/@wpitallo/globalClient/vue/components/templates/dev-express-dual-menu/layouts/mobile/Mobile.vue?vue&type=script&lang=js 5:0-39 17:18-28
 @ ./node_modules/@wpitallo/globalClient/vue/components/templates/dev-express-dual-menu/layouts/mobile/Mobile.vue?vue&type=script&lang=js
 @ ./node_modules/@wpitallo/globalClient/vue/components/templates/dev-express-dual-menu/layouts/mobile/Mobile.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./node_modules/@wpitallo/globalClient/vue/components/landing/Landing.vue?vue&type=script&lang=js
 @ ./node_modules/@wpitallo/globalClient/vue/components/landing/Landing.vue?vue&type=script&lang=js
 @ ./node_modules/@wpitallo/globalClient/vue/components/landing/Landing.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader-v16/dist??ref--0-1!./node_modules/@wpitallo/globalClient/vue/components/app/default/App.vue?vue&type=script&lang=js
 @ ./node_modules/@wpitallo/globalClient/vue/components/app/default/App.vue?vue&type=script&lang=js
 @ ./node_modules/@wpitallo/globalClient/vue/components/app/default/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?https://0.0.0.0&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by LinusBorg** [comment]
Please provide a reproduction as explained in the issue rules.

**Comment by jrgwerum** [comment]
I`ve got the same issue but, as i figured out, that was no babel or vue problem. It was the typescript tsconfig file that needed to get tweaked. See here  https://stackoverflow.com/questions/58813176/webpack-cant-compile-ts-3-7-optional-chaining-nullish-coalescing

**Comment by wpitallo** [comment]
Not using typescript though.
