### ISSUE TITLE
For a production build, output file names do not change when changing code.

### ISSUE THREAD

**Issue by Mikilll94** [vuejs/vue-cli#6197]
### Version
4.5.10

### Environment info
```
Environment Info:

  System:
    OS: macOS 11.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
  Binaries:
    Node: 12.16.3 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.0.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.0 
    @vue/babel-plugin-jsx:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.10 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.10 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.10 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.10 
    @vue/cli-plugin-router:  4.5.10 
    @vue/cli-plugin-vuex:  4.5.10 
    @vue/cli-service: ~4.5.0 => 4.5.10 
    @vue/cli-shared-utils:  4.5.10 
    @vue/component-compiler-utils:  3.2.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.12 
    vue-eslint-parser:  7.3.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.6 (16.1.2)
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.5.10
```

### Steps to reproduce
1. Download this project and run `npm install`
[test-vue-project.zip](https://github.com/vuejs/vue-cli/files/5791204/test-vue-project.zip)
2. Build this project for production (run `npm run build`)
3. Check and save somewhere output file names. It should be something like this:
```
File                                 Size                                                                Gzipped

  dist/js/chunk-vendors.5a5a5781.js    89.51 KiB                                                           32.08 KiB
  dist/js/app.43bcbd1d.js              4.58 KiB                                                            1.63 KiB
  dist/css/app.fb0c6e1c.css            0.33 KiB                                                            0.23 KiB
```
4. Do some changes in the source code, like i.e. remove the line `alert("Hello");` in App.vue
5. Build the app for production again.
6. Check the output file names. There are exactly the same as before.

As you can see, making changes in the source code does not change the output file names. This is very bad, because it means that when deploying a new version to production, the new code won't be picked up. Thus, the user needs to press CTRL + F5 to see new changes.

IMO, vue-cli should use `[contenthash]` Webpack substitution for generating output file names.
https://webpack.js.org/guides/caching/#output-filenames

By using `[contenthash]`, the hash will change when code changes.

### What is expected?
Output file names in production build should change when source code changes.

### What is actually happening?
Output file names in production build are always the same.

**Comment by sodatea** [comment]
Can't reproduce. The file name changed on my machine.

FYI, Vue CLI did use `[contenthash]`:
https://github.com/vuejs/vue-cli/blob/637414cb6972ff5600f5e37c4e2762a88478c873/packages/%40vue/cli-service/lib/config/app.js#L31-L34

**Comment by Mikilll94** [comment]
@sodatea 
Hm... You are right. I have checked this in details and file names are changing when making changes in the source code. However, many when I deployed Vue app to IIS server, I have encountered this caching problem and the user was forced to press CTRL+F5. Do you have any ideas what could be the reason?

**Comment by sodatea** [comment]
If a CTRL + F5 can solve the problem, the cache is on the `index.html` side. See https://stackoverflow.com/questions/26600845/how-to-disable-caching-of-single-page-application-html-file-served-through-iis
