### ISSUE TITLE
The project generated with vue-cli init webpack-simple is not able to run under IE11

### ISSUE THREAD

**Issue by yinshipeng** [vuejs/vue-cli#620]
![](http://ow3sf64ph.bkt.clouddn.com/17-10-24/53412304.jpg)
![](http://ow3sf64ph.bkt.clouddn.com/17-10-24/34486496.jpg)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by yinshipeng** [comment]
What is the gitter url of vue-cli？

**Comment by LinusBorg** [comment]
We don't really have a specific gitter for vue-cli, the official chat is on discord.
