### ISSUE TITLE
why the NODE_ENV is '"development"' rather than 'development'?

### ISSUE THREAD

**Issue by sqfbeijing** [vuejs/vue-cli#621]
I found when i want set the NODE_ENV in package.json, i can use NODE_ENV=development   or NODE_ENV='development'   achive my goal, but why in the vue-cli , there is two quotes?
code in vue-cli:

```
module.exports = merge(prodEnv, {
  NODE_ENV: '"development"'
})
```
code in myself project:
```
		"test": "echo \"Error: no test specified\" && exit 1",
		"watch": "NODE_ENV='production' webpack --watch --config webpack.prod.config.js",
		"dev": "NODE_ENV='development' webpack-dev-server --open --config webpack.dev.config.js",
		"build": "NODE_ENV='production' webpack --config webpack.prod.config.js"
```

**Comment by sqfbeijing** [comment]
links: (https://doc.webpack-china.org/guides/production/#cli-)[https://doc.webpack-china.org/guides/production/#cli-]

**Comment by posva** [comment]
Because it's a basic string replacement (like using `sed -i`) so we need to add quotes to keep it as a string in the js code

**Comment by sqfbeijing** [comment]
@posva  thanks very much, i find the reason.  and the  [plugin.](https://doc.webpack-china.org/plugins/define-plugin)
