### ISSUE TITLE
ios白屏

### ISSUE THREAD

**Issue by 767339608** [vuejs/vue-cli#6213]
### Version
5.0.0-alpha.2

### Environment info
```
node 版本12.14  vue 3
```

### Steps to reproduce
所有项目

### What is expected?
正常显示页面

### What is actually happening?
在ios10.0.2上白屏报错

**Comment by sodatea** [comment]
应该是这个问题：https://github.com/vuejs/vue-next/pull/2943
我查了一下 ShadowRoot 在 iOS 10.1 以上才支持。

这个问题会在下个版本的 Vue 3 里修复，不是 CLI 的 bug，所以我先把这个 issue 关掉了。
