### ISSUE TITLE
sample not working properly in vue3

### ISSUE THREAD

**Issue by kumaresan-subramani** [vuejs/vue-cli#6217]
### Version
4.5.0

### Reproduction link
[https://github.com/kumaresan-subramani/vue3-suport](https://github.com/kumaresan-subramani/vue3-suport)

### working sample

sample sample with `"vue": "^2.6.11` works fine without any error

https://github.com/Saranya13/vue-sample/

### Environment info
```
"vue": "^3.0.5"
"@vue/cli-plugin-babel": "^4.5.10",
    "@vue/cli-plugin-eslint": "^4.5.10",
    "@vue/cli-service": "^4.5.10",
    "@vue/compiler-sfc": "^3.0.5",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.8.0",
    "eslint-plugin-vue": "^7.4.1",
```

### Steps to reproduce
clone above mentioned smple
then `npm i`
finally npm run serve

browser throws script error, but the same working fine in `vue2`

### What is expected?
component gets rendered without script error

### What is actually happening?
throws script error

```
component-base.js?5981:6 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at extendStatics (component-base.js?5981:6)
    at __extends (component-base.js?5981:9)
    at eval (component-base.js?5981:20)
    at eval (component-base.js?5981:195)
    at Module../node_modules/@syncfusion/ej2-vue-base/src/component-base.js (chunk-vendors.js:575)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (index.js?4867:1)
    at Module../node_modules/@syncfusion/ej2-vue-base/src/index.js (chunk-vendors.js:599)
```

**Comment by kumaresan-subramani** [comment]
@sodatea , any suggestion on this?

Here we re extending `Vue` as like below

https://github.com/syncfusion/ej2-vue-ui-components/blob/master/components/base/src/component-base.ts#L7

After webpack done its job, it generates like below:

![image](https://user-images.githubusercontent.com/36756050/104994910-66486680-5a4b-11eb-868b-1544201fc075.png)

## Here `Vue` gets undefined, so extend not work s expected in latest vue 3, refer below:

![image](https://user-images.githubusercontent.com/36756050/104995012-93951480-5a4b-11eb-800e-2ae7fd4c2f87.png)

**Comment by sodatea** [comment]
Yeah, Vue 3 doesn't work this way. It's no longer `new`able. Maybe you should check out the Vue base class from `vue-class-component`. https://github.com/vuejs/vue-class-component/issues/406#issue-584349864

**Comment by kumaresan-subramani** [comment]
Hi @sodatea ,

Thnks for your reply,

i m still confused

Here what do you want me to change to get this work

https://github.com/syncfusion/ej2-vue-ui-components/blob/master/components/buttons/src/button/button.component.ts

**Comment by sodatea** [comment]
I'm not sure. `class Base extends Vue` and then `class Button extends Base` wasn't actually a recommended pattern, so I have little experience with such usage.

Maybe changing the `import Vue from 'vue'` to `import { Vue } from 'vue-class-component'` in all the files can do the trick?

**Comment by kumaresan-subramani** [comment]
@sodatea , yes i tried but still facing same issue `Vue` module reference gets undefined.

Is there any migration tool available?

**Comment by sodatea** [comment]
> Is there any migration tool available?

The tool is not yet ready. Even if it's ready, I'm afraid it won't be helpful in this use case.

> yes i tried but still facing same issue `Vue` module reference gets undefined.

Make sure you are using `vue-class-component` v8.0.0-rc.1, not v7.

I found a test case in its repo, it should work: https://github.com/vuejs/vue-class-component/blob/53c0535c81fea0a7f6d1d279318e671033b790d1/test/specs/test.spec.ts#L143-L167

**Comment by kumaresan-subramani** [comment]
Thanks @sodatea , will try this

**Comment by kumaresan-subramani** [comment]
@sodatea 

Please find detailed Info, please suggest on this

![Untitled](https://user-images.githubusercontent.com/36756050/105133221-5ba4d480-5b12-11eb-881e-26ae12594284.png)

**Comment by kumaresan-subramani** [comment]
## in old vue version, i am getting extend method reference

![image](https://user-images.githubusercontent.com/36756050/105139040-c0b0f800-5b1b-11eb-8da3-f8757d705011.png)

**Comment by sodatea** [comment]
It's because in Vue 3 there's no `extend` method.
I guess your decorator implementation is influenced by https://github.com/vuejs/vue-class-component/blob/master/src/component.ts#L24-L91? It's refactored out in the `next` branch for Vue 3. I'm no expert on vue-class-component, so maybe you need to ask someone else for further guidance.

**Comment by kumaresan-subramani** [comment]
@sodatea , Thanks for your details.

yes, our decorator implementation based on this only. Then what will be the alternate way for `extend`.

Can you suggest someone who know this details

**Comment by sodatea** [comment]
The Vue 3 support of `vue-class-component` is done by @ktsn.

**Comment by kumaresan-subramani** [comment]
@ktsn , Can you please suggest on this

**Comment by kumaresan-subramani** [comment]
@sodatea , can you please re-open this issue

**Comment by sodatea** [comment]
I'm afraid not. Because it's not a bug in Vue CLI.

**Comment by kumaresan-subramani** [comment]
Can i open new issue Vue repo?

**Comment by ktsn** [comment]
Use `extends` option.
https://v3.vuejs.org/api/options-composition.html#extends

**Comment by kumaresan-subramani** [comment]
@ktsn , thanks for your reply.

Will check and update you.

**Comment by Tonysmark** [comment]
```tsx
```

**Comment by kumaresan-subramani** [comment]
> Use `extends` option.
> https://v3.vuejs.org/api/options-composition.html#extends

HI @ktsn ,

Our decorator implementation influenced by below

https://github.com/vuejs/vue-class-component/blob/master/src/component.ts#L82

Here it is not possible to extend options as like your suggestion

**Comment by kumaresan-subramani** [comment]
HI @ktsn ,

Any update on this

**Comment by ktsn** [comment]
Just extend a super Vue constructor if you need a constructor:

```js
// const Extended = Super.extend(options)
@Options(options)
class Extended extends Super {}

return Extended
```

**Comment by kumaresan-subramani** [comment]
HI @ktsn ,

Still i am not clear on your comment,

Here below is `decorator` class which extends `options` to component after all changes [**added props, methods and etc to options**] done .

**class** - https://github.com/vuejs/vue-cli/issues/6217#issuecomment-772248200

**Return value** - https://github.com/vuejs/vue-class-component/blob/master/src/component.ts#L90

**My Decorator implementation s like yours** - https://github.com/kumaresan-subramani/ej2-vue-ui-components/blob/master/components/base/src/component-decorator.ts#L29-L126


**Using my decorator** - https://github.com/kumaresan-subramani/ej2-vue-ui-components/blob/master/components/buttons/src/button/button.component.ts#L15


Here i am not sure where you want me to use like above

**Comment by kumaresan-subramani** [comment]
Do you want me to change like below:

https://github.com/kumaresan-subramani/ej2-vue-ui-components/commit/f8778c2ea53535f3b4d1bac9ccdeec660ae2cb6d

**Comment by kumaresan-subramani** [comment]
Hi @ktsn 

Any update on this.

**Comment by kumaresan-subramani** [comment]
Hi @ktsn ,

will below way work in vue3

https://github.com/syncfusion/ej2-vue-ui-components/blob/master/components/buttons/src/button/button.component.ts#L63

Now i have extended options using `definecomponent` - refer below: but component not get registered properly

![Untitled](https://user-images.githubusercontent.com/36756050/108997927-39304900-76c6-11eb-9d21-800c61f67c35.png)

 ## Error:
![image](https://user-images.githubusercontent.com/36756050/108998539-0d619300-76c7-11eb-8f28-f9916c50b930.png)
