### ISSUE TITLE
4.5.x 打包库lib 报错

### ISSUE THREAD

**Issue by xiaogaofudao** [vuejs/vue-cli#6244]
### Version
4.5.11

### Reproduction link
[https://github.com/xiaogaofudao/demo](https://github.com/xiaogaofudao/demo)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 88.0.4324.104
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.2
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.11
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.11
    @vue/cli-plugin-babel: ~4.5.11 => 4.5.11
    @vue/cli-plugin-eslint: ~4.5.11 => 4.5.11
    @vue/cli-plugin-router:  4.5.11
    @vue/cli-plugin-vuex:  4.5.11
    @vue/cli-service: ~4.5.11 => 4.5.11
    @vue/cli-shared-utils:  4.5.11
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^7.5.0 => 7.5.0
    vue-eslint-parser:  7.4.1
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.6 (16.1.2)
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.12 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
执行 npm run build   => 实际执行 vue-cli-service build --target lib --name index src/index.js

### What is expected?
希望打包成功

### What is actually happening?
打包库文件。4.5.x 版本的 都报错。降级 4.4.x 可以打包成功。
报错信息：

vue-cli-service build --target lib --name index src/index.js

Building for production as library (commonjs,umd,umd-min)...
ERROR Failed to compile with 1 error 下午8:11:10
error in ./src/components/Dialog/index.vue

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

| <el-dialog
| class="v-dialog"

@ ./src/index.js 1:0-41 4:18-24 4:31-37
@ ./node_modules/@vue/cli-service/lib/commands/build/entry-lib.js

**Comment by sodatea** [comment]
请提供可以复现的代码

**Comment by xiaogaofudao** [comment]
@sodatea 复现仓库  https://github.com/xiaogaofudao/demo

**Comment by xiaogaofudao** [comment]
> vue-cli-service build --target lib --name index src/index.js


/  Building for production as library (commonjs,umd,umd-min)...

 ERROR  Failed to compile with 1 error                                                                                                                                                          上午9:31:49
 error  in ./src/components/Dialog/index.vue

Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|   <div></div>
| </template>

 @ ./src/index.js 1:0-41 4:18-24 4:31-37
 @ ./node_modules/@vue/cli-service/lib/commands/build/entry-lib.js

**Comment by fangbinwei** [comment]
CLI会根据node_modules中`vue`的版本配置相应版本的`vue-loader`。

`peerDependencies`字段其实也需要考虑, 我更建议使用`npm i vue@2 -D`来让CLI知道你使用的vue版本(而且在没有`vue`的情况下开发/调试组件也不是很方便)

**Comment by xiaogaofudao** [comment]
@fangbinwei 多谢大佬，完美解决

**Comment by xiaogaofudao** [comment]
@fangbinwei npm i -D vue@2.6.12 是可以解决报错问题，也打包了。发现比 4.4.x 不安装 vue 打包 大了不少，另外项目引入打包后的库文件项目。发现 vue 被打包了两次。
开发模式下控制台提示：
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
出现了两次。怎么回事呢

**Comment by xiaogaofudao** [comment]
能否不强制安装 vue。读取 vue-template-compiler 或者 peerDependencies 下面的vue 版本

**Comment by fangbinwei** [comment]
> 发现比 4.4.x 不安装 vue 打包 大了不少

可以提供对比的demo么?

> 另外项目引入打包后的库文件项目。发现 vue 被打包了两次。

怎么确定vue被打包了两次, 打包后的代码里有两份vue的代码? 库文件 和vue被打包两次应该没有直接关系?

**Comment by xiaogaofudao** [comment]
@fangbinwei 之前为方便调试，使用的是 npm link 模式链接源码。经过测试发现，改为 npm i 安装后，正常了
