### ISSUE TITLE
建议 vue-cli 加上critical css 这样的优化

### ISSUE THREAD

**Issue by avilang** [vuejs/vue-cli#625]
目前 vue-cli 样式打包都只生成一个css的文件，如果工程大，这个css文件就比较大了，会影响首次页面渲染的时间，建议可以加上类似 [critical css](https://github.com/addyosmani/critical) 这样的优化

**Comment by posva** [comment]
Please open the issue in the relevant template repo.
If you have SSR and want to add it to your project you can check the SSR docs: https://ssr.vuejs.org/en/css.html

Googling critical css vue lead me to this article: https://vuejsdevelopers.com/2017/07/24/critical-css-webpack/ might be helpful
