### ISSUE TITLE
 Failed to download repo vuejs-templates/webpack-simple: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by Stenfrank** [vuejs/vue-cli#626]
When executing the command "vue init webpack-simple lesson22" generates the following error:

vue-cli · Failed to download repo vuejs-templates/webpack-simple: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:80

I'm not inside a proxy
I attach the configuration

; cli configs
long = true
metrics-registry = null
scope = ""
user-agent = "npm/5.4.2 node/v8.8.1 win32 x64"

; userconfig C:\Users\PC\.npmrc
https-proxy = null
registry = null
strict-ssl = false

; builtin config undefined
prefix = "C:\\Users\\PC\\AppData\\Roaming\\npm"

; default values
access = null
allow-same-version = false
also = null
always-auth = false
auth-type = "legacy"
bin-links = true
browser = null
ca = null
cache = "C:\\Users\\PC\\AppData\\Roaming\\npm-cache"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
dry-run = false
editor = "notepad.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "C:\\Users\\PC\\AppData\\Roaming\\npm\\etc\\npmrc"
globalignorefile = "C:\\Users\\PC\\AppData\\Roaming\\npm\\etc\\npmignore"
group = 0
ham-it-up = false
heading = "npm"
https-proxy = null
if-present = false
ignore-prepublish = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\\Users\\PC\\.npm-init.js"
init-version = "1.0.0"
json = false
key = null
legacy-bundling = false
link = false
local-address = undefined
loglevel = "notice"
logs-max = 10
; long = false (overridden)
maxsockets = 50
message = "%s"
metrics-registry = null
node-version = "8.8.1"
offline = false
onload-script = null
only = null
optional = true
package-lock = true
parseable = false
prefer-offline = false
prefer-online = false
; prefix = "C:\\Program Files\\nodejs" (overridden)
production = false
progress = true
proxy = null
rebuild-bundle = true
; registry = "https://registry.npmjs.org/" (overridden)
rollback = true
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
scripts-prepend-node-path = "warn-only"
searchexclude = null
searchlimit = 20
searchopts = ""
searchstaleness = 900
send-metrics = false
shell = "C:\\WINDOWS\\system32\\cmd.exe"
shrinkwrap = true
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
; strict-ssl = true (overridden)
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "C:\\Users\\PC\\AppData\\Local\\Temp"
umask = 0
unicode = false
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "C:\\Users\\PC\\.npmrc"
version = false
versions = false
viewer = "browser"

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is more of network issue btw

**Comment by Stenfrank** [comment]
Thanks for your answer

**Comment by lifeMiik** [comment]
@Stenfrank Did you fixed the problem? I meat the same problem.

**Comment by wansj** [comment]
@lifeMiik I encoutered this issue too. My solution is: 
1. Recover the hosts file to default
2. Remove the HTTP_Proxy and HTTPs_Proxy env variables

**Comment by lifeMiik** [comment]
@wansj Thanks.  I had fix it by used the code npm config set http-profix null

**Comment by zuekegreen** [comment]
I have the same problem i cannot fix it .. help me please i still got vue-cli . Failed to download repo

**Comment by CharlesLN** [comment]
I have the same problem too.. the message is `vue-cli · Failed to download repo vuejs-templates/webpack: tunneling socket could not be established, cause=socket hang up`

my env: vue 2.9.2
node 9.2.1
webpack 3.10.0
npm -V: 5.6.0
cnpm: 5.1.1

Please help me if you know how to fix it, thank you all.

**Comment by lifeMiik** [comment]
@zuekegreen  
1.Recover the hosts file to default
2.Terminal input the code
npm config set http-profix null

**Comment by localheinz** [comment]
If you run into this: disabling VPN helped.
