### ISSUE TITLE
vue add @vue/unit-jest not working

### ISSUE THREAD

**Issue by shashiOrdant** [vuejs/vue-cli#6264]
### Version
5.0.0-alpha.3

### Environment info
```
Vue  2.9.6
```

### Steps to reproduce
I had created new project using https://github.com/vuejs-templates/webpack (without tests)
installed npm install @vue/cli-plugin-unit-jest
run command vue add unit-jest and nothing happens

### What is expected?
Expect jest to be added in project

### What is actually happening?
![image](https://user-images.githubusercontent.com/46495737/107118594-ebcf7180-68a7-11eb-9d48-764aaac5c60c.png)

---
I am quite new to it so any help will be appreciated

**Comment by fangbinwei** [comment]
you can install `@vue/cli`,  then creating project by command `vue create`

 > https://cli.vuejs.org/guide/installation.html

**Comment by sodatea** [comment]
You are using Vue CLI 2.x, and plugins are for Vue CLI 3 or later.
