### ISSUE TITLE
Which packages can be updated and which cannot

### ISSUE THREAD

**Issue by m4ss1m0g** [vuejs/vue-cli#6267]
### What problem does this feature solve?
Inside the package.json there are vuecli plugin like this:

```
    "@vue/cli-plugin-babel": "~4.5.8",
    "@vue/cli-plugin-eslint": "~4.5.8",
    "@vue/cli-plugin-router": "~4.5.8",
    "@vue/cli-plugin-typescript": "~4.5.8",
    "@vue/cli-plugin-unit-jest": "~4.5.8",
    "@vue/cli-plugin-vuex": "~4.5.8",
    "@vue/cli-service": "~4.5.8",
```

I have also the package `eslint`, `vuex-module-decorator` (if I working with typescript), `jest`.

How I can know until version I can update `xxx` package  ? 

For example I cannot find any clue if Jest v 26 is supported by the plugin unit-jest.

### What does the proposed API look like?
On https://cli.vuejs.org/core-plugins specify for each plugin which is the max version supported by the plugin.

**Comment by sodatea** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by sodatea** [comment]
Oh, sorry, you are asking for a documentation update - that's a valid feature request.
