### ISSUE TITLE
how to remove typescript

### ISSUE THREAD

**Issue by liyong2008** [vuejs/vue-cli#6268]
### What problem does this feature solve?
i has selected typescript option when i generate code use vue-cli,but the last i won`t use typescript,so i remove the ts-relative dependency from package.json and rename main.ts to main.js,but it seems vue-cli has assumed at generated it,it confirmed，it forever,
it`s has error when i execute cmd 'npm run serve',！！！it doesn`t means that i must regenerate it again，i`m totally confused

### What does the proposed API look like?
none

**Comment by fangbinwei** [comment]
Did you remove `@vue/cli-plugin-typescript` ?  Or could you provide reproducible repo

**Comment by sodatea** [comment]
It is not a feature request. Please don't abuse GitHub issues.
