### ISSUE TITLE
vue init webpack error · [README.md] Missing helper: "if_or"

### ISSUE THREAD

**Issue by memoryleakyu** [vuejs/vue-cli#627]
vue init webpack my-project

? Project name ***
? Project description ***
? Author ***
? Vue build standalone
? Install vue-router? No
? Use ESLint to lint your code? No
? Setup unit tests with Karma + Mocha? No
? Setup e2e tests with Nightwatch? No
   vue-cli · [README.md] Missing helper: "if_or"

I tried several times and the error seems to be randomly reported. like this
vue-cli · [package.json] Missing helper: "if_or"

my node version is 8.5.0

a lot appreciate if you could solve this problem

**Comment by posva** [comment]
Could you give more information about your OS? I'm unable to reproduce it on OS X

**Comment by memoryleakyu** [comment]
Sorry I forgot to mention it. I'm using it on **windows 10** . I also tired it with node v8.9.0. It reported the same error `vue-cli · [package.json] Missing helper: "if_or"`. 
I have used vue-cli 2.8.2 before successfully with the same computer and os. Dont know what happened when I updated the vue-cli to 2.9.1

**Comment by khoanguyen96** [comment]
Hey, are you using yarn or npm?
I encountered a similar issue but it was complaining about `Missing helper: "if_eq"` ...

**Comment by HaitianLiu** [comment]
I got the exactly same error on my OS X.

**Comment by memoryleakyu** [comment]
my problem was solved. try not to name the project. 
just use `vue init webpack` then everything goes well. don't know what's the trick behind it

**Comment by LinusBorg** [comment]
OPs problem was solved, reproductions where not provided, issue has been inactive for 7 days.

=> Closing.

**Comment by nazar-xda** [comment]
`vue init pwa myproject`

? Project name myproject
? Project short name: fewer than 12 characters to not be truncated on homescreens (default: same as name)
? Project description A Vue.js project
? Author Mohamed Abdul Nazar <nazarvio2.0@gmail.com>
? Vue build standalone
? Install vue-router? Yes
? Use ESLint to lint your code? Yes
? Pick an ESLint preset Standard
? Setup unit tests with Karma + Mocha? Yes
? Setup e2e tests with Nightwatch? Yes
   **vue-cli · [.eslintrc.js] Missing helper: "if_eq"**

node  : 8.5.0
vue-cli: 2.9.2
OS: Windows 10

**Comment by adrienthiery** [comment]
Hey there @LinusBorg ,

Got that error today on MacOSX 10.12.6.

Installing `vue-cli` with `yarn` globally threw that error. 

Uninstalling it and reinstalling it with `npm i -g vue-cli` solved the problem.

Hopefully this helps

**Comment by drazisil** [comment]
@adrienthiery Do you have any idea why that is? Seems like a strange edge case. 

I assume it's related to https://github.com/vuejs-templates/webpack/blob/develop/template/.babelrc#L11 but the only reference I can find to `if_or` is that only `if_eq` is registered here https://github.com/vuejs/vue-cli/blob/master/lib/generate.js#L14

That said, I'm at a loss as to why npm install works and yarn doesn't.

**Comment by Drudwyn** [comment]
Reproduced this bug, on Windows 10, installing using npm. 

```
npm uninstall -g vue-cli
removed 264 packages in 3.876s

C:\Users\my.user\Documents\js>npm i -g vue-cli
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
C:\Users\my.user\AppData\Roaming\npm\vue-list -> C:\Users\my.user\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-list
C:\Users\my.user\AppData\Roaming\npm\vue -> C:\Users\my.user\AppData\Roaming\npm\node_modules\vue-cli\bin\vue
C:\Users\my.user\AppData\Roaming\npm\vue-init -> C:\Users\my.user\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-init
+ vue-cli@2.9.2
added 264 packages in 17.433s

C:\Users\my.user\Documents\js> vue init webpack --offline
> Use cached template at ~\.vue-templates\webpack

? Generate project in current directory? Yes
? name js
? author Me <me@work.co.uk>
   vue-cli · [.babelrc] Missing helper: "if_or"

```

Had to git clone the webpack repo down, and move the vue-templates down to the .vue-templates/webpack/template dir:

`C:\Users\my.user\.vue-templates\webpack\template`
