### ISSUE TITLE
image not show with a base64 encoded byte array source.

### ISSUE THREAD

**Issue by rrki** [vuejs/vue-cli#628]
I have something like this:

```
<template>
<div><img :src="image_sourse" /></div>
</template>

<script>
...{
   mounted: async function() {
        // f() return a base64 image source e.g, "data:image/png;base64,...."
        this.image_source = await f(); 
   }
}
...
</script>
```

From the page source I see HTML block seems to be correct.. but can't display the image and log an error `Failed to load resource: net::ERR_INVALID_URL` in the console.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
