### ISSUE TITLE
Update source code template when gererating project by vue-cli

### ISSUE THREAD

**Issue by andres-iniesta** [vuejs/vue-cli#6280]
### What problem does this feature solve?
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.

**This is message when I install packages after generating project by cli, please update template to use @babel/eslint-parser instead of babel-eslint** 

### What does the proposed API look like?
```
"devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/eslint-parser": "^7.12.16",
    ...
}
```

**Comment by fangbinwei** [comment]
You can try to upgrade `@vue/cli-plugin-eslint`  to v5 
```
vue upgrade  eslint -t v5.0.0-alpha.4
```

**Comment by andres-iniesta** [comment]
OK let me try @fangbinwei. Thank you.
