### ISSUE TITLE
<script setup> not working on root component in production build

### ISSUE THREAD

**Issue by raukaute** [vuejs/vue-cli#6282]
### Version
4.5.11

### Environment info
```
System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
  Binaries:
    Node: 15.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.4.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.68)
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Create new project with vue create testing (select vue3)

In App.vue change `<script></script>` block to 

```
<script setup>
/* eslint-disable */
import HelloWorld from "./components/HelloWorld.vue";
</script>
```

works:
Run: `npm run serve`   -> Everything works as expected;

does not work:
Run: `npm run build` 
Serve dist directory (e.g. http-server)  -> nothing gets rendered

### What is expected?
Render App

### What is actually happening?
App does not get rendered

---
I somehow have the feeling, that this was working before. This is only happening on the root App component. 
When I look the imported object, I don't see any render function.

Cheers!

**Comment by meedfine** [comment]
me too
when i use <script setup>  and defineProps 
run serve      no problem
run build    the component who use script setup    render empty

**Comment by zizyzhang** [comment]
一样的问题

**Comment by mitow7821** [comment]
Downgrade from 3.0.11 to vue 3.0.0 and adding code above solved problem in my case.

**Comment by bodograumann** [comment]
Just got stuck on this issue for hours, trying to reproduce it locally, where I usually only do development builds. I guess that is what you get for using experimental features :disappointed:

The reason, it is so hard to pin-point, is that after a local development build the `node_modules/.cache` is primed with correct compilation results. Then in the production build, some of these are reused and yield a correct build. Only when you delete the cache (or run `npm ci`) and directly start the production build, will you get the error locally.

**Comment by XHalso** [comment]
I have the same problem, I try the following way, works for me
Using Vue 3.1.4:
```javascript
<script lang='ts' setup>
  ...
</script>

<template>
  ...
</template>
```
But I don't know why the following way can be used to build successfully in vite, but in Vue cli, the value of template refs is undefined after build
```javascript
<template>
  <Header ref="header"></Header>
</template>

<script lang='ts' setup>
  import Header from "@/components/Header.vue";
  const header = ref(); // header.value is undefined
</script>
```

**Comment by bodograumann** [comment]
@XHalso: Your question seems offtopic. My guess would be, that the ref is only available after the component was mounted, not during setup(). If you have further question please come join us in discord!

**Comment by XHalso** [comment]
> @XHalso: Your question seems offtopic. My guess would be, that the ref is only available after the component was mounted, not during setup(). If you have further question please come join us in discord!

There is something wrong with the above example code, but I did build it, and in onmounted, template refs is undefined

**Comment by suyingtao** [comment]
run:
```
$ yarn add vue-loader --dev
```
can solve.

https://github.com/vuejs/vue-loader/issues/1838

**Comment by talrasha007** [comment]
> run:
> 
> ```
> $ yarn add vue-loader --dev
> ```
> 
> can solve.
> 
> [vuejs/vue-loader#1838](https://github.com/vuejs/vue-loader/issues/1838)

this works for me.

**Comment by sodatea** [comment]
I think this issue is fixed since `vue-loader@16.3.0` if it's indeed caused by the `thread-loader` bug mentioned above.

**Comment by bodograumann** [comment]
I can confirm that it was fixed for me, but the relevant commit is only included since `vue-loader@16.3.1`.

**Comment by hello-hyh** [comment]
> run:
> 
> ```
> $ yarn add vue-loader --dev
> ```
> 
> can solve.
> 
> [vuejs/vue-loader#1838](https://github.com/vuejs/vue-loader/issues/1838)



> run:
> 
> ```
> $ yarn add vue-loader --dev
> ```
> 
> can solve.
> 
> [vuejs/vue-loader#1838](https://github.com/vuejs/vue-loader/issues/1838)

work for vue@3.2.6 when using setup script.

**Comment by numfin** [comment]
its not working

**Comment by numfin** [comment]
@sodatea its not working

**Comment by marsimeau** [comment]
For anyone still having the issue. I am working with `yarn` and Vue CLI, and I solved the problem by adding the following snippet to my package.json :

```
"resolutions": {
  "vue-loader": "^16.8.1"
}
```

I believe this is necessary because `@vue/cli-service` is using its own `vue-loader` version.

**Comment by numfin** [comment]
After failing with `vue-loader@latest` instalation i decided to update everything to the latest and it worked. By everything i mean:
`vue`, `@vue/cli-service`, `@vue/comiler-sfc`, `vue-loader`

![image](https://user-images.githubusercontent.com/8134947/134704088-4690ce53-88d1-415b-93ab-c23e2673f741.png)
