### ISSUE TITLE
e2e test webdriverio can not open firefox

### ISSUE THREAD

**Issue by Assone** [vuejs/vue-cli#6288]
### Version
4.5.11

### Reproduction link
[https://github.com/Assone/Music](https://github.com/Assone/Music)

### Environment info
```
Environment Info:

  System:
    OS: macOS 11.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz
  Binaries:
    Node: 15.2.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.182
    Edge: 88.0.705.68
    Firefox: 85.0.2
    Safari: 14.0.3
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
yarn install
yarn test:e2e

### What is expected?
Open firefox for testing

### What is actually happening?
FAILED

**Comment by sodatea** [comment]
Delete the `port` field.
https://github.com/Assone/Music/blob/6cf424b84da70388a2b3eb40d9033ec1cb252f07/wdio.local.conf.ts#L28
