### ISSUE TITLE
Vue build docs out of date, should mention Poi

### ISSUE THREAD

**Issue by daveknapik** [vuejs/vue-cli#629]
I'm new to Vue, vue-cli, etc, but I was excited to see that "vue build" could prepare a build for production. I was less happy when I saw this, because the main repository readme points me to https://github.com/vuejs/vue-cli/blob/master/docs/build.md to learn about building:

> -> vue build
> 
>   We are slimming down vue-cli to optimize the initial installation by removing the `vue build` command.
>   Check out Poi (https://github.com/egoist/poi) which offers the same functionality!

On the awesome side, I installed Poi, and it works, but I think it would be nice to have documentation here about how to use Poi as the build tool. It seems like Poi can do more than just build though? Can it do everything vue-cli can do? Some words about the relationship between the two tools here would be really appreciated by a noob like me, who is also learning a million other things right now. I want to learn about Poi more, but right now I just need to know how it relates to vue-cli as the replacement build tool.

Thanks.

**Comment by posva** [comment]
This is, in a way, part 3.0 #589 
If you need to know about poi, then you should go to its repo instead 😄

**Comment by daveknapik** [comment]
@posva Thanks for your reply. I read #589 but I still think the 2.x docs should not tell us to use vue-build when vue-build is no longer a part of the project. True, you run it and it tells you to use Poi, but a few sentences here about what part of poi you need to focus on, I think, would really help. Poi is a deep, deep project and telling us to basically RTFM isn't a great answer, imho.

**Comment by LinusBorg** [comment]
The first page of poi's documentation tells you exactly what to do to get a build running in about 3 paragraphs. I don't really know how to shorten that, or what benefit copying that section over to `vue-cli's` README would bring - but we are open to suggestions.

Generally, I think "RTFM" is part of our jobs as developers - documentation is there to be read, and asking people to do so isn't a bad thing, if that documentation is good, which I think POI's is.

**Comment by daveknapik** [comment]
@LinusBorg Ok cool, once I understand all this more, I might pull request you, but 3.0 might be done then! haha.

Poi has awesome docs, yes, and I read through them and totally got a build running. But it also seems like it can do so much more than just build my vue-cli generated app. That's the source of the confusion for me here. At the very least, I think vue-cli docs need to not say "use vue-build" since it is no longer there. Just say "use Poi to build" or something and link to that.

Sorry to ask for clarification here, because I know a forum thread might be better, but here goes. Do I just keep Poi around to build my app? It seems like it has a lot of overlapping functionality with vue-cli. What I was hoping to learn was how the two tools complement each other and even though I read the docs, I was unable to figure that out, I'm sorry.

**Comment by halex2005** [comment]
@LinusBorg, @posva, I'm agreed with @daveknapik.
I just started to use vue-cli and found the section in main readme:

```
### vue build

Use vue-cli as a zero-configuration development tool for your Vue apps and component, check out the [docs](https://github.com/vuejs/vue-cli/blob/master/docs/build.md).
```

Then I read that docs link and run `vue build Component.vue` command for my component. And what do you think I saw in the console output?

```
  We are slimming down vue-cli to optimize the initial installation by removing the `vue build` command.
  Check out Poi (https://github.com/egoist/poi) which offers the same functionality!
``` 

What the shame for official docs! I'm sorry for time spent. It would be better if I just got a link to the poi's documentation on how to use it.

Actually, `vue build` command was removed on [2 of October 2017](https://github.com/vuejs/vue-cli/commit/ad2b1917b0986ac1c77c55ea91d3fe9ed8ad0388#diff-717c156349205ed009fef966a51f3b3d). Why documentation was not updated yet? Should I make PR to fix docs?

**Comment by posva** [comment]
> Should I make PR to fix docs?

@halex2005 That would be very appreciated 🙂

**Comment by LaKing** [comment]
The cli documentation is:
Last Updated: 6/5/2018, 10:51:44 PM

This issue is still around?

**Comment by LinusBorg** [comment]
No
