### ISSUE TITLE
Modes and Environment Variables don't work when I use the command `vue-cli-service build --mode xxx`

### ISSUE THREAD

**Issue by wangxiaocuo** [vuejs/vue-cli#6290]
### Version
4.5.8

### Reproduction link
[https://github.com/wangxiaocuo/bugs-colllection/tree/master/vue-cli3-build-mode](https://github.com/wangxiaocuo/bugs-colllection/tree/master/vue-cli3-build-mode)

### Environment info
```
Environment Info:

  System:
    OS: macOS 11.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Not Found
    Firefox: 70.0.1
    Safari: 14.0.3
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.3 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.11 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.11 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.11 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.11 
    @vue/cli-plugin-router:  4.5.11 
    @vue/cli-plugin-vuex:  4.5.11 
    @vue/cli-service: ~4.5.0 => 4.5.11 
    @vue/cli-shared-utils:  4.5.11 
    @vue/component-compiler-utils:  3.2.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.12 
    vue-eslint-parser:  7.5.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.6 (16.1.2)
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.12 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.5.8
```

### Steps to reproduce
Run command `npm run build:uat` or `vue-cli-service build --mode uat`

### What is expected?
Alert outputs the variable of the `production` environment

### What is actually happening?
Alert outputs the variable of the `uat` environment

**Comment by sodatea** [comment]
Can't reproduce with the given reproduction:
![image](https://user-images.githubusercontent.com/3277634/108677841-39dda980-7525-11eb-8b7c-8e617433c1bf.png)

Maybe it's caused by browser cache?

**Comment by sodatea** [comment]
Sorry, misunderstood the issue. Please ignore the previous comment.

**Comment by sodatea** [comment]
I think it's the expected behavior.
`.env.uat` should be used when `--mode uat` is specified. That's what the documentation says.

**Comment by wangxiaocuo** [comment]
> I think it's the expected behavior.
> `.env.uat` should be used when `--mode uat` is specified. That's what the documentation says.

It's so strange that I did a good job after updating the node version v14.15.5, but there was something wrong with the old node version v12.18.4

**Comment by wangxiaocuo** [comment]
After repeated testing, I mistakenly thought that the reason for the bug was the browser cache of the development environment.
