### ISSUE TITLE
vuetify for typescript always show warning 

### ISSUE THREAD

**Issue by khoiphanngoc89** [vuejs/vue-cli#6293]
### Version
4.5.11

### Reproduction link
[https://github.com/khoiphanngoc89/vue-typescript-vuetify](https://github.com/khoiphanngoc89/vue-typescript-vuetify)

### Environment info
```
System:
    OS: Windows 10 Version 20H2 (OS bUILD 19042.746)
    CPU: Intel(R)) Core(TM) i5-8500 CUP @3.00GHz (6 CPUs)
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.10 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: 88.0.705.68 
  npmPackages:
    @typescript-eslint/eslint-plugin: ^2.33.0,
    @typescript-eslint/parser: ^2.33.0,
    @vue/cli-plugin-babel: ~4.5.0",
    @vue/cli-plugin-eslint": ~4.5.0,
    @vue/cli-plugin-pwa: ~4.5.0,
    @vue/cli-plugin-router: ~4.5.0",
    @vue/cli-plugin-typescript: ~4.5.0,
    @vue/cli-plugin-vuex: ~4.5.0,
    @vue/cli-service: ~4.5.0,
    @vue/eslint-config-typescript": ^5.0.2,
    eslint": "^6.7.2",
    eslint-plugin-vue: ^6.2.2,
    sass: ^1.26.5,
    sass-loader: "^8.0.2,
    typescript": ~3.9.3,
    vue-template-compiler: ^2.6.11
  npmGlobalPackages:
    
```

### Steps to reproduce
Create vue typescript project and add vuetify by cmd vue add vuetify
Then, in the vue file, I cannot use export class that extends from Vue 
I must use like: export default Vue.extend. 
Although the project can works, it show warn 
"Property or method "isUpdating" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property."
I already declare it in the export class. 
I make me so confuse why so many ways to write 
![image](https://user-images.githubusercontent.com/30396127/108488476-03105500-72d3-11eb-85bd-644fde3a3f47.png)

### What is expected?
I want to use like 
export default class HelloWorld extends Vue  without show warning 

### What is actually happening?
The vue warn show 
Property or method "isUpdating" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.

**Comment by sodatea** [comment]
The error message already gave the solution:
> for class-based components, by initializing the property

See the documentation https://class-component.vuejs.org/guide/class-component.html#data

> Note that if the initial value is `undefined`, the class property will not be reactive which means the changes for the properties will not be detected:

> To avoid this, you can use `null` value or use `data` hook instead:

By only declaring the fields but not initializing them (https://github.com/khoiphanngoc89/vue-typescript-vuetify/blob/48e1323a7e31c7ab66a5a580aadc909da543b6db/src/components/HelloWorld.vue#L142-L147), you ran exactly into this problem.
