### ISSUE TITLE
lint-stage config is defined in package.json even if we choose to keep configurations in standalone files

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/vue-cli#6298]
### Version
4.5.11

### Environment info
```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Binaries:
    Node: 12.13.1 - ~/.nodebrew/current/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nodebrew/current/bin/npm
  Browsers:
    Chrome: 88.0.4324.182
    Edge: Not Found
    Firefox: 83.0
    Safari: 14.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Run `vue create myProject`
2. Follow the wizard
3. On the "Where do you prefer placing config for Babel, ESLint, etc.?" step choose "In dedicated config files"

### What is expected?
`lint-staged` config do be stored in `.lintstagedrc.yml` or `.lintstagedrc`

### What is actually happening?
`lint-staged` config is stored in `package.json`

**Comment by HexPandaa** [comment]
Seems like it was quite an easy fix.
