### ISSUE TITLE
vue-cli 建议

### ISSUE THREAD

**Issue by henjue** [vuejs/vue-cli#63]
您好！能否给一些命令增加简单模式的参数比如

``` bash
vue list --short
```

结果就只输出简单的

``` bash
browserify
browserify-simple
simple
webpack
webpack-simple
```

而不是

``` bash
  Available official templates:

  ★  browserify - A full-featured Browserify + vueify setup with hot-reload, linting & unit testing.
  ★  browserify-simple - A simple Browserify + vueify setup for quick prototyping.
  ★  simple - The simplest possible Vue setup in a single HTML file
  ★  webpack - A full-featured Webpack + vue-loader setup with hot reload, linting, testing & css extraction.
  ★  webpack-simple - A simple Webpack + vue-loader setup for quick prototyping.
```

因为这让我想起来golang提供的各种工具，方便别的开发者开发相关工具，我在尝试开发vue for idea plugin的时候必须要人工解析输出的字符串，才能获取模板列表。

同样比如init的时候可以这样

``` bash
vue init webpack VueProjectTest --name VueProjectTest --author henjue --version 2.0.1 --private false
```

直接使用命令行参数创建项目而不用询问用户。这样开发IDE的可以可以IDE弹窗让用户填写相关信息然后输入到命令行参数来初始化项目。非常感谢。

**Comment by yyx990803** [comment]
可以，欢迎开 PR

另外 list 其实就是调用了 GitHub 的官方 API 列出 vuejs-templates  org 下面的所有 repo，你也可以直接发个 API 请求就行了

**Comment by egoist** [comment]
`vue init webpack VueProjectTest --name VueProjectTest --author henjue` 这种很少直接在命令行配置，想要达到这种效果可以让 `vue-cli` 提供一个 JavaScript API 来使用

**Comment by Dreacatcher** [comment]
@yyx990803   现在发现使用你的脚手架  在dev环境下 热更新时候出现很多重复的style 如何解决这个问题？
