### ISSUE TITLE
Yarn can't run the dev command

### ISSUE THREAD

**Issue by nothingrandom** [vuejs/vue-cli#631]
Hey.

Having issues using yarn on this

```
yarn run v0.15.1
$ "node build/dev-server.js" 
sh: node build/dev-server.js: No such file or directory
error Command failed with exit code 127.
info Visit http://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

But it works perfectly when using npm.

`npm -v is 5.5.1`
`node -v is 9.0.0`
`yarn -v is 0.15.1`
`vue -V is 2.9.1`

**Comment by nothingrandom** [comment]
I needed to upgrade `yarn`, now running `v1.2.1`.

See here: https://github.com/yarnpkg/yarn/issues/1139

Sorry for the unnecessary issue - but hopes it helps someone in the future.

**Comment by posva** [comment]
Thanks for posting the solution back 🙂
