### ISSUE TITLE
vue-cli-service: not found

### ISSUE THREAD

**Issue by linuxandroid-xyz** [vuejs/vue-cli#6317]
### Version
5.0.0-alpha.5

### Reproduction link
[https://cnspecialcolor.web.app](https://cnspecialcolor.web.app)

### Environment info
```
https://console.firebase.google.com/project/cnspecialcolor/hosting/sites
```

### Steps to reproduce
sudo npm run build

### What is expected?
arthur@Arthur:~/Desktop/digital-ocean-app$ npm run build

> digital-ocean-app@0.1.0 build
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  41.34 KB  build/static/js/2.a7ce996d.chunk.js
  1.6 KB    build/static/js/3.cb767c74.chunk.js
  1.17 KB   build/static/js/runtime-main.b3831708.js
  599 B     build/static/js/main.f76335c5.chunk.js
  531 B     build/static/css/main.8c8b27cf.chunk.css

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

arthur@Arthur:~/Desktop/digital-ocean-app$ firebase deploy

### What is actually happening?
arthur@Arthur:~/Desktop/sub-web-master$ sudo npm run build
[sudo] password for arthur: 

> sub-web@0.1.0 build
> vue-cli-service build

sh: 1: vue-cli-service: not found
arthur@Arthur:~/Desktop/sub-web-master$ sudo npm run build

**Comment by sodatea** [comment]
1. Please follow the instructions in the issue helper to fill in the accurate information;
2. Have you run `npm install` before running `npm run build`?
