### ISSUE TITLE
Missing changelog for v4.5.11

### ISSUE THREAD

**Issue by Mosharush** [vuejs/vue-cli#6319]
### Version
4.5.11

### Reproduction link
[https://github.com/vuejs/vue-cli/blob/dev/CHANGELOG.md#4510-2021-01-06](https://github.com/vuejs/vue-cli/blob/dev/CHANGELOG.md#4510-2021-01-06)

### Environment info
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.74)
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
Missing changelog for 4.5.11, there is only v4.5.10 & 5.0.0-alpha.0 after it

### What is expected?
To be changelog each version published

### What is actually happening?
Missing version (The stable one) on changelog

**Comment by sodatea** [comment]
Thanks! I forgot to update the dev branch when releasing 4.5.11
