### ISSUE TITLE
process对象重置

### ISSUE THREAD

**Issue by fakership** [vuejs/vue-cli#632]
vue-cli里头的webpack相关文件打印process会有env以及argv，
但是在vue文件里头去打印process会是一个原本的对象，env以及argv属性下什么都没有

如图所示：
![image](https://user-images.githubusercontent.com/16553183/32403232-76c14986-c102-11e7-8bf1-825329f0c887.png)
![image](https://user-images.githubusercontent.com/16553183/32403237-97060f1a-c102-11e7-97c7-32585d06a377.png)

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Webpack runs in node while Vue runs in the browser. I think webpack mocks the process or some parts of it

**Comment by wuyuedefeng** [comment]
遇到了相同的问题，是vue-cli的bug吗
