### ISSUE TITLE
The default config now missing some polyfills under IE, e.g. `Number.isNaN`

### ISSUE THREAD

**Issue by wangziling** [vuejs/vue-cli#6324]
### Version
4.5.11

### Environment info
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
  Binaries:
    Node: 14.16.0 - H:\Environments\Nvs\default\node.EXE
    Yarn: 1.22.10 - H:\Environments\Yarn\bin\yarn.CMD
    npm: 6.14.11 - H:\Environments\Nvs\default\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.74), ChromiumDev (90.0.803.0)
    IE: 11 (20H2, v19042.844)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.3
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.11
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.11
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.11
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.11
    @vue/cli-plugin-router: ~4.5.0 => 4.5.11
    @vue/cli-plugin-typescript: ~4.5.0 => 4.5.11
    @vue/cli-plugin-unit-mocha: ~4.5.0 => 4.5.11
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.11
    @vue/cli-service: ~4.5.0 => 4.5.11
    @vue/cli-shared-utils:  4.5.11
    @vue/component-compiler-utils:  3.2.0
    @vue/eslint-config-standard: ^5.1.2 => 5.1.2
    @vue/eslint-config-typescript: ^5.0.2 => 5.1.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/test-utils: ^1.0.3 => 1.1.3
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    typescript: ~3.9.3 => 3.9.9
    vue: ^2.6.11 => 2.6.12
    vue-class-component: ^7.2.3 => 7.2.6
    vue-eslint-parser:  7.5.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.6 (16.1.2)
    vue-property-decorator: ^9.1.2 => 9.1.2
    vue-router: ^3.2.0 => 3.5.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.4.0 => 3.6.2
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
1. Exec `vue create test`.
2. Exec `yarn serve`.
3. Open the link `http://localhost:8080` by IE.
4. Open the devtools, try to exec `Number.isNaN`, got `undefined`.

### What is expected?
Should get `function isNaN() { [native code] }`

### What is actually happening?
Get `undefined`.

---
I thought that maybe it due to the updates about the @babel/core, or maybe the babel preset `@vue/cli-plugin-babel/preset` missing some config to point that need to add the complete es2015 polyfills for IE.

Cannot reproduce by `codesandbox` due to IE.

Using the v7.13.x `@babel/core`, the error will ocur, but rollback to 7.12.x, it works well.

**Comment by sodatea** [comment]
Please provide a runnable reproduction, such as a git repository.

**Comment by sodatea** [comment]
And to clarify: the default babel preset uses the `useBuiltIns: 'usage'` option in `@babel/preset-env`, so polyfills are only imported when their usage is detected. https://babeljs.io/docs/en/babel-preset-env#usebuiltins

**Comment by wangziling** [comment]
Yes. I had added in code.

![image](https://user-images.githubusercontent.com/24818903/109495877-d6c2b880-7aca-11eb-9c66-9324340a4748.png)

But:
![image](https://user-images.githubusercontent.com/24818903/109495913-e510d480-7aca-11eb-947a-9dfb2a4b70d8.png)

**Comment by wangziling** [comment]
Sorry about that. I tried to add a minimal reproduction with codesandbox.
But it didn't support IE browser...

**Comment by wangziling** [comment]
Hmmm... Wait a second, I will add a git repo for this issue.

**Comment by sodatea** [comment]
Maybe related to this bug in babel?
https://github.com/babel/babel/issues/12880#issuecomment-787216822

**Comment by wangziling** [comment]
> 
> 
> Maybe related to this bug in babel?
> [babel/babel#12880 (comment)](https://github.com/babel/babel/issues/12880#issuecomment-787216822)

Ooops. Seems yes... I didn't look so carefully about the issue you provided, sorry...

**Comment by wangziling** [comment]
Thanks~

**Comment by fangbinwei** [comment]
@wangziling  Did you solve the problem ?  It's seems it's the bug of [`babel-plugin-polygill-corejs3`](https://github.com/babel/babel-polyfills/blob/9f43e20e71005cf00963c2653960a393c368c224/packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.js#L269-L270)

Now the code is 
```js
    isNaN: define("number/is-nan", ["es.number.is-safe-integer"]),
    isSafeInteger: define("number/is-safe-integer", ["es.number.is-nan"]),
```
You can verify this by changing the code to the following

**`node_modules/babel-plugin-polyfill-corejs3`**
```js
    isNaN: define("number/is-nan", ["es.number.is-nan"]),
    isSafeInteger: define("number/is-safe-integer", ["es.number.is-safe-integer"]),
```

**Comment by wangziling** [comment]
> 
> 
> @wangziling Did you solve the problem ? It's seems it's the bug of [babel-plugin-polygill-corejs3](https://github.com/babel/babel-polyfills/blob/9f43e20e71005cf00963c2653960a393c368c224/packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.js#L269-L270) which is used by `@babel/preset-env@7.13.x`
> Now the code is
> 
> ```js
>     isNaN: define("number/is-nan", ["es.number.is-safe-integer"]),
>     isSafeInteger: define("number/is-safe-integer", ["es.number.is-nan"]),
> ```
> 
> You can verify this by changing the code to the following
> 
> **`node_modules\babel-plugin-polyfill-corejs3\lib\built-in-definitions.js`**
> 
> ```js
>     isNaN: define("number/is-nan", ["es.number.is-nan"]),
>     isSafeInteger: define("number/is-safe-integer", ["es.number.is-safe-integer"]),
> ```

We just revert the lock file, to revert the `@babel/core` from `v7.13.x` to `v7.12.x`.

**Comment by wangziling** [comment]
> 
> 
> @wangziling Did you solve the problem ? It's seems it's the bug of [babel-plugin-polygill-corejs3](https://github.com/babel/babel-polyfills/blob/9f43e20e71005cf00963c2653960a393c368c224/packages/babel-plugin-polyfill-corejs3/src/built-in-definitions.js#L269-L270) which is used by `@babel/preset-env@7.13.x`
> Now the code is
> 
> ```js
>     isNaN: define("number/is-nan", ["es.number.is-safe-integer"]),
>     isSafeInteger: define("number/is-safe-integer", ["es.number.is-nan"]),
> ```
> 
> You can verify this by changing the code to the following
> 
> **`node_modules\babel-plugin-polyfill-corejs3\lib\built-in-definitions.js`**
> 
> ```js
>     isNaN: define("number/is-nan", ["es.number.is-nan"]),
>     isSafeInteger: define("number/is-safe-integer", ["es.number.is-safe-integer"]),
> ```

Checking...

**Comment by wangziling** [comment]
Hmmm... When I use the command `yarn serve`, and modify the code as you mentioned. it didn't work...

But no matter I modify that file or not, `yarn build` works well under IE.

😟

**Comment by fangbinwei** [comment]
@wangziling  sorry, I forgot to mention it, you should delete `node_modules/.cache` if modifying the code in `node_modules`

**Comment by wangziling** [comment]
> 
> 
> @wangziling sorry, I forgot to mention it, you should delete `node_modules/.cache` and run `yarn serve` again if modifying the code in `node_modules`

Yes. I realize that `yarn serve` maybe creates and uses the cache, but... I didn't find where it is...
And I remember that `yarn build` provide an option `no-clean`, so I thought that maybe serve will clear cache automatically, so I did nothing additional before I re-execute `yarn serve`...

After empty the `node_modules/.cache` folder, it works well under IE.

WOW... I checked the git blame about `babel-plugin-polygill-corejs3`. OMG, is it an issue for 2 years?! 😮

**Comment by wangziling** [comment]
But... Why it works well for `production build` -> `yarn build`? Did vue do something correctly or additionally before or after applying some polyfills? 🤔

**Comment by fangbinwei** [comment]
@wangziling  no, I get consistent behavior in the dev and prod environments

**Comment by wangziling** [comment]
Sorry for the slow reply.
Hmmm... Maybe `babel` did something additional. :thinking:

Thank you all for your help. @fangbinwei, @sodatea .

After upgrade to the latest `babel-plugin-polyfill-corejs3`, issue fixed. 😆
