### ISSUE TITLE
The 「object-treeify」causes  @vue/cli installation to fail

### ISSUE THREAD

**Issue by screetBloom** [vuejs/vue-cli#6336]
### Version
@vue/cli   4.5.11
@vue/cli-ui 4.5.11

### Environment info
- mac os
- node -v 10.15.3
- @vue/cli 4.5.11
- @vue/cli-ui 4.5.11

<br>

### Steps to reproduce
just run `yarn add @vue/cli` in  any project

<br>

### What is expected?
Hope @vue/cli works in node@10.x

https://github.com/vuejs/vue-cli/blob/cf7b46adc4c5f181d9e3eb03decbeb4cfb792bc8/packages/%40vue/cli-ui/package.json#L116-L118

<br>

#### 1.dependency tree
1. `@vue/cl`i => `@vue/cli-ui` => `vue-cli-plugin-apollo` => `apollo` =>  `cli-ux` =>  **object-treeify@^1.1.4**
2. `@vue/cli` => `@vue/cli-ui`=> `vue-cli-plugin-apollo`  => `apollo` => `@oclif/plugin-not-found + @oclif/plugin-plugins +@oclif/plugin-autocomplete`  =>  `cli-ux`  =>  `object-treeify@^1.1.4`
3. **object-treeify@1.1.32 published 12 hours ago by simlu**

#### 2.error info
[object-treeify](https://github.com/blackflux/object-treeify/blob/327888bb70f43eae7ea985dc2f037e63987ae823/package.json#L102-L108)

``` js
"engines": {
  "node": ">= 12"
},
```

![image](https://user-images.githubusercontent.com/22092110/110428097-bd7dc580-80e3-11eb-988c-a96da5949380.png)

``` shell
error object-treeify@1.1.32: The engine "node" is incompatible with this module. Expected version ">= 12". Got "10.15.3"
```

<br>
<br>
<br>

@sodatea  

help look at it, because our tools rely on @vue/cli at the bottom; **this has a big impact on us**

**Comment by screetBloom** [comment]
Other than `yarn resolutions`, is there any other method that doesn't require the user to change the code?

**Comment by sodatea** [comment]
https://github.com/yarnpkg/yarn/issues/6627#issuecomment-435865688

`yarn add @vue/cli --ignore-engines`

**Comment by screetBloom** [comment]
1. We will inject @vue/cli into the project by a **generator plugin**
      i. Actually , It's another npm package that contains @vue/cli 
2. Then create the project by `vue create --preset` in remote  jenkins machines

**so this solution may not really help us**


<br>

> In fact, at first I thought of solving this error from this idea, but **it will cause all engines check to fail**，And it's also hard to make it work in the `vue create --preset` process

**Comment by screetBloom** [comment]
Thanks a million，is there any other way I can sponsor you besides Sponsors，like alipay？

**Comment by sodatea** [comment]
🤔Actually `vue-cli-plugin-apollo` should be considered a dev dependency. I should release a patch tonight or tomorrow to fix this.

**Comment by sodatea** [comment]
> Thanks a million，is there any other way I can sponsor you besides Sponsors，like alipay？

Thanks for your kindness!

But I want sponsorships to be transparent, so I don't intend to accept private payments.

For Chinese users who want to sponsor via Alipay or WeChat, I've just set up a service similar to GitHub sponsors: https://www.afdian.net/@sodatea

**Comment by simlu** [comment]
Everything should be working as expected now.

My sincere apologies - I've accidentally released the deprecation as a fix version. Corrected now.

PS: Talk about timing. I just went to sleep as this issue came up, that's why my response here is a bit delayed...
