### ISSUE TITLE
vue cli 配置 output chunkFilename 为 [id] 时无效

### ISSUE THREAD

**Issue by liuquanzhang** [vuejs/vue-cli#6344]
### Version
4.5.0

### Environment info
```
win 10 
npm 6.14.9
node 14.15.3
```

### Steps to reproduce
在打包编译时设置ouput参数中的 chunkFilename 为 [id].js 时无效 会把  [id]  当成 [name] 处理，这是个bug吗？
我希望chunk名称是  [id].[contenthash:8].js 这样的格式 但是无法实现。

### What is expected?
[id].[contenthash:8].js 

### What is actually happening?
[name].[contenthash:8].js

**Comment by liuquanzhang** [comment]
我在router设置了chunk的名称 /* webpackChunkName: "login" */

**Comment by sodatea** [comment]
特地这么做的，不算 bug：https://github.com/vuejs/vue-cli/blob/bef2375326aa4274c3cb83809b1f60e133e46c7c/packages/%40vue/cli-service/lib/config/app.js#L131-L145
