### ISSUE TITLE
Error: options/query provided without loader

### ISSUE THREAD

**Issue by n006** [vuejs/vue-cli#635]
Hi,
I've just installed vue-cli to try it out and after the following steps

```
npm install vue-cli -g
vue init webpack-simple i-vue
cd i-vue
npm install
npm run dev
```

I got this issue

```
Error: options/query provided without loader (use loader + options) in {
  "test": {},
  "use": "vue-loader",
  "options": {
    "loaders": {}
  }
}
```
Just don't know what to do.
Would be really happy if someone could help.
Thank you in advance.

--
**npm: 5.5.1**
**node: 6.11.3**
**vue: 2.9.1**

**Comment by n006** [comment]
Seems like leaving out "webpack-simple" works. I'll go with that.

**Comment by LinusBorg** [comment]
For the record: I messed up the webpack-simple template yesterday with a bad commit. I fixed it soon after and it's working as expected again. 

Sorry for the inconvenience.
