### ISSUE TITLE
npm install vue-cli fails; yarn install works... vue 4.5.11/npm 7.5.3/node v12.20.1/OSX 10.13.6

### ISSUE THREAD

**Issue by pablo-mayrgundter** [vuejs/vue-cli#6357]
### Version
4.5.11

### Reproduction link
[https://github.com/pablo-mayrgundter/vue-cli/blob/main/README.md](https://github.com/pablo-mayrgundter/vue-cli/blob/main/README.md)

### Environment info
```
vue latest=4.5.11/npm 7.5.3/node v12.20.1/OSX 10.13.6
```
### Steps to reproduce
npm i -g @vue/cli

### What is expected?
vue-cli installed

### What is actually happening?
didn't

---
I thought this was probably transient, but it's been a week.  Also, I saw an issue like this on github but have since lost track of it.

**Comment by pablo-mayrgundter** [comment]
Found the previous issue.. someone else was having trouble installing vue with npm and file it there:

https://github.com/npm/cli/issues/2645

**Comment by sodatea** [comment]
To narrow down the problem, please first upgrade your npm version to at least 7.5.5, or downgrade to 6.x.
There's a bug in earlier versions of npm 7: https://github.com/npm/cli/issues/2615#issuecomment-784509497

Though, as for the `FETCH_ERROR`, it might be a network issue.

**Comment by pablo-mayrgundter** [comment]
Ah, didn't realize npm was that old.  I just tried updating npm to fix a similar issue with another lib based on your feedback and it worked, so marking this closed.
