### ISSUE TITLE
vue-cli does not hot reload when running from within Dropbox folder (no special characters)

### ISSUE THREAD

**Issue by bugs181** [vuejs/vue-cli#637]
I have a project that works fine when outside of the Dropbox folder, however if I try to make changes from within the Dropbox folder, those changes are not hot reloaded. The file path does not contain any spaces, parentheses, or other characters so that excludes the https://github.com/webpack/watchpack/issues/42 issue.

Directions: Make a change to a `.Vue` component file and nothing happens.

File path: `/Users/levi/Dropbox/Company/Project`
Command: `npm run dev`
OS: `Mac OS X Yosemite 10.10.1`

Versions:
`vue -V`: `2.8.2`
`npm -v`: `5.0.3`
`node -v`: `v8.1.2`

`package.json` versions:
webpack: `^2.6.1`
webpack-bundle-analyzer: `^2.2.1`
webpack-merge: `^4.1.0`
vue-loader: `^12.1.0`
file-loader: `^0.11.1`
opn: `^4.0.2`

Please let me know if there are further tests I can run.

**Comment by LinusBorg** [comment]
That's a general problem with Webpack's File watching mechanism. It usually can only be fixed by switching to a poll mechanism:

https://github.com/vuejs-templates/webpack/blob/develop/template/config/index.js#L21
