### ISSUE TITLE
打包到tomcat web服务器后，api直接连接自由后台api服务，后台接口一直访问不了，请问如何配置vue.config.js文件

### ISSUE THREAD

**Issue by changgong1** [vuejs/vue-cli#6378]
### Version
5.0.0-alpha.8

### Environment info
```
centos
```

### Steps to reproduce
1、npm run build:prod
2、部署到tomcat webapp下
3、能正常访问，but，api接口请求失败。api直连api server。没有通过nainx转发

### What is expected?
有什么方法可以不通过nainx,直接请求后台吗？

### What is actually happening?
api请求失败

**Comment by fangbinwei** [comment]
不是CLI的问题, 是需要服务端设置CORS?

**Comment by changgong1** [comment]
是的，现在请求到了后台，但是tomcat出现了跨域的问题，试了好几个filter> 都未能解决。参考这个文档：http://tomcat.apache.org/tomcat-8.0-doc/config/filter.html#Add_Default_Character_Set_Filter/Initialisation_parameters
