### ISSUE TITLE
the questions of stylus-module

### ISSUE THREAD

**Issue by onlyLiuMing** [vuejs/vue-cli#638]
使用stylus文件加载外部字体文件时，会报相对路径错误
我重新配置了webpack，并且尝试用绝对路径，仍会报错，根本无法使用
thank you see this question

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

if you're using the webpack template, putting files in the `static` folder will make them available _as is_ so you can write urls like `/static/my-font.ttf`

**Comment by onlyLiuMing** [comment]
sorry , I will remember your prompt！！
thank you answer  my question！！！！
O(∩_∩)O~~
good lucky！
