### ISSUE TITLE
Vue CLI Bug with Module Federation, Module not loaded

### ISSUE THREAD

**Issue by T0miii** [vuejs/vue-cli#6386]
### Version
5.0.0-alpha.8

### Environment info
```
Vue CLI 5 alpha 8
```

### Steps to reproduce
Create two vue cli projects 
localhost:8082 Container App
localhost:8083 Feature App

Configure Host App:
`````
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");

const path = require('path');

module.exports = {
    configureWebpack: {
        resolve: {
            extensions: ['.js', '.vue', '.json'],
            alias: {
                '@': path.join(__dirname, '/src'),
                '@modules': path.join(__dirname, '/Modules'),
            },
        },
        plugins: [
            new ModuleFederationPlugin({
                name: "appcontainer",
                filename: "remoteEntry.js",
                remotes: {
                    "data" : "data@http://localhost:8083/remoteEntry.js"
                },
                exposes: {},
                shared: {}
            }),
        ],
    },
}
``````

Configure Feature App:
````
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");

const path = require('path');

module.exports = {
    configureWebpack: {
        resolve: {
            extensions: ['.js', '.vue', '.json'],
            alias: {
                '@': path.join(__dirname, '/src'),
                '@modules': path.join(__dirname, '/Modules'),
            },
        },
        plugins: [
            new ModuleFederationPlugin({
                name: "data",
                filename: "remoteEntry.js",
                remotes: {},
                exposes: {
                    './App' : './src/App.vue'
                },
                shared: {},
            }),
        ],
    },
}
`````
Use components in Host app:
`````
<template>
  <div>
    <App />
  </div>
</template>

<script>
import {computed} from "vue"
import {apps} from "../../store/apps";
import App from "data/App";

export default {
  name: "index",
  components: {
    App
  },
......
`````

### What is expected?
Expected to show the feature app in the host app

### What is actually happening?
nothing is shown getting error in the network tab that the src_App_vue.js not found 404.

---
Even tho the feature app is served cause if i change the name to something else import App from "data/whatever"; then its telling me the component is not found.

My guess is that vue cli is loading the component from the wrong url : http://localhost:8082/js/src_App_vue.js

8082 is the url of the Host app. If i call http://localhost:8083/js/src_App_vue.js the js is loaded.

Is this a bug or is it supposed to be loaded from the host app and something else is missing.

**Comment by T0miii** [comment]
It made it work , it seems like i have to put all the code in my main js and add it to a bootstrap.js file and the import in in the main.js file, seems to work for components.

But i cant expose the App.vue components. Seems like the entire app can not be exposed.

**Comment by telmaantunes** [comment]
@T0miii Where you ever able to export the whole App?

**Comment by roshan2921** [comment]
> 

@T0miii can you please share your repo

**Comment by T0miii** [comment]
i did gave up on the idea on exporting all the app, it feels like MF wasnt made for that purpose. What you can do is exporting, your router, and all your views, and setting up the routers in the Consumer App, (wich turned out be also quit tricky with everything being asyc). 

For hosting entier app in another one, i would just go with something like vue-iframe, and for single component MF, works quit well.
