### ISSUE TITLE
Unexpected token: punc (() [static/js/app.....js:85,6]

### ISSUE THREAD

**Issue by MaksimBazarov** [vuejs/vue-cli#639]
`npm run dev` works fine
but when I try to build I got this error

**Comment by MaksimBazarov** [comment]
only when anywhere using ```data () {} ``` syntax

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
