### ISSUE TITLE
Vue CLI installation fails with errors, perhaps only with npm v7

### ISSUE THREAD

**Issue by shoichiaizawa** [vuejs/vue-cli#6392]
### Version

4.5.12

### Environment info

```
OS: macOS Catelina 10.15.7 (19H524)
Node.js: v12.y.z, v14.y.z (installed via nvm v0.38.0)
npm: v7.7.6
```

### Steps to reproduce

```
❯❯ npm install -g @vue/cli
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/compiler-core@3.0.10.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sho/.npm/_logs/2021-03-31T00_36_52_758Z-debug.log
```

### What is expected?

Install Vue CLI successfully.

### What is actually happening?

Installation fails with the aforementioned error.

---

This only seems to happen with npm v7.y.z, not with v6.y.z, under any recent Node.js LTS versions (i.e. v12 and v14).

**Comment by kei-ichi** [comment]
### Issue reproduced with following setups:
```
OS: macOS Bigsur - Version 11.2.3 (20D91)
nvm: v0.38.0
Node.js: v14.16.0
npm: v7.7.6
```

### Error details:
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vue/compiler-core@3.0.10.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user-name/.npm/_logs/2021-03-31T01_58_57_404Z-debug.log
```

> Somebody please tell me what happened?

**Comment by sodatea** [comment]
I guess it's due to a network issue or npm registry cache or something like that.
Because `@vue/compiler-core` 3.0.10 does exist https://www.npmjs.com/package/@vue/compiler-core/v/3.0.10
But it was released only hours ago so it might be not accessible at the time of your installation due to all kinds of network issues.

**Comment by kei-ichi** [comment]
> I guess it's due to a network issue or npm registry cache or something like that.
> Because `@vue/compiler-core` 3.0.10 does exist https://www.npmjs.com/package/@vue/compiler-core/v/3.0.10
> But it was released only hours ago so it might be not accessible at the time of your installation due to all kinds of network issues.

Bro, you are absolutely right. I'm run `npm install -g @vue/cli` again and it's successful installed.
Thank you.
```
➜ npm install -g @vue/cli
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
```

@shoichiaizawa close this issue please. :)

**Comment by shoichiaizawa** [comment]
> I guess it's due to a network issue or npm registry cache or something like that.
> Because `@vue/compiler-core` 3.0.10 does exist [npmjs.com/package/@vue/compiler-core/v/3.0.10](https://www.npmjs.com/package/@vue/compiler-core/v/3.0.10)
> But it was released only hours ago so it might be not accessible at the time of your installation due to all kinds of network issues.

As of 2021-03-31 13:20 GTM+9, Vue CLI is installed properly.

<details>
  <summary>Click to expand!</summary>

```
❯❯ nvm -v
0.38.0

❯❯ nvm version
v12.22.0

❯❯ node -v
v12.22.0

❯❯ npm -v
7.7.6

❯❯ npm install -g @vue/cli
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'

added 937 packages, and audited 938 packages in 32s

58 packages are looking for funding
run `npm fund` for details

found 0 vulnerabilities

❯❯ npm list -g --depth=0
/Users/sho/.nvm/versions/node/v12.22.0/lib
├── (ellipsis)
├── @vue/cli@4.5.12
└── (ellipsis)
```  
</details>

Thus, I am closing this issue.

@sodatea @kei-ichi Thanks guys for your help 🖖
