### ISSUE TITLE
How to add HTML tag type="text/javascript" for scripts in final bundle?

### ISSUE THREAD

**Issue by mostopalove** [vuejs/vue-cli#6399]
### Version
4.5.10

### Environment info
```
vue-cli-service build
```

### Steps to reproduce
Now vue-cli creates bundle without HTML tag type="text/javascript". How can this be configured?

### What is expected?
Flexible configuration of the final bundle

### What is actually happening?
Cant add tag type

**Comment by mostopalove** [comment]
I'll leave a sample configuration here. It might help someone.

```
module.exports = {
  chainWebpack: config => {
    config
      .plugin('html')
      .tap(args => {
        args[0].minify.removeScriptTypeAttributes = false
        return args
      })
  }
}
```

**Comment by sodatea** [comment]
But why?
Per MDN:

> Omitted or a JavaScript MIME type: This indicates the script is JavaScript. The HTML5 specification urges authors to omit the attribute rather than provide a redundant MIME type.

**Comment by mostopalove** [comment]
@sodatea , yes its true. But I faced a problem with Microsoft Edge and sometimes with Firefox as well.

![photo_2021-04-06 12 18 42](https://user-images.githubusercontent.com/49098339/113689020-898dc400-96d2-11eb-90ce-9e63d446fc3a.jpeg)

**Comment by sodatea** [comment]
That's likely due to a misconfiguration in the server (wrong `Content-Type` in the response header).
It's better to be fixed on the server side… otherwise, you might run into other problems again in the future.

**Comment by alpsenelcn** [comment]
my solution was adding the `--no-module` while building for production.
`"build": "vue-cli-service build --no-module"`
