### ISSUE TITLE
按着教程来npm run dev不能运行。

### ISSUE THREAD

**Issue by VinceXie** [vuejs/vue-cli#64]
vincexiedeMacBook-Pro:vue vincexie$ npm run dev

> vue@0.1.0 dev /Users/vincexie/WebstormProjects/test/vue
> node build/dev-server.js

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at EventEmitter.listen (/Users/vincexie/WebstormProjects/test/vue/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/vincexie/WebstormProjects/test/vue/build/dev-server.js:60:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! vue@0.1.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue@0.1.0 dev script 'node build/dev-server.js'.
npm ERR! This is most likely a problem with the vue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls vue
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vincexie/WebstormProjects/test/vue/npm-debug.log

npm-debug.log信息如下：
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@2.12.1
3 info using node@v0.12.7
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'predev', 'dev', 'postdev' ]
6 info predev vue@0.1.0
7 info dev vue@0.1.0
8 verbose unsafe-perm in lifecycle true
9 info vue@0.1.0 Failed to exec dev script
10 verbose stack Error: vue@0.1.0 dev: `node build/dev-server.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid vue@0.1.0
12 verbose cwd /Users/vincexie/WebstormProjects/test/vue
13 error Darwin 15.0.0
14 error argv "node" "/usr/local/bin/npm" "run" "dev"
15 error node v0.12.7
16 error npm  v2.12.1
17 error code ELIFECYCLE
18 error vue@0.1.0 dev: `node build/dev-server.js`
18 error Exit status 1
19 error Failed at the vue@0.1.0 dev script 'node build/dev-server.js'.
19 error This is most likely a problem with the vue package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     node build/dev-server.js
19 error You can get their info via:
19 error     npm owner ls vue
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by yyx990803** [comment]
8080 端口被占用了。
