### ISSUE TITLE
Ask for the language attribute value for <html> on creating new project

### ISSUE THREAD

**Issue by farhadnowzari** [vuejs/vue-cli#6409]
### What problem does this feature solve?
It happens that developers will create a project with vue-cli and they won't notice that vue has an index.html file which has set the language attribute of the <html> tag to "en" by default and it is really easy to be overlooked.
If while installation vue asks about what language to be set on the html tag would be nice.
We recently had problem with one of our Vue apps and some of the customers had complained that why the texts are so bad or are they copy-pasted. Then we found out that since it is set to english by default google was translating a german text from english to german and it was causing a work like "Hell" in german which means "Light" being translated to "Hölle".

### What does the proposed API look like?
```
Please enter the html tag language attribute(default: en):
```

**Comment by fangbinwei** [comment]
> vue has an index.html file which has set the language attribute of the tag to "en" by default

This default behavior has been revised by https://github.com/vuejs/vue-cli/pull/5992

**Comment by farhadnowzari** [comment]
That's is nice but I don't think setting to empty string would be enough.
Just ask that while creating a new project would do to it.
Because the empty string can still be simply overlooked
