### ISSUE TITLE
 ReferenceError: htmlWebpackPlugin is not defined

### ISSUE THREAD

**Issue by xcgs123** [vuejs/vue-cli#6425]
### Version
4.5.12

### Reproduction link
[https://github.com/xcgs123/vuecli-vue-demo](https://github.com/xcgs123/vuecli-vue-demo)

### Environment info
```
"vue": "^3.0.11"
"@vue/cli-service": "~4.5.0"
```

### Steps to reproduce
npm run dev

### What is expected?
success

### What is actually happening?
vue.config.js

it will be found when  add "templateParameters" in  pages

it may be htmlWebpackPlugin 'version wrong

**Comment by fangbinwei** [comment]
Try to delete [these codes](https://github.com/xcgs123/vuecli-vue-demo/blob/1412d74aa12cabaf23a5ec447adc048a64cddf8b/vue.config.js#L135-L137). 

If you want to use latest html-webpack-plugin, you can try alpha version of @vue/cli
