### ISSUE TITLE
How can I use it in main.JS inside the definition of the global less file inside variables

### ISSUE THREAD

**Issue by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [vuejs/vue-cli#643]
I want to be in main.JS introduces a common less file and then uses the variables in the less file in the assembly, but now I can't use Main in the component.JS inside variables, can only be imported in each component of a common less file to help, can you tell me how to solve this problem?

**Comment by ganyusheng520** [comment]
Maybe you can write some global class instead

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Maybe this can help: https://vue-loader.vuejs.org/en/configurations/pre-processors.html#loading-a-global-settings-file
