### ISSUE TITLE
Vue-cli-serve Could not resolve dependency

### ISSUE THREAD

**Issue by throrin19** [vuejs/vue-cli#6431]
### Version
4.5.12

### Environment info
```
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: Not Found
    npm: 7.5.2 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Chrome: 90.0.4430.85
    Firefox: 85.0.2
    Safari: 14.0.3
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
- uninstall node_modules and package-lock
- npm install

### What is expected?
All packages installed correctly using vue 2 with vue-cli 4.5.12. 

### What is actually happening?

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: manager-app@1.22.1
npm ERR! Found: vue@2.6.12
npm ERR! node_modules/vue
npm ERR!   dev vue@"2.6.12" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"3.0.11" from @vue/compiler-sfc@3.0.11
npm ERR! node_modules/@vue/compiler-sfc
npm ERR!   peerOptional @vue/compiler-sfc@"^3.0.0-beta.14" from @vue/cli-service@4.5.12
npm ERR!   node_modules/@vue/cli-service
npm ERR!     dev @vue/cli-service@"4.5.12" from the root project
npm ERR!     1 more (@vue/cli-plugin-babel)
```

---
It works fine few days before. Now, it's not working. I think the problem is with `@vue/compiler-sfc` peerOptional in `@vue/cli-service` package

**Comment by sodatea** [comment]
See https://github.com/vuejs/vue-cli/issues/6270#issuecomment-790666206. Please update your npm version.

**Comment by throrin19** [comment]
It's no working with last npm version. To works we have to set the `legacy-peer-deps` flag and it's not normal...

**Comment by sodatea** [comment]
Then please open a new issue **with a reproduction**.
