### ISSUE TITLE
npm upgrade issues with vue/cli-plugin-eslint

### ISSUE THREAD

**Issue by hogsmill** [vuejs/vue-cli#6434]
### Version
4.5.11

### Reproduction link
[https://github.com/hogsmill/socket-test](https://github.com/hogsmill/socket-test)

### Environment info
```
 System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 90.0.4430.85
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.42)
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.3
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.12
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.12
    @vue/cli-plugin-babel: ^4.5.12 => 4.5.12
    @vue/cli-plugin-eslint: ^4.5.12 => 4.5.12
    @vue/cli-plugin-router:  4.5.12
    @vue/cli-plugin-vuex:  4.5.12
    @vue/cli-service: ^4.5.12 => 4.5.12
    @vue/cli-shared-utils:  4.5.12
    @vue/component-compiler-utils:  3.2.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^7.9.0 => 7.9.0
    vue: ^2.6.12 => 2.6.12
    vue-eslint-parser:  7.6.0
    vue-hot-reload-api:  2.3.4
    vue-js-modal: ^2.0.0-rc.6 => 2.0.0-rc.6
    vue-loader:  15.9.6 (16.1.2)
    vue-style-loader:  4.1.3
    vue-template-compiler: ^2.6.12 => 2.6.12
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.5.1 => 3.6.2
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
C:\DATA\APPS\socket-test>npm upgrade
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: socket-test@0.1.0
npm ERR! Found: eslint@7.24.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.24.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.12
npm ERR! node_modules/@vue/cli-plugin-eslint
npm ERR!   dev @vue/cli-plugin-eslint@"^4.5.12" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Steve\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Steve\AppData\Local\npm-cache\_logs\2021-04-23T15_32_11_564Z-debug.log

### What is expected?
npm upgrade should upgrade outdated project packages - mainly core-js at the moment. I know about the chart.js and sass-loader issues; npm upgrae is *not* trying to upgrade these

### What is actually happening?
npm upgrade fails. This was working fine 3 days ago when i last ran it. I have tried latest version of npm, and it still fails.

I have tried to upgrade vue, but it says it is up to date

**Comment by hogsmill** [comment]
BTW, npm is 7.9.0

C:\DATA\APPS\socket-test>npm --v
7.9.0

**Comment by sodatea** [comment]
Vue CLI v4 doesn't support ESLint 7, please stay with ESLint 6.

Because adding ESLint 7 support would introduce breaking changes, it's only supported in Vue CLI v5 beta.
