### ISSUE TITLE
linux环境无法创建名称包含大写字母的项目, 报Error: NO_MODULES

### ISSUE THREAD

**Issue by kentalee** [vuejs/vue-cli#6436]
### Version
4.5.12

### Environment info
```
  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 15.14.0 - /usr/bin/node
    Yarn: 1.22.10 - ~/.npm/global/bin/yarn
    npm: 7.9.0 - /usr/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
命令行执行vue ui 打开网页界面，输入包含大写字母的项目名，使用默认配置创建项目

### What is expected?
项目被正常创建

### What is actually happening?
报错Error: NO_MODULES

跟踪代码发现报错处尝试访问项目根目录的node_modules

控制台打印程序访问的path得到：
/mnt/WorkSpace/projects/frontend/apiConfigure

但项目的实际path为：
/mnt/WorkSpace/projects/frontend/apiconfigure

推测原因是linux下ext4文件系统区分大小写导致无法访问项目目录

---
Error: NO_MODULES
    at importProject (/home/kenta/.config/yarn/global/node_modules/@vue/cli-ui/apollo-server/connectors/projects.js:373:11)
    at /home/kenta/.config/yarn/global/node_modules/@vue/cli-ui/apollo-server/connectors/projects.js:364:12
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Object.wrap (/home/kenta/.config/yarn/global/node_modules/@vue/cli-ui/apollo-server/connectors/progress.js:39:14)

**Comment by sodatea** [comment]
不建议、并且下个版本起将不允许创建名称含大写字母的项目。

参见 https://github.com/vuejs/vue-cli/pull/5096 的讨论。具体的校验功能将会在 https://github.com/vuejs/vue-cli/pull/6443 实现。
