### ISSUE TITLE
process_child not found in node_modules/sqlite3.... when installing sqlite3  VUE CLI

### ISSUE THREAD

**Issue by talalzaki** [vuejs/vue-cli#644]
i was installing sqlite3 with npm install --save dev sqlite3, after running npm run dev give me error 👍 

These dependencies were not found:

* child_process in ./node_modules/sqlite3/node_modules/node-pre-gyp/lib/testbina
ry.js, ./node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js and
2 others
* fs in ./node_modules/sqlite3/node_modules/fs.realpath/index.js, ./node_modules
/sqlite3/node_modules/fs.realpath/old.js and 21 others

To install them, you can run: npm install --save child_process fs
i install it but the same error

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
