### ISSUE TITLE
[ESM] export {{type}} was not found in '@/utils' 

### ISSUE THREAD

**Issue by HomyeeKing** [vuejs/vue-cli#6441]
### Version
4.5.0

### Reproduction link
[http:no.com](http:no.com)

### Environment info
```
windows
 "vue": "^3.0.0",
"@vue/cli-service": "~4.5.0",
```

### Steps to reproduce
just `vue create` a new project with `typescript`
cd <your_project>/src
mkdir utils --> cd utils --> touch index.ts && touch var.ts

echo export * from './var' > index.ts

then we import the type through `import { Type1} from '@/utils'`
```ts
// var.ts

export interface Type1{
 .....
}

// index.ts
export * from './var'

//  test.vue

<script>

import {Type1} from '@/utils'
</script>
```

### What is expected?
no warning , works well 

### What is actually happening?
*warning:* "export 'TYPE1' was not found in '@/utils',  but have no effect to use
![image](https://user-images.githubusercontent.com/49113249/115998842-cedf4a80-a61b-11eb-9e85-dc28dfe34ae7.png)

**Comment by LinusBorg** [comment]
```
import type { Type1 } from '@/utils'
```

also, please provide a runnable reproduction as is required in the guidelines.

**Comment by HomyeeKing** [comment]
it's ok now, thanks for your time
