### ISSUE TITLE
Error downloading Webpack

### ISSUE THREAD

**Issue by feryan78** [vuejs/vue-cli#645]
hi, I'm used ubuntu 16.04 with and with a proxy the version of npm = 5.5.1 and node = 9.2.0. I configured my npm ".npmrc" like this:

prefix=/home/user
registry=http://registry.npmjs.org/
proxy=http://myproxy:8080/
https-proxy=http://myproxy:8080/

when I try to create a single project using vue-cli with this command "vue init webpack myproject" this is the error:

> url.js:292
>       this.auth = decodeURIComponent(rest.slice(0, atSign));
>                   ^
> 
> URIError: URI malformed
>     at decodeURIComponent (<anonymous>)
>     at Url.parse (url.js:292:19)
>     at Object.urlParse [as parse] (url.js:100:13)
>     at Tunnel.setup (/home/fyanez/lib/node_modules/vue-cli/node_modules/request/lib/tunnel.js:140:25)
>     at Request.init (/home/fyanez/lib/node_modules/vue-cli/node_modules/request/request.js:283:18)
>     at new Request (/home/fyanez/lib/node_modules/vue-cli/node_modules/request/request.js:128:8)
>     at request (/home/fyanez/lib/node_modules/vue-cli/node_modules/request/index.js:53:10)
>     at module.exports.done (/home/fyanez/lib/node_modules/vue-cli/lib/check-version.js:14:3)
>     at run (/home/fyanez/lib/node_modules/vue-cli/bin/vue-init:117:5)
>     at Object.<anonymous> (/home/fyanez/lib/node_modules/vue-cli/bin/vue-init:96:3)
>     at Module._compile (module.js:641:30)
>     at Object.Module._extensions..js (module.js:652:10)
>     at Module.load (module.js:560:32)
>     at tryModuleLoad (module.js:503:12)
>     at Function.Module._load (module.js:495:3)
>     at Function.Module.runMain (module.js:682:10)

Sorry for my english it's no my native language

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Also, note this is the repo of the vue-cli, not the repo of the webpack template (vuejs-templates/webpack)
