### ISSUE TITLE
routes on Vue ui or Vue dev tools

### ISSUE THREAD

**Issue by claranceliberi** [vuejs/vue-cli#6453]
### What problem does this feature solve?
it will improve debugging process for developers since they will not need to scroll into hundreds of lines of file finding a specific route

### What does the proposed API look like?
For those who have used laravel, you may already know `artisan routes` which shows a list of routes and their corresponding controllers

**Comment by sodatea** [comment]
Vue.js devtools 6 beta already has a router plugin.
