### ISSUE TITLE
使用vue-cli之后页面不能自动刷新了

### ISSUE THREAD

**Issue by YZlingyu** [vuejs/vue-cli#646]
升级到了2.9.1之后，代码改变，浏览器内容不变化，而且不能自动启动页面了

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This looks like a template problem, not cli's
