### ISSUE TITLE
@vue/cli-plugin-eslint - eslint > 7.0.0 fails

### ISSUE THREAD

**Issue by UglyHobbitFeet** [vuejs/vue-cli#6469]
### Version
4.5.13

### Reproduction link
[https://github.com/vuejs/vue-cli/blob/v4.5.13/packages/@vue/cli-plugin-eslint/package.json](https://github.com/vuejs/vue-cli/blob/v4.5.13/packages/@vue/cli-plugin-eslint/package.json)

### Environment info
```
Linux
```

### Steps to reproduce
Eslint > 7.0.0 seems to work fine, so why is there this restriction?

### What is expected?
To relax the package.json rule

### What is actually happening?
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@">= 1.6.0 < 7.0.0" from @vue/cli-plugin-eslint@4.5.13

**Comment by sodatea** [comment]
Because `eslint-loader` v2 (which this plugin depends on) has this restriction
https://github.com/webpack-contrib/eslint-loader/blob/v2.2.1/package.json

If you wanna use ESLint 7, please upgrade to `@vue/cli-plugin-eslint` v5.0.0-beta.0
