### ISSUE TITLE
vue list uses colors hard to read

### ISSUE THREAD

**Issue by cfjedimaster** [vuejs/vue-cli#647]
I'm using WSL (Windows Subsystem for Linux) and noticed the following output for `vue list`:

![image](https://user-images.githubusercontent.com/393660/32998681-dcde72ae-cd62-11e7-88ab-b2fd560add91.png)

Readable, but just barely.

**Comment by LinusBorg** [comment]
Might indeed be better to switch this to a lighter color, like a "vue" green:

https://github.com/vuejs/vue-cli/blob/master/bin/vue-list#L34

**Comment by posva** [comment]
Is the color theme changeable on Windows? I hope that we can find a better color so it works everywhere, but let's be honest here, why is the blue color so dark on the default windows theme...
