### ISSUE TITLE
postcss-loader version not update

### ISSUE THREAD

**Issue by gitbu** [vuejs/vue-cli#6484]
### Version
4.5.13

### Reproduction link
[https://github.com/vuejs/vue-cli/blob/master/packages/@vue/cli-service/package.json](https://github.com/vuejs/vue-cli/blob/master/packages/@vue/cli-service/package.json)

### Environment info
```
window
```

### Steps to reproduce
send email to me 1282185668@qq.com

### What is expected?
postcss-loader@4.2.0 can install and can work

### What is actually happening?
when i install postcss-loader@4.2.0 , postcss@3.0.0 move to @vue/cli-service/node-modules, it can overvide my project installed postcss-loader@4.2.0

**Comment by sodatea** [comment]
Just use Vue CLI 5.0 beta. It's a breaking change so we can't update it in v4.
