### ISSUE TITLE
@vue/cli 5.0.0-beta.1   npm install  404 

### ISSUE THREAD

**Issue by huhan** [vuejs/vue-cli#6488]
### Version
5.0.0-beta.0

### Environment info
```
win10
```

### Steps to reproduce
create

### What is expected?
install 

### What is actually happening?
@vue/cli 5.0.0-beta.1   
npm install  packge   404 error

 npm i sass
npm WARN deprecated @types/anymatch@3.0.0: This is a stub types definition. anymatch provides its own type definitions, so you do not need this installed.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.com/vue-loader-v15 - Not found
npm ERR! 404
npm ERR! 404  'vue-loader-v15@15.9.7' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@vue/cli-service'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by sodatea** [comment]
Please follow the issue template and provide the output of `vue info` here.

It's likely because your npm version is too low.

**Comment by huhan** [comment]
npm version from 6 to 7,it's nomal
