### ISSUE TITLE
How to optimize the webpack build?

### ISSUE THREAD

**Issue by siyongXia** [vuejs/vue-cli#649]
1.i use  vue init webpack demo to init my project,and new a file a.vue under /src/components,as below
```
<template>
    <div>component 1</div>
</template>
<script>
    export default {
        data(){
            return {
            }
        },
        methods:{
            getData () {
                console.log(1);
            }
        },
        mounted(){
            this.getData();
        }
    }
</script>
<style scoped >
    .box {
        width: 1px;
        height: 10px;
        background-color: #ccc;
    }
</style>
```
2.Modify /src/router/index.js,use component lazyload 
```
import Vue from 'vue'
import Router from 'vue-router'

const HelloWorld = () => import('@/components/HelloWorld')
const A = () => import('@/components/a.vue')
Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'HelloWorld',
      component: HelloWorld
    },
    {path: '/a',name: 'A',component: A},
  ]
})
```
3. Terminal execute npm run build,and i get the directory dist as below
![image](https://user-images.githubusercontent.com/24487873/33049839-db73e544-ce9c-11e7-9957-5614297eccb5.png)
4.then new the second file b.vue under /src/components,as below
```
<template>
    <div>component B</div>
</template>
<script>
    export default {
        data(){
            return {

            }
        },
        methods:{
            fetchData (page) {
                console.log(page);
            }
        },
        mounted(){
            this.fetchData(2);
        }
    }
</script>

<style scoped >
    .box {
        width: 1px;
        height: 10px;
        background-color: red;
    }
</style>
```
5.update  /src/router/index.js
```
import Vue from 'vue'
import Router from 'vue-router'

const HelloWorld = () => import('@/components/HelloWorld')
const A = () => import('@/components/a.vue')
const B = () => import('@/components/b.vue')

Vue.use(Router)

export default new Router({
  routes: [
    {
      path: '/',
      name: 'HelloWorld',
      component: HelloWorld
    },
    {path: '/a',name: 'A',component: A},
    {path: '/b',name: 'B',component: B},
  ]
})
```
5.Repeat step 3(npm run build),and get the build directory dist,as below
![image](https://user-images.githubusercontent.com/24487873/33049935-44cf023a-ce9d-11e7-9da4-57bfa9911e74.png)
6.Compare the result of two build director,like 0.edeec9e7398311b1e3f1.js vs 0.4f388e450a65c74371bf.js,
complete different,as below
![image](https://user-images.githubusercontent.com/24487873/33050074-fbf37c8e-ce9d-11e7-8b0e-900f8db15d2a.png)

I found the file 0.edeec9e7398311b1e3f1.js(after first build) is related to 1.a79f1cfd1b16dba782c6.js(after second build),but still has a little difference,as below
![image](https://user-images.githubusercontent.com/24487873/33050084-08293246-ce9e-11e7-8951-40a89021fc73.png)

Q:This is a small scene,At my work,we have more than 40 routes and many components for these routes,and we changed the webpack config to build  the project to another repository(used CDN for static);Now i get a task to add a new route,and after i exec npm run build,i found there are two many changes compare to before;It mean  every time i exec npm run build will affect the files at online,and our CDN for static is unnecessary because the file is always change;
How can i control the build to promise not affect the file before?

**Comment by posva** [comment]
Sorry but this has nothing to deal with vue-cli 😅 

Please, consider using the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js) for questions first. But feel free to come back and open an issue if it turns out to be a bug 🙂
