### ISSUE TITLE
vue init webpack demo ， router is history,  npm run build，production environment Can't run???

### ISSUE THREAD

**Issue by wwb568109135** [vuejs/vue-cli#650]
(1) vue init webpack demo 
(2)  router is history,  
(3) npm run build，
(4) production environment
Can't run

why ???

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---


You need to serve the generated `dist` folder with a static web server. You can use `serve`:
```sh
npm i -g serve
serve dist
```

**Comment by wwb568109135** [comment]
sorry  , The problem has been solved

thank  you ！！
