### ISSUE TITLE
Update ts-jest dependency

### ISSUE THREAD

**Issue by Oleksii14** [vuejs/vue-cli#6502]
### What problem does this feature solve?
the old version of ts-jest (v24) causes the warnings while running unit tests

### What does the proposed API look like?
Package has updated dependency of ts-jest

example repo: https://github.com/Oleksii14/ts-jest-typescript-v4.2.4

https://github.com/Oleksii14/ts-jest-typescript-v4.2.4/blob/master/yarn.lock#L1846

**Comment by sodatea** [comment]
Use 5.0 beta
