### ISSUE TITLE
declare module '@vue/runtime-core'  break the whole app

### ISSUE THREAD

**Issue by yaquawa** [vuejs/vue-cli#6503]
### Version
5.0.0-beta.1

### Reproduction link
[https://github.com/yaquawa/vuetest](https://github.com/yaquawa/vuetest)

### Steps to reproduce
Add the following to `src/shims-vue.d.ts`
```ts
declare module '@vue/runtime-core' {
  interface ComponentCustomOptions {
    layout?: string
    breadcrumb?: number
  }
}
```
then you'll get this:
<img width="750" alt="Screen Shot 2021-05-29 at 18 26 40" src="https://user-images.githubusercontent.com/13927101/120065291-759b8880-c0ab-11eb-9a9d-063261e8951a.png">

---
I just want to add some custom options for all my components, not sure why this is happening.

If I add the above `declare module...` to a file of a npm package, for example `node_modules/vue-router-layout/lib/index.d.ts`, that works..

**Comment by LinusBorg** [comment]
You need to import the interface before overwriting it.

Without that, the declaration overrides the whole runtime-core package's types.

**Comment by LinusBorg** [comment]
```ts
import { ComponentCustomOptions } from '@vue/runtime-core'

declare module '@vue/runtime-core' {
  interface ComponentCustomOptions {
    layout?: string
    breadcrumb?: number
  }
}

```

**Comment by yaquawa** [comment]
@LeBenLeBen This time, I got something different errors.

<img width="540" alt="Screen Shot 2021-05-29 at 18 56 50" src="https://user-images.githubusercontent.com/13927101/120066059-a7165300-c0af-11eb-9d98-86968cc324c9.png">

**Comment by LinusBorg** [comment]
you might have to move the import into the `declare` block like in the other one

**Comment by LinusBorg** [comment]
Oh, or I think you just have to export the interface:

```ts
declare module '@vue/runtime-core' {
  export interface ComponentCustomOptions {
    layout?: string
    breadcrumb?: number
  }
}
```

TBH type augmentation in declaration files still confuse me all the time.

**Comment by yaquawa** [comment]
Put it in a *.ts file works for me, thanks a lot !!
