### ISSUE TITLE
How to use less plugin?

### ISSUE THREAD

**Issue by hysyer** [vuejs/vue-cli#651]
`less: generateLoaders('less', { plugins: [new LessPluginFunctions()]})`
 
this is the error: `Module build failed: Plugin.install is not a function  in undefined (line undefined, column undefined)`

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
