### ISSUE TITLE
Can't use compeonnt from another file

### ISSUE THREAD

**Issue by kumaresan-subramani** [vuejs/vue-cli#6513]
### Version
4.5.10

### Reproduction link
[https://github.com/kumaresan-subramani/Vue3-template-check](https://github.com/kumaresan-subramani/Vue3-template-check)

### Environment info
```
"vue": "^3.0.5",
    "vue-class-component": "^8.0.0-rc.1",
    "vue-template-compiler": "^2.6.11"
"@vue/cli-plugin-babel": "^4.5.10",
    "@vue/cli-plugin-eslint": "^4.5.10",
    "@vue/cli-service": "^4.5.10",
    "@vue/compiler-sfc": "^3.0.5",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.8.0",
    "eslint-plugin-vue": "^7.4.1",
    "vue-loader-v16": "^16.0.0-beta.5.4"
```

### Steps to reproduce

- CLone below sample

https://github.com/kumaresan-subramani/Vue3-template-check
- And give `npm run serve`

- it wont render `helloworld` component

- But it is working fine in below compoent

https://stackblitz.com/edit/vue-s4fpy3?file=package.json

### What is expected?
Need to redner compeonnt form another file

### What is actually happening?
But it not renderign properly

**Comment by kumaresan-subramani** [comment]
@sodatea - can you sugegst on this

**Comment by sodatea** [comment]
https://github.com/kumaresan-subramani/Vue3-template-check/blob/fc962ebda6488ea453196725a927876b7f95972c/src/App.vue#L26

```diff
- import { HelloWorld } from "./components/HelloWorld";
+ import HelloWorld from "./components/HelloWorld.vue";
```

1. Don't omit the `.vue` extension
2. It's the default export

**Comment by kumaresan-subramani** [comment]
@sodatea , even after changing this same issue occurs

**Comment by sodatea** [comment]
What issue? I don't see any errors on my machine. The app renders as expected:
![image](https://user-images.githubusercontent.com/3277634/120768702-06141600-c54f-11eb-9441-322efc0837f0.png)

**Comment by kumaresan-subramani** [comment]
Still not working for me

Is there any limitation like node version vue version etc?

**Comment by sodatea** [comment]
What's your node version? And what's the error?

**Comment by kumaresan-subramani** [comment]
@sodatea ,

node - 10.15.1

it is wokring fine when i use `yarn install` to install node modules
