### ISSUE TITLE
Unexpected token , in JSON at position 1987

### ISSUE THREAD

**Issue by neilyoung** [vuejs/vue-cli#6516]
### Version
5.0.0-beta.1

### Reproduction link
[https://google.com](https://google.com)

### Environment info
```
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 87.0
    Safari: 14.1.1
  npmGlobalPackages:
    @vue/cli: Not Found


```

### Steps to reproduce
npm i -g @vue/cli

vue ui

### What is expected?
It should work

### What is actually happening?
It doesn't work

**Comment by neilyoung** [comment]
And a hint: Make it more complicated to create an issue and you will finally land at zero problems....

**Comment by neilyoung** [comment]
BTW:  `@vue/cli: Not Found` this is because I immediately uninstalled this crap. Feel free to close this issue

**Comment by sodatea** [comment]
Well, what's the point of this issue if you don't provide any necessary information for diagnosing and refuse to learn any manners?

**Comment by neilyoung** [comment]
Well, I'll tell you, so that you learn something: Initially I wanted to get that solved. Then, after having passed your "DONT REPORT ANY ISSUE" prevention phalanx I was so p...d, that I decided to get rid of it. In the end I was able to find it, but since I was just keen about to see, what is it (and it is nothing at all) I removed id. The baseline is: Your installation does not work on macOS 11.4 latest version with the npm command outlined above, but this is your problem not mind, and if here is somebody who has to learn, it is not me. Period.

**Comment by sodatea** [comment]
This is obviously your problem because Vue CLI already works on thousands of other users' machines running macOS 11.4.

We are happy to help if you provide the *necessary* information that are required in the issue helped.
But you chose to ignore it.

So, fuck off.

**Comment by neilyoung** [comment]
Same to you, jerk
