### ISSUE TITLE
vue-cli can`t be run with ip adrees

### ISSUE THREAD

**Issue by zhenwoo** [vuejs/vue-cli#652]
A Vue project  create by vue-cli can be run with 'localhot:8080' but can not be run with ip adrees, why?

**Comment by LinusBorg** [comment]
what kind of IP address?

**Comment by zhenwoo** [comment]
such as "http://192.168.1.101:8080"

**Comment by LinusBorg** [comment]
`localhost` doesn't allow external access from our network. That'S why it's the default setting, it's secure.

Set the host to `0.0.0.0`, then other computers in the network can access it via your local IP.

**Comment by fimars** [comment]
https://github.com/webpack/webpack-dev-server/issues/147

**Comment by lwxbr** [comment]
Firewalls can be trouble too. I had to disable the Firewall of Windows to use that feature.
