### ISSUE TITLE
"vue-cli-service serve" not support symlink

### ISSUE THREAD

**Issue by k8w** [vuejs/vue-cli#6521]
### Version
4.5.13

### Reproduction link
[https://github.com/k8w/vue-cli-symlink-issue](https://github.com/k8w/vue-cli-symlink-issue)

### Environment info
```
- Both Windows 10 & Mac OS BigSur
- Both Node14 & Node16
```

### Steps to reproduce
1. Create a new Vue project
2. Put a symlink outside the project dir into `src`
3. npm run serve

### What is expected?
Run successfully, treat symlink as a normal directory.

### What is actually happening?
Syntax Error: Error: No ESLint configuration found in "xxxx"

**Comment by sodatea** [comment]
https://cli.vuejs.org/guide/troubleshooting.html#running-installation-with-sudo-or-as-root
