### ISSUE TITLE
How to Render Data to the DOM

### ISSUE THREAD

**Issue by carlosHerz** [vuejs/vue-cli#653]
I have created a template:

<template>
    <div>
    <slot></slot>
    </div>
</template>

<script>
export default {
 data() {
     return {
        isShowing: false 
     },
 methods: {
    toggleShow: function() {
      this.isShowing = !this.isShowing;
      setTimeout(() => {
        this.toggleShow1();
      }, 800);
    }
 }
<script>

<style>
  ..
</style>

And in the HTML document i'd like to toggle a heading only when isShowing is set to true:

<div v-if="isShowing">
   <div>
       <h1>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h1>
   </div>
</div>

But then i get this error: ReferenceError: isShowing is not defined

Any help would be much appreciated. Thanks!

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
