### ISSUE TITLE
Spelling mistake when creating new project

### ISSUE THREAD

**Issue by tomkochi** [vuejs/vue-cli#6536]
### Version
4.5.13

### Reproduction link
[NA](NA)

### Environment info
```
Mac
```

### Steps to reproduce
npm create vue-app

### What is expected?
The second prompt must be `How would your describe your superb project`

### What is actually happening?
"How would your descripe your superb project" (please note the spelling of DESCRIBE)

**Comment by 719media** [comment]
Sounds like you're in the wrong place, that code is nowhere in this repo, and using `npm create/init` is not part of the installation instructions. The `vue-app` package looks to be an old, dead package. Please close this issue.
