### ISSUE TITLE
设置publicPath后，路由跳转出错

### ISSUE THREAD

**Issue by hello-lun** [vuejs/vue-cli#6537]
### Version
5.0.0-beta.2

### Reproduction link
[http://no-url](http://no-url)

### Environment info
```
vue 2.16.11
node 14.17.0
```

### Steps to reproduce
yarn
yarn serve

### What is expected?
路由调整正常

### What is actually happening?
路由跳转出错

问题描述：
我们用到webpack5的模块联邦做微前端，现在有A父应用、B子应用，B子应用的vue.config.js设置了publicPath为“192.168.2.101:8887”后，
 嵌入到A中，点击B中的路由跳转，地址栏多出现“192.168.2.101:8887”，这个怎么解决呀

![image](https://user-images.githubusercontent.com/34638158/122431130-c45f8280-cfc6-11eb-9cf4-01c3109e3b9c.png)

**Comment by LinusBorg** [comment]
> Reproduction link

> http://no-url
