### ISSUE TITLE
Vuejs-templates v1.2.3, v1.2.4 s open the blank with afari browser, who knows what to do?

### ISSUE THREAD

**Issue by lxk1080** [vuejs/vue-cli#654]

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by lxk1080** [comment]
Well, thanks for your reminder
