### ISSUE TITLE
根本创建不了项目

### ISSUE THREAD

**Issue by tangly1991** [vuejs/vue-cli#6551]
### Version
4.5.13

### Environment info
```
根据文档的步骤，安装完cli根本无法创建项目，一直报错
```

### Steps to reproduce
1、创建新项目

### What is expected?
1、真正做到按文档的操作就能成功创建项目
2、完善错误信息

### What is actually happening?
1、安装了所有可能需要的包还是报错，不能创建项目
2、错误信息太笼统，不够精确

**Comment by vcluo** [comment]
sorry can you provide the more detail

**Comment by sodatea** [comment]
> 2、错误信息太笼统，不够精确

什么错误信息？

提供的信息太少，恕无法提供帮助。

**Comment by vcluo** [comment]
may be you can learn first to the officel demo begin. 
this is address : https://cn.vuejs.org/v2/guide/index.html
wish can help you

**Comment by sarlemon** [comment]
建议附上详细的报错信息，方便解决你的问题
