### ISSUE TITLE
Webpack 5 resove.fallback api not support in vue-cli

### ISSUE THREAD

**Issue by BertieGo** [vuejs/vue-cli#6552]
### What problem does this feature solve?
With new webpack 5 release, then I try to use Vue-cli ^5.0.0-beta.1 to build my project, but appear bugs with node polyfill config, then Webpack office document guide me to use :
````
module.exports = {
  //...
  resolve: {
    fallback: {
      xyz: path.resolve(__dirname, 'path/to/file.js'),
    },
  },
};
````

but when I use it in my Vue-cli config, like this:
````
config.resolve.alias.fallback
````

it's doesn't work, check the source code seen like have not support or I do it with the wrong way ?

plz check this out, thx~ : )

### What does the proposed API look like?
config.resolve.alias.fallback

**Comment by LinusBorg** [comment]
Missing reproduction as required in issue guidelines
