### ISSUE TITLE
minimist high vulnerability issue with @vue/cli-plugin-e2e-cypress@4.5.13

### ISSUE THREAD

**Issue by mtermoul** [vuejs/vue-cli#6555]
<img width="1080" alt="Screen Shot 2021-06-29 at 2 40 50 PM" src="https://user-images.githubusercontent.com/8376035/123850481-14ecaf00-d8e8-11eb-8e55-bac6a218c19b.png">

<img width="719" alt="Screen Shot 2021-06-29 at 2 41 17 PM" src="https://user-images.githubusercontent.com/8376035/123850509-1b7b2680-d8e8-11eb-9b70-615c82909621.png">

### Version
4.5.13

### Environment info
```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 7.11.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: Not Found
    Firefox: 88.0.1
    Safari: 13.1

```

### Steps to reproduce
run npm audit

### What is expected?
update mini mist dependency to version 1.2.5 or higher

### What is actually happening?
npm is showing this error
minimist  <0.2.1 || >=1.0.0 <1.2.3
Prototype Pollution - https://npmjs.com/advisories/1179
No fix available

**Comment by hasanhameed-tenovos** [comment]
anu update?

**Comment by sodatea** [comment]
It doesn't expose any real threats to users. See https://overreacted.io/npm-audit-broken-by-design/
