### ISSUE TITLE
peer dependency error

### ISSUE THREAD

**Issue by panhezeng** [vuejs/vue-cli#6558]
### Version
4.5.13

### Reproduction link
[https://new-issue.vuejs.org/?repo=vuejs/vue-cli](https://new-issue.vuejs.org/?repo=vuejs/vue-cli)

### Environment info
```
  System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.22.1/bin/yarn
    npm: 7.16.0 - ~/.nvm/versions/node/v12.22.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: Not Found
    Firefox: 75.0
    Safari: 14.1.1
  npmPackages:
    @panhezeng/vue-axios: ^2.0.5 => 2.0.5 
    @panhezeng/vue-tinymce:  2.3.8 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.6 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.13 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.13 
    @vue/cli-plugin-babel: ^4.5.13 => 4.5.13 
    @vue/cli-plugin-eslint: ^4.5.13 => 4.5.13 
    @vue/cli-plugin-router: ^4.5.13 => 4.5.13 
    @vue/cli-plugin-vuex: ^4.5.13 => 4.5.13 
    @vue/cli-service: ^4.5.13 => 4.5.13 
    @vue/cli-shared-utils:  4.5.13 
    @vue/compiler-core:  3.1.2 
    @vue/compiler-dom:  3.1.2 
    @vue/compiler-sfc:  3.1.2 
    @vue/compiler-ssr:  3.1.2 
    @vue/component-compiler-utils:  3.2.2 
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/shared:  3.1.2 
    @vue/web-component-wrapper:  1.3.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.14 
    vue-cli-plugin-element: ^1.0.1 => 1.0.1 
    vue-cropper: ^0.5.6 => 0.5.6 
    vue-echarts: ^4.1.0 => 4.1.0 
    vue-eslint-parser:  7.6.0 
    vue-hot-reload-api:  2.3.4 
    vue-i18n: ^8.21.0 => 8.24.5 
    vue-image-crop-upload: ^2.5.0 => 2.5.0 
    vue-img-cutter: ^2.2.3 => 2.2.3 
    vue-loader:  15.9.7 (16.3.0)
    vue-router: ^3.2.0 => 3.5.2 
    vue-style-loader:  4.1.3 
    vue-template-compiler: ^2.6.11 => 2.6.14 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.4.0 => 3.6.2 
  npmGlobalPackages:
    @vue/cli: 4.5.13

```

### Steps to reproduce
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: vue@2.6.14
npm WARN node_modules/vue
npm WARN   dev vue@"^2.6.11" from the root project
npm WARN   8 more (@panhezeng/el-multiple-upload, element-ui, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer vue@"3.1.2" from @vue/compiler-sfc@3.1.2
npm WARN node_modules/@vue/compiler-sfc
npm WARN   peer @vue/compiler-sfc@"^3.0.0-beta.14" from @vue/cli-service@4.5.13
npm WARN   node_modules/@vue/cli-service

### What is expected?
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: vue@2.6.14
npm WARN node_modules/vue
npm WARN   dev vue@"^2.6.11" from the root project
npm WARN   8 more (@panhezeng/el-multiple-upload, element-ui, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer vue@"3.1.2" from @vue/compiler-sfc@3.1.2
npm WARN node_modules/@vue/compiler-sfc
npm WARN   peer @vue/compiler-sfc@"^3.0.0-beta.14" from @vue/cli-service@4.5.13
npm WARN   node_modules/@vue/cli-service

### What is actually happening?
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: vue@2.6.14
npm WARN node_modules/vue
npm WARN   dev vue@"^2.6.11" from the root project
npm WARN   8 more (@panhezeng/el-multiple-upload, element-ui, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer vue@"3.1.2" from @vue/compiler-sfc@3.1.2
npm WARN node_modules/@vue/compiler-sfc
npm WARN   peer @vue/compiler-sfc@"^3.0.0-beta.14" from @vue/cli-service@4.5.13
npm WARN   node_modules/@vue/cli-service

---
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: vue@2.6.14
npm WARN node_modules/vue
npm WARN   dev vue@"^2.6.11" from the root project
npm WARN   8 more (@panhezeng/el-multiple-upload, element-ui, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer vue@"3.1.2" from @vue/compiler-sfc@3.1.2
npm WARN node_modules/@vue/compiler-sfc
npm WARN   peer @vue/compiler-sfc@"^3.0.0-beta.14" from @vue/cli-service@4.5.13
npm WARN   node_modules/@vue/cli-service

**Comment by LinusBorg** [comment]
closing for ignored reproduction requirement
