### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Marka83** [vuejs/vue-cli#656]
I can't install vue-cli. 
I reinstalled node.js but it didn't help.
Complete log is in attachment.
[2017-11-30T08_16_34_678Z-debug.log](https://github.com/vuejs/vue-cli/files/1516997/2017-11-30T08_16_34_678Z-debug.log)

**Comment by a062670** [comment]
CoffeeScript has moved!

https://www.npmjs.com/package/coffee-script

**Comment by Jackliu007888** [comment]
now how can i use vue-cli ? i installed coffeescript -g ,but it didn't work.

**Comment by a062670** [comment]
I have the same trouble.

Waiting for vue-cli to update...

**Comment by serdem** [comment]
Same problem, I can't use vue-cli any more

**Comment by agogex** [comment]
+1 The same problem. How to fix it?

**Comment by pkoecker** [comment]
+1 Same Issue

**Comment by lihua123569** [comment]
Same problem

**Comment by posva** [comment]
Duplicate of #655

**Comment by avatarvb** [comment]
hello i juste remove the folder @vue from my desktop C:\Users\Labo\AppData\Roaming\npm
