### ISSUE TITLE
cli-plugin-e2e-cypress has runaway promise in a very simple setup

### ISSUE THREAD

**Issue by andruhon** [vuejs/vue-cli#6574]
### Version
5.0.0-beta.2

### Reproduction link
[https://github.com/andruhon/dodgy-promise-quickstart](https://github.com/andruhon/dodgy-promise-quickstart)

### Environment info
```
Not sure if the issue is rooted in the cli-plugin-e2e-cypress or somewhere else. 
I created a quick start project to reproduce it: https://github.com/andruhon/dodgy-promise-quickstart

Generally the the issue is: I run e2e tests in headless mode with `vue-cli-service test:e2e --mode e2e --headless` and after "All specs passed!" the following warning is displayed
```
(node:3448) Warning: a promise was created in a handler at internal/timers.js:461:21 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (Local\Cypress\Cache\7.6.0\Cypress\resources\app\packages\server\node_modules\bluebird\js\release\promise.js:225:13)
```
The run shuts down successfully with 0 code after a few minutes. In bigger project it takes 10-20 minutes to shut down after this runaway promise.
```

### Steps to reproduce
git clone git@github.com:andruhon/dodgy-promise-quickstart.git
cd dodgy-promise-quickstart
npm install
npm run test:e2e-headless

### What is expected?
Test to finish gracefully, without promise warnings.

### What is actually happening?
Runaway promise warning displayed.

**Comment by andruhon** [comment]
https://github.com/vuejs/vue-cli/issues/6574

**Comment by WhereJuly** [comment]
Same issue here.
