### ISSUE TITLE
今天全局安装vue-cli提示coffee-script错误，请尽快修改这个错误

### ISSUE THREAD

**Issue by love2157dream** [vuejs/vue-cli#658]
L:\nodejs\node_global\vue -> L:\nodejs\node_global\node_modules\vue-cli\bin\vue
L:\nodejs\node_global\vue-init -> L:\nodejs\node_global\node_modules\vue-cli\bin\v
ue-init
L:\nodejs\node_global\vue-list -> L:\nodejs\node_global\node_modules\vue-cli\bin\v
ue-list

> coffee-script@1.12.8 postinstall L:\nodejs\node_global\node_modules\vue-cli\node
_modules\coffee-script
> node --eval 'if (require("./package.json").name === "coffee-script") { var red,
yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISAB
LE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x
1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update r
eferences to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"c
offeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major
 version has been released under the " + yellow + "coffeescript" + reset + " name
on NPM. This new release targets modern JavaScript, with minimal breaking changes.
 Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn("
"); }'

[eval]:1
'if
^^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:569:30)
    at evalScript (bootstrap_node.js:432:27)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.js
on").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan
 = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow =
"\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScri
pt has moved!" + reset + " Please update references to " + yellow + "\"coffee-scri
pt\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) i
nstead."); console.warn("Also, a new major version has been released under the " +
 yellow + "coffeescript" + reset + " name on NPM. This new release targets modern
JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffee
script.org" + reset + "."); console.warn(""); }'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the coffee-script@1.12.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional loggi
ng output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     L:\nodejs\node_cache\_logs\2017-11-30T10_26_19_285Z-debug.log

**Comment by formattedzzz** [comment]
可是好像不需要装vue-cli啊，装个vue也可以初始化啊

**Comment by lihua123569** [comment]
我也是，node8 npm5

**Comment by posva** [comment]
Duplicate of #655

**Comment by formattedzzz** [comment]
可以装了吗
