### ISSUE TITLE
can  not install vue-cli

### ISSUE THREAD

**Issue by lihua123569** [vuejs/vue-cli#660]
Coffeescript has been installed, but there are other problems, as follows
https://user-images.githubusercontent.com/8295524/33428497-0a5b2656-d604-11e7-8845-2c11129fa4d2.png

**Comment by marekchen** [comment]
same,want for help @yyx990803

**Comment by ksbaozi** [comment]
me too...

**Comment by heiliuer** [comment]
me too...

**Comment by SmileStrength** [comment]
me too..

**Comment by posva** [comment]
Duplicate of #655 
@lihua123569 Please, stop already opening new issues
