### ISSUE TITLE
Use?. in Android 9 browser And?? Syntax will make the page unable to run. Babel should already support it

### ISSUE THREAD

**Issue by ht-sauce** [vuejs/vue-cli#6606]
### Version
5.0.0-beta.2

### Environment info
```
Android 9
```

### Steps to reproduce
use?. And?? grammar

### What is expected?
Normal compilation to es2015

### What is actually happening?
error

**Comment by screetBloom** [comment]
@ht-sauce 

add `@babel/plugin-proposal-optional-chaining` in your babel.config.js

<br>

just like this👇
``` shell
$ yarn add @babel/plugin-proposal-optional-chaining
```

``` js
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset'
  ],
  plugins: [
    '@babel/plugin-proposal-optional-chaining'
  ],
}


```

**Comment by sodatea** [comment]
Can't help without a proper reproduction.
