### ISSUE TITLE
"css.requireModuleExtension" is not allowed 

### ISSUE THREAD

**Issue by lisiyizu** [vuejs/vue-cli#6607]
### Version
5.0.0-beta.2

### Environment info
```
"devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/eslint-parser": "^7.12.16",
    "@vue/cli-plugin-babel": "~5.0.0-beta.2",
    "@vue/cli-plugin-eslint": "~5.0.0-beta.2",
    "@vue/cli-service": "~5.0.0-beta.2",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.24.0",
    "eslint-plugin-vue": "^7.6.0",
    "external-remotes-plugin": "^1.0.0",
    "node-sass": "^6.0.1",
    "path-browserify": "^1.0.1",
    "sass-loader": "^12.1.0",
    "vue": "2.5.17",
    "vue-template-compiler": "2.5.17",
    "webpack": "^5.47.0"
  },
```

### Steps to reproduce
```javascript
// vue.config.js
module.exports = {
  css: {
    requireModuleExtension: false
  }
}
```

![image](https://user-images.githubusercontent.com/12014252/127314196-2eea480f-4614-40de-b990-2e41286ffced.png)

**Comment by sodatea** [comment]
https://next.cli.vuejs.org/migrations/migrate-from-v4.html#vue-cli-service

> The `css.requireModuleExtension` option is removed. If you do need to strip the `.module` part in CSS Module file names, please refer to [Working with CSS > CSS Modules](https://next.cli.vuejs.org/guide/css.html#css-modules) for more guidance.
