### ISSUE TITLE
run dev error

### ISSUE THREAD

**Issue by ChangedenCZD** [vuejs/vue-cli#662]
14% building modules 35/37 modules 2 active ...s\vue-demo\src\module\index\index.vue
 14% building modules 35/39 modules 4 active ...e-style-loader\lib\addStylesClient.js
 14% building modules 36/39 modules 3 active ...e-style-loader\lib\addStylesClient.js
 14% building modules 37/39 modules 2 active ...e-style-loader\lib\addStylesClient.js
 14% building modules 38/39 modules 1 active ...s\vue-demo\src\module\index\index.vue
 14% building modules 38/40 modules 2 active ...\vue-style-loader\lib\listToStyles.js
 14% building modules 38/41 modules 3 active ...-demo\node_modules\process\browser.js
 15% building modules 42/42 modules 0 active
 71% sealing
 82% module reviving
 83% module order optimization
 88% hashing
 90% chunk assets processing
 94% asset optimization ERROR  Failed to compile with 1 errors09:40:58

 error

**Comment by LinusBorg** [comment]
Please open an issue in the template you are using, and provide more information (e.g. node version)
