### ISSUE TITLE
Potential vulnerability introduced in @vue/cli-service

### ISSUE THREAD

**Issue by vincentsum777** [vuejs/vue-cli#6621]
Hi, @sodatea @fangbinwei, 
### Issue Description

   I noticed that a vulnerability is introduced in **_@vue/cli-service@4.5.13_**:
     Vulnerability **SNYK-JS-EJS-1049328** affects package **_ejs_** (versions:<3.1.6):  [https://snyk.io/vuln/SNYK-JS-EJS-1049328](https://snyk.io/vuln/SNYK-JS-EJS-1049328)
  The above vulnerable package is referenced by **_@vue/cli-service@4.5.13_** via:
`@vue/cli-service@4.5.13 ➔ webpack-bundle-analyzer@3.9.0 ➔ ejs@2.7.4`

Since **_@vue/cli-service@4.5.13_** ([317,225 downloads per week](https://www.npmjs.com/package/@vue/cli-service/v/4.5.13?activeTab=versions)) is referenced by **145** downstream projects (e.g.,@iez/core 3.0.6 (latest version), @ditojs/server 0.259.0 (latest version), radiate-framework 4.4.1 (latest version), @quasiris/qsc-data-table 1.3.3 (latest version)), the vulnerability [https://snyk.io/vuln/SNYK-JS-EJS-1049328](https://snyk.io/vuln/SNYK-JS-EJS-1049328) can be propagated into these downstream projects and expose security threats to them via the following package dependency paths:
 (1)`@quasiris/qsc-data-table@1.3.3 ➔ @vue/cli-service-global@4.5.13 ➔ @vue/cli-service@4.5.13 ➔ webpack-bundle-analyzer@3.9.0 ➔ ejs@2.7.4`
  **......**

If **_@vue/cli-service@4.5.13_** removes the vulnerable package from the above version, then its fixed version can help downstream users decrease their pain.

**Given the large number of downstream users, could you help update your package to remove the vulnerability from @vue/cli-service@4.5.13 ?**

### Fixing suggestions

In **_@vue/cli-service@4.5.14_**, you can kindly perform the following upgrade :
`webpack-bundle-analyzer ^3.8.0 ➔ ^4.0.0`; 

**Note:**
_webpack-bundle-analyzer@4.0.0(>=4.0.0) directly depends on ejs@3.1.6 which has fixed the vulnerability ([https://snyk.io/vuln/SNYK-JS-EJS-1049328](https://snyk.io/vuln/SNYK-JS-EJS-1049328))_
Of course, you are welcome to share other ways to resolve the issue.

Thank you for your attention to this issue.

Best regards,
Vincentsum ^_^

**Comment by sodatea** [comment]
It's not a real vulnerability for Vue CLI projects.

See https://overreacted.io/npm-audit-broken-by-design/
