### ISSUE TITLE
Build drops some dependency css that dev server uses

### ISSUE THREAD

**Issue by slaweet** [vuejs/vue-cli#6628]
### Version
4.5.13

### Reproduction link
[https://github.com/slaweet/vue-cli-build-omits-bootstrap-darktheme-css](https://github.com/slaweet/vue-cli-build-omits-bootstrap-darktheme-css) 

note that there is just one commit on top of the default vue-cli app https://github.com/slaweet/vue-cli-build-omits-bootstrap-darktheme-css/commit/aa9dbd980a23c8d1b644a227492816d8b08f60cc

### Environment info
```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 90.0.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.6 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.13 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.13 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-router:  4.5.13 
    @vue/cli-plugin-vuex:  4.5.13 
    @vue/cli-service: ~4.5.0 => 4.5.13 
    @vue/cli-shared-utils:  4.5.13 
    @vue/component-compiler-utils:  3.2.2 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.14 
    vue-eslint-parser:  7.10.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.8 (16.4.1)
    vue-style-loader:  4.1.3 
    vue-template-compiler: ^2.6.11 => 2.6.14 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
```
yarn serve
```
Open the page to see it looks like this:

![Screenshot from 2021-08-09 09-07-25](https://user-images.githubusercontent.com/1254342/128670739-23a1bca4-95d8-499a-9f8d-dc6cf766a592.png)

compare the page to

```
yarn build
yarn add serve
serve dist -d
```

open the page to see it looks like this
![Screenshot from 2021-08-09 09-07-44](https://user-images.githubusercontent.com/1254342/128670780-71a5d029-45fa-46d2-af3b-93e9ce017150.png)

### What is expected?
The page from `yarn serve` looks the same as the page from `yarn build`

### What is actually happening?
`yarn build` omits all the css rules with `[data-theme=dark]` so that the dark styles from https://www.npmjs.com/package/bootstrap-darkmode are missing.

---
I don't understand why is this happening, but if it's not possible to build the css, it should at least fail the build, not omit it silently.

**Comment by sodatea** [comment]
https://unpkg.com/browse/bootstrap-darkmode@0.9.0/package.json#L33

Bug in `bootstrap-darkmode`. CSS files *are* side effects. It shouldn't be marked as `sideEffects: false`.

I guess it's set by default by `ng-packagr`, but that's not a correct default for a CSS package.

**Comment by slaweet** [comment]
@sodatea Thank you for the explanation.

I filed a bug with `bootstrap-darkmode`.

But now I think the bug in vue-cli is that `sideEffects: false` is ignored by `yarn serve`. I was trying to google some docs about this that would say the this is expected behavior, but didn't find any. I know I cannot rely on dev server working exactly the same as build, but `sideEffects` config feels like something that should be possible to align in build and dev server.

Can I open a new issue in vue-cli, or am I missing something?

**Comment by LinusBorg** [comment]
`sideEffects` only has an effect during bundling for production, when webpack does tree-shaking. so it's expected that this effect doesn't manifest during development.

Also, here's the relevant webpack docs clearly stating that you should 

https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free (see last paragraph under that heading):

> Note that any imported file is subject to tree shaking. This means if you use something like css-loader in your project and import a CSS file, it needs to be added to the side effect list so it will not be unintentionally dropped **in production mode**:
```json
{
  "name": "your-project",
  "sideEffects": ["./src/some-side-effectful-file.js", "*.css"]
}
```
