### ISSUE TITLE
怎么打包出多个js文件

### ISSUE THREAD

**Issue by huygo** [vuejs/vue-cli#664]
用vue-cli里配置的webpack怎么分离出多个js，项目单个js文件过大

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
