### ISSUE TITLE
vue-cli      Init a new project with error "Uncaught SyntaxError: Use of const in strict mode.  "

### ISSUE THREAD

**Issue by Hillkinsh** [vuejs/vue-cli#665]
when I initial a new project, I used commands as follows:
vue init webpack my-pro
cd my-pro/
npm install
npm run dev

then, it shows " DONE  Compiled successfully in 5653ms                 

Your application is running here: http://localhost:8080" in  command line", 
but when I open chrome and address in localhost:8080, there is an error: "Uncaught SyntaxError: Use of const in strict mode. "

so, how could I solve it?
 
ps: node version v8.8.0

**Comment by LinusBorg** [comment]
This is the wrong repository - that template has its own repository:

https://github.com/vuejs-templates/webpack

Please open an issue there, and provide further information, like the file and line number where this error message comes from.
