### ISSUE TITLE
pages多页面配置中，非vue页面无法运行

### ISSUE THREAD

**Issue by gapkukb** [vuejs/vue-cli#6651]
### Version
4.4.6

### Environment info
```
windows 10
```

### Steps to reproduce
//vue.config.js
{
pages:{
  index:{ .... } // 正常配置,
  test:{
    entry:'src/test.js',
    chunks:['test']
  }
}
}

//需要打包多个html页面，供window.open调用，部分test.html页面不需要用到vue的功能，也就不用引入vue模块，在vue.config.js中配置pages中的chunks只指定了页面本身要用到js文件，但是无法运行

### What is expected?
能够正常运行

### What is actually happening?
程序不能运行

**Comment by sodatea** [comment]
请提供必要的复现代码和环境信息。
