### ISSUE TITLE
No matching version found for core-js-pure@^3.10.2.

### ISSUE THREAD

**Issue by hossein13m** [vuejs/vue-cli#6654]
### Version
4.4.6

### Environment info
```
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.17.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.21.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 92.0.4515.107
    Firefox: 91.0.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
When I try to install the latest Vue-Cli using `npm install -g @vue/cli`, I get the following error. I think core-js-pure^3.10.2 is not available in NPM as a dependency of Vue-CLI. 

### What is expected?
The latest version of vue-cli should have been installed.

### What is actually happening?
I get an error and installation fails.

**Comment by sodatea** [comment]
Likely a network issue.
Please check your network condition and try again.
It's available https://www.npmjs.com/package/core-js-pure
