### ISSUE TITLE
vue-cli安装时为报错,但是执行vue -V失败

### ISSUE THREAD

**Issue by muzishuiji** [vuejs/vue-cli#666]
node版本8.8.0    npm版本4.5.2
全局安装vue-cli 的信息

**C:\Users\25109\AppData\Roaming\npm\vue-init -> C:\Users\25109\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-init
C:\Users\25109\AppData\Roaming\npm\vue-list -> C:\Users\25109\AppData\Roaming\npm\node_modules\vue-cli\bin\vue-list
C:\Users\25109\AppData\Roaming\npm\vue -> C:\Users\25109\AppData\Roaming\npm\node_modules\vue-cli\bin\vue
+ vue-cli@2.9.2
updated 1 package in 38.625s**

执行vue -V时候的报错信息

**vue : 无法将“vue”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路
径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ vue -V
+ ~~~
    + CategoryInfo          : ObjectNotFound: (vue:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException**

没找到是什么原因,求解救.

**Comment by muzishuiji** [comment]
some changes

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You need to setup windows to make clis (pretty much any other) work correctly. It's about configuring the PATH env variable. But, don't worry, a lot of people have solved similar issues already, so it's fairly easy to find help 🙂
