### ISSUE TITLE
Improve docs about VUE_APP_

### ISSUE THREAD

**Issue by darius-v** [vuejs/vue-cli#6676]
### Version
5.0.0-beta.3

### Reproduction link
[cli.vuejs.org](https://cli.vuejs.org/guide/mode-and-env.html#environment-variables)

### Environment info
```
Environment Info:

  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 9.11.2 - ~/.nvm/versions/node/v9.11.2/bin/node
    Yarn: 1.22.11 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v9.11.2/bin/npm
  Browsers:
    Chrome: 91.0.4472.164
    Firefox: 90.0
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.6 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.13 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.13 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-router:  4.5.13 
    @vue/cli-plugin-vuex:  4.5.13 
    @vue/cli-service: ~4.5.0 => 4.5.13 
    @vue/cli-shared-utils:  4.5.13 
    @vue/compiler-core:  3.2.6 
    @vue/compiler-dom:  3.2.6 
    @vue/compiler-sfc: ^3.0.0 => 3.2.6 
    @vue/compiler-ssr:  3.2.6 
    @vue/component-compiler-utils:  3.2.2 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/reactivity:  3.2.6 
    @vue/ref-transform:  3.2.6 
    @vue/runtime-core:  3.2.6 
    @vue/runtime-dom:  3.2.6 
    @vue/shared:  3.2.6 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^7.0.0 => 7.16.0 
    vue: ^3.0.0 => 3.2.6 
    vue-eslint-parser:  7.10.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.8 (16.5.0)
    vue-style-loader:  4.1.3 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 4.5.13
```

### Steps to reproduce
Read the doc https://cli.vuejs.org/guide/mode-and-env.html#environment-variables

### What is expected?
It is not clearly written that variables need to start with VUE_APP_ , otherwise they are not visible

### What is actually happening?
When not starting with VUE_APP_ - they are not visible.

---
I just copy chat, as we discussed:

Hello, how can I set some configuration for vue project? I think I need .env file . Trying it but no luck so far
https://cli.vuejs.org/guide/mode-and-env.html#example-staging-mode
I have created .env file with such content:

# vue application config

API_BASE_URL=localhost:8000
executed
npx vue-cli-service build --mode development
and in main.js trying to get var from .env
import { createApp } from 'vue'
import App from './App.vue'

import 'primevue/resources/themes/saga-blue/theme.css'
import 'primevue/resources/primevue.min.css'                 // core css
import 'primeicons/primeicons.css'

import PrimeVue from 'primevue/config';

const app = createApp(App)

app.config.globalProperties.apiBaseUrl = 'localhost'

app.mount('#app')

console.log(process.env.API_BASE_URL)

app.use(PrimeVue);
but it gives undefined
how can I get value from .env?

........

thats weird - if I add variable like this, it works console.log(process.env.VUE_APP_TITLE)
ok, so problem solved, I can add those prefixes

jacek — Today at 11:27 AM
it's stated in docs that you need VUE_APP_ prefix
Darius — Today at 11:36 AM
I do not see
jacek — Today at 11:40 AM
https://cli.vuejs.org/guide/mode-and-env.html#environment-variables

I have read this part but did not see statment that I need or synonim of "need" to use VUEAPP prefix. Can you show me exact sentence?
I see this tip:

You can have computed env vars in your vue.config.js file. They still need to be prefixed with VUEAPP. This is useful for version info

but here I assume this is for vars in vue.config.js
maybe because of word still I had to assume I needed this prefix in .env
but if thats the case, it could state it in more clear way
jacek — Today at 12:37 PM
i guess this Note that only NODE_ENV, BASE_URL, and variables that start with VUE_APP_ will be statically embedded into the client bundle with webpack.DefinePlugin
Darius — Today at 12:41 PM
"into the client bundle with webpack.DefinePlugin." - I thought I am not using webpack, so this does not matter to me
jacek — Today at 12:41 PM
you are (implicitely), vue cli is using it internally
Darius — Today at 12:41 PM
ok, then thats why it was not clear
jacek — Today at 12:42 PM
i agree it's not very clear, you can file an issue/pr in docs repo.

So need to state in more clear way that this prefix is needed, otherwise it will not work.

**Comment by Akryum** [comment]
> Note that only NODE_ENV, BASE_URL, and variables that start with VUE_APP_ will be statically embedded into the client bundle with webpack.DefinePlugin. It is to avoid accidentally exposing a private key on the machine that could have the same name.
