### ISSUE TITLE
Vue Cli 's serve command shows undefined 

### ISSUE THREAD

**Issue by iron-coder12** [vuejs/vue-cli#6678]
### Version
4.5.13

### Environment info
```

 System:
    OS: Linux 4.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64         Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: Not Found
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: 4.5.13
```

### Steps to reproduce
I tried to create a project like we do with create-react-app I used the following command:  vue init webpack-simple new-project
It says i need to install a undefined vue/@undefined package so that's a problem 

If I type vue --version it works but it does not serve or something

### What is expected?
I wanted to make a starter app like in create-react-app

### What is actually happening?
It's not working it says undefined or something full info is in steps to reproduce

**Comment by sodatea** [comment]
Vue CLI is not create-react-app, so don't use it like create-react-app.

Please follow the [documentation](https://cli.vuejs.org/guide/creating-a-project.html):
1. First, install Vue CLI globally: `npm install -g @vue/cli`
2. Then create a project with `vue create hello-world` (*Not `vue init`*)

**Comment by iron-coder12** [comment]
thanks
