### ISSUE TITLE
Proposal: Sync boilerplate file after init. 

### ISSUE THREAD

**Issue by pwang2** [vuejs/vue-cli#668]
Note sure this is the correct place to request feature. 

I have been creating and working with code scaffolding for a while.  I feel it would be a key important thing to keep the good practice going with the version iteration of the templates.  

As a CLI, 
1. we should provide a way to keep the boilerplate helper file untouched and use configuration file to inject the different use case optionally.  In vue cli, we have the config folder, but not all the configuration needs could be satisfied.  
2. we should be able to sync the boilerplate file easily. For now, in my own project, I am using following shell script file to keep me up to date with the vuejs-template/webpack.
```sh
#!/usr/bin/env bash

TMP=$(mktemp -d)
NAME=vue-template
TEMPLATE_DIR=$TMP/$NAME

(cd $TMP && vue init webpack $NAME)
clear

cd $(dirname $(npm root))
build=$(diff -Nr build/ $TEMPLATE_DIR/build)
config=$(diff -Nr config/ $TEMPLATE_DIR/config)
unit=$(diff -Nr --exclude=specs test/unit  $TEMPLATE_DIR/test/unit)
e2e=$(diff -Nr --exclude=specs --exclude=html-reporter.*  test/e2e $TEMPLATE_DIR/test/e2e)

echo -e "$build\n$config\n$unit\n$e2e"  | vi -d -u NONE -c 'syntax on' -
```
3. Also, as a community member, we should work on one place to iron out the requirement of the template and keep it evolving.  But all good things should happen in one place in a collaborative manner.  

I would like to hear other folks think about this.

**Comment by LinusBorg** [comment]
Please see #589 - We won't need that with 3.0, and won't invest resources to add something like you propose for the time until 3.0 is released.

**Comment by pwang2** [comment]
#589 is exactly the problem I want to address.   Do you have any branch/PR regarding the work being made?
