### ISSUE TITLE
Too many vulnerabilities on fresh vue project

### ISSUE THREAD

**Issue by JoaoHamerski** [vuejs/vue-cli#6686]
### Version
4.5.13

### Environment info
```
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 7.23.0 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 91.0.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.7 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.13 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.13 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-router: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.13 
    @vue/cli-service: ~4.5.0 => 4.5.13 
    @vue/cli-shared-utils:  4.5.13 
    @vue/component-compiler-utils:  3.2.2 
    @vue/eslint-config-standard: ^5.1.2 => 5.1.2 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.14 
    vue-eslint-parser:  7.11.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.8 (16.5.0)
    vue-router: ^3.2.0 => 3.5.2 
    vue-style-loader:  4.1.3 
    vue-template-compiler: ^2.6.11 => 2.6.14 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.4.0 => 3.6.2 
  npmGlobalPackages:
    @vue/cli: Not Found


```

### Steps to reproduce
Create a new project with `vue create project-name`
- Select "Manullay select features"

```
 ◉ Choose Vue version

 ◉ Babel

 ◯ TypeScript

 ◯ Progressive Web App (PWA) Support

 ◉ Router

 ◉ Vuex

 ◉   CSS Pre-processors

 ◉ Linter / Formatter

 ◯ Unit Testing

 ◯ E2E Testing
```

[ENTER]

```
❯ 2.x 

  3.x 
```

[ENTER]

```
? Use history mode for router? (Requires proper server setup for index fallback in production) (Y/n)  n
```

[ENTER]

```
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): 


  Sass/SCSS (with dart-sass) 

❯ Sass/SCSS (with node-sass) 

  Less 

  Stylus 
```

[ENTER]

```
? Pick a linter / formatter config: 


  ESLint with error prevention only 

  ESLint + Airbnb config 

❯ ESLint + Standard config 

  ESLint + Prettier 
```

[ENTER]

```
? Pick additional lint features: (Press \<space> to select, \<a> to toggle all, \<i> to invert selection)

❯◉ Lint on save

 ◯ Lint and fix on commit
```

[ENTER]

```
? Where do you prefer placing config for Babel, ESLint, etc.? (Use arrow keys)

❯ In dedicated config files 

  In package.json
```

[ENTER]

At the end the result is:

### What is expected?
Maybe less vulnerabilities?

### What is actually happening?
To many deprecated dependencies

**Comment by JoaoHamerski** [comment]
> From my understanding, the fact is that these vulnerabilities don't really affect our business projects
> 
> In addition, the maintainers are actively working on these
> 
> * [Upgrade webpack-dev-server to resolve security vulnerability #6690](https://github.com/vuejs/vue-cli/issues/6690)

I hope you're right, because the more dependencies i add more warnings i get because the deprecated ones.

**Comment by himynameisubik** [comment]
Just even installing Vue CLI with
`npm install -g @vue/cli `

Ends up with: 23 vulnerabilities (4 moderate, 19 high)

**Comment by MentalGear** [comment]
> Just even installing Vue CLI with `npm install -g @vue/cli `
> 
> Ends up with: 23 vulnerabilities (4 moderate, 19 high)

After just installing cli globally, it's
`
15 vulnerabilities (8 moderate, 7 high)
`

**Comment by lbineau** [comment]
Same here, I believe these are not "real" vulnerabilities. But still doesn't get well along security reports and log files...

**Comment by sfwhite** [comment]
This needs attention. We're looking at potentially adopting Vue for some of our projects, but security will not approve with this many vulnerabilities on a clean install. All attempts to rectify the dev dependency issues manually have resulted in even more errors. Please do a clean sweep of your official packages and clear your audits.

**Comment by Akryum** [comment]
> We're looking at potentially adopting Vue for some of our projects, but security will not approve with this many vulnerabilities on a clean install.

This is very dumb. [npm audit is broken by design](https://overreacted.io/npm-audit-broken-by-design/) and is just [useless noise](https://twitter.com/devongovett/status/1479884165118054401). Spending so much time on this non-issue is just wasting everybody's time (especially maintainers).
