### ISSUE TITLE
Load vue-cli plugins from the third-party package

### ISSUE THREAD

**Issue by zdm** [vuejs/vue-cli#6687]
### What problem does this feature solve?
I have the package, that contains standard configuration and peer dependencies for all my vue projects.
It also contains `vue-cli` plugins as peer dependencies.
I want to load `vue-cli` plugins from this package `package.json`, not from the main project. This will be very handy, because I will need to maintain and manage dependencies from one place.
But currently this is impossible, because `vue-cli-service` can load plugins only from the main project `package.json`.

### What does the proposed API look like?
Is it possible to add possibility to load plugins from the package, defined in the `vue.config.js`. For example:

`vue.config.js`
```js
{
	loadPluginsFrom: "@softvisio/vue",
}
```

**Comment by zdm** [comment]
does anybody at home?

**Comment by Dygerydoo** [comment]
I think this should do the trick, put this in your package.json

```
"vuePlugins": {
    "resolveFrom": "./node_modules/yourmainpackage"
},
```

**Comment by zdm** [comment]
This is not a portable way.
Path to the package may be differ, depends on other dependencies.
