### ISSUE TITLE
How to use topLevelAwait?

### ISSUE THREAD

**Issue by reactleaner** [vuejs/vue-cli#6697]
### Version
5.0.0-beta.4

### Reproduction link
[github.com](https://github.com/vuejs/vue-cli/issues?page=3&q=is%3Aissue+is%3Aopen)

### Environment info
```
Nodejs v14.17.8
```

### Steps to reproduce
null

### What is expected?
use topLevelAwait

### What is actually happening?
I do not how to use topLevelAwait in vue.config.js

**Comment by reactleaner** [comment]
![image](https://user-images.githubusercontent.com/89075874/133635158-4a5fcdef-e02c-42f8-b4f7-a682150c02cd.png)

**Comment by sodatea** [comment]
Put them inside `configureWebpack`: https://next.cli.vuejs.org/config/#configurewebpack

**Comment by reactleaner** [comment]
![image](https://user-images.githubusercontent.com/89075874/133642153-b499ced9-be38-4b12-9240-1dd062197ff2.png)
I'm sorry. I still don't know how to write it. Can you tell me?

**Comment by sodatea** [comment]
```js
module.exports = {
  // ...
  configureWebpack: {
    experiments: {
      // ...
   }
}
```

Like this

**Comment by reactleaner** [comment]
Thanks! It is resolve！
