### ISSUE TITLE
如何在项目中添加eslint+prettier

### ISSUE THREAD

**Issue by zhoufanglu** [vuejs/vue-cli#6698]
### Version
4.5.0

### Reproduction link
[github.com](https://github.com/zhoufanglu/vue-temp-2021-3-8)

### Environment info
```
chrome ,webstorm
```

### Steps to reproduce
我新建项目的时候没有选择estlint+prettier, 现在项目开发到一半，想加上， 请问有比较好的方法或者文章推荐吗？ 网上的文章太乱了。

### What is expected?
eslint+prettier生效

### What is actually happening?
eslint+prettier未选择

**Comment by fangbinwei** [comment]
可以看下[eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier), 提问性质建议在[discussion](https://github.com/vuejs/vue-cli/discussions)中讨论

**Comment by zhoufanglu** [comment]
> 可以看下[eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier), 提问性质建议在[discussion](https://github.com/vuejs/vue-cli/discussions)中讨论

好的 谢谢你的回答 我去研究下
