### ISSUE TITLE
can't use scss in vuetify

### ISSUE THREAD

**Issue by arawwad** [vuejs/vue-cli#670]
so I am trying to write scss in the style tag of a vue component. I am trying  `<style lang="scss">` but I get an error when compiling 

`This dependency was not found:`
`* !!vue-style-loader!css-loader?{"sourceMap":false}!../node_modules/vue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-04c2046b","scoped":false,"hasInlineConfig":false}!sass-loader?{"sourceMap":false}!../node_modules/vu
e-loader/lib/selector?type=styles&index=0&bustCache!./App.vue in ./src/App.vue
`
I am doing something wrong here or missing something

**Comment by LinusBorg** [comment]
I don't see what that has to do with vue-cli but:

...you probably just have to install the necessary dependencies:
```
npm install -D node-sass sass-loader
```

**Comment by nmarshall23** [comment]
This should be part of the starting doc's so it's easy for new users to find.

**Comment by LinusBorg** [comment]
It is part of the docs of the webpack template.
