### ISSUE TITLE
Pre-processors - SASS

### ISSUE THREAD

**Issue by RoosDev** [vuejs/vue-cli#6717]
### Version
4.5.13

### Reproduction link
[github.com](https://github.com/RoosDev/TonyBrondel_7_27042021)

### Environment info
```
  System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (94.0.992.31)
  npmPackages:
    vue: ^2.6.14 => 2.6.14
  npmGlobalPackages:
    @vue/cli: Not Found

```

### Steps to reproduce
run :      vue create frontend

I tried to create a new project but it's not working. So I uninstall and reinstall vue @cli  but still the same. 
The difference between today and last week on my environment: I installed MySQL on my computer, that's all 

### What is expected?
a new project

### What is actually happening?
Vue CLI v4.5.13
? Please pick a preset: Manually select features
? Check the features needed for your project: Choose Vue version, Babel, TS, PWA, Router, Vuex, CSS Pre-processors, Linter
? Choose a version of Vue.js that you want to start the project with 3.x
? Use class-style component syntax? Yes
? Use Babel alongside TypeScript (required for modern mode, auto-detected polyfills, transpiling JSX)? Yes
? Use history mode for router? (Requires proper server setup for index fallback in production) Yes
? Pick a CSS pre-processor (PostCSS, Autoprefixer and CSS Modules are supported by default): Sass/SCSS (with node-sass)
? Pick a linter / formatter config: Basic
? Pick additional lint features: Lint on save
? Where do you prefer placing config for Babel, ESLint, etc.? In dedicated config files
? Save this as a preset for future projects? No

Vue CLI v4.5.13
✨  Creating project in C:.........\www\frontend.
⚙️  Installing CLI plugins. This might take a while...

added 1373 packages, and audited 1374 packages in 46s

86 packages are looking for funding
  run `npm fund` for details

12 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
🚀  Invoking generators...
📦  Installing additional dependencies...

npm ERR! code 1
npm ERR! path C:.........\www\frontend\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:.........\www\frontend\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:............\\www\\frontend\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.9.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:.........\www\frontend\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:.........\www\frontend\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:.........\www\frontend\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:.........\www\frontend\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:.........\www\frontend\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:.........\www\frontend\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:.........\www\frontend\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:.........\www\frontend\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:.........\www\frontend\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:.........\www\frontend\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:.........\www\frontend\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:.........\www\frontend\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python39\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:.........\www\\frontend\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:.........\www\frontend\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.9.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:.........\AppData\Local\npm-cache\_logs\2021-10-01T15_03_31_207Z-debug.log
 ERROR  command failed: npm install --loglevel error --legacy-peer-deps

---
the install works if I don't install pre-processors (but I need it)
the github link have no many things on it

**Comment by LinusBorg** [comment]
It seems node-sass doesn't install on your system. have you tried the dart-sass option instead? It's the preferred and faster option anyway.

**Comment by RoosDev** [comment]
It's perfect !! You're my hero !!
So now I know that I'm dumb but, I don't understand why it was working on last week !! ;)
