### ISSUE TITLE
 transpileDependencies failure？ Unable to compile element-ui.vue file JSX

### ISSUE THREAD

**Issue by jxZhangLi** [vuejs/vue-cli#6720]
### Version
4.5.13

### Environment info
```
  System:
    OS: macOS 11.5.2
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.19.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 94.0.4606.61
    Edge: Not Found
    Firefox: Not Found
    Safari: 14.1.2
  npmPackages:
    @vue/babel-helper-vue-jsx-merge-props: ^1.2.1 => 1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.7 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.13 
    @vue/babel-preset-jsx: ^1.2.4 => 1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.13 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-router: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-vuex: ~4.5.0 => 4.5.13 
    @vue/cli-service: ~4.5.0 => 4.5.13 
    @vue/cli-shared-utils:  4.5.13 
    @vue/component-compiler-utils:  3.2.2 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.3.0 
    babel-helper-vue-jsx-merge-props: ^2.0.3 => 2.0.3 
    babel-plugin-transform-vue-jsx: ^4.0.1 => 4.0.1 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    vue: ^2.6.11 => 2.6.14 
    vue-eslint-parser:  7.11.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.8 (16.8.1)
    vue-router: ^3.2.0 => 3.5.2 
    vue-style-loader:  4.1.3 
    vue-template-compiler: ^2.6.11 => 2.6.14 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.4.0 => 3.6.2 
  npmGlobalPackages:
    @vue/cli: 4.5.13
```

### Steps to reproduce

1.node_modules>element-ui>package.json
Modify the configuration："main": "lib/element-ui.common.js", =>  "main": "src/index.js",
2.vue.config.js 
transpileDependencies: [
        'element-ui'
    ],
3. npm run serve

### What is expected?
success to compile.

### What is actually happening?
Failed to compile.

./node_modules/element-ui/packages/avatar/src/main.vue?vue&type=script&lang=js& (./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/element-ui/packages/avatar/src/main.vue?vue&type=script&lang=js&)
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/zhangli/Desktop/vue-performance/node_modules/element-ui/packages/avatar/src/main.vue: Support for the experimental syntax 'jsx' isn't currently enabled (72:16):

  70 |
  71 |       if (isImageExist && src) {
> 72 |         return <img
     |                ^
  73 |           src={src}
  74 |           onError={this.handleError}
  75 |           alt={alt}

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.

---

**Comment by screetBloom** [comment]
You should provide a reproduction so that we can also help you

**Comment by AzronChan** [comment]
@proc07 请问大佬是怎么解决的？
