### ISSUE TITLE
Can not open multi pages at the same time, is there a limit?

### ISSUE THREAD

**Issue by weiweiwei256** [vuejs/vue-cli#676]
For example,  I created file named "demo.vue"  and added it into "router.js".   And, I open "http://localhost:8080/#/demo" many times.   The first six times is successful to loading the page. Then, this 
page can't load more.  Other page can't load,too.   
PS:If you close one that loaded successfully, those pages that waiting to be loaded can  load successful.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
