### ISSUE TITLE
npm run dev cause error, the log as follow

### ISSUE THREAD

**Issue by caoxiaoshuai1** [vuejs/vue-cli#677]
0 info it worked if it ends with ok
1 verbose cli [ '/Users/xiaoshuaicao/.nvm/versions/node/v9.0.0/bin/node',
1 verbose cli   '/Users/xiaoshuaicao/.nvm/versions/node/v9.0.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v9.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle querymarking@1.0.0~prestart: querymarking@1.0.0
6 info lifecycle querymarking@1.0.0~start: querymarking@1.0.0
7 verbose lifecycle querymarking@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle querymarking@1.0.0~start: PATH: /Users/xiaoshuaicao/.nvm/versions/node/v9.0.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/xiaoshuaicao/Desktop/querymarking/node_modules/.bin:/Users/xiaoshuaicao/.nvm/versions/node/v9.0.0/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/mysql/bin
9 verbose lifecycle querymarking@1.0.0~start: CWD: /Users/xiaoshuaicao/Desktop/querymarking
10 silly lifecycle querymarking@1.0.0~start: Args: [ '-c', 'npm run dev' ]
11 silly lifecycle querymarking@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle querymarking@1.0.0~start: Failed to exec start script
13 verbose stack Error: querymarking@1.0.0 start: `npm run dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/xiaoshuaicao/.nvm/versions/node/v9.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:135:13)
13 verbose stack     at EventEmitter.emit (events.js:224:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/xiaoshuaicao/.nvm/versions/node/v9.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:135:13)
13 verbose stack     at ChildProcess.emit (events.js:224:7)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid querymarking@1.0.0
15 verbose cwd /Users/xiaoshuaicao/Desktop/querymarking
16 verbose Darwin 16.7.0
17 verbose argv "/Users/xiaoshuaicao/.nvm/versions/node/v9.0.0/bin/node" "/Users/xiaoshuaicao/.nvm/versions/node/v9.0.0/bin/npm" "start"
18 verbose node v9.0.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error querymarking@1.0.0 start: `npm run dev`
22 error Exit status 1
23 error Failed at the querymarking@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Bimgle** [comment]
解决好了？我也遇到了这个问题
