### ISSUE TITLE
Why the new version of the CLI generated template does not support LAN IP access!

### ISSUE THREAD

**Issue by nailao** [vuejs/vue-cli#678]
Why the new version of the CLI generated template does not support LAN IP access!
For example: 192.168.1.2:8080

**Comment by nailao** [comment]
./config/index.js
module.exports.dev.host = '0.0.0.0'

**Comment by posva** [comment]
Using `module.exports.dev.host = '0.0.0.0'` works perfectly fin (in webpack template)
In any case, this is something related to webpack not vue-cli nor its templates
