### ISSUE TITLE
Why is the devServer attribute in the configuration file of the Chinese document vue incomplete

### ISSUE THREAD

**Issue by WorldToCode** [vuejs/vue-cli#6799]
### What problem does this feature solve?
For example, open the browser properties open, etc., which are not stated and detailed.Hope to complete the document

### What does the proposed API look like?
Not an api

**Comment by screetBloom** [comment]
[vue.config.js   devserver](https://cli.vuejs.org/zh/config/#devserver)

From my point of view, the documentation is  clear


The parameters here are passed directly, you can't ask it to list all the params here, there will be the problem of untimely update


![image](https://user-images.githubusercontent.com/22092110/139624999-fe73190b-0a40-4c1d-9e90-484a47f8f7f8.png)

**Comment by WorldToCode** [comment]
I didn't pay attention, sorry haha
