### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by codewithpom** [vuejs/vue-cli#6816]
### What problem does this feature solve?
So as if you go to the website of babel-eslint you will see that is it is now deprecated and is now @babel/eslint-parser so I think we should change the package.json for it.

### What does the proposed API look like?
No problem about removing it.

**Comment by LinusBorg** [comment]
Vue CLI (`@vue/cli-plugin-eslint`) has already been using that package since around 9 months.

https://github.com/vuejs/vue-cli/blob/60140af5ba029e30d433ebf5afd442f754ee87e5/packages/%40vue/cli-plugin-eslint/eslintDeps.js#L39

**Comment by codewithpom** [comment]
Ok Thanks
