### ISSUE TITLE
the sass-loader has failed when i use @import '~normalize.css/normalize.css'

### ISSUE THREAD

**Issue by Benzenes** [vuejs/vue-cli#682]
The terminal info like '
 Module build failed: Error: Failed to find '~normalize.css/normalize.css'
  in [
    D:\work\vue-layui\src\components
  ]
'
the vue-loader didn't load the file from node_modules,it's from 'src'.
when i use the relative path @import '../node_modules/normalize.css/normalize.css' it's normal!

node v8.9.3
vue-cli v2.9.2
windows 10

**Comment by crossgit** [comment]
@Benzenes  How do you deal with this problem, please?

**Comment by slipkinem** [comment]
@Benzenes  Are you deal?

**Comment by Benzenes** [comment]
I'm so sorry!!!   This problem was solved after I omitted the suffix '.css';;
like this @import '~normalize.css/normalize'
