### ISSUE TITLE
vue.config.js 配置 css.requireModuleExtension 报错

### ISSUE THREAD

**Issue by jiefei666** [vuejs/vue-cli#6822]
### Version
5.0.0-rc.0

### Reproduction link
[github.com](https://github.com/jiefei666/vue3-cli5.0.0-rc.0-demo/blob/main/vue.config.js)

### Environment info
```
..
```

### Steps to reproduce
npm run serve

### What is expected?
..

### What is actually happening?
 ERROR  Invalid options in vue.config.js: "css.requireModuleExtension" is not allowed

---
..

**Comment by zch233** [comment]
Invalid options in vue.config.js: "css.requireModuleExtension" is not allowed

**Comment by zch233** [comment]
Both removed in v5, see [Working with CSS > CSS Modules](https://next.cli.vuejs.org/guide/css.html#css-modules) for guidance on how to treat all style imports as CSS Modules.
