### ISSUE TITLE
新版vue-cli创建项目，不能外部打开项目运行地址问题

### ISSUE THREAD

**Issue by FirstAurora183** [vuejs/vue-cli#683]
emmmm  
之前版本的vue-cli创建项目时带着express这些东西，运行`npm run dev`之后的`http://localhost:8080/#/`地址修改成 例如:`http://192.168.1.111:8080/#/`(电脑本机ip)，这个192的地址直接copy到qq里面，然后手机qq(包括其他浏览器)点击这个地址就能直接通过局域网访问到这个项目。包括使用HBuilder、APIcloud手机调试工具直接外链这个192地址就能在手机(包括模拟器)查看项目。  
我主要目的是想使用vue全家桶将项目打包成web app，然后通过使用HBuilder、cordova等工具打包成app，现在手机点连接提示找不到网页。  
新版vue-cli不能除浏览器之外打开项目运行连接，请问有没有解决办法。_(:з」∠)_

**Comment by Yakima-Teng** [comment]
这个貌似跟vue-cli并没有关系吧，是不是你自己电脑本机IP变了。。

**Comment by FirstAurora183** [comment]
不是，之前创建的项目现在还能这么玩，新创建的项目不行了

**Comment by weineel** [comment]
新版用了[webpack-dev-server](https://github.com/webpack/webpack-dev-server)
需要在启动的命令行加上 `--host 0.0.0.0` 这样就能允许远程任意ip访问里。

![image](https://user-images.githubusercontent.com/13328625/34028527-b79dcfee-e19e-11e7-8bbf-9988d84f1455.png)

**Comment by FirstAurora183** [comment]
ok 学习了，O(∩_∩)O谢谢

**Comment by hellowqw** [comment]
这样改完之后如果开启`autoOpenBrowser: true` 会自动打开浏览器访问http://0.0.0.0:8080  无法访问

**Comment by wangxiangyao** [comment]
0.0.0.0治标不治本啊兄弟
