### ISSUE TITLE
Where did the [if IE] tag come from

### ISSUE THREAD

**Issue by LonHon** [vuejs/vue-cli#6835]
### Version
4.5.9

### Reproduction link
[None](none)

### Environment info
```
vue@2.6
```

### Steps to reproduce
原始index.html
![image](https://user-images.githubusercontent.com/19330620/141712793-7076fee9-cec6-4487-8a5d-91f520718653.png)

### What is expected?
能显示上面指定的favicon图标

### What is actually happening?
打包之后，得到了如下文件

指定的icon被注释掉了，还有[if IE]标签，另外后面还被注入了2个其它icon，我翻了下vue-cli的文档  没有找到相关的描述

导致无法正常显示网站图标

![image](https://user-images.githubusercontent.com/19330620/141713587-d2b5c24f-b7f1-4e9a-a965-30bf4272d2ad.png)

**Comment by fangbinwei** [comment]
这个和`@vue/cli-plugin-pwa`相关

**Comment by LonHon** [comment]
> 这个和`@vue/cli-plugin-pwa`相关

感谢  找到了

https://cli.vuejs.org/core-plugins/pwa.html#configuration

![image](https://user-images.githubusercontent.com/19330620/141752405-ee48bf02-f0d2-42b8-953e-9b747108fc4a.png)

**Comment by caiqichang** [comment]
@LonHon  请问如何解决
