### ISSUE TITLE
When choosing yarn, should show yarn command

### ISSUE THREAD

**Issue by Narven** [vuejs/vue-cli#684]
When running a `vue init webpack <project-name>` If you choose `YARN` has a package manager it should show the commands from yarn... not npm.

<img width="656" alt="screenshot 2017-12-15 12 34 27" src="https://user-images.githubusercontent.com/123594/34042485-d95d07da-e194-11e7-9632-4aed2aafa7d1.png">

should be `yarn install`

<img width="512" alt="screenshot 2017-12-15 12 34 49" src="https://user-images.githubusercontent.com/123594/34042522-07f52e2e-e195-11e7-9624-968300a83e5e.png">

should be `yarn run dev`

**Comment by posva** [comment]
At the end it doesn't really matter but this is something that has to be dealt in the template, not in cli. Feel free to submit a PR there 🙂
