### ISSUE TITLE
version 2.9.2 vue-cli can not load local json data

### ISSUE THREAD

**Issue by wanglch1213** [vuejs/vue-cli#685]
const express = require('express');
const app = express();
var appData = require('../data.json');
var seller = appData.seller;
var goods = appData.goods;
var ratings = appData.ratings;
var apiRoutes = express.Router();
app.use('/api',apiRoutes);

devServer:{
before(app) {
  app.get('/api/seller', (req, res) => {
    res.json({
      // 这里是你的json内容
      errno: 0,
      data: seller
    })
  })
}
......
}

localhost:8080/api/seller，result 200 status code, not result json data, why?
please help me

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

**Comment by dannyk08** [comment]
for those looking for an answer, I solved this by placing my .json file in the public folder

so to fetch i.e `fetch('/products.json')` the file should be in `public/products.json`
