### ISSUE TITLE
Remove Console.log and warnings from production

### ISSUE THREAD

**Issue by AhadCove** [vuejs/vue-cli#686]
I'm trying to build for production and it works, but i'm still seeing all my warnings, console logs, etc.
How do I remove this? i'm using vue-cli
And this is the command i'm using
node build/build.js --prod
in my webpack.prod.config.js I have this line which I would assume would take care of all the messages:
```
 new HtmlWebpackPlugin({
      filename: config.build.index,
      template: 'index.html',
      inject: true,
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeAttributeQuotes: true
      },
      // necessary to consistently work with multiple chunks via CommonsChunkPlugin
      chunksSortMode: 'dependency'
    }),
```
But, it isn't

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

in the webpack template, any code surrounded by `if (process.env.NODE_ENV === 'development')` is removed in production mode
