### ISSUE TITLE
依赖包terser-webpack-plugin版本过低导致编译代码错误

### ISSUE THREAD

**Issue by swatch17** [vuejs/vue-cli#6862]
### Version
4.5.5

### Reproduction link
[github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Environment info
```
npm run serve
```

### Steps to reproduce
npm run build

### What is expected?
解决问题

### What is actually happening?
npm run build

---
该版本依赖的terser-webpack-plugin版本是1.4.4，如果升级到4.2.3版本就成功了

**Comment by sodatea** [comment]
请升级到 v5.0.0-rc.1
terser plugin 的大版本升级是破坏性变更，没法在 4.x 里做
