### ISSUE TITLE
new install with 7 HIGH vulnerabilities

### ISSUE THREAD

**Issue by greenpdx** [vuejs/vue-cli#6868]
### Version
4.5.15

### Environment info
```
Ubuntu 21.10 nodejs 16.13.1 npm 8.3.0
changed 952 packages, and audited 953 packages in 7s

67 packages are looking for funding
  run `npm fund` for details

11 vulnerabilities (4 moderate, 7 high)

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

  System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.13.1 - /usr/bin/node
    Yarn: Not Found
    npm: 8.3.0 - /usr/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: 4.5.15



```

### Steps to reproduce
new ubuntu 21.10 install
install nodejs 16 using package manager
sudo npm install -g @vue/cli

### What is expected?
no vulnerabilities

### What is actually happening?
changed 952 packages, and audited 953 packages in 7s

67 packages are looking for funding
  run `npm fund` for details

11 vulnerabilities (4 moderate, 7 high)

Some issues need review, and may require choosing
a different dependency.

**Comment by LuisMiguelFilipe** [comment]
You may check which vulnerabilities impact packages in production and which ones only have development packages.

Anyway, In our project we upgraded to 5.0.0-rc.1 and this was one of the main factors.

**Comment by alexey-sh** [comment]
>Anyway, In our project we upgraded to 5.0.0-rc.1 and this was one of the main factors.

It doesn't help with `cli-service`

```
npm list ansi-regex     
─┬ @vue/cli-service@5.0.0-rc.1
│ ├─┬ progress-webpack-plugin@1.0.12
│ │ └─┬ log-update@2.3.0
│ │   └─┬ wrap-ansi@3.0.1
│ │     └─┬ strip-ansi@4.0.0
│ │       └── ansi-regex@3.0.0
```

**Comment by haoqunjiang** [comment]
The vulnerabilities are gone in the latest versions.
