### ISSUE TITLE
在gitbash 和 windows自带的命令行执行 vue init webpack  vue-demo需优化

### ISSUE THREAD

**Issue by wenhandi** [vuejs/vue-cli#687]
在gitbash 和 windows自带的命令行执行 vue init webpack  vue-demo，Vue build和Pick an ESLint preset时选择不准确，例如我想选Airbnb实际结果却无意中选了其他。

**Comment by hxl-dy** [comment]
It's nothing to do with vue-cli. Maybe you should pose this question on [SO](https://stackoverflow.com/).

**Comment by posva** [comment]
Are you saying that picking airbnb in eslint config still yields another preset?

**Comment by wenhandi** [comment]
@posva yes, windows7 with DOS CLI has problem abount "vue build"，gitbash has more problems during "vue init webpack vue-demo"
