### ISSUE TITLE
How do I remove yarn and return to npm?

### ISSUE THREAD

**Issue by pefka** [vuejs/vue-cli#6881]
### Version
4.5.13

### Environment info
```
mac os
```

### Steps to reproduce
Installed a new project via vue-cli 4, instead of using npm, yarn automatically supplied me. I don't like yarn. How do I switch back to npm?

this in package.json:     "serve": "vue-cli-service serve"
automatically starts always yarn

### What is expected?
npm instead yarn

### What is actually happening?
low performance due yarn

**Comment by pefka** [comment]
in fact "npm run serve" launches **vue-cli-service serve** and this **vue-cli-service serve** launches yarn
so it is not a solution

**Comment by pefka** [comment]
I am not interested in this question anymore. I removed this "great" vue-cli with **743 issues**. It's somehow easier without it. Thanks of course to the developers, but now it's a piece of shit, not good software.

**Comment by tony19** [comment]
What makes you think `vue-cli-service serve` launches yarn?
