### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'transformFile')     at C:\Users\v6pipvc\Downloads\exbot-mobile-app-master\node_modules\metro\src\Bundler.js:95:34     at Generator.next (<anonymous>)     at asyncGeneratorStep (C:\Users\v6pipvc\Downloads\exbot-mobile-app-master\node_modules\metro\src\Bundler.js:14:24)     at _next (C:\Users\v6pipvc\Downloads\exbot-mobile-app-master\node_modules\metro\src\Bundler.js:36:9)     at processTicksAndRejections (node:internal/process/task_queues:96:5)

### ISSUE THREAD

**Issue by shrutitambade** [vuejs/vue-cli#6889]
### Version
5.0.0-rc.1

### Environment info
```
node js : v10.13.0
npm : 6.4.1
java : openjdk version "1.8.0_181-1-redhat"
windows 10 64 bit
```

### Steps to reproduce
react-native run-android 

### What is expected?
App should be run on device

### What is actually happening?
TypeError: Cannot read properties of undefined (reading 'transformFile')     at C:\Users\v6pipvc\Downloads\exbot-mobile-app-master\node_modules\metro\src\Bundler.js:95:34     at Generator.next (<anonymous>)     at asyncGeneratorStep (C:\Users\v6pipvc\Downloads\exbot-mobile-app-master\node_modules\metro\src\Bundler.js:14:24)     at _next (C:\Users\v6pipvc\Downloads\exbot-mobile-app-master\node_modules\metro\src\Bundler.js:36:9)     at processTicksAndRejections (node:internal/process/task_queues:96:5)

---
App installing in mobile device but getting error TypeError: Cannot read properties of undefined (reading 'transformFile')     at C:\Users\v6pipvc\Downloads\exbot-mobile-app-master\node_modules\metro\src\Bundler.js:95:34     at Generator.next (<anonymous>)     at asyncGeneratorStep (C:\Users\v6pipvc\Downloads\exbot-mobile-app-master\node_modules\metro\src\Bundler.js:14:24)     at _next (C:\Users\v6pipvc\Downloads\exbot-mobile-app-master\node_modules\metro\src\Bundler.js:36:9)     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by sodatea** [comment]
I don't see how it's related to Vue CLI.

Next time, please respect the issue form and include a reproduction link to a minimal full reproduction of your problem (for example in a GitHub repository)
