### ISSUE TITLE
Uncaught SyntaxError: Use of const in strict mode. at http://192.168.1.108:8080/#/:6

### ISSUE THREAD

**Issue by FirstAurora183** [vuejs/vue-cli#689]
node:8.9.0
vue-cli:2.9.2
vue:2.5.2
os:OS X
Android:4.4.4
我设置完 `--host 0.0.0.0`之后使用安卓模拟器(MUMU和其他)的浏览器打开本机项目地址，结果报错`Uncaught SyntaxError: Use of const in strict mode. at http://192.168.1.108:8080/#/:6`,使用安卓真机打开项目地址正常，请问这是什么原因？

I set out the `--host 0.0.0.0` after using the android emulator  browser to open the machine address, the result error ` Uncaught SyntaxError: the Use of const in strict mode. At http://192.168.1.108:8080/#/:6 `, what reason is this excuse me?

**Comment by LinusBorg** [comment]
https://github.com/vuejs-templates/webpack/issues/1140#issuecomment-350920886
