### ISSUE TITLE
npm run on windows is ok , but on linux it report errors, said that my comopents is  not found

### ISSUE THREAD

**Issue by Dowgen** [vuejs/vue-cli#690]
![image](https://user-images.githubusercontent.com/15230192/34296801-57726876-e74f-11e7-9d3f-e19c2533fe79.png)

**Comment by LinusBorg** [comment]
1. Issues should be reported in the template's repository, not the CLI
2. You don't share your code, so how should we know what you did?
3. My guess: file systems on linux are case-sensitive. you likely made a case mistake in the component filename.
