### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by ForeveHG** [vuejs/vue-cli#692]
升级到2.9.2，新建一个项目后直接打包，报了这个错，又试了2.8.2正常
building for production...
return new Error(`${file} from UglifyJs\n${err.message} [${requestShortener.shorten(original.source)}:${original.line},${original.column}][${file}:${err.line},${err.col}]`);
                                                                                      ^
TypeError: requestShortener.shorten is not a function

**Comment by jamchen** [comment]
same here

**Comment by jamchen** [comment]
by workaround UglifyJs' exception I got following error instead

```
ERROR in static/js/app.e3f37e373a7b0be800ee.js from UglifyJs
Unexpected token: keyword (var) [/Users/jamchen/Developer/code/cloud-screen/dev-console/node_modules/vue-loader/lib/template-compiler/index.js?{"id":"data-v-e86976ae","hasScoped":false,"transformToRequire":{"video":["src","poster"],"source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!/Users/jamchen/Developer/code/cloud-screen/dev-console/node_modules/vue-loader/lib/selector.js?type=template&index=0!/Users/jamchen/Developer/code/cloud-screen/dev-console/src/App.vue:4,0][static/js/app.e3f37e373a7b0be800ee.js:42,29]
```

line 42 is 

```
/* harmony default export */ var selectortype_template_index_0_src_App = (esExports);
```

**Comment by An0nymous0** [comment]
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/197

**Comment by LinusBorg** [comment]
https://github.com/vuejs-templates/webpack/issues/1200
