### ISSUE TITLE
`@vue/cli-plugin-typescript` breaks WebStorm 2021.3.1

### ISSUE THREAD

**Issue by yaquawa** [vuejs/vue-cli#6920]
### Version
5.0.0-rc.1

### Environment info
```
macOS
```

### Steps to reproduce
**index.vue**

```vue
<script>
import { ref } from 'vue'
</script>
```

**package.json**
```json
{
  "private": true,
  "dependencies": {
    "vue": "^3.2.21"
  },
  "devDependencies": {
    "@vue/cli-plugin-typescript": "^5.0.0-rc.1"
  }
}
```
### What is expected?
If I have `@vue/cli-plugin-typescript@5.0.0-rc.1` installed, I can't jump into source via "command + click" in `.vue` file with WebStorm. not sure if this is a problem of WebStorm(2021.3.1) or `@vue/cli-plugin-typescript@5.0.0-rc.1`. but, the version 4.x works fine.

**Comment by lookenghua** [comment]
I also have some proble

**Comment by yaquawa** [comment]
this will be fixed in the next version of webstorm.
