### ISSUE TITLE
Can't create Vue project with Node LTS

### ISSUE THREAD

**Issue by leonheess** [vuejs/vue-cli#6929]
### Version
4.5.15

### Environment info
```
System:
    OS: Linux 4.19 Fedora Remix for WSL 31
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 16.13.2 - ~/.volta/tools/image/node/16.13.2/bin/node
    Yarn: 1.22.15 - ~/.volta/bin/yarn
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.2/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmGlobalPackages:
    @vue/cli: 4.5.15
```

### Steps to reproduce
1. Install Node LTS
2. Install @vue/cli
3. Create Vue 3 + TS + Babel + Linters project

### What is expected?
Project is created

### What is actually happening?
`npm ERR! cb.apply is not a function`

**Comment by derekwsgray** [comment]
Same. `npm install` fails at this version of node. The dependency on `fibres` appears to be the problem.
(Was updating an existing project.)

**Comment by xup3** [comment]
Hi @leonheess,

have you tried to clear your npm cache?
I matched your node/npm versions on my MBP and it works as expected.
