### ISSUE TITLE
'Starting Selenium Server...' hangs without error on Ubuntu

### ISSUE THREAD

**Issue by mikatalk** [vuejs/vue-cli#696]
Hi there, I've been running into some problems trying to run Nightwatch/Selenium tests on an an integration server. 

Context:
  - launch Ubuntu 16.04.3 LTS EC2 instance on AWS
  - install node version 8
  - setup vue-cli webpack project `vue init webpack my-project` (with nightwatch)

Expected: 
  Test should spawn chrome driver and selenium driver,
  tests should succeed within a few seconds 

Behavior:
  The log hangs at `Starting selenium server... ` without error or ever timing out.

Note there is a similar open issue on nightwatch project but the solution seems to be the port number which seems fine in my case. Both Chromedriver and selenium process are running.
 
Your help would be much appreciated

**Comment by mjgorman** [comment]
ps aux output:
```ubuntu    9030  0.2  0.9 1048980 39576 pts/1   Sl+  17:44   0:00 npm
ubuntu    9040  0.0  0.0   4516   796 pts/1    S+   17:44   0:00 sh -c node test/e2e/runner.js
ubuntu    9041  6.2  4.4 1343452 178632 pts/1  Sl+  17:44   0:06 node test/e2e/runner.js
ubuntu    9051  0.5  1.1 901452 44764 pts/1    Sl+  17:44   0:00 node ./node_modules/.bin/nightwatch --config test/e2e/nightwatch.conf.js --env chrome
ubuntu    9057  1.0  1.7 3645396 72704 pts/1   Sl+  17:44   0:01 java -Dwebdriver.chrome.driver=/home/ubuntu/mika_tmp/test-project/node_modules/chromedriver/lib/chromedriver/chromedriver -jar /home/ubuntu/mika_tmp/test-project/node_modules/selenium-server/lib/runner/selen
```

netstat ntpl
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      8463/node       
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               
tcp6       0      0 :::4444                 :::*                    LISTEN      8479/java 
```

**Comment by LinusBorg** [comment]
This error is, if at all, related to the template, not the cli.

https://github.com/vuejs-templates/webpack/
