### ISSUE TITLE
"export 'default' was not found in 

### ISSUE THREAD

**Issue by zhoufanglu** [vuejs/vue-cli#6963]
### Version
4.5.6

### Reproduction link
[[new-issue.vuejs.org/](https://new-issue.vuejs.org/?repo=vuejs/vue-cli)](https://github.com/zhoufanglu/vue3-for-issus)

### Environment info
```
"dependencies": {
    "core-js": "^3.6.5",
    "screenfull": "^5.1.0",
    "vue": "^3.0.0",
    "vue-router": "^4.0.11"
  },
  "devDependencies": {
    "@element-plus/icons": "0.0.11",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "axios": "^0.24.0",
    "babel-eslint": "^10.1.0",
    "element-plus": "^1.3.0-beta.5",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0",
    "nprogress": "^0.2.0",
    "pinia": "^2.0.0-rc.10",
    "pinia-plugin-persistedstate": "^1.0.3",
    "postcss-pxtorem": "^5.1.1",
    "qs": "^6.10.1",
    "sass": "^1.46.0",
    "sass-loader": "^10.0.5",
    "unplugin-auto-import": "^0.5.10",
    "unplugin-vue-components": "^0.17.11"
  }
```

### Steps to reproduce
1、npm run build
2、Then report a warning.
"export 'default' was not found in '-!../../../../../node_modules/unplugin/dist/webpack/loaders/transform.js??

### What is expected?
build success

### What is actually happening?
"export 'default' was not found in '-!../../../../../node_modules/unplugin/dist/webpack/loaders/transform.js??
![image](https://user-images.githubusercontent.com/24451091/150738958-0086af70-9507-4caa-9b88-160795d9dbfd.png)

**Comment by sodatea** [comment]
Thanks for submitting this issue! Due to our limited time, we ask you to include a reproduction link to a minimal full reproduction of your problem (for example in a GitHub repository) so we can find what is causing the issue. Thank you for your understanding!

**Comment by zhoufanglu** [comment]
> Thanks for submitting this issue! Due to our limited time, we ask you to include a reproduction link to a minimal full reproduction of your problem (for example in a GitHub repository) so we can find what is causing the issue. Thank you for your understanding!

i update links, [demo](https://github.com/zhoufanglu/vue3-for-issus)

**Comment by zhoufanglu** [comment]
> > Thanks for submitting this issue! Due to our limited time, we ask you to include a reproduction link to a minimal full reproduction of your problem (for example in a GitHub repository) so we can find what is causing the issue. Thank you for your understanding!
> 
> i update links, [demo](https://github.com/zhoufanglu/vue3-for-issus)

Because it is a company project deleted

**Comment by zhoufanglu** [comment]
I found that the warning had something to do with the on-demand introduction of Element
```js
//element-plus 自动引入插件
const AutoImport = require('unplugin-auto-import/webpack')
const Components = require('unplugin-vue-components/webpack')
const { ElementPlusResolver } = require('unplugin-vue-components/resolvers')
```
when i remove `unplugin-auto-import` and `unplugin-vue-components`, build success
