### ISSUE TITLE
Cannot write Mustache syntax in template

### ISSUE THREAD

**Issue by ulivz** [vuejs/vue-cli#698]
**Did the `vue init` command *itself* result in an error?**

- No.

**Actual result:**

- I try to write mustache syntax `{{ ... }}` at my `.vue` component file. the `hbs` render engine will transform it as hbs element. and even if the var is not defined, vue-cli will not throw error:

```vue
{{ a.b }}  <!-- Will be transformed to empty, and doesn't throw error -->
```

**Expected result:**

`vue-cli` should rewrite the transform function to add extra syntax to distinguish `hbs-mustache` token and `vue-mustache` token. And when customized template try to use non-existed variable, `vue-cli` should throw error.

**Comment by LinusBorg** [comment]
We are currently not planning to mess with the handlebars defaults, at least not in the 2.* version of vue-cli. There's alreadya request for this though: https://github.com/vuejs/vue-cli/issues/546

So for now:

1. You can escape those easily:
```html
  <h1>\{{message}}</h1>
```
We do that in our templates as well, [see here](https://github.com/vuejs-templates/webpack/blob/cd4d7d957c9af3d37092c79bf490b56b8d88b108/template/src/components/HelloWorld.vue#L3).

2. You can make the vue-cli skip interpolation for some files in your own templates: https://github.com/vuejs/vue-cli#skip-rendering
