### ISSUE TITLE
vue serve 无反应

### ISSUE THREAD

**Issue by Sunny-117** [vuejs/vue-cli#6988]
### Version
5.0.0-rc.3

### Reproduction link
[https://github.com/Sunny-117](https://github.com/Sunny-117)

### Environment info
```
macOS12.0.1
```

### Steps to reproduce
vue serve 无反应

### What is expected?
vue serve 无反应？

### What is actually happening?
vue serve 无反应

**Comment by Sunny-117** [comment]
<img width="317" alt="image" src="https://user-images.githubusercontent.com/73089592/153757861-713018d6-a832-4e70-8c1e-22d145c5bd60.png">

**Comment by sodatea** [comment]
https://next.cli.vuejs.org/migrations/migrate-from-v4.html#the-vue-command-the-global-vue-cli-package

这个命令已经去掉了。请在项目中使用 `npm run serve` 或 `yarn serve`
