### ISSUE TITLE
proxyTable can't work

### ISSUE THREAD

**Issue by lo56ve** [vuejs/vue-cli#699]
The latest vue-cli has no **http-proxy-middleware**,how does proxy work？It always request the localhost,but no server

**Comment by LinusBorg** [comment]
1. You are posting in the wrong repository. You are looking for this: https://github.com/vuejs-templates/webpack
2. We use webpack-dev-server now in the webpack template, which has the proxy middleware included: https://webpack.js.org/configuration/dev-server/#devserver-proxy

**Comment by lo56ve** [comment]
thx
