### ISSUE TITLE
如何关闭现代模式

### ISSUE THREAD

**Issue by ideayuye** [vuejs/vue-cli#6995]
### Version
5.0.0-rc.3

### Environment info
```
由于vue-cli build会默认进入modern模式，导致要编译两次。本来每次编译要耗时几分钟，现在需要十几分钟。有没办法关闭现代模式，直接编译一个兼容老版本浏览器的版本。
```

### Steps to reproduce
vue-cli-service.js build

### What is expected?
关闭现代模式

### What is actually happening?
默认进现代模式

**Comment by sodatea** [comment]
https://next.cli.vuejs.org/migrations/migrate-from-v4.html#vue-cli-service

> You can opt-out this behavior by appending a `--no-module` flag to the build command. `vue-cli-service build --no-module` will only output the legacy bundles that support all target browsers (loaded via plain `<script>`s).

**Comment by ideayuye** [comment]
Thank you.
