### ISSUE TITLE
HMR not working inside docker container

### ISSUE THREAD

**Issue by DRoet** [vuejs/vue-cli#6996]
### Version
5.0.1

### Environment info
```
Docker Desktop 4.5.1 (Windows)
```

### Steps to reproduce
In @vue/cli v4 I was able to add the following to vue.config.js:

```js
devServer: {
   public: '0.0.0.0:8080',
   disableHostCheck: true,
},
```

which results in:
```
App running at:
 - Local:    http://localhost:8080/ 
 - Network:  http://0.0.0.0:8080/
```

Using the webpack-dev-server v4 migration guide, I tried the following in @vue/cli V5:

```js
devServer: {
   client: {
      webSocketURL: 'ws://0.0.0.0:8080/ws',
   },
   allowedHosts: 'all',
},
```

which results in:
```
App running at:
 - Local:    http://localhost:8080/ 
 - Network:  http://172.18.0.13:8080/   // <-- not actually binding to 0.0.0.0
```

### What is expected?
The page loads on localhost:8080 and the HMR works as expected

### What is actually happening?
The page loads on localhost:8080, but HMR is not working and doesn't pick up any changes until a manual reload

**Comment by abellion** [comment]
The issue doesn't come from vue-cli, but from docker. It looks like they have made a change that prevents vue-cli from properly detecting the application is running inside a container.

As a workaround, you can set the `devServer.public` option of your `vue.config.js` to the URL you're accessing your application from.

```js
{
  devServer: {
    host: '0.0.0.0',
    port: 80,
    public: 'your-app-url.test'
  }
}
```

**Comment by DRoet** [comment]
Ughh I was messing around with WSL2 earlier today and it turns out I just ruined my local docker setup and I had to do a fresh wipe.

This actually works fine in v5:
```js
client: {
   webSocketURL: 'ws://0.0.0.0:8080/ws',
},
```

@abellion please note that your example only works in @vue/cli 4.x. `devServer.public` is no longer a valid option in webpack 5 + webpack-dev-server v4 that is being used in @vue/cli 5.x

**Comment by sheerazabbas** [comment]
in case someone struggling to find the **webSocketURL** or 
in some case even you know and provide your correct URL into the solution as mentioned by @DRoet it seems not working.

in that case just try as: 
```js
client: {
   webSocketURL: 'auto://0.0.0.0:0/ws',
},
```

**Comment by TheDevelolper** [comment]
I found a solution to the problem and I've written an article on how to fix it here: 
https://dev.to/simplifycomplexity/solving-hot-reload-issues-in-vs-code-dev-containers-on-windows-with-wsl2-16d5

It might be caused by the way WSL2 monitors mounted drives for changes. There's an issue where it will not do this from within a mounted drive (I don't mean a docker volume). So my article describes the steps needed to fix the issue. 

I hope my work helps anyone else facing the problem.
