### ISSUE TITLE
Conditional files

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-cli#70]
Allow copying files conditionally based on prompt results. Probably a custom metalsmith middleware that deletes entries from `files`. We will need a extra field in `meta.json`:

``` json
{
  "schema": {
    "linter": {
      "label": "ESLint configuration",
      "type": "list",
      "choices": [
        "standard",
        "airbnb",
        "none"
      ]
    }
  },
  "files": {
    ".eslintrc.js": "linter.standard || linter.airbnb"
  }
}
```

We can allow simple expressions in the value for each file entry, probably evaluated using a `new Function()`. Or, we can allow the meta file to actually be a JavaScript file, so that each `files` entry can be a function that receives the prompt results and return a Boolean to determine whether the file should be copied.

Update: we also need to handle conditionally rendering entire directories.

**Comment by zigomir** [comment]
Feature landed with [2.0 release](https://github.com/vuejs/vue-cli/releases/tag/v2.0.0).
