### ISSUE TITLE
ValidationError: Invalid configuration object.

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-cli#7000]
### Version
5.0.1

### Reproduction link
[github.com](https://github.com/BallAerospace/COSMOS/tree/vuecli_v5)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.7.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.62)
  npmPackages:
    @vue/eslint-config-prettier: 7.0.0 => 7.0.0
    eslint-plugin-vue: 8.4.1 => 8.4.1
    vue-eslint-parser:  8.2.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
cd cosmos-init\plugins\packages\cosmosc2-tool-cmdsender;
yarn install;
yarn build;

### What is expected?
Successful build

### What is actually happening?
C:\_Programs\COSMOS\COSMOS\cosmos-init\plugins\packages\cosmosc2-tool-cmdsender>yarn build
yarn run v1.22.15
$ vue-cli-service build

 ERROR  ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
         - configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".
           BREAKING CHANGE since webpack 5: The devtool option is more strict.
           Please strictly follow the order of the keywords in the pattern.
         - configuration.output has an unknown property 'jsonpFunction'.

---
When I type "npx vue inpsect" I can see that it is indeed generating invalid output with the jsonpFunction. 

COSMOS\cosmos-init\plugins\packages\cosmosc2-tool-cmdsender>npx vue -V
@vue/cli 5.0.1

COSMOS\cosmos-init\plugins\packages\cosmosc2-tool-cmdsender>npx vue upgrade
 WARN  There are uncommitted changes in the current repository, it's recommended to commit or stash them first.
? Still proceed? Yes
✔  Gathering package information...
 DONE  Seems all plugins are up to date. Good work!

**Comment by ghost** [comment]
I apologize for the less than minimal reproduceable project but since this is a brand new release (5.0!) I assume I'm probably not the only one working through issues. I'm using Vuetify and single-spa so if my project's level of complexity is too much and/or the error message not immediately obviously then I know your time is valuable and feel free to close. I'll wait for the other projects in my stack to catch up. Thanks for Vue CLI!

**Comment by haoqunjiang** [comment]
I think it's because `vue-cli-plugin-single-spa` isn't compatible with webpack 5 yet.
Due to this line: https://github.com/single-spa/vue-cli-plugin-single-spa/blob/93121d4836ef58d4681e9cf9ea59af31fbc4f6b1/index.js#L28
Already reported https://github.com/single-spa/vue-cli-plugin-single-spa/issues/43 and there are several PRs addressing this issue.

**Comment by ghost** [comment]
Thanks for the links. I'll wait for vue-cli-plugin-single-spa to get updated.
