### ISSUE TITLE
Incorrect package being required in cli-plugin-typescript

### ISSUE THREAD

**Issue by AmbrosiaDevelopments** [vuejs/vue-cli#7003]
### Version
5.0.1

### Environment info
I cannot run `vue info` as I use vue with vue-loader via Nx workspace and am recompiling my own version of @nx-plus/vue to support custom element definitions. 

### Steps to reproduce

Make use of cli-plugin-typescript and see it fail to import the specified library due to typo at https://github.com/vuejs/vue-cli/blob/master/packages/%40vue/cli-plugin-typescript/index.js#L92 where `require.resolve('vue/compiler-sfc')` needs to be replaced with `require.resolve('@vue/compiler-sfc')`

### What is expected?
That during use it will import the right package, which needs to be prefixed with an '@' symbol.

### What is actually happening?
The package being required at https://github.com/vuejs/vue-cli/blob/master/packages/%40vue/cli-plugin-typescript/index.js#L92 is missing the '@' symbol so fails to be imported.

---

**Comment by haoqunjiang** [comment]
It's not wrong. The `vue` package has a `vue/compiler-sfc` export since v3.2.13.
