### ISSUE TITLE
Vue-cli doesn't actually install?

### ISSUE THREAD

**Issue by Tsaukpaetra** [vuejs/vue-cli#7011]
### Version
5.0.1

### Reproduction link
[None](Can't create a project, thus there is no code to reproduce)

### Environment info
```
Unable to comply, vue-cli doesn't get installed.
Running Windows 11 22000.527 (21H2)
```

### Steps to reproduce

```
C:\>yarn global add @vue/cli
yarn global v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "@vue/cli@5.0.1" with binaries:
      - vue
Done in 4.92s.

C:\>vue ui
'vue' is not recognized as an internal or external command,
operable program or batch file.

C:\>where vue
INFO: Could not find files for the given pattern(s).

C:\>
```

### What is expected?
Installing Vue-cli

### What is actually happening?
Things apparently get installed, but...  aren't?

---
This is a clean Windows 11 install, installed node-v16.14.0-x64, enabled Yarn via `corepack enable` and then attempted to install Vue ui.
I'm not sure where I went wrong, things have apparently changed since I last worked with this early 2020, so maybe I'm not following instructions correctly.

**Comment by YFengFly** [comment]
I think it's a matter of environment variables: environment variables may not be automatically configured when yarn is installed.
I recommend that you reinstall yarn as an administrator, or add environment variable for yarn.

**Comment by Tsaukpaetra** [comment]
I'm not sure how environment variables come into play. Since I can run the `yarn` command, that's clearly already been handled, has it not? As far as I remember the documentation mentioning, you just need the path for it added and Bob's your uncle.

Why should I be required to faff about with environment variables anyways? This should have been a solved problem since Windows NT...

**Comment by LinusBorg** [comment]
> I'm not sure how environment variables come into play. Since I can run the yarn command, that's clearly already been handled, has it not?

Not necessarily. yarn will put the global package some place, and then add a symlink in a location that has to be within your terminal's PATH (that how it's on OSX at least).

That yarn can be run doesn't mean that whatever you install globally with it is also within the PATH of your terminal. Not having any experience with yarn on windows I can't provide you any further hints beyond that.

This is not something we can influence within this project, it's a problem of configuration with your machine: it's not about `@vue/cli`, it's about how the tool you use to install `@vue/cli` makes it executable - or fails to do so on your machine.
