### ISSUE TITLE
maybe bug? If using nginx redirect, webpack hmr doesn't work on dev

### ISSUE THREAD

**Issue by leafiy** [vuejs/vue-cli#702]
I've just update vue-template to 1.2.8

if I set config/index.js like this
`host: 'myproject.local'
    port: 8020`

and nginx conf like 
`location /{
proxy_pass http://localhost:8020;
}
`

a blank page will show when I change my local codes, but if I use myproject.local:8020, everything is good

I like to use the url without port number, what should I do?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
