### ISSUE TITLE
5.0.1  显示 process 未定义，process.env 可以正常输出。但是，4.x 版本均可输出。

### ISSUE THREAD

**Issue by loannea** [vuejs/vue-cli#7020]
### Version
5.0.1

### Environment info
```
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 16.13.1 - D:\nodejs16\node.EXE
    Yarn: Not Found
    npm: 8.1.2 - D:\nodejs16\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.62)
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
vue-cli（5.0.1） create 创建项目，然后在main.ts 分别console.log 出  process.env  和 process   
前者正常输出，后者显示未定义。
4.5.15 ，可以正常输出。
因为引入的第三方js库初始化的时候会判断中存在 if(process),导致第三方包无法正常使用。

### What is expected?
process 正常定义

### What is actually happening?
process 显示未定义

---
版本4.5.15  是正常的

**Comment by yoyo837** [comment]
webpack 5 删除了process内置支持，不知道是否于此有关。

**Comment by justforuse** [comment]
https://webpack.js.org/migrate/5#run-a-single-build-and-follow-advice

![image](https://user-images.githubusercontent.com/11868477/156989103-d6ccf4c6-ee28-4c5c-8520-c210aece7320.png)

**Comment by YFengFly** [comment]
继楼上 Contributor 的内容，官方中文版为：
[https://webpack.docschina.org/migrate/5/#run-a-single-build-and-follow-advises](https://webpack.docschina.org/migrate/5/#run-a-single-build-and-follow-advises)

升级日志：
[https://webpack.docschina.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed](https://webpack.docschina.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed)

Vue CLI 5 的升级说明（英文）：
[https://next.cli.vuejs.org/migrations/migrate-from-v4.html#vue-cli-service](https://next.cli.vuejs.org/migrations/migrate-from-v4.html#vue-cli-service)

**所以这不是和 Vue CLI 有关的 issue** ，而是和 Webpack 大版本升级有关的。
Webpack 5 之后不再为 Node.js 核心模块增加 Polyfills ，需要自行解决。可以自己安装 process 依赖后再修改配置，也可以用 Vue CLI 提供的环境变量方法来改变原有的设计方案：
[https://cli.vuejs.org/zh/guide/mode-and-env.html](https://cli.vuejs.org/zh/guide/mode-and-env.html)
如果你认真看报错，其实报错写的非常清楚，告诉你该如何解决。把报错看明白后，基本上也就知道问题该从哪里开始下手解决了。
