### ISSUE TITLE
[bug] browserlist not honored.

### ISSUE THREAD

**Issue by trusktr** [vuejs/vue-cli#703]
I used `vue init` to create a webpack project, then I tried to edit package.json's `browserlist` property to configure my build target, to no avail. Finally, I erased that from package.json then I configured `preset-env` "targets" directly in `.babelrc` and that worked.

Just a heads up, maybe the vue-cli output needs to be updated to use `.babelrc` instead, as browserlist seems to be completely ignored.

**Comment by LinusBorg** [comment]
1. This is an issue about the template, not the cli. 
2. Babel-preset-env doesn't (yet) honor browserlist in `package.json` currently, which is why we also have a target config in `.babelrc`. With babel7, the field in `package.json` will be honored.

**Comment by trusktr** [comment]
Aah, i was confused, I thought it worked since it was included. Thanks!
