### ISSUE TITLE
无法跳转到自己想要的路径

### ISSUE THREAD

**Issue by carpONE** [vuejs/vue-cli#7050]
### Version
5.0.1

### Environment info
```
无法跳转到自己想要的路径
```

### Steps to reproduce
无法跳转到自己想要的路径

### What is expected?
无法跳转到自己想要的路径

### What is actually happening?
无法跳转到自己想要的路径

---
无法跳转到自己想要的路径

**Comment by haoqunjiang** [comment]
请按 issue helper 提示正确填写必要的信息。
