### ISSUE TITLE
默认编译不转换成es5么 请大佬解答一下

### ISSUE THREAD

**Issue by kamiyan233** [vuejs/vue-cli#7055]
### Version
5.0.3

### Environment info
```
电脑 mac m1
```
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/31337302/158544687-82a6696c-930a-47bd-88df-02bb1b2b87d8.png">

### Steps to reproduce
1.create testproject
2.npm install
3.npm run build
没有加任何其他逻辑和文件
然后发现dist编译的js文件中有const等es6的语法存在

### What is expected?
默认转换成es5

### What is actually happening?
部分代码没有转换成es5 chunk-vendors.js文件没转换的比较多

**Comment by haoqunjiang** [comment]
因为这是 Vue 3 项目，Vue 3 要求浏览器至少原生支持 Proxy，而支持 Proxy 的环境都支持 const，所以不需要转换。

**Comment by alanwei43** [comment]
> ### Version
> 
> 5.0.3
> ### Environment info
> 
> ```
> 电脑 mac m1
> ```
> 
> <img alt="image" width="1152" src="https://user-images.githubusercontent.com/31337302/158544687-82a6696c-930a-47bd-88df-02bb1b2b87d8.png">
> ### Steps to reproduce
> 
> 1.create testproject 2.npm install 3.npm run build 没有加任何其他逻辑和文件 然后发现dist编译的js文件中有const等es6的语法存在
> ### What is expected?
> 
> 默认转换成es5
> ### What is actually happening?
> 
> 部分代码没有转换成es5 chunk-vendors.js文件没转换的比较多

修改你的`babel.config.js`文件内容为: 

```javascript
module.exports = {
  presets: [
    ['@vue/cli-plugin-babel/preset', {
      "targets": { // https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/babel-preset-app#targets
        "chrome": "67",
        "ie": "11"
      },
      "useBuiltIns": false, // https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/babel-preset-app#usebuiltins
    }]
  ],
};
```

同时 `vue.config.js` 的 `transpileDependencies` 值改成 `true`.
