### ISSUE TITLE
Installing vue-cli I get the error ENOVERSION -  No valid versions available for timed-out

### ISSUE THREAD

**Issue by troneras** [vuejs/vue-cli#706]
Installing vue-cli I get this error. 

```
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for timed-out
```

I got before that error, the following one, but it disappeared when I updated node and npm. 

`
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for duplexer3
`

I have check the requisites for installation and I think this is not the  problem. 
```
npm --v = 5.5.1
node -v  = v8.9.1
graphcool version = 0.4.9 //required
```

I'm using windows 10 with powershell in Visual Studio Code.

Attached the debug log. 

[2018-01-06T19_27_05_478Z-debug.log](https://github.com/vuejs/vue-cli/files/1609138/2018-01-06T19_27_05_478Z-debug.log)

Thanks.

**Comment by hjJunior** [comment]
Same problem here, I tried to downgrade npm version but, I didn't resolve it
Versions that I've tried:
`npm --v = 4.6.1` and `npm --v = 5.6.0`
`node -v  = v8.9.4`


[2018-01-06T19_44_30_733Z-debug.log](https://github.com/vuejs/vue-cli/files/1609146/2018-01-06T19_44_30_733Z-debug.log)

**Comment by nats-afs** [comment]
I'm new on Node...
I have the same problem

npm -v      => 5.6.0
node -v      => v8.9.4
OS Windows 7

**Comment by michaeljaekel** [comment]
Hi, 
I got the same error.
With the latest node installed (9.3.0) I got the duplexer3 not found error. 
After downgrading to node v.8.9.4 and npm v5.6.0 I got 
```
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for timed-out
```

**Comment by randinterval** [comment]
@troneras @hjJunior @nats-afs @michaeljaekel  @neves This is due to npm registry issue: 
See https://github.com/npm/registry/issues/255

**Comment by troneras** [comment]
It has been a NPM issue with many packages

It's already working.

**Comment by michaeljaekel** [comment]
works again like expected.
Thanks.
