### ISSUE TITLE
Some folders are ignored when building or compiling.

### ISSUE THREAD

**Issue by John-Soul** [vuejs/vue-cli#7062]
### What problem does this feature solve?
For example. I have three projects in one main folder. they use main folder some code, layout, style, components etc.
views/projectA | views/projectB | views/projectC
entry file in themself folder.
I will input npm run dev -- --project A compile the projectA.
compile the projectB or projectC use same way.
This method save my ssd space and maintenance time.

But the more project in the "views" folder, It will be slow.
I hope vue-cli have a method, other folders are ignored when building or compiling.

### What does the proposed API look like?
ignore: ['@/src/views/projectB', '@/src/views/projectC']

**Comment by LinusBorg** [comment]
https://github.com/vuejs/vue-cli#status
