### ISSUE TITLE
Kokoko

### ISSUE THREAD

**Issue by ghost** [vuejs/vue-cli#7065]
### Version
5.0.3

### Reproduction link
[None](kek.ru)

### Environment info
```
Kokoko
```

### Steps to reproduce
Kokoko

### What is expected?
Kokoko

### What is actually happening?
Kokoko

**Comment by ghost** [comment]
Ко-кок-коко

**Comment by TchernyavskyDaniil** [comment]
You got it wrong, if you mean this thread https://github.com/vuejs/vue-cli/issues/7054. The maintainers closed the problem this library was causing https://github.com/RIAEvangelist/node-ipc/issues/233#issuecomment-1068182278
Take it easy

**Comment by ghost** [comment]
Конечно - да!

**Comment by TchernyavskyDaniil** [comment]
So why spam here? It's not the Maintainers' fault and they fixed it.

**Comment by ghost** [comment]
Как это было допущено вообще?

**Comment by TchernyavskyDaniil** [comment]
It is impossible to monitor all dependencies for this situation. At the current time, for sure.  It is not the fault of any of the Vue team
There are thousands of dependencies on the project, get it
They corrected it as soon as they saw it.

**Comment by ghost** [comment]
Ок, я бы высказался в том Issue, если бы он не был закрыт. Но то, что он закрыт меня очень расстроило

**Comment by ghost** [comment]
Хорошо, если проблема от того, что вы не можете уследить - может вы не компетентны?! Это доставляет много неудобств...
