### ISSUE TITLE
使用 vue-cli 构建项目时，选择 webpack 模板，在IE11下 无法正常显示

### ISSUE THREAD

**Issue by xubaoduo** [vuejs/vue-cli#707]
使用 npm run dev 运行，使用F12 ，监控IE11内容时，app.js 有脚本异常。

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

The problem you're experiencing is related to webpack template but it has nothing to do with the cli itself. If you find it's not working properly and it was before, please, open an issue in the [template repository](https://github.com/vuejs-templates/webpack/) as it may be a regression
