### ISSUE TITLE
node-ipc 9.2.1 transient dependencies included in @vue/cli are unsafe

### ISSUE THREAD

**Issue by lorand-horvath** [vuejs/vue-cli#7071]
### Version
4.5.16
5.0.3

### Environment info
```
@vue/cli 4.5.16
@vue/cli 5.0.3

node 12.22.11
```

### Steps to reproduce
node-ipc 9.2.1 has transient dependencies that can be injected with malware.

### What is expected?
A bundled node-ipc version with safe, locked transient dependencies should be included in @vue/cli

### What is actually happening?
Transient dependencies are not safe against new updated versions.

---
Follow-up to closed issue https://github.com/vuejs/vue-cli/issues/7051

> Can we be sure that the locked node-ipc version 9.2.1 is and will always be trustworthy in the future?
>> @sodatea: No, transitive dependencies may break things too. So I'm gonna ship a version that bundles node-ipc and all its dependencies.

When can we expect the new @vue/cli versions (4.x and 5.x) that bundle node-ipc 9.2.1? I have completely uninstalled the CLI and will not use it to create any vue projects because we cannot simply trust what RIAEvangelist does in his other packages, the transient dependencies I've mentioned above (`event-pubsub`, `js-message`, `js-queue`, `node-cmd`). If you take a look, he has been further "developing" the peacenotwar module since then, so it's only a matter of time until this blows up again.

**Comment by lorand-horvath** [comment]
Thanks for 5.0.4.
4.5.17 would be nice, as well...

**Comment by lorand-horvath** [comment]
Note to myself: latest 4.5.16 is still unpatched against RIAEvangelist, could be compromised at any point in time - DO NOT USE.

**Comment by LinusBorg** [comment]
4.5.17 has the same fix.
