### ISSUE TITLE
WhiteSource 检测提示ansi-regex/3.0.0 高危漏洞需要升级版本

### ISSUE THREAD

**Issue by huyafei** [vuejs/vue-cli#7081]
### Version
5.0.4

### Environment info
```
无
```

### Steps to reproduce
@vue/cli-service@~5.0.4/progress-webpack-plugin@^1.0.12/log-update@^2.1.0/wrap-ansi@^3.0.1/strip-ansi@^4.0.0/ansi-regex@^3.0.0

### What is expected?
没有漏洞

### What is actually happening?
提示高危漏洞

**Comment by lorand-horvath** [comment]
There is already an issue opened for this under the `progress-webpack-plugin` repo here: https://github.com/ali322/progress-webpack-plugin/issues/5

**Comment by haoqunjiang** [comment]
`ansi-regex` 3.0.1 has fixed this issue. Please update your dependencies.
