### ISSUE TITLE
Template execution failed: ReferenceError: dataList is not defined

### ISSUE THREAD

**Issue by umayanga1997** [vuejs/vue-cli#7087]
### What problem does this feature solve?
ReferenceError: dataList is not defined

  - index.html:10 eval
    [.]/[html-webpack-plugin]/lib/loader.js!./public/index.html:10:10

  - index.html:13 module.exports
    [.]/[html-webpack-plugin]/lib/loader.js!./public/index.html:13:3

  - index.js:284
    [apec-pos-online]/[html-webpack-plugin]/index.js:284:18

  - runMicrotasks

  - task_queues.js:95 processTicksAndRejections
    internal/process/task_queues.js:95:5

### What does the proposed API look like?
ReferenceError: dataList is not defined

  - index.html:10 eval
    [.]/[html-webpack-plugin]/lib/loader.js!./public/index.html:10:10

  - index.html:13 module.exports
    [.]/[html-webpack-plugin]/lib/loader.js!./public/index.html:13:3

  - index.js:284
    [apec-pos-online]/[html-webpack-plugin]/index.js:284:18

  - runMicrotasks

  - task_queues.js:95 processTicksAndRejections
    internal/process/task_queues.js:95:5

**Comment by haoqunjiang** [comment]
Please follow the instruction in the issue helper and provide the necessary information.
