### ISSUE TITLE
Question: Conditional filters from checkbox prompt

### ISSUE THREAD

**Issue by DrSensor** [vuejs/vue-cli#710]
How do I filter file based on a prompt value that uses checkbox? 
For example:
I have checkbox prompt like this
```js
    ci: {
      type: 'checkbox',
      message:
        'Add circleci for Continuos Deployment',
      choices: [
        {
          name: 'Publish to NPM',
          value: 'publish',
          short: 'npm'
        },
        {
          name: 'Deploy storybook to surge.sh',
          value: 'deploy',
          short: 'surge'
        },
        {
          name: 'No CI',
          value: false,
          short: 'no'
        }
      ]
    }
```
Then how do I filters file from that checkbox?

Something like this
```js
{
  "filters": {
    ".circleci/*": "ci.no"
  }
}
```
or this
```js
{
  "filters": {
    ".circleci/*": "ci === no"
  }
}
```

Because there is no documentation in the readme.

**Comment by DrSensor** [comment]
Sorry, had a long day and seems I had a typo in my folder name.
I accidentally just tested in 3 way and its work:
```js
filters: {
    '.loader/docs-loader.js': 'addons.readme',
    '.loader/info-loader.js': 'addons["info"]',
    '.loader/notes-loader.js': 'addons === "notes"',
}
```

**Comment by LinusBorg** [comment]
I'll comment on the initial post, since you provide no context for `addons` in your second one:

The atring you pass is just a javascript expression
```javascript
{
  "filters": {
    ".circleci/*": "ci" // or "ci === false"
  }
}
```

**Comment by LinusBorg** [comment]
For further questions, please use forum.vuejs.org or chat.vuejs.org. As per our rules, issues are only for bugs and feature requests.
