### ISSUE TITLE
vue init webpack my-project , then  npm start failed

### ISSUE THREAD

**Issue by KloveML** [vuejs/vue-cli#712]
why not webpack-dev-server CLI  load webpack.config.js

**Comment by LinusBorg** [comment]
Hi, thanks for reporting an issue. 

However, two things: 

1. You are in the wrong repository: https://github.com/vuejs-templates/webpack
2. You don't describe your problem in an understandable way. I don't understand what you mean by this:

> why not webpack-dev-server CLI load webpack.config.js

Please open a new issue in the right repository and provide more information.
