### ISSUE TITLE
why vue-cli5.0.4 always build twice ?

### ISSUE THREAD

**Issue by xiaoweibaniu** [vuejs/vue-cli#7128]
### Version
5.0.4

### Reproduction link
[github.com](https://github.com/vuejs/vue-cli/issues/7127)

### Environment info
```
windows
```

### Steps to reproduce
build

### What is expected?
https://github.com/vuejs/vue-cli/issues/7127

### What is actually happening?
https://github.com/vuejs/vue-cli/issues/7127

**Comment by sodatea** [comment]
https://cli.vuejs.org/migrations/migrate-from-v4.html#vue-cli-service

**Comment by haoqunjiang** [comment]
https://cli.vuejs.org/migrations/migrate-from-v4.html#the-build-command-and-modern-mode
