### ISSUE TITLE
vue init webpack newProject 

### ISSUE THREAD

**Issue by roytime** [vuejs/vue-cli#713]
vue init webpack newProject 
初始化
然后 cd newProject
然后 yarn install 
都没有问题
再然后  yarn run dev ，就出现这个问题：

没有给这些选项指定值：config-name, context, entry, module-bind, module-bind-post, module-bind-pre, output-path, output-filename, output-chunk-filename, output-source-map-filename, output-public-path, output-jsonp-function, output-library, output-library-target, records-input-path, records-output-path, records-path, define, target, watch-aggregate-timeout, devtool, resolve-alias, resolve-extensions, resolve-loader-alias, optimize-max-chunks, optimize-min-chunk-size, prefetch, provide, plugin, open-page
error Command failed with exit code 1.

当然，前面还有很长的Config options 

为什么，我第一次安装，运行都没有问题，而后其他几次，无论怎么样删除重装，都是这个问题？

**Comment by xiaochen9506** [comment]
webpack-dev-server 2.9.10 bug。
`"webpack-dev-server": "2.9.1"` 
指定2.9.1 版本可以。2.9.10 有bug，这样可以运行

**Comment by inmWang** [comment]
@xiaochen9506 我init出来默认的版本是2.9.1 ，但是还是报上面这个错误

**Comment by xiaochen9506** [comment]
@inmWang 你确定？init出来默认是
`"webpack-dev-server": "^2.9.1"`
多个^的，可以展示先去掉^，2.9.10 好像有bug

**Comment by roytime** [comment]
这个问题很奇怪。 我昨天运行的时候，很正常。 就是今天不知道为什么出错，怎么运行都出错。

**Comment by inmWang** [comment]
@xiaochen9506 去掉^也还是不行emmm

**Comment by roytime** [comment]
@xiaochen9506 嗯，是的，是这个问题。 
"webpack-dev-server": "2.9.1",
这样就可以了。 

我的操作方法是  yarn remove webpack-dev-server
然后，再 yarn add webpack-dev-server@2.9.1  --dev  
然后在 yarn run dev  ，一起就正常了。

**Comment by roytime** [comment]
@inmWang 问题可以这样解决。

**Comment by ajhsu** [comment]
@roytime 
原本 `vue init` 出來的 `"webpack-dev-server": "^2.9.1"` 版號，是包含 `2.x.x` 的，因此目前出問題的 `2.10.0` 會意外地被安裝；試試看改為 `"webpack-dev-server": "2.9.7"` 之後，再重新執行一次 `npm install` 即可解決。

**Comment by xiaochen9506** [comment]
@inmWang 需要重新npm i一下的吧，emmmm

**Comment by roytime** [comment]
@ajhsu 我的问题已经解决了。 这样可以的。

**Comment by linjiangl** [comment]
解决:
"webpack-dev-server": "^2.9.1" => "webpack-dev-server": "2.9.1"
rm -rf node_modules
npm install
