### ISSUE TITLE
在vue.config.js中设置publicPath值之后，pages中页面路径访问紊乱

### ISSUE THREAD

**Issue by ZhaoJiwu** [vuejs/vue-cli#7139]
### Version
5.0.4

### Reproduction link
[github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Environment info
```
OS: Windows 10 10.0.18362
项目启动后，在浏览器地址栏中输入每个page的名称，无法导向正确的路径，需要把publicPath值去掉后，直接输入page名称才可以进入页面，但是刷新后，页面又不见了。
```

### Steps to reproduce
1、创建项目后，配置vue.config.js
2、配置publicPath，值设置为非默认的其他路径
3、配置pages，添加两个及以上的页面

### What is expected?
/

### What is actually happening?
/

**Comment by ZhaoJiwu** [comment]
/

**Comment by bj-white** [comment]
需求+1
