### ISSUE TITLE
Module not found: Error: Package path . is not exported from package

### ISSUE THREAD

**Issue by wangjieCode** [vuejs/vue-cli#7144]
### Version
5.0.4

### Reproduction link
[github.com](https://github.com/wangjieCode/vuecli-report)

### Environment info
```
node v14.18.1
vue/cli 5.0.4
```

### Steps to reproduce
1. ``npm install``
2. ``npm run serve``

### What is expected?
Normal operation
<img width="708" alt="image" src="https://user-images.githubusercontent.com/49115360/169701864-1b231b90-d350-4499-bdae-cd91986beda9.png">

### What is actually happening?
Module not found: Error: Package path . is not exported from package

---
in “version-compare” package.json;
```json
"exports": {
    "node": {
      "import": "./edition-es5-esm/index.js",
      "require": "./edition-es5/index.js"
    }
 },
```
Is it because of this? How to import and use it correctly

**Comment by LinusBorg** [comment]
This is a problem with that package - it needs to correctly define exports for non-node environments.

you already opened an issue there, so we will close this one.

**Comment by wangjieCode** [comment]
Thank you for your reply

**Comment by Ahayaat** [comment]
- error ./src/app/page.tsx:10:0
Module not found: Package path ./lib/image is not exported from package D:\API PROJECT\ecommerce-website\node_modules\sanity (see exports field in D:\API PROJECT\ecommerce-website\node_modules\sanity\package.json)
   8 | import { Image as IImage } from "sanity";
   9 | import Image from "next/image";
> 10 | import { urlForImage } from "sanity/lib/image";
  11 | 
  12 | export const getProductData = async () => {
  13 |   const res = await client.fetch(`*[_type=="product"]{

https://nextjs.org/docs/messages/module-not-found

how to resolve this issue?

**Comment by rmcsharry** [comment]
> @Ahayaat 

FYI ->

![Screenshot 2023-07-11 at 20 08 42](https://github.com/vuejs/vue-cli/assets/1156100/59c4b09e-f781-4982-97ff-0eb8c4a97dd1)

**Comment by Eric-Kosovec** [comment]
@rmcsharry 

FYI ->

![252752793-59c4b09e-f781-4982-97ff-0eb8c4a97dd1](https://github.com/vuejs/vue-cli/assets/9274795/b3c2ad13-ae0d-46b1-837c-00b26357b73a)

**Comment by dksingh001** [comment]
Module not found: Error: Package path ./swiper.less is not exported from package C:\Users\dkade\Desktop\landingIron\node_modules\swiper (see exports field in C:\Users\dkade\Desktop\landingIron\node_modules\swiper\package.json)

**Comment by fvdavid** [comment]
still same. 

**_- Error: Module not found: Error: Package path ./public-api is not exported from package_**

library standalone

**Comment by betul** [comment]
still same:  fyi
Module not found: Error: Package path ./modules is not exported from package "url"
