### ISSUE TITLE
vue-cli脚手架生成的项目无法运行

### ISSUE THREAD

**Issue by spk-aimin** [vuejs/vue-cli#715]
<img src='http://media.winbaoxian.com/autoUpload/common/WechatIMG13_d5dbbbe6b660872.jpeg'/>

**Comment by fengcms** [comment]
是因为新版本的 webpack-dev-server 错了。解决方法如下：

npm remove webpack-dev-server
npm install webpack-dev-server@2.9.1
npm run dev
参考：http://blog.csdn.net/fungleo/article/details/79016838

**Comment by spk-aimin** [comment]
<div><img src='http://media.winbaoxian.com/autoUpload/common/WechatIMG14_bbaf53ee922f2c7.jpeg'/><div>
<p>这样改也可以。'^' 改成 '~', 前面是拉取当前版本的最新版本，后者是拉取当前版本小版本的最新版本</p>
