### ISSUE TITLE
error:when npm run dev

### ISSUE THREAD

**Issue by crazyNoah** [vuejs/vue-cli#719]
env:vue 2.9.2
       node 8.9.4
       npm 5.6.0
when i init a new vue-cli and run it,this error comes in below.
than i change my node version.failed
than i uninstall all my node and reinstall a new version of 8.9.4, its no useful,
i dont know the reson and my computer system is macos 10.12.4
$ npm run dev

> my@1.0.0 dev /Users/dashuoge/Desktop/my
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 10% building modules 1/1 modules 0 activeevents.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2018-01-11T07_11_07_226Z-debug.log

**Comment by crazyNoah** [comment]
when u do this:vue init webpack
in this select:Should we run `npm install` for you after the project has been created? 
choose No, I will handle that myself !!!!

**Comment by johnnynode** [comment]
@crazyNoah Hey, I think It's a hosts problem, I have the same issue here, but I fixed it by this way:

```
sudo vi /etc/hosts

// add this to the hosts file
27.0.0.1        localhost
```

the error info 
```
Error: getaddrinfo ENOTFOUND localhost
at errnoException (dns.js:50:10)
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```
After I search `getaddrinfo ENOTFOUND localhost` ,  I got the anwser.
