### ISSUE TITLE
It doesn't work on node@14

### ISSUE THREAD

**Issue by libondev** [vuejs/vue-cli#7193]
### Version
5.0.4

### Environment info
```
node-v14.9.0
```

### Steps to reproduce
cnpm install

### What is expected?
normal operation Normal Running

### What is actually happening?
 Installing "@vue/vue-loader-v15" will fail on earlier versions of Node, which do not support this installation. It does not support installation with aliases("@vue/vue-loader-v15": "npm:vue-loader@^15.9.7") as dependent version packages.

---
I could not enter the vue info command on the server, but it was an error when installing dependencies as CNPM under the node@14.9.0 version

**Comment by haoqunjiang** [comment]
It's not because of Node.js v14.

It's your dependency manager that is too outdated.
Package aliases have been supported since NPM 6.9, which was released more than 3 years ago.
