### ISSUE TITLE
need proxy config for vue-cli

### ISSUE THREAD

**Issue by tommyfok** [vuejs/vue-cli#72]
![image](https://cloud.githubusercontent.com/assets/3250229/14376538/b1d4728a-fd9c-11e5-8b79-d576cbb345bc.png)
内网屏蔽访问外网了，需要用代理

**Comment by yyx990803** [comment]
自己用系统级代理吧，后面还要用 npm，vue-cli 有代理也没用。

**Comment by ttyen** [comment]
windows 7 環境下有proxy,  **vue init** 會出現
 **vue-cli · tunneling socket could not be established, cause=socket hang up**
這個有解嗎?

**Comment by xsbchen** [comment]
Window试试：
```bash
set HTTP_PROXY=http://proxy.com && set HTTPS_PROXY=http://proxy.com && vue init webpack fb2
```

**Comment by webia1** [comment]
You should be able to install Vue behind a proxy (there is alwas a proxy in EU) and the proxy is just the first step. There are also Artifactory-Servers. Big companies use all their own repositories (they pull packages on demand) and they may not be connected to the Internet directly. Therefore the ability to say Vue using the same settings set by npm is essential. I'am not an inftrastructure expert, maybe there is an easier way to do it?
