### ISSUE TITLE
Compile error Module parse failed: Unexpected token. File was processed with these loaders

### ISSUE THREAD

**Issue by alexcolo** [vuejs/vue-cli#7215]
### Version
4.5.18

### Reproduction link
[github.com](https://github.com/alexcolo/vue-cli-compile-error)

### Environment info
```
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  Binaries:
    Node: 14.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.37)
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
I got this issue when I compiled my project on my local env. Recently (June 22nd), I compiled the same project project on a different machine and I did't get this issue. It seems some node package has been update and now I got the issue.

### What is expected?
Get code compiled

### What is actually happening?
Code is not compiled and got this error on multiple js files:
error  in ./src/store/modules/bookmark.js

Module parse failed: Unexpected token (9:52)
File was processed with these loaders:
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/eslint-loader/index.js
You may need an additional loader to handle the result of these loaders.
| const getters = {
|   // getStartupBookmark: () => state.startupBookmark,
>   getStartupBookmark: name => state.startupBookmark?.[name],
|   getAppBookmarks: name => state.qlikAppBookmarks?.[name]
| };

 @ ./src/store/index.js 3:0-48 8:5-19 14:5-19

**Comment by haoqunjiang** [comment]
Same issue as https://github.com/vuejs/vue-cli/issues/7209#issuecomment-1163981026
