### ISSUE TITLE
Bitbucket fails to establish connection

### ISSUE THREAD

**Issue by timrijkse** [vuejs/vue-cli#723]
I'm trying to clone a private repository which is hosted on Bitbucket. However, when I try to do run the following command:

`vue init bitbucket:username/repository --clone` 

I get the following error:

`The authenticity of host 'bitbucket.com (104.192.143.8)' can't be established.`

I've checked my SSH key and I'm sure bitbucket is a known_host since SSH to Bitbucket works all fine..

Any idea where to start looking? Could it be a limitation of vue-cli? Because when I ssh to bitbucket I get the same message but then I'm able to answer the question "Are you sure you want to continue connecting?" while with vue-cli it just shows the spinner with the "downloading template" text.

Thanks!

**Comment by LinusBorg** [comment]
Probably this package, which we use to download repositories:

https://github.com/flipxfx/download-git-repo

**Comment by timrijkse** [comment]
@LinusBorg Thanks, I'll see if I can reproduce it when I try the package separately from vue-cli

**Comment by timrijkse** [comment]
When I try do download my repository directly with download-git-repo it does download the repository although I'm seeing the same error.
