### ISSUE TITLE
快速原型开发vue serve失效了？

### ISSUE THREAD

**Issue by dong-lufei** [vuejs/vue-cli#7243]
### Version
5.0.8

### Reproduction link
[www.npmjs.com](https://www.npmjs.com/package/@vue/cli-service-global)

### Environment info
```
Environment Info:

  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
  Binaries:
    Node: 16.15.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.1 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.53)
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
vue serve

### What is expected?
vue serve 正常运行

### What is actually happening?
>vue serve App.vue
Running yarn serve App.vue
yarn run v1.22.19
error Couldn't find a package.json file in "E:\\jeecg\\logs"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
C:\Users\13697\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\execa\index.js:174
                err = new Error(`Command failed: ${joinedCmd}${output}`);
                      ^

Error: Command failed: yarn serve App.vue
    at makeError (C:\Users\13697\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\execa\index.js:174:9)
    at C:\Users\13697\AppData\Roaming\npm\node_modules\@vue\cli\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runNpmScript (C:\Users\13697\AppData\Roaming\npm\node_modules\@vue\cli\lib\util\runNpmScript.js:17:10) {
  code: 1,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'yarn serve App.vue',
  timedOut: false,
  killed: false
}

---
为什么我用你的vue info命令出来的我的系统配置不对，我的是11，显示10，我全局有装@vue/cli-service-global，vue inof命令却显示没有装

**Comment by haoqunjiang** [comment]
CLI 5 里去掉了这个功能。需要快速原型开发的，用 `npm init vue@3` 快速新建一个 Vite + Vue 3 项目就可以了。

**Comment by dong-lufei** [comment]
> CLI 5 里去掉了这个功能。需要快速原型开发的，用`npm init vue@3`快速新建一个 Vite + Vue 3 项目就可以了。

那我如何运行单个的vue文件，比如Test.vue(文件内容如下):
```
<template>
  <h1>hello dlf</h1>
</template>
```
以前可以vue serve 单独测试运行这一个文件，而不需要跑整个项目npm run serve

**Comment by dong-lufei** [comment]
https://cli.vuejs.org/zh/guide/prototyping.html
官方页面底下显示上次编辑时间:7/16/2022, 10:12:14 PM，咋我照着这文档运行报错

**Comment by Ljfy** [comment]
要是不能用 文档就说明一下吧

**Comment by linzcity** [comment]
确实，不能用了，vue serve 直接报 error Couldn't find a package.json file
