### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'tap')

### ISSUE THREAD

**Issue by rol2005hun** [vuejs/vue-cli#7249]
### Version
5.0.8

### Environment info
```
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.71)
  npmGlobalPackages:
    @vue/cli: Not Found
```

### Steps to reproduce
i installed to my existing vue 3 project the pwa (vue add pwa)

### What is expected?
i am getting this error: TypeError: Cannot read properties of undefined (reading 'tap')

### What is actually happening?
i am getting this error: TypeError: Cannot read properties of undefined (reading 'tap')

---
I tried to delete my node_modules, package-lock.json and reinstalling it.

**Comment by MrThanlon** [comment]
same issue, downgrade to @vue/cli-plugin-pwa:4.5.17 solve it.

**Comment by rol2005hun** [comment]
yap, thats working, or update the vue-cli to 5
