### ISSUE TITLE
Just a simple vue init webpack install doesnot load in IE. throws syntax error

### ISSUE THREAD

**Issue by suprithwork** [vuejs/vue-cli#725]

**Comment by posva** [comment]
Hello!
Please, open the issue on the relevant template repo (I think you're using the [webpack one](https://github.com/vuejs-templates/webpack)) and provide some steps to reproduce the problem.
Thanks!

You'll also need to provide more information like node, browser, os versions

**Comment by suprithwork** [comment]
it has no steps 
vue init webpack sample-project

i run this and then npm run dev in the project folder it opens on chrome but doesnt work on IE. shows some syntax error.

**Comment by suprithwork** [comment]
I tried some polyfill also but no use.

The versions of webpack are way above one.

    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"

these are the versions used

**Comment by yyx990803** [comment]
This is a `webpack-dev-server` issue, pending PR https://github.com/webpack/webpack-dev-server/pull/1273

**Comment by posva** [comment]
Ah thanks, I knew I saw it somewhere but couldn't remember where

**Comment by suprithwork** [comment]
Thats fine , but now cant we use vue and test its compatibility on IE

**Comment by suprithwork** [comment]
So does this mean we cannot try vue in IE. I see a theme which uses a different setup and still makes work Vue work on IE. I wanna know how I can make it work.

**Comment by rianran1993** [comment]
mark

**Comment by Shadowlauch** [comment]
From webpack-dev-server 2.11.2 this seems to be fixed
