### ISSUE TITLE
开发环境下总是报下面这些错和发起这些请求的问题

### ISSUE THREAD

**Issue by zhangshulei** [vuejs/vue-cli#726]
![image](https://user-images.githubusercontent.com/24769526/35079817-c0a83f3c-fc44-11e7-99bd-95d6ac8e7c0f.png)

![image](https://user-images.githubusercontent.com/24769526/35079753-727d4c30-fc44-11e7-952e-958ca6f3ffad.png)

**Comment by yyx990803** [comment]
你服务器关了当然会报错...
