### ISSUE TITLE
vue create 创建的项目ie10下打开报错

### ISSUE THREAD

**Issue by bestxiaoming** [vuejs/vue-cli#7266]
### Version
4.5.19

### Reproduction link
[github.com](https://github.com/bestxiaoming/vue2-ie-demo)

### Environment info
```
window8.1 ie10
```

### Steps to reproduce
npm install
npm run serve

### What is expected?
ie10下可以正常运行

### What is actually happening?
ie10下报错

---
vue create的项目默认ie10下不能运行，根据文档配置 useBuiltIns: 'entry' 也没有效果

**Comment by haoqunjiang** [comment]
Browserslist 的默认目标浏览器已经不支持 IE 了（[微软已于今年 6 月 15 日停止支持 IE 11](https://docs.microsoft.com/zh-cn/lifecycle/announcements/internet-explorer-11-support-end-dates)）。

你需要自己在 `.browserslistrc` 或者 package.json 的 `browserslist` 字段里加上一行 "IE 10"

**Comment by bestxiaoming** [comment]
<img width="1597" alt="image" src="https://user-images.githubusercontent.com/110893548/183802738-f829daf8-185e-4e08-99e2-00335e168023.png">
配了ie 10还是不行

**Comment by bestxiaoming** [comment]
解决了，需要去除not dead, 或者把ie 10放在 not dead后面

**Comment by beierzhijin** [comment]
> 解决了，需要去除not dead, 或者把ie 10放在 not dead后面

bro，我这边也是4.5.19，按官方默认建的项目，ie11打不开啊包括360的兼容模式

**Comment by beierzhijin** [comment]
> Browserslist 的默认目标浏览器已经不支持 IE 了（[微软已于今年 6 月 15 日停止支持 IE 11](https://docs.microsoft.com/zh-cn/lifecycle/announcements/internet-explorer-11-support-end-dates)）。
> 
> 你需要自己在 `.browserslistrc` 或者 package.json 的 `browserslist` 字段里加上一行 "IE 10"

我用`Vue-Cli 5.0.8` 和 `Vue-Cli 4.5.19` 建的默认 `vue 2` 的项目，在 .browserslistrc都加入 `IE 11`，在IE11环境下或者360浏览器兼容模式（默认也是ie11）都是白屏状态
另外我想问下  `vue-cli` 的版本和 `vue` 的版本是强关联的吗 我想在`vuecli4` 或者 `vuecli5`创建的 `vue2` 项目中使用当前的 `vue-2.7.10` 版本是可行的吗（项目之前用vue3做的，但是后来需要适配ie11）

**Comment by pengdu1** [comment]
解决了吗，铁汁

**Comment by zy9703** [comment]
> > Browserslist 的默认目标浏览器已经不支持 IE 了（[微软已于今年 6 月 15 日停止支持 IE 11](https://docs.microsoft.com/zh-cn/lifecycle/announcements/internet-explorer-11-support-end-dates)）。
> > 
> > 你需要自己在 `.browserslistrc` 或者 package.json 的 `browserslist` 字段里加上一行 "IE 10"
> 
> 我用`Vue-Cli 5.0.8` 和 `Vue-Cli 4.5.19` 建的默认 `vue 2` 的项目，在 .browserslistrc都加入 `IE 11`，在IE11环境下或者360浏览器兼容模式（默认也是ie11）都是白屏状态
> 另外我想问下  `vue-cli` 的版本和 `vue` 的版本是强关联的吗 我想在`vuecli4` 或者 `vuecli5`创建的 `vue2` 项目中使用当前的 `vue-2.7.10` 版本是可行的吗（项目之前用vue3做的，但是后来需要适配ie11）

4.5.19版本中，把sockjs-client版本降到1.5.1，然后在package.json里面的browserslist的not dead后面添加“IE 11”，IE11就不会白屏了。
5.0.8版本中，只需要添加“IE 11”就行了，IE11中就会正常显示，不会白屏，
以上所用都是官方脚手架默认的vue2选项。

**Comment by carior** [comment]
5.0.4版本在browserslistrc 中设置IE11也不行，后来将vue-cli升级到5.0.8，再设置IE 11就可以了

**Comment by JokerSora** [comment]
`
> 1%
last 2 versions
IE 11
IE 10
`
kill the not dead then OK
