### ISSUE TITLE
package.json change for coffee-script

### ISSUE THREAD

**Issue by rajpatel507** [vuejs/vue-cli#728]
`npm install -g vue-cli` shows following warning for coffee-script 
`npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)`

can we change coffee-script to coffeescript in package.json as it is moved to new name?

**Comment by yyx990803** [comment]
https://github.com/vuejs/vue-cli/pull/679#issuecomment-358551952
