### ISSUE TITLE
@vue/cli-service@3 has dependency thread-loader@^2.1.2 which is potentially incompatible with vue-loader@^15.10.0

### ISSUE THREAD

**Issue by hucsmn** [vuejs/vue-cli#7289]
### Version
3.12.1

### Environment info
```
@vue/cli-service@^3.12.1
thread-loader@^2.1.2
vue-loader@^15.10.0
```

### Steps to reproduce
create a project with `"@vue/cli-service": "^3.12.1"`, then add several SFCs to project, and finally run `vue-cli-service build --mode production`.

### What is expected?
always successfully build iff code is correct

### What is actually happening?
seldomly failed to build

---
vue-loader >= 15.10.0 uses `loaderContext.rootContext` which is not available under thread-loader 3.0.1, see:

https://github.com/vuejs/vue-loader/blob/master/lib/index.js#L39

https://github.com/webpack-contrib/thread-loader/blob/master/CHANGELOG.md#301-2020-10-27

**Comment by linghengqian** [comment]
- No PR will go back to the old version, this issue should actually be closed.

**Comment by hucsmn** [comment]
Okay, upgrade to newer version of @vue/cli-service or just force yarn resolutions of thread-loader to ^3.0.1 should solve this issue.
