### ISSUE TITLE
项目启动后无法使用本机的ipv6地址访问

### ISSUE THREAD

**Issue by magneter** [vuejs/vue-cli#7297]
### Environment info
```
macos:11.6.6
"vue": "^3.2.4"
```

### Steps to reproduce
启动本地的web服务后，使用本地的ipv6地址访问 http://[xxxx]:port 无法访问

### What is expected?
期望可以通过本地ipv6地址正常访问web服务

### What is actually happening?
实际没有任何返回，没有任何消息提示。浏览器也没有加载资源

**Comment by magneter** [comment]
我翻了一下webpack的资料，webpack本身是可以的
<img width="744" alt="image" src="https://user-images.githubusercontent.com/22872135/191015616-f7575dee-8ce8-455d-a221-5e0fb557ddb8.png">
前端新手期待大佬们的解答

**Comment by 21paradox** [comment]
```js
 devServer: {
    host: '::1'
 }
```

或者
vue-cli-service serve --host ::1
