### ISSUE TITLE
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

### ISSUE THREAD

**Issue by iSatishYadav** [vuejs/vue-cli#730]
While ````npm install -g vue-cli````, npm gives a warning:
__npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)__
Should I be worried?

**Comment by jorgevilasboas** [comment]
Same here. Did you fix it?

**Comment by mandaputra8** [comment]
Same here any method to fix? Or just install coffescript?

**Comment by iSatishYadav** [comment]
#679

**Comment by ruanfumin** [comment]
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

**Comment by ruanfumin** [comment]
> npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/usr/local/bin/vue -> /usr/local/lib/node_modules/vue-cli/bin/vue
/usr/local/bin/vue-init -> /usr/local/lib/node_modules/vue-cli/bin/vue-init
/usr/local/bin/vue-list -> /usr/local/lib/node_modules/vue-cli/bin/vue-list
> + vue-cli@2.9.6
updated 1 package in 4.96s

**Comment by MigratoryBirds** [comment]
LSD:~ liu$ npm install wepy-cli -g
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   stack:
npm ERR!    "Error: EACCES: permission denied, access '/usr/local/lib/node_modules'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liu/.npm/_logs/2019-02-22T07_25_44_951Z-debug.log

**Comment by siner9586** [comment]
PS D:\node\nodejs> npm i vue-cli -g
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
D:\node\nodejs\node_global\vue-init -> D:\node\nodejs\node_global\node_modules\vue-cli\bin\vue-init
D:\node\nodejs\node_global\vue -> D:\node\nodejs\node_global\node_modules\vue-cli\bin\vue
D:\node\nodejs\node_global\vue-list -> D:\node\nodejs\node_global\node_modules\vue-cli\bin\vue-list
+ vue-cli@2.9.6
updated 2 packages in 45.87s

**Comment by huhailin666** [comment]
$ npm install -g vue-cli
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! path C:\Users\asus\AppData\Roaming\npm\node_modules\vue-cli\node_modules\mime-db
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'C:\Users\asus\AppData\Roaming\npm\node_modules\vue-cli\node_modules\mime-db'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent


How to solve it?

**Comment by lKingslayer** [comment]
Add sudo in the beginning.

**Comment by qinzhiyonyan** [comment]
How to deal with it in windows

**Comment by mandaputtra** [comment]
@qinzhiyonyan lower your vue-cli version

**Comment by qinzhiyonyan** [comment]
ok, thanks



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Manda Putra"<notifications@github.com&gt;; 
发送时间: 2021年3月3日(星期三) 凌晨2:37
收件人: "vuejs/vue-cli"<vue-cli@noreply.github.com&gt;; 
抄送: "Ո�Iԁ�V"<1447312816@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [vuejs/vue-cli] npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to &quot;coffeescript&quot; (no hyphen) (#730)





 
@qinzhiyonyan lower your vue-cli version
