### ISSUE TITLE
我现在需要将后端的baseURL预留出来请求

### ISSUE THREAD

**Issue by wangyalijas** [vuejs/vue-cli#731]
我在static 下的写了一个config.json。

在http的时候
import config from '../../../static/config.json'
const baseURL = config.baseUrl

打包后可以使用，但是再次修改的话，还是之前的路径，这就违背了我的初衷，我想问一下，为什么不能修改静态文件。

如果解决不了，我打算使用dev-server  请求json数据，或者把它变成windows下的变量。

望解答！！！

**Comment by wangyalijas** [comment]
@neves @kazupon @skyronic @Jinjiang @orlandoaleman

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

Please, do not ping people like that, most of them don't even speak Chinese so they will probably completely ignore the ping. Also, it looks like the issue you're having is related to one of the templates, remember to say which one you're using when posting the question, it will definitely help! 🙂
