### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'ignore')

### ISSUE THREAD

**Issue by jub0t** [vuejs/vue-cli#7312]
### Version
5.0.8

### Environment info
```

Environment Info:

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: Not Found
    npm: 8.19.2 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Browsers:
    Chrome: 106.0.5249.103
    Firefox: Not Found
  npmPackages:
    @vitejs/plugin-vue: ^3.0.3 => 3.1.2 
    @vue/cli-overlay:  5.0.8 
    @vue/cli-plugin-router:  5.0.8 
    @vue/cli-plugin-vuex:  5.0.8 
    @vue/cli-service: ^5.0.8 => 5.0.8 
    @vue/cli-shared-utils:  3.12.1 (5.0.8)
    @vue/compiler-core:  3.2.40 
    @vue/compiler-dom:  3.2.40 
    @vue/compiler-sfc:  3.2.40 
    @vue/compiler-ssr:  3.2.40 
    @vue/component-compiler-utils:  3.3.0 
    @vue/eslint-config-prettier: ^7.0.0 => 7.0.0 
    @vue/reactivity:  3.2.40 
    @vue/reactivity-transform:  3.2.40 
    @vue/runtime-core:  3.2.40 
    @vue/runtime-dom:  3.2.40 
    @vue/server-renderer:  3.2.40 
    @vue/shared:  3.2.40 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^9.3.0 => 9.6.0 
    vue: ^3.2.38 => 3.2.40 
    vue-cli-plugin-browser-extension: ~0.25.2 => 0.25.2 
    vue-eslint-parser:  9.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  17.0.0 (15.10.0)
    vue-style-loader:  4.1.3 
    vue-template-es2015-compiler:  1.9.1 
  npmGlobalPackages:
    @vue/cli: 5.0.8

```

### Steps to reproduce
1.  npm init vue@latest
2. vue add browser-extension
3. npm run serve

### What is expected?
The Browser extension to compile & run properly.

### What is actually happening?
jub0t@jub0t:~/Documents/codebuffer/extension$ npm run serve

> package.json@0.0.0 serve
> vue-cli-service build --mode development --watch

All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.

✔  Building for development...
 ERROR  TypeError: Cannot read properties of undefined (reading 'ignore')
TypeError: Cannot read properties of undefined (reading 'ignore')
    at /home/jub0t/Documents/codebuffer/extension/node_modules/vue-cli-plugin-browser-extension/index.js:129:20
    at Object.tap (/home/jub0t/Documents/codebuffer/extension/node_modules/webpack-chain/src/Plugin.js:30:24)
    at /home/jub0t/Documents/codebuffer/extension/node_modules/vue-cli-plugin-browser-extension/index.js:128:36
    at /home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/Service.js:268:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/Service.js:268:26)
    at PluginAPI.resolveChainableWebpackConfig (/home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/PluginAPI.js:145:25)
    at module.exports (/home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/commands/build/resolveAppConfig.js:9:22)
    at build (/home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/commands/build/index.js:147:50)
    at /home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/commands/build/index.js:69:13
    at Service.run (/home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/Service.js:262:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by jub0t** [comment]
```sh
jub0t@jub0t:~/Documents/codebuffer/extension$ vue-cli-service build
All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


✔  Building for production...
 ERROR  Error: Cannot find module 'vue/compiler-sfc'
        Require stack:
        - /home/jub0t/.nvm/versions/node/v16.17.1/lib/node_modules/@vue/cli-service/node_modules/vue-loader/dist/index.js
        - /home/jub0t/.nvm/versions/node/v16.17.1/lib/node_modules/@vue/cli-service/lib/config/base.js
        - /home/jub0t/.nvm/versions/node/v16.17.1/lib/node_modules/@vue/cli-service/lib/Service.js
        - /home/jub0t/.nvm/versions/node/v16.17.1/lib/node_modules/@vue/cli-service/bin/vue-cli-service.js
Error: Cannot find module 'vue/compiler-sfc'
Require stack:
```

**Comment by farzadtara** [comment]
> ### Version
> 5.0.8
> 
> ### Environment info
> ```
> 
> Environment Info:
> 
>   System:
>     OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
>     CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
>   Binaries:
>     Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
>     Yarn: Not Found
>     npm: 8.19.2 - ~/.nvm/versions/node/v16.17.1/bin/npm
>   Browsers:
>     Chrome: 106.0.5249.103
>     Firefox: Not Found
>   npmPackages:
>     @vitejs/plugin-vue: ^3.0.3 => 3.1.2 
>     @vue/cli-overlay:  5.0.8 
>     @vue/cli-plugin-router:  5.0.8 
>     @vue/cli-plugin-vuex:  5.0.8 
>     @vue/cli-service: ^5.0.8 => 5.0.8 
>     @vue/cli-shared-utils:  3.12.1 (5.0.8)
>     @vue/compiler-core:  3.2.40 
>     @vue/compiler-dom:  3.2.40 
>     @vue/compiler-sfc:  3.2.40 
>     @vue/compiler-ssr:  3.2.40 
>     @vue/component-compiler-utils:  3.3.0 
>     @vue/eslint-config-prettier: ^7.0.0 => 7.0.0 
>     @vue/reactivity:  3.2.40 
>     @vue/reactivity-transform:  3.2.40 
>     @vue/runtime-core:  3.2.40 
>     @vue/runtime-dom:  3.2.40 
>     @vue/server-renderer:  3.2.40 
>     @vue/shared:  3.2.40 
>     @vue/web-component-wrapper:  1.3.0 
>     eslint-plugin-vue: ^9.3.0 => 9.6.0 
>     vue: ^3.2.38 => 3.2.40 
>     vue-cli-plugin-browser-extension: ~0.25.2 => 0.25.2 
>     vue-eslint-parser:  9.1.0 
>     vue-hot-reload-api:  2.3.4 
>     vue-loader:  17.0.0 (15.10.0)
>     vue-style-loader:  4.1.3 
>     vue-template-es2015-compiler:  1.9.1 
>   npmGlobalPackages:
>     @vue/cli: 5.0.8
> ```
> 
> ### Steps to reproduce
> 1. npm init vue@latest
> 2. vue add browser-extension
> 3. npm run serve
> 
> ### What is expected?
> The Browser extension to compile & run properly.
> 
> ### What is actually happening?
> jub0t@jub0t:~/Documents/codebuffer/extension$ npm run serve
> 
> > package.json@0.0.0 serve
> > vue-cli-service build --mode development --watch
> 
> All browser targets in the browserslist configuration have supported ES module. Therefore we don't build two separate bundles for differential loading.
> 
> heavy_check_mark Building for development... ERROR TypeError: Cannot read properties of undefined (reading 'ignore') TypeError: Cannot read properties of undefined (reading 'ignore') at /home/jub0t/Documents/codebuffer/extension/node_modules/vue-cli-plugin-browser-extension/index.js:129:20 at Object.tap (/home/jub0t/Documents/codebuffer/extension/node_modules/webpack-chain/src/Plugin.js:30:24) at /home/jub0t/Documents/codebuffer/extension/node_modules/vue-cli-plugin-browser-extension/index.js:128:36 at /home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/Service.js:268:40 at Array.forEach () at Service.resolveChainableWebpackConfig (/home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/Service.js:268:26) at PluginAPI.resolveChainableWebpackConfig (/home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/PluginAPI.js:145:25) at module.exports (/home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/commands/build/resolveAppConfig.js:9:22) at build (/home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/commands/build/index.js:147:50) at /home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/commands/build/index.js:69:13 at Service.run (/home/jub0t/Documents/codebuffer/extension/node_modules/@vue/cli-service/lib/Service.js:262:12) at processTicksAndRejections (node:internal/process/task_queues:96:5)

did you find any  solution  ?

**Comment by ManutdGTA** [comment]
TypeError: Cannot read properties of undefined (reading 'ignore')
TypeError: Cannot read properties of undefined (reading 'ignore')
    at C:\code\chrome-extention\node_modules\vue-cli-plugin-browser-extension\index.js:129:20
    at module.exports.tap (C:\code\chrome-extention\node_modules\webpack-chain\src\Plugin.js:30:24)
    at C:\code\chrome-extention\node_modules\vue-cli-plugin-browser-extension\index.js:128:36
    at C:\code\chrome-extention\node_modules\@vue\cli-service\lib\Service.js:268:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (C:\code\chrome-extention\node_modules\@vue\cli-service\lib\Service.js:268:26)
    at PluginAPI.resolveChainableWebpackConfig (C:\code\chrome-extention\node_modules\@vue\cli-service\lib\PluginAPI.js:145:25)
    at module.exports (C:\code\chrome-extention\node_modules\@vue\cli-service\lib\commands\build\resolveAppConfig.js:9:22)
    at build (C:\code\chrome-extention\node_modules\@vue\cli-service\lib\commands\build\index.js:147:50)
    at C:\code\chrome-extention\node_modules\@vue\cli-service\lib\commands\build\index.js:69:13
    at Service.run (C:\code\chrome-extention\node_modules\@vue\cli-service\lib\Service.js:262:12)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
