### ISSUE TITLE
Include polyfills

### ISSUE THREAD

**Issue by johnnyshankman** [vuejs/vue-cli#7325]
### What problem does this feature solve?
Everyone expects that, this was a stupid breaking change. Webpack already treeshakes the unused modules and the convenience of having them pre-filled was massive. Setting up polyfills takes forever and I want that scaffolding done by vue cli.

### What does the proposed API look like?
What you already had from Webpack.

**Comment by haoqunjiang** [comment]
No idea what you are talking about.
Vue CLI removes nothing from the webpack core.
