### ISSUE TITLE
in vendor.js, es6 code does not translate to es5 code 

### ISSUE THREAD

**Issue by eric-ocz** [vuejs/vue-cli#734]
in dist folder, vendor.js keeps es6 code, app.js is es5 code

`./node_modules/element-ui/src/utils/dom.js
/* istanbul ignore next */

**const** isServer = vue_esm["default"].prototype.$isServer;
const SPECIAL_CHARS_REGEXP = /([\:\-\_]+(.))/g;
const MOZ_HACK_REGEXP = /^moz([A-Z])/;
const ieVersion = isServer ? 0 : Number(document.documentMode);

/* istanbul ignore next */
const trim = function(string) {
  return (string || '').replace(/^[\s\uFEFF]+|[\s\uFEFF]+$/g, '');
};
/* istanbul ignore next */
const camelCase = function(name) {
  return name.replace(SPECIAL_CHARS_REGEXP, function(_, separator, letter, offset) {
    return offset ? letter.toUpperCase() : letter;
  }).replace(MOZ_HACK_REGEXP, 'Moz$1');
};`

Expected:
vendor.js code is es5 code。so it can work in ie11

**Comment by yyx990803** [comment]
- no version info
- no reproduction
- no info on how you are using element

Can't help if you don't even provide the miminum amount of information.
