### ISSUE TITLE
Components get full re-render without preserving state

### ISSUE THREAD

**Issue by cristijora** [vuejs/vue-cli#738]
### Version
3.0.0-alpha.4

### Reproduction link
[https://github.com/cristijora/vue-cli-state-refresh](https://github.com/cristijora/vue-cli-state-refresh)

### Steps to reproduce
1. Init repo
2. Type something in the input
3. Add some tag, text near the input in the code. 
4. Save the file

### What is expected?
Input state is preserved as in the old webpack template.

### What is actually happening?
The edited component gets a full re-render and the previous state is lost. Input is empty after changing something modifying the component

---
Is this an intentional/design decision or just something that is not implemented yet?
From my POV, preserving state on hot-reloads is very important and it saves lots of time.

**Comment by yyx990803** [comment]
Cannot reproduce - it does preserve the state properly for me. Note state is only preserved when editing the `<template>` or `<style>` parts - editing `<script>` always causes the component to reset.

**Comment by cristijora** [comment]
@yyx990803 This seems to happen on template part when adding new lines (with or without code)
Here is a gif

![jan-28-2018 10-39-212](https://user-images.githubusercontent.com/15955045/35480483-9aec9272-0417-11e8-90ec-57c17f5943ec.gif)
