### ISSUE TITLE
The initial README.md has markdown lint issues - MD040/fenced-code-language: Fenced code blocks should have a language specifiedmarkdownlintMD040

### ISSUE THREAD

**Issue by briansu2004** [vuejs/vue-cli#7386]
### Vue version

5.0.8

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-cxxzon?file=README.md&terminal=dev

### Steps to reproduce

After ` vue create my-app` , the initial README.md has some markdown lint issues.

![image](https://github.com/vuejs/core/assets/6775994/abf78f83-13b5-416a-a3c7-71cde623b037)

## Project setup

```shell
npm install
```

### Compiles and hot-reloads for development

```shell
npm run serve
```

### Compiles and minifies for production

```shell
npm run build
```

### Lints and fixes files

```shell
npm run lint
```

### What is actually happening?

MD040/fenced-code-language: Fenced code blocks should have a language specified markdownlintMD040

Maybe you shpi;d add the language specified (e.g. shell, bash etc.)?

**Comment by LinusBorg** [comment]
1. Vue CLI does not integrate Markdonwlint. We don't feeel required to respect its rules.
2. Vue CLI is in maintenance mode. We only fix relevant bug and security problems.
