### ISSUE TITLE
modify assetsPublicPath lead to "can not get"

### ISSUE THREAD

**Issue by rayzang8** [vuejs/vue-cli#74]
Use the webpack template.
Issue: I modified the assetsPublicPath option in config.js when to built my project, it's run properly.
but when I run dev agian, the page "can not get" appears.

So I find the cause. If the assetsPublicPath change from '/' to others, the dev server can not find the
rootpath when npm run dev. Then I add a option in config.js 
dev: {
     assetsPublicPath:'/',
      port: 8080,
      proxyTable: {}
  }

and modify dev-server.js
var staticPath = path.posix.join( config.dev.assetsPublicPath, config.build.assetsSubDirectory)

finally modify webpack.base.conf.js 
 output: {
    path: config.build.assetsRoot,
   publicPath:  process.env.NODE_ENV === 'production' ? config.build.assetsPublicPath : config.dev.assetsPublicPath ,
    filename: '[name].js'
  }

So, I do not have to modify assetsPublicPath option after npm run build every time.

**Comment by zigomir** [comment]
@rayzang8 can you explain it a bit more. Also, if you're using one of official [vuejs-templates](https://github.com/vuejs-templates) please file an issue on repository you use.

**Comment by rayzang8** [comment]
I have file this issue on webpack reposityory

**Comment by dqisme** [comment]
WTF??? loop reference?
I encounter the same problem, how to solve it?
