### ISSUE TITLE
Jest tries to execute E2E tests

### ISSUE THREAD

**Issue by Ldoppea** [vuejs/vue-cli#740]
### Version
3.0.0-alpha.4

### Reproduction link
[https://github.com/Ldoppea/vue-cli-jest-e2e](https://github.com/Ldoppea/vue-cli-jest-e2e)

### Steps to reproduce
- execute `vue create myapp`
- select `Manually select features`
- select `Unit Testing` and `E2E Testing`
- select `Jest`
- select `Cypress (Chrome only)`
- select `Use Yarn`
- Wait for install
- run `yarn test`

### What is expected?
Only test/unit/HelloWorld.spec.js should be executed

E2E tests should not be executed

### What is actually happening?
test/e2e/specs/test.js is executed and throws an error

---
I just created a project using Vue-CLI and selected Jest and Cypress as testing frameworks. Generated Jest configuration includes e2e tests which should not be the case.

**Comment by helaili** [comment]
I've run into the same issue but not using Typescript the fix doesn't wok for me. Looking at the code, I see it's meant this way but I don't see a reason why it should only apply when Typescript is used.

https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-plugin-unit-jest/index.js#L21..L23
