### ISSUE TITLE
FuseBox template

### ISSUE THREAD

**Issue by wujekbogdan** [vuejs/vue-cli#741]
### What problem does this feature solve?
[FuseBox](https://github.com/fuse-box/fuse-box) is a relatively new bundler/module loader that can entirely replace Webpack and it's gaining more and more popularity lately. Its JS compiler is TypeScript driven, so it comes with TypeScript support out of the box and what's the most important it comes with Vue.js plugin too.

So it seems that implementing a support for this new bundler should be relatively simple. 

What do you think?

### What does the proposed API look like?
vue init fuse my-project

**Comment by yyx990803** [comment]
We have limited bandwidth and unfortunately I don't think Fusebox has gotten enough traction to warrant a template.
