### ISSUE TITLE
Vue-cli generators give an error when creating a project whose path contains spaces

### ISSUE THREAD

**Issue by mrg0lden** [vuejs/vue-cli#742]
### Version
3.0.0-alpha.4

### Reproduction link
[https://github.com/mrg0lden/vue-cli-bug](https://github.com/mrg0lden/vue-cli-bug)

### Steps to reproduce
Make a folder with spaces in its name, inside it, use vue create, now you got it.

### What is expected?
To work properly.

### What is actually happening?
Gives an error:  ERROR  Error: ENOENT: no such file or directory, scandir  'F:\Coding Zone - منطقة الترميز\الترميز\test\node_modules\@vue\cli-service\generator\template'

---

hint: actual directory should be : "F:\Coding Zone - منطقة الترميز\test\node_modules\@vue\cli-service\generator\template"

but for some strange reason, "الترميز" got duplicated.

I also tried to make a project whose parent folder's name is written in Arabic without spaces, and it worked like a charm!

**Comment by mrg0lden** [comment]
Unfortunately the issue is still present
![image](https://user-images.githubusercontent.com/8347078/35585815-0808227e-060a-11e8-89ad-06439157d55f.png)

**Comment by yyx990803** [comment]
The fix is not released yet.

**Comment by mrg0lden** [comment]
OK sorry then 🌚
