### ISSUE TITLE
Error: spawn yarn ENOENT

### ISSUE THREAD

**Issue by forzeny** [vuejs/vue-cli#746]
### Version
3.0.0-alpha.5

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
```bash 
Vue CLI v3.0.0-alpha.5
✨  Creating project in /Users/yxc/my-poject.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...

ERROR  Error: spawn yarn ENOENT
Error: spawn yarn ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
bogon:~ yxc$
```

### What is expected?
no error throw 

### What is actually happening?
throw error

---
npm : 5.5.1

node: 8.9.3

mac: 10.13.3 

yarn: 1.3.2

today 2018/01/30 i upgrade the new vue-cli to create my-project and throw this error ,i sawed [issues/681)](https://github.com/vuejs/vue-cli/issues/681) can not solve this problem

now i fallback master branch it works well

**Comment by yyx990803** [comment]
Hmm, do you have `yarn` installed?

**Comment by forzeny** [comment]
@yyx990803 yes !

**Comment by forzeny** [comment]
ignore this error and entry project directory `yarn install` by myself 

```bash
yarn global add @vue/cli-service-global
echo '<template><h1>Hello!</h1></template>' > App.vue
vue serve
```

localhost:8080
```html
Hello!
```

**Comment by yxuchen** [comment]
recently i was using create-react-app tool for create react app and throw this error
 
we can use this command to solve this error

```bash
npm uninstall -g yarn
```
