### ISSUE TITLE
command to eject webpack config

### ISSUE THREAD

**Issue by rafaesc** [vuejs/vue-cli#747]
### What problem does this feature solve?
Hi

I use the new 3.0.0-alpha version. But I need to add a new alias to add a vue plugin, [vue-konva](https://github.com/rafaesc/vue-konva) because when I try to add it,  I get the following error.

````
You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
found in
---> \<VLayer\>
````
The solution is here:
https://github.com/vuejs-templates/webpack/issues/215#issuecomment-238095102

### What does the proposed API look like?
I think that should have a new command like `vue eject`

**Comment by yyx990803** [comment]
There's no eject. You will be able to configure everything, but the documentation is not out yet.

**Comment by Ldoppea** [comment]
@yyx990803 Do you have an estimation of when this feature and its documentation will be available? So I can decide if I go back to 2.9 or if I should wait :wink:

**Comment by kindofone** [comment]
@yyx990803 Hey, we're using v3 beta1, and stumbled this issue too. How can we edit the webpack config (aside from downgrading to v2.9)?

**Comment by Ldoppea** [comment]
Hi @kindofone ,

The solution has been discussed here : https://github.com/vuejs/vue-cli/issues/589#issuecomment-361734701

Since the documentation has been created and can be found there : https://github.com/vuejs/vue-cli/blob/dev/docs/webpack.md

**Comment by kindofone** [comment]
@Ldoppea Awesome, thanks! ✌️

**Comment by dannyk08** [comment]
The links no longer work
Where can I find this?

**Comment by kushalmahajan** [comment]
I ran into this thread and earlier https://github.com/vuejs-templates/webpack/issues/215 
because of  vue styled components as they require the local registration of components. So how can I use them?
