### ISSUE TITLE
Programmatic access to API

### ISSUE THREAD

**Issue by termosa** [vuejs/vue-cli#748]
### What problem does this feature solve?
It will be easier to create tools that uses vue-cli

### What does the proposed API look like?
```js
import vue from 'vue-cli'

// run default behavior of vue-cli
vue.setup('template_name', 'app/path')

// run vue-cli but not asking for anything from users and using answers object instead
vue.setup('template_name', 'app/path', { / * answers */ })

// run vue-cli and trigger callback instead of use input
vue.setup('template_name', 'app/path', (question, next) => { /* ... */ })
```

**Comment by yyx990803** [comment]
We are unlikely to introduce new features to vue-cli 2.x.

In 3.x this is [already possible](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli/lib/create.js).

**Comment by termosa** [comment]
Oh, I didn't mention the version. I have expect it from v3. So, thank you then!

**Comment by OneQMobile** [comment]
So how exactly is one suppose to use that?
Because this doesn't work
```
const { create } = require('@vue/cli/lib')

module.exports = async serviceName => {
  process.stdin.setRawMode(true)
  await create(serviceName, {git:false})
}
```

**Comment by termosa** [comment]
@OneQMobile can you provide more information on what doesn't work for you?

**Comment by gregbenner** [comment]
@termosa I think he means, and I was wondering too, how do you properly require('@vue/cli/lib') etc in a node.js context to use it programmatically ?
I'm looking into starting the ui from a node.js script personally.
cheers
