### ISSUE TITLE
How to use globals variables in sass?

### ISSUE THREAD

**Issue by codermarcos** [vuejs/vue-cli#753]
### What problem does this feature solve?
How to use globals variables in sass - vue 2.5.13 / generate on vue/cli-service 3.0.0-alpha.5

### What does the proposed API look like?
Use globals variables in sass - vue 2.5.13 / generate on vue/cli-service 3.0.0-alpha.5

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/), [gitter](https://gitter.im/vuejs/vue) or [StackOverflow](http://stackoverflow.com/tags/vue.js).


---

The answer you're looking for is at https://vue-loader.vuejs.org/en/configurations/pre-processors.html 🙂

**Comment by yyx990803** [comment]
We will have dedicated documentation for this use case.

In brief, this is what you need:

``` js
// vue.config.js
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        data: fs.readFileSync('./src/variables.scss', 'utf-8')
      }
    }
  }
}
```

**Comment by WrenchDE** [comment]
scss: {
        'resolve url': true,
        import: ['./src/assets/css/variable']
      }

**Comment by WrenchDE** [comment]
module.exports = {
 css: {
    loaderOptions: {
      stylus: {
        'resolve url': true,
        import: ['./src/theme']
      },
      scss: {
        'resolve url': true,
        import: ['./src/assets/css/variable']
      }
    }
  },
}

**Comment by WrenchDE** [comment]
`
module.exports = {
  css: {
    loaderOptions: {
      stylus: {
        'resolve url': true,
        import: ['./src/theme']
      },
      scss: {
        'resolve url': true,
        import: ['./src/assets/css/variable']
      }
    }
  }
}
`

**Comment by WrenchDE** [comment]
css: {
    loaderOptions: {
      scss: {
        'resolve url': true,
        import: ['./src/assets/css/variable']
      }
    }
  },
