### ISSUE TITLE
vue.config.js can't work well

### ISSUE THREAD

**Issue by njzyfr** [vuejs/vue-cli#754]
### Version
3.0.0-alpha.5

### Reproduction link
[https://github.com/njzyfr/test-vue-cli](https://github.com/njzyfr/test-vue-cli)

### Steps to reproduce
1 vue create test-vue-cli
2 select Zero-config with defaults
3 cd  test-vue-cli
4 vim vue.config.js
5 vue.config.js 
const remoteIP = 'localhost:3333';
module.exports = {
  devServer: {
    port: 8888,
    proxy: {
      '/api*': {
        target: `http://${remoteIP}`,
      },
    },
  }
};
7 npm run serve

### What is expected?
open localhost:8888

### What is actually happening?
open localhost:8080

---
when I select  Manually select features and just select vuex, vue-router. I use the same vue.config.js, but it works well.
maybe it's babel compile problem.

**Comment by yyx990803** [comment]
You need to delete/migrate the vue field in package.json. There will be a warning for this in the future

**Comment by njzyfr** [comment]
That works for me. Thank you!
