### ISSUE TITLE
Can't find App.vue in typescript compile process

### ISSUE THREAD

**Issue by richardyou** [vuejs/vue-cli#758]
### Version
3.0.0-alpha.5

### Reproduction link
[https://github.com/richardyou/ts-vue-bugreport](https://github.com/richardyou/ts-vue-bugreport)

### Steps to reproduce
1. install and run serve
2.exit and run serve again and it went error

### What is expected?
successful compile

### What is actually happening?
 error  in ./src/views/Home.vue

Module build failed: Error: Could not find file: 'C:\Users\Desktop\MyProjects\ts-vue-bugreport\src\views\Home.vue'.

---
the declaration file has not changed,and the vue file is correctly declared

**Comment by yyx990803** [comment]
This is a `cache-loader` config error, we already fixed this and will be out in next alpha soon.

**Comment by dtrinh100** [comment]
Not sure if the error was reintroduced or not, but I am having the exact same issue in version 3.0.0-beta.6.
