### ISSUE TITLE
use custom index.html  

### ISSUE THREAD

**Issue by greenpdx** [vuejs/vue-cli#765]
### Version
3.0.0-alpha.5

### Reproduction link
[https://github.com/greenpdx/rustwasm](https://github.com/greenpdx/rustwasm)

### Steps to reproduce
npm install

npm run serve

### What is expected?
I added a index.html in the root directory, I want to use that html file

### What is actually happening?
the server is generating it own index.html

---
I am trying to load a opencv as wasm file inside a js file. I run out of memory if I try to import it because webpack tries to parse and optimize it. The example in opencvjs shows it added in the html file.

I want to use a custom index.html and add it there.

**Comment by yyx990803** [comment]
index.html is in the public directory.

**Comment by TAGC** [comment]
@yyx990803 What's the solution if I want to specify a different custom HTML file? For example, in my project I have a `demo/` subdirectory which is essentially a small project in its own right. In my project root directory, I define a `dev` npm script in `package.json`: `vue-cli-service serve demo/src/main.ts`.

I want my demo to use a custom HTML file that I've created as `<root>/demo/public/index.html`. However, running `npm run dev` makes it bundle `<root>/public/index.html` instead.

**Comment by yyx990803** [comment]
@TAGC for now you will have to use an env variable and conditionally modify the options for the HTML plugin in `vue.config.js`.

**Comment by TAGC** [comment]
Ah okay, fair enough.

**Comment by hguiney** [comment]
@yyx990803 Which env variable and options?

**Comment by TAGC** [comment]
@hguiney This worked for me

https://github.com/TAGC/vue-expandable-grid/blob/5a3f4562d5151989a71311ba5f16b4d0949a2bc4/vue.config.js#L1-L16

**Comment by xushnudbek20** [comment]
if I wrote `npm run dev` automatically opened `app.vue`. But i want change this, namely if I wrote `npm run dev` in my cmd then opened 'blogs.vue'

**Comment by tjcchen** [comment]
Thanks @TAGC, very helpful. I have a similar project works too. For someone who stuck at this place, please also refer to this repo:

https://github.com/tjcchen/vuex-best-practice
