### ISSUE TITLE
how to configure the eslint rule 'script-indent' in vue-cli

### ISSUE THREAD

**Issue by SilenceZeng** [vuejs/vue-cli#766]
* **vue-cli Version: 2.9.2**
i start the project width vue init webpack.the default indent in script tag is 0,but i want 2 spaces in SFC.i am confused about configure to disable the errors eslint throw(Expected indentation of 0 spaces but found 2).i have tried to add the follow eslint-plugin-vue 's rule to rules in eslintrc.js:
```
'vue/script-indent': ["error", 2, {"baseIndent": 1}]
```
the errors were still thrown,that i could not find which eslint plugin result in.
This may not be appropriate to add this issue here,forgive me for i don't know how to solve this problem and give some help please,thanks

**Comment by yyx990803** [comment]
This is a `eslint-plugin-vue` issue.

**Comment by SilenceZeng** [comment]
Thanks for your reply!At first i also thought it is a esint-plugin-vue issue,but the errors were still thrown event i have added 'vue/script-indent': ["error", 2, {"baseIndent": 1}] in eslintrc.js.Then i change the code in script tag to 0 indent,the eslint error will be "Expected indentation of 2 spaces but found 0 spaces".So it seems that the eslint-plugin-vue is working correctly,and i couldn't find out which eslint plugin throw errors if the indent is 2

**Comment by SilenceZeng** [comment]
sorry, it can be solved by adding the rule 'indent': 'off' too
