### ISSUE TITLE
Env variables don't seem to load from a .env file on the new cli

### ISSUE THREAD

**Issue by alexjoverm** [vuejs/vue-cli#767]
### Version
3.0.0-alpha.5

### Reproduction link
[https://github.com/alexjoverm/vue-cli-env-reproduce](https://github.com/alexjoverm/vue-cli-env-reproduce)

### Steps to reproduce
Clone, run `npm install` and `npm run serve` on the repo provided.

### What is expected?
According to the code of the [Service](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/Service.js#L61), some env variables should be loaded taken from a path, which are parsed on the [loadEnv](https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/util/loadEnv.js) util.

By adding some logs, it seems that indeed the path it takes when running `npm run serve` is `${rootDirectory}/.env.development` and `${rootDirectory}/.env.development.local`. They're indeed loaded. 

So, by the `console.log(process.env)` line in the main.js file, those variables should be printed in the console.

### What is actually happening?
They're not listed in the console.

Note: if this is not supposed how is it possible to add env variables?

**Comment by yyx990803** [comment]
Only variables that starts with `VUE_APP_` are loaded: https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/util/resolveClientEnv.js#L1

**Comment by irufus** [comment]
Why is this not part of the documentation?

**Comment by kispi** [comment]
> Why is this not at the very top part of the documentation?
> 
> Especially where you give your example
> 
> > FOO=bar
> > VUE_APP_SECRET=secret
> 
> FOO should be VUE_APP_FOO
> 
> Edited:
> It is documented but easily overlooked.

Yes I also overlooked

I was yelling on myself 'why it's not working!' like 10 minutes and eventually came here



*READ THE DOCUMENTATION*
"EACH AND EVERY CHARACTER"

**Comment by 3zzy** [comment]
For those who arrived here looking for a solution, but already use have your variables prefixed with `VUE_APP_`, just restart.

**Comment by gregfr** [comment]
> just restart.
This should be stressed out in the docs, I spent two hours figuring out why the documented example was not working...

**Comment by malandles** [comment]
I understand that the prefix is a good thing to have when your Vue app is coupled with another framework like Laravel, but when the app is standalone, the prefix requirement is a bit exagerated no?

Is there any other reason for the hard requirement? As I can see, we are not the first to overlook the requirement, and the docs are still showing `FOO=bar`.

**Comment by FernandoBasso** [comment]
I noticed that I cannot use it with Ramda.

This code...

```js
console.log(pathOr('what', ['env'], process));
console.log(pathOr('the', ['env', 'VUE_APP_TITLE'], process));
console.log(pathOr('poop 💩', ['env', 'VUE_APP_TITLE'], process));
```
...produces this output:

![image](https://user-images.githubusercontent.com/6560620/76711505-6838ef00-66ef-11ea-8460-c1d50d1e3c0e.png)

**Comment by dagrooms52** [comment]
> Note that only NODE_ENV, BASE_URL, and variables that start with VUE_APP_ will be statically embedded into the client bundle with webpack.DefinePlugin.

I read this sentence while setting up a `.env` file and still did not realize that my variable needed to start with `VUE_APP_` to be applied when I run `npm run serve`, taking me to google for this issue. The docs probably need to clarify this point.

**Comment by MariaIm** [comment]
Use touch to create your environment files.
Install touch with `npm install touch-cli -g`
Create your environment files in root folder with `touch .env.production` and `touch .env.development`

**Comment by towry** [comment]
In development mode, make sure the env file name is correct(not misspelled): ".env.development" or ".env.development.local".

**Comment by andyslack** [comment]
> I understand that the prefix is a good thing to have when your Vue app is coupled with another framework like Laravel, but when the app is standalone, the prefix requirement is a bit exagerated no?
> 
> Is there any other reason for the hard requirement? As I can see, we are not the first to overlook the requirement, and the docs are still showing `FOO=bar`.

Totally agree with this.

**Comment by pushpesh4u** [comment]
To anyone who is still not getting it to work, please make sure your env files (.env, .env.development, .env.development.local, .env.production) have a `UTF-8` encoding. My files had a `UCS-2 LE BOM` encoding and vue was silently ignoring them.

They started working after changing to `UTF-8`.

**Comment by fokosun** [comment]
still freaking undefined!

**Comment by jakedurell** [comment]
This is working for me fine on mac with VUE 2.6.11 in package.json and a .env. When running npm run serve, the .env loads and keys work. This same thing is not working on windows.

**Comment by EuniceB** [comment]
Also make sure the .env file is in the root of the project, and not inside src

**Comment by adeyinkakoya** [comment]
> Use touch to create your environment files.
> Install touch with `npm install touch-cli -g`
> Create your environment files in root folder with `touch .env.production` and `touch .env.development`

The only thing that worked
