### ISSUE TITLE
Template compiler is not available

### ISSUE THREAD

**Issue by yooouuri** [vuejs/vue-cli#768]
### Version
3.0.0-alpha.6

### Reproduction link
[https://gist.github.com/yooouuri/07949278d01a55035756eda8200b2614](https://gist.github.com/yooouuri/07949278d01a55035756eda8200b2614)

### Steps to reproduce
```
vue create <name>
```

After it add the vue router and create a component with a router-view and some router-links

### What is expected?
Router should work

### What is actually happening?
```
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
```

**Comment by yyx990803** [comment]
Add `{ compiler: true }` in `vue.config.js`.

**Comment by Pwntus** [comment]
**FYI**
It is now called `{ runtimeCompiler: true }` in `vue.config.js`.
