### ISSUE TITLE
今天有vue cli webpack 搭建了个项目，结果打包出来路径全错了

### ISSUE THREAD

**Issue by pencil2014** [vuejs/vue-cli#77]
打包出来变成这样了：
![1](https://cloud.githubusercontent.com/assets/10042880/14519767/8365f584-0253-11e6-8b23-e2a61684ef60.png)
![2](https://cloud.githubusercontent.com/assets/10042880/14519826/d1b84c1e-0253-11e6-8a55-83d4c4dad5b0.png)

代码里是这样的：
![3](https://cloud.githubusercontent.com/assets/10042880/14519831/d89cfc8c-0253-11e6-9d2f-9479ca36bce5.png)
![4](https://cloud.githubusercontent.com/assets/10042880/14519882/0f890632-0254-11e6-86a2-e6c3dcffeafa.png)

请问这是怎么回事？

**Comment by yyx990803** [comment]
升级下新建就好了

**Comment by arixse** [comment]
项目的静态文件根目录是什么
