### ISSUE TITLE
`vue-cli-version-marker` not updated to alpha 7

### ISSUE THREAD

**Issue by jarrodldavis** [vuejs/vue-cli#772]
### Version
3.0.0-alpha.7

### Reproduction link
[https://www.npmjs.com/package/vue-cli-version-marker](https://www.npmjs.com/package/vue-cli-version-marker)

### Steps to reproduce
Go to the [npm package page for `vue-cli-version-marker`](https://www.npmjs.com/package/vue-cli-version-marker) and compare its version to that of [`@vue/cli`](https://www.npmjs.com/package/@vue/cli).

### What is expected?
Both packages are the same, latest version (`3.0.0-alpha.7`).

### What is actually happening?
While all of the `@vue`-scoped packages were updated, `vue-cli-version-marker` is not.

---
I noticed that you [updated all of the packages to 3.0.0-alpha.7](https://github.com/vuejs/vue-cli/commit/5cdc07cd2144b81f0aa60aa01248b4b2687b1245) yesterday with the exception of `vue-cli-version-marker`. I just wanted to make sure you were aware in case you needed to update your lerna config.

**Comment by yyx990803** [comment]
Ah, thanks for catching that. Yes, I missed it in the yarn workspace config so it was skipped by Lerna.
