### ISSUE TITLE
Jest hangs indefinitely

### ISSUE THREAD

**Issue by dunglas** [vuejs/vue-cli#777]
### Version
3.0.0-alpha.8

### Reproduction link
[https://github.com/dunglas/test-again](https://github.com/dunglas/test-again)

### Steps to reproduce

```
$ vue create foo
# Select "Unit testing" then "jest"
$ cd foo
$ yarn test
```

### What is expected?
The dummy test in the skeleton should run

### What is actually happening?
```
$ yarn test
  yarn run v1.3.2
  $ vue-cli-service test

  ... never returns, displays nothing
```
---
Mac   zsh

**Comment by yyx990803** [comment]
Hmm, this may be a zsh specific issue... since I can run it without a problem in bash.

**Comment by dunglas** [comment]
I've the same problem using `bash`, and when invoking `jest` directly. I'll try to go deeper in the investigation

**Comment by oldskool73** [comment]
not much help, but with `cli-service 3.0.0-alpha.8`, `zsh 5.4.2 (x86_64-apple-darwin15.6.0)` and OSX Sierra, running `yarn test` in a brand new cli project works fine for me.

**Comment by dunglas** [comment]
Closing for now, it's probably on my side, I'll investigate.

**Comment by dunglas** [comment]
Just in case someone find this issue on GitHub, the issue was related to https://github.com/facebook/jest/issues/4529

Quick fix: `brew uninstall watchman`
