### ISSUE TITLE
after build find background url path is wrong

### ISSUE THREAD

**Issue by cloudshadow** [vuejs/vue-cli#78]
This is my project struct
|------src
|------|------assets
|------|------|------bg.jpg
|------|------views
|------|------|------index.vue
|------|------app.vue
|------|------main.js

i write css in index.vue

body{
  background: url('../assets/bg.jpg') no-repeat;
  background-size: cover;
  font-size: 62.5%;
}

After i run "npm run build"
i find dist folder struct like this
|------dist
|------|------static
|------|------|------bg.jpg
|------|------|------app.xxx.js
|------|------|------app.xxx.css
|------|------index.html

but in app.xxx.css i find the bg.jpg's path is background:url(./static/bg.jpg?1b5ca27)
i think it is wrong.
how can i to fixed it?

And all build option i used default setting

**Comment by zigomir** [comment]
@cloudshadow which template did you use?

**Comment by cloudshadow** [comment]
@zigomir i used default template like this:

<template>
  <div class="about-page container-fluid">
  </div>
</template>

**Comment by zigomir** [comment]
@cloudshadow sorry, I meant template for `vue-cli` ... I'm guessing you used one from: https://github.com/vuejs-templates but I'm not sure know which one.

**Comment by cloudshadow** [comment]
@zigomir i think is webpack

**Comment by yyx990803** [comment]
It seems you are using a relative `publicPath`. `publicPath` should be a root-relative path like `/static` instead of `./static`.

**Comment by cloudshadow** [comment]
@yyx990803 thx, i try it now.

**Comment by cloudshadow** [comment]
@yyx990803 work for me! thanks a lot
