### ISSUE TITLE
Component gets re-rendering when adding/removing new lines in template

### ISSUE THREAD

**Issue by cristijora** [vuejs/vue-cli#783]
### Version
3.0.0-alpha.8

This is a reopening of #738 since it was closed but still reproducible.

### Reproduction link
[https://github.com/cristijora/vue-cli-state-refresh](https://github.com/cristijora/vue-cli-state-refresh)

### Steps to reproduce
1. Init repo
2. Type something in the input
3. Add a new line/tag anywhere in the template. See gif below
4. Save the file

### What is expected?
Input state is preserved as in the old webpack template.

### What is actually happening?
The edited component gets a full re-render and the previous state is lost. Input is empty after changing something modifying the component. See gif below

![jan-28-2018 10-43-35](https://user-images.githubusercontent.com/15955045/35480503-30c4afa0-0418-11e8-902c-aed46878e8f3.gif)

**Comment by samundrak** [comment]
Did you use any state management (Vuex) before?

**Comment by cristijora** [comment]
No vuex here. It's bare bones Vue.

**Comment by yyx990803** [comment]
I think this is related to the virtual dom patching behavior when newlines/whitespaces are inserted. This can only be fixed in core, but since this is such an edge case it will be a pretty low priority item.
