### ISSUE TITLE
How to add PUG and SCSS support to the Zero-config Prototyping setup?

### ISSUE THREAD

**Issue by pbastowski** [vuejs/vue-cli#786]
### What problem does this feature solve?
I am using `vue serve` for fast prototyping and I would like to use PUG and SCSS in my templates. So, I added the relevant npm packages to the global package.json for @vue/cli-service-global. This works just fine for now, but when I update to a new version of my changes are overwritten.

Hence the question: how can I add PUG and SCSS to `vue serve`, so that it will stick through updates?

I love the zero-config feature :)

Thanks.

### What does the proposed API look like?
I don't have a proposal other than adding to the package.json for @vue/cli-service-global.

**Comment by yyx990803** [comment]
You can just use a local `package.json` and install those deps locally.

**Comment by pbastowski** [comment]
Fantastic :) Thanks.
