### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by brunoseco** [vuejs/vue-cli#787]
How can I configure my environment variables in this new cli? For example, BASE_URL, ENDPOINT_API?

Thanks.

**Comment by yyx990803** [comment]
Use `.env` files. Variations like `.env.[.mode][.local]` are also supported. Also, only variables starting in `VUE_APP_` will be available in the app.

There will be more documentation on this soon.

**Comment by brunoseco** [comment]
Thanks dude,

But how can I replace BASE_URL?

**Comment by LinusBorg** [comment]
> There will be more documentation on this soon.

As Evan just told you: Use a `.env` file. If you don't know what that is - it's a file that contains env variables just like you write them in your terminal:
```
BASE_URL=http://google.com/
```

**Comment by yyx990803** [comment]
`BASE_URL` should be configured in `vue.config.js`, since it's also needed by the cli-service:

``` js
module.exports = {
  baseUrl: '/foo'
}
```

**Comment by brunoseco** [comment]
> As Evan just told you: Use a .env file. If you don't know what that is - it's a file named .env, in your project's root directory, that contains env variables just like you write them in your terminal:

I know what is that.

Actually, .env file just allow variables that starts with VUE_APP_ ;)

**Comment by sylvaincaillot** [comment]
Hello I just tried  something similar by setting up a .env.development and a .env.production files in my app. My .env.development file looks like:

```
NODE_ENV: '"development"'
VUE_APP_API: '"http://localhost:2096/api/"'
VUE_APP_DEBUG=true
```
As specified in the docs, I have used variables starting with `VUE_APP_`

However, if i do
```
console.log(process.env.VUE_APP_API)
```
it returns undefined  while it should return http://localhost:2096/api/

Any thoughts?

**Comment by antonelepfl** [comment]
Hello, 
Regarding to the ENV I would like to use in the app some variables from **Jenkins** for example.

When in `vue.config.js` I do `console.log('Commit:', process.env.GIT_COMMIT)` I get it **correctly**.

In `.vue` files `process.env` is **only** replaced by 
```javascript
Object({
   NODE_ENV: "production"
})
```
I read about the `.env` but I don't know how to put _variables_ there. What is the correct way to do it?

**Comment by phoet** [comment]
just FYI

**Comment by antonelepfl** [comment]
Thanks @phoet in the end I made it work with the change below in `vue.config.js`

``` javascript
module.exports = {
  configureWebpack: {
    ...,
    plugins: [
      new webpack.DefinePlugin({
        'process.env': {
          'GIT_COMMIT': JSON.stringify(process.env.GIT_COMMIT),
          'GIT_BRANCH': JSON.stringify(process.env.GIT_BRANCH)
        }
      })
    ]
  }
}
```

And then using it like `process.env.GIT_COMMIT` in some `.js`

**Comment by antonelepfl** [comment]
I have done another thing that probably is not really good but it works too.

In `package.json`:
```
"scripts": {
  "build": "VUE_APP_ANNOTATION_VERSION=$(npm run --silent getAnnotationVersion) vue-cli-service build",
  "getAnnotationVersion": "node ./custom-script.js'"
},
```

And in `custom-script.js`
```
const {readFile} = require('fs');

function getAnnotationVersion() {
  readFile('../version.py', 'utf8', function(err, data) {
    if (err) {
      return console.log(err);
    }
    let reg = /.*VERSION.+'(.*)'/;
    let found = data.match(reg);
    if (found.length > 1) console.log(found[1]);
  });
}

getAnnotationVersion();
```

**Comment by bdiz** [comment]
Does support for .env[mode][local] require we add dotenv library? I have a .env.development file in my app root with an environment variable using the VUE_APP_ prefix and it does not get loaded.

**Comment by bdiz** [comment]
No dotenv required I see: https://github.com/vuejs/vue-cli/blob/dd39866cad4385b284782428abcbd554f131e1ab/packages/%40vue/cli-service/lib/Service.js#L58

Sorry, I was not running with the right mode to load my .env.development file. ie `vue-cli-service test:e2e --mode development`

**Comment by RDeluxe** [comment]
I've been looking for this information around but could not find it.

If I create a real env variables (during my Gitlab pipeline for example) such as `VUE_APP_API_URL`, will this variable take priority from the .env files ?

.env files should never contain sensible data, and thus sensible data should be provided by Jenkins/Gitlab/etc. It's not clear if the `.env` file from vue are working like dotenv ones

**Comment by yyx990803** [comment]
Existing env variables have highest priority.

**Comment by RDeluxe** [comment]
Sadly, after testing it seems it is not the case.

` echo "$VUE_APP_API_URL"` will give me the correct output before a `yarn build`, so I would expect the variable to be correctly replaced in the build.

**Comment by cbo317110** [comment]
We need this in DOC 🤔

**Comment by LinusBorg** [comment]
@RDeluxe Hard to make anything from such a blanket statement. Can you provide a reproduction?

Also, maybe you simply aren't on the latest version? We only fixed this in the last beta before RC or soemthing.

**Comment by RDeluxe** [comment]
Sorry. The repro is quite simple : 

* Create an .env file with a variable, such as `VUE_APP_VAR = myvar`
* Add it to the webpack defines in vue.config.js. For now it's fine
* Define an env variable (ie in windows `SET VUE_APP_VAR = mysecondvar`)
* Build, and check. For me, it was still equals to `myvar`

We are using `3.0.0-beta.15`

**Comment by Akryum** [comment]
> Add it to the webpack defines in vue.config.js. For now it's fine

You shouldn't do this.

**Comment by LinusBorg** [comment]
> Add it to the webpack defines in vue.config.js. For now it's fine

We introduced .env file so you don't have to do this, why would you?

> We are using 3.0.0-beta.15

... and we changed priority for env variables in beta.16:

https://github.com/vuejs/vue-cli/blob/dev/CHANGELOG.md#300-beta16-2018-06-08

> * env: preserve existing env vars so load in reverse order. (#1503) (7c1ef24)

**Comment by RDeluxe** [comment]
Sorry, just a reflex, does not change anything in the end I guess, but the behavior was the same anyway, and it seems the explanation was simply the version we were using ! Thanks.

**Comment by PrimozRome** [comment]
We are deployin vue-cli3 app od Digital Ocean trough Laravel Forge and the `.env` variables are not read. Locally in development environment works fine but on the DO server not. Anyone knows what is the issue?

We have followed this guide as well https://alligator.io/vuejs/using-new-vue-cli-3/#environment-variables but we can not find the solution.

**Comment by pavinduLakshan** [comment]
> 
> 
> Thanks @phoet in the end I made it work with the change below in `vue.config.js`
> 
> ```js
> module.exports = {
>   configureWebpack: {
>     ...,
>     plugins: [
>       new webpack.DefinePlugin({
>         'process.env': {
>           'GIT_COMMIT': JSON.stringify(process.env.GIT_COMMIT),
>           'GIT_BRANCH': JSON.stringify(process.env.GIT_BRANCH)
>         }
>       })
>     ]
>   }
> }
> ```
> 
> And then using it like `process.env.GIT_COMMIT` in some `.js`

This worked really well for me..But it would be great if there's a way in which variables can be directly read from .env file.

**Comment by LinusBorg** [comment]
But there is, we have a big section about it in the docs

**Comment by pavinduLakshan** [comment]
> 
> 
> We need this in DOC 🤔

Now it's in the doc.see [here](https://cli.vuejs.org/guide/mode-and-env.html#modes).Thanks @LinusBorg for letting me know about that.

**Comment by LinusBorg** [comment]
I has always been in the docs.

**Comment by Akryum** [comment]
https://github.com/vuejs/vue-cli/commit/dfb25830e19cb17a0ff3c3516409c0487cad6dbe#diff-eed3c9cd8ce5593f9de87fdeab03be11R33
`8 Feb 2018` 😹

**Comment by SouthRibbleTech** [comment]
I have the following in a .env file in the root of my project
```
VUE_APP_SERVER_URI = http://localhost:3333/api/v1
VUE_APP_SERVER_URL = TestString`
```

When I do console.log(process.env) in my App.vue file, I don't see the variables

This is the output

```
{NODE_ENV: "development"}
NODE_ENV: "development"
__proto__: Object
```

Any idea why vue might not be loading my environment variables?

**Comment by lexicalninja** [comment]
> I have the following in a .env file in the root of my project
> 
> ```
> VUE_APP_SERVER_URI = http://localhost:3333/api/v1
> VUE_APP_SERVER_URL = TestString
> ```
> 
> When I do console.log(process.env) in my App.vue file, I don't see the variables
> 
> This is the output
> 
> ```
> {NODE_ENV: "development"}
> NODE_ENV: "development"
> __proto__: Object
> ```
> 
> Any idea why vue might not be loading my environment variables?

I am having the same issue. It's getting a little frustrating

**Comment by pavinduLakshan** [comment]
> 
> 
> > I have the following in a .env file in the root of my project
> > ```
> > VUE_APP_SERVER_URI = http://localhost:3333/api/v1
> > VUE_APP_SERVER_URL = TestString
> > ```
> > 
> > 
> > When I do console.log(process.env) in my App.vue file, I don't see the variables
> > This is the output
> > ```
> > {NODE_ENV: "development"}
> > NODE_ENV: "development"
> > __proto__: Object
> > ```
> > 
> > 
> > Any idea why vue might not be loading my environment variables?
> 
> I am having the same issue. It's getting a little frustrating

Didn't you try this? https://github.com/vuejs/vue-cli/issues/787#issuecomment-390899673

**Comment by dvlden** [comment]
@yyx990803 Hey Evan, how can I tell my `vue.config.js` to change the precedence of the `.env` variables? I want to set that `.env.local` and/or `.env.[mode].local` have the highest priority and if the same variable is defined elsewhere, it'd be ignored.

Is this possible?

> Reason: I want to use `.env` for the production environment, `.env.development` for the development environment (duh) and locally while "developing" to pass some extra and some override variables within `.env.local`

**Comment by Angular-Mast** [comment]
I tried this [#787 (comment)(https://github.com/vuejs/vue-cli/issues/787#issuecomment-390899673) but it was not working....

**Comment by Angular-Mast** [comment]
I tried to stop node server and restarted node server...

`npm run serve`

of course, after editing vue.config.js and it is working fine...

**Comment by mpan-wework** [comment]
You can take a look at following and write your own `chainWebpack`.

https://github.com/vuejs/vue-cli/blob/eaa2b73/packages/%40vue/cli-service/lib/Service.js#L90-L106
https://github.com/vuejs/vue-cli/blob/01e36f3/packages/%40vue/cli-service/lib/util/resolveClientEnv.js
https://github.com/vuejs/vue-cli/blob/5bf6051/packages/@vue/cli-service/lib/config/base.js#L192-L197
