### ISSUE TITLE
yarn --registry is error command when create new project 

### ISSUE THREAD

**Issue by ws456999** [vuejs/vue-cli#789]
### Version
3.0.0-alpha.8

### Reproduction link
[https://github.com/vuejs/vue-cli](https://github.com/vuejs/vue-cli)

### Steps to reproduce
command-line output：

```
Vue CLI v3.0.0-alpha.8
✨  Creating project in /Users/a39/Desktop/profile/new-vue.
🗃  Initializing git repository...
⚙  Installing CLI plugins. This might take a while...


  error: unknown option `--registry'

 ERROR  command failed: yarn --registry=https://registry.npm.taobao.org
```

### What is expected?
when i use yarn and select taobao source

use:
```
yarn config set registry https://registry.npm.taobao.org
```

### What is actually happening?
when i use yarn and select taobao source

```
yarn --registry=https://registry.npm.taobao.org
```

**Comment by ws456999** [comment]
btw: how can i clear the cache of the  taobao source selection?

**Comment by yyx990803** [comment]
@ws456999 in `~/.vuerc`, set `useTaobaoRegistry` to `false`
