### ISSUE TITLE
proxy 配置 ajax 请求怎么无效呢 

### ISSUE THREAD

**Issue by geekpeng** [vuejs/vue-cli#79]
vue-cli 生成的项目,配置代理没有作用...  求解答:

配置是参数这个文档来的

http://vuejs-templates.github.io/webpack/proxy.html

配置了代理但还是请求到了localhost

使用的是
http-proxy-middleware

====================

知道是怎么回事了, 因为开了VPN

**Comment by mlyknown** [comment]
+1

**Comment by zzmm1** [comment]
https://forum-archive.vuejs.org/topic/5129/vue-cli%E7%9A%84proxytable%E4%BB%A3%E7%90%86%E6%97%A0%E6%95%88/2

同样的问题。

**Comment by Pines-Cheng** [comment]
+1，有人解决了吗？

**Comment by chordmo** [comment]
放在main.js就可以。

**Comment by morrain** [comment]
+1
