### ISSUE TITLE
install vue-cli failed

### ISSUE THREAD

**Issue by justyeh** [vuejs/vue-cli#792]
### Version
2.9.3

### Steps to reproduce
```npm i -g vue-cli```

failed

```npm config set registry https://registry.npm.taobao.org```

```npm i -g vue-cli```

failed

### What is expected?
vue-cli should install

### What is actually happening?
vue-cli install failed , here is error log

```
npm ERR! path C:\Users\54657645\AppData\Roaming\npm\node_modules\vue-cli\node_modules\get-stream
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'C:\Users\54657645\AppData\Roaming\npm\node_modules\vue-cli\node_modules\get-stream'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

---
I tried to set npm register to 'https://registry.npm.taobao.org' , but it is not useful.

**Comment by yyx990803** [comment]
Cannot reproduce. This is not something we can fix.

**Comment by vikapitoshka** [comment]
@justyeh , hi! You solved the problem?

**Comment by justyeh** [comment]
yeh , it is caused by  the network environment of my company
