### ISSUE TITLE
Hope to add TSX support.

### ISSUE THREAD

**Issue by wolfstark** [vuejs/vue-cli#793]
### What problem does this feature solve?
When enabling typescripts, I hope to add TSX support, which is necessary when creating feature components

### What does the proposed API look like?
Work like this：
![image](https://user-images.githubusercontent.com/15010463/35896744-b1b73316-0bf8-11e8-9963-ca161ba5ae75.png)

**Comment by yyx990803** [comment]
What's preventing you from configuring it yourself?

**Comment by yyx990803** [comment]
Wait, it already works... just use `.tsx` extension.
