### ISSUE TITLE
能不能添加一个vue打包成webapp模式的路径选择

### ISSUE THREAD

**Issue by hearsay316** [vuejs/vue-cli#797]
### What problem does this feature solve?
1 平时喜欢将自己写的小网站用hubilder打包成app 
2 在vue cli 2.0 需要将config下的index.js 的 build 改成 assetsPublicPath: './', 

### What does the proposed API look like?
1 在vue cli 3.0中能不能添加这个模式 , 将打包后的html里的引用文件自动加'./ ' 
```
<link rel=preload as=script href=/js/vendor.6c050399.js>
```
变成
```
<link rel=preload as=script href=./js/vendor.6c050399.js>
```
2 css里的引用从
```
@font-face{font-family:HelveticaThin;src:url(/fonts/HelveticaThin.1570d2f0.ttf)}
```
变成
```
@font-face{font-family:HelveticaThin;src:url(../fonts/HelveticaThin.1570d2f0.ttf)}
```
这样就能用打包软件将npm run build 之后的文件直接打包成app

**Comment by yyx990803** [comment]
用 `vue.config.js` 配置:

``` js
module.exports = {
  baesUrl: './'
}
```

**Comment by licong96** [comment]
@yyx990803 大神，我偷了个懒，直接复制你的代码，结果报个错，我发现你的单词拼错了，你会不会打死我？文档里的是`baseUrl`
