### ISSUE TITLE
ENOENT: no such file or directory, stat 'xxx/webpack/template'

### ISSUE THREAD

**Issue by djyde** [vuejs/vue-cli#8]
![image](https://cloud.githubusercontent.com/assets/914329/12082068/f18c94a0-b2c6-11e5-8f91-14d9758221d0.png)

**Comment by yyx990803** [comment]
fixed in 1.1.1

**Comment by migueljteixeira** [comment]
I'm having the same problem..

![captura de ecra 2016-04-13 as 17 57 49](https://cloud.githubusercontent.com/assets/1232161/14502145/cce82c48-01a1-11e6-8512-914ec654cba0.png)

**Comment by pipi32167** [comment]
Same problem again! @yyx990803 

![image](https://cloud.githubusercontent.com/assets/1400806/17977437/4cb67d9e-6b24-11e6-9849-253b33a0dcc7.png)

**Comment by zhkzyth** [comment]
I got the same problems with follow envs:
```
➜  code vue -V
2.3.1
➜  code node -v
v5.10.0
```

**Comment by ThemeWP** [comment]
**Try this:**
mkdir my-project
cd my-project
vue init webpack

**Comment by zhkzyth** [comment]
@ThemeWP It worked finally~~Thanks ThemeWp.
