### ISSUE TITLE
node版本为4.4.3是否可以使用vue cli？

### ISSUE THREAD

**Issue by dianxiacun** [vuejs/vue-cli#80]

**Comment by mlyknown** [comment]
这个和node版本没啥关系吧。。

**Comment by yyx990803** [comment]
4 以上应该都可以，你自己试下不就知道了...

**Comment by dianxiacun** [comment]
是因为我用vue cli创建了个webpack项目，然后npm install完后要run dev，会有其他依赖库未安装。所以提出了这个问题，以为跟node或npm的版本相关。
