### ISSUE TITLE
net::ERR_FILE_NOT_FOUND on "npm run build"

### ISSUE THREAD

**Issue by marco-carvalho** [vuejs/vue-cli#802]
### Version
3.0.0-alpha.9

### Reproduction link
[http://github.com/marco-carvalho/lastfm](http://github.com/marco-carvalho/lastfm)

### Steps to reproduce
> npm run build
> open dist/index.html

### What is expected?
strings of src/href between quotation marks and with the initial dot

ex: src="./js/vendor.2f9a9ad9.js"

### What is actually happening?
strings of src/href **without** quotation marks **and without** initial dot

ex: src=/js/vendor.2f9a9ad9.js

**Comment by yyx990803** [comment]
Cannot reproduce. I cloned your repo, did fresh install + build and the dist loads without error. Make sure you are serving the `dist` folder with an HTTP server. Also, the src without quote is perfectly valid HTML and is a result of HTML minification. It's not related to the error you are seeing.
