### ISSUE TITLE
Vue-cli made project doesn't detect already running dev server on the same port

### ISSUE THREAD

**Issue by mrg0lden** [vuejs/vue-cli#803]
### Version
3.0.0-alpha.9

### Reproduction link
[https://github.com/mrg0lden/vue-cli-bug](https://github.com/mrg0lden/vue-cli-bug)

### Steps to reproduce
run another project that uses webpack dev server (I used a vue project that's made with vue-cli v2)
run "yarn serve" on the new project that's made with vue-cli v3
the first one will be already serving on :8080
the second one will -somehow- serve to the same port
the first project shows up in the browser.

### What is expected?
To serve on another port or at least give an error

### What is actually happening?
It does neither.

**Comment by yyx990803** [comment]
Cannot reproduce. I did exactly what you did and the new CLI was able to launch on port 8081.

Please provide more information regarding your OS - this maybe an issue in https://github.com/indexzero/node-portfinder
