### ISSUE TITLE
index页面可配置

### ISSUE THREAD

**Issue by zhaojh329** [vuejs/vue-cli#805]
### What problem does this feature solve?
index页面可配置

### What does the proposed API look like?
{
    index: 'vuci.html'
}

**Comment by yyx990803** [comment]
为了确保项目的一致性，不打算提供这样的功能。

**Comment by zhaojh329** [comment]
但是我的项目真的需要这个功能。老版本可以通过webpack配置文件配置，希望新版本支持配置。

**Comment by yyx990803** [comment]
``` js
module.exports = {
  chainWebpack: config => {
    config.plugin('html').tap(args => {
      args[0].template = 'vuci.html'
      return args
    })
  }
}
```

**Comment by zhaojh329** [comment]
@yyx990803 你好，我按照你提供的配置，但运行抱错：
> my-project@0.1.0 serve /home/zjh/my-project
> vue-cli-service serve

 INFO  Starting development server...
 94% asset optimization                                                              

 ERROR  Failed to compile with 1 errors                                                                                                                       00:57:27

 error

**Comment by zhaojh329** [comment]
知道问题了，需要指定全路径。但vue-cli没有提示错误原因。

**Comment by karneaud** [comment]
+1
