### ISSUE TITLE
Option to disable polyfills through babel-preset-env

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-cli#812]
### What problem does this feature solve?
The `@vue/app` preset will always bundle any needed polyfills. An alternative to including polyfills via Babel is the polyfill.io service, which will only serve polyfills if the browser actually needs them, thus vastly reducing total bundle size for most visitors.

For users that want to use this service, could we provide an option to disable polyfills through babel-preset-env?

### What does the proposed API look like?
I see a few solutions:

- A: Simply document how to solve the problem in `.babelrc` if that's feasible without potentially breaking with the `@vue/app` preset.
- B: Create a new preset called something like `@vue/app-no-polyfills`.
- C: Provide an option in `vue.config.js` to disable polyfills.

I don't have a strong preference on which of those strategies is used.

**Comment by LinusBorg** [comment]
I think piping the `useBuiltIns`option through the vue-app preset to the preset env options should be easy enough and worth it.

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/babel-preset-app/index.js#L20

should become
```javascript
useBuiltIns: options.useBuiltIns || 'usage'
```

...and the option should be documented in README

**Comment by chrisvfritz** [comment]
@LinusBorg I like that. I'm wondering if taking it a step further would be even better though, e.g.:

``` js
{
  "presets": [
    ["@vue/app", { "bundlePolyfills": false }]
  ]
}
```

This way, the option basically explains itself and users don't have to know about the implementation detail of `useBuiltIns`. _And_, we also retain the freedom to change how we bundle polyfills in the future without it being a breaking change for users. What do you think?
