### ISSUE TITLE
Should formatting with Prettier be a separate option from linting?

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-cli#816]
It doesn't seem to currently be possible to use Prettier with an ESLint config like Standard or AirBnb, but I think that's a pretty common use case. For that reason, I'm thinking we should possibly ask about formatting separate from linting, and then we can also use config-specific overrides where appropriate, like [`prettier/standard`](https://github.com/prettier/eslint-config-prettier#installation).

**Comment by yyx990803** [comment]
I think the line between linting and formatting is pretty blurry nowadays, with `eslint --fix` being able to fix a wide range of rules. Using Prettier with another ESLint config with stylistic rules also doesn't feel like super common to me.

The user can always manually install additional configs to use on top of the `@vue/prettier` config, or just completely use their own config. We don't necessarily have to bake everything in the out of the box configs.
