### ISSUE TITLE
incomplete dependencies with project created by 3.0.0-alpha.11

### ISSUE THREAD

**Issue by lzp4ever** [vuejs/vue-cli#822]
### Version
3.0.0-alpha.11

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
1. create a project by vue cli 3.0.0-alpha.11
2. delete node_modules folder
3. reinstall dependencies with `npm install`
4. run `npm run serve`

### What is expected?
build & run dev server

### What is actually happening?
have error below
```
Module build failed: Error: Cannot find module '@vue/babel-preset-app'
```

and have to install `@vue/babel-preset-app` manually

**Comment by yyx990803** [comment]
Cannot reproduce. `@vue/babel-preset-app` is a dependency of `@vue/cli-plugin-babel`, so it can't be missing. Make sure you are using an up-to-date version of npm.
