### ISSUE TITLE
vue文件中的import没有被解析

### ISSUE THREAD

**Issue by Riokai** [vuejs/vue-cli#83]
```shell
➜  fe-test-bank git:(master) ✗ node -v
v5.9.1
➜  fe-test-bank git:(master) ✗ npm -v
3.6.0
➜  fe-test-bank git:(master) ✗ vue -V
2.0.2
```

使用vue-cli正常生成脚手架，vue文件中写的import不会转成ES5代码，直接报错。下面贴代码
![qq20160424-0 2x](https://cloud.githubusercontent.com/assets/7970372/14766974/4de6bbc6-0a4d-11e6-8bb8-a0cee2ac60e5.png)
![qq20160424-1 2x](https://cloud.githubusercontent.com/assets/7970372/14766983/79f3fe04-0a4d-11e6-8340-038386886a21.png)
![qq20160424-2 2x](https://cloud.githubusercontent.com/assets/7970372/14766984/7ba4dd72-0a4d-11e6-9161-d76eeb74ab25.png)
![qq20160424-3 2x](https://cloud.githubusercontent.com/assets/7970372/14766985/7c7938ec-0a4d-11e6-8e4d-d3226dfe57ac.png)

![qq20160424-4 2x](https://cloud.githubusercontent.com/assets/7970372/14766998/c8c50e88-0a4d-11e6-8de1-e81513e4fece.png)

还有一个问题，为什么2.X版本这里新增了一个babel-runtime包，我记得1.X版本没有这个。而且在浏览器r指定babel应该是不推荐的操作。

**Comment by mlyknown** [comment]
命令行里面没报错吗 0.0

**Comment by yyx990803** [comment]
列下你的 npm list --depth=0

**Comment by Riokai** [comment]
@yyx990803 问题已经解决，看起来是我代码写的有问题
```shell
├── data
│   ├── api.js
│   └── index.js
```

api.js
```js
export const API = {
  login: '/permission/json_web_token',
  student: {

  },
  teacher: {

  },
  admin: {

  }
}
```

index.js
```js
export * from './api'
```

只要把`index.js`修改成`export { API } from './api'`，就不会再报import错误。应该是我的写法有问题，不过webpack也没有提示，所以弄的我找不到问题所在。
