### ISSUE TITLE
Electron browserify boilerplate as template

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [vuejs/vue-cli#84]
I have built this boilerplate to get started writing desktop apps, without the frontend js / dev setup hassle. Since I have no plans maintaining it, but find it kind of cool I would offer it to port it as template.

Hit me up if you wanna have it.

https://github.com/eljefedelrodeodeljefe/vue-electron-boilerplate

**Comment by zigomir** [comment]
@eljefedelrodeodeljefe cool! I think it would be nice to extract it into a template yes. You might just need to put all the contents inside `template` dir and add a `meta.json` to the root.

Later on you can put a link to https://github.com/vuejs/awesome-vue or maybe even get it on list of official templates on https://github.com/vuejs-templates

**Comment by eljefedelrodeodeljefe** [comment]
Okay, understood. Will do so then! Thx

**Comment by chrisvfritz** [comment]
@eljefedelrodeodeljefe Adding to @zigomir's excellent advice to organize the template so that it can be used by `vue-cli` - once that's done, I'd be happy to add a "Community Templates" section to the README, with yours as the first item. 😃
