### ISSUE TITLE
Automatic plugin install

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue-cli#844]
When running the `vue invoke <name>` command, vue-cli could automatically install the `@vue/cli-plugin-<name>` or `vue-cli-plugin-<name>`, using the user prefered tool (npm or yarn).
If `<name>` contains `@vue/cli-plugin` or `vue-cli-plugin`, use `npm install <name>` directly.
Then run the real `invoke`.

Example:

```
vue create my-app
cd my-app
vue invoke apollo
```

**Comment by yyx990803** [comment]
I kinda hope it's possible to explicitly separate the install and invocation steps.

Maybe instead we can have a different command `vue add` which combines both.

**Comment by zephraph** [comment]
Yeah. I was noticing tonight when I tried to add the just plugin to a project just by installing it it didn't automatically make the config updates. I just created an example with `vue create` with the plugin that I wanted and manually moved over the config. 

Having a command like `vue add` to both install and configure the plugin would be nice.
