### ISSUE TITLE
Generated index.html should contain a <noscript> tag

### ISSUE THREAD

**Issue by nanomad** [vuejs/vue-cli#854]
### What problem does this feature solve?
By default a project generated by `vue-cli` doesn't pass the `no-js` Lighthouse inspection:

https://developers.google.com/web/tools/lighthouse/audits/no-js

### What does the proposed API look like?
`vue-cli` should add something like the following in `index.html` inside the `body` tag to notify users that Javascript is mandatory:

```html
<noscript>
    <strong>We're sorry but {{APP_NAME}} doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
</noscript>
```

**Comment by mrksbnch** [comment]
Is there any way to remove this element? E.g. in most cases the app would still work without JS if you are using SSR?
