### ISSUE TITLE
Promise polyfill not working on IE11

### ISSUE THREAD

**Issue by nanomad** [vuejs/vue-cli#858]
### Version
3.0.0-beta.1

### Reproduction link
[https://github.com/nanomad/vue-cli-promise-test](https://github.com/nanomad/vue-cli-promise-test)

### Steps to reproduce
- Create a new project via vue-cli (accepts the defaults)
- Add the following to main.js
```
Promise.all([0]).then(function() {
  alert("ALL OK");
})
```

- Run `yarn serve`
- Open IE11

### What is expected?
An alert with "ALL OK" appears

### What is actually happening?
- No alert
- Error in console `Unhandled promise rejection TypeError: 0 is not iterable!`

---
Seems like the babel preset for vue is pulling in the wrong polyfill

**Comment by LinusBorg** [comment]
No, your Javascript is invalid. `Promise.all()` expects an array of `Promise` objects - you passed it an array containing a `Number`.

The error message tells you that `Promise` itself is working - it's a `promise rejection error`

**Comment by nanomad** [comment]
Re-opening because the following fails as well:
```
var p = Promise.resolve(0);
Promise.all([p]).then(function() {
  alert("ALL OK");
});
```
with error:
```
Unhandled promise rejection TypeError: [object Object] is not iterable!
```

Also, it's totally legal to use an object in place of a promise. See: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

**Comment by nanomad** [comment]
Ok, so i've done some digging by playing around with the built-in babel preset (@vue/babel-preset-app).
Seems like the culprit is the following piece of code:

https://github.com/vuejs/vue-cli/blob/399e7591f67020e2b5213b76b28f373d0d58d2d7/packages/%40vue/babel-preset-app/index.js#L43-L44

If I switch polyfill to true babel will insert the non-global polluting version of the Promise polyfill that works properly on IE10

**Comment by LinusBorg** [comment]
Then the question is why the normal polyfill doesn't work on IE10?

And the side-question is why do you have to support IE10? Poor guy, you have my sympthy :(

I don't think we want to add the ponyfills from `babel-transform`, as some libs (like vuex) need them available as globals anyway, so we would have to include a polyfill as well, which would blow up code size etc.

**Comment by nanomad** [comment]
@LinusBorg I think I can manage to leave to IE10 out but I was a bit surprised it didn't work since it was theoretically included in the list of supported browsers.

Given that I can reproduce it successfully without vue, do you think it may be worth opening a ticket in the babel repo? Maybe that combination _is not supposed to work on IE10_

**Comment by nanomad** [comment]
Filed a babel issue, seems like a feature detection error on IE10

**Comment by nanomad** [comment]
@LinusBorg I'm dumb... It's IE11 (the one available on Windows 10)

**Comment by LinusBorg** [comment]
Feel free to rename again ;)

**Comment by ZrbJava** [comment]
。

**Comment by yyx990803** [comment]
Looks like a fixing PR has been merged into Babel and should be fixed in the next Babel 7 release.

**Comment by drw112** [comment]
I'm seeing a similar thing with a new CLI project.

```
vue create testcli

Select Vuex + any other options

npm run serve
```

Error in IE
` [vuex] vuex requires a Promise polyfill in this browser.`

**Comment by yyx990803** [comment]
Closed as it's fixed in Babel 7.0.0-beta.46

**Comment by drbdvd** [comment]
I still get the same error with 7.0.0-beta.46

**Comment by LinusBorg** [comment]
Then you should probably report that in the Babel repo.
