### ISSUE TITLE
Add `eject` information to README/add `eject` functionality

### ISSUE THREAD

**Issue by soanvig** [vuejs/vue-cli#861]
### What problem does this feature solve?
The new vue-cli 3.x.x lacks `eject` option (either only in README or in whole project). The README mentions:

> At the same time, it still offers the flexibility to tweak the config of each tool without the need for **ejecting**.

> Projects created by Vue CLI allows you to configure almost every aspect of the tooling without ever needing to **eject**.

But no such command exist, or no such command is mentioned in README.

### What does the proposed API look like?
`yarn eject` -> `yarn run eject`
+ confirmation, that this is unrevesable action.

It should then immediately fallback whole project directory into standard Vue/Webpack project directory known from vue-cli 2.x.x

**Comment by soanvig** [comment]
It would at least follow **Vue.js** philosophy of being customizable (which is guaranteed by vue-cli actually), **and** elastic (which is not guaranteed now, since it requires **yarn**, which would be dispensable after actual ejecting).

**Comment by yyx990803** [comment]
The whole point is... It doesn't exist because you don't need to. This is by design.

**Comment by asadsahi** [comment]
@yyx990803 if eject isn't available, then how to achieve the project model of https://github.com/vuejs/vue-hackernews-2.0 i.e implement SSR if someone have to or to use node as backend (not just proxy requests to a node backend for instance running using a seperate command)? Or it isn't possible with vue cli based template?

**Comment by Akryum** [comment]
@asadsahi A SSR plugin will be added at some point.

**Comment by asadsahi** [comment]
@Akryum I am guessing in current version of cli, its webpack-dev-server, but with SSR plugin are you planning to use node as a server and static assets being compiled using webpack-dev-middleware?

**Comment by njleonzhang** [comment]
@yyx990803 can you consider to support the `eject`? The tool is cool, and the configuration through `vue.config.js` is also cool, but working without `webpack config`(souce code) makes me scared, especially if I encounter some weird issue.

**Comment by AliasT** [comment]
@vue/cli have the [vue.config.js configureWebpack](https://cli.vuejs.org/guide/webpack.html), but it is more friendly with adding, not modifying. just as [@vue/cli](https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-plugin) indicates:
> You will need to familiarize yourself with `webpack-chain's API` and `read some source code` in order to understand how to leverage the full power of this option...
