### ISSUE TITLE
Documentation for how to configure templates in v3

### ISSUE THREAD

**Issue by philwolstenholme** [vuejs/vue-cli#862]
### What problem does this feature solve?
In v2, it was easy to build a template that came with a custom index.html file and some default components. In v3 I'm not sure if this is possible, or if it is possible, how it is done.

I'm building a `vue-cli` template for my organisation and I'd like to benefit from the plugin based approach of v3, but also give my users something more than just the default HelloWorld components after they have run `vue create`. I'd like to supply some components and also a customised app shell, so would need to alter the contents of `generator/template` (https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-service/generator/template) - I guess? 

Is this possible? It might be useful to document this either way as it will help users who wish to migrate from v2 to v3.

### What does the proposed API look like?
Documentation change to either supply information on producing custom generator templates, or to specify that v2 should be used for this purpose.

**Comment by LinusBorg** [comment]
Well, the intended way would be to simply write a plugin for that, and publish it.

Your plugin can ask the user additional prompts as well as copy over it's own templates, check the docs:

https://github.com/vuejs/vue-cli/blob/dev/docs/plugin-dev.md

So the workflow for your users would be:
```
npm i -D vue-cli-plugin-phils-template && vue create myApp && myApp/vue invoke phils-template
```

**Comment by philwolstenholme** [comment]
Thank you @LinusBorg, I'd briefly scanned the plugin dev page but hadn't noticed the `api.render('./template')` line in the example. 

I'll take a look at that page and see if I can get something working locally 👍
