### ISSUE TITLE
Errors in vue.config.js are swallowed

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-cli#874]
### Version
3.0.0-alpha.13

### Reproduction link
[https://github.com/chrisvfritz/vue-enterprise-boilerplate](https://github.com/chrisvfritz/vue-enterprise-boilerplate)

### Steps to reproduce
Add a syntax error or throw an error from `vue.config.js`. 

### What is expected?
I would expect Vue CLI commands that require `vue.config.js` to fail loudly when it contains an error, making me aware of the source of the problem (or even that there _is_ a problem).

### What is actually happening?
Vue CLI will swallow it and continue as if everything is normal. I noticed this behavior when Webpack was acting as if my aliases were not defined. It took a little while to figure out that there was a syntax error in a file required from `vue.config.js`.

**Comment by LinusBorg** [comment]
The `require` statement for the file is wrapped in a try/catch that swallows the error:

https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/Service.js#L163-L171

**Comment by chrisvfritz** [comment]
@LinusBorg Thanks for digging into it! Made submitting a fix much easier. 🙂
