### ISSUE TITLE
Potentially confusing name of dev server script 

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-cli#875]
I can see why the _service_ is called `serve`, as it's used in more contexts than just development (e.g. e2e tests), but I think the default NPM script to run it for development should be changed from:

```json
"serve": "vue-cli-service serve --open",
```

to:

```json
"dev": "vue-cli-service serve --open",
```

A few advantages I'm thinking of:

- Vue devs used to the Webpack template already know exactly what to expect with this command.
- A `serve` script is often used for the production version of a server-side app, so I worry some users may try to use it for that purpose. They may even assume it's giving them server-side rendering or something. The rename would help prevent that misconception.

Thoughts?

**Comment by yyx990803** [comment]
The reason why it's not called `dev`: because it's possible to do `vue-cli-service serve --mode production`.

`yarn dev --mode production` reads quite wrong to me.

**Comment by chrisvfritz** [comment]
But it is serving _dev_ server, right? Or are there valid cases where one might use `vue-cli-service serve --mode production` in the actual production environment? 

If it is a dev server, `yarn dev --mode production` reads perfectly fine to me. You're launching the dev server in production mode, but it's still a dev server and you're still doing development (presumably just troubleshooting a production-only issue).

Some might still find it strange typing `yarn dev --mode production`, but there would be no serious consequences and I think most people will probably never even have reason to run that command. 

On the other hand, someone using `yarn serve` to serve their app in actual production environment would be an extremely bad misunderstanding, so the risks are much higher.

Does that make sense?
