### ISSUE TITLE
Replace e2e:open script with dev:e2e when Cypress is installed

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-cli#878]
Something unique about Cypress is that it's not just a test framework, but also offers a nice development environment. The plugin for Cypress currently comes with an `e2e:open` script for running the Cypress client:

```json
"e2e:open": "vue-cli-service e2e:open"
```

But it serves in production mode, which I only prefer when debugging the very rare production-only issue. This also defeats what I feel is the primary purpose of the client: to facilitate _development_, whether you're writing new tests alongside or not.

For that reason, I've replaced it with a `dev:e2e` script in vue-enterprise-boilerplate:

```json
"dev:e2e": "vue-cli-service e2e:open --mode=development",
```

A few advantages I'm thinking of:

- The emphasis on development (`dev:e2e` instead of `e2e:open` or `e2e:dev`) highlights it as a vital tool in the development process.
- Running the dev server in development mode means that when something goes wrong, users will get more useful errors from Vue and potentially other libraries. This would make debugging failing tests a lot easier.

What do you think? Would it be appropriate to replace `e2e:open` with a `dev:e2e`?

**Comment by nanomad** [comment]
I have to agree, the dev mode is, to me, more useful. I'd still keep the old open around as it useful to debug sporadic issues with "prod-like" code

**Comment by yyx990803** [comment]
So I think this is better done by exposing a single `e2e` command, which defaults to `open` mode and takes an optional `--headless` flag.

**Comment by chrisvfritz** [comment]
@yyx990803 That works for me! 🙂 However, it still doesn't address the core development/production mode issue. 

Maybe the default mode for `e2e` should be `development`, since it will be most useful when people want to develop/debug and the quality of that experience will usually be the top priority.

But then when specifying `--headless` the default mode could be `production`, since that will usually run in a CI process, where the top priority is making sure everything works in production.

What do you think?

**Comment by yyx990803** [comment]
I think it's more confusing to have different default modes depending on another flag.

So with the latest changes you can just do `yarn test:e2e --mode=development` for the same effect, or simply add the `--mode=development` to the default script.

I prefer to keep the naming consistent, so no `dev:e2e` - that can be added manually after project is created.
