### ISSUE TITLE
引入bootstrap.min.css报错？怎么新增css-loader

### ISSUE THREAD

**Issue by wendaosanshou** [vuejs/vue-cli#88]
## 当我通过```import './lib/bootstrap.min.css'```引入bootstrap.min.css时。
```npm run dev```命令报错了。
![报错](https://raw.githubusercontent.com/wendaosanshou/pic-repository/master/error/error_vue-cli.png)

## 我猜是webpack配置的css-loader不支持bootstrap的加载。
我从其它的项目中webpack找到了
```{ test: /\.css$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader?sourceMap' ) },```
这样的配置。

但是vue-cli生成的项目，plugin和loader是放在了两个不同的config中。我想添加一个style-loader但是创建```ExtractTextPlugin```和引用```ExtractTextPlugin```就处在了两个不同的文件。现在不知道该怎么修改。

我的问题是为什么会不支持```bootstrap.min.css```编译呢？是没有style-loader的原因吗？
还有我要如何添加这个loader。

**Comment by zigomir** [comment]
It says it can't resolve `..fonts/glyphicons-halflings-regular.eot` in your case. I haven't used webpack and bootstrap together yet but I've found this, maybe it can help you: https://github.com/gowravshekar/bootstrap-webpack

**Comment by wendaosanshou** [comment]
thanks, because i only copy bootstrap.min.css but not copy relay source such as font folder .

when i copy font folder, the problem was solved.

**Comment by zigomir** [comment]
np, I'm glad you solved it :)
