### ISSUE TITLE
Hidden public files are not copied to output

### ISSUE THREAD

**Issue by Akryum** [vuejs/vue-cli#880]
### Version
3.0.0-alpha.13

### Reproduction link
[https://github.com/vuejs/ui/tree/master/public](https://github.com/vuejs/ui/tree/master/public)

### Steps to reproduce
Have a hidden file in the `public` folder, for example `.nojekyll`.

### What is expected?
The file is copied to the output folder alongside the other files from the `public` folder.

### What is actually happening?
The file isn't copied.

**Comment by LinusBorg** [comment]
https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/config/app.js#L152

Since this explicitly added as an ignore pattern, it seems @yyx990803 intended this behaviour. Thoughts?
