### ISSUE TITLE
Add `cli-plugin-unit-ava`

### ISSUE THREAD

**Issue by brandon93s** [vuejs/vue-cli#883]
### What problem does this feature solve?
[AVA](https://github.com/avajs/ava) test runner.

Add `unit-ava` in addition to the existing `unit-mocha` and `unit-jest` core plugins. `unit-ava` would be exposed in the same way as jest and mocha support and given as an option for unit testing configuration.

### What does the proposed API look like?
The API / implementation would follow the pattern(s) established by `unit-jest` and `unit-mocha`.

**Comment by brandon93s** [comment]
I'm glad to work on this and submit a PR, but wanted to check if it would be accepted into core before proceeding. If not, I can build it as a standalone plugin.

Thanks!

**Comment by corbinu** [comment]
I would love to see this. Happy to help with getting it working with the TypeScript plugin as I am using ava and TypeScript with my own custom template for version 2

**Comment by LinusBorg** [comment]
How is the testing story with .vue files with ava?

/ping @eddyerburgh tested ava some time ago and performance of existing solutions to transpile .vue files in ava were, well disappointing.

Generelly I don't think we want to add *every* testing framework as a core pluin, just like we won't add *every* preprocessor and *every* compile-to-js language to it (no coffeescript! :-P)

So In order for a PR to be accepted, this proposition would have to:

1. Provide a great testing experience with Vue, especially `.vue` files
2. Gather enough support from the community to make clear using ava with Vue has enough support to add it as a core plugin.

If that doesn't happen, you can ofg course make it a "normal" plugin to the cli, which means users would simpl have to do this to add ava after the initial `vue create` setup:

```
npm i -D vue-cli-plugin-ava
vue invoke ava
```

**Comment by yyx990803** [comment]
I'd encourage working on a standalone plugin for Ava first, as it would:

- Help us gauge the feasibility of the current plugin API for making standalone plugins. In particular, is there any blockers for a 3rd party plugin to play nicely with built-in ones.

- Lower barrier to get started, as you are free to experiment with the plugin without having to adhere to all the requirements we have for built-in plugins.

If it proves successful for Ava users, we'd be happy to consider pulling it into core.

**Comment by corbinu** [comment]
@yyx990803 That makes sense to me

@brandon93s Did you want any help on this? I am also going to start working on a testcafe plugin as cypress doesn't have support for any browsers other than chrome.

**Comment by brandon93s** [comment]
@corbinu - I've got a plugin started locally with the early stages of an implementation working. I'll get it pushed up to GitHub in the next few days so that we can collaborate.

**Comment by corbinu** [comment]
@brandon93s sounds great!

**Comment by MartinMuzatko** [comment]
I would love to see ava being an option for testing for Vue. I have no particular experience with testing Vue apps with ava, but ava has been very comfortable to work with and allows for a great testing experience. From personal experience, performance is okayish depending on project size. But I hear that from [many sources](https://github.com/avajs/ava/issues/1418). 

What makes me stick with ava, is that the way tests can be described and organized (and quickly disabled/enabled/test only), is what makes testing so easy with ava.

**Comment by yyx990803** [comment]
Closing in favor of a community plugin. Too many built-in choices increase both maintenance debt for us and decision fatigue for users.

**Comment by dnlup** [comment]
I am developing a plugin, if anyone would like to try it and give me some feedback here is the repo:
https://github.com/dnlup/vue-cli-plugin-unit-ava
