### ISSUE TITLE
无法通过 npm 升级 vue-cli （can't update vue-cli using npm）

### ISSUE THREAD

**Issue by qusiba** [vuejs/vue-cli#89]
之前安装的版本初始化项目时没有自定义测试和代码提示
通过 npm 无论是 update 还是 uninstall 后再 install (都是全局安装和卸载和升级) 都无法升级 vue-cli
最后是去到 vue-cli 里面直接 git pull 才升级成功

**Comment by sohucw** [comment]
你是不是命令不正确？ npm update vue-cli -g
