### ISSUE TITLE
pwa plugin: allow to define cacheId to prevent 'not allowed error'

### ISSUE THREAD

**Issue by mutefiRe** [vuejs/vue-cli#891]
### What problem does this feature solve?
I'm having trouble with the pwa plugin for 3.0. I want to use `InjectManifest`, but building the project doesn't work because `cacheId` is not allowed for workbox 3 in `InjectManifest` Mode. But `cacheId` is always set by `cli-plugin-pwa/index.js`, no matter which mode is set.
Error message: `ERROR  ValidationError: "cacheId" is not a supported parameter.`

### What does the proposed API look like?
Allow setting `CacheId` in `vue.config.js` and also add the possibilty to use null as value, which causes `cli-plugin-pwa/index.js` to remove the attribute, to prevent this error.

**Comment by umarov** [comment]
I stumbled upon this issue as well and submitted a PR https://github.com/vuejs/vue-cli/pull/939.

**Comment by mutefiRe** [comment]
Very nice, thanks 😉
