### ISSUE TITLE
Pug templates are not set as doctype html

### ISSUE THREAD

**Issue by CaleCrawford** [vuejs/vue-cli#894]
### Version
3.0.0-alpha.13

### Reproduction link
[https://codesandbox.io/s/pjzpx376q](https://codesandbox.io/s/pjzpx376q)

### Steps to reproduce
1. Create a new project using the CLI.
2. Set <template> to <template lang="pug">
3. Install pug
4. Create element with a boolean value e.g. `b-navbar(toggleable type="light")`
5. Start app and load page.

### What is expected?
The render output should be `<b-navbar toggleable type="light">`

### What is actually happening?
The rendered output is `b-navbar toggleable="toggleable" type="light">`

---
- This setting is dependant on https://pugjs.org/language/attributes.html#boolean-attributes having the doctype be set to html.
- Nuxt seemed to have fixed a similar issue: https://github.com/nuxt/nuxt.js/pull/1361/files#diff-4f5f40ac2485bef65351d77d76fd33c5
- Currently you can get around the issue by setting `toggleable=''` but that seems like a hack.
- I tried using `chainWebpack` in vue.config.js to add the setting but was unable to add the option to vue-loader

**Comment by CaleCrawford** [comment]
After reading more source code I was able to get it to work using
```
  chainWebpack: (config) => {
    config.module
      .rule('vue')
      .test(/\.vue$/)
      .use('vue-loader')
      .loader('vue-loader')
      .tap((args) => ({
        ...args,
        template: {
          doctype: 'html',
        },
      }));
  },
```
Not sure if there would be a reason not to have this be the default.

**Comment by casret** [comment]
I'm having this problem using rc5.  Was there a regression or do I need to configure it differently?
