### ISSUE TITLE
Running an unknown command should throw an error

### ISSUE THREAD

**Issue by rbrtmrtn** [vuejs/vue-cli#895]
### Version
2.9.3

### Reproduction link
[https://codesandbox.io/s/vue](https://codesandbox.io/s/vue)

### Steps to reproduce
1. Run `vue foo`

### What is expected?
I would expect an error to be thrown.

### What is actually happening?
It does nothing and exits silently.

---
FWIW this is on macOS 10.13.3.

**Comment by yyx990803** [comment]
Addressed in #857
