### ISSUE TITLE
Ability to download from git url or other sources

### ISSUE THREAD

**Issue by flipxfx** [vuejs/vue-cli#9]
Within our company, we would like to fork some of the main templates and make changes to them, but we would like to host it privately in Bitbucket. Our use case is not so much building templates for everyone to use, but building templates for us to use internally that contains our api hooks, layouts etc. Is this something that may be supported?

**Comment by yyx990803** [comment]
Technically, yes. The project current uses [download-github-repo](https://github.com/ianstormtaylor/download-github-repo) which only supports public github repos; however it should be pretty straightforward to use the lower level [download](https://github.com/kevva/download) instead. Feel free to open a PR for this.
