### ISSUE TITLE
Debug code / test using breakpoints

### ISSUE THREAD

**Issue by ConnorStroomberg** [vuejs/vue-cli#901]
### What problem does this feature solve?
Fix errors in your test or code under test by setting a break point and inspecting the system state.

Using the 2.x CLI combined with Karma   Chrome/Firefox/... i could run a test and use the browsers build in debugger to debug de code. In the new CLI ( 3.x with jsdom) i do not see how this is done in a clean and easy to use way.

### What does the proposed API look like?
yarn test --debug

**Comment by yyx990803** [comment]
This may help:

- https://facebook.github.io/jest/docs/en/troubleshooting.html
- If you use VSCode: https://medium.com/@mattmazzola/how-to-debug-jest-tests-with-vscode-48f003c7cb41

I doubt we can make this part of the command itself.

**Comment by wangxuepeng** [comment]
Debug Jest unit test following the links works perfect:
`{
            "type": "node",
            "request": "launch",
            "name": "Jest",
            "protocol": "inspector",
            "program": "${workspaceRoot}/node_modules/jest/bin/jest.js",
            "args": ["--runInBand"],
            "console": "integratedTerminal",
            "sourceMaps": true,
            "stopOnEntry": false
          },`

but the same approach for mocha does not work:
`{
            "type": "node",
            "request": "launch",
            "name": "Mocha",
            "protocol": "inspector",
            "program": "${workspaceRoot}/node_modules/mocha-webpack/bin/mocha-webpack",
            "args": [
                "--timeout",
                "999999",
                "--colors",
                "${workspaceFolder}/tests/**/*.spec.*"
            ],
            "console": "integratedTerminal",
            "sourceMaps": true,
            "stopOnEntry": false
          },
`, 
it prompts error below:
` WEBPACK  Failed to compile with 1 error(s)

Error in ./tests/unit/HelloWorld.spec.js

  Module not found: '@/components/HelloWorld.vue' in '/Users/mkw/Dev/vue_mocha/tests/unit'

Waiting for the debugger to disconnect...
Killed: 9`
Looks like it need some webpack configuration?

BTW, I also check link [feat(service): Enable inspector debugging for unit test by mocha](https://github.com/vuejs/vue-cli/pull/2013), it seems the solution, but how to config it in VSCode? 

Thanks.
