### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by zhangguixu** [vuejs/vue-cli#91]
![image-1](https://cloud.githubusercontent.com/assets/8208625/15062337/a0c6e208-1371-11e6-9ca2-b8fae8fc44be.png)

不知道是不是npm install的原因

**Comment by phanan** [comment]
Hello! Please use our [forum](http://forum.vuejs.org) or [Gitter](https://gitter.im/vuejs/vue) for questions like this. The repo issue list is strictly for bug reports and feature requests, as specified in the [contributing guidelines](https://github.com/vuejs/vue/blob/dev/CONTRIBUTING.md). Thanks.

**Comment by knownothingsnow** [comment]
I met the same question on macOS.It same like that Babel did not work.Still looking for the method to fix.

**Comment by zigomir** [comment]
@knownothingsnow and @zhangguixu please open an issue on https://github.com/vuejs-templates/webpack or on [any other official template](https://github.com/vuejs-templates) if you use one.
