### ISSUE TITLE
methods property doesnt connect. what happen

### ISSUE THREAD

**Issue by dongugkim** [vuejs/vue-cli#910]
![123](https://user-images.githubusercontent.com/25264202/36842180-25ab5184-1d8e-11e8-822a-0b222ae74774.PNG)
![default](https://user-images.githubusercontent.com/25264202/36842182-25e044fc-1d8e-11e8-82f7-12d8a9b05e35.PNG)
what happen? why i cant see "

> methods

" part in vue chrome tools.

**Comment by liuhuanhui** [comment]
同样问题! 事件点击也找不到
