### ISSUE TITLE
Just for more customized configruation !

### ISSUE THREAD

**Issue by PedroGao** [vuejs/vue-cli#911]
As mentioned,i want to change the entry of the webpack config . But the vue.config.js does't support it!
> $ node_modules/.bin/vue-cli-service inspect
 ERROR  Invalid options in vue.config.js: "entry" is not allowed
So,could you add it ?

**Comment by yyx990803** [comment]
Please read the docs more carefully.

**Comment by PedroGao** [comment]
I am sorry , i got it when i report this issue! it's my mistake.
