### ISSUE TITLE
Customized localIdentName in config

### ISSUE THREAD

**Issue by n-zeplo** [vuejs/vue-cli#912]
### What problem does this feature solve?
Allows individual teams to customize the css module class naming conventions for their team. This enables teams to align with style guides / design system naming conventions such as BEM or SMACSS.

### What does the proposed API look like?
Add it as an option in the css portion of the config. Then add it in the CSSLoaderResolver to take input or default to existing localIdentName.

**Comment by yyx990803** [comment]
Closed via #915
