### ISSUE TITLE
connot open app use local ip

### ISSUE THREAD

**Issue by wangxiangyao** [vuejs/vue-cli#914]
### Version
2.9.3

### Reproduction link
[https://github.com/wangxiangyao/venusManage](https://github.com/wangxiangyao/venusManage)

### Steps to reproduce
最近我升级了vue-cli，这个项目是升级后写的。
任何一个新vue-cli创建的项目，应该都有这个问题

npm run dev运行项目后，在浏览器用`localhost:8080`打开，没有问题。但是用本机ip打开就不行，比如'192.168.1.9:8080'

我把很早以前，用老版本vue-cli创建的项目运行了下，是可以打开的

网上有人说，修改devServer配置的host为0.0.0.0,。这样是可以通过ip打开了。但是项目中需要使用外网nginx代理到本地，进行开发（微信支付之类的功能），这个反向代理依然不能使用。

### What is expected?
期望可以使用ip直接打开项目，并且可以使用反向代理

### What is actually happening?
不能用ip打开，反向代理失败

---
init a new app`vue init webpack proj`
then 
`cd proj`
`npm run dev`
open chrome and  input url 'localhost:8080' At this point, I can access my website.
but if i input url '192.168.1.9:8080',There was a mistake. I couldn't open the site properly.

Some people say that you can solve the problem by changing the host ( `localhost -> 0.0.0.0`)
That's possible, but when i use Nginx reverse proxy. it dosen't work.

I demoted vue-cli to 1.1.2. and creat a new project .There was no problem.

**Comment by yyx990803** [comment]
Should be fixed by #868 868

**Comment by wangxiangyao** [comment]
如果想要做代理，还需要在vue.config.js中配置
```
vue.config.js
module.exports = {
  devServer: {
    disableHostCheck: true,
  }
}
```

**Comment by wangxiangyao** [comment]
很感谢，没有代理很多功能开发很麻烦
