### ISSUE TITLE
Add `cli-plugin-unit-jasmine`

### ISSUE THREAD

**Issue by joseluisq** [vuejs/vue-cli#919]
### What problem does this feature solve?
[Jasmine](https://jasmine.github.io/) BDD testing framework.

Add `unit-jasmine` in addition to the existing testing plugins like `unit-mocha` and `unit-jest`. 

### What does the proposed API look like?
Basically the implementation would follow the patterns similar to `unit-mocha` and `unit-jest`.

**Comment by yyx990803** [comment]
See https://github.com/vuejs/vue-cli/issues/883#issuecomment-369423084

**Comment by joseluisq** [comment]
👍

**Comment by yyx990803** [comment]
Closing in favor of a community plugin. Too many built-in choices increase both maintenance debt for us and decision fatigue for users.
