### ISSUE TITLE
different css outputs from serve and build script

### ISSUE THREAD

**Issue by you06** [vuejs/vue-cli#927]
### Version
3.0.0-beta.3

### Reproduction link
[https://github.com/you06/vue-cli-css-issue](https://github.com/you06/vue-cli-css-issue)

### Steps to reproduce
The following css is in [https://github.com/you06/vue-cli-css-issue/blob/master/src/components/HelloWorld.vue#L19](https://github.com/you06/vue-cli-css-issue/blob/master/src/components/HelloWorld.vue#L19)
```css
background-image: linear-gradient(top, #ffffff, #2196F3);
```

running `yarn build`, check the style from chrome, webkit compatible is auto added
```css
background-image: -webkit-gradient(linear, left top, left bottom, from(#ffffff), to(#2196F3));
background-image: linear-gradient(top, #ffffff, #2196F3);
```

running `yarn serve`, check the style from chrome, there is no webkit compatible
```css
background-image: linear-gradient(top, #ffffff, #2196F3);
```

### What is expected?
I think the serve and build script should get the same output.

### What is actually happening?
The css output is different.

**Comment by yyx990803** [comment]
Can't reproduce... the webkit prefixed version is there for me with `yarn serve` as well.
