### ISSUE TITLE
Asset paths not generated for inline styles

### ISSUE THREAD

**Issue by faxal** [vuejs/vue-cli#928]
### Version
3.0.0-beta.2

### Reproduction link
[https://codesandbox.io/s/wz6989r7r5](https://codesandbox.io/s/wz6989r7r5)

### Steps to reproduce
Run the sandbox and check generated source

```
<div class="image" style="background-image:url('@/assets/logo.png');"></div>
```

### What is expected?
Correct image link be generated

### What is actually happening?
It is as is with '@' in URL

**Comment by yyx990803** [comment]
This is tracked in https://github.com/vuejs/vue-loader/issues/1113
