### ISSUE TITLE
register handlebars helper

### ISSUE THREAD

**Issue by queckezz** [vuejs/vue-cli#93]
Is there a possibility to register custom handlebars helper to `vue-cli`? Specifically I need the a helper for camelcasing names automatically. 

An use case is for installation usage in the readme as follows:
```js
const {{camelcase name}} = require('{{name}}')
```

Khaos has this [built into core](https://github.com/segmentio/khaos/blob/master/lib/helpers.js#L9-L13), not sure if you want to include it too.

**Comment by yyx990803** [comment]
Sounds useful - what we can do is [in addition to `meta.json`, also accept `meta.js`](https://github.com/vuejs/vue-cli/blob/master/lib/options.js). Then you can do something like:

``` js
// meta.js
module.exports = {
  prompts: { ... },
  helpers: {
    // custom helpers
  }
}
```
