### ISSUE TITLE
Make all <projectRoot>/node_modules/** related file/folder as Environment Variable

### ISSUE THREAD

**Issue by DrSensor** [vuejs/vue-cli#938]
### What problem does this feature solve?
- Imagine that there is CLI for doing nitty-gritty SPA stuff in backend code `dotnet webpack <webpack.config.js>`.
- In order to use it, the user needs to invoke it like `dotnet webpack node_modules/@vue/cli-service/webpack.config.js`.
- Is it better if the command can be shortened like `dotnet webpack $VUE_WEBPACK_CONFIG`?

---
> For `cache-loader`, there is a case when the developer needs to [import it into database](https://github.com/webpack-contrib/cache-loader#database-integration).

### What does the proposed API look like?
Generate `.env` file with content
```env
VUE_CACHE_LOADER=<projectRoot>/node_modules/.cache/cache-loader
VUE_WEBPACK_CONFIG=<projectRoot>/node_modules/@vue/cli-service/webpack.config.js
```
After it was generated, the cli can prompt user how to import `.env` into shell. In bash shell I can do it like 
```bash
export $(egrep -v '^#' .env | xargs)
```

> Note that every shell has the different way to export Environment Variables

**Comment by yyx990803** [comment]
Not sure if this needs to be in by default, since these use cases don't seem to be super common and this is not required to make it work.
