### ISSUE TITLE
Add an option to provide BASE_HREF in the project.

### ISSUE THREAD

**Issue by ayush987goyal** [vuejs/vue-cli#944]
### What problem does this feature solve?
This feature solves the problem of deploying the built files to a domain endpoint other then `/` (for example GitHub Pages). Currently we have to do the same manually for all the built bundles and assets.

### What does the proposed API look like?
This can be a command line parameter for the `build` functionality of `vue-cli-service`. It may look like
```yarn build --base=my-project```

**Comment by yyx990803** [comment]
`baseUrl` is the first documented option in `vue.config.js`: https://github.com/vuejs/vue-cli/blob/dev/docs/config.md
