### ISSUE TITLE
babel-preset-app 问题

### ISSUE THREAD

**Issue by zhfish** [vuejs/vue-cli#946]
### What problem does this feature solve?
babel-preset-app很方便，常用的设置都不用管了， 能否出一个官方的babel-preset-app-es6？ 
因为对公的开发，我们会强制要求用chrome 61.0以上，所以之前是对babel的配置做了改造，让他可以支持原声es6
我觉得应该也有别的同学有这种需求

### What does the proposed API look like?
{
  "plugins": [
    "transform-runtime",
    "transform-object-rest-spread",
    "syntax-dynamic-import",
    "transform-decorators-legacy",
    "transform-class-properties"
  ],
  "env": {
    "production": {
      "presets": ["minify"]
    }
  }
}

**Comment by yyx990803** [comment]
用 `targets` 选项：https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/babel-preset-app#options
