### ISSUE TITLE
Testing with inject-loader does not work out of the box.

### ISSUE THREAD

**Issue by thomasmichaelwallace** [vuejs/vue-cli#947]
### Version
2.9.3

### Steps to reproduce
- Setup a project using babel, mocha/chai and inject-loader
- Injecting a module will return: "Module parse failed: 'import' and 'export' may only appear at the top level inject"

### What is expected?
The module injection function to be returned.

### What is actually happening?
Test fails due to invalid configuration.

---
A workaround for this is to set the VUE_CLI_BABEL_TRANSPILE_MODULES flag while testing.

**Comment by yyx990803** [comment]
`vue-loader` no longer works with `inject-loader` in 14.0+ because it does not work with ES modules.

We will suggest a different solution for mocking during tests after more investigation.

**Comment by thomasmichaelwallace** [comment]
Thanks @yyx990803 - isn't esModules an option in vue-loader that can be set to false (or you can use the babel workaround I mentioned, which seems to be used when Jest is selected.)

I'm happy to do a PR to switch this on for mocha/chai so that the inject-loader approach noted on the vue-loader documentation works out of the box: https://vue-loader.vuejs.org/en/workflow/testing-with-mocks.html

**Comment by thomasmichaelwallace** [comment]
@morningdew830 - you can work around it by using `VUE_CLI_BABEL_TRANSPILE_MODULES=*`

e.g. the test command should be:
`"test": "VUE_CLI_BABEL_TRANSPILE_MODULES=* vue-cli-service test"`

**Comment by thomasmichaelwallace** [comment]
I actually made the jump to karma in the end because I needed some of the browser built-ins; but happy to do a PR to fix this with mocha if it's still an issue?

It's all about this line: https://github.com/vuejs/vue-cli/blob/b20f624c32a5a82e7ae5b48369068039be881251/packages/%40vue/babel-preset-app/index.js#L141

**Comment by morningdew830** [comment]
Thanks for quick help! @thomasmichaelwallace
Unfortunately, I just tried with the environment but still getting the same error.

![image](https://user-images.githubusercontent.com/22661536/44362037-6054a100-a4f2-11e8-84d0-e387fa160b01.png)

This is the old test code that had been working with vue-loader v13.
```
// eslint-disable-next-line import/no-webpack-loader-syntax
const injector = require('inject-loader!@/store/modules/item')
```
Any good idea?

**Comment by thomasmichaelwallace** [comment]
Hmm.

Give me a day (it's evening where I am!) I'll see if I can get my old
project with the fix working again with the latest version.

What you've got to do is change that usESModules to false in the resulting
webpack/vue-loader configuration.

**Comment by morningdew830** [comment]
Thanks again!
I just updated the presets in the babel configuration so it worked.

`--- babel.config.js ---`
```
  presets: [
    ['@vue/app', {
      polyfills: [
        'es6.promise',
        'es6.symbol'
      ]
    }]
  ]
```

**Comment by thomasmichaelwallace** [comment]
Interesting.

Do you still need the env flag with that too?

**Comment by morningdew830** [comment]
no need, that env flag doesn't effect for me but I think it would be better if it works.

**Comment by salvadordiaz** [comment]
@thomasmichaelwallace @morningdew830 :

I had to add `es6.module` to the polyfills section to make it work. My `babel.config.js` looks like this:
```
module.exports = {
    presets: [
        ['@vue/app', {
            polyfills: [
                'es6.promise',
                'es6.symbol',
                'es6.module'
            ]
        }]
    ]
};
```

**Comment by IlyaEremin** [comment]
Hello. Since `inject-module` no longer supported then I guess It would be good to remove `inject-module` from examples: https://vuex.vuejs.org/guide/testing.html
`const actionsInjector = require('inject-loader!./actions')`

**Comment by OziOcb** [comment]
> Hello. Since `inject-module` no longer supported then I guess It would be good to remove `inject-module` from examples: https://vuex.vuejs.org/guide/testing.html
> `const actionsInjector = require('inject-loader!./actions')`

I completely agree, I've just spent 30 min trying to make it work. All because of the example that you've mentioned
