### ISSUE TITLE
Building features on demand

### ISSUE THREAD

**Issue by Aferz** [vuejs/vue-cli#948]
### What problem does this feature solve?
Build the application based on a set of a features instead of the current building environment.

I'm facing with a problem in the new `@vue/cli`. I want to create a staging environment for my company/application but I don't find a nice way to do it without override lots of line of default webpack configuration file.

If I explicitly set the build mode (`--mode staging`), vue cli in fact gets the `.env.staging` environment variables BUT it builds the bundle with development features (for example, it doesn't minify the code, it doesn't extract the CSS, etc ...)

Futhermore, if I build the bundle using this command, as the documentation recommends `vue-cli-service build --mode development`, it just not work without being served by internal vue dev-server. The static assets like images or icons are not being extracted out the bundle (I suppose this is intended behaviour) but my `app.js` is requesting images via HTTP that doesn't exists in my `dist`folder.

### What does the proposed API look like?
My proposal would be a way to abstract the core features available in `@vue/cli` to build against a set of required features instead of basing the build in the variable `process.env.NODE_ENV`

Of course, this behaviour can fallback in a pre-defined set of features by `NODE_ENV` if this list is not defined.

One example, *vue.config.js*:

```
...

webpackFeatures () {
    const features = [
      'pwa',
      'dll',
      'css-extract',
    ];
    
    if (process.env.NODE_ENV === 'production') {
      features.push('minification')
      features.push('css-purge')
    }
    
    return features
  }

...
```

If this becomes in something, in a future this could be a good approach to create plugins with features that encapsulate any webpack behaviour under a good readable name.

Of course, this is just a draft and the behaviour/api could change to adapt to the current code or whatever. I'm sure that I'm forgetting/not getting something into account, but I hope my idea is a bit more understandable.

Cheers.

**Comment by LinusBorg** [comment]
> If I explicitly set the build mode (`--mode staging`), vue cli in fact gets the `.env.staging` environment variables BUT it builds the bundle with development features (for example, it doesn't minify the code, it doesn't extract the CSS, etc ...)

```
NODE_ENV=production vue-cli-service build --mode staging
```

**Comment by Aferz** [comment]
> NODE_ENV=production vue-cli-service build --mode staging

Ok, this work as I expected, but you have to admit this is a bit confusing. Having to set the environment to production and declaring `--mode staging` is seems confusing to me. But maybe it's just me.

> I don't really understand this part.

If I bundle my application with `--mode development` and then serve the result with apache/nginx, the server requests all the images via HTTP, but the build process didn't output any `/img` folder in the `dist` directory (Because I guess the images size was lower than expected by the `file-loader`).

Screenshots for `./node_modules/.bin/vue-cli-service build --mode=development`:

*Build Process*
![captura de pantalla 2018-03-06 a las 14 33 21](https://user-images.githubusercontent.com/8954655/37034993-5d1ab52c-214b-11e8-9b4c-85b51172edf6.png)

*Dist folder content*
![captura de pantalla 2018-03-06 a las 14 34 21](https://user-images.githubusercontent.com/8954655/37035048-853201a0-214b-11e8-8df2-79e7c44c5e2f.png)

*Basic server loading the index.html*
![captura de pantalla 2018-03-06 a las 14 36 28](https://user-images.githubusercontent.com/8954655/37035127-ca944c94-214b-11e8-89b8-67236672ced2.png)

---

Anyways, it looks that with your first comment I can solve the problem of the bundle creation with the same production "features" but using other environment variables.

I'm not closing this issue because I'd like to know if the proposed feature could be a good improvement to the build process. If that is not the case, feel free to close it just tell me to do it.

Thanks @LinusBorg

**Comment by yyx990803** [comment]
You are supposed to add
```
NODE_ENV=production
```
Into your `.env.staging`. As the doc explains:

- mode !== env.
- Only `NODE_ENV=production` will result in a production oriented build, regardless of mode.
- Only production mode defaults to `NODE_ENV=production`. In any other mode, you need to explicitly set `NODE_ENV` to your desired value.

**Comment by Aferz** [comment]
All clear @yyx990803 !

**Comment by phcoliveira** [comment]
I am using `vue-cli@3.0.0-beta.2`, and I have been trying to get the build service to read a file named `.env.staging`. Can't get it to work, though.

I have tried using:
- `npm run build --mode staging`
- `npm run build NODE_ENV=production --mode staging`
- `NODE_ENV=production npm run build --mode staging`

I wonder what am I missing.

**Comment by phcoliveira** [comment]
If somebody else is having the same problem I did, I got it working by adding another script in the `package.json` file, `build-staging`. Don't forget to set env variable `NODE_ENV` either in this new command or in the file `.env.staging`.

```
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "build-staging": "vue-cli-service build --mode staging",
    "test": "vue-cli-service test --watch",
    "e2e": "vue-cli-service e2e",
    "lint": "vue-cli-service lint"
  }
```

**Comment by paanoop** [comment]
@phcoliveira What command did you use to run your "build-staging"?
