### ISSUE TITLE
exclamation marks in property declarations aren't parsed 

### ISSUE THREAD

**Issue by muhajirframe** [vuejs/vue-cli#953]
### Version
3.0.0-beta.6

### Reproduction link
[https://jsfiddle.net/50wL7mdz/165908/](https://jsfiddle.net/50wL7mdz/165908/)

### Steps to reproduce
Create new vue project with typescript, eslint   prettier

open app.vue

### What is expected?
Got linting error in vscode

``` 
 '=' expected.
 Expression expected.
 Member 'string' implicitly has an 'any' type.
```

### What is actually happening?
There's error messages

---
Same issue here https://github.com/prettier/prettier/issues/3561

**Comment by daekano** [comment]
Does this really qualify as a reproduction link? It's really just displaying the code used and your reported error, which is being emitted from TypeScript. A repository would be much more helpful because then we can clone that down, inspect your dependencies, and how you have them configured.

**Comment by elevatebart** [comment]
I have the same issue as @muhajirframe when I display HelloWorld.vue in vscode.
When I tried `jarn serve` everything was actually peachy. TypeScript was happy.

Two things can be happening here: 
- The definite assignments are a [TS 2.7 feature](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#definite-assignment-assertions). Therefore, try updating your typescript glogal version (`yarn global add typescript` or `npm i -g typescript`). It should bump up the global parser you are using and fix compilation issues if you have some.
- If, like me, you are using [Vetur](https://github.com/vuejs/vetur) in vscode, I do not think they have updated the version of the parser they use for typescript. In which case we should probably report this issue to them.
## with Vetur
<img width="914" alt="withvetur" src="https://user-images.githubusercontent.com/5592465/37211191-c65c32c8-2370-11e8-90c2-dc98644d4ea4.png">
## Same code out of Vetur
<img width="649" alt="novetur" src="https://user-images.githubusercontent.com/5592465/37211196-ca2ae50c-2370-11e8-8b4e-4bc3251bb0f3.png">

**Comment by elevatebart** [comment]
@linusborg I finally got around to create a reproduction repo
https://github.com/elevatebart/reprovuecli953
Should I already post this to vetur ?

**Comment by elevatebart** [comment]
I posted the [issue](https://github.com/vuejs/vetur/issues/723) on vetur and they answered promptly.
To me, the case is closed. @muhajirframe ?

**Comment by muhajirframe** [comment]
The issue seems will be fixed on next release 👍.
Btw thanks for reproducing and reporting to vetoer @elevatebart .
