### ISSUE TITLE
ENV/mode loading timing problem

### ISSUE THREAD

**Issue by hengwei-lhm** [vuejs/vue-cli#959]
### Version
3.0.0-beta.5

### Reproduction link
[https://codepen.io/anon/pen/yKBxvQ](https://codepen.io/anon/pen/yKBxvQ)

### Steps to reproduce
1 .vue.config.js
module.exports = {
     baseUrl: process.env.NODE_ENV === 'production' ? "{{.urlPrefix}}" : "debug",
}
2 .run vue-cli-service build --mode production in command line

### What is expected?
run vue-cli-service build --mode production in command line ; process.env.NODE_ENV === 'production'

### What is actually happening?
process.env.NODE_ENV === undefined

**Comment by jkzing** [comment]
Um...seems to be a bug, user options is loaded before NODE_ENV initialized.

**Comment by LinusBorg** [comment]
We might have an architectural issue here. The `build` command (which is setting the `production` mode) is implemented as a plugin (like all other commands), and plugins receive the loaded config in their arguments - so the config has to be loaded before the build command can be run.

This might not be a simple *change this line* type of bugfix.

**Comment by posva** [comment]
As a workaround, I remember putting `NODE_ENV=production` in front of the existing `build command`

**Comment by jkzing** [comment]
@LinusBorg , Yes, I managed to find a clean fix and realized it's not that simple...Actually we can pass all user arguments in to `Service` when calling its constructor. However commands like `serve` and `build` have their own default  arguments, which can not simply get during `Service` initialize stage.

**Comment by xvaara** [comment]
As a workaround at the moment I'm using `process.env.npm_lifecycle_event === 'build'` to differentiate between dev/build.

**Comment by laomao800** [comment]
I'm using a similar way as @xvaara but match the `process.env.npm_lifecycle_script` to get the mode value, and use [Dotenv](https://www.npmjs.com/package/dotenv) to load the `.env.[mode]` file at the `vue.config.js` 's beginning.
