### ISSUE TITLE
How can i Integrate this with Laravel ?

### ISSUE THREAD

**Issue by midascodebreaker** [vuejs/vue-cli#96]
Ive seen vue-loader...

All i can say is i manage to hook in it with...

laravel elixir + ext for webpack...

So i can simply run gulp...

But its taking too much time around 1 min...

since i cannot exclude node_modules folder since

i got components fetch at that folder...

This Vue Cli is the latest... if im not wrong...

Its more somewhat like laravel that can instantly create a new project...

But vueJs literal project...

Is there a way i can hook this up...

To a laravel project? What is the best approach i can do to make it possible...

**Comment by chrisvfritz** [comment]
I think this is more a question for [the forum](http://forum.vuejs.org/), as it's not a bug or feature request.
