### ISSUE TITLE
`vue.config.js` vueLoader.preserveWhitespace = false not work

### ISSUE THREAD

**Issue by yozman** [vuejs/vue-cli#962]
### Version
3.0.0-beta.6

### Reproduction link
[https://jsfiddle.net/yozman/3Lcwjrts/](https://jsfiddle.net/yozman/3Lcwjrts/)

### Steps to reproduce
vue.config.js

### What is expected?
$slots.default 去掉空格

### What is actually happening?
$slots.default 空格一直存在

---
感觉是 vueLoader 的 preserveWhitespace 未生效

**Comment by jkzing** [comment]
Tested, and it's working with or without `vue.config.js`.🤔

**Comment by yozman** [comment]
@jkzing 
r u sure？
`$slots.default.length` 一直是包含空格的

**Comment by jkzing** [comment]
@yozman Yes, from what I'm seeing, `preserveWhitespace` is working as expected.
Maybe you could provide your problematic code (like a github repo) to help reproduce the issue.

**Comment by yozman** [comment]
@jkzing 
I use `.js` without `.vue`
```javascript
// parent.js
import Child from './child';

const template = /*html*/`
  <child>
    <h1>one</h1>
    <h1>two</h1>
  </child>
`;

export default {
  template,
  components: {
    Child,
  },
};

// child.js
const template = /*html*/`
  <div>
    <slot/>
  </div>
`;

export default {
  template,

  created() {
    console.log(this.$slots.default.length);
  },
};
```

**Comment by LinusBorg** [comment]
Well, if you use js files, then you are not using vue-loader, which only takes care of `.vue` files.

**Comment by yyx990803** [comment]
Inline JS strings are compiled by the runtime compiler, not `vue-loader`.

**Comment by yozman** [comment]
@yyx990803 
how can I set `preserveWhitespace` to runtime compiler?

**Comment by yozman** [comment]
@yyx990803 @LinusBorg 
could u please give a solution?

**Comment by LinusBorg** [comment]
This would have to be addressed in the vue repository, not vue-loader.

**Comment by yyx990803** [comment]
@yozman you cannot. If you want that behavior you **have** to use pre-compile via `vue-loader`.

**Comment by yozman** [comment]
@yyx990803 why don't u make a feature to that, as every FE known everything is js, not `.vue`

**Comment by sunchanglong** [comment]
> @yyx990803 why don't u make a feature to that, as every FE known everything is js, not `.vue`

yes, inline template need preserve whitespace
