### ISSUE TITLE
vue add [plugin name] doesnt work

### ISSUE THREAD

**Issue by riyasat** [vuejs/vue-cli#963]
Hi,
I had started using Vue/Cli v3.0 it looks awesome except it doesn't work for 3rd party plugins e.g when I try to install webpack-obfuscator with
`$ vue add webpack-obfuscator`

I get following error.

```
Installing vue-cli-plugin-webpack-obfuscator...

npm ERR! code E404
npm ERR! 404 Not Found: vue-cli-plugin-webpack-obfuscator@latest
```
I thought it might be this package doesn't exist in NPM but when I install with NPM install webpack-obfuscator it does install the plugin to node_modules.

Even though I installed it with NPM I am not able to invoke the plugin using vue.config.js. my config looks like
```

module.exports = {
  configureWebpack: {
    plugins: [
      new JavaScriptObfuscator(
        {
          rotateUnicodeArray: true,
          renameGlobals: true,
          stringArray: true,
          stringArrayEncoding: true,
          stringArrayThreshold: 0.5,
          target: "browser"
        },
        ["static/js/vendor**", "static/js/manifest**"]
      )
    ]
  }
};

```
I am struggling to install 3rd party plugins in VUE project. Please suggest how can I use 3rd party plugins. I had read documentation carefully but the provided guide lines doesn't work for me. I tried

```
vue add vue-container
vue add vue-i18n
```
with few others but none of them seems to work.

**Comment by erwin16** [comment]
Got the same issue ... but I guess you wil not get into it !

**Comment by Akryum** [comment]
Any npm package is not necessary a vue-cli plugin. `vue add` and `vue invoke` only work with vue-cli plugins.

**Comment by yyx990803** [comment]
**`vue add` is only for vue-cli plugins**. For webpack plugins you still install them with npm or yarn...

**Comment by erwin16** [comment]
this not the issue I guess, once installed w npm/yan , hos to add them into the webpack config...  ? 
module.exports = {
  configureWebpack: {
    plugins: [
      new JavaScriptObfuscator(

**Comment by riyasat** [comment]
@erwin16 You have to add
`var JavaScriptObfuscator = require('webpack-obfuscator');`
before you use
```
module.exports = {
configureWebpack: {
plugins: [
new JavaScriptObfuscator(
```
all plugins you installed with npm/yarn should work as expected.
