### ISSUE TITLE
Getting error trying to build library of components

### ISSUE THREAD

**Issue by jineshshah36** [vuejs/vue-cli#965]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/jineshshah36/vue-test-lib](https://github.com/jineshshah36/vue-test-lib)

### Steps to reproduce
clone repo, run yarn, run yarn run build. 

### What is expected?
Build should create a lib of components

### What is actually happening?
Build will fail

**Comment by LinusBorg** [comment]
Would it be possible to share the error in the issue description so we might get a first idea whats happening before we clone the reporduction repository (thanks for setting that up btw)?

**Comment by DanielPe05** [comment]
I think you are only missing the entry point of your components in your build script. Something like this: `vue-cli-service build --dest lib --target lib src/main.js`. This should give you a little more context: https://github.com/vuejs/vue-cli/blob/dev/docs/build-targets.md#library

**Comment by jineshshah36** [comment]
You are correct, but actually in the process, I have uncovered a new bug If you clone the repo and `yarn run build` you'll see that it does build but because I had a dash in the name, it spits out. It should probably camelcase the name?

```<title>joinarthur-components demo</title>
<script src="https://unpkg.com/vue"></script>
<script src="./joinarthur-components.umd.js"></script>
<link rel="stylesheet" href="./joinarthur-components.css">

<div id="app">
  <demo></demo>
</div>

<script>
new Vue({
  components: {
    demo: joinarthur-components
  }
}).$mount('#app')
</script>
```

**Comment by johnwebbcole** [comment]
I'm seeing this with a scoped package as well.  Is there a way to set the name in the umd.js besides project name?

**Comment by johnwebbcole** [comment]
I've created issue #1064 and a sample repo for the scoped library issue.  Maybe someone will be able to show me what I've done wrong :-)

**Comment by yyx990803** [comment]
Closing as the original repro seems no longer available.
