### ISSUE TITLE
vue-cli 3.0 怎么配置多页面

### ISSUE THREAD

**Issue by wss610** [vuejs/vue-cli#968]
vue-cli 3.0 怎么配置多页面?

**Comment by aaavieri** [comment]
我也在找这个多页面的配置方法，然而并没有找到，于是自己摸索出来了。只需要修改vue.config.js文件即可，修改后文件内容如下：
// vue.config.js
const HtmlWebpackPlugin = require('html-webpack-plugin')
var pageNames = ['custom', 'origin']
var entry = {}
var plugins = []
pageNames.map(pageName => {
  entry[pageName] = `./src/${pageName}.js` // js文件路径
  plugins.push(new HtmlWebpackPlugin({
    filename: pageName + '.html',
    template: `./public/${pageName}.html`, //模板路径
    inject: true,
    excludeChunks: pageNames.filter(item => item != pageName)
  }))
})

module.exports = {
  lintOnSave: true,
  configureWebpack: {
    entry,
    plugins
  },
  chainWebpack: config => {
    config.entry('app').clear().end()
  }
}
希望对你有所帮助

**Comment by yyx990803** [comment]
https://cli.vuejs.org/config/#pages

**Comment by giggo1604** [comment]
Should this work with historyApiFallback or am I doing something wrong?

**Comment by itxuye** [comment]
@giggo1604  Have you solved it ?

**Comment by giggo1604** [comment]
@itxuye Nope, currently working with an "vue project per site" setup (I only have two sites) and share common components via a symlinked local npm module. This is not very satisfying but i didn't have the time to further dig into vue-cli-3 and make it work...
