### ISSUE TITLE
Webpack 4.0 Support for better wasm intergration 

### ISSUE THREAD

**Issue by greenpdx** [vuejs/vue-cli#969]
### What problem does this feature solve?
I am "rust-native-wasm-loader" to build and load wasm created by "wasm-bindgen". This development system creates es6 interface for wasm.  With webpack 3, I have to play games with promises, async and yield , with webpack 4 it works out of the box.
Also webpack 4 is faster.

### What does the proposed API look like?
Webpack 4 makes it easier to to load wasm libraries and builds are faster.

**Comment by philwolstenholme** [comment]
@greenpdx have a look at https://github.com/vuejs/vue-cli/issues/836, specifically the final comment from Evan (yyx990803)

> Closing since the answer is yes - will open a separate tracking issue when we try to finalize it.

**Comment by yyx990803** [comment]
We already have a [WIP branch](https://github.com/vuejs/vue-cli/tree/webpack4) but at the moment webpack 4 still lacks updated documentation, and a few plugins we rely on from the ecosystem still have not been fully stabilized yet.

Our priority is to ship a stable, production ready setup as the default, so we want to make sure we only migrate when it is ready.

**Comment by rowild** [comment]
What is the status quo here? Any chance to provide a link with current info?
Thank you!

**Comment by Akryum** [comment]
We already migrated to Webpack 4 since [beta.10](https://github.com/vuejs/vue-cli/blob/dev/CHANGELOG.md#300-beta10-2018-05-11)

**Comment by rowild** [comment]
I just tested the Vue Cli 3 rc5 again, using the UI. Looks AMAZING! But what I cannot find is a hint anywhere on which webpack is used. Am I missing something? Shouldn't that be shown somewhere?
