### ISSUE TITLE
Vue init not respecting Airbnb style guide

### ISSUE THREAD

**Issue by amcsi** [vuejs/vue-cli#97]
When I do `vue init webpack my-project` and I tell the interactive installer that I want to use the Airbnb style guide, the generated js files still seem to be following `standard` instead of `airbnb`.

This is quite a problem I think, knowing that there's no simple tool for just converting those `standard` style files to `airbnb` style ones.

Is it planned to create different templates for different standards?

**Comment by chrisvfritz** [comment]
Hmm... my preference would be to just remove the Airbnb option. I don't have anything against that style, but it doesn't bring a clear benefit over standard and I certainly don't want to support it as a first-class citizen - which would mean maintaining two almost identical versions of the template.

**Comment by amcsi** [comment]
I myself do prefer the Airbnb style guide pretty much because of the fact that you do use semicolons there, but also because that style guide is a lot more popular and that it evolves all the time.

I do see the appeal of `standard` trying to be more set in stone though. I really think it would be reasonable to support those exact 2 style guides though.

**Comment by yyx990803** [comment]
I can't seem to reproduce this, the `src` code generated does follow AirBNB style for me. The build folder is not linted and you shouldn't really care what style it uses.

**Comment by amcsi** [comment]
I see that the component files are indeed following the AirBNB style, but are you sure about the build folder not being linted?

This is the `.eslintrc.js` file's contents:

```js
module.exports = {
  root: true,
  extends: 'airbnb/base',
  // required to lint *.vue files
  plugins: [
    'html'
  ],
  // add your custom rules here
  'rules': {
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0
  }
}
```

There doesn't seem to be any reference to the build folder (or the test folders for that matter) to being an exception to the rules, nor do I see any `.eslintrc` override files in those subdirectories

**Comment by chrisvfritz** [comment]
The correct folders are linted with `npm run dev` and `npm run lint`. My guess is you're also using a linter in your code editor to lint the entire project on-the-fly. I also do this and can imagine it being annoying when the entire project doesn't follow the same style rules. 

What would you think having an `.eslintignore` file added when not extending `standard`? Would that solve the problem in your editor?

**Comment by amcsi** [comment]
@chrisvfritz ah yes you're right, I forgot to mention that. Although since there was an `.eslintrc.js` file included in the files, I was assuming I was meant to use eslint anyway.

So yes either an `.eslintignore` file would be good, or _maybe_ have the build directory conditionally be standard? Although that might be completely pointless

Note also that there are some files in the test directories that also don't adjust to airbnb if chosen, although half of those files are just the hello-world test examples that are to be deleted anyway.

**Comment by chrisvfritz** [comment]
I think it'd be good to have a conditional `.eslintignore`. Much less work than maintaining a separate version of files in the `build` directory, which I think is fine considering people shouldn't be spending too much time in them.

I'll also update those test files, since they actually should be adhering to the same style as the `src` files.

**Comment by chrisvfritz** [comment]
Consolidating this into [https://github.com/vuejs-templates/webpack/issues/129](https://github.com/vuejs-templates/webpack/issues/129).
