### ISSUE TITLE
vue-cli: failed to init project 

### ISSUE THREAD

**Issue by Randysheng** [vuejs/vue-cli#971]
### Version
2.9.3

### Reproduction link
[https://github.com/fdeitelhoff/brickobotik.codes](https://github.com/fdeitelhoff/brickobotik.codes)

### Steps to reproduce
vue init webpack projectname

### What is expected?
success 

### What is actually happening?
/usr/local/lib/node_modules/vue-cli/node_modules/rimraf/rimraf.js:313
        throw er
        ^

Error: EACCES: permission denied, unlink '/Users/Randy/.vue-templates/webpack/.gitignore'

---
- mac:10.13.3
- node:v.9.0.4
- npm:5.7.1

when i used vue-cli to init my project, i got this error. I know i can use "sudo" to solve this problem. But, I never met this problem before. So, I want to know why this problem come this time? can you help me?

**Comment by yyx990803** [comment]
You **should** have access to your own home directory, so this means your home directory permission seems to be messed up somehow. You should `chown` your home directory. This is not something `vue-cli` can fix.
