### ISSUE TITLE
npm run build运行错误Error: "extract-text-webpack-plugin" loader is used without eht corresponding plugin

### ISSUE THREAD

**Issue by camoth** [vuejs/vue-cli#98]
使用Vue-cli 运行npm run dev没问题，打包的时候出现问题，附上我的package.json
麻烦尤大帮我看看，是在找不到解决办法了。
node -v 
v6.1.0

npm -v 
v3.8.6

![98d543e4-273e-4486-a7e9-22ad52780489](https://cloud.githubusercontent.com/assets/14108724/15279082/4eb0daac-1b53-11e6-8d5e-84c3a37e073d.jpg)

{
  "name": "joylife",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "camoth &lt;669762172@qq.com&gt;",
  "private": true,
  "scripts": {
    "dev": "node build/dev-server.js",
    "build": "node build/build.js",
    "test": "",
    "lint": "eslint --ext .js,.vue src test/unit/specs test/e2e/specs"
  },
  "dependencies": {
    "vue": "^1.0.21",
    "babel-runtime": "^6.0.0"
  },
  "devDependencies": {
    "babel-core": "^6.0.0",
    "babel-loader": "^6.0.0",
    "babel-plugin-transform-runtime": "^6.0.0",
    "babel-preset-es2015": "^6.0.0",
    "babel-preset-stage-2": "^6.0.0",
    "connect-history-api-fallback": "^1.1.0",
    "css-loader": "^0.23.0",
    "eslint": "^2.0.0",
    "eslint-config-standard": "^5.1.0",
    "eslint-friendly-formatter": "^1.2.2",
    "eslint-loader": "^1.3.0",
    "eslint-plugin-html": "^1.3.0",
    "eslint-plugin-promise": "^1.0.8",
    "eslint-plugin-standard": "^1.3.2",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.13.3",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.4",
    "function-bind": "^1.0.2",
    "html-webpack-plugin": "^2.8.1",
    "http-proxy-middleware": "^0.12.0",
    "json-loader": "^0.5.4",
    "lib-flexible": "^0.3.2",
    "normalize.css": "^4.1.1",
    "ora": "^0.2.0",
    "shelljs": "^0.6.0",
    "url-loader": "^0.5.7",
    "vue-hot-reload-api": "^1.2.0",
    "vue-html-loader": "^1.0.0",
    "vue-loader": "^8.3.0",
    "vue-resource": "^0.7.0",
    "vue-router": "^0.7.13",
    "vue-style-loader": "^1.0.0",
    "vuex": "^0.6.3",
    "webpack": "^1.12.2",
    "webpack-dev-middleware": "^1.4.0",
    "webpack-hot-middleware": "^2.6.0",
    "webpack-merge": "^0.8.3"
  }
}

**Comment by yangpei425** [comment]
how to sovle this problem?
