### ISSUE TITLE
Setting own npm registry (behind corporate proxy)

### ISSUE THREAD

**Issue by webia1** [vuejs/vue-cli#984]
Following situation:

```jsx
> vue -V
3.0.0-beta.6

> vue create myproject -r https://whatever.de/artifactory/api/npm/npm-remote/
 ERROR  RequestError: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443

> vue create myproject --registry https://whatever.de/artifactory/api/npm/npm-remote/
 ERROR  RequestError: Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
```
How can I set my own npm artifactory? We are behind a corporate proxy.

My current workaround was modifying the cli-source-code. Can someone help me? Many thanks!

that's the .npmrc, installation of other npm packages works properly

```
registry=https://whatever.de/artifactory/api/npm/npm-remote/
_auth="blabla..."
always-auth=true
email=its.me@example.com
proxy=http://proxy.whatever.de:8080
https-proxy=https://proxy.whatever.de:8080
no_proxy=https://whatever.de/artifactory/api/npm/npm-remote/
strict-ssl=false
```

**Comment by webia1** [comment]
I cannot Issue-Helper, because I'm behind a corporate proxy (api.github is forbidden) and I cannot set the CLI-Version. All the necessary information is given above.

```
api.github.com/repos/vuejs/vue-cli/releases?page=1&per_page=100 
Failed to load resource: the server responded with a status of 403 (Forbidden)
```

Thanks for feedbacks in advance,..

**Comment by webia1** [comment]
that's the problem (getVersions.js)

```jsx
    const registry = options.useTaobaoRegistry
      ? `https://registry.npm.taobao.org`
      : `https://registry.npmjs.org`
```
`https://registry.npmjs.org` is hardwired,..

**Comment by Akryum** [comment]
You can use the `hosts` file of your OS to 'redirect' to another URL.

**Comment by webia1** [comment]
corporate bots overwrite (reset) host files regularly,.. CLI should provide a configuration possibility, but thank you very much, would be great, if the next version offers that.

**Comment by webia1** [comment]
Current workaround:

1) Modifying `..\AppData(Roaming)\npm\node_modules\@vue\cli\lib\util\getVersions.js`

```jsx
    const registry = options.useTaobaoRegistry 
    ? `https://registry.npm.taobao.org` 
    : `https://myOwn/artifactory/api/npm/npm-remote/`;
```

2) Setting an environment variable to avoid self signed certificate errors (= setting up for a MitM attack) 

```jsx
NODE_TLS_REJECT_UNAUTHORIZED=0
```
