### ISSUE TITLE
Events attached twice on hot reload

### ISSUE THREAD

**Issue by rustunn** [vuejs/vue-cli#99]
I have simple project setup with webpack cli. And I attach event listeners on window to listen for key events in created callback and than remove them in destroyed callback. But when I do some changes in the project and save it, webpack reloads the page and all events getting registered twice now. 

I also did the same thing, but with socket.io this time, and all notifications also gettiing duplicated on webpack hot reload

**Comment by yyx990803** [comment]
Make sure you teardown these listeners in the `beforeDestroy` hook of your component.
