### ISSUE TITLE
Broke page styles when live changing it n Chrome DevTools with webpack template

### ISSUE THREAD

**Issue by marcinlesek** [vuejs/vue-cli#990]
### Version
3.0.0-beta.6

### Reproduction link
[https://github.com/vuejs-templates/webpack](https://github.com/vuejs-templates/webpack)

### Steps to reproduce
I have application bootstrapped from `vue-cli` with a `webpack` template. I'm running it on Chrome `65.0.3325.146` but it also exists on `64.X.XXX` version.

I'm adding here:
`package.json`: https://gist.github.com/marcinlesek/a7e6076ce4befe2e810743fdbaf81480

`webpack.base.conf.js`: https://gist.github.com/marcinlesek/80cbf27b6ef4172248709f32c257d0cd

### What is expected?
The application works fine with Chrome Browser.

### What is actually happening?
When I change style via Chrome `dev tools` it broke all styles (after changing or disabling one property) that page looks like in pure HTML without any line of style code. Fresh dev tools setup and Chrome reinstall doesn't help. What is a bit tricky, on Firefox `58.0.2` everything works correctly.

---
My collegues also had this problem, so it convince me that it isn't my local bug but something bigger on Vue side. Also find some questions regarding this bug, like https://stackoverflow.com/questions/48407862/page-styles-break-when-i-change-styles-in-chrome-devtools-with-webpack-hmr

Thanks in advance.

Best regards,
Marcin

**Comment by LinusBorg** [comment]
Well, if  that's a problem with the template, please open an issue in the template's repository.

**Comment by marcinlesek** [comment]
@LinusBorg Thanks for information, I will do this. ;)

**Comment by JFGHT** [comment]
@LinusBorg 

This is actually still happening with the current Vue & Vue Cli versions and sourceMap activated.

**Comment by LinusBorg** [comment]
Then the last sentence of my previous comment still applies.
