### ISSUE TITLE
vue serve not working, and not outputting anything

### ISSUE THREAD

**Issue by cfjedimaster** [vuejs/vue-cli#996]
### Version
2.9.3

### Reproduction link
[https://www.raymondcamden.com](https://www.raymondcamden.com)

### Steps to reproduce
Please forgive the invalid "Link to minimal reproduction". I do not understand why this is required for a CLI issue? It isn't code related.

I installed `@vue/cli-service-global` and trying to use "vue serve" returns nothing. No error, no output, just zip.

### What is expected?
That it would start up a development server.

### What is actually happening?
Nothing.

**Comment by cfjedimaster** [comment]
Ditto for OSX.

**Comment by LinusBorg** [comment]
> trying to use "vue serve" returns nothing. 

Trying how? If you can't provide a repository with runnable reproduction code, at least be more specific that 4 words, even if you are sure you followed the docs.

This is the reason we do ask for a reproduction by default - and while it would indeed be a bit overly complicated to produce a reproduction of an issue with vue-cli-service-global and a simply `vue serve App.vue`, it is useful even for most reports on the cli, just to be sure to have all the same dependencies and choices as the author of the issue.

**Comment by cfjedimaster** [comment]
But t that's all I did - I typed "vue serve". And hit enter of course. The CLI didn't error but didn't do anything else either. How would I create a reproduction of a CLI issue?

**Comment by cfjedimaster** [comment]
As an additional comment, I notice that the vue cli doesn't seem to do anything on a bad command. So for exampe, "vue foo" or "vue dkjlfdsjlkfsdlkjfsdkljsfdkljsflk" doesn't return an error, it just does nothing as well. I'm assuming that should be another bug report (or enhancement request)?

**Comment by LinusBorg** [comment]
Oh, I just realized you are running 2.9.3? Well, `vue serve` is a command of vue-cli 3.0. Where did you learn about this command if not in the 3.0 docs?

Additionally, even if you *were* running 3.0, you would *still* have to provide a file to serve:
````
vue serve App.vue
```

See: https://github.com/vuejs/vue-cli/blob/dev/docs/cli.md#vue-serve

>  it just does nothing as well. I'm assuming that should be another bug report (or enhancement request)?

Theoretically, yes. But I think we won't improve 2.* anymore in such ways, only fix major bugs.

**Comment by cfjedimaster** [comment]
Here - and I totally skipped over the installation part as I already have it installed, but I see the he documents needing 3. Sigh - sorry.

That being said, does 3.x handle unknown commands better?

**Comment by Akryum** [comment]
> That being said, does 3.x handle unknown commands better?

Yes.

**Comment by appsparkler** [comment]
You need to create a `main.js` or `index.js` or `app.vue` or `App.vue` for `vue serve` to work with `Vue Cli 3`...

Good Luck...

**Comment by appsparkler** [comment]
You need to create a `main.js` or `index.js` or `app.vue` or `App.vue` for `vue serve` to work with `Vue Cli 3`...


![image](https://user-images.githubusercontent.com/12084821/50571507-5d3bbc80-0dd2-11e9-8d5d-7989a2399aaf.png)

Good Luck...

**Comment by lucio-lu** [comment]
The package name changed from vue-cli to @vue/cli. If you have the previous vue-cli (1.x or 2.x) package installed globally, you need to uninstall it first with npm uninstall vue-cli -g or yarn global remove vue-cli.

**Comment by davleb** [comment]
Got the same problem and changed from vue-cli to @vue/cli as lucio-lu suggested. Problem solved.
You can use your vue file directly, ie, `vue serve mycomponent.vue` ...
