### ISSUE TITLE
vue-cli-service build --report

### ISSUE THREAD

**Issue by chrisvfritz** [vuejs/vue-cli#998]
### What problem does this feature solve?
There doesn't currently seem to be a way to generate a detailed build report, e.g. with webpack-bundle-analyzer. 

### What does the proposed API look like?
I think it'd be ideal if `vue-cli-service build --report` did that.

**Comment by chrisvfritz** [comment]
@Akryum I think this feature is still probably necessary for CI artifacts, but I also wonder if it might be something that could be built into the UI. 😻

**Comment by Akryum** [comment]
The plan for the first release of cli-ui is to have a custom view for `serve` and `build` with respectively the equivalent of webpack dashboard and webpack analyzer.

**Comment by pranavjindal999** [comment]
For the time being, we can customize webpack config in [`vue.config.js `](https://github.com/vuejs/vue-cli/blob/dev/docs/config.md) and use [ `webpack-bundle-analyzer`](https://github.com/webpack-contrib/webpack-bundle-analyzer)

Make following changes to your `vue.config.js` (make one parallel to `package.json` if not already there)

```javascript
// ...other requires here
const BundleAnalyzerPlugin = require("webpack-bundle-analyzer").BundleAnalyzerPlugin;

module.exports = {
   // ...your other settings here

  chainWebpack: config => {
      // ...your other webpack config overrides here

    if (process.env.NODE_ENV === "production")
        config.plugin("webpack-report")
            .use(BundleAnalyzerPlugin, {
                // ...webpack-bundle-analyzer options here
            });
  }
};
```


> [Options for webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer#options-for-plugin)

**Comment by manico** [comment]
@pranavjindal999 This gives `address in use`  on all ports. Probably bacause of webpack configuration that interferes somehow.

**Comment by pranavjindal999** [comment]
@manico you can use different port by configuring `options` of `webpack-bundle-analyzer`

``` javascript
.use(BundleAnalyzerPlugin, [{
      analyzerPort : 98989
}]);
```

or simply go for static file instead of server

``` javascript
.use(BundleAnalyzerPlugin, [{
      analyzerMode: 'static'
}]);
```

[Options for webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer#options-for-plugin)

**Comment by manico** [comment]
No, I tried different ports.
It seems that with mutating it does not work.
My build command is for lib:

`vue-cli-service build --target lib --name vizceral-vue src/index.js`

**Comment by pranavjindal999** [comment]
Try the `static` mode

**Comment by manico** [comment]
It works, but it runs three times which is problem for server mode too because it tries listen three times. :D

Anyone knows how to use `webpack-bundle-analyzer` in this case?
Repository: https://github.com/manico/vizceral-vue
Command: `npm run build`

**Comment by yyx990803** [comment]
Closed via 272ef5e2

**Comment by zzlw** [comment]
```
"build": "vue-cli-service build  --report"
```


``` 
✘ andy@andydeMacBook-Pro  ~/Desktop/lenovo_rubiks_cube   master ●  yarn build
yarn run v1.7.0
$ vue-cli-service build  --report

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
 configureWebpack: config => {
    if (process.env.NODE_ENV === 'production') {
       config.plugins= [
              new BundleAnalyzerPlugin()
        ]
    } else {

    }
  }
```

**Comment by rhymes** [comment]
@zzlw did you upgrade the packages :D ? Also, you have to comment out that `configureWebpack` with the bundle analyzer plugin.

I just tried it and it works
